In [1]:
%load_ext autoreload
%autoreload 2
# Supress default INFO logging  (Hide Info)

import logging
logger = logging.getLogger()
logger.setLevel(logging.CRITICAL)
#logging.root.hanlder = []
#logging.basicConfig(format="%(asctime)s : %(leveltime)s : %(message)s", message=logging.INFO)

In [2]:
import logging
import collections
logging.root.handlers = []  # Jupyter messes up logging so needs a reset
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
from smart_open import smart_open 
import pandas as pd
import numpy as np
from numpy import random
from collections import Counter
import heapq #check n largest
import json
import warnings
from sqlalchemy import create_engine 
import nltk
import spacy
import json
import seaborn as sns

In [3]:
def isEnglish(s):
    try:
        s.encode(encoding='utf-8').decode('ascii')
    except UnicodeDecodeError:
        return False
    else:
        return True

In [4]:
bath_path = r'C:/Users/asus/Downloads/ADB_final/'

computer_security_and_networks = json.load(open(bath_path + r'computer-security-and-networks.json', encoding='utf8'))
algorithms = json.load(open(bath_path + r'algorithms.json', encoding='utf8'))
cloud_computing = json.load(open(bath_path + r'cloud-computing.json', encoding='utf8'))
data_management = json.load(open(bath_path + r'data-management.json', encoding='utf8'))
design_and_product = json.load(open(bath_path + r'design-and-product.json', encoding='utf8'))
electrical_engineering = json.load(open(bath_path + r'electrical-engineering.json', encoding='utf8'))
math_and_logic = json.load(open(bath_path + r'math-and-logic.json', encoding='utf8'))
mobile_and_web_development = json.load(open(bath_path + r'mobile-and-web-development.json', encoding='utf8'))
networking = json.load(open(bath_path + r'networking.json', encoding='utf8'))
probability_and_statistics = json.load(open(bath_path + r'probability-and-statistics.json', encoding='utf8'))
security = json.load(open(bath_path + r'security.json', encoding='utf8'))
machine_learning = json.load(open(bath_path + r'machine-learning.json', encoding='utf8'))
data_analysis = json.load(open(bath_path + r'data-analysis.json', encoding='utf8'))
software_development = json.load(open(bath_path + r'software-development.json', encoding='utf8'))

all_data = computer_security_and_networks + \
algorithms + \
cloud_computing + \
data_management + \
design_and_product + \
electrical_engineering + \
math_and_logic + \
mobile_and_web_development + \
networking + \
probability_and_statistics + \
security + \
machine_learning + \
data_analysis + \
software_development

In [5]:
len(all_data)

881

In [6]:
def get_course(course):
    cat=[]; title=[]; week_data=[]; target_audience=[]; created_by=[]; teach_by=[]
    week_data_title=[]; course_info=[]; department=[]; week_data_desc=[]
    package_num=[];package_name=[]; level=[]; rating=[]; index=[]; uid=[]
    x = 0
    for (category) in course:
        for n in range(len(eval(category))):
            for i in range(len(eval(category)[n]['teach_by'])):
                    uid.append(x)
                    cat.append(category)
                    title.append(eval(category)[n]['title'])
                    target_audience.append(eval(category)[n]['target_audience'])
                    created_by.append(eval(category)[n]['created_by'])
                    course_info.append(eval(category)[n]['course_info'])
                    package_num.append(eval(category)[n]['package_num'])
                    package_name.append(eval(category)[n]['package_name'])
                    level.append(eval(category)[n]['level'])
                    rating.append(eval(category)[n]['rating']) 
                    index.append(n)
                    teach_by.append(list((eval(category)[n]['teach_by'][i].values()))[1])  
                    department.append(list((eval(category)[n]['teach_by'][i].values()))[0])
            x += 1
    data = pd.DataFrame({
                   'category': cat,
                   'uid': uid,
                    'title': title,
                    'target_audience': target_audience,
                    'created_by' : created_by,  
                    'course_info': course_info,
                    'teach_by': teach_by,
                     'department': department,
                     'level': level,
                     'rating': rating,
                     'package_num': package_num,
                     'package_name': package_name          
                    },
                    columns = ['uid','category', 'title',
                               'course_info', 'target_audience', 'created_by','teach_by',
                               'department','package_num','package_name', 'level','rating']) 
    return data

In [7]:
course_list_cat = ['computer_security_and_networks','algorithms','cloud_computing' ,'data_management' ,
               'design_and_product','electrical_engineering' ,'math_and_logic' ,'mobile_and_web_development' ,'networking',
              'probability_and_statistics','security','machine_learning' ,'data_analysis','software_development']

In [8]:
data = get_course(course_list_cat)

In [9]:
tmp = data.drop_duplicates(subset=['uid'])
tmp.reset_index(inplace=True)

In [10]:
for i, row in tmp.iterrows():
    data.loc[(data.course_info==row.course_info) & (data.title==row.title), 'uid'] = i

In [11]:
for i, row in data.iterrows():
    if not isEnglish(row.title):
        data.drop(i, inplace=True)

In [12]:
data.head()

,uid,category,title,course_info,target_audience,created_by,teach_by,department,package_num,package_name,level,rating
0,0,computer_security_and_networks,Bitcoin and Cryptocurrency Technologies,About this course: To really understand what i...,None,Princeton University,Arvind Narayanan,Computer Science,None,None,None,4.7
1,284,computer_security_and_networks,Cryptography I,About this course: Cryptography is an indispen...,None,Stanford University,Dan Boneh,Computer Science,None,None,None,4.8
2,157,computer_security_and_networks,Google Cloud Platform Fundamentals: Core Infra...,About this course: <<< ATTENTION >>> Learners ...,Who is this class for: This specialization is ...,Google Cloud,Google Cloud Training,None,1,Architecting with Google Cloud Platform Specia...,Intermediate,4.6
3,3,computer_security_and_networks,G Suite Administrator Fundamentals,About this course: G Suite Administrator Funda...,Who is this class for: This class is intended ...,Google Cloud,Google Cloud Training,None,None,None,Beginner,4.5
4,4,computer_security_and_networks,Usable Security,About this course: This course focuses on how ...,None,"University of Maryland, College Park",Jennifer Golbeck,Human-Computer Interaction Lab,1,Cybersecurity Specialization,None,4.5

In [13]:
len(data.uid.unique())

609

In [14]:
len(data.course_info.unique())

606

In [15]:
title=[]; created_by=[]; course_info=[]
data_title=[]; data_desc=[]; data_video=[]; course_info=[];
uid = []
# teach_by, week_data: 多值
for n in range(len(all_data)):
    week_data_title=[];  week_data_desc=[];week_data_video=[]
    title.append(all_data[n]['title'])
    created_by.append(all_data[n]['created_by'])
    course_info.append(all_data[n]['course_info'])
    uid.append(n)
    
    for i in range(len(all_data[n]['week_data'])):
        week_data_desc.append(all_data[n]['week_data'][i]['description'])
        week_data_title.append(all_data[n]['week_data'][i]['title'])
        week_data_video += all_data[n]['week_data'][i]['video']
    data_title.append(week_data_title)
    data_desc.append(week_data_desc)
    data_video.append(week_data_video)

In [16]:
data_created_by = pd.DataFrame({'title': title,
                    'created_by':created_by,
                    'uid':uid,
                    'course_info':course_info},
                    columns = ['title', 'created_by', 'uid', 'course_info'])

data_detail = pd.DataFrame({     
                    'week_data_desc': data_desc,
                    'week_data_title': data_title,
                    'week_data_video': data_video
                    },
                    columns = ['week_data_desc', 'week_data_title','week_data_video'])

In [17]:
for i, row in data_created_by.iterrows():
    if not isEnglish(row.title):
        data_created_by.drop(i, inplace=True)

In [18]:
for i, row in data_created_by.iterrows():
    data_created_by.loc[(data_created_by.course_info==row.course_info) & (data_created_by.title==row.title), 'uid'] = i

In [19]:
data_created_by.head()

,title,created_by,uid,course_info
0,Bitcoin and Cryptocurrency Technologies,Princeton University,0,About this course: To really understand what i...
1,Cryptography I,Stanford University,284,About this course: Cryptography is an indispen...
2,Google Cloud Platform Fundamentals: Core Infra...,Google Cloud,157,About this course: <<< ATTENTION >>> Learners ...
3,G Suite Administrator Fundamentals,Google Cloud,3,About this course: G Suite Administrator Funda...
4,Usable Security,"University of Maryland, College Park",4,About this course: This course focuses on how ...

In [20]:
data_created_by.drop_duplicates(subset=['title', 'created_by'], inplace=True)

In [21]:
data_detail = pd.merge(data_created_by, data_detail, left_index=True, right_index=True, how="left")

In [22]:
data_detail.head()

,title,created_by,uid,course_info,week_data_desc,week_data_title,week_data_video
0,Bitcoin and Cryptocurrency Technologies,Princeton University,0,About this course: To really understand what i...,"[Learn about cryptographic building blocks (""p...","[Introduction to Crypto and Cryptocurrencies, ...","[Welcome, Cryptographic Hash Functions, Hash P..."
1,Cryptography I,Stanford University,284,About this course: Cryptography is an indispen...,[Week 1. This week's topic is an overview of ...,"[Course overview and stream ciphers, Block Cip...","[Lecture slides for all six weeks, Course over..."
2,Google Cloud Platform Fundamentals: Core Infra...,Google Cloud,157,About this course: <<< ATTENTION >>> Learners ...,"[, , , , , , , , , , , , , , , ]",[Welcome to GCP Fundamentals: Core Infrastruct...,"[Welcome, Please read me, What is Google Cloud..."
3,G Suite Administrator Fundamentals,Google Cloud,3,About this course: G Suite Administrator Funda...,[You will be setting up your G Suite account a...,"[GETTING STARTED, USERS, SERVICES, SECURITY, D...","[Welcome and Getting Started Guide!, G Suite O..."
4,Usable Security,"University of Maryland, College Park",4,About this course: This course focuses on how ...,[Fundamentals of Human-Computer Interaction: u...,"[Week 1, Week 2, Week 3, Week 4, Week 5, Week ...","[Privacy Policy, Syllabus, Grading and Logisti..."

In [23]:
for i, row in data_detail.iterrows():
    if len(row.week_data_video) == 0:
        data_detail.drop(i, inplace=True)

In [24]:
data_detail = data_detail.reset_index(drop=True)

In [25]:
len(data_detail)

596

In [26]:
nlp = spacy.load(r'C:\Users\asus\AppData\Local\Programs\Python\Python35\Lib\site-packages\en_core_web_lg\en_core_web_lg-2.0.0')

In [27]:
week_video_list = []
for video_data in data_detail.week_data_video:
    video_str = ''
    x = ' '.join(video_data)
    doc = nlp(x.lower())
    for token in doc:
        if not token.is_stop and token.is_alpha:
            video_str += token.lemma_
            video_str += ' '
    week_video_list.append(video_str)

In [28]:
data_detail['week_data_video_str'] = pd.Series(week_video_list)
data_detail.dropna(inplace=True)
data_detail = data_detail.reset_index(drop=True)

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorize = TfidfVectorizer(max_df=150)
bows = vectorize.fit(data_detail.week_data_video_str)
document_matrix = bows.transform(data_detail.week_data_video_str).toarray()

In [30]:
document_matrix.shape

(596, 8805)

In [31]:
f = bows.get_feature_names()

In [32]:
from sklearn.metrics.pairwise import cosine_similarity
result = cosine_similarity(document_matrix)

In [33]:
data_detail.loc[np.argsort(result[20])[::-1], :]

,title,created_by,uid,course_info,week_data_desc,week_data_title,week_data_video,week_data_video_str
20,Introduction to Cybersecurity for Business,University of Colorado System,463,About this course: The world runs computers. ...,[Understand the basics of computer security fo...,"[What is Practical Computer Security, The CIA ...","[Welcome!, About the Instructor, Glossary of C...",welcome about the instructor glossary of compu...
13,Information Security: Context and Introduction,University of London,13,About this course: In this course you will exp...,"[, This module introduces cryptography, which ...","[Introduction to Information Security, Introdu...","[An overview, What are you hoping to achieve i...",an overview what be -PRON- hop to achieve in t...
6,Cybersecurity and Its Ten Domains,University System of Georgia,6,About this course: This course is designed to ...,[Checkout our marquee speaker. She's the Chief...,"[Welcome and Course Overview, Introduction to ...","[Welcome to ""Cybersecurity and Its Ten Domains...",welcome to cybersecurity and -PRON- ten domain...
408,Cyber Security in Manufacturing,"University at Buffalo, The State University of...",515,About this course: The nature of digital manuf...,[The purpose of this module is to introduce yo...,[Introduction to Digital Manufacturing Securit...,"[Course Introduction, Digital Manufacturing Se...",course introduction digital manufacture securi...
49,Enterprise and Infrastructure Security,New York University Tandon School of Engineering,50,About this course: This course introduces a se...,[This module includes an introduction to many ...,"[Security Awareness, Compliance, Assessments, ...",[Introduction: What You Will Learn from This C...,introduction what -PRON- will learn from this ...
588,Software Requirements Prioritization: Risk Ana...,University of Colorado System,845,"About this course: Risk Analysis, Assessment, ...",[Once requirements have been somewhat/mostly d...,"[Risk Analysis, Assessment and Prioritization,...","[Intro to Risk Analysis, Assessment, and Prior...",intro to risk analysis assessment and prioriti...
79,The Business of Cybersecurity Capstone,University System of Georgia,874,About this course: This course intends to make...,[This module provides a welcome to the course ...,[Welcome to the Management of Information Secu...,"[An overview of this course, Welcome to securi...",an overview of this course welcome to security...
1,Cryptography I,Stanford University,284,About this course: Cryptography is an indispen...,[Week 1. This week's topic is an overview of ...,"[Course overview and stream ciphers, Block Cip...","[Lecture slides for all six weeks, Course over...",lecture slide for all six week course overview...
33,Enterprise System Management and Security,University of Colorado System,464,About this course: The world runs on computers...,[Welcome and Introduction to Enterprise System...,[It's not that different from my home computer...,"[Welcome!, About this course, Resources for bu...",welcome about this course resource for build -...
38,Cyber Threats and Attack Vectors,University of Colorado System,465,About this course: Data breaches occur nearly ...,[Welcome! This week we'll explore users and us...,[THREATS AND ATTACK VECTORS IN COMPUTER SECURI...,"[Introduction, About this course, About the In...",introduction about this course about the instr...
27,Cryptography,"University of Maryland, College Park",28,About this course: This course will introduce ...,"[Introduction to Classical Cryptography, Comp...","[Week 1, Week 2, Week 3, Week 4, Week 5, Week ...","[Course Overview, Syllabus, Programming Assign...",course overview syllabus programming assignmen...
30,Cryptography and Information Theory,University of Colorado System,322,About this course: Welcome to Cryptography and...,[This module defines the technical terms in cr...,"[Cryptography Overview, Information Entropy, B...","[Instructor Introduction, Module Objectives, A...",instructor introduction module objective alice...
42,Cyber Attack Countermeasures,New York University Tandon School of Engineering,43,About this course: This course introduces the ...,[This module provides an introduction to secur...,"[ Cyber Security Safeguards, Understanding Aut...",[Introduction: What You Will Learn from This C...,introduction what -PRON- will learn from this ...
127,Algorithms for DNA Sequencing,Johns Hopkins University,640,About this course: We will learn computational...,[This module we begin our exploration of algor...,"[DNA sequencing, strings and matching, Preproc...","[Welcome to Algorithms for DNA Sequencing, Pre...",welcome to algorithm for dna sequencing pre co...
74,Cybersecurity and the X-Factor,University System of Georgia,75,About this course: What is the X-Factor? In Cy...,[The X-factor within information security is h...,"[Introduction to the X-Factor, Security Educat...","[Course Overview video, Learning Objectives, S...",course overview video learn objective security...
60,Asymmetric Cryptography and Key Management,University of Colorado System,344,About this course: Welcome to Asymmetric Crypt...,[This module reviews the principles and requir...,"[Asymmetric Cryptography Overview, RSA Algorit...","[Instructor Introduction, Module Objectives, W...",instructor introduction module objective what ...
61,Web Connectivity and Security in Embedded Systems,EIT Digital,62,About this course: Welcome to Web Connectivity...,[In this module you will learn about the layer...,"[Introduction to Web Connectivity & Security, ...","[Introduction, Introduction to CPS: Web Connec...",introduction introduction to cps web connectiv...
7,Introduction to Cyber Attacks,New York University Tandon School of Engineering,7,About this course: This course provides learne...,[This module provides exposure to basic cyber ...,"[Introduction to Cyber Security, Understanding...",[Introduction: What You Will Learn from This C...,introduction what -PRON- will learn from this ...
64,Cryptographic Hash and Integrity Protection,University of Colorado System,346,About this course: Welcome to Cryptographic Ha...,[Cryptographic hash function is a fundamental ...,"[Cryptographic Hash Function, Cryptographic Ha...","[Instructor Introduction, Module Objectives, H...",instructor introduction module objective hash ...
130,Approximation Algorithms Part I,École normale supérieure,137,"About this course: Approximation algorithms, P...",[We introduce the course topic by a typical ex...,"[Vertex cover and Linear Programming, Knapsack...","[Lecture: Introduction, Slides, Quiz 1: P vs. ...",lecture introduction slide quiz p np review al...
62,Proactive Computer Security,University of Colorado System,468,About this course: I’ve heard this before – “I...,[This module covers information sharing. Info...,"[Information Sharing and Threat Intelligence, ...","[Introduction, About this course, About the In...",introduction about this course about the instr...
23,Home Networking Basics,Cisco,424,About this course: Welcome to the fourth of fi...,"[In this module, you will compare different ty...","[Building a Home Network, Module 2: Connecting...","[About this Course, Cisco Packet Tracer, Conne...",about this course cisco packet tracer connect ...
48,Real-Time Cyber Threat Detection and Mitigation,New York University Tandon School of Engineering,49,About this course: This course introduces real...,[This module introduces the basics of TCP/IP f...,"[Basic Network Security, More Advanced Network...",[Introduction: What You Will Learn from This C...,introduction what -PRON- will learn from this ...
36,Classical Cryptosystems and Core Concepts,University of Colorado System,329,About this course: Welcome to Introduction to ...,[This module covers an introduction of the spe...,"[Specialization Introduction, Cryptographic Ti...","[About the Instructors, Course Introduction, A...",about the instructor course introduction about...
46,Windows Server Management and Security,University of Colorado System,466,About this course: Microsoft Windows has been ...,[In this module we'll discuss how Windows is u...,[Introduction to practical Windows system mana...,"[Welcome!, About This Course, Resources for bu...",welcome about this course resource for build -...
157,Introduction to the Internet of Things and Emb...,"University of California, Irvine",726,About this course: The explosive growth of the...,[The Internet of Things (IoT) is a popular buz...,"[What Is the Internet of Things (IoT)?, Embedd...","[Pre-Course Survey, Prof. Harris' Introduction...",pre course survey prof harris introduction cou...
22,Design and Analyze Secure Networked Systems,University of Colorado System,195,"About this course: In this MOOC, we will learn...","[In this module, we will introduce the basic c...",[Cybersecurity Concepts and Security Principle...,"[Course Overview, Lesson 1. Vulnerabilities a...",course overview lesson vulnerability and threa...
257,Introduction to Complex Analysis,Wesleyan University,305,About this course: This course provides an int...,[We’ll begin this module by briefly learning a...,"[Introduction to Complex Numbers, Complex Func...","[History of Complex Numbers, Lecture Slides, A...",history of complex number lecture slide algebr...
285,Dynamical Modeling Methods for Systems Biology,Icahn School of Medicine at Mount Sinai,347,About this course: An introduction to dynamica...,"[The description goes here, The description go...","[Introduction | Computing with MATLAB, Introdu...","[Syllabus, Supplemental Files, Lecture 1 - Int...",syllabus supplemental file lecture introductio...
67,"Planning, Auditing and Maintaining Enterprise ...",University of Colorado System,469,About this course: Good system management not ...,[This module covers the essentials of what you...,"[Critical first steps in System Management, Pl...","[Introduction, About this course, Resources fo...",introduction about this course resource for bu...
...,...,...,...,...,...,...,...,...
239,Capstone Design Project in Power Electronics,University of Colorado Boulder,277,About this course: Learners will design a DC-D...,[Select a converter circuit approach for the b...,"[Introduction and Power Stage Design, Power St...","[Introduction and Specifications, Introduction...",introduction and specification introduction sp...
331,App Design and Development for iOS,University of Toronto,409,About this course: In App Design and Developme...,"[Get oriented to the course., In this module y...",[Welcome to App Design and Development for iOS...,"[Welcome to the Course, Demo Project File, Scr...",welcome to the course demo project file scroll...
338,iOS Project: Transreality Game,"University of California, Irvine",417,About this course: Students will produce a net...,[In this module we go through the project that...,"[The Project and the Plan, Basic Scaffold Impl...","[Project Description, Capstone Grading, Welcom...",project description capstone grading welcome p...
143,The Fundamentals of Computing Capstone Exam,Rice University,871,About this course: While most specializations ...,[Complete a 25 question exam to demonstrate yo...,[Fundamentals of Computing Capstone Exam],"[Class Overview, Exam Preparation, Frequently ...",class overview exam preparation frequently ask...
569,Parallel programming,École Polytechnique Fédérale de Lausanne,764,About this course: With every smartphone and c...,[We motivate parallel programming and introduc...,"[Parallel Programming, Basic Task Parallel Alg...","[Course Overview, Introduction to Parallel Com...",course overview introduction to parallel compu...
259,Mathematical Biostatistics Boot Camp 1,Johns Hopkins University,309,About this course: This class presents the fun...,[You are about to undergo an intense and deman...,"[Introduction, Probability, Expectations, and ...","[Welcome to the Course, Syllabus, Faculty, Bio...",welcome to the course syllabus faculty biostat...
410,Recommender Systems Capstone,University of Minnesota,518,About this course: This capstone project cours...,[],[Capstone Project],"[Capstone Course: Introduction, Capstone Assig...",capstone course introduction capstone assignme...
552,"C++ For C Programmers, Part A","University of California, Santa Cruz",715,About this course: This course is for experien...,[How to convert an existing C program to C++. ...,"[Module 1, Module 2, Module 3, Module 4, Final...","[1.0 Module 1 Overview, 1.1 Overview and Cours...",module overview overview and course organizati...
373,Structuring Machine Learning Projects,deeplearning.ai,520,About this course: You will learn how to build...,"[, ]","[ML Strategy (1), ML Strategy (2)]","[Why ML Strategy, Orthogonalization, Single nu...",why ml strategy orthogonalization single numbe...
287,Robotics: Capstone,University of Pennsylvania,358,About this course: In our 6 week Robotics Caps...,[Welcome to Robotics Capstone! This week you w...,"[Week 1, Week 2, Week 3, Week 4, Week 5, Week 6]",[Capstone Introduction and Choosing the Capsto...,capstone introduction and choose the capstone ...
384,Deep Learning for Business,Yonsei University,488,"About this course: Your smartphone, smartwatch...","[For the course “Deep Learning for Business,” ...","[Deep Learning Products & Services , Business ...",[0.0 Introduction to Deep Learning for Busines...,introduction to deep learning for business fut...
78,Cloud Computing Project,University of Illinois at Urbana-Champaign,79,About this course: Note: You should complete a...,"[In this module, you will become familiar with...","[Orientation, Week 1 - Task Overview, Week 2, ...","[Welcome to the Cloud Computing Project!, Orie...",welcome to the cloud computing project orienta...
334,Interfaz de usuario en iOS,Tecnológico de Monterrey,864,About this course: En este curso podrás crear ...,"[La interfaz gráfica, una pieza fundamental en...","[Introducción y bienvenida, La interfaz gráfic...","[Bienvenidos al curso, La experiencia gráfica,...",bienvenidos al curso la experiencia gráfica pl...
205,System Validation (2): Model process behaviour,EIT Digital,857,About this course: System Validation is the fi...,"[, , ]","[Sequential behaviour, Data types, Parallel be...","[Introduction MOOC model process behaviour, Ac...",introduction mooc model process behaviour acti...
206,System Validation (3): Requirements by modal f...,EIT Digital,860,About this course: System Validation is the fi...,[In this module you learn how to specify requi...,"[Basic modal formulas, Advanced modal formulas]",[Introduction MOOC requirements by modal formu...,introduction mooc requirement by modal formula...
207,UI Design Capstone,University of Minnesota,868,About this course: This Capstone Course for th...,"[, , , , , , , ]","[Preface, User research and ideation I, User r...","[Welcome to UI Design Capstone Project, Projec...",welcome to ui design capstone project project ...
274,Valuing Companies,University of Michigan,330,About this course: This course is a theoretica...,[This module contains detailed videos and syll...,"[Overview of Specialization & Course, Module 1...","[Specialization: An Overview , Specialization:...",specialization an overview specialization a co...
483,Understanding Your Data: Analytical Tools,University of Virginia,624,About this course: Are you trying to understan...,[Welcome to the first week of our research met...,"[Mediation and Moderation, Conditional Indirec...","[Course Overview, Course Overview and Requirem...",course overview course overview and requiremen...
496,Data Analysis Tools,Wesleyan University,637,"About this course: In this course, you will de...",[This session starts where the Data Management...,"[Hypothesis Testing and ANOVA, Chi Square Test...",[Lesson 1 - The role of probability in inferen...,lesson the role of probability in inference le...
232,Magnetics for Power Electronic Converters,University of Colorado Boulder,269,About this course: This course covers the anal...,[This module introduces the physical principle...,"[Introduction to Magnetics and Inductors, Tran...","[Introduction to Magnetics, Inductance, Reluct...",introduction to magnetic inductance reluctance...
366,Statistics for Genomic Data Science,Johns Hopkins University,455,About this course: An introduction to the stat...,[This course is structured to hit the key conc...,"[Module 1, Module 2, Module 3, Module 4]",[Welcome to Statistics for Genomic Data Scienc...,welcome to statistic for genomic datum science...
508,Bioconductor for Genomic Data Science,Johns Hopkins University,655,About this course: Learn to use tools from the...,[The class will cover how to install and use B...,"[Week One, Week Two, Week Three, Week Four]","[Welcome, Syllabus, Pre Course Survey, Install...",welcome syllabus pre course survey instal r on...
98,Big Data Analysis with Scala and Spark,École Polytechnique Fédérale de Lausanne,100,About this course: Manipulating big data distr...,[Get up and running with Scala on your compute...,"[Getting Started + Spark Basics, Reduction Ope...","[Tools setup, Eclipse tutorial, Intellij IDEA ...",tool setup eclipse tutorial intellij idea tuto...
267,Fibonacci Numbers and the Golden Ratio,The Hong Kong University of Science and Techno...,319,About this course: This is a course about the ...,"[By the end of this week, you will be able to:...","[Dip your toes in the water, Dive deeper, Swim...","[Course Overview, Assignments and Grading, Pre...",course overview assignment and grade pre cours...
223,Wireless Communications for Everybody,Yonsei University,258,About this course: This course will provide an...,"[In this part of the course, we will learn the...",[Introduction and History of Cellular Communic...,"[1.1 Cellular Communication, Services in Cellu...",cellular communication service in cellular sys...
531,Data Mining Project,University of Illinois at Urbana-Champaign,872,About this course: Note: You should complete a...,"[In this module, you will become familiar with...","[Orientation, Task 1 - Exploration of a Data S...","[Welcome to the Data Mining Project!, Orientat...",welcome to the data mining project orientation...
540,Data Analysis and Interpretation Capstone,Wesleyan University,692,About this course: The Capstone project will a...,"[In this Module, your goal is to review the le...",[Module 1. Identify Your Data and Research Que...,"[Read Me First, Introduction to the Capstone C...",read -PRON- first introduction to the capstone...
32,Getting Started with Google Kubernetes Engine,Google Cloud,162,About this course: >>> By enrolling in this co...,"[Welcome to the course., Acquaint yourself wit...",[Welcome to Getting Started with Google Kubern...,"[Welcome to the Course, Course Overview, What ...",welcome to the course course overview what be ...
542,Mastering Software Development in R Capstone,Johns Hopkins University,876,About this course: R Programming Capstone,[The overall goal of the capstone project is t...,"[Obtain and Clean the Data, Building Geoms, Bu...","[Welcome to the Capstone Project, Introduction...",welcome to the capstone project introduction m...
336,"Capstone MOOC for ""Android App Development""",Vanderbilt University,870,About this course: The Capstone project integr...,[This module provides an introduction to the c...,"[Capstone Overview, Week 2 Milestone, Week 3 M...","[Overview of the Capstone Project, Summary of ...",overview of the capstone project summary of th...

In [34]:
## build title & Top-5 relation   (use this to build similatyty)

def get_nth_relation(index, n_th):
    return data_detail.loc[np.argsort(result[index])[::-1][n_th], :]['uid']

title_relation_df = pd.DataFrame(data_detail[['title', 'uid']])
title_relation_df['index'] = list(range(len(data_detail)))

top_n = 5
for i in range(1, top_n+1):
    str_i = str(i)
    title_relation_df['relate_'+str_i] = title_relation_df['index'].apply(lambda x: get_nth_relation(x, i))

title_relation_df.drop('index', axis=1, inplace=True)
title_relation_df.head()

,title,uid,relate_1,relate_2,relate_3,relate_4,relate_5
0,Bitcoin and Cryptocurrency Technologies,0,852,346,596,294,707
1,Cryptography I,284,28,340,822,344,463
2,Google Cloud Platform Fundamentals: Core Infra...,157,840,867,161,159,829
3,G Suite Administrator Fundamentals,3,250,733,436,365,706
4,Usable Security,4,654,858,743,60,70

In [35]:
## data_more for more word  (need data, data_detail)
data_more = pd.merge(data, data_detail, left_on='uid', right_on='uid', how="left")

## lower check, in 'data_more'
print ('lower check:')
check_list = ['C++', 'python', 'Java', 'HTML', 'Javascript', 'PHP', ' R ', ' C ', 'perl', 'spark', 'hadoop',
              'Swift', 'Android', 'Ruby', 'programming language']

for check_ele in check_list:
    check_times = 0
    check_ele = check_ele.lower()
    for all_info in data_more.values:
        info = ' '
        for all_info_ele in all_info:
            info = info + ' ' + str(all_info_ele)
        if check_ele in info.lower():
            check_times += 1
    print ('check_ele: "{}", check_times: {}'.format(check_ele, check_times))
##  data_language_df:  use it to build language relation

def check_function(uid, check_ele):
    data_target = data_more[data_more['uid']==uid]
    for all_info in data_target.values:
        info = ' '
        for all_info_ele in all_info:
            info = info + ' ' + str(all_info_ele)
        if check_ele in info.lower():
            return True
        else:
            return False

check_list = ['C++', 'python', 'Java', 'HTML', 'Javascript', 'PHP', ' R ', ' C ', 
              'perl', 'spark', 'hadoop', 'Swift', 'Android', 'Ruby', 'programming language']

data_language_df = pd.DataFrame(data_more['uid'])
for check_ele in check_list:
    check_ele = check_ele.lower()
    data_language_df[check_ele] = data_language_df['uid'].apply(lambda x: check_function(x, check_ele))
check_list.insert(0, 'uid')
data_language_df.columns = check_list
data_language_df.head()

lower check:
check_ele: "c++", check_times: 36
check_ele: "python", check_times: 272
check_ele: "java", check_times: 183
check_ele: "html", check_times: 84
check_ele: "javascript", check_times: 79
check_ele: "php", check_times: 14
check_ele: " r ", check_times: 153
check_ele: " c ", check_times: 48
check_ele: "perl", check_times: 25
check_ele: "spark", check_times: 68
check_ele: "hadoop", check_times: 59
check_ele: "swift", check_times: 19
check_ele: "android", check_times: 66
check_ele: "ruby", check_times: 22
check_ele: "programming language", check_times: 189

,uid,C++,python,Java,HTML,Javascript,PHP,R,C,perl,spark,hadoop,Swift,Android,Ruby,programming language
0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,284,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,157,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [36]:
data_clear = data.drop_duplicates(subset = ['uid'])

In [53]:
from py2neo import Graph
from py2neo import Relationship
from py2neo import Node

graph = Graph()
graph.delete_all()

2018-01-01 21:38:18,107 : INFO : > Sending batch request with 2 jobs
2018-01-01 21:38:18,107 : INFO : > {0} POST cypher {"query":"MATCH ()-[r]->()\nDELETE r"}
2018-01-01 21:38:18,111 : INFO : > {1} POST cypher {"query":"MATCH (n)\nDELETE n"}
2018-01-01 21:38:18,115 : INFO : > POST http://localhost:7474/db/data/batch [164]
2018-01-01 21:38:18,115 : INFO : ~ Reconnecting (peer closed connection)
2018-01-01 21:38:19,127 : INFO : > POST http://localhost:7474/db/data/batch [164]
2018-01-01 21:38:19,304 : INFO : < 200 OK [141]
2018-01-01 21:38:19,306 : INFO : < Received batch response for 2 jobs
2018-01-01 21:38:19,308 : INFO : < Discarding batch response

In [54]:
cat_dict = {}
for category in course_list_cat:
    cat_dict[category] = Node("Category", name=category)
    graph.create(cat_dict[category])

2018-01-01 21:38:19,500 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'computer_security_and_networks'}}
2018-01-01 21:38:19,500 : INFO : > POST http://localhost:7474/db/data/cypher [106]
2018-01-01 21:38:19,508 : INFO : < 200 OK [1406]
2018-01-01 21:38:19,512 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'algorithms'}}
2018-01-01 21:38:19,512 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:19,520 : INFO : < 200 OK [1386]
2018-01-01 21:38:19,520 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'cloud_computing'}}
2018-01-01 21:38:19,520 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:19,524 : INFO : < 200 OK [1391]
2018-01-01 21:38:19,528 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'data_management'}}
2018-01-01 21:38:19,528 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:19,536 : INFO : < 200 OK [1391]
2018-01-01 21:38:19,536 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'design_and_product'}}
2018-01-01 21:38:19,540 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:19,544 : INFO : < 200 OK [1394]
2018-01-01 21:38:19,548 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'electrical_engineering'}}
2018-01-01 21:38:19,548 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:19,556 : INFO : < 200 OK [1398]
2018-01-01 21:38:19,556 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'math_and_logic'}}
2018-01-01 21:38:19,560 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:19,564 : INFO : < 200 OK [1390]
2018-01-01 21:38:19,568 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'mobile_and_web_development'}}
2018-01-01 21:38:19,568 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2018-01-01 21:38:19,572 : INFO : < 200 OK [1402]
2018-01-01 21:38:19,576 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'networking'}}
2018-01-01 21:38:19,576 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:19,583 : INFO : < 200 OK [1386]
2018-01-01 21:38:19,586 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'probability_and_statistics'}}
2018-01-01 21:38:19,588 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2018-01-01 21:38:19,593 : INFO : < 200 OK [1402]
2018-01-01 21:38:19,595 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'security'}}
2018-01-01 21:38:19,596 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:19,600 : INFO : < 200 OK [1384]
2018-01-01 21:38:19,600 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'machine_learning'}}
2018-01-01 21:38:19,604 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:19,608 : INFO : < 200 OK [1392]
2018-01-01 21:38:19,608 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'data_analysis'}}
2018-01-01 21:38:19,612 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:19,616 : INFO : < 200 OK [1389]
2018-01-01 21:38:19,616 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'software_development'}}
2018-01-01 21:38:19,620 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:19,624 : INFO : < 200 OK [1396]

In [55]:
course_dict = {}
for i, row in data_clear.iterrows():
    course_dict[row.uid] = Node("Course", name=row.title, rating=row.rating, level=row.level, id=row.uid)
    graph.create(course_dict[row.uid])

2018-01-01 21:38:19,812 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 0, 'rating': '4.7', 'name': 'Bitcoin and Cryptocurrency Technologies'}}
2018-01-01 21:38:19,812 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2018-01-01 21:38:19,820 : INFO : < 200 OK [1455]
2018-01-01 21:38:19,824 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 284, 'rating': '4.8', 'name': 'Cryptography I'}}
2018-01-01 21:38:19,824 : INFO : > POST http://localhost:7474/db/data/cypher [112]
2018-01-01 21:38:19,828 : INFO : < 200 OK [1432]
2018-01-01 21:38:19,832 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 157, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Google Cloud Platform Fundamentals: Core Infrastructure'}}
2018-01-01 21:38:19,832 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:19,836 : INFO : < 200 OK [1506]
2018-01-01 21:38:19,840 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 3, 'rating': '4.5', 'level': 'Beginner', 'name': 'G Suite Administrator Fundamentals'}}
2018-01-01 21:38:19,840 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:19,844 : INFO : < 200 OK [1479]
2018-01-01 21:38:19,848 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 4, 'rating': '4.5', 'name': 'Usable Security'}}
2018-01-01 21:38:19,848 : INFO : > POST http://localhost:7474/db/data/cypher [111]
2018-01-01 21:38:19,852 : INFO : < 200 OK [1431]
2018-01-01 21:38:19,856 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 422, 'rating': '4.7', 'level': 'Beginner', 'name': 'Internet Connection: How to Get Online?'}}
2018-01-01 21:38:19,856 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2018-01-01 21:38:19,864 : INFO : < 200 OK [1486]
2018-01-01 21:38:19,864 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 6, 'rating': '4.1', 'level': 'Beginner', 'name': 'Cybersecurity and Its Ten Domains'}}
2018-01-01 21:38:19,864 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:19,868 : INFO : < 200 OK [1478]
2018-01-01 21:38:19,872 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 7, 'rating': '4.5', 'level': 'Beginner', 'name': 'Introduction to Cyber Attacks'}}
2018-01-01 21:38:19,872 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:19,876 : INFO : < 200 OK [1474]
2018-01-01 21:38:19,880 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 246, 'rating': '4.4', 'level': 'Beginner', 'name': 'Introduction to TCP/IP'}}
2018-01-01 21:38:19,882 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:19,886 : INFO : < 200 OK [1469]
2018-01-01 21:38:19,889 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 158, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Essential Cloud Infrastructure: Foundation'}}
2018-01-01 21:38:19,890 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2018-01-01 21:38:19,895 : INFO : < 200 OK [1493]
2018-01-01 21:38:19,896 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 10, 'rating': '4.6', 'name': 'Software Security '}}
2018-01-01 21:38:19,896 : INFO : > POST http://localhost:7474/db/data/cypher [115]
2018-01-01 21:38:19,904 : INFO : < 200 OK [1435]
2018-01-01 21:38:19,904 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 159, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Essential Cloud Infrastructure: Core Services'}}
2018-01-01 21:38:19,908 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2018-01-01 21:38:19,912 : INFO : < 200 OK [1496]
2018-01-01 21:38:19,916 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 186, 'level': 'Intermediate', 'name': 'Hacking and Patching'}}
2018-01-01 21:38:19,916 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2018-01-01 21:38:19,924 : INFO : < 200 OK [1446]
2018-01-01 21:38:19,928 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 13, 'rating': '4.5', 'level': 'Beginner', 'name': 'Information Security: Context and Introduction'}}
2018-01-01 21:38:19,928 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2018-01-01 21:38:19,932 : INFO : < 200 OK [1492]
2018-01-01 21:38:19,936 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 160, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Elastic Cloud Infrastructure: Scaling and Automation'}}
2018-01-01 21:38:19,940 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:38:19,944 : INFO : < 200 OK [1503]
2018-01-01 21:38:19,948 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 423, 'rating': '4.9', 'level': 'Beginner', 'name': 'Network Protocols and Architecture'}}
2018-01-01 21:38:19,948 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2018-01-01 21:38:19,952 : INFO : < 200 OK [1481]
2018-01-01 21:38:19,956 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 161, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Elastic Cloud Infrastructure: Containers and Services'}}
2018-01-01 21:38:19,960 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:38:19,964 : INFO : < 200 OK [1504]
2018-01-01 21:38:19,968 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 17, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Fundamentals of Network Communication'}}
2018-01-01 21:38:19,968 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2018-01-01 21:38:19,976 : INFO : < 200 OK [1487]
2018-01-01 21:38:19,976 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 462, 'rating': '4.0', 'level': 'Intermediate', 'name': 'Linux Server Management and Security'}}
2018-01-01 21:38:19,981 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2018-01-01 21:38:19,986 : INFO : < 200 OK [1487]
2018-01-01 21:38:19,989 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 769, 'rating': '3.9', 'level': 'Intermediate', 'name': 'Cloud Computing Applications, Part 1: Cloud Systems and Infrastructure'}}
2018-01-01 21:38:19,991 : INFO : > POST http://localhost:7474/db/data/cypher [191]
2018-01-01 21:38:19,995 : INFO : < 200 OK [1521]
2018-01-01 21:38:19,995 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 773, 'name': 'Software Defined Networking'}}
2018-01-01 21:38:20,000 : INFO : > POST http://localhost:7474/db/data/cypher [110]
2018-01-01 21:38:20,004 : INFO : < 200 OK [1420]
2018-01-01 21:38:20,008 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 463, 'rating': '4.7', 'level': 'Beginner', 'name': 'Introduction to Cybersecurity for Business'}}
2018-01-01 21:38:20,008 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2018-01-01 21:38:20,012 : INFO : < 200 OK [1489]
2018-01-01 21:38:20,016 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 782, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Serverless Data Analysis with Google BigQuery and Cloud Dataflow'}}
2018-01-01 21:38:20,020 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:38:20,028 : INFO : < 200 OK [1515]
2018-01-01 21:38:20,032 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 195, 'rating': '3.8', 'level': 'Intermediate', 'name': 'Design and Analyze Secure Networked Systems'}}
2018-01-01 21:38:20,036 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2018-01-01 21:38:20,044 : INFO : < 200 OK [1494]
2018-01-01 21:38:20,048 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 424, 'rating': '4.8', 'level': 'Beginner', 'name': 'Home Networking Basics'}}
2018-01-01 21:38:20,048 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:20,056 : INFO : < 200 OK [1469]
2018-01-01 21:38:20,060 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 254, 'rating': '4.5', 'name': 'Interfacing with the Raspberry Pi'}}
2018-01-01 21:38:20,064 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2018-01-01 21:38:20,072 : INFO : < 200 OK [1451]

2018-01-01 21:38:20,072 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 26, 'rating': '4.7', 'name': 'Internet History, Technology, and Security'}}
2018-01-01 21:38:20,076 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:20,087 : INFO : < 200 OK [1417]
2018-01-01 21:38:20,091 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 425, 'rating': '4.8', 'level': 'Beginner', 'name': 'Introduction to Cisco Networking'}}
2018-01-01 21:38:20,094 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:20,103 : INFO : < 200 OK [1479]
2018-01-01 21:38:20,106 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 28, 'rating': '4.5', 'name': 'Cryptography'}}
2018-01-01 21:38:20,111 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2018-01-01 21:38:20,130 : INFO : < 200 OK [1387]
2018-01-01 21:38:20,134 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 426, 'rating': '4.9', 'level': 'Beginner', 'name': 'Data Communications and Network Services'}}
2018-01-01 21:38:20,136 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2018-01-01 21:38:20,142 : INFO : < 200 OK [1487]
2018-01-01 21:38:20,146 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 30, 'rating': '4.0', 'name': 'Cloud Computing Applications, Part 2: Big Data and Applications in the Cloud'}}
2018-01-01 21:38:20,148 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:38:20,154 : INFO : < 200 OK [1451]
2018-01-01 21:38:20,156 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 322, 'rating': '4.0', 'level': 'Intermediate', 'name': 'Cryptography and Information Theory'}}
2018-01-01 21:38:20,158 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2018-01-01 21:38:20,163 : INFO : < 200 OK [1458]
2018-01-01 21:38:20,167 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 32, 'rating': '4.1', 'name': 'Big Data, Cloud Computing, & CDN Emerging Technologies'}}
2018-01-01 21:38:20,168 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2018-01-01 21:38:20,173 : INFO : < 200 OK [1429]
2018-01-01 21:38:20,176 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 162, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Getting Started with Google Kubernetes Engine'}}
2018-01-01 21:38:20,178 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2018-01-01 21:38:20,183 : INFO : < 200 OK [1468]
2018-01-01 21:38:20,186 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 464, 'rating': '4.7', 'level': 'Beginner', 'name': 'Enterprise System Management and Security '}}
2018-01-01 21:38:20,186 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2018-01-01 21:38:20,190 : INFO : < 200 OK [1447]
2018-01-01 21:38:20,190 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 35, 'rating': '4.5', 'name': 'Cloud Networking'}}
2018-01-01 21:38:20,194 : INFO : > POST http://localhost:7474/db/data/cypher [113]
2018-01-01 21:38:20,198 : INFO : < 200 OK [1405]
2018-01-01 21:38:20,198 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 163, 'rating': '5.0', 'level': 'Intermediate', 'name': 'Reliable Cloud Infrastructure: Design and Process'}}
2018-01-01 21:38:20,202 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2018-01-01 21:38:20,206 : INFO : < 200 OK [1458]
2018-01-01 21:38:20,210 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 329, 'rating': '4.8', 'level': 'Beginner', 'name': 'Classical Cryptosystems and Core Concepts'}}
2018-01-01 21:38:20,210 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:20,218 : INFO : < 200 OK [1446]
2018-01-01 21:38:20,222 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 38, 'rating': '4.0', 'name': 'Hardware Security'}}
2018-01-01 21:38:20,222 : INFO : > POST http://localhost:7474/db/data/cypher [114]
2018-01-01 21:38:20,226 : INFO : < 200 OK [1406]
2018-01-01 21:38:20,230 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 465, 'rating': '4.6', 'level': 'Beginner', 'name': 'Cyber Threats and Attack Vectors'}}
2018-01-01 21:38:20,234 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:20,238 : INFO : < 200 OK [1451]
2018-01-01 21:38:20,242 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 262, 'rating': '4.3', 'name': 'Wireless Communication Emerging Technologies'}}
2018-01-01 21:38:20,246 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:20,250 : INFO : < 200 OK [1420]
2018-01-01 21:38:20,254 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 41, 'rating': '4.3', 'name': 'TCP/IP and Advanced Topics'}}
2018-01-01 21:38:20,254 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2018-01-01 21:38:20,258 : INFO : < 200 OK [1415]
2018-01-01 21:38:20,262 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 817, 'rating': '4.2', 'level': 'Intermediate', 'name': 'Architecting Smart IoT Devices'}}
2018-01-01 21:38:20,266 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2018-01-01 21:38:20,272 : INFO : < 200 OK [1439]
2018-01-01 21:38:20,275 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 43, 'rating': '5.0', 'level': 'Intermediate', 'name': 'Cyber Attack Countermeasures'}}
2018-01-01 21:38:20,277 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:20,282 : INFO : < 200 OK [1450]
2018-01-01 21:38:20,284 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 44, 'rating': '4.4', 'name': 'International Cyber Conflicts'}}
2018-01-01 21:38:20,286 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2018-01-01 21:38:20,290 : INFO : < 200 OK [1404]
2018-01-01 21:38:20,290 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 822, 'level': 'Intermediate', 'name': 'Basic Cryptography and Programming with Crypto API'}}
2018-01-01 21:38:20,294 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2018-01-01 21:38:20,298 : INFO : < 200 OK [1448]
2018-01-01 21:38:20,302 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 140, 'rating': '4.7', 'level': 'Beginner', 'name': 'Mathematical Foundations for Cryptography'}}
2018-01-01 21:38:20,302 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:20,310 : INFO : < 200 OK [1460]
2018-01-01 21:38:20,314 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 466, 'level': 'Beginner', 'name': 'Windows Server Management and Security'}}
2018-01-01 21:38:20,314 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2018-01-01 21:38:20,318 : INFO : < 200 OK [1432]
2018-01-01 21:38:20,322 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 48, 'rating': '4.3', 'level': 'Intermediate', 'name': 'Cybersecurity and the Internet of Things'}}
2018-01-01 21:38:20,322 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2018-01-01 21:38:20,326 : INFO : < 200 OK [1462]
2018-01-01 21:38:20,330 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 49, 'level': 'Intermediate', 'name': 'Real-Time Cyber Threat Detection and Mitigation'}}
2018-01-01 21:38:20,334 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2018-01-01 21:38:20,338 : INFO : < 200 OK [1444]
2018-01-01 21:38:20,342 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 50, 'rating': '5.0', 'level': 'Intermediate', 'name': 'Enterprise and Infrastructure Security'}}
2018-01-01 21:38:20,342 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:20,346 : INFO : < 200 OK [1460]
2018-01-01 21:38:20,350 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 467, 'rating': '4.9', 'level': 'Beginner', 'name': 'Detecting and Mitigating Cyber Threats and Attacks'}}
2018-01-01 21:38:20,350 : INFO : > POST http://localhost:7474/db/data/cypher [167]
2018-01-01 21:38:20,354 : INFO : < 200 OK [1469]
2018-01-01 21:38:20,358 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 52, 'rating': '4.4', 'name': 'Internet of Things: Communication Technologies'}}

2018-01-01 21:38:20,358 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2018-01-01 21:38:20,366 : INFO : < 200 OK [1435]
2018-01-01 21:38:20,371 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 829, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Google Cloud Platform Fundamentals for AWS Professionals'}}
2018-01-01 21:38:20,372 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:20,377 : INFO : < 200 OK [1479]
2018-01-01 21:38:20,381 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 833, 'rating': '3.7', 'level': 'Beginner', 'name': 'Introduction to Architecting Smart IoT Devices'}}
2018-01-01 21:38:20,383 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2018-01-01 21:38:20,386 : INFO : < 200 OK [1465]
2018-01-01 21:38:20,390 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 55, 'name': 'Peer-to-Peer Protocols and Local Area Networks'}}
2018-01-01 21:38:20,390 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:20,398 : INFO : < 200 OK [1410]
2018-01-01 21:38:20,402 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 56, 'rating': '4.7', 'name': 'Networks: Friends, Money, and Bytes'}}
2018-01-01 21:38:20,402 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:20,407 : INFO : < 200 OK [1424]
2018-01-01 21:38:20,410 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 340, 'level': 'Intermediate', 'name': 'Symmetric Cryptography'}}
2018-01-01 21:38:20,410 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:20,414 : INFO : < 200 OK [1420]
2018-01-01 21:38:20,418 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 222, 'rating': '5.0', 'level': 'Intermediate', 'name': 'Secure Networked System with Firewall and IDS'}}
2018-01-01 21:38:20,418 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2018-01-01 21:38:20,426 : INFO : < 200 OK [1468]
2018-01-01 21:38:20,426 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 59, 'level': 'Intermediate', 'name': 'Packet Switching Networks and Algorithms'}}
2018-01-01 21:38:20,430 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:20,434 : INFO : < 200 OK [1437]
2018-01-01 21:38:20,438 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 60, 'rating': '4.5', 'level': 'Beginner', 'name': 'Privacy, Reputation, and Identity in a Digital Age Teach-Out'}}
2018-01-01 21:38:20,438 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:20,442 : INFO : < 200 OK [1478]
2018-01-01 21:38:20,446 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 344, 'level': 'Intermediate', 'name': 'Asymmetric Cryptography and Key Management'}}
2018-01-01 21:38:20,446 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:20,454 : INFO : < 200 OK [1440]
2018-01-01 21:38:20,458 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 62, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Web Connectivity and Security in Embedded Systems'}}
2018-01-01 21:38:20,458 : INFO : > POST http://localhost:7474/db/data/cypher [169]
2018-01-01 21:38:20,462 : INFO : < 200 OK [1471]
2018-01-01 21:38:20,466 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 468, 'rating': '5.0', 'level': 'Beginner', 'name': 'Proactive Computer Security'}}
2018-01-01 21:38:20,466 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:20,475 : INFO : < 200 OK [1446]
2018-01-01 21:38:20,478 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 64, 'rating': '4.3', 'name': 'Internet Emerging Technologies'}}
2018-01-01 21:38:20,480 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:20,484 : INFO : < 200 OK [1419]
2018-01-01 21:38:20,487 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 346, 'level': 'Intermediate', 'name': 'Cryptographic Hash and Integrity Protection'}}
2018-01-01 21:38:20,487 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:20,491 : INFO : < 200 OK [1441]
2018-01-01 21:38:20,495 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 66, 'rating': '4.4', 'level': 'Beginner', 'name': 'Cybersecurity and Mobility'}}
2018-01-01 21:38:20,495 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:20,503 : INFO : < 200 OK [1444]
2018-01-01 21:38:20,503 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 67, 'rating': '4.4', 'level': 'Beginner', 'name': 'Networks Illustrated: Principles without Calculus'}}
2018-01-01 21:38:20,507 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:20,511 : INFO : < 200 OK [1467]
2018-01-01 21:38:20,515 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 469, 'level': 'Intermediate', 'name': 'Planning, Auditing and Maintaining Enterprise Systems'}}
2018-01-01 21:38:20,515 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2018-01-01 21:38:20,519 : INFO : < 200 OK [1451]
2018-01-01 21:38:20,523 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 69, 'rating': '4.6', 'level': 'Beginner', 'name': "Homeland Security & Cybersecurity Connection - It's Not About the Terrorists"}}
2018-01-01 21:38:20,523 : INFO : > POST http://localhost:7474/db/data/cypher [192]
2018-01-01 21:38:20,527 : INFO : < 200 OK [1494]
2018-01-01 21:38:20,531 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 70, 'rating': '4.8', 'name': 'Securing Digital Democracy'}}
2018-01-01 21:38:20,531 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2018-01-01 21:38:20,535 : INFO : < 200 OK [1415]
2018-01-01 21:38:20,539 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 855, 'rating': '4.4', 'level': 'Advanced', 'name': 'System Validation (4): Modelling Software, Protocols, and other behaviour'}}
2018-01-01 21:38:20,539 : INFO : > POST http://localhost:7474/db/data/cypher [190]
2018-01-01 21:38:20,547 : INFO : < 200 OK [1492]
2018-01-01 21:38:20,547 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 72, 'rating': '4.7', 'level': 'Beginner', 'name': 'Cybersecurity Policy for Water and Electricity Infrastructures'}}
2018-01-01 21:38:20,551 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:20,555 : INFO : < 200 OK [1480]
2018-01-01 21:38:20,555 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 412, 'rating': '4.6', 'name': 'Networking and Security in iOS Applications'}}
2018-01-01 21:38:20,559 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:20,575 : INFO : < 200 OK [1433]
2018-01-01 21:38:20,578 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 74, 'rating': '4.8', 'level': 'Beginner', 'name': 'Homeland Security and Cybersecurity Future'}}
2018-01-01 21:38:20,581 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:20,585 : INFO : < 200 OK [1460]
2018-01-01 21:38:20,587 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 75, 'rating': '4.6', 'level': 'Beginner', 'name': 'Cybersecurity and the X-Factor'}}
2018-01-01 21:38:20,587 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2018-01-01 21:38:20,595 : INFO : < 200 OK [1448]
2018-01-01 21:38:20,595 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 274, 'rating': '4.1', 'name': 'Emerging Technologies Capstone '}}
2018-01-01 21:38:20,599 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2018-01-01 21:38:20,603 : INFO : < 200 OK [1421]
2018-01-01 21:38:20,607 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 77, 'rating': '4.8', 'level': 'Beginner', 'name': 'Cybersecurity Policy for Aviation and Internet Infrastructures'}}
2018-01-01 21:38:20,607 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:20,611 : INFO : < 200 OK [1480]
2018-01-01 21:38:20,615 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 867, 'rating': '5.0', 'level': 'Beginner', 'name': 'Develop and Deploy Windows Applications on Google Cloud Platform'}}

2018-01-01 21:38:20,615 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:20,623 : INFO : < 200 OK [1483]
2018-01-01 21:38:20,623 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 79, 'rating': '4.5', 'name': 'Cloud Computing Project'}}
2018-01-01 21:38:20,627 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2018-01-01 21:38:20,631 : INFO : < 200 OK [1412]
2018-01-01 21:38:20,631 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 874, 'rating': '4.7', 'level': 'Beginner', 'name': 'The Business of Cybersecurity Capstone'}}
2018-01-01 21:38:20,635 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2018-01-01 21:38:20,639 : INFO : < 200 OK [1457]
2018-01-01 21:38:20,639 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 81, 'rating': '4.0', 'level': 'Intermediate', 'name': 'Cybersecurity Capstone Project'}}
2018-01-01 21:38:20,643 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:20,651 : INFO : < 200 OK [1452]
2018-01-01 21:38:20,655 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 82, 'rating': '4.5', 'level': 'Beginner', 'name': 'The Internet and You'}}
2018-01-01 21:38:20,655 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:20,663 : INFO : < 200 OK [1438]
2018-01-01 21:38:20,667 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 471, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Neural Networks and Deep Learning'}}
2018-01-01 21:38:20,667 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:20,676 : INFO : < 200 OK [1456]
2018-01-01 21:38:20,679 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 472, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Convolutional Neural Networks'}}
2018-01-01 21:38:20,681 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:20,686 : INFO : < 200 OK [1452]
2018-01-01 21:38:20,687 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 473, 'rating': '4.9', 'level': 'Beginner', 'name': 'Improving Deep Neural Networks: Hyperparameter tuning, Regularization and Optimization'}}
2018-01-01 21:38:20,691 : INFO : > POST http://localhost:7474/db/data/cypher [203]
2018-01-01 21:38:20,695 : INFO : < 200 OK [1505]
2018-01-01 21:38:20,699 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 699, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Algorithms, Part I'}}
2018-01-01 21:38:20,699 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:20,703 : INFO : < 200 OK [1441]
2018-01-01 21:38:20,707 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 701, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Algorithmic Toolbox'}}
2018-01-01 21:38:20,707 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2018-01-01 21:38:20,715 : INFO : < 200 OK [1442]
2018-01-01 21:38:20,715 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 476, 'level': 'Intermediate', 'name': 'Sequence Models'}}
2018-01-01 21:38:20,719 : INFO : > POST http://localhost:7474/db/data/cypher [121]
2018-01-01 21:38:20,723 : INFO : < 200 OK [1413]
2018-01-01 21:38:20,727 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 288, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Divide and Conquer, Sorting and Searching, and Randomized Algorithms'}}
2018-01-01 21:38:20,731 : INFO : > POST http://localhost:7474/db/data/cypher [189]
2018-01-01 21:38:20,735 : INFO : < 200 OK [1491]
2018-01-01 21:38:20,739 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 711, 'rating': '4.8', 'name': 'An Introduction to Interactive Programming in Python (Part 1)'}}
2018-01-01 21:38:20,739 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2018-01-01 21:38:20,743 : INFO : < 200 OK [1451]
2018-01-01 21:38:20,747 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 714, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Algorithms, Part II'}}
2018-01-01 21:38:20,747 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2018-01-01 21:38:20,755 : INFO : < 200 OK [1442]
2018-01-01 21:38:20,759 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 92, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Data Structures'}}
2018-01-01 21:38:20,759 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2018-01-01 21:38:20,763 : INFO : < 200 OK [1437]
2018-01-01 21:38:20,767 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 93, 'rating': '4.9', 'name': 'Build a Modern Computer from First Principles: From Nand to Tetris (Project-Centered Course)'}}
2018-01-01 21:38:20,767 : INFO : > POST http://localhost:7474/db/data/cypher [189]
2018-01-01 21:38:20,773 : INFO : < 200 OK [1481]
2018-01-01 21:38:20,776 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 723, 'rating': '4.7', 'level': 'Beginner', 'name': 'Programming Fundamentals'}}
2018-01-01 21:38:20,778 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:20,782 : INFO : < 200 OK [1443]
2018-01-01 21:38:20,785 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 95, 'rating': '4.5', 'level': 'Beginner', 'name': 'Cloud Computing Concepts, Part 1'}}
2018-01-01 21:38:20,787 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:20,791 : INFO : < 200 OK [1450]
2018-01-01 21:38:20,791 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 239, 'rating': '4.6', 'name': 'Fundamentals of Digital Image and Video Processing'}}
2018-01-01 21:38:20,795 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:20,799 : INFO : < 200 OK [1440]
2018-01-01 21:38:20,803 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 484, 'rating': '4.7', 'level': 'Advanced', 'name': 'Probabilistic Graphical Models 1: Representation'}}
2018-01-01 21:38:20,803 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:20,811 : INFO : < 200 OK [1467]
2018-01-01 21:38:20,811 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 294, 'rating': '4.6', 'level': 'Beginner', 'name': 'What is a Proof?'}}
2018-01-01 21:38:20,815 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2018-01-01 21:38:20,819 : INFO : < 200 OK [1435]
2018-01-01 21:38:20,823 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 99, 'rating': '4.4', 'name': 'Computational Investing, Part I'}}
2018-01-01 21:38:20,823 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:20,831 : INFO : < 200 OK [1420]
2018-01-01 21:38:20,831 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 100, 'rating': '4.6', 'name': 'Big Data Analysis with Scala and Spark'}}
2018-01-01 21:38:20,835 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:20,839 : INFO : < 200 OK [1428]
2018-01-01 21:38:20,843 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 243, 'rating': '4.4', 'level': 'Beginner', 'name': 'Building Arduino robots and devices'}}
2018-01-01 21:38:20,843 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2018-01-01 21:38:20,847 : INFO : < 200 OK [1454]
2018-01-01 21:38:20,851 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 297, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Graph Search, Shortest Paths, and Data Structures'}}
2018-01-01 21:38:20,855 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2018-01-01 21:38:20,859 : INFO : < 200 OK [1472]
2018-01-01 21:38:20,863 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 740, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Algorithms on Graphs'}}
2018-01-01 21:38:20,863 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:20,871 : INFO : < 200 OK [1443]
2018-01-01 21:38:20,874 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 742, 'level': 'Beginner', 'name': 'Writing, Running, and Fixing Code in C'}}
2018-01-01 21:38:20,876 : INFO : > POST http://localhost:7474/db/data/cypher [140]

2018-01-01 21:38:20,880 : INFO : < 200 OK [1432]
2018-01-01 21:38:20,883 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 299, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Greedy Algorithms, Minimum Spanning Trees, and Dynamic Programming'}}
2018-01-01 21:38:20,885 : INFO : > POST http://localhost:7474/db/data/cypher [187]
2018-01-01 21:38:20,887 : INFO : < 200 OK [1489]
2018-01-01 21:38:20,891 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 301, 'rating': '3.7', 'level': 'Intermediate', 'name': 'Discrete Mathematics'}}
2018-01-01 21:38:20,891 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:20,895 : INFO : < 200 OK [1443]
2018-01-01 21:38:20,899 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 107, 'rating': '4.7', 'level': 'Beginner', 'name': 'Finding Hidden Messages in DNA (Bioinformatics I)'}}
2018-01-01 21:38:20,899 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2018-01-01 21:38:20,907 : INFO : < 200 OK [1468]
2018-01-01 21:38:20,911 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 302, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Discrete Optimization'}}
2018-01-01 21:38:20,911 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:20,915 : INFO : < 200 OK [1444]
2018-01-01 21:38:20,919 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 303, 'rating': '4.6', 'level': 'Beginner', 'name': 'Introduction to Graph Theory'}}
2018-01-01 21:38:20,919 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:20,923 : INFO : < 200 OK [1447]
2018-01-01 21:38:20,927 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 307, 'rating': '4.6', 'level': 'Beginner', 'name': 'Combinatorics and Probability'}}
2018-01-01 21:38:20,927 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2018-01-01 21:38:20,935 : INFO : < 200 OK [1448]
2018-01-01 21:38:20,935 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 753, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Algorithmic Thinking (Part 1)'}}
2018-01-01 21:38:20,939 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:20,943 : INFO : < 200 OK [1466]
2018-01-01 21:38:20,947 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 112, 'level': 'Beginner', 'name': 'Excel/VBA for Creative Problem Solving, Part 1'}}
2018-01-01 21:38:20,947 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:20,951 : INFO : < 200 OK [1440]
2018-01-01 21:38:20,955 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 755, 'rating': '4.4', 'level': 'Advanced', 'name': 'Advanced Algorithms and Complexity'}}
2018-01-01 21:38:20,955 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2018-01-01 21:38:20,959 : INFO : < 200 OK [1467]
2018-01-01 21:38:20,963 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 114, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Data Structures and Performance'}}
2018-01-01 21:38:20,967 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2018-01-01 21:38:20,971 : INFO : < 200 OK [1454]
2018-01-01 21:38:20,974 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 115, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Algorithms on Strings'}}
2018-01-01 21:38:20,975 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:20,980 : INFO : < 200 OK [1458]
2018-01-01 21:38:20,982 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 308, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Shortest Paths Revisited, NP-Complete Problems and What To Do About Them'}}
2018-01-01 21:38:20,984 : INFO : > POST http://localhost:7474/db/data/cypher [193]
2018-01-01 21:38:20,987 : INFO : < 200 OK [1495]
2018-01-01 21:38:20,991 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 586, 'rating': '4.5', 'name': 'Introduction to Genomic Technologies'}}
2018-01-01 21:38:20,991 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:20,995 : INFO : < 200 OK [1440]
2018-01-01 21:38:20,999 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 768, 'rating': '4.3', 'level': 'Intermediate', 'name': 'Interactive Computer Graphics'}}
2018-01-01 21:38:20,999 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:21,003 : INFO : < 200 OK [1452]
2018-01-01 21:38:21,007 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 772, 'rating': '4.9', 'level': 'Beginner', 'name': 'An Introduction to Interactive Programming in Python (Part 2)'}}
2018-01-01 21:38:21,011 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:21,015 : INFO : < 200 OK [1494]
2018-01-01 21:38:21,015 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 496, 'level': 'Intermediate', 'name': 'Practical Reinforcement Learning'}}
2018-01-01 21:38:21,019 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:21,023 : INFO : < 200 OK [1430]
2018-01-01 21:38:21,023 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 312, 'rating': '4.5', 'level': 'Beginner', 'name': 'Number Theory and Cryptography'}}
2018-01-01 21:38:21,027 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2018-01-01 21:38:21,031 : INFO : < 200 OK [1463]
2018-01-01 21:38:21,035 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 122, 'rating': '4.1', 'level': 'Advanced', 'name': 'Big Data, Genes, and Medicine'}}
2018-01-01 21:38:21,035 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2018-01-01 21:38:21,043 : INFO : < 200 OK [1448]
2018-01-01 21:38:21,043 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 123, 'level': 'Advanced', 'name': 'Natural Language Processing'}}
2018-01-01 21:38:21,047 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2018-01-01 21:38:21,051 : INFO : < 200 OK [1435]
2018-01-01 21:38:21,055 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 499, 'rating': '4.6', 'level': 'Advanced', 'name': 'Probabilistic Graphical Models 2: Inference'}}
2018-01-01 21:38:21,055 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2018-01-01 21:38:21,059 : INFO : < 200 OK [1462]
2018-01-01 21:38:21,063 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 502, 'rating': '4.7', 'level': 'Advanced', 'name': 'Probabilistic Graphical Models 3: Learning'}}
2018-01-01 21:38:21,063 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2018-01-01 21:38:21,067 : INFO : < 200 OK [1475]
2018-01-01 21:38:21,071 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 789, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Principles of Computing (Part 1)'}}
2018-01-01 21:38:21,073 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:21,078 : INFO : < 200 OK [1455]
2018-01-01 21:38:21,080 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 128, 'level': 'Advanced', 'name': 'Analysis of Algorithms'}}
2018-01-01 21:38:21,083 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2018-01-01 21:38:21,087 : INFO : < 200 OK [1430]
2018-01-01 21:38:21,087 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 129, 'rating': '4.8', 'level': 'Intermediate', 'name': 'VLSI CAD Part I: Logic'}}
2018-01-01 21:38:21,087 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2018-01-01 21:38:21,091 : INFO : < 200 OK [1445]
2018-01-01 21:38:21,095 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 791, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Advanced Data Structures in Java'}}
2018-01-01 21:38:21,099 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:21,103 : INFO : < 200 OK [1469]
2018-01-01 21:38:21,107 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 131, 'rating': '4.6', 'name': 'Cloud Computing Concepts: Part 2'}}
2018-01-01 21:38:21,107 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:21,115 : INFO : < 200 OK [1422]
2018-01-01 21:38:21,119 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 132, 'level': 'Advanced', 'name': 'Deep Learning in Computer Vision'}}

2018-01-01 21:38:21,119 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:21,123 : INFO : < 200 OK [1440]
2018-01-01 21:38:21,127 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 324, 'rating': '4.8', 'level': 'Beginner', 'name': 'Delivery Problem'}}
2018-01-01 21:38:21,127 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2018-01-01 21:38:21,135 : INFO : < 200 OK [1435]
2018-01-01 21:38:21,135 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 640, 'rating': '4.8', 'name': 'Algorithms for DNA Sequencing'}}
2018-01-01 21:38:21,139 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:21,143 : INFO : < 200 OK [1433]
2018-01-01 21:38:21,147 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 811, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Algorithmic Thinking (Part 2)'}}
2018-01-01 21:38:21,147 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:21,155 : INFO : < 200 OK [1452]
2018-01-01 21:38:21,155 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 136, 'rating': '5.0', 'level': 'Advanced', 'name': 'Kinematics: Describing the Motions of Spacecraft'}}
2018-01-01 21:38:21,155 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:21,159 : INFO : < 200 OK [1481]
2018-01-01 21:38:21,163 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 137, 'rating': '4.7', 'name': 'Approximation Algorithms Part I'}}
2018-01-01 21:38:21,163 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2018-01-01 21:38:21,171 : INFO : < 200 OK [1421]
2018-01-01 21:38:21,172 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 815, 'rating': '4.8', 'name': 'Principles of Computing (Part 2)'}}
2018-01-01 21:38:21,174 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:21,178 : INFO : < 200 OK [1436]
2018-01-01 21:38:21,181 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 139, 'rating': '5.0', 'level': 'Advanced', 'name': 'Kinetics: Studying Spacecraft Motion'}}
2018-01-01 21:38:21,182 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:21,187 : INFO : < 200 OK [1455]
2018-01-01 21:38:21,187 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 141, 'rating': '4.7', 'level': 'Beginner', 'name': 'Genome Sequencing (Bioinformatics II)'}}
2018-01-01 21:38:21,191 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:21,195 : INFO : < 200 OK [1470]
2018-01-01 21:38:21,199 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 142, 'rating': '5.0', 'level': 'Advanced', 'name': 'Control of Nonlinear Spacecraft Attitude Motion'}}
2018-01-01 21:38:21,199 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2018-01-01 21:38:21,207 : INFO : < 200 OK [1466]
2018-01-01 21:38:21,211 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 143, 'rating': '4.1', 'level': 'Beginner', 'name': 'Genomic Data Science and Clustering (Bioinformatics V)'}}
2018-01-01 21:38:21,211 : INFO : > POST http://localhost:7474/db/data/cypher [171]
2018-01-01 21:38:21,215 : INFO : < 200 OK [1487]
2018-01-01 21:38:21,219 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 144, 'rating': '4.9', 'level': 'Intermediate', 'name': 'VLSI CAD Part II: Layout'}}
2018-01-01 21:38:21,219 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:21,223 : INFO : < 200 OK [1447]
2018-01-01 21:38:21,227 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 145, 'level': 'Advanced', 'name': 'Addressing Large Hadron Collider Challenges by Machine Learning'}}
2018-01-01 21:38:21,227 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:21,235 : INFO : < 200 OK [1471]
2018-01-01 21:38:21,235 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 146, 'rating': '4.5', 'level': 'Beginner', 'name': 'Molecular Evolution (Bioinformatics IV)'}}
2018-01-01 21:38:21,239 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2018-01-01 21:38:21,243 : INFO : < 200 OK [1472]
2018-01-01 21:38:21,247 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 147, 'rating': '4.7', 'level': 'Beginner', 'name': 'Comparing Genes, Proteins, and Genomes (Bioinformatics III)'}}
2018-01-01 21:38:21,247 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:21,251 : INFO : < 200 OK [1492]
2018-01-01 21:38:21,255 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 148, 'rating': '4.5', 'level': 'Beginner', 'name': 'Finding Mutations in DNA and Proteins (Bioinformatics VI)'}}
2018-01-01 21:38:21,255 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:38:21,259 : INFO : < 200 OK [1490]
2018-01-01 21:38:21,263 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 150, 'rating': '4.2', 'name': 'Global Warming II: Create Your Own Models in Python'}}
2018-01-01 21:38:21,263 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:21,267 : INFO : < 200 OK [1455]
2018-01-01 21:38:21,272 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 151, 'rating': '4.8', 'name': 'Approximation Algorithms Part II'}}
2018-01-01 21:38:21,274 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:21,278 : INFO : < 200 OK [1436]
2018-01-01 21:38:21,280 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 152, 'rating': '4.3', 'level': 'Advanced', 'name': 'Genome Assembly Programming Challenge'}}
2018-01-01 21:38:21,282 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:21,287 : INFO : < 200 OK [1470]
2018-01-01 21:38:21,287 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 871, 'rating': '4.8', 'level': 'Intermediate', 'name': 'The Fundamentals of Computing Capstone Exam'}}
2018-01-01 21:38:21,291 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2018-01-01 21:38:21,295 : INFO : < 200 OK [1480]
2018-01-01 21:38:21,299 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 154, 'rating': '4.5', 'level': 'Beginner', 'name': 'Bioinformatics Capstone: Big Data in Biology'}}
2018-01-01 21:38:21,299 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2018-01-01 21:38:21,307 : INFO : < 200 OK [1477]
2018-01-01 21:38:21,307 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 279, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Digital Signal Processing'}}
2018-01-01 21:38:21,311 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2018-01-01 21:38:21,315 : INFO : < 200 OK [1462]
2018-01-01 21:38:21,319 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 696, 'rating': '4.1', 'level': 'Intermediate', 'name': 'Introduction to Natural Language Processing'}}
2018-01-01 21:38:21,319 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2018-01-01 21:38:21,323 : INFO : < 200 OK [1480]
2018-01-01 21:38:21,327 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 736, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Introduction to MongoDB'}}
2018-01-01 21:38:21,327 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:21,335 : INFO : < 200 OK [1460]
2018-01-01 21:38:21,335 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 641, 'level': 'Intermediate', 'name': 'Applying Machine Learning to your Data with GCP'}}
2018-01-01 21:38:21,339 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:21,343 : INFO : < 200 OK [1459]
2018-01-01 21:38:21,347 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 667, 'rating': '4.2', 'level': 'Beginner', 'name': 'Creating New BigQuery Datasets and Visualizing Insights'}}
2018-01-01 21:38:21,347 : INFO : > POST http://localhost:7474/db/data/cypher [172]
2018-01-01 21:38:21,351 : INFO : < 200 OK [1488]
2018-01-01 21:38:21,355 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 671, 'rating': '4.8', 'level': 'Beginner', 'name': 'Achieving Advanced Insights with BigQuery'}}

2018-01-01 21:38:21,355 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:21,363 : INFO : < 200 OK [1474]
2018-01-01 21:38:21,363 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 169, 'rating': '4.7', 'name': 'Fundamentals of Graphic Design'}}
2018-01-01 21:38:21,367 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:21,373 : INFO : < 200 OK [1434]
2018-01-01 21:38:21,376 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 535, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Applied Plotting, Charting & Data Representation in Python'}}
2018-01-01 21:38:21,378 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2018-01-01 21:38:21,382 : INFO : < 200 OK [1495]
2018-01-01 21:38:21,385 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 362, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Introduction to Structured Query Language (SQL)'}}
2018-01-01 21:38:21,387 : INFO : > POST http://localhost:7474/db/data/cypher [168]
2018-01-01 21:38:21,391 : INFO : < 200 OK [1484]
2018-01-01 21:38:21,395 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 364, 'rating': '4.9', 'name': 'HTML, CSS, and Javascript for Web Developers'}}
2018-01-01 21:38:21,395 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:21,399 : INFO : < 200 OK [1448]
2018-01-01 21:38:21,403 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 238, 'rating': '4.8', 'level': 'Advanced', 'name': 'Computer Architecture'}}
2018-01-01 21:38:21,403 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:21,407 : INFO : < 200 OK [1454]
2018-01-01 21:38:21,411 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 174, 'rating': '4.4', 'level': 'Beginner', 'name': 'Introduction to User Experience Design '}}
2018-01-01 21:38:21,411 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2018-01-01 21:38:21,419 : INFO : < 200 OK [1472]
2018-01-01 21:38:21,419 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 369, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Building Web Applications in PHP'}}
2018-01-01 21:38:21,423 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:21,427 : INFO : < 200 OK [1469]
2018-01-01 21:38:21,431 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 726, 'rating': '4.5', 'name': 'Introduction to the Internet of Things and Embedded Systems'}}
2018-01-01 21:38:21,431 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2018-01-01 21:38:21,439 : INFO : < 200 OK [1463]
2018-01-01 21:38:21,443 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 177, 'rating': '4.8', 'level': 'Beginner', 'name': 'VR & 360 Video Production'}}
2018-01-01 21:38:21,443 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:21,451 : INFO : < 200 OK [1458]
2018-01-01 21:38:21,451 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 178, 'name': 'Gamification'}}
2018-01-01 21:38:21,455 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:21,459 : INFO : < 200 OK [1391]
2018-01-01 21:38:21,463 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 241, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Introduction to FPGA Design for Embedded Systems'}}
2018-01-01 21:38:21,463 : INFO : > POST http://localhost:7474/db/data/cypher [169]
2018-01-01 21:38:21,467 : INFO : < 200 OK [1485]
2018-01-01 21:38:21,473 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 374, 'rating': '4.7', 'level': 'Intermediate', 'name': 'JavaScript, jQuery, and JSON'}}
2018-01-01 21:38:21,475 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:21,479 : INFO : < 200 OK [1465]
2018-01-01 21:38:21,482 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 734, 'rating': '4.7', 'name': 'Getting Started: Agile Meets Design Thinking'}}
2018-01-01 21:38:21,484 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:21,487 : INFO : < 200 OK [1448]
2018-01-01 21:38:21,487 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 182, 'rating': '4.6', 'name': 'Human-Centered Design: an Introduction'}}
2018-01-01 21:38:21,491 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:21,495 : INFO : < 200 OK [1442]
2018-01-01 21:38:21,499 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 743, 'rating': '4.6', 'level': 'Beginner', 'name': 'Introduction to UI Design'}}
2018-01-01 21:38:21,499 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:21,507 : INFO : < 200 OK [1458]
2018-01-01 21:38:21,511 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 184, 'rating': '4.7', 'name': 'Introduction to Typography'}}
2018-01-01 21:38:21,511 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2018-01-01 21:38:21,515 : INFO : < 200 OK [1430]
2018-01-01 21:38:21,515 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 185, 'level': 'Intermediate', 'name': 'Autodesk Fusion 360 Integrated CAD/CAM/CAE'}}
2018-01-01 21:38:21,519 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:21,519 : INFO : < 200 OK [1454]
2018-01-01 21:38:21,523 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 756, 'rating': '4.5', 'name': 'Introduction to Software Product Management'}}
2018-01-01 21:38:21,523 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:21,531 : INFO : < 200 OK [1447]
2018-01-01 21:38:21,531 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 251, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Digital Systems: From Logic Gates to Processors'}}
2018-01-01 21:38:21,531 : INFO : > POST http://localhost:7474/db/data/cypher [168]
2018-01-01 21:38:21,539 : INFO : < 200 OK [1484]
2018-01-01 21:38:21,539 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 382, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Building Database Applications in PHP'}}
2018-01-01 21:38:21,543 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:21,547 : INFO : < 200 OK [1474]
2018-01-01 21:38:21,551 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 190, 'rating': '4.4', 'level': 'Beginner', 'name': 'Introduction to Imagemaking'}}
2018-01-01 21:38:21,551 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:21,555 : INFO : < 200 OK [1460]
2018-01-01 21:38:21,559 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 384, 'rating': '4.7', 'level': 'Beginner', 'name': 'Introduction to Virtual Reality'}}
2018-01-01 21:38:21,559 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:21,563 : INFO : < 200 OK [1464]
2018-01-01 21:38:21,567 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 776, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Development of Real-Time Systems'}}
2018-01-01 21:38:21,567 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:21,574 : INFO : < 200 OK [1469]
2018-01-01 21:38:21,578 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 193, 'rating': '4.7', 'level': 'Beginner', 'name': 'Introduction to Game Design'}}
2018-01-01 21:38:21,581 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:21,586 : INFO : < 200 OK [1460]
2018-01-01 21:38:21,587 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 781, 'rating': '4.7', 'name': 'Software Processes and Agile Practices'}}
2018-01-01 21:38:21,587 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:21,587 : INFO : < 200 OK [1442]
2018-01-01 21:38:21,587 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 609, 'rating': '4.5', 'name': 'Data Warehouse Concepts, Design, and Data Integration'}}
2018-01-01 21:38:21,587 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2018-01-01 21:38:21,603 : INFO : < 200 OK [1457]
2018-01-01 21:38:21,603 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 790, 'rating': '4.7', 'name': 'Client Needs and Software Requirements '}}

2018-01-01 21:38:21,603 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:21,603 : INFO : < 200 OK [1443]
2018-01-01 21:38:21,603 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 198, 'rating': '4.7', 'name': 'Managing an Agile Team'}}
2018-01-01 21:38:21,618 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2018-01-01 21:38:21,624 : INFO : < 200 OK [1426]
2018-01-01 21:38:21,628 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 199, 'rating': '4.6', 'level': 'Beginner', 'name': 'Design Principles: an Introduction'}}
2018-01-01 21:38:21,628 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2018-01-01 21:38:21,634 : INFO : < 200 OK [1467]
2018-01-01 21:38:21,634 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 794, 'rating': '4.7', 'name': 'Agile Planning for Software Products'}}
2018-01-01 21:38:21,634 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:21,634 : INFO : < 200 OK [1440]
2018-01-01 21:38:21,646 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 622, 'rating': '3.6', 'level': 'Intermediate', 'name': 'Designing, Running, and Analyzing Experiments'}}
2018-01-01 21:38:21,646 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2018-01-01 21:38:21,654 : INFO : < 200 OK [1482]
2018-01-01 21:38:21,658 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 795, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Running Product Design Sprints'}}
2018-01-01 21:38:21,658 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2018-01-01 21:38:21,686 : INFO : < 200 OK [1467]
2018-01-01 21:38:21,691 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 203, 'rating': '4.5', 'name': 'User Experience: Research & Prototyping'}}
2018-01-01 21:38:21,693 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:21,700 : INFO : < 200 OK [1443]
2018-01-01 21:38:21,703 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 798, 'rating': '4.4', 'name': 'Principles of Game Design'}}
2018-01-01 21:38:21,704 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2018-01-01 21:38:21,713 : INFO : < 200 OK [1429]
2018-01-01 21:38:21,717 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 802, 'rating': '4.4', 'name': 'Testing with Agile'}}
2018-01-01 21:38:21,719 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2018-01-01 21:38:21,727 : INFO : < 200 OK [1422]
2018-01-01 21:38:21,730 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 803, 'rating': '4.7', 'level': 'Intermediate', 'name': '3D Models for Virtual Reality'}}
2018-01-01 21:38:21,732 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:21,737 : INFO : < 200 OK [1466]
2018-01-01 21:38:21,740 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 804, 'rating': '4.7', 'name': 'User Research and Design'}}
2018-01-01 21:38:21,743 : INFO : > POST http://localhost:7474/db/data/cypher [122]
2018-01-01 21:38:21,748 : INFO : < 200 OK [1428]
2018-01-01 21:38:21,752 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 208, 'rating': '3.9', 'name': 'Internet of Things & Augmented Reality Emerging Technologies'}}
2018-01-01 21:38:21,755 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:21,761 : INFO : < 200 OK [1464]
2018-01-01 21:38:21,764 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 814, 'rating': '4.7', 'name': 'Prototyping and Design'}}
2018-01-01 21:38:21,767 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2018-01-01 21:38:21,772 : INFO : < 200 OK [1426]
2018-01-01 21:38:21,776 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 210, 'rating': '4.4', 'name': 'Information Design'}}
2018-01-01 21:38:21,779 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2018-01-01 21:38:21,784 : INFO : < 200 OK [1422]
2018-01-01 21:38:21,787 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 816, 'rating': '4.6', 'name': 'Reviews & Metrics for Software Improvements'}}
2018-01-01 21:38:21,789 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:21,796 : INFO : < 200 OK [1447]
2018-01-01 21:38:21,799 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 818, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Agile Development in Practice (Project-centered Course)'}}
2018-01-01 21:38:21,801 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:21,805 : INFO : < 200 OK [1492]
2018-01-01 21:38:21,809 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 213, 'rating': '4.6', 'name': 'Story and Narrative Development for Video Games'}}
2018-01-01 21:38:21,810 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:21,815 : INFO : < 200 OK [1451]
2018-01-01 21:38:21,817 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 214, 'rating': '4.6', 'name': 'Character Design for Video Games'}}
2018-01-01 21:38:21,819 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:21,824 : INFO : < 200 OK [1436]
2018-01-01 21:38:21,829 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 825, 'rating': '4.8', 'name': 'Software Product Management Capstone'}}
2018-01-01 21:38:21,831 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:21,836 : INFO : < 200 OK [1440]
2018-01-01 21:38:21,839 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 827, 'level': 'Intermediate', 'name': 'Building Interactive 3D Characters and Social VR'}}
2018-01-01 21:38:21,841 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:21,846 : INFO : < 200 OK [1460]
2018-01-01 21:38:21,848 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 830, 'rating': '4.7', 'name': 'Evaluating User Interfaces'}}
2018-01-01 21:38:21,850 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2018-01-01 21:38:21,855 : INFO : < 200 OK [1430]
2018-01-01 21:38:21,859 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 218, 'rating': '4.5', 'level': 'Beginner', 'name': 'Intro to Digital Manufacturing with Autodesk Fusion 360'}}
2018-01-01 21:38:21,861 : INFO : > POST http://localhost:7474/db/data/cypher [172]
2018-01-01 21:38:21,865 : INFO : < 200 OK [1488]
2018-01-01 21:38:21,868 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 832, 'rating': '4.9', 'level': 'Intermediate', 'name': '3D Interaction Design in Virtual Reality'}}
2018-01-01 21:38:21,869 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2018-01-01 21:38:21,876 : INFO : < 200 OK [1477]
2018-01-01 21:38:21,878 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 835, 'level': 'Intermediate', 'name': 'Making Your First Virtual Reality Game'}}
2018-01-01 21:38:21,880 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:21,885 : INFO : < 200 OK [1450]
2018-01-01 21:38:21,887 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 221, 'rating': '4.6', 'name': 'Input and Interaction'}}
2018-01-01 21:38:21,890 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2018-01-01 21:38:21,897 : INFO : < 200 OK [1425]
2018-01-01 21:38:21,899 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 223, 'rating': '4.4', 'name': 'World Design for Video Games'}}
2018-01-01 21:38:21,901 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2018-01-01 21:38:21,906 : INFO : < 200 OK [1432]
2018-01-01 21:38:21,910 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 224, 'level': 'Intermediate', 'name': 'Mobile Interaction Design: How to Design Usable Mobile Products and Services'}}
2018-01-01 21:38:21,911 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:21,916 : INFO : < 200 OK [1488]
2018-01-01 21:38:21,919 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 849, 'rating': '4.0', 'level': 'Intermediate', 'name': 'System Validation: Automata and behavioural equivalences'}}

2018-01-01 21:38:21,920 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:21,925 : INFO : < 200 OK [1493]
2018-01-01 21:38:21,928 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 230, 'rating': '4.9', 'name': 'Brand New Brand'}}
2018-01-01 21:38:21,930 : INFO : > POST http://localhost:7474/db/data/cypher [113]
2018-01-01 21:38:21,936 : INFO : < 200 OK [1419]
2018-01-01 21:38:21,938 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 857, 'rating': '4.0', 'level': 'Intermediate', 'name': 'System Validation (2): Model process behaviour'}}
2018-01-01 21:38:21,940 : INFO : > POST http://localhost:7474/db/data/cypher [167]
2018-01-01 21:38:21,944 : INFO : < 200 OK [1483]
2018-01-01 21:38:21,948 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 860, 'rating': '3.8', 'level': 'Advanced', 'name': 'System Validation (3): Requirements by modal formulas'}}
2018-01-01 21:38:21,949 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2018-01-01 21:38:21,954 : INFO : < 200 OK [1486]
2018-01-01 21:38:21,957 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 868, 'rating': '4.5', 'name': 'UI Design Capstone'}}
2018-01-01 21:38:21,959 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2018-01-01 21:38:21,964 : INFO : < 200 OK [1422]
2018-01-01 21:38:21,966 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 235, 'rating': '4.5', 'name': 'Interaction Design Capstone Project'}}
2018-01-01 21:38:21,968 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2018-01-01 21:38:21,973 : INFO : < 200 OK [1439]
2018-01-01 21:38:21,977 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 236, 'rating': '4.5', 'name': 'Game Design Document: Define the Art & Concepts'}}
2018-01-01 21:38:21,979 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:21,983 : INFO : < 200 OK [1451]
2018-01-01 21:38:21,986 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 237, 'rating': '4.7', 'name': 'Introduction to Electronics'}}
2018-01-01 21:38:21,988 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2018-01-01 21:38:21,993 : INFO : < 200 OK [1431]
2018-01-01 21:38:21,998 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 240, 'rating': '4.8', 'level': 'Beginner', 'name': 'Introduction to solar cells'}}
2018-01-01 21:38:22,002 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:22,007 : INFO : < 200 OK [1460]
2018-01-01 21:38:22,010 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 737, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Introduction to Embedded Systems Software and Development Environments'}}
2018-01-01 21:38:22,012 : INFO : > POST http://localhost:7474/db/data/cypher [191]
2018-01-01 21:38:22,017 : INFO : < 200 OK [1507]
2018-01-01 21:38:22,020 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 744, 'rating': '4.6', 'name': 'The Arduino Platform and C Programming'}}
2018-01-01 21:38:22,022 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:22,027 : INFO : < 200 OK [1442]
2018-01-01 21:38:22,031 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 245, 'rating': '4.6', 'name': 'Wind Energy'}}
2018-01-01 21:38:22,033 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2018-01-01 21:38:22,038 : INFO : < 200 OK [1415]
2018-01-01 21:38:22,042 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 248, 'rating': '4.8', 'name': 'Introduction to Power Electronics'}}
2018-01-01 21:38:22,044 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2018-01-01 21:38:22,048 : INFO : < 200 OK [1437]
2018-01-01 21:38:22,051 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 249, 'rating': '4.3', 'name': 'Linear Circuits 1: DC Analysis'}}
2018-01-01 21:38:22,053 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:22,058 : INFO : < 200 OK [1434]
2018-01-01 21:38:22,061 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 250, 'rating': '4.7', 'name': 'Introduction to Systems Engineering'}}
2018-01-01 21:38:22,063 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2018-01-01 21:38:22,068 : INFO : < 200 OK [1439]
2018-01-01 21:38:22,071 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 252, 'rating': '4.6', 'name': 'Fundamentals of Audio and Music Engineering: Part 1 Musical Sound & Electronics'}}
2018-01-01 21:38:22,073 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:22,078 : INFO : < 200 OK [1483]
2018-01-01 21:38:22,081 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 253, 'rating': '4.6', 'name': 'Interfacing with the Arduino'}}
2018-01-01 21:38:22,083 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2018-01-01 21:38:22,088 : INFO : < 200 OK [1432]
2018-01-01 21:38:22,091 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 255, 'rating': '4.2', 'name': 'Internet of Things: How did we get here?'}}
2018-01-01 21:38:22,093 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:22,098 : INFO : < 200 OK [1444]
2018-01-01 21:38:22,102 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 256, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Linear Circuits 2: AC Analysis '}}
2018-01-01 21:38:22,103 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2018-01-01 21:38:22,131 : INFO : < 200 OK [1468]
2018-01-01 21:38:22,134 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 257, 'rating': '4.6', 'level': 'Beginner', 'name': 'Introduction to Satellite Communications'}}
2018-01-01 21:38:22,136 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2018-01-01 21:38:22,141 : INFO : < 200 OK [1473]
2018-01-01 21:38:22,144 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 258, 'rating': '4.6', 'level': 'Beginner', 'name': 'Wireless Communications for Everybody'}}
2018-01-01 21:38:22,146 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:22,150 : INFO : < 200 OK [1470]
2018-01-01 21:38:22,153 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 259, 'rating': '4.6', 'name': 'MOS Transistors'}}
2018-01-01 21:38:22,155 : INFO : > POST http://localhost:7474/db/data/cypher [113]
2018-01-01 21:38:22,159 : INFO : < 200 OK [1419]
2018-01-01 21:38:22,163 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 260, 'rating': '4.8', 'name': 'Converter Circuits'}}
2018-01-01 21:38:22,165 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2018-01-01 21:38:22,169 : INFO : < 200 OK [1422]
2018-01-01 21:38:22,172 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 261, 'level': 'Intermediate', 'name': 'Intro to Acoustics (Part 1)'}}
2018-01-01 21:38:22,173 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2018-01-01 21:38:22,178 : INFO : < 200 OK [1439]
2018-01-01 21:38:22,181 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 398, 'rating': '4.0', 'name': 'Smartphone Emerging Technologies'}}
2018-01-01 21:38:22,183 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:22,188 : INFO : < 200 OK [1436]
2018-01-01 21:38:22,192 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 264, 'name': 'Requirements Writing'}}
2018-01-01 21:38:22,193 : INFO : > POST http://localhost:7474/db/data/cypher [103]
2018-01-01 21:38:22,198 : INFO : < 200 OK [1399]
2018-01-01 21:38:22,201 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 265, 'rating': '4.8', 'name': 'Converter Control'}}
2018-01-01 21:38:22,202 : INFO : > POST http://localhost:7474/db/data/cypher [115]
2018-01-01 21:38:22,207 : INFO : < 200 OK [1421]
2018-01-01 21:38:22,209 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 266, 'rating': '4.3', 'name': 'Internet of Things: Sensing and Actuation From Devices'}}
2018-01-01 21:38:22,211 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2018-01-01 21:38:22,216 : INFO : < 200 OK [1458]

2018-01-01 21:38:22,218 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 268, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Advanced Converter Control Techniques'}}
2018-01-01 21:38:22,220 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:22,225 : INFO : < 200 OK [1474]
2018-01-01 21:38:22,227 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 269, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Magnetics for Power Electronic Converters'}}
2018-01-01 21:38:22,230 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2018-01-01 21:38:22,236 : INFO : < 200 OK [1478]
2018-01-01 21:38:22,239 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 841, 'rating': '4.3', 'name': 'Internet of Things: Multimedia Technologies'}}
2018-01-01 21:38:22,242 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:22,246 : INFO : < 200 OK [1447]
2018-01-01 21:38:22,249 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 271, 'rating': '4.7', 'level': 'Beginner', 'name': 'Personal Leadership Development Planning and Leading High Performing Teams'}}
2018-01-01 21:38:22,251 : INFO : > POST http://localhost:7474/db/data/cypher [191]
2018-01-01 21:38:22,256 : INFO : < 200 OK [1507]
2018-01-01 21:38:22,259 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 854, 'rating': '4.5', 'name': 'Quantitative Formal Modeling and Worst-Case Performance Analysis'}}
2018-01-01 21:38:22,261 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2018-01-01 21:38:22,266 : INFO : < 200 OK [1468]
2018-01-01 21:38:22,269 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 273, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Bioelectricity: A Quantitative Approach'}}
2018-01-01 21:38:22,271 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2018-01-01 21:38:22,275 : INFO : < 200 OK [1476]
2018-01-01 21:38:22,279 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 275, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Bioelectricity:  The Mechanism of Origin of Extracellular Potentials'}}
2018-01-01 21:38:22,281 : INFO : > POST http://localhost:7474/db/data/cypher [189]
2018-01-01 21:38:22,285 : INFO : < 200 OK [1505]
2018-01-01 21:38:22,288 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 869, 'rating': '4.6', 'name': 'Programming for the Internet of Things Project'}}
2018-01-01 21:38:22,290 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:22,295 : INFO : < 200 OK [1450]
2018-01-01 21:38:22,298 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 277, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Capstone Design Project in Power Electronics'}}
2018-01-01 21:38:22,300 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:22,305 : INFO : < 200 OK [1481]
2018-01-01 21:38:22,309 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 278, 'rating': '3.9', 'name': 'Internet of Things Capstone: Build a Mobile Surveillance System'}}
2018-01-01 21:38:22,311 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2018-01-01 21:38:22,315 : INFO : < 200 OK [1467]
2018-01-01 21:38:22,318 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 521, 'rating': '4.5', 'level': 'Beginner', 'name': 'SQL for Data Science'}}
2018-01-01 21:38:22,320 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:22,325 : INFO : < 200 OK [1453]
2018-01-01 21:38:22,327 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 281, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Introduction to Mathematical Thinking'}}
2018-01-01 21:38:22,329 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:22,333 : INFO : < 200 OK [1474]
2018-01-01 21:38:22,336 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 283, 'rating': '4.6', 'level': 'Beginner', 'name': 'Game Theory'}}
2018-01-01 21:38:22,339 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:22,343 : INFO : < 200 OK [1444]
2018-01-01 21:38:22,346 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 530, 'rating': '4.4', 'level': 'Beginner', 'name': 'Data Science Math Skills'}}
2018-01-01 21:38:22,348 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:22,352 : INFO : < 200 OK [1457]
2018-01-01 21:38:22,355 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 286, 'rating': '4.8', 'name': 'Calculus One'}}
2018-01-01 21:38:22,357 : INFO : > POST http://localhost:7474/db/data/cypher [110]
2018-01-01 21:38:22,358 : INFO : < 200 OK [1416]
2018-01-01 21:38:22,362 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 706, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Introduction to Logic'}}
2018-01-01 21:38:22,362 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:22,366 : INFO : < 200 OK [1458]
2018-01-01 21:38:22,370 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 289, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Machine Design Part I'}}
2018-01-01 21:38:22,370 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:22,378 : INFO : < 200 OK [1458]
2018-01-01 21:38:22,378 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 429, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Bayesian Statistics: From Concept to Data Analysis'}}
2018-01-01 21:38:22,382 : INFO : > POST http://localhost:7474/db/data/cypher [171]
2018-01-01 21:38:22,386 : INFO : < 200 OK [1487]
2018-01-01 21:38:22,386 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 291, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Pre-Calculus: Functions'}}
2018-01-01 21:38:22,390 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:22,394 : INFO : < 200 OK [1460]
2018-01-01 21:38:22,398 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 436, 'rating': '4.5', 'name': 'Econometrics: Methods and Applications'}}
2018-01-01 21:38:22,398 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:22,406 : INFO : < 200 OK [1442]
2018-01-01 21:38:22,406 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 293, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Pre-Calculus: Trigonometry'}}
2018-01-01 21:38:22,410 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2018-01-01 21:38:22,414 : INFO : < 200 OK [1463]
2018-01-01 21:38:22,418 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 438, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Bayesian Statistics: Techniques and Models'}}
2018-01-01 21:38:22,418 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2018-01-01 21:38:22,422 : INFO : < 200 OK [1479]
2018-01-01 21:38:22,426 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 296, 'rating': '4.5', 'name': 'Robotics: Aerial Robotics'}}
2018-01-01 21:38:22,426 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2018-01-01 21:38:22,430 : INFO : < 200 OK [1429]
2018-01-01 21:38:22,434 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 298, 'level': 'Beginner', 'name': 'Introduction to Ordinary Differential Equations'}}
2018-01-01 21:38:22,434 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:22,438 : INFO : < 200 OK [1455]
2018-01-01 21:38:22,443 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 300, 'name': 'Calculus: Single Variable Part 1 - Functions'}}
2018-01-01 21:38:22,445 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:22,449 : INFO : < 200 OK [1423]
2018-01-01 21:38:22,452 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 304, 'rating': '4.8', 'name': 'Calculus Two: Sequences and Series'}}
2018-01-01 21:38:22,453 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:22,457 : INFO : < 200 OK [1438]
2018-01-01 21:38:22,459 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 305, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Introduction to Complex Analysis'}}

2018-01-01 21:38:22,459 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:22,463 : INFO : < 200 OK [1469]
2018-01-01 21:38:22,467 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 750, 'rating': '4.7', 'name': 'Image and Video Processing: From Mars to Hollywood with a Stop at the Hospital'}}
2018-01-01 21:38:22,467 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:22,475 : INFO : < 200 OK [1482]
2018-01-01 21:38:22,479 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 309, 'rating': '4.4', 'name': 'Mathematical Biostatistics Boot Camp 1'}}
2018-01-01 21:38:22,479 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:22,483 : INFO : < 200 OK [1442]
2018-01-01 21:38:22,487 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 310, 'rating': '4.7', 'level': 'Advanced', 'name': 'Introduction into General Theory of Relativity'}}
2018-01-01 21:38:22,487 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2018-01-01 21:38:22,491 : INFO : < 200 OK [1479]
2018-01-01 21:38:22,495 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 311, 'rating': '4.7', 'level': 'Advanced', 'name': 'Game Theory II: Advanced Applications'}}
2018-01-01 21:38:22,499 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:22,503 : INFO : < 200 OK [1470]
2018-01-01 21:38:22,503 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 314, 'rating': '4.5', 'level': 'Advanced', 'name': 'Interest Rate Models'}}
2018-01-01 21:38:22,507 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:22,511 : INFO : < 200 OK [1453]
2018-01-01 21:38:22,515 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 315, 'rating': '4.1', 'name': 'Robotics: Computational Motion Planning'}}
2018-01-01 21:38:22,515 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:22,519 : INFO : < 200 OK [1443]
2018-01-01 21:38:22,523 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 451, 'rating': '4.4', 'level': 'Advanced', 'name': 'Advanced Linear Models for Data Science 1: Least Squares'}}
2018-01-01 21:38:22,527 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:38:22,531 : INFO : < 200 OK [1489]
2018-01-01 21:38:22,531 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 317, 'rating': '4.3', 'level': 'Intermediate', 'name': 'Robotics: Perception'}}
2018-01-01 21:38:22,535 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:22,539 : INFO : < 200 OK [1457]
2018-01-01 21:38:22,543 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 318, 'rating': '4.1', 'name': 'Robotics: Estimation and Learning'}}
2018-01-01 21:38:22,546 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2018-01-01 21:38:22,551 : INFO : < 200 OK [1437]
2018-01-01 21:38:22,553 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 319, 'rating': '4.7', 'level': 'Beginner', 'name': 'Fibonacci Numbers and the Golden Ratio'}}
2018-01-01 21:38:22,555 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2018-01-01 21:38:22,558 : INFO : < 200 OK [1471]
2018-01-01 21:38:22,558 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 320, 'name': 'Single Variable Calculus'}}
2018-01-01 21:38:22,563 : INFO : > POST http://localhost:7474/db/data/cypher [107]
2018-01-01 21:38:22,567 : INFO : < 200 OK [1403]
2018-01-01 21:38:22,571 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 621, 'rating': '4.6', 'level': 'Beginner', 'name': 'Julia Scientific Programming'}}
2018-01-01 21:38:22,571 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:22,575 : INFO : < 200 OK [1461]
2018-01-01 21:38:22,579 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 323, 'name': 'Calculus: Single Variable Part 2 - Differentiation'}}
2018-01-01 21:38:22,579 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2018-01-01 21:38:22,583 : INFO : < 200 OK [1429]
2018-01-01 21:38:22,587 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 325, 'rating': '4.3', 'level': 'Advanced', 'name': 'Introduction to Galois Theory'}}
2018-01-01 21:38:22,591 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2018-01-01 21:38:22,595 : INFO : < 200 OK [1462]
2018-01-01 21:38:22,595 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 806, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Basic Modeling for Discrete Optimization'}}
2018-01-01 21:38:22,599 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2018-01-01 21:38:22,603 : INFO : < 200 OK [1477]
2018-01-01 21:38:22,603 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 328, 'name': 'Calculus: Single Variable Part 3 - Integration'}}
2018-01-01 21:38:22,607 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2018-01-01 21:38:22,611 : INFO : < 200 OK [1425]
2018-01-01 21:38:22,615 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 330, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Valuing Companies'}}
2018-01-01 21:38:22,615 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:22,619 : INFO : < 200 OK [1454]
2018-01-01 21:38:22,623 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 331, 'rating': '3.8', 'name': 'Robotics: Mobility'}}
2018-01-01 21:38:22,623 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2018-01-01 21:38:22,627 : INFO : < 200 OK [1422]
2018-01-01 21:38:22,631 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 454, 'rating': '4.6', 'level': 'Advanced', 'name': 'Advanced Linear Models for Data Science 2: Statistical Linear Models'}}
2018-01-01 21:38:22,631 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:38:22,639 : INFO : < 200 OK [1501]
2018-01-01 21:38:22,639 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 333, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Mechanics of Materials III: Beam Bending'}}
2018-01-01 21:38:22,643 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2018-01-01 21:38:22,650 : INFO : < 200 OK [1477]
2018-01-01 21:38:22,653 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 334, 'name': 'Calculus: Single Variable Part 4 - Applications'}}
2018-01-01 21:38:22,655 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:22,659 : INFO : < 200 OK [1426]
2018-01-01 21:38:22,659 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 336, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Introduction to Enumerative Combinatorics'}}
2018-01-01 21:38:22,663 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2018-01-01 21:38:22,667 : INFO : < 200 OK [1478]
2018-01-01 21:38:22,671 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 338, 'level': 'Intermediate', 'name': 'Analytic Combinatorics'}}
2018-01-01 21:38:22,671 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:22,675 : INFO : < 200 OK [1434]
2018-01-01 21:38:22,679 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 834, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Advanced Modeling for Discrete Optimization'}}
2018-01-01 21:38:22,679 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2018-01-01 21:38:22,687 : INFO : < 200 OK [1480]
2018-01-01 21:38:22,687 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 341, 'rating': '4.8', 'level': 'Beginner', 'name': 'Six Sigma Tools for Analyze'}}
2018-01-01 21:38:22,691 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:22,695 : INFO : < 200 OK [1460]
2018-01-01 21:38:22,699 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 342, 'rating': '4.3', 'name': 'Games without Chance: Combinatorial Game Theory '}}
2018-01-01 21:38:22,699 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2018-01-01 21:38:22,703 : INFO : < 200 OK [1452]
2018-01-01 21:38:22,707 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 458, 'rating': '4.1', 'name': 'Mathematical Biostatistics Boot Camp 2'}}

2018-01-01 21:38:22,707 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:22,711 : INFO : < 200 OK [1442]
2018-01-01 21:38:22,715 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 661, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Introduction to Formal Concept Analysis'}}
2018-01-01 21:38:22,719 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2018-01-01 21:38:22,723 : INFO : < 200 OK [1476]
2018-01-01 21:38:22,723 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 347, 'rating': '4.7', 'name': 'Dynamical Modeling Methods for Systems Biology'}}
2018-01-01 21:38:22,727 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:22,731 : INFO : < 200 OK [1450]
2018-01-01 21:38:22,735 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 349, 'rating': '3.7', 'name': 'Quantitative Foundations for International Business'}}
2018-01-01 21:38:22,735 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:22,739 : INFO : < 200 OK [1455]
2018-01-01 21:38:22,744 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 358, 'rating': '4.6', 'name': 'Robotics: Capstone'}}
2018-01-01 21:38:22,746 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2018-01-01 21:38:22,750 : INFO : < 200 OK [1422]
2018-01-01 21:38:22,752 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 359, 'rating': '4.7', 'name': 'Introduction to HTML5'}}
2018-01-01 21:38:22,754 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2018-01-01 21:38:22,758 : INFO : < 200 OK [1425]
2018-01-01 21:38:22,759 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 707, 'rating': '4.3', 'name': 'Build Your First Android App (Project-Centered Course)'}}
2018-01-01 21:38:22,759 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2018-01-01 21:38:22,763 : INFO : < 200 OK [1458]
2018-01-01 21:38:22,767 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 361, 'rating': '4.5', 'level': 'Beginner', 'name': 'Programming Foundations with JavaScript, HTML and CSS'}}
2018-01-01 21:38:22,767 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2018-01-01 21:38:22,775 : INFO : < 200 OK [1486]
2018-01-01 21:38:22,775 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 363, 'rating': '3.3', 'name': 'How To Create a Website in a Weekend! (Project-Centered Course)'}}
2018-01-01 21:38:22,779 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2018-01-01 21:38:22,783 : INFO : < 200 OK [1467]
2018-01-01 21:38:22,783 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 365, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Front-End Web UI Frameworks and Tools: Bootstrap 4'}}
2018-01-01 21:38:22,787 : INFO : > POST http://localhost:7474/db/data/cypher [171]
2018-01-01 21:38:22,791 : INFO : < 200 OK [1487]
2018-01-01 21:38:22,795 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 722, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Programming Languages, Part A'}}
2018-01-01 21:38:22,795 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:22,799 : INFO : < 200 OK [1466]
2018-01-01 21:38:22,803 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 367, 'rating': '4.5', 'level': 'Beginner', 'name': 'Java for Android'}}
2018-01-01 21:38:22,803 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2018-01-01 21:38:22,811 : INFO : < 200 OK [1449]
2018-01-01 21:38:22,811 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 724, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Front-End JavaScript Frameworks: Angular'}}
2018-01-01 21:38:22,815 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2018-01-01 21:38:22,819 : INFO : < 200 OK [1477]
2018-01-01 21:38:22,819 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 370, 'rating': '4.8', 'name': 'Introduction to CSS3'}}
2018-01-01 21:38:22,823 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2018-01-01 21:38:22,827 : INFO : < 200 OK [1424]
2018-01-01 21:38:22,831 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 728, 'rating': '5.0', 'level': 'Intermediate', 'name': 'Server-side Development with NodeJS, Express and MongoDB'}}
2018-01-01 21:38:22,831 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:22,835 : INFO : < 200 OK [1493]
2018-01-01 21:38:22,839 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 372, 'rating': '4.6', 'name': 'Interactivity with JavaScript'}}
2018-01-01 21:38:22,839 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:22,846 : INFO : < 200 OK [1433]
2018-01-01 21:38:22,849 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 373, 'rating': '4.5', 'level': 'Beginner', 'name': 'Introduction to Web Development'}}
2018-01-01 21:38:22,850 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:22,855 : INFO : < 200 OK [1464]
2018-01-01 21:38:22,858 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 739, 'rating': '4.6', 'name': 'Programming Mobile Applications for Android Handheld Systems: Part 1'}}
2018-01-01 21:38:22,859 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2018-01-01 21:38:22,863 : INFO : < 200 OK [1472]
2018-01-01 21:38:22,867 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 741, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Design Patterns'}}
2018-01-01 21:38:22,867 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:22,875 : INFO : < 200 OK [1452]
2018-01-01 21:38:22,879 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 377, 'rating': '4.5', 'name': 'Responsive Website Basics: Code with HTML, CSS, and JavaScript '}}
2018-01-01 21:38:22,879 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2018-01-01 21:38:22,883 : INFO : < 200 OK [1467]
2018-01-01 21:38:22,887 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 378, 'rating': '4.5', 'name': 'Ruby on Rails: An Introduction'}}
2018-01-01 21:38:22,887 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:22,895 : INFO : < 200 OK [1434]
2018-01-01 21:38:22,899 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 754, 'rating': '4.8', 'name': 'Control of Mobile Robots'}}
2018-01-01 21:38:22,899 : INFO : > POST http://localhost:7474/db/data/cypher [122]
2018-01-01 21:38:22,903 : INFO : < 200 OK [1428]
2018-01-01 21:38:22,907 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 380, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Single Page Web Applications with AngularJS'}}
2018-01-01 21:38:22,907 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2018-01-01 21:38:22,915 : INFO : < 200 OK [1480]
2018-01-01 21:38:22,919 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 760, 'rating': '4.2', 'level': 'Intermediate', 'name': 'Service-Oriented Architecture'}}
2018-01-01 21:38:22,919 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:22,923 : INFO : < 200 OK [1466]
2018-01-01 21:38:22,927 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 766, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Software Architecture'}}
2018-01-01 21:38:22,931 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:22,935 : INFO : < 200 OK [1458]
2018-01-01 21:38:22,935 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 385, 'rating': '4.5', 'name': 'Web Application Development: Basic Concepts'}}
2018-01-01 21:38:22,939 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:22,945 : INFO : < 200 OK [1447]
2018-01-01 21:38:22,949 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 775, 'rating': '4.8', 'name': 'Multiplatform Mobile App Development with Web Technologies: Ionic and Cordova'}}
2018-01-01 21:38:22,951 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:22,955 : INFO : < 200 OK [1481]
2018-01-01 21:38:22,959 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 777, 'rating': '4.8', 'level': 'Beginner', 'name': 'Developing Android Apps with App Inventor'}}

2018-01-01 21:38:22,959 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:22,963 : INFO : < 200 OK [1474]
2018-01-01 21:38:22,967 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 388, 'rating': '3.9', 'name': 'Introduction To Swift Programming'}}
2018-01-01 21:38:22,967 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2018-01-01 21:38:22,971 : INFO : < 200 OK [1437]
2018-01-01 21:38:22,975 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 389, 'rating': '4.7', 'name': 'Advanced Styling with Responsive Design'}}
2018-01-01 21:38:22,975 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:22,979 : INFO : < 200 OK [1443]
2018-01-01 21:38:22,983 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 788, 'rating': '4.9', 'name': 'Programming Languages, Part C'}}
2018-01-01 21:38:22,983 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:22,991 : INFO : < 200 OK [1433]
2018-01-01 21:38:22,991 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 391, 'rating': '4.5', 'name': 'Responsive Web Design'}}
2018-01-01 21:38:22,995 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2018-01-01 21:38:23,003 : INFO : < 200 OK [1425]
2018-01-01 21:38:23,003 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 793, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Programming Languages, Part B'}}
2018-01-01 21:38:23,007 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:23,011 : INFO : < 200 OK [1466]
2018-01-01 21:38:23,015 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 393, 'rating': '4.0', 'name': 'Android App Components - Intents, Activities, and Broadcast Receivers'}}
2018-01-01 21:38:23,015 : INFO : > POST http://localhost:7474/db/data/cypher [167]
2018-01-01 21:38:23,019 : INFO : < 200 OK [1473]
2018-01-01 21:38:23,023 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 799, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Multiplatform Mobile App Development with NativeScript'}}
2018-01-01 21:38:23,023 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:23,031 : INFO : < 200 OK [1491]
2018-01-01 21:38:23,035 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 801, 'rating': '4.1', 'level': 'Intermediate', 'name': 'Agile Software Development'}}
2018-01-01 21:38:23,035 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2018-01-01 21:38:23,039 : INFO : < 200 OK [1463]
2018-01-01 21:38:23,045 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 813, 'rating': '4.6', 'name': 'Web Application Development with JavaScript and MongoDB'}}
2018-01-01 21:38:23,047 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:23,051 : INFO : < 200 OK [1459]
2018-01-01 21:38:23,055 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 821, 'rating': '4.3', 'level': 'Beginner', 'name': 'Android App Components - Services, Local IPC, and Content Providers'}}
2018-01-01 21:38:23,056 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:23,061 : INFO : < 200 OK [1500]
2018-01-01 21:38:23,063 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 399, 'rating': '4.7', 'name': 'Programming Mobile Applications for Android Handheld Systems: Part 2'}}
2018-01-01 21:38:23,065 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2018-01-01 21:38:23,070 : INFO : < 200 OK [1472]
2018-01-01 21:38:23,072 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 824, 'rating': '4.3', 'name': 'Engineering Maintainable Android Apps'}}
2018-01-01 21:38:23,074 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2018-01-01 21:38:23,080 : INFO : < 200 OK [1441]
2018-01-01 21:38:23,083 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 828, 'rating': '4.3', 'name': 'Ruby on Rails Web Services and Integration with MongoDB'}}
2018-01-01 21:38:23,085 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:23,089 : INFO : < 200 OK [1459]
2018-01-01 21:38:23,092 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 402, 'rating': '4.6', 'name': 'Introduction to Meteor.js Development  '}}
2018-01-01 21:38:23,093 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:23,098 : INFO : < 200 OK [1443]
2018-01-01 21:38:23,100 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 403, 'rating': '4.2', 'name': 'Responsive Website Tutorial and Examples'}}
2018-01-01 21:38:23,102 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:23,107 : INFO : < 200 OK [1444]
2018-01-01 21:38:23,110 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 404, 'rating': '4.2', 'name': 'iOS App Development Basics'}}
2018-01-01 21:38:23,112 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2018-01-01 21:38:23,116 : INFO : < 200 OK [1430]
2018-01-01 21:38:23,119 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 837, 'rating': '4.7', 'name': 'Rails with Active Record and Action Pack'}}
2018-01-01 21:38:23,121 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:23,125 : INFO : < 200 OK [1444]
2018-01-01 21:38:23,128 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 406, 'rating': '4.7', 'name': 'Foundations of Objective-C App Development'}}
2018-01-01 21:38:23,129 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2018-01-01 21:38:23,134 : INFO : < 200 OK [1446]
2018-01-01 21:38:23,137 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 407, 'rating': '4.2', 'name': 'CODAPPS: Coding mobile apps for entrepreneurs'}}
2018-01-01 21:38:23,139 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2018-01-01 21:38:23,143 : INFO : < 200 OK [1449]
2018-01-01 21:38:23,145 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 840, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Getting Started With Application Development'}}
2018-01-01 21:38:23,147 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:23,151 : INFO : < 200 OK [1481]
2018-01-01 21:38:23,154 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 409, 'rating': '4.1', 'name': 'App Design and Development for iOS'}}
2018-01-01 21:38:23,156 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:23,161 : INFO : < 200 OK [1438]
2018-01-01 21:38:23,164 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 410, 'rating': '4.6', 'name': 'Best Practices for iOS User Interface Design'}}
2018-01-01 21:38:23,166 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:23,171 : INFO : < 200 OK [1448]
2018-01-01 21:38:23,173 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 411, 'rating': '3.8', 'name': 'Toward the Future of iOS Development with Swift'}}
2018-01-01 21:38:23,175 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:23,180 : INFO : < 200 OK [1451]
2018-01-01 21:38:23,183 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 864, 'rating': '4.3', 'name': 'Interfaz de usuario en iOS'}}
2018-01-01 21:38:23,185 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2018-01-01 21:38:23,190 : INFO : < 200 OK [1430]
2018-01-01 21:38:23,194 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 865, 'rating': '4.7', 'name': 'Interactuando con el hardware del dispositivo iOS'}}
2018-01-01 21:38:23,195 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2018-01-01 21:38:23,200 : INFO : < 200 OK [1453]
2018-01-01 21:38:23,202 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 870, 'rating': '4.1', 'name': 'Capstone MOOC for "Android App Development"'}}
2018-01-01 21:38:23,204 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2018-01-01 21:38:23,211 : INFO : < 200 OK [1449]
2018-01-01 21:38:23,213 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 416, 'rating': '4.7', 'name': 'Capstone: Photo Tourist Web Application'}}

2018-01-01 21:38:23,215 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:23,222 : INFO : < 200 OK [1443]
2018-01-01 21:38:23,226 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 417, 'rating': '4.9', 'name': 'iOS Project: Transreality Game'}}
2018-01-01 21:38:23,228 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:23,233 : INFO : < 200 OK [1434]
2018-01-01 21:38:23,236 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 418, 'rating': '4.7', 'name': 'Web Design for Everybody Capstone'}}
2018-01-01 21:38:23,238 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2018-01-01 21:38:23,243 : INFO : < 200 OK [1437]
2018-01-01 21:38:23,245 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 419, 'rating': '4.8', 'name': 'Responsive Website Development and Design Capstone '}}
2018-01-01 21:38:23,247 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:23,252 : INFO : < 200 OK [1455]
2018-01-01 21:38:23,255 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 420, 'rating': '2.8', 'name': 'Build Your Own iOS App'}}
2018-01-01 21:38:23,257 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2018-01-01 21:38:23,261 : INFO : < 200 OK [1426]
2018-01-01 21:38:23,264 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 421, 'rating': '4.2', 'level': 'Intermediate', 'name': 'Getting started with Augmented Reality'}}
2018-01-01 21:38:23,266 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2018-01-01 21:38:23,271 : INFO : < 200 OK [1475]
2018-01-01 21:38:23,275 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 524, 'rating': '4.5', 'level': 'Intermediate', 'name': 'R Programming'}}
2018-01-01 21:38:23,277 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:23,281 : INFO : < 200 OK [1450]
2018-01-01 21:38:23,284 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 528, 'rating': '4.7', 'level': 'Beginner', 'name': 'Introduction to Probability and Data'}}
2018-01-01 21:38:23,287 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:23,291 : INFO : < 200 OK [1469]
2018-01-01 21:38:23,294 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 539, 'rating': '4.5', 'name': 'Getting and Cleaning Data'}}
2018-01-01 21:38:23,297 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2018-01-01 21:38:23,301 : INFO : < 200 OK [1429]
2018-01-01 21:38:23,305 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 431, 'rating': '4.7', 'level': 'Beginner', 'name': 'Basic Statistics'}}
2018-01-01 21:38:23,307 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2018-01-01 21:38:23,311 : INFO : < 200 OK [1449]
2018-01-01 21:38:23,315 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 551, 'rating': '4.6', 'name': 'Exploratory Data Analysis'}}
2018-01-01 21:38:23,316 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2018-01-01 21:38:23,321 : INFO : < 200 OK [1429]
2018-01-01 21:38:23,325 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 553, 'rating': '4.4', 'name': 'Regression Models'}}
2018-01-01 21:38:23,327 : INFO : > POST http://localhost:7474/db/data/cypher [115]
2018-01-01 21:38:23,331 : INFO : < 200 OK [1421]
2018-01-01 21:38:23,335 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 555, 'rating': '4.1', 'name': 'Statistical Inference'}}
2018-01-01 21:38:23,336 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2018-01-01 21:38:23,341 : INFO : < 200 OK [1425]
2018-01-01 21:38:23,344 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 483, 'rating': '4.8', 'name': 'Machine Learning: Regression'}}
2018-01-01 21:38:23,346 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2018-01-01 21:38:23,351 : INFO : < 200 OK [1432]
2018-01-01 21:38:23,353 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 558, 'rating': '4.8', 'level': 'Beginner', 'name': 'Inferential Statistics'}}
2018-01-01 21:38:23,355 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:23,360 : INFO : < 200 OK [1455]
2018-01-01 21:38:23,362 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 562, 'rating': '4.4', 'name': 'Data Visualization'}}
2018-01-01 21:38:23,364 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2018-01-01 21:38:23,369 : INFO : < 200 OK [1422]
2018-01-01 21:38:23,371 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 564, 'rating': '3.8', 'level': 'Intermediate', 'name': 'Bayesian Statistics'}}
2018-01-01 21:38:23,373 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2018-01-01 21:38:23,379 : INFO : < 200 OK [1456]
2018-01-01 21:38:23,381 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 566, 'rating': '4.7', 'level': 'Beginner', 'name': 'Linear Regression and Modeling '}}
2018-01-01 21:38:23,383 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:23,389 : INFO : < 200 OK [1464]
2018-01-01 21:38:23,391 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 572, 'rating': '4.5', 'name': 'Reproducible Research'}}
2018-01-01 21:38:23,393 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2018-01-01 21:38:23,397 : INFO : < 200 OK [1425]
2018-01-01 21:38:23,401 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 443, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Improving your statistical inferences'}}
2018-01-01 21:38:23,402 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:23,407 : INFO : < 200 OK [1474]
2018-01-01 21:38:23,410 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 444, 'rating': '4.7', 'name': 'Understanding Clinical Research: Behind the Statistics'}}
2018-01-01 21:38:23,412 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2018-01-01 21:38:23,416 : INFO : < 200 OK [1458]
2018-01-01 21:38:23,419 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 575, 'rating': '4.5', 'name': 'Developing Data Products'}}
2018-01-01 21:38:23,421 : INFO : > POST http://localhost:7474/db/data/cypher [122]
2018-01-01 21:38:23,425 : INFO : < 200 OK [1428]
2018-01-01 21:38:23,428 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 446, 'rating': '4.8', 'name': 'Statistical Reasoning for Public Health 1: Estimation, Inference, & Interpretation'}}
2018-01-01 21:38:23,430 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:38:23,434 : INFO : < 200 OK [1486]
2018-01-01 21:38:23,438 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 447, 'rating': '4.8', 'level': 'Beginner', 'name': 'An Intuitive Introduction to Probability'}}
2018-01-01 21:38:23,440 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2018-01-01 21:38:23,445 : INFO : < 200 OK [1473]
2018-01-01 21:38:23,447 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 602, 'rating': '4.9', 'level': 'Intermediate', 'name': 'A Crash Course in Causality:  Inferring Causal Effects from Observational Data'}}
2018-01-01 21:38:23,449 : INFO : > POST http://localhost:7474/db/data/cypher [199]
2018-01-01 21:38:23,453 : INFO : < 200 OK [1515]
2018-01-01 21:38:23,457 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 614, 'rating': '4.4', 'name': 'Inferential Statistics'}}
2018-01-01 21:38:23,460 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2018-01-01 21:38:23,465 : INFO : < 200 OK [1426]
2018-01-01 21:38:23,468 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 450, 'rating': '4.7', 'name': 'Statistical Reasoning for Public Health 2: Regression Methods'}}
2018-01-01 21:38:23,470 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2018-01-01 21:38:23,475 : INFO : < 200 OK [1465]
2018-01-01 21:38:23,479 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 452, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Experimentation for Improvement'}}
2018-01-01 21:38:23,480 : INFO : > POST http://localhost:7474/db/data/cypher [152]

2018-01-01 21:38:23,485 : INFO : < 200 OK [1468]
2018-01-01 21:38:23,488 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 638, 'rating': '4.3', 'name': 'Regression Modeling in Practice'}}
2018-01-01 21:38:23,490 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2018-01-01 21:38:23,495 : INFO : < 200 OK [1435]
2018-01-01 21:38:23,498 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 455, 'rating': '4.1', 'name': 'Statistics for Genomic Data Science'}}
2018-01-01 21:38:23,500 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2018-01-01 21:38:23,505 : INFO : < 200 OK [1439]
2018-01-01 21:38:23,507 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 456, 'rating': '4.0', 'name': 'Measuring Causal Effects in the Social Sciences'}}
2018-01-01 21:38:23,509 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:23,514 : INFO : < 200 OK [1451]
2018-01-01 21:38:23,518 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 654, 'level': 'Beginner', 'name': 'Data Science Ethics'}}
2018-01-01 21:38:23,520 : INFO : > POST http://localhost:7474/db/data/cypher [121]
2018-01-01 21:38:23,525 : INFO : < 200 OK [1427]
2018-01-01 21:38:23,531 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 459, 'rating': '4.7', 'level': 'Beginner', 'name': 'Exploring and Producing Data for Business Decision Making'}}
2018-01-01 21:38:23,533 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:38:23,537 : INFO : < 200 OK [1490]
2018-01-01 21:38:23,541 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 460, 'rating': '4.2', 'level': 'Beginner', 'name': 'Science Literacy - How Solid Science Can Help You Save the World'}}
2018-01-01 21:38:23,543 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:23,548 : INFO : < 200 OK [1497]
2018-01-01 21:38:23,551 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 680, 'rating': '4.7', 'name': 'Statistics with R Capstone'}}
2018-01-01 21:38:23,553 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2018-01-01 21:38:23,558 : INFO : < 200 OK [1430]
2018-01-01 21:38:23,561 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 470, 'rating': '4.9', 'name': 'Machine Learning'}}
2018-01-01 21:38:23,563 : INFO : > POST http://localhost:7474/db/data/cypher [114]
2018-01-01 21:38:23,567 : INFO : < 200 OK [1420]
2018-01-01 21:38:23,570 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 520, 'rating': '4.8', 'level': 'Beginner', 'name': 'Structuring Machine Learning Projects'}}
2018-01-01 21:38:23,572 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:23,577 : INFO : < 200 OK [1470]
2018-01-01 21:38:23,580 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 523, 'rating': '4.6', 'name': 'Neural Networks for Machine Learning'}}
2018-01-01 21:38:23,582 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:23,587 : INFO : < 200 OK [1440]
2018-01-01 21:38:23,589 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 477, 'rating': '4.3', 'level': 'Advanced', 'name': 'Introduction to Deep Learning'}}
2018-01-01 21:38:23,592 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2018-01-01 21:38:23,596 : INFO : < 200 OK [1462]
2018-01-01 21:38:23,599 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 478, 'rating': '4.6', 'name': 'Machine Learning Foundations: A Case Study Approach'}}
2018-01-01 21:38:23,601 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:23,606 : INFO : < 200 OK [1455]
2018-01-01 21:38:23,609 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 532, 'rating': '4.8', 'level': 'Advanced', 'name': 'How to Win a Data Science Competition: Learn from Top Kagglers'}}
2018-01-01 21:38:23,611 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2018-01-01 21:38:23,618 : INFO : < 200 OK [1495]
2018-01-01 21:38:23,621 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 480, 'rating': '4.4', 'level': 'Advanced', 'name': 'Bayesian Methods for Machine Learning'}}
2018-01-01 21:38:23,623 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:23,628 : INFO : < 200 OK [1470]
2018-01-01 21:38:23,630 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 549, 'rating': '4.4', 'name': 'Practical Machine Learning'}}
2018-01-01 21:38:23,632 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2018-01-01 21:38:23,637 : INFO : < 200 OK [1430]
2018-01-01 21:38:23,640 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 482, 'rating': '4.6', 'level': 'Beginner', 'name': 'Computational Neuroscience'}}
2018-01-01 21:38:23,642 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2018-01-01 21:38:23,646 : INFO : < 200 OK [1459]
2018-01-01 21:38:23,650 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 485, 'rating': '4.7', 'name': 'Machine Learning: Classification'}}
2018-01-01 21:38:23,652 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:23,657 : INFO : < 200 OK [1436]
2018-01-01 21:38:23,659 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 733, 'rating': '4.7', 'level': 'Beginner', 'name': 'The Unix Workbench'}}
2018-01-01 21:38:23,662 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2018-01-01 21:38:23,666 : INFO : < 200 OK [1451]
2018-01-01 21:38:23,669 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 738, 'rating': '4.5', 'level': 'Beginner', 'name': "A developer's guide to the Internet of Things (IoT)"}}
2018-01-01 21:38:23,671 : INFO : > POST http://localhost:7474/db/data/cypher [168]
2018-01-01 21:38:23,676 : INFO : < 200 OK [1484]
2018-01-01 21:38:23,679 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 488, 'rating': '4.4', 'level': 'Beginner', 'name': 'Deep Learning for Business'}}
2018-01-01 21:38:23,681 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2018-01-01 21:38:23,685 : INFO : < 200 OK [1459]
2018-01-01 21:38:23,689 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 568, 'rating': '4.6', 'name': 'Machine Learning: Clustering & Retrieval'}}
2018-01-01 21:38:23,691 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:23,695 : INFO : < 200 OK [1444]
2018-01-01 21:38:23,699 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 570, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Google Cloud Platform Big Data and Machine Learning Fundamentals'}}
2018-01-01 21:38:23,701 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:38:23,706 : INFO : < 200 OK [1501]
2018-01-01 21:38:23,709 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 491, 'rating': '4.5', 'name': 'Machine Learning With Big Data'}}
2018-01-01 21:38:23,712 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:23,716 : INFO : < 200 OK [1434]
2018-01-01 21:38:23,719 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 577, 'rating': '4.4', 'name': 'Text Mining and Analytics'}}
2018-01-01 21:38:23,722 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2018-01-01 21:38:23,727 : INFO : < 200 OK [1429]
2018-01-01 21:38:23,730 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 765, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Serverless Machine Learning with Tensorflow on Google Cloud Platform'}}
2018-01-01 21:38:23,732 : INFO : > POST http://localhost:7474/db/data/cypher [189]
2018-01-01 21:38:23,737 : INFO : < 200 OK [1505]
2018-01-01 21:38:23,740 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 494, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Introduction to Recommender Systems:  Non-Personalized and Content-Based'}}
2018-01-01 21:38:23,742 : INFO : > POST http://localhost:7474/db/data/cypher [193]
2018-01-01 21:38:23,746 : INFO : < 200 OK [1509]
2018-01-01 21:38:23,749 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 589, 'rating': '4.4', 'name': 'Text Retrieval and Search Engines'}}

2018-01-01 21:38:23,750 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2018-01-01 21:38:23,755 : INFO : < 200 OK [1437]
2018-01-01 21:38:23,758 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 600, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Leveraging Unstructured Data with Cloud Dataproc on Google Cloud Platform'}}
2018-01-01 21:38:23,760 : INFO : > POST http://localhost:7474/db/data/cypher [194]
2018-01-01 21:38:23,764 : INFO : < 200 OK [1510]
2018-01-01 21:38:23,767 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 778, 'rating': '3.7', 'level': 'Advanced', 'name': 'Big Data Applications: Machine Learning at Scale'}}
2018-01-01 21:38:23,769 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:23,774 : INFO : < 200 OK [1481]
2018-01-01 21:38:23,777 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 613, 'rating': '4.0', 'level': 'Intermediate', 'name': 'Social Media Data Analytics'}}
2018-01-01 21:38:23,779 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:23,783 : INFO : < 200 OK [1464]
2018-01-01 21:38:23,786 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 612, 'rating': '4.1', 'name': 'Machine Learning for Data Analysis'}}
2018-01-01 21:38:23,789 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:23,793 : INFO : < 200 OK [1438]
2018-01-01 21:38:23,797 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 503, 'rating': '4.2', 'name': 'Matrix Factorization and Advanced Techniques'}}
2018-01-01 21:38:23,799 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:23,804 : INFO : < 200 OK [1448]
2018-01-01 21:38:23,806 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 504, 'rating': '4.5', 'level': 'Beginner', 'name': 'Digital Manufacturing & Design'}}
2018-01-01 21:38:23,808 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2018-01-01 21:38:23,813 : INFO : < 200 OK [1463]
2018-01-01 21:38:23,816 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 505, 'rating': '4.3', 'name': 'Nearest Neighbor Collaborative Filtering'}}
2018-01-01 21:38:23,817 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:23,821 : INFO : < 200 OK [1444]
2018-01-01 21:38:23,825 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 506, 'rating': '4.2', 'name': 'Recommender Systems:  Evaluation and Metrics'}}
2018-01-01 21:38:23,825 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:23,833 : INFO : < 200 OK [1448]
2018-01-01 21:38:23,837 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 649, 'rating': '4.4', 'name': 'Data Science Capstone'}}
2018-01-01 21:38:23,841 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2018-01-01 21:38:23,845 : INFO : < 200 OK [1425]
2018-01-01 21:38:23,845 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 508, 'rating': '4.5', 'level': 'Beginner', 'name': 'Intelligent Machining'}}
2018-01-01 21:38:23,849 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:23,853 : INFO : < 200 OK [1454]
2018-01-01 21:38:23,853 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 509, 'rating': '4.7', 'level': 'Beginner', 'name': 'MBSE: Model-Based Systems Engineering '}}
2018-01-01 21:38:23,857 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2018-01-01 21:38:23,861 : INFO : < 200 OK [1471]
2018-01-01 21:38:23,865 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 510, 'rating': '4.3', 'level': 'Beginner', 'name': 'Advanced Manufacturing Process Analysis'}}
2018-01-01 21:38:23,865 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2018-01-01 21:38:23,869 : INFO : < 200 OK [1472]
2018-01-01 21:38:23,873 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 511, 'rating': '4.5', 'level': 'Beginner', 'name': 'Digital Thread: Components'}}
2018-01-01 21:38:23,873 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2018-01-01 21:38:23,881 : INFO : < 200 OK [1459]
2018-01-01 21:38:23,881 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 512, 'rating': '4.6', 'level': 'Beginner', 'name': 'Digital Thread: Implementation'}}
2018-01-01 21:38:23,885 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2018-01-01 21:38:23,889 : INFO : < 200 OK [1463]
2018-01-01 21:38:23,893 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 513, 'rating': '4.2', 'level': 'Beginner', 'name': 'Advanced Manufacturing Enterprise'}}
2018-01-01 21:38:23,893 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:23,897 : INFO : < 200 OK [1466]
2018-01-01 21:38:23,901 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 514, 'level': 'Beginner', 'name': 'Roadmap to Success in Digital Manufacturing & Design '}}
2018-01-01 21:38:23,901 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2018-01-01 21:38:23,908 : INFO : < 200 OK [1461]
2018-01-01 21:38:23,911 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 515, 'rating': '4.6', 'level': 'Beginner', 'name': 'Cyber Security in Manufacturing  '}}
2018-01-01 21:38:23,912 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:23,917 : INFO : < 200 OK [1466]
2018-01-01 21:38:23,919 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 516, 'rating': '3.9', 'level': 'Beginner', 'name': 'Digital Manufacturing Commons (opendmc.org)'}}
2018-01-01 21:38:23,921 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2018-01-01 21:38:23,925 : INFO : < 200 OK [1476]
2018-01-01 21:38:23,925 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 862, 'level': 'Advanced', 'name': 'Big Data Services: Capstone Project'}}
2018-01-01 21:38:23,929 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:23,933 : INFO : < 200 OK [1443]
2018-01-01 21:38:23,937 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 518, 'name': 'Recommender Systems Capstone'}}
2018-01-01 21:38:23,937 : INFO : > POST http://localhost:7474/db/data/cypher [111]
2018-01-01 21:38:23,945 : INFO : < 200 OK [1407]
2018-01-01 21:38:23,945 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 700, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Introduction to Data Science in Python'}}
2018-01-01 21:38:23,949 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2018-01-01 21:38:23,953 : INFO : < 200 OK [1475]
2018-01-01 21:38:23,957 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 702, 'rating': '4.8', 'name': 'Python Data Structures'}}
2018-01-01 21:38:23,957 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2018-01-01 21:38:23,961 : INFO : < 200 OK [1426]
2018-01-01 21:38:23,965 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 526, 'rating': '4.4', 'name': 'A Crash Course in Data Science'}}
2018-01-01 21:38:23,965 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:23,973 : INFO : < 200 OK [1434]
2018-01-01 21:38:23,973 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 527, 'rating': '4.6', 'level': 'Beginner', 'name': 'Data-driven Decision Making'}}
2018-01-01 21:38:23,977 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:23,981 : INFO : < 200 OK [1460]
2018-01-01 21:38:23,981 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 529, 'rating': '4.5', 'name': 'Introduction to Big Data'}}
2018-01-01 21:38:23,985 : INFO : > POST http://localhost:7474/db/data/cypher [122]
2018-01-01 21:38:23,989 : INFO : < 200 OK [1428]
2018-01-01 21:38:23,993 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 531, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Applied Machine Learning in Python'}}
2018-01-01 21:38:23,993 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2018-01-01 21:38:23,997 : INFO : < 200 OK [1471]

2018-01-01 21:38:24,001 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 533, 'rating': '4.9', 'level': 'Beginner', 'name': 'Excel Skills for Business: Essentials'}}
2018-01-01 21:38:24,007 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:24,012 : INFO : < 200 OK [1470]
2018-01-01 21:38:24,014 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 709, 'rating': '4.8', 'name': 'Using Databases with Python'}}
2018-01-01 21:38:24,016 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2018-01-01 21:38:24,021 : INFO : < 200 OK [1431]
2018-01-01 21:38:24,022 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 536, 'rating': '4.7', 'level': 'Beginner', 'name': 'Problem Solving with Excel '}}
2018-01-01 21:38:24,022 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:24,030 : INFO : < 200 OK [1460]
2018-01-01 21:38:24,030 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 713, 'rating': '4.4', 'level': 'Intermediate', 'name': 'The R Programming Environment'}}
2018-01-01 21:38:24,034 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:24,038 : INFO : < 200 OK [1466]
2018-01-01 21:38:24,038 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 538, 'rating': '4.7', 'name': 'Data Visualization and Communication with Tableau'}}
2018-01-01 21:38:24,042 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2018-01-01 21:38:24,046 : INFO : < 200 OK [1453]
2018-01-01 21:38:24,050 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 540, 'rating': '4.5', 'name': 'Business Metrics for Data-Driven Companies'}}
2018-01-01 21:38:24,050 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2018-01-01 21:38:24,054 : INFO : < 200 OK [1446]
2018-01-01 21:38:24,058 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 717, 'rating': '4.0', 'level': 'Intermediate', 'name': 'Applied Text Mining in Python'}}
2018-01-01 21:38:24,058 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:24,062 : INFO : < 200 OK [1466]
2018-01-01 21:38:24,066 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 718, 'rating': '4.7', 'level': 'Beginner', 'name': 'Python Programming Essentials'}}
2018-01-01 21:38:24,066 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2018-01-01 21:38:24,074 : INFO : < 200 OK [1462]
2018-01-01 21:38:24,074 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 543, 'rating': '4.7', 'name': 'Introduction to Data Analysis Using Excel'}}
2018-01-01 21:38:24,074 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:24,082 : INFO : < 200 OK [1445]
2018-01-01 21:38:24,082 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 544, 'rating': '4.6', 'name': 'Fundamentals of Quantitative Modeling'}}
2018-01-01 21:38:24,086 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2018-01-01 21:38:24,090 : INFO : < 200 OK [1441]
2018-01-01 21:38:24,090 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 545, 'name': 'Customer Analytics'}}
2018-01-01 21:38:24,094 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2018-01-01 21:38:24,098 : INFO : < 200 OK [1397]
2018-01-01 21:38:24,098 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 720, 'rating': '4.1', 'level': 'Intermediate', 'name': 'Big Data Essentials: HDFS, MapReduce and Spark RDD'}}
2018-01-01 21:38:24,102 : INFO : > POST http://localhost:7474/db/data/cypher [171]
2018-01-01 21:38:24,107 : INFO : < 200 OK [1487]
2018-01-01 21:38:24,110 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 547, 'rating': '4.2', 'name': 'Mastering Data Analysis in Excel'}}
2018-01-01 21:38:24,112 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:24,116 : INFO : < 200 OK [1436]
2018-01-01 21:38:24,118 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 721, 'rating': '4.6', 'name': 'Capstone: Retrieving, Processing, and Visualizing Data with Python'}}
2018-01-01 21:38:24,119 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2018-01-01 21:38:24,122 : INFO : < 200 OK [1470]
2018-01-01 21:38:24,126 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 550, 'rating': '4.7', 'name': 'Managing Big Data with MySQL'}}
2018-01-01 21:38:24,126 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2018-01-01 21:38:24,130 : INFO : < 200 OK [1432]
2018-01-01 21:38:24,134 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 552, 'rating': '4.8', 'level': 'Beginner', 'name': 'Data Visualization with Advanced Excel'}}
2018-01-01 21:38:24,134 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2018-01-01 21:38:24,138 : INFO : < 200 OK [1471]
2018-01-01 21:38:24,142 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 554, 'rating': '4.4', 'level': 'Beginner', 'name': 'Fundamentals of Visualization with Tableau'}}
2018-01-01 21:38:24,142 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2018-01-01 21:38:24,146 : INFO : < 200 OK [1475]
2018-01-01 21:38:24,150 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 556, 'rating': '4.5', 'level': 'Beginner', 'name': 'Effective Business Presentations with Powerpoint'}}
2018-01-01 21:38:24,150 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:24,154 : INFO : < 200 OK [1481]
2018-01-01 21:38:24,158 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 557, 'rating': '4.5', 'level': 'Beginner', 'name': 'Marketing Analytics'}}
2018-01-01 21:38:24,158 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:24,162 : INFO : < 200 OK [1452]
2018-01-01 21:38:24,166 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 729, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Applied Social Network Analysis in Python'}}
2018-01-01 21:38:24,166 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2018-01-01 21:38:24,170 : INFO : < 200 OK [1478]
2018-01-01 21:38:24,170 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 560, 'name': 'Hadoop Platform and Application Framework'}}
2018-01-01 21:38:24,174 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2018-01-01 21:38:24,178 : INFO : < 200 OK [1420]
2018-01-01 21:38:24,182 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 732, 'rating': '4.6', 'name': 'Database Management Essentials'}}
2018-01-01 21:38:24,182 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2018-01-01 21:38:24,186 : INFO : < 200 OK [1434]
2018-01-01 21:38:24,190 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 563, 'rating': '4.6', 'name': 'Introduction to Search Engine Optimization'}}
2018-01-01 21:38:24,190 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2018-01-01 21:38:24,198 : INFO : < 200 OK [1446]
2018-01-01 21:38:24,198 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 565, 'rating': '4.2', 'name': 'Introduction to Spreadsheets and Models'}}
2018-01-01 21:38:24,198 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:24,206 : INFO : < 200 OK [1443]
2018-01-01 21:38:24,208 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 567, 'rating': '4.3', 'name': 'Big Data Modeling and Management Systems'}}
2018-01-01 21:38:24,210 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:24,214 : INFO : < 200 OK [1444]
2018-01-01 21:38:24,218 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 569, 'rating': '5.0', 'level': 'Intermediate', 'name': 'Excel Skills for Business: Intermediate I'}}
2018-01-01 21:38:24,221 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2018-01-01 21:38:24,226 : INFO : < 200 OK [1478]
2018-01-01 21:38:24,230 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 571, 'name': 'People Analytics'}}
2018-01-01 21:38:24,230 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2018-01-01 21:38:24,238 : INFO : < 200 OK [1395]
2018-01-01 21:38:24,242 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 573, 'name': 'Operations Analytics'}}

2018-01-01 21:38:24,242 : INFO : > POST http://localhost:7474/db/data/cypher [103]
2018-01-01 21:38:24,250 : INFO : < 200 OK [1399]
2018-01-01 21:38:24,250 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 574, 'level': 'Intermediate', 'name': 'Excel Skills for Business: Advanced'}}
2018-01-01 21:38:24,254 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:24,258 : INFO : < 200 OK [1447]
2018-01-01 21:38:24,262 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 576, 'rating': '4.4', 'level': 'Beginner', 'name': 'Big Data Integration and Processing'}}
2018-01-01 21:38:24,262 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2018-01-01 21:38:24,266 : INFO : < 200 OK [1468]
2018-01-01 21:38:24,270 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 748, 'rating': '4.3', 'level': 'Beginner', 'name': 'Data Processing Using Python'}}
2018-01-01 21:38:24,270 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:24,274 : INFO : < 200 OK [1461]
2018-01-01 21:38:24,278 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 749, 'rating': '3.9', 'level': 'Advanced', 'name': 'Big Data Analysis: Hive, Spark SQL, DataFrames and GraphFrames'}}
2018-01-01 21:38:24,278 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2018-01-01 21:38:24,286 : INFO : < 200 OK [1495]
2018-01-01 21:38:24,290 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 580, 'rating': '4.5', 'name': 'Managing Data Analysis'}}
2018-01-01 21:38:24,290 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2018-01-01 21:38:24,294 : INFO : < 200 OK [1426]
2018-01-01 21:38:24,298 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 581, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Excel Skills for Business: Intermediate II'}}
2018-01-01 21:38:24,298 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2018-01-01 21:38:24,302 : INFO : < 200 OK [1479]
2018-01-01 21:38:24,308 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 582, 'rating': '4.8', 'level': 'Advanced', 'name': 'Social and Economic Networks:  Models and Analysis'}}
2018-01-01 21:38:24,310 : INFO : > POST http://localhost:7474/db/data/cypher [167]
2018-01-01 21:38:24,315 : INFO : < 200 OK [1483]
2018-01-01 21:38:24,318 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 583, 'rating': '4.5', 'name': 'Accounting Analytics'}}
2018-01-01 21:38:24,321 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2018-01-01 21:38:24,322 : INFO : < 200 OK [1424]
2018-01-01 21:38:24,326 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 584, 'rating': '4.7', 'level': 'Beginner', 'name': 'Data Management for Clinical Research'}}
2018-01-01 21:38:24,326 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:24,330 : INFO : < 200 OK [1470]
2018-01-01 21:38:24,334 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 761, 'rating': '4.8', 'level': 'Beginner', 'name': 'Python Data Visualization'}}
2018-01-01 21:38:24,338 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:24,342 : INFO : < 200 OK [1458]
2018-01-01 21:38:24,342 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 587, 'rating': '4.6', 'name': 'Modeling Risk and Realities'}}
2018-01-01 21:38:24,346 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2018-01-01 21:38:24,350 : INFO : < 200 OK [1431]
2018-01-01 21:38:24,354 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 762, 'rating': '4.8', 'level': 'Beginner', 'name': 'Python Data Analysis'}}
2018-01-01 21:38:24,354 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:24,362 : INFO : < 200 OK [1453]
2018-01-01 21:38:24,362 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 590, 'rating': '4.1', 'name': 'Graph Analytics for Big Data'}}
2018-01-01 21:38:24,366 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2018-01-01 21:38:24,370 : INFO : < 200 OK [1432]
2018-01-01 21:38:24,370 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 591, 'rating': '4.6', 'name': 'Introduction to Data Analytics for Business'}}
2018-01-01 21:38:24,374 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:24,378 : INFO : < 200 OK [1447]
2018-01-01 21:38:24,382 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 592, 'rating': '4.4', 'level': 'Beginner', 'name': 'Essential Design Principles for Tableau'}}
2018-01-01 21:38:24,382 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2018-01-01 21:38:24,386 : INFO : < 200 OK [1472]
2018-01-01 21:38:24,390 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 593, 'rating': '4.4', 'name': 'Digital Analytics for Marketing Professionals: Marketing Analytics in Practice'}}
2018-01-01 21:38:24,390 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:24,394 : INFO : < 200 OK [1482]
2018-01-01 21:38:24,398 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 770, 'rating': '4.3', 'name': 'Data Manipulation at Scale: Systems and Algorithms'}}
2018-01-01 21:38:24,398 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:24,406 : INFO : < 200 OK [1454]
2018-01-01 21:38:24,409 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 771, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Advanced R Programming'}}
2018-01-01 21:38:24,412 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2018-01-01 21:38:24,416 : INFO : < 200 OK [1459]
2018-01-01 21:38:24,419 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 596, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Process Mining: Data science in Action'}}
2018-01-01 21:38:24,421 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2018-01-01 21:38:24,422 : INFO : < 200 OK [1475]
2018-01-01 21:38:24,426 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 597, 'rating': '4.5', 'name': 'Building a Data Science Team'}}
2018-01-01 21:38:24,426 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2018-01-01 21:38:24,430 : INFO : < 200 OK [1432]
2018-01-01 21:38:24,434 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 598, 'rating': '4.4', 'name': 'Data Management and Visualization'}}
2018-01-01 21:38:24,438 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2018-01-01 21:38:24,442 : INFO : < 200 OK [1437]
2018-01-01 21:38:24,442 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 599, 'rating': '4.4', 'name': 'Data Science in Real Life'}}
2018-01-01 21:38:24,446 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2018-01-01 21:38:24,450 : INFO : < 200 OK [1429]
2018-01-01 21:38:24,454 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 601, 'rating': '4.7', 'name': 'Forensic Accounting and Fraud Examination'}}
2018-01-01 21:38:24,454 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:24,462 : INFO : < 200 OK [1445]
2018-01-01 21:38:24,462 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 779, 'rating': '4.9', 'level': 'Beginner', 'name': 'Python Data Representations'}}
2018-01-01 21:38:24,466 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:24,470 : INFO : < 200 OK [1460]
2018-01-01 21:38:24,474 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 604, 'rating': '4.4', 'level': 'Beginner', 'name': 'Visual Analytics with Tableau'}}
2018-01-01 21:38:24,474 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2018-01-01 21:38:24,478 : INFO : < 200 OK [1462]
2018-01-01 21:38:24,482 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 605, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Qualitative Research Methods'}}
2018-01-01 21:38:24,482 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:24,486 : INFO : < 200 OK [1465]
2018-01-01 21:38:24,490 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 606, 'rating': '4.6', 'name': 'Decision-Making and Scenarios'}}

2018-01-01 21:38:24,490 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:24,494 : INFO : < 200 OK [1433]
2018-01-01 21:38:24,498 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 607, 'rating': '4.7', 'name': 'Basic Data Descriptors, Statistical Distributions, and Application to Business Decisions'}}
2018-01-01 21:38:24,498 : INFO : > POST http://localhost:7474/db/data/cypher [186]
2018-01-01 21:38:24,502 : INFO : < 200 OK [1492]
2018-01-01 21:38:24,506 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 608, 'rating': '4.6', 'level': 'Beginner', 'name': 'Creating Dashboards and Storytelling with Tableau'}}
2018-01-01 21:38:24,508 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2018-01-01 21:38:24,513 : INFO : < 200 OK [1482]
2018-01-01 21:38:24,515 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 786, 'rating': '4.2', 'name': 'Cluster Analysis in Data Mining'}}
2018-01-01 21:38:24,517 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2018-01-01 21:38:24,521 : INFO : < 200 OK [1435]
2018-01-01 21:38:24,522 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 787, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Building Resilient Streaming Systems on Google Cloud Platform'}}
2018-01-01 21:38:24,526 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:24,530 : INFO : < 200 OK [1498]
2018-01-01 21:38:24,530 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 792, 'rating': '4.2', 'name': 'Pattern Discovery in Data Mining'}}
2018-01-01 21:38:24,534 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:24,538 : INFO : < 200 OK [1436]
2018-01-01 21:38:24,538 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 616, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Data-driven Astronomy'}}
2018-01-01 21:38:24,542 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:24,546 : INFO : < 200 OK [1458]
2018-01-01 21:38:24,546 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 617, 'rating': '4.8', 'level': 'Beginner', 'name': 'Data Analytics for Lean Six Sigma'}}
2018-01-01 21:38:24,550 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:24,554 : INFO : < 200 OK [1466]
2018-01-01 21:38:24,558 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 618, 'rating': '4.5', 'name': 'Principles of fMRI 1'}}
2018-01-01 21:38:24,558 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2018-01-01 21:38:24,562 : INFO : < 200 OK [1424]
2018-01-01 21:38:24,566 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 619, 'rating': '4.6', 'name': 'The Importance of Listening'}}
2018-01-01 21:38:24,566 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2018-01-01 21:38:24,574 : INFO : < 200 OK [1431]
2018-01-01 21:38:24,574 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 620, 'rating': '4.1', 'name': 'Practical Predictive Analytics: Models and Methods'}}
2018-01-01 21:38:24,578 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:24,582 : INFO : < 200 OK [1454]
2018-01-01 21:38:24,586 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 623, 'rating': '4.3', 'name': 'Python for Genomic Data Science'}}
2018-01-01 21:38:24,586 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2018-01-01 21:38:24,590 : INFO : < 200 OK [1435]
2018-01-01 21:38:24,594 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 624, 'rating': '4.5', 'level': 'Beginner', 'name': 'Understanding Your Data: Analytical Tools'}}
2018-01-01 21:38:24,594 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:24,598 : INFO : < 200 OK [1474]
2018-01-01 21:38:24,598 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 625, 'rating': '3.7', 'name': 'Predictive Modeling and Analytics '}}
2018-01-01 21:38:24,602 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:24,607 : INFO : < 200 OK [1438]
2018-01-01 21:38:24,609 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 626, 'rating': '4.8', 'name': 'Linear Regression for Business Statistics'}}
2018-01-01 21:38:24,611 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:24,615 : INFO : < 200 OK [1445]
2018-01-01 21:38:24,617 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 797, 'rating': '4.1', 'level': 'Intermediate', 'name': 'Hands-on Text Mining and Analytics'}}
2018-01-01 21:38:24,619 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2018-01-01 21:38:24,622 : INFO : < 200 OK [1471]
2018-01-01 21:38:24,622 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 628, 'rating': '4.4', 'name': 'Foundations of strategic business analytics'}}
2018-01-01 21:38:24,626 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:24,630 : INFO : < 200 OK [1447]
2018-01-01 21:38:24,634 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 629, 'rating': '4.7', 'name': 'Business Analytics for Decision Making'}}
2018-01-01 21:38:24,634 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:24,638 : INFO : < 200 OK [1442]
2018-01-01 21:38:24,642 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 800, 'rating': '4.4', 'name': 'Business Intelligence Concepts, Tools, and Applications'}}
2018-01-01 21:38:24,646 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:24,654 : INFO : < 200 OK [1459]
2018-01-01 21:38:24,654 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 631, 'rating': '4.5', 'level': 'Beginner', 'name': "A developer's guide to Exploring and Visualizing IoT Data"}}
2018-01-01 21:38:24,658 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:38:24,662 : INFO : < 200 OK [1490]
2018-01-01 21:38:24,662 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 632, 'rating': '4.8', 'name': 'Business Applications of Hypothesis Testing and Confidence Interval Estimation '}}
2018-01-01 21:38:24,666 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:24,670 : INFO : < 200 OK [1483]
2018-01-01 21:38:24,674 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 633, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Introduction to Neurohacking In R'}}
2018-01-01 21:38:24,674 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:24,678 : INFO : < 200 OK [1470]
2018-01-01 21:38:24,682 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 634, 'rating': '4.7', 'level': 'Beginner', 'name': 'Maps and the Geospatial Revolution'}}
2018-01-01 21:38:24,682 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2018-01-01 21:38:24,686 : INFO : < 200 OK [1467]
2018-01-01 21:38:24,690 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 635, 'rating': '4.1', 'level': 'Intermediate', 'name': 'Framework for Data Collection and Analysis'}}
2018-01-01 21:38:24,690 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2018-01-01 21:38:24,694 : INFO : < 200 OK [1479]
2018-01-01 21:38:24,698 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 808, 'rating': '4.0', 'level': 'Intermediate', 'name': 'Building Data Visualization Tools'}}
2018-01-01 21:38:24,698 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2018-01-01 21:38:24,702 : INFO : < 200 OK [1470]
2018-01-01 21:38:24,708 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 637, 'rating': '4.5', 'name': 'Data Analysis Tools'}}
2018-01-01 21:38:24,710 : INFO : > POST http://localhost:7474/db/data/cypher [117]
2018-01-01 21:38:24,714 : INFO : < 200 OK [1423]
2018-01-01 21:38:24,716 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 809, 'rating': '4.4', 'name': 'Functional Programming in Scala Capstone'}}
2018-01-01 21:38:24,718 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:24,721 : INFO : < 200 OK [1444]
2018-01-01 21:38:24,721 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 642, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Meaningful Marketing Insights'}}

2018-01-01 21:38:24,726 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:24,730 : INFO : < 200 OK [1466]
2018-01-01 21:38:24,730 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 643, 'rating': '3.6', 'name': 'Genomic Data Science with Galaxy'}}
2018-01-01 21:38:24,730 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:24,738 : INFO : < 200 OK [1436]
2018-01-01 21:38:24,738 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 645, 'rating': '4.5', 'name': 'Research Data Management and Sharing'}}
2018-01-01 21:38:24,742 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:24,746 : INFO : < 200 OK [1440]
2018-01-01 21:38:24,746 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 819, 'rating': '4.3', 'level': 'Intermediate', 'name': 'Building R Packages'}}
2018-01-01 21:38:24,746 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2018-01-01 21:38:24,754 : INFO : < 200 OK [1456]
2018-01-01 21:38:24,754 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 647, 'level': 'Intermediate', 'name': 'Introduction to Apache Spark and AWS'}}
2018-01-01 21:38:24,754 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:24,758 : INFO : < 200 OK [1448]
2018-01-01 21:38:24,762 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 648, 'rating': '4.5', 'level': 'Beginner', 'name': 'Digital Footprint'}}
2018-01-01 21:38:24,762 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:24,770 : INFO : < 200 OK [1450]
2018-01-01 21:38:24,770 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 823, 'rating': '4.6', 'name': 'Relational Database Support for Data Warehouses'}}
2018-01-01 21:38:24,774 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:24,778 : INFO : < 200 OK [1451]
2018-01-01 21:38:24,782 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 651, 'rating': '4.0', 'name': 'Introduction to People Analytics'}}
2018-01-01 21:38:24,782 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:24,786 : INFO : < 200 OK [1436]
2018-01-01 21:38:24,790 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 652, 'rating': '4.2', 'name': 'Command Line Tools for Genomic Data Science'}}
2018-01-01 21:38:24,790 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:24,794 : INFO : < 200 OK [1447]
2018-01-01 21:38:24,798 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 653, 'rating': '4.6', 'level': 'Beginner', 'name': 'Math behind Moneyball'}}
2018-01-01 21:38:24,798 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:24,802 : INFO : < 200 OK [1454]
2018-01-01 21:38:24,806 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 655, 'rating': '3.9', 'name': 'Bioconductor for Genomic Data Science'}}
2018-01-01 21:38:24,806 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2018-01-01 21:38:24,813 : INFO : < 200 OK [1441]
2018-01-01 21:38:24,816 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 656, 'rating': '4.5', 'name': 'Understanding China, 1700-2000: A Data Analytic Approach, Part 1'}}
2018-01-01 21:38:24,818 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2018-01-01 21:38:24,822 : INFO : < 200 OK [1468]
2018-01-01 21:38:24,826 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 657, 'rating': '4.7', 'name': 'Principles of fMRI 2'}}
2018-01-01 21:38:24,826 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2018-01-01 21:38:24,830 : INFO : < 200 OK [1424]
2018-01-01 21:38:24,834 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 658, 'rating': '4.1', 'name': 'Communicating Business Analytics Results'}}
2018-01-01 21:38:24,834 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:24,838 : INFO : < 200 OK [1444]
2018-01-01 21:38:24,842 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 659, 'rating': '4.0', 'level': 'Beginner', 'name': 'Business Analytics and Digital Media'}}
2018-01-01 21:38:24,842 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:24,846 : INFO : < 200 OK [1469]
2018-01-01 21:38:24,850 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 660, 'rating': '3.8', 'name': 'Dealing With Missing Data'}}
2018-01-01 21:38:24,850 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2018-01-01 21:38:24,854 : INFO : < 200 OK [1429]
2018-01-01 21:38:24,858 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 662, 'rating': '3.5', 'name': 'Communicating Data Science Results'}}
2018-01-01 21:38:24,858 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:24,862 : INFO : < 200 OK [1438]
2018-01-01 21:38:24,866 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 663, 'rating': '4.1', 'level': 'Intermediate', 'name': 'Materials Data Sciences and Informatics'}}
2018-01-01 21:38:24,870 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2018-01-01 21:38:24,874 : INFO : < 200 OK [1476]
2018-01-01 21:38:24,874 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 664, 'name': 'Case studies in business analytics with ACCENTURE'}}
2018-01-01 21:38:24,878 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:24,882 : INFO : < 200 OK [1428]
2018-01-01 21:38:24,886 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 665, 'rating': '4.3', 'name': 'Interprofessional Healthcare Informatics '}}
2018-01-01 21:38:24,886 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:24,890 : INFO : < 200 OK [1445]
2018-01-01 21:38:24,894 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 666, 'rating': '4.4', 'name': 'Business Statistics and Analysis Capstone'}}
2018-01-01 21:38:24,894 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:24,898 : INFO : < 200 OK [1445]
2018-01-01 21:38:24,902 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 846, 'level': 'Advanced', 'name': 'Big Data Applications: Real-Time Streaming'}}
2018-01-01 21:38:24,902 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2018-01-01 21:38:24,906 : INFO : < 200 OK [1450]
2018-01-01 21:38:24,911 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 669, 'rating': '4.4', 'name': 'Combining and Analyzing Complex Data'}}
2018-01-01 21:38:24,913 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:24,917 : INFO : < 200 OK [1440]
2018-01-01 21:38:24,921 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 670, 'rating': '4.2', 'level': 'Intermediate', 'name': 'Biological Diversity (Theories, Measures and Data sampling techniques)'}}
2018-01-01 21:38:24,922 : INFO : > POST http://localhost:7474/db/data/cypher [191]
2018-01-01 21:38:24,926 : INFO : < 200 OK [1507]
2018-01-01 21:38:24,926 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 672, 'rating': '4.6', 'name': 'Executive Data Science Capstone'}}
2018-01-01 21:38:24,930 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2018-01-01 21:38:24,934 : INFO : < 200 OK [1435]
2018-01-01 21:38:24,934 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 673, 'rating': '4.8', 'level': 'Beginner', 'name': 'Geodesign: Change Your World'}}
2018-01-01 21:38:24,938 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:24,942 : INFO : < 200 OK [1461]
2018-01-01 21:38:24,946 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 674, 'rating': '4.6', 'name': 'Wharton Business and Financial Modeling Capstone'}}
2018-01-01 21:38:24,946 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2018-01-01 21:38:24,950 : INFO : < 200 OK [1452]
2018-01-01 21:38:24,954 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 675, 'rating': '5.0', 'level': 'Intermediate', 'name': 'Big Data Science with the BD2K-LINCS Data Coordination and Integration Center'}}

2018-01-01 21:38:24,954 : INFO : > POST http://localhost:7474/db/data/cypher [198]
2018-01-01 21:38:24,958 : INFO : < 200 OK [1514]
2018-01-01 21:38:24,962 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 676, 'rating': '4.6', 'name': 'Understanding China, 1700-2000: A Data Analytic Approach, Part 2'}}
2018-01-01 21:38:24,962 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2018-01-01 21:38:24,970 : INFO : < 200 OK [1468]
2018-01-01 21:38:24,970 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 677, 'rating': '4.3', 'level': 'Beginner', 'name': 'Social Science Approaches to the Study of Chinese Society Part 1'}}
2018-01-01 21:38:24,974 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:24,978 : INFO : < 200 OK [1497]
2018-01-01 21:38:24,982 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 678, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Data Visualization with Tableau Project'}}
2018-01-01 21:38:24,982 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2018-01-01 21:38:24,986 : INFO : < 200 OK [1476]
2018-01-01 21:38:24,990 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 679, 'name': 'Data Analytics Foundations for Accountancy I'}}
2018-01-01 21:38:24,994 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:24,998 : INFO : < 200 OK [1423]
2018-01-01 21:38:24,998 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 681, 'rating': '4.7', 'name': 'Increasing Real Estate Management Profits: Harnessing Data Analytics'}}
2018-01-01 21:38:25,002 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2018-01-01 21:38:25,011 : INFO : < 200 OK [1472]
2018-01-01 21:38:25,014 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 682, 'level': 'Beginner', 'name': 'Social Science Approaches to the Study of Chinese Society Part 2'}}
2018-01-01 21:38:25,015 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2018-01-01 21:38:25,020 : INFO : < 200 OK [1472]
2018-01-01 21:38:25,022 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 872, 'rating': '4.5', 'name': 'Data Mining Project'}}
2018-01-01 21:38:25,022 : INFO : > POST http://localhost:7474/db/data/cypher [117]
2018-01-01 21:38:25,030 : INFO : < 200 OK [1423]
2018-01-01 21:38:25,030 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 684, 'rating': '4.1', 'name': 'Data Science at Scale - Capstone Project'}}
2018-01-01 21:38:25,034 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2018-01-01 21:38:25,038 : INFO : < 200 OK [1444]
2018-01-01 21:38:25,038 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 685, 'rating': '4.3', 'level': 'Intermediate', 'name': 'Business Analytics Capstone'}}
2018-01-01 21:38:25,042 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:25,046 : INFO : < 200 OK [1464]
2018-01-01 21:38:25,050 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 686, 'rating': '4.3', 'name': 'Big Data - Capstone Project'}}
2018-01-01 21:38:25,050 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2018-01-01 21:38:25,058 : INFO : < 200 OK [1431]
2018-01-01 21:38:25,058 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 687, 'rating': '4.7', 'level': 'Beginner', 'name': 'Data Analysis and Presentation Skills: the PwC Approach Final Project'}}
2018-01-01 21:38:25,058 : INFO : > POST http://localhost:7474/db/data/cypher [186]
2018-01-01 21:38:25,062 : INFO : < 200 OK [1502]
2018-01-01 21:38:25,066 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 688, 'rating': '4.6', 'name': 'Design and Build a Data Warehouse for Business Intelligence Implementation'}}
2018-01-01 21:38:25,070 : INFO : > POST http://localhost:7474/db/data/cypher [172]
2018-01-01 21:38:25,074 : INFO : < 200 OK [1478]
2018-01-01 21:38:25,074 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 689, 'rating': '4.7', 'name': 'Capstone: Analyzing (Social) Network Data'}}
2018-01-01 21:38:25,078 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:25,082 : INFO : < 200 OK [1445]
2018-01-01 21:38:25,086 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 690, 'rating': '3.6', 'name': 'Capstone:  Create Value from Open Data'}}
2018-01-01 21:38:25,086 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2018-01-01 21:38:25,090 : INFO : < 200 OK [1442]
2018-01-01 21:38:25,094 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 691, 'rating': '4.5', 'name': 'Genomic Data Science Capstone'}}
2018-01-01 21:38:25,094 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:25,102 : INFO : < 200 OK [1433]
2018-01-01 21:38:25,102 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 692, 'rating': '4.6', 'name': 'Data Analysis and Interpretation Capstone'}}
2018-01-01 21:38:25,108 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:25,111 : INFO : < 200 OK [1445]
2018-01-01 21:38:25,114 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 693, 'rating': '4.9', 'name': 'Geospatial Analysis Project'}}
2018-01-01 21:38:25,116 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2018-01-01 21:38:25,120 : INFO : < 200 OK [1431]
2018-01-01 21:38:25,122 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 876, 'rating': '4.1', 'level': 'Intermediate', 'name': 'Mastering Software Development in R Capstone'}}
2018-01-01 21:38:25,122 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:25,126 : INFO : < 200 OK [1481]
2018-01-01 21:38:25,130 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 695, 'rating': '4.2', 'name': 'Advanced Business Analytics Capstone'}}
2018-01-01 21:38:25,130 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:25,134 : INFO : < 200 OK [1440]
2018-01-01 21:38:25,138 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 697, 'rating': '4.8', 'name': 'Programming for Everybody (Getting Started with Python)'}}
2018-01-01 21:38:25,138 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:25,142 : INFO : < 200 OK [1459]
2018-01-01 21:38:25,146 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 698, 'rating': '4.6', 'level': 'Intermediate', 'name': 'IBM Blockchain Foundation for Developers'}}
2018-01-01 21:38:25,146 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2018-01-01 21:38:25,150 : INFO : < 200 OK [1477]
2018-01-01 21:38:25,154 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 703, 'rating': '4.8', 'level': 'Beginner', 'name': 'Introduction to Programming with MATLAB'}}
2018-01-01 21:38:25,154 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2018-01-01 21:38:25,158 : INFO : < 200 OK [1472]
2018-01-01 21:38:25,162 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 704, 'rating': '4.8', 'name': 'Using Python to Access Web Data'}}
2018-01-01 21:38:25,166 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2018-01-01 21:38:25,170 : INFO : < 200 OK [1435]
2018-01-01 21:38:25,174 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 705, 'rating': '4.7', 'level': 'Beginner', 'name': 'Learn to Program: The Fundamentals'}}
2018-01-01 21:38:25,178 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2018-01-01 21:38:25,182 : INFO : < 200 OK [1467]
2018-01-01 21:38:25,186 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 708, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Object Oriented Programming in Java'}}
2018-01-01 21:38:25,186 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2018-01-01 21:38:25,190 : INFO : < 200 OK [1472]
2018-01-01 21:38:25,194 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 710, 'rating': '4.6', 'level': 'Beginner', 'name': 'Python Programming: A Concise Introduction'}}
2018-01-01 21:38:25,194 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2018-01-01 21:38:25,198 : INFO : < 200 OK [1475]

2018-01-01 21:38:25,202 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 712, 'rating': '4.8', 'level': 'Intermediate', 'name': 'Functional Programming Principles in Scala'}}
2018-01-01 21:38:25,202 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2018-01-01 21:38:25,210 : INFO : < 200 OK [1479]
2018-01-01 21:38:25,212 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 715, 'rating': '4.3', 'name': 'C++ For C Programmers, Part A'}}
2018-01-01 21:38:25,214 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:25,219 : INFO : < 200 OK [1433]
2018-01-01 21:38:25,221 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 716, 'rating': '4.5', 'level': 'Beginner', 'name': 'Java Programming: Solving Problems with Software'}}
2018-01-01 21:38:25,222 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:25,226 : INFO : < 200 OK [1481]
2018-01-01 21:38:25,226 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 719, 'rating': '4.5', 'level': 'Beginner', 'name': 'Biology Meets Programming: Bioinformatics for Beginners'}}
2018-01-01 21:38:25,230 : INFO : > POST http://localhost:7474/db/data/cypher [172]
2018-01-01 21:38:25,234 : INFO : < 200 OK [1488]
2018-01-01 21:38:25,238 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 725, 'rating': '4.7', 'name': 'Code Yourself! An Introduction to Programming'}}
2018-01-01 21:38:25,238 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2018-01-01 21:38:25,242 : INFO : < 200 OK [1449]
2018-01-01 21:38:25,246 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 727, 'rating': '4.7', 'level': 'Beginner', 'name': 'Digital Product Management: Modern Fundamentals'}}
2018-01-01 21:38:25,246 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2018-01-01 21:38:25,250 : INFO : < 200 OK [1480]
2018-01-01 21:38:25,254 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 730, 'rating': '4.7', 'name': 'Beginning Game Programming with C#'}}
2018-01-01 21:38:25,254 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:25,258 : INFO : < 200 OK [1438]
2018-01-01 21:38:25,262 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 731, 'rating': '4.6', 'level': 'Intermediate', 'name': 'The Finite Element Method for Problems in Physics'}}
2018-01-01 21:38:25,262 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2018-01-01 21:38:25,266 : INFO : < 200 OK [1486]
2018-01-01 21:38:25,270 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 735, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Object-Oriented Design'}}
2018-01-01 21:38:25,270 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2018-01-01 21:38:25,274 : INFO : < 200 OK [1459]
2018-01-01 21:38:25,278 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 745, 'rating': '4.8', 'name': 'Introduction to Game Development'}}
2018-01-01 21:38:25,278 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2018-01-01 21:38:25,286 : INFO : < 200 OK [1436]
2018-01-01 21:38:25,286 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 746, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Parallel Programming in Java'}}
2018-01-01 21:38:25,290 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2018-01-01 21:38:25,294 : INFO : < 200 OK [1465]
2018-01-01 21:38:25,298 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 747, 'rating': '4.5', 'name': 'The Raspberry Pi Platform and Python Programming for the Raspberry Pi'}}
2018-01-01 21:38:25,302 : INFO : > POST http://localhost:7474/db/data/cypher [167]
2018-01-01 21:38:25,307 : INFO : < 200 OK [1473]
2018-01-01 21:38:25,310 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 751, 'rating': '4.7', 'level': 'Beginner', 'name': 'Java Programming: Arrays, Lists, and Structured Data'}}
2018-01-01 21:38:25,311 : INFO : > POST http://localhost:7474/db/data/cypher [169]
2018-01-01 21:38:25,317 : INFO : < 200 OK [1485]
2018-01-01 21:38:25,319 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 752, 'rating': '3.7', 'level': 'Intermediate', 'name': 'Embedded Hardware and Operating Systems'}}
2018-01-01 21:38:25,321 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2018-01-01 21:38:25,322 : INFO : < 200 OK [1476]
2018-01-01 21:38:25,326 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 757, 'rating': '4.5', 'name': 'Learn to Program: Crafting Quality Code'}}
2018-01-01 21:38:25,330 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:25,334 : INFO : < 200 OK [1443]
2018-01-01 21:38:25,334 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 758, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Functional Program Design in Scala'}}
2018-01-01 21:38:25,338 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2018-01-01 21:38:25,342 : INFO : < 200 OK [1471]
2018-01-01 21:38:25,342 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 759, 'rating': '4.9', 'level': 'Intermediate', 'name': 'Audio Signal Processing for Music Applications'}}
2018-01-01 21:38:25,346 : INFO : > POST http://localhost:7474/db/data/cypher [167]
2018-01-01 21:38:25,350 : INFO : < 200 OK [1483]
2018-01-01 21:38:25,354 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 763, 'level': 'Intermediate', 'name': "A Developer's guide to Node-RED"}}
2018-01-01 21:38:25,354 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2018-01-01 21:38:25,358 : INFO : < 200 OK [1443]
2018-01-01 21:38:25,358 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 764, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Parallel programming'}}
2018-01-01 21:38:25,362 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2018-01-01 21:38:25,366 : INFO : < 200 OK [1457]
2018-01-01 21:38:25,370 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 767, 'rating': '4.6', 'level': 'Beginner', 'name': 'Java Programming: Principles of Software Design'}}
2018-01-01 21:38:25,370 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2018-01-01 21:38:25,374 : INFO : < 200 OK [1480]
2018-01-01 21:38:25,374 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 774, 'rating': '4.4', 'level': 'Intermediate', 'name': 'Distributed Programming in Java'}}
2018-01-01 21:38:25,378 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2018-01-01 21:38:25,382 : INFO : < 200 OK [1468]
2018-01-01 21:38:25,386 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 780, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Concurrent Programming in Java'}}
2018-01-01 21:38:25,386 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2018-01-01 21:38:25,390 : INFO : < 200 OK [1467]
2018-01-01 21:38:25,394 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 783, 'rating': '4.9', 'name': 'Build a Modern Computer from First Principles: Nand to Tetris Part II (project-centered course)'}}
2018-01-01 21:38:25,394 : INFO : > POST http://localhost:7474/db/data/cypher [193]
2018-01-01 21:38:25,402 : INFO : < 200 OK [1499]
2018-01-01 21:38:25,402 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 784, 'rating': '4.2', 'name': 'C++ For C Programmers, Part B'}}
2018-01-01 21:38:25,408 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:25,413 : INFO : < 200 OK [1433]
2018-01-01 21:38:25,418 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 785, 'rating': '4.6', 'level': 'Intermediate', 'name': 'Mastering the Software Engineering Interview'}}
2018-01-01 21:38:25,420 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:25,423 : INFO : < 200 OK [1481]
2018-01-01 21:38:25,427 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 805, 'level': 'Beginner', 'name': 'Requirements Gathering for Secure Software Development'}}
2018-01-01 21:38:25,427 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2018-01-01 21:38:25,431 : INFO : < 200 OK [1462]

2018-01-01 21:38:25,435 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 810, 'rating': '4.5', 'level': 'Beginner', 'name': 'Software Development Processes and Methodologies'}}
2018-01-01 21:38:25,435 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:25,439 : INFO : < 200 OK [1481]
2018-01-01 21:38:25,443 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 812, 'rating': '2.0', 'level': 'Intermediate', 'name': 'Fundamentals of Parallelism on Intel Architecture'}}
2018-01-01 21:38:25,443 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2018-01-01 21:38:25,447 : INFO : < 200 OK [1486]
2018-01-01 21:38:25,451 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 820, 'rating': '4.8', 'name': 'Game Development for Modern Platforms'}}
2018-01-01 21:38:25,451 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2018-01-01 21:38:25,455 : INFO : < 200 OK [1441]
2018-01-01 21:38:25,459 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 826, 'rating': '4.7', 'name': 'Creative Programming for Digital Media & Mobile Apps'}}
2018-01-01 21:38:25,459 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2018-01-01 21:38:25,463 : INFO : < 200 OK [1456]
2018-01-01 21:38:25,467 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 831, 'rating': '4.2', 'name': 'Software Architecture for the Internet of Things'}}
2018-01-01 21:38:25,471 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2018-01-01 21:38:25,475 : INFO : < 200 OK [1452]
2018-01-01 21:38:25,475 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 836, 'rating': '1.0', 'level': 'Beginner', 'name': 'Lean Software Development'}}
2018-01-01 21:38:25,479 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2018-01-01 21:38:25,483 : INFO : < 200 OK [1458]
2018-01-01 21:38:25,487 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 838, 'level': 'Beginner', 'name': 'SRS Documents: Requirements and Diagrammatic Notations'}}
2018-01-01 21:38:25,487 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2018-01-01 21:38:25,491 : INFO : < 200 OK [1462]
2018-01-01 21:38:25,495 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 839, 'rating': '5.0', 'name': 'Software Design as an Element of the Software Development Lifecycle'}}
2018-01-01 21:38:25,495 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2018-01-01 21:38:25,499 : INFO : < 200 OK [1471]
2018-01-01 21:38:25,503 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 842, 'rating': '4.5', 'level': 'Intermediate', 'name': 'Quantitative Model Checking'}}
2018-01-01 21:38:25,503 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2018-01-01 21:38:25,509 : INFO : < 200 OK [1464]
2018-01-01 21:38:25,513 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 843, 'level': 'Intermediate', 'name': 'Software Design Methods and Tools'}}
2018-01-01 21:38:25,515 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:25,518 : INFO : < 200 OK [1445]
2018-01-01 21:38:25,521 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 844, 'level': 'Beginner', 'name': 'Requirements Elicitation: Artifact and Stakeholder Analysis'}}
2018-01-01 21:38:25,523 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2018-01-01 21:38:25,527 : INFO : < 200 OK [1467]
2018-01-01 21:38:25,527 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 845, 'level': 'Beginner', 'name': 'Software Requirements Prioritization: Risk Analysis'}}
2018-01-01 21:38:25,531 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:25,535 : INFO : < 200 OK [1459]
2018-01-01 21:38:25,535 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 847, 'level': 'Beginner', 'name': 'Requirements Specifications: Goals and Conflict Analysis'}}
2018-01-01 21:38:25,539 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2018-01-01 21:38:25,543 : INFO : < 200 OK [1464]
2018-01-01 21:38:25,547 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 850, 'level': 'Intermediate', 'name': 'Software Design as an Abstraction'}}
2018-01-01 21:38:25,547 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2018-01-01 21:38:25,551 : INFO : < 200 OK [1445]
2018-01-01 21:38:25,555 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 852, 'level': 'Intermediate', 'name': 'Software Design Threats and Mitigations'}}
2018-01-01 21:38:25,555 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2018-01-01 21:38:25,559 : INFO : < 200 OK [1451]
2018-01-01 21:38:25,563 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 858, 'rating': '4.6', 'name': 'Games, Sensors and Media'}}
2018-01-01 21:38:25,563 : INFO : > POST http://localhost:7474/db/data/cypher [122]
2018-01-01 21:38:25,567 : INFO : < 200 OK [1428]
2018-01-01 21:38:25,571 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 859, 'name': 'Malicious Software and its Underground Economy: Two Sides to Every Story'}}
2018-01-01 21:38:25,571 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2018-01-01 21:38:25,579 : INFO : < 200 OK [1451]
2018-01-01 21:38:25,583 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 861, 'rating': '5.0', 'level': 'Advanced', 'name': 'Capstone:  Autonomous Runway Detection for IoT'}}
2018-01-01 21:38:25,583 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2018-01-01 21:38:25,591 : INFO : < 200 OK [1479]
2018-01-01 21:38:25,591 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 866, 'name': 'Engineering Practices for Building Quality Software'}}
2018-01-01 21:38:25,595 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:25,599 : INFO : < 200 OK [1430]
2018-01-01 21:38:25,603 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 873, 'rating': '4.7', 'level': 'Intermediate', 'name': 'Java Programming: Build a Recommendation System'}}
2018-01-01 21:38:25,603 : INFO : > POST http://localhost:7474/db/data/cypher [168]
2018-01-01 21:38:25,610 : INFO : < 200 OK [1484]
2018-01-01 21:38:25,612 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 875, 'rating': '4.7', 'name': 'Game Design and Development Capstone'}}
2018-01-01 21:38:25,614 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2018-01-01 21:38:25,739 : INFO : < 200 OK [1440]

In [56]:
for i, row in data.drop_duplicates(subset=['category', 'uid']).iterrows():
    graph.create(Relationship(course_dict[row.uid], 'belong to', cat_dict[row.category]))

2018-01-01 21:38:25,928 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1228, '_0n1': 1221}
2018-01-01 21:38:25,928 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:25,941 : INFO : < 200 OK [3332]
2018-01-01 21:38:25,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1246, '_0n1': 1221}
2018-01-01 21:38:25,945 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:25,949 : INFO : < 200 OK [3309]
2018-01-01 21:38:25,953 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1229, '_0n1': 1221}
2018-01-01 21:38:25,953 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:25,957 : INFO : < 200 OK [3383]
2018-01-01 21:38:25,961 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1247, '_0n1': 1221}
2018-01-01 21:38:25,961 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:25,965 : INFO : < 200 OK [3356]
2018-01-01 21:38:25,969 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1230, '_0n1': 1221}
2018-01-01 21:38:25,969 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:25,973 : INFO : < 200 OK [3308]
2018-01-01 21:38:25,977 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1248, '_0n1': 1221}
2018-01-01 21:38:25,977 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:25,985 : INFO : < 200 OK [3363]
2018-01-01 21:38:25,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1231, '_0n1': 1221}
2018-01-01 21:38:25,989 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:25,993 : INFO : < 200 OK [3355]
2018-01-01 21:38:25,993 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1249, '_0n1': 1221}
2018-01-01 21:38:25,997 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,001 : INFO : < 200 OK [3351]
2018-01-01 21:38:26,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1232, '_0n1': 1221}
2018-01-01 21:38:26,001 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,005 : INFO : < 200 OK [3346]
2018-01-01 21:38:26,011 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1250, '_0n1': 1221}
2018-01-01 21:38:26,013 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,018 : INFO : < 200 OK [3370]
2018-01-01 21:38:26,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1233, '_0n1': 1221}
2018-01-01 21:38:26,023 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,027 : INFO : < 200 OK [3312]
2018-01-01 21:38:26,031 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1251, '_0n1': 1221}
2018-01-01 21:38:26,035 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,039 : INFO : < 200 OK [3373]
2018-01-01 21:38:26,043 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1234, '_0n1': 1221}
2018-01-01 21:38:26,043 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,047 : INFO : < 200 OK [3311]
2018-01-01 21:38:26,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1252, '_0n1': 1221}
2018-01-01 21:38:26,051 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,055 : INFO : < 200 OK [3361]
2018-01-01 21:38:26,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1235, '_0n1': 1221}
2018-01-01 21:38:26,059 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,067 : INFO : < 200 OK [3368]
2018-01-01 21:38:26,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1253, '_0n1': 1221}
2018-01-01 21:38:26,071 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,075 : INFO : < 200 OK [3350]
2018-01-01 21:38:26,079 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1236, '_0n1': 1221}
2018-01-01 21:38:26,079 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,083 : INFO : < 200 OK [3369]
2018-01-01 21:38:26,087 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1254, '_0n1': 1221}
2018-01-01 21:38:26,087 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,091 : INFO : < 200 OK [3356]
2018-01-01 21:38:26,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1237, '_0n1': 1221}
2018-01-01 21:38:26,095 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,099 : INFO : < 200 OK [3352]
2018-01-01 21:38:26,103 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1255, '_0n1': 1221}
2018-01-01 21:38:26,103 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,109 : INFO : < 200 OK [3390]
2018-01-01 21:38:26,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1238, '_0n1': 1221}
2018-01-01 21:38:26,112 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,117 : INFO : < 200 OK [3285]
2018-01-01 21:38:26,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1256, '_0n1': 1221}
2018-01-01 21:38:26,123 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,123 : INFO : < 200 OK [3358]
2018-01-01 21:38:26,127 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1239, '_0n1': 1221}
2018-01-01 21:38:26,131 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,139 : INFO : < 200 OK [3380]
2018-01-01 21:38:26,143 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1259, '_0n1': 1221}
2018-01-01 21:38:26,143 : INFO : > POST http://localhost:7474/db/data/cypher [184]

2018-01-01 21:38:26,151 : INFO : < 200 OK [3363]
2018-01-01 21:38:26,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1240, '_0n1': 1221}
2018-01-01 21:38:26,159 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,163 : INFO : < 200 OK [3334]
2018-01-01 21:38:26,167 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1260, '_0n1': 1221}
2018-01-01 21:38:26,167 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,175 : INFO : < 200 OK [3320]
2018-01-01 21:38:26,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 0, '_0n1': 1221}
2018-01-01 21:38:26,179 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:26,187 : INFO : < 200 OK [3279]
2018-01-01 21:38:26,191 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1301, '_0n1': 1221}
2018-01-01 21:38:26,195 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,199 : INFO : < 200 OK [3348]
2018-01-01 21:38:26,199 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1, '_0n1': 1221}
2018-01-01 21:38:26,203 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:26,211 : INFO : < 200 OK [3249]
2018-01-01 21:38:26,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1302, '_0n1': 1221}
2018-01-01 21:38:26,216 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:26,221 : INFO : < 200 OK [3356]
2018-01-01 21:38:26,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 1221}
2018-01-01 21:38:26,227 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:26,231 : INFO : < 200 OK [3313]
2018-01-01 21:38:26,235 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 20, '_0n1': 1221}
2018-01-01 21:38:26,235 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,243 : INFO : < 200 OK [3325]
2018-01-01 21:38:26,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 3, '_0n1': 1221}
2018-01-01 21:38:26,247 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:26,251 : INFO : < 200 OK [3295]
2018-01-01 21:38:26,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 21, '_0n1': 1221}
2018-01-01 21:38:26,255 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,259 : INFO : < 200 OK [3335]
2018-01-01 21:38:26,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 4, '_0n1': 1221}
2018-01-01 21:38:26,267 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:26,271 : INFO : < 200 OK [3313]
2018-01-01 21:38:26,271 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 22, '_0n1': 1221}
2018-01-01 21:38:26,275 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,279 : INFO : < 200 OK [3272]
2018-01-01 21:38:26,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 5, '_0n1': 1221}
2018-01-01 21:38:26,283 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:26,287 : INFO : < 200 OK [3324]
2018-01-01 21:38:26,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 6, '_0n1': 1221}
2018-01-01 21:38:26,291 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:26,295 : INFO : < 200 OK [3312]
2018-01-01 21:38:26,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 23, '_0n1': 1221}
2018-01-01 21:38:26,299 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,303 : INFO : < 200 OK [3273]
2018-01-01 21:38:26,303 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 24, '_0n1': 1221}
2018-01-01 21:38:26,307 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,311 : INFO : < 200 OK [3318]
2018-01-01 21:38:26,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 7, '_0n1': 1221}
2018-01-01 21:38:26,315 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:26,319 : INFO : < 200 OK [3286]
2018-01-01 21:38:26,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 25, '_0n1': 1221}
2018-01-01 21:38:26,323 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,327 : INFO : < 200 OK [3282]
2018-01-01 21:38:26,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 8, '_0n1': 1221}
2018-01-01 21:38:26,331 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:26,335 : INFO : < 200 OK [3305]
2018-01-01 21:38:26,339 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 26, '_0n1': 1221}
2018-01-01 21:38:26,339 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,343 : INFO : < 200 OK [3317]
2018-01-01 21:38:26,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 9, '_0n1': 1221}
2018-01-01 21:38:26,351 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:26,355 : INFO : < 200 OK [3270]
2018-01-01 21:38:26,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 27, '_0n1': 1221}
2018-01-01 21:38:26,359 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,367 : INFO : < 200 OK [3315]
2018-01-01 21:38:26,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 10, '_0n1': 1221}
2018-01-01 21:38:26,371 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,379 : INFO : < 200 OK [3327]
2018-01-01 21:38:26,383 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 28, '_0n1': 1221}
2018-01-01 21:38:26,387 : INFO : > POST http://localhost:7474/db/data/cypher [182]

2018-01-01 21:38:26,391 : INFO : < 200 OK [3299]
2018-01-01 21:38:26,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 11, '_0n1': 1221}
2018-01-01 21:38:26,395 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,403 : INFO : < 200 OK [3329]
2018-01-01 21:38:26,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 29, '_0n1': 1221}
2018-01-01 21:38:26,407 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,412 : INFO : < 200 OK [3311]
2018-01-01 21:38:26,415 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 12, '_0n1': 1221}
2018-01-01 21:38:26,417 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,422 : INFO : < 200 OK [3327]
2018-01-01 21:38:26,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 30, '_0n1': 1221}
2018-01-01 21:38:26,427 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,431 : INFO : < 200 OK [3336]
2018-01-01 21:38:26,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 13, '_0n1': 1221}
2018-01-01 21:38:26,439 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,443 : INFO : < 200 OK [3302]
2018-01-01 21:38:26,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 31, '_0n1': 1221}
2018-01-01 21:38:26,447 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,451 : INFO : < 200 OK [3346]
2018-01-01 21:38:26,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 14, '_0n1': 1221}
2018-01-01 21:38:26,455 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,459 : INFO : < 200 OK [3332]
2018-01-01 21:38:26,463 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 32, '_0n1': 1221}
2018-01-01 21:38:26,467 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,471 : INFO : < 200 OK [3277]
2018-01-01 21:38:26,475 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 15, '_0n1': 1221}
2018-01-01 21:38:26,475 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,479 : INFO : < 200 OK [3291]
2018-01-01 21:38:26,483 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 33, '_0n1': 1221}
2018-01-01 21:38:26,483 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,487 : INFO : < 200 OK [3287]
2018-01-01 21:38:26,491 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 16, '_0n1': 1221}
2018-01-01 21:38:26,491 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,495 : INFO : < 200 OK [3335]
2018-01-01 21:38:26,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 34, '_0n1': 1221}
2018-01-01 21:38:26,503 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,507 : INFO : < 200 OK [3304]
2018-01-01 21:38:26,511 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 17, '_0n1': 1221}
2018-01-01 21:38:26,513 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,518 : INFO : < 200 OK [3345]
2018-01-01 21:38:26,521 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 35, '_0n1': 1221}
2018-01-01 21:38:26,523 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,523 : INFO : < 200 OK [3307]
2018-01-01 21:38:26,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 18, '_0n1': 1221}
2018-01-01 21:38:26,531 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,535 : INFO : < 200 OK [3338]
2018-01-01 21:38:26,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 36, '_0n1': 1221}
2018-01-01 21:38:26,539 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,543 : INFO : < 200 OK [3313]
2018-01-01 21:38:26,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 19, '_0n1': 1221}
2018-01-01 21:38:26,547 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,551 : INFO : < 200 OK [3286]
2018-01-01 21:38:26,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 37, '_0n1': 1221}
2018-01-01 21:38:26,555 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,559 : INFO : < 200 OK [3308]
2018-01-01 21:38:26,559 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 40, '_0n1': 1221}
2018-01-01 21:38:26,563 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,567 : INFO : < 200 OK [3311]
2018-01-01 21:38:26,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 38, '_0n1': 1221}
2018-01-01 21:38:26,571 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,575 : INFO : < 200 OK [3334]
2018-01-01 21:38:26,579 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 41, '_0n1': 1221}
2018-01-01 21:38:26,579 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,583 : INFO : < 200 OK [3318]
2018-01-01 21:38:26,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 39, '_0n1': 1221}
2018-01-01 21:38:26,587 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,595 : INFO : < 200 OK [3361]
2018-01-01 21:38:26,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 42, '_0n1': 1221}
2018-01-01 21:38:26,599 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,603 : INFO : < 200 OK [3282]
2018-01-01 21:38:26,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 60, '_0n1': 1221}
2018-01-01 21:38:26,610 : INFO : > POST http://localhost:7474/db/data/cypher [182]

2018-01-01 21:38:26,614 : INFO : < 200 OK [3359]
2018-01-01 21:38:26,617 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 43, '_0n1': 1221}
2018-01-01 21:38:26,620 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,623 : INFO : < 200 OK [3347]
2018-01-01 21:38:26,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 61, '_0n1': 1221}
2018-01-01 21:38:26,627 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,631 : INFO : < 200 OK [3300]
2018-01-01 21:38:26,635 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 44, '_0n1': 1221}
2018-01-01 21:38:26,635 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,643 : INFO : < 200 OK [3327]
2018-01-01 21:38:26,647 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 62, '_0n1': 1221}
2018-01-01 21:38:26,647 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,655 : INFO : < 200 OK [3315]
2018-01-01 21:38:26,659 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 45, '_0n1': 1221}
2018-01-01 21:38:26,659 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,667 : INFO : < 200 OK [3288]
2018-01-01 21:38:26,671 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 63, '_0n1': 1221}
2018-01-01 21:38:26,671 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,675 : INFO : < 200 OK [3347]
2018-01-01 21:38:26,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 46, '_0n1': 1221}
2018-01-01 21:38:26,683 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,687 : INFO : < 200 OK [3350]
2018-01-01 21:38:26,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 64, '_0n1': 1221}
2018-01-01 21:38:26,695 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,699 : INFO : < 200 OK [3279]
2018-01-01 21:38:26,703 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 47, '_0n1': 1221}
2018-01-01 21:38:26,703 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,711 : INFO : < 200 OK [3324]
2018-01-01 21:38:26,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 65, '_0n1': 1221}
2018-01-01 21:38:26,716 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,720 : INFO : < 200 OK [3319]
2018-01-01 21:38:26,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 48, '_0n1': 1221}
2018-01-01 21:38:26,723 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,727 : INFO : < 200 OK [3305]
2018-01-01 21:38:26,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 1219}
2018-01-01 21:38:26,731 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,739 : INFO : < 200 OK [3303]
2018-01-01 21:38:26,739 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 1219}
2018-01-01 21:38:26,743 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,747 : INFO : < 200 OK [3299]
2018-01-01 21:38:26,751 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 67, '_0n1': 1219}
2018-01-01 21:38:26,751 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,755 : INFO : < 200 OK [3352]
2018-01-01 21:38:26,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 50, '_0n1': 1219}
2018-01-01 21:38:26,763 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,767 : INFO : < 200 OK [3288]
2018-01-01 21:38:26,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1219}
2018-01-01 21:38:26,771 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,775 : INFO : < 200 OK [3289]
2018-01-01 21:38:26,779 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 51, '_0n1': 1219}
2018-01-01 21:38:26,779 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,783 : INFO : < 200 OK [3260]
2018-01-01 21:38:26,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 69, '_0n1': 1219}
2018-01-01 21:38:26,791 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,795 : INFO : < 200 OK [3338]
2018-01-01 21:38:26,799 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 1219}
2018-01-01 21:38:26,803 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,809 : INFO : < 200 OK [3298]
2018-01-01 21:38:26,812 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 1219}
2018-01-01 21:38:26,814 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,818 : INFO : < 200 OK [3289]
2018-01-01 21:38:26,822 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1219}
2018-01-01 21:38:26,823 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,827 : INFO : < 200 OK [3284]
2018-01-01 21:38:26,827 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 71, '_0n1': 1219}
2018-01-01 21:38:26,831 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,835 : INFO : < 200 OK [3332]
2018-01-01 21:38:26,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 54, '_0n1': 1219}
2018-01-01 21:38:26,839 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,843 : INFO : < 200 OK [3290]
2018-01-01 21:38:26,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 72, '_0n1': 1219}
2018-01-01 21:38:26,847 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,851 : INFO : < 200 OK [3301]

2018-01-01 21:38:26,855 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 55, '_0n1': 1219}
2018-01-01 21:38:26,855 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,859 : INFO : < 200 OK [3287]
2018-01-01 21:38:26,863 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 73, '_0n1': 1219}
2018-01-01 21:38:26,863 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,867 : INFO : < 200 OK [3318]
2018-01-01 21:38:26,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 1219}
2018-01-01 21:38:26,875 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,879 : INFO : < 200 OK [3282]
2018-01-01 21:38:26,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 74, '_0n1': 1219}
2018-01-01 21:38:26,883 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,891 : INFO : < 200 OK [3271]
2018-01-01 21:38:26,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 57, '_0n1': 1219}
2018-01-01 21:38:26,895 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,899 : INFO : < 200 OK [3275]
2018-01-01 21:38:26,903 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 75, '_0n1': 1219}
2018-01-01 21:38:26,903 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,910 : INFO : < 200 OK [3305]
2018-01-01 21:38:26,912 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 58, '_0n1': 1219}
2018-01-01 21:38:26,914 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,918 : INFO : < 200 OK [3319]
2018-01-01 21:38:26,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 76, '_0n1': 1219}
2018-01-01 21:38:26,923 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,927 : INFO : < 200 OK [3294]
2018-01-01 21:38:26,931 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 1219}
2018-01-01 21:38:26,931 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,939 : INFO : < 200 OK [3279]
2018-01-01 21:38:26,943 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 77, '_0n1': 1219}
2018-01-01 21:38:26,943 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,951 : INFO : < 200 OK [3340]
2018-01-01 21:38:26,951 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 81, '_0n1': 1219}
2018-01-01 21:38:26,955 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,963 : INFO : < 200 OK [3290]
2018-01-01 21:38:26,967 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 78, '_0n1': 1219}
2018-01-01 21:38:26,967 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,971 : INFO : < 200 OK [3319]
2018-01-01 21:38:26,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 82, '_0n1': 1219}
2018-01-01 21:38:26,979 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,983 : INFO : < 200 OK [3291]
2018-01-01 21:38:26,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 80, '_0n1': 1219}
2018-01-01 21:38:26,987 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,991 : INFO : < 200 OK [3298]
2018-01-01 21:38:26,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 83, '_0n1': 1219}
2018-01-01 21:38:26,995 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:26,999 : INFO : < 200 OK [3295]
2018-01-01 21:38:27,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1219}
2018-01-01 21:38:27,003 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,010 : INFO : < 200 OK [3318]
2018-01-01 21:38:27,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 84, '_0n1': 1219}
2018-01-01 21:38:27,016 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,020 : INFO : < 200 OK [3287]
2018-01-01 21:38:27,023 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 1219}
2018-01-01 21:38:27,023 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,027 : INFO : < 200 OK [3319]
2018-01-01 21:38:27,031 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 85, '_0n1': 1219}
2018-01-01 21:38:27,031 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,035 : INFO : < 200 OK [3301]
2018-01-01 21:38:27,039 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 103, '_0n1': 1219}
2018-01-01 21:38:27,039 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,043 : INFO : < 200 OK [3310]
2018-01-01 21:38:27,047 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 86, '_0n1': 1219}
2018-01-01 21:38:27,051 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,055 : INFO : < 200 OK [3342]
2018-01-01 21:38:27,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 104, '_0n1': 1219}
2018-01-01 21:38:27,059 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,063 : INFO : < 200 OK [3292]
2018-01-01 21:38:27,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 87, '_0n1': 1219}
2018-01-01 21:38:27,067 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,071 : INFO : < 200 OK [3299]
2018-01-01 21:38:27,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 1219}
2018-01-01 21:38:27,075 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,079 : INFO : < 200 OK [3346]
2018-01-01 21:38:27,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 88, '_0n1': 1219}

2018-01-01 21:38:27,083 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,087 : INFO : < 200 OK [3277]
2018-01-01 21:38:27,091 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 1219}
2018-01-01 21:38:27,091 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,095 : INFO : < 200 OK [3315]
2018-01-01 21:38:27,099 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 89, '_0n1': 1219}
2018-01-01 21:38:27,099 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,103 : INFO : < 200 OK [3295]
2018-01-01 21:38:27,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 107, '_0n1': 1219}
2018-01-01 21:38:27,112 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,118 : INFO : < 200 OK [3287]
2018-01-01 21:38:27,123 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 90, '_0n1': 1219}
2018-01-01 21:38:27,123 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,127 : INFO : < 200 OK [3309]
2018-01-01 21:38:27,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 108, '_0n1': 1219}
2018-01-01 21:38:27,135 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,139 : INFO : < 200 OK [3327]
2018-01-01 21:38:27,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 1219}
2018-01-01 21:38:27,143 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,147 : INFO : < 200 OK [3302]
2018-01-01 21:38:27,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 109, '_0n1': 1219}
2018-01-01 21:38:27,151 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,155 : INFO : < 200 OK [3282]
2018-01-01 21:38:27,159 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 92, '_0n1': 1219}
2018-01-01 21:38:27,159 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,163 : INFO : < 200 OK [3292]
2018-01-01 21:38:27,167 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 1219}
2018-01-01 21:38:27,171 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,175 : INFO : < 200 OK [3321]
2018-01-01 21:38:27,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 93, '_0n1': 1219}
2018-01-01 21:38:27,179 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,183 : INFO : < 200 OK [3269]
2018-01-01 21:38:27,187 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 111, '_0n1': 1219}
2018-01-01 21:38:27,191 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,195 : INFO : < 200 OK [3292]
2018-01-01 21:38:27,199 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 94, '_0n1': 1219}
2018-01-01 21:38:27,199 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,203 : INFO : < 200 OK [3286]
2018-01-01 21:38:27,209 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 112, '_0n1': 1219}
2018-01-01 21:38:27,211 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,215 : INFO : < 200 OK [3285]
2018-01-01 21:38:27,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1219}
2018-01-01 21:38:27,223 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,227 : INFO : < 200 OK [3303]
2018-01-01 21:38:27,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 113, '_0n1': 1219}
2018-01-01 21:38:27,231 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,235 : INFO : < 200 OK [3333]
2018-01-01 21:38:27,239 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 96, '_0n1': 1219}
2018-01-01 21:38:27,239 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,243 : INFO : < 200 OK [3272]
2018-01-01 21:38:27,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1219}
2018-01-01 21:38:27,247 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,251 : INFO : < 200 OK [3288]
2018-01-01 21:38:27,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 97, '_0n1': 1219}
2018-01-01 21:38:27,259 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,263 : INFO : < 200 OK [3306]
2018-01-01 21:38:27,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 10, '_0n1': 1219}
2018-01-01 21:38:27,267 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,271 : INFO : < 200 OK [3311]
2018-01-01 21:38:27,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 115, '_0n1': 1219}
2018-01-01 21:38:27,279 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,283 : INFO : < 200 OK [3322]
2018-01-01 21:38:27,283 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 98, '_0n1': 1219}
2018-01-01 21:38:27,287 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,291 : INFO : < 200 OK [3317]
2018-01-01 21:38:27,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 116, '_0n1': 1219}
2018-01-01 21:38:27,299 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,303 : INFO : < 200 OK [3339]
2018-01-01 21:38:27,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 99, '_0n1': 1219}
2018-01-01 21:38:27,307 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,313 : INFO : < 200 OK [3298]
2018-01-01 21:38:27,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 117, '_0n1': 1219}
2018-01-01 21:38:27,317 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:27,323 : INFO : < 200 OK [3323]
2018-01-01 21:38:27,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 100, '_0n1': 1219}
2018-01-01 21:38:27,327 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,335 : INFO : < 200 OK [3324]
2018-01-01 21:38:27,339 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 118, '_0n1': 1219}
2018-01-01 21:38:27,343 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,347 : INFO : < 200 OK [3344]
2018-01-01 21:38:27,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 121, '_0n1': 1219}
2018-01-01 21:38:27,351 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,355 : INFO : < 200 OK [3342]
2018-01-01 21:38:27,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 119, '_0n1': 1219}
2018-01-01 21:38:27,359 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,363 : INFO : < 200 OK [3307]
2018-01-01 21:38:27,367 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 122, '_0n1': 1219}
2018-01-01 21:38:27,371 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,375 : INFO : < 200 OK [3288]
2018-01-01 21:38:27,379 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 120, '_0n1': 1219}
2018-01-01 21:38:27,379 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,387 : INFO : < 200 OK [3322]
2018-01-01 21:38:27,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 123, '_0n1': 1219}
2018-01-01 21:38:27,391 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,395 : INFO : < 200 OK [3332]
2018-01-01 21:38:27,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 141, '_0n1': 1219}
2018-01-01 21:38:27,399 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,403 : INFO : < 200 OK [3329]
2018-01-01 21:38:27,410 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1219}
2018-01-01 21:38:27,413 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,418 : INFO : < 200 OK [3314]
2018-01-01 21:38:27,422 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 142, '_0n1': 1219}
2018-01-01 21:38:27,424 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,428 : INFO : < 200 OK [3332]
2018-01-01 21:38:27,436 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1229, '_0n1': 1222}
2018-01-01 21:38:27,436 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:27,440 : INFO : < 200 OK [3364]
2018-01-01 21:38:27,444 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1250, '_0n1': 1222}
2018-01-01 21:38:27,448 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:27,456 : INFO : < 200 OK [3351]
2018-01-01 21:38:27,460 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1251, '_0n1': 1222}
2018-01-01 21:38:27,460 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:27,464 : INFO : < 200 OK [3354]
2018-01-01 21:38:27,468 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1235, '_0n1': 1222}
2018-01-01 21:38:27,472 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:27,476 : INFO : < 200 OK [3361]
2018-01-01 21:38:27,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1236, '_0n1': 1222}
2018-01-01 21:38:27,480 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:27,488 : INFO : < 200 OK [3362]
2018-01-01 21:38:27,492 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 21, '_0n1': 1222}
2018-01-01 21:38:27,492 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:27,496 : INFO : < 200 OK [3324]
2018-01-01 21:38:27,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 5, '_0n1': 1222}
2018-01-01 21:38:27,500 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:27,508 : INFO : < 200 OK [3313]
2018-01-01 21:38:27,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 1220}
2018-01-01 21:38:27,514 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,519 : INFO : < 200 OK [3317]
2018-01-01 21:38:27,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 143, '_0n1': 1220}
2018-01-01 21:38:27,524 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,528 : INFO : < 200 OK [3316]
2018-01-01 21:38:27,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 126, '_0n1': 1220}
2018-01-01 21:38:27,533 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,538 : INFO : < 200 OK [3345]
2018-01-01 21:38:27,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 144, '_0n1': 1220}
2018-01-01 21:38:27,543 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,548 : INFO : < 200 OK [3331]
2018-01-01 21:38:27,552 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 127, '_0n1': 1223}
2018-01-01 21:38:27,554 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,559 : INFO : < 200 OK [3294]
2018-01-01 21:38:27,562 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 145, '_0n1': 1223}
2018-01-01 21:38:27,564 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,568 : INFO : < 200 OK [3355]
2018-01-01 21:38:27,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 128, '_0n1': 1223}
2018-01-01 21:38:27,573 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,578 : INFO : < 200 OK [3344]

2018-01-01 21:38:27,581 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1223}
2018-01-01 21:38:27,583 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,587 : INFO : < 200 OK [3308]
2018-01-01 21:38:27,591 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 129, '_0n1': 1223}
2018-01-01 21:38:27,594 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,599 : INFO : < 200 OK [3314]
2018-01-01 21:38:27,602 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 147, '_0n1': 1223}
2018-01-01 21:38:27,604 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,608 : INFO : < 200 OK [3332]
2018-01-01 21:38:27,612 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 130, '_0n1': 1223}
2018-01-01 21:38:27,613 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,618 : INFO : < 200 OK [3329]
2018-01-01 21:38:27,622 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 148, '_0n1': 1223}
2018-01-01 21:38:27,624 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,629 : INFO : < 200 OK [3323]
2018-01-01 21:38:27,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 131, '_0n1': 1223}
2018-01-01 21:38:27,634 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,638 : INFO : < 200 OK [3318]
2018-01-01 21:38:27,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 149, '_0n1': 1223}
2018-01-01 21:38:27,643 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,648 : INFO : < 200 OK [3251]
2018-01-01 21:38:27,652 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 132, '_0n1': 1223}
2018-01-01 21:38:27,653 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,658 : INFO : < 200 OK [3345]
2018-01-01 21:38:27,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 150, '_0n1': 1223}
2018-01-01 21:38:27,663 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,667 : INFO : < 200 OK [3325]
2018-01-01 21:38:27,670 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 133, '_0n1': 1223}
2018-01-01 21:38:27,671 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,676 : INFO : < 200 OK [3308]
2018-01-01 21:38:27,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 151, '_0n1': 1223}
2018-01-01 21:38:27,682 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,687 : INFO : < 200 OK [3302]
2018-01-01 21:38:27,690 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 134, '_0n1': 1223}
2018-01-01 21:38:27,692 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,696 : INFO : < 200 OK [3318]
2018-01-01 21:38:27,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 152, '_0n1': 1223}
2018-01-01 21:38:27,702 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,706 : INFO : < 200 OK [3290]
2018-01-01 21:38:27,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 135, '_0n1': 1223}
2018-01-01 21:38:27,711 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,715 : INFO : < 200 OK [3314]
2018-01-01 21:38:27,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1234, '_0n1': 1223}
2018-01-01 21:38:27,721 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:27,725 : INFO : < 200 OK [3307]
2018-01-01 21:38:27,729 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 153, '_0n1': 1223}
2018-01-01 21:38:27,731 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,736 : INFO : < 200 OK [3307]
2018-01-01 21:38:27,739 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1223}
2018-01-01 21:38:27,741 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,745 : INFO : < 200 OK [3344]
2018-01-01 21:38:27,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 154, '_0n1': 1223}
2018-01-01 21:38:27,751 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,756 : INFO : < 200 OK [3334]
2018-01-01 21:38:27,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 137, '_0n1': 1223}
2018-01-01 21:38:27,762 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,766 : INFO : < 200 OK [3320]
2018-01-01 21:38:27,770 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 155, '_0n1': 1223}
2018-01-01 21:38:27,772 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,776 : INFO : < 200 OK [3324]
2018-01-01 21:38:27,779 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 138, '_0n1': 1223}
2018-01-01 21:38:27,781 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,819 : INFO : < 200 OK [3329]
2018-01-01 21:38:27,822 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 156, '_0n1': 1223}
2018-01-01 21:38:27,824 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,828 : INFO : < 200 OK [3320]
2018-01-01 21:38:27,831 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 139, '_0n1': 1223}
2018-01-01 21:38:27,833 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,839 : INFO : < 200 OK [3302]
2018-01-01 21:38:27,843 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1259, '_0n1': 1223}
2018-01-01 21:38:27,845 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:27,849 : INFO : < 200 OK [3355]
2018-01-01 21:38:27,852 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 157, '_0n1': 1223}

2018-01-01 21:38:27,854 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,859 : INFO : < 200 OK [3317]
2018-01-01 21:38:27,863 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 140, '_0n1': 1223}
2018-01-01 21:38:27,864 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,870 : INFO : < 200 OK [3303]
2018-01-01 21:38:27,873 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 158, '_0n1': 1223}
2018-01-01 21:38:27,874 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,879 : INFO : < 200 OK [3286]
2018-01-01 21:38:27,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 161, '_0n1': 1223}
2018-01-01 21:38:27,884 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,889 : INFO : < 200 OK [3327]
2018-01-01 21:38:27,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 159, '_0n1': 1223}
2018-01-01 21:38:27,894 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,899 : INFO : < 200 OK [3300]
2018-01-01 21:38:27,902 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 1223}
2018-01-01 21:38:27,905 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,909 : INFO : < 200 OK [3342]
2018-01-01 21:38:27,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 160, '_0n1': 1223}
2018-01-01 21:38:27,914 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,918 : INFO : < 200 OK [3327]
2018-01-01 21:38:27,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 163, '_0n1': 1223}
2018-01-01 21:38:27,924 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,929 : INFO : < 200 OK [3303]
2018-01-01 21:38:27,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 164, '_0n1': 1223}
2018-01-01 21:38:27,933 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,938 : INFO : < 200 OK [3289]
2018-01-01 21:38:27,941 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 181, '_0n1': 1223}
2018-01-01 21:38:27,943 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,947 : INFO : < 200 OK [3282]
2018-01-01 21:38:27,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 165, '_0n1': 1223}
2018-01-01 21:38:27,952 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,956 : INFO : < 200 OK [3326]
2018-01-01 21:38:27,960 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 182, '_0n1': 1223}
2018-01-01 21:38:27,962 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,967 : INFO : < 200 OK [3288]
2018-01-01 21:38:27,971 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 166, '_0n1': 1223}
2018-01-01 21:38:27,973 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,977 : INFO : < 200 OK [3324]
2018-01-01 21:38:27,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 183, '_0n1': 1223}
2018-01-01 21:38:27,983 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,987 : INFO : < 200 OK [3286]
2018-01-01 21:38:27,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 167, '_0n1': 1223}
2018-01-01 21:38:27,993 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:27,997 : INFO : < 200 OK [3282]
2018-01-01 21:38:28,000 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 184, '_0n1': 1223}
2018-01-01 21:38:28,002 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,007 : INFO : < 200 OK [3307]
2018-01-01 21:38:28,010 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 168, '_0n1': 1223}
2018-01-01 21:38:28,011 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,017 : INFO : < 200 OK [3352]
2018-01-01 21:38:28,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 185, '_0n1': 1223}
2018-01-01 21:38:28,023 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,027 : INFO : < 200 OK [3311]
2018-01-01 21:38:28,031 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 169, '_0n1': 1223}
2018-01-01 21:38:28,032 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,037 : INFO : < 200 OK [3296]
2018-01-01 21:38:28,041 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 186, '_0n1': 1223}
2018-01-01 21:38:28,042 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,048 : INFO : < 200 OK [3300]
2018-01-01 21:38:28,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 170, '_0n1': 1223}
2018-01-01 21:38:28,052 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,058 : INFO : < 200 OK [3320]
2018-01-01 21:38:28,062 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 187, '_0n1': 1223}
2018-01-01 21:38:28,063 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,070 : INFO : < 200 OK [3290]
2018-01-01 21:38:28,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 171, '_0n1': 1223}
2018-01-01 21:38:28,077 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,082 : INFO : < 200 OK [3348]
2018-01-01 21:38:28,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 188, '_0n1': 1223}
2018-01-01 21:38:28,087 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,092 : INFO : < 200 OK [3337]
2018-01-01 21:38:28,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 172, '_0n1': 1223}
2018-01-01 21:38:28,097 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:28,102 : INFO : < 200 OK [3310]
2018-01-01 21:38:28,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 189, '_0n1': 1223}
2018-01-01 21:38:28,107 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,111 : INFO : < 200 OK [3285]
2018-01-01 21:38:28,114 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 16, '_0n1': 1223}
2018-01-01 21:38:28,116 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,121 : INFO : < 200 OK [3327]
2018-01-01 21:38:28,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 173, '_0n1': 1223}
2018-01-01 21:38:28,126 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,131 : INFO : < 200 OK [3292]
2018-01-01 21:38:28,134 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 190, '_0n1': 1223}
2018-01-01 21:38:28,136 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,141 : INFO : < 200 OK [3348]
2018-01-01 21:38:28,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 174, '_0n1': 1223}
2018-01-01 21:38:28,145 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,150 : INFO : < 200 OK [3353]
2018-01-01 21:38:28,153 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 191, '_0n1': 1223}
2018-01-01 21:38:28,154 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,159 : INFO : < 200 OK [3279]
2018-01-01 21:38:28,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 175, '_0n1': 1223}
2018-01-01 21:38:28,165 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,170 : INFO : < 200 OK [3343]
2018-01-01 21:38:28,173 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 192, '_0n1': 1223}
2018-01-01 21:38:28,175 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,180 : INFO : < 200 OK [3346]
2018-01-01 21:38:28,184 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 176, '_0n1': 1223}
2018-01-01 21:38:28,185 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,190 : INFO : < 200 OK [3282]
2018-01-01 21:38:28,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 193, '_0n1': 1223}
2018-01-01 21:38:28,196 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,200 : INFO : < 200 OK [3299]
2018-01-01 21:38:28,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 177, '_0n1': 1223}
2018-01-01 21:38:28,206 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,211 : INFO : < 200 OK [3311]
2018-01-01 21:38:28,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 194, '_0n1': 1241}
2018-01-01 21:38:28,217 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,222 : INFO : < 200 OK [3295]
2018-01-01 21:38:28,226 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 129, '_0n1': 1241}
2018-01-01 21:38:28,228 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,233 : INFO : < 200 OK [3318]
2018-01-01 21:38:28,237 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 55, '_0n1': 1241}
2018-01-01 21:38:28,239 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,244 : INFO : < 200 OK [3303]
2018-01-01 21:38:28,248 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 178, '_0n1': 1241}
2018-01-01 21:38:28,250 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,255 : INFO : < 200 OK [3324]
2018-01-01 21:38:28,259 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 132, '_0n1': 1241}
2018-01-01 21:38:28,263 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,270 : INFO : < 200 OK [3349]
2018-01-01 21:38:28,274 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 195, '_0n1': 1241}
2018-01-01 21:38:28,276 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,281 : INFO : < 200 OK [3371]
2018-01-01 21:38:28,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 75, '_0n1': 1241}
2018-01-01 21:38:28,286 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,290 : INFO : < 200 OK [3317]
2018-01-01 21:38:28,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 179, '_0n1': 1241}
2018-01-01 21:38:28,296 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,300 : INFO : < 200 OK [3306]
2018-01-01 21:38:28,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1241}
2018-01-01 21:38:28,306 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,310 : INFO : < 200 OK [3279]
2018-01-01 21:38:28,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1232, '_0n1': 1241}
2018-01-01 21:38:28,315 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:28,320 : INFO : < 200 OK [3334]
2018-01-01 21:38:28,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 180, '_0n1': 1241}
2018-01-01 21:38:28,325 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,329 : INFO : < 200 OK [3301]
2018-01-01 21:38:28,333 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 197, '_0n1': 1241}
2018-01-01 21:38:28,334 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,340 : INFO : < 200 OK [3298]
2018-01-01 21:38:28,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 201, '_0n1': 1241}
2018-01-01 21:38:28,345 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,349 : INFO : < 200 OK [3303]

2018-01-01 21:38:28,353 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1241}
2018-01-01 21:38:28,355 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,359 : INFO : < 200 OK [3348]
2018-01-01 21:38:28,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 198, '_0n1': 1241}
2018-01-01 21:38:28,365 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,370 : INFO : < 200 OK [3347]
2018-01-01 21:38:28,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 202, '_0n1': 1241}
2018-01-01 21:38:28,376 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,380 : INFO : < 200 OK [3296]
2018-01-01 21:38:28,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1260, '_0n1': 1241}
2018-01-01 21:38:28,386 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:28,390 : INFO : < 200 OK [3316]
2018-01-01 21:38:28,394 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 199, '_0n1': 1241}
2018-01-01 21:38:28,397 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,401 : INFO : < 200 OK [3308]
2018-01-01 21:38:28,405 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 203, '_0n1': 1241}
2018-01-01 21:38:28,407 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,411 : INFO : < 200 OK [3332]
2018-01-01 21:38:28,415 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 200, '_0n1': 1241}
2018-01-01 21:38:28,418 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,422 : INFO : < 200 OK [3337]
2018-01-01 21:38:28,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 204, '_0n1': 1241}
2018-01-01 21:38:28,429 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,434 : INFO : < 200 OK [3334]
2018-01-01 21:38:28,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 221, '_0n1': 1241}
2018-01-01 21:38:28,439 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,446 : INFO : < 200 OK [3283]
2018-01-01 21:38:28,450 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 205, '_0n1': 1241}
2018-01-01 21:38:28,454 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,459 : INFO : < 200 OK [3286]
2018-01-01 21:38:28,463 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 222, '_0n1': 1241}
2018-01-01 21:38:28,465 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,470 : INFO : < 200 OK [3303]
2018-01-01 21:38:28,474 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 7, '_0n1': 1241}
2018-01-01 21:38:28,476 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:28,481 : INFO : < 200 OK [3282]
2018-01-01 21:38:28,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 206, '_0n1': 1241}
2018-01-01 21:38:28,486 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,491 : INFO : < 200 OK [3300]
2018-01-01 21:38:28,495 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 223, '_0n1': 1241}
2018-01-01 21:38:28,497 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,502 : INFO : < 200 OK [3263]
2018-01-01 21:38:28,506 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 207, '_0n1': 1241}
2018-01-01 21:38:28,508 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,512 : INFO : < 200 OK [3285]
2018-01-01 21:38:28,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 243, '_0n1': 1241}
2018-01-01 21:38:28,516 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,520 : INFO : < 200 OK [3322]
2018-01-01 21:38:28,524 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 208, '_0n1': 1241}
2018-01-01 21:38:28,526 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,530 : INFO : < 200 OK [3338]
2018-01-01 21:38:28,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 244, '_0n1': 1241}
2018-01-01 21:38:28,534 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,539 : INFO : < 200 OK [3342]
2018-01-01 21:38:28,542 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1241}
2018-01-01 21:38:28,544 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,548 : INFO : < 200 OK [3311]
2018-01-01 21:38:28,551 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 245, '_0n1': 1241}
2018-01-01 21:38:28,553 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,557 : INFO : < 200 OK [3371]
2018-01-01 21:38:28,559 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 210, '_0n1': 1241}
2018-01-01 21:38:28,561 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,565 : INFO : < 200 OK [3332]
2018-01-01 21:38:28,566 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 246, '_0n1': 1241}
2018-01-01 21:38:28,570 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,574 : INFO : < 200 OK [3340]
2018-01-01 21:38:28,574 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 45, '_0n1': 1241}
2018-01-01 21:38:28,578 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,582 : INFO : < 200 OK [3284]
2018-01-01 21:38:28,586 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 211, '_0n1': 1241}
2018-01-01 21:38:28,586 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,590 : INFO : < 200 OK [3369]
2018-01-01 21:38:28,594 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 247, '_0n1': 1241}

2018-01-01 21:38:28,594 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,598 : INFO : < 200 OK [3314]
2018-01-01 21:38:28,602 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 212, '_0n1': 1241}
2018-01-01 21:38:28,606 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,610 : INFO : < 200 OK [3345]
2018-01-01 21:38:28,614 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 248, '_0n1': 1241}
2018-01-01 21:38:28,614 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,618 : INFO : < 200 OK [3331]
2018-01-01 21:38:28,622 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1241}
2018-01-01 21:38:28,626 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,630 : INFO : < 200 OK [3326]
2018-01-01 21:38:28,634 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 213, '_0n1': 1224}
2018-01-01 21:38:28,638 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,642 : INFO : < 200 OK [3309]
2018-01-01 21:38:28,646 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 249, '_0n1': 1224}
2018-01-01 21:38:28,646 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,655 : INFO : < 200 OK [3330]
2018-01-01 21:38:28,658 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 214, '_0n1': 1224}
2018-01-01 21:38:28,660 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,663 : INFO : < 200 OK [3300]
2018-01-01 21:38:28,666 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1246, '_0n1': 1224}
2018-01-01 21:38:28,666 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:28,670 : INFO : < 200 OK [3289]
2018-01-01 21:38:28,674 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 250, '_0n1': 1224}
2018-01-01 21:38:28,674 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,678 : INFO : < 200 OK [3313]
2018-01-01 21:38:28,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 215, '_0n1': 1224}
2018-01-01 21:38:28,686 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,690 : INFO : < 200 OK [3272]
2018-01-01 21:38:28,690 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 251, '_0n1': 1224}
2018-01-01 21:38:28,694 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,698 : INFO : < 200 OK [3314]
2018-01-01 21:38:28,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 69, '_0n1': 1224}
2018-01-01 21:38:28,702 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,706 : INFO : < 200 OK [3346]
2018-01-01 21:38:28,706 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 216, '_0n1': 1224}
2018-01-01 21:38:28,710 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,714 : INFO : < 200 OK [3314]
2018-01-01 21:38:28,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 252, '_0n1': 1224}
2018-01-01 21:38:28,718 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,722 : INFO : < 200 OK [3343]
2018-01-01 21:38:28,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 217, '_0n1': 1224}
2018-01-01 21:38:28,726 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,730 : INFO : < 200 OK [3316]
2018-01-01 21:38:28,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 1224}
2018-01-01 21:38:28,734 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,742 : INFO : < 200 OK [3298]
2018-01-01 21:38:28,742 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 218, '_0n1': 1224}
2018-01-01 21:38:28,746 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,751 : INFO : < 200 OK [3319]
2018-01-01 21:38:28,754 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 1224}
2018-01-01 21:38:28,755 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,759 : INFO : < 200 OK [3290]
2018-01-01 21:38:28,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 254, '_0n1': 1224}
2018-01-01 21:38:28,765 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,770 : INFO : < 200 OK [3335]
2018-01-01 21:38:28,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 219, '_0n1': 1224}
2018-01-01 21:38:28,774 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,782 : INFO : < 200 OK [3285]
2018-01-01 21:38:28,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 58, '_0n1': 1224}
2018-01-01 21:38:28,786 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,794 : INFO : < 200 OK [3327]
2018-01-01 21:38:28,794 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 255, '_0n1': 1224}
2018-01-01 21:38:28,798 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,802 : INFO : < 200 OK [3311]
2018-01-01 21:38:28,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 77, '_0n1': 1224}
2018-01-01 21:38:28,810 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,814 : INFO : < 200 OK [3344]
2018-01-01 21:38:28,818 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 220, '_0n1': 1224}
2018-01-01 21:38:28,822 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,826 : INFO : < 200 OK [3279]
2018-01-01 21:38:28,830 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 81, '_0n1': 1224}
2018-01-01 21:38:28,830 : INFO : > POST http://localhost:7474/db/data/cypher [182]

2018-01-01 21:38:28,838 : INFO : < 200 OK [3298]
2018-01-01 21:38:28,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 82, '_0n1': 1224}
2018-01-01 21:38:28,846 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,850 : INFO : < 200 OK [3299]
2018-01-01 21:38:28,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 80, '_0n1': 1224}
2018-01-01 21:38:28,857 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,863 : INFO : < 200 OK [3302]
2018-01-01 21:38:28,865 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 256, '_0n1': 1224}
2018-01-01 21:38:28,867 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,871 : INFO : < 200 OK [3294]
2018-01-01 21:38:28,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 260, '_0n1': 1224}
2018-01-01 21:38:28,879 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,883 : INFO : < 200 OK [3325]
2018-01-01 21:38:28,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 257, '_0n1': 1224}
2018-01-01 21:38:28,887 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,895 : INFO : < 200 OK [3338]
2018-01-01 21:38:28,899 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 83, '_0n1': 1224}
2018-01-01 21:38:28,899 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,907 : INFO : < 200 OK [3303]
2018-01-01 21:38:28,911 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 86, '_0n1': 1224}
2018-01-01 21:38:28,911 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:28,915 : INFO : < 200 OK [3350]
2018-01-01 21:38:28,919 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 261, '_0n1': 1224}
2018-01-01 21:38:28,923 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,927 : INFO : < 200 OK [3298]
2018-01-01 21:38:28,931 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 258, '_0n1': 1224}
2018-01-01 21:38:28,931 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,935 : INFO : < 200 OK [3335]
2018-01-01 21:38:28,939 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 262, '_0n1': 1224}
2018-01-01 21:38:28,943 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,947 : INFO : < 200 OK [3326]
2018-01-01 21:38:28,953 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 1224}
2018-01-01 21:38:28,955 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,959 : INFO : < 200 OK [3319]
2018-01-01 21:38:28,962 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 259, '_0n1': 1224}
2018-01-01 21:38:28,964 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,966 : INFO : < 200 OK [3309]
2018-01-01 21:38:28,966 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 263, '_0n1': 1224}
2018-01-01 21:38:28,970 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,974 : INFO : < 200 OK [3299]
2018-01-01 21:38:28,978 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 280, '_0n1': 1224}
2018-01-01 21:38:28,978 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,986 : INFO : < 200 OK [3345]
2018-01-01 21:38:28,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 264, '_0n1': 1224}
2018-01-01 21:38:28,994 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:28,998 : INFO : < 200 OK [3313]
2018-01-01 21:38:29,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 281, '_0n1': 1224}
2018-01-01 21:38:29,002 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,010 : INFO : < 200 OK [3293]
2018-01-01 21:38:29,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 265, '_0n1': 1224}
2018-01-01 21:38:29,014 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,018 : INFO : < 200 OK [3327]
2018-01-01 21:38:29,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 282, '_0n1': 1224}
2018-01-01 21:38:29,026 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,030 : INFO : < 200 OK [3259]
2018-01-01 21:38:29,034 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1224}
2018-01-01 21:38:29,038 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,042 : INFO : < 200 OK [3317]
2018-01-01 21:38:29,046 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 20, '_0n1': 1224}
2018-01-01 21:38:29,050 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:29,056 : INFO : < 200 OK [3313]
2018-01-01 21:38:29,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 283, '_0n1': 1224}
2018-01-01 21:38:29,063 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,067 : INFO : < 200 OK [3285]
2018-01-01 21:38:29,071 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 94, '_0n1': 1224}
2018-01-01 21:38:29,071 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:29,079 : INFO : < 200 OK [3290]
2018-01-01 21:38:29,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 267, '_0n1': 1224}
2018-01-01 21:38:29,083 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,087 : INFO : < 200 OK [3318]
2018-01-01 21:38:29,091 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 284, '_0n1': 1224}
2018-01-01 21:38:29,091 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:29,095 : INFO : < 200 OK [3333]
2018-01-01 21:38:29,099 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 268, '_0n1': 1224}
2018-01-01 21:38:29,103 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,103 : INFO : < 200 OK [3281]
2018-01-01 21:38:29,107 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 6, '_0n1': 1224}
2018-01-01 21:38:29,111 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:29,115 : INFO : < 200 OK [3300]
2018-01-01 21:38:29,115 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 285, '_0n1': 1224}
2018-01-01 21:38:29,119 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,123 : INFO : < 200 OK [3310]
2018-01-01 21:38:29,123 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 269, '_0n1': 1224}
2018-01-01 21:38:29,127 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,131 : INFO : < 200 OK [3278]
2018-01-01 21:38:29,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 286, '_0n1': 1224}
2018-01-01 21:38:29,135 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,139 : INFO : < 200 OK [3357]
2018-01-01 21:38:29,143 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 270, '_0n1': 1224}
2018-01-01 21:38:29,143 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,147 : INFO : < 200 OK [3333]
2018-01-01 21:38:29,152 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 287, '_0n1': 1224}
2018-01-01 21:38:29,153 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,157 : INFO : < 200 OK [3282]
2018-01-01 21:38:29,160 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 271, '_0n1': 1224}
2018-01-01 21:38:29,161 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,165 : INFO : < 200 OK [3334]
2018-01-01 21:38:29,166 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 288, '_0n1': 1224}
2018-01-01 21:38:29,171 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,175 : INFO : < 200 OK [3290]
2018-01-01 21:38:29,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 272, '_0n1': 1224}
2018-01-01 21:38:29,179 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,187 : INFO : < 200 OK [3336]
2018-01-01 21:38:29,187 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 33, '_0n1': 1224}
2018-01-01 21:38:29,191 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:29,195 : INFO : < 200 OK [3275]
2018-01-01 21:38:29,199 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 289, '_0n1': 1224}
2018-01-01 21:38:29,199 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,203 : INFO : < 200 OK [3316]
2018-01-01 21:38:29,207 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 273, '_0n1': 1224}
2018-01-01 21:38:29,207 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,215 : INFO : < 200 OK [3308]
2018-01-01 21:38:29,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 290, '_0n1': 1224}
2018-01-01 21:38:29,219 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,223 : INFO : < 200 OK [3298]
2018-01-01 21:38:29,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 35, '_0n1': 1224}
2018-01-01 21:38:29,227 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:29,231 : INFO : < 200 OK [3295]
2018-01-01 21:38:29,235 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 274, '_0n1': 1224}
2018-01-01 21:38:29,235 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,239 : INFO : < 200 OK [3332]
2018-01-01 21:38:29,243 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 37, '_0n1': 1224}
2018-01-01 21:38:29,243 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:29,247 : INFO : < 200 OK [3296]
2018-01-01 21:38:29,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 291, '_0n1': 1224}
2018-01-01 21:38:29,253 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,256 : INFO : < 200 OK [3306]
2018-01-01 21:38:29,260 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 275, '_0n1': 1224}
2018-01-01 21:38:29,261 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,266 : INFO : < 200 OK [3311]
2018-01-01 21:38:29,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 292, '_0n1': 1224}
2018-01-01 21:38:29,271 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,275 : INFO : < 200 OK [3278]
2018-01-01 21:38:29,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 276, '_0n1': 1242}
2018-01-01 21:38:29,279 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,283 : INFO : < 200 OK [3293]
2018-01-01 21:38:29,283 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1242}
2018-01-01 21:38:29,287 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,291 : INFO : < 200 OK [3326]
2018-01-01 21:38:29,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1242}
2018-01-01 21:38:29,295 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,299 : INFO : < 200 OK [3354]
2018-01-01 21:38:29,303 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 128, '_0n1': 1242}
2018-01-01 21:38:29,303 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,307 : INFO : < 200 OK [3352]

2018-01-01 21:38:29,311 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 1242}
2018-01-01 21:38:29,311 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,319 : INFO : < 200 OK [3335]
2018-01-01 21:38:29,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1242}
2018-01-01 21:38:29,323 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,331 : INFO : < 200 OK [3316]
2018-01-01 21:38:29,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 278, '_0n1': 1242}
2018-01-01 21:38:29,335 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,343 : INFO : < 200 OK [3355]
2018-01-01 21:38:29,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 1242}
2018-01-01 21:38:29,347 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,353 : INFO : < 200 OK [3334]
2018-01-01 21:38:29,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1242}
2018-01-01 21:38:29,360 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,365 : INFO : < 200 OK [3317]
2018-01-01 21:38:29,367 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 296, '_0n1': 1242}
2018-01-01 21:38:29,367 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,375 : INFO : < 200 OK [3345]
2018-01-01 21:38:29,379 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 130, '_0n1': 1242}
2018-01-01 21:38:29,379 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,383 : INFO : < 200 OK [3337]
2018-01-01 21:38:29,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 300, '_0n1': 1242}
2018-01-01 21:38:29,391 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,395 : INFO : < 200 OK [3292]
2018-01-01 21:38:29,399 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 297, '_0n1': 1242}
2018-01-01 21:38:29,399 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,407 : INFO : < 200 OK [3361]
2018-01-01 21:38:29,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 301, '_0n1': 1242}
2018-01-01 21:38:29,411 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,415 : INFO : < 200 OK [3301]
2018-01-01 21:38:29,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 298, '_0n1': 1242}
2018-01-01 21:38:29,423 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,427 : INFO : < 200 OK [3332]
2018-01-01 21:38:29,431 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 150, '_0n1': 1242}
2018-01-01 21:38:29,431 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,435 : INFO : < 200 OK [3333]
2018-01-01 21:38:29,439 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 302, '_0n1': 1242}
2018-01-01 21:38:29,439 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,443 : INFO : < 200 OK [3340]
2018-01-01 21:38:29,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 299, '_0n1': 1242}
2018-01-01 21:38:29,452 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,456 : INFO : < 200 OK [3320]
2018-01-01 21:38:29,462 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1242}
2018-01-01 21:38:29,464 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,468 : INFO : < 200 OK [3335]
2018-01-01 21:38:29,471 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 320, '_0n1': 1242}
2018-01-01 21:38:29,473 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,477 : INFO : < 200 OK [3302]
2018-01-01 21:38:29,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 304, '_0n1': 1242}
2018-01-01 21:38:29,482 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,487 : INFO : < 200 OK [3296]
2018-01-01 21:38:29,491 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 321, '_0n1': 1242}
2018-01-01 21:38:29,492 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,497 : INFO : < 200 OK [3348]
2018-01-01 21:38:29,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 1242}
2018-01-01 21:38:29,502 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,507 : INFO : < 200 OK [3334]
2018-01-01 21:38:29,511 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 154, '_0n1': 1242}
2018-01-01 21:38:29,513 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,518 : INFO : < 200 OK [3342]
2018-01-01 21:38:29,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 322, '_0n1': 1242}
2018-01-01 21:38:29,526 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,531 : INFO : < 200 OK [3326]
2018-01-01 21:38:29,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 155, '_0n1': 1242}
2018-01-01 21:38:29,537 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,541 : INFO : < 200 OK [3332]
2018-01-01 21:38:29,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1242}
2018-01-01 21:38:29,546 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,552 : INFO : < 200 OK [3315]
2018-01-01 21:38:29,556 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 1242}
2018-01-01 21:38:29,558 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,562 : INFO : < 200 OK [3349]
2018-01-01 21:38:29,567 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 307, '_0n1': 1242}

2018-01-01 21:38:29,569 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,573 : INFO : < 200 OK [3342]
2018-01-01 21:38:29,577 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 324, '_0n1': 1242}
2018-01-01 21:38:29,578 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,584 : INFO : < 200 OK [3305]
2018-01-01 21:38:29,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 308, '_0n1': 1242}
2018-01-01 21:38:29,590 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,595 : INFO : < 200 OK [3311]
2018-01-01 21:38:29,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 1242}
2018-01-01 21:38:29,601 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,605 : INFO : < 200 OK [3301]
2018-01-01 21:38:29,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1242}
2018-01-01 21:38:29,611 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,615 : INFO : < 200 OK [3293]
2018-01-01 21:38:29,622 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 1242}
2018-01-01 21:38:29,624 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,628 : INFO : < 200 OK [3334]
2018-01-01 21:38:29,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 310, '_0n1': 1242}
2018-01-01 21:38:29,634 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,638 : INFO : < 200 OK [3341]
2018-01-01 21:38:29,642 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 327, '_0n1': 1242}
2018-01-01 21:38:29,644 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,648 : INFO : < 200 OK [3359]
2018-01-01 21:38:29,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 311, '_0n1': 1242}
2018-01-01 21:38:29,653 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,658 : INFO : < 200 OK [3331]
2018-01-01 21:38:29,662 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 328, '_0n1': 1242}
2018-01-01 21:38:29,663 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,668 : INFO : < 200 OK [3327]
2018-01-01 21:38:29,671 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 312, '_0n1': 1242}
2018-01-01 21:38:29,673 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,678 : INFO : < 200 OK [3368]
2018-01-01 21:38:29,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 206, '_0n1': 1242}
2018-01-01 21:38:29,684 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,688 : INFO : < 200 OK [3304]
2018-01-01 21:38:29,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 329, '_0n1': 1242}
2018-01-01 21:38:29,694 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,698 : INFO : < 200 OK [3340]
2018-01-01 21:38:29,702 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1242}
2018-01-01 21:38:29,704 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,716 : INFO : < 200 OK [3309]
2018-01-01 21:38:29,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 330, '_0n1': 1242}
2018-01-01 21:38:29,725 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,730 : INFO : < 200 OK [3327]
2018-01-01 21:38:29,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 314, '_0n1': 1242}
2018-01-01 21:38:29,735 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,742 : INFO : < 200 OK [3311]
2018-01-01 21:38:29,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 331, '_0n1': 1242}
2018-01-01 21:38:29,747 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,752 : INFO : < 200 OK [3312]
2018-01-01 21:38:29,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 315, '_0n1': 1242}
2018-01-01 21:38:29,760 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,765 : INFO : < 200 OK [3298]
2018-01-01 21:38:29,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 332, '_0n1': 1242}
2018-01-01 21:38:29,772 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,777 : INFO : < 200 OK [3312]
2018-01-01 21:38:29,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 316, '_0n1': 1242}
2018-01-01 21:38:29,783 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,787 : INFO : < 200 OK [3314]
2018-01-01 21:38:29,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 333, '_0n1': 1242}
2018-01-01 21:38:29,793 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,798 : INFO : < 200 OK [3317]
2018-01-01 21:38:29,801 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 317, '_0n1': 1242}
2018-01-01 21:38:29,803 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,808 : INFO : < 200 OK [3349]
2018-01-01 21:38:29,812 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 334, '_0n1': 1242}
2018-01-01 21:38:29,814 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,819 : INFO : < 200 OK [3306]
2018-01-01 21:38:29,822 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 318, '_0n1': 1242}
2018-01-01 21:38:29,825 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,829 : INFO : < 200 OK [3316]
2018-01-01 21:38:29,833 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 1242}
2018-01-01 21:38:29,835 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:29,840 : INFO : < 200 OK [3319]
2018-01-01 21:38:29,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 61, '_0n1': 1242}
2018-01-01 21:38:29,847 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:29,851 : INFO : < 200 OK [3300]
2018-01-01 21:38:29,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 319, '_0n1': 1242}
2018-01-01 21:38:29,856 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,861 : INFO : < 200 OK [3298]
2018-01-01 21:38:29,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 336, '_0n1': 1242}
2018-01-01 21:38:29,866 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,870 : INFO : < 200 OK [3321]
2018-01-01 21:38:29,874 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1242}
2018-01-01 21:38:29,876 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,880 : INFO : < 200 OK [3317]
2018-01-01 21:38:29,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 337, '_0n1': 1242}
2018-01-01 21:38:29,886 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,890 : INFO : < 200 OK [3311]
2018-01-01 21:38:29,893 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 341, '_0n1': 1242}
2018-01-01 21:38:29,896 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,900 : INFO : < 200 OK [3302]
2018-01-01 21:38:29,903 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 338, '_0n1': 1242}
2018-01-01 21:38:29,905 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,910 : INFO : < 200 OK [3305]
2018-01-01 21:38:29,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 342, '_0n1': 1242}
2018-01-01 21:38:29,915 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,919 : INFO : < 200 OK [3323]
2018-01-01 21:38:29,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 339, '_0n1': 1242}
2018-01-01 21:38:29,924 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,939 : INFO : < 200 OK [3294]
2018-01-01 21:38:29,942 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 1242}
2018-01-01 21:38:29,944 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:29,949 : INFO : < 200 OK [3343]
2018-01-01 21:38:29,953 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1248, '_0n1': 1225}
2018-01-01 21:38:29,954 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:29,959 : INFO : < 200 OK [3339]
2018-01-01 21:38:29,963 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1253, '_0n1': 1225}
2018-01-01 21:38:29,965 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:29,972 : INFO : < 200 OK [3334]
2018-01-01 21:38:29,976 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1240, '_0n1': 1225}
2018-01-01 21:38:29,978 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:29,983 : INFO : < 200 OK [3322]
2018-01-01 21:38:29,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1301, '_0n1': 1225}
2018-01-01 21:38:29,989 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:29,994 : INFO : < 200 OK [3332]
2018-01-01 21:38:29,998 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1302, '_0n1': 1225}
2018-01-01 21:38:30,000 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:30,005 : INFO : < 200 OK [3340]
2018-01-01 21:38:30,009 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1243}
2018-01-01 21:38:30,011 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,016 : INFO : < 200 OK [3318]
2018-01-01 21:38:30,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 344, '_0n1': 1243}
2018-01-01 21:38:30,025 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,030 : INFO : < 200 OK [3337]
2018-01-01 21:38:30,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 252, '_0n1': 1243}
2018-01-01 21:38:30,036 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,041 : INFO : < 200 OK [3355]
2018-01-01 21:38:30,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 1243}
2018-01-01 21:38:30,047 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,051 : INFO : < 200 OK [3297]
2018-01-01 21:38:30,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 345, '_0n1': 1243}
2018-01-01 21:38:30,058 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,063 : INFO : < 200 OK [3317]
2018-01-01 21:38:30,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 1243}
2018-01-01 21:38:30,069 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,073 : INFO : < 200 OK [3297]
2018-01-01 21:38:30,076 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 1243}
2018-01-01 21:38:30,078 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,083 : INFO : < 200 OK [3289]
2018-01-01 21:38:30,086 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 1243}
2018-01-01 21:38:30,088 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,093 : INFO : < 200 OK [3293]
2018-01-01 21:38:30,096 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 347, '_0n1': 1243}
2018-01-01 21:38:30,099 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:30,106 : INFO : < 200 OK [3300]
2018-01-01 21:38:30,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 1243}
2018-01-01 21:38:30,112 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,117 : INFO : < 200 OK [3310]
2018-01-01 21:38:30,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 364, '_0n1': 1243}
2018-01-01 21:38:30,123 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,127 : INFO : < 200 OK [3323]
2018-01-01 21:38:30,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 254, '_0n1': 1243}
2018-01-01 21:38:30,132 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,137 : INFO : < 200 OK [3347]
2018-01-01 21:38:30,140 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 348, '_0n1': 1243}
2018-01-01 21:38:30,142 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,147 : INFO : < 200 OK [3290]
2018-01-01 21:38:30,150 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 1243}
2018-01-01 21:38:30,152 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,158 : INFO : < 200 OK [3324]
2018-01-01 21:38:30,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 349, '_0n1': 1243}
2018-01-01 21:38:30,163 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,168 : INFO : < 200 OK [3332]
2018-01-01 21:38:30,171 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 1243}
2018-01-01 21:38:30,173 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,178 : INFO : < 200 OK [3293]
2018-01-01 21:38:30,182 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 350, '_0n1': 1243}
2018-01-01 21:38:30,183 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,189 : INFO : < 200 OK [3342]
2018-01-01 21:38:30,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 367, '_0n1': 1243}
2018-01-01 21:38:30,194 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,199 : INFO : < 200 OK [3326]
2018-01-01 21:38:30,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1243}
2018-01-01 21:38:30,204 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,209 : INFO : < 200 OK [3296]
2018-01-01 21:38:30,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 368, '_0n1': 1243}
2018-01-01 21:38:30,215 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,220 : INFO : < 200 OK [3354]
2018-01-01 21:38:30,223 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 352, '_0n1': 1243}
2018-01-01 21:38:30,225 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,229 : INFO : < 200 OK [3341]
2018-01-01 21:38:30,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 369, '_0n1': 1243}
2018-01-01 21:38:30,234 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,239 : INFO : < 200 OK [3383]
2018-01-01 21:38:30,242 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 353, '_0n1': 1243}
2018-01-01 21:38:30,244 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,248 : INFO : < 200 OK [3294]
2018-01-01 21:38:30,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 370, '_0n1': 1243}
2018-01-01 21:38:30,256 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,260 : INFO : < 200 OK [3333]
2018-01-01 21:38:30,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 280, '_0n1': 1243}
2018-01-01 21:38:30,265 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,269 : INFO : < 200 OK [3357]
2018-01-01 21:38:30,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 354, '_0n1': 1243}
2018-01-01 21:38:30,275 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,279 : INFO : < 200 OK [3336]
2018-01-01 21:38:30,283 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 371, '_0n1': 1243}
2018-01-01 21:38:30,285 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,289 : INFO : < 200 OK [3303]
2018-01-01 21:38:30,293 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 286, '_0n1': 1243}
2018-01-01 21:38:30,295 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,300 : INFO : < 200 OK [3369]
2018-01-01 21:38:30,305 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 355, '_0n1': 1243}
2018-01-01 21:38:30,307 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,311 : INFO : < 200 OK [3307]
2018-01-01 21:38:30,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 372, '_0n1': 1243}
2018-01-01 21:38:30,317 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,319 : INFO : < 200 OK [3319]
2018-01-01 21:38:30,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 356, '_0n1': 1243}
2018-01-01 21:38:30,323 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,331 : INFO : < 200 OK [3295]
2018-01-01 21:38:30,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 290, '_0n1': 1243}
2018-01-01 21:38:30,335 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,339 : INFO : < 200 OK [3310]
2018-01-01 21:38:30,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 373, '_0n1': 1243}
2018-01-01 21:38:30,343 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,347 : INFO : < 200 OK [3358]

2018-01-01 21:38:30,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 357, '_0n1': 1243}
2018-01-01 21:38:30,355 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,359 : INFO : < 200 OK [3365]
2018-01-01 21:38:30,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 1243}
2018-01-01 21:38:30,363 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,367 : INFO : < 200 OK [3298]
2018-01-01 21:38:30,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1237, '_0n1': 1226}
2018-01-01 21:38:30,371 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:30,375 : INFO : < 200 OK [3338]
2018-01-01 21:38:30,379 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1256, '_0n1': 1226}
2018-01-01 21:38:30,379 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:30,383 : INFO : < 200 OK [3340]
2018-01-01 21:38:30,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 4, '_0n1': 1226}
2018-01-01 21:38:30,387 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:30,391 : INFO : < 200 OK [3295]
2018-01-01 21:38:30,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 24, '_0n1': 1226}
2018-01-01 21:38:30,399 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,405 : INFO : < 200 OK [3300]
2018-01-01 21:38:30,409 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 28, '_0n1': 1226}
2018-01-01 21:38:30,411 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,415 : INFO : < 200 OK [3281]
2018-01-01 21:38:30,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 30, '_0n1': 1226}
2018-01-01 21:38:30,419 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,423 : INFO : < 200 OK [3318]
2018-01-01 21:38:30,427 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 36, '_0n1': 1226}
2018-01-01 21:38:30,427 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,431 : INFO : < 200 OK [3295]
2018-01-01 21:38:30,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 41, '_0n1': 1226}
2018-01-01 21:38:30,439 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,443 : INFO : < 200 OK [3300]
2018-01-01 21:38:30,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 358, '_0n1': 1244}
2018-01-01 21:38:30,447 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,451 : INFO : < 200 OK [3278]
2018-01-01 21:38:30,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 1244}
2018-01-01 21:38:30,455 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,459 : INFO : < 200 OK [3313]
2018-01-01 21:38:30,463 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 1244}
2018-01-01 21:38:30,463 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,467 : INFO : < 200 OK [3309]
2018-01-01 21:38:30,471 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 67, '_0n1': 1244}
2018-01-01 21:38:30,471 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,479 : INFO : < 200 OK [3362]
2018-01-01 21:38:30,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 375, '_0n1': 1244}
2018-01-01 21:38:30,483 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,487 : INFO : < 200 OK [3328]
2018-01-01 21:38:30,491 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 359, '_0n1': 1244}
2018-01-01 21:38:30,491 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,495 : INFO : < 200 OK [3298]
2018-01-01 21:38:30,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 51, '_0n1': 1244}
2018-01-01 21:38:30,499 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,503 : INFO : < 200 OK [3270]
2018-01-01 21:38:30,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 1244}
2018-01-01 21:38:30,510 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,515 : INFO : < 200 OK [3320]
2018-01-01 21:38:30,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 380, '_0n1': 1244}
2018-01-01 21:38:30,519 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,519 : INFO : < 200 OK [3313]
2018-01-01 21:38:30,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1244}
2018-01-01 21:38:30,527 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,535 : INFO : < 200 OK [3353]
2018-01-01 21:38:30,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 381, '_0n1': 1244}
2018-01-01 21:38:30,539 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,543 : INFO : < 200 OK [3328]
2018-01-01 21:38:30,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 378, '_0n1': 1244}
2018-01-01 21:38:30,547 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,551 : INFO : < 200 OK [3288]
2018-01-01 21:38:30,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 382, '_0n1': 1244}
2018-01-01 21:38:30,555 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,563 : INFO : < 200 OK [3317]
2018-01-01 21:38:30,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 347, '_0n1': 1244}
2018-01-01 21:38:30,567 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,571 : INFO : < 200 OK [3290]

2018-01-01 21:38:30,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 73, '_0n1': 1244}
2018-01-01 21:38:30,575 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,579 : INFO : < 200 OK [3324]
2018-01-01 21:38:30,583 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 379, '_0n1': 1244}
2018-01-01 21:38:30,583 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,587 : INFO : < 200 OK [3294]
2018-01-01 21:38:30,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1244}
2018-01-01 21:38:30,591 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,595 : INFO : < 200 OK [3309]
2018-01-01 21:38:30,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1244}
2018-01-01 21:38:30,599 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,605 : INFO : < 200 OK [3342]
2018-01-01 21:38:30,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 384, '_0n1': 1244}
2018-01-01 21:38:30,610 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,614 : INFO : < 200 OK [3317]
2018-01-01 21:38:30,617 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 401, '_0n1': 1244}
2018-01-01 21:38:30,619 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,620 : INFO : < 200 OK [3302]
2018-01-01 21:38:30,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 385, '_0n1': 1244}
2018-01-01 21:38:30,624 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,632 : INFO : < 200 OK [3359]
2018-01-01 21:38:30,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 402, '_0n1': 1244}
2018-01-01 21:38:30,636 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,640 : INFO : < 200 OK [3292]
2018-01-01 21:38:30,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 386, '_0n1': 1244}
2018-01-01 21:38:30,644 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,648 : INFO : < 200 OK [3287]
2018-01-01 21:38:30,652 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 403, '_0n1': 1244}
2018-01-01 21:38:30,652 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,660 : INFO : < 200 OK [3363]
2018-01-01 21:38:30,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 387, '_0n1': 1244}
2018-01-01 21:38:30,664 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,668 : INFO : < 200 OK [3367]
2018-01-01 21:38:30,676 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 404, '_0n1': 1244}
2018-01-01 21:38:30,676 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,680 : INFO : < 200 OK [3295]
2018-01-01 21:38:30,684 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 88, '_0n1': 1244}
2018-01-01 21:38:30,684 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,688 : INFO : < 200 OK [3287]
2018-01-01 21:38:30,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 388, '_0n1': 1244}
2018-01-01 21:38:30,696 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,700 : INFO : < 200 OK [3368]
2018-01-01 21:38:30,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1244}
2018-01-01 21:38:30,706 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,710 : INFO : < 200 OK [3339]
2018-01-01 21:38:30,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 90, '_0n1': 1244}
2018-01-01 21:38:30,716 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:30,720 : INFO : < 200 OK [3319]
2018-01-01 21:38:30,720 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1244}
2018-01-01 21:38:30,724 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,728 : INFO : < 200 OK [3322]
2018-01-01 21:38:30,732 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 406, '_0n1': 1244}
2018-01-01 21:38:30,732 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,736 : INFO : < 200 OK [3296]
2018-01-01 21:38:30,740 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 108, '_0n1': 1244}
2018-01-01 21:38:30,744 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,748 : INFO : < 200 OK [3333]
2018-01-01 21:38:30,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 390, '_0n1': 1244}
2018-01-01 21:38:30,752 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,756 : INFO : < 200 OK [3306]
2018-01-01 21:38:30,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 407, '_0n1': 1244}
2018-01-01 21:38:30,760 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,764 : INFO : < 200 OK [3321]
2018-01-01 21:38:30,768 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 391, '_0n1': 1244}
2018-01-01 21:38:30,768 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,772 : INFO : < 200 OK [3302]
2018-01-01 21:38:30,776 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 408, '_0n1': 1244}
2018-01-01 21:38:30,776 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,780 : INFO : < 200 OK [3306]
2018-01-01 21:38:30,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 1244}
2018-01-01 21:38:30,788 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,792 : INFO : < 200 OK [3283]
2018-01-01 21:38:30,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 409, '_0n1': 1244}

2018-01-01 21:38:30,796 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,800 : INFO : < 200 OK [3312]
2018-01-01 21:38:30,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 393, '_0n1': 1244}
2018-01-01 21:38:30,808 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,812 : INFO : < 200 OK [3329]
2018-01-01 21:38:30,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 410, '_0n1': 1244}
2018-01-01 21:38:30,817 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,820 : INFO : < 200 OK [3330]
2018-01-01 21:38:30,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 394, '_0n1': 1244}
2018-01-01 21:38:30,824 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,828 : INFO : < 200 OK [3317]
2018-01-01 21:38:30,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 411, '_0n1': 1244}
2018-01-01 21:38:30,832 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,840 : INFO : < 200 OK [3321]
2018-01-01 21:38:30,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 395, '_0n1': 1244}
2018-01-01 21:38:30,844 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,852 : INFO : < 200 OK [3324]
2018-01-01 21:38:30,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 412, '_0n1': 1244}
2018-01-01 21:38:30,856 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,860 : INFO : < 200 OK [3319]
2018-01-01 21:38:30,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 396, '_0n1': 1244}
2018-01-01 21:38:30,868 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,872 : INFO : < 200 OK [3324]
2018-01-01 21:38:30,872 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 413, '_0n1': 1244}
2018-01-01 21:38:30,876 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,880 : INFO : < 200 OK [3334]
2018-01-01 21:38:30,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 397, '_0n1': 1244}
2018-01-01 21:38:30,888 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,892 : INFO : < 200 OK [3301]
2018-01-01 21:38:30,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 414, '_0n1': 1244}
2018-01-01 21:38:30,896 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,900 : INFO : < 200 OK [3265]
2018-01-01 21:38:30,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 398, '_0n1': 1227}
2018-01-01 21:38:30,908 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,912 : INFO : < 200 OK [3330]
2018-01-01 21:38:30,915 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 375, '_0n1': 1227}
2018-01-01 21:38:30,917 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,919 : INFO : < 200 OK [3325]
2018-01-01 21:38:30,923 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 213, '_0n1': 1227}
2018-01-01 21:38:30,923 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,927 : INFO : < 200 OK [3308]
2018-01-01 21:38:30,931 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 359, '_0n1': 1227}
2018-01-01 21:38:30,931 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,935 : INFO : < 200 OK [3295]
2018-01-01 21:38:30,939 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1227}
2018-01-01 21:38:30,939 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,943 : INFO : < 200 OK [3305]
2018-01-01 21:38:30,947 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1227}
2018-01-01 21:38:30,947 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,951 : INFO : < 200 OK [3281]
2018-01-01 21:38:30,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 399, '_0n1': 1227}
2018-01-01 21:38:30,955 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,959 : INFO : < 200 OK [3289]
2018-01-01 21:38:30,963 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 416, '_0n1': 1227}
2018-01-01 21:38:30,967 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,971 : INFO : < 200 OK [3315]
2018-01-01 21:38:30,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 344, '_0n1': 1227}
2018-01-01 21:38:30,975 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,979 : INFO : < 200 OK [3324]
2018-01-01 21:38:30,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 420, '_0n1': 1227}
2018-01-01 21:38:30,983 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,987 : INFO : < 200 OK [3283]
2018-01-01 21:38:30,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 250, '_0n1': 1227}
2018-01-01 21:38:30,995 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:30,999 : INFO : < 200 OK [3312]
2018-01-01 21:38:31,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 417, '_0n1': 1227}
2018-01-01 21:38:31,009 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,014 : INFO : < 200 OK [3326]
2018-01-01 21:38:31,018 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1227}
2018-01-01 21:38:31,020 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,024 : INFO : < 200 OK [3350]
2018-01-01 21:38:31,028 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 421, '_0n1': 1227}

2018-01-01 21:38:31,028 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,036 : INFO : < 200 OK [3325]
2018-01-01 21:38:31,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 418, '_0n1': 1227}
2018-01-01 21:38:31,044 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,048 : INFO : < 200 OK [3286]
2018-01-01 21:38:31,048 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 145, '_0n1': 1227}
2018-01-01 21:38:31,052 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,056 : INFO : < 200 OK [3350]
2018-01-01 21:38:31,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 422, '_0n1': 1227}
2018-01-01 21:38:31,064 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,068 : INFO : < 200 OK [3315]
2018-01-01 21:38:31,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1227}
2018-01-01 21:38:31,076 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,080 : INFO : < 200 OK [3321]
2018-01-01 21:38:31,084 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 423, '_0n1': 1227}
2018-01-01 21:38:31,088 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,092 : INFO : < 200 OK [3308]
2018-01-01 21:38:31,096 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 1227}
2018-01-01 21:38:31,096 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,104 : INFO : < 200 OK [3284]
2018-01-01 21:38:31,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 440, '_0n1': 1227}
2018-01-01 21:38:31,111 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,115 : INFO : < 200 OK [3301]
2018-01-01 21:38:31,118 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 424, '_0n1': 1227}
2018-01-01 21:38:31,119 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,124 : INFO : < 200 OK [3321]
2018-01-01 21:38:31,128 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 1227}
2018-01-01 21:38:31,128 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,132 : INFO : < 200 OK [3317]
2018-01-01 21:38:31,136 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 425, '_0n1': 1227}
2018-01-01 21:38:31,136 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,144 : INFO : < 200 OK [3300]
2018-01-01 21:38:31,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 442, '_0n1': 1227}
2018-01-01 21:38:31,148 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,152 : INFO : < 200 OK [3296]
2018-01-01 21:38:31,152 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 426, '_0n1': 1227}
2018-01-01 21:38:31,156 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,160 : INFO : < 200 OK [3252]
2018-01-01 21:38:31,164 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1227}
2018-01-01 21:38:31,164 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,168 : INFO : < 200 OK [3342]
2018-01-01 21:38:31,172 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 427, '_0n1': 1227}
2018-01-01 21:38:31,172 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,176 : INFO : < 200 OK [3291]
2018-01-01 21:38:31,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 444, '_0n1': 1227}
2018-01-01 21:38:31,180 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,184 : INFO : < 200 OK [3325]
2018-01-01 21:38:31,188 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 378, '_0n1': 1227}
2018-01-01 21:38:31,188 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,192 : INFO : < 200 OK [3285]
2018-01-01 21:38:31,196 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 428, '_0n1': 1227}
2018-01-01 21:38:31,196 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,204 : INFO : < 200 OK [3287]
2018-01-01 21:38:31,207 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 1227}
2018-01-01 21:38:31,208 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,212 : INFO : < 200 OK [3284]
2018-01-01 21:38:31,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 445, '_0n1': 1227}
2018-01-01 21:38:31,217 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,220 : INFO : < 200 OK [3326]
2018-01-01 21:38:31,224 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 1227}
2018-01-01 21:38:31,224 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,232 : INFO : < 200 OK [3276]
2018-01-01 21:38:31,232 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 429, '_0n1': 1227}
2018-01-01 21:38:31,236 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,244 : INFO : < 200 OK [3330]
2018-01-01 21:38:31,248 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 1227}
2018-01-01 21:38:31,248 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,252 : INFO : < 200 OK [3280]
2018-01-01 21:38:31,256 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 446, '_0n1': 1227}
2018-01-01 21:38:31,256 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,264 : INFO : < 200 OK [3336]
2018-01-01 21:38:31,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 430, '_0n1': 1227}
2018-01-01 21:38:31,268 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:31,268 : INFO : < 200 OK [3307]
2018-01-01 21:38:31,272 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 364, '_0n1': 1227}
2018-01-01 21:38:31,276 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,280 : INFO : < 200 OK [3310]
2018-01-01 21:38:31,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 447, '_0n1': 1227}
2018-01-01 21:38:31,284 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,288 : INFO : < 200 OK [3333]
2018-01-01 21:38:31,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1227}
2018-01-01 21:38:31,292 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,296 : INFO : < 200 OK [3275]
2018-01-01 21:38:31,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 448, '_0n1': 1227}
2018-01-01 21:38:31,300 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,306 : INFO : < 200 OK [3289]
2018-01-01 21:38:31,309 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 348, '_0n1': 1227}
2018-01-01 21:38:31,311 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,316 : INFO : < 200 OK [3277]
2018-01-01 21:38:31,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 432, '_0n1': 1227}
2018-01-01 21:38:31,320 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,324 : INFO : < 200 OK [3301]
2018-01-01 21:38:31,328 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 1227}
2018-01-01 21:38:31,328 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,332 : INFO : < 200 OK [3311]
2018-01-01 21:38:31,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 449, '_0n1': 1227}
2018-01-01 21:38:31,340 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,344 : INFO : < 200 OK [3298]
2018-01-01 21:38:31,348 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 349, '_0n1': 1227}
2018-01-01 21:38:31,348 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,352 : INFO : < 200 OK [3319]
2018-01-01 21:38:31,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 433, '_0n1': 1227}
2018-01-01 21:38:31,356 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,360 : INFO : < 200 OK [3299]
2018-01-01 21:38:31,364 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 401, '_0n1': 1227}
2018-01-01 21:38:31,368 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,372 : INFO : < 200 OK [3299]
2018-01-01 21:38:31,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 450, '_0n1': 1227}
2018-01-01 21:38:31,376 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,380 : INFO : < 200 OK [3333]
2018-01-01 21:38:31,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 385, '_0n1': 1227}
2018-01-01 21:38:31,384 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,392 : INFO : < 200 OK [3356]
2018-01-01 21:38:31,392 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 434, '_0n1': 1227}
2018-01-01 21:38:31,396 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,400 : INFO : < 200 OK [3250]
2018-01-01 21:38:31,405 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 1227}
2018-01-01 21:38:31,407 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,411 : INFO : < 200 OK [3280]
2018-01-01 21:38:31,414 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 451, '_0n1': 1227}
2018-01-01 21:38:31,416 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,420 : INFO : < 200 OK [3254]
2018-01-01 21:38:31,424 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 435, '_0n1': 1227}
2018-01-01 21:38:31,424 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,428 : INFO : < 200 OK [3302]
2018-01-01 21:38:31,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1227}
2018-01-01 21:38:31,436 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,440 : INFO : < 200 OK [3283]
2018-01-01 21:38:31,444 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 452, '_0n1': 1227}
2018-01-01 21:38:31,448 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,452 : INFO : < 200 OK [3323]
2018-01-01 21:38:31,456 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 386, '_0n1': 1227}
2018-01-01 21:38:31,456 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,464 : INFO : < 200 OK [3284]
2018-01-01 21:38:31,464 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 436, '_0n1': 1227}
2018-01-01 21:38:31,468 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,472 : INFO : < 200 OK [3316]
2018-01-01 21:38:31,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1227}
2018-01-01 21:38:31,476 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,480 : INFO : < 200 OK [3350]
2018-01-01 21:38:31,484 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 437, '_0n1': 1227}
2018-01-01 21:38:31,488 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,492 : INFO : < 200 OK [3281]
2018-01-01 21:38:31,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 454, '_0n1': 1227}
2018-01-01 21:38:31,496 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,505 : INFO : < 200 OK [3334]

2018-01-01 21:38:31,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 438, '_0n1': 1227}
2018-01-01 21:38:31,509 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,513 : INFO : < 200 OK [3338]
2018-01-01 21:38:31,516 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 455, '_0n1': 1227}
2018-01-01 21:38:31,518 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,520 : INFO : < 200 OK [3279]
2018-01-01 21:38:31,524 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 439, '_0n1': 1227}
2018-01-01 21:38:31,524 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,528 : INFO : < 200 OK [3325]
2018-01-01 21:38:31,532 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 456, '_0n1': 1227}
2018-01-01 21:38:31,532 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,540 : INFO : < 200 OK [3313]
2018-01-01 21:38:31,540 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 104, '_0n1': 1227}
2018-01-01 21:38:31,544 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,548 : INFO : < 200 OK [3295]
2018-01-01 21:38:31,552 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 460, '_0n1': 1227}
2018-01-01 21:38:31,552 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,556 : INFO : < 200 OK [3286]
2018-01-01 21:38:31,560 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 1227}
2018-01-01 21:38:31,560 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,564 : INFO : < 200 OK [3308]
2018-01-01 21:38:31,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 404, '_0n1': 1227}
2018-01-01 21:38:31,568 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,576 : INFO : < 200 OK [3292]
2018-01-01 21:38:31,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 461, '_0n1': 1227}
2018-01-01 21:38:31,576 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,580 : INFO : < 200 OK [3287]
2018-01-01 21:38:31,584 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 458, '_0n1': 1227}
2018-01-01 21:38:31,588 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,592 : INFO : < 200 OK [3302]
2018-01-01 21:38:31,592 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 462, '_0n1': 1227}
2018-01-01 21:38:31,596 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,600 : INFO : < 200 OK [3327]
2018-01-01 21:38:31,600 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 459, '_0n1': 1227}
2018-01-01 21:38:31,604 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,609 : INFO : < 200 OK [3337]
2018-01-01 21:38:31,612 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 1227}
2018-01-01 21:38:31,614 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,618 : INFO : < 200 OK [3309]
2018-01-01 21:38:31,620 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 480, '_0n1': 1227}
2018-01-01 21:38:31,620 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,624 : INFO : < 200 OK [3314]
2018-01-01 21:38:31,628 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 464, '_0n1': 1227}
2018-01-01 21:38:31,628 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,636 : INFO : < 200 OK [3330]
2018-01-01 21:38:31,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 481, '_0n1': 1227}
2018-01-01 21:38:31,640 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,644 : INFO : < 200 OK [3287]
2018-01-01 21:38:31,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 465, '_0n1': 1227}
2018-01-01 21:38:31,648 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,652 : INFO : < 200 OK [3292]
2018-01-01 21:38:31,656 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 482, '_0n1': 1227}
2018-01-01 21:38:31,660 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,664 : INFO : < 200 OK [3284]
2018-01-01 21:38:31,668 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 388, '_0n1': 1227}
2018-01-01 21:38:31,672 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,676 : INFO : < 200 OK [3365]
2018-01-01 21:38:31,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 466, '_0n1': 1227}
2018-01-01 21:38:31,684 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,688 : INFO : < 200 OK [3300]
2018-01-01 21:38:31,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 369, '_0n1': 1227}
2018-01-01 21:38:31,692 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,700 : INFO : < 200 OK [3370]
2018-01-01 21:38:31,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 1227}
2018-01-01 21:38:31,706 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,713 : INFO : < 200 OK [3315]
2018-01-01 21:38:31,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 467, '_0n1': 1227}
2018-01-01 21:38:31,719 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,724 : INFO : < 200 OK [3317]
2018-01-01 21:38:31,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 484, '_0n1': 1227}
2018-01-01 21:38:31,728 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,732 : INFO : < 200 OK [3320]
2018-01-01 21:38:31,740 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 468, '_0n1': 1227}

2018-01-01 21:38:31,740 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,744 : INFO : < 200 OK [3288]
2018-01-01 21:38:31,748 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 485, '_0n1': 1227}
2018-01-01 21:38:31,748 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,752 : INFO : < 200 OK [3347]
2018-01-01 21:38:31,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 469, '_0n1': 1227}
2018-01-01 21:38:31,760 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,764 : INFO : < 200 OK [3337]
2018-01-01 21:38:31,768 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 157, '_0n1': 1227}
2018-01-01 21:38:31,768 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,772 : INFO : < 200 OK [3312]
2018-01-01 21:38:31,776 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 486, '_0n1': 1227}
2018-01-01 21:38:31,780 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,784 : INFO : < 200 OK [3290]
2018-01-01 21:38:31,788 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 470, '_0n1': 1227}
2018-01-01 21:38:31,788 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,792 : INFO : < 200 OK [3353]
2018-01-01 21:38:31,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 406, '_0n1': 1227}
2018-01-01 21:38:31,800 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,805 : INFO : < 200 OK [3293]
2018-01-01 21:38:31,808 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1227}
2018-01-01 21:38:31,810 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,814 : INFO : < 200 OK [3319]
2018-01-01 21:38:31,817 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 353, '_0n1': 1227}
2018-01-01 21:38:31,819 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,820 : INFO : < 200 OK [3281]
2018-01-01 21:38:31,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 500, '_0n1': 1227}
2018-01-01 21:38:31,824 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,828 : INFO : < 200 OK [3291]
2018-01-01 21:38:31,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 471, '_0n1': 1227}
2018-01-01 21:38:31,832 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,836 : INFO : < 200 OK [3313]
2018-01-01 21:38:31,840 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 501, '_0n1': 1227}
2018-01-01 21:38:31,844 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,848 : INFO : < 200 OK [3321]
2018-01-01 21:38:31,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 472, '_0n1': 1227}
2018-01-01 21:38:31,852 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,856 : INFO : < 200 OK [3279]
2018-01-01 21:38:31,860 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 502, '_0n1': 1227}
2018-01-01 21:38:31,860 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,864 : INFO : < 200 OK [3286]
2018-01-01 21:38:31,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 473, '_0n1': 1227}
2018-01-01 21:38:31,872 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,876 : INFO : < 200 OK [3309]
2018-01-01 21:38:31,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1227}
2018-01-01 21:38:31,880 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,884 : INFO : < 200 OK [3316]
2018-01-01 21:38:31,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 1227}
2018-01-01 21:38:31,892 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,896 : INFO : < 200 OK [3337]
2018-01-01 21:38:31,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 503, '_0n1': 1227}
2018-01-01 21:38:31,900 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,907 : INFO : < 200 OK [3290]
2018-01-01 21:38:31,910 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 474, '_0n1': 1227}
2018-01-01 21:38:31,912 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,917 : INFO : < 200 OK [3329]
2018-01-01 21:38:31,920 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 504, '_0n1': 1227}
2018-01-01 21:38:31,920 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,924 : INFO : < 200 OK [3293]
2018-01-01 21:38:31,928 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 475, '_0n1': 1227}
2018-01-01 21:38:31,932 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,936 : INFO : < 200 OK [3300]
2018-01-01 21:38:31,940 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 505, '_0n1': 1227}
2018-01-01 21:38:31,944 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,948 : INFO : < 200 OK [3326]
2018-01-01 21:38:31,952 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 476, '_0n1': 1227}
2018-01-01 21:38:31,952 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,956 : INFO : < 200 OK [3302]
2018-01-01 21:38:31,960 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 506, '_0n1': 1227}
2018-01-01 21:38:31,964 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:31,976 : INFO : < 200 OK [3297]
2018-01-01 21:38:31,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 477, '_0n1': 1227}
2018-01-01 21:38:31,984 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:31,988 : INFO : < 200 OK [3314]
2018-01-01 21:38:32,031 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 507, '_0n1': 1227}
2018-01-01 21:38:32,035 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,040 : INFO : < 200 OK [3345]
2018-01-01 21:38:32,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 478, '_0n1': 1227}
2018-01-01 21:38:32,047 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,051 : INFO : < 200 OK [3338]
2018-01-01 21:38:32,054 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 1227}
2018-01-01 21:38:32,057 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,062 : INFO : < 200 OK [3325]
2018-01-01 21:38:32,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 479, '_0n1': 1227}
2018-01-01 21:38:32,068 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,073 : INFO : < 200 OK [3322]
2018-01-01 21:38:32,077 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 509, '_0n1': 1227}
2018-01-01 21:38:32,079 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,083 : INFO : < 200 OK [3334]
2018-01-01 21:38:32,086 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 1227}
2018-01-01 21:38:32,088 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,093 : INFO : < 200 OK [3325]
2018-01-01 21:38:32,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 510, '_0n1': 1227}
2018-01-01 21:38:32,100 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,105 : INFO : < 200 OK [3278]
2018-01-01 21:38:32,109 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 371, '_0n1': 1227}
2018-01-01 21:38:32,111 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,115 : INFO : < 200 OK [3290]
2018-01-01 21:38:32,118 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 514, '_0n1': 1227}
2018-01-01 21:38:32,120 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,125 : INFO : < 200 OK [3299]
2018-01-01 21:38:32,129 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 112, '_0n1': 1227}
2018-01-01 21:38:32,131 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,135 : INFO : < 200 OK [3288]
2018-01-01 21:38:32,138 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 143, '_0n1': 1227}
2018-01-01 21:38:32,140 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,144 : INFO : < 200 OK [3314]
2018-01-01 21:38:32,148 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 511, '_0n1': 1227}
2018-01-01 21:38:32,149 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,151 : INFO : < 200 OK [3321]
2018-01-01 21:38:32,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 515, '_0n1': 1227}
2018-01-01 21:38:32,155 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,159 : INFO : < 200 OK [3291]
2018-01-01 21:38:32,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 512, '_0n1': 1227}
2018-01-01 21:38:32,167 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,171 : INFO : < 200 OK [3295]
2018-01-01 21:38:32,171 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 516, '_0n1': 1227}
2018-01-01 21:38:32,175 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,179 : INFO : < 200 OK [3311]
2018-01-01 21:38:32,183 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 533, '_0n1': 1227}
2018-01-01 21:38:32,183 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,187 : INFO : < 200 OK [3303]
2018-01-01 21:38:32,191 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 517, '_0n1': 1227}
2018-01-01 21:38:32,191 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,195 : INFO : < 200 OK [3305]
2018-01-01 21:38:32,199 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 1227}
2018-01-01 21:38:32,199 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,203 : INFO : < 200 OK [3280]
2018-01-01 21:38:32,207 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 534, '_0n1': 1227}
2018-01-01 21:38:32,211 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,215 : INFO : < 200 OK [3306]
2018-01-01 21:38:32,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 518, '_0n1': 1227}
2018-01-01 21:38:32,219 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,223 : INFO : < 200 OK [3291]
2018-01-01 21:38:32,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 535, '_0n1': 1227}
2018-01-01 21:38:32,227 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,231 : INFO : < 200 OK [3302]
2018-01-01 21:38:32,235 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 519, '_0n1': 1227}
2018-01-01 21:38:32,238 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,242 : INFO : < 200 OK [3309]
2018-01-01 21:38:32,245 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 356, '_0n1': 1227}
2018-01-01 21:38:32,246 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,250 : INFO : < 200 OK [3282]
2018-01-01 21:38:32,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 536, '_0n1': 1227}
2018-01-01 21:38:32,251 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:32,255 : INFO : < 200 OK [3296]
2018-01-01 21:38:32,259 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 520, '_0n1': 1227}
2018-01-01 21:38:32,263 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,267 : INFO : < 200 OK [3323]
2018-01-01 21:38:32,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 537, '_0n1': 1227}
2018-01-01 21:38:32,271 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,275 : INFO : < 200 OK [3279]
2018-01-01 21:38:32,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 521, '_0n1': 1227}
2018-01-01 21:38:32,279 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,283 : INFO : < 200 OK [3299]
2018-01-01 21:38:32,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 538, '_0n1': 1227}
2018-01-01 21:38:32,291 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,295 : INFO : < 200 OK [3324]
2018-01-01 21:38:32,299 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 522, '_0n1': 1227}
2018-01-01 21:38:32,299 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,303 : INFO : < 200 OK [3284]
2018-01-01 21:38:32,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 274, '_0n1': 1227}
2018-01-01 21:38:32,311 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,315 : INFO : < 200 OK [3331]
2018-01-01 21:38:32,319 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 539, '_0n1': 1227}
2018-01-01 21:38:32,319 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,327 : INFO : < 200 OK [3293]
2018-01-01 21:38:32,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 523, '_0n1': 1227}
2018-01-01 21:38:32,331 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,337 : INFO : < 200 OK [3331]
2018-01-01 21:38:32,340 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 540, '_0n1': 1227}
2018-01-01 21:38:32,342 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,347 : INFO : < 200 OK [3283]
2018-01-01 21:38:32,350 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 524, '_0n1': 1227}
2018-01-01 21:38:32,351 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,355 : INFO : < 200 OK [3300]
2018-01-01 21:38:32,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 541, '_0n1': 1227}
2018-01-01 21:38:32,359 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,363 : INFO : < 200 OK [3300]
2018-01-01 21:38:32,367 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 126, '_0n1': 1227}
2018-01-01 21:38:32,367 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,371 : INFO : < 200 OK [3343]
2018-01-01 21:38:32,375 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1227}
2018-01-01 21:38:32,379 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,379 : INFO : < 200 OK [3305]
2018-01-01 21:38:32,383 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 542, '_0n1': 1227}
2018-01-01 21:38:32,387 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,391 : INFO : < 200 OK [3295]
2018-01-01 21:38:32,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 526, '_0n1': 1227}
2018-01-01 21:38:32,395 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,403 : INFO : < 200 OK [3362]
2018-01-01 21:38:32,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 144, '_0n1': 1227}
2018-01-01 21:38:32,407 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,411 : INFO : < 200 OK [3329]
2018-01-01 21:38:32,415 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 543, '_0n1': 1227}
2018-01-01 21:38:32,415 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,419 : INFO : < 200 OK [3290]
2018-01-01 21:38:32,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 527, '_0n1': 1227}
2018-01-01 21:38:32,423 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,427 : INFO : < 200 OK [3316]
2018-01-01 21:38:32,431 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 544, '_0n1': 1227}
2018-01-01 21:38:32,431 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,438 : INFO : < 200 OK [3307]
2018-01-01 21:38:32,441 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 528, '_0n1': 1227}
2018-01-01 21:38:32,442 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,446 : INFO : < 200 OK [3369]
2018-01-01 21:38:32,449 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 545, '_0n1': 1227}
2018-01-01 21:38:32,451 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,455 : INFO : < 200 OK [3323]
2018-01-01 21:38:32,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 529, '_0n1': 1227}
2018-01-01 21:38:32,459 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,463 : INFO : < 200 OK [3352]
2018-01-01 21:38:32,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 546, '_0n1': 1227}
2018-01-01 21:38:32,467 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,471 : INFO : < 200 OK [3331]
2018-01-01 21:38:32,475 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 530, '_0n1': 1227}
2018-01-01 21:38:32,475 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,479 : INFO : < 200 OK [3278]

2018-01-01 21:38:32,483 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 1227}
2018-01-01 21:38:32,483 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,491 : INFO : < 200 OK [3285]
2018-01-01 21:38:32,495 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 547, '_0n1': 1227}
2018-01-01 21:38:32,495 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,499 : INFO : < 200 OK [3327]
2018-01-01 21:38:32,503 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 531, '_0n1': 1227}
2018-01-01 21:38:32,503 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,511 : INFO : < 200 OK [3327]
2018-01-01 21:38:32,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 548, '_0n1': 1227}
2018-01-01 21:38:32,515 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,519 : INFO : < 200 OK [3278]
2018-01-01 21:38:32,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 532, '_0n1': 1227}
2018-01-01 21:38:32,527 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,531 : INFO : < 200 OK [3299]
2018-01-01 21:38:32,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 549, '_0n1': 1227}
2018-01-01 21:38:32,538 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,544 : INFO : < 200 OK [3319]
2018-01-01 21:38:32,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 553, '_0n1': 1227}
2018-01-01 21:38:32,549 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,550 : INFO : < 200 OK [3286]
2018-01-01 21:38:32,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 550, '_0n1': 1227}
2018-01-01 21:38:32,559 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,563 : INFO : < 200 OK [3357]
2018-01-01 21:38:32,567 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 554, '_0n1': 1227}
2018-01-01 21:38:32,567 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,571 : INFO : < 200 OK [3333]
2018-01-01 21:38:32,575 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 551, '_0n1': 1227}
2018-01-01 21:38:32,579 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,583 : INFO : < 200 OK [3300]
2018-01-01 21:38:32,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 555, '_0n1': 1227}
2018-01-01 21:38:32,587 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,591 : INFO : < 200 OK [3297]
2018-01-01 21:38:32,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 552, '_0n1': 1227}
2018-01-01 21:38:32,595 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,603 : INFO : < 200 OK [3288]
2018-01-01 21:38:32,607 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 556, '_0n1': 1227}
2018-01-01 21:38:32,607 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,611 : INFO : < 200 OK [3300]
2018-01-01 21:38:32,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 573, '_0n1': 1227}
2018-01-01 21:38:32,615 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,619 : INFO : < 200 OK [3286]
2018-01-01 21:38:32,623 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 557, '_0n1': 1227}
2018-01-01 21:38:32,623 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,627 : INFO : < 200 OK [3336]
2018-01-01 21:38:32,631 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 574, '_0n1': 1227}
2018-01-01 21:38:32,636 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,640 : INFO : < 200 OK [3295]
2018-01-01 21:38:32,642 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 142, '_0n1': 1227}
2018-01-01 21:38:32,645 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,649 : INFO : < 200 OK [3335]
2018-01-01 21:38:32,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 558, '_0n1': 1245}
2018-01-01 21:38:32,651 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,655 : INFO : < 200 OK [3321]
2018-01-01 21:38:32,659 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 575, '_0n1': 1245}
2018-01-01 21:38:32,659 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,663 : INFO : < 200 OK [3339]
2018-01-01 21:38:32,667 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 50, '_0n1': 1245}
2018-01-01 21:38:32,667 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:32,671 : INFO : < 200 OK [3302]
2018-01-01 21:38:32,675 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 398, '_0n1': 1245}
2018-01-01 21:38:32,675 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,679 : INFO : < 200 OK [3337]
2018-01-01 21:38:32,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1245}
2018-01-01 21:38:32,683 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:32,691 : INFO : < 200 OK [3303]
2018-01-01 21:38:32,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1245}
2018-01-01 21:38:32,695 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,699 : INFO : < 200 OK [3288]
2018-01-01 21:38:32,703 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 559, '_0n1': 1245}
2018-01-01 21:38:32,703 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,707 : INFO : < 200 OK [3334]
2018-01-01 21:38:32,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 576, '_0n1': 1245}

2018-01-01 21:38:32,711 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,719 : INFO : < 200 OK [3297]
2018-01-01 21:38:32,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 560, '_0n1': 1245}
2018-01-01 21:38:32,723 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,727 : INFO : < 200 OK [3329]
2018-01-01 21:38:32,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 251, '_0n1': 1245}
2018-01-01 21:38:32,736 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,743 : INFO : < 200 OK [3320]
2018-01-01 21:38:32,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1245}
2018-01-01 21:38:32,749 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,750 : INFO : < 200 OK [3320]
2018-01-01 21:38:32,755 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 577, '_0n1': 1245}
2018-01-01 21:38:32,759 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,763 : INFO : < 200 OK [3334]
2018-01-01 21:38:32,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 418, '_0n1': 1245}
2018-01-01 21:38:32,767 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,771 : INFO : < 200 OK [3293]
2018-01-01 21:38:32,775 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 561, '_0n1': 1245}
2018-01-01 21:38:32,775 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,779 : INFO : < 200 OK [3337]
2018-01-01 21:38:32,783 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 1245}
2018-01-01 21:38:32,783 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:32,787 : INFO : < 200 OK [3312]
2018-01-01 21:38:32,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 578, '_0n1': 1245}
2018-01-01 21:38:32,791 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,799 : INFO : < 200 OK [3341]
2018-01-01 21:38:32,799 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1245}
2018-01-01 21:38:32,803 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,807 : INFO : < 200 OK [3328]
2018-01-01 21:38:32,807 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 1245}
2018-01-01 21:38:32,811 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:32,815 : INFO : < 200 OK [3303]
2018-01-01 21:38:32,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 562, '_0n1': 1245}
2018-01-01 21:38:32,819 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,823 : INFO : < 200 OK [3295]
2018-01-01 21:38:32,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1245}
2018-01-01 21:38:32,827 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,831 : INFO : < 200 OK [3343]
2018-01-01 21:38:32,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 424, '_0n1': 1245}
2018-01-01 21:38:32,835 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,840 : INFO : < 200 OK [3328]
2018-01-01 21:38:32,843 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 1245}
2018-01-01 21:38:32,845 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,850 : INFO : < 200 OK [3324]
2018-01-01 21:38:32,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 563, '_0n1': 1245}
2018-01-01 21:38:32,851 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,855 : INFO : < 200 OK [3350]
2018-01-01 21:38:32,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1245}
2018-01-01 21:38:32,863 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,867 : INFO : < 200 OK [3349]
2018-01-01 21:38:32,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 444, '_0n1': 1245}
2018-01-01 21:38:32,871 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,875 : INFO : < 200 OK [3332]
2018-01-01 21:38:32,879 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 1245}
2018-01-01 21:38:32,879 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,883 : INFO : < 200 OK [3328]
2018-01-01 21:38:32,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 54, '_0n1': 1245}
2018-01-01 21:38:32,887 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:32,891 : INFO : < 200 OK [3304]
2018-01-01 21:38:32,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 296, '_0n1': 1245}
2018-01-01 21:38:32,895 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,903 : INFO : < 200 OK [3339]
2018-01-01 21:38:32,903 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 580, '_0n1': 1245}
2018-01-01 21:38:32,907 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,911 : INFO : < 200 OK [3311]
2018-01-01 21:38:32,915 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 148, '_0n1': 1245}
2018-01-01 21:38:32,919 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,927 : INFO : < 200 OK [3325]
2018-01-01 21:38:32,927 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 564, '_0n1': 1245}
2018-01-01 21:38:32,931 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,936 : INFO : < 200 OK [3342]
2018-01-01 21:38:32,939 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 297, '_0n1': 1245}
2018-01-01 21:38:32,941 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:32,945 : INFO : < 200 OK [3355]
2018-01-01 21:38:32,948 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 447, '_0n1': 1245}
2018-01-01 21:38:32,950 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,951 : INFO : < 200 OK [3340]
2018-01-01 21:38:32,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 581, '_0n1': 1245}
2018-01-01 21:38:32,959 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,963 : INFO : < 200 OK [3300]
2018-01-01 21:38:32,963 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 565, '_0n1': 1245}
2018-01-01 21:38:32,967 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,971 : INFO : < 200 OK [3348]
2018-01-01 21:38:32,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 448, '_0n1': 1245}
2018-01-01 21:38:32,975 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,979 : INFO : < 200 OK [3296]
2018-01-01 21:38:32,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1245}
2018-01-01 21:38:32,983 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,987 : INFO : < 200 OK [3313]
2018-01-01 21:38:32,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 133, '_0n1': 1245}
2018-01-01 21:38:32,995 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:32,999 : INFO : < 200 OK [3310]
2018-01-01 21:38:33,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 582, '_0n1': 1245}
2018-01-01 21:38:33,007 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,011 : INFO : < 200 OK [3321]
2018-01-01 21:38:33,011 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 1245}
2018-01-01 21:38:33,015 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,019 : INFO : < 200 OK [3322]
2018-01-01 21:38:33,019 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 195, '_0n1': 1245}
2018-01-01 21:38:33,023 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,027 : INFO : < 200 OK [3369]
2018-01-01 21:38:33,027 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1245}
2018-01-01 21:38:33,031 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,037 : INFO : < 200 OK [3346]
2018-01-01 21:38:33,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 302, '_0n1': 1245}
2018-01-01 21:38:33,042 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,046 : INFO : < 200 OK [3334]
2018-01-01 21:38:33,049 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 76, '_0n1': 1245}
2018-01-01 21:38:33,051 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:33,055 : INFO : < 200 OK [3304]
2018-01-01 21:38:33,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 299, '_0n1': 1245}
2018-01-01 21:38:33,059 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,063 : INFO : < 200 OK [3314]
2018-01-01 21:38:33,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 1245}
2018-01-01 21:38:33,067 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:33,071 : INFO : < 200 OK [3293]
2018-01-01 21:38:33,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 134, '_0n1': 1245}
2018-01-01 21:38:33,075 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,083 : INFO : < 200 OK [3320]
2018-01-01 21:38:33,087 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 179, '_0n1': 1245}
2018-01-01 21:38:33,091 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,095 : INFO : < 200 OK [3304]
2018-01-01 21:38:33,099 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 566, '_0n1': 1245}
2018-01-01 21:38:33,103 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,107 : INFO : < 200 OK [3298]
2018-01-01 21:38:33,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 583, '_0n1': 1245}
2018-01-01 21:38:33,111 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,115 : INFO : < 200 OK [3327]
2018-01-01 21:38:33,119 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 567, '_0n1': 1245}
2018-01-01 21:38:33,123 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,127 : INFO : < 200 OK [3335]
2018-01-01 21:38:33,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 436, '_0n1': 1245}
2018-01-01 21:38:33,131 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,139 : INFO : < 200 OK [3323]
2018-01-01 21:38:33,141 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1245}
2018-01-01 21:38:33,143 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,148 : INFO : < 200 OK [3357]
2018-01-01 21:38:33,150 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 257, '_0n1': 1245}
2018-01-01 21:38:33,151 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,155 : INFO : < 200 OK [3344]
2018-01-01 21:38:33,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1245}
2018-01-01 21:38:33,159 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,163 : INFO : < 200 OK [3347]
2018-01-01 21:38:33,167 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 568, '_0n1': 1245}
2018-01-01 21:38:33,167 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:33,171 : INFO : < 200 OK [3338]
2018-01-01 21:38:33,175 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1245}
2018-01-01 21:38:33,175 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,183 : INFO : < 200 OK [3328]
2018-01-01 21:38:33,183 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 304, '_0n1': 1245}
2018-01-01 21:38:33,187 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,191 : INFO : < 200 OK [3290]
2018-01-01 21:38:33,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 1245}
2018-01-01 21:38:33,195 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,199 : INFO : < 200 OK [3329]
2018-01-01 21:38:33,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 153, '_0n1': 1245}
2018-01-01 21:38:33,207 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,211 : INFO : < 200 OK [3309]
2018-01-01 21:38:33,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 585, '_0n1': 1245}
2018-01-01 21:38:33,215 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,223 : INFO : < 200 OK [3305]
2018-01-01 21:38:33,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 569, '_0n1': 1245}
2018-01-01 21:38:33,227 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,236 : INFO : < 200 OK [3333]
2018-01-01 21:38:33,241 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 586, '_0n1': 1245}
2018-01-01 21:38:33,243 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,247 : INFO : < 200 OK [3345]
2018-01-01 21:38:33,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 1245}
2018-01-01 21:38:33,251 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,255 : INFO : < 200 OK [3328]
2018-01-01 21:38:33,259 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 456, '_0n1': 1245}
2018-01-01 21:38:33,263 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,267 : INFO : < 200 OK [3320]
2018-01-01 21:38:33,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 1245}
2018-01-01 21:38:33,275 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,283 : INFO : < 200 OK [3315]
2018-01-01 21:38:33,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 1245}
2018-01-01 21:38:33,291 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,295 : INFO : < 200 OK [3305]
2018-01-01 21:38:33,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1245}
2018-01-01 21:38:33,299 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,303 : INFO : < 200 OK [3319]
2018-01-01 21:38:33,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 403, '_0n1': 1245}
2018-01-01 21:38:33,311 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,315 : INFO : < 200 OK [3367]
2018-01-01 21:38:33,319 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 322, '_0n1': 1245}
2018-01-01 21:38:33,319 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,323 : INFO : < 200 OK [3320]
2018-01-01 21:38:33,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1245}
2018-01-01 21:38:33,331 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,336 : INFO : < 200 OK [3342]
2018-01-01 21:38:33,340 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 87, '_0n1': 1245}
2018-01-01 21:38:33,341 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:33,346 : INFO : < 200 OK [3313]
2018-01-01 21:38:33,348 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1255, '_0n1': 1245}
2018-01-01 21:38:33,350 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:33,351 : INFO : < 200 OK [3384]
2018-01-01 21:38:33,355 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 1245}
2018-01-01 21:38:33,355 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,359 : INFO : < 200 OK [3316]
2018-01-01 21:38:33,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 480, '_0n1': 1245}
2018-01-01 21:38:33,363 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,371 : INFO : < 200 OK [3321]
2018-01-01 21:38:33,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 1245}
2018-01-01 21:38:33,375 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,379 : INFO : < 200 OK [3356]
2018-01-01 21:38:33,379 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1238, '_0n1': 1245}
2018-01-01 21:38:33,383 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:33,387 : INFO : < 200 OK [3283]
2018-01-01 21:38:33,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 588, '_0n1': 1245}
2018-01-01 21:38:33,391 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,395 : INFO : < 200 OK [3330]
2018-01-01 21:38:33,399 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 1245}
2018-01-01 21:38:33,399 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,403 : INFO : < 200 OK [3343]
2018-01-01 21:38:33,407 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 138, '_0n1': 1245}
2018-01-01 21:38:33,411 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:33,415 : INFO : < 200 OK [3331]
2018-01-01 21:38:33,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 307, '_0n1': 1245}
2018-01-01 21:38:33,419 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,423 : INFO : < 200 OK [3336]
2018-01-01 21:38:33,427 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1245}
2018-01-01 21:38:33,431 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,436 : INFO : < 200 OK [3343]
2018-01-01 21:38:33,440 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 1245}
2018-01-01 21:38:33,442 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,447 : INFO : < 200 OK [3322]
2018-01-01 21:38:33,451 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 572, '_0n1': 1245}
2018-01-01 21:38:33,451 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,455 : INFO : < 200 OK [3329]
2018-01-01 21:38:33,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 139, '_0n1': 1245}
2018-01-01 21:38:33,459 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,463 : INFO : < 200 OK [3304]
2018-01-01 21:38:33,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1239, '_0n1': 1245}
2018-01-01 21:38:33,467 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:38:33,475 : INFO : < 200 OK [3378]
2018-01-01 21:38:33,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 589, '_0n1': 1245}
2018-01-01 21:38:33,479 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,483 : INFO : < 200 OK [3361]
2018-01-01 21:38:33,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 593, '_0n1': 1245}
2018-01-01 21:38:33,487 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,491 : INFO : < 200 OK [3295]
2018-01-01 21:38:33,495 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 590, '_0n1': 1245}
2018-01-01 21:38:33,495 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,499 : INFO : < 200 OK [3343]
2018-01-01 21:38:33,503 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 486, '_0n1': 1245}
2018-01-01 21:38:33,507 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,511 : INFO : < 200 OK [3297]
2018-01-01 21:38:33,511 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 470, '_0n1': 1245}
2018-01-01 21:38:33,515 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,519 : INFO : < 200 OK [3360]
2018-01-01 21:38:33,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 1245}
2018-01-01 21:38:33,523 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,531 : INFO : < 200 OK [3295]
2018-01-01 21:38:33,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 1245}
2018-01-01 21:38:33,535 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:33,540 : INFO : < 200 OK [3316]
2018-01-01 21:38:33,542 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 140, '_0n1': 1245}
2018-01-01 21:38:33,544 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,548 : INFO : < 200 OK [3305]
2018-01-01 21:38:33,551 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 1245}
2018-01-01 21:38:33,551 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,555 : INFO : < 200 OK [3331]
2018-01-01 21:38:33,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 500, '_0n1': 1245}
2018-01-01 21:38:33,559 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,563 : INFO : < 200 OK [3298]
2018-01-01 21:38:33,567 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 1245}
2018-01-01 21:38:33,567 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,571 : INFO : < 200 OK [3328]
2018-01-01 21:38:33,575 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 159, '_0n1': 1245}
2018-01-01 21:38:33,575 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,579 : INFO : < 200 OK [3302]
2018-01-01 21:38:33,583 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 160, '_0n1': 1245}
2018-01-01 21:38:33,583 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,587 : INFO : < 200 OK [3329]
2018-01-01 21:38:33,591 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 505, '_0n1': 1245}
2018-01-01 21:38:33,591 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,595 : INFO : < 200 OK [3333]
2018-01-01 21:38:33,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 164, '_0n1': 1245}
2018-01-01 21:38:33,599 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,603 : INFO : < 200 OK [3291]
2018-01-01 21:38:33,607 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 327, '_0n1': 1245}
2018-01-01 21:38:33,607 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,611 : INFO : < 200 OK [3353]
2018-01-01 21:38:33,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 477, '_0n1': 1245}
2018-01-01 21:38:33,615 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,619 : INFO : < 200 OK [3321]
2018-01-01 21:38:33,623 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 311, '_0n1': 1245}
2018-01-01 21:38:33,623 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:38:33,627 : INFO : < 200 OK [3325]
2018-01-01 21:38:33,631 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 181, '_0n1': 1245}
2018-01-01 21:38:33,638 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,643 : INFO : < 200 OK [3284]
2018-01-01 21:38:33,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 165, '_0n1': 1245}
2018-01-01 21:38:33,651 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,659 : INFO : < 200 OK [3328]
2018-01-01 21:38:33,663 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 182, '_0n1': 1245}
2018-01-01 21:38:33,663 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,667 : INFO : < 200 OK [3290]
2018-01-01 21:38:33,671 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 594, '_0n1': 1245}
2018-01-01 21:38:33,671 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,679 : INFO : < 200 OK [3324]
2018-01-01 21:38:33,679 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 284, '_0n1': 1245}
2018-01-01 21:38:33,683 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,687 : INFO : < 200 OK [3339]
2018-01-01 21:38:33,687 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 1245}
2018-01-01 21:38:33,691 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,695 : INFO : < 200 OK [3332]
2018-01-01 21:38:33,699 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 514, '_0n1': 1245}
2018-01-01 21:38:33,699 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,703 : INFO : < 200 OK [3306]
2018-01-01 21:38:33,707 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 591, '_0n1': 1245}
2018-01-01 21:38:33,707 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,711 : INFO : < 200 OK [3343]
2018-01-01 21:38:33,715 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1245}
2018-01-01 21:38:33,715 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:33,719 : INFO : < 200 OK [3313]
2018-01-01 21:38:33,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 595, '_0n1': 1245}
2018-01-01 21:38:33,723 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,727 : INFO : < 200 OK [3348]
2018-01-01 21:38:33,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 328, '_0n1': 1245}
2018-01-01 21:38:33,731 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,738 : INFO : < 200 OK [3321]
2018-01-01 21:38:33,741 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 183, '_0n1': 1245}
2018-01-01 21:38:33,742 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,746 : INFO : < 200 OK [3288]
2018-01-01 21:38:33,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1245}
2018-01-01 21:38:33,750 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,751 : INFO : < 200 OK [3298]
2018-01-01 21:38:33,755 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 184, '_0n1': 1245}
2018-01-01 21:38:33,759 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,763 : INFO : < 200 OK [3309]
2018-01-01 21:38:33,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 8, '_0n1': 1245}
2018-01-01 21:38:33,767 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:38:33,771 : INFO : < 200 OK [3299]
2018-01-01 21:38:33,771 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 168, '_0n1': 1245}
2018-01-01 21:38:33,775 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,779 : INFO : < 200 OK [3354]
2018-01-01 21:38:33,783 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 516, '_0n1': 1245}
2018-01-01 21:38:33,783 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,787 : INFO : < 200 OK [3318]
2018-01-01 21:38:33,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 592, '_0n1': 1245}
2018-01-01 21:38:33,791 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,799 : INFO : < 200 OK [3303]
2018-01-01 21:38:33,803 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 312, '_0n1': 1245}
2018-01-01 21:38:33,803 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,807 : INFO : < 200 OK [3362]
2018-01-01 21:38:33,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 27, '_0n1': 1245}
2018-01-01 21:38:33,815 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:33,819 : INFO : < 200 OK [3309]
2018-01-01 21:38:33,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 534, '_0n1': 1245}
2018-01-01 21:38:33,823 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,831 : INFO : < 200 OK [3313]
2018-01-01 21:38:33,831 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1245}
2018-01-01 21:38:33,838 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,841 : INFO : < 200 OK [3303]
2018-01-01 21:38:33,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 186, '_0n1': 1245}
2018-01-01 21:38:33,846 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,850 : INFO : < 200 OK [3302]
2018-01-01 21:38:33,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1245}
2018-01-01 21:38:33,851 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,859 : INFO : < 200 OK [3318]

2018-01-01 21:38:33,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 170, '_0n1': 1245}
2018-01-01 21:38:33,863 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,867 : INFO : < 200 OK [3322]
2018-01-01 21:38:33,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 330, '_0n1': 1245}
2018-01-01 21:38:33,871 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,875 : INFO : < 200 OK [3321]
2018-01-01 21:38:33,879 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 31, '_0n1': 1245}
2018-01-01 21:38:33,879 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:33,883 : INFO : < 200 OK [3340]
2018-01-01 21:38:33,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 187, '_0n1': 1245}
2018-01-01 21:38:33,887 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,895 : INFO : < 200 OK [3292]
2018-01-01 21:38:33,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 613, '_0n1': 1245}
2018-01-01 21:38:33,899 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,903 : INFO : < 200 OK [3314]
2018-01-01 21:38:33,903 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 188, '_0n1': 1245}
2018-01-01 21:38:33,907 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,911 : INFO : < 200 OK [3339]
2018-01-01 21:38:33,915 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 14, '_0n1': 1245}
2018-01-01 21:38:33,915 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:33,919 : INFO : < 200 OK [3326]
2018-01-01 21:38:33,923 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 272, '_0n1': 1245}
2018-01-01 21:38:33,923 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,927 : INFO : < 200 OK [3342]
2018-01-01 21:38:33,931 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 172, '_0n1': 1245}
2018-01-01 21:38:33,931 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,939 : INFO : < 200 OK [3312]
2018-01-01 21:38:33,942 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 597, '_0n1': 1245}
2018-01-01 21:38:33,944 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,948 : INFO : < 200 OK [3320]
2018-01-01 21:38:33,951 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 332, '_0n1': 1245}
2018-01-01 21:38:33,951 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,955 : INFO : < 200 OK [3306]
2018-01-01 21:38:33,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 614, '_0n1': 1245}
2018-01-01 21:38:33,959 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,963 : INFO : < 200 OK [3324]
2018-01-01 21:38:33,963 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 598, '_0n1': 1245}
2018-01-01 21:38:33,967 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,971 : INFO : < 200 OK [3333]
2018-01-01 21:38:33,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 317, '_0n1': 1245}
2018-01-01 21:38:33,975 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,983 : INFO : < 200 OK [3343]
2018-01-01 21:38:33,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1245}
2018-01-01 21:38:33,987 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:33,995 : INFO : < 200 OK [3309]
2018-01-01 21:38:33,999 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 615, '_0n1': 1245}
2018-01-01 21:38:33,999 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,007 : INFO : < 200 OK [3326]
2018-01-01 21:38:34,007 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 599, '_0n1': 1245}
2018-01-01 21:38:34,011 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,015 : INFO : < 200 OK [3307]
2018-01-01 21:38:34,019 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 616, '_0n1': 1245}
2018-01-01 21:38:34,019 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,023 : INFO : < 200 OK [3329]
2018-01-01 21:38:34,027 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 600, '_0n1': 1245}
2018-01-01 21:38:34,027 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,031 : INFO : < 200 OK [3321]
2018-01-01 21:38:34,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1245}
2018-01-01 21:38:34,035 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,043 : INFO : < 200 OK [3312]
2018-01-01 21:38:34,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 617, '_0n1': 1245}
2018-01-01 21:38:34,047 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,051 : INFO : < 200 OK [3326]
2018-01-01 21:38:34,052 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 174, '_0n1': 1245}
2018-01-01 21:38:34,052 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,060 : INFO : < 200 OK [3355]
2018-01-01 21:38:34,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 601, '_0n1': 1245}
2018-01-01 21:38:34,064 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,068 : INFO : < 200 OK [3307]
2018-01-01 21:38:34,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 618, '_0n1': 1245}
2018-01-01 21:38:34,072 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,076 : INFO : < 200 OK [3313]
2018-01-01 21:38:34,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 210, '_0n1': 1245}

2018-01-01 21:38:34,080 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,084 : INFO : < 200 OK [3330]
2018-01-01 21:38:34,088 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 60, '_0n1': 1245}
2018-01-01 21:38:34,088 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:34,092 : INFO : < 200 OK [3353]
2018-01-01 21:38:34,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 175, '_0n1': 1245}
2018-01-01 21:38:34,100 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,108 : INFO : < 200 OK [3345]
2018-01-01 21:38:34,112 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 602, '_0n1': 1245}
2018-01-01 21:38:34,112 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,116 : INFO : < 200 OK [3290]
2018-01-01 21:38:34,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 619, '_0n1': 1245}
2018-01-01 21:38:34,124 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,128 : INFO : < 200 OK [3313]
2018-01-01 21:38:34,132 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 192, '_0n1': 1245}
2018-01-01 21:38:34,132 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,142 : INFO : < 200 OK [3348]
2018-01-01 21:38:34,146 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 603, '_0n1': 1245}
2018-01-01 21:38:34,148 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,152 : INFO : < 200 OK [3341]
2018-01-01 21:38:34,156 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 397, '_0n1': 1245}
2018-01-01 21:38:34,160 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,164 : INFO : < 200 OK [3305]
2018-01-01 21:38:34,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 319, '_0n1': 1245}
2018-01-01 21:38:34,168 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,176 : INFO : < 200 OK [3292]
2018-01-01 21:38:34,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 336, '_0n1': 1245}
2018-01-01 21:38:34,180 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,184 : INFO : < 200 OK [3315]
2018-01-01 21:38:34,188 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 620, '_0n1': 1245}
2018-01-01 21:38:34,192 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,196 : INFO : < 200 OK [3292]
2018-01-01 21:38:34,200 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 46, '_0n1': 1245}
2018-01-01 21:38:34,200 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:34,208 : INFO : < 200 OK [3344]
2018-01-01 21:38:34,212 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 176, '_0n1': 1245}
2018-01-01 21:38:34,212 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,216 : INFO : < 200 OK [3284]
2018-01-01 21:38:34,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 247, '_0n1': 1245}
2018-01-01 21:38:34,220 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,228 : INFO : < 200 OK [3312]
2018-01-01 21:38:34,232 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1245}
2018-01-01 21:38:34,232 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,239 : INFO : < 200 OK [3311]
2018-01-01 21:38:34,242 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 123, '_0n1': 1245}
2018-01-01 21:38:34,244 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,248 : INFO : < 200 OK [3342]
2018-01-01 21:38:34,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 548, '_0n1': 1245}
2018-01-01 21:38:34,252 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,256 : INFO : < 200 OK [3285]
2018-01-01 21:38:34,260 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 604, '_0n1': 1245}
2018-01-01 21:38:34,260 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,264 : INFO : < 200 OK [3346]
2018-01-01 21:38:34,268 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 47, '_0n1': 1245}
2018-01-01 21:38:34,268 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:38:34,272 : INFO : < 200 OK [3318]
2018-01-01 21:38:34,276 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 621, '_0n1': 1245}
2018-01-01 21:38:34,280 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,284 : INFO : < 200 OK [3302]
2018-01-01 21:38:34,288 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 557, '_0n1': 1245}
2018-01-01 21:38:34,292 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:38:34,296 : INFO : < 200 OK [3343]

In [57]:
institute_dict = {}
for created_by in set(data.created_by):
    institute_dict[created_by] = Node("Institute", name=created_by)
    graph.create(institute_dict[created_by])

2018-01-01 21:38:34,472 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Toronto'}}
2018-01-01 21:38:34,476 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:34,480 : INFO : < 200 OK [1384]
2018-01-01 21:38:34,480 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Virginia'}}
2018-01-01 21:38:34,484 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2018-01-01 21:38:34,488 : INFO : < 200 OK [1385]
2018-01-01 21:38:34,492 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Tokyo'}}
2018-01-01 21:38:34,492 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:34,496 : INFO : < 200 OK [1386]
2018-01-01 21:38:34,496 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Macquarie University'}}
2018-01-01 21:38:34,500 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:34,504 : INFO : < 200 OK [1383]
2018-01-01 21:38:34,504 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of North Carolina at Chapel Hill, The University of Edinburgh'}}
2018-01-01 21:38:34,508 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2018-01-01 21:38:34,512 : INFO : < 200 OK [1439]
2018-01-01 21:38:34,512 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Columbia University'}}
2018-01-01 21:38:34,512 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:34,516 : INFO : < 200 OK [1382]
2018-01-01 21:38:34,520 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The Hong Kong University of Science and Technology'}}
2018-01-01 21:38:34,520 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:34,524 : INFO : < 200 OK [1413]
2018-01-01 21:38:34,528 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'École normale supérieure'}}
2018-01-01 21:38:34,528 : INFO : > POST http://localhost:7474/db/data/cypher [111]
2018-01-01 21:38:34,532 : INFO : < 200 OK [1389]
2018-01-01 21:38:34,532 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Johns Hopkins University, University of Colorado Boulder'}}
2018-01-01 21:38:34,537 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2018-01-01 21:38:34,541 : INFO : < 200 OK [1419]
2018-01-01 21:38:34,543 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The Pennsylvania State University'}}
2018-01-01 21:38:34,544 : INFO : > POST http://localhost:7474/db/data/cypher [110]
2018-01-01 21:38:34,549 : INFO : < 200 OK [1396]
2018-01-01 21:38:34,552 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Zurich'}}
2018-01-01 21:38:34,552 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:34,556 : INFO : < 200 OK [1383]
2018-01-01 21:38:34,560 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University at Buffalo, The State University of New York'}}
2018-01-01 21:38:34,560 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:34,564 : INFO : < 200 OK [1418]
2018-01-01 21:38:34,568 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of London'}}
2018-01-01 21:38:34,572 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:34,580 : INFO : < 200 OK [1383]
2018-01-01 21:38:34,580 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Intel'}}
2018-01-01 21:38:34,580 : INFO : > POST http://localhost:7474/db/data/cypher [82]
2018-01-01 21:38:34,588 : INFO : < 200 OK [1368]
2018-01-01 21:38:34,588 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'emlyon business school'}}
2018-01-01 21:38:34,592 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2018-01-01 21:38:34,596 : INFO : < 200 OK [1385]
2018-01-01 21:38:34,596 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Hebrew University of Jerusalem'}}
2018-01-01 21:38:34,600 : INFO : > POST http://localhost:7474/db/data/cypher [107]
2018-01-01 21:38:34,604 : INFO : < 200 OK [1393]
2018-01-01 21:38:34,604 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Stanford University, The University of British Columbia'}}
2018-01-01 21:38:34,604 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:34,612 : INFO : < 200 OK [1418]
2018-01-01 21:38:34,612 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Rochester'}}
2018-01-01 21:38:34,612 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:34,616 : INFO : < 200 OK [1386]
2018-01-01 21:38:34,620 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of California, San Diego'}}
2018-01-01 21:38:34,620 : INFO : > POST http://localhost:7474/db/data/cypher [112]
2018-01-01 21:38:34,624 : INFO : < 200 OK [1398]
2018-01-01 21:38:34,628 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Moscow Institute of Physics and Technology'}}
2018-01-01 21:38:34,628 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2018-01-01 21:38:34,632 : INFO : < 200 OK [1405]
2018-01-01 21:38:34,636 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Copenhagen'}}
2018-01-01 21:38:34,637 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2018-01-01 21:38:34,641 : INFO : < 200 OK [1387]
2018-01-01 21:38:34,643 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of New Mexico'}}
2018-01-01 21:38:34,644 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2018-01-01 21:38:34,648 : INFO : < 200 OK [1387]
2018-01-01 21:38:34,650 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Rice University'}}
2018-01-01 21:38:34,651 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:34,651 : INFO : < 200 OK [1378]
2018-01-01 21:38:34,656 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Maryland, College Park'}}
2018-01-01 21:38:34,656 : INFO : > POST http://localhost:7474/db/data/cypher [113]
2018-01-01 21:38:34,660 : INFO : < 200 OK [1399]
2018-01-01 21:38:34,664 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Georgia Institute of Technology'}}
2018-01-01 21:38:34,664 : INFO : > POST http://localhost:7474/db/data/cypher [108]
2018-01-01 21:38:34,668 : INFO : < 200 OK [1394]
2018-01-01 21:38:34,672 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'California Institute of the Arts'}}
2018-01-01 21:38:34,676 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2018-01-01 21:38:34,680 : INFO : < 200 OK [1395]
2018-01-01 21:38:34,680 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Edinburgh, Universidad ORT Uruguay'}}
2018-01-01 21:38:34,684 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2018-01-01 21:38:34,688 : INFO : < 200 OK [1415]
2018-01-01 21:38:34,692 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The State University of New York'}}
2018-01-01 21:38:34,692 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2018-01-01 21:38:34,696 : INFO : < 200 OK [1395]
2018-01-01 21:38:34,700 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Melbourne'}}
2018-01-01 21:38:34,700 : INFO : > POST http://localhost:7474/db/data/cypher [104]
2018-01-01 21:38:34,704 : INFO : < 200 OK [1390]
2018-01-01 21:38:34,708 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'West Virginia University'}}
2018-01-01 21:38:34,708 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2018-01-01 21:38:34,712 : INFO : < 200 OK [1387]
2018-01-01 21:38:34,716 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Melbourne, The Chinese University of Hong Kong'}}
2018-01-01 21:38:34,716 : INFO : > POST http://localhost:7474/db/data/cypher [141]

2018-01-01 21:38:34,720 : INFO : < 200 OK [1427]
2018-01-01 21:38:34,724 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'École Polytechnique Fédérale de Lausanne'}}
2018-01-01 21:38:34,724 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:34,728 : INFO : < 200 OK [1406]
2018-01-01 21:38:34,732 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Minnesota'}}
2018-01-01 21:38:34,732 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:34,738 : INFO : < 200 OK [1386]
2018-01-01 21:38:34,741 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'PwC'}}
2018-01-01 21:38:34,744 : INFO : > POST http://localhost:7474/db/data/cypher [80]
2018-01-01 21:38:34,748 : INFO : < 200 OK [1366]
2018-01-01 21:38:34,750 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Indian School of Business'}}
2018-01-01 21:38:34,752 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2018-01-01 21:38:34,756 : INFO : < 200 OK [1388]
2018-01-01 21:38:34,760 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'National Research University Higher School of Economics'}}
2018-01-01 21:38:34,764 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2018-01-01 21:38:34,768 : INFO : < 200 OK [1418]
2018-01-01 21:38:34,768 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Autodesk'}}
2018-01-01 21:38:34,772 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:34,776 : INFO : < 200 OK [1371]
2018-01-01 21:38:34,776 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The Ohio State University'}}
2018-01-01 21:38:34,780 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2018-01-01 21:38:34,784 : INFO : < 200 OK [1388]
2018-01-01 21:38:34,784 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Universitat Autònoma de Barcelona'}}
2018-01-01 21:38:34,784 : INFO : > POST http://localhost:7474/db/data/cypher [115]
2018-01-01 21:38:34,788 : INFO : < 200 OK [1397]
2018-01-01 21:38:34,792 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'New York University Tandon School of Engineering'}}
2018-01-01 21:38:34,796 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2018-01-01 21:38:34,800 : INFO : < 200 OK [1411]
2018-01-01 21:38:34,800 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Google Daydream Impact'}}
2018-01-01 21:38:34,800 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2018-01-01 21:38:34,808 : INFO : < 200 OK [1385]
2018-01-01 21:38:34,808 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Eindhoven University of Technology'}}
2018-01-01 21:38:34,808 : INFO : > POST http://localhost:7474/db/data/cypher [111]
2018-01-01 21:38:34,812 : INFO : < 200 OK [1397]
2018-01-01 21:38:34,816 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Erasmus University Rotterdam'}}
2018-01-01 21:38:34,816 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2018-01-01 21:38:34,820 : INFO : < 200 OK [1391]
2018-01-01 21:38:34,824 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Yonsei University'}}
2018-01-01 21:38:34,824 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:34,828 : INFO : < 200 OK [1380]
2018-01-01 21:38:34,832 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Vanderbilt University'}}
2018-01-01 21:38:34,832 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:34,838 : INFO : < 200 OK [1384]
2018-01-01 21:38:34,840 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Stanford University'}}
2018-01-01 21:38:34,842 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:34,846 : INFO : < 200 OK [1382]
2018-01-01 21:38:34,849 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Illinois at Urbana-Champaign'}}
2018-01-01 21:38:34,850 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2018-01-01 21:38:34,852 : INFO : < 200 OK [1405]
2018-01-01 21:38:34,856 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of California, Irvine'}}
2018-01-01 21:38:34,860 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2018-01-01 21:38:34,868 : INFO : < 200 OK [1395]
2018-01-01 21:38:34,868 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'National Research Tomsk State University'}}
2018-01-01 21:38:34,872 : INFO : > POST http://localhost:7474/db/data/cypher [117]
2018-01-01 21:38:34,876 : INFO : < 200 OK [1403]
2018-01-01 21:38:34,880 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of London, Goldsmiths, University of London'}}
2018-01-01 21:38:34,880 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2018-01-01 21:38:34,888 : INFO : < 200 OK [1417]
2018-01-01 21:38:34,888 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Institut Mines-Télécom'}}
2018-01-01 21:38:34,892 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2018-01-01 21:38:34,896 : INFO : < 200 OK [1387]
2018-01-01 21:38:34,896 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Technical University of Denmark (DTU)'}}
2018-01-01 21:38:34,900 : INFO : > POST http://localhost:7474/db/data/cypher [114]
2018-01-01 21:38:34,904 : INFO : < 200 OK [1400]
2018-01-01 21:38:34,908 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'ESSEC Business School'}}
2018-01-01 21:38:34,908 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:34,916 : INFO : < 200 OK [1384]
2018-01-01 21:38:34,916 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of California, Davis'}}
2018-01-01 21:38:34,920 : INFO : > POST http://localhost:7474/db/data/cypher [108]
2018-01-01 21:38:34,924 : INFO : < 200 OK [1394]
2018-01-01 21:38:34,928 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'EIT Digital '}}
2018-01-01 21:38:34,928 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:34,932 : INFO : < 200 OK [1375]
2018-01-01 21:38:34,936 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Sydney'}}
2018-01-01 21:38:34,938 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2018-01-01 21:38:34,943 : INFO : < 200 OK [1387]
2018-01-01 21:38:34,945 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Emory University'}}
2018-01-01 21:38:34,947 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:34,952 : INFO : < 200 OK [1379]
2018-01-01 21:38:34,952 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Michigan'}}
2018-01-01 21:38:34,956 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2018-01-01 21:38:34,960 : INFO : < 200 OK [1385]
2018-01-01 21:38:34,960 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of California, Santa Cruz'}}
2018-01-01 21:38:34,964 : INFO : > POST http://localhost:7474/db/data/cypher [113]
2018-01-01 21:38:34,968 : INFO : < 200 OK [1399]
2018-01-01 21:38:34,968 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Northwestern University'}}
2018-01-01 21:38:34,972 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:34,976 : INFO : < 200 OK [1386]
2018-01-01 21:38:34,980 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'CentraleSupélec'}}
2018-01-01 21:38:34,980 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:34,984 : INFO : < 200 OK [1379]
2018-01-01 21:38:34,988 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'UNSW Australia (The University of New South Wales)'}}
2018-01-01 21:38:34,988 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:34,992 : INFO : < 200 OK [1413]
2018-01-01 21:38:34,992 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'deeplearning.ai'}}

2018-01-01 21:38:34,996 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:35,000 : INFO : < 200 OK [1378]
2018-01-01 21:38:35,004 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Princeton University'}}
2018-01-01 21:38:35,004 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:35,008 : INFO : < 200 OK [1383]
2018-01-01 21:38:35,012 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of California, San Diego, National Research University Higher School of Economics'}}
2018-01-01 21:38:35,012 : INFO : > POST http://localhost:7474/db/data/cypher [169]
2018-01-01 21:38:35,020 : INFO : < 200 OK [1455]
2018-01-01 21:38:35,020 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Edinburgh'}}
2018-01-01 21:38:35,024 : INFO : > POST http://localhost:7474/db/data/cypher [104]
2018-01-01 21:38:35,028 : INFO : < 200 OK [1390]
2018-01-01 21:38:35,032 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Tecnológico de Monterrey'}}
2018-01-01 21:38:35,032 : INFO : > POST http://localhost:7474/db/data/cypher [106]
2018-01-01 21:38:35,038 : INFO : < 200 OK [1388]
2018-01-01 21:38:35,041 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Yandex'}}
2018-01-01 21:38:35,043 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2018-01-01 21:38:35,048 : INFO : < 200 OK [1369]
2018-01-01 21:38:35,050 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Pennsylvania'}}
2018-01-01 21:38:35,052 : INFO : > POST http://localhost:7474/db/data/cypher [103]
2018-01-01 21:38:35,056 : INFO : < 200 OK [1389]
2018-01-01 21:38:35,060 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Shanghai Jiao Tong University'}}
2018-01-01 21:38:35,064 : INFO : > POST http://localhost:7474/db/data/cypher [106]
2018-01-01 21:38:35,068 : INFO : < 200 OK [1392]
2018-01-01 21:38:35,072 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Alberta'}}
2018-01-01 21:38:35,072 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:35,076 : INFO : < 200 OK [1384]
2018-01-01 21:38:35,080 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University System of Georgia'}}
2018-01-01 21:38:35,084 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2018-01-01 21:38:35,088 : INFO : < 200 OK [1391]
2018-01-01 21:38:35,092 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Amsterdam'}}
2018-01-01 21:38:35,092 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:35,100 : INFO : < 200 OK [1386]
2018-01-01 21:38:35,104 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Universitat Pompeu Fabra of Barcelona, Stanford University'}}
2018-01-01 21:38:35,104 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2018-01-01 21:38:35,112 : INFO : < 200 OK [1421]
2018-01-01 21:38:35,116 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Cisco'}}
2018-01-01 21:38:35,116 : INFO : > POST http://localhost:7474/db/data/cypher [82]
2018-01-01 21:38:35,120 : INFO : < 200 OK [1368]
2018-01-01 21:38:35,124 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Rutgers the State University of New Jersey'}}
2018-01-01 21:38:35,124 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2018-01-01 21:38:35,128 : INFO : < 200 OK [1405]
2018-01-01 21:38:35,132 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'McMaster University'}}
2018-01-01 21:38:35,137 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:35,145 : INFO : < 200 OK [1382]
2018-01-01 21:38:35,148 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Cape Town'}}
2018-01-01 21:38:35,150 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:35,154 : INFO : < 200 OK [1386]
2018-01-01 21:38:35,158 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Google Cloud'}}
2018-01-01 21:38:35,159 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:35,166 : INFO : < 200 OK [1375]
2018-01-01 21:38:35,168 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'IBM'}}
2018-01-01 21:38:35,170 : INFO : > POST http://localhost:7474/db/data/cypher [80]
2018-01-01 21:38:35,175 : INFO : < 200 OK [1366]
2018-01-01 21:38:35,180 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Wesleyan University'}}
2018-01-01 21:38:35,181 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:35,186 : INFO : < 200 OK [1382]
2018-01-01 21:38:35,189 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Icahn School of Medicine at Mount Sinai'}}
2018-01-01 21:38:35,191 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2018-01-01 21:38:35,197 : INFO : < 200 OK [1402]
2018-01-01 21:38:35,200 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Colorado System'}}
2018-01-01 21:38:35,202 : INFO : > POST http://localhost:7474/db/data/cypher [106]
2018-01-01 21:38:35,207 : INFO : < 200 OK [1392]
2018-01-01 21:38:35,209 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Michigan State University'}}
2018-01-01 21:38:35,211 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2018-01-01 21:38:35,217 : INFO : < 200 OK [1388]
2018-01-01 21:38:35,220 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Chicago'}}
2018-01-01 21:38:35,222 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2018-01-01 21:38:35,226 : INFO : < 200 OK [1388]
2018-01-01 21:38:35,228 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Nanjing University'}}
2018-01-01 21:38:35,230 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:35,235 : INFO : < 200 OK [1381]
2018-01-01 21:38:35,237 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Colorado Boulder'}}
2018-01-01 21:38:35,239 : INFO : > POST http://localhost:7474/db/data/cypher [107]
2018-01-01 21:38:35,243 : INFO : < 200 OK [1393]
2018-01-01 21:38:35,246 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Johns Hopkins University'}}
2018-01-01 21:38:35,248 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2018-01-01 21:38:35,253 : INFO : < 200 OK [1387]
2018-01-01 21:38:35,256 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'MongoDB Inc.'}}
2018-01-01 21:38:35,258 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:35,262 : INFO : < 200 OK [1375]
2018-01-01 21:38:35,265 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Duke University'}}
2018-01-01 21:38:35,267 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:35,271 : INFO : < 200 OK [1378]
2018-01-01 21:38:35,273 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Houston System'}}
2018-01-01 21:38:35,276 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2018-01-01 21:38:35,281 : INFO : < 200 OK [1391]
2018-01-01 21:38:35,284 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Korea Advanced Institute of Science and Technology'}}
2018-01-01 21:38:35,286 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2018-01-01 21:38:35,291 : INFO : < 200 OK [1413]
2018-01-01 21:38:35,294 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Washington'}}
2018-01-01 21:38:35,296 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2018-01-01 21:38:35,301 : INFO : < 200 OK [1387]

In [58]:
teach_dict = {}
for teach_by in set(data.teach_by):
    teach_dict[teach_by] = Node("Teacher", name=teach_by)
    graph.create(teach_dict[teach_by])

2018-01-01 21:38:35,526 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Evgeniy Ryabenko'}}
2018-01-01 21:38:35,527 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:35,533 : INFO : < 200 OK [1377]
2018-01-01 21:38:35,533 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mark  Bocko'}}
2018-01-01 21:38:35,537 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:35,541 : INFO : < 200 OK [1372]
2018-01-01 21:38:35,541 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ron Berman'}}
2018-01-01 21:38:35,541 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:35,549 : INFO : < 200 OK [1371]
2018-01-01 21:38:35,549 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': ' Dr Sylvia Xueni Pan'}}
2018-01-01 21:38:35,553 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:35,557 : INFO : < 200 OK [1381]
2018-01-01 21:38:35,561 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert Duvall'}}
2018-01-01 21:38:35,561 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:35,565 : INFO : < 200 OK [1374]
2018-01-01 21:38:35,569 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John McGready, PhD, MS'}}
2018-01-01 21:38:35,573 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:35,577 : INFO : < 200 OK [1383]
2018-01-01 21:38:35,577 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Helen Tibbo'}}
2018-01-01 21:38:35,581 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:35,585 : INFO : < 200 OK [1372]
2018-01-01 21:38:35,585 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Hunter Whitney'}}
2018-01-01 21:38:35,589 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:35,593 : INFO : < 200 OK [1375]
2018-01-01 21:38:35,593 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Yvonne Breyer'}}
2018-01-01 21:38:35,593 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:35,597 : INFO : < 200 OK [1377]
2018-01-01 21:38:35,601 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Praveen Mittal'}}
2018-01-01 21:38:35,601 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:35,605 : INFO : < 200 OK [1375]
2018-01-01 21:38:35,609 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ekaterina Lobacheva'}}
2018-01-01 21:38:35,609 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:35,613 : INFO : < 200 OK [1380]
2018-01-01 21:38:35,613 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Harinath Garudadri'}}
2018-01-01 21:38:35,618 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:35,623 : INFO : < 200 OK [1379]
2018-01-01 21:38:35,625 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexey Dolinskiy'}}
2018-01-01 21:38:35,626 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:35,630 : INFO : < 200 OK [1377]
2018-01-01 21:38:35,632 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrea Zonca'}}
2018-01-01 21:38:35,633 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:35,637 : INFO : < 200 OK [1373]
2018-01-01 21:38:35,641 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Brian Caffo, PhD'}}
2018-01-01 21:38:35,641 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:35,649 : INFO : < 200 OK [1377]
2018-01-01 21:38:35,649 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Cristiano Guarana'}}
2018-01-01 21:38:35,653 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:35,657 : INFO : < 200 OK [1378]
2018-01-01 21:38:35,657 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel Lakens'}}
2018-01-01 21:38:35,661 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:35,665 : INFO : < 200 OK [1374]
2018-01-01 21:38:35,665 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Rajesh P. N. Rao'}}
2018-01-01 21:38:35,669 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:35,673 : INFO : < 200 OK [1377]
2018-01-01 21:38:35,673 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Telethia Willis'}}
2018-01-01 21:38:35,677 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:35,681 : INFO : < 200 OK [1376]
2018-01-01 21:38:35,681 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Carleton Coffrin'}}
2018-01-01 21:38:35,685 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:35,689 : INFO : < 200 OK [1381]
2018-01-01 21:38:35,689 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christophe Rhodes'}}
2018-01-01 21:38:35,693 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:35,697 : INFO : < 200 OK [1378]
2018-01-01 21:38:35,697 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexander Panin'}}
2018-01-01 21:38:35,697 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:35,705 : INFO : < 200 OK [1376]
2018-01-01 21:38:35,705 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Roger Barr'}}
2018-01-01 21:38:35,705 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:35,709 : INFO : < 200 OK [1375]
2018-01-01 21:38:35,713 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nguyen Gia Tuan'}}
2018-01-01 21:38:35,713 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:35,719 : INFO : < 200 OK [1376]
2018-01-01 21:38:35,721 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alex Mannella'}}
2018-01-01 21:38:35,722 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:35,726 : INFO : < 200 OK [1374]
2018-01-01 21:38:35,728 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Brian J Bushee'}}
2018-01-01 21:38:35,730 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:35,732 : INFO : < 200 OK [1375]
2018-01-01 21:38:35,732 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexey Artemov'}}
2018-01-01 21:38:35,737 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:35,741 : INFO : < 200 OK [1375]
2018-01-01 21:38:35,741 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Greg Williams'}}
2018-01-01 21:38:35,741 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:35,749 : INFO : < 200 OK [1374]
2018-01-01 21:38:35,749 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jean-Pierre Deschamps'}}
2018-01-01 21:38:35,749 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:35,753 : INFO : < 200 OK [1382]
2018-01-01 21:38:35,757 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Inés Friss de Kereki'}}
2018-01-01 21:38:35,757 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:35,761 : INFO : < 200 OK [1382]
2018-01-01 21:38:35,765 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Marie-Laure Boucheret'}}
2018-01-01 21:38:35,765 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:35,777 : INFO : < 200 OK [1382]
2018-01-01 21:38:35,777 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Richard Waterman'}}
2018-01-01 21:38:35,781 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:35,789 : INFO : < 200 OK [1377]
2018-01-01 21:38:35,793 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Senthil Veeraraghavan'}}
2018-01-01 21:38:35,793 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:35,797 : INFO : < 200 OK [1382]
2018-01-01 21:38:35,801 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dan Boneh'}}

2018-01-01 21:38:35,801 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:35,805 : INFO : < 200 OK [1370]
2018-01-01 21:38:35,809 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sol Bermann'}}
2018-01-01 21:38:35,809 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:35,813 : INFO : < 200 OK [1372]
2018-01-01 21:38:35,817 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert Ghrist'}}
2018-01-01 21:38:35,817 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:35,822 : INFO : < 200 OK [1374]
2018-01-01 21:38:35,824 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John Walicki'}}
2018-01-01 21:38:35,826 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:35,831 : INFO : < 200 OK [1373]
2018-01-01 21:38:35,832 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vera Schölmerich'}}
2018-01-01 21:38:35,833 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:35,837 : INFO : < 200 OK [1378]
2018-01-01 21:38:35,837 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'J. Alex Halderman'}}
2018-01-01 21:38:35,841 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:35,845 : INFO : < 200 OK [1378]
2018-01-01 21:38:35,845 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Jerry Roth'}}
2018-01-01 21:38:35,849 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:35,853 : INFO : < 200 OK [1375]
2018-01-01 21:38:35,853 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Head Teaching Assistant - Kian Katanforoosh'}}
2018-01-01 21:38:35,857 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2018-01-01 21:38:35,861 : INFO : < 200 OK [1404]
2018-01-01 21:38:35,861 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ant Cole'}}
2018-01-01 21:38:35,865 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2018-01-01 21:38:35,869 : INFO : < 200 OK [1369]
2018-01-01 21:38:35,869 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Merlise A Clyde'}}
2018-01-01 21:38:35,873 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:35,877 : INFO : < 200 OK [1376]
2018-01-01 21:38:35,877 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Whitman, Ph.D., CISM, CISSP'}}
2018-01-01 21:38:35,877 : INFO : > POST http://localhost:7474/db/data/cypher [110]
2018-01-01 21:38:35,885 : INFO : < 200 OK [1396]
2018-01-01 21:38:35,885 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ben Langmead, PhD'}}
2018-01-01 21:38:35,885 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:35,889 : INFO : < 200 OK [1378]
2018-01-01 21:38:35,893 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Wayne'}}
2018-01-01 21:38:35,893 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:35,901 : INFO : < 200 OK [1372]
2018-01-01 21:38:35,901 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Roger D. Peng, PhD'}}
2018-01-01 21:38:35,901 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:35,909 : INFO : < 200 OK [1379]
2018-01-01 21:38:35,909 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Geoffrey Hinton'}}
2018-01-01 21:38:35,913 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:35,917 : INFO : < 200 OK [1376]
2018-01-01 21:38:35,917 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Eric Sobie, PhD'}}
2018-01-01 21:38:35,923 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:35,928 : INFO : < 200 OK [1376]
2018-01-01 21:38:35,931 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Bill Boyd'}}
2018-01-01 21:38:35,933 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:35,933 : INFO : < 200 OK [1370]
2018-01-01 21:38:35,937 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Tom  Morley'}}
2018-01-01 21:38:35,941 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:35,941 : INFO : < 200 OK [1376]
2018-01-01 21:38:35,945 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Areti Manataki'}}
2018-01-01 21:38:35,949 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:35,953 : INFO : < 200 OK [1375]
2018-01-01 21:38:35,953 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jacob Pritt'}}
2018-01-01 21:38:35,957 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:35,961 : INFO : < 200 OK [1372]
2018-01-01 21:38:35,965 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dan Zhang'}}
2018-01-01 21:38:35,965 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:35,973 : INFO : < 200 OK [1370]
2018-01-01 21:38:35,973 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Julie L. Johnson'}}
2018-01-01 21:38:35,977 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:35,981 : INFO : < 200 OK [1381]
2018-01-01 21:38:35,981 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alex Fosdick'}}
2018-01-01 21:38:35,985 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:35,989 : INFO : < 200 OK [1373]
2018-01-01 21:38:35,993 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Bill Howe'}}
2018-01-01 21:38:35,993 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:35,997 : INFO : < 200 OK [1370]
2018-01-01 21:38:36,001 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': "Nick O'Leary"}}
2018-01-01 21:38:36,001 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,005 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,009 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kiran Chittargi'}}
2018-01-01 21:38:36,009 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:36,017 : INFO : < 200 OK [1376]
2018-01-01 21:38:36,020 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nikolay Vyahhi'}}
2018-01-01 21:38:36,022 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,026 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,028 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Cade Massey'}}
2018-01-01 21:38:36,030 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:36,033 : INFO : < 200 OK [1372]
2018-01-01 21:38:36,033 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Jorge Blasco Alis'}}
2018-01-01 21:38:36,037 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:36,041 : INFO : < 200 OK [1381]
2018-01-01 21:38:36,045 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel M Kane'}}
2018-01-01 21:38:36,045 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:36,049 : INFO : < 200 OK [1374]
2018-01-01 21:38:36,053 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Takeo Igarashi'}}
2018-01-01 21:38:36,053 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,057 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,061 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Rachel Cohen Lehman'}}
2018-01-01 21:38:36,061 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:36,065 : INFO : < 200 OK [1384]
2018-01-01 21:38:36,069 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Merete Badger'}}
2018-01-01 21:38:36,069 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:36,073 : INFO : < 200 OK [1374]
2018-01-01 21:38:36,077 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ganz Chockalingam'}}
2018-01-01 21:38:36,077 : INFO : > POST http://localhost:7474/db/data/cypher [92]

2018-01-01 21:38:36,081 : INFO : < 200 OK [1378]
2018-01-01 21:38:36,085 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Shannon Bradshaw'}}
2018-01-01 21:38:36,085 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,089 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,093 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Douglas C. Schmidt'}}
2018-01-01 21:38:36,093 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:36,097 : INFO : < 200 OK [1383]
2018-01-01 21:38:36,101 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexander Novikov'}}
2018-01-01 21:38:36,101 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:36,105 : INFO : < 200 OK [1378]
2018-01-01 21:38:36,105 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrew Ng'}}
2018-01-01 21:38:36,109 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:36,113 : INFO : < 200 OK [1370]
2018-01-01 21:38:36,113 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Wendt'}}
2018-01-01 21:38:36,118 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:36,122 : INFO : < 200 OK [1372]
2018-01-01 21:38:36,124 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nicolas Glady '}}
2018-01-01 21:38:36,126 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,130 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,132 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Erik Kole'}}
2018-01-01 21:38:36,133 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:36,137 : INFO : < 200 OK [1370]
2018-01-01 21:38:36,137 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ekaterina Amerik'}}
2018-01-01 21:38:36,141 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,145 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,145 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Professor Wayne Winston'}}
2018-01-01 21:38:36,145 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:36,153 : INFO : < 200 OK [1384]
2018-01-01 21:38:36,153 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sadie St. Lawrence'}}
2018-01-01 21:38:36,153 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:36,157 : INFO : < 200 OK [1379]
2018-01-01 21:38:36,161 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Matthew Heiner'}}
2018-01-01 21:38:36,161 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,165 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,169 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Shimon Schocken'}}
2018-01-01 21:38:36,169 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:36,173 : INFO : < 200 OK [1376]
2018-01-01 21:38:36,173 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Timothy Scherr'}}
2018-01-01 21:38:36,177 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,181 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,185 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Emeli Dral '}}
2018-01-01 21:38:36,185 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:36,189 : INFO : < 200 OK [1372]
2018-01-01 21:38:36,189 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Reza Farivar'}}
2018-01-01 21:38:36,193 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,201 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,205 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Parham Aarabi'}}
2018-01-01 21:38:36,209 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:36,213 : INFO : < 200 OK [1374]
2018-01-01 21:38:36,219 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vladimir Fedorov'}}
2018-01-01 21:38:36,221 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,227 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,230 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sanjay Goel'}}
2018-01-01 21:38:36,231 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:36,233 : INFO : < 200 OK [1372]
2018-01-01 21:38:36,238 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ilya Breyman'}}
2018-01-01 21:38:36,238 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,242 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,246 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dan  Grossman'}}
2018-01-01 21:38:36,246 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:36,254 : INFO : < 200 OK [1374]
2018-01-01 21:38:36,254 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Marco Gillies'}}
2018-01-01 21:38:36,258 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,262 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,262 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'ChengXiang Zhai'}}
2018-01-01 21:38:36,266 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:36,270 : INFO : < 200 OK [1376]
2018-01-01 21:38:36,270 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'P. Brighten Godfrey'}}
2018-01-01 21:38:36,274 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:36,278 : INFO : < 200 OK [1380]
2018-01-01 21:38:36,278 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Professor Pascal Van Hentenryck'}}
2018-01-01 21:38:36,282 : INFO : > POST http://localhost:7474/db/data/cypher [106]
2018-01-01 21:38:36,286 : INFO : < 200 OK [1392]
2018-01-01 21:38:36,286 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ian Harris'}}
2018-01-01 21:38:36,290 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:36,294 : INFO : < 200 OK [1371]
2018-01-01 21:38:36,294 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Elizabeth Sweeney '}}
2018-01-01 21:38:36,298 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:36,302 : INFO : < 200 OK [1383]
2018-01-01 21:38:36,302 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vivek Sarkar'}}
2018-01-01 21:38:36,306 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,310 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,314 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Morten Vesterager Madsen'}}
2018-01-01 21:38:36,314 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2018-01-01 21:38:36,319 : INFO : < 200 OK [1385]
2018-01-01 21:38:36,322 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kenneth W T Leung'}}
2018-01-01 21:38:36,324 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:36,328 : INFO : < 200 OK [1378]
2018-01-01 21:38:36,330 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Julien Fasson'}}
2018-01-01 21:38:36,331 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:36,333 : INFO : < 200 OK [1374]
2018-01-01 21:38:36,337 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Алексей Перепелкин'}}
2018-01-01 21:38:36,337 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:36,341 : INFO : < 200 OK [1396]
2018-01-01 21:38:36,345 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mikhail Trofimov'}}
2018-01-01 21:38:36,345 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,349 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,353 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Martine Haas'}}
2018-01-01 21:38:36,353 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,361 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,361 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ivan Puzyrevskiy'}}

2018-01-01 21:38:36,365 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,369 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,373 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr.  Margaret Anne Schedel'}}
2018-01-01 21:38:36,373 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2018-01-01 21:38:36,381 : INFO : < 200 OK [1387]
2018-01-01 21:38:36,381 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Elena Valderrama'}}
2018-01-01 21:38:36,385 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,389 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,389 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Banks'}}
2018-01-01 21:38:36,393 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:36,397 : INFO : < 200 OK [1372]
2018-01-01 21:38:36,397 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Evgeny Frolov'}}
2018-01-01 21:38:36,401 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:36,405 : INFO : < 200 OK [1374]
2018-01-01 21:38:36,405 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mine Çetinkaya-Rundel'}}
2018-01-01 21:38:36,405 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2018-01-01 21:38:36,413 : INFO : < 200 OK [1383]
2018-01-01 21:38:36,413 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Charlie Nuttelman'}}
2018-01-01 21:38:36,417 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:36,422 : INFO : < 200 OK [1378]
2018-01-01 21:38:36,425 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Scott  Klemmer'}}
2018-01-01 21:38:36,426 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,431 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,434 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Seong-Lyun Kim'}}
2018-01-01 21:38:36,434 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,438 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,442 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jen Rose'}}
2018-01-01 21:38:36,442 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2018-01-01 21:38:36,446 : INFO : < 200 OK [1369]
2018-01-01 21:38:36,450 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John Greiner'}}
2018-01-01 21:38:36,450 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,454 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,458 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrey Vladimirov'}}
2018-01-01 21:38:36,458 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:36,462 : INFO : < 200 OK [1378]
2018-01-01 21:38:36,466 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Romeo Kienzler'}}
2018-01-01 21:38:36,466 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,470 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,474 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Annemarie Zand Scholten'}}
2018-01-01 21:38:36,474 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:36,482 : INFO : < 200 OK [1384]
2018-01-01 21:38:36,482 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Pavel Manakhov'}}
2018-01-01 21:38:36,486 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,490 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,490 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Cook, PhD'}}
2018-01-01 21:38:36,494 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:36,498 : INFO : < 200 OK [1376]
2018-01-01 21:38:36,498 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Julien Richard-Foy'}}
2018-01-01 21:38:36,502 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:36,506 : INFO : < 200 OK [1383]
2018-01-01 21:38:36,506 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Khurram Afridi'}}
2018-01-01 21:38:36,510 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:36,514 : INFO : < 200 OK [1379]
2018-01-01 21:38:36,514 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Roy H. Campbell'}}
2018-01-01 21:38:36,514 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:36,522 : INFO : < 200 OK [1376]
2018-01-01 21:38:36,523 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Maarten Weyn'}}
2018-01-01 21:38:36,525 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,529 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,531 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Phillip Compeau'}}
2018-01-01 21:38:36,532 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:36,534 : INFO : < 200 OK [1376]
2018-01-01 21:38:36,538 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Don Patterson'}}
2018-01-01 21:38:36,538 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:36,542 : INFO : < 200 OK [1374]
2018-01-01 21:38:36,546 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Paul Bendich'}}
2018-01-01 21:38:36,546 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,550 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,554 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mariel Leonard'}}
2018-01-01 21:38:36,554 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,558 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,562 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sergei Obiedkov '}}
2018-01-01 21:38:36,562 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,566 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,570 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Gail Swanlund'}}
2018-01-01 21:38:36,570 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:36,578 : INFO : < 200 OK [1374]
2018-01-01 21:38:36,578 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Kathryn Wingate'}}
2018-01-01 21:38:36,582 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:36,586 : INFO : < 200 OK [1380]
2018-01-01 21:38:36,590 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Paul Gries'}}
2018-01-01 21:38:36,594 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:36,598 : INFO : < 200 OK [1371]
2018-01-01 21:38:36,602 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Keith Devlin'}}
2018-01-01 21:38:36,602 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,610 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,610 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jennifer Golbeck'}}
2018-01-01 21:38:36,614 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,618 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,621 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Natalia Pritykovskaya'}}
2018-01-01 21:38:36,624 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:36,628 : INFO : < 200 OK [1382]
2018-01-01 21:38:36,631 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel Lee'}}
2018-01-01 21:38:36,634 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:36,634 : INFO : < 200 OK [1371]
2018-01-01 21:38:36,638 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr.ir. Pieter Cuijpers'}}
2018-01-01 21:38:36,638 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:36,646 : INFO : < 200 OK [1383]
2018-01-01 21:38:36,646 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Herbert J. Mattord, Ph.D., CISM, CISSP, CDP'}}
2018-01-01 21:38:36,650 : INFO : > POST http://localhost:7474/db/data/cypher [118]

2018-01-01 21:38:36,654 : INFO : < 200 OK [1404]
2018-01-01 21:38:36,658 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vladimir Lesnichenko'}}
2018-01-01 21:38:36,658 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:36,662 : INFO : < 200 OK [1381]
2018-01-01 21:38:36,666 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Evgeny Sokolov'}}
2018-01-01 21:38:36,666 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,670 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,674 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Hartman'}}
2018-01-01 21:38:36,674 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:36,678 : INFO : < 200 OK [1374]
2018-01-01 21:38:36,682 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anton Konushin'}}
2018-01-01 21:38:36,682 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,686 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,686 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Richard Lambert'}}
2018-01-01 21:38:36,690 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:36,694 : INFO : < 200 OK [1376]
2018-01-01 21:38:36,698 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Robert Erickson'}}
2018-01-01 21:38:36,698 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:36,702 : INFO : < 200 OK [1380]
2018-01-01 21:38:36,706 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Merce Rullan'}}
2018-01-01 21:38:36,706 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,710 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,714 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kostas Daniilidis'}}
2018-01-01 21:38:36,714 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:36,720 : INFO : < 200 OK [1378]
2018-01-01 21:38:36,721 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel E. Koditschek'}}
2018-01-01 21:38:36,723 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:36,728 : INFO : < 200 OK [1381]
2018-01-01 21:38:36,730 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Peter Fader'}}
2018-01-01 21:38:36,732 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:36,734 : INFO : < 200 OK [1372]
2018-01-01 21:38:36,738 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Rebekah May'}}
2018-01-01 21:38:36,738 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:36,742 : INFO : < 200 OK [1372]
2018-01-01 21:38:36,746 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Albert Glock'}}
2018-01-01 21:38:36,746 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,750 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,754 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Aleksandar Prokopec'}}
2018-01-01 21:38:36,754 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:36,758 : INFO : < 200 OK [1384]
2018-01-01 21:38:36,762 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Fran Krause'}}
2018-01-01 21:38:36,762 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:36,770 : INFO : < 200 OK [1372]
2018-01-01 21:38:36,770 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Mick Grierson'}}
2018-01-01 21:38:36,774 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,778 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,778 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Simon Holmbacka'}}
2018-01-01 21:38:36,778 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:36,786 : INFO : < 200 OK [1376]
2018-01-01 21:38:36,786 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christopher Brooks'}}
2018-01-01 21:38:36,786 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:36,794 : INFO : < 200 OK [1379]
2018-01-01 21:38:36,794 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Guillermo Sapiro'}}
2018-01-01 21:38:36,794 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,798 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,802 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Poul Ejnar Sørensen'}}
2018-01-01 21:38:36,806 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2018-01-01 21:38:36,810 : INFO : < 200 OK [1381]
2018-01-01 21:38:36,810 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Philip Hans Franses'}}
2018-01-01 21:38:36,814 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:36,819 : INFO : < 200 OK [1380]
2018-01-01 21:38:36,822 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Mike Ryan'}}
2018-01-01 21:38:36,824 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,828 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,829 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jim Stafford'}}
2018-01-01 21:38:36,831 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,834 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,838 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sudhir Voleti'}}
2018-01-01 21:38:36,838 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:36,842 : INFO : < 200 OK [1374]
2018-01-01 21:38:36,846 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Hanspeter Schaub'}}
2018-01-01 21:38:36,846 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,850 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,854 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Gang Qu'}}
2018-01-01 21:38:36,854 : INFO : > POST http://localhost:7474/db/data/cypher [82]
2018-01-01 21:38:36,858 : INFO : < 200 OK [1368]
2018-01-01 21:38:36,862 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Bañeres'}}
2018-01-01 21:38:36,866 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:36,870 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,874 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Veronica Scurtu'}}
2018-01-01 21:38:36,874 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:36,882 : INFO : < 200 OK [1376]
2018-01-01 21:38:36,886 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Autodesk Education'}}
2018-01-01 21:38:36,886 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:36,890 : INFO : < 200 OK [1379]
2018-01-01 21:38:36,894 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Krishna Garikipati, Ph.D.'}}
2018-01-01 21:38:36,894 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:36,898 : INFO : < 200 OK [1386]
2018-01-01 21:38:36,902 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Leyton-Brown'}}
2018-01-01 21:38:36,902 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:36,906 : INFO : < 200 OK [1379]
2018-01-01 21:38:36,910 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Suk S. Brar, M.B.A.'}}
2018-01-01 21:38:36,910 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:36,918 : INFO : < 200 OK [1380]
2018-01-01 21:38:36,920 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anne Bracy'}}
2018-01-01 21:38:36,922 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:36,926 : INFO : < 200 OK [1371]
2018-01-01 21:38:36,928 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Xavier Serra'}}
2018-01-01 21:38:36,931 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,934 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,934 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel Egger'}}

2018-01-01 21:38:36,938 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:36,942 : INFO : < 200 OK [1373]
2018-01-01 21:38:36,942 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kirby Kohlmorgen'}}
2018-01-01 21:38:36,946 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:36,950 : INFO : < 200 OK [1377]
2018-01-01 21:38:36,950 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Дмитрий Савицкий'}}
2018-01-01 21:38:36,954 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2018-01-01 21:38:36,958 : INFO : < 200 OK [1392]
2018-01-01 21:38:36,962 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jeff Leek, PhD'}}
2018-01-01 21:38:36,962 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,966 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,966 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel Randall'}}
2018-01-01 21:38:36,970 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:36,974 : INFO : < 200 OK [1375]
2018-01-01 21:38:36,978 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Matthew Bidwell'}}
2018-01-01 21:38:36,978 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:36,982 : INFO : < 200 OK [1376]
2018-01-01 21:38:36,986 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ralf Brockhaus '}}
2018-01-01 21:38:36,986 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:36,990 : INFO : < 200 OK [1376]
2018-01-01 21:38:36,994 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Prof. Peter James Stuckey'}}
2018-01-01 21:38:36,994 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:36,998 : INFO : < 200 OK [1386]
2018-01-01 21:38:36,998 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Brent Hecht'}}
2018-01-01 21:38:37,002 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,006 : INFO : < 200 OK [1376]
2018-01-01 21:38:37,010 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kristen Walcott-Justice'}}
2018-01-01 21:38:37,010 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:37,014 : INFO : < 200 OK [1384]
2018-01-01 21:38:37,018 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': ' Dr Sorrel Harriet'}}
2018-01-01 21:38:37,020 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:37,025 : INFO : < 200 OK [1379]
2018-01-01 21:38:37,028 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Clement Levallois'}}
2018-01-01 21:38:37,030 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:37,033 : INFO : < 200 OK [1378]
2018-01-01 21:38:37,034 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Traci Carte'}}
2018-01-01 21:38:37,038 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,042 : INFO : < 200 OK [1376]
2018-01-01 21:38:37,042 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ankit Singla'}}
2018-01-01 21:38:37,046 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:37,050 : INFO : < 200 OK [1373]
2018-01-01 21:38:37,050 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alex Cowan'}}
2018-01-01 21:38:37,054 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:37,058 : INFO : < 200 OK [1371]
2018-01-01 21:38:37,058 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Anthony C. Robinson'}}
2018-01-01 21:38:37,062 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:37,066 : INFO : < 200 OK [1384]
2018-01-01 21:38:37,066 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sergei Savin'}}
2018-01-01 21:38:37,066 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:37,074 : INFO : < 200 OK [1373]
2018-01-01 21:38:37,074 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Noah Gans'}}
2018-01-01 21:38:37,074 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:37,078 : INFO : < 200 OK [1370]
2018-01-01 21:38:37,082 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Karen  Monsen, Ph.D., RN, FAAN'}}
2018-01-01 21:38:37,082 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2018-01-01 21:38:37,086 : INFO : < 200 OK [1391]
2018-01-01 21:38:37,090 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Dunn'}}
2018-01-01 21:38:37,090 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:37,098 : INFO : < 200 OK [1371]
2018-01-01 21:38:37,102 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Rajkumar Venkatesan'}}
2018-01-01 21:38:37,102 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:37,110 : INFO : < 200 OK [1380]
2018-01-01 21:38:37,110 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Humayun Zafar'}}
2018-01-01 21:38:37,114 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:37,122 : INFO : < 200 OK [1378]
2018-01-01 21:38:37,125 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Melissa Clarke'}}
2018-01-01 21:38:37,126 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:37,132 : INFO : < 200 OK [1375]
2018-01-01 21:38:37,134 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vladimir Podolskii'}}
2018-01-01 21:38:37,134 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:37,138 : INFO : < 200 OK [1379]
2018-01-01 21:38:37,142 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nikita Kazeev'}}
2018-01-01 21:38:37,142 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:37,146 : INFO : < 200 OK [1374]
2018-01-01 21:38:37,150 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Genevieve M. Lipp'}}
2018-01-01 21:38:37,150 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:37,154 : INFO : < 200 OK [1378]
2018-01-01 21:38:37,158 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Matthijs Rooduijn'}}
2018-01-01 21:38:37,158 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:37,162 : INFO : < 200 OK [1378]
2018-01-01 21:38:37,166 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mung Chiang'}}
2018-01-01 21:38:37,166 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:37,170 : INFO : < 200 OK [1372]
2018-01-01 21:38:37,174 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Traian Lavric'}}
2018-01-01 21:38:37,174 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:37,178 : INFO : < 200 OK [1374]
2018-01-01 21:38:37,182 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr  Lorenzo Cavallaro'}}
2018-01-01 21:38:37,182 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:37,190 : INFO : < 200 OK [1382]
2018-01-01 21:38:37,190 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dick van Dijk '}}
2018-01-01 21:38:37,194 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:37,198 : INFO : < 200 OK [1375]
2018-01-01 21:38:37,202 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Gerben Moerman'}}
2018-01-01 21:38:37,202 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:37,206 : INFO : < 200 OK [1375]
2018-01-01 21:38:37,210 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Steven Salzberg, PhD'}}
2018-01-01 21:38:37,214 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:37,219 : INFO : < 200 OK [1381]
2018-01-01 21:38:37,221 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Petra Bonfert-Taylor'}}
2018-01-01 21:38:37,223 : INFO : > POST http://localhost:7474/db/data/cypher [99]

2018-01-01 21:38:37,228 : INFO : < 200 OK [1385]
2018-01-01 21:38:37,231 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael D. Ekstrand'}}
2018-01-01 21:38:37,232 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:37,234 : INFO : < 200 OK [1380]
2018-01-01 21:38:37,238 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Charles Severance'}}
2018-01-01 21:38:37,238 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:37,242 : INFO : < 200 OK [1378]
2018-01-01 21:38:37,246 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Susan H. Rodger'}}
2018-01-01 21:38:37,246 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,250 : INFO : < 200 OK [1376]
2018-01-01 21:38:37,254 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jana Schaich Borg'}}
2018-01-01 21:38:37,254 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:37,258 : INFO : < 200 OK [1378]
2018-01-01 21:38:37,262 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Pavel Shvechikov'}}
2018-01-01 21:38:37,262 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:37,266 : INFO : < 200 OK [1377]
2018-01-01 21:38:37,270 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Professor Peter Komisarczuk'}}
2018-01-01 21:38:37,274 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2018-01-01 21:38:37,278 : INFO : < 200 OK [1388]
2018-01-01 21:38:37,282 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Evgeny Smirnov'}}
2018-01-01 21:38:37,282 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:37,286 : INFO : < 200 OK [1375]
2018-01-01 21:38:37,290 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Edward G. Amoroso'}}
2018-01-01 21:38:37,290 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:37,298 : INFO : < 200 OK [1382]
2018-01-01 21:38:37,298 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Ian  Faulconbridge '}}
2018-01-01 21:38:37,302 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:37,306 : INFO : < 200 OK [1383]
2018-01-01 21:38:37,306 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Colin Rundel '}}
2018-01-01 21:38:37,310 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:37,314 : INFO : < 200 OK [1374]
2018-01-01 21:38:37,319 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Neil Rhodes'}}
2018-01-01 21:38:37,320 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:37,324 : INFO : < 200 OK [1372]
2018-01-01 21:38:37,327 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Simon Murphy'}}
2018-01-01 21:38:37,329 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:37,333 : INFO : < 200 OK [1373]
2018-01-01 21:38:37,334 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alma Salnaja'}}
2018-01-01 21:38:37,334 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:37,342 : INFO : < 200 OK [1373]
2018-01-01 21:38:37,342 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Brian Winn'}}
2018-01-01 21:38:37,346 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:37,350 : INFO : < 200 OK [1371]
2018-01-01 21:38:37,350 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John Gill, J.D., CFE'}}
2018-01-01 21:38:37,354 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:37,358 : INFO : < 200 OK [1381]
2018-01-01 21:38:37,358 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nick Santos'}}
2018-01-01 21:38:37,358 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:37,362 : INFO : < 200 OK [1372]
2018-01-01 21:38:37,366 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tim Roughgarden'}}
2018-01-01 21:38:37,366 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,374 : INFO : < 200 OK [1376]
2018-01-01 21:38:37,374 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Schweidel'}}
2018-01-01 21:38:37,378 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,382 : INFO : < 200 OK [1376]
2018-01-01 21:38:37,386 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Richard Dull, Ph.D'}}
2018-01-01 21:38:37,386 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:37,390 : INFO : < 200 OK [1383]
2018-01-01 21:38:37,394 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Juha Plosila'}}
2018-01-01 21:38:37,394 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:37,402 : INFO : < 200 OK [1373]
2018-01-01 21:38:37,406 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Scott Rixner'}}
2018-01-01 21:38:37,406 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:37,414 : INFO : < 200 OK [1373]
2018-01-01 21:38:37,414 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Luay Nakhleh'}}
2018-01-01 21:38:37,419 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:37,424 : INFO : < 200 OK [1373]
2018-01-01 21:38:37,427 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Henrik Bredmose'}}
2018-01-01 21:38:37,429 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,434 : INFO : < 200 OK [1376]
2018-01-01 21:38:37,434 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Adrienne Fairhall'}}
2018-01-01 21:38:37,438 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:37,442 : INFO : < 200 OK [1378]
2018-01-01 21:38:37,442 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Van Kleeck'}}
2018-01-01 21:38:37,446 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:37,450 : INFO : < 200 OK [1377]
2018-01-01 21:38:37,450 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Wayne Whiteman, PE'}}
2018-01-01 21:38:37,454 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:37,458 : INFO : < 200 OK [1383]
2018-01-01 21:38:37,458 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Yianna Papadakis Kantos'}}
2018-01-01 21:38:37,462 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:37,466 : INFO : < 200 OK [1384]
2018-01-01 21:38:37,470 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Richard White'}}
2018-01-01 21:38:37,470 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:37,474 : INFO : < 200 OK [1374]
2018-01-01 21:38:37,478 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jogesh K. Muppala'}}
2018-01-01 21:38:37,478 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:37,482 : INFO : < 200 OK [1378]
2018-01-01 21:38:37,486 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Elizabeth Gerber'}}
2018-01-01 21:38:37,486 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:37,490 : INFO : < 200 OK [1377]
2018-01-01 21:38:37,494 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Robert Allen Robinson, Jr.'}}
2018-01-01 21:38:37,494 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2018-01-01 21:38:37,498 : INFO : < 200 OK [1391]
2018-01-01 21:38:37,502 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Matthew O. Jackson'}}
2018-01-01 21:38:37,502 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:37,506 : INFO : < 200 OK [1379]
2018-01-01 21:38:37,510 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Owen Astrachan'}}
2018-01-01 21:38:37,510 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:37,514 : INFO : < 200 OK [1375]

2018-01-01 21:38:37,514 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dave Gorman'}}
2018-01-01 21:38:37,520 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:37,524 : INFO : < 200 OK [1372]
2018-01-01 21:38:37,526 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Gautam Kaul'}}
2018-01-01 21:38:37,527 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:37,532 : INFO : < 200 OK [1372]
2018-01-01 21:38:37,533 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Dragan Maksimovic'}}
2018-01-01 21:38:37,535 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:37,539 : INFO : < 200 OK [1382]
2018-01-01 21:38:37,543 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Greg Heileman'}}
2018-01-01 21:38:37,543 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:37,547 : INFO : < 200 OK [1374]
2018-01-01 21:38:37,551 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mikhail Hushchyn'}}
2018-01-01 21:38:37,551 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:37,555 : INFO : < 200 OK [1377]
2018-01-01 21:38:37,559 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. C. Jules White'}}
2018-01-01 21:38:37,559 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:37,563 : INFO : < 200 OK [1379]
2018-01-01 21:38:37,567 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. José Martín Molina Espinosa'}}
2018-01-01 21:38:37,567 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2018-01-01 21:38:37,571 : INFO : < 200 OK [1394]
2018-01-01 21:38:37,575 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Roberto Cazzolla Gatti'}}
2018-01-01 21:38:37,575 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:37,579 : INFO : < 200 OK [1383]
2018-01-01 21:38:37,583 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Noam  Nisan'}}
2018-01-01 21:38:37,583 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:37,587 : INFO : < 200 OK [1372]
2018-01-01 21:38:37,587 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexey Zobnin'}}
2018-01-01 21:38:37,591 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:37,595 : INFO : < 200 OK [1374]
2018-01-01 21:38:37,599 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Kate Devlin'}}
2018-01-01 21:38:37,599 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:37,603 : INFO : < 200 OK [1375]
2018-01-01 21:38:37,603 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Torgerson'}}
2018-01-01 21:38:37,607 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,611 : INFO : < 200 OK [1376]
2018-01-01 21:38:37,611 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Natasha Balac'}}
2018-01-01 21:38:37,615 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:37,620 : INFO : < 200 OK [1374]
2018-01-01 21:38:37,622 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Haiyi Zhu'}}
2018-01-01 21:38:37,624 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:37,628 : INFO : < 200 OK [1370]
2018-01-01 21:38:37,630 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tor Wager'}}
2018-01-01 21:38:37,632 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:37,635 : INFO : < 200 OK [1370]
2018-01-01 21:38:37,635 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Hicks'}}
2018-01-01 21:38:37,639 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:37,643 : INFO : < 200 OK [1374]
2018-01-01 21:38:37,643 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christina Scherrer, PhD'}}
2018-01-01 21:38:37,647 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:37,651 : INFO : < 200 OK [1384]
2018-01-01 21:38:37,651 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Niels-Erik Clausen'}}
2018-01-01 21:38:37,655 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:37,659 : INFO : < 200 OK [1379]
2018-01-01 21:38:37,663 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Edward Chow'}}
2018-01-01 21:38:37,663 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:37,671 : INFO : < 200 OK [1372]
2018-01-01 21:38:37,671 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sergey Yudin'}}
2018-01-01 21:38:37,675 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:37,679 : INFO : < 200 OK [1373]
2018-01-01 21:38:37,683 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Chi Zhou'}}
2018-01-01 21:38:37,683 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2018-01-01 21:38:37,691 : INFO : < 200 OK [1369]
2018-01-01 21:38:37,695 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Bill Bailey, PhD'}}
2018-01-01 21:38:37,695 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:37,699 : INFO : < 200 OK [1377]
2018-01-01 21:38:37,703 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert W. Holthausen'}}
2018-01-01 21:38:37,703 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:37,707 : INFO : < 200 OK [1381]
2018-01-01 21:38:37,711 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jiawei Han'}}
2018-01-01 21:38:37,711 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:37,715 : INFO : < 200 OK [1371]
2018-01-01 21:38:37,715 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sven-Erik Gryning'}}
2018-01-01 21:38:37,720 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:37,725 : INFO : < 200 OK [1378]
2018-01-01 21:38:37,727 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dragomir R. Radev, Ph.D.'}}
2018-01-01 21:38:37,729 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2018-01-01 21:38:37,733 : INFO : < 200 OK [1385]
2018-01-01 21:38:37,735 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Stephen Wong'}}
2018-01-01 21:38:37,735 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:37,739 : INFO : < 200 OK [1373]
2018-01-01 21:38:37,743 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': "Maeve O'Reilly"}}
2018-01-01 21:38:37,743 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:37,747 : INFO : < 200 OK [1375]
2018-01-01 21:38:37,751 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ken English'}}
2018-01-01 21:38:37,751 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:37,755 : INFO : < 200 OK [1372]
2018-01-01 21:38:37,759 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Richard Valliant, Ph.D.'}}
2018-01-01 21:38:37,759 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:37,763 : INFO : < 200 OK [1384]
2018-01-01 21:38:37,767 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Théotime Vaillant'}}
2018-01-01 21:38:37,767 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:37,771 : INFO : < 200 OK [1379]
2018-01-01 21:38:37,775 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Levin'}}
2018-01-01 21:38:37,775 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:37,779 : INFO : < 200 OK [1374]
2018-01-01 21:38:37,783 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ilya Trofimov'}}
2018-01-01 21:38:37,783 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:37,787 : INFO : < 200 OK [1374]
2018-01-01 21:38:37,791 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jim Fowler, PhD'}}

2018-01-01 21:38:37,791 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,795 : INFO : < 200 OK [1376]
2018-01-01 21:38:37,795 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrei Zimovnov'}}
2018-01-01 21:38:37,799 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,803 : INFO : < 200 OK [1376]
2018-01-01 21:38:37,807 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Lana Yarosh'}}
2018-01-01 21:38:37,807 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:37,811 : INFO : < 200 OK [1386]
2018-01-01 21:38:37,815 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Adam Porter'}}
2018-01-01 21:38:37,815 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,820 : INFO : < 200 OK [1376]
2018-01-01 21:38:37,823 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Chan-Byoung Chae'}}
2018-01-01 21:38:37,824 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:37,829 : INFO : < 200 OK [1391]
2018-01-01 21:38:37,831 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Indranil Gupta'}}
2018-01-01 21:38:37,833 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:37,835 : INFO : < 200 OK [1375]
2018-01-01 21:38:37,839 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michel Ianotto '}}
2018-01-01 21:38:37,839 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,843 : INFO : < 200 OK [1390]
2018-01-01 21:38:37,847 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Chirag Shah'}}
2018-01-01 21:38:37,847 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:37,851 : INFO : < 200 OK [1372]
2018-01-01 21:38:37,855 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'H.V. Jagadish'}}
2018-01-01 21:38:37,855 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:37,859 : INFO : < 200 OK [1388]
2018-01-01 21:38:37,863 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sara Behdad'}}
2018-01-01 21:38:37,863 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:37,867 : INFO : < 200 OK [1372]
2018-01-01 21:38:37,871 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mia Minnes'}}
2018-01-01 21:38:37,871 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:37,879 : INFO : < 200 OK [1385]
2018-01-01 21:38:37,879 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Carlos Guestrin'}}
2018-01-01 21:38:37,883 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,887 : INFO : < 200 OK [1376]
2018-01-01 21:38:37,887 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Farhoud Hosseinpour'}}
2018-01-01 21:38:37,887 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:37,895 : INFO : < 200 OK [1394]
2018-01-01 21:38:37,895 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Pavel Mezentsev '}}
2018-01-01 21:38:37,899 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:37,903 : INFO : < 200 OK [1377]
2018-01-01 21:38:37,903 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Claire Mathieu'}}
2018-01-01 21:38:37,903 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:37,911 : INFO : < 200 OK [1389]
2018-01-01 21:38:37,911 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mike Fitzpatrick'}}
2018-01-01 21:38:37,911 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:37,919 : INFO : < 200 OK [1377]
2018-01-01 21:38:37,920 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Lars Pilgaard Mikkelsen'}}
2018-01-01 21:38:37,922 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:37,926 : INFO : < 200 OK [1398]
2018-01-01 21:38:37,928 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Frauke Kreuter, Ph.D.'}}
2018-01-01 21:38:37,930 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:37,933 : INFO : < 200 OK [1396]
2018-01-01 21:38:37,935 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Rob A. Rutenbar'}}
2018-01-01 21:38:37,935 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,939 : INFO : < 200 OK [1390]
2018-01-01 21:38:37,943 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sang-Yoon Chang'}}
2018-01-01 21:38:37,943 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,947 : INFO : < 200 OK [1390]
2018-01-01 21:38:37,951 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Leo Porter'}}
2018-01-01 21:38:37,955 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:37,959 : INFO : < 200 OK [1385]
2018-01-01 21:38:37,959 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Louise Connelly'}}
2018-01-01 21:38:37,959 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:37,967 : INFO : < 200 OK [1390]
2018-01-01 21:38:37,967 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Prof. Viktor Kuncak'}}
2018-01-01 21:38:37,967 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:37,971 : INFO : < 200 OK [1394]
2018-01-01 21:38:37,975 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'James Z. Lee'}}
2018-01-01 21:38:37,975 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:37,979 : INFO : < 200 OK [1387]
2018-01-01 21:38:37,979 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Cameron Campbell'}}
2018-01-01 21:38:37,983 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:37,987 : INFO : < 200 OK [1391]
2018-01-01 21:38:37,991 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrew D. Hilton'}}
2018-01-01 21:38:37,991 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:37,995 : INFO : < 200 OK [1391]
2018-01-01 21:38:37,999 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kenny Wong'}}
2018-01-01 21:38:37,999 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:38,003 : INFO : < 200 OK [1385]
2018-01-01 21:38:38,007 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Pavel Klemenkov'}}
2018-01-01 21:38:38,007 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:38,011 : INFO : < 200 OK [1390]
2018-01-01 21:38:38,015 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Yannis Tsividis'}}
2018-01-01 21:38:38,015 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:38,021 : INFO : < 200 OK [1390]
2018-01-01 21:38:38,024 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Brian Innes'}}
2018-01-01 21:38:38,025 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:38,029 : INFO : < 200 OK [1386]
2018-01-01 21:38:38,032 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Martin Lindquist, PhD, MSc'}}
2018-01-01 21:38:38,034 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2018-01-01 21:38:38,039 : INFO : < 200 OK [1401]
2018-01-01 21:38:38,043 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Amy Moore'}}
2018-01-01 21:38:38,047 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:38,051 : INFO : < 200 OK [1384]
2018-01-01 21:38:38,055 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ilkay Altintas'}}
2018-01-01 21:38:38,055 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,063 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,063 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vijay Kumar'}}
2018-01-01 21:38:38,067 : INFO : > POST http://localhost:7474/db/data/cypher [86]

2018-01-01 21:38:38,071 : INFO : < 200 OK [1386]
2018-01-01 21:38:38,075 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Arvind Narayanan'}}
2018-01-01 21:38:38,075 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:38,083 : INFO : < 200 OK [1391]
2018-01-01 21:38:38,083 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Paul Rodriguez'}}
2018-01-01 21:38:38,087 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,091 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,095 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Teaching Assistant - Younes Bensouda Mourri'}}
2018-01-01 21:38:38,095 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2018-01-01 21:38:38,099 : INFO : < 200 OK [1418]
2018-01-01 21:38:38,103 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Nick Feamster'}}
2018-01-01 21:38:38,103 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:38,107 : INFO : < 200 OK [1392]
2018-01-01 21:38:38,107 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mr. Andy Green'}}
2018-01-01 21:38:38,111 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,115 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,119 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Matthew Yee-King'}}
2018-01-01 21:38:38,121 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:38,125 : INFO : < 200 OK [1394]
2018-01-01 21:38:38,127 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Wharton Teaching Staff'}}
2018-01-01 21:38:38,129 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:38,133 : INFO : < 200 OK [1397]
2018-01-01 21:38:38,134 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Liliana Florea, PhD'}}
2018-01-01 21:38:38,135 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:38,139 : INFO : < 200 OK [1394]
2018-01-01 21:38:38,139 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sam Kaufman'}}
2018-01-01 21:38:38,143 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:38,147 : INFO : < 200 OK [1386]
2018-01-01 21:38:38,147 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tarik Benaddi'}}
2018-01-01 21:38:38,151 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:38,155 : INFO : < 200 OK [1388]
2018-01-01 21:38:38,155 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexander Guschin'}}
2018-01-01 21:38:38,159 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:38,163 : INFO : < 200 OK [1392]
2018-01-01 21:38:38,167 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'James Taylor, PhD'}}
2018-01-01 21:38:38,167 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:38,171 : INFO : < 200 OK [1392]
2018-01-01 21:38:38,175 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Pavel  Pevzner'}}
2018-01-01 21:38:38,175 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,179 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,183 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dariush Derakhshani'}}
2018-01-01 21:38:38,183 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:38,187 : INFO : < 200 OK [1394]
2018-01-01 21:38:38,191 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kwon, Kil Hyun'}}
2018-01-01 21:38:38,191 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,195 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,199 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kellie Liket'}}
2018-01-01 21:38:38,199 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,203 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,207 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Richard Paap'}}
2018-01-01 21:38:38,207 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,211 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,215 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Yaakov Chaikin'}}
2018-01-01 21:38:38,215 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,221 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,224 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Martin Timmerman'}}
2018-01-01 21:38:38,226 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:38,230 : INFO : < 200 OK [1391]
2018-01-01 21:38:38,233 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Wentzlaff '}}
2018-01-01 21:38:38,235 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:38,235 : INFO : < 200 OK [1391]
2018-01-01 21:38:38,239 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anders Holm'}}
2018-01-01 21:38:38,239 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:38,243 : INFO : < 200 OK [1386]
2018-01-01 21:38:38,247 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christopher Brinton'}}
2018-01-01 21:38:38,247 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:38,251 : INFO : < 200 OK [1394]
2018-01-01 21:38:38,255 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Song-Kuk Kim'}}
2018-01-01 21:38:38,255 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,259 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,263 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Richard Riley, Ph.D'}}
2018-01-01 21:38:38,263 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:38,267 : INFO : < 200 OK [1398]
2018-01-01 21:38:38,271 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Virginie Galtier'}}
2018-01-01 21:38:38,271 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:38,275 : INFO : < 200 OK [1395]
2018-01-01 21:38:38,279 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert Sedgewick'}}
2018-01-01 21:38:38,279 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:38,283 : INFO : < 200 OK [1391]
2018-01-01 21:38:38,287 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Emily Fox'}}
2018-01-01 21:38:38,287 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:38,291 : INFO : < 200 OK [1384]
2018-01-01 21:38:38,291 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Isabelle Bichindaritz'}}
2018-01-01 21:38:38,295 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:38,299 : INFO : < 200 OK [1396]
2018-01-01 21:38:38,303 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Douglas Van Houweling'}}
2018-01-01 21:38:38,303 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:38,311 : INFO : < 200 OK [1396]
2018-01-01 21:38:38,315 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Torben Krogh Mikkelsen'}}
2018-01-01 21:38:38,315 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:38,322 : INFO : < 200 OK [1397]
2018-01-01 21:38:38,325 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Emil Akhmedov'}}
2018-01-01 21:38:38,327 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:38,333 : INFO : < 200 OK [1388]
2018-01-01 21:38:38,334 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Bonnie Ram'}}
2018-01-01 21:38:38,335 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:38,339 : INFO : < 200 OK [1385]
2018-01-01 21:38:38,339 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Herbert Lee'}}
2018-01-01 21:38:38,343 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:38,347 : INFO : < 200 OK [1386]

2018-01-01 21:38:38,347 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Lluis Terés'}}
2018-01-01 21:38:38,351 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:38,355 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,355 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Genesereth'}}
2018-01-01 21:38:38,359 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:38,363 : INFO : < 200 OK [1393]
2018-01-01 21:38:38,363 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Surya Kalidindi'}}
2018-01-01 21:38:38,367 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:38,371 : INFO : < 200 OK [1394]
2018-01-01 21:38:38,371 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Mannino'}}
2018-01-01 21:38:38,371 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:38,379 : INFO : < 200 OK [1390]
2018-01-01 21:38:38,379 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Raghu Iyengar'}}
2018-01-01 21:38:38,379 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:38,387 : INFO : < 200 OK [1388]
2018-01-01 21:38:38,387 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Prof. Jimmy Ho Man Lee'}}
2018-01-01 21:38:38,387 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:38,395 : INFO : < 200 OK [1397]
2018-01-01 21:38:38,395 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dae-Sik Hong'}}
2018-01-01 21:38:38,399 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,403 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,403 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexey A. Dral'}}
2018-01-01 21:38:38,403 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,411 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,411 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Williams'}}
2018-01-01 21:38:38,415 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,419 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,419 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Frank Ayars '}}
2018-01-01 21:38:38,419 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,427 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,429 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrei Ustyuzhanin'}}
2018-01-01 21:38:38,431 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:38,435 : INFO : < 200 OK [1393]
2018-01-01 21:38:38,435 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Min Song'}}
2018-01-01 21:38:38,439 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2018-01-01 21:38:38,443 : INFO : < 200 OK [1383]
2018-01-01 21:38:38,443 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Heather Miller'}}
2018-01-01 21:38:38,447 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:38,451 : INFO : < 200 OK [1393]
2018-01-01 21:38:38,455 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Juan H Klopper'}}
2018-01-01 21:38:38,455 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,459 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,463 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Marios Michailidis'}}
2018-01-01 21:38:38,463 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:38,467 : INFO : < 200 OK [1393]
2018-01-01 21:38:38,471 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Paul Harris, PhD'}}
2018-01-01 21:38:38,471 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:38,475 : INFO : < 200 OK [1391]
2018-01-01 21:38:38,479 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sarah Jones'}}
2018-01-01 21:38:38,479 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:38,483 : INFO : < 200 OK [1386]
2018-01-01 21:38:38,483 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John C. Hart'}}
2018-01-01 21:38:38,487 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,491 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,495 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anna Kozlova'}}
2018-01-01 21:38:38,495 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,499 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,503 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'CJ Taylor'}}
2018-01-01 21:38:38,503 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:38,507 : INFO : < 200 OK [1384]
2018-01-01 21:38:38,511 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'George Kapetanios'}}
2018-01-01 21:38:38,511 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:38,515 : INFO : < 200 OK [1392]
2018-01-01 21:38:38,519 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dmitry Ulyanov'}}
2018-01-01 21:38:38,519 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,524 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,527 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Akos Ledeczi'}}
2018-01-01 21:38:38,529 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,533 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,535 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Colleen van Lent, Ph.D.'}}
2018-01-01 21:38:38,535 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:38,539 : INFO : < 200 OK [1398]
2018-01-01 21:38:38,543 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sharad Borle'}}
2018-01-01 21:38:38,543 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,547 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,551 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Werbach'}}
2018-01-01 21:38:38,551 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:38,555 : INFO : < 200 OK [1388]
2018-01-01 21:38:38,559 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert Brunner'}}
2018-01-01 21:38:38,559 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,563 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,567 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Martin Vetterli'}}
2018-01-01 21:38:38,567 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:38,571 : INFO : < 200 OK [1390]
2018-01-01 21:38:38,571 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Rosa I. Arriaga'}}
2018-01-01 21:38:38,575 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:38,579 : INFO : < 200 OK [1394]
2018-01-01 21:38:38,579 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tom Cronin'}}
2018-01-01 21:38:38,583 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:38,587 : INFO : < 200 OK [1385]
2018-01-01 21:38:38,591 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mihaela Pertea, PhD'}}
2018-01-01 21:38:38,591 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:38,595 : INFO : < 200 OK [1394]
2018-01-01 21:38:38,595 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daphne Koller'}}
2018-01-01 21:38:38,599 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:38,603 : INFO : < 200 OK [1388]
2018-01-01 21:38:38,603 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jan Friso Groote'}}
2018-01-01 21:38:38,607 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:38,611 : INFO : < 200 OK [1391]
2018-01-01 21:38:38,611 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Bonnie H. Ferri'}}

2018-01-01 21:38:38,615 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:38,621 : INFO : < 200 OK [1394]
2018-01-01 21:38:38,623 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Myrthe van Dieijen'}}
2018-01-01 21:38:38,625 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:38,629 : INFO : < 200 OK [1393]
2018-01-01 21:38:38,632 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sid Deliwala'}}
2018-01-01 21:38:38,634 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,635 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,639 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Damir Filipović'}}
2018-01-01 21:38:38,643 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:38,647 : INFO : < 200 OK [1391]
2018-01-01 21:38:38,651 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Amarnath Gupta'}}
2018-01-01 21:38:38,651 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,655 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,659 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Hilmar Kjartansson Danielsen'}}
2018-01-01 21:38:38,659 : INFO : > POST http://localhost:7474/db/data/cypher [103]
2018-01-01 21:38:38,667 : INFO : < 200 OK [1403]
2018-01-01 21:38:38,671 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Avi Ma’ayan, PhD'}}
2018-01-01 21:38:38,671 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:38,675 : INFO : < 200 OK [1393]
2018-01-01 21:38:38,679 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tara Murphy'}}
2018-01-01 21:38:38,679 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:38,687 : INFO : < 200 OK [1386]
2018-01-01 21:38:38,687 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Henri Laurie'}}
2018-01-01 21:38:38,691 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,695 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,699 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr James Ohene-Djan'}}
2018-01-01 21:38:38,699 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:38,703 : INFO : < 200 OK [1394]
2018-01-01 21:38:38,707 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ira Pohl'}}
2018-01-01 21:38:38,707 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2018-01-01 21:38:38,715 : INFO : < 200 OK [1383]
2018-01-01 21:38:38,715 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sean Kross'}}
2018-01-01 21:38:38,720 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:38,724 : INFO : < 200 OK [1385]
2018-01-01 21:38:38,726 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jason A. Roy, Ph.D. '}}
2018-01-01 21:38:38,728 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:38,732 : INFO : < 200 OK [1395]
2018-01-01 21:38:38,735 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Yoav Shoham'}}
2018-01-01 21:38:38,735 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:38,739 : INFO : < 200 OK [1386]
2018-01-01 21:38:38,743 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ameya Sathe'}}
2018-01-01 21:38:38,743 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:38,747 : INFO : < 200 OK [1386]
2018-01-01 21:38:38,747 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Loren Terveen'}}
2018-01-01 21:38:38,751 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:38,755 : INFO : < 200 OK [1388]
2018-01-01 21:38:38,759 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michel van der Wel'}}
2018-01-01 21:38:38,759 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:38,763 : INFO : < 200 OK [1393]
2018-01-01 21:38:38,767 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Randy Hlavac'}}
2018-01-01 21:38:38,771 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,775 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,779 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kim Branner'}}
2018-01-01 21:38:38,779 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:38,783 : INFO : < 200 OK [1386]
2018-01-01 21:38:38,787 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jahangir Karimi'}}
2018-01-01 21:38:38,787 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:38,791 : INFO : < 200 OK [1390]
2018-01-01 21:38:38,795 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Xiaobo Zhou'}}
2018-01-01 21:38:38,795 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:38,799 : INFO : < 200 OK [1386]
2018-01-01 21:38:38,803 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Emiel van Loon'}}
2018-01-01 21:38:38,803 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,807 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,811 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'V. G. Vinod Vydiswaran'}}
2018-01-01 21:38:38,811 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:38,815 : INFO : < 200 OK [1397]
2018-01-01 21:38:38,820 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Norberto Leite'}}
2018-01-01 21:38:38,821 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,826 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,828 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Rahul Rai'}}
2018-01-01 21:38:38,830 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:38,834 : INFO : < 200 OK [1384]
2018-01-01 21:38:38,835 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Stephany Duda, PhD'}}
2018-01-01 21:38:38,835 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:38,839 : INFO : < 200 OK [1393]
2018-01-01 21:38:38,843 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anther Kiley'}}
2018-01-01 21:38:38,843 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,847 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,851 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Lisa Dierker'}}
2018-01-01 21:38:38,851 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:38,855 : INFO : < 200 OK [1387]
2018-01-01 21:38:38,859 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Manuel Laguna'}}
2018-01-01 21:38:38,863 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:38,867 : INFO : < 200 OK [1388]
2018-01-01 21:38:38,871 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Tucker Balch'}}
2018-01-01 21:38:38,875 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:38,879 : INFO : < 200 OK [1391]
2018-01-01 21:38:38,879 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr.  Sarah Eichhorn'}}
2018-01-01 21:38:38,883 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:38,887 : INFO : < 200 OK [1394]
2018-01-01 21:38:38,887 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Joe Warren'}}
2018-01-01 21:38:38,891 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:38,895 : INFO : < 200 OK [1385]
2018-01-01 21:38:38,899 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jong-Moon Chung'}}
2018-01-01 21:38:38,899 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:38,903 : INFO : < 200 OK [1390]
2018-01-01 21:38:38,907 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jeffrey R. Chasnov'}}
2018-01-01 21:38:38,907 : INFO : > POST http://localhost:7474/db/data/cypher [93]

2018-01-01 21:38:38,911 : INFO : < 200 OK [1393]
2018-01-01 21:38:38,915 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Google Cloud Training'}}
2018-01-01 21:38:38,915 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:38,921 : INFO : < 200 OK [1396]
2018-01-01 21:38:38,923 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John Muschelli III '}}
2018-01-01 21:38:38,924 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:38,929 : INFO : < 200 OK [1394]
2018-01-01 21:38:38,932 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Joseph A Konstan'}}
2018-01-01 21:38:38,933 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2018-01-01 21:38:38,935 : INFO : < 200 OK [1391]
2018-01-01 21:38:38,935 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Martin Odersky'}}
2018-01-01 21:38:38,939 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,943 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,943 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Gregory Wiles, PhD'}}
2018-01-01 21:38:38,947 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:38,951 : INFO : < 200 OK [1393]
2018-01-01 21:38:38,951 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tim McKay'}}
2018-01-01 21:38:38,955 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2018-01-01 21:38:38,959 : INFO : < 200 OK [1384]
2018-01-01 21:38:38,959 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert  Clark'}}
2018-01-01 21:38:38,963 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:38,967 : INFO : < 200 OK [1388]
2018-01-01 21:38:38,967 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Francine Gresnigt'}}
2018-01-01 21:38:38,971 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:38,975 : INFO : < 200 OK [1392]
2018-01-01 21:38:38,975 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ciprian M. Crainiceanu'}}
2018-01-01 21:38:38,979 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:38,983 : INFO : < 200 OK [1397]
2018-01-01 21:38:38,983 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'ZHANG Li'}}
2018-01-01 21:38:38,983 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2018-01-01 21:38:38,987 : INFO : < 200 OK [1383]
2018-01-01 21:38:38,991 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jonathan  Katz'}}
2018-01-01 21:38:38,991 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:38,995 : INFO : < 200 OK [1389]
2018-01-01 21:38:38,999 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mai Nguyen'}}
2018-01-01 21:38:38,999 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:39,003 : INFO : < 200 OK [1385]
2018-01-01 21:38:39,007 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Víctor Manuel de la Cueva Hernández'}}
2018-01-01 21:38:39,007 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2018-01-01 21:38:39,011 : INFO : < 200 OK [1416]
2018-01-01 21:38:39,015 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Yang-Hann Kim'}}
2018-01-01 21:38:39,015 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:39,019 : INFO : < 200 OK [1388]
2018-01-01 21:38:39,024 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Prof Julius O Smith, III'}}
2018-01-01 21:38:39,026 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2018-01-01 21:38:39,031 : INFO : < 200 OK [1399]
2018-01-01 21:38:39,035 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kalman Hazins'}}
2018-01-01 21:38:39,035 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:39,039 : INFO : < 200 OK [1388]
2018-01-01 21:38:39,043 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Manel Martínez-Ramón'}}
2018-01-01 21:38:39,043 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2018-01-01 21:38:39,047 : INFO : < 200 OK [1397]
2018-01-01 21:38:39,051 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Marius Preda'}}
2018-01-01 21:38:39,051 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:39,055 : INFO : < 200 OK [1387]
2018-01-01 21:38:39,059 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Eric Bradlow'}}
2018-01-01 21:38:39,059 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:39,063 : INFO : < 200 OK [1387]
2018-01-01 21:38:39,067 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daydream Impact Training'}}
2018-01-01 21:38:39,067 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2018-01-01 21:38:39,071 : INFO : < 200 OK [1399]
2018-01-01 21:38:39,075 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kasper Daniel Hansen, PhD'}}
2018-01-01 21:38:39,075 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:39,079 : INFO : < 200 OK [1400]
2018-01-01 21:38:39,083 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dominik Scheder'}}
2018-01-01 21:38:39,083 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:39,087 : INFO : < 200 OK [1390]
2018-01-01 21:38:39,091 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jacob O. Wobbrock'}}
2018-01-01 21:38:39,091 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:39,095 : INFO : < 200 OK [1392]
2018-01-01 21:38:39,099 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Govind Acharya'}}
2018-01-01 21:38:39,099 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:39,103 : INFO : < 200 OK [1389]
2018-01-01 21:38:39,107 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Magnus Egerstedt'}}
2018-01-01 21:38:39,107 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:39,111 : INFO : < 200 OK [1395]
2018-01-01 21:38:39,115 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jennifer Campbell'}}
2018-01-01 21:38:39,115 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:39,121 : INFO : < 200 OK [1392]
2018-01-01 21:38:39,123 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Archer'}}
2018-01-01 21:38:39,126 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:39,130 : INFO : < 200 OK [1387]
2018-01-01 21:38:39,132 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Wil van der Aalst'}}
2018-01-01 21:38:39,134 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:39,135 : INFO : < 200 OK [1392]
2018-01-01 21:38:39,139 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Don Huesman'}}
2018-01-01 21:38:39,139 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2018-01-01 21:38:39,143 : INFO : < 200 OK [1386]
2018-01-01 21:38:39,143 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Laurent Franck'}}
2018-01-01 21:38:39,147 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:39,151 : INFO : < 200 OK [1389]
2018-01-01 21:38:39,155 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kwang-Soon Kim'}}
2018-01-01 21:38:39,155 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:39,163 : INFO : < 200 OK [1389]
2018-01-01 21:38:39,167 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Professor Keith M. Martin'}}
2018-01-01 21:38:39,167 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:39,171 : INFO : < 200 OK [1400]
2018-01-01 21:38:39,175 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christine Alvarado'}}
2018-01-01 21:38:39,175 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:39,179 : INFO : < 200 OK [1393]

2018-01-01 21:38:39,183 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dennis Fok'}}
2018-01-01 21:38:39,183 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:39,191 : INFO : < 200 OK [1385]
2018-01-01 21:38:39,191 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Worthington'}}
2018-01-01 21:38:39,195 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:38:39,199 : INFO : < 200 OK [1394]
2018-01-01 21:38:39,203 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Tim "Dr. T" Chamillard'}}
2018-01-01 21:38:39,203 : INFO : > POST http://localhost:7474/db/data/cypher [103]
2018-01-01 21:38:39,207 : INFO : < 200 OK [1403]
2018-01-01 21:38:39,211 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Prof. Kelleann Foster'}}
2018-01-01 21:38:39,211 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:39,215 : INFO : < 200 OK [1396]
2018-01-01 21:38:39,222 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'William Bahn'}}
2018-01-01 21:38:39,223 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:39,228 : INFO : < 200 OK [1387]
2018-01-01 21:38:39,231 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Paolo Prandoni'}}
2018-01-01 21:38:39,232 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:39,235 : INFO : < 200 OK [1389]
2018-01-01 21:38:39,235 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Morten Hartvig Hansen'}}
2018-01-01 21:38:39,239 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:39,243 : INFO : < 200 OK [1396]
2018-01-01 21:38:39,247 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': "Casey O'Donnell"}}
2018-01-01 21:38:39,247 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:39,251 : INFO : < 200 OK [1390]
2018-01-01 21:38:39,255 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anne Remke'}}
2018-01-01 21:38:39,255 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:39,259 : INFO : < 200 OK [1385]
2018-01-01 21:38:39,263 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christopher D. Ittner'}}
2018-01-01 21:38:39,263 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:39,267 : INFO : < 200 OK [1396]
2018-01-01 21:38:39,267 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dmitry Altukhov'}}
2018-01-01 21:38:39,271 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:39,275 : INFO : < 200 OK [1390]
2018-01-01 21:38:39,275 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Frank Gielen'}}
2018-01-01 21:38:39,279 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2018-01-01 21:38:39,283 : INFO : < 200 OK [1387]
2018-01-01 21:38:39,287 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel Romero'}}
2018-01-01 21:38:39,287 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2018-01-01 21:38:39,291 : INFO : < 200 OK [1388]
2018-01-01 21:38:39,291 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Inez Zwetsloot'}}
2018-01-01 21:38:39,295 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:39,299 : INFO : < 200 OK [1389]
2018-01-01 21:38:39,299 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniil Polykovskiy'}}
2018-01-01 21:38:39,299 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:39,307 : INFO : < 200 OK [1393]
2018-01-01 21:38:39,307 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Karl Schmedders'}}
2018-01-01 21:38:39,311 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:39,315 : INFO : < 200 OK [1390]
2018-01-01 21:38:39,315 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nicola Osborne'}}
2018-01-01 21:38:39,320 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:39,326 : INFO : < 200 OK [1389]
2018-01-01 21:38:39,328 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexander S. Kulikov'}}
2018-01-01 21:38:39,330 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:38:39,335 : INFO : < 200 OK [1395]
2018-01-01 21:38:39,339 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Juan Antonio Martínez'}}
2018-01-01 21:38:39,339 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2018-01-01 21:38:39,343 : INFO : < 200 OK [1397]
2018-01-01 21:38:39,343 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Joyelle Harris'}}
2018-01-01 21:38:39,347 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:38:39,351 : INFO : < 200 OK [1393]
2018-01-01 21:38:39,355 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christiaan Heij'}}
2018-01-01 21:38:39,355 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:39,359 : INFO : < 200 OK [1390]
2018-01-01 21:38:39,363 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nathalie Thomas'}}
2018-01-01 21:38:39,363 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:39,367 : INFO : < 200 OK [1390]
2018-01-01 21:38:39,371 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Mary Ann Weitnauer'}}
2018-01-01 21:38:39,371 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:38:39,375 : INFO : < 200 OK [1396]
2018-01-01 21:38:39,379 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Fataneh Taghaboni-Dutta'}}
2018-01-01 21:38:39,379 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:39,383 : INFO : < 200 OK [1398]
2018-01-01 21:38:39,387 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Aggelos K. Katsaggelos'}}
2018-01-01 21:38:39,387 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:39,391 : INFO : < 200 OK [1397]
2018-01-01 21:38:39,395 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anna Potapenko'}}
2018-01-01 21:38:39,399 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:39,403 : INFO : < 200 OK [1389]
2018-01-01 21:38:39,407 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Walker'}}
2018-01-01 21:38:39,411 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2018-01-01 21:38:39,415 : INFO : < 200 OK [1389]
2018-01-01 21:38:39,415 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevyn Collins-Thompson'}}
2018-01-01 21:38:39,421 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:38:39,426 : INFO : < 200 OK [1397]
2018-01-01 21:38:39,428 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Joaquín Saiz Alcaine'}}
2018-01-01 21:38:39,431 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:38:39,435 : INFO : < 200 OK [1396]
2018-01-01 21:38:39,435 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Shambhu Upadhyaya'}}
2018-01-01 21:38:39,439 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2018-01-01 21:38:39,443 : INFO : < 200 OK [1392]
2018-01-01 21:38:39,443 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jianbo Shi'}}
2018-01-01 21:38:39,447 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2018-01-01 21:38:39,451 : INFO : < 200 OK [1385]
2018-01-01 21:38:39,451 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Brooke Anderson'}}
2018-01-01 21:38:39,455 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2018-01-01 21:38:39,459 : INFO : < 200 OK [1390]
2018-01-01 21:38:39,459 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Justin-Nicholas Toyama '}}
2018-01-01 21:38:39,463 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2018-01-01 21:38:39,467 : INFO : < 200 OK [1398]

In [59]:
## add offer relation
for i, row in data.drop_duplicates(subset=['created_by', 'uid']).iterrows():
    x = teach_dict[row.teach_by]
    y = course_dict[row.uid]
    graph.create(Relationship(x, "offer", y))

2018-01-01 21:38:39,640 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1047, '_0n1': 1228}
2018-01-01 21:38:39,640 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,657 : INFO : < 200 OK [3305]
2018-01-01 21:38:39,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 751, '_0n1': 1246}
2018-01-01 21:38:39,661 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,665 : INFO : < 200 OK [3260]
2018-01-01 21:38:39,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 1229}
2018-01-01 21:38:39,669 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,673 : INFO : < 200 OK [3361]
2018-01-01 21:38:39,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 1247}
2018-01-01 21:38:39,677 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,681 : INFO : < 200 OK [3334]
2018-01-01 21:38:39,685 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 869, '_0n1': 1230}
2018-01-01 21:38:39,685 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,689 : INFO : < 200 OK [3266]
2018-01-01 21:38:39,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 726, '_0n1': 1248}
2018-01-01 21:38:39,693 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,697 : INFO : < 200 OK [3320]
2018-01-01 21:38:39,701 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 901, '_0n1': 1231}
2018-01-01 21:38:39,701 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,705 : INFO : < 200 OK [3314]
2018-01-01 21:38:39,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 931, '_0n1': 1249}
2018-01-01 21:38:39,709 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,713 : INFO : < 200 OK [3314]
2018-01-01 21:38:39,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1118, '_0n1': 1232}
2018-01-01 21:38:39,717 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,724 : INFO : < 200 OK [3318]
2018-01-01 21:38:39,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 1250}
2018-01-01 21:38:39,730 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,735 : INFO : < 200 OK [3348]
2018-01-01 21:38:39,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 990, '_0n1': 1233}
2018-01-01 21:38:39,740 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,744 : INFO : < 200 OK [3267]
2018-01-01 21:38:39,748 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 1251}
2018-01-01 21:38:39,748 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,756 : INFO : < 200 OK [3351]
2018-01-01 21:38:39,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 974, '_0n1': 1234}
2018-01-01 21:38:39,760 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,764 : INFO : < 200 OK [3276]
2018-01-01 21:38:39,764 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 930, '_0n1': 1252}
2018-01-01 21:38:39,768 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,772 : INFO : < 200 OK [3338]
2018-01-01 21:38:39,772 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1173, '_0n1': 1252}
2018-01-01 21:38:39,776 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,780 : INFO : < 200 OK [3351]
2018-01-01 21:38:39,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 795, '_0n1': 1252}
2018-01-01 21:38:39,784 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,788 : INFO : < 200 OK [3331]
2018-01-01 21:38:39,788 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 1235}
2018-01-01 21:38:39,792 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,796 : INFO : < 200 OK [3358]
2018-01-01 21:38:39,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 726, '_0n1': 1253}
2018-01-01 21:38:39,800 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,804 : INFO : < 200 OK [3315]
2018-01-01 21:38:39,804 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 1236}
2018-01-01 21:38:39,808 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,812 : INFO : < 200 OK [3359]
2018-01-01 21:38:39,812 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1112, '_0n1': 1254}
2018-01-01 21:38:39,816 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,822 : INFO : < 200 OK [3332]
2018-01-01 21:38:39,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 748, '_0n1': 1237}
2018-01-01 21:38:39,828 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,833 : INFO : < 200 OK [3319]
2018-01-01 21:38:39,836 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 826, '_0n1': 1255}
2018-01-01 21:38:39,840 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,844 : INFO : < 200 OK [3355]
2018-01-01 21:38:39,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 805, '_0n1': 1255}
2018-01-01 21:38:39,848 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,852 : INFO : < 200 OK [3352]
2018-01-01 21:38:39,852 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1031, '_0n1': 1238}
2018-01-01 21:38:39,856 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,860 : INFO : < 200 OK [3271]
2018-01-01 21:38:39,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 748, '_0n1': 1256}

2018-01-01 21:38:39,864 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,868 : INFO : < 200 OK [3321]
2018-01-01 21:38:39,872 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 1239}
2018-01-01 21:38:39,872 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:38:39,876 : INFO : < 200 OK [3370]
2018-01-01 21:38:39,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 974, '_0n1': 1259}
2018-01-01 21:38:39,880 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,884 : INFO : < 200 OK [3324]
2018-01-01 21:38:39,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 726, '_0n1': 1240}
2018-01-01 21:38:39,888 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,892 : INFO : < 200 OK [3303]
2018-01-01 21:38:39,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 830, '_0n1': 1260}
2018-01-01 21:38:39,900 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,904 : INFO : < 200 OK [3280]
2018-01-01 21:38:39,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 0}
2018-01-01 21:38:39,908 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:38:39,912 : INFO : < 200 OK [3250]
2018-01-01 21:38:39,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 726, '_0n1': 1301}
2018-01-01 21:38:39,916 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,923 : INFO : < 200 OK [3313]
2018-01-01 21:38:39,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1144, '_0n1': 1}
2018-01-01 21:38:39,927 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:39,930 : INFO : < 200 OK [3232]
2018-01-01 21:38:39,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 726, '_0n1': 1302}
2018-01-01 21:38:39,936 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:39,940 : INFO : < 200 OK [3321]
2018-01-01 21:38:39,948 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 805, '_0n1': 2}
2018-01-01 21:38:39,948 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:38:39,956 : INFO : < 200 OK [3279]
2018-01-01 21:38:39,960 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 826, '_0n1': 2}
2018-01-01 21:38:39,960 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:38:39,964 : INFO : < 200 OK [3282]
2018-01-01 21:38:39,968 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1022, '_0n1': 20}
2018-01-01 21:38:39,968 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:39,976 : INFO : < 200 OK [3305]
2018-01-01 21:38:39,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1118, '_0n1': 3}
2018-01-01 21:38:39,980 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:39,984 : INFO : < 200 OK [3275]
2018-01-01 21:38:39,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 21}
2018-01-01 21:38:39,988 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:39,992 : INFO : < 200 OK [3321]
2018-01-01 21:38:39,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 748, '_0n1': 4}
2018-01-01 21:38:40,000 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:38:40,004 : INFO : < 200 OK [3276]
2018-01-01 21:38:40,004 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 829, '_0n1': 22}
2018-01-01 21:38:40,008 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,012 : INFO : < 200 OK [3241]
2018-01-01 21:38:40,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 897, '_0n1': 22}
2018-01-01 21:38:40,016 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,021 : INFO : < 200 OK [3234]
2018-01-01 21:38:40,024 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 5}
2018-01-01 21:38:40,025 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,029 : INFO : < 200 OK [3310]
2018-01-01 21:38:40,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1176, '_0n1': 6}
2018-01-01 21:38:40,035 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,040 : INFO : < 200 OK [3289]
2018-01-01 21:38:40,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 941, '_0n1': 6}
2018-01-01 21:38:40,044 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:38:40,048 : INFO : < 200 OK [3275]
2018-01-01 21:38:40,048 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1022, '_0n1': 6}
2018-01-01 21:38:40,052 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,056 : INFO : < 200 OK [3292]
2018-01-01 21:38:40,056 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 866, '_0n1': 23}
2018-01-01 21:38:40,060 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,064 : INFO : < 200 OK [3230]
2018-01-01 21:38:40,064 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 748, '_0n1': 24}
2018-01-01 21:38:40,068 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,072 : INFO : < 200 OK [3281]
2018-01-01 21:38:40,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1118, '_0n1': 7}
2018-01-01 21:38:40,076 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,080 : INFO : < 200 OK [3266]
2018-01-01 21:38:40,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1112, '_0n1': 25}
2018-01-01 21:38:40,084 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,088 : INFO : < 200 OK [3258]
2018-01-01 21:38:40,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1056, '_0n1': 8}

2018-01-01 21:38:40,092 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,100 : INFO : < 200 OK [3286]
2018-01-01 21:38:40,104 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 844, '_0n1': 8}
2018-01-01 21:38:40,104 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:38:40,108 : INFO : < 200 OK [3267]
2018-01-01 21:38:40,112 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 931, '_0n1': 26}
2018-01-01 21:38:40,116 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,122 : INFO : < 200 OK [3288]
2018-01-01 21:38:40,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 809, '_0n1': 9}
2018-01-01 21:38:40,126 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:38:40,130 : INFO : < 200 OK [3231]
2018-01-01 21:38:40,133 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1070, '_0n1': 9}
2018-01-01 21:38:40,135 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,136 : INFO : < 200 OK [3249]
2018-01-01 21:38:40,140 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 974, '_0n1': 27}
2018-01-01 21:38:40,140 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,148 : INFO : < 200 OK [3276]
2018-01-01 21:38:40,152 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1176, '_0n1': 10}
2018-01-01 21:38:40,152 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,156 : INFO : < 200 OK [3304]
2018-01-01 21:38:40,160 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 941, '_0n1': 10}
2018-01-01 21:38:40,160 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,164 : INFO : < 200 OK [3290]
2018-01-01 21:38:40,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1022, '_0n1': 10}
2018-01-01 21:38:40,172 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,176 : INFO : < 200 OK [3307]
2018-01-01 21:38:40,176 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 748, '_0n1': 28}
2018-01-01 21:38:40,180 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,184 : INFO : < 200 OK [3262]
2018-01-01 21:38:40,188 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 901, '_0n1': 11}
2018-01-01 21:38:40,188 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,192 : INFO : < 200 OK [3296]
2018-01-01 21:38:40,196 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 914, '_0n1': 11}
2018-01-01 21:38:40,196 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,200 : INFO : < 200 OK [3294]
2018-01-01 21:38:40,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1049, '_0n1': 11}
2018-01-01 21:38:40,204 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,208 : INFO : < 200 OK [3308]
2018-01-01 21:38:40,212 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 871, '_0n1': 11}
2018-01-01 21:38:40,212 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,216 : INFO : < 200 OK [3322]
2018-01-01 21:38:40,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 756, '_0n1': 11}
2018-01-01 21:38:40,222 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,226 : INFO : < 200 OK [3314]
2018-01-01 21:38:40,230 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 931, '_0n1': 29}
2018-01-01 21:38:40,231 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,236 : INFO : < 200 OK [3282]
2018-01-01 21:38:40,236 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 931, '_0n1': 12}
2018-01-01 21:38:40,240 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,244 : INFO : < 200 OK [3298]
2018-01-01 21:38:40,248 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 748, '_0n1': 30}
2018-01-01 21:38:40,248 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,252 : INFO : < 200 OK [3299]
2018-01-01 21:38:40,256 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 780, '_0n1': 13}
2018-01-01 21:38:40,256 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,260 : INFO : < 200 OK [3269]
2018-01-01 21:38:40,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 740, '_0n1': 13}
2018-01-01 21:38:40,264 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,268 : INFO : < 200 OK [3270]
2018-01-01 21:38:40,272 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 31}
2018-01-01 21:38:40,272 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,280 : INFO : < 200 OK [3332]
2018-01-01 21:38:40,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1056, '_0n1': 14}
2018-01-01 21:38:40,284 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,292 : INFO : < 200 OK [3313]
2018-01-01 21:38:40,296 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1112, '_0n1': 32}
2018-01-01 21:38:40,296 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,304 : INFO : < 200 OK [3253]
2018-01-01 21:38:40,308 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 904, '_0n1': 15}
2018-01-01 21:38:40,308 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,312 : INFO : < 200 OK [3252]
2018-01-01 21:38:40,316 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1040, '_0n1': 15}
2018-01-01 21:38:40,316 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,324 : INFO : < 200 OK [3275]
2018-01-01 21:38:40,328 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1022, '_0n1': 33}

2018-01-01 21:38:40,329 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,333 : INFO : < 200 OK [3267]
2018-01-01 21:38:40,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 974, '_0n1': 16}
2018-01-01 21:38:40,336 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,340 : INFO : < 200 OK [3296]
2018-01-01 21:38:40,344 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1112, '_0n1': 34}
2018-01-01 21:38:40,344 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,348 : INFO : < 200 OK [3280]
2018-01-01 21:38:40,352 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1140, '_0n1': 17}
2018-01-01 21:38:40,352 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,360 : INFO : < 200 OK [3319]
2018-01-01 21:38:40,360 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 734, '_0n1': 17}
2018-01-01 21:38:40,364 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,368 : INFO : < 200 OK [3306]
2018-01-01 21:38:40,372 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1022, '_0n1': 35}
2018-01-01 21:38:40,372 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,376 : INFO : < 200 OK [3287]
2018-01-01 21:38:40,380 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 937, '_0n1': 18}
2018-01-01 21:38:40,384 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,388 : INFO : < 200 OK [3300]
2018-01-01 21:38:40,388 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1016, '_0n1': 18}
2018-01-01 21:38:40,392 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,396 : INFO : < 200 OK [3322]
2018-01-01 21:38:40,400 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 748, '_0n1': 36}
2018-01-01 21:38:40,400 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,404 : INFO : < 200 OK [3276]
2018-01-01 21:38:40,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1118, '_0n1': 19}
2018-01-01 21:38:40,408 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,412 : INFO : < 200 OK [3266]
2018-01-01 21:38:40,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1022, '_0n1': 37}
2018-01-01 21:38:40,416 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,422 : INFO : < 200 OK [3288]
2018-01-01 21:38:40,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 901, '_0n1': 40}
2018-01-01 21:38:40,428 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,432 : INFO : < 200 OK [3278]
2018-01-01 21:38:40,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1040, '_0n1': 38}
2018-01-01 21:38:40,436 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,440 : INFO : < 200 OK [3318]
2018-01-01 21:38:40,440 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 904, '_0n1': 38}
2018-01-01 21:38:40,444 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,448 : INFO : < 200 OK [3295]
2018-01-01 21:38:40,452 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 748, '_0n1': 41}
2018-01-01 21:38:40,452 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,460 : INFO : < 200 OK [3281]
2018-01-01 21:38:40,464 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 941, '_0n1': 39}
2018-01-01 21:38:40,468 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,472 : INFO : < 200 OK [3324]
2018-01-01 21:38:40,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 736, '_0n1': 42}
2018-01-01 21:38:40,476 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,480 : INFO : < 200 OK [3249]
2018-01-01 21:38:40,484 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1102, '_0n1': 60}
2018-01-01 21:38:40,484 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,488 : INFO : < 200 OK [3340]
2018-01-01 21:38:40,492 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 941, '_0n1': 43}
2018-01-01 21:38:40,496 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,500 : INFO : < 200 OK [3310]
2018-01-01 21:38:40,504 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 845, '_0n1': 61}
2018-01-01 21:38:40,504 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,508 : INFO : < 200 OK [3263]
2018-01-01 21:38:40,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1051, '_0n1': 61}
2018-01-01 21:38:40,512 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,516 : INFO : < 200 OK [3276]
2018-01-01 21:38:40,520 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 941, '_0n1': 44}
2018-01-01 21:38:40,520 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,527 : INFO : < 200 OK [3290]
2018-01-01 21:38:40,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 901, '_0n1': 62}
2018-01-01 21:38:40,532 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,535 : INFO : < 200 OK [3282]
2018-01-01 21:38:40,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 914, '_0n1': 62}
2018-01-01 21:38:40,540 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,544 : INFO : < 200 OK [3280]
2018-01-01 21:38:40,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 871, '_0n1': 62}
2018-01-01 21:38:40,548 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,552 : INFO : < 200 OK [3308]
2018-01-01 21:38:40,556 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1049, '_0n1': 62}

2018-01-01 21:38:40,556 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,564 : INFO : < 200 OK [3294]
2018-01-01 21:38:40,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 756, '_0n1': 62}
2018-01-01 21:38:40,568 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,572 : INFO : < 200 OK [3300]
2018-01-01 21:38:40,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1118, '_0n1': 45}
2018-01-01 21:38:40,580 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,584 : INFO : < 200 OK [3268]
2018-01-01 21:38:40,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 941, '_0n1': 63}
2018-01-01 21:38:40,588 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,596 : INFO : < 200 OK [3310]
2018-01-01 21:38:40,596 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 46}
2018-01-01 21:38:40,600 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,604 : INFO : < 200 OK [3336]
2018-01-01 21:38:40,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 984, '_0n1': 64}
2018-01-01 21:38:40,608 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,616 : INFO : < 200 OK [3243]
2018-01-01 21:38:40,620 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 826, '_0n1': 64}
2018-01-01 21:38:40,622 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,626 : INFO : < 200 OK [3244]
2018-01-01 21:38:40,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 829, '_0n1': 64}
2018-01-01 21:38:40,631 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,635 : INFO : < 200 OK [3248]
2018-01-01 21:38:40,637 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 897, '_0n1': 64}
2018-01-01 21:38:40,637 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,641 : INFO : < 200 OK [3241]
2018-01-01 21:38:40,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 901, '_0n1': 47}
2018-01-01 21:38:40,645 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,649 : INFO : < 200 OK [3291]
2018-01-01 21:38:40,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 914, '_0n1': 47}
2018-01-01 21:38:40,653 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,661 : INFO : < 200 OK [3289]
2018-01-01 21:38:40,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 871, '_0n1': 47}
2018-01-01 21:38:40,665 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,669 : INFO : < 200 OK [3317]
2018-01-01 21:38:40,673 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1049, '_0n1': 47}
2018-01-01 21:38:40,673 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,677 : INFO : < 200 OK [3303]
2018-01-01 21:38:40,681 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 756, '_0n1': 47}
2018-01-01 21:38:40,681 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,689 : INFO : < 200 OK [3309]
2018-01-01 21:38:40,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 869, '_0n1': 65}
2018-01-01 21:38:40,693 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,701 : INFO : < 200 OK [3285]
2018-01-01 21:38:40,705 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 48}
2018-01-01 21:38:40,705 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,709 : INFO : < 200 OK [3272]
2018-01-01 21:38:40,713 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1081, '_0n1': 48}
2018-01-01 21:38:40,713 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,721 : INFO : < 200 OK [3291]
2018-01-01 21:38:40,724 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 782, '_0n1': 66}
2018-01-01 21:38:40,726 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,730 : INFO : < 200 OK [3282]
2018-01-01 21:38:40,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 737, '_0n1': 66}
2018-01-01 21:38:40,736 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,737 : INFO : < 200 OK [3316]
2018-01-01 21:38:40,741 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1048, '_0n1': 66}
2018-01-01 21:38:40,745 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,749 : INFO : < 200 OK [3331]
2018-01-01 21:38:40,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 782, '_0n1': 49}
2018-01-01 21:38:40,753 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,757 : INFO : < 200 OK [3278]
2018-01-01 21:38:40,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 737, '_0n1': 49}
2018-01-01 21:38:40,761 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,765 : INFO : < 200 OK [3312]
2018-01-01 21:38:40,765 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1048, '_0n1': 49}
2018-01-01 21:38:40,769 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,773 : INFO : < 200 OK [3327]
2018-01-01 21:38:40,777 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 782, '_0n1': 67}
2018-01-01 21:38:40,777 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,781 : INFO : < 200 OK [3331]
2018-01-01 21:38:40,785 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 737, '_0n1': 67}
2018-01-01 21:38:40,785 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,789 : INFO : < 200 OK [3365]
2018-01-01 21:38:40,793 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1048, '_0n1': 67}

2018-01-01 21:38:40,797 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,801 : INFO : < 200 OK [3380]
2018-01-01 21:38:40,805 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 757, '_0n1': 50}
2018-01-01 21:38:40,805 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,813 : INFO : < 200 OK [3269]
2018-01-01 21:38:40,813 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1062, '_0n1': 50}
2018-01-01 21:38:40,817 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,822 : INFO : < 200 OK [3289]
2018-01-01 21:38:40,827 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 68}
2018-01-01 21:38:40,829 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,834 : INFO : < 200 OK [3294]
2018-01-01 21:38:40,836 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 998, '_0n1': 68}
2018-01-01 21:38:40,836 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,841 : INFO : < 200 OK [3272]
2018-01-01 21:38:40,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 950, '_0n1': 68}
2018-01-01 21:38:40,849 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,853 : INFO : < 200 OK [3270]
2018-01-01 21:38:40,857 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 68}
2018-01-01 21:38:40,857 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,865 : INFO : < 200 OK [3288]
2018-01-01 21:38:40,865 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 778, '_0n1': 68}
2018-01-01 21:38:40,869 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,873 : INFO : < 200 OK [3272]
2018-01-01 21:38:40,873 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 782, '_0n1': 51}
2018-01-01 21:38:40,877 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,881 : INFO : < 200 OK [3239]
2018-01-01 21:38:40,885 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 737, '_0n1': 51}
2018-01-01 21:38:40,885 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,889 : INFO : < 200 OK [3273]
2018-01-01 21:38:40,893 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1048, '_0n1': 51}
2018-01-01 21:38:40,893 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,897 : INFO : < 200 OK [3288]
2018-01-01 21:38:40,897 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 953, '_0n1': 69}
2018-01-01 21:38:40,901 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,905 : INFO : < 200 OK [3323]
2018-01-01 21:38:40,905 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 822, '_0n1': 52}
2018-01-01 21:38:40,909 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,913 : INFO : < 200 OK [3280]
2018-01-01 21:38:40,917 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 978, '_0n1': 52}
2018-01-01 21:38:40,917 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,922 : INFO : < 200 OK [3280]
2018-01-01 21:38:40,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 52}
2018-01-01 21:38:40,927 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,932 : INFO : < 200 OK [3280]
2018-01-01 21:38:40,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 52}
2018-01-01 21:38:40,937 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,941 : INFO : < 200 OK [3293]
2018-01-01 21:38:40,941 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1062, '_0n1': 70}
2018-01-01 21:38:40,949 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,953 : INFO : < 200 OK [3290]
2018-01-01 21:38:40,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 757, '_0n1': 70}
2018-01-01 21:38:40,957 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,961 : INFO : < 200 OK [3270]
2018-01-01 21:38:40,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 53}
2018-01-01 21:38:40,969 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:40,973 : INFO : < 200 OK [3289]
2018-01-01 21:38:40,973 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 998, '_0n1': 53}
2018-01-01 21:38:40,977 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,981 : INFO : < 200 OK [3267]
2018-01-01 21:38:40,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 778, '_0n1': 53}
2018-01-01 21:38:40,985 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,989 : INFO : < 200 OK [3267]
2018-01-01 21:38:40,993 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 950, '_0n1': 53}
2018-01-01 21:38:40,993 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:40,997 : INFO : < 200 OK [3265]
2018-01-01 21:38:41,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 786, '_0n1': 71}
2018-01-01 21:38:41,001 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,009 : INFO : < 200 OK [3313]
2018-01-01 21:38:41,009 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 948, '_0n1': 71}
2018-01-01 21:38:41,013 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,017 : INFO : < 200 OK [3309]
2018-01-01 21:38:41,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1025, '_0n1': 54}
2018-01-01 21:38:41,023 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,028 : INFO : < 200 OK [3291]
2018-01-01 21:38:41,031 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 903, '_0n1': 54}

2018-01-01 21:38:41,033 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,036 : INFO : < 200 OK [3277]
2018-01-01 21:38:41,036 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 887, '_0n1': 54}
2018-01-01 21:38:41,040 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,044 : INFO : < 200 OK [3270]
2018-01-01 21:38:41,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 984, '_0n1': 72}
2018-01-01 21:38:41,048 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,056 : INFO : < 200 OK [3281]
2018-01-01 21:38:41,056 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1206, '_0n1': 55}
2018-01-01 21:38:41,060 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,068 : INFO : < 200 OK [3294]
2018-01-01 21:38:41,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1099, '_0n1': 73}
2018-01-01 21:38:41,072 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,076 : INFO : < 200 OK [3312]
2018-01-01 21:38:41,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 56}
2018-01-01 21:38:41,080 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,084 : INFO : < 200 OK [3287]
2018-01-01 21:38:41,088 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 998, '_0n1': 56}
2018-01-01 21:38:41,088 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,096 : INFO : < 200 OK [3265]
2018-01-01 21:38:41,096 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 902, '_0n1': 56}
2018-01-01 21:38:41,100 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,104 : INFO : < 200 OK [3270]
2018-01-01 21:38:41,104 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1135, '_0n1': 74}
2018-01-01 21:38:41,108 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,112 : INFO : < 200 OK [3268]
2018-01-01 21:38:41,116 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1072, '_0n1': 57}
2018-01-01 21:38:41,116 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,120 : INFO : < 200 OK [3278]
2018-01-01 21:38:41,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 833, '_0n1': 75}
2018-01-01 21:38:41,126 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,130 : INFO : < 200 OK [3306]
2018-01-01 21:38:41,132 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 909, '_0n1': 75}
2018-01-01 21:38:41,134 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,137 : INFO : < 200 OK [3302]
2018-01-01 21:38:41,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 953, '_0n1': 58}
2018-01-01 21:38:41,141 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,145 : INFO : < 200 OK [3304]
2018-01-01 21:38:41,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 76}
2018-01-01 21:38:41,149 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,153 : INFO : < 200 OK [3295]
2018-01-01 21:38:41,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 998, '_0n1': 76}
2018-01-01 21:38:41,157 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,165 : INFO : < 200 OK [3273]
2018-01-01 21:38:41,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 778, '_0n1': 76}
2018-01-01 21:38:41,169 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,173 : INFO : < 200 OK [3277]
2018-01-01 21:38:41,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 950, '_0n1': 76}
2018-01-01 21:38:41,181 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,185 : INFO : < 200 OK [3271]
2018-01-01 21:38:41,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1025, '_0n1': 59}
2018-01-01 21:38:41,189 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,193 : INFO : < 200 OK [3284]
2018-01-01 21:38:41,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 903, '_0n1': 59}
2018-01-01 21:38:41,197 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,201 : INFO : < 200 OK [3266]
2018-01-01 21:38:41,205 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 887, '_0n1': 59}
2018-01-01 21:38:41,205 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,213 : INFO : < 200 OK [3263]
2018-01-01 21:38:41,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 953, '_0n1': 77}
2018-01-01 21:38:41,217 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,221 : INFO : < 200 OK [3321]
2018-01-01 21:38:41,224 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1168, '_0n1': 81}
2018-01-01 21:38:41,226 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,230 : INFO : < 200 OK [3294]
2018-01-01 21:38:41,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 78}
2018-01-01 21:38:41,234 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,237 : INFO : < 200 OK [3314]
2018-01-01 21:38:41,241 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 827, '_0n1': 78}
2018-01-01 21:38:41,241 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,245 : INFO : < 200 OK [3304]
2018-01-01 21:38:41,249 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 812, '_0n1': 82}
2018-01-01 21:38:41,249 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,253 : INFO : < 200 OK [3296]
2018-01-01 21:38:41,257 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 744, '_0n1': 82}

2018-01-01 21:38:41,257 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,261 : INFO : < 200 OK [3285]
2018-01-01 21:38:41,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 80}
2018-01-01 21:38:41,265 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,269 : INFO : < 200 OK [3303]
2018-01-01 21:38:41,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 83}
2018-01-01 21:38:41,277 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,281 : INFO : < 200 OK [3304]
2018-01-01 21:38:41,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 902, '_0n1': 83}
2018-01-01 21:38:41,285 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,293 : INFO : < 200 OK [3287]
2018-01-01 21:38:41,293 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 938, '_0n1': 101}
2018-01-01 21:38:41,297 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,301 : INFO : < 200 OK [3300]
2018-01-01 21:38:41,305 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 101}
2018-01-01 21:38:41,305 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,309 : INFO : < 200 OK [3300]
2018-01-01 21:38:41,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 101}
2018-01-01 21:38:41,313 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,317 : INFO : < 200 OK [3313]
2018-01-01 21:38:41,322 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 820, '_0n1': 84}
2018-01-01 21:38:41,324 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,329 : INFO : < 200 OK [3278]
2018-01-01 21:38:41,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 102}
2018-01-01 21:38:41,333 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,336 : INFO : < 200 OK [3324]
2018-01-01 21:38:41,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 998, '_0n1': 102}
2018-01-01 21:38:41,340 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,344 : INFO : < 200 OK [3302]
2018-01-01 21:38:41,344 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 778, '_0n1': 102}
2018-01-01 21:38:41,348 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,352 : INFO : < 200 OK [3302]
2018-01-01 21:38:41,352 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 950, '_0n1': 102}
2018-01-01 21:38:41,356 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,360 : INFO : < 200 OK [3300]
2018-01-01 21:38:41,360 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1155, '_0n1': 85}
2018-01-01 21:38:41,364 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,368 : INFO : < 200 OK [3308]
2018-01-01 21:38:41,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1015, '_0n1': 85}
2018-01-01 21:38:41,372 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,376 : INFO : < 200 OK [3300]
2018-01-01 21:38:41,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1020, '_0n1': 85}
2018-01-01 21:38:41,380 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,384 : INFO : < 200 OK [3300]
2018-01-01 21:38:41,388 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 103}
2018-01-01 21:38:41,392 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,396 : INFO : < 200 OK [3315]
2018-01-01 21:38:41,400 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 998, '_0n1': 103}
2018-01-01 21:38:41,404 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,408 : INFO : < 200 OK [3293]
2018-01-01 21:38:41,408 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 103}
2018-01-01 21:38:41,412 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,416 : INFO : < 200 OK [3309]
2018-01-01 21:38:41,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 950, '_0n1': 103}
2018-01-01 21:38:41,420 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,426 : INFO : < 200 OK [3291]
2018-01-01 21:38:41,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 953, '_0n1': 86}
2018-01-01 21:38:41,433 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,437 : INFO : < 200 OK [3331]
2018-01-01 21:38:41,441 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 924, '_0n1': 104}
2018-01-01 21:38:41,441 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,445 : INFO : < 200 OK [3282]
2018-01-01 21:38:41,449 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 104}
2018-01-01 21:38:41,449 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,453 : INFO : < 200 OK [3276]
2018-01-01 21:38:41,457 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 796, '_0n1': 87}
2018-01-01 21:38:41,457 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,461 : INFO : < 200 OK [3287]
2018-01-01 21:38:41,465 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 105}
2018-01-01 21:38:41,465 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,469 : INFO : < 200 OK [3341]
2018-01-01 21:38:41,473 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 105}
2018-01-01 21:38:41,473 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,477 : INFO : < 200 OK [3328]
2018-01-01 21:38:41,481 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 822, '_0n1': 105}

2018-01-01 21:38:41,481 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,485 : INFO : < 200 OK [3328]
2018-01-01 21:38:41,489 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 978, '_0n1': 105}
2018-01-01 21:38:41,489 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,497 : INFO : < 200 OK [3328]
2018-01-01 21:38:41,497 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 927, '_0n1': 88}
2018-01-01 21:38:41,501 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,505 : INFO : < 200 OK [3267]
2018-01-01 21:38:41,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 745, '_0n1': 88}
2018-01-01 21:38:41,513 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,517 : INFO : < 200 OK [3266]
2018-01-01 21:38:41,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 106}
2018-01-01 21:38:41,525 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,530 : INFO : < 200 OK [3320]
2018-01-01 21:38:41,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 998, '_0n1': 106}
2018-01-01 21:38:41,535 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,537 : INFO : < 200 OK [3298]
2018-01-01 21:38:41,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 902, '_0n1': 106}
2018-01-01 21:38:41,541 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,545 : INFO : < 200 OK [3303]
2018-01-01 21:38:41,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1063, '_0n1': 89}
2018-01-01 21:38:41,553 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,557 : INFO : < 200 OK [3305]
2018-01-01 21:38:41,561 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1188, '_0n1': 107}
2018-01-01 21:38:41,561 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,565 : INFO : < 200 OK [3286]
2018-01-01 21:38:41,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 967, '_0n1': 107}
2018-01-01 21:38:41,569 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,573 : INFO : < 200 OK [3270]
2018-01-01 21:38:41,577 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1075, '_0n1': 107}
2018-01-01 21:38:41,577 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,581 : INFO : < 200 OK [3284]
2018-01-01 21:38:41,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 992, '_0n1': 107}
2018-01-01 21:38:41,589 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,593 : INFO : < 200 OK [3269]
2018-01-01 21:38:41,597 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 982, '_0n1': 107}
2018-01-01 21:38:41,597 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,601 : INFO : < 200 OK [3272]
2018-01-01 21:38:41,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1099, '_0n1': 90}
2018-01-01 21:38:41,605 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,613 : INFO : < 200 OK [3311]
2018-01-01 21:38:41,613 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1099, '_0n1': 108}
2018-01-01 21:38:41,617 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,623 : INFO : < 200 OK [3325]
2018-01-01 21:38:41,626 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 91}
2018-01-01 21:38:41,628 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,633 : INFO : < 200 OK [3288]
2018-01-01 21:38:41,637 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 91}
2018-01-01 21:38:41,637 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,645 : INFO : < 200 OK [3301]
2018-01-01 21:38:41,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 938, '_0n1': 91}
2018-01-01 21:38:41,653 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,665 : INFO : < 200 OK [3288]
2018-01-01 21:38:41,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1062, '_0n1': 109}
2018-01-01 21:38:41,673 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,677 : INFO : < 200 OK [3283]
2018-01-01 21:38:41,681 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1019, '_0n1': 92}
2018-01-01 21:38:41,685 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,689 : INFO : < 200 OK [3296]
2018-01-01 21:38:41,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1020, '_0n1': 110}
2018-01-01 21:38:41,697 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,701 : INFO : < 200 OK [3316]
2018-01-01 21:38:41,705 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1015, '_0n1': 110}
2018-01-01 21:38:41,709 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,717 : INFO : < 200 OK [3316]
2018-01-01 21:38:41,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1155, '_0n1': 110}
2018-01-01 21:38:41,722 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,728 : INFO : < 200 OK [3324]
2018-01-01 21:38:41,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 984, '_0n1': 93}
2018-01-01 21:38:41,734 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,741 : INFO : < 200 OK [3257]
2018-01-01 21:38:41,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 873, '_0n1': 111}
2018-01-01 21:38:41,747 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,751 : INFO : < 200 OK [3276]
2018-01-01 21:38:41,755 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 730, '_0n1': 111}

2018-01-01 21:38:41,758 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,764 : INFO : < 200 OK [3276]
2018-01-01 21:38:41,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 94}
2018-01-01 21:38:41,769 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,778 : INFO : < 200 OK [3291]
2018-01-01 21:38:41,782 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 759, '_0n1': 112}
2018-01-01 21:38:41,784 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,790 : INFO : < 200 OK [3272]
2018-01-01 21:38:41,795 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 773, '_0n1': 112}
2018-01-01 21:38:41,797 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,802 : INFO : < 200 OK [3266]
2018-01-01 21:38:41,807 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 938, '_0n1': 95}
2018-01-01 21:38:41,810 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,816 : INFO : < 200 OK [3285]
2018-01-01 21:38:41,819 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 95}
2018-01-01 21:38:41,822 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,828 : INFO : < 200 OK [3285]
2018-01-01 21:38:41,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 95}
2018-01-01 21:38:41,834 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,840 : INFO : < 200 OK [3298]
2018-01-01 21:38:41,843 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 883, '_0n1': 113}
2018-01-01 21:38:41,845 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,850 : INFO : < 200 OK [3319]
2018-01-01 21:38:41,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1017, '_0n1': 96}
2018-01-01 21:38:41,855 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,860 : INFO : < 200 OK [3271]
2018-01-01 21:38:41,863 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 114}
2018-01-01 21:38:41,864 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,869 : INFO : < 200 OK [3270]
2018-01-01 21:38:41,874 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 114}
2018-01-01 21:38:41,876 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,881 : INFO : < 200 OK [3283]
2018-01-01 21:38:41,885 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 938, '_0n1': 114}
2018-01-01 21:38:41,888 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,892 : INFO : < 200 OK [3270]
2018-01-01 21:38:41,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 883, '_0n1': 97}
2018-01-01 21:38:41,897 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,903 : INFO : < 200 OK [3292]
2018-01-01 21:38:41,907 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 115}
2018-01-01 21:38:41,909 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,914 : INFO : < 200 OK [3321]
2018-01-01 21:38:41,917 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 827, '_0n1': 115}
2018-01-01 21:38:41,919 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,923 : INFO : < 200 OK [3307]
2018-01-01 21:38:41,927 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 883, '_0n1': 98}
2018-01-01 21:38:41,929 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:38:41,934 : INFO : < 200 OK [3303]
2018-01-01 21:38:41,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 116}
2018-01-01 21:38:41,940 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,944 : INFO : < 200 OK [3338]
2018-01-01 21:38:41,947 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 827, '_0n1': 116}
2018-01-01 21:38:41,949 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,954 : INFO : < 200 OK [3324]
2018-01-01 21:38:41,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1019, '_0n1': 99}
2018-01-01 21:38:41,958 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,963 : INFO : < 200 OK [3298]
2018-01-01 21:38:41,966 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1071, '_0n1': 117}
2018-01-01 21:38:41,968 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,972 : INFO : < 200 OK [3326]
2018-01-01 21:38:41,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 946, '_0n1': 117}
2018-01-01 21:38:41,977 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,981 : INFO : < 200 OK [3309]
2018-01-01 21:38:41,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 100}
2018-01-01 21:38:41,985 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:41,989 : INFO : < 200 OK [3323]
2018-01-01 21:38:41,992 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 827, '_0n1': 100}
2018-01-01 21:38:41,994 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:41,998 : INFO : < 200 OK [3309]
2018-01-01 21:38:42,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 118}
2018-01-01 21:38:42,004 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,008 : INFO : < 200 OK [3343]
2018-01-01 21:38:42,011 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 827, '_0n1': 118}
2018-01-01 21:38:42,013 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,017 : INFO : < 200 OK [3329]
2018-01-01 21:38:42,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 794, '_0n1': 118}

2018-01-01 21:38:42,024 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,028 : INFO : < 200 OK [3328]
2018-01-01 21:38:42,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 121}
2018-01-01 21:38:42,032 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,037 : INFO : < 200 OK [3341]
2018-01-01 21:38:42,041 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 827, '_0n1': 121}
2018-01-01 21:38:42,043 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,048 : INFO : < 200 OK [3327]
2018-01-01 21:38:42,052 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1152, '_0n1': 119}
2018-01-01 21:38:42,055 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,059 : INFO : < 200 OK [3304]
2018-01-01 21:38:42,063 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1017, '_0n1': 122}
2018-01-01 21:38:42,066 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,070 : INFO : < 200 OK [3287]
2018-01-01 21:38:42,076 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 120}
2018-01-01 21:38:42,078 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,082 : INFO : < 200 OK [3327]
2018-01-01 21:38:42,086 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 998, '_0n1': 120}
2018-01-01 21:38:42,086 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,094 : INFO : < 200 OK [3305]
2018-01-01 21:38:42,094 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 120}
2018-01-01 21:38:42,098 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,102 : INFO : < 200 OK [3321]
2018-01-01 21:38:42,102 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 950, '_0n1': 120}
2018-01-01 21:38:42,106 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,110 : INFO : < 200 OK [3303]
2018-01-01 21:38:42,114 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 123}
2018-01-01 21:38:42,114 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,118 : INFO : < 200 OK [3327]
2018-01-01 21:38:42,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 123}
2018-01-01 21:38:42,122 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,126 : INFO : < 200 OK [3314]
2018-01-01 21:38:42,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 938, '_0n1': 123}
2018-01-01 21:38:42,130 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,134 : INFO : < 200 OK [3314]
2018-01-01 21:38:42,138 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 827, '_0n1': 141}
2018-01-01 21:38:42,142 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,146 : INFO : < 200 OK [3314]
2018-01-01 21:38:42,146 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 141}
2018-01-01 21:38:42,150 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,154 : INFO : < 200 OK [3328]
2018-01-01 21:38:42,158 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1158, '_0n1': 124}
2018-01-01 21:38:42,158 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,165 : INFO : < 200 OK [3313]
2018-01-01 21:38:42,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1097, '_0n1': 124}
2018-01-01 21:38:42,171 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,176 : INFO : < 200 OK [3314]
2018-01-01 21:38:42,178 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 995, '_0n1': 142}
2018-01-01 21:38:42,178 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,186 : INFO : < 200 OK [3326]
2018-01-01 21:38:42,190 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1132, '_0n1': 125}
2018-01-01 21:38:42,190 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,194 : INFO : < 200 OK [3311]
2018-01-01 21:38:42,198 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 891, '_0n1': 125}
2018-01-01 21:38:42,198 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,202 : INFO : < 200 OK [3298]
2018-01-01 21:38:42,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 798, '_0n1': 125}
2018-01-01 21:38:42,210 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,214 : INFO : < 200 OK [3298]
2018-01-01 21:38:42,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 143}
2018-01-01 21:38:42,218 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,222 : INFO : < 200 OK [3317]
2018-01-01 21:38:42,226 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 126}
2018-01-01 21:38:42,226 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,230 : INFO : < 200 OK [3346]
2018-01-01 21:38:42,234 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 144}
2018-01-01 21:38:42,234 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,242 : INFO : < 200 OK [3332]
2018-01-01 21:38:42,242 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1156, '_0n1': 127}
2018-01-01 21:38:42,246 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,250 : INFO : < 200 OK [3290]
2018-01-01 21:38:42,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 862, '_0n1': 145}
2018-01-01 21:38:42,254 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,258 : INFO : < 200 OK [3335]
2018-01-01 21:38:42,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 128}

2018-01-01 21:38:42,265 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,269 : INFO : < 200 OK [3323]
2018-01-01 21:38:42,271 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1038, '_0n1': 146}
2018-01-01 21:38:42,273 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,277 : INFO : < 200 OK [3299]
2018-01-01 21:38:42,278 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1039, '_0n1': 129}
2018-01-01 21:38:42,278 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,282 : INFO : < 200 OK [3307]
2018-01-01 21:38:42,286 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1080, '_0n1': 147}
2018-01-01 21:38:42,290 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,294 : INFO : < 200 OK [3328]
2018-01-01 21:38:42,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 130}
2018-01-01 21:38:42,298 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,302 : INFO : < 200 OK [3308]
2018-01-01 21:38:42,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 830, '_0n1': 148}
2018-01-01 21:38:42,306 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,314 : INFO : < 200 OK [3295]
2018-01-01 21:38:42,318 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1167, '_0n1': 131}
2018-01-01 21:38:42,322 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,326 : INFO : < 200 OK [3319]
2018-01-01 21:38:42,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1096, '_0n1': 149}
2018-01-01 21:38:42,334 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,338 : INFO : < 200 OK [3241]
2018-01-01 21:38:42,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 804, '_0n1': 132}
2018-01-01 21:38:42,346 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,350 : INFO : < 200 OK [3321]
2018-01-01 21:38:42,354 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 150}
2018-01-01 21:38:42,358 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,364 : INFO : < 200 OK [3304]
2018-01-01 21:38:42,366 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 915, '_0n1': 133}
2018-01-01 21:38:42,368 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,372 : INFO : < 200 OK [3280]
2018-01-01 21:38:42,375 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 838, '_0n1': 151}
2018-01-01 21:38:42,377 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,378 : INFO : < 200 OK [3278]
2018-01-01 21:38:42,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1128, '_0n1': 134}
2018-01-01 21:38:42,382 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,386 : INFO : < 200 OK [3308]
2018-01-01 21:38:42,390 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 969, '_0n1': 134}
2018-01-01 21:38:42,390 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,394 : INFO : < 200 OK [3289]
2018-01-01 21:38:42,398 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1000, '_0n1': 134}
2018-01-01 21:38:42,398 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,402 : INFO : < 200 OK [3306]
2018-01-01 21:38:42,410 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 912, '_0n1': 134}
2018-01-01 21:38:42,410 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,414 : INFO : < 200 OK [3295]
2018-01-01 21:38:42,418 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1120, '_0n1': 134}
2018-01-01 21:38:42,422 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,426 : INFO : < 200 OK [3311]
2018-01-01 21:38:42,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1115, '_0n1': 152}
2018-01-01 21:38:42,430 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,434 : INFO : < 200 OK [3279]
2018-01-01 21:38:42,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 885, '_0n1': 135}
2018-01-01 21:38:42,438 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,442 : INFO : < 200 OK [3294]
2018-01-01 21:38:42,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1043, '_0n1': 153}
2018-01-01 21:38:42,450 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,454 : INFO : < 200 OK [3294]
2018-01-01 21:38:42,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 818, '_0n1': 136}
2018-01-01 21:38:42,458 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,467 : INFO : < 200 OK [3322]
2018-01-01 21:38:42,470 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 731, '_0n1': 136}
2018-01-01 21:38:42,473 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,477 : INFO : < 200 OK [3327]
2018-01-01 21:38:42,478 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1066, '_0n1': 136}
2018-01-01 21:38:42,478 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,482 : INFO : < 200 OK [3333]
2018-01-01 21:38:42,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 857, '_0n1': 136}
2018-01-01 21:38:42,486 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,490 : INFO : < 200 OK [3318]
2018-01-01 21:38:42,494 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1208, '_0n1': 136}
2018-01-01 21:38:42,494 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,502 : INFO : < 200 OK [3342]
2018-01-01 21:38:42,502 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 884, '_0n1': 136}

2018-01-01 21:38:42,506 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,510 : INFO : < 200 OK [3320]
2018-01-01 21:38:42,514 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1203, '_0n1': 136}
2018-01-01 21:38:42,514 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,518 : INFO : < 200 OK [3343]
2018-01-01 21:38:42,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 154}
2018-01-01 21:38:42,522 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,526 : INFO : < 200 OK [3313]
2018-01-01 21:38:42,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 847, '_0n1': 137}
2018-01-01 21:38:42,534 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,538 : INFO : < 200 OK [3295]
2018-01-01 21:38:42,538 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 716, '_0n1': 155}
2018-01-01 21:38:42,542 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,546 : INFO : < 200 OK [3306]
2018-01-01 21:38:42,546 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 808, '_0n1': 155}
2018-01-01 21:38:42,550 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,554 : INFO : < 200 OK [3302]
2018-01-01 21:38:42,558 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 879, '_0n1': 138}
2018-01-01 21:38:42,558 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,565 : INFO : < 200 OK [3306]
2018-01-01 21:38:42,567 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 878, '_0n1': 156}
2018-01-01 21:38:42,570 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,574 : INFO : < 200 OK [3293]
2018-01-01 21:38:42,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1043, '_0n1': 139}
2018-01-01 21:38:42,578 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,582 : INFO : < 200 OK [3289]
2018-01-01 21:38:42,582 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1085, '_0n1': 157}
2018-01-01 21:38:42,586 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,590 : INFO : < 200 OK [3309]
2018-01-01 21:38:42,594 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1043, '_0n1': 140}
2018-01-01 21:38:42,594 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,602 : INFO : < 200 OK [3290]
2018-01-01 21:38:42,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 915, '_0n1': 158}
2018-01-01 21:38:42,610 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,614 : INFO : < 200 OK [3258]
2018-01-01 21:38:42,614 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 838, '_0n1': 161}
2018-01-01 21:38:42,618 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,622 : INFO : < 200 OK [3303]
2018-01-01 21:38:42,626 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1043, '_0n1': 159}
2018-01-01 21:38:42,626 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,630 : INFO : < 200 OK [3287]
2018-01-01 21:38:42,634 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 838, '_0n1': 162}
2018-01-01 21:38:42,634 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,638 : INFO : < 200 OK [3318]
2018-01-01 21:38:42,642 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1150, '_0n1': 162}
2018-01-01 21:38:42,642 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,646 : INFO : < 200 OK [3336]
2018-01-01 21:38:42,650 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 915, '_0n1': 160}
2018-01-01 21:38:42,650 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,658 : INFO : < 200 OK [3299]
2018-01-01 21:38:42,658 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 942, '_0n1': 163}
2018-01-01 21:38:42,663 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,667 : INFO : < 200 OK [3281]
2018-01-01 21:38:42,671 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 838, '_0n1': 163}
2018-01-01 21:38:42,672 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,676 : INFO : < 200 OK [3279]
2018-01-01 21:38:42,678 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1159, '_0n1': 164}
2018-01-01 21:38:42,678 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,686 : INFO : < 200 OK [3281]
2018-01-01 21:38:42,686 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 915, '_0n1': 181}
2018-01-01 21:38:42,690 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,694 : INFO : < 200 OK [3254]
2018-01-01 21:38:42,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 716, '_0n1': 165}
2018-01-01 21:38:42,702 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,706 : INFO : < 200 OK [3308]
2018-01-01 21:38:42,706 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 808, '_0n1': 165}
2018-01-01 21:38:42,710 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,714 : INFO : < 200 OK [3304]
2018-01-01 21:38:42,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1128, '_0n1': 182}
2018-01-01 21:38:42,718 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,722 : INFO : < 200 OK [3278]
2018-01-01 21:38:42,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 969, '_0n1': 182}
2018-01-01 21:38:42,726 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,734 : INFO : < 200 OK [3259]
2018-01-01 21:38:42,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1000, '_0n1': 182}

2018-01-01 21:38:42,738 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,742 : INFO : < 200 OK [3276]
2018-01-01 21:38:42,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 912, '_0n1': 182}
2018-01-01 21:38:42,746 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,750 : INFO : < 200 OK [3265]
2018-01-01 21:38:42,754 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1120, '_0n1': 182}
2018-01-01 21:38:42,758 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,763 : INFO : < 200 OK [3281]
2018-01-01 21:38:42,766 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1118, '_0n1': 166}
2018-01-01 21:38:42,768 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,773 : INFO : < 200 OK [3316]
2018-01-01 21:38:42,776 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1128, '_0n1': 183}
2018-01-01 21:38:42,777 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,782 : INFO : < 200 OK [3276]
2018-01-01 21:38:42,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 969, '_0n1': 183}
2018-01-01 21:38:42,786 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,790 : INFO : < 200 OK [3257]
2018-01-01 21:38:42,794 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1000, '_0n1': 183}
2018-01-01 21:38:42,798 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,802 : INFO : < 200 OK [3274]
2018-01-01 21:38:42,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 912, '_0n1': 183}
2018-01-01 21:38:42,810 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,814 : INFO : < 200 OK [3263]
2018-01-01 21:38:42,818 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1120, '_0n1': 183}
2018-01-01 21:38:42,822 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,826 : INFO : < 200 OK [3279]
2018-01-01 21:38:42,830 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 838, '_0n1': 167}
2018-01-01 21:38:42,834 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,838 : INFO : < 200 OK [3258]
2018-01-01 21:38:42,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1043, '_0n1': 184}
2018-01-01 21:38:42,842 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,850 : INFO : < 200 OK [3294]
2018-01-01 21:38:42,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 915, '_0n1': 168}
2018-01-01 21:38:42,858 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,869 : INFO : < 200 OK [3324]
2018-01-01 21:38:42,874 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1036, '_0n1': 185}
2018-01-01 21:38:42,876 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,882 : INFO : < 200 OK [3307]
2018-01-01 21:38:42,886 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 878, '_0n1': 169}
2018-01-01 21:38:42,886 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,890 : INFO : < 200 OK [3269]
2018-01-01 21:38:42,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1043, '_0n1': 186}
2018-01-01 21:38:42,898 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,902 : INFO : < 200 OK [3287]
2018-01-01 21:38:42,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 716, '_0n1': 170}
2018-01-01 21:38:42,910 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,914 : INFO : < 200 OK [3302]
2018-01-01 21:38:42,918 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 808, '_0n1': 170}
2018-01-01 21:38:42,918 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,922 : INFO : < 200 OK [3298]
2018-01-01 21:38:42,926 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1128, '_0n1': 187}
2018-01-01 21:38:42,926 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,930 : INFO : < 200 OK [3280]
2018-01-01 21:38:42,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 969, '_0n1': 187}
2018-01-01 21:38:42,934 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,938 : INFO : < 200 OK [3261]
2018-01-01 21:38:42,942 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1000, '_0n1': 187}
2018-01-01 21:38:42,942 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,946 : INFO : < 200 OK [3278]
2018-01-01 21:38:42,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 912, '_0n1': 187}
2018-01-01 21:38:42,950 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,954 : INFO : < 200 OK [3267]
2018-01-01 21:38:42,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1120, '_0n1': 187}
2018-01-01 21:38:42,958 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:42,965 : INFO : < 200 OK [3283]
2018-01-01 21:38:42,967 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 885, '_0n1': 171}
2018-01-01 21:38:42,969 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,973 : INFO : < 200 OK [3328]
2018-01-01 21:38:42,976 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 716, '_0n1': 188}
2018-01-01 21:38:42,978 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,982 : INFO : < 200 OK [3319]
2018-01-01 21:38:42,982 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 808, '_0n1': 188}
2018-01-01 21:38:42,986 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,990 : INFO : < 200 OK [3315]

2018-01-01 21:38:42,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 716, '_0n1': 172}
2018-01-01 21:38:42,994 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:42,998 : INFO : < 200 OK [3292]
2018-01-01 21:38:43,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 808, '_0n1': 172}
2018-01-01 21:38:43,002 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,010 : INFO : < 200 OK [3288]
2018-01-01 21:38:43,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 838, '_0n1': 189}
2018-01-01 21:38:43,018 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,022 : INFO : < 200 OK [3261]
2018-01-01 21:38:43,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 980, '_0n1': 173}
2018-01-01 21:38:43,030 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,034 : INFO : < 200 OK [3272]
2018-01-01 21:38:43,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 824, '_0n1': 190}
2018-01-01 21:38:43,042 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,046 : INFO : < 200 OK [3324]
2018-01-01 21:38:43,050 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1102, '_0n1': 174}
2018-01-01 21:38:43,050 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,058 : INFO : < 200 OK [3346]
2018-01-01 21:38:43,063 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1156, '_0n1': 191}
2018-01-01 21:38:43,065 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,070 : INFO : < 200 OK [3275]
2018-01-01 21:38:43,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1102, '_0n1': 175}
2018-01-01 21:38:43,078 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,078 : INFO : < 200 OK [3336]
2018-01-01 21:38:43,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1102, '_0n1': 192}
2018-01-01 21:38:43,086 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,090 : INFO : < 200 OK [3339]
2018-01-01 21:38:43,094 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1120, '_0n1': 176}
2018-01-01 21:38:43,094 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,102 : INFO : < 200 OK [3275]
2018-01-01 21:38:43,106 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1128, '_0n1': 176}
2018-01-01 21:38:43,106 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,110 : INFO : < 200 OK [3272]
2018-01-01 21:38:43,114 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 969, '_0n1': 176}
2018-01-01 21:38:43,118 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,122 : INFO : < 200 OK [3253]
2018-01-01 21:38:43,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1000, '_0n1': 176}
2018-01-01 21:38:43,126 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,130 : INFO : < 200 OK [3270]
2018-01-01 21:38:43,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 912, '_0n1': 176}
2018-01-01 21:38:43,134 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,138 : INFO : < 200 OK [3259]
2018-01-01 21:38:43,142 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 838, '_0n1': 193}
2018-01-01 21:38:43,142 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,146 : INFO : < 200 OK [3275]
2018-01-01 21:38:43,150 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1036, '_0n1': 177}
2018-01-01 21:38:43,154 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,158 : INFO : < 200 OK [3307]
2018-01-01 21:38:43,164 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 980, '_0n1': 177}
2018-01-01 21:38:43,167 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,173 : INFO : < 200 OK [3291]
2018-01-01 21:38:43,178 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1100, '_0n1': 194}
2018-01-01 21:38:43,178 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,182 : INFO : < 200 OK [3287]
2018-01-01 21:38:43,186 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 961, '_0n1': 194}
2018-01-01 21:38:43,186 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,194 : INFO : < 200 OK [3283]
2018-01-01 21:38:43,198 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 814, '_0n1': 178}
2018-01-01 21:38:43,198 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,202 : INFO : < 200 OK [3306]
2018-01-01 21:38:43,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 792, '_0n1': 195}
2018-01-01 21:38:43,206 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,210 : INFO : < 200 OK [3341]
2018-01-01 21:38:43,214 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 830, '_0n1': 179}
2018-01-01 21:38:43,214 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,218 : INFO : < 200 OK [3274]
2018-01-01 21:38:43,222 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 797, '_0n1': 196}
2018-01-01 21:38:43,222 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,230 : INFO : < 200 OK [3250]
2018-01-01 21:38:43,230 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 951, '_0n1': 196}
2018-01-01 21:38:43,234 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,238 : INFO : < 200 OK [3249]
2018-01-01 21:38:43,242 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1018, '_0n1': 196}

2018-01-01 21:38:43,242 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,246 : INFO : < 200 OK [3275]
2018-01-01 21:38:43,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1109, '_0n1': 196}
2018-01-01 21:38:43,250 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,254 : INFO : < 200 OK [3263]
2018-01-01 21:38:43,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 806, '_0n1': 196}
2018-01-01 21:38:43,258 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,264 : INFO : < 200 OK [3253]
2018-01-01 21:38:43,268 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1098, '_0n1': 196}
2018-01-01 21:38:43,269 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,273 : INFO : < 200 OK [3262]
2018-01-01 21:38:43,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1064, '_0n1': 196}
2018-01-01 21:38:43,277 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,278 : INFO : < 200 OK [3274]
2018-01-01 21:38:43,282 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1177, '_0n1': 196}
2018-01-01 21:38:43,282 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,286 : INFO : < 200 OK [3273]
2018-01-01 21:38:43,290 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 991, '_0n1': 196}
2018-01-01 21:38:43,290 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,294 : INFO : < 200 OK [3255]
2018-01-01 21:38:43,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1065, '_0n1': 196}
2018-01-01 21:38:43,298 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,306 : INFO : < 200 OK [3262]
2018-01-01 21:38:43,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 977, '_0n1': 196}
2018-01-01 21:38:43,310 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,314 : INFO : < 200 OK [3254]
2018-01-01 21:38:43,318 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1111, '_0n1': 196}
2018-01-01 21:38:43,322 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,326 : INFO : < 200 OK [3263]
2018-01-01 21:38:43,326 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 863, '_0n1': 196}
2018-01-01 21:38:43,330 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,334 : INFO : < 200 OK [3257]
2018-01-01 21:38:43,338 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1123, '_0n1': 196}
2018-01-01 21:38:43,342 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,350 : INFO : < 200 OK [3280]
2018-01-01 21:38:43,354 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 957, '_0n1': 196}
2018-01-01 21:38:43,354 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,358 : INFO : < 200 OK [3252]
2018-01-01 21:38:43,364 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 874, '_0n1': 180}
2018-01-01 21:38:43,366 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,370 : INFO : < 200 OK [3278]
2018-01-01 21:38:43,373 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1100, '_0n1': 197}
2018-01-01 21:38:43,374 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,378 : INFO : < 200 OK [3290]
2018-01-01 21:38:43,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1185, '_0n1': 197}
2018-01-01 21:38:43,382 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,386 : INFO : < 200 OK [3289]
2018-01-01 21:38:43,390 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1205, '_0n1': 197}
2018-01-01 21:38:43,390 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,398 : INFO : < 200 OK [3292]
2018-01-01 21:38:43,398 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 864, '_0n1': 201}
2018-01-01 21:38:43,402 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,406 : INFO : < 200 OK [3273]
2018-01-01 21:38:43,410 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 949, '_0n1': 201}
2018-01-01 21:38:43,410 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,414 : INFO : < 200 OK [3283]
2018-01-01 21:38:43,418 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1142, '_0n1': 198}
2018-01-01 21:38:43,418 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,422 : INFO : < 200 OK [3333]
2018-01-01 21:38:43,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 715, '_0n1': 198}
2018-01-01 21:38:43,426 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,430 : INFO : < 200 OK [3316]
2018-01-01 21:38:43,434 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 830, '_0n1': 202}
2018-01-01 21:38:43,434 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,438 : INFO : < 200 OK [3264]
2018-01-01 21:38:43,442 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 740, '_0n1': 199}
2018-01-01 21:38:43,442 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,446 : INFO : < 200 OK [3284]
2018-01-01 21:38:43,450 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 780, '_0n1': 199}
2018-01-01 21:38:43,450 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,454 : INFO : < 200 OK [3283]
2018-01-01 21:38:43,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1100, '_0n1': 203}
2018-01-01 21:38:43,458 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,466 : INFO : < 200 OK [3324]
2018-01-01 21:38:43,468 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1185, '_0n1': 203}

2018-01-01 21:38:43,470 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,474 : INFO : < 200 OK [3323]
2018-01-01 21:38:43,477 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1172, '_0n1': 200}
2018-01-01 21:38:43,479 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,483 : INFO : < 200 OK [3324]
2018-01-01 21:38:43,483 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1034, '_0n1': 200}
2018-01-01 21:38:43,487 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,491 : INFO : < 200 OK [3323]
2018-01-01 21:38:43,495 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 815, '_0n1': 200}
2018-01-01 21:38:43,495 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,499 : INFO : < 200 OK [3308]
2018-01-01 21:38:43,503 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1186, '_0n1': 200}
2018-01-01 21:38:43,503 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,511 : INFO : < 200 OK [3325]
2018-01-01 21:38:43,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 732, '_0n1': 200}
2018-01-01 21:38:43,515 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,523 : INFO : < 200 OK [3316]
2018-01-01 21:38:43,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1154, '_0n1': 204}
2018-01-01 21:38:43,527 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,531 : INFO : < 200 OK [3321]
2018-01-01 21:38:43,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 821, '_0n1': 204}
2018-01-01 21:38:43,539 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,543 : INFO : < 200 OK [3306]
2018-01-01 21:38:43,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1012, '_0n1': 204}
2018-01-01 21:38:43,547 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,551 : INFO : < 200 OK [3323]
2018-01-01 21:38:43,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1069, '_0n1': 204}
2018-01-01 21:38:43,559 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,565 : INFO : < 200 OK [3319]
2018-01-01 21:38:43,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1058, '_0n1': 204}
2018-01-01 21:38:43,571 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,575 : INFO : < 200 OK [3319]
2018-01-01 21:38:43,579 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1044, '_0n1': 221}
2018-01-01 21:38:43,579 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,583 : INFO : < 200 OK [3271]
2018-01-01 21:38:43,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 874, '_0n1': 205}
2018-01-01 21:38:43,591 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,595 : INFO : < 200 OK [3263]
2018-01-01 21:38:43,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1164, '_0n1': 222}
2018-01-01 21:38:43,603 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,607 : INFO : < 200 OK [3289]
2018-01-01 21:38:43,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1118, '_0n1': 206}
2018-01-01 21:38:43,611 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,615 : INFO : < 200 OK [3288]
2018-01-01 21:38:43,619 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 864, '_0n1': 223}
2018-01-01 21:38:43,623 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,627 : INFO : < 200 OK [3233]
2018-01-01 21:38:43,631 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 874, '_0n1': 207}
2018-01-01 21:38:43,631 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,635 : INFO : < 200 OK [3262]
2018-01-01 21:38:43,639 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 780, '_0n1': 243}
2018-01-01 21:38:43,639 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,647 : INFO : < 200 OK [3297]
2018-01-01 21:38:43,647 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 740, '_0n1': 243}
2018-01-01 21:38:43,651 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,655 : INFO : < 200 OK [3298]
2018-01-01 21:38:43,659 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 945, '_0n1': 208}
2018-01-01 21:38:43,659 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,666 : INFO : < 200 OK [3317]
2018-01-01 21:38:43,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 843, '_0n1': 244}
2018-01-01 21:38:43,672 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,676 : INFO : < 200 OK [3318]
2018-01-01 21:38:43,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 740, '_0n1': 209}
2018-01-01 21:38:43,682 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,686 : INFO : < 200 OK [3287]
2018-01-01 21:38:43,690 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 780, '_0n1': 209}
2018-01-01 21:38:43,692 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,696 : INFO : < 200 OK [3286]
2018-01-01 21:38:43,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 958, '_0n1': 245}
2018-01-01 21:38:43,702 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,707 : INFO : < 200 OK [3345]
2018-01-01 21:38:43,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 853, '_0n1': 210}
2018-01-01 21:38:43,714 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,721 : INFO : < 200 OK [3312]
2018-01-01 21:38:43,725 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1178, '_0n1': 210}

2018-01-01 21:38:43,727 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,733 : INFO : < 200 OK [3315]
2018-01-01 21:38:43,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 728, '_0n1': 246}
2018-01-01 21:38:43,739 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,743 : INFO : < 200 OK [3312]
2018-01-01 21:38:43,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 728, '_0n1': 211}
2018-01-01 21:38:43,749 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,754 : INFO : < 200 OK [3341]
2018-01-01 21:38:43,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 830, '_0n1': 247}
2018-01-01 21:38:43,759 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,764 : INFO : < 200 OK [3282]
2018-01-01 21:38:43,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 874, '_0n1': 212}
2018-01-01 21:38:43,769 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,774 : INFO : < 200 OK [3322]
2018-01-01 21:38:43,777 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 945, '_0n1': 212}
2018-01-01 21:38:43,779 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,784 : INFO : < 200 OK [3324]
2018-01-01 21:38:43,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 843, '_0n1': 212}
2018-01-01 21:38:43,789 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,793 : INFO : < 200 OK [3321]
2018-01-01 21:38:43,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 780, '_0n1': 248}
2018-01-01 21:38:43,799 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,803 : INFO : < 200 OK [3306]
2018-01-01 21:38:43,807 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 740, '_0n1': 248}
2018-01-01 21:38:43,808 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,813 : INFO : < 200 OK [3307]
2018-01-01 21:38:43,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 785, '_0n1': 213}
2018-01-01 21:38:43,818 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,824 : INFO : < 200 OK [3293]
2018-01-01 21:38:43,827 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 851, '_0n1': 249}
2018-01-01 21:38:43,829 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,833 : INFO : < 200 OK [3312]
2018-01-01 21:38:43,836 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 943, '_0n1': 214}
2018-01-01 21:38:43,838 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,842 : INFO : < 200 OK [3284]
2018-01-01 21:38:43,846 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 886, '_0n1': 214}
2018-01-01 21:38:43,847 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,852 : INFO : < 200 OK [3284]
2018-01-01 21:38:43,855 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1127, '_0n1': 214}
2018-01-01 21:38:43,857 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,862 : INFO : < 200 OK [3292]
2018-01-01 21:38:43,865 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 888, '_0n1': 250}
2018-01-01 21:38:43,867 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,871 : INFO : < 200 OK [3291]
2018-01-01 21:38:43,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 828, '_0n1': 250}
2018-01-01 21:38:43,877 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,881 : INFO : < 200 OK [3291]
2018-01-01 21:38:43,885 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 999, '_0n1': 215}
2018-01-01 21:38:43,887 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,891 : INFO : < 200 OK [3253]
2018-01-01 21:38:43,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1084, '_0n1': 251}
2018-01-01 21:38:43,896 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,902 : INFO : < 200 OK [3313]
2018-01-01 21:38:43,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 850, '_0n1': 216}
2018-01-01 21:38:43,909 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,917 : INFO : < 200 OK [3299]
2018-01-01 21:38:43,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1083, '_0n1': 252}
2018-01-01 21:38:43,924 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,930 : INFO : < 200 OK [3335]
2018-01-01 21:38:43,933 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1117, '_0n1': 217}
2018-01-01 21:38:43,935 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,940 : INFO : < 200 OK [3316]
2018-01-01 21:38:43,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 779, '_0n1': 217}
2018-01-01 21:38:43,947 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,951 : INFO : < 200 OK [3305]
2018-01-01 21:38:43,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 881, '_0n1': 253}
2018-01-01 21:38:43,957 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:43,962 : INFO : < 200 OK [3283]
2018-01-01 21:38:43,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1204, '_0n1': 253}
2018-01-01 21:38:43,967 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,972 : INFO : < 200 OK [3294]
2018-01-01 21:38:43,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1110, '_0n1': 253}
2018-01-01 21:38:43,977 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,982 : INFO : < 200 OK [3297]
2018-01-01 21:38:43,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1174, '_0n1': 253}

2018-01-01 21:38:43,987 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:43,992 : INFO : < 200 OK [3289]
2018-01-01 21:38:43,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1055, '_0n1': 253}
2018-01-01 21:38:43,997 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,003 : INFO : < 200 OK [3291]
2018-01-01 21:38:44,006 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 923, '_0n1': 253}
2018-01-01 21:38:44,008 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,013 : INFO : < 200 OK [3278]
2018-01-01 21:38:44,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 801, '_0n1': 253}
2018-01-01 21:38:44,018 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,022 : INFO : < 200 OK [3273]
2018-01-01 21:38:44,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1161, '_0n1': 253}
2018-01-01 21:38:44,027 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,032 : INFO : < 200 OK [3296]
2018-01-01 21:38:44,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1103, '_0n1': 253}
2018-01-01 21:38:44,037 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,041 : INFO : < 200 OK [3297]
2018-01-01 21:38:44,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1117, '_0n1': 218}
2018-01-01 21:38:44,046 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,050 : INFO : < 200 OK [3319]
2018-01-01 21:38:44,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 779, '_0n1': 218}
2018-01-01 21:38:44,055 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,060 : INFO : < 200 OK [3308]
2018-01-01 21:38:44,063 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 803, '_0n1': 254}
2018-01-01 21:38:44,065 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,070 : INFO : < 200 OK [3315]
2018-01-01 21:38:44,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1029, '_0n1': 219}
2018-01-01 21:38:44,074 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,079 : INFO : < 200 OK [3277]
2018-01-01 21:38:44,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1054, '_0n1': 255}
2018-01-01 21:38:44,084 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,090 : INFO : < 200 OK [3306]
2018-01-01 21:38:44,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 752, '_0n1': 220}
2018-01-01 21:38:44,095 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,099 : INFO : < 200 OK [3258]
2018-01-01 21:38:44,102 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 999, '_0n1': 256}
2018-01-01 21:38:44,104 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,109 : INFO : < 200 OK [3275]
2018-01-01 21:38:44,112 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 907, '_0n1': 260}
2018-01-01 21:38:44,114 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,119 : INFO : < 200 OK [3315]
2018-01-01 21:38:44,123 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 880, '_0n1': 257}
2018-01-01 21:38:44,125 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,131 : INFO : < 200 OK [3320]
2018-01-01 21:38:44,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 261}
2018-01-01 21:38:44,138 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,144 : INFO : < 200 OK [3280]
2018-01-01 21:38:44,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1082, '_0n1': 258}
2018-01-01 21:38:44,152 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,157 : INFO : < 200 OK [3329]
2018-01-01 21:38:44,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 943, '_0n1': 262}
2018-01-01 21:38:44,165 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,172 : INFO : < 200 OK [3310]
2018-01-01 21:38:44,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 886, '_0n1': 262}
2018-01-01 21:38:44,180 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,185 : INFO : < 200 OK [3310]
2018-01-01 21:38:44,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1127, '_0n1': 262}
2018-01-01 21:38:44,193 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,198 : INFO : < 200 OK [3318]
2018-01-01 21:38:44,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1104, '_0n1': 259}
2018-01-01 21:38:44,207 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,212 : INFO : < 200 OK [3306]
2018-01-01 21:38:44,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1093, '_0n1': 263}
2018-01-01 21:38:44,217 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,222 : INFO : < 200 OK [3289]
2018-01-01 21:38:44,228 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 280}
2018-01-01 21:38:44,230 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,234 : INFO : < 200 OK [3327]
2018-01-01 21:38:44,238 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 875, '_0n1': 264}
2018-01-01 21:38:44,240 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,245 : INFO : < 200 OK [3296]
2018-01-01 21:38:44,249 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1209, '_0n1': 264}
2018-01-01 21:38:44,251 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,255 : INFO : < 200 OK [3304]
2018-01-01 21:38:44,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 870, '_0n1': 281}

2018-01-01 21:38:44,260 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,265 : INFO : < 200 OK [3269]
2018-01-01 21:38:44,269 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1137, '_0n1': 265}
2018-01-01 21:38:44,271 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,276 : INFO : < 200 OK [3326]
2018-01-01 21:38:44,280 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 752, '_0n1': 282}
2018-01-01 21:38:44,281 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,286 : INFO : < 200 OK [3238]
2018-01-01 21:38:44,290 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1090, '_0n1': 266}
2018-01-01 21:38:44,292 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,296 : INFO : < 200 OK [3312]
2018-01-01 21:38:44,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1106, '_0n1': 266}
2018-01-01 21:38:44,428 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,438 : INFO : < 200 OK [3310]
2018-01-01 21:38:44,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 752, '_0n1': 283}
2018-01-01 21:38:44,445 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,450 : INFO : < 200 OK [3264]
2018-01-01 21:38:44,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 784, '_0n1': 267}
2018-01-01 21:38:44,459 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,463 : INFO : < 200 OK [3300]
2018-01-01 21:38:44,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 894, '_0n1': 284}
2018-01-01 21:38:44,468 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,473 : INFO : < 200 OK [3324]
2018-01-01 21:38:44,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1086, '_0n1': 284}
2018-01-01 21:38:44,478 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,483 : INFO : < 200 OK [3336]
2018-01-01 21:38:44,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 752, '_0n1': 268}
2018-01-01 21:38:44,489 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,497 : INFO : < 200 OK [3260]
2018-01-01 21:38:44,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 963, '_0n1': 285}
2018-01-01 21:38:44,502 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,508 : INFO : < 200 OK [3287]
2018-01-01 21:38:44,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 858, '_0n1': 269}
2018-01-01 21:38:44,514 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,518 : INFO : < 200 OK [3264]
2018-01-01 21:38:44,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 286}
2018-01-01 21:38:44,524 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,528 : INFO : < 200 OK [3339]
2018-01-01 21:38:44,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 940, '_0n1': 270}
2018-01-01 21:38:44,533 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,537 : INFO : < 200 OK [3321]
2018-01-01 21:38:44,540 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 752, '_0n1': 287}
2018-01-01 21:38:44,542 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,547 : INFO : < 200 OK [3261]
2018-01-01 21:38:44,550 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 928, '_0n1': 271}
2018-01-01 21:38:44,551 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,556 : INFO : < 200 OK [3314]
2018-01-01 21:38:44,559 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1062, '_0n1': 288}
2018-01-01 21:38:44,560 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,565 : INFO : < 200 OK [3287]
2018-01-01 21:38:44,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1086, '_0n1': 272}
2018-01-01 21:38:44,570 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,574 : INFO : < 200 OK [3339]
2018-01-01 21:38:44,577 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 894, '_0n1': 272}
2018-01-01 21:38:44,579 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,585 : INFO : < 200 OK [3327]
2018-01-01 21:38:44,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 973, '_0n1': 289}
2018-01-01 21:38:44,590 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,595 : INFO : < 200 OK [3305]
2018-01-01 21:38:44,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 842, '_0n1': 289}
2018-01-01 21:38:44,601 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,606 : INFO : < 200 OK [3297]
2018-01-01 21:38:44,610 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1141, '_0n1': 289}
2018-01-01 21:38:44,611 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,616 : INFO : < 200 OK [3315]
2018-01-01 21:38:44,619 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 993, '_0n1': 289}
2018-01-01 21:38:44,621 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,626 : INFO : < 200 OK [3298]
2018-01-01 21:38:44,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 772, '_0n1': 273}
2018-01-01 21:38:44,631 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,635 : INFO : < 200 OK [3289]
2018-01-01 21:38:44,638 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 290}
2018-01-01 21:38:44,641 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,645 : INFO : < 200 OK [3280]
2018-01-01 21:38:44,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 849, '_0n1': 274}

2018-01-01 21:38:44,650 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,655 : INFO : < 200 OK [3314]
2018-01-01 21:38:44,658 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 761, '_0n1': 291}
2018-01-01 21:38:44,660 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,665 : INFO : < 200 OK [3287]
2018-01-01 21:38:44,668 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1076, '_0n1': 275}
2018-01-01 21:38:44,671 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,675 : INFO : < 200 OK [3309]
2018-01-01 21:38:44,679 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 875, '_0n1': 292}
2018-01-01 21:38:44,681 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,685 : INFO : < 200 OK [3261]
2018-01-01 21:38:44,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1121, '_0n1': 292}
2018-01-01 21:38:44,690 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,695 : INFO : < 200 OK [3271]
2018-01-01 21:38:44,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1095, '_0n1': 276}
2018-01-01 21:38:44,700 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,708 : INFO : < 200 OK [3285]
2018-01-01 21:38:44,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1059, '_0n1': 293}
2018-01-01 21:38:44,714 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,719 : INFO : < 200 OK [3315]
2018-01-01 21:38:44,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1013, '_0n1': 293}
2018-01-01 21:38:44,725 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,729 : INFO : < 200 OK [3310]
2018-01-01 21:38:44,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 926, '_0n1': 277}
2018-01-01 21:38:44,737 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,742 : INFO : < 200 OK [3323]
2018-01-01 21:38:44,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 719, '_0n1': 277}
2018-01-01 21:38:44,750 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,755 : INFO : < 200 OK [3321]
2018-01-01 21:38:44,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 962, '_0n1': 277}
2018-01-01 21:38:44,761 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,767 : INFO : < 200 OK [3322]
2018-01-01 21:38:44,771 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1025, '_0n1': 277}
2018-01-01 21:38:44,773 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,777 : INFO : < 200 OK [3339]
2018-01-01 21:38:44,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 835, '_0n1': 294}
2018-01-01 21:38:44,782 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,787 : INFO : < 200 OK [3315]
2018-01-01 21:38:44,790 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 919, '_0n1': 294}
2018-01-01 21:38:44,793 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,797 : INFO : < 200 OK [3303]
2018-01-01 21:38:44,800 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 960, '_0n1': 278}
2018-01-01 21:38:44,802 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,807 : INFO : < 200 OK [3326]
2018-01-01 21:38:44,810 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 810, '_0n1': 295}
2018-01-01 21:38:44,812 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,817 : INFO : < 200 OK [3301]
2018-01-01 21:38:44,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 754, '_0n1': 279}
2018-01-01 21:38:44,822 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,827 : INFO : < 200 OK [3285]
2018-01-01 21:38:44,831 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 774, '_0n1': 279}
2018-01-01 21:38:44,834 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,838 : INFO : < 200 OK [3291]
2018-01-01 21:38:44,841 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1207, '_0n1': 279}
2018-01-01 21:38:44,843 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,847 : INFO : < 200 OK [3300]
2018-01-01 21:38:44,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 781, '_0n1': 279}
2018-01-01 21:38:44,853 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,858 : INFO : < 200 OK [3293]
2018-01-01 21:38:44,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 960, '_0n1': 296}
2018-01-01 21:38:44,863 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,867 : INFO : < 200 OK [3316]
2018-01-01 21:38:44,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1095, '_0n1': 300}
2018-01-01 21:38:44,873 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,877 : INFO : < 200 OK [3284]
2018-01-01 21:38:44,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 960, '_0n1': 297}
2018-01-01 21:38:44,883 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,887 : INFO : < 200 OK [3332]
2018-01-01 21:38:44,890 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1095, '_0n1': 301}
2018-01-01 21:38:44,892 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,897 : INFO : < 200 OK [3293]
2018-01-01 21:38:44,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 910, '_0n1': 298}
2018-01-01 21:38:44,902 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,908 : INFO : < 200 OK [3300]

2018-01-01 21:38:44,912 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 983, '_0n1': 302}
2018-01-01 21:38:44,915 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,921 : INFO : < 200 OK [3309]
2018-01-01 21:38:44,924 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1043, '_0n1': 299}
2018-01-01 21:38:44,927 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,932 : INFO : < 200 OK [3299]
2018-01-01 21:38:44,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1032, '_0n1': 303}
2018-01-01 21:38:44,939 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,945 : INFO : < 200 OK [3323]
2018-01-01 21:38:44,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 808, '_0n1': 303}
2018-01-01 21:38:44,952 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,959 : INFO : < 200 OK [3305]
2018-01-01 21:38:44,962 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 970, '_0n1': 303}
2018-01-01 21:38:44,965 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:44,969 : INFO : < 200 OK [3303]
2018-01-01 21:38:44,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1165, '_0n1': 320}
2018-01-01 21:38:44,976 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,981 : INFO : < 200 OK [3284]
2018-01-01 21:38:44,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1151, '_0n1': 304}
2018-01-01 21:38:44,987 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:44,992 : INFO : < 200 OK [3285]
2018-01-01 21:38:44,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1038, '_0n1': 321}
2018-01-01 21:38:44,999 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,004 : INFO : < 200 OK [3331]
2018-01-01 21:38:45,008 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1043, '_0n1': 305}
2018-01-01 21:38:45,010 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,015 : INFO : < 200 OK [3313]
2018-01-01 21:38:45,018 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1043, '_0n1': 322}
2018-01-01 21:38:45,020 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,026 : INFO : < 200 OK [3305]
2018-01-01 21:38:45,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 964, '_0n1': 306}
2018-01-01 21:38:45,031 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,036 : INFO : < 200 OK [3282]
2018-01-01 21:38:45,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1147, '_0n1': 306}
2018-01-01 21:38:45,042 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,046 : INFO : < 200 OK [3306]
2018-01-01 21:38:45,050 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 960, '_0n1': 323}
2018-01-01 21:38:45,052 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,056 : INFO : < 200 OK [3320]
2018-01-01 21:38:45,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 832, '_0n1': 307}
2018-01-01 21:38:45,062 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,066 : INFO : < 200 OK [3313]
2018-01-01 21:38:45,070 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 788, '_0n1': 324}
2018-01-01 21:38:45,072 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,076 : INFO : < 200 OK [3272]
2018-01-01 21:38:45,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1095, '_0n1': 308}
2018-01-01 21:38:45,081 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,086 : INFO : < 200 OK [3303]
2018-01-01 21:38:45,089 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 810, '_0n1': 325}
2018-01-01 21:38:45,091 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,096 : INFO : < 200 OK [3268]
2018-01-01 21:38:45,099 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1032, '_0n1': 309}
2018-01-01 21:38:45,100 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,105 : INFO : < 200 OK [3281]
2018-01-01 21:38:45,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 970, '_0n1': 309}
2018-01-01 21:38:45,110 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,114 : INFO : < 200 OK [3261]
2018-01-01 21:38:45,117 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 808, '_0n1': 309}
2018-01-01 21:38:45,119 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,124 : INFO : < 200 OK [3263]
2018-01-01 21:38:45,127 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 861, '_0n1': 309}
2018-01-01 21:38:45,129 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,133 : INFO : < 200 OK [3263]
2018-01-01 21:38:45,138 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 810, '_0n1': 326}
2018-01-01 21:38:45,139 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,144 : INFO : < 200 OK [3301]
2018-01-01 21:38:45,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 781, '_0n1': 310}
2018-01-01 21:38:45,149 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,153 : INFO : < 200 OK [3317]
2018-01-01 21:38:45,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1207, '_0n1': 310}
2018-01-01 21:38:45,159 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,163 : INFO : < 200 OK [3324]
2018-01-01 21:38:45,167 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 965, '_0n1': 310}

2018-01-01 21:38:45,169 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,174 : INFO : < 200 OK [3313]
2018-01-01 21:38:45,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 960, '_0n1': 327}
2018-01-01 21:38:45,178 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,183 : INFO : < 200 OK [3330]
2018-01-01 21:38:45,187 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 739, '_0n1': 311}
2018-01-01 21:38:45,189 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,193 : INFO : < 200 OK [3299]
2018-01-01 21:38:45,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1032, '_0n1': 328}
2018-01-01 21:38:45,199 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,204 : INFO : < 200 OK [3315]
2018-01-01 21:38:45,208 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 781, '_0n1': 312}
2018-01-01 21:38:45,211 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,216 : INFO : < 200 OK [3344]
2018-01-01 21:38:45,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 983, '_0n1': 329}
2018-01-01 21:38:45,223 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,227 : INFO : < 200 OK [3309]
2018-01-01 21:38:45,232 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 781, '_0n1': 313}
2018-01-01 21:38:45,234 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,240 : INFO : < 200 OK [3285]
2018-01-01 21:38:45,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1207, '_0n1': 313}
2018-01-01 21:38:45,246 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,250 : INFO : < 200 OK [3292]
2018-01-01 21:38:45,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 965, '_0n1': 313}
2018-01-01 21:38:45,256 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,261 : INFO : < 200 OK [3281]
2018-01-01 21:38:45,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 776, '_0n1': 330}
2018-01-01 21:38:45,267 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,272 : INFO : < 200 OK [3296]
2018-01-01 21:38:45,276 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1032, '_0n1': 314}
2018-01-01 21:38:45,279 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,283 : INFO : < 200 OK [3299]
2018-01-01 21:38:45,288 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1032, '_0n1': 331}
2018-01-01 21:38:45,291 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,295 : INFO : < 200 OK [3300]
2018-01-01 21:38:45,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 861, '_0n1': 331}
2018-01-01 21:38:45,302 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,307 : INFO : < 200 OK [3282]
2018-01-01 21:38:45,311 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 788, '_0n1': 315}
2018-01-01 21:38:45,313 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,317 : INFO : < 200 OK [3265]
2018-01-01 21:38:45,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1165, '_0n1': 332}
2018-01-01 21:38:45,323 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,327 : INFO : < 200 OK [3294]
2018-01-01 21:38:45,332 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 845, '_0n1': 316}
2018-01-01 21:38:45,333 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,338 : INFO : < 200 OK [3281]
2018-01-01 21:38:45,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1051, '_0n1': 316}
2018-01-01 21:38:45,344 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,348 : INFO : < 200 OK [3294]
2018-01-01 21:38:45,353 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 896, '_0n1': 333}
2018-01-01 21:38:45,355 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,359 : INFO : < 200 OK [3288]
2018-01-01 21:38:45,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 317}
2018-01-01 21:38:45,365 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,370 : INFO : < 200 OK [3339]
2018-01-01 21:38:45,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 788, '_0n1': 334}
2018-01-01 21:38:45,376 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,380 : INFO : < 200 OK [3273]
2018-01-01 21:38:45,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 845, '_0n1': 318}
2018-01-01 21:38:45,386 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,391 : INFO : < 200 OK [3283]
2018-01-01 21:38:45,394 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1051, '_0n1': 318}
2018-01-01 21:38:45,396 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,400 : INFO : < 200 OK [3296]
2018-01-01 21:38:45,405 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1210, '_0n1': 335}
2018-01-01 21:38:45,406 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,411 : INFO : < 200 OK [3311]
2018-01-01 21:38:45,415 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1088, '_0n1': 335}
2018-01-01 21:38:45,416 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,421 : INFO : < 200 OK [3300]
2018-01-01 21:38:45,424 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 911, '_0n1': 335}
2018-01-01 21:38:45,426 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,430 : INFO : < 200 OK [3288]
2018-01-01 21:38:45,433 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 947, '_0n1': 319}

2018-01-01 21:38:45,435 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,439 : INFO : < 200 OK [3285]
2018-01-01 21:38:45,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1145, '_0n1': 336}
2018-01-01 21:38:45,444 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,449 : INFO : < 200 OK [3331]
2018-01-01 21:38:45,452 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 781, '_0n1': 340}
2018-01-01 21:38:45,454 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,458 : INFO : < 200 OK [3293]
2018-01-01 21:38:45,462 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1207, '_0n1': 340}
2018-01-01 21:38:45,464 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,468 : INFO : < 200 OK [3300]
2018-01-01 21:38:45,472 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 965, '_0n1': 340}
2018-01-01 21:38:45,475 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,479 : INFO : < 200 OK [3289]
2018-01-01 21:38:45,483 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 882, '_0n1': 337}
2018-01-01 21:38:45,485 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,489 : INFO : < 200 OK [3277]
2018-01-01 21:38:45,493 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 845, '_0n1': 341}
2018-01-01 21:38:45,494 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,499 : INFO : < 200 OK [3269]
2018-01-01 21:38:45,502 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1051, '_0n1': 341}
2018-01-01 21:38:45,504 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,509 : INFO : < 200 OK [3282]
2018-01-01 21:38:45,514 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1095, '_0n1': 338}
2018-01-01 21:38:45,516 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,521 : INFO : < 200 OK [3297]
2018-01-01 21:38:45,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1032, '_0n1': 342}
2018-01-01 21:38:45,527 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,531 : INFO : < 200 OK [3311]
2018-01-01 21:38:45,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1125, '_0n1': 342}
2018-01-01 21:38:45,538 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,543 : INFO : < 200 OK [3311]
2018-01-01 21:38:45,548 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 788, '_0n1': 339}
2018-01-01 21:38:45,549 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,554 : INFO : < 200 OK [3261]
2018-01-01 21:38:45,558 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1166, '_0n1': 343}
2018-01-01 21:38:45,560 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,565 : INFO : < 200 OK [3324]
2018-01-01 21:38:45,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 867, '_0n1': 343}
2018-01-01 21:38:45,571 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,575 : INFO : < 200 OK [3312]
2018-01-01 21:38:45,579 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 922, '_0n1': 343}
2018-01-01 21:38:45,581 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,585 : INFO : < 200 OK [3310]
2018-01-01 21:38:45,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 360}
2018-01-01 21:38:45,591 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,595 : INFO : < 200 OK [3290]
2018-01-01 21:38:45,600 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 360}
2018-01-01 21:38:45,602 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,606 : INFO : < 200 OK [3286]
2018-01-01 21:38:45,610 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 360}
2018-01-01 21:38:45,612 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,617 : INFO : < 200 OK [3288]
2018-01-01 21:38:45,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 837, '_0n1': 344}
2018-01-01 21:38:45,623 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,627 : INFO : < 200 OK [3313]
2018-01-01 21:38:45,631 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 361}
2018-01-01 21:38:45,633 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,637 : INFO : < 200 OK [3265]
2018-01-01 21:38:45,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 361}
2018-01-01 21:38:45,643 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,648 : INFO : < 200 OK [3269]
2018-01-01 21:38:45,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 361}
2018-01-01 21:38:45,653 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,657 : INFO : < 200 OK [3267]
2018-01-01 21:38:45,660 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 921, '_0n1': 345}
2018-01-01 21:38:45,662 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,667 : INFO : < 200 OK [3288]
2018-01-01 21:38:45,670 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1131, '_0n1': 345}
2018-01-01 21:38:45,672 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,676 : INFO : < 200 OK [3300]
2018-01-01 21:38:45,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 362}
2018-01-01 21:38:45,682 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,686 : INFO : < 200 OK [3269]
2018-01-01 21:38:45,690 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 362}

2018-01-01 21:38:45,692 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,697 : INFO : < 200 OK [3265]
2018-01-01 21:38:45,701 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 362}
2018-01-01 21:38:45,703 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,708 : INFO : < 200 OK [3267]
2018-01-01 21:38:45,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 346}
2018-01-01 21:38:45,713 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,721 : INFO : < 200 OK [3259]
2018-01-01 21:38:45,725 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 346}
2018-01-01 21:38:45,727 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,731 : INFO : < 200 OK [3261]
2018-01-01 21:38:45,735 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 346}
2018-01-01 21:38:45,737 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,742 : INFO : < 200 OK [3257]
2018-01-01 21:38:45,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 363}
2018-01-01 21:38:45,747 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,752 : INFO : < 200 OK [3263]
2018-01-01 21:38:45,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 363}
2018-01-01 21:38:45,758 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,762 : INFO : < 200 OK [3265]
2018-01-01 21:38:45,766 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 363}
2018-01-01 21:38:45,768 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,772 : INFO : < 200 OK [3261]
2018-01-01 21:38:45,776 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1060, '_0n1': 347}
2018-01-01 21:38:45,778 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,783 : INFO : < 200 OK [3278]
2018-01-01 21:38:45,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 987, '_0n1': 347}
2018-01-01 21:38:45,788 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,792 : INFO : < 200 OK [3269]
2018-01-01 21:38:45,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 837, '_0n1': 364}
2018-01-01 21:38:45,798 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,803 : INFO : < 200 OK [3299]
2018-01-01 21:38:45,807 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1092, '_0n1': 348}
2018-01-01 21:38:45,808 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,813 : INFO : < 200 OK [3271]
2018-01-01 21:38:45,817 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 837, '_0n1': 365}
2018-01-01 21:38:45,819 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,823 : INFO : < 200 OK [3300]
2018-01-01 21:38:45,827 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 836, '_0n1': 365}
2018-01-01 21:38:45,830 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,834 : INFO : < 200 OK [3289]
2018-01-01 21:38:45,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 932, '_0n1': 365}
2018-01-01 21:38:45,839 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,844 : INFO : < 200 OK [3291]
2018-01-01 21:38:45,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 738, '_0n1': 365}
2018-01-01 21:38:45,849 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,854 : INFO : < 200 OK [3293]
2018-01-01 21:38:45,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 837, '_0n1': 349}
2018-01-01 21:38:45,860 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,864 : INFO : < 200 OK [3308]
2018-01-01 21:38:45,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 366}
2018-01-01 21:38:45,870 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,876 : INFO : < 200 OK [3265]
2018-01-01 21:38:45,879 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 366}
2018-01-01 21:38:45,881 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,888 : INFO : < 200 OK [3261]
2018-01-01 21:38:45,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 366}
2018-01-01 21:38:45,894 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,898 : INFO : < 200 OK [3263]
2018-01-01 21:38:45,902 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 725, '_0n1': 350}
2018-01-01 21:38:45,904 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,909 : INFO : < 200 OK [3309]
2018-01-01 21:38:45,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1090, '_0n1': 367}
2018-01-01 21:38:45,915 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,920 : INFO : < 200 OK [3309]
2018-01-01 21:38:45,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 351}
2018-01-01 21:38:45,924 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,928 : INFO : < 200 OK [3266]
2018-01-01 21:38:45,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 351}
2018-01-01 21:38:45,934 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,935 : INFO : < 200 OK [3264]
2018-01-01 21:38:45,939 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 351}
2018-01-01 21:38:45,939 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,947 : INFO : < 200 OK [3268]
2018-01-01 21:38:45,951 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 717, '_0n1': 368}

2018-01-01 21:38:45,951 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,955 : INFO : < 200 OK [3330]
2018-01-01 21:38:45,959 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1183, '_0n1': 352}
2018-01-01 21:38:45,959 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,967 : INFO : < 200 OK [3325]
2018-01-01 21:38:45,967 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1108, '_0n1': 369}
2018-01-01 21:38:45,971 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,975 : INFO : < 200 OK [3372]
2018-01-01 21:38:45,979 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 841, '_0n1': 353}
2018-01-01 21:38:45,979 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,983 : INFO : < 200 OK [3271]
2018-01-01 21:38:45,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1131, '_0n1': 353}
2018-01-01 21:38:45,987 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:45,991 : INFO : < 200 OK [3277]
2018-01-01 21:38:45,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 717, '_0n1': 370}
2018-01-01 21:38:45,995 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:45,999 : INFO : < 200 OK [3309]
2018-01-01 21:38:46,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 900, '_0n1': 354}
2018-01-01 21:38:46,003 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,007 : INFO : < 200 OK [3300]
2018-01-01 21:38:46,011 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 839, '_0n1': 371}
2018-01-01 21:38:46,011 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,015 : INFO : < 200 OK [3265]
2018-01-01 21:38:46,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1134, '_0n1': 371}
2018-01-01 21:38:46,021 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,026 : INFO : < 200 OK [3284]
2018-01-01 21:38:46,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 355}
2018-01-01 21:38:46,031 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,035 : INFO : < 200 OK [3275]
2018-01-01 21:38:46,039 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1057, '_0n1': 372}
2018-01-01 21:38:46,043 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,047 : INFO : < 200 OK [3299]
2018-01-01 21:38:46,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1014, '_0n1': 356}
2018-01-01 21:38:46,051 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,055 : INFO : < 200 OK [3277]
2018-01-01 21:38:46,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1187, '_0n1': 373}
2018-01-01 21:38:46,063 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,067 : INFO : < 200 OK [3350]
2018-01-01 21:38:46,071 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 753, '_0n1': 357}
2018-01-01 21:38:46,071 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,075 : INFO : < 200 OK [3336]
2018-01-01 21:38:46,079 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1037, '_0n1': 357}
2018-01-01 21:38:46,079 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,083 : INFO : < 200 OK [3346]
2018-01-01 21:38:46,087 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 738, '_0n1': 374}
2018-01-01 21:38:46,087 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,091 : INFO : < 200 OK [3267]
2018-01-01 21:38:46,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 932, '_0n1': 374}
2018-01-01 21:38:46,095 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,099 : INFO : < 200 OK [3265]
2018-01-01 21:38:46,103 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 836, '_0n1': 374}
2018-01-01 21:38:46,103 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,111 : INFO : < 200 OK [3263]
2018-01-01 21:38:46,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 837, '_0n1': 374}
2018-01-01 21:38:46,115 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,121 : INFO : < 200 OK [3274]
2018-01-01 21:38:46,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 782, '_0n1': 358}
2018-01-01 21:38:46,127 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,132 : INFO : < 200 OK [3251]
2018-01-01 21:38:46,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 782, '_0n1': 375}
2018-01-01 21:38:46,135 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,143 : INFO : < 200 OK [3301]
2018-01-01 21:38:46,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 737, '_0n1': 375}
2018-01-01 21:38:46,147 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,151 : INFO : < 200 OK [3335]
2018-01-01 21:38:46,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1048, '_0n1': 375}
2018-01-01 21:38:46,155 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,163 : INFO : < 200 OK [3350]
2018-01-01 21:38:46,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 758, '_0n1': 359}
2018-01-01 21:38:46,167 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,171 : INFO : < 200 OK [3277]
2018-01-01 21:38:46,175 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 872, '_0n1': 376}
2018-01-01 21:38:46,175 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,179 : INFO : < 200 OK [3298]
2018-01-01 21:38:46,183 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 982, '_0n1': 376}

2018-01-01 21:38:46,183 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,187 : INFO : < 200 OK [3299]
2018-01-01 21:38:46,191 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 745, '_0n1': 376}
2018-01-01 21:38:46,195 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,199 : INFO : < 200 OK [3299]
2018-01-01 21:38:46,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 722, '_0n1': 376}
2018-01-01 21:38:46,203 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,207 : INFO : < 200 OK [3303]
2018-01-01 21:38:46,211 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 920, '_0n1': 376}
2018-01-01 21:38:46,211 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,215 : INFO : < 200 OK [3297]
2018-01-01 21:38:46,219 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 987, '_0n1': 380}
2018-01-01 21:38:46,222 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,226 : INFO : < 200 OK [3292]
2018-01-01 21:38:46,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1060, '_0n1': 380}
2018-01-01 21:38:46,232 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,235 : INFO : < 200 OK [3301]
2018-01-01 21:38:46,235 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1094, '_0n1': 377}
2018-01-01 21:38:46,239 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,243 : INFO : < 200 OK [3346]
2018-01-01 21:38:46,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1052, '_0n1': 377}
2018-01-01 21:38:46,247 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,251 : INFO : < 200 OK [3349]
2018-01-01 21:38:46,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 816, '_0n1': 377}
2018-01-01 21:38:46,255 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,259 : INFO : < 200 OK [3333]
2018-01-01 21:38:46,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1179, '_0n1': 377}
2018-01-01 21:38:46,263 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,267 : INFO : < 200 OK [3347]
2018-01-01 21:38:46,271 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1073, '_0n1': 377}
2018-01-01 21:38:46,271 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,275 : INFO : < 200 OK [3350]
2018-01-01 21:38:46,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1201, '_0n1': 381}
2018-01-01 21:38:46,283 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,287 : INFO : < 200 OK [3325]
2018-01-01 21:38:46,291 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 799, '_0n1': 381}
2018-01-01 21:38:46,295 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,299 : INFO : < 200 OK [3309]
2018-01-01 21:38:46,303 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 378}
2018-01-01 21:38:46,303 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,307 : INFO : < 200 OK [3266]
2018-01-01 21:38:46,311 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 378}
2018-01-01 21:38:46,311 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,315 : INFO : < 200 OK [3270]
2018-01-01 21:38:46,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 378}
2018-01-01 21:38:46,322 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,327 : INFO : < 200 OK [3268]
2018-01-01 21:38:46,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 743, '_0n1': 382}
2018-01-01 21:38:46,333 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,334 : INFO : < 200 OK [3297]
2018-01-01 21:38:46,339 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 939, '_0n1': 382}
2018-01-01 21:38:46,339 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,343 : INFO : < 200 OK [3298]
2018-01-01 21:38:46,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 987, '_0n1': 379}
2018-01-01 21:38:46,347 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,355 : INFO : < 200 OK [3273]
2018-01-01 21:38:46,355 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1060, '_0n1': 379}
2018-01-01 21:38:46,359 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,363 : INFO : < 200 OK [3282]
2018-01-01 21:38:46,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1126, '_0n1': 383}
2018-01-01 21:38:46,367 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,371 : INFO : < 200 OK [3298]
2018-01-01 21:38:46,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 383}
2018-01-01 21:38:46,375 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,379 : INFO : < 200 OK [3287]
2018-01-01 21:38:46,379 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 383}
2018-01-01 21:38:46,383 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,387 : INFO : < 200 OK [3289]
2018-01-01 21:38:46,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 383}
2018-01-01 21:38:46,391 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,395 : INFO : < 200 OK [3291]
2018-01-01 21:38:46,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1027, '_0n1': 400}
2018-01-01 21:38:46,399 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,403 : INFO : < 200 OK [3332]
2018-01-01 21:38:46,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 959, '_0n1': 400}

2018-01-01 21:38:46,407 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,411 : INFO : < 200 OK [3329]
2018-01-01 21:38:46,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1118, '_0n1': 384}
2018-01-01 21:38:46,415 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,423 : INFO : < 200 OK [3311]
2018-01-01 21:38:46,427 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1060, '_0n1': 401}
2018-01-01 21:38:46,430 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,435 : INFO : < 200 OK [3290]
2018-01-01 21:38:46,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 987, '_0n1': 401}
2018-01-01 21:38:46,439 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,443 : INFO : < 200 OK [3281]
2018-01-01 21:38:46,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 385}
2018-01-01 21:38:46,447 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,451 : INFO : < 200 OK [3359]
2018-01-01 21:38:46,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1163, '_0n1': 402}
2018-01-01 21:38:46,455 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,463 : INFO : < 200 OK [3281]
2018-01-01 21:38:46,463 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1046, '_0n1': 402}
2018-01-01 21:38:46,467 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,471 : INFO : < 200 OK [3285]
2018-01-01 21:38:46,471 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 811, '_0n1': 386}
2018-01-01 21:38:46,475 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,479 : INFO : < 200 OK [3266]
2018-01-01 21:38:46,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 403}
2018-01-01 21:38:46,483 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,487 : INFO : < 200 OK [3363]
2018-01-01 21:38:46,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1120, '_0n1': 387}
2018-01-01 21:38:46,491 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,495 : INFO : < 200 OK [3362]
2018-01-01 21:38:46,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 925, '_0n1': 387}
2018-01-01 21:38:46,499 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,503 : INFO : < 200 OK [3350]
2018-01-01 21:38:46,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 811, '_0n1': 404}
2018-01-01 21:38:46,507 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,515 : INFO : < 200 OK [3274]
2018-01-01 21:38:46,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 388}
2018-01-01 21:38:46,521 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,525 : INFO : < 200 OK [3368]
2018-01-01 21:38:46,528 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 854, '_0n1': 405}
2018-01-01 21:38:46,530 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,535 : INFO : < 200 OK [3323]
2018-01-01 21:38:46,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 988, '_0n1': 405}
2018-01-01 21:38:46,539 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,547 : INFO : < 200 OK [3319]
2018-01-01 21:38:46,551 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 787, '_0n1': 405}
2018-01-01 21:38:46,555 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,559 : INFO : < 200 OK [3314]
2018-01-01 21:38:46,559 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1087, '_0n1': 405}
2018-01-01 21:38:46,563 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,567 : INFO : < 200 OK [3332]
2018-01-01 21:38:46,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 981, '_0n1': 405}
2018-01-01 21:38:46,571 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,575 : INFO : < 200 OK [3316]
2018-01-01 21:38:46,579 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 819, '_0n1': 405}
2018-01-01 21:38:46,579 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,583 : INFO : < 200 OK [3316]
2018-01-01 21:38:46,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 985, '_0n1': 389}
2018-01-01 21:38:46,587 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,591 : INFO : < 200 OK [3297]
2018-01-01 21:38:46,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 839, '_0n1': 406}
2018-01-01 21:38:46,595 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,599 : INFO : < 200 OK [3268]
2018-01-01 21:38:46,603 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1134, '_0n1': 406}
2018-01-01 21:38:46,603 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,607 : INFO : < 200 OK [3287]
2018-01-01 21:38:46,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 925, '_0n1': 390}
2018-01-01 21:38:46,611 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,615 : INFO : < 200 OK [3289]
2018-01-01 21:38:46,619 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1120, '_0n1': 390}
2018-01-01 21:38:46,621 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,625 : INFO : < 200 OK [3301]
2018-01-01 21:38:46,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 979, '_0n1': 407}
2018-01-01 21:38:46,629 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,633 : INFO : < 200 OK [3296]
2018-01-01 21:38:46,635 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1120, '_0n1': 391}

2018-01-01 21:38:46,635 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,639 : INFO : < 200 OK [3297]
2018-01-01 21:38:46,643 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 925, '_0n1': 391}
2018-01-01 21:38:46,643 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,651 : INFO : < 200 OK [3285]
2018-01-01 21:38:46,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 925, '_0n1': 408}
2018-01-01 21:38:46,655 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,659 : INFO : < 200 OK [3289]
2018-01-01 21:38:46,663 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1120, '_0n1': 408}
2018-01-01 21:38:46,663 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,671 : INFO : < 200 OK [3301]
2018-01-01 21:38:46,671 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 392}
2018-01-01 21:38:46,675 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,679 : INFO : < 200 OK [3261]
2018-01-01 21:38:46,679 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 392}
2018-01-01 21:38:46,683 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,687 : INFO : < 200 OK [3265]
2018-01-01 21:38:46,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 392}
2018-01-01 21:38:46,691 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,699 : INFO : < 200 OK [3263]
2018-01-01 21:38:46,699 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1114, '_0n1': 409}
2018-01-01 21:38:46,703 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,707 : INFO : < 200 OK [3300]
2018-01-01 21:38:46,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 979, '_0n1': 393}
2018-01-01 21:38:46,711 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,715 : INFO : < 200 OK [3304]
2018-01-01 21:38:46,715 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1114, '_0n1': 410}
2018-01-01 21:38:46,720 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,724 : INFO : < 200 OK [3318]
2018-01-01 21:38:46,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 979, '_0n1': 394}
2018-01-01 21:38:46,728 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,732 : INFO : < 200 OK [3292]
2018-01-01 21:38:46,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 979, '_0n1': 411}
2018-01-01 21:38:46,734 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,738 : INFO : < 200 OK [3296]
2018-01-01 21:38:46,738 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 986, '_0n1': 395}
2018-01-01 21:38:46,742 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,746 : INFO : < 200 OK [3299]
2018-01-01 21:38:46,750 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1028, '_0n1': 412}
2018-01-01 21:38:46,750 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,758 : INFO : < 200 OK [3307]
2018-01-01 21:38:46,762 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1190, '_0n1': 396}
2018-01-01 21:38:46,766 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,771 : INFO : < 200 OK [3320]
2018-01-01 21:38:46,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 975, '_0n1': 413}
2018-01-01 21:38:46,774 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,778 : INFO : < 200 OK [3306]
2018-01-01 21:38:46,782 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1087, '_0n1': 397}
2018-01-01 21:38:46,782 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,786 : INFO : < 200 OK [3294]
2018-01-01 21:38:46,790 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 817, '_0n1': 397}
2018-01-01 21:38:46,794 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,818 : INFO : < 200 OK [3281]
2018-01-01 21:38:46,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 925, '_0n1': 414}
2018-01-01 21:38:46,827 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,832 : INFO : < 200 OK [3248]
2018-01-01 21:38:46,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1120, '_0n1': 414}
2018-01-01 21:38:46,835 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,839 : INFO : < 200 OK [3260]
2018-01-01 21:38:46,843 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 862, '_0n1': 398}
2018-01-01 21:38:46,843 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,847 : INFO : < 200 OK [3315]
2018-01-01 21:38:46,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 415}
2018-01-01 21:38:46,851 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,855 : INFO : < 200 OK [3265]
2018-01-01 21:38:46,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 399}
2018-01-01 21:38:46,859 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,863 : INFO : < 200 OK [3270]
2018-01-01 21:38:46,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 399}
2018-01-01 21:38:46,867 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,871 : INFO : < 200 OK [3272]
2018-01-01 21:38:46,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 399}
2018-01-01 21:38:46,875 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,883 : INFO : < 200 OK [3274]
2018-01-01 21:38:46,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 729, '_0n1': 416}

2018-01-01 21:38:46,887 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,895 : INFO : < 200 OK [3295]
2018-01-01 21:38:46,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1046, '_0n1': 420}
2018-01-01 21:38:46,899 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,903 : INFO : < 200 OK [3279]
2018-01-01 21:38:46,907 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1122, '_0n1': 420}
2018-01-01 21:38:46,907 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,911 : INFO : < 200 OK [3279]
2018-01-01 21:38:46,915 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1189, '_0n1': 417}
2018-01-01 21:38:46,915 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,924 : INFO : < 200 OK [3330]
2018-01-01 21:38:46,927 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 721, '_0n1': 421}
2018-01-01 21:38:46,929 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,933 : INFO : < 200 OK [3308]
2018-01-01 21:38:46,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 418}
2018-01-01 21:38:46,935 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,939 : INFO : < 200 OK [3270]
2018-01-01 21:38:46,943 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 729, '_0n1': 422}
2018-01-01 21:38:46,943 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,947 : INFO : < 200 OK [3295]
2018-01-01 21:38:46,951 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 419}
2018-01-01 21:38:46,951 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,955 : INFO : < 200 OK [3306]
2018-01-01 21:38:46,959 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1191, '_0n1': 419}
2018-01-01 21:38:46,959 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:46,963 : INFO : < 200 OK [3318]
2018-01-01 21:38:46,967 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 888, '_0n1': 423}
2018-01-01 21:38:46,967 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,971 : INFO : < 200 OK [3287]
2018-01-01 21:38:46,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 929, '_0n1': 423}
2018-01-01 21:38:46,975 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,979 : INFO : < 200 OK [3292]
2018-01-01 21:38:46,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 888, '_0n1': 440}
2018-01-01 21:38:46,987 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:46,991 : INFO : < 200 OK [3280]
2018-01-01 21:38:46,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 929, '_0n1': 440}
2018-01-01 21:38:46,995 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,003 : INFO : < 200 OK [3285]
2018-01-01 21:38:47,007 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1113, '_0n1': 424}
2018-01-01 21:38:47,007 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,011 : INFO : < 200 OK [3325]
2018-01-01 21:38:47,015 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 441}
2018-01-01 21:38:47,015 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,022 : INFO : < 200 OK [3296]
2018-01-01 21:38:47,024 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 441}
2018-01-01 21:38:47,026 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,031 : INFO : < 200 OK [3309]
2018-01-01 21:38:47,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1078, '_0n1': 425}
2018-01-01 21:38:47,035 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,035 : INFO : < 200 OK [3294]
2018-01-01 21:38:47,039 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 750, '_0n1': 442}
2018-01-01 21:38:47,043 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,047 : INFO : < 200 OK [3279]
2018-01-01 21:38:47,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1148, '_0n1': 426}
2018-01-01 21:38:47,051 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,055 : INFO : < 200 OK [3246]
2018-01-01 21:38:47,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 876, '_0n1': 426}
2018-01-01 21:38:47,059 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,067 : INFO : < 200 OK [3230]
2018-01-01 21:38:47,071 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1068, '_0n1': 426}
2018-01-01 21:38:47,071 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,075 : INFO : < 200 OK [3247]
2018-01-01 21:38:47,079 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 698, '_0n1': 426}
2018-01-01 21:38:47,083 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,087 : INFO : < 200 OK [3229]
2018-01-01 21:38:47,091 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 817, '_0n1': 443}
2018-01-01 21:38:47,091 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,095 : INFO : < 200 OK [3325]
2018-01-01 21:38:47,099 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1087, '_0n1': 443}
2018-01-01 21:38:47,099 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,103 : INFO : < 200 OK [3338]
2018-01-01 21:38:47,107 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 787, '_0n1': 443}
2018-01-01 21:38:47,111 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,115 : INFO : < 200 OK [3320]
2018-01-01 21:38:47,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 697, '_0n1': 443}

2018-01-01 21:38:47,122 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,126 : INFO : < 200 OK [3325]
2018-01-01 21:38:47,128 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 929, '_0n1': 427}
2018-01-01 21:38:47,131 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,135 : INFO : < 200 OK [3275]
2018-01-01 21:38:47,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 888, '_0n1': 427}
2018-01-01 21:38:47,139 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,143 : INFO : < 200 OK [3270]
2018-01-01 21:38:47,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 444}
2018-01-01 21:38:47,147 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,151 : INFO : < 200 OK [3309]
2018-01-01 21:38:47,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 888, '_0n1': 428}
2018-01-01 21:38:47,155 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,163 : INFO : < 200 OK [3266]
2018-01-01 21:38:47,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 929, '_0n1': 428}
2018-01-01 21:38:47,167 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,171 : INFO : < 200 OK [3271]
2018-01-01 21:38:47,171 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 729, '_0n1': 445}
2018-01-01 21:38:47,175 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,179 : INFO : < 200 OK [3306]
2018-01-01 21:38:47,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 889, '_0n1': 429}
2018-01-01 21:38:47,183 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,187 : INFO : < 200 OK [3316]
2018-01-01 21:38:47,187 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1169, '_0n1': 429}
2018-01-01 21:38:47,191 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,195 : INFO : < 200 OK [3326]
2018-01-01 21:38:47,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 729, '_0n1': 446}
2018-01-01 21:38:47,199 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,203 : INFO : < 200 OK [3316]
2018-01-01 21:38:47,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 918, '_0n1': 430}
2018-01-01 21:38:47,207 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,215 : INFO : < 200 OK [3293]
2018-01-01 21:38:47,219 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1180, '_0n1': 447}
2018-01-01 21:38:47,221 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,227 : INFO : < 200 OK [3328]
2018-01-01 21:38:47,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 971, '_0n1': 431}
2018-01-01 21:38:47,233 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,239 : INFO : < 200 OK [3255]
2018-01-01 21:38:47,239 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1030, '_0n1': 431}
2018-01-01 21:38:47,243 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,247 : INFO : < 200 OK [3271]
2018-01-01 21:38:47,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 741, '_0n1': 431}
2018-01-01 21:38:47,251 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,255 : INFO : < 200 OK [3254]
2018-01-01 21:38:47,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1085, '_0n1': 448}
2018-01-01 21:38:47,259 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,263 : INFO : < 200 OK [3286]
2018-01-01 21:38:47,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 859, '_0n1': 432}
2018-01-01 21:38:47,267 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,271 : INFO : < 200 OK [3279]
2018-01-01 21:38:47,271 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1153, '_0n1': 449}
2018-01-01 21:38:47,275 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,279 : INFO : < 200 OK [3291]
2018-01-01 21:38:47,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1046, '_0n1': 433}
2018-01-01 21:38:47,283 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,287 : INFO : < 200 OK [3295]
2018-01-01 21:38:47,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1122, '_0n1': 433}
2018-01-01 21:38:47,291 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,295 : INFO : < 200 OK [3295]
2018-01-01 21:38:47,303 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 721, '_0n1': 450}
2018-01-01 21:38:47,303 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,311 : INFO : < 200 OK [3316]
2018-01-01 21:38:47,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 777, '_0n1': 434}
2018-01-01 21:38:47,315 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,319 : INFO : < 200 OK [3228]
2018-01-01 21:38:47,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 834, '_0n1': 434}
2018-01-01 21:38:47,329 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,333 : INFO : < 200 OK [3229]
2018-01-01 21:38:47,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 893, '_0n1': 434}
2018-01-01 21:38:47,335 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,339 : INFO : < 200 OK [3232]
2018-01-01 21:38:47,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 733, '_0n1': 451}
2018-01-01 21:38:47,347 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,351 : INFO : < 200 OK [3242]
2018-01-01 21:38:47,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 916, '_0n1': 451}

2018-01-01 21:38:47,355 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,359 : INFO : < 200 OK [3233]
2018-01-01 21:38:47,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 899, '_0n1': 451}
2018-01-01 21:38:47,363 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,367 : INFO : < 200 OK [3230]
2018-01-01 21:38:47,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 721, '_0n1': 435}
2018-01-01 21:38:47,371 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,375 : INFO : < 200 OK [3285]
2018-01-01 21:38:47,379 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1046, '_0n1': 452}
2018-01-01 21:38:47,379 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,383 : INFO : < 200 OK [3319]
2018-01-01 21:38:47,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1122, '_0n1': 452}
2018-01-01 21:38:47,387 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,391 : INFO : < 200 OK [3319]
2018-01-01 21:38:47,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1162, '_0n1': 436}
2018-01-01 21:38:47,395 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,399 : INFO : < 200 OK [3306]
2018-01-01 21:38:47,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 852, '_0n1': 453}
2018-01-01 21:38:47,403 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,407 : INFO : < 200 OK [3338]
2018-01-01 21:38:47,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1026, '_0n1': 453}
2018-01-01 21:38:47,411 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,415 : INFO : < 200 OK [3347]
2018-01-01 21:38:47,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 988, '_0n1': 453}
2018-01-01 21:38:47,419 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,427 : INFO : < 200 OK [3333]
2018-01-01 21:38:47,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1087, '_0n1': 453}
2018-01-01 21:38:47,432 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,436 : INFO : < 200 OK [3346]
2018-01-01 21:38:47,440 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 437}
2018-01-01 21:38:47,440 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,444 : INFO : < 200 OK [3262]
2018-01-01 21:38:47,448 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 437}
2018-01-01 21:38:47,448 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,456 : INFO : < 200 OK [3264]
2018-01-01 21:38:47,456 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 437}
2018-01-01 21:38:47,460 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,464 : INFO : < 200 OK [3266]
2018-01-01 21:38:47,468 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 721, '_0n1': 454}
2018-01-01 21:38:47,468 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,472 : INFO : < 200 OK [3317]
2018-01-01 21:38:47,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 943, '_0n1': 438}
2018-01-01 21:38:47,480 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,484 : INFO : < 200 OK [3323]
2018-01-01 21:38:47,488 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 747, '_0n1': 455}
2018-01-01 21:38:47,488 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,492 : INFO : < 200 OK [3260]
2018-01-01 21:38:47,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1160, '_0n1': 455}
2018-01-01 21:38:47,500 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,504 : INFO : < 200 OK [3282]
2018-01-01 21:38:47,508 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1133, '_0n1': 439}
2018-01-01 21:38:47,508 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,512 : INFO : < 200 OK [3325]
2018-01-01 21:38:47,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1091, '_0n1': 439}
2018-01-01 21:38:47,516 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,521 : INFO : < 200 OK [3323]
2018-01-01 21:38:47,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 456}
2018-01-01 21:38:47,525 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,531 : INFO : < 200 OK [3292]
2018-01-01 21:38:47,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 456}
2018-01-01 21:38:47,536 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,540 : INFO : < 200 OK [3305]
2018-01-01 21:38:47,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 916, '_0n1': 460}
2018-01-01 21:38:47,544 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,548 : INFO : < 200 OK [3265]
2018-01-01 21:38:47,556 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 733, '_0n1': 460}
2018-01-01 21:38:47,560 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,564 : INFO : < 200 OK [3274]
2018-01-01 21:38:47,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 457}
2018-01-01 21:38:47,568 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,572 : INFO : < 200 OK [3287]
2018-01-01 21:38:47,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 457}
2018-01-01 21:38:47,576 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,584 : INFO : < 200 OK [3300]
2018-01-01 21:38:47,584 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1122, '_0n1': 461}

2018-01-01 21:38:47,588 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,592 : INFO : < 200 OK [3283]
2018-01-01 21:38:47,596 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 968, '_0n1': 458}
2018-01-01 21:38:47,596 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,600 : INFO : < 200 OK [3284]
2018-01-01 21:38:47,604 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1169, '_0n1': 462}
2018-01-01 21:38:47,604 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,608 : INFO : < 200 OK [3323]
2018-01-01 21:38:47,612 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 718, '_0n1': 462}
2018-01-01 21:38:47,612 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,616 : INFO : < 200 OK [3308]
2018-01-01 21:38:47,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 855, '_0n1': 459}
2018-01-01 21:38:47,623 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,626 : INFO : < 200 OK [3317]
2018-01-01 21:38:47,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 775, '_0n1': 463}
2018-01-01 21:38:47,631 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,635 : INFO : < 200 OK [3285]
2018-01-01 21:38:47,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 480}
2018-01-01 21:38:47,636 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,640 : INFO : < 200 OK [3299]
2018-01-01 21:38:47,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1191, '_0n1': 480}
2018-01-01 21:38:47,644 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,648 : INFO : < 200 OK [3311]
2018-01-01 21:38:47,652 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1171, '_0n1': 464}
2018-01-01 21:38:47,652 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,656 : INFO : < 200 OK [3329]
2018-01-01 21:38:47,660 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 481}
2018-01-01 21:38:47,660 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,664 : INFO : < 200 OK [3268]
2018-01-01 21:38:47,668 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 481}
2018-01-01 21:38:47,668 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,672 : INFO : < 200 OK [3270]
2018-01-01 21:38:47,676 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 481}
2018-01-01 21:38:47,676 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,680 : INFO : < 200 OK [3272]
2018-01-01 21:38:47,684 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1134, '_0n1': 465}
2018-01-01 21:38:47,684 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,688 : INFO : < 200 OK [3286]
2018-01-01 21:38:47,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 482}
2018-01-01 21:38:47,692 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,696 : INFO : < 200 OK [3267]
2018-01-01 21:38:47,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 482}
2018-01-01 21:38:47,704 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,708 : INFO : < 200 OK [3265]
2018-01-01 21:38:47,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 482}
2018-01-01 21:38:47,712 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,724 : INFO : < 200 OK [3269]
2018-01-01 21:38:47,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1061, '_0n1': 466}
2018-01-01 21:38:47,729 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,734 : INFO : < 200 OK [3305]
2018-01-01 21:38:47,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 954, '_0n1': 466}
2018-01-01 21:38:47,736 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,740 : INFO : < 200 OK [3289]
2018-01-01 21:38:47,744 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 952, '_0n1': 466}
2018-01-01 21:38:47,744 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,752 : INFO : < 200 OK [3287]
2018-01-01 21:38:47,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 483}
2018-01-01 21:38:47,756 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,760 : INFO : < 200 OK [3294]
2018-01-01 21:38:47,764 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 483}
2018-01-01 21:38:47,764 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,768 : INFO : < 200 OK [3307]
2018-01-01 21:38:47,772 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 889, '_0n1': 467}
2018-01-01 21:38:47,772 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,776 : INFO : < 200 OK [3303]
2018-01-01 21:38:47,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 906, '_0n1': 484}
2018-01-01 21:38:47,780 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,784 : INFO : < 200 OK [3301]
2018-01-01 21:38:47,788 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 856, '_0n1': 468}
2018-01-01 21:38:47,788 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,796 : INFO : < 200 OK [3270]
2018-01-01 21:38:47,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 976, '_0n1': 468}
2018-01-01 21:38:47,800 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,804 : INFO : < 200 OK [3275]
2018-01-01 21:38:47,808 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1078, '_0n1': 485}

2018-01-01 21:38:47,808 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,812 : INFO : < 200 OK [3341]
2018-01-01 21:38:47,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1169, '_0n1': 469}
2018-01-01 21:38:47,816 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,823 : INFO : < 200 OK [3333]
2018-01-01 21:38:47,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 718, '_0n1': 469}
2018-01-01 21:38:47,827 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,831 : INFO : < 200 OK [3318]
2018-01-01 21:38:47,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 994, '_0n1': 486}
2018-01-01 21:38:47,836 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,840 : INFO : < 200 OK [3267]
2018-01-01 21:38:47,840 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 470}
2018-01-01 21:38:47,844 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,848 : INFO : < 200 OK [3356]
2018-01-01 21:38:47,852 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 994, '_0n1': 500}
2018-01-01 21:38:47,852 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,856 : INFO : < 200 OK [3268]
2018-01-01 21:38:47,860 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1124, '_0n1': 471}
2018-01-01 21:38:47,864 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,868 : INFO : < 200 OK [3306]
2018-01-01 21:38:47,872 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 933, '_0n1': 471}
2018-01-01 21:38:47,872 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,876 : INFO : < 200 OK [3292]
2018-01-01 21:38:47,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1182, '_0n1': 501}
2018-01-01 21:38:47,880 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,884 : INFO : < 200 OK [3317]
2018-01-01 21:38:47,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1045, '_0n1': 472}
2018-01-01 21:38:47,892 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,896 : INFO : < 200 OK [3287]
2018-01-01 21:38:47,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 972, '_0n1': 472}
2018-01-01 21:38:47,900 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,904 : INFO : < 200 OK [3255]
2018-01-01 21:38:47,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1129, '_0n1': 502}
2018-01-01 21:38:47,908 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,912 : INFO : < 200 OK [3280]
2018-01-01 21:38:47,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 775, '_0n1': 473}
2018-01-01 21:38:47,916 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,924 : INFO : < 200 OK [3285]
2018-01-01 21:38:47,929 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1101, '_0n1': 503}
2018-01-01 21:38:47,932 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,936 : INFO : < 200 OK [3291]
2018-01-01 21:38:47,940 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 924, '_0n1': 503}
2018-01-01 21:38:47,940 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,948 : INFO : < 200 OK [3277]
2018-01-01 21:38:47,952 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 742, '_0n1': 474}
2018-01-01 21:38:47,956 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,960 : INFO : < 200 OK [3313]
2018-01-01 21:38:47,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 791, '_0n1': 504}
2018-01-01 21:38:47,964 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,968 : INFO : < 200 OK [3269]
2018-01-01 21:38:47,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1078, '_0n1': 475}
2018-01-01 21:38:47,972 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,976 : INFO : < 200 OK [3294]
2018-01-01 21:38:47,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1089, '_0n1': 505}
2018-01-01 21:38:47,984 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:47,988 : INFO : < 200 OK [3316]
2018-01-01 21:38:47,992 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 783, '_0n1': 476}
2018-01-01 21:38:47,992 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:47,996 : INFO : < 200 OK [3283]
2018-01-01 21:38:48,000 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1116, '_0n1': 506}
2018-01-01 21:38:48,000 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,008 : INFO : < 200 OK [3292]
2018-01-01 21:38:48,008 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1130, '_0n1': 477}
2018-01-01 21:38:48,012 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,016 : INFO : < 200 OK [3311]
2018-01-01 21:38:48,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 823, '_0n1': 507}
2018-01-01 21:38:48,022 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,026 : INFO : < 200 OK [3326]
2018-01-01 21:38:48,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1078, '_0n1': 478}
2018-01-01 21:38:48,031 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,035 : INFO : < 200 OK [3332]
2018-01-01 21:38:48,036 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 813, '_0n1': 508}
2018-01-01 21:38:48,036 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,040 : INFO : < 200 OK [3314]
2018-01-01 21:38:48,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1143, '_0n1': 508}

2018-01-01 21:38:48,048 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,052 : INFO : < 200 OK [3329]
2018-01-01 21:38:48,056 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1138, '_0n1': 508}
2018-01-01 21:38:48,056 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,060 : INFO : < 200 OK [3326]
2018-01-01 21:38:48,064 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 898, '_0n1': 479}
2018-01-01 21:38:48,064 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,068 : INFO : < 200 OK [3312]
2018-01-01 21:38:48,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1021, '_0n1': 509}
2018-01-01 21:38:48,072 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,076 : INFO : < 200 OK [3337]
2018-01-01 21:38:48,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 846, '_0n1': 509}
2018-01-01 21:38:48,080 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,084 : INFO : < 200 OK [3315]
2018-01-01 21:38:48,088 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 513}
2018-01-01 21:38:48,092 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,096 : INFO : < 200 OK [3310]
2018-01-01 21:38:48,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1191, '_0n1': 513}
2018-01-01 21:38:48,100 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,108 : INFO : < 200 OK [3322]
2018-01-01 21:38:48,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 839, '_0n1': 510}
2018-01-01 21:38:48,112 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,116 : INFO : < 200 OK [3253]
2018-01-01 21:38:48,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1134, '_0n1': 510}
2018-01-01 21:38:48,123 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,127 : INFO : < 200 OK [3272]
2018-01-01 21:38:48,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 825, '_0n1': 514}
2018-01-01 21:38:48,132 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,136 : INFO : < 200 OK [3288]
2018-01-01 21:38:48,140 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 936, '_0n1': 511}
2018-01-01 21:38:48,140 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,144 : INFO : < 200 OK [3303]
2018-01-01 21:38:48,148 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1035, '_0n1': 515}
2018-01-01 21:38:48,148 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,156 : INFO : < 200 OK [3290]
2018-01-01 21:38:48,160 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 720, '_0n1': 512}
2018-01-01 21:38:48,160 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,164 : INFO : < 200 OK [3273]
2018-01-01 21:38:48,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1074, '_0n1': 512}
2018-01-01 21:38:48,168 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,172 : INFO : < 200 OK [3288]
2018-01-01 21:38:48,176 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 516}
2018-01-01 21:38:48,176 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,180 : INFO : < 200 OK [3296]
2018-01-01 21:38:48,184 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1191, '_0n1': 516}
2018-01-01 21:38:48,188 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,192 : INFO : < 200 OK [3308]
2018-01-01 21:38:48,196 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 913, '_0n1': 533}
2018-01-01 21:38:48,196 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,200 : INFO : < 200 OK [3288]
2018-01-01 21:38:48,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 727, '_0n1': 533}
2018-01-01 21:38:48,204 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,208 : INFO : < 200 OK [3287]
2018-01-01 21:38:48,212 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1023, '_0n1': 517}
2018-01-01 21:38:48,212 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,216 : INFO : < 200 OK [3302]
2018-01-01 21:38:48,223 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1202, '_0n1': 517}
2018-01-01 21:38:48,224 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,229 : INFO : < 200 OK [3301]
2018-01-01 21:38:48,232 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1085, '_0n1': 534}
2018-01-01 21:38:48,236 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,240 : INFO : < 200 OK [3303]
2018-01-01 21:38:48,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 807, '_0n1': 518}
2018-01-01 21:38:48,244 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,248 : INFO : < 200 OK [3270]
2018-01-01 21:38:48,252 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 723, '_0n1': 518}
2018-01-01 21:38:48,252 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,256 : INFO : < 200 OK [3274]
2018-01-01 21:38:48,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1033, '_0n1': 535}
2018-01-01 21:38:48,264 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,268 : INFO : < 200 OK [3303]
2018-01-01 21:38:48,272 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 802, '_0n1': 519}
2018-01-01 21:38:48,272 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,280 : INFO : < 200 OK [3299]
2018-01-01 21:38:48,280 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1149, '_0n1': 536}

2018-01-01 21:38:48,284 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,288 : INFO : < 200 OK [3303]
2018-01-01 21:38:48,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1024, '_0n1': 520}
2018-01-01 21:38:48,292 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,296 : INFO : < 200 OK [3317]
2018-01-01 21:38:48,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1045, '_0n1': 537}
2018-01-01 21:38:48,300 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,304 : INFO : < 200 OK [3287]
2018-01-01 21:38:48,308 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 972, '_0n1': 537}
2018-01-01 21:38:48,312 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,316 : INFO : < 200 OK [3255]
2018-01-01 21:38:48,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1116, '_0n1': 521}
2018-01-01 21:38:48,323 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,327 : INFO : < 200 OK [3294]
2018-01-01 21:38:48,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 791, '_0n1': 521}
2018-01-01 21:38:48,333 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,336 : INFO : < 200 OK [3275]
2018-01-01 21:38:48,340 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 968, '_0n1': 521}
2018-01-01 21:38:48,340 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,344 : INFO : < 200 OK [3281]
2018-01-01 21:38:48,348 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 865, '_0n1': 538}
2018-01-01 21:38:48,348 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,352 : INFO : < 200 OK [3304]
2018-01-01 21:38:48,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 997, '_0n1': 522}
2018-01-01 21:38:48,360 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,364 : INFO : < 200 OK [3274]
2018-01-01 21:38:48,364 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 775, '_0n1': 539}
2018-01-01 21:38:48,368 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,372 : INFO : < 200 OK [3269]
2018-01-01 21:38:48,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1067, '_0n1': 523}
2018-01-01 21:38:48,376 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,380 : INFO : < 200 OK [3332]
2018-01-01 21:38:48,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 783, '_0n1': 540}
2018-01-01 21:38:48,388 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,392 : INFO : < 200 OK [3264]
2018-01-01 21:38:48,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 917, '_0n1': 524}
2018-01-01 21:38:48,400 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,404 : INFO : < 200 OK [3297]
2018-01-01 21:38:48,408 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1078, '_0n1': 541}
2018-01-01 21:38:48,408 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,412 : INFO : < 200 OK [3294]
2018-01-01 21:38:48,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 817, '_0n1': 525}
2018-01-01 21:38:48,420 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,424 : INFO : < 200 OK [3288]
2018-01-01 21:38:48,428 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 988, '_0n1': 525}
2018-01-01 21:38:48,430 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,434 : INFO : < 200 OK [3288]
2018-01-01 21:38:48,436 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 787, '_0n1': 525}
2018-01-01 21:38:48,436 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,440 : INFO : < 200 OK [3283]
2018-01-01 21:38:48,444 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1087, '_0n1': 525}
2018-01-01 21:38:48,444 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,448 : INFO : < 200 OK [3301]
2018-01-01 21:38:48,452 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 997, '_0n1': 542}
2018-01-01 21:38:48,452 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,456 : INFO : < 200 OK [3285]
2018-01-01 21:38:48,460 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 966, '_0n1': 526}
2018-01-01 21:38:48,464 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,468 : INFO : < 200 OK [3351]
2018-01-01 21:38:48,468 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 543}
2018-01-01 21:38:48,472 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,476 : INFO : < 200 OK [3271]
2018-01-01 21:38:48,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 543}
2018-01-01 21:38:48,480 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,484 : INFO : < 200 OK [3273]
2018-01-01 21:38:48,488 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 543}
2018-01-01 21:38:48,488 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,492 : INFO : < 200 OK [3275]
2018-01-01 21:38:48,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1157, '_0n1': 527}
2018-01-01 21:38:48,496 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,500 : INFO : < 200 OK [3319]
2018-01-01 21:38:48,504 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 856, '_0n1': 544}
2018-01-01 21:38:48,508 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,512 : INFO : < 200 OK [3289]
2018-01-01 21:38:48,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 976, '_0n1': 544}

2018-01-01 21:38:48,516 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,523 : INFO : < 200 OK [3294]
2018-01-01 21:38:48,528 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1153, '_0n1': 544}
2018-01-01 21:38:48,529 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,533 : INFO : < 200 OK [3300]
2018-01-01 21:38:48,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 750, '_0n1': 544}
2018-01-01 21:38:48,536 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,540 : INFO : < 200 OK [3290]
2018-01-01 21:38:48,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1105, '_0n1': 528}
2018-01-01 21:38:48,544 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,552 : INFO : < 200 OK [3369]
2018-01-01 21:38:48,552 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1024, '_0n1': 545}
2018-01-01 21:38:48,556 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,560 : INFO : < 200 OK [3317]
2018-01-01 21:38:48,564 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1042, '_0n1': 529}
2018-01-01 21:38:48,564 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,568 : INFO : < 200 OK [3350]
2018-01-01 21:38:48,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 889, '_0n1': 546}
2018-01-01 21:38:48,572 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,576 : INFO : < 200 OK [3317]
2018-01-01 21:38:48,580 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 718, '_0n1': 546}
2018-01-01 21:38:48,580 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,584 : INFO : < 200 OK [3312]
2018-01-01 21:38:48,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1079, '_0n1': 530}
2018-01-01 21:38:48,588 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,592 : INFO : < 200 OK [3274]
2018-01-01 21:38:48,596 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 888, '_0n1': 547}
2018-01-01 21:38:48,596 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,600 : INFO : < 200 OK [3306]
2018-01-01 21:38:48,604 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 929, '_0n1': 547}
2018-01-01 21:38:48,608 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,612 : INFO : < 200 OK [3311]
2018-01-01 21:38:48,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1042, '_0n1': 531}
2018-01-01 21:38:48,616 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,623 : INFO : < 200 OK [3325]
2018-01-01 21:38:48,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 994, '_0n1': 548}
2018-01-01 21:38:48,627 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,631 : INFO : < 200 OK [3255]
2018-01-01 21:38:48,634 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 811, '_0n1': 548}
2018-01-01 21:38:48,636 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,640 : INFO : < 200 OK [3260]
2018-01-01 21:38:48,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1092, '_0n1': 548}
2018-01-01 21:38:48,644 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,648 : INFO : < 200 OK [3272]
2018-01-01 21:38:48,652 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 775, '_0n1': 532}
2018-01-01 21:38:48,656 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,660 : INFO : < 200 OK [3275]
2018-01-01 21:38:48,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1050, '_0n1': 549}
2018-01-01 21:38:48,664 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,672 : INFO : < 200 OK [3323]
2018-01-01 21:38:48,676 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1046, '_0n1': 553}
2018-01-01 21:38:48,676 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,680 : INFO : < 200 OK [3282]
2018-01-01 21:38:48,684 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1122, '_0n1': 553}
2018-01-01 21:38:48,684 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,688 : INFO : < 200 OK [3282]
2018-01-01 21:38:48,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 729, '_0n1': 550}
2018-01-01 21:38:48,692 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,700 : INFO : < 200 OK [3337]
2018-01-01 21:38:48,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1085, '_0n1': 554}
2018-01-01 21:38:48,704 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,708 : INFO : < 200 OK [3330]
2018-01-01 21:38:48,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1130, '_0n1': 554}
2018-01-01 21:38:48,712 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,716 : INFO : < 200 OK [3330]
2018-01-01 21:38:48,716 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1155, '_0n1': 551}
2018-01-01 21:38:48,722 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,725 : INFO : < 200 OK [3300]
2018-01-01 21:38:48,729 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1015, '_0n1': 551}
2018-01-01 21:38:48,731 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,736 : INFO : < 200 OK [3292]
2018-01-01 21:38:48,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1020, '_0n1': 551}
2018-01-01 21:38:48,736 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,744 : INFO : < 200 OK [3292]
2018-01-01 21:38:48,744 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 783, '_0n1': 555}

2018-01-01 21:38:48,744 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,748 : INFO : < 200 OK [3278]
2018-01-01 21:38:48,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 552}
2018-01-01 21:38:48,752 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,764 : INFO : < 200 OK [3269]
2018-01-01 21:38:48,764 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1149, '_0n1': 552}
2018-01-01 21:38:48,768 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,776 : INFO : < 200 OK [3295]
2018-01-01 21:38:48,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 839, '_0n1': 556}
2018-01-01 21:38:48,780 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,784 : INFO : < 200 OK [3275]
2018-01-01 21:38:48,788 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1134, '_0n1': 556}
2018-01-01 21:38:48,788 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,796 : INFO : < 200 OK [3294]
2018-01-01 21:38:48,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 935, '_0n1': 573}
2018-01-01 21:38:48,800 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,804 : INFO : < 200 OK [3264]
2018-01-01 21:38:48,804 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 557}
2018-01-01 21:38:48,808 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,812 : INFO : < 200 OK [3321]
2018-01-01 21:38:48,812 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1191, '_0n1': 557}
2018-01-01 21:38:48,816 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,822 : INFO : < 200 OK [3333]
2018-01-01 21:38:48,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1116, '_0n1': 574}
2018-01-01 21:38:48,826 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,830 : INFO : < 200 OK [3290]
2018-01-01 21:38:48,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 791, '_0n1': 574}
2018-01-01 21:38:48,834 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,836 : INFO : < 200 OK [3271]
2018-01-01 21:38:48,836 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 968, '_0n1': 574}
2018-01-01 21:38:48,840 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,844 : INFO : < 200 OK [3277]
2018-01-01 21:38:48,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 558}
2018-01-01 21:38:48,848 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,852 : INFO : < 200 OK [3298]
2018-01-01 21:38:48,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 755, '_0n1': 575}
2018-01-01 21:38:48,856 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,860 : INFO : < 200 OK [3307]
2018-01-01 21:38:48,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 944, '_0n1': 575}
2018-01-01 21:38:48,864 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,868 : INFO : < 200 OK [3310]
2018-01-01 21:38:48,872 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1077, '_0n1': 559}
2018-01-01 21:38:48,872 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,884 : INFO : < 200 OK [3321]
2018-01-01 21:38:48,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 989, '_0n1': 559}
2018-01-01 21:38:48,888 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,892 : INFO : < 200 OK [3310]
2018-01-01 21:38:48,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 576}
2018-01-01 21:38:48,900 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,904 : INFO : < 200 OK [3274]
2018-01-01 21:38:48,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1170, '_0n1': 560}
2018-01-01 21:38:48,908 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,916 : INFO : < 200 OK [3321]
2018-01-01 21:38:48,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 848, '_0n1': 560}
2018-01-01 21:38:48,920 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,926 : INFO : < 200 OK [3299]
2018-01-01 21:38:48,929 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1015, '_0n1': 577}
2018-01-01 21:38:48,930 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,935 : INFO : < 200 OK [3319]
2018-01-01 21:38:48,937 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1020, '_0n1': 577}
2018-01-01 21:38:48,937 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,941 : INFO : < 200 OK [3319]
2018-01-01 21:38:48,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1155, '_0n1': 577}
2018-01-01 21:38:48,945 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,949 : INFO : < 200 OK [3327]
2018-01-01 21:38:48,953 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 789, '_0n1': 561}
2018-01-01 21:38:48,953 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,957 : INFO : < 200 OK [3306]
2018-01-01 21:38:48,961 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1139, '_0n1': 578}
2018-01-01 21:38:48,961 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,969 : INFO : < 200 OK [3330]
2018-01-01 21:38:48,969 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1107, '_0n1': 562}
2018-01-01 21:38:48,973 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:48,977 : INFO : < 200 OK [3278]
2018-01-01 21:38:48,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 962, '_0n1': 579}

2018-01-01 21:38:48,981 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,985 : INFO : < 200 OK [3317]
2018-01-01 21:38:48,989 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 719, '_0n1': 579}
2018-01-01 21:38:48,989 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:48,993 : INFO : < 200 OK [3316]
2018-01-01 21:38:48,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1025, '_0n1': 579}
2018-01-01 21:38:48,997 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,001 : INFO : < 200 OK [3334]
2018-01-01 21:38:49,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 926, '_0n1': 579}
2018-01-01 21:38:49,009 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,013 : INFO : < 200 OK [3318]
2018-01-01 21:38:49,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 563}
2018-01-01 21:38:49,017 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,026 : INFO : < 200 OK [3339]
2018-01-01 21:38:49,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 827, '_0n1': 563}
2018-01-01 21:38:49,032 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,037 : INFO : < 200 OK [3325]
2018-01-01 21:38:49,041 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 790, '_0n1': 580}
2018-01-01 21:38:49,041 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,045 : INFO : < 200 OK [3285]
2018-01-01 21:38:49,049 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 749, '_0n1': 580}
2018-01-01 21:38:49,049 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,057 : INFO : < 200 OK [3292]
2018-01-01 21:38:49,057 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 915, '_0n1': 564}
2018-01-01 21:38:49,061 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,065 : INFO : < 200 OK [3312]
2018-01-01 21:38:49,069 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1175, '_0n1': 581}
2018-01-01 21:38:49,069 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,077 : INFO : < 200 OK [3303]
2018-01-01 21:38:49,077 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 868, '_0n1': 565}
2018-01-01 21:38:49,081 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,085 : INFO : < 200 OK [3333]
2018-01-01 21:38:49,089 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1043, '_0n1': 582}
2018-01-01 21:38:49,089 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,093 : INFO : < 200 OK [3306]
2018-01-01 21:38:49,097 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 934, '_0n1': 566}
2018-01-01 21:38:49,097 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,101 : INFO : < 200 OK [3268]
2018-01-01 21:38:49,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 831, '_0n1': 583}
2018-01-01 21:38:49,105 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,109 : INFO : < 200 OK [3299]
2018-01-01 21:38:49,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 830, '_0n1': 567}
2018-01-01 21:38:49,113 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,117 : INFO : < 200 OK [3305]
2018-01-01 21:38:49,123 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1025, '_0n1': 584}
2018-01-01 21:38:49,124 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,128 : INFO : < 200 OK [3338]
2018-01-01 21:38:49,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 719, '_0n1': 584}
2018-01-01 21:38:49,133 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,136 : INFO : < 200 OK [3320]
2018-01-01 21:38:49,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 962, '_0n1': 584}
2018-01-01 21:38:49,141 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,145 : INFO : < 200 OK [3321]
2018-01-01 21:38:49,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 926, '_0n1': 584}
2018-01-01 21:38:49,149 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,153 : INFO : < 200 OK [3322]
2018-01-01 21:38:49,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 746, '_0n1': 568}
2018-01-01 21:38:49,161 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,165 : INFO : < 200 OK [3313]
2018-01-01 21:38:49,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1170, '_0n1': 585}
2018-01-01 21:38:49,169 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,177 : INFO : < 200 OK [3297]
2018-01-01 21:38:49,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 848, '_0n1': 585}
2018-01-01 21:38:49,181 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,185 : INFO : < 200 OK [3275]
2018-01-01 21:38:49,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1139, '_0n1': 569}
2018-01-01 21:38:49,189 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,193 : INFO : < 200 OK [3322]
2018-01-01 21:38:49,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 890, '_0n1': 586}
2018-01-01 21:38:49,197 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,201 : INFO : < 200 OK [3317]
2018-01-01 21:38:49,205 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1146, '_0n1': 586}
2018-01-01 21:38:49,205 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,213 : INFO : < 200 OK [3344]
2018-01-01 21:38:49,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1027, '_0n1': 570}

2018-01-01 21:38:49,217 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,221 : INFO : < 200 OK [3291]
2018-01-01 21:38:49,221 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 793, '_0n1': 570}
2018-01-01 21:38:49,227 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,230 : INFO : < 200 OK [3277]
2018-01-01 21:38:49,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 996, '_0n1': 570}
2018-01-01 21:38:49,234 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,237 : INFO : < 200 OK [3279]
2018-01-01 21:38:49,237 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 735, '_0n1': 570}
2018-01-01 21:38:49,241 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,245 : INFO : < 200 OK [3277]
2018-01-01 21:38:49,249 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1041, '_0n1': 587}
2018-01-01 21:38:49,249 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,253 : INFO : < 200 OK [3313]
2018-01-01 21:38:49,257 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 860, '_0n1': 587}
2018-01-01 21:38:49,257 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,261 : INFO : < 200 OK [3302]
2018-01-01 21:38:49,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 719, '_0n1': 571}
2018-01-01 21:38:49,265 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,269 : INFO : < 200 OK [3315]
2018-01-01 21:38:49,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 962, '_0n1': 571}
2018-01-01 21:38:49,273 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,277 : INFO : < 200 OK [3316]
2018-01-01 21:38:49,281 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1025, '_0n1': 571}
2018-01-01 21:38:49,281 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,285 : INFO : < 200 OK [3333]
2018-01-01 21:38:49,289 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 926, '_0n1': 571}
2018-01-01 21:38:49,289 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,293 : INFO : < 200 OK [3317]
2018-01-01 21:38:49,297 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 831, '_0n1': 588}
2018-01-01 21:38:49,297 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,305 : INFO : < 200 OK [3302]
2018-01-01 21:38:49,309 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 831, '_0n1': 572}
2018-01-01 21:38:49,309 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,317 : INFO : < 200 OK [3301]
2018-01-01 21:38:49,322 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 786, '_0n1': 589}
2018-01-01 21:38:49,325 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,333 : INFO : < 200 OK [3336]
2018-01-01 21:38:49,337 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1107, '_0n1': 593}
2018-01-01 21:38:49,337 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,341 : INFO : < 200 OK [3278]
2018-01-01 21:38:49,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1015, '_0n1': 590}
2018-01-01 21:38:49,349 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,353 : INFO : < 200 OK [3328]
2018-01-01 21:38:49,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1020, '_0n1': 590}
2018-01-01 21:38:49,357 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,361 : INFO : < 200 OK [3328]
2018-01-01 21:38:49,369 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1155, '_0n1': 590}
2018-01-01 21:38:49,369 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,373 : INFO : < 200 OK [3336]
2018-01-01 21:38:49,377 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 895, '_0n1': 594}
2018-01-01 21:38:49,381 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,385 : INFO : < 200 OK [3307]
2018-01-01 21:38:49,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 739, '_0n1': 591}
2018-01-01 21:38:49,393 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,397 : INFO : < 200 OK [3317]
2018-01-01 21:38:49,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 800, '_0n1': 591}
2018-01-01 21:38:49,405 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,409 : INFO : < 200 OK [3314]
2018-01-01 21:38:49,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 840, '_0n1': 595}
2018-01-01 21:38:49,413 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,424 : INFO : < 200 OK [3325]
2018-01-01 21:38:49,427 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 934, '_0n1': 592}
2018-01-01 21:38:49,429 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,433 : INFO : < 200 OK [3273]
2018-01-01 21:38:49,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 808, '_0n1': 596}
2018-01-01 21:38:49,437 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,441 : INFO : < 200 OK [3294]
2018-01-01 21:38:49,445 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1032, '_0n1': 596}
2018-01-01 21:38:49,445 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,453 : INFO : < 200 OK [3312]
2018-01-01 21:38:49,457 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 861, '_0n1': 596}
2018-01-01 21:38:49,457 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,461 : INFO : < 200 OK [3294]
2018-01-01 21:38:49,465 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1181, '_0n1': 613}

2018-01-01 21:38:49,465 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,473 : INFO : < 200 OK [3301]
2018-01-01 21:38:49,477 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 739, '_0n1': 597}
2018-01-01 21:38:49,477 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,481 : INFO : < 200 OK [3294]
2018-01-01 21:38:49,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 895, '_0n1': 614}
2018-01-01 21:38:49,485 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,493 : INFO : < 200 OK [3307]
2018-01-01 21:38:49,497 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 877, '_0n1': 598}
2018-01-01 21:38:49,497 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,501 : INFO : < 200 OK [3305]
2018-01-01 21:38:49,505 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1178, '_0n1': 615}
2018-01-01 21:38:49,505 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,509 : INFO : < 200 OK [3311]
2018-01-01 21:38:49,513 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 877, '_0n1': 599}
2018-01-01 21:38:49,517 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,522 : INFO : < 200 OK [3279]
2018-01-01 21:38:49,526 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 895, '_0n1': 616}
2018-01-01 21:38:49,527 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,532 : INFO : < 200 OK [3312]
2018-01-01 21:38:49,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 895, '_0n1': 600}
2018-01-01 21:38:49,536 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,541 : INFO : < 200 OK [3304]
2018-01-01 21:38:49,545 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 895, '_0n1': 617}
2018-01-01 21:38:49,545 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,549 : INFO : < 200 OK [3309]
2018-01-01 21:38:49,553 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 877, '_0n1': 601}
2018-01-01 21:38:49,553 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,561 : INFO : < 200 OK [3279]
2018-01-01 21:38:49,561 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 877, '_0n1': 618}
2018-01-01 21:38:49,565 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,569 : INFO : < 200 OK [3285]
2018-01-01 21:38:49,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 845, '_0n1': 602}
2018-01-01 21:38:49,573 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,581 : INFO : < 200 OK [3263]
2018-01-01 21:38:49,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1051, '_0n1': 602}
2018-01-01 21:38:49,589 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,593 : INFO : < 200 OK [3276]
2018-01-01 21:38:49,597 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 905, '_0n1': 619}
2018-01-01 21:38:49,601 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,605 : INFO : < 200 OK [3294]
2018-01-01 21:38:49,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 937, '_0n1': 603}
2018-01-01 21:38:49,613 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,617 : INFO : < 200 OK [3313]
2018-01-01 21:38:49,623 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 739, '_0n1': 620}
2018-01-01 21:38:49,626 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,631 : INFO : < 200 OK [3266]
2018-01-01 21:38:49,635 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 800, '_0n1': 620}
2018-01-01 21:38:49,636 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,641 : INFO : < 200 OK [3263]
2018-01-01 21:38:49,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 719, '_0n1': 604}
2018-01-01 21:38:49,645 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,649 : INFO : < 200 OK [3319]
2018-01-01 21:38:49,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 962, '_0n1': 604}
2018-01-01 21:38:49,657 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,661 : INFO : < 200 OK [3320]
2018-01-01 21:38:49,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1025, '_0n1': 604}
2018-01-01 21:38:49,669 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,673 : INFO : < 200 OK [3337]
2018-01-01 21:38:49,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 926, '_0n1': 604}
2018-01-01 21:38:49,681 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,685 : INFO : < 200 OK [3321]
2018-01-01 21:38:49,689 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 934, '_0n1': 621}
2018-01-01 21:38:49,689 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:38:49,697 : INFO : < 200 OK [3272]
2018-01-01 21:38:49,701 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1159, '_0n1': 621}
2018-01-01 21:38:49,701 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:38:49,705 : INFO : < 200 OK [3292]

In [67]:
for i, row in data.drop_duplicates(subset=['created_by', 'teach_by']).iterrows():
    x = teach_dict[row.teach_by]
    y = institute_dict[row.created_by]
    graph.create(Relationship(x, "from", y))

2018-01-01 21:52:46,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1047, '_0n1': 682}
2018-01-01 21:52:46,543 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:46,543 : INFO : ~ Reconnecting (connection aborted)
2018-01-01 21:52:47,553 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,561 : INFO : < 200 OK [3234]
2018-01-01 21:52:47,565 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 751, '_0n1': 647}
2018-01-01 21:52:47,569 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,577 : INFO : < 200 OK [3211]
2018-01-01 21:52:47,581 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1119, '_0n1': 707}
2018-01-01 21:52:47,585 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,589 : INFO : < 200 OK [3231]
2018-01-01 21:52:47,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 869, '_0n1': 636}
2018-01-01 21:52:47,593 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,597 : INFO : < 200 OK [3235]
2018-01-01 21:52:47,601 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 726, '_0n1': 705}
2018-01-01 21:52:47,601 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,605 : INFO : < 200 OK [3203]
2018-01-01 21:52:47,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 901, '_0n1': 686}
2018-01-01 21:52:47,609 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,613 : INFO : < 200 OK [3228]
2018-01-01 21:52:47,617 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 931, '_0n1': 644}
2018-01-01 21:52:47,619 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,622 : INFO : < 200 OK [3252]
2018-01-01 21:52:47,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1118, '_0n1': 646}
2018-01-01 21:52:47,627 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,629 : INFO : < 200 OK [3230]
2018-01-01 21:52:47,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 990, '_0n1': 636}
2018-01-01 21:52:47,633 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,637 : INFO : < 200 OK [3232]
2018-01-01 21:52:47,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 974, '_0n1': 709}
2018-01-01 21:52:47,645 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,649 : INFO : < 200 OK [3223]
2018-01-01 21:52:47,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 930, '_0n1': 628}
2018-01-01 21:52:47,653 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,657 : INFO : < 200 OK [3230]
2018-01-01 21:52:47,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1173, '_0n1': 628}
2018-01-01 21:52:47,661 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,669 : INFO : < 200 OK [3243]
2018-01-01 21:52:47,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 795, '_0n1': 628}
2018-01-01 21:52:47,673 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,677 : INFO : < 200 OK [3223]
2018-01-01 21:52:47,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1112, '_0n1': 709}
2018-01-01 21:52:47,681 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,685 : INFO : < 200 OK [3238]
2018-01-01 21:52:47,685 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 748, '_0n1': 709}
2018-01-01 21:52:47,689 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,693 : INFO : < 200 OK [3225]
2018-01-01 21:52:47,697 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 826, '_0n1': 665}
2018-01-01 21:52:47,697 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,701 : INFO : < 200 OK [3240]
2018-01-01 21:52:47,705 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 805, '_0n1': 665}
2018-01-01 21:52:47,705 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,709 : INFO : < 200 OK [3237]
2018-01-01 21:52:47,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1031, '_0n1': 682}
2018-01-01 21:52:47,715 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,719 : INFO : < 200 OK [3235]
2018-01-01 21:52:47,722 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 830, '_0n1': 648}
2018-01-01 21:52:47,723 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,727 : INFO : < 200 OK [3225]
2018-01-01 21:52:47,729 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 908, '_0n1': 679}
2018-01-01 21:52:47,729 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,733 : INFO : < 200 OK [3222]
2018-01-01 21:52:47,737 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1144, '_0n1': 636}
2018-01-01 21:52:47,737 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,741 : INFO : < 200 OK [3248]
2018-01-01 21:52:47,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1022, '_0n1': 709}
2018-01-01 21:52:47,745 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,753 : INFO : < 200 OK [3242]
2018-01-01 21:52:47,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 829, '_0n1': 665}
2018-01-01 21:52:47,761 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,765 : INFO : < 200 OK [3244]
2018-01-01 21:52:47,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 897, '_0n1': 665}
2018-01-01 21:52:47,769 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,773 : INFO : < 200 OK [3237]
2018-01-01 21:52:47,777 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1176, '_0n1': 709}

2018-01-01 21:52:47,777 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,781 : INFO : < 200 OK [3239]
2018-01-01 21:52:47,785 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 941, '_0n1': 709}
2018-01-01 21:52:47,789 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,793 : INFO : < 200 OK [3225]
2018-01-01 21:52:47,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 866, '_0n1': 636}
2018-01-01 21:52:47,797 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,801 : INFO : < 200 OK [3226]
2018-01-01 21:52:47,805 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1056, '_0n1': 675}
2018-01-01 21:52:47,805 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,814 : INFO : < 200 OK [3226]
2018-01-01 21:52:47,817 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 844, '_0n1': 675}
2018-01-01 21:52:47,820 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,824 : INFO : < 200 OK [3207]
2018-01-01 21:52:47,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 809, '_0n1': 638}
2018-01-01 21:52:47,828 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,833 : INFO : < 200 OK [3226]
2018-01-01 21:52:47,833 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1070, '_0n1': 638}
2018-01-01 21:52:47,837 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,841 : INFO : < 200 OK [3244]
2018-01-01 21:52:47,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 914, '_0n1': 686}
2018-01-01 21:52:47,845 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,849 : INFO : < 200 OK [3226]
2018-01-01 21:52:47,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1049, '_0n1': 686}
2018-01-01 21:52:47,853 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,857 : INFO : < 200 OK [3240]
2018-01-01 21:52:47,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 871, '_0n1': 686}
2018-01-01 21:52:47,861 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,865 : INFO : < 200 OK [3254]
2018-01-01 21:52:47,869 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 756, '_0n1': 686}
2018-01-01 21:52:47,869 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,873 : INFO : < 200 OK [3246]
2018-01-01 21:52:47,877 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 780, '_0n1': 631}
2018-01-01 21:52:47,877 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,881 : INFO : < 200 OK [3235]
2018-01-01 21:52:47,885 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 740, '_0n1': 631}
2018-01-01 21:52:47,889 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,893 : INFO : < 200 OK [3236]
2018-01-01 21:52:47,897 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 904, '_0n1': 682}
2018-01-01 21:52:47,897 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,901 : INFO : < 200 OK [3214]
2018-01-01 21:52:47,905 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1040, '_0n1': 682}
2018-01-01 21:52:47,905 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,909 : INFO : < 200 OK [3237]
2018-01-01 21:52:47,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1140, '_0n1': 679}
2018-01-01 21:52:47,916 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,920 : INFO : < 200 OK [3229]
2018-01-01 21:52:47,923 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 734, '_0n1': 679}
2018-01-01 21:52:47,925 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,929 : INFO : < 200 OK [3216]
2018-01-01 21:52:47,929 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 937, '_0n1': 675}
2018-01-01 21:52:47,933 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,937 : INFO : < 200 OK [3207]
2018-01-01 21:52:47,941 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1016, '_0n1': 675}
2018-01-01 21:52:47,941 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,945 : INFO : < 200 OK [3229]
2018-01-01 21:52:47,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 736, '_0n1': 679}
2018-01-01 21:52:47,949 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,953 : INFO : < 200 OK [3222]
2018-01-01 21:52:47,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1102, '_0n1': 675}
2018-01-01 21:52:47,957 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,961 : INFO : < 200 OK [3226]
2018-01-01 21:52:47,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 845, '_0n1': 648}
2018-01-01 21:52:47,965 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,973 : INFO : < 200 OK [3228]
2018-01-01 21:52:47,977 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1051, '_0n1': 648}
2018-01-01 21:52:47,977 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:47,985 : INFO : < 200 OK [3241]
2018-01-01 21:52:47,993 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 984, '_0n1': 665}
2018-01-01 21:52:47,993 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:47,997 : INFO : < 200 OK [3239]
2018-01-01 21:52:48,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1081, '_0n1': 679}
2018-01-01 21:52:48,005 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,009 : INFO : < 200 OK [3241]
2018-01-01 21:52:48,015 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 782, '_0n1': 699}

2018-01-01 21:52:48,017 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,022 : INFO : < 200 OK [3207]
2018-01-01 21:52:48,024 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 737, '_0n1': 699}
2018-01-01 21:52:48,025 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,029 : INFO : < 200 OK [3241]
2018-01-01 21:52:48,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1048, '_0n1': 699}
2018-01-01 21:52:48,033 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,037 : INFO : < 200 OK [3256]
2018-01-01 21:52:48,041 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 757, '_0n1': 682}
2018-01-01 21:52:48,041 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,049 : INFO : < 200 OK [3214]
2018-01-01 21:52:48,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1062, '_0n1': 682}
2018-01-01 21:52:48,053 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,057 : INFO : < 200 OK [3234]
2018-01-01 21:52:48,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1184, '_0n1': 700}
2018-01-01 21:52:48,061 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,065 : INFO : < 200 OK [3310]
2018-01-01 21:52:48,069 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 998, '_0n1': 700}
2018-01-01 21:52:48,073 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,077 : INFO : < 200 OK [3288]
2018-01-01 21:52:48,081 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 950, '_0n1': 700}
2018-01-01 21:52:48,081 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,085 : INFO : < 200 OK [3286]
2018-01-01 21:52:48,089 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 700}
2018-01-01 21:52:48,093 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,097 : INFO : < 200 OK [3304]
2018-01-01 21:52:48,101 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 778, '_0n1': 700}
2018-01-01 21:52:48,101 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,109 : INFO : < 200 OK [3288]
2018-01-01 21:52:48,114 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 953, '_0n1': 647}
2018-01-01 21:52:48,117 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,122 : INFO : < 200 OK [3217]
2018-01-01 21:52:48,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 822, '_0n1': 653}
2018-01-01 21:52:48,126 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,129 : INFO : < 200 OK [3210]
2018-01-01 21:52:48,133 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 978, '_0n1': 653}
2018-01-01 21:52:48,137 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,141 : INFO : < 200 OK [3210]
2018-01-01 21:52:48,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 956, '_0n1': 653}
2018-01-01 21:52:48,145 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,153 : INFO : < 200 OK [3210]
2018-01-01 21:52:48,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1136, '_0n1': 653}
2018-01-01 21:52:48,157 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,161 : INFO : < 200 OK [3223]
2018-01-01 21:52:48,165 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 786, '_0n1': 612}
2018-01-01 21:52:48,169 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,173 : INFO : < 200 OK [3228]
2018-01-01 21:52:48,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 948, '_0n1': 612}
2018-01-01 21:52:48,177 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,185 : INFO : < 200 OK [3224]
2018-01-01 21:52:48,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1025, '_0n1': 695}
2018-01-01 21:52:48,185 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,193 : INFO : < 200 OK [3229]
2018-01-01 21:52:48,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 903, '_0n1': 695}
2018-01-01 21:52:48,197 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,201 : INFO : < 200 OK [3215]
2018-01-01 21:52:48,205 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 887, '_0n1': 695}
2018-01-01 21:52:48,205 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,213 : INFO : < 200 OK [3208]
2018-01-01 21:52:48,216 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1206, '_0n1': 680}
2018-01-01 21:52:48,218 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,223 : INFO : < 200 OK [3243]
2018-01-01 21:52:48,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1099, '_0n1': 647}
2018-01-01 21:52:48,228 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,233 : INFO : < 200 OK [3230]
2018-01-01 21:52:48,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 902, '_0n1': 700}
2018-01-01 21:52:48,237 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,241 : INFO : < 200 OK [3293]
2018-01-01 21:52:48,245 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1135, '_0n1': 654}
2018-01-01 21:52:48,249 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,253 : INFO : < 200 OK [3245]
2018-01-01 21:52:48,257 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1072, '_0n1': 640}
2018-01-01 21:52:48,257 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,261 : INFO : < 200 OK [3259]
2018-01-01 21:52:48,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 833, '_0n1': 634}

2018-01-01 21:52:48,265 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,273 : INFO : < 200 OK [3260]
2018-01-01 21:52:48,277 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 909, '_0n1': 634}
2018-01-01 21:52:48,277 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,281 : INFO : < 200 OK [3256]
2018-01-01 21:52:48,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1168, '_0n1': 685}
2018-01-01 21:52:48,289 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,293 : INFO : < 200 OK [3242]
2018-01-01 21:52:48,293 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1053, '_0n1': 631}
2018-01-01 21:52:48,297 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,301 : INFO : < 200 OK [3247]
2018-01-01 21:52:48,305 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 827, '_0n1': 631}
2018-01-01 21:52:48,305 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,314 : INFO : < 200 OK [3233]
2018-01-01 21:52:48,317 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 812, '_0n1': 656}
2018-01-01 21:52:48,319 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,323 : INFO : < 200 OK [3241]
2018-01-01 21:52:48,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 744, '_0n1': 656}
2018-01-01 21:52:48,329 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,333 : INFO : < 200 OK [3230]
2018-01-01 21:52:48,337 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 938, '_0n1': 653}
2018-01-01 21:52:48,337 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,341 : INFO : < 200 OK [3210]
2018-01-01 21:52:48,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 820, '_0n1': 711}
2018-01-01 21:52:48,349 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,353 : INFO : < 200 OK [3230]
2018-01-01 21:52:48,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1155, '_0n1': 631}
2018-01-01 21:52:48,357 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,361 : INFO : < 200 OK [3251]
2018-01-01 21:52:48,365 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1015, '_0n1': 631}
2018-01-01 21:52:48,369 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,373 : INFO : < 200 OK [3243]
2018-01-01 21:52:48,381 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1020, '_0n1': 631}
2018-01-01 21:52:48,381 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,385 : INFO : < 200 OK [3243]
2018-01-01 21:52:48,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 924, '_0n1': 694}
2018-01-01 21:52:48,389 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,397 : INFO : < 200 OK [3227]
2018-01-01 21:52:48,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 892, '_0n1': 694}
2018-01-01 21:52:48,401 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,405 : INFO : < 200 OK [3221]
2018-01-01 21:52:48,409 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 796, '_0n1': 623}
2018-01-01 21:52:48,413 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,418 : INFO : < 200 OK [3220]
2018-01-01 21:52:48,422 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 927, '_0n1': 642}
2018-01-01 21:52:48,424 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,429 : INFO : < 200 OK [3254]
2018-01-01 21:52:48,429 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 745, '_0n1': 642}
2018-01-01 21:52:48,433 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,437 : INFO : < 200 OK [3253]
2018-01-01 21:52:48,441 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1063, '_0n1': 638}
2018-01-01 21:52:48,445 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,453 : INFO : < 200 OK [3251]
2018-01-01 21:52:48,457 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1188, '_0n1': 642}
2018-01-01 21:52:48,457 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,461 : INFO : < 200 OK [3267]
2018-01-01 21:52:48,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 967, '_0n1': 642}
2018-01-01 21:52:48,469 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,477 : INFO : < 200 OK [3251]
2018-01-01 21:52:48,481 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1075, '_0n1': 642}
2018-01-01 21:52:48,485 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,489 : INFO : < 200 OK [3265]
2018-01-01 21:52:48,493 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 992, '_0n1': 642}
2018-01-01 21:52:48,493 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,497 : INFO : < 200 OK [3250]
2018-01-01 21:52:48,501 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 982, '_0n1': 642}
2018-01-01 21:52:48,501 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,505 : INFO : < 200 OK [3253]
2018-01-01 21:52:48,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1019, '_0n1': 665}
2018-01-01 21:52:48,514 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,518 : INFO : < 200 OK [3255]
2018-01-01 21:52:48,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 873, '_0n1': 642}
2018-01-01 21:52:48,524 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,528 : INFO : < 200 OK [3252]
2018-01-01 21:52:48,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 730, '_0n1': 642}

2018-01-01 21:52:48,533 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,537 : INFO : < 200 OK [3252]
2018-01-01 21:52:48,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 759, '_0n1': 694}
2018-01-01 21:52:48,541 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,549 : INFO : < 200 OK [3224]
2018-01-01 21:52:48,553 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 773, '_0n1': 694}
2018-01-01 21:52:48,553 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,557 : INFO : < 200 OK [3218]
2018-01-01 21:52:48,561 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 883, '_0n1': 711}
2018-01-01 21:52:48,561 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,569 : INFO : < 200 OK [3229]
2018-01-01 21:52:48,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1017, '_0n1': 608}
2018-01-01 21:52:48,573 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,577 : INFO : < 200 OK [3238]
2018-01-01 21:52:48,581 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1071, '_0n1': 642}
2018-01-01 21:52:48,585 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,589 : INFO : < 200 OK [3271]
2018-01-01 21:52:48,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 946, '_0n1': 642}
2018-01-01 21:52:48,593 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,597 : INFO : < 200 OK [3254]
2018-01-01 21:52:48,601 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 794, '_0n1': 631}
2018-01-01 21:52:48,601 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,605 : INFO : < 200 OK [3232]
2018-01-01 21:52:48,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1152, '_0n1': 710}
2018-01-01 21:52:48,609 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,617 : INFO : < 200 OK [3235]
2018-01-01 21:52:48,619 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1158, '_0n1': 640}
2018-01-01 21:52:48,621 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,625 : INFO : < 200 OK [3255]
2018-01-01 21:52:48,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1097, '_0n1': 640}
2018-01-01 21:52:48,629 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,633 : INFO : < 200 OK [3256]
2018-01-01 21:52:48,637 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 995, '_0n1': 679}
2018-01-01 21:52:48,637 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,641 : INFO : < 200 OK [3229]
2018-01-01 21:52:48,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1132, '_0n1': 712}
2018-01-01 21:52:48,645 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,649 : INFO : < 200 OK [3224]
2018-01-01 21:52:48,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 891, '_0n1': 712}
2018-01-01 21:52:48,653 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,657 : INFO : < 200 OK [3211]
2018-01-01 21:52:48,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 798, '_0n1': 712}
2018-01-01 21:52:48,665 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,669 : INFO : < 200 OK [3211]
2018-01-01 21:52:48,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1156, '_0n1': 637}
2018-01-01 21:52:48,673 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,677 : INFO : < 200 OK [3249]
2018-01-01 21:52:48,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 862, '_0n1': 679}
2018-01-01 21:52:48,681 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,685 : INFO : < 200 OK [3223]
2018-01-01 21:52:48,689 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1038, '_0n1': 694}
2018-01-01 21:52:48,689 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,693 : INFO : < 200 OK [3236]
2018-01-01 21:52:48,697 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1039, '_0n1': 682}
2018-01-01 21:52:48,701 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,705 : INFO : < 200 OK [3234]
2018-01-01 21:52:48,705 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1080, '_0n1': 654}
2018-01-01 21:52:48,709 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,714 : INFO : < 200 OK [3248]
2018-01-01 21:52:48,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1167, '_0n1': 662}
2018-01-01 21:52:48,719 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,723 : INFO : < 200 OK [3244]
2018-01-01 21:52:48,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1096, '_0n1': 702}
2018-01-01 21:52:48,729 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,733 : INFO : < 200 OK [3237]
2018-01-01 21:52:48,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 804, '_0n1': 711}
2018-01-01 21:52:48,737 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,741 : INFO : < 200 OK [3227]
2018-01-01 21:52:48,741 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 915, '_0n1': 605}
2018-01-01 21:52:48,745 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,749 : INFO : < 200 OK [3215]
2018-01-01 21:52:48,753 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 838, '_0n1': 631}
2018-01-01 21:52:48,753 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,757 : INFO : < 200 OK [3232]
2018-01-01 21:52:48,761 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1128, '_0n1': 658}

2018-01-01 21:52:48,761 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,769 : INFO : < 200 OK [3234]
2018-01-01 21:52:48,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 969, '_0n1': 658}
2018-01-01 21:52:48,773 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,777 : INFO : < 200 OK [3215]
2018-01-01 21:52:48,777 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1000, '_0n1': 658}
2018-01-01 21:52:48,781 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,785 : INFO : < 200 OK [3232]
2018-01-01 21:52:48,789 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 912, '_0n1': 658}
2018-01-01 21:52:48,789 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,793 : INFO : < 200 OK [3221]
2018-01-01 21:52:48,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1120, '_0n1': 658}
2018-01-01 21:52:48,797 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,801 : INFO : < 200 OK [3237]
2018-01-01 21:52:48,805 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1115, '_0n1': 637}
2018-01-01 21:52:48,805 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,809 : INFO : < 200 OK [3242]
2018-01-01 21:52:48,813 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 885, '_0n1': 660}
2018-01-01 21:52:48,815 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,819 : INFO : < 200 OK [3209]
2018-01-01 21:52:48,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1043, '_0n1': 703}
2018-01-01 21:52:48,823 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,829 : INFO : < 200 OK [3229]
2018-01-01 21:52:48,833 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 818, '_0n1': 661}
2018-01-01 21:52:48,837 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,841 : INFO : < 200 OK [3233]
2018-01-01 21:52:48,841 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 731, '_0n1': 661}
2018-01-01 21:52:48,845 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,849 : INFO : < 200 OK [3238]
2018-01-01 21:52:48,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1066, '_0n1': 661}
2018-01-01 21:52:48,853 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,857 : INFO : < 200 OK [3244]
2018-01-01 21:52:48,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 857, '_0n1': 661}
2018-01-01 21:52:48,861 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,865 : INFO : < 200 OK [3229]
2018-01-01 21:52:48,869 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1208, '_0n1': 661}
2018-01-01 21:52:48,869 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,877 : INFO : < 200 OK [3253]
2018-01-01 21:52:48,877 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 884, '_0n1': 661}
2018-01-01 21:52:48,881 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,885 : INFO : < 200 OK [3231]
2018-01-01 21:52:48,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1203, '_0n1': 661}
2018-01-01 21:52:48,889 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,897 : INFO : < 200 OK [3254]
2018-01-01 21:52:48,897 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 847, '_0n1': 637}
2018-01-01 21:52:48,901 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,905 : INFO : < 200 OK [3228]
2018-01-01 21:52:48,909 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 716, '_0n1': 649}
2018-01-01 21:52:48,914 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,918 : INFO : < 200 OK [3257]
2018-01-01 21:52:48,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 808, '_0n1': 649}
2018-01-01 21:52:48,923 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,927 : INFO : < 200 OK [3253]
2018-01-01 21:52:48,929 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 879, '_0n1': 675}
2018-01-01 21:52:48,929 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,933 : INFO : < 200 OK [3210]
2018-01-01 21:52:48,937 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 878, '_0n1': 637}
2018-01-01 21:52:48,937 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,941 : INFO : < 200 OK [3226]
2018-01-01 21:52:48,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1085, '_0n1': 709}
2018-01-01 21:52:48,945 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,949 : INFO : < 200 OK [3242]
2018-01-01 21:52:48,953 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1150, '_0n1': 631}
2018-01-01 21:52:48,953 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,957 : INFO : < 200 OK [3250]
2018-01-01 21:52:48,961 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 942, '_0n1': 631}
2018-01-01 21:52:48,961 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,965 : INFO : < 200 OK [3234]
2018-01-01 21:52:48,969 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1159, '_0n1': 692}
2018-01-01 21:52:48,969 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,973 : INFO : < 200 OK [3238]
2018-01-01 21:52:48,977 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1036, '_0n1': 637}
2018-01-01 21:52:48,977 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:48,981 : INFO : < 200 OK [3249]
2018-01-01 21:52:48,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 980, '_0n1': 637}

2018-01-01 21:52:48,985 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,989 : INFO : < 200 OK [3233]
2018-01-01 21:52:48,993 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 824, '_0n1': 642}
2018-01-01 21:52:48,993 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:48,997 : INFO : < 200 OK [3252]
2018-01-01 21:52:49,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1100, '_0n1': 654}
2018-01-01 21:52:49,001 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,009 : INFO : < 200 OK [3248]
2018-01-01 21:52:49,009 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 961, '_0n1': 654}
2018-01-01 21:52:49,015 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,018 : INFO : < 200 OK [3244]
2018-01-01 21:52:49,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 814, '_0n1': 650}
2018-01-01 21:52:49,022 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,026 : INFO : < 200 OK [3244]
2018-01-01 21:52:49,028 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 792, '_0n1': 711}
2018-01-01 21:52:49,029 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,037 : INFO : < 200 OK [3225]
2018-01-01 21:52:49,041 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 797, '_0n1': 650}
2018-01-01 21:52:49,041 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,049 : INFO : < 200 OK [3233]
2018-01-01 21:52:49,049 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 951, '_0n1': 650}
2018-01-01 21:52:49,053 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,057 : INFO : < 200 OK [3232]
2018-01-01 21:52:49,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1018, '_0n1': 650}
2018-01-01 21:52:49,065 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,069 : INFO : < 200 OK [3258]
2018-01-01 21:52:49,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1109, '_0n1': 650}
2018-01-01 21:52:49,073 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,077 : INFO : < 200 OK [3246]
2018-01-01 21:52:49,081 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 806, '_0n1': 650}
2018-01-01 21:52:49,081 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,085 : INFO : < 200 OK [3236]
2018-01-01 21:52:49,089 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1098, '_0n1': 650}
2018-01-01 21:52:49,093 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,097 : INFO : < 200 OK [3245]
2018-01-01 21:52:49,101 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1064, '_0n1': 650}
2018-01-01 21:52:49,101 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,105 : INFO : < 200 OK [3257]
2018-01-01 21:52:49,109 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1177, '_0n1': 650}
2018-01-01 21:52:49,109 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,113 : INFO : < 200 OK [3256]
2018-01-01 21:52:49,118 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 991, '_0n1': 650}
2018-01-01 21:52:49,119 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,123 : INFO : < 200 OK [3238]
2018-01-01 21:52:49,127 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1065, '_0n1': 650}
2018-01-01 21:52:49,129 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,129 : INFO : < 200 OK [3245]
2018-01-01 21:52:49,133 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 977, '_0n1': 650}
2018-01-01 21:52:49,137 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,141 : INFO : < 200 OK [3237]
2018-01-01 21:52:49,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1111, '_0n1': 650}
2018-01-01 21:52:49,145 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,149 : INFO : < 200 OK [3246]
2018-01-01 21:52:49,153 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 863, '_0n1': 650}
2018-01-01 21:52:49,153 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,157 : INFO : < 200 OK [3240]
2018-01-01 21:52:49,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1123, '_0n1': 650}
2018-01-01 21:52:49,161 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,165 : INFO : < 200 OK [3263]
2018-01-01 21:52:49,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 957, '_0n1': 650}
2018-01-01 21:52:49,169 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,173 : INFO : < 200 OK [3235]
2018-01-01 21:52:49,181 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 874, '_0n1': 711}
2018-01-01 21:52:49,181 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,185 : INFO : < 200 OK [3232]
2018-01-01 21:52:49,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1185, '_0n1': 654}
2018-01-01 21:52:49,193 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,197 : INFO : < 200 OK [3247]
2018-01-01 21:52:49,201 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1205, '_0n1': 654}
2018-01-01 21:52:49,201 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,205 : INFO : < 200 OK [3250]
2018-01-01 21:52:49,209 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 864, '_0n1': 681}
2018-01-01 21:52:49,214 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,218 : INFO : < 200 OK [3245]
2018-01-01 21:52:49,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 949, '_0n1': 681}

2018-01-01 21:52:49,221 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,226 : INFO : < 200 OK [3255]
2018-01-01 21:52:49,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1142, '_0n1': 633}
2018-01-01 21:52:49,229 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,242 : INFO : < 200 OK [3234]
2018-01-01 21:52:49,246 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 715, '_0n1': 633}
2018-01-01 21:52:49,246 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,254 : INFO : < 200 OK [3217]
2018-01-01 21:52:49,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1172, '_0n1': 673}
2018-01-01 21:52:49,262 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,266 : INFO : < 200 OK [3236]
2018-01-01 21:52:49,270 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1034, '_0n1': 673}
2018-01-01 21:52:49,270 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,278 : INFO : < 200 OK [3235]
2018-01-01 21:52:49,282 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 815, '_0n1': 673}
2018-01-01 21:52:49,282 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,290 : INFO : < 200 OK [3220]
2018-01-01 21:52:49,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1186, '_0n1': 673}
2018-01-01 21:52:49,294 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,298 : INFO : < 200 OK [3237]
2018-01-01 21:52:49,302 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 732, '_0n1': 673}
2018-01-01 21:52:49,306 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,310 : INFO : < 200 OK [3228]
2018-01-01 21:52:49,317 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1154, '_0n1': 646}
2018-01-01 21:52:49,320 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,325 : INFO : < 200 OK [3229]
2018-01-01 21:52:49,329 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 821, '_0n1': 646}
2018-01-01 21:52:49,330 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,334 : INFO : < 200 OK [3214]
2018-01-01 21:52:49,338 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1012, '_0n1': 646}
2018-01-01 21:52:49,338 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,342 : INFO : < 200 OK [3231]
2018-01-01 21:52:49,346 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1069, '_0n1': 646}
2018-01-01 21:52:49,350 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,354 : INFO : < 200 OK [3227]
2018-01-01 21:52:49,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1058, '_0n1': 646}
2018-01-01 21:52:49,358 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,366 : INFO : < 200 OK [3227]
2018-01-01 21:52:49,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1044, '_0n1': 607}
2018-01-01 21:52:49,370 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,374 : INFO : < 200 OK [3232]
2018-01-01 21:52:49,378 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1164, '_0n1': 696}
2018-01-01 21:52:49,378 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,386 : INFO : < 200 OK [3261]
2018-01-01 21:52:49,390 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 945, '_0n1': 711}
2018-01-01 21:52:49,390 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,394 : INFO : < 200 OK [3234]
2018-01-01 21:52:49,398 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 843, '_0n1': 711}
2018-01-01 21:52:49,402 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,406 : INFO : < 200 OK [3231]
2018-01-01 21:52:49,406 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 958, '_0n1': 653}
2018-01-01 21:52:49,410 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,417 : INFO : < 200 OK [3214]
2018-01-01 21:52:49,421 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 853, '_0n1': 675}
2018-01-01 21:52:49,423 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,428 : INFO : < 200 OK [3217]
2018-01-01 21:52:49,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1178, '_0n1': 675}
2018-01-01 21:52:49,434 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,438 : INFO : < 200 OK [3220]
2018-01-01 21:52:49,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 728, '_0n1': 695}
2018-01-01 21:52:49,442 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,446 : INFO : < 200 OK [3212]
2018-01-01 21:52:49,450 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 785, '_0n1': 651}
2018-01-01 21:52:49,454 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,458 : INFO : < 200 OK [3232]
2018-01-01 21:52:49,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 851, '_0n1': 647}
2018-01-01 21:52:49,462 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,466 : INFO : < 200 OK [3218]
2018-01-01 21:52:49,470 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 943, '_0n1': 630}
2018-01-01 21:52:49,470 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,474 : INFO : < 200 OK [3256]
2018-01-01 21:52:49,478 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 886, '_0n1': 630}
2018-01-01 21:52:49,478 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,482 : INFO : < 200 OK [3256]
2018-01-01 21:52:49,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1127, '_0n1': 630}

2018-01-01 21:52:49,490 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,494 : INFO : < 200 OK [3264]
2018-01-01 21:52:49,498 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 888, '_0n1': 695}
2018-01-01 21:52:49,498 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,502 : INFO : < 200 OK [3210]
2018-01-01 21:52:49,506 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 828, '_0n1': 695}
2018-01-01 21:52:49,506 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,510 : INFO : < 200 OK [3210]
2018-01-01 21:52:49,514 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 999, '_0n1': 643}
2018-01-01 21:52:49,516 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,520 : INFO : < 200 OK [3223]
2018-01-01 21:52:49,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1084, '_0n1': 647}
2018-01-01 21:52:49,524 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,528 : INFO : < 200 OK [3235]
2018-01-01 21:52:49,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 850, '_0n1': 654}
2018-01-01 21:52:49,530 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,534 : INFO : < 200 OK [3233]
2018-01-01 21:52:49,538 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1083, '_0n1': 677}
2018-01-01 21:52:49,538 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,542 : INFO : < 200 OK [3245]
2018-01-01 21:52:49,546 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1117, '_0n1': 648}
2018-01-01 21:52:49,546 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,550 : INFO : < 200 OK [3249]
2018-01-01 21:52:49,554 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 779, '_0n1': 648}
2018-01-01 21:52:49,554 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,558 : INFO : < 200 OK [3238]
2018-01-01 21:52:49,562 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 881, '_0n1': 663}
2018-01-01 21:52:49,562 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,566 : INFO : < 200 OK [3230]
2018-01-01 21:52:49,570 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1204, '_0n1': 663}
2018-01-01 21:52:49,570 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,578 : INFO : < 200 OK [3241]
2018-01-01 21:52:49,582 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1110, '_0n1': 663}
2018-01-01 21:52:49,586 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,590 : INFO : < 200 OK [3244]
2018-01-01 21:52:49,590 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1174, '_0n1': 663}
2018-01-01 21:52:49,594 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,598 : INFO : < 200 OK [3236]
2018-01-01 21:52:49,602 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1055, '_0n1': 663}
2018-01-01 21:52:49,606 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,610 : INFO : < 200 OK [3238]
2018-01-01 21:52:49,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 923, '_0n1': 663}
2018-01-01 21:52:49,617 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,621 : INFO : < 200 OK [3225]
2018-01-01 21:52:49,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 801, '_0n1': 663}
2018-01-01 21:52:49,627 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,630 : INFO : < 200 OK [3220]
2018-01-01 21:52:49,630 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1161, '_0n1': 663}
2018-01-01 21:52:49,634 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,638 : INFO : < 200 OK [3243]
2018-01-01 21:52:49,638 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1103, '_0n1': 663}
2018-01-01 21:52:49,642 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,646 : INFO : < 200 OK [3244]
2018-01-01 21:52:49,650 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 803, '_0n1': 677}
2018-01-01 21:52:49,650 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,654 : INFO : < 200 OK [3233]
2018-01-01 21:52:49,658 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1029, '_0n1': 702}
2018-01-01 21:52:49,658 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,662 : INFO : < 200 OK [3235]
2018-01-01 21:52:49,666 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1054, '_0n1': 696}
2018-01-01 21:52:49,666 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,670 : INFO : < 200 OK [3262]
2018-01-01 21:52:49,674 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 752, '_0n1': 702}
2018-01-01 21:52:49,674 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,678 : INFO : < 200 OK [3222]
2018-01-01 21:52:49,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 907, '_0n1': 708}
2018-01-01 21:52:49,686 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,690 : INFO : < 200 OK [3226]
2018-01-01 21:52:49,694 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 880, '_0n1': 695}
2018-01-01 21:52:49,698 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,702 : INFO : < 200 OK [3214]
2018-01-01 21:52:49,706 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 724, '_0n1': 694}
2018-01-01 21:52:49,706 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,710 : INFO : < 200 OK [3223]
2018-01-01 21:52:49,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1082, '_0n1': 642}

2018-01-01 21:52:49,719 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,723 : INFO : < 200 OK [3266]
2018-01-01 21:52:49,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1104, '_0n1': 640}
2018-01-01 21:52:49,728 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,730 : INFO : < 200 OK [3257]
2018-01-01 21:52:49,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1093, '_0n1': 702}
2018-01-01 21:52:49,734 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,738 : INFO : < 200 OK [3233]
2018-01-01 21:52:49,742 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 875, '_0n1': 702}
2018-01-01 21:52:49,742 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,746 : INFO : < 200 OK [3226]
2018-01-01 21:52:49,750 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1209, '_0n1': 702}
2018-01-01 21:52:49,750 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,754 : INFO : < 200 OK [3234]
2018-01-01 21:52:49,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 870, '_0n1': 702}
2018-01-01 21:52:49,758 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,762 : INFO : < 200 OK [3219]
2018-01-01 21:52:49,766 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1137, '_0n1': 625}
2018-01-01 21:52:49,766 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,770 : INFO : < 200 OK [3266]
2018-01-01 21:52:49,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1090, '_0n1': 689}
2018-01-01 21:52:49,774 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,778 : INFO : < 200 OK [3235]
2018-01-01 21:52:49,782 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1106, '_0n1': 689}
2018-01-01 21:52:49,782 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,790 : INFO : < 200 OK [3233]
2018-01-01 21:52:49,790 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 784, '_0n1': 642}
2018-01-01 21:52:49,794 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,798 : INFO : < 200 OK [3254]
2018-01-01 21:52:49,802 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 894, '_0n1': 657}
2018-01-01 21:52:49,802 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,806 : INFO : < 200 OK [3272]
2018-01-01 21:52:49,810 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1086, '_0n1': 657}
2018-01-01 21:52:49,814 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,818 : INFO : < 200 OK [3284]
2018-01-01 21:52:49,822 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 963, '_0n1': 679}
2018-01-01 21:52:49,826 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,830 : INFO : < 200 OK [3216]
2018-01-01 21:52:49,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 858, '_0n1': 702}
2018-01-01 21:52:49,834 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,838 : INFO : < 200 OK [3229]
2018-01-01 21:52:49,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 940, '_0n1': 654}
2018-01-01 21:52:49,842 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,850 : INFO : < 200 OK [3236]
2018-01-01 21:52:49,850 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 928, '_0n1': 642}
2018-01-01 21:52:49,854 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,858 : INFO : < 200 OK [3252]
2018-01-01 21:52:49,862 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 973, '_0n1': 686}
2018-01-01 21:52:49,862 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,866 : INFO : < 200 OK [3234]
2018-01-01 21:52:49,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 842, '_0n1': 686}
2018-01-01 21:52:49,874 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,878 : INFO : < 200 OK [3226]
2018-01-01 21:52:49,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1141, '_0n1': 686}
2018-01-01 21:52:49,882 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,886 : INFO : < 200 OK [3244]
2018-01-01 21:52:49,890 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 993, '_0n1': 686}
2018-01-01 21:52:49,890 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,894 : INFO : < 200 OK [3227]
2018-01-01 21:52:49,898 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 772, '_0n1': 654}
2018-01-01 21:52:49,898 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,902 : INFO : < 200 OK [3229]
2018-01-01 21:52:49,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 849, '_0n1': 642}
2018-01-01 21:52:49,906 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,910 : INFO : < 200 OK [3254]
2018-01-01 21:52:49,915 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 761, '_0n1': 691}
2018-01-01 21:52:49,917 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,921 : INFO : < 200 OK [3237]
2018-01-01 21:52:49,923 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1076, '_0n1': 628}
2018-01-01 21:52:49,925 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,930 : INFO : < 200 OK [3235]
2018-01-01 21:52:49,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1121, '_0n1': 702}
2018-01-01 21:52:49,934 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,942 : INFO : < 200 OK [3236]
2018-01-01 21:52:49,946 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1095, '_0n1': 679}

2018-01-01 21:52:49,946 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,950 : INFO : < 200 OK [3243]
2018-01-01 21:52:49,954 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1059, '_0n1': 678}
2018-01-01 21:52:49,954 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,958 : INFO : < 200 OK [3234]
2018-01-01 21:52:49,966 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1013, '_0n1': 678}
2018-01-01 21:52:49,966 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:49,970 : INFO : < 200 OK [3229]
2018-01-01 21:52:49,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 926, '_0n1': 695}
2018-01-01 21:52:49,974 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,982 : INFO : < 200 OK [3213]
2018-01-01 21:52:49,982 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 719, '_0n1': 695}
2018-01-01 21:52:49,986 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:49,990 : INFO : < 200 OK [3211]
2018-01-01 21:52:49,994 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 962, '_0n1': 695}
2018-01-01 21:52:49,994 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,002 : INFO : < 200 OK [3212]
2018-01-01 21:52:50,006 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 835, '_0n1': 638}
2018-01-01 21:52:50,006 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,010 : INFO : < 200 OK [3241]
2018-01-01 21:52:50,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 919, '_0n1': 638}
2018-01-01 21:52:50,018 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,022 : INFO : < 200 OK [3229]
2018-01-01 21:52:50,024 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 960, '_0n1': 625}
2018-01-01 21:52:50,026 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,030 : INFO : < 200 OK [3250]
2018-01-01 21:52:50,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 810, '_0n1': 714}
2018-01-01 21:52:50,034 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,038 : INFO : < 200 OK [3220]
2018-01-01 21:52:50,042 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 754, '_0n1': 664}
2018-01-01 21:52:50,042 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,050 : INFO : < 200 OK [3218]
2018-01-01 21:52:50,054 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 774, '_0n1': 664}
2018-01-01 21:52:50,054 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,058 : INFO : < 200 OK [3224]
2018-01-01 21:52:50,062 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1207, '_0n1': 664}
2018-01-01 21:52:50,062 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,070 : INFO : < 200 OK [3233]
2018-01-01 21:52:50,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 781, '_0n1': 664}
2018-01-01 21:52:50,074 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,078 : INFO : < 200 OK [3226]
2018-01-01 21:52:50,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 910, '_0n1': 651}
2018-01-01 21:52:50,086 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,090 : INFO : < 200 OK [3228]
2018-01-01 21:52:50,094 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 983, '_0n1': 636}
2018-01-01 21:52:50,094 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,098 : INFO : < 200 OK [3234]
2018-01-01 21:52:50,102 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1032, '_0n1': 649}
2018-01-01 21:52:50,102 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,110 : INFO : < 200 OK [3271]
2018-01-01 21:52:50,117 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 970, '_0n1': 649}
2018-01-01 21:52:50,119 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,123 : INFO : < 200 OK [3251]
2018-01-01 21:52:50,127 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1165, '_0n1': 694}
2018-01-01 21:52:50,128 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,130 : INFO : < 200 OK [3235]
2018-01-01 21:52:50,134 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1151, '_0n1': 654}
2018-01-01 21:52:50,134 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,142 : INFO : < 200 OK [3249]
2018-01-01 21:52:50,142 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 964, '_0n1': 635}
2018-01-01 21:52:50,146 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,150 : INFO : < 200 OK [3220]
2018-01-01 21:52:50,154 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1147, '_0n1': 635}
2018-01-01 21:52:50,154 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,158 : INFO : < 200 OK [3244]
2018-01-01 21:52:50,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 832, '_0n1': 625}
2018-01-01 21:52:50,162 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,166 : INFO : < 200 OK [3250]
2018-01-01 21:52:50,170 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 788, '_0n1': 622}
2018-01-01 21:52:50,170 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,178 : INFO : < 200 OK [3217]
2018-01-01 21:52:50,182 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 861, '_0n1': 649}
2018-01-01 21:52:50,182 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,186 : INFO : < 200 OK [3253]
2018-01-01 21:52:50,190 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 965, '_0n1': 664}

2018-01-01 21:52:50,190 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,194 : INFO : < 200 OK [3222]
2018-01-01 21:52:50,198 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 739, '_0n1': 658}
2018-01-01 21:52:50,198 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,202 : INFO : < 200 OK [3220]
2018-01-01 21:52:50,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 776, '_0n1': 694}
2018-01-01 21:52:50,206 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,210 : INFO : < 200 OK [3222]
2018-01-01 21:52:50,216 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 896, '_0n1': 629}
2018-01-01 21:52:50,218 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,223 : INFO : < 200 OK [3222]
2018-01-01 21:52:50,226 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1210, '_0n1': 648}
2018-01-01 21:52:50,228 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,230 : INFO : < 200 OK [3253]
2018-01-01 21:52:50,230 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1088, '_0n1': 648}
2018-01-01 21:52:50,234 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,238 : INFO : < 200 OK [3242]
2018-01-01 21:52:50,242 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 911, '_0n1': 648}
2018-01-01 21:52:50,242 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,246 : INFO : < 200 OK [3230]
2018-01-01 21:52:50,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 947, '_0n1': 701}
2018-01-01 21:52:50,254 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,258 : INFO : < 200 OK [3241]
2018-01-01 21:52:50,262 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1145, '_0n1': 701}
2018-01-01 21:52:50,266 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,270 : INFO : < 200 OK [3264]
2018-01-01 21:52:50,274 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 882, '_0n1': 694}
2018-01-01 21:52:50,274 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,282 : INFO : < 200 OK [3219]
2018-01-01 21:52:50,286 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1125, '_0n1': 649}
2018-01-01 21:52:50,286 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,290 : INFO : < 200 OK [3271]
2018-01-01 21:52:50,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1166, '_0n1': 673}
2018-01-01 21:52:50,298 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,302 : INFO : < 200 OK [3234]
2018-01-01 21:52:50,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 867, '_0n1': 673}
2018-01-01 21:52:50,306 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,310 : INFO : < 200 OK [3222]
2018-01-01 21:52:50,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 922, '_0n1': 673}
2018-01-01 21:52:50,317 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,321 : INFO : < 200 OK [3220]
2018-01-01 21:52:50,324 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 760, '_0n1': 694}
2018-01-01 21:52:50,326 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,330 : INFO : < 200 OK [3225]
2018-01-01 21:52:50,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 837, '_0n1': 695}
2018-01-01 21:52:50,334 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,338 : INFO : < 200 OK [3220]
2018-01-01 21:52:50,338 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 921, '_0n1': 704}
2018-01-01 21:52:50,342 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,346 : INFO : < 200 OK [3223]
2018-01-01 21:52:50,350 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1131, '_0n1': 704}
2018-01-01 21:52:50,350 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,354 : INFO : < 200 OK [3235]
2018-01-01 21:52:50,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1060, '_0n1': 714}
2018-01-01 21:52:50,358 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,362 : INFO : < 200 OK [3231]
2018-01-01 21:52:50,366 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 987, '_0n1': 714}
2018-01-01 21:52:50,366 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,374 : INFO : < 200 OK [3222]
2018-01-01 21:52:50,378 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1092, '_0n1': 665}
2018-01-01 21:52:50,378 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,382 : INFO : < 200 OK [3252]
2018-01-01 21:52:50,386 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 836, '_0n1': 695}
2018-01-01 21:52:50,390 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,394 : INFO : < 200 OK [3209]
2018-01-01 21:52:50,398 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 932, '_0n1': 695}
2018-01-01 21:52:50,402 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,406 : INFO : < 200 OK [3211]
2018-01-01 21:52:50,410 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 738, '_0n1': 695}
2018-01-01 21:52:50,410 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,417 : INFO : < 200 OK [3213]
2018-01-01 21:52:50,420 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 725, '_0n1': 645}
2018-01-01 21:52:50,422 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,427 : INFO : < 200 OK [3230]
2018-01-01 21:52:50,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 717, '_0n1': 694}

2018-01-01 21:52:50,430 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,434 : INFO : < 200 OK [3229]
2018-01-01 21:52:50,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1183, '_0n1': 627}
2018-01-01 21:52:50,438 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,446 : INFO : < 200 OK [3233]
2018-01-01 21:52:50,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1108, '_0n1': 702}
2018-01-01 21:52:50,450 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,454 : INFO : < 200 OK [3244]
2018-01-01 21:52:50,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 841, '_0n1': 704}
2018-01-01 21:52:50,458 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,462 : INFO : < 200 OK [3229]
2018-01-01 21:52:50,470 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 900, '_0n1': 706}
2018-01-01 21:52:50,470 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,474 : INFO : < 200 OK [3212]
2018-01-01 21:52:50,478 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 839, '_0n1': 708}
2018-01-01 21:52:50,478 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,486 : INFO : < 200 OK [3210]
2018-01-01 21:52:50,490 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1134, '_0n1': 708}
2018-01-01 21:52:50,494 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,498 : INFO : < 200 OK [3229]
2018-01-01 21:52:50,502 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1057, '_0n1': 632}
2018-01-01 21:52:50,506 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,510 : INFO : < 200 OK [3233]
2018-01-01 21:52:50,518 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1014, '_0n1': 679}
2018-01-01 21:52:50,519 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,523 : INFO : < 200 OK [3233]
2018-01-01 21:52:50,526 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1187, '_0n1': 665}
2018-01-01 21:52:50,530 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,534 : INFO : < 200 OK [3263]
2018-01-01 21:52:50,542 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 753, '_0n1': 663}
2018-01-01 21:52:50,542 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,554 : INFO : < 200 OK [3228]
2018-01-01 21:52:50,558 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1037, '_0n1': 663}
2018-01-01 21:52:50,558 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,566 : INFO : < 200 OK [3238]
2018-01-01 21:52:50,570 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 782, '_0n1': 647}
2018-01-01 21:52:50,570 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,578 : INFO : < 200 OK [3211]
2018-01-01 21:52:50,582 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 758, '_0n1': 622}
2018-01-01 21:52:50,586 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,590 : INFO : < 200 OK [3219]
2018-01-01 21:52:50,590 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 872, '_0n1': 642}
2018-01-01 21:52:50,598 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,602 : INFO : < 200 OK [3252]
2018-01-01 21:52:50,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 722, '_0n1': 642}
2018-01-01 21:52:50,606 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,617 : INFO : < 200 OK [3257]
2018-01-01 21:52:50,620 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 920, '_0n1': 642}
2018-01-01 21:52:50,621 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,625 : INFO : < 200 OK [3251]
2018-01-01 21:52:50,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1094, '_0n1': 642}
2018-01-01 21:52:50,630 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,638 : INFO : < 200 OK [3267]
2018-01-01 21:52:50,638 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1052, '_0n1': 642}
2018-01-01 21:52:50,642 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,646 : INFO : < 200 OK [3270]
2018-01-01 21:52:50,650 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 816, '_0n1': 642}
2018-01-01 21:52:50,650 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,658 : INFO : < 200 OK [3254]
2018-01-01 21:52:50,658 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1179, '_0n1': 642}
2018-01-01 21:52:50,662 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,670 : INFO : < 200 OK [3268]
2018-01-01 21:52:50,670 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1073, '_0n1': 642}
2018-01-01 21:52:50,674 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,678 : INFO : < 200 OK [3271]
2018-01-01 21:52:50,686 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1201, '_0n1': 642}
2018-01-01 21:52:50,686 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,690 : INFO : < 200 OK [3271]
2018-01-01 21:52:50,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 799, '_0n1': 642}
2018-01-01 21:52:50,698 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,706 : INFO : < 200 OK [3255]
2018-01-01 21:52:50,710 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 743, '_0n1': 714}
2018-01-01 21:52:50,710 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,717 : INFO : < 200 OK [3223]

2018-01-01 21:52:50,720 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 939, '_0n1': 714}
2018-01-01 21:52:50,722 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,727 : INFO : < 200 OK [3224]
2018-01-01 21:52:50,730 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1126, '_0n1': 694}
2018-01-01 21:52:50,730 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,734 : INFO : < 200 OK [3232]
2018-01-01 21:52:50,738 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1027, '_0n1': 690}
2018-01-01 21:52:50,742 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,746 : INFO : < 200 OK [3212]
2018-01-01 21:52:50,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 959, '_0n1': 690}
2018-01-01 21:52:50,750 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,754 : INFO : < 200 OK [3209]
2018-01-01 21:52:50,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1163, '_0n1': 631}
2018-01-01 21:52:50,758 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,762 : INFO : < 200 OK [3243]
2018-01-01 21:52:50,762 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1046, '_0n1': 631}
2018-01-01 21:52:50,766 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,770 : INFO : < 200 OK [3247]
2018-01-01 21:52:50,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 811, '_0n1': 665}
2018-01-01 21:52:50,774 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,782 : INFO : < 200 OK [3240]
2018-01-01 21:52:50,782 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 925, '_0n1': 658}
2018-01-01 21:52:50,786 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,790 : INFO : < 200 OK [3225]
2018-01-01 21:52:50,794 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 854, '_0n1': 684}
2018-01-01 21:52:50,794 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,798 : INFO : < 200 OK [3209]
2018-01-01 21:52:50,802 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 988, '_0n1': 684}
2018-01-01 21:52:50,802 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,806 : INFO : < 200 OK [3205]
2018-01-01 21:52:50,810 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 787, '_0n1': 684}
2018-01-01 21:52:50,810 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,816 : INFO : < 200 OK [3200]
2018-01-01 21:52:50,818 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1087, '_0n1': 684}
2018-01-01 21:52:50,820 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,825 : INFO : < 200 OK [3218]
2018-01-01 21:52:50,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 981, '_0n1': 684}
2018-01-01 21:52:50,829 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,830 : INFO : < 200 OK [3202]
2018-01-01 21:52:50,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 819, '_0n1': 684}
2018-01-01 21:52:50,834 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,838 : INFO : < 200 OK [3202]
2018-01-01 21:52:50,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 985, '_0n1': 688}
2018-01-01 21:52:50,842 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,846 : INFO : < 200 OK [3236]
2018-01-01 21:52:50,850 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 979, '_0n1': 610}
2018-01-01 21:52:50,854 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,858 : INFO : < 200 OK [3249]
2018-01-01 21:52:50,862 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1114, '_0n1': 610}
2018-01-01 21:52:50,862 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,870 : INFO : < 200 OK [3262]
2018-01-01 21:52:50,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 986, '_0n1': 610}
2018-01-01 21:52:50,874 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,878 : INFO : < 200 OK [3249]
2018-01-01 21:52:50,878 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1028, '_0n1': 610}
2018-01-01 21:52:50,882 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,886 : INFO : < 200 OK [3262]
2018-01-01 21:52:50,886 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1190, '_0n1': 610}
2018-01-01 21:52:50,890 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,894 : INFO : < 200 OK [3270]
2018-01-01 21:52:50,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 975, '_0n1': 610}
2018-01-01 21:52:50,898 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,902 : INFO : < 200 OK [3246]
2018-01-01 21:52:50,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 817, '_0n1': 684}
2018-01-01 21:52:50,906 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,910 : INFO : < 200 OK [3205]
2018-01-01 21:52:50,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 729, '_0n1': 641}
2018-01-01 21:52:50,918 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,922 : INFO : < 200 OK [3199]
2018-01-01 21:52:50,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1122, '_0n1': 631}
2018-01-01 21:52:50,927 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,930 : INFO : < 200 OK [3247]

2018-01-01 21:52:50,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1189, '_0n1': 679}
2018-01-01 21:52:50,934 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,938 : INFO : < 200 OK [3242]
2018-01-01 21:52:50,942 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 721, '_0n1': 606}
2018-01-01 21:52:50,942 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,946 : INFO : < 200 OK [3219]
2018-01-01 21:52:50,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1191, '_0n1': 694}
2018-01-01 21:52:50,950 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,954 : INFO : < 200 OK [3237]
2018-01-01 21:52:50,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 929, '_0n1': 695}
2018-01-01 21:52:50,962 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,970 : INFO : < 200 OK [3215]
2018-01-01 21:52:50,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1113, '_0n1': 679}
2018-01-01 21:52:50,974 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,978 : INFO : < 200 OK [3242]
2018-01-01 21:52:50,982 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1078, '_0n1': 653}
2018-01-01 21:52:50,986 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:50,990 : INFO : < 200 OK [3225]
2018-01-01 21:52:50,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 750, '_0n1': 702}
2018-01-01 21:52:50,994 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:50,998 : INFO : < 200 OK [3225]
2018-01-01 21:52:51,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1148, '_0n1': 702}
2018-01-01 21:52:51,002 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,006 : INFO : < 200 OK [3236]
2018-01-01 21:52:51,010 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 876, '_0n1': 702}
2018-01-01 21:52:51,010 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,016 : INFO : < 200 OK [3220]
2018-01-01 21:52:51,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1068, '_0n1': 702}
2018-01-01 21:52:51,022 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,025 : INFO : < 200 OK [3237]
2018-01-01 21:52:51,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 698, '_0n1': 702}
2018-01-01 21:52:51,030 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,031 : INFO : < 200 OK [3219]
2018-01-01 21:52:51,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 697, '_0n1': 684}
2018-01-01 21:52:51,039 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,043 : INFO : < 200 OK [3205]
2018-01-01 21:52:51,043 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 889, '_0n1': 651}
2018-01-01 21:52:51,047 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,051 : INFO : < 200 OK [3233]
2018-01-01 21:52:51,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1169, '_0n1': 651}
2018-01-01 21:52:51,055 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,059 : INFO : < 200 OK [3243]
2018-01-01 21:52:51,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 918, '_0n1': 605}
2018-01-01 21:52:51,063 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,067 : INFO : < 200 OK [3224]
2018-01-01 21:52:51,071 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1180, '_0n1': 679}
2018-01-01 21:52:51,075 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,079 : INFO : < 200 OK [3233]
2018-01-01 21:52:51,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 971, '_0n1': 631}
2018-01-01 21:52:51,087 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,091 : INFO : < 200 OK [3231]
2018-01-01 21:52:51,091 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1030, '_0n1': 631}
2018-01-01 21:52:51,095 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,099 : INFO : < 200 OK [3247]
2018-01-01 21:52:51,103 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 741, '_0n1': 631}
2018-01-01 21:52:51,103 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,107 : INFO : < 200 OK [3230]
2018-01-01 21:52:51,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 859, '_0n1': 651}
2018-01-01 21:52:51,111 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,118 : INFO : < 200 OK [3225]
2018-01-01 21:52:51,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1153, '_0n1': 702}
2018-01-01 21:52:51,123 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,127 : INFO : < 200 OK [3235]
2018-01-01 21:52:51,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 777, '_0n1': 702}
2018-01-01 21:52:51,131 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,135 : INFO : < 200 OK [3220]
2018-01-01 21:52:51,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 834, '_0n1': 702}
2018-01-01 21:52:51,139 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,143 : INFO : < 200 OK [3221]
2018-01-01 21:52:51,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 893, '_0n1': 702}
2018-01-01 21:52:51,147 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,151 : INFO : < 200 OK [3224]
2018-01-01 21:52:51,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 733, '_0n1': 702}

2018-01-01 21:52:51,155 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,159 : INFO : < 200 OK [3230]
2018-01-01 21:52:51,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 916, '_0n1': 702}
2018-01-01 21:52:51,167 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,171 : INFO : < 200 OK [3221]
2018-01-01 21:52:51,171 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 899, '_0n1': 702}
2018-01-01 21:52:51,175 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,179 : INFO : < 200 OK [3218]
2018-01-01 21:52:51,183 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1162, '_0n1': 693}
2018-01-01 21:52:51,183 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,187 : INFO : < 200 OK [3224]
2018-01-01 21:52:51,191 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 852, '_0n1': 684}
2018-01-01 21:52:51,191 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,199 : INFO : < 200 OK [3210]
2018-01-01 21:52:51,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1026, '_0n1': 684}
2018-01-01 21:52:51,203 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,207 : INFO : < 200 OK [3219]
2018-01-01 21:52:51,211 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 943, '_0n1': 647}
2018-01-01 21:52:51,211 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,218 : INFO : < 200 OK [3220]
2018-01-01 21:52:51,221 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 747, '_0n1': 702}
2018-01-01 21:52:51,224 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,228 : INFO : < 200 OK [3223]
2018-01-01 21:52:51,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1160, '_0n1': 702}
2018-01-01 21:52:51,231 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,235 : INFO : < 200 OK [3245]
2018-01-01 21:52:51,239 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1133, '_0n1': 664}
2018-01-01 21:52:51,239 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,247 : INFO : < 200 OK [3237]
2018-01-01 21:52:51,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1091, '_0n1': 664}
2018-01-01 21:52:51,247 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,255 : INFO : < 200 OK [3235]
2018-01-01 21:52:51,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 968, '_0n1': 711}
2018-01-01 21:52:51,259 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,263 : INFO : < 200 OK [3228]
2018-01-01 21:52:51,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 718, '_0n1': 651}
2018-01-01 21:52:51,267 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,271 : INFO : < 200 OK [3228]
2018-01-01 21:52:51,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 855, '_0n1': 665}
2018-01-01 21:52:51,279 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,283 : INFO : < 200 OK [3238]
2018-01-01 21:52:51,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 775, '_0n1': 714}
2018-01-01 21:52:51,287 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,291 : INFO : < 200 OK [3216]
2018-01-01 21:52:51,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1171, '_0n1': 645}
2018-01-01 21:52:51,295 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,299 : INFO : < 200 OK [3249]
2018-01-01 21:52:51,303 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1061, '_0n1': 639}
2018-01-01 21:52:51,303 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,307 : INFO : < 200 OK [3245]
2018-01-01 21:52:51,311 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 954, '_0n1': 639}
2018-01-01 21:52:51,315 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,320 : INFO : < 200 OK [3229]
2018-01-01 21:52:51,324 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 952, '_0n1': 639}
2018-01-01 21:52:51,326 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,331 : INFO : < 200 OK [3227]
2018-01-01 21:52:51,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 906, '_0n1': 704}
2018-01-01 21:52:51,335 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,339 : INFO : < 200 OK [3220]
2018-01-01 21:52:51,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 856, '_0n1': 702}
2018-01-01 21:52:51,343 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,347 : INFO : < 200 OK [3224]
2018-01-01 21:52:51,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 976, '_0n1': 702}
2018-01-01 21:52:51,351 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,355 : INFO : < 200 OK [3229]
2018-01-01 21:52:51,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 994, '_0n1': 665}
2018-01-01 21:52:51,363 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,367 : INFO : < 200 OK [3235]
2018-01-01 21:52:51,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1124, '_0n1': 652}
2018-01-01 21:52:51,371 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,379 : INFO : < 200 OK [3233]
2018-01-01 21:52:51,383 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 933, '_0n1': 652}
2018-01-01 21:52:51,383 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,387 : INFO : < 200 OK [3219]
2018-01-01 21:52:51,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1182, '_0n1': 704}

2018-01-01 21:52:51,391 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,395 : INFO : < 200 OK [3235]
2018-01-01 21:52:51,399 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1045, '_0n1': 626}
2018-01-01 21:52:51,399 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,403 : INFO : < 200 OK [3280]
2018-01-01 21:52:51,407 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 972, '_0n1': 626}
2018-01-01 21:52:51,411 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,415 : INFO : < 200 OK [3248]
2018-01-01 21:52:51,417 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1129, '_0n1': 680}
2018-01-01 21:52:51,420 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,423 : INFO : < 200 OK [3233]
2018-01-01 21:52:51,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1101, '_0n1': 694}
2018-01-01 21:52:51,428 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,430 : INFO : < 200 OK [3241]
2018-01-01 21:52:51,434 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 742, '_0n1': 605}
2018-01-01 21:52:51,434 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,438 : INFO : < 200 OK [3222]
2018-01-01 21:52:51,442 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 791, '_0n1': 711}
2018-01-01 21:52:51,442 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,446 : INFO : < 200 OK [3222]
2018-01-01 21:52:51,450 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1089, '_0n1': 646}
2018-01-01 21:52:51,450 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,454 : INFO : < 200 OK [3223]
2018-01-01 21:52:51,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 783, '_0n1': 674}
2018-01-01 21:52:51,462 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,466 : INFO : < 200 OK [3218]
2018-01-01 21:52:51,466 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1116, '_0n1': 711}
2018-01-01 21:52:51,466 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,474 : INFO : < 200 OK [3241]
2018-01-01 21:52:51,474 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1130, '_0n1': 709}
2018-01-01 21:52:51,478 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,482 : INFO : < 200 OK [3242]
2018-01-01 21:52:51,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 823, '_0n1': 690}
2018-01-01 21:52:51,490 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,494 : INFO : < 200 OK [3200]
2018-01-01 21:52:51,498 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 813, '_0n1': 694}
2018-01-01 21:52:51,502 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,506 : INFO : < 200 OK [3229]
2018-01-01 21:52:51,506 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1143, '_0n1': 694}
2018-01-01 21:52:51,510 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,514 : INFO : < 200 OK [3244]
2018-01-01 21:52:51,519 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1138, '_0n1': 694}
2018-01-01 21:52:51,520 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,524 : INFO : < 200 OK [3241]
2018-01-01 21:52:51,526 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 898, '_0n1': 609}
2018-01-01 21:52:51,528 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,531 : INFO : < 200 OK [3239]
2018-01-01 21:52:51,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1021, '_0n1': 636}
2018-01-01 21:52:51,535 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,539 : INFO : < 200 OK [3255]
2018-01-01 21:52:51,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 846, '_0n1': 636}
2018-01-01 21:52:51,543 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,551 : INFO : < 200 OK [3233]
2018-01-01 21:52:51,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 825, '_0n1': 640}
2018-01-01 21:52:51,559 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,563 : INFO : < 200 OK [3248]
2018-01-01 21:52:51,567 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 936, '_0n1': 676}
2018-01-01 21:52:51,567 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,575 : INFO : < 200 OK [3214]
2018-01-01 21:52:51,583 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1035, '_0n1': 694}
2018-01-01 21:52:51,583 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,591 : INFO : < 200 OK [3239]
2018-01-01 21:52:51,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 720, '_0n1': 624}
2018-01-01 21:52:51,599 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,607 : INFO : < 200 OK [3270]
2018-01-01 21:52:51,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1074, '_0n1': 624}
2018-01-01 21:52:51,611 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,622 : INFO : < 200 OK [3285]
2018-01-01 21:52:51,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 913, '_0n1': 628}
2018-01-01 21:52:51,626 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,631 : INFO : < 200 OK [3221]
2018-01-01 21:52:51,635 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 727, '_0n1': 628}
2018-01-01 21:52:51,635 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,639 : INFO : < 200 OK [3220]
2018-01-01 21:52:51,647 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1023, '_0n1': 683}

2018-01-01 21:52:51,651 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,655 : INFO : < 200 OK [3240]
2018-01-01 21:52:51,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1202, '_0n1': 683}
2018-01-01 21:52:51,659 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,667 : INFO : < 200 OK [3239]
2018-01-01 21:52:51,671 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 807, '_0n1': 634}
2018-01-01 21:52:51,671 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,679 : INFO : < 200 OK [3237]
2018-01-01 21:52:51,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 723, '_0n1': 634}
2018-01-01 21:52:51,687 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,691 : INFO : < 200 OK [3241]
2018-01-01 21:52:51,695 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1033, '_0n1': 694}
2018-01-01 21:52:51,695 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,703 : INFO : < 200 OK [3241]
2018-01-01 21:52:51,707 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 802, '_0n1': 713}
2018-01-01 21:52:51,707 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,711 : INFO : < 200 OK [3234]
2018-01-01 21:52:51,719 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1149, '_0n1': 694}
2018-01-01 21:52:51,720 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,725 : INFO : < 200 OK [3247]
2018-01-01 21:52:51,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1024, '_0n1': 625}
2018-01-01 21:52:51,731 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,735 : INFO : < 200 OK [3260]
2018-01-01 21:52:51,739 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 865, '_0n1': 659}
2018-01-01 21:52:51,739 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,743 : INFO : < 200 OK [3221]
2018-01-01 21:52:51,751 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 997, '_0n1': 636}
2018-01-01 21:52:51,751 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,755 : INFO : < 200 OK [3242]
2018-01-01 21:52:51,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1067, '_0n1': 654}
2018-01-01 21:52:51,767 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,771 : INFO : < 200 OK [3248]
2018-01-01 21:52:51,775 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 917, '_0n1': 658}
2018-01-01 21:52:51,779 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,783 : INFO : < 200 OK [3236]
2018-01-01 21:52:51,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 966, '_0n1': 672}
2018-01-01 21:52:51,787 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,795 : INFO : < 200 OK [3245]
2018-01-01 21:52:51,795 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1157, '_0n1': 609}
2018-01-01 21:52:51,799 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,803 : INFO : < 200 OK [3252]
2018-01-01 21:52:51,807 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1105, '_0n1': 691}
2018-01-01 21:52:51,811 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,817 : INFO : < 200 OK [3255]
2018-01-01 21:52:51,820 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1042, '_0n1': 625}
2018-01-01 21:52:51,822 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,826 : INFO : < 200 OK [3264]
2018-01-01 21:52:51,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1079, '_0n1': 665}
2018-01-01 21:52:51,830 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,831 : INFO : < 200 OK [3254]
2018-01-01 21:52:51,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1050, '_0n1': 702}
2018-01-01 21:52:51,839 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,843 : INFO : < 200 OK [3246]
2018-01-01 21:52:51,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 935, '_0n1': 651}
2018-01-01 21:52:51,847 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,855 : INFO : < 200 OK [3225]
2018-01-01 21:52:51,855 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 755, '_0n1': 690}
2018-01-01 21:52:51,859 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,863 : INFO : < 200 OK [3194]
2018-01-01 21:52:51,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 944, '_0n1': 690}
2018-01-01 21:52:51,871 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,875 : INFO : < 200 OK [3197]
2018-01-01 21:52:51,879 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1077, '_0n1': 664}
2018-01-01 21:52:51,883 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,887 : INFO : < 200 OK [3231]
2018-01-01 21:52:51,891 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 989, '_0n1': 664}
2018-01-01 21:52:51,891 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,899 : INFO : < 200 OK [3220]
2018-01-01 21:52:51,903 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1170, '_0n1': 622}
2018-01-01 21:52:51,903 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,911 : INFO : < 200 OK [3236]
2018-01-01 21:52:51,917 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 848, '_0n1': 622}
2018-01-01 21:52:51,919 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,923 : INFO : < 200 OK [3214]
2018-01-01 21:52:51,926 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 789, '_0n1': 708}

2018-01-01 21:52:51,929 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,931 : INFO : < 200 OK [3211]
2018-01-01 21:52:51,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1139, '_0n1': 640}
2018-01-01 21:52:51,939 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,943 : INFO : < 200 OK [3255]
2018-01-01 21:52:51,947 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1107, '_0n1': 677}
2018-01-01 21:52:51,951 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,955 : INFO : < 200 OK [3242]
2018-01-01 21:52:51,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 790, '_0n1': 655}
2018-01-01 21:52:51,959 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,963 : INFO : < 200 OK [3249]
2018-01-01 21:52:51,967 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 749, '_0n1': 655}
2018-01-01 21:52:51,967 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,971 : INFO : < 200 OK [3256]
2018-01-01 21:52:51,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1175, '_0n1': 709}
2018-01-01 21:52:51,975 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:51,983 : INFO : < 200 OK [3255]
2018-01-01 21:52:51,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 868, '_0n1': 679}
2018-01-01 21:52:51,987 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:51,991 : INFO : < 200 OK [3230]
2018-01-01 21:52:51,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 934, '_0n1': 692}
2018-01-01 21:52:51,999 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,003 : INFO : < 200 OK [3218]
2018-01-01 21:52:52,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 831, '_0n1': 653}
2018-01-01 21:52:52,007 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,011 : INFO : < 200 OK [3210]
2018-01-01 21:52:52,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 746, '_0n1': 675}
2018-01-01 21:52:52,019 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,022 : INFO : < 200 OK [3210]
2018-01-01 21:52:52,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 890, '_0n1': 687}
2018-01-01 21:52:52,028 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,031 : INFO : < 200 OK [3253]
2018-01-01 21:52:52,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1146, '_0n1': 687}
2018-01-01 21:52:52,039 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:52,043 : INFO : < 200 OK [3280]
2018-01-01 21:52:52,047 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 793, '_0n1': 690}
2018-01-01 21:52:52,047 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,051 : INFO : < 200 OK [3198]
2018-01-01 21:52:52,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 996, '_0n1': 690}
2018-01-01 21:52:52,055 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,059 : INFO : < 200 OK [3200]
2018-01-01 21:52:52,063 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 735, '_0n1': 690}
2018-01-01 21:52:52,067 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,071 : INFO : < 200 OK [3198]
2018-01-01 21:52:52,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1041, '_0n1': 640}
2018-01-01 21:52:52,075 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:52,079 : INFO : < 200 OK [3260]
2018-01-01 21:52:52,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 860, '_0n1': 640}
2018-01-01 21:52:52,083 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,091 : INFO : < 200 OK [3249]
2018-01-01 21:52:52,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 895, '_0n1': 709}
2018-01-01 21:52:52,099 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,103 : INFO : < 200 OK [3235]
2018-01-01 21:52:52,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 800, '_0n1': 658}
2018-01-01 21:52:52,111 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,120 : INFO : < 200 OK [3217]
2018-01-01 21:52:52,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 840, '_0n1': 611}
2018-01-01 21:52:52,126 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,131 : INFO : < 200 OK [3205]
2018-01-01 21:52:52,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1181, '_0n1': 675}
2018-01-01 21:52:52,135 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:52,139 : INFO : < 200 OK [3222]
2018-01-01 21:52:52,143 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 877, '_0n1': 709}
2018-01-01 21:52:52,147 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,151 : INFO : < 200 OK [3224]
2018-01-01 21:52:52,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 905, '_0n1': 628}
2018-01-01 21:52:52,155 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,159 : INFO : < 200 OK [3224]

In [68]:
for i, row in data.drop_duplicates(subset=['uid', 'teach_by']).iterrows():
    x = teach_dict[row.teach_by]
    y = course_dict[row.uid]
    graph.create(Relationship(x, "teach", y))

2018-01-01 21:52:52,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1228, '_0n1': 1047}
2018-01-01 21:52:52,331 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,345 : INFO : < 200 OK [3309]
2018-01-01 21:52:52,349 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1246, '_0n1': 751}
2018-01-01 21:52:52,349 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,353 : INFO : < 200 OK [3264]
2018-01-01 21:52:52,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1229, '_0n1': 1119}
2018-01-01 21:52:52,357 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,361 : INFO : < 200 OK [3365]
2018-01-01 21:52:52,365 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1247, '_0n1': 1119}
2018-01-01 21:52:52,365 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,369 : INFO : < 200 OK [3338]
2018-01-01 21:52:52,373 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1230, '_0n1': 869}
2018-01-01 21:52:52,373 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,377 : INFO : < 200 OK [3270]
2018-01-01 21:52:52,381 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1248, '_0n1': 726}
2018-01-01 21:52:52,381 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,385 : INFO : < 200 OK [3324]
2018-01-01 21:52:52,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1231, '_0n1': 901}
2018-01-01 21:52:52,393 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,397 : INFO : < 200 OK [3318]
2018-01-01 21:52:52,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1249, '_0n1': 931}
2018-01-01 21:52:52,401 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,405 : INFO : < 200 OK [3318]
2018-01-01 21:52:52,409 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1232, '_0n1': 1118}
2018-01-01 21:52:52,409 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,413 : INFO : < 200 OK [3322]
2018-01-01 21:52:52,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1250, '_0n1': 1119}
2018-01-01 21:52:52,421 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,424 : INFO : < 200 OK [3352]
2018-01-01 21:52:52,427 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1233, '_0n1': 990}
2018-01-01 21:52:52,428 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,431 : INFO : < 200 OK [3271]
2018-01-01 21:52:52,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1251, '_0n1': 1119}
2018-01-01 21:52:52,439 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,447 : INFO : < 200 OK [3355]
2018-01-01 21:52:52,451 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1234, '_0n1': 974}
2018-01-01 21:52:52,455 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,467 : INFO : < 200 OK [3280]
2018-01-01 21:52:52,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1252, '_0n1': 930}
2018-01-01 21:52:52,471 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,475 : INFO : < 200 OK [3342]
2018-01-01 21:52:52,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1252, '_0n1': 1173}
2018-01-01 21:52:52,483 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,487 : INFO : < 200 OK [3355]
2018-01-01 21:52:52,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1252, '_0n1': 795}
2018-01-01 21:52:52,491 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,495 : INFO : < 200 OK [3335]
2018-01-01 21:52:52,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1235, '_0n1': 1119}
2018-01-01 21:52:52,499 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,503 : INFO : < 200 OK [3362]
2018-01-01 21:52:52,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1253, '_0n1': 726}
2018-01-01 21:52:52,507 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,515 : INFO : < 200 OK [3319]
2018-01-01 21:52:52,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1236, '_0n1': 1119}
2018-01-01 21:52:52,519 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,523 : INFO : < 200 OK [3363]
2018-01-01 21:52:52,526 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1254, '_0n1': 1112}
2018-01-01 21:52:52,527 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,531 : INFO : < 200 OK [3336]
2018-01-01 21:52:52,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1237, '_0n1': 748}
2018-01-01 21:52:52,535 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,539 : INFO : < 200 OK [3323]
2018-01-01 21:52:52,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1255, '_0n1': 826}
2018-01-01 21:52:52,547 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,555 : INFO : < 200 OK [3359]
2018-01-01 21:52:52,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1255, '_0n1': 805}
2018-01-01 21:52:52,559 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,567 : INFO : < 200 OK [3356]
2018-01-01 21:52:52,575 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1238, '_0n1': 1031}
2018-01-01 21:52:52,575 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,579 : INFO : < 200 OK [3275]
2018-01-01 21:52:52,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1256, '_0n1': 748}

2018-01-01 21:52:52,587 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,591 : INFO : < 200 OK [3325]
2018-01-01 21:52:52,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1239, '_0n1': 1119}
2018-01-01 21:52:52,595 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:52:52,603 : INFO : < 200 OK [3374]
2018-01-01 21:52:52,603 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1259, '_0n1': 974}
2018-01-01 21:52:52,607 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,611 : INFO : < 200 OK [3328]
2018-01-01 21:52:52,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1240, '_0n1': 726}
2018-01-01 21:52:52,618 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,622 : INFO : < 200 OK [3307]
2018-01-01 21:52:52,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1260, '_0n1': 830}
2018-01-01 21:52:52,627 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,631 : INFO : < 200 OK [3284]
2018-01-01 21:52:52,631 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 0, '_0n1': 908}
2018-01-01 21:52:52,635 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:52:52,639 : INFO : < 200 OK [3254]
2018-01-01 21:52:52,643 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1301, '_0n1': 726}
2018-01-01 21:52:52,643 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,647 : INFO : < 200 OK [3317]
2018-01-01 21:52:52,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1, '_0n1': 1144}
2018-01-01 21:52:52,651 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,655 : INFO : < 200 OK [3236]
2018-01-01 21:52:52,659 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1302, '_0n1': 726}
2018-01-01 21:52:52,659 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:52,663 : INFO : < 200 OK [3325]
2018-01-01 21:52:52,667 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 805}
2018-01-01 21:52:52,667 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:52:52,671 : INFO : < 200 OK [3283]
2018-01-01 21:52:52,675 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 826}
2018-01-01 21:52:52,675 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:52:52,679 : INFO : < 200 OK [3286]
2018-01-01 21:52:52,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 20, '_0n1': 1022}
2018-01-01 21:52:52,683 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:52,687 : INFO : < 200 OK [3309]
2018-01-01 21:52:52,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 3, '_0n1': 1118}
2018-01-01 21:52:52,691 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,695 : INFO : < 200 OK [3279]
2018-01-01 21:52:52,699 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 21, '_0n1': 1119}
2018-01-01 21:52:52,699 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:52,703 : INFO : < 200 OK [3325]
2018-01-01 21:52:52,707 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 4, '_0n1': 748}
2018-01-01 21:52:52,707 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:52:52,711 : INFO : < 200 OK [3280]
2018-01-01 21:52:52,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 22, '_0n1': 829}
2018-01-01 21:52:52,719 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,724 : INFO : < 200 OK [3245]
2018-01-01 21:52:52,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 22, '_0n1': 897}
2018-01-01 21:52:52,729 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,731 : INFO : < 200 OK [3238]
2018-01-01 21:52:52,735 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 5, '_0n1': 1119}
2018-01-01 21:52:52,739 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,743 : INFO : < 200 OK [3314]
2018-01-01 21:52:52,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 6, '_0n1': 1176}
2018-01-01 21:52:52,747 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,755 : INFO : < 200 OK [3293]
2018-01-01 21:52:52,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 6, '_0n1': 941}
2018-01-01 21:52:52,763 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:52:52,767 : INFO : < 200 OK [3279]
2018-01-01 21:52:52,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 6, '_0n1': 1022}
2018-01-01 21:52:52,771 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,775 : INFO : < 200 OK [3296]
2018-01-01 21:52:52,779 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 23, '_0n1': 866}
2018-01-01 21:52:52,779 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,783 : INFO : < 200 OK [3234]
2018-01-01 21:52:52,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 24, '_0n1': 748}
2018-01-01 21:52:52,787 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,791 : INFO : < 200 OK [3285]
2018-01-01 21:52:52,795 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 7, '_0n1': 1118}
2018-01-01 21:52:52,795 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,799 : INFO : < 200 OK [3270]
2018-01-01 21:52:52,803 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 25, '_0n1': 1112}
2018-01-01 21:52:52,807 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:52,811 : INFO : < 200 OK [3262]
2018-01-01 21:52:52,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 8, '_0n1': 1056}

2018-01-01 21:52:52,817 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,821 : INFO : < 200 OK [3290]
2018-01-01 21:52:52,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 8, '_0n1': 844}
2018-01-01 21:52:52,826 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:52:52,830 : INFO : < 200 OK [3271]
2018-01-01 21:52:52,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 26, '_0n1': 931}
2018-01-01 21:52:52,832 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,836 : INFO : < 200 OK [3292]
2018-01-01 21:52:52,840 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 9, '_0n1': 809}
2018-01-01 21:52:52,840 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:52:52,844 : INFO : < 200 OK [3235]
2018-01-01 21:52:52,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 9, '_0n1': 1070}
2018-01-01 21:52:52,848 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,852 : INFO : < 200 OK [3253]
2018-01-01 21:52:52,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 27, '_0n1': 974}
2018-01-01 21:52:52,860 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,864 : INFO : < 200 OK [3280]
2018-01-01 21:52:52,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 10, '_0n1': 1176}
2018-01-01 21:52:52,868 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:52,872 : INFO : < 200 OK [3308]
2018-01-01 21:52:52,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 10, '_0n1': 941}
2018-01-01 21:52:52,876 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,880 : INFO : < 200 OK [3294]
2018-01-01 21:52:52,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 10, '_0n1': 1022}
2018-01-01 21:52:52,884 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:52,888 : INFO : < 200 OK [3311]
2018-01-01 21:52:52,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 28, '_0n1': 748}
2018-01-01 21:52:52,892 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,896 : INFO : < 200 OK [3266]
2018-01-01 21:52:52,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 11, '_0n1': 901}
2018-01-01 21:52:52,900 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,904 : INFO : < 200 OK [3300]
2018-01-01 21:52:52,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 11, '_0n1': 914}
2018-01-01 21:52:52,908 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,912 : INFO : < 200 OK [3298]
2018-01-01 21:52:52,917 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 11, '_0n1': 1049}
2018-01-01 21:52:52,918 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:52,922 : INFO : < 200 OK [3312]
2018-01-01 21:52:52,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 11, '_0n1': 871}
2018-01-01 21:52:52,927 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,931 : INFO : < 200 OK [3326]
2018-01-01 21:52:52,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 11, '_0n1': 756}
2018-01-01 21:52:52,936 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,940 : INFO : < 200 OK [3318]
2018-01-01 21:52:52,944 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 29, '_0n1': 931}
2018-01-01 21:52:52,944 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,948 : INFO : < 200 OK [3286]
2018-01-01 21:52:52,956 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 12, '_0n1': 931}
2018-01-01 21:52:52,956 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,964 : INFO : < 200 OK [3302]
2018-01-01 21:52:52,968 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 30, '_0n1': 748}
2018-01-01 21:52:52,968 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,976 : INFO : < 200 OK [3303]
2018-01-01 21:52:52,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 13, '_0n1': 780}
2018-01-01 21:52:52,980 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,984 : INFO : < 200 OK [3273]
2018-01-01 21:52:52,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 13, '_0n1': 740}
2018-01-01 21:52:52,988 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:52,996 : INFO : < 200 OK [3274]
2018-01-01 21:52:52,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 31, '_0n1': 1119}
2018-01-01 21:52:53,000 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,004 : INFO : < 200 OK [3336]
2018-01-01 21:52:53,004 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 14, '_0n1': 1056}
2018-01-01 21:52:53,008 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,012 : INFO : < 200 OK [3317]
2018-01-01 21:52:53,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 32, '_0n1': 1112}
2018-01-01 21:52:53,018 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,022 : INFO : < 200 OK [3257]
2018-01-01 21:52:53,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 15, '_0n1': 904}
2018-01-01 21:52:53,028 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,032 : INFO : < 200 OK [3256]
2018-01-01 21:52:53,032 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 15, '_0n1': 1040}
2018-01-01 21:52:53,036 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,040 : INFO : < 200 OK [3279]
2018-01-01 21:52:53,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 33, '_0n1': 1022}

2018-01-01 21:52:53,044 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,048 : INFO : < 200 OK [3271]
2018-01-01 21:52:53,052 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 16, '_0n1': 974}
2018-01-01 21:52:53,052 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,060 : INFO : < 200 OK [3300]
2018-01-01 21:52:53,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 34, '_0n1': 1112}
2018-01-01 21:52:53,064 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,068 : INFO : < 200 OK [3284]
2018-01-01 21:52:53,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 17, '_0n1': 1140}
2018-01-01 21:52:53,072 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,076 : INFO : < 200 OK [3323]
2018-01-01 21:52:53,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 17, '_0n1': 734}
2018-01-01 21:52:53,080 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,084 : INFO : < 200 OK [3310]
2018-01-01 21:52:53,088 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 35, '_0n1': 1022}
2018-01-01 21:52:53,088 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,092 : INFO : < 200 OK [3291]
2018-01-01 21:52:53,096 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 18, '_0n1': 937}
2018-01-01 21:52:53,096 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,100 : INFO : < 200 OK [3304]
2018-01-01 21:52:53,104 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 18, '_0n1': 1016}
2018-01-01 21:52:53,104 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,108 : INFO : < 200 OK [3326]
2018-01-01 21:52:53,112 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 36, '_0n1': 748}
2018-01-01 21:52:53,117 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,121 : INFO : < 200 OK [3280]
2018-01-01 21:52:53,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 19, '_0n1': 1118}
2018-01-01 21:52:53,126 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,130 : INFO : < 200 OK [3270]
2018-01-01 21:52:53,132 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 37, '_0n1': 1022}
2018-01-01 21:52:53,132 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,136 : INFO : < 200 OK [3292]
2018-01-01 21:52:53,140 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 40, '_0n1': 901}
2018-01-01 21:52:53,140 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,144 : INFO : < 200 OK [3282]
2018-01-01 21:52:53,148 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 38, '_0n1': 1040}
2018-01-01 21:52:53,148 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,152 : INFO : < 200 OK [3322]
2018-01-01 21:52:53,156 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 38, '_0n1': 904}
2018-01-01 21:52:53,156 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,160 : INFO : < 200 OK [3299]
2018-01-01 21:52:53,164 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 41, '_0n1': 748}
2018-01-01 21:52:53,164 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,168 : INFO : < 200 OK [3285]
2018-01-01 21:52:53,172 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 39, '_0n1': 941}
2018-01-01 21:52:53,176 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,180 : INFO : < 200 OK [3328]
2018-01-01 21:52:53,184 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 42, '_0n1': 736}
2018-01-01 21:52:53,184 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,188 : INFO : < 200 OK [3253]
2018-01-01 21:52:53,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 60, '_0n1': 1102}
2018-01-01 21:52:53,192 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,196 : INFO : < 200 OK [3344]
2018-01-01 21:52:53,200 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 43, '_0n1': 941}
2018-01-01 21:52:53,200 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,204 : INFO : < 200 OK [3314]
2018-01-01 21:52:53,208 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 61, '_0n1': 845}
2018-01-01 21:52:53,208 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,216 : INFO : < 200 OK [3267]
2018-01-01 21:52:53,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 61, '_0n1': 1051}
2018-01-01 21:52:53,220 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,225 : INFO : < 200 OK [3280]
2018-01-01 21:52:53,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 44, '_0n1': 941}
2018-01-01 21:52:53,229 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,232 : INFO : < 200 OK [3294]
2018-01-01 21:52:53,236 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 62, '_0n1': 901}
2018-01-01 21:52:53,236 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,240 : INFO : < 200 OK [3286]
2018-01-01 21:52:53,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 62, '_0n1': 914}
2018-01-01 21:52:53,244 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,252 : INFO : < 200 OK [3284]
2018-01-01 21:52:53,256 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 62, '_0n1': 871}
2018-01-01 21:52:53,256 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,260 : INFO : < 200 OK [3312]
2018-01-01 21:52:53,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 62, '_0n1': 1049}

2018-01-01 21:52:53,264 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,272 : INFO : < 200 OK [3298]
2018-01-01 21:52:53,272 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 62, '_0n1': 756}
2018-01-01 21:52:53,276 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,276 : INFO : < 200 OK [3304]
2018-01-01 21:52:53,280 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 45, '_0n1': 1118}
2018-01-01 21:52:53,284 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,288 : INFO : < 200 OK [3272]
2018-01-01 21:52:53,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 63, '_0n1': 941}
2018-01-01 21:52:53,292 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,300 : INFO : < 200 OK [3314]
2018-01-01 21:52:53,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 46, '_0n1': 1119}
2018-01-01 21:52:53,308 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,312 : INFO : < 200 OK [3340]
2018-01-01 21:52:53,319 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 64, '_0n1': 984}
2018-01-01 21:52:53,321 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,326 : INFO : < 200 OK [3247]
2018-01-01 21:52:53,329 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 64, '_0n1': 826}
2018-01-01 21:52:53,332 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,336 : INFO : < 200 OK [3248]
2018-01-01 21:52:53,340 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 64, '_0n1': 829}
2018-01-01 21:52:53,340 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,344 : INFO : < 200 OK [3252]
2018-01-01 21:52:53,348 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 64, '_0n1': 897}
2018-01-01 21:52:53,348 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,352 : INFO : < 200 OK [3245]
2018-01-01 21:52:53,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 47, '_0n1': 901}
2018-01-01 21:52:53,360 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,364 : INFO : < 200 OK [3295]
2018-01-01 21:52:53,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 47, '_0n1': 914}
2018-01-01 21:52:53,368 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,372 : INFO : < 200 OK [3293]
2018-01-01 21:52:53,372 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 47, '_0n1': 871}
2018-01-01 21:52:53,376 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,380 : INFO : < 200 OK [3321]
2018-01-01 21:52:53,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 47, '_0n1': 1049}
2018-01-01 21:52:53,384 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,388 : INFO : < 200 OK [3307]
2018-01-01 21:52:53,392 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 47, '_0n1': 756}
2018-01-01 21:52:53,396 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,400 : INFO : < 200 OK [3313]
2018-01-01 21:52:53,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 65, '_0n1': 869}
2018-01-01 21:52:53,404 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,408 : INFO : < 200 OK [3289]
2018-01-01 21:52:53,412 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 48, '_0n1': 908}
2018-01-01 21:52:53,416 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,421 : INFO : < 200 OK [3276]
2018-01-01 21:52:53,425 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 48, '_0n1': 1081}
2018-01-01 21:52:53,428 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,432 : INFO : < 200 OK [3295]
2018-01-01 21:52:53,436 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 782}
2018-01-01 21:52:53,436 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,440 : INFO : < 200 OK [3286]
2018-01-01 21:52:53,444 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 737}
2018-01-01 21:52:53,444 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,448 : INFO : < 200 OK [3320]
2018-01-01 21:52:53,452 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 1048}
2018-01-01 21:52:53,456 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,460 : INFO : < 200 OK [3335]
2018-01-01 21:52:53,460 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 782}
2018-01-01 21:52:53,464 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,468 : INFO : < 200 OK [3282]
2018-01-01 21:52:53,472 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 737}
2018-01-01 21:52:53,472 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,476 : INFO : < 200 OK [3316]
2018-01-01 21:52:53,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 1048}
2018-01-01 21:52:53,480 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,484 : INFO : < 200 OK [3331]
2018-01-01 21:52:53,488 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 67, '_0n1': 782}
2018-01-01 21:52:53,488 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,492 : INFO : < 200 OK [3335]
2018-01-01 21:52:53,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 67, '_0n1': 737}
2018-01-01 21:52:53,496 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,500 : INFO : < 200 OK [3369]
2018-01-01 21:52:53,504 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 67, '_0n1': 1048}

2018-01-01 21:52:53,508 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,512 : INFO : < 200 OK [3384]
2018-01-01 21:52:53,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 50, '_0n1': 757}
2018-01-01 21:52:53,517 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,521 : INFO : < 200 OK [3273]
2018-01-01 21:52:53,524 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 50, '_0n1': 1062}
2018-01-01 21:52:53,526 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,530 : INFO : < 200 OK [3293]
2018-01-01 21:52:53,532 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1184}
2018-01-01 21:52:53,532 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,540 : INFO : < 200 OK [3298]
2018-01-01 21:52:53,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 998}
2018-01-01 21:52:53,544 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,548 : INFO : < 200 OK [3276]
2018-01-01 21:52:53,552 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 950}
2018-01-01 21:52:53,552 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,556 : INFO : < 200 OK [3274]
2018-01-01 21:52:53,560 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1053}
2018-01-01 21:52:53,560 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,568 : INFO : < 200 OK [3292]
2018-01-01 21:52:53,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 778}
2018-01-01 21:52:53,572 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,576 : INFO : < 200 OK [3276]
2018-01-01 21:52:53,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 51, '_0n1': 782}
2018-01-01 21:52:53,580 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,584 : INFO : < 200 OK [3243]
2018-01-01 21:52:53,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 51, '_0n1': 737}
2018-01-01 21:52:53,588 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,592 : INFO : < 200 OK [3277]
2018-01-01 21:52:53,596 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 51, '_0n1': 1048}
2018-01-01 21:52:53,596 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,600 : INFO : < 200 OK [3292]
2018-01-01 21:52:53,604 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 69, '_0n1': 953}
2018-01-01 21:52:53,604 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,608 : INFO : < 200 OK [3327]
2018-01-01 21:52:53,612 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 822}
2018-01-01 21:52:53,612 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,619 : INFO : < 200 OK [3284]
2018-01-01 21:52:53,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 978}
2018-01-01 21:52:53,623 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,627 : INFO : < 200 OK [3284]
2018-01-01 21:52:53,631 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 956}
2018-01-01 21:52:53,632 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,636 : INFO : < 200 OK [3284]
2018-01-01 21:52:53,640 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 1136}
2018-01-01 21:52:53,640 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,644 : INFO : < 200 OK [3297]
2018-01-01 21:52:53,648 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 1062}
2018-01-01 21:52:53,648 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,652 : INFO : < 200 OK [3294]
2018-01-01 21:52:53,656 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 757}
2018-01-01 21:52:53,656 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,660 : INFO : < 200 OK [3274]
2018-01-01 21:52:53,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1184}
2018-01-01 21:52:53,664 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,672 : INFO : < 200 OK [3293]
2018-01-01 21:52:53,672 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 998}
2018-01-01 21:52:53,676 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,680 : INFO : < 200 OK [3271]
2018-01-01 21:52:53,684 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 778}
2018-01-01 21:52:53,684 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,688 : INFO : < 200 OK [3271]
2018-01-01 21:52:53,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 950}
2018-01-01 21:52:53,692 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,696 : INFO : < 200 OK [3269]
2018-01-01 21:52:53,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 71, '_0n1': 786}
2018-01-01 21:52:53,700 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,704 : INFO : < 200 OK [3317]
2018-01-01 21:52:53,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 71, '_0n1': 948}
2018-01-01 21:52:53,712 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,716 : INFO : < 200 OK [3313]
2018-01-01 21:52:53,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 54, '_0n1': 1025}
2018-01-01 21:52:53,720 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,724 : INFO : < 200 OK [3295]

2018-01-01 21:52:53,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 54, '_0n1': 903}
2018-01-01 21:52:53,728 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,732 : INFO : < 200 OK [3281]
2018-01-01 21:52:53,732 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 54, '_0n1': 887}
2018-01-01 21:52:53,736 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,740 : INFO : < 200 OK [3274]
2018-01-01 21:52:53,744 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 72, '_0n1': 984}
2018-01-01 21:52:53,744 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,748 : INFO : < 200 OK [3285]
2018-01-01 21:52:53,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 55, '_0n1': 1206}
2018-01-01 21:52:53,752 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,756 : INFO : < 200 OK [3298]
2018-01-01 21:52:53,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 73, '_0n1': 1099}
2018-01-01 21:52:53,760 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,764 : INFO : < 200 OK [3316]
2018-01-01 21:52:53,768 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 1184}
2018-01-01 21:52:53,768 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,772 : INFO : < 200 OK [3291]
2018-01-01 21:52:53,776 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 998}
2018-01-01 21:52:53,776 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,784 : INFO : < 200 OK [3269]
2018-01-01 21:52:53,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 902}
2018-01-01 21:52:53,788 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,792 : INFO : < 200 OK [3274]
2018-01-01 21:52:53,792 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 74, '_0n1': 1135}
2018-01-01 21:52:53,796 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,800 : INFO : < 200 OK [3272]
2018-01-01 21:52:53,804 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 57, '_0n1': 1072}
2018-01-01 21:52:53,804 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,817 : INFO : < 200 OK [3282]
2018-01-01 21:52:53,820 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 75, '_0n1': 833}
2018-01-01 21:52:53,822 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,827 : INFO : < 200 OK [3310]
2018-01-01 21:52:53,831 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 75, '_0n1': 909}
2018-01-01 21:52:53,832 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,836 : INFO : < 200 OK [3306]
2018-01-01 21:52:53,840 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 58, '_0n1': 953}
2018-01-01 21:52:53,840 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,844 : INFO : < 200 OK [3308]
2018-01-01 21:52:53,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 76, '_0n1': 1184}
2018-01-01 21:52:53,848 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,856 : INFO : < 200 OK [3299]
2018-01-01 21:52:53,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 76, '_0n1': 998}
2018-01-01 21:52:53,860 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,864 : INFO : < 200 OK [3277]
2018-01-01 21:52:53,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 76, '_0n1': 778}
2018-01-01 21:52:53,868 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,872 : INFO : < 200 OK [3277]
2018-01-01 21:52:53,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 76, '_0n1': 950}
2018-01-01 21:52:53,876 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,880 : INFO : < 200 OK [3275]
2018-01-01 21:52:53,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 1025}
2018-01-01 21:52:53,884 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,888 : INFO : < 200 OK [3284]
2018-01-01 21:52:53,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 903}
2018-01-01 21:52:53,892 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,896 : INFO : < 200 OK [3270]
2018-01-01 21:52:53,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 887}
2018-01-01 21:52:53,904 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,908 : INFO : < 200 OK [3263]
2018-01-01 21:52:53,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 77, '_0n1': 953}
2018-01-01 21:52:53,912 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,918 : INFO : < 200 OK [3325]
2018-01-01 21:52:53,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 81, '_0n1': 1168}
2018-01-01 21:52:53,924 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,929 : INFO : < 200 OK [3294]
2018-01-01 21:52:53,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 78, '_0n1': 1053}
2018-01-01 21:52:53,932 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,936 : INFO : < 200 OK [3318]
2018-01-01 21:52:53,940 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 78, '_0n1': 827}
2018-01-01 21:52:53,940 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,944 : INFO : < 200 OK [3304]
2018-01-01 21:52:53,948 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 82, '_0n1': 812}

2018-01-01 21:52:53,948 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,952 : INFO : < 200 OK [3296]
2018-01-01 21:52:53,956 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 82, '_0n1': 744}
2018-01-01 21:52:53,956 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,960 : INFO : < 200 OK [3285]
2018-01-01 21:52:53,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 80, '_0n1': 1184}
2018-01-01 21:52:53,968 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,972 : INFO : < 200 OK [3303]
2018-01-01 21:52:53,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 83, '_0n1': 1184}
2018-01-01 21:52:53,976 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:53,980 : INFO : < 200 OK [3304]
2018-01-01 21:52:53,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 83, '_0n1': 902}
2018-01-01 21:52:53,984 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:53,988 : INFO : < 200 OK [3287]
2018-01-01 21:52:53,992 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 938}
2018-01-01 21:52:53,996 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,000 : INFO : < 200 OK [3300]
2018-01-01 21:52:54,000 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 956}
2018-01-01 21:52:54,004 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,008 : INFO : < 200 OK [3300]
2018-01-01 21:52:54,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1136}
2018-01-01 21:52:54,012 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,020 : INFO : < 200 OK [3313]
2018-01-01 21:52:54,022 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 84, '_0n1': 820}
2018-01-01 21:52:54,024 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,028 : INFO : < 200 OK [3278]
2018-01-01 21:52:54,031 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 1184}
2018-01-01 21:52:54,032 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,036 : INFO : < 200 OK [3324]
2018-01-01 21:52:54,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 998}
2018-01-01 21:52:54,040 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,044 : INFO : < 200 OK [3302]
2018-01-01 21:52:54,048 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 778}
2018-01-01 21:52:54,048 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,056 : INFO : < 200 OK [3302]
2018-01-01 21:52:54,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 950}
2018-01-01 21:52:54,060 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,064 : INFO : < 200 OK [3300]
2018-01-01 21:52:54,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 85, '_0n1': 1155}
2018-01-01 21:52:54,068 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,072 : INFO : < 200 OK [3308]
2018-01-01 21:52:54,076 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 85, '_0n1': 1015}
2018-01-01 21:52:54,076 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,084 : INFO : < 200 OK [3300]
2018-01-01 21:52:54,084 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 85, '_0n1': 1020}
2018-01-01 21:52:54,088 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,092 : INFO : < 200 OK [3300]
2018-01-01 21:52:54,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 103, '_0n1': 1184}
2018-01-01 21:52:54,096 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,100 : INFO : < 200 OK [3315]
2018-01-01 21:52:54,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 103, '_0n1': 998}
2018-01-01 21:52:54,104 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,108 : INFO : < 200 OK [3293]
2018-01-01 21:52:54,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 103, '_0n1': 1053}
2018-01-01 21:52:54,112 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,118 : INFO : < 200 OK [3309]
2018-01-01 21:52:54,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 103, '_0n1': 950}
2018-01-01 21:52:54,122 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,127 : INFO : < 200 OK [3291]
2018-01-01 21:52:54,129 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 86, '_0n1': 953}
2018-01-01 21:52:54,131 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,132 : INFO : < 200 OK [3331]
2018-01-01 21:52:54,136 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 104, '_0n1': 924}
2018-01-01 21:52:54,136 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,144 : INFO : < 200 OK [3282]
2018-01-01 21:52:54,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 104, '_0n1': 892}
2018-01-01 21:52:54,148 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,152 : INFO : < 200 OK [3276]
2018-01-01 21:52:54,152 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 87, '_0n1': 796}
2018-01-01 21:52:54,156 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,160 : INFO : < 200 OK [3287]
2018-01-01 21:52:54,164 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 1136}
2018-01-01 21:52:54,164 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,168 : INFO : < 200 OK [3341]
2018-01-01 21:52:54,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 956}

2018-01-01 21:52:54,172 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,176 : INFO : < 200 OK [3328]
2018-01-01 21:52:54,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 822}
2018-01-01 21:52:54,180 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,188 : INFO : < 200 OK [3328]
2018-01-01 21:52:54,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 978}
2018-01-01 21:52:54,196 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,200 : INFO : < 200 OK [3328]
2018-01-01 21:52:54,200 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 88, '_0n1': 927}
2018-01-01 21:52:54,204 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,208 : INFO : < 200 OK [3267]
2018-01-01 21:52:54,212 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 88, '_0n1': 745}
2018-01-01 21:52:54,217 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,221 : INFO : < 200 OK [3266]
2018-01-01 21:52:54,225 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 1184}
2018-01-01 21:52:54,227 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,231 : INFO : < 200 OK [3320]
2018-01-01 21:52:54,232 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 998}
2018-01-01 21:52:54,232 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,236 : INFO : < 200 OK [3298]
2018-01-01 21:52:54,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 902}
2018-01-01 21:52:54,240 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,248 : INFO : < 200 OK [3303]
2018-01-01 21:52:54,248 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 89, '_0n1': 1063}
2018-01-01 21:52:54,252 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,256 : INFO : < 200 OK [3305]
2018-01-01 21:52:54,260 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 107, '_0n1': 1188}
2018-01-01 21:52:54,260 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,264 : INFO : < 200 OK [3286]
2018-01-01 21:52:54,268 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 107, '_0n1': 967}
2018-01-01 21:52:54,268 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,272 : INFO : < 200 OK [3270]
2018-01-01 21:52:54,276 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 107, '_0n1': 1075}
2018-01-01 21:52:54,276 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,280 : INFO : < 200 OK [3284]
2018-01-01 21:52:54,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 107, '_0n1': 992}
2018-01-01 21:52:54,288 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,292 : INFO : < 200 OK [3269]
2018-01-01 21:52:54,296 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 107, '_0n1': 982}
2018-01-01 21:52:54,296 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,300 : INFO : < 200 OK [3272]
2018-01-01 21:52:54,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 90, '_0n1': 1099}
2018-01-01 21:52:54,304 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,308 : INFO : < 200 OK [3311]
2018-01-01 21:52:54,312 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 108, '_0n1': 1099}
2018-01-01 21:52:54,316 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,320 : INFO : < 200 OK [3325]
2018-01-01 21:52:54,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 956}
2018-01-01 21:52:54,326 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,330 : INFO : < 200 OK [3288]
2018-01-01 21:52:54,332 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 1136}
2018-01-01 21:52:54,333 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,337 : INFO : < 200 OK [3301]
2018-01-01 21:52:54,341 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 938}
2018-01-01 21:52:54,341 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,345 : INFO : < 200 OK [3288]
2018-01-01 21:52:54,349 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 109, '_0n1': 1062}
2018-01-01 21:52:54,353 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,357 : INFO : < 200 OK [3283]
2018-01-01 21:52:54,361 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 92, '_0n1': 1019}
2018-01-01 21:52:54,365 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,369 : INFO : < 200 OK [3296]
2018-01-01 21:52:54,373 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 1020}
2018-01-01 21:52:54,373 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,377 : INFO : < 200 OK [3316]
2018-01-01 21:52:54,381 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 1015}
2018-01-01 21:52:54,381 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,389 : INFO : < 200 OK [3316]
2018-01-01 21:52:54,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 1155}
2018-01-01 21:52:54,393 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,397 : INFO : < 200 OK [3324]
2018-01-01 21:52:54,397 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 93, '_0n1': 984}
2018-01-01 21:52:54,401 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,405 : INFO : < 200 OK [3257]
2018-01-01 21:52:54,409 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 111, '_0n1': 873}

2018-01-01 21:52:54,409 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,413 : INFO : < 200 OK [3276]
2018-01-01 21:52:54,417 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 111, '_0n1': 730}
2018-01-01 21:52:54,419 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,423 : INFO : < 200 OK [3276]
2018-01-01 21:52:54,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 94, '_0n1': 1184}
2018-01-01 21:52:54,429 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,432 : INFO : < 200 OK [3291]
2018-01-01 21:52:54,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 112, '_0n1': 759}
2018-01-01 21:52:54,437 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,441 : INFO : < 200 OK [3272]
2018-01-01 21:52:54,441 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 112, '_0n1': 773}
2018-01-01 21:52:54,445 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,449 : INFO : < 200 OK [3266]
2018-01-01 21:52:54,449 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 938}
2018-01-01 21:52:54,453 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,457 : INFO : < 200 OK [3285]
2018-01-01 21:52:54,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 956}
2018-01-01 21:52:54,461 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,465 : INFO : < 200 OK [3285]
2018-01-01 21:52:54,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1136}
2018-01-01 21:52:54,469 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,473 : INFO : < 200 OK [3298]
2018-01-01 21:52:54,477 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 113, '_0n1': 883}
2018-01-01 21:52:54,477 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,481 : INFO : < 200 OK [3319]
2018-01-01 21:52:54,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 96, '_0n1': 1017}
2018-01-01 21:52:54,485 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,489 : INFO : < 200 OK [3271]
2018-01-01 21:52:54,493 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 956}
2018-01-01 21:52:54,493 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,501 : INFO : < 200 OK [3270]
2018-01-01 21:52:54,505 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1136}
2018-01-01 21:52:54,505 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,513 : INFO : < 200 OK [3283]
2018-01-01 21:52:54,518 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 938}
2018-01-01 21:52:54,520 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,524 : INFO : < 200 OK [3270]
2018-01-01 21:52:54,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 97, '_0n1': 883}
2018-01-01 21:52:54,532 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,537 : INFO : < 200 OK [3292]
2018-01-01 21:52:54,537 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 115, '_0n1': 1053}
2018-01-01 21:52:54,541 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,545 : INFO : < 200 OK [3321]
2018-01-01 21:52:54,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 115, '_0n1': 827}
2018-01-01 21:52:54,549 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,553 : INFO : < 200 OK [3307]
2018-01-01 21:52:54,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 98, '_0n1': 883}
2018-01-01 21:52:54,557 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:52:54,561 : INFO : < 200 OK [3303]
2018-01-01 21:52:54,565 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 116, '_0n1': 1053}
2018-01-01 21:52:54,565 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,569 : INFO : < 200 OK [3338]
2018-01-01 21:52:54,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 116, '_0n1': 827}
2018-01-01 21:52:54,573 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,577 : INFO : < 200 OK [3324]
2018-01-01 21:52:54,581 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 99, '_0n1': 1019}
2018-01-01 21:52:54,581 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,585 : INFO : < 200 OK [3298]
2018-01-01 21:52:54,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 117, '_0n1': 1071}
2018-01-01 21:52:54,593 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,597 : INFO : < 200 OK [3326]
2018-01-01 21:52:54,601 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 117, '_0n1': 946}
2018-01-01 21:52:54,605 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,609 : INFO : < 200 OK [3309]
2018-01-01 21:52:54,613 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 100, '_0n1': 1053}
2018-01-01 21:52:54,613 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,620 : INFO : < 200 OK [3323]
2018-01-01 21:52:54,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 100, '_0n1': 827}
2018-01-01 21:52:54,625 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,630 : INFO : < 200 OK [3309]
2018-01-01 21:52:54,633 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 118, '_0n1': 1053}
2018-01-01 21:52:54,633 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,637 : INFO : < 200 OK [3343]
2018-01-01 21:52:54,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 118, '_0n1': 827}

2018-01-01 21:52:54,641 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,645 : INFO : < 200 OK [3329]
2018-01-01 21:52:54,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 118, '_0n1': 794}
2018-01-01 21:52:54,649 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,657 : INFO : < 200 OK [3328]
2018-01-01 21:52:54,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 121, '_0n1': 1053}
2018-01-01 21:52:54,661 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,665 : INFO : < 200 OK [3341]
2018-01-01 21:52:54,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 121, '_0n1': 827}
2018-01-01 21:52:54,669 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,673 : INFO : < 200 OK [3327]
2018-01-01 21:52:54,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 119, '_0n1': 1152}
2018-01-01 21:52:54,681 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,681 : INFO : < 200 OK [3304]
2018-01-01 21:52:54,685 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 122, '_0n1': 1017}
2018-01-01 21:52:54,685 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,689 : INFO : < 200 OK [3287]
2018-01-01 21:52:54,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 120, '_0n1': 1184}
2018-01-01 21:52:54,697 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,701 : INFO : < 200 OK [3327]
2018-01-01 21:52:54,701 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 120, '_0n1': 998}
2018-01-01 21:52:54,705 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,709 : INFO : < 200 OK [3305]
2018-01-01 21:52:54,713 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 120, '_0n1': 1053}
2018-01-01 21:52:54,713 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,719 : INFO : < 200 OK [3321]
2018-01-01 21:52:54,722 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 120, '_0n1': 950}
2018-01-01 21:52:54,723 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,727 : INFO : < 200 OK [3303]
2018-01-01 21:52:54,730 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 123, '_0n1': 1136}
2018-01-01 21:52:54,731 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,733 : INFO : < 200 OK [3327]
2018-01-01 21:52:54,737 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 123, '_0n1': 956}
2018-01-01 21:52:54,737 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,741 : INFO : < 200 OK [3314]
2018-01-01 21:52:54,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 123, '_0n1': 938}
2018-01-01 21:52:54,749 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,753 : INFO : < 200 OK [3314]
2018-01-01 21:52:54,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 141, '_0n1': 827}
2018-01-01 21:52:54,757 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,765 : INFO : < 200 OK [3314]
2018-01-01 21:52:54,765 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 141, '_0n1': 1053}
2018-01-01 21:52:54,769 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,773 : INFO : < 200 OK [3328]
2018-01-01 21:52:54,777 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1158}
2018-01-01 21:52:54,777 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,785 : INFO : < 200 OK [3313]
2018-01-01 21:52:54,785 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1097}
2018-01-01 21:52:54,789 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,793 : INFO : < 200 OK [3314]
2018-01-01 21:52:54,793 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 142, '_0n1': 995}
2018-01-01 21:52:54,797 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,801 : INFO : < 200 OK [3326]
2018-01-01 21:52:54,805 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 1132}
2018-01-01 21:52:54,805 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,809 : INFO : < 200 OK [3311]
2018-01-01 21:52:54,813 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 891}
2018-01-01 21:52:54,813 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,819 : INFO : < 200 OK [3298]
2018-01-01 21:52:54,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 798}
2018-01-01 21:52:54,823 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,826 : INFO : < 200 OK [3298]
2018-01-01 21:52:54,830 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 143, '_0n1': 1119}
2018-01-01 21:52:54,832 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,833 : INFO : < 200 OK [3317]
2018-01-01 21:52:54,837 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 126, '_0n1': 1119}
2018-01-01 21:52:54,837 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,841 : INFO : < 200 OK [3346]
2018-01-01 21:52:54,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 144, '_0n1': 1119}
2018-01-01 21:52:54,845 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,849 : INFO : < 200 OK [3332]
2018-01-01 21:52:54,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 127, '_0n1': 1156}
2018-01-01 21:52:54,857 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,861 : INFO : < 200 OK [3290]
2018-01-01 21:52:54,865 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 145, '_0n1': 862}

2018-01-01 21:52:54,869 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,873 : INFO : < 200 OK [3335]
2018-01-01 21:52:54,873 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 128, '_0n1': 908}
2018-01-01 21:52:54,877 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,885 : INFO : < 200 OK [3323]
2018-01-01 21:52:54,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1038}
2018-01-01 21:52:54,889 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,893 : INFO : < 200 OK [3299]
2018-01-01 21:52:54,901 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 129, '_0n1': 1039}
2018-01-01 21:52:54,901 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,905 : INFO : < 200 OK [3307]
2018-01-01 21:52:54,909 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 147, '_0n1': 1080}
2018-01-01 21:52:54,913 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,920 : INFO : < 200 OK [3328]
2018-01-01 21:52:54,924 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 130, '_0n1': 908}
2018-01-01 21:52:54,926 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,932 : INFO : < 200 OK [3308]
2018-01-01 21:52:54,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 148, '_0n1': 830}
2018-01-01 21:52:54,936 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,940 : INFO : < 200 OK [3295]
2018-01-01 21:52:54,944 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 131, '_0n1': 1167}
2018-01-01 21:52:54,944 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,952 : INFO : < 200 OK [3319]
2018-01-01 21:52:54,956 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 149, '_0n1': 1096}
2018-01-01 21:52:54,956 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:54,964 : INFO : < 200 OK [3241]
2018-01-01 21:52:54,968 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 132, '_0n1': 804}
2018-01-01 21:52:54,968 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,972 : INFO : < 200 OK [3321]
2018-01-01 21:52:54,976 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 150, '_0n1': 908}
2018-01-01 21:52:54,976 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,980 : INFO : < 200 OK [3304]
2018-01-01 21:52:54,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 133, '_0n1': 915}
2018-01-01 21:52:54,988 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:54,992 : INFO : < 200 OK [3280]
2018-01-01 21:52:54,992 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 151, '_0n1': 838}
2018-01-01 21:52:54,992 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,000 : INFO : < 200 OK [3278]
2018-01-01 21:52:55,000 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 134, '_0n1': 1128}
2018-01-01 21:52:55,004 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,008 : INFO : < 200 OK [3308]
2018-01-01 21:52:55,008 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 134, '_0n1': 969}
2018-01-01 21:52:55,008 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,012 : INFO : < 200 OK [3289]
2018-01-01 21:52:55,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 134, '_0n1': 1000}
2018-01-01 21:52:55,022 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,026 : INFO : < 200 OK [3306]
2018-01-01 21:52:55,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 134, '_0n1': 912}
2018-01-01 21:52:55,030 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,032 : INFO : < 200 OK [3295]
2018-01-01 21:52:55,037 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 134, '_0n1': 1120}
2018-01-01 21:52:55,037 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,045 : INFO : < 200 OK [3311]
2018-01-01 21:52:55,049 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 152, '_0n1': 1115}
2018-01-01 21:52:55,049 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,057 : INFO : < 200 OK [3279]
2018-01-01 21:52:55,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 135, '_0n1': 885}
2018-01-01 21:52:55,061 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,069 : INFO : < 200 OK [3294]
2018-01-01 21:52:55,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 153, '_0n1': 1043}
2018-01-01 21:52:55,077 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,081 : INFO : < 200 OK [3294]
2018-01-01 21:52:55,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 818}
2018-01-01 21:52:55,085 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,093 : INFO : < 200 OK [3322]
2018-01-01 21:52:55,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 731}
2018-01-01 21:52:55,097 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,101 : INFO : < 200 OK [3327]
2018-01-01 21:52:55,101 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1066}
2018-01-01 21:52:55,105 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,109 : INFO : < 200 OK [3333]
2018-01-01 21:52:55,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 857}
2018-01-01 21:52:55,113 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,120 : INFO : < 200 OK [3318]
2018-01-01 21:52:55,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1208}

2018-01-01 21:52:55,124 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,128 : INFO : < 200 OK [3342]
2018-01-01 21:52:55,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 884}
2018-01-01 21:52:55,133 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,137 : INFO : < 200 OK [3320]
2018-01-01 21:52:55,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1203}
2018-01-01 21:52:55,141 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,145 : INFO : < 200 OK [3343]
2018-01-01 21:52:55,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 154, '_0n1': 908}
2018-01-01 21:52:55,149 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,153 : INFO : < 200 OK [3313]
2018-01-01 21:52:55,153 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 137, '_0n1': 847}
2018-01-01 21:52:55,157 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,161 : INFO : < 200 OK [3295]
2018-01-01 21:52:55,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 155, '_0n1': 716}
2018-01-01 21:52:55,165 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,169 : INFO : < 200 OK [3306]
2018-01-01 21:52:55,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 155, '_0n1': 808}
2018-01-01 21:52:55,173 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,177 : INFO : < 200 OK [3302]
2018-01-01 21:52:55,181 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 138, '_0n1': 879}
2018-01-01 21:52:55,181 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,185 : INFO : < 200 OK [3306]
2018-01-01 21:52:55,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 156, '_0n1': 878}
2018-01-01 21:52:55,189 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,193 : INFO : < 200 OK [3293]
2018-01-01 21:52:55,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 139, '_0n1': 1043}
2018-01-01 21:52:55,197 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,201 : INFO : < 200 OK [3289]
2018-01-01 21:52:55,205 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 157, '_0n1': 1085}
2018-01-01 21:52:55,205 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,209 : INFO : < 200 OK [3309]
2018-01-01 21:52:55,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 140, '_0n1': 1043}
2018-01-01 21:52:55,219 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,225 : INFO : < 200 OK [3290]
2018-01-01 21:52:55,228 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 158, '_0n1': 915}
2018-01-01 21:52:55,231 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,237 : INFO : < 200 OK [3258]
2018-01-01 21:52:55,241 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 161, '_0n1': 838}
2018-01-01 21:52:55,241 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,245 : INFO : < 200 OK [3303]
2018-01-01 21:52:55,249 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 159, '_0n1': 1043}
2018-01-01 21:52:55,253 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,257 : INFO : < 200 OK [3287]
2018-01-01 21:52:55,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 838}
2018-01-01 21:52:55,261 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,265 : INFO : < 200 OK [3318]
2018-01-01 21:52:55,269 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 1150}
2018-01-01 21:52:55,269 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,273 : INFO : < 200 OK [3336]
2018-01-01 21:52:55,277 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 160, '_0n1': 915}
2018-01-01 21:52:55,277 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,285 : INFO : < 200 OK [3299]
2018-01-01 21:52:55,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 163, '_0n1': 942}
2018-01-01 21:52:55,289 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,293 : INFO : < 200 OK [3281]
2018-01-01 21:52:55,293 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 163, '_0n1': 838}
2018-01-01 21:52:55,297 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,301 : INFO : < 200 OK [3279]
2018-01-01 21:52:55,305 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 164, '_0n1': 1159}
2018-01-01 21:52:55,305 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,309 : INFO : < 200 OK [3281]
2018-01-01 21:52:55,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 181, '_0n1': 915}
2018-01-01 21:52:55,313 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,319 : INFO : < 200 OK [3254]
2018-01-01 21:52:55,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 165, '_0n1': 716}
2018-01-01 21:52:55,323 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,327 : INFO : < 200 OK [3308]
2018-01-01 21:52:55,329 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 165, '_0n1': 808}
2018-01-01 21:52:55,331 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,332 : INFO : < 200 OK [3304]
2018-01-01 21:52:55,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 182, '_0n1': 1128}
2018-01-01 21:52:55,336 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,340 : INFO : < 200 OK [3278]
2018-01-01 21:52:55,344 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 182, '_0n1': 969}

2018-01-01 21:52:55,344 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,352 : INFO : < 200 OK [3259]
2018-01-01 21:52:55,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 182, '_0n1': 1000}
2018-01-01 21:52:55,356 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,360 : INFO : < 200 OK [3276]
2018-01-01 21:52:55,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 182, '_0n1': 912}
2018-01-01 21:52:55,368 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,372 : INFO : < 200 OK [3265]
2018-01-01 21:52:55,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 182, '_0n1': 1120}
2018-01-01 21:52:55,376 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,384 : INFO : < 200 OK [3281]
2018-01-01 21:52:55,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 166, '_0n1': 1118}
2018-01-01 21:52:55,388 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,392 : INFO : < 200 OK [3316]
2018-01-01 21:52:55,392 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 183, '_0n1': 1128}
2018-01-01 21:52:55,396 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,400 : INFO : < 200 OK [3276]
2018-01-01 21:52:55,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 183, '_0n1': 969}
2018-01-01 21:52:55,404 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,408 : INFO : < 200 OK [3257]
2018-01-01 21:52:55,412 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 183, '_0n1': 1000}
2018-01-01 21:52:55,412 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,419 : INFO : < 200 OK [3274]
2018-01-01 21:52:55,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 183, '_0n1': 912}
2018-01-01 21:52:55,424 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,428 : INFO : < 200 OK [3263]
2018-01-01 21:52:55,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 183, '_0n1': 1120}
2018-01-01 21:52:55,432 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,433 : INFO : < 200 OK [3279]
2018-01-01 21:52:55,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 167, '_0n1': 838}
2018-01-01 21:52:55,437 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,441 : INFO : < 200 OK [3258]
2018-01-01 21:52:55,445 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 184, '_0n1': 1043}
2018-01-01 21:52:55,445 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,449 : INFO : < 200 OK [3294]
2018-01-01 21:52:55,453 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 168, '_0n1': 915}
2018-01-01 21:52:55,453 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,457 : INFO : < 200 OK [3324]
2018-01-01 21:52:55,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 185, '_0n1': 1036}
2018-01-01 21:52:55,461 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,465 : INFO : < 200 OK [3307]
2018-01-01 21:52:55,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 169, '_0n1': 878}
2018-01-01 21:52:55,473 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,477 : INFO : < 200 OK [3269]
2018-01-01 21:52:55,481 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 186, '_0n1': 1043}
2018-01-01 21:52:55,485 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,489 : INFO : < 200 OK [3287]
2018-01-01 21:52:55,493 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 170, '_0n1': 716}
2018-01-01 21:52:55,497 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,501 : INFO : < 200 OK [3302]
2018-01-01 21:52:55,501 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 170, '_0n1': 808}
2018-01-01 21:52:55,505 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,509 : INFO : < 200 OK [3298]
2018-01-01 21:52:55,513 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 187, '_0n1': 1128}
2018-01-01 21:52:55,513 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,520 : INFO : < 200 OK [3280]
2018-01-01 21:52:55,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 187, '_0n1': 969}
2018-01-01 21:52:55,525 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,529 : INFO : < 200 OK [3261]
2018-01-01 21:52:55,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 187, '_0n1': 1000}
2018-01-01 21:52:55,533 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,537 : INFO : < 200 OK [3278]
2018-01-01 21:52:55,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 187, '_0n1': 912}
2018-01-01 21:52:55,541 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,549 : INFO : < 200 OK [3267]
2018-01-01 21:52:55,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 187, '_0n1': 1120}
2018-01-01 21:52:55,553 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,557 : INFO : < 200 OK [3283]
2018-01-01 21:52:55,561 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 171, '_0n1': 885}
2018-01-01 21:52:55,561 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,565 : INFO : < 200 OK [3328]
2018-01-01 21:52:55,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 188, '_0n1': 716}
2018-01-01 21:52:55,569 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,573 : INFO : < 200 OK [3319]
2018-01-01 21:52:55,577 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 188, '_0n1': 808}

2018-01-01 21:52:55,577 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,581 : INFO : < 200 OK [3315]
2018-01-01 21:52:55,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 172, '_0n1': 716}
2018-01-01 21:52:55,585 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,589 : INFO : < 200 OK [3292]
2018-01-01 21:52:55,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 172, '_0n1': 808}
2018-01-01 21:52:55,593 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,597 : INFO : < 200 OK [3288]
2018-01-01 21:52:55,601 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 189, '_0n1': 838}
2018-01-01 21:52:55,601 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,605 : INFO : < 200 OK [3261]
2018-01-01 21:52:55,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 173, '_0n1': 980}
2018-01-01 21:52:55,613 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,618 : INFO : < 200 OK [3272]
2018-01-01 21:52:55,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 190, '_0n1': 824}
2018-01-01 21:52:55,626 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,630 : INFO : < 200 OK [3324]
2018-01-01 21:52:55,633 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 174, '_0n1': 1102}
2018-01-01 21:52:55,633 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,637 : INFO : < 200 OK [3346]
2018-01-01 21:52:55,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 191, '_0n1': 1156}
2018-01-01 21:52:55,641 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,645 : INFO : < 200 OK [3275]
2018-01-01 21:52:55,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 175, '_0n1': 1102}
2018-01-01 21:52:55,649 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,657 : INFO : < 200 OK [3336]
2018-01-01 21:52:55,657 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 192, '_0n1': 1102}
2018-01-01 21:52:55,661 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,665 : INFO : < 200 OK [3339]
2018-01-01 21:52:55,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 176, '_0n1': 1120}
2018-01-01 21:52:55,669 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,673 : INFO : < 200 OK [3275]
2018-01-01 21:52:55,673 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 176, '_0n1': 1128}
2018-01-01 21:52:55,677 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,681 : INFO : < 200 OK [3272]
2018-01-01 21:52:55,681 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 176, '_0n1': 969}
2018-01-01 21:52:55,685 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,689 : INFO : < 200 OK [3253]
2018-01-01 21:52:55,689 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 176, '_0n1': 1000}
2018-01-01 21:52:55,693 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,697 : INFO : < 200 OK [3270]
2018-01-01 21:52:55,697 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 176, '_0n1': 912}
2018-01-01 21:52:55,701 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,705 : INFO : < 200 OK [3259]
2018-01-01 21:52:55,705 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 193, '_0n1': 838}
2018-01-01 21:52:55,709 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,713 : INFO : < 200 OK [3275]
2018-01-01 21:52:55,713 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 177, '_0n1': 1036}
2018-01-01 21:52:55,719 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,724 : INFO : < 200 OK [3307]
2018-01-01 21:52:55,729 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 177, '_0n1': 980}
2018-01-01 21:52:55,730 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,733 : INFO : < 200 OK [3291]
2018-01-01 21:52:55,737 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 194, '_0n1': 1100}
2018-01-01 21:52:55,737 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,745 : INFO : < 200 OK [3287]
2018-01-01 21:52:55,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 194, '_0n1': 961}
2018-01-01 21:52:55,749 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,753 : INFO : < 200 OK [3283]
2018-01-01 21:52:55,753 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 178, '_0n1': 814}
2018-01-01 21:52:55,757 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,761 : INFO : < 200 OK [3306]
2018-01-01 21:52:55,765 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 195, '_0n1': 792}
2018-01-01 21:52:55,765 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,769 : INFO : < 200 OK [3341]
2018-01-01 21:52:55,773 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 179, '_0n1': 830}
2018-01-01 21:52:55,773 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,777 : INFO : < 200 OK [3274]
2018-01-01 21:52:55,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 797}
2018-01-01 21:52:55,781 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,785 : INFO : < 200 OK [3250]
2018-01-01 21:52:55,789 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 951}
2018-01-01 21:52:55,789 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,797 : INFO : < 200 OK [3249]
2018-01-01 21:52:55,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1018}

2018-01-01 21:52:55,801 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,801 : INFO : < 200 OK [3275]
2018-01-01 21:52:55,805 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1109}
2018-01-01 21:52:55,805 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,813 : INFO : < 200 OK [3263]
2018-01-01 21:52:55,813 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 806}
2018-01-01 21:52:55,813 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,821 : INFO : < 200 OK [3253]
2018-01-01 21:52:55,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1098}
2018-01-01 21:52:55,825 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,829 : INFO : < 200 OK [3262]
2018-01-01 21:52:55,831 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1064}
2018-01-01 21:52:55,833 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,837 : INFO : < 200 OK [3274]
2018-01-01 21:52:55,841 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1177}
2018-01-01 21:52:55,845 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,849 : INFO : < 200 OK [3273]
2018-01-01 21:52:55,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 991}
2018-01-01 21:52:55,853 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,861 : INFO : < 200 OK [3255]
2018-01-01 21:52:55,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1065}
2018-01-01 21:52:55,865 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,869 : INFO : < 200 OK [3262]
2018-01-01 21:52:55,873 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 977}
2018-01-01 21:52:55,873 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,877 : INFO : < 200 OK [3254]
2018-01-01 21:52:55,881 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1111}
2018-01-01 21:52:55,881 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,885 : INFO : < 200 OK [3263]
2018-01-01 21:52:55,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 863}
2018-01-01 21:52:55,889 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,893 : INFO : < 200 OK [3257]
2018-01-01 21:52:55,897 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1123}
2018-01-01 21:52:55,897 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,901 : INFO : < 200 OK [3280]
2018-01-01 21:52:55,905 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 957}
2018-01-01 21:52:55,905 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,909 : INFO : < 200 OK [3252]
2018-01-01 21:52:55,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 180, '_0n1': 874}
2018-01-01 21:52:55,913 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,920 : INFO : < 200 OK [3278]
2018-01-01 21:52:55,923 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 197, '_0n1': 1100}
2018-01-01 21:52:55,925 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,929 : INFO : < 200 OK [3290]
2018-01-01 21:52:55,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 197, '_0n1': 1185}
2018-01-01 21:52:55,933 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,937 : INFO : < 200 OK [3289]
2018-01-01 21:52:55,937 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 197, '_0n1': 1205}
2018-01-01 21:52:55,941 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,945 : INFO : < 200 OK [3292]
2018-01-01 21:52:55,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 201, '_0n1': 864}
2018-01-01 21:52:55,949 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,953 : INFO : < 200 OK [3273]
2018-01-01 21:52:55,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 201, '_0n1': 949}
2018-01-01 21:52:55,957 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,965 : INFO : < 200 OK [3283]
2018-01-01 21:52:55,969 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 198, '_0n1': 1142}
2018-01-01 21:52:55,969 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:55,977 : INFO : < 200 OK [3333]
2018-01-01 21:52:55,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 198, '_0n1': 715}
2018-01-01 21:52:55,981 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,985 : INFO : < 200 OK [3316]
2018-01-01 21:52:55,989 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 202, '_0n1': 830}
2018-01-01 21:52:55,989 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:55,993 : INFO : < 200 OK [3264]
2018-01-01 21:52:55,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 199, '_0n1': 740}
2018-01-01 21:52:55,997 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,005 : INFO : < 200 OK [3284]
2018-01-01 21:52:56,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 199, '_0n1': 780}
2018-01-01 21:52:56,009 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,013 : INFO : < 200 OK [3283]
2018-01-01 21:52:56,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 203, '_0n1': 1100}
2018-01-01 21:52:56,017 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,023 : INFO : < 200 OK [3324]
2018-01-01 21:52:56,027 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 203, '_0n1': 1185}

2018-01-01 21:52:56,029 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,033 : INFO : < 200 OK [3323]
2018-01-01 21:52:56,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 200, '_0n1': 1172}
2018-01-01 21:52:56,037 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,041 : INFO : < 200 OK [3324]
2018-01-01 21:52:56,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 200, '_0n1': 1034}
2018-01-01 21:52:56,045 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,053 : INFO : < 200 OK [3323]
2018-01-01 21:52:56,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 200, '_0n1': 815}
2018-01-01 21:52:56,057 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,061 : INFO : < 200 OK [3308]
2018-01-01 21:52:56,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 200, '_0n1': 1186}
2018-01-01 21:52:56,065 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,069 : INFO : < 200 OK [3325]
2018-01-01 21:52:56,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 200, '_0n1': 732}
2018-01-01 21:52:56,073 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,077 : INFO : < 200 OK [3316]
2018-01-01 21:52:56,081 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 204, '_0n1': 1154}
2018-01-01 21:52:56,081 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,085 : INFO : < 200 OK [3321]
2018-01-01 21:52:56,089 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 204, '_0n1': 821}
2018-01-01 21:52:56,089 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,093 : INFO : < 200 OK [3306]
2018-01-01 21:52:56,097 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 204, '_0n1': 1012}
2018-01-01 21:52:56,097 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,101 : INFO : < 200 OK [3323]
2018-01-01 21:52:56,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 204, '_0n1': 1069}
2018-01-01 21:52:56,105 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,113 : INFO : < 200 OK [3319]
2018-01-01 21:52:56,117 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 204, '_0n1': 1058}
2018-01-01 21:52:56,119 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,125 : INFO : < 200 OK [3319]
2018-01-01 21:52:56,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 221, '_0n1': 1044}
2018-01-01 21:52:56,132 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,137 : INFO : < 200 OK [3271]
2018-01-01 21:52:56,141 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 205, '_0n1': 874}
2018-01-01 21:52:56,141 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,145 : INFO : < 200 OK [3263]
2018-01-01 21:52:56,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 222, '_0n1': 1164}
2018-01-01 21:52:56,149 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,157 : INFO : < 200 OK [3289]
2018-01-01 21:52:56,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 206, '_0n1': 1118}
2018-01-01 21:52:56,161 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,165 : INFO : < 200 OK [3288]
2018-01-01 21:52:56,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 223, '_0n1': 864}
2018-01-01 21:52:56,169 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,173 : INFO : < 200 OK [3233]
2018-01-01 21:52:56,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 207, '_0n1': 874}
2018-01-01 21:52:56,177 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,181 : INFO : < 200 OK [3262]
2018-01-01 21:52:56,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 243, '_0n1': 780}
2018-01-01 21:52:56,185 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,189 : INFO : < 200 OK [3297]
2018-01-01 21:52:56,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 243, '_0n1': 740}
2018-01-01 21:52:56,193 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,197 : INFO : < 200 OK [3298]
2018-01-01 21:52:56,201 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 208, '_0n1': 945}
2018-01-01 21:52:56,201 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,205 : INFO : < 200 OK [3317]
2018-01-01 21:52:56,209 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 244, '_0n1': 843}
2018-01-01 21:52:56,209 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,213 : INFO : < 200 OK [3318]
2018-01-01 21:52:56,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 740}
2018-01-01 21:52:56,219 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,223 : INFO : < 200 OK [3287]
2018-01-01 21:52:56,225 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 780}
2018-01-01 21:52:56,227 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,232 : INFO : < 200 OK [3286]
2018-01-01 21:52:56,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 245, '_0n1': 958}
2018-01-01 21:52:56,233 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,241 : INFO : < 200 OK [3345]
2018-01-01 21:52:56,245 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 210, '_0n1': 853}
2018-01-01 21:52:56,245 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,249 : INFO : < 200 OK [3312]

2018-01-01 21:52:56,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 210, '_0n1': 1178}
2018-01-01 21:52:56,257 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,261 : INFO : < 200 OK [3315]
2018-01-01 21:52:56,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 246, '_0n1': 728}
2018-01-01 21:52:56,265 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,273 : INFO : < 200 OK [3312]
2018-01-01 21:52:56,277 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 211, '_0n1': 728}
2018-01-01 21:52:56,277 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,281 : INFO : < 200 OK [3341]
2018-01-01 21:52:56,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 247, '_0n1': 830}
2018-01-01 21:52:56,289 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,293 : INFO : < 200 OK [3282]
2018-01-01 21:52:56,293 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 212, '_0n1': 874}
2018-01-01 21:52:56,293 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,297 : INFO : < 200 OK [3322]
2018-01-01 21:52:56,301 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 212, '_0n1': 945}
2018-01-01 21:52:56,301 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,309 : INFO : < 200 OK [3324]
2018-01-01 21:52:56,309 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 212, '_0n1': 843}
2018-01-01 21:52:56,313 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,317 : INFO : < 200 OK [3321]
2018-01-01 21:52:56,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 248, '_0n1': 780}
2018-01-01 21:52:56,323 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,327 : INFO : < 200 OK [3306]
2018-01-01 21:52:56,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 248, '_0n1': 740}
2018-01-01 21:52:56,332 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,333 : INFO : < 200 OK [3307]
2018-01-01 21:52:56,337 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 213, '_0n1': 785}
2018-01-01 21:52:56,341 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,345 : INFO : < 200 OK [3293]
2018-01-01 21:52:56,349 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 249, '_0n1': 851}
2018-01-01 21:52:56,349 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,353 : INFO : < 200 OK [3312]
2018-01-01 21:52:56,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 214, '_0n1': 943}
2018-01-01 21:52:56,361 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,365 : INFO : < 200 OK [3284]
2018-01-01 21:52:56,369 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 214, '_0n1': 886}
2018-01-01 21:52:56,373 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,377 : INFO : < 200 OK [3284]
2018-01-01 21:52:56,381 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 214, '_0n1': 1127}
2018-01-01 21:52:56,381 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,389 : INFO : < 200 OK [3292]
2018-01-01 21:52:56,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 250, '_0n1': 888}
2018-01-01 21:52:56,393 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,397 : INFO : < 200 OK [3291]
2018-01-01 21:52:56,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 250, '_0n1': 828}
2018-01-01 21:52:56,401 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,405 : INFO : < 200 OK [3291]
2018-01-01 21:52:56,409 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 215, '_0n1': 999}
2018-01-01 21:52:56,409 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,433 : INFO : < 200 OK [3253]
2018-01-01 21:52:56,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 251, '_0n1': 1084}
2018-01-01 21:52:56,437 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,445 : INFO : < 200 OK [3313]
2018-01-01 21:52:56,445 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 216, '_0n1': 850}
2018-01-01 21:52:56,449 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,453 : INFO : < 200 OK [3299]
2018-01-01 21:52:56,457 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 252, '_0n1': 1083}
2018-01-01 21:52:56,457 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,461 : INFO : < 200 OK [3335]
2018-01-01 21:52:56,465 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 217, '_0n1': 1117}
2018-01-01 21:52:56,465 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,469 : INFO : < 200 OK [3316]
2018-01-01 21:52:56,473 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 217, '_0n1': 779}
2018-01-01 21:52:56,473 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,477 : INFO : < 200 OK [3305]
2018-01-01 21:52:56,481 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 881}
2018-01-01 21:52:56,485 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,489 : INFO : < 200 OK [3283]
2018-01-01 21:52:56,489 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 1204}
2018-01-01 21:52:56,493 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,497 : INFO : < 200 OK [3294]
2018-01-01 21:52:56,497 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 1110}

2018-01-01 21:52:56,501 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,505 : INFO : < 200 OK [3297]
2018-01-01 21:52:56,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 1174}
2018-01-01 21:52:56,509 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,519 : INFO : < 200 OK [3289]
2018-01-01 21:52:56,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 1055}
2018-01-01 21:52:56,526 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,532 : INFO : < 200 OK [3291]
2018-01-01 21:52:56,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 923}
2018-01-01 21:52:56,537 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,541 : INFO : < 200 OK [3278]
2018-01-01 21:52:56,545 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 801}
2018-01-01 21:52:56,545 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,549 : INFO : < 200 OK [3273]
2018-01-01 21:52:56,553 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 1161}
2018-01-01 21:52:56,553 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,561 : INFO : < 200 OK [3296]
2018-01-01 21:52:56,561 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 1103}
2018-01-01 21:52:56,565 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,569 : INFO : < 200 OK [3297]
2018-01-01 21:52:56,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 218, '_0n1': 1117}
2018-01-01 21:52:56,573 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,581 : INFO : < 200 OK [3319]
2018-01-01 21:52:56,581 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 218, '_0n1': 779}
2018-01-01 21:52:56,585 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,589 : INFO : < 200 OK [3308]
2018-01-01 21:52:56,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 254, '_0n1': 803}
2018-01-01 21:52:56,593 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,597 : INFO : < 200 OK [3315]
2018-01-01 21:52:56,601 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 219, '_0n1': 1029}
2018-01-01 21:52:56,601 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,605 : INFO : < 200 OK [3277]
2018-01-01 21:52:56,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 255, '_0n1': 1054}
2018-01-01 21:52:56,613 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,618 : INFO : < 200 OK [3306]
2018-01-01 21:52:56,620 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 220, '_0n1': 752}
2018-01-01 21:52:56,622 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,626 : INFO : < 200 OK [3258]
2018-01-01 21:52:56,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 256, '_0n1': 999}
2018-01-01 21:52:56,630 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,633 : INFO : < 200 OK [3275]
2018-01-01 21:52:56,633 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 260, '_0n1': 907}
2018-01-01 21:52:56,638 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,642 : INFO : < 200 OK [3315]
2018-01-01 21:52:56,646 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 257, '_0n1': 880}
2018-01-01 21:52:56,646 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,650 : INFO : < 200 OK [3320]
2018-01-01 21:52:56,654 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 261, '_0n1': 724}
2018-01-01 21:52:56,654 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,658 : INFO : < 200 OK [3280]
2018-01-01 21:52:56,662 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 258, '_0n1': 1082}
2018-01-01 21:52:56,662 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,666 : INFO : < 200 OK [3329]
2018-01-01 21:52:56,670 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 262, '_0n1': 943}
2018-01-01 21:52:56,670 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,674 : INFO : < 200 OK [3310]
2018-01-01 21:52:56,678 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 262, '_0n1': 886}
2018-01-01 21:52:56,678 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,682 : INFO : < 200 OK [3310]
2018-01-01 21:52:56,685 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 262, '_0n1': 1127}
2018-01-01 21:52:56,685 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,690 : INFO : < 200 OK [3318]
2018-01-01 21:52:56,694 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 259, '_0n1': 1104}
2018-01-01 21:52:56,694 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,698 : INFO : < 200 OK [3306]
2018-01-01 21:52:56,702 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 263, '_0n1': 1093}
2018-01-01 21:52:56,706 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,710 : INFO : < 200 OK [3289]
2018-01-01 21:52:56,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 280, '_0n1': 724}
2018-01-01 21:52:56,714 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,725 : INFO : < 200 OK [3327]
2018-01-01 21:52:56,730 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 264, '_0n1': 875}
2018-01-01 21:52:56,732 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,733 : INFO : < 200 OK [3296]

2018-01-01 21:52:56,737 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 264, '_0n1': 1209}
2018-01-01 21:52:56,741 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,745 : INFO : < 200 OK [3304]
2018-01-01 21:52:56,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 281, '_0n1': 870}
2018-01-01 21:52:56,749 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,753 : INFO : < 200 OK [3269]
2018-01-01 21:52:56,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 265, '_0n1': 1137}
2018-01-01 21:52:56,757 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,761 : INFO : < 200 OK [3326]
2018-01-01 21:52:56,765 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 282, '_0n1': 752}
2018-01-01 21:52:56,765 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,773 : INFO : < 200 OK [3238]
2018-01-01 21:52:56,773 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1090}
2018-01-01 21:52:56,777 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,781 : INFO : < 200 OK [3312]
2018-01-01 21:52:56,785 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1106}
2018-01-01 21:52:56,785 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,789 : INFO : < 200 OK [3310]
2018-01-01 21:52:56,793 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 283, '_0n1': 752}
2018-01-01 21:52:56,793 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,797 : INFO : < 200 OK [3264]
2018-01-01 21:52:56,801 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 267, '_0n1': 784}
2018-01-01 21:52:56,801 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,809 : INFO : < 200 OK [3300]
2018-01-01 21:52:56,809 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 284, '_0n1': 894}
2018-01-01 21:52:56,813 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,817 : INFO : < 200 OK [3324]
2018-01-01 21:52:56,822 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 284, '_0n1': 1086}
2018-01-01 21:52:56,824 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,828 : INFO : < 200 OK [3336]
2018-01-01 21:52:56,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 268, '_0n1': 752}
2018-01-01 21:52:56,834 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,838 : INFO : < 200 OK [3260]
2018-01-01 21:52:56,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 285, '_0n1': 963}
2018-01-01 21:52:56,842 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,846 : INFO : < 200 OK [3287]
2018-01-01 21:52:56,850 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 269, '_0n1': 858}
2018-01-01 21:52:56,850 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,858 : INFO : < 200 OK [3264]
2018-01-01 21:52:56,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 286, '_0n1': 724}
2018-01-01 21:52:56,862 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,866 : INFO : < 200 OK [3339]
2018-01-01 21:52:56,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 270, '_0n1': 940}
2018-01-01 21:52:56,870 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,874 : INFO : < 200 OK [3321]
2018-01-01 21:52:56,878 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 287, '_0n1': 752}
2018-01-01 21:52:56,878 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,882 : INFO : < 200 OK [3261]
2018-01-01 21:52:56,886 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 271, '_0n1': 928}
2018-01-01 21:52:56,886 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,890 : INFO : < 200 OK [3314]
2018-01-01 21:52:56,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 288, '_0n1': 1062}
2018-01-01 21:52:56,898 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,902 : INFO : < 200 OK [3287]
2018-01-01 21:52:56,902 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 272, '_0n1': 1086}
2018-01-01 21:52:56,906 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,910 : INFO : < 200 OK [3339]
2018-01-01 21:52:56,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 272, '_0n1': 894}
2018-01-01 21:52:56,914 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,919 : INFO : < 200 OK [3327]
2018-01-01 21:52:56,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 289, '_0n1': 973}
2018-01-01 21:52:56,924 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,927 : INFO : < 200 OK [3305]
2018-01-01 21:52:56,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 289, '_0n1': 842}
2018-01-01 21:52:56,932 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,934 : INFO : < 200 OK [3297]
2018-01-01 21:52:56,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 289, '_0n1': 1141}
2018-01-01 21:52:56,938 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,942 : INFO : < 200 OK [3315]
2018-01-01 21:52:56,946 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 289, '_0n1': 993}
2018-01-01 21:52:56,946 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,950 : INFO : < 200 OK [3298]
2018-01-01 21:52:56,954 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 273, '_0n1': 772}

2018-01-01 21:52:56,954 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,958 : INFO : < 200 OK [3289]
2018-01-01 21:52:56,962 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 290, '_0n1': 724}
2018-01-01 21:52:56,962 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,966 : INFO : < 200 OK [3280]
2018-01-01 21:52:56,970 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 274, '_0n1': 849}
2018-01-01 21:52:56,970 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,974 : INFO : < 200 OK [3314]
2018-01-01 21:52:56,978 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 291, '_0n1': 761}
2018-01-01 21:52:56,982 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:56,986 : INFO : < 200 OK [3287]
2018-01-01 21:52:56,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 275, '_0n1': 1076}
2018-01-01 21:52:56,990 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:56,998 : INFO : < 200 OK [3309]
2018-01-01 21:52:56,998 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 292, '_0n1': 875}
2018-01-01 21:52:57,002 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,006 : INFO : < 200 OK [3261]
2018-01-01 21:52:57,010 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 292, '_0n1': 1121}
2018-01-01 21:52:57,010 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,014 : INFO : < 200 OK [3271]
2018-01-01 21:52:57,019 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 276, '_0n1': 1095}
2018-01-01 21:52:57,021 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,025 : INFO : < 200 OK [3285]
2018-01-01 21:52:57,028 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1059}
2018-01-01 21:52:57,030 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,034 : INFO : < 200 OK [3315]
2018-01-01 21:52:57,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1013}
2018-01-01 21:52:57,038 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,046 : INFO : < 200 OK [3310]
2018-01-01 21:52:57,050 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 926}
2018-01-01 21:52:57,050 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,054 : INFO : < 200 OK [3323]
2018-01-01 21:52:57,058 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 719}
2018-01-01 21:52:57,058 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,066 : INFO : < 200 OK [3321]
2018-01-01 21:52:57,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 962}
2018-01-01 21:52:57,070 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,074 : INFO : < 200 OK [3322]
2018-01-01 21:52:57,078 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1025}
2018-01-01 21:52:57,078 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,082 : INFO : < 200 OK [3339]
2018-01-01 21:52:57,086 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 835}
2018-01-01 21:52:57,086 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,090 : INFO : < 200 OK [3315]
2018-01-01 21:52:57,094 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 919}
2018-01-01 21:52:57,094 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,098 : INFO : < 200 OK [3303]
2018-01-01 21:52:57,102 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 278, '_0n1': 960}
2018-01-01 21:52:57,102 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,106 : INFO : < 200 OK [3326]
2018-01-01 21:52:57,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 810}
2018-01-01 21:52:57,110 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,114 : INFO : < 200 OK [3301]
2018-01-01 21:52:57,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 754}
2018-01-01 21:52:57,121 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,125 : INFO : < 200 OK [3285]
2018-01-01 21:52:57,128 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 774}
2018-01-01 21:52:57,129 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,134 : INFO : < 200 OK [3291]
2018-01-01 21:52:57,134 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1207}
2018-01-01 21:52:57,138 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,142 : INFO : < 200 OK [3300]
2018-01-01 21:52:57,146 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 781}
2018-01-01 21:52:57,146 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,150 : INFO : < 200 OK [3293]
2018-01-01 21:52:57,154 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 296, '_0n1': 960}
2018-01-01 21:52:57,154 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,158 : INFO : < 200 OK [3316]
2018-01-01 21:52:57,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 300, '_0n1': 1095}
2018-01-01 21:52:57,162 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,170 : INFO : < 200 OK [3284]
2018-01-01 21:52:57,170 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 297, '_0n1': 960}
2018-01-01 21:52:57,174 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,178 : INFO : < 200 OK [3332]
2018-01-01 21:52:57,182 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 301, '_0n1': 1095}

2018-01-01 21:52:57,182 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,190 : INFO : < 200 OK [3293]
2018-01-01 21:52:57,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 298, '_0n1': 910}
2018-01-01 21:52:57,194 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,202 : INFO : < 200 OK [3300]
2018-01-01 21:52:57,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 302, '_0n1': 983}
2018-01-01 21:52:57,206 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,210 : INFO : < 200 OK [3309]
2018-01-01 21:52:57,214 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 299, '_0n1': 1043}
2018-01-01 21:52:57,214 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,222 : INFO : < 200 OK [3299]
2018-01-01 21:52:57,225 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1032}
2018-01-01 21:52:57,227 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,232 : INFO : < 200 OK [3323]
2018-01-01 21:52:57,234 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 808}
2018-01-01 21:52:57,234 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,238 : INFO : < 200 OK [3305]
2018-01-01 21:52:57,242 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 970}
2018-01-01 21:52:57,242 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,246 : INFO : < 200 OK [3303]
2018-01-01 21:52:57,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 320, '_0n1': 1165}
2018-01-01 21:52:57,250 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,258 : INFO : < 200 OK [3284]
2018-01-01 21:52:57,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 304, '_0n1': 1151}
2018-01-01 21:52:57,262 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,266 : INFO : < 200 OK [3285]
2018-01-01 21:52:57,266 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 321, '_0n1': 1038}
2018-01-01 21:52:57,270 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,274 : INFO : < 200 OK [3331]
2018-01-01 21:52:57,278 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 1043}
2018-01-01 21:52:57,278 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,282 : INFO : < 200 OK [3313]
2018-01-01 21:52:57,286 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 322, '_0n1': 1043}
2018-01-01 21:52:57,286 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,290 : INFO : < 200 OK [3305]
2018-01-01 21:52:57,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 964}
2018-01-01 21:52:57,294 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,298 : INFO : < 200 OK [3282]
2018-01-01 21:52:57,302 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1147}
2018-01-01 21:52:57,306 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,310 : INFO : < 200 OK [3306]
2018-01-01 21:52:57,310 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 960}
2018-01-01 21:52:57,314 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,319 : INFO : < 200 OK [3320]
2018-01-01 21:52:57,322 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 307, '_0n1': 832}
2018-01-01 21:52:57,324 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,328 : INFO : < 200 OK [3313]
2018-01-01 21:52:57,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 324, '_0n1': 788}
2018-01-01 21:52:57,333 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,338 : INFO : < 200 OK [3272]
2018-01-01 21:52:57,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 308, '_0n1': 1095}
2018-01-01 21:52:57,342 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,350 : INFO : < 200 OK [3303]
2018-01-01 21:52:57,354 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 810}
2018-01-01 21:52:57,354 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,362 : INFO : < 200 OK [3268]
2018-01-01 21:52:57,366 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1032}
2018-01-01 21:52:57,366 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,374 : INFO : < 200 OK [3281]
2018-01-01 21:52:57,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 970}
2018-01-01 21:52:57,378 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,382 : INFO : < 200 OK [3261]
2018-01-01 21:52:57,386 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 808}
2018-01-01 21:52:57,386 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,390 : INFO : < 200 OK [3263]
2018-01-01 21:52:57,394 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 861}
2018-01-01 21:52:57,394 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,398 : INFO : < 200 OK [3263]
2018-01-01 21:52:57,402 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 810}
2018-01-01 21:52:57,402 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,410 : INFO : < 200 OK [3301]
2018-01-01 21:52:57,414 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 310, '_0n1': 781}
2018-01-01 21:52:57,414 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,420 : INFO : < 200 OK [3317]
2018-01-01 21:52:57,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 310, '_0n1': 1207}

2018-01-01 21:52:57,424 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,429 : INFO : < 200 OK [3324]
2018-01-01 21:52:57,433 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 310, '_0n1': 965}
2018-01-01 21:52:57,434 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,438 : INFO : < 200 OK [3313]
2018-01-01 21:52:57,442 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 327, '_0n1': 960}
2018-01-01 21:52:57,442 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,446 : INFO : < 200 OK [3330]
2018-01-01 21:52:57,450 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 311, '_0n1': 739}
2018-01-01 21:52:57,450 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,454 : INFO : < 200 OK [3299]
2018-01-01 21:52:57,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 328, '_0n1': 1032}
2018-01-01 21:52:57,458 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,462 : INFO : < 200 OK [3315]
2018-01-01 21:52:57,466 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 312, '_0n1': 781}
2018-01-01 21:52:57,466 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,470 : INFO : < 200 OK [3344]
2018-01-01 21:52:57,474 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 329, '_0n1': 983}
2018-01-01 21:52:57,474 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,478 : INFO : < 200 OK [3309]
2018-01-01 21:52:57,482 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 781}
2018-01-01 21:52:57,482 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,490 : INFO : < 200 OK [3285]
2018-01-01 21:52:57,494 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1207}
2018-01-01 21:52:57,494 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,498 : INFO : < 200 OK [3292]
2018-01-01 21:52:57,502 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 965}
2018-01-01 21:52:57,502 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,510 : INFO : < 200 OK [3281]
2018-01-01 21:52:57,514 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 330, '_0n1': 776}
2018-01-01 21:52:57,518 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,523 : INFO : < 200 OK [3296]
2018-01-01 21:52:57,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 314, '_0n1': 1032}
2018-01-01 21:52:57,531 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,534 : INFO : < 200 OK [3299]
2018-01-01 21:52:57,538 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 331, '_0n1': 1032}
2018-01-01 21:52:57,538 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,542 : INFO : < 200 OK [3300]
2018-01-01 21:52:57,546 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 331, '_0n1': 861}
2018-01-01 21:52:57,550 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,554 : INFO : < 200 OK [3282]
2018-01-01 21:52:57,558 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 315, '_0n1': 788}
2018-01-01 21:52:57,558 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,562 : INFO : < 200 OK [3265]
2018-01-01 21:52:57,566 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 332, '_0n1': 1165}
2018-01-01 21:52:57,566 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,570 : INFO : < 200 OK [3294]
2018-01-01 21:52:57,574 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 316, '_0n1': 845}
2018-01-01 21:52:57,574 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,582 : INFO : < 200 OK [3281]
2018-01-01 21:52:57,582 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 316, '_0n1': 1051}
2018-01-01 21:52:57,586 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,590 : INFO : < 200 OK [3294]
2018-01-01 21:52:57,590 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 333, '_0n1': 896}
2018-01-01 21:52:57,594 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,598 : INFO : < 200 OK [3288]
2018-01-01 21:52:57,602 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 317, '_0n1': 1119}
2018-01-01 21:52:57,602 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,606 : INFO : < 200 OK [3339]
2018-01-01 21:52:57,610 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 334, '_0n1': 788}
2018-01-01 21:52:57,610 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,614 : INFO : < 200 OK [3273]
2018-01-01 21:52:57,619 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 318, '_0n1': 845}
2018-01-01 21:52:57,621 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,624 : INFO : < 200 OK [3283]
2018-01-01 21:52:57,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 318, '_0n1': 1051}
2018-01-01 21:52:57,629 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,634 : INFO : < 200 OK [3296]
2018-01-01 21:52:57,634 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 1210}
2018-01-01 21:52:57,634 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,638 : INFO : < 200 OK [3311]
2018-01-01 21:52:57,642 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 1088}
2018-01-01 21:52:57,646 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,650 : INFO : < 200 OK [3300]
2018-01-01 21:52:57,654 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 911}

2018-01-01 21:52:57,654 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,662 : INFO : < 200 OK [3288]
2018-01-01 21:52:57,666 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 319, '_0n1': 947}
2018-01-01 21:52:57,670 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,674 : INFO : < 200 OK [3285]
2018-01-01 21:52:57,678 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 336, '_0n1': 1145}
2018-01-01 21:52:57,678 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,682 : INFO : < 200 OK [3331]
2018-01-01 21:52:57,686 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 781}
2018-01-01 21:52:57,686 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,694 : INFO : < 200 OK [3293]
2018-01-01 21:52:57,694 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1207}
2018-01-01 21:52:57,698 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,702 : INFO : < 200 OK [3300]
2018-01-01 21:52:57,706 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 965}
2018-01-01 21:52:57,706 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,710 : INFO : < 200 OK [3289]
2018-01-01 21:52:57,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 337, '_0n1': 882}
2018-01-01 21:52:57,714 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,721 : INFO : < 200 OK [3277]
2018-01-01 21:52:57,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 341, '_0n1': 845}
2018-01-01 21:52:57,725 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,729 : INFO : < 200 OK [3269]
2018-01-01 21:52:57,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 341, '_0n1': 1051}
2018-01-01 21:52:57,734 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,738 : INFO : < 200 OK [3282]
2018-01-01 21:52:57,738 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 338, '_0n1': 1095}
2018-01-01 21:52:57,742 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,746 : INFO : < 200 OK [3297]
2018-01-01 21:52:57,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 342, '_0n1': 1032}
2018-01-01 21:52:57,750 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,754 : INFO : < 200 OK [3311]
2018-01-01 21:52:57,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 342, '_0n1': 1125}
2018-01-01 21:52:57,758 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,762 : INFO : < 200 OK [3311]
2018-01-01 21:52:57,766 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 339, '_0n1': 788}
2018-01-01 21:52:57,766 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,770 : INFO : < 200 OK [3261]
2018-01-01 21:52:57,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 1166}
2018-01-01 21:52:57,774 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,782 : INFO : < 200 OK [3324]
2018-01-01 21:52:57,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 867}
2018-01-01 21:52:57,786 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,794 : INFO : < 200 OK [3312]
2018-01-01 21:52:57,794 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 922}
2018-01-01 21:52:57,798 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,802 : INFO : < 200 OK [3310]
2018-01-01 21:52:57,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 760}
2018-01-01 21:52:57,810 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,814 : INFO : < 200 OK [3290]
2018-01-01 21:52:57,820 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 892}
2018-01-01 21:52:57,821 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,826 : INFO : < 200 OK [3286]
2018-01-01 21:52:57,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 724}
2018-01-01 21:52:57,830 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,834 : INFO : < 200 OK [3288]
2018-01-01 21:52:57,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 344, '_0n1': 837}
2018-01-01 21:52:57,838 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,842 : INFO : < 200 OK [3313]
2018-01-01 21:52:57,846 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 892}
2018-01-01 21:52:57,846 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,850 : INFO : < 200 OK [3265]
2018-01-01 21:52:57,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 760}
2018-01-01 21:52:57,854 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,858 : INFO : < 200 OK [3269]
2018-01-01 21:52:57,862 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 724}
2018-01-01 21:52:57,862 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,866 : INFO : < 200 OK [3267]
2018-01-01 21:52:57,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 345, '_0n1': 921}
2018-01-01 21:52:57,870 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,874 : INFO : < 200 OK [3288]
2018-01-01 21:52:57,878 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 345, '_0n1': 1131}
2018-01-01 21:52:57,878 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,882 : INFO : < 200 OK [3300]
2018-01-01 21:52:57,886 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 760}

2018-01-01 21:52:57,886 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,890 : INFO : < 200 OK [3269]
2018-01-01 21:52:57,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 892}
2018-01-01 21:52:57,898 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,902 : INFO : < 200 OK [3265]
2018-01-01 21:52:57,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 724}
2018-01-01 21:52:57,906 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,910 : INFO : < 200 OK [3267]
2018-01-01 21:52:57,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 724}
2018-01-01 21:52:57,914 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,922 : INFO : < 200 OK [3259]
2018-01-01 21:52:57,926 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 760}
2018-01-01 21:52:57,928 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,933 : INFO : < 200 OK [3261]
2018-01-01 21:52:57,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 892}
2018-01-01 21:52:57,938 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,942 : INFO : < 200 OK [3257]
2018-01-01 21:52:57,946 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 724}
2018-01-01 21:52:57,946 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,954 : INFO : < 200 OK [3263]
2018-01-01 21:52:57,954 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 760}
2018-01-01 21:52:57,958 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,962 : INFO : < 200 OK [3265]
2018-01-01 21:52:57,966 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 892}
2018-01-01 21:52:57,970 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,974 : INFO : < 200 OK [3261]
2018-01-01 21:52:57,978 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 347, '_0n1': 1060}
2018-01-01 21:52:57,978 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:57,982 : INFO : < 200 OK [3278]
2018-01-01 21:52:57,986 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 347, '_0n1': 987}
2018-01-01 21:52:57,986 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,990 : INFO : < 200 OK [3269]
2018-01-01 21:52:57,994 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 364, '_0n1': 837}
2018-01-01 21:52:57,994 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:57,998 : INFO : < 200 OK [3299]
2018-01-01 21:52:58,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 348, '_0n1': 1092}
2018-01-01 21:52:58,002 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,006 : INFO : < 200 OK [3271]
2018-01-01 21:52:58,010 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 837}
2018-01-01 21:52:58,010 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,014 : INFO : < 200 OK [3300]
2018-01-01 21:52:58,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 836}
2018-01-01 21:52:58,022 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,026 : INFO : < 200 OK [3289]
2018-01-01 21:52:58,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 932}
2018-01-01 21:52:58,031 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,034 : INFO : < 200 OK [3291]
2018-01-01 21:52:58,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 738}
2018-01-01 21:52:58,038 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,042 : INFO : < 200 OK [3293]
2018-01-01 21:52:58,046 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 349, '_0n1': 837}
2018-01-01 21:52:58,046 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,050 : INFO : < 200 OK [3308]
2018-01-01 21:52:58,054 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 760}
2018-01-01 21:52:58,054 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,058 : INFO : < 200 OK [3265]
2018-01-01 21:52:58,062 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 892}
2018-01-01 21:52:58,066 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,070 : INFO : < 200 OK [3261]
2018-01-01 21:52:58,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 724}
2018-01-01 21:52:58,078 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,082 : INFO : < 200 OK [3263]
2018-01-01 21:52:58,086 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 350, '_0n1': 725}
2018-01-01 21:52:58,086 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,090 : INFO : < 200 OK [3309]
2018-01-01 21:52:58,094 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 367, '_0n1': 1090}
2018-01-01 21:52:58,098 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,102 : INFO : < 200 OK [3309]
2018-01-01 21:52:58,102 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 724}
2018-01-01 21:52:58,106 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,110 : INFO : < 200 OK [3266]
2018-01-01 21:52:58,114 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 892}
2018-01-01 21:52:58,118 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,123 : INFO : < 200 OK [3264]
2018-01-01 21:52:58,126 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 760}

2018-01-01 21:52:58,128 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,133 : INFO : < 200 OK [3268]
2018-01-01 21:52:58,134 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 368, '_0n1': 717}
2018-01-01 21:52:58,134 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,138 : INFO : < 200 OK [3330]
2018-01-01 21:52:58,142 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 352, '_0n1': 1183}
2018-01-01 21:52:58,142 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,146 : INFO : < 200 OK [3325]
2018-01-01 21:52:58,150 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 369, '_0n1': 1108}
2018-01-01 21:52:58,154 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,158 : INFO : < 200 OK [3372]
2018-01-01 21:52:58,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 353, '_0n1': 841}
2018-01-01 21:52:58,162 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,166 : INFO : < 200 OK [3271]
2018-01-01 21:52:58,170 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 353, '_0n1': 1131}
2018-01-01 21:52:58,170 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,174 : INFO : < 200 OK [3277]
2018-01-01 21:52:58,178 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 370, '_0n1': 717}
2018-01-01 21:52:58,178 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,182 : INFO : < 200 OK [3309]
2018-01-01 21:52:58,186 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 354, '_0n1': 900}
2018-01-01 21:52:58,186 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,190 : INFO : < 200 OK [3300]
2018-01-01 21:52:58,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 371, '_0n1': 839}
2018-01-01 21:52:58,194 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,198 : INFO : < 200 OK [3265]
2018-01-01 21:52:58,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 371, '_0n1': 1134}
2018-01-01 21:52:58,202 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,206 : INFO : < 200 OK [3284]
2018-01-01 21:52:58,210 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 355, '_0n1': 892}
2018-01-01 21:52:58,210 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,214 : INFO : < 200 OK [3275]
2018-01-01 21:52:58,219 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 372, '_0n1': 1057}
2018-01-01 21:52:58,221 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,227 : INFO : < 200 OK [3299]
2018-01-01 21:52:58,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 356, '_0n1': 1014}
2018-01-01 21:52:58,233 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,238 : INFO : < 200 OK [3277]
2018-01-01 21:52:58,242 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 373, '_0n1': 1187}
2018-01-01 21:52:58,242 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,250 : INFO : < 200 OK [3350]
2018-01-01 21:52:58,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 357, '_0n1': 753}
2018-01-01 21:52:58,254 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,258 : INFO : < 200 OK [3336]
2018-01-01 21:52:58,262 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 357, '_0n1': 1037}
2018-01-01 21:52:58,262 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,266 : INFO : < 200 OK [3346]
2018-01-01 21:52:58,270 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 738}
2018-01-01 21:52:58,270 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,274 : INFO : < 200 OK [3267]
2018-01-01 21:52:58,278 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 932}
2018-01-01 21:52:58,282 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,282 : INFO : < 200 OK [3265]
2018-01-01 21:52:58,290 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 836}
2018-01-01 21:52:58,290 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,294 : INFO : < 200 OK [3263]
2018-01-01 21:52:58,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 837}
2018-01-01 21:52:58,298 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,302 : INFO : < 200 OK [3274]
2018-01-01 21:52:58,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 358, '_0n1': 782}
2018-01-01 21:52:58,306 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,310 : INFO : < 200 OK [3251]
2018-01-01 21:52:58,314 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 375, '_0n1': 782}
2018-01-01 21:52:58,314 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,321 : INFO : < 200 OK [3301]
2018-01-01 21:52:58,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 375, '_0n1': 737}
2018-01-01 21:52:58,325 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,329 : INFO : < 200 OK [3335]
2018-01-01 21:52:58,333 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 375, '_0n1': 1048}
2018-01-01 21:52:58,334 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,338 : INFO : < 200 OK [3350]
2018-01-01 21:52:58,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 359, '_0n1': 758}
2018-01-01 21:52:58,346 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,350 : INFO : < 200 OK [3277]
2018-01-01 21:52:58,354 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 872}

2018-01-01 21:52:58,358 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,362 : INFO : < 200 OK [3298]
2018-01-01 21:52:58,366 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 982}
2018-01-01 21:52:58,366 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,370 : INFO : < 200 OK [3299]
2018-01-01 21:52:58,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 745}
2018-01-01 21:52:58,374 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,382 : INFO : < 200 OK [3299]
2018-01-01 21:52:58,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 722}
2018-01-01 21:52:58,386 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,390 : INFO : < 200 OK [3303]
2018-01-01 21:52:58,394 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 920}
2018-01-01 21:52:58,394 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,398 : INFO : < 200 OK [3297]
2018-01-01 21:52:58,402 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 380, '_0n1': 987}
2018-01-01 21:52:58,406 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,410 : INFO : < 200 OK [3292]
2018-01-01 21:52:58,410 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 380, '_0n1': 1060}
2018-01-01 21:52:58,414 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,420 : INFO : < 200 OK [3301]
2018-01-01 21:52:58,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1094}
2018-01-01 21:52:58,425 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,429 : INFO : < 200 OK [3346]
2018-01-01 21:52:58,433 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1052}
2018-01-01 21:52:58,435 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,439 : INFO : < 200 OK [3349]
2018-01-01 21:52:58,439 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 816}
2018-01-01 21:52:58,443 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,447 : INFO : < 200 OK [3333]
2018-01-01 21:52:58,451 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1179}
2018-01-01 21:52:58,451 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,455 : INFO : < 200 OK [3347]
2018-01-01 21:52:58,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1073}
2018-01-01 21:52:58,459 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,463 : INFO : < 200 OK [3350]
2018-01-01 21:52:58,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 381, '_0n1': 1201}
2018-01-01 21:52:58,467 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,471 : INFO : < 200 OK [3325]
2018-01-01 21:52:58,475 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 381, '_0n1': 799}
2018-01-01 21:52:58,475 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,479 : INFO : < 200 OK [3309]
2018-01-01 21:52:58,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 378, '_0n1': 892}
2018-01-01 21:52:58,487 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,491 : INFO : < 200 OK [3266]
2018-01-01 21:52:58,495 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 378, '_0n1': 760}
2018-01-01 21:52:58,499 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,503 : INFO : < 200 OK [3270]
2018-01-01 21:52:58,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 378, '_0n1': 724}
2018-01-01 21:52:58,511 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,515 : INFO : < 200 OK [3268]
2018-01-01 21:52:58,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 382, '_0n1': 743}
2018-01-01 21:52:58,520 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,524 : INFO : < 200 OK [3297]
2018-01-01 21:52:58,528 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 382, '_0n1': 939}
2018-01-01 21:52:58,529 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,533 : INFO : < 200 OK [3298]
2018-01-01 21:52:58,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 379, '_0n1': 987}
2018-01-01 21:52:58,535 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,539 : INFO : < 200 OK [3273]
2018-01-01 21:52:58,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 379, '_0n1': 1060}
2018-01-01 21:52:58,547 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,551 : INFO : < 200 OK [3282]
2018-01-01 21:52:58,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1126}
2018-01-01 21:52:58,555 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,563 : INFO : < 200 OK [3298]
2018-01-01 21:52:58,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 892}
2018-01-01 21:52:58,567 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,571 : INFO : < 200 OK [3287]
2018-01-01 21:52:58,575 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 724}
2018-01-01 21:52:58,575 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,579 : INFO : < 200 OK [3289]
2018-01-01 21:52:58,583 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 760}
2018-01-01 21:52:58,583 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,587 : INFO : < 200 OK [3291]
2018-01-01 21:52:58,591 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1027}

2018-01-01 21:52:58,591 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,595 : INFO : < 200 OK [3332]
2018-01-01 21:52:58,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 959}
2018-01-01 21:52:58,603 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,607 : INFO : < 200 OK [3329]
2018-01-01 21:52:58,607 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 384, '_0n1': 1118}
2018-01-01 21:52:58,611 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,615 : INFO : < 200 OK [3311]
2018-01-01 21:52:58,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 401, '_0n1': 1060}
2018-01-01 21:52:58,620 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,625 : INFO : < 200 OK [3290]
2018-01-01 21:52:58,630 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 401, '_0n1': 987}
2018-01-01 21:52:58,632 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,634 : INFO : < 200 OK [3281]
2018-01-01 21:52:58,638 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 385, '_0n1': 1119}
2018-01-01 21:52:58,638 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,646 : INFO : < 200 OK [3359]
2018-01-01 21:52:58,646 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 402, '_0n1': 1163}
2018-01-01 21:52:58,650 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,654 : INFO : < 200 OK [3281]
2018-01-01 21:52:58,654 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 402, '_0n1': 1046}
2018-01-01 21:52:58,658 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,662 : INFO : < 200 OK [3285]
2018-01-01 21:52:58,666 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 386, '_0n1': 811}
2018-01-01 21:52:58,666 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,670 : INFO : < 200 OK [3266]
2018-01-01 21:52:58,674 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 403, '_0n1': 1119}
2018-01-01 21:52:58,674 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,678 : INFO : < 200 OK [3363]
2018-01-01 21:52:58,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 387, '_0n1': 1120}
2018-01-01 21:52:58,682 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,686 : INFO : < 200 OK [3362]
2018-01-01 21:52:58,690 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 387, '_0n1': 925}
2018-01-01 21:52:58,690 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,694 : INFO : < 200 OK [3350]
2018-01-01 21:52:58,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 404, '_0n1': 811}
2018-01-01 21:52:58,698 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,702 : INFO : < 200 OK [3274]
2018-01-01 21:52:58,706 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 388, '_0n1': 1119}
2018-01-01 21:52:58,710 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,714 : INFO : < 200 OK [3368]
2018-01-01 21:52:58,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 854}
2018-01-01 21:52:58,718 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,723 : INFO : < 200 OK [3323]
2018-01-01 21:52:58,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 988}
2018-01-01 21:52:58,727 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,732 : INFO : < 200 OK [3319]
2018-01-01 21:52:58,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 787}
2018-01-01 21:52:58,735 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,739 : INFO : < 200 OK [3314]
2018-01-01 21:52:58,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1087}
2018-01-01 21:52:58,743 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,747 : INFO : < 200 OK [3332]
2018-01-01 21:52:58,751 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 981}
2018-01-01 21:52:58,751 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,755 : INFO : < 200 OK [3316]
2018-01-01 21:52:58,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 819}
2018-01-01 21:52:58,763 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,767 : INFO : < 200 OK [3316]
2018-01-01 21:52:58,771 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 985}
2018-01-01 21:52:58,771 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,779 : INFO : < 200 OK [3297]
2018-01-01 21:52:58,783 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 406, '_0n1': 839}
2018-01-01 21:52:58,783 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,787 : INFO : < 200 OK [3268]
2018-01-01 21:52:58,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 406, '_0n1': 1134}
2018-01-01 21:52:58,795 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,799 : INFO : < 200 OK [3287]
2018-01-01 21:52:58,803 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 390, '_0n1': 925}
2018-01-01 21:52:58,803 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,807 : INFO : < 200 OK [3289]
2018-01-01 21:52:58,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 390, '_0n1': 1120}
2018-01-01 21:52:58,811 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,815 : INFO : < 200 OK [3301]
2018-01-01 21:52:58,820 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 407, '_0n1': 979}

2018-01-01 21:52:58,822 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,826 : INFO : < 200 OK [3296]
2018-01-01 21:52:58,830 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 391, '_0n1': 1120}
2018-01-01 21:52:58,831 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,835 : INFO : < 200 OK [3297]
2018-01-01 21:52:58,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 391, '_0n1': 925}
2018-01-01 21:52:58,839 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,843 : INFO : < 200 OK [3285]
2018-01-01 21:52:58,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 408, '_0n1': 925}
2018-01-01 21:52:58,847 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,851 : INFO : < 200 OK [3289]
2018-01-01 21:52:58,855 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 408, '_0n1': 1120}
2018-01-01 21:52:58,855 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,863 : INFO : < 200 OK [3301]
2018-01-01 21:52:58,863 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 892}
2018-01-01 21:52:58,867 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,871 : INFO : < 200 OK [3261]
2018-01-01 21:52:58,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 760}
2018-01-01 21:52:58,875 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,879 : INFO : < 200 OK [3265]
2018-01-01 21:52:58,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 724}
2018-01-01 21:52:58,883 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,887 : INFO : < 200 OK [3263]
2018-01-01 21:52:58,891 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 409, '_0n1': 1114}
2018-01-01 21:52:58,891 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,895 : INFO : < 200 OK [3300]
2018-01-01 21:52:58,899 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 393, '_0n1': 979}
2018-01-01 21:52:58,899 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,903 : INFO : < 200 OK [3304]
2018-01-01 21:52:58,907 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 410, '_0n1': 1114}
2018-01-01 21:52:58,907 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,915 : INFO : < 200 OK [3318]
2018-01-01 21:52:58,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 394, '_0n1': 979}
2018-01-01 21:52:58,923 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,929 : INFO : < 200 OK [3292]
2018-01-01 21:52:58,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 411, '_0n1': 979}
2018-01-01 21:52:58,934 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,939 : INFO : < 200 OK [3296]
2018-01-01 21:52:58,943 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 395, '_0n1': 986}
2018-01-01 21:52:58,943 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,947 : INFO : < 200 OK [3299]
2018-01-01 21:52:58,951 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 412, '_0n1': 1028}
2018-01-01 21:52:58,951 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,959 : INFO : < 200 OK [3307]
2018-01-01 21:52:58,959 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 396, '_0n1': 1190}
2018-01-01 21:52:58,963 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,967 : INFO : < 200 OK [3320]
2018-01-01 21:52:58,971 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 413, '_0n1': 975}
2018-01-01 21:52:58,971 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,979 : INFO : < 200 OK [3306]
2018-01-01 21:52:58,979 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 397, '_0n1': 1087}
2018-01-01 21:52:58,983 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:58,987 : INFO : < 200 OK [3294]
2018-01-01 21:52:58,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 397, '_0n1': 817}
2018-01-01 21:52:58,991 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:58,995 : INFO : < 200 OK [3281]
2018-01-01 21:52:58,999 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 414, '_0n1': 925}
2018-01-01 21:52:58,999 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,003 : INFO : < 200 OK [3248]
2018-01-01 21:52:59,007 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 414, '_0n1': 1120}
2018-01-01 21:52:59,007 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,011 : INFO : < 200 OK [3260]
2018-01-01 21:52:59,015 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 398, '_0n1': 862}
2018-01-01 21:52:59,015 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,023 : INFO : < 200 OK [3315]
2018-01-01 21:52:59,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 908}
2018-01-01 21:52:59,028 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,035 : INFO : < 200 OK [3265]
2018-01-01 21:52:59,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 399, '_0n1': 892}
2018-01-01 21:52:59,039 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,047 : INFO : < 200 OK [3270]
2018-01-01 21:52:59,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 399, '_0n1': 724}
2018-01-01 21:52:59,051 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,055 : INFO : < 200 OK [3272]
2018-01-01 21:52:59,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 399, '_0n1': 760}

2018-01-01 21:52:59,059 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,067 : INFO : < 200 OK [3274]
2018-01-01 21:52:59,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 416, '_0n1': 729}
2018-01-01 21:52:59,071 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,075 : INFO : < 200 OK [3295]
2018-01-01 21:52:59,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 420, '_0n1': 1046}
2018-01-01 21:52:59,079 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,083 : INFO : < 200 OK [3279]
2018-01-01 21:52:59,087 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 420, '_0n1': 1122}
2018-01-01 21:52:59,087 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,095 : INFO : < 200 OK [3279]
2018-01-01 21:52:59,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 417, '_0n1': 1189}
2018-01-01 21:52:59,099 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,103 : INFO : < 200 OK [3330]
2018-01-01 21:52:59,107 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 421, '_0n1': 721}
2018-01-01 21:52:59,107 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,111 : INFO : < 200 OK [3308]
2018-01-01 21:52:59,115 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 418, '_0n1': 908}
2018-01-01 21:52:59,115 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,122 : INFO : < 200 OK [3270]
2018-01-01 21:52:59,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 422, '_0n1': 729}
2018-01-01 21:52:59,126 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,130 : INFO : < 200 OK [3295]
2018-01-01 21:52:59,133 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 760}
2018-01-01 21:52:59,134 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,135 : INFO : < 200 OK [3306]
2018-01-01 21:52:59,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1191}
2018-01-01 21:52:59,139 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,143 : INFO : < 200 OK [3318]
2018-01-01 21:52:59,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 423, '_0n1': 888}
2018-01-01 21:52:59,147 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,151 : INFO : < 200 OK [3287]
2018-01-01 21:52:59,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 423, '_0n1': 929}
2018-01-01 21:52:59,155 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,159 : INFO : < 200 OK [3292]
2018-01-01 21:52:59,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 440, '_0n1': 888}
2018-01-01 21:52:59,163 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,167 : INFO : < 200 OK [3280]
2018-01-01 21:52:59,171 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 440, '_0n1': 929}
2018-01-01 21:52:59,175 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,179 : INFO : < 200 OK [3285]
2018-01-01 21:52:59,183 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 424, '_0n1': 1113}
2018-01-01 21:52:59,187 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,191 : INFO : < 200 OK [3325]
2018-01-01 21:52:59,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 956}
2018-01-01 21:52:59,195 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,203 : INFO : < 200 OK [3296]
2018-01-01 21:52:59,207 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 1136}
2018-01-01 21:52:59,207 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,211 : INFO : < 200 OK [3309]
2018-01-01 21:52:59,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 425, '_0n1': 1078}
2018-01-01 21:52:59,215 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,223 : INFO : < 200 OK [3294]
2018-01-01 21:52:59,226 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 442, '_0n1': 750}
2018-01-01 21:52:59,229 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,233 : INFO : < 200 OK [3279]
2018-01-01 21:52:59,235 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 426, '_0n1': 1148}
2018-01-01 21:52:59,235 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,239 : INFO : < 200 OK [3246]
2018-01-01 21:52:59,243 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 426, '_0n1': 876}
2018-01-01 21:52:59,247 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,251 : INFO : < 200 OK [3230]
2018-01-01 21:52:59,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 426, '_0n1': 1068}
2018-01-01 21:52:59,255 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,259 : INFO : < 200 OK [3247]
2018-01-01 21:52:59,259 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 426, '_0n1': 698}
2018-01-01 21:52:59,263 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,267 : INFO : < 200 OK [3229]
2018-01-01 21:52:59,271 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 817}
2018-01-01 21:52:59,271 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,275 : INFO : < 200 OK [3325]
2018-01-01 21:52:59,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1087}
2018-01-01 21:52:59,279 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,283 : INFO : < 200 OK [3338]
2018-01-01 21:52:59,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 787}

2018-01-01 21:52:59,287 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,291 : INFO : < 200 OK [3320]
2018-01-01 21:52:59,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 697}
2018-01-01 21:52:59,295 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,303 : INFO : < 200 OK [3325]
2018-01-01 21:52:59,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 427, '_0n1': 929}
2018-01-01 21:52:59,307 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,315 : INFO : < 200 OK [3275]
2018-01-01 21:52:59,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 427, '_0n1': 888}
2018-01-01 21:52:59,322 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,326 : INFO : < 200 OK [3270]
2018-01-01 21:52:59,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 444, '_0n1': 908}
2018-01-01 21:52:59,332 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,335 : INFO : < 200 OK [3309]
2018-01-01 21:52:59,339 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 428, '_0n1': 888}
2018-01-01 21:52:59,339 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,343 : INFO : < 200 OK [3266]
2018-01-01 21:52:59,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 428, '_0n1': 929}
2018-01-01 21:52:59,347 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,351 : INFO : < 200 OK [3271]
2018-01-01 21:52:59,355 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 445, '_0n1': 729}
2018-01-01 21:52:59,355 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,359 : INFO : < 200 OK [3306]
2018-01-01 21:52:59,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 429, '_0n1': 889}
2018-01-01 21:52:59,367 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,371 : INFO : < 200 OK [3316]
2018-01-01 21:52:59,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 429, '_0n1': 1169}
2018-01-01 21:52:59,375 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,379 : INFO : < 200 OK [3326]
2018-01-01 21:52:59,383 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 446, '_0n1': 729}
2018-01-01 21:52:59,383 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,387 : INFO : < 200 OK [3316]
2018-01-01 21:52:59,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 430, '_0n1': 918}
2018-01-01 21:52:59,391 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,395 : INFO : < 200 OK [3293]
2018-01-01 21:52:59,399 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 447, '_0n1': 1180}
2018-01-01 21:52:59,399 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,407 : INFO : < 200 OK [3328]
2018-01-01 21:52:59,407 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 971}
2018-01-01 21:52:59,411 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,415 : INFO : < 200 OK [3255]
2018-01-01 21:52:59,421 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1030}
2018-01-01 21:52:59,423 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,428 : INFO : < 200 OK [3271]
2018-01-01 21:52:59,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 741}
2018-01-01 21:52:59,434 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,439 : INFO : < 200 OK [3254]
2018-01-01 21:52:59,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 448, '_0n1': 1085}
2018-01-01 21:52:59,443 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,447 : INFO : < 200 OK [3286]
2018-01-01 21:52:59,451 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 432, '_0n1': 859}
2018-01-01 21:52:59,451 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,455 : INFO : < 200 OK [3279]
2018-01-01 21:52:59,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 449, '_0n1': 1153}
2018-01-01 21:52:59,459 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,467 : INFO : < 200 OK [3291]
2018-01-01 21:52:59,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 433, '_0n1': 1046}
2018-01-01 21:52:59,471 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,475 : INFO : < 200 OK [3295]
2018-01-01 21:52:59,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 433, '_0n1': 1122}
2018-01-01 21:52:59,479 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,483 : INFO : < 200 OK [3295]
2018-01-01 21:52:59,483 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 450, '_0n1': 721}
2018-01-01 21:52:59,487 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,491 : INFO : < 200 OK [3316]
2018-01-01 21:52:59,495 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 434, '_0n1': 777}
2018-01-01 21:52:59,495 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,499 : INFO : < 200 OK [3228]
2018-01-01 21:52:59,503 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 434, '_0n1': 834}
2018-01-01 21:52:59,503 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,507 : INFO : < 200 OK [3229]
2018-01-01 21:52:59,511 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 434, '_0n1': 893}
2018-01-01 21:52:59,511 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,515 : INFO : < 200 OK [3232]
2018-01-01 21:52:59,520 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 451, '_0n1': 733}

2018-01-01 21:52:59,522 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,525 : INFO : < 200 OK [3242]
2018-01-01 21:52:59,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 451, '_0n1': 916}
2018-01-01 21:52:59,529 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,533 : INFO : < 200 OK [3233]
2018-01-01 21:52:59,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 451, '_0n1': 899}
2018-01-01 21:52:59,539 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,543 : INFO : < 200 OK [3230]
2018-01-01 21:52:59,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 435, '_0n1': 721}
2018-01-01 21:52:59,551 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,555 : INFO : < 200 OK [3285]
2018-01-01 21:52:59,559 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 452, '_0n1': 1046}
2018-01-01 21:52:59,563 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,567 : INFO : < 200 OK [3319]
2018-01-01 21:52:59,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 452, '_0n1': 1122}
2018-01-01 21:52:59,571 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,575 : INFO : < 200 OK [3319]
2018-01-01 21:52:59,579 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 436, '_0n1': 1162}
2018-01-01 21:52:59,579 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,587 : INFO : < 200 OK [3306]
2018-01-01 21:52:59,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 852}
2018-01-01 21:52:59,591 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,595 : INFO : < 200 OK [3338]
2018-01-01 21:52:59,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1026}
2018-01-01 21:52:59,599 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,603 : INFO : < 200 OK [3347]
2018-01-01 21:52:59,607 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 988}
2018-01-01 21:52:59,607 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,611 : INFO : < 200 OK [3333]
2018-01-01 21:52:59,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1087}
2018-01-01 21:52:59,615 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,622 : INFO : < 200 OK [3346]
2018-01-01 21:52:59,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 437, '_0n1': 892}
2018-01-01 21:52:59,626 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,630 : INFO : < 200 OK [3262]
2018-01-01 21:52:59,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 437, '_0n1': 724}
2018-01-01 21:52:59,634 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,635 : INFO : < 200 OK [3264]
2018-01-01 21:52:59,639 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 437, '_0n1': 760}
2018-01-01 21:52:59,639 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,643 : INFO : < 200 OK [3266]
2018-01-01 21:52:59,647 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 454, '_0n1': 721}
2018-01-01 21:52:59,651 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,655 : INFO : < 200 OK [3317]
2018-01-01 21:52:59,659 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 438, '_0n1': 943}
2018-01-01 21:52:59,663 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,667 : INFO : < 200 OK [3323]
2018-01-01 21:52:59,671 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 455, '_0n1': 747}
2018-01-01 21:52:59,675 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,679 : INFO : < 200 OK [3260]
2018-01-01 21:52:59,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 455, '_0n1': 1160}
2018-01-01 21:52:59,683 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,687 : INFO : < 200 OK [3282]
2018-01-01 21:52:59,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 439, '_0n1': 1133}
2018-01-01 21:52:59,691 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,699 : INFO : < 200 OK [3325]
2018-01-01 21:52:59,699 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 439, '_0n1': 1091}
2018-01-01 21:52:59,703 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,707 : INFO : < 200 OK [3323]
2018-01-01 21:52:59,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 456, '_0n1': 956}
2018-01-01 21:52:59,711 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,715 : INFO : < 200 OK [3292]
2018-01-01 21:52:59,720 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 456, '_0n1': 1136}
2018-01-01 21:52:59,721 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,726 : INFO : < 200 OK [3305]
2018-01-01 21:52:59,729 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 460, '_0n1': 916}
2018-01-01 21:52:59,731 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,735 : INFO : < 200 OK [3265]
2018-01-01 21:52:59,735 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 460, '_0n1': 733}
2018-01-01 21:52:59,739 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,743 : INFO : < 200 OK [3274]
2018-01-01 21:52:59,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 956}
2018-01-01 21:52:59,747 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,751 : INFO : < 200 OK [3287]
2018-01-01 21:52:59,755 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 1136}

2018-01-01 21:52:59,755 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,759 : INFO : < 200 OK [3300]
2018-01-01 21:52:59,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 461, '_0n1': 1122}
2018-01-01 21:52:59,763 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,771 : INFO : < 200 OK [3283]
2018-01-01 21:52:59,771 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 458, '_0n1': 968}
2018-01-01 21:52:59,775 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,779 : INFO : < 200 OK [3284]
2018-01-01 21:52:59,783 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 462, '_0n1': 1169}
2018-01-01 21:52:59,783 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,791 : INFO : < 200 OK [3323]
2018-01-01 21:52:59,795 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 462, '_0n1': 718}
2018-01-01 21:52:59,795 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,799 : INFO : < 200 OK [3308]
2018-01-01 21:52:59,803 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 459, '_0n1': 855}
2018-01-01 21:52:59,807 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,811 : INFO : < 200 OK [3317]
2018-01-01 21:52:59,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 775}
2018-01-01 21:52:59,819 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,824 : INFO : < 200 OK [3285]
2018-01-01 21:52:59,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 480, '_0n1': 760}
2018-01-01 21:52:59,828 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,832 : INFO : < 200 OK [3299]
2018-01-01 21:52:59,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 480, '_0n1': 1191}
2018-01-01 21:52:59,835 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,839 : INFO : < 200 OK [3311]
2018-01-01 21:52:59,843 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 464, '_0n1': 1171}
2018-01-01 21:52:59,843 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,847 : INFO : < 200 OK [3329]
2018-01-01 21:52:59,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 481, '_0n1': 892}
2018-01-01 21:52:59,851 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,855 : INFO : < 200 OK [3268]
2018-01-01 21:52:59,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 481, '_0n1': 724}
2018-01-01 21:52:59,859 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,863 : INFO : < 200 OK [3270]
2018-01-01 21:52:59,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 481, '_0n1': 760}
2018-01-01 21:52:59,867 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,871 : INFO : < 200 OK [3272]
2018-01-01 21:52:59,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 465, '_0n1': 1134}
2018-01-01 21:52:59,875 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,879 : INFO : < 200 OK [3286]
2018-01-01 21:52:59,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 482, '_0n1': 724}
2018-01-01 21:52:59,883 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,887 : INFO : < 200 OK [3267]
2018-01-01 21:52:59,891 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 482, '_0n1': 892}
2018-01-01 21:52:59,891 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,895 : INFO : < 200 OK [3265]
2018-01-01 21:52:59,899 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 482, '_0n1': 760}
2018-01-01 21:52:59,899 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,903 : INFO : < 200 OK [3269]
2018-01-01 21:52:59,907 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 466, '_0n1': 1061}
2018-01-01 21:52:59,907 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,915 : INFO : < 200 OK [3305]
2018-01-01 21:52:59,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 466, '_0n1': 954}
2018-01-01 21:52:59,924 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,928 : INFO : < 200 OK [3289]
2018-01-01 21:52:59,933 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 466, '_0n1': 952}
2018-01-01 21:52:59,935 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,939 : INFO : < 200 OK [3287]
2018-01-01 21:52:59,939 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 956}
2018-01-01 21:52:59,943 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,947 : INFO : < 200 OK [3294]
2018-01-01 21:52:59,951 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 1136}
2018-01-01 21:52:59,951 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,955 : INFO : < 200 OK [3307]
2018-01-01 21:52:59,959 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 467, '_0n1': 889}
2018-01-01 21:52:59,959 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,963 : INFO : < 200 OK [3303]
2018-01-01 21:52:59,967 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 484, '_0n1': 906}
2018-01-01 21:52:59,971 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,975 : INFO : < 200 OK [3301]
2018-01-01 21:52:59,979 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 468, '_0n1': 856}
2018-01-01 21:52:59,979 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,983 : INFO : < 200 OK [3270]
2018-01-01 21:52:59,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 468, '_0n1': 976}

2018-01-01 21:52:59,987 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:52:59,991 : INFO : < 200 OK [3275]
2018-01-01 21:52:59,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 485, '_0n1': 1078}
2018-01-01 21:52:59,995 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:52:59,999 : INFO : < 200 OK [3341]
2018-01-01 21:53:00,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 469, '_0n1': 1169}
2018-01-01 21:53:00,003 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,011 : INFO : < 200 OK [3333]
2018-01-01 21:53:00,015 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 469, '_0n1': 718}
2018-01-01 21:53:00,015 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,023 : INFO : < 200 OK [3318]
2018-01-01 21:53:00,025 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 486, '_0n1': 994}
2018-01-01 21:53:00,026 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,031 : INFO : < 200 OK [3267]
2018-01-01 21:53:00,034 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 470, '_0n1': 1119}
2018-01-01 21:53:00,035 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,040 : INFO : < 200 OK [3356]
2018-01-01 21:53:00,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 500, '_0n1': 994}
2018-01-01 21:53:00,044 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,048 : INFO : < 200 OK [3268]
2018-01-01 21:53:00,052 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 471, '_0n1': 1124}
2018-01-01 21:53:00,052 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,056 : INFO : < 200 OK [3306]
2018-01-01 21:53:00,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 471, '_0n1': 933}
2018-01-01 21:53:00,060 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,064 : INFO : < 200 OK [3292]
2018-01-01 21:53:00,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 501, '_0n1': 1182}
2018-01-01 21:53:00,068 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,072 : INFO : < 200 OK [3317]
2018-01-01 21:53:00,076 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 472, '_0n1': 1045}
2018-01-01 21:53:00,076 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,084 : INFO : < 200 OK [3287]
2018-01-01 21:53:00,088 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 472, '_0n1': 972}
2018-01-01 21:53:00,088 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,096 : INFO : < 200 OK [3255]
2018-01-01 21:53:00,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 502, '_0n1': 1129}
2018-01-01 21:53:00,100 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,104 : INFO : < 200 OK [3280]
2018-01-01 21:53:00,112 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 473, '_0n1': 775}
2018-01-01 21:53:00,112 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,116 : INFO : < 200 OK [3285]
2018-01-01 21:53:00,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 503, '_0n1': 1101}
2018-01-01 21:53:00,123 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,127 : INFO : < 200 OK [3291]
2018-01-01 21:53:00,129 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 503, '_0n1': 924}
2018-01-01 21:53:00,131 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,135 : INFO : < 200 OK [3277]
2018-01-01 21:53:00,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 474, '_0n1': 742}
2018-01-01 21:53:00,139 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,143 : INFO : < 200 OK [3313]
2018-01-01 21:53:00,143 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 504, '_0n1': 791}
2018-01-01 21:53:00,147 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,151 : INFO : < 200 OK [3269]
2018-01-01 21:53:00,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 475, '_0n1': 1078}
2018-01-01 21:53:00,155 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,159 : INFO : < 200 OK [3294]
2018-01-01 21:53:00,159 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 505, '_0n1': 1089}
2018-01-01 21:53:00,163 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,167 : INFO : < 200 OK [3316]
2018-01-01 21:53:00,167 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 476, '_0n1': 783}
2018-01-01 21:53:00,171 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,175 : INFO : < 200 OK [3283]
2018-01-01 21:53:00,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 506, '_0n1': 1116}
2018-01-01 21:53:00,179 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,183 : INFO : < 200 OK [3292]
2018-01-01 21:53:00,187 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 477, '_0n1': 1130}
2018-01-01 21:53:00,187 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,195 : INFO : < 200 OK [3311]
2018-01-01 21:53:00,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 507, '_0n1': 823}
2018-01-01 21:53:00,199 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,207 : INFO : < 200 OK [3326]
2018-01-01 21:53:00,211 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 478, '_0n1': 1078}
2018-01-01 21:53:00,211 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,220 : INFO : < 200 OK [3332]

2018-01-01 21:53:00,223 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 813}
2018-01-01 21:53:00,226 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,230 : INFO : < 200 OK [3314]
2018-01-01 21:53:00,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 1143}
2018-01-01 21:53:00,235 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,239 : INFO : < 200 OK [3329]
2018-01-01 21:53:00,239 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 1138}
2018-01-01 21:53:00,243 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,247 : INFO : < 200 OK [3326]
2018-01-01 21:53:00,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 479, '_0n1': 898}
2018-01-01 21:53:00,251 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,259 : INFO : < 200 OK [3312]
2018-01-01 21:53:00,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 509, '_0n1': 1021}
2018-01-01 21:53:00,263 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,267 : INFO : < 200 OK [3337]
2018-01-01 21:53:00,271 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 509, '_0n1': 846}
2018-01-01 21:53:00,271 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,279 : INFO : < 200 OK [3315]
2018-01-01 21:53:00,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 760}
2018-01-01 21:53:00,283 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,287 : INFO : < 200 OK [3310]
2018-01-01 21:53:00,291 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 1191}
2018-01-01 21:53:00,291 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,299 : INFO : < 200 OK [3322]
2018-01-01 21:53:00,299 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 510, '_0n1': 839}
2018-01-01 21:53:00,303 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,307 : INFO : < 200 OK [3253]
2018-01-01 21:53:00,311 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 510, '_0n1': 1134}
2018-01-01 21:53:00,315 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,320 : INFO : < 200 OK [3272]
2018-01-01 21:53:00,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 514, '_0n1': 825}
2018-01-01 21:53:00,325 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,330 : INFO : < 200 OK [3288]
2018-01-01 21:53:00,334 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 511, '_0n1': 936}
2018-01-01 21:53:00,335 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,339 : INFO : < 200 OK [3303]
2018-01-01 21:53:00,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 515, '_0n1': 1035}
2018-01-01 21:53:00,343 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,351 : INFO : < 200 OK [3290]
2018-01-01 21:53:00,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 512, '_0n1': 720}
2018-01-01 21:53:00,355 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,359 : INFO : < 200 OK [3273]
2018-01-01 21:53:00,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 512, '_0n1': 1074}
2018-01-01 21:53:00,367 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,371 : INFO : < 200 OK [3288]
2018-01-01 21:53:00,375 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 516, '_0n1': 760}
2018-01-01 21:53:00,375 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,383 : INFO : < 200 OK [3296]
2018-01-01 21:53:00,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 516, '_0n1': 1191}
2018-01-01 21:53:00,391 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,399 : INFO : < 200 OK [3308]
2018-01-01 21:53:00,407 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 533, '_0n1': 913}
2018-01-01 21:53:00,407 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,415 : INFO : < 200 OK [3288]
2018-01-01 21:53:00,420 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 533, '_0n1': 727}
2018-01-01 21:53:00,422 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,427 : INFO : < 200 OK [3287]
2018-01-01 21:53:00,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 517, '_0n1': 1023}
2018-01-01 21:53:00,434 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,435 : INFO : < 200 OK [3302]
2018-01-01 21:53:00,439 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 517, '_0n1': 1202}
2018-01-01 21:53:00,443 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,447 : INFO : < 200 OK [3301]
2018-01-01 21:53:00,451 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 534, '_0n1': 1085}
2018-01-01 21:53:00,451 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,455 : INFO : < 200 OK [3303]
2018-01-01 21:53:00,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 518, '_0n1': 807}
2018-01-01 21:53:00,463 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,467 : INFO : < 200 OK [3270]
2018-01-01 21:53:00,471 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 518, '_0n1': 723}
2018-01-01 21:53:00,471 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,475 : INFO : < 200 OK [3274]
2018-01-01 21:53:00,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 535, '_0n1': 1033}

2018-01-01 21:53:00,483 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,487 : INFO : < 200 OK [3303]
2018-01-01 21:53:00,491 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 519, '_0n1': 802}
2018-01-01 21:53:00,491 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,495 : INFO : < 200 OK [3299]
2018-01-01 21:53:00,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 536, '_0n1': 1149}
2018-01-01 21:53:00,499 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,507 : INFO : < 200 OK [3303]
2018-01-01 21:53:00,511 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 520, '_0n1': 1024}
2018-01-01 21:53:00,511 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,515 : INFO : < 200 OK [3317]
2018-01-01 21:53:00,521 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 537, '_0n1': 1045}
2018-01-01 21:53:00,523 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,527 : INFO : < 200 OK [3287]
2018-01-01 21:53:00,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 537, '_0n1': 972}
2018-01-01 21:53:00,533 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,535 : INFO : < 200 OK [3255]
2018-01-01 21:53:00,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 521, '_0n1': 1116}
2018-01-01 21:53:00,539 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,543 : INFO : < 200 OK [3294]
2018-01-01 21:53:00,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 521, '_0n1': 791}
2018-01-01 21:53:00,547 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,555 : INFO : < 200 OK [3275]
2018-01-01 21:53:00,559 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 521, '_0n1': 968}
2018-01-01 21:53:00,559 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,563 : INFO : < 200 OK [3281]
2018-01-01 21:53:00,567 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 538, '_0n1': 865}
2018-01-01 21:53:00,571 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,575 : INFO : < 200 OK [3304]
2018-01-01 21:53:00,579 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 522, '_0n1': 997}
2018-01-01 21:53:00,583 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,587 : INFO : < 200 OK [3274]
2018-01-01 21:53:00,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 539, '_0n1': 775}
2018-01-01 21:53:00,591 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,595 : INFO : < 200 OK [3269]
2018-01-01 21:53:00,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 523, '_0n1': 1067}
2018-01-01 21:53:00,603 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,607 : INFO : < 200 OK [3332]
2018-01-01 21:53:00,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 540, '_0n1': 783}
2018-01-01 21:53:00,615 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,621 : INFO : < 200 OK [3264]
2018-01-01 21:53:00,626 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 524, '_0n1': 917}
2018-01-01 21:53:00,628 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,634 : INFO : < 200 OK [3297]
2018-01-01 21:53:00,635 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 541, '_0n1': 1078}
2018-01-01 21:53:00,639 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,643 : INFO : < 200 OK [3294]
2018-01-01 21:53:00,647 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 817}
2018-01-01 21:53:00,647 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,651 : INFO : < 200 OK [3288]
2018-01-01 21:53:00,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 988}
2018-01-01 21:53:00,655 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,659 : INFO : < 200 OK [3288]
2018-01-01 21:53:00,663 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 787}
2018-01-01 21:53:00,667 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,671 : INFO : < 200 OK [3283]
2018-01-01 21:53:00,675 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1087}
2018-01-01 21:53:00,675 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,679 : INFO : < 200 OK [3301]
2018-01-01 21:53:00,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 542, '_0n1': 997}
2018-01-01 21:53:00,687 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,691 : INFO : < 200 OK [3285]
2018-01-01 21:53:00,695 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 526, '_0n1': 966}
2018-01-01 21:53:00,695 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,836 : INFO : < 200 OK [3351]
2018-01-01 21:53:00,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 543, '_0n1': 892}
2018-01-01 21:53:00,844 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,852 : INFO : < 200 OK [3271]
2018-01-01 21:53:00,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 543, '_0n1': 724}
2018-01-01 21:53:00,856 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,864 : INFO : < 200 OK [3273]
2018-01-01 21:53:00,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 543, '_0n1': 760}
2018-01-01 21:53:00,868 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,872 : INFO : < 200 OK [3275]
2018-01-01 21:53:00,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 527, '_0n1': 1157}

2018-01-01 21:53:00,880 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,884 : INFO : < 200 OK [3319]
2018-01-01 21:53:00,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 544, '_0n1': 856}
2018-01-01 21:53:00,888 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,892 : INFO : < 200 OK [3289]
2018-01-01 21:53:00,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 544, '_0n1': 976}
2018-01-01 21:53:00,896 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,900 : INFO : < 200 OK [3294]
2018-01-01 21:53:00,904 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 544, '_0n1': 1153}
2018-01-01 21:53:00,908 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,912 : INFO : < 200 OK [3300]
2018-01-01 21:53:00,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 544, '_0n1': 750}
2018-01-01 21:53:00,916 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,922 : INFO : < 200 OK [3290]
2018-01-01 21:53:00,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 528, '_0n1': 1105}
2018-01-01 21:53:00,927 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,931 : INFO : < 200 OK [3369]
2018-01-01 21:53:00,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 545, '_0n1': 1024}
2018-01-01 21:53:00,936 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,940 : INFO : < 200 OK [3317]
2018-01-01 21:53:00,944 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 529, '_0n1': 1042}
2018-01-01 21:53:00,944 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,948 : INFO : < 200 OK [3350]
2018-01-01 21:53:00,952 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 546, '_0n1': 889}
2018-01-01 21:53:00,956 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,960 : INFO : < 200 OK [3317]
2018-01-01 21:53:00,960 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 546, '_0n1': 718}
2018-01-01 21:53:00,964 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,968 : INFO : < 200 OK [3312]
2018-01-01 21:53:00,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 530, '_0n1': 1079}
2018-01-01 21:53:00,972 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:00,976 : INFO : < 200 OK [3274]
2018-01-01 21:53:00,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 547, '_0n1': 888}
2018-01-01 21:53:00,980 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,984 : INFO : < 200 OK [3306]
2018-01-01 21:53:00,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 547, '_0n1': 929}
2018-01-01 21:53:00,992 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:00,996 : INFO : < 200 OK [3311]
2018-01-01 21:53:00,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 531, '_0n1': 1042}
2018-01-01 21:53:01,000 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,004 : INFO : < 200 OK [3325]
2018-01-01 21:53:01,008 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 548, '_0n1': 994}
2018-01-01 21:53:01,008 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,012 : INFO : < 200 OK [3255]
2018-01-01 21:53:01,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 548, '_0n1': 811}
2018-01-01 21:53:01,016 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,023 : INFO : < 200 OK [3260]
2018-01-01 21:53:01,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 548, '_0n1': 1092}
2018-01-01 21:53:01,028 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,032 : INFO : < 200 OK [3272]
2018-01-01 21:53:01,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 532, '_0n1': 775}
2018-01-01 21:53:01,036 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,040 : INFO : < 200 OK [3275]
2018-01-01 21:53:01,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 549, '_0n1': 1050}
2018-01-01 21:53:01,044 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,048 : INFO : < 200 OK [3323]
2018-01-01 21:53:01,052 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 553, '_0n1': 1046}
2018-01-01 21:53:01,052 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,060 : INFO : < 200 OK [3282]
2018-01-01 21:53:01,064 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 553, '_0n1': 1122}
2018-01-01 21:53:01,064 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,068 : INFO : < 200 OK [3282]
2018-01-01 21:53:01,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 550, '_0n1': 729}
2018-01-01 21:53:01,072 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,080 : INFO : < 200 OK [3337]
2018-01-01 21:53:01,084 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 554, '_0n1': 1085}
2018-01-01 21:53:01,084 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,088 : INFO : < 200 OK [3330]
2018-01-01 21:53:01,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 554, '_0n1': 1130}
2018-01-01 21:53:01,096 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,100 : INFO : < 200 OK [3330]
2018-01-01 21:53:01,104 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 551, '_0n1': 1155}
2018-01-01 21:53:01,108 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,112 : INFO : < 200 OK [3300]
2018-01-01 21:53:01,116 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 551, '_0n1': 1015}

2018-01-01 21:53:01,120 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,124 : INFO : < 200 OK [3292]
2018-01-01 21:53:01,128 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 551, '_0n1': 1020}
2018-01-01 21:53:01,130 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,134 : INFO : < 200 OK [3292]
2018-01-01 21:53:01,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 555, '_0n1': 783}
2018-01-01 21:53:01,135 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,144 : INFO : < 200 OK [3278]
2018-01-01 21:53:01,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 552, '_0n1': 892}
2018-01-01 21:53:01,148 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,152 : INFO : < 200 OK [3269]
2018-01-01 21:53:01,156 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 552, '_0n1': 1149}
2018-01-01 21:53:01,156 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,160 : INFO : < 200 OK [3295]
2018-01-01 21:53:01,164 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 556, '_0n1': 839}
2018-01-01 21:53:01,168 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,176 : INFO : < 200 OK [3275]
2018-01-01 21:53:01,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 556, '_0n1': 1134}
2018-01-01 21:53:01,184 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,188 : INFO : < 200 OK [3294]
2018-01-01 21:53:01,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 573, '_0n1': 935}
2018-01-01 21:53:01,196 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,200 : INFO : < 200 OK [3264]
2018-01-01 21:53:01,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 557, '_0n1': 760}
2018-01-01 21:53:01,204 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,212 : INFO : < 200 OK [3321]
2018-01-01 21:53:01,212 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 557, '_0n1': 1191}
2018-01-01 21:53:01,216 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,222 : INFO : < 200 OK [3333]
2018-01-01 21:53:01,226 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 574, '_0n1': 1116}
2018-01-01 21:53:01,230 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,234 : INFO : < 200 OK [3290]
2018-01-01 21:53:01,236 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 574, '_0n1': 791}
2018-01-01 21:53:01,236 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,240 : INFO : < 200 OK [3271]
2018-01-01 21:53:01,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 574, '_0n1': 968}
2018-01-01 21:53:01,248 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,252 : INFO : < 200 OK [3277]
2018-01-01 21:53:01,256 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 558, '_0n1': 908}
2018-01-01 21:53:01,256 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,264 : INFO : < 200 OK [3298]
2018-01-01 21:53:01,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 575, '_0n1': 755}
2018-01-01 21:53:01,268 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,272 : INFO : < 200 OK [3307]
2018-01-01 21:53:01,276 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 575, '_0n1': 944}
2018-01-01 21:53:01,276 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,280 : INFO : < 200 OK [3310]
2018-01-01 21:53:01,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 559, '_0n1': 1077}
2018-01-01 21:53:01,284 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,288 : INFO : < 200 OK [3321]
2018-01-01 21:53:01,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 559, '_0n1': 989}
2018-01-01 21:53:01,292 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,300 : INFO : < 200 OK [3310]
2018-01-01 21:53:01,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 576, '_0n1': 908}
2018-01-01 21:53:01,304 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,308 : INFO : < 200 OK [3274]
2018-01-01 21:53:01,308 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 560, '_0n1': 1170}
2018-01-01 21:53:01,312 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,316 : INFO : < 200 OK [3321]
2018-01-01 21:53:01,316 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 560, '_0n1': 848}
2018-01-01 21:53:01,321 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,325 : INFO : < 200 OK [3299]
2018-01-01 21:53:01,329 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 577, '_0n1': 1015}
2018-01-01 21:53:01,331 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,335 : INFO : < 200 OK [3319]
2018-01-01 21:53:01,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 577, '_0n1': 1020}
2018-01-01 21:53:01,340 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,344 : INFO : < 200 OK [3319]
2018-01-01 21:53:01,348 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 577, '_0n1': 1155}
2018-01-01 21:53:01,348 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,352 : INFO : < 200 OK [3327]
2018-01-01 21:53:01,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 561, '_0n1': 789}
2018-01-01 21:53:01,356 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,360 : INFO : < 200 OK [3306]
2018-01-01 21:53:01,364 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 578, '_0n1': 1139}

2018-01-01 21:53:01,364 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,368 : INFO : < 200 OK [3330]
2018-01-01 21:53:01,372 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 562, '_0n1': 1107}
2018-01-01 21:53:01,372 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,376 : INFO : < 200 OK [3278]
2018-01-01 21:53:01,380 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 962}
2018-01-01 21:53:01,380 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,384 : INFO : < 200 OK [3317]
2018-01-01 21:53:01,388 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 719}
2018-01-01 21:53:01,388 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,392 : INFO : < 200 OK [3316]
2018-01-01 21:53:01,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1025}
2018-01-01 21:53:01,396 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,400 : INFO : < 200 OK [3334]
2018-01-01 21:53:01,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 926}
2018-01-01 21:53:01,404 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,412 : INFO : < 200 OK [3318]
2018-01-01 21:53:01,412 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 563, '_0n1': 1053}
2018-01-01 21:53:01,416 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,421 : INFO : < 200 OK [3339]
2018-01-01 21:53:01,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 563, '_0n1': 827}
2018-01-01 21:53:01,425 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,429 : INFO : < 200 OK [3325]
2018-01-01 21:53:01,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 580, '_0n1': 790}
2018-01-01 21:53:01,433 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,435 : INFO : < 200 OK [3285]
2018-01-01 21:53:01,439 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 580, '_0n1': 749}
2018-01-01 21:53:01,439 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,443 : INFO : < 200 OK [3292]
2018-01-01 21:53:01,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 564, '_0n1': 915}
2018-01-01 21:53:01,451 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,455 : INFO : < 200 OK [3312]
2018-01-01 21:53:01,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 581, '_0n1': 1175}
2018-01-01 21:53:01,459 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,463 : INFO : < 200 OK [3303]
2018-01-01 21:53:01,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 565, '_0n1': 868}
2018-01-01 21:53:01,467 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,475 : INFO : < 200 OK [3333]
2018-01-01 21:53:01,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 582, '_0n1': 1043}
2018-01-01 21:53:01,479 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,487 : INFO : < 200 OK [3306]
2018-01-01 21:53:01,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 566, '_0n1': 934}
2018-01-01 21:53:01,491 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,495 : INFO : < 200 OK [3268]
2018-01-01 21:53:01,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 583, '_0n1': 831}
2018-01-01 21:53:01,499 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,503 : INFO : < 200 OK [3299]
2018-01-01 21:53:01,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 567, '_0n1': 830}
2018-01-01 21:53:01,507 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,511 : INFO : < 200 OK [3305]
2018-01-01 21:53:01,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1025}
2018-01-01 21:53:01,515 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,524 : INFO : < 200 OK [3338]
2018-01-01 21:53:01,526 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 719}
2018-01-01 21:53:01,528 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,532 : INFO : < 200 OK [3320]
2018-01-01 21:53:01,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 962}
2018-01-01 21:53:01,536 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,540 : INFO : < 200 OK [3321]
2018-01-01 21:53:01,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 926}
2018-01-01 21:53:01,548 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,552 : INFO : < 200 OK [3322]
2018-01-01 21:53:01,556 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 568, '_0n1': 746}
2018-01-01 21:53:01,560 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,564 : INFO : < 200 OK [3313]
2018-01-01 21:53:01,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 585, '_0n1': 1170}
2018-01-01 21:53:01,568 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,572 : INFO : < 200 OK [3297]
2018-01-01 21:53:01,580 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 585, '_0n1': 848}
2018-01-01 21:53:01,580 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,584 : INFO : < 200 OK [3275]
2018-01-01 21:53:01,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 569, '_0n1': 1139}
2018-01-01 21:53:01,588 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,592 : INFO : < 200 OK [3322]
2018-01-01 21:53:01,596 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 586, '_0n1': 890}

2018-01-01 21:53:01,596 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,604 : INFO : < 200 OK [3317]
2018-01-01 21:53:01,604 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 586, '_0n1': 1146}
2018-01-01 21:53:01,608 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,612 : INFO : < 200 OK [3344]
2018-01-01 21:53:01,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 1027}
2018-01-01 21:53:01,616 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,624 : INFO : < 200 OK [3291]
2018-01-01 21:53:01,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 793}
2018-01-01 21:53:01,629 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,634 : INFO : < 200 OK [3277]
2018-01-01 21:53:01,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 996}
2018-01-01 21:53:01,636 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,644 : INFO : < 200 OK [3279]
2018-01-01 21:53:01,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 735}
2018-01-01 21:53:01,648 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,652 : INFO : < 200 OK [3277]
2018-01-01 21:53:01,656 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1041}
2018-01-01 21:53:01,656 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,660 : INFO : < 200 OK [3313]
2018-01-01 21:53:01,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 860}
2018-01-01 21:53:01,664 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,668 : INFO : < 200 OK [3302]
2018-01-01 21:53:01,672 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 719}
2018-01-01 21:53:01,672 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,680 : INFO : < 200 OK [3315]
2018-01-01 21:53:01,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 962}
2018-01-01 21:53:01,684 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,688 : INFO : < 200 OK [3316]
2018-01-01 21:53:01,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1025}
2018-01-01 21:53:01,692 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,696 : INFO : < 200 OK [3333]
2018-01-01 21:53:01,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 926}
2018-01-01 21:53:01,700 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,704 : INFO : < 200 OK [3317]
2018-01-01 21:53:01,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 588, '_0n1': 831}
2018-01-01 21:53:01,708 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,716 : INFO : < 200 OK [3302]
2018-01-01 21:53:01,716 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 572, '_0n1': 831}
2018-01-01 21:53:01,720 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,725 : INFO : < 200 OK [3301]
2018-01-01 21:53:01,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 589, '_0n1': 786}
2018-01-01 21:53:01,731 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,735 : INFO : < 200 OK [3336]
2018-01-01 21:53:01,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 593, '_0n1': 1107}
2018-01-01 21:53:01,736 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,740 : INFO : < 200 OK [3278]
2018-01-01 21:53:01,744 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 590, '_0n1': 1015}
2018-01-01 21:53:01,748 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,752 : INFO : < 200 OK [3328]
2018-01-01 21:53:01,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 590, '_0n1': 1020}
2018-01-01 21:53:01,756 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,760 : INFO : < 200 OK [3328]
2018-01-01 21:53:01,764 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 590, '_0n1': 1155}
2018-01-01 21:53:01,764 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,768 : INFO : < 200 OK [3336]
2018-01-01 21:53:01,772 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 594, '_0n1': 895}
2018-01-01 21:53:01,772 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,776 : INFO : < 200 OK [3307]
2018-01-01 21:53:01,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 591, '_0n1': 739}
2018-01-01 21:53:01,780 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,784 : INFO : < 200 OK [3317]
2018-01-01 21:53:01,788 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 591, '_0n1': 800}
2018-01-01 21:53:01,788 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,792 : INFO : < 200 OK [3314]
2018-01-01 21:53:01,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 595, '_0n1': 840}
2018-01-01 21:53:01,796 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,804 : INFO : < 200 OK [3325]
2018-01-01 21:53:01,804 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 592, '_0n1': 934}
2018-01-01 21:53:01,808 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,812 : INFO : < 200 OK [3273]
2018-01-01 21:53:01,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 808}
2018-01-01 21:53:01,816 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,823 : INFO : < 200 OK [3294]
2018-01-01 21:53:01,825 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1032}

2018-01-01 21:53:01,826 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,830 : INFO : < 200 OK [3312]
2018-01-01 21:53:01,833 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 861}
2018-01-01 21:53:01,835 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,836 : INFO : < 200 OK [3294]
2018-01-01 21:53:01,840 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 613, '_0n1': 1181}
2018-01-01 21:53:01,840 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,844 : INFO : < 200 OK [3301]
2018-01-01 21:53:01,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 597, '_0n1': 739}
2018-01-01 21:53:01,848 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,852 : INFO : < 200 OK [3294]
2018-01-01 21:53:01,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 614, '_0n1': 895}
2018-01-01 21:53:01,860 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,864 : INFO : < 200 OK [3307]
2018-01-01 21:53:01,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 598, '_0n1': 877}
2018-01-01 21:53:01,872 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,876 : INFO : < 200 OK [3305]
2018-01-01 21:53:01,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 615, '_0n1': 1178}
2018-01-01 21:53:01,884 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,888 : INFO : < 200 OK [3311]
2018-01-01 21:53:01,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 599, '_0n1': 877}
2018-01-01 21:53:01,892 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,900 : INFO : < 200 OK [3279]
2018-01-01 21:53:01,904 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 616, '_0n1': 895}
2018-01-01 21:53:01,904 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,908 : INFO : < 200 OK [3312]
2018-01-01 21:53:01,912 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 600, '_0n1': 895}
2018-01-01 21:53:01,912 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,916 : INFO : < 200 OK [3304]
2018-01-01 21:53:01,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 617, '_0n1': 895}
2018-01-01 21:53:01,923 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,927 : INFO : < 200 OK [3309]
2018-01-01 21:53:01,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 601, '_0n1': 877}
2018-01-01 21:53:01,931 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,936 : INFO : < 200 OK [3279]
2018-01-01 21:53:01,936 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 618, '_0n1': 877}
2018-01-01 21:53:01,940 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,944 : INFO : < 200 OK [3285]
2018-01-01 21:53:01,948 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 602, '_0n1': 845}
2018-01-01 21:53:01,948 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,956 : INFO : < 200 OK [3263]
2018-01-01 21:53:01,956 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 602, '_0n1': 1051}
2018-01-01 21:53:01,960 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:01,964 : INFO : < 200 OK [3276]
2018-01-01 21:53:01,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 619, '_0n1': 905}
2018-01-01 21:53:01,968 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,972 : INFO : < 200 OK [3294]
2018-01-01 21:53:01,976 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 603, '_0n1': 937}
2018-01-01 21:53:01,976 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,980 : INFO : < 200 OK [3313]
2018-01-01 21:53:01,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 620, '_0n1': 739}
2018-01-01 21:53:01,984 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:01,988 : INFO : < 200 OK [3266]
2018-01-01 21:53:01,992 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 620, '_0n1': 800}
2018-01-01 21:53:01,992 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:02,000 : INFO : < 200 OK [3263]
2018-01-01 21:53:02,000 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 604, '_0n1': 719}
2018-01-01 21:53:02,004 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:02,008 : INFO : < 200 OK [3319]
2018-01-01 21:53:02,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 604, '_0n1': 962}
2018-01-01 21:53:02,012 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:02,016 : INFO : < 200 OK [3320]
2018-01-01 21:53:02,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 604, '_0n1': 1025}
2018-01-01 21:53:02,023 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:02,027 : INFO : < 200 OK [3337]
2018-01-01 21:53:02,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 604, '_0n1': 926}
2018-01-01 21:53:02,032 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:02,036 : INFO : < 200 OK [3321]
2018-01-01 21:53:02,036 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 621, '_0n1': 934}
2018-01-01 21:53:02,040 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:53:02,044 : INFO : < 200 OK [3272]
2018-01-01 21:53:02,048 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 621, '_0n1': 1159}
2018-01-01 21:53:02,048 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:53:02,056 : INFO : < 200 OK [3292]

In [62]:
df = pd.merge(title_relation_df, data_clear[['uid', 'package_name', 'package_num']], on='uid', how='left')
df.head()

,title,uid,relate_1,relate_2,relate_3,relate_4,relate_5,package_name,package_num
0,Bitcoin and Cryptocurrency Technologies,0,852,346,596,294,707,None,None
1,Cryptography I,284,28,340,822,344,463,None,None
2,Google Cloud Platform Fundamentals: Core Infra...,157,840,867,161,159,829,Architecting with Google Cloud Platform Specia...,1
3,G Suite Administrator Fundamentals,3,250,733,436,365,706,None,None
4,Usable Security,4,654,858,743,60,70,Cybersecurity Specialization,1

In [63]:
for name, group in df.groupby('package_name')['uid']:
    tmp = list(group)
    for i, row in enumerate(tmp):
        if i != 0:
            x = course_dict[tmp[i-1]]
            y = course_dict[row]
            graph.create(Relationship(x, "require", y))

2018-01-01 21:39:04,722 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 458, '_0n1': 504}
2018-01-01 21:39:04,722 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,737 : INFO : < 200 OK [3350]
2018-01-01 21:39:04,740 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 504, '_0n1': 506}
2018-01-01 21:39:04,741 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,746 : INFO : < 200 OK [3345]
2018-01-01 21:39:04,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 506, '_0n1': 521}
2018-01-01 21:39:04,747 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,751 : INFO : < 200 OK [3351]
2018-01-01 21:39:04,751 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 521, '_0n1': 574}
2018-01-01 21:39:04,755 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,759 : INFO : < 200 OK [3349]
2018-01-01 21:39:04,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 377}
2018-01-01 21:39:04,763 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,767 : INFO : < 200 OK [3422]
2018-01-01 21:39:04,771 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 381}
2018-01-01 21:39:04,771 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,775 : INFO : < 200 OK [3430]
2018-01-01 21:39:04,775 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 133, '_0n1': 158}
2018-01-01 21:39:04,779 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,783 : INFO : < 200 OK [3339]
2018-01-01 21:39:04,783 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 158, '_0n1': 160}
2018-01-01 21:39:04,787 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,791 : INFO : < 200 OK [3358]
2018-01-01 21:39:04,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 160, '_0n1': 181}
2018-01-01 21:39:04,795 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,799 : INFO : < 200 OK [3354]
2018-01-01 21:39:04,799 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 181, '_0n1': 168}
2018-01-01 21:39:04,803 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,811 : INFO : < 200 OK [3379]
2018-01-01 21:39:04,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 69, '_0n1': 58}
2018-01-01 21:39:04,815 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:04,819 : INFO : < 200 OK [3426]
2018-01-01 21:39:04,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 58, '_0n1': 77}
2018-01-01 21:39:04,823 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:04,827 : INFO : < 200 OK [3424]
2018-01-01 21:39:04,833 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 77, '_0n1': 86}
2018-01-01 21:39:04,835 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:04,839 : INFO : < 200 OK [3447]
2018-01-01 21:39:04,841 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1260, '_0n1': 148}
2018-01-01 21:39:04,843 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2018-01-01 21:39:04,847 : INFO : < 200 OK [3380]
2018-01-01 21:39:04,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 148, '_0n1': 179}
2018-01-01 21:39:04,848 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,852 : INFO : < 200 OK [3370]
2018-01-01 21:39:04,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 179, '_0n1': 202}
2018-01-01 21:39:04,856 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,860 : INFO : < 200 OK [3339]
2018-01-01 21:39:04,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 202, '_0n1': 247}
2018-01-01 21:39:04,864 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,868 : INFO : < 200 OK [3347]
2018-01-01 21:39:04,872 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 247, '_0n1': 567}
2018-01-01 21:39:04,872 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,876 : INFO : < 200 OK [3388]
2018-01-01 21:39:04,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 310}
2018-01-01 21:39:04,880 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,884 : INFO : < 200 OK [3387]
2018-01-01 21:39:04,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 310, '_0n1': 312}
2018-01-01 21:39:04,888 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,892 : INFO : < 200 OK [3438]
2018-01-01 21:39:04,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 312, '_0n1': 313}
2018-01-01 21:39:04,896 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,904 : INFO : < 200 OK [3406]
2018-01-01 21:39:04,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 340}
2018-01-01 21:39:04,908 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,912 : INFO : < 200 OK [3355]
2018-01-01 21:39:04,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 20, '_0n1': 33}
2018-01-01 21:39:04,916 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:04,920 : INFO : < 200 OK [3341]
2018-01-01 21:39:04,924 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 33, '_0n1': 35}
2018-01-01 21:39:04,924 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:04,928 : INFO : < 200 OK [3323]
2018-01-01 21:39:04,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 35, '_0n1': 37}

2018-01-01 21:39:04,936 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:04,941 : INFO : < 200 OK [3344]
2018-01-01 21:39:04,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 145, '_0n1': 398}
2018-01-01 21:39:04,946 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,948 : INFO : < 200 OK [3435]
2018-01-01 21:39:04,956 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 398, '_0n1': 417}
2018-01-01 21:39:04,956 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,960 : INFO : < 200 OK [3411]
2018-01-01 21:39:04,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 417, '_0n1': 424}
2018-01-01 21:39:04,968 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,972 : INFO : < 200 OK [3402]
2018-01-01 21:39:04,976 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 424, '_0n1': 447}
2018-01-01 21:39:04,976 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:04,980 : INFO : < 200 OK [3409]
2018-01-01 21:39:04,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1229, '_0n1': 1250}
2018-01-01 21:39:04,984 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:04,992 : INFO : < 200 OK [3466]
2018-01-01 21:39:04,992 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1250, '_0n1': 1251}
2018-01-01 21:39:04,996 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:05,000 : INFO : < 200 OK [3456]
2018-01-01 21:39:05,004 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1251, '_0n1': 1235}
2018-01-01 21:39:05,004 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:05,008 : INFO : < 200 OK [3466]
2018-01-01 21:39:05,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1235, '_0n1': 1236}
2018-01-01 21:39:05,012 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:05,016 : INFO : < 200 OK [3474]
2018-01-01 21:39:05,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1236, '_0n1': 5}
2018-01-01 21:39:05,020 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:05,024 : INFO : < 200 OK [3426]
2018-01-01 21:39:05,028 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 402, '_0n1': 420}
2018-01-01 21:39:05,028 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,035 : INFO : < 200 OK [3327]
2018-01-01 21:39:05,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 420, '_0n1': 433}
2018-01-01 21:39:05,040 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,043 : INFO : < 200 OK [3337]
2018-01-01 21:39:05,046 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 433, '_0n1': 452}
2018-01-01 21:39:05,048 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,052 : INFO : < 200 OK [3377]
2018-01-01 21:39:05,056 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 452, '_0n1': 461}
2018-01-01 21:39:05,056 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,060 : INFO : < 200 OK [3365]
2018-01-01 21:39:05,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 461, '_0n1': 553}
2018-01-01 21:39:05,064 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,068 : INFO : < 200 OK [3328]
2018-01-01 21:39:05,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 443}
2018-01-01 21:39:05,072 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,076 : INFO : < 200 OK [3433]
2018-01-01 21:39:05,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 453}
2018-01-01 21:39:05,084 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,092 : INFO : < 200 OK [3447]
2018-01-01 21:39:05,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 78, '_0n1': 115}
2018-01-01 21:39:05,096 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:05,104 : INFO : < 200 OK [3402]
2018-01-01 21:39:05,104 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 115, '_0n1': 116}
2018-01-01 21:39:05,108 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,112 : INFO : < 200 OK [3422]
2018-01-01 21:39:05,116 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 116, '_0n1': 100}
2018-01-01 21:39:05,116 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,120 : INFO : < 200 OK [3424]
2018-01-01 21:39:05,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 100, '_0n1': 118}
2018-01-01 21:39:05,124 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,132 : INFO : < 200 OK [3429]
2018-01-01 21:39:05,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 118, '_0n1': 121}
2018-01-01 21:39:05,137 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,141 : INFO : < 200 OK [3447]
2018-01-01 21:39:05,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 121, '_0n1': 141}
2018-01-01 21:39:05,147 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,148 : INFO : < 200 OK [3432]
2018-01-01 21:39:05,152 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 426, '_0n1': 434}
2018-01-01 21:39:05,156 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,160 : INFO : < 200 OK [3257]
2018-01-01 21:39:05,164 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 434, '_0n1': 451}
2018-01-01 21:39:05,164 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,168 : INFO : < 200 OK [3259]

2018-01-01 21:39:05,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 451, '_0n1': 455}
2018-01-01 21:39:05,172 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,176 : INFO : < 200 OK [3288]
2018-01-01 21:39:05,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 455, '_0n1': 549}
2018-01-01 21:39:05,180 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,184 : INFO : < 200 OK [3353]
2018-01-01 21:39:05,188 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 425, '_0n1': 485}
2018-01-01 21:39:05,188 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,192 : INFO : < 200 OK [3402]
2018-01-01 21:39:05,196 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 485, '_0n1': 475}
2018-01-01 21:39:05,196 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,200 : INFO : < 200 OK [3402]
2018-01-01 21:39:05,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 475, '_0n1': 478}
2018-01-01 21:39:05,204 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,208 : INFO : < 200 OK [3393]
2018-01-01 21:39:05,212 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 478, '_0n1': 541}
2018-01-01 21:39:05,212 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,216 : INFO : < 200 OK [3393]
2018-01-01 21:39:05,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 442, '_0n1': 449}
2018-01-01 21:39:05,220 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,224 : INFO : < 200 OK [3349]
2018-01-01 21:39:05,228 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 449, '_0n1': 460}
2018-01-01 21:39:05,228 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,234 : INFO : < 200 OK [3339]
2018-01-01 21:39:05,236 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 460, '_0n1': 468}
2018-01-01 21:39:05,238 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,242 : INFO : < 200 OK [3329]
2018-01-01 21:39:05,245 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 468, '_0n1': 544}
2018-01-01 21:39:05,247 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,252 : INFO : < 200 OK [3350]
2018-01-01 21:39:05,256 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1248, '_0n1': 1253}
2018-01-01 21:39:05,260 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:05,264 : INFO : < 200 OK [3434]
2018-01-01 21:39:05,268 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1253, '_0n1': 1240}
2018-01-01 21:39:05,268 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:05,276 : INFO : < 200 OK [3417]
2018-01-01 21:39:05,276 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1240, '_0n1': 1301}
2018-01-01 21:39:05,280 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:05,284 : INFO : < 200 OK [3415]
2018-01-01 21:39:05,288 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1301, '_0n1': 1302}
2018-01-01 21:39:05,288 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:05,292 : INFO : < 200 OK [3433]
2018-01-01 21:39:05,296 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1255, '_0n1': 2}
2018-01-01 21:39:05,296 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:05,300 : INFO : < 200 OK [3436]
2018-01-01 21:39:05,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 22}
2018-01-01 21:39:05,304 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:05,308 : INFO : < 200 OK [3318]
2018-01-01 21:39:05,312 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 22, '_0n1': 64}
2018-01-01 21:39:05,312 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,316 : INFO : < 200 OK [3280]
2018-01-01 21:39:05,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 64, '_0n1': 72}
2018-01-01 21:39:05,320 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,324 : INFO : < 200 OK [3325]
2018-01-01 21:39:05,328 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 72, '_0n1': 93}
2018-01-01 21:39:05,328 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,334 : INFO : < 200 OK [3335]
2018-01-01 21:39:05,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1254, '_0n1': 25}
2018-01-01 21:39:05,338 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,342 : INFO : < 200 OK [3367]
2018-01-01 21:39:05,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 25, '_0n1': 32}
2018-01-01 21:39:05,346 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,348 : INFO : < 200 OK [3288]
2018-01-01 21:39:05,352 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 32, '_0n1': 34}
2018-01-01 21:39:05,352 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,356 : INFO : < 200 OK [3310]
2018-01-01 21:39:05,360 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1237, '_0n1': 4}
2018-01-01 21:39:05,360 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:05,364 : INFO : < 200 OK [3398]
2018-01-01 21:39:05,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 4, '_0n1': 28}
2018-01-01 21:39:05,368 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:05,372 : INFO : < 200 OK [3341]
2018-01-01 21:39:05,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 28, '_0n1': 41}

2018-01-01 21:39:05,376 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,384 : INFO : < 200 OK [3346]
2018-01-01 21:39:05,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1230, '_0n1': 1233}
2018-01-01 21:39:05,388 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:05,392 : INFO : < 200 OK [3333]
2018-01-01 21:39:05,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1233, '_0n1': 1}
2018-01-01 21:39:05,396 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:05,404 : INFO : < 200 OK [3286]
2018-01-01 21:39:05,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1, '_0n1': 23}
2018-01-01 21:39:05,408 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:05,412 : INFO : < 200 OK [3255]
2018-01-01 21:39:05,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 23, '_0n1': 65}
2018-01-01 21:39:05,420 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,424 : INFO : < 200 OK [3321]
2018-01-01 21:39:05,428 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1256, '_0n1': 24}
2018-01-01 21:39:05,432 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,436 : INFO : < 200 OK [3405]
2018-01-01 21:39:05,440 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 24, '_0n1': 30}
2018-01-01 21:39:05,441 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,445 : INFO : < 200 OK [3383]
2018-01-01 21:39:05,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 30, '_0n1': 36}
2018-01-01 21:39:05,447 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,451 : INFO : < 200 OK [3378]
2018-01-01 21:39:05,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 11, '_0n1': 40}
2018-01-01 21:39:05,455 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,459 : INFO : < 200 OK [3369]
2018-01-01 21:39:05,463 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 40, '_0n1': 62}
2018-01-01 21:39:05,463 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,467 : INFO : < 200 OK [3355]
2018-01-01 21:39:05,471 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 62, '_0n1': 47}
2018-01-01 21:39:05,475 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,479 : INFO : < 200 OK [3368]
2018-01-01 21:39:05,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 371, '_0n1': 406}
2018-01-01 21:39:05,483 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,487 : INFO : < 200 OK [3338]
2018-01-01 21:39:05,491 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 406, '_0n1': 465}
2018-01-01 21:39:05,491 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,495 : INFO : < 200 OK [3340]
2018-01-01 21:39:05,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 465, '_0n1': 510}
2018-01-01 21:39:05,499 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,503 : INFO : < 200 OK [3325]
2018-01-01 21:39:05,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 510, '_0n1': 556}
2018-01-01 21:39:05,507 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,511 : INFO : < 200 OK [3333]
2018-01-01 21:39:05,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 416, '_0n1': 422}
2018-01-01 21:39:05,515 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,519 : INFO : < 200 OK [3385]
2018-01-01 21:39:05,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 422, '_0n1': 445}
2018-01-01 21:39:05,523 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,527 : INFO : < 200 OK [3396]
2018-01-01 21:39:05,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 445, '_0n1': 446}
2018-01-01 21:39:05,531 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,537 : INFO : < 200 OK [3417]
2018-01-01 21:39:05,540 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 446, '_0n1': 550}
2018-01-01 21:39:05,542 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,547 : INFO : < 200 OK [3448]
2018-01-01 21:39:05,548 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1239, '_0n1': 385}
2018-01-01 21:39:05,552 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2018-01-01 21:39:05,556 : INFO : < 200 OK [3482]
2018-01-01 21:39:05,560 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 385, '_0n1': 403}
2018-01-01 21:39:05,560 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,564 : INFO : < 200 OK [3471]
2018-01-01 21:39:05,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 403, '_0n1': 388}
2018-01-01 21:39:05,568 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,572 : INFO : < 200 OK [3480]
2018-01-01 21:39:05,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 388, '_0n1': 470}
2018-01-01 21:39:05,576 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,580 : INFO : < 200 OK [3473]
2018-01-01 21:39:05,584 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 348, '_0n1': 386}
2018-01-01 21:39:05,584 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,588 : INFO : < 200 OK [3316]
2018-01-01 21:39:05,592 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 386, '_0n1': 404}
2018-01-01 21:39:05,592 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,596 : INFO : < 200 OK [3331]
2018-01-01 21:39:05,600 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 404, '_0n1': 486}

2018-01-01 21:39:05,600 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,604 : INFO : < 200 OK [3337]
2018-01-01 21:39:05,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 486, '_0n1': 500}
2018-01-01 21:39:05,612 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,616 : INFO : < 200 OK [3336]
2018-01-01 21:39:05,620 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 500, '_0n1': 548}
2018-01-01 21:39:05,624 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,628 : INFO : < 200 OK [3324]
2018-01-01 21:39:05,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 361}
2018-01-01 21:39:05,635 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,639 : INFO : < 200 OK [3344]
2018-01-01 21:39:05,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 362}
2018-01-01 21:39:05,643 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,648 : INFO : < 200 OK [3323]
2018-01-01 21:39:05,648 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 346}
2018-01-01 21:39:05,652 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,656 : INFO : < 200 OK [3315]
2018-01-01 21:39:05,660 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 363}
2018-01-01 21:39:05,660 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,664 : INFO : < 200 OK [3311]
2018-01-01 21:39:05,668 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 366}
2018-01-01 21:39:05,668 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,672 : INFO : < 200 OK [3315]
2018-01-01 21:39:05,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 351}
2018-01-01 21:39:05,680 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,684 : INFO : < 200 OK [3318]
2018-01-01 21:39:05,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 378}
2018-01-01 21:39:05,688 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,692 : INFO : < 200 OK [3323]
2018-01-01 21:39:05,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 378, '_0n1': 392}
2018-01-01 21:39:05,696 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,700 : INFO : < 200 OK [3320]
2018-01-01 21:39:05,704 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 473}
2018-01-01 21:39:05,704 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,708 : INFO : < 200 OK [3373]
2018-01-01 21:39:05,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 473, '_0n1': 539}
2018-01-01 21:39:05,712 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,716 : INFO : < 200 OK [3357]
2018-01-01 21:39:05,720 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 539, '_0n1': 532}
2018-01-01 21:39:05,720 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,724 : INFO : < 200 OK [3347]
2018-01-01 21:39:05,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 53}
2018-01-01 21:39:05,728 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,734 : INFO : < 200 OK [3342]
2018-01-01 21:39:05,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 76}
2018-01-01 21:39:05,738 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,742 : INFO : < 200 OK [3343]
2018-01-01 21:39:05,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 76, '_0n1': 102}
2018-01-01 21:39:05,747 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:05,748 : INFO : < 200 OK [3374]
2018-01-01 21:39:05,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 103}
2018-01-01 21:39:05,756 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,760 : INFO : < 200 OK [3390]
2018-01-01 21:39:05,764 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 103, '_0n1': 120}
2018-01-01 21:39:05,764 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,768 : INFO : < 200 OK [3393]
2018-01-01 21:39:05,772 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 429, '_0n1': 462}
2018-01-01 21:39:05,772 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,776 : INFO : < 200 OK [3412]
2018-01-01 21:39:05,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 462, '_0n1': 467}
2018-01-01 21:39:05,780 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,784 : INFO : < 200 OK [3399]
2018-01-01 21:39:05,788 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 467, '_0n1': 469}
2018-01-01 21:39:05,788 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,796 : INFO : < 200 OK [3409]
2018-01-01 21:39:05,800 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 469, '_0n1': 546}
2018-01-01 21:39:05,800 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,808 : INFO : < 200 OK [3423]
2018-01-01 21:39:05,812 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 157, '_0n1': 448}
2018-01-01 21:39:05,812 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,816 : INFO : < 200 OK [3356]
2018-01-01 21:39:05,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 448, '_0n1': 477}
2018-01-01 21:39:05,824 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,828 : INFO : < 200 OK [3358]

2018-01-01 21:39:05,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 477, '_0n1': 534}
2018-01-01 21:39:05,838 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,842 : INFO : < 200 OK [3375]
2018-01-01 21:39:05,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 534, '_0n1': 554}
2018-01-01 21:39:05,848 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,852 : INFO : < 200 OK [3394]
2018-01-01 21:39:05,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 49}
2018-01-01 21:39:05,860 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,864 : INFO : < 200 OK [3371]
2018-01-01 21:39:05,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 67}
2018-01-01 21:39:05,868 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,872 : INFO : < 200 OK [3420]
2018-01-01 21:39:05,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 67, '_0n1': 375}
2018-01-01 21:39:05,876 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:05,884 : INFO : < 200 OK [3439]
2018-01-01 21:39:05,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 319, '_0n1': 336}
2018-01-01 21:39:05,888 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,892 : INFO : < 200 OK [3348]
2018-01-01 21:39:05,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 407, '_0n1': 409}
2018-01-01 21:39:05,896 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,900 : INFO : < 200 OK [3382]
2018-01-01 21:39:05,904 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 409, '_0n1': 393}
2018-01-01 21:39:05,904 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,908 : INFO : < 200 OK [3390]
2018-01-01 21:39:05,912 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 393, '_0n1': 410}
2018-01-01 21:39:05,912 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,916 : INFO : < 200 OK [3408]
2018-01-01 21:39:05,920 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 410, '_0n1': 394}
2018-01-01 21:39:05,920 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,924 : INFO : < 200 OK [3396]
2018-01-01 21:39:05,928 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 394, '_0n1': 411}
2018-01-01 21:39:05,928 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,935 : INFO : < 200 OK [3387]
2018-01-01 21:39:05,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 411, '_0n1': 395}
2018-01-01 21:39:05,940 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,944 : INFO : < 200 OK [3394]
2018-01-01 21:39:05,947 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 395, '_0n1': 412}
2018-01-01 21:39:05,948 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,952 : INFO : < 200 OK [3392]
2018-01-01 21:39:05,956 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 412, '_0n1': 396}
2018-01-01 21:39:05,956 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,960 : INFO : < 200 OK [3392]
2018-01-01 21:39:05,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 396, '_0n1': 413}
2018-01-01 21:39:05,964 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:05,968 : INFO : < 200 OK [3407]
2018-01-01 21:39:05,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 3, '_0n1': 7}
2018-01-01 21:39:05,972 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:05,976 : INFO : < 200 OK [3310]
2018-01-01 21:39:05,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 7, '_0n1': 19}
2018-01-01 21:39:05,980 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:05,984 : INFO : < 200 OK [3301]
2018-01-01 21:39:05,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 19, '_0n1': 45}
2018-01-01 21:39:05,988 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:05,992 : INFO : < 200 OK [3303]
2018-01-01 21:39:05,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 45, '_0n1': 166}
2018-01-01 21:39:05,996 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:06,000 : INFO : < 200 OK [3349]
2018-01-01 21:39:06,004 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 166, '_0n1': 206}
2018-01-01 21:39:06,004 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,008 : INFO : < 200 OK [3365]
2018-01-01 21:39:06,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 421, '_0n1': 450}
2018-01-01 21:39:06,012 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,016 : INFO : < 200 OK [3413]
2018-01-01 21:39:06,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 450, '_0n1': 435}
2018-01-01 21:39:06,020 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,024 : INFO : < 200 OK [3390]
2018-01-01 21:39:06,028 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 435, '_0n1': 454}
2018-01-01 21:39:06,028 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,034 : INFO : < 200 OK [3391]
2018-01-01 21:39:06,037 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 423, '_0n1': 440}
2018-01-01 21:39:06,039 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,043 : INFO : < 200 OK [3364]
2018-01-01 21:39:06,046 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 440, '_0n1': 427}

2018-01-01 21:39:06,047 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,048 : INFO : < 200 OK [3347]
2018-01-01 21:39:06,052 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 427, '_0n1': 428}
2018-01-01 21:39:06,052 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,056 : INFO : < 200 OK [3333]
2018-01-01 21:39:06,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 428, '_0n1': 547}
2018-01-01 21:39:06,060 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,064 : INFO : < 200 OK [3369]
2018-01-01 21:39:06,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 399, '_0n1': 437}
2018-01-01 21:39:06,068 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,072 : INFO : < 200 OK [3325]
2018-01-01 21:39:06,076 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 437, '_0n1': 481}
2018-01-01 21:39:06,076 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,080 : INFO : < 200 OK [3323]
2018-01-01 21:39:06,084 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 481, '_0n1': 482}
2018-01-01 21:39:06,084 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,088 : INFO : < 200 OK [3326]
2018-01-01 21:39:06,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 482, '_0n1': 543}
2018-01-01 21:39:06,092 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,096 : INFO : < 200 OK [3329]
2018-01-01 21:39:06,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 126, '_0n1': 144}
2018-01-01 21:39:06,100 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,104 : INFO : < 200 OK [3427]
2018-01-01 21:39:06,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 278, '_0n1': 296}
2018-01-01 21:39:06,108 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,112 : INFO : < 200 OK [3429]
2018-01-01 21:39:06,116 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 296, '_0n1': 297}
2018-01-01 21:39:06,120 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,124 : INFO : < 200 OK [3435]
2018-01-01 21:39:06,128 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 297, '_0n1': 323}
2018-01-01 21:39:06,132 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,140 : INFO : < 200 OK [3439]
2018-01-01 21:39:06,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 327}
2018-01-01 21:39:06,147 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,148 : INFO : < 200 OK [3437]
2018-01-01 21:39:06,156 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 57, '_0n1': 514}
2018-01-01 21:39:06,160 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:06,164 : INFO : < 200 OK [3336]
2018-01-01 21:39:06,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 514, '_0n1': 578}
2018-01-01 21:39:06,172 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,176 : INFO : < 200 OK [3388]
2018-01-01 21:39:06,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 578, '_0n1': 569}
2018-01-01 21:39:06,180 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,184 : INFO : < 200 OK [3415]
2018-01-01 21:39:06,188 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 569, '_0n1': 587}
2018-01-01 21:39:06,188 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,192 : INFO : < 200 OK [3393]
2018-01-01 21:39:06,196 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1234, '_0n1': 1259}
2018-01-01 21:39:06,200 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:06,204 : INFO : < 200 OK [3407]
2018-01-01 21:39:06,208 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1259, '_0n1': 27}
2018-01-01 21:39:06,208 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,212 : INFO : < 200 OK [3407]
2018-01-01 21:39:06,216 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 27, '_0n1': 16}
2018-01-01 21:39:06,220 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:06,224 : INFO : < 200 OK [3379]
2018-01-01 21:39:06,228 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 101}
2018-01-01 21:39:06,228 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:06,237 : INFO : < 200 OK [3381]
2018-01-01 21:39:06,239 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 105}
2018-01-01 21:39:06,241 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,245 : INFO : < 200 OK [3425]
2018-01-01 21:39:06,248 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 91}
2018-01-01 21:39:06,248 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:06,252 : INFO : < 200 OK [3413]
2018-01-01 21:39:06,256 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 95}
2018-01-01 21:39:06,256 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:06,260 : INFO : < 200 OK [3370]
2018-01-01 21:39:06,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 114}
2018-01-01 21:39:06,264 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:06,268 : INFO : < 200 OK [3352]
2018-01-01 21:39:06,272 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 123}
2018-01-01 21:39:06,272 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,280 : INFO : < 200 OK [3381]
2018-01-01 21:39:06,280 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 164, '_0n1': 566}

2018-01-01 21:39:06,284 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,288 : INFO : < 200 OK [3330]
2018-01-01 21:39:06,288 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 566, '_0n1': 592}
2018-01-01 21:39:06,292 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,296 : INFO : < 200 OK [3342]
2018-01-01 21:39:06,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 592, '_0n1': 621}
2018-01-01 21:39:06,300 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,304 : INFO : < 200 OK [3346]
2018-01-01 21:39:06,308 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 156, '_0n1': 185}
2018-01-01 21:39:06,308 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,312 : INFO : < 200 OK [3376]
2018-01-01 21:39:06,316 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 185, '_0n1': 169}
2018-01-01 21:39:06,316 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,320 : INFO : < 200 OK [3352]
2018-01-01 21:39:06,324 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 169, '_0n1': 173}
2018-01-01 21:39:06,324 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,328 : INFO : < 200 OK [3333]
2018-01-01 21:39:06,334 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 173, '_0n1': 177}
2018-01-01 21:39:06,336 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,340 : INFO : < 200 OK [3348]
2018-01-01 21:39:06,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 104, '_0n1': 112}
2018-01-01 21:39:06,344 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,348 : INFO : < 200 OK [3338]
2018-01-01 21:39:06,348 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 112, '_0n1': 355}
2018-01-01 21:39:06,352 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,356 : INFO : < 200 OK [3337]
2018-01-01 21:39:06,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 355, '_0n1': 503}
2018-01-01 21:39:06,356 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,364 : INFO : < 200 OK [3339]
2018-01-01 21:39:06,364 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 503, '_0n1': 515}
2018-01-01 21:39:06,368 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,372 : INFO : < 200 OK [3336]
2018-01-01 21:39:06,372 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 515, '_0n1': 535}
2018-01-01 21:39:06,372 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,380 : INFO : < 200 OK [3348]
2018-01-01 21:39:06,380 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 535, '_0n1': 536}
2018-01-01 21:39:06,384 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,388 : INFO : < 200 OK [3353]
2018-01-01 21:39:06,388 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 536, '_0n1': 552}
2018-01-01 21:39:06,388 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,396 : INFO : < 200 OK [3339]
2018-01-01 21:39:06,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 127, '_0n1': 152}
2018-01-01 21:39:06,400 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,404 : INFO : < 200 OK [3329]
2018-01-01 21:39:06,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 152, '_0n1': 137}
2018-01-01 21:39:06,408 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,408 : INFO : < 200 OK [3355]
2018-01-01 21:39:06,412 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 137, '_0n1': 191}
2018-01-01 21:39:06,412 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,416 : INFO : < 200 OK [3344]
2018-01-01 21:39:06,420 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 39, '_0n1': 43}
2018-01-01 21:39:06,420 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:06,428 : INFO : < 200 OK [3437]
2018-01-01 21:39:06,428 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 43, '_0n1': 44}
2018-01-01 21:39:06,432 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:06,438 : INFO : < 200 OK [3403]
2018-01-01 21:39:06,442 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 44, '_0n1': 63}
2018-01-01 21:39:06,445 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:06,449 : INFO : < 200 OK [3403]
2018-01-01 21:39:06,453 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 151, '_0n1': 161}
2018-01-01 21:39:06,453 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,461 : INFO : < 200 OK [3374]
2018-01-01 21:39:06,465 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 161, '_0n1': 162}
2018-01-01 21:39:06,465 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,469 : INFO : < 200 OK [3414]
2018-01-01 21:39:06,473 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 163}
2018-01-01 21:39:06,473 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,481 : INFO : < 200 OK [3390]
2018-01-01 21:39:06,481 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 163, '_0n1': 167}
2018-01-01 21:39:06,485 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,489 : INFO : < 200 OK [3330]
2018-01-01 21:39:06,489 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 167, '_0n1': 189}
2018-01-01 21:39:06,493 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,497 : INFO : < 200 OK [3312]
2018-01-01 21:39:06,497 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 189, '_0n1': 193}

2018-01-01 21:39:06,501 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,505 : INFO : < 200 OK [3329]
2018-01-01 21:39:06,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 13, '_0n1': 199}
2018-01-01 21:39:06,509 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:06,513 : INFO : < 200 OK [3343]
2018-01-01 21:39:06,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 199, '_0n1': 243}
2018-01-01 21:39:06,517 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,521 : INFO : < 200 OK [3367]
2018-01-01 21:39:06,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 243, '_0n1': 209}
2018-01-01 21:39:06,525 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,529 : INFO : < 200 OK [3370]
2018-01-01 21:39:06,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 248}
2018-01-01 21:39:06,535 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,539 : INFO : < 200 OK [3379]
2018-01-01 21:39:06,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 6, '_0n1': 10}
2018-01-01 21:39:06,543 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:06,547 : INFO : < 200 OK [3368]
2018-01-01 21:39:06,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1249, '_0n1': 26}
2018-01-01 21:39:06,549 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,553 : INFO : < 200 OK [3389]
2018-01-01 21:39:06,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 26, '_0n1': 29}
2018-01-01 21:39:06,557 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:06,565 : INFO : < 200 OK [3357]
2018-01-01 21:39:06,565 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 29, '_0n1': 12}
2018-01-01 21:39:06,569 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:06,573 : INFO : < 200 OK [3367]
2018-01-01 21:39:06,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 80}
2018-01-01 21:39:06,577 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:06,581 : INFO : < 200 OK [3345]
2018-01-01 21:39:06,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 80, '_0n1': 83}
2018-01-01 21:39:06,585 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:06,593 : INFO : < 200 OK [3358]
2018-01-01 21:39:06,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 83, '_0n1': 106}
2018-01-01 21:39:06,597 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:06,601 : INFO : < 200 OK [3375]
2018-01-01 21:39:06,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 94}
2018-01-01 21:39:06,609 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:06,613 : INFO : < 200 OK [3362]
2018-01-01 21:39:06,617 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 456}
2018-01-01 21:39:06,621 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,625 : INFO : < 200 OK [3385]
2018-01-01 21:39:06,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 456, '_0n1': 457}
2018-01-01 21:39:06,634 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,639 : INFO : < 200 OK [3376]
2018-01-01 21:39:06,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 483}
2018-01-01 21:39:06,646 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,649 : INFO : < 200 OK [3378]
2018-01-01 21:39:06,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 571}
2018-01-01 21:39:06,657 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,661 : INFO : < 200 OK [3431]
2018-01-01 21:39:06,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 604}
2018-01-01 21:39:06,665 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,673 : INFO : < 200 OK [3429]
2018-01-01 21:39:06,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 347, '_0n1': 380}
2018-01-01 21:39:06,677 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,685 : INFO : < 200 OK [3352]
2018-01-01 21:39:06,685 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 380, '_0n1': 379}
2018-01-01 21:39:06,689 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,693 : INFO : < 200 OK [3356]
2018-01-01 21:39:06,697 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 379, '_0n1': 401}
2018-01-01 21:39:06,697 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,705 : INFO : < 200 OK [3345]
2018-01-01 21:39:06,705 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 480}
2018-01-01 21:39:06,709 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,713 : INFO : < 200 OK [3390]
2018-01-01 21:39:06,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 480, '_0n1': 513}
2018-01-01 21:39:06,717 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,721 : INFO : < 200 OK [3394]
2018-01-01 21:39:06,725 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 516}
2018-01-01 21:39:06,725 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,729 : INFO : < 200 OK [3391]
2018-01-01 21:39:06,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 516, '_0n1': 557}
2018-01-01 21:39:06,736 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,740 : INFO : < 200 OK [3402]

2018-01-01 21:39:06,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 345, '_0n1': 353}
2018-01-01 21:39:06,745 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,748 : INFO : < 200 OK [3340]
2018-01-01 21:39:06,748 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 353, '_0n1': 484}
2018-01-01 21:39:06,752 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,756 : INFO : < 200 OK [3356]
2018-01-01 21:39:06,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 551}
2018-01-01 21:39:06,760 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,764 : INFO : < 200 OK [3379]
2018-01-01 21:39:06,768 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 551, '_0n1': 590}
2018-01-01 21:39:06,768 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,772 : INFO : < 200 OK [3391]
2018-01-01 21:39:06,776 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 85, '_0n1': 577}
2018-01-01 21:39:06,776 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:06,784 : INFO : < 200 OK [3390]
2018-01-01 21:39:06,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 577, '_0n1': 579}
2018-01-01 21:39:06,788 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,792 : INFO : < 200 OK [3418]
2018-01-01 21:39:06,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 584}
2018-01-01 21:39:06,796 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,800 : INFO : < 200 OK [3431]
2018-01-01 21:39:06,804 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 583, '_0n1': 588}
2018-01-01 21:39:06,808 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,812 : INFO : < 200 OK [3398]
2018-01-01 21:39:06,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 588, '_0n1': 572}
2018-01-01 21:39:06,816 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,820 : INFO : < 200 OK [3400]
2018-01-01 21:39:06,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 180, '_0n1': 205}
2018-01-01 21:39:06,828 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,833 : INFO : < 200 OK [3324]
2018-01-01 21:39:06,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 205, '_0n1': 207}
2018-01-01 21:39:06,838 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,842 : INFO : < 200 OK [3308]
2018-01-01 21:39:06,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 207, '_0n1': 208}
2018-01-01 21:39:06,846 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,849 : INFO : < 200 OK [3360]
2018-01-01 21:39:06,849 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 208, '_0n1': 244}
2018-01-01 21:39:06,853 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,857 : INFO : < 200 OK [3417]
2018-01-01 21:39:06,857 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 244, '_0n1': 212}
2018-01-01 21:39:06,861 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,865 : INFO : < 200 OK [3424]
2018-01-01 21:39:06,869 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 73, '_0n1': 90}
2018-01-01 21:39:06,869 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:06,873 : INFO : < 200 OK [3392]
2018-01-01 21:39:06,877 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 90, '_0n1': 108}
2018-01-01 21:39:06,881 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:06,885 : INFO : < 200 OK [3401]
2018-01-01 21:39:06,885 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 418}
2018-01-01 21:39:06,889 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,893 : INFO : < 200 OK [3322]
2018-01-01 21:39:06,893 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 418, '_0n1': 444}
2018-01-01 21:39:06,897 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,901 : INFO : < 200 OK [3366]
2018-01-01 21:39:06,905 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 444, '_0n1': 558}
2018-01-01 21:39:06,905 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,909 : INFO : < 200 OK [3394]
2018-01-01 21:39:06,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 558, '_0n1': 576}
2018-01-01 21:39:06,913 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,921 : INFO : < 200 OK [3359]
2018-01-01 21:39:06,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 387, '_0n1': 390}
2018-01-01 21:39:06,925 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,929 : INFO : < 200 OK [3422]
2018-01-01 21:39:06,933 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 390, '_0n1': 391}
2018-01-01 21:39:06,934 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,939 : INFO : < 200 OK [3357]
2018-01-01 21:39:06,940 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 391, '_0n1': 408}
2018-01-01 21:39:06,943 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,946 : INFO : < 200 OK [3357]
2018-01-01 21:39:06,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 408, '_0n1': 414}
2018-01-01 21:39:06,949 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,953 : INFO : < 200 OK [3320]
2018-01-01 21:39:06,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 594, '_0n1': 614}

2018-01-01 21:39:06,957 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,961 : INFO : < 200 OK [3389]
2018-01-01 21:39:06,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 614, '_0n1': 616}
2018-01-01 21:39:06,965 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,969 : INFO : < 200 OK [3394]
2018-01-01 21:39:06,973 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 616, '_0n1': 600}
2018-01-01 21:39:06,973 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,977 : INFO : < 200 OK [3391]
2018-01-01 21:39:06,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 600, '_0n1': 617}
2018-01-01 21:39:06,981 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,985 : INFO : < 200 OK [3388]
2018-01-01 21:39:06,989 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 309}
2018-01-01 21:39:06,989 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:06,997 : INFO : < 200 OK [3357]
2018-01-01 21:39:06,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 328}
2018-01-01 21:39:07,001 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,005 : INFO : < 200 OK [3349]
2018-01-01 21:39:07,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 328, '_0n1': 314}
2018-01-01 21:39:07,009 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,013 : INFO : < 200 OK [3367]
2018-01-01 21:39:07,013 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 314, '_0n1': 331}
2018-01-01 21:39:07,017 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,021 : INFO : < 200 OK [3352]
2018-01-01 21:39:07,025 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 331, '_0n1': 342}
2018-01-01 21:39:07,025 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,029 : INFO : < 200 OK [3364]
2018-01-01 21:39:07,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 219, '_0n1': 263}
2018-01-01 21:39:07,040 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,045 : INFO : < 200 OK [3337]
2018-01-01 21:39:07,048 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 263, '_0n1': 264}
2018-01-01 21:39:07,049 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,053 : INFO : < 200 OK [3365]
2018-01-01 21:39:07,057 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 264, '_0n1': 281}
2018-01-01 21:39:07,057 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,061 : INFO : < 200 OK [3359]
2018-01-01 21:39:07,065 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 281, '_0n1': 269}
2018-01-01 21:39:07,065 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,073 : INFO : < 200 OK [3324]
2018-01-01 21:39:07,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 269, '_0n1': 292}
2018-01-01 21:39:07,077 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,081 : INFO : < 200 OK [3309]
2018-01-01 21:39:07,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 320}
2018-01-01 21:39:07,085 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,093 : INFO : < 200 OK [3347]
2018-01-01 21:39:07,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 320, '_0n1': 321}
2018-01-01 21:39:07,097 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,101 : INFO : < 200 OK [3379]
2018-01-01 21:39:07,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 321, '_0n1': 330}
2018-01-01 21:39:07,105 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,113 : INFO : < 200 OK [3404]
2018-01-01 21:39:07,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 330, '_0n1': 332}
2018-01-01 21:39:07,117 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,121 : INFO : < 200 OK [3368]
2018-01-01 21:39:07,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 332, '_0n1': 337}
2018-01-01 21:39:07,125 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,129 : INFO : < 200 OK [3352]
2018-01-01 21:39:07,134 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 598, '_0n1': 599}
2018-01-01 21:39:07,136 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,140 : INFO : < 200 OK [3381]
2018-01-01 21:39:07,143 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 599, '_0n1': 601}
2018-01-01 21:39:07,144 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,149 : INFO : < 200 OK [3355]
2018-01-01 21:39:07,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 601, '_0n1': 618}
2018-01-01 21:39:07,153 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,157 : INFO : < 200 OK [3361]
2018-01-01 21:39:07,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 299, '_0n1': 305}
2018-01-01 21:39:07,161 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,165 : INFO : < 200 OK [3383]
2018-01-01 21:39:07,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 322}
2018-01-01 21:39:07,169 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,173 : INFO : < 200 OK [3389]
2018-01-01 21:39:07,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 322, '_0n1': 582}
2018-01-01 21:39:07,177 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,181 : INFO : < 200 OK [3382]

2018-01-01 21:39:07,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 311, '_0n1': 591}
2018-01-01 21:39:07,185 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,189 : INFO : < 200 OK [3409]
2018-01-01 21:39:07,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 591, '_0n1': 597}
2018-01-01 21:39:07,193 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,201 : INFO : < 200 OK [3404]
2018-01-01 21:39:07,205 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 153, '_0n1': 139}
2018-01-01 21:39:07,205 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,209 : INFO : < 200 OK [3354]
2018-01-01 21:39:07,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 139, '_0n1': 140}
2018-01-01 21:39:07,217 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,221 : INFO : < 200 OK [3350]
2018-01-01 21:39:07,225 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 140, '_0n1': 159}
2018-01-01 21:39:07,225 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,229 : INFO : < 200 OK [3348]
2018-01-01 21:39:07,235 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 159, '_0n1': 184}
2018-01-01 21:39:07,237 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,241 : INFO : < 200 OK [3352]
2018-01-01 21:39:07,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 184, '_0n1': 186}
2018-01-01 21:39:07,246 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,249 : INFO : < 200 OK [3352]
2018-01-01 21:39:07,249 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 344, '_0n1': 364}
2018-01-01 21:39:07,253 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,257 : INFO : < 200 OK [3389]
2018-01-01 21:39:07,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 364, '_0n1': 365}
2018-01-01 21:39:07,261 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,265 : INFO : < 200 OK [3376]
2018-01-01 21:39:07,269 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 349}
2018-01-01 21:39:07,269 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,273 : INFO : < 200 OK [3385]
2018-01-01 21:39:07,277 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 349, '_0n1': 374}
2018-01-01 21:39:07,277 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,281 : INFO : < 200 OK [3359]
2018-01-01 21:39:07,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 476, '_0n1': 540}
2018-01-01 21:39:07,285 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,289 : INFO : < 200 OK [3340]
2018-01-01 21:39:07,293 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 540, '_0n1': 555}
2018-01-01 21:39:07,293 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,297 : INFO : < 200 OK [3335]
2018-01-01 21:39:07,301 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 509, '_0n1': 522}
2018-01-01 21:39:07,301 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,305 : INFO : < 200 OK [3373]
2018-01-01 21:39:07,309 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 522, '_0n1': 542}
2018-01-01 21:39:07,309 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,313 : INFO : < 200 OK [3334]
2018-01-01 21:39:07,317 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 134, '_0n1': 182}
2018-01-01 21:39:07,317 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,321 : INFO : < 200 OK [3351]
2018-01-01 21:39:07,325 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 182, '_0n1': 183}
2018-01-01 21:39:07,325 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,329 : INFO : < 200 OK [3319]
2018-01-01 21:39:07,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 183, '_0n1': 187}
2018-01-01 21:39:07,337 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,341 : INFO : < 200 OK [3321]
2018-01-01 21:39:07,344 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 187, '_0n1': 176}
2018-01-01 21:39:07,346 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,349 : INFO : < 200 OK [3317]
2018-01-01 21:39:07,353 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 155, '_0n1': 165}
2018-01-01 21:39:07,357 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,361 : INFO : < 200 OK [3395]
2018-01-01 21:39:07,365 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 165, '_0n1': 170}
2018-01-01 21:39:07,365 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,373 : INFO : < 200 OK [3391]
2018-01-01 21:39:07,377 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 170, '_0n1': 188}
2018-01-01 21:39:07,377 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,381 : INFO : < 200 OK [3402]
2018-01-01 21:39:07,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 188, '_0n1': 172}
2018-01-01 21:39:07,389 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,393 : INFO : < 200 OK [3392]
2018-01-01 21:39:07,397 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 128, '_0n1': 130}
2018-01-01 21:39:07,401 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,409 : INFO : < 200 OK [3418]
2018-01-01 21:39:07,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 130, '_0n1': 150}

2018-01-01 21:39:07,413 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,417 : INFO : < 200 OK [3399]
2018-01-01 21:39:07,421 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 150, '_0n1': 154}
2018-01-01 21:39:07,425 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,429 : INFO : < 200 OK [3404]
2018-01-01 21:39:07,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 276, '_0n1': 300}
2018-01-01 21:39:07,439 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,443 : INFO : < 200 OK [3314]
2018-01-01 21:39:07,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 300, '_0n1': 301}
2018-01-01 21:39:07,448 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,453 : INFO : < 200 OK [3322]
2018-01-01 21:39:07,453 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 301, '_0n1': 308}
2018-01-01 21:39:07,457 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,461 : INFO : < 200 OK [3341]
2018-01-01 21:39:07,465 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 308, '_0n1': 338}
2018-01-01 21:39:07,465 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,473 : INFO : < 200 OK [3345]
2018-01-01 21:39:07,477 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 324, '_0n1': 315}
2018-01-01 21:39:07,477 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,481 : INFO : < 200 OK [3332]
2018-01-01 21:39:07,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 315, '_0n1': 334}
2018-01-01 21:39:07,485 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,489 : INFO : < 200 OK [3333]
2018-01-01 21:39:07,493 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 334, '_0n1': 339}
2018-01-01 21:39:07,493 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,497 : INFO : < 200 OK [3329]
2018-01-01 21:39:07,501 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 61, '_0n1': 316}
2018-01-01 21:39:07,501 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2018-01-01 21:39:07,505 : INFO : < 200 OK [3343]
2018-01-01 21:39:07,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 316, '_0n1': 318}
2018-01-01 21:39:07,509 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,513 : INFO : < 200 OK [3359]
2018-01-01 21:39:07,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 318, '_0n1': 335}
2018-01-01 21:39:07,517 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,521 : INFO : < 200 OK [3364]
2018-01-01 21:39:07,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 341}
2018-01-01 21:39:07,525 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,529 : INFO : < 200 OK [3350]
2018-01-01 21:39:07,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 341, '_0n1': 602}
2018-01-01 21:39:07,533 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2018-01-01 21:39:07,543 : INFO : < 200 OK [3327]

In [64]:
tmp = data.drop_duplicates(subset=['uid', 'category'])
for i, row in title_relation_df.iterrows():
    uid = row['uid']
    x = course_dict[row.uid]
    cat_x = list(tmp[tmp.uid==row.uid])
    for i in range(1, 3):
        y = course_dict[row['relate_%s' % i]]
        cat_y = list(tmp[tmp.uid==row['relate_%s' % i]])
        flag = False
        for cat in cat_x:
            if cat in cat_y:
                flag = True
        if flag:
            if df[df.uid == uid].package_name.values[0] != None:
                if df[df.uid == row['relate_%s' % i]].package_name.values[0] != df[df.uid == uid].package_name.values[0]:
                    graph.create(Relationship(x, "related to", y))
                   # graph.create(Relationship(y, "related to", x))
            else:
                graph.create(Relationship(x, "related to", y))

2018-01-01 21:39:07,778 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1228, '_0n1': 618}
2018-01-01 21:39:07,782 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:07,786 : INFO : < 200 OK [3378]
2018-01-01 21:39:07,790 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1228, '_0n1': 37}
2018-01-01 21:39:07,794 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:07,798 : INFO : < 200 OK [3367]
2018-01-01 21:39:07,802 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1246, '_0n1': 1}
2018-01-01 21:39:07,806 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:07,810 : INFO : < 200 OK [3289]
2018-01-01 21:39:07,814 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1246, '_0n1': 33}
2018-01-01 21:39:07,814 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:07,818 : INFO : < 200 OK [3323]
2018-01-01 21:39:07,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1229, '_0n1': 317}
2018-01-01 21:39:07,826 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:07,830 : INFO : < 200 OK [3459]
2018-01-01 21:39:07,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1229, '_0n1': 46}
2018-01-01 21:39:07,840 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:07,844 : INFO : < 200 OK [3460]
2018-01-01 21:39:07,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1247, '_0n1': 201}
2018-01-01 21:39:07,850 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:07,854 : INFO : < 200 OK [3390]
2018-01-01 21:39:07,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1247, '_0n1': 383}
2018-01-01 21:39:07,858 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:07,862 : INFO : < 200 OK [3402]
2018-01-01 21:39:07,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1230, '_0n1': 356}
2018-01-01 21:39:07,874 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:07,878 : INFO : < 200 OK [3330]
2018-01-01 21:39:07,886 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1230, '_0n1': 602}
2018-01-01 21:39:07,886 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:07,890 : INFO : < 200 OK [3331]
2018-01-01 21:39:07,902 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1231, '_0n1': 1252}
2018-01-01 21:39:07,902 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:39:07,906 : INFO : < 200 OK [3443]
2018-01-01 21:39:07,910 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1231, '_0n1': 396}
2018-01-01 21:39:07,910 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:07,914 : INFO : < 200 OK [3416]
2018-01-01 21:39:07,926 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1232, '_0n1': 19}
2018-01-01 21:39:07,926 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:07,935 : INFO : < 200 OK [3359]
2018-01-01 21:39:07,940 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1232, '_0n1': 25}
2018-01-01 21:39:07,941 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:07,947 : INFO : < 200 OK [3355]
2018-01-01 21:39:07,954 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1250, '_0n1': 385}
2018-01-01 21:39:07,954 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:07,958 : INFO : < 200 OK [3466]
2018-01-01 21:39:07,962 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1233, '_0n1': 1234}
2018-01-01 21:39:07,966 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:39:07,970 : INFO : < 200 OK [3354]
2018-01-01 21:39:07,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1233, '_0n1': 1231}
2018-01-01 21:39:07,974 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:39:07,978 : INFO : < 200 OK [3386]
2018-01-01 21:39:07,986 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1251, '_0n1': 317}
2018-01-01 21:39:07,990 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:07,994 : INFO : < 200 OK [3449]
2018-01-01 21:39:08,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1234, '_0n1': 1233}
2018-01-01 21:39:08,002 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:39:08,006 : INFO : < 200 OK [3354]
2018-01-01 21:39:08,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1234, '_0n1': 24}
2018-01-01 21:39:08,014 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,022 : INFO : < 200 OK [3368]
2018-01-01 21:39:08,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1252, '_0n1': 1231}
2018-01-01 21:39:08,030 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:39:08,035 : INFO : < 200 OK [3443]
2018-01-01 21:39:08,039 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1252, '_0n1': 1256}
2018-01-01 21:39:08,040 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:39:08,044 : INFO : < 200 OK [3454]
2018-01-01 21:39:08,070 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1237, '_0n1': 567}
2018-01-01 21:39:08,074 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:08,078 : INFO : < 200 OK [3432]
2018-01-01 21:39:08,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1237, '_0n1': 96}
2018-01-01 21:39:08,082 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,086 : INFO : < 200 OK [3379]

2018-01-01 21:39:08,094 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1255, '_0n1': 317}
2018-01-01 21:39:08,094 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:08,098 : INFO : < 200 OK [3474]
2018-01-01 21:39:08,106 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1255, '_0n1': 1229}
2018-01-01 21:39:08,110 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:39:08,114 : INFO : < 200 OK [3500]
2018-01-01 21:39:08,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1256, '_0n1': 1252}
2018-01-01 21:39:08,122 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:39:08,126 : INFO : < 200 OK [3454]
2018-01-01 21:39:08,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1256, '_0n1': 1231}
2018-01-01 21:39:08,135 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:39:08,139 : INFO : < 200 OK [3440]
2018-01-01 21:39:08,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1239, '_0n1': 144}
2018-01-01 21:39:08,146 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:08,149 : INFO : < 200 OK [3461]
2018-01-01 21:39:08,153 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1239, '_0n1': 126}
2018-01-01 21:39:08,153 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:08,157 : INFO : < 200 OK [3475]
2018-01-01 21:39:08,165 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1259, '_0n1': 1231}
2018-01-01 21:39:08,165 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2018-01-01 21:39:08,169 : INFO : < 200 OK [3445]
2018-01-01 21:39:08,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 0, '_0n1': 576}
2018-01-01 21:39:08,185 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,193 : INFO : < 200 OK [3321]
2018-01-01 21:39:08,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 0, '_0n1': 418}
2018-01-01 21:39:08,201 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,205 : INFO : < 200 OK [3317]
2018-01-01 21:39:08,221 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1, '_0n1': 1246}
2018-01-01 21:39:08,221 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,225 : INFO : < 200 OK [3289]
2018-01-01 21:39:08,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1, '_0n1': 35}
2018-01-01 21:39:08,233 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:08,238 : INFO : < 200 OK [3295]
2018-01-01 21:39:08,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 452}
2018-01-01 21:39:08,250 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,254 : INFO : < 200 OK [3388]
2018-01-01 21:39:08,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 431}
2018-01-01 21:39:08,258 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,266 : INFO : < 200 OK [3340]
2018-01-01 21:39:08,270 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 20, '_0n1': 24}
2018-01-01 21:39:08,270 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,274 : INFO : < 200 OK [3378]
2018-01-01 21:39:08,278 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 20, '_0n1': 1256}
2018-01-01 21:39:08,282 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,286 : INFO : < 200 OK [3418]
2018-01-01 21:39:08,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 3, '_0n1': 317}
2018-01-01 21:39:08,294 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,302 : INFO : < 200 OK [3379]
2018-01-01 21:39:08,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 3, '_0n1': 420}
2018-01-01 21:39:08,310 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,314 : INFO : < 200 OK [3326]
2018-01-01 21:39:08,318 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 21, '_0n1': 1236}
2018-01-01 21:39:08,318 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,322 : INFO : < 200 OK [3443]
2018-01-01 21:39:08,326 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 21, '_0n1': 5}
2018-01-01 21:39:08,330 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:08,334 : INFO : < 200 OK [3394]
2018-01-01 21:39:08,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 4, '_0n1': 1256}
2018-01-01 21:39:08,343 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,347 : INFO : < 200 OK [3406]
2018-01-01 21:39:08,350 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 4, '_0n1': 1252}
2018-01-01 21:39:08,354 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,358 : INFO : < 200 OK [3409]
2018-01-01 21:39:08,362 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 22, '_0n1': 4}
2018-01-01 21:39:08,362 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:08,370 : INFO : < 200 OK [3320]
2018-01-01 21:39:08,378 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 22, '_0n1': 356}
2018-01-01 21:39:08,378 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,386 : INFO : < 200 OK [3302]
2018-01-01 21:39:08,390 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 5, '_0n1': 1231}
2018-01-01 21:39:08,394 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,398 : INFO : < 200 OK [3406]
2018-01-01 21:39:08,402 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 5, '_0n1': 21}

2018-01-01 21:39:08,406 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:08,410 : INFO : < 200 OK [3394]
2018-01-01 21:39:08,414 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 6, '_0n1': 37}
2018-01-01 21:39:08,418 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:08,418 : INFO : < 200 OK [3355]
2018-01-01 21:39:08,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 23, '_0n1': 24}
2018-01-01 21:39:08,430 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,436 : INFO : < 200 OK [3326]
2018-01-01 21:39:08,441 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 23, '_0n1': 30}
2018-01-01 21:39:08,442 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,446 : INFO : < 200 OK [3344]
2018-01-01 21:39:08,454 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 7, '_0n1': 204}
2018-01-01 21:39:08,458 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,462 : INFO : < 200 OK [3359]
2018-01-01 21:39:08,466 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 7, '_0n1': 1240}
2018-01-01 21:39:08,470 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,474 : INFO : < 200 OK [3359]
2018-01-01 21:39:08,478 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 25, '_0n1': 19}
2018-01-01 21:39:08,482 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,486 : INFO : < 200 OK [3303]
2018-01-01 21:39:08,498 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 8, '_0n1': 396}
2018-01-01 21:39:08,498 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,502 : INFO : < 200 OK [3374]
2018-01-01 21:39:08,506 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 8, '_0n1': 11}
2018-01-01 21:39:08,510 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:08,514 : INFO : < 200 OK [3369]
2018-01-01 21:39:08,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 9, '_0n1': 1232}
2018-01-01 21:39:08,526 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,530 : INFO : < 200 OK [3343]
2018-01-01 21:39:08,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 9, '_0n1': 11}
2018-01-01 21:39:08,537 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:08,541 : INFO : < 200 OK [3334]
2018-01-01 21:39:08,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 27, '_0n1': 35}
2018-01-01 21:39:08,548 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,550 : INFO : < 200 OK [3357]
2018-01-01 21:39:08,554 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 27, '_0n1': 1246}
2018-01-01 21:39:08,558 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,562 : INFO : < 200 OK [3351]
2018-01-01 21:39:08,574 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 10, '_0n1': 96}
2018-01-01 21:39:08,578 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,582 : INFO : < 200 OK [3350]
2018-01-01 21:39:08,590 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 28, '_0n1': 1256}
2018-01-01 21:39:08,590 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,594 : INFO : < 200 OK [3392]
2018-01-01 21:39:08,602 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 11, '_0n1': 166}
2018-01-01 21:39:08,602 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,606 : INFO : < 200 OK [3396]
2018-01-01 21:39:08,610 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 11, '_0n1': 1232}
2018-01-01 21:39:08,610 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,614 : INFO : < 200 OK [3402]
2018-01-01 21:39:08,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 12, '_0n1': 1231}
2018-01-01 21:39:08,638 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,643 : INFO : < 200 OK [3409]
2018-01-01 21:39:08,650 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 30, '_0n1': 29}
2018-01-01 21:39:08,650 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,658 : INFO : < 200 OK [3382]
2018-01-01 21:39:08,670 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 31, '_0n1': 1229}
2018-01-01 21:39:08,670 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,674 : INFO : < 200 OK [3456]
2018-01-01 21:39:08,678 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 31, '_0n1': 98}
2018-01-01 21:39:08,678 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,686 : INFO : < 200 OK [3414]
2018-01-01 21:39:08,690 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 14, '_0n1': 393}
2018-01-01 21:39:08,690 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,694 : INFO : < 200 OK [3406]
2018-01-01 21:39:08,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 14, '_0n1': 395}
2018-01-01 21:39:08,698 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,702 : INFO : < 200 OK [3401]
2018-01-01 21:39:08,710 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 32, '_0n1': 96}
2018-01-01 21:39:08,710 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,714 : INFO : < 200 OK [3300]
2018-01-01 21:39:08,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 15, '_0n1': 93}
2018-01-01 21:39:08,726 : INFO : > POST http://localhost:7474/db/data/cypher [181]

2018-01-01 21:39:08,730 : INFO : < 200 OK [3315]
2018-01-01 21:39:08,738 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 15, '_0n1': 287}
2018-01-01 21:39:08,739 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,743 : INFO : < 200 OK [3320]
2018-01-01 21:39:08,748 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 33, '_0n1': 1246}
2018-01-01 21:39:08,750 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,754 : INFO : < 200 OK [3323]
2018-01-01 21:39:08,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 33, '_0n1': 6}
2018-01-01 21:39:08,758 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:08,762 : INFO : < 200 OK [3334]
2018-01-01 21:39:08,770 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 16, '_0n1': 30}
2018-01-01 21:39:08,770 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,774 : INFO : < 200 OK [3406]
2018-01-01 21:39:08,778 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 16, '_0n1': 29}
2018-01-01 21:39:08,782 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,786 : INFO : < 200 OK [3381]
2018-01-01 21:39:08,790 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 34, '_0n1': 96}
2018-01-01 21:39:08,790 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,794 : INFO : < 200 OK [3327]
2018-01-01 21:39:08,802 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 34, '_0n1': 260}
2018-01-01 21:39:08,806 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,810 : INFO : < 200 OK [3376]
2018-01-01 21:39:08,814 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 17, '_0n1': 539}
2018-01-01 21:39:08,818 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,822 : INFO : < 200 OK [3386]
2018-01-01 21:39:08,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 17, '_0n1': 1230}
2018-01-01 21:39:08,826 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,830 : INFO : < 200 OK [3380]
2018-01-01 21:39:08,840 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 35, '_0n1': 27}
2018-01-01 21:39:08,841 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,845 : INFO : < 200 OK [3357]
2018-01-01 21:39:08,850 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 35, '_0n1': 1}
2018-01-01 21:39:08,850 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:08,854 : INFO : < 200 OK [3295]
2018-01-01 21:39:08,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 18, '_0n1': 19}
2018-01-01 21:39:08,862 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,866 : INFO : < 200 OK [3359]
2018-01-01 21:39:08,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 18, '_0n1': 1252}
2018-01-01 21:39:08,870 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,874 : INFO : < 200 OK [3434]
2018-01-01 21:39:08,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 36, '_0n1': 96}
2018-01-01 21:39:08,886 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,890 : INFO : < 200 OK [3336]
2018-01-01 21:39:08,898 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 36, '_0n1': 1252}
2018-01-01 21:39:08,902 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,906 : INFO : < 200 OK [3409]
2018-01-01 21:39:08,910 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 19, '_0n1': 1232}
2018-01-01 21:39:08,910 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:08,918 : INFO : < 200 OK [3359]
2018-01-01 21:39:08,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 19, '_0n1': 25}
2018-01-01 21:39:08,922 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,926 : INFO : < 200 OK [3303]
2018-01-01 21:39:08,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 37, '_0n1': 6}
2018-01-01 21:39:08,936 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:08,940 : INFO : < 200 OK [3355]
2018-01-01 21:39:08,946 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 37, '_0n1': 53}
2018-01-01 21:39:08,948 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,950 : INFO : < 200 OK [3347]
2018-01-01 21:39:08,962 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 38, '_0n1': 15}
2018-01-01 21:39:08,966 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,970 : INFO : < 200 OK [3360]
2018-01-01 21:39:08,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 38, '_0n1': 447}
2018-01-01 21:39:08,978 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:08,982 : INFO : < 200 OK [3415]
2018-01-01 21:39:08,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 41, '_0n1': 96}
2018-01-01 21:39:08,994 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:08,998 : INFO : < 200 OK [3341]
2018-01-01 21:39:09,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 41, '_0n1': 260}
2018-01-01 21:39:09,002 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,010 : INFO : < 200 OK [3390]
2018-01-01 21:39:09,018 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 42, '_0n1': 1230}
2018-01-01 21:39:09,018 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:09,022 : INFO : < 200 OK [3317]

2018-01-01 21:39:09,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 42, '_0n1': 1252}
2018-01-01 21:39:09,030 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:09,034 : INFO : < 200 OK [3378]
2018-01-01 21:39:09,039 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 60, '_0n1': 19}
2018-01-01 21:39:09,040 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,044 : INFO : < 200 OK [3380]
2018-01-01 21:39:09,048 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 60, '_0n1': 175}
2018-01-01 21:39:09,049 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,050 : INFO : < 200 OK [3445]
2018-01-01 21:39:09,070 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 61, '_0n1': 333}
2018-01-01 21:39:09,074 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,078 : INFO : < 200 OK [3352]
2018-01-01 21:39:09,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 61, '_0n1': 389}
2018-01-01 21:39:09,082 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,090 : INFO : < 200 OK [3367]
2018-01-01 21:39:09,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 62, '_0n1': 1252}
2018-01-01 21:39:09,102 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:09,106 : INFO : < 200 OK [3411]
2018-01-01 21:39:09,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 62, '_0n1': 1231}
2018-01-01 21:39:09,110 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:09,114 : INFO : < 200 OK [3397]
2018-01-01 21:39:09,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 45, '_0n1': 317}
2018-01-01 21:39:09,122 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,126 : INFO : < 200 OK [3372]
2018-01-01 21:39:09,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 45, '_0n1': 4}
2018-01-01 21:39:09,135 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:09,140 : INFO : < 200 OK [3336]
2018-01-01 21:39:09,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 46, '_0n1': 1229}
2018-01-01 21:39:09,151 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:09,159 : INFO : < 200 OK [3460]
2018-01-01 21:39:09,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 46, '_0n1': 1236}
2018-01-01 21:39:09,167 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:09,171 : INFO : < 200 OK [3458]
2018-01-01 21:39:09,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 64, '_0n1': 548}
2018-01-01 21:39:09,179 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,187 : INFO : < 200 OK [3305]
2018-01-01 21:39:09,191 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 64, '_0n1': 392}
2018-01-01 21:39:09,191 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,195 : INFO : < 200 OK [3307]
2018-01-01 21:39:09,199 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 47, '_0n1': 1231}
2018-01-01 21:39:09,203 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:09,207 : INFO : < 200 OK [3406]
2018-01-01 21:39:09,211 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 47, '_0n1': 600}
2018-01-01 21:39:09,215 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,219 : INFO : < 200 OK [3386]
2018-01-01 21:39:09,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 65, '_0n1': 408}
2018-01-01 21:39:09,227 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,231 : INFO : < 200 OK [3370]
2018-01-01 21:39:09,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 65, '_0n1': 551}
2018-01-01 21:39:09,244 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,248 : INFO : < 200 OK [3367]
2018-01-01 21:39:09,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 48, '_0n1': 0}
2018-01-01 21:39:09,255 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2018-01-01 21:39:09,259 : INFO : < 200 OK [3323]
2018-01-01 21:39:09,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 48, '_0n1': 246}
2018-01-01 21:39:09,267 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,271 : INFO : < 200 OK [3384]
2018-01-01 21:39:09,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 384}
2018-01-01 21:39:09,279 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,283 : INFO : < 200 OK [3385]
2018-01-01 21:39:09,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 504}
2018-01-01 21:39:09,291 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,295 : INFO : < 200 OK [3364]
2018-01-01 21:39:09,303 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 384}
2018-01-01 21:39:09,303 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,311 : INFO : < 200 OK [3381]
2018-01-01 21:39:09,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 67, '_0n1': 358}
2018-01-01 21:39:09,315 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,319 : INFO : < 200 OK [3395]
2018-01-01 21:39:09,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 50, '_0n1': 70}
2018-01-01 21:39:09,331 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,337 : INFO : < 200 OK [3352]
2018-01-01 21:39:09,344 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 50, '_0n1': 96}

2018-01-01 21:39:09,346 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,350 : INFO : < 200 OK [3331]
2018-01-01 21:39:09,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 86}
2018-01-01 21:39:09,363 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,367 : INFO : < 200 OK [3406]
2018-01-01 21:39:09,375 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 69}
2018-01-01 21:39:09,375 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,379 : INFO : < 200 OK [3402]
2018-01-01 21:39:09,407 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 50}
2018-01-01 21:39:09,411 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,415 : INFO : < 200 OK [3352]
2018-01-01 21:39:09,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 96}
2018-01-01 21:39:09,423 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,431 : INFO : < 200 OK [3332]
2018-01-01 21:39:09,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 58}
2018-01-01 21:39:09,449 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,451 : INFO : < 200 OK [3378]
2018-01-01 21:39:09,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 71, '_0n1': 589}
2018-01-01 21:39:09,459 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,463 : INFO : < 200 OK [3450]
2018-01-01 21:39:09,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 71, '_0n1': 262}
2018-01-01 21:39:09,471 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,475 : INFO : < 200 OK [3421]
2018-01-01 21:39:09,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 54, '_0n1': 560}
2018-01-01 21:39:09,483 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,487 : INFO : < 200 OK [3380]
2018-01-01 21:39:09,491 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 54, '_0n1': 579}
2018-01-01 21:39:09,491 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,499 : INFO : < 200 OK [3394]
2018-01-01 21:39:09,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 72, '_0n1': 220}
2018-01-01 21:39:09,511 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,515 : INFO : < 200 OK [3343]
2018-01-01 21:39:09,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 55, '_0n1': 287}
2018-01-01 21:39:09,523 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,531 : INFO : < 200 OK [3336]
2018-01-01 21:39:09,538 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 55, '_0n1': 220}
2018-01-01 21:39:09,540 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,544 : INFO : < 200 OK [3333]
2018-01-01 21:39:09,551 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 73, '_0n1': 358}
2018-01-01 21:39:09,555 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,559 : INFO : < 200 OK [3357]
2018-01-01 21:39:09,575 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 74, '_0n1': 544}
2018-01-01 21:39:09,575 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,579 : INFO : < 200 OK [3342]
2018-01-01 21:39:09,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 74, '_0n1': 338}
2018-01-01 21:39:09,587 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,591 : INFO : < 200 OK [3327]
2018-01-01 21:39:09,603 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 57, '_0n1': 452}
2018-01-01 21:39:09,603 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,611 : INFO : < 200 OK [3366]
2018-01-01 21:39:09,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 75, '_0n1': 76}
2018-01-01 21:39:09,619 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,623 : INFO : < 200 OK [3366]
2018-01-01 21:39:09,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 75, '_0n1': 179}
2018-01-01 21:39:09,631 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,639 : INFO : < 200 OK [3366]
2018-01-01 21:39:09,658 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 76, '_0n1': 77}
2018-01-01 21:39:09,662 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,666 : INFO : < 200 OK [3401]
2018-01-01 21:39:09,674 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 604}
2018-01-01 21:39:09,678 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,682 : INFO : < 200 OK [3386]
2018-01-01 21:39:09,690 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 54}
2018-01-01 21:39:09,690 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,698 : INFO : < 200 OK [3344]
2018-01-01 21:39:09,710 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 81, '_0n1': 80}
2018-01-01 21:39:09,710 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,718 : INFO : < 200 OK [3359]
2018-01-01 21:39:09,722 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 81, '_0n1': 461}
2018-01-01 21:39:09,722 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,726 : INFO : < 200 OK [3345]
2018-01-01 21:39:09,739 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 78, '_0n1': 563}
2018-01-01 21:39:09,741 : INFO : > POST http://localhost:7474/db/data/cypher [182]

2018-01-01 21:39:09,745 : INFO : < 200 OK [3426]
2018-01-01 21:39:09,755 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 82, '_0n1': 86}
2018-01-01 21:39:09,755 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,763 : INFO : < 200 OK [3408]
2018-01-01 21:39:09,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 82, '_0n1': 68}
2018-01-01 21:39:09,767 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,771 : INFO : < 200 OK [3355]
2018-01-01 21:39:09,783 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 80, '_0n1': 81}
2018-01-01 21:39:09,783 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,787 : INFO : < 200 OK [3359]
2018-01-01 21:39:09,795 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 83, '_0n1': 122}
2018-01-01 21:39:09,799 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,819 : INFO : < 200 OK [3354]
2018-01-01 21:39:09,827 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 83, '_0n1': 96}
2018-01-01 21:39:09,827 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:09,835 : INFO : < 200 OK [3338]
2018-01-01 21:39:09,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 110}
2018-01-01 21:39:09,849 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:09,851 : INFO : < 200 OK [3406]
2018-01-01 21:39:09,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 84, '_0n1': 451}
2018-01-01 21:39:09,859 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,863 : INFO : < 200 OK [3309]
2018-01-01 21:39:09,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 84, '_0n1': 519}
2018-01-01 21:39:09,871 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,879 : INFO : < 200 OK [3364]
2018-01-01 21:39:09,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 86}
2018-01-01 21:39:09,887 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,895 : INFO : < 200 OK [3432]
2018-01-01 21:39:09,907 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 85, '_0n1': 110}
2018-01-01 21:39:09,911 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,915 : INFO : < 200 OK [3393]
2018-01-01 21:39:09,927 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 103, '_0n1': 299}
2018-01-01 21:39:09,927 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:09,931 : INFO : < 200 OK [3381]
2018-01-01 21:39:09,940 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 86, '_0n1': 102}
2018-01-01 21:39:09,941 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,946 : INFO : < 200 OK [3432]
2018-01-01 21:39:09,959 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 104, '_0n1': 399}
2018-01-01 21:39:09,963 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:09,967 : INFO : < 200 OK [3345]
2018-01-01 21:39:09,971 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 87, '_0n1': 514}
2018-01-01 21:39:09,971 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,979 : INFO : < 200 OK [3366]
2018-01-01 21:39:09,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 87, '_0n1': 188}
2018-01-01 21:39:09,983 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:09,987 : INFO : < 200 OK [3399]
2018-01-01 21:39:10,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 10}
2018-01-01 21:39:10,003 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,007 : INFO : < 200 OK [3393]
2018-01-01 21:39:10,015 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 122}
2018-01-01 21:39:10,015 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,019 : INFO : < 200 OK [3370]
2018-01-01 21:39:10,027 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 89, '_0n1': 530}
2018-01-01 21:39:10,027 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,036 : INFO : < 200 OK [3341]
2018-01-01 21:39:10,042 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 89, '_0n1': 398}
2018-01-01 21:39:10,044 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,049 : INFO : < 200 OK [3393]
2018-01-01 21:39:10,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 90, '_0n1': 80}
2018-01-01 21:39:10,059 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:10,063 : INFO : < 200 OK [3378]
2018-01-01 21:39:10,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 90, '_0n1': 381}
2018-01-01 21:39:10,075 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,079 : INFO : < 200 OK [3402]
2018-01-01 21:39:10,091 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 108, '_0n1': 365}
2018-01-01 21:39:10,095 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,099 : INFO : < 200 OK [3402]
2018-01-01 21:39:10,103 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 108, '_0n1': 381}
2018-01-01 21:39:10,107 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,111 : INFO : < 200 OK [3416]
2018-01-01 21:39:10,123 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 92, '_0n1': 192}
2018-01-01 21:39:10,127 : INFO : > POST http://localhost:7474/db/data/cypher [182]

2018-01-01 21:39:10,131 : INFO : < 200 OK [3401]
2018-01-01 21:39:10,138 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 92, '_0n1': 441}
2018-01-01 21:39:10,139 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,144 : INFO : < 200 OK [3377]
2018-01-01 21:39:10,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 85}
2018-01-01 21:39:10,151 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,155 : INFO : < 200 OK [3393]
2018-01-01 21:39:10,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 577}
2018-01-01 21:39:10,163 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,171 : INFO : < 200 OK [3412]
2018-01-01 21:39:10,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 93, '_0n1': 287}
2018-01-01 21:39:10,183 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,187 : INFO : < 200 OK [3318]
2018-01-01 21:39:10,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 94, '_0n1': 102}
2018-01-01 21:39:10,195 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,199 : INFO : < 200 OK [3372]
2018-01-01 21:39:10,207 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 94, '_0n1': 86}
2018-01-01 21:39:10,211 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:10,215 : INFO : < 200 OK [3399]
2018-01-01 21:39:10,223 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 112, '_0n1': 578}
2018-01-01 21:39:10,227 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,231 : INFO : < 200 OK [3383]
2018-01-01 21:39:10,242 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 68}
2018-01-01 21:39:10,244 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:10,249 : INFO : < 200 OK [3363]
2018-01-01 21:39:10,259 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 113, '_0n1': 98}
2018-01-01 21:39:10,259 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,263 : INFO : < 200 OK [3417]
2018-01-01 21:39:10,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 113, '_0n1': 97}
2018-01-01 21:39:10,271 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,275 : INFO : < 200 OK [3406]
2018-01-01 21:39:10,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 96, '_0n1': 260}
2018-01-01 21:39:10,279 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,283 : INFO : < 200 OK [3360]
2018-01-01 21:39:10,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 96, '_0n1': 291}
2018-01-01 21:39:10,291 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,295 : INFO : < 200 OK [3341]
2018-01-01 21:39:10,303 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 97, '_0n1': 98}
2018-01-01 21:39:10,303 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:10,311 : INFO : < 200 OK [3390]
2018-01-01 21:39:10,311 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 97, '_0n1': 113}
2018-01-01 21:39:10,315 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,319 : INFO : < 200 OK [3406]
2018-01-01 21:39:10,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 98, '_0n1': 97}
2018-01-01 21:39:10,331 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:10,338 : INFO : < 200 OK [3390]
2018-01-01 21:39:10,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 98, '_0n1': 113}
2018-01-01 21:39:10,345 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,351 : INFO : < 200 OK [3417]
2018-01-01 21:39:10,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 99, '_0n1': 92}
2018-01-01 21:39:10,363 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:10,367 : INFO : < 200 OK [3361]
2018-01-01 21:39:10,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 99, '_0n1': 34}
2018-01-01 21:39:10,375 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:10,379 : INFO : < 200 OK [3353]
2018-01-01 21:39:10,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 119, '_0n1': 301}
2018-01-01 21:39:10,395 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,399 : INFO : < 200 OK [3359]
2018-01-01 21:39:10,407 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 119, '_0n1': 303}
2018-01-01 21:39:10,407 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,415 : INFO : < 200 OK [3393]
2018-01-01 21:39:10,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 122, '_0n1': 96}
2018-01-01 21:39:10,423 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,427 : INFO : < 200 OK [3327]
2018-01-01 21:39:10,431 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 122, '_0n1': 260}
2018-01-01 21:39:10,436 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,440 : INFO : < 200 OK [3376]
2018-01-01 21:39:10,445 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 120, '_0n1': 112}
2018-01-01 21:39:10,446 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,450 : INFO : < 200 OK [3374]
2018-01-01 21:39:10,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 120, '_0n1': 115}
2018-01-01 21:39:10,455 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:10,459 : INFO : < 200 OK [3411]
2018-01-01 21:39:10,463 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 123, '_0n1': 414}
2018-01-01 21:39:10,467 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,471 : INFO : < 200 OK [3358]
2018-01-01 21:39:10,475 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 123, '_0n1': 522}
2018-01-01 21:39:10,479 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,483 : INFO : < 200 OK [3380]
2018-01-01 21:39:10,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 141, '_0n1': 128}
2018-01-01 21:39:10,491 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,499 : INFO : < 200 OK [3432]
2018-01-01 21:39:10,503 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 141, '_0n1': 418}
2018-01-01 21:39:10,503 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,507 : INFO : < 200 OK [3379]
2018-01-01 21:39:10,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 404}
2018-01-01 21:39:10,515 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,519 : INFO : < 200 OK [3370]
2018-01-01 21:39:10,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 252}
2018-01-01 21:39:10,527 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,531 : INFO : < 200 OK [3420]
2018-01-01 21:39:10,538 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 142, '_0n1': 424}
2018-01-01 21:39:10,539 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,543 : INFO : < 200 OK [3417]
2018-01-01 21:39:10,546 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 142, '_0n1': 386}
2018-01-01 21:39:10,547 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,551 : INFO : < 200 OK [3380]
2018-01-01 21:39:10,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 330}
2018-01-01 21:39:10,555 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,559 : INFO : < 200 OK [3390]
2018-01-01 21:39:10,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 452}
2018-01-01 21:39:10,567 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,571 : INFO : < 200 OK [3399]
2018-01-01 21:39:10,583 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 126, '_0n1': 385}
2018-01-01 21:39:10,583 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,587 : INFO : < 200 OK [3460]
2018-01-01 21:39:10,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 144, '_0n1': 1239}
2018-01-01 21:39:10,599 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:10,603 : INFO : < 200 OK [3461]
2018-01-01 21:39:10,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 145, '_0n1': 467}
2018-01-01 21:39:10,615 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,619 : INFO : < 200 OK [3428]
2018-01-01 21:39:10,623 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 145, '_0n1': 462}
2018-01-01 21:39:10,627 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,631 : INFO : < 200 OK [3438]
2018-01-01 21:39:10,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 128, '_0n1': 418}
2018-01-01 21:39:10,646 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,651 : INFO : < 200 OK [3386]
2018-01-01 21:39:10,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 578}
2018-01-01 21:39:10,664 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,668 : INFO : < 200 OK [3398]
2018-01-01 21:39:10,672 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 129, '_0n1': 194}
2018-01-01 21:39:10,672 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,676 : INFO : < 200 OK [3356]
2018-01-01 21:39:10,684 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 129, '_0n1': 195}
2018-01-01 21:39:10,684 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,688 : INFO : < 200 OK [3432]
2018-01-01 21:39:10,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 147, '_0n1': 187}
2018-01-01 21:39:10,696 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,700 : INFO : < 200 OK [3373]
2018-01-01 21:39:10,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 147, '_0n1': 140}
2018-01-01 21:39:10,712 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,716 : INFO : < 200 OK [3386]
2018-01-01 21:39:10,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 130, '_0n1': 298}
2018-01-01 21:39:10,732 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,738 : INFO : < 200 OK [3404]
2018-01-01 21:39:10,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 131, '_0n1': 155}
2018-01-01 21:39:10,751 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,756 : INFO : < 200 OK [3393]
2018-01-01 21:39:10,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 131, '_0n1': 165}
2018-01-01 21:39:10,760 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,764 : INFO : < 200 OK [3395]
2018-01-01 21:39:10,772 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 149, '_0n1': 164}
2018-01-01 21:39:10,776 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,780 : INFO : < 200 OK [3291]

2018-01-01 21:39:10,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 149, '_0n1': 156}
2018-01-01 21:39:10,784 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,792 : INFO : < 200 OK [3322]
2018-01-01 21:39:10,800 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 132, '_0n1': 23}
2018-01-01 21:39:10,804 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,808 : INFO : < 200 OK [3361]
2018-01-01 21:39:10,812 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 132, '_0n1': 568}
2018-01-01 21:39:10,816 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,820 : INFO : < 200 OK [3432]
2018-01-01 21:39:10,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 150, '_0n1': 301}
2018-01-01 21:39:10,828 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,836 : INFO : < 200 OK [3369]
2018-01-01 21:39:10,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 151, '_0n1': 187}
2018-01-01 21:39:10,856 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,860 : INFO : < 200 OK [3343]
2018-01-01 21:39:10,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 134, '_0n1': 64}
2018-01-01 21:39:10,868 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,872 : INFO : < 200 OK [3340]
2018-01-01 21:39:10,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 134, '_0n1': 392}
2018-01-01 21:39:10,876 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,880 : INFO : < 200 OK [3354]
2018-01-01 21:39:10,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 152, '_0n1': 54}
2018-01-01 21:39:10,892 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,896 : INFO : < 200 OK [3343]
2018-01-01 21:39:10,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 135, '_0n1': 171}
2018-01-01 21:39:10,904 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,908 : INFO : < 200 OK [3413]
2018-01-01 21:39:10,912 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 135, '_0n1': 1247}
2018-01-01 21:39:10,916 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:10,920 : INFO : < 200 OK [3405]
2018-01-01 21:39:10,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 333}
2018-01-01 21:39:10,937 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,942 : INFO : < 200 OK [3404]
2018-01-01 21:39:10,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 404}
2018-01-01 21:39:10,947 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,951 : INFO : < 200 OK [3392]
2018-01-01 21:39:10,963 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 137, '_0n1': 269}
2018-01-01 21:39:10,963 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:10,971 : INFO : < 200 OK [3353]
2018-01-01 21:39:10,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 138, '_0n1': 85}
2018-01-01 21:39:10,983 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,987 : INFO : < 200 OK [3393]
2018-01-01 21:39:10,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 138, '_0n1': 31}
2018-01-01 21:39:10,995 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:10,999 : INFO : < 200 OK [3418]
2018-01-01 21:39:11,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 156, '_0n1': 164}
2018-01-01 21:39:11,003 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,011 : INFO : < 200 OK [3360]
2018-01-01 21:39:11,015 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 156, '_0n1': 273}
2018-01-01 21:39:11,015 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,019 : INFO : < 200 OK [3383]
2018-01-01 21:39:11,031 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 139, '_0n1': 591}
2018-01-01 21:39:11,031 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,035 : INFO : < 200 OK [3394]
2018-01-01 21:39:11,052 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 140, '_0n1': 594}
2018-01-01 21:39:11,052 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,056 : INFO : < 200 OK [3376]
2018-01-01 21:39:11,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 158, '_0n1': 311}
2018-01-01 21:39:11,068 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,072 : INFO : < 200 OK [3360]
2018-01-01 21:39:11,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 161, '_0n1': 354}
2018-01-01 21:39:11,084 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,088 : INFO : < 200 OK [3406]
2018-01-01 21:39:11,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 353}
2018-01-01 21:39:11,108 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,112 : INFO : < 200 OK [3379]
2018-01-01 21:39:11,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 290}
2018-01-01 21:39:11,120 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,124 : INFO : < 200 OK [3395]
2018-01-01 21:39:11,132 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 160, '_0n1': 311}
2018-01-01 21:39:11,137 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,142 : INFO : < 200 OK [3401]
2018-01-01 21:39:11,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 163, '_0n1': 122}

2018-01-01 21:39:11,149 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,151 : INFO : < 200 OK [3350]
2018-01-01 21:39:11,156 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 163, '_0n1': 96}
2018-01-01 21:39:11,156 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:11,160 : INFO : < 200 OK [3334]
2018-01-01 21:39:11,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 164, '_0n1': 273}
2018-01-01 21:39:11,168 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,172 : INFO : < 200 OK [3352]
2018-01-01 21:39:11,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 164, '_0n1': 156}
2018-01-01 21:39:11,180 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,184 : INFO : < 200 OK [3360]
2018-01-01 21:39:11,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 181, '_0n1': 597}
2018-01-01 21:39:11,196 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,200 : INFO : < 200 OK [3351]
2018-01-01 21:39:11,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 182, '_0n1': 366}
2018-01-01 21:39:11,220 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,224 : INFO : < 200 OK [3324]
2018-01-01 21:39:11,228 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 166, '_0n1': 11}
2018-01-01 21:39:11,232 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:11,237 : INFO : < 200 OK [3396]
2018-01-01 21:39:11,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 166, '_0n1': 343}
2018-01-01 21:39:11,245 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,250 : INFO : < 200 OK [3410]
2018-01-01 21:39:11,252 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 183, '_0n1': 147}
2018-01-01 21:39:11,256 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,260 : INFO : < 200 OK [3369]
2018-01-01 21:39:11,268 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 183, '_0n1': 299}
2018-01-01 21:39:11,268 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,276 : INFO : < 200 OK [3349]
2018-01-01 21:39:11,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 167, '_0n1': 308}
2018-01-01 21:39:11,292 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,296 : INFO : < 200 OK [3336]
2018-01-01 21:39:11,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 167, '_0n1': 11}
2018-01-01 21:39:11,304 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:11,308 : INFO : < 200 OK [3354]
2018-01-01 21:39:11,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 168, '_0n1': 212}
2018-01-01 21:39:11,320 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,324 : INFO : < 200 OK [3444]
2018-01-01 21:39:11,332 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 185, '_0n1': 469}
2018-01-01 21:39:11,338 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,343 : INFO : < 200 OK [3404]
2018-01-01 21:39:11,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 169, '_0n1': 287}
2018-01-01 21:39:11,351 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,355 : INFO : < 200 OK [3333]
2018-01-01 21:39:11,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 169, '_0n1': 220}
2018-01-01 21:39:11,363 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,367 : INFO : < 200 OK [3330]
2018-01-01 21:39:11,383 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 187, '_0n1': 408}
2018-01-01 21:39:11,383 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,387 : INFO : < 200 OK [3349]
2018-01-01 21:39:11,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 187, '_0n1': 190}
2018-01-01 21:39:11,399 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,403 : INFO : < 200 OK [3389]
2018-01-01 21:39:11,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 171, '_0n1': 135}
2018-01-01 21:39:11,411 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,415 : INFO : < 200 OK [3413]
2018-01-01 21:39:11,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 171, '_0n1': 407}
2018-01-01 21:39:11,419 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,423 : INFO : < 200 OK [3422]
2018-01-01 21:39:11,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 189, '_0n1': 188}
2018-01-01 21:39:11,449 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,452 : INFO : < 200 OK [3373]
2018-01-01 21:39:11,456 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 189, '_0n1': 96}
2018-01-01 21:39:11,460 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:11,464 : INFO : < 200 OK [3316]
2018-01-01 21:39:11,472 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 173, '_0n1': 164}
2018-01-01 21:39:11,472 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,476 : INFO : < 200 OK [3332]
2018-01-01 21:39:11,488 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 190, '_0n1': 187}
2018-01-01 21:39:11,488 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,496 : INFO : < 200 OK [3389]
2018-01-01 21:39:11,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 190, '_0n1': 160}
2018-01-01 21:39:11,504 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:11,508 : INFO : < 200 OK [3426]
2018-01-01 21:39:11,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 174, '_0n1': 60}
2018-01-01 21:39:11,516 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:11,520 : INFO : < 200 OK [3455]
2018-01-01 21:39:11,524 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 174, '_0n1': 565}
2018-01-01 21:39:11,528 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,532 : INFO : < 200 OK [3450]
2018-01-01 21:39:11,538 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 191, '_0n1': 430}
2018-01-01 21:39:11,540 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,544 : INFO : < 200 OK [3342]
2018-01-01 21:39:11,552 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 175, '_0n1': 60}
2018-01-01 21:39:11,552 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:11,556 : INFO : < 200 OK [3445]
2018-01-01 21:39:11,560 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 175, '_0n1': 587}
2018-01-01 21:39:11,564 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,568 : INFO : < 200 OK [3411]
2018-01-01 21:39:11,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 192, '_0n1': 92}
2018-01-01 21:39:11,580 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:11,584 : INFO : < 200 OK [3401]
2018-01-01 21:39:11,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 192, '_0n1': 217}
2018-01-01 21:39:11,592 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,596 : INFO : < 200 OK [3417]
2018-01-01 21:39:11,604 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 176, '_0n1': 340}
2018-01-01 21:39:11,604 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,608 : INFO : < 200 OK [3342]
2018-01-01 21:39:11,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 176, '_0n1': 212}
2018-01-01 21:39:11,620 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,624 : INFO : < 200 OK [3374]
2018-01-01 21:39:11,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 193, '_0n1': 187}
2018-01-01 21:39:11,637 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,643 : INFO : < 200 OK [3340]
2018-01-01 21:39:11,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 177, '_0n1': 164}
2018-01-01 21:39:11,652 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,656 : INFO : < 200 OK [3351]
2018-01-01 21:39:11,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 177, '_0n1': 273}
2018-01-01 21:39:11,668 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,672 : INFO : < 200 OK [3374]
2018-01-01 21:39:11,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 194, '_0n1': 203}
2018-01-01 21:39:11,684 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,688 : INFO : < 200 OK [3370]
2018-01-01 21:39:11,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 194, '_0n1': 197}
2018-01-01 21:39:11,696 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,700 : INFO : < 200 OK [3336]
2018-01-01 21:39:11,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 178, '_0n1': 104}
2018-01-01 21:39:11,708 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,712 : INFO : < 200 OK [3371]
2018-01-01 21:39:11,720 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 178, '_0n1': 291}
2018-01-01 21:39:11,724 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,728 : INFO : < 200 OK [3381]
2018-01-01 21:39:11,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 195, '_0n1': 419}
2018-01-01 21:39:11,737 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,741 : INFO : < 200 OK [3444]
2018-01-01 21:39:11,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 195, '_0n1': 129}
2018-01-01 21:39:11,746 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,750 : INFO : < 200 OK [3432]
2018-01-01 21:39:11,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 244}
2018-01-01 21:39:11,760 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,764 : INFO : < 200 OK [3364]
2018-01-01 21:39:11,768 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 374}
2018-01-01 21:39:11,768 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,772 : INFO : < 200 OK [3316]
2018-01-01 21:39:11,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 197, '_0n1': 194}
2018-01-01 21:39:11,788 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,792 : INFO : < 200 OK [3336]
2018-01-01 21:39:11,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 197, '_0n1': 203}
2018-01-01 21:39:11,800 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,804 : INFO : < 200 OK [3373]
2018-01-01 21:39:11,808 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 201, '_0n1': 1247}
2018-01-01 21:39:11,808 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:11,812 : INFO : < 200 OK [3390]
2018-01-01 21:39:11,820 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 201, '_0n1': 383}
2018-01-01 21:39:11,820 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,824 : INFO : < 200 OK [3361]

2018-01-01 21:39:11,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 198, '_0n1': 208}
2018-01-01 21:39:11,832 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,838 : INFO : < 200 OK [3428]
2018-01-01 21:39:11,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 198, '_0n1': 203}
2018-01-01 21:39:11,844 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,847 : INFO : < 200 OK [3422]
2018-01-01 21:39:11,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 199, '_0n1': 404}
2018-01-01 21:39:11,856 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,860 : INFO : < 200 OK [3352]
2018-01-01 21:39:11,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 199, '_0n1': 252}
2018-01-01 21:39:11,868 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,872 : INFO : < 200 OK [3402]
2018-01-01 21:39:11,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 203, '_0n1': 194}
2018-01-01 21:39:11,876 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,884 : INFO : < 200 OK [3370]
2018-01-01 21:39:11,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 203, '_0n1': 197}
2018-01-01 21:39:11,892 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,900 : INFO : < 200 OK [3373]
2018-01-01 21:39:11,904 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 200, '_0n1': 524}
2018-01-01 21:39:11,904 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,908 : INFO : < 200 OK [3389]
2018-01-01 21:39:11,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 200, '_0n1': 163}
2018-01-01 21:39:11,916 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,920 : INFO : < 200 OK [3387]
2018-01-01 21:39:11,924 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 204, '_0n1': 7}
2018-01-01 21:39:11,924 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:11,932 : INFO : < 200 OK [3359]
2018-01-01 21:39:11,936 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 204, '_0n1': 34}
2018-01-01 21:39:11,936 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:11,943 : INFO : < 200 OK [3377]
2018-01-01 21:39:11,948 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 221, '_0n1': 208}
2018-01-01 21:39:11,950 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,952 : INFO : < 200 OK [3364]
2018-01-01 21:39:11,956 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 221, '_0n1': 124}
2018-01-01 21:39:11,956 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,960 : INFO : < 200 OK [3352]
2018-01-01 21:39:11,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 222, '_0n1': 503}
2018-01-01 21:39:11,972 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,976 : INFO : < 200 OK [3345]
2018-01-01 21:39:11,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 222, '_0n1': 578}
2018-01-01 21:39:11,984 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:11,988 : INFO : < 200 OK [3389]
2018-01-01 21:39:11,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 206, '_0n1': 310}
2018-01-01 21:39:11,996 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,000 : INFO : < 200 OK [3380]
2018-01-01 21:39:12,008 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 206, '_0n1': 312}
2018-01-01 21:39:12,008 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,012 : INFO : < 200 OK [3407]
2018-01-01 21:39:12,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 223, '_0n1': 306}
2018-01-01 21:39:12,020 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,024 : INFO : < 200 OK [3317]
2018-01-01 21:39:12,028 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 223, '_0n1': 316}
2018-01-01 21:39:12,028 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,032 : INFO : < 200 OK [3316]
2018-01-01 21:39:12,064 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 244, '_0n1': 196}
2018-01-01 21:39:12,068 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,072 : INFO : < 200 OK [3364]
2018-01-01 21:39:12,088 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 245, '_0n1': 481}
2018-01-01 21:39:12,092 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,096 : INFO : < 200 OK [3410]
2018-01-01 21:39:12,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 245, '_0n1': 617}
2018-01-01 21:39:12,104 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,108 : INFO : < 200 OK [3442]
2018-01-01 21:39:12,112 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 210, '_0n1': 77}
2018-01-01 21:39:12,112 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:12,120 : INFO : < 200 OK [3427]
2018-01-01 21:39:12,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 210, '_0n1': 76}
2018-01-01 21:39:12,128 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:12,132 : INFO : < 200 OK [3381]
2018-01-01 21:39:12,141 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 246, '_0n1': 211}
2018-01-01 21:39:12,143 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,148 : INFO : < 200 OK [3452]
2018-01-01 21:39:12,153 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 246, '_0n1': 194}

2018-01-01 21:39:12,153 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,161 : INFO : < 200 OK [3378]
2018-01-01 21:39:12,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 211, '_0n1': 246}
2018-01-01 21:39:12,169 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,177 : INFO : < 200 OK [3452]
2018-01-01 21:39:12,181 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 211, '_0n1': 122}
2018-01-01 21:39:12,181 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,189 : INFO : < 200 OK [3412]
2018-01-01 21:39:12,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 247, '_0n1': 342}
2018-01-01 21:39:12,197 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,201 : INFO : < 200 OK [3376]
2018-01-01 21:39:12,205 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 247, '_0n1': 306}
2018-01-01 21:39:12,205 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,209 : INFO : < 200 OK [3368]
2018-01-01 21:39:12,217 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 212, '_0n1': 340}
2018-01-01 21:39:12,217 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,221 : INFO : < 200 OK [3401]
2018-01-01 21:39:12,225 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 212, '_0n1': 532}
2018-01-01 21:39:12,229 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,233 : INFO : < 200 OK [3396]
2018-01-01 21:39:12,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 248, '_0n1': 340}
2018-01-01 21:39:12,241 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,245 : INFO : < 200 OK [3387]
2018-01-01 21:39:12,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 213, '_0n1': 458}
2018-01-01 21:39:12,253 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,261 : INFO : < 200 OK [3371]
2018-01-01 21:39:12,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 213, '_0n1': 128}
2018-01-01 21:39:12,269 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,273 : INFO : < 200 OK [3408]
2018-01-01 21:39:12,277 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 249, '_0n1': 578}
2018-01-01 21:39:12,277 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,281 : INFO : < 200 OK [3424]
2018-01-01 21:39:12,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 249, '_0n1': 569}
2018-01-01 21:39:12,289 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,293 : INFO : < 200 OK [3416]
2018-01-01 21:39:12,297 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 214, '_0n1': 273}
2018-01-01 21:39:12,297 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,301 : INFO : < 200 OK [3367]
2018-01-01 21:39:12,305 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 214, '_0n1': 164}
2018-01-01 21:39:12,305 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,309 : INFO : < 200 OK [3344]
2018-01-01 21:39:12,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 250, '_0n1': 534}
2018-01-01 21:39:12,317 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,321 : INFO : < 200 OK [3379]
2018-01-01 21:39:12,325 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 250, '_0n1': 448}
2018-01-01 21:39:12,325 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,333 : INFO : < 200 OK [3362]
2018-01-01 21:39:12,340 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 215, '_0n1': 275}
2018-01-01 21:39:12,343 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,348 : INFO : < 200 OK [3342]
2018-01-01 21:39:12,353 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 215, '_0n1': 256}
2018-01-01 21:39:12,353 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,357 : INFO : < 200 OK [3325]
2018-01-01 21:39:12,361 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 251, '_0n1': 326}
2018-01-01 21:39:12,361 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,365 : INFO : < 200 OK [3395]
2018-01-01 21:39:12,373 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 251, '_0n1': 1247}
2018-01-01 21:39:12,373 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:12,377 : INFO : < 200 OK [3409]
2018-01-01 21:39:12,381 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 216, '_0n1': 194}
2018-01-01 21:39:12,385 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,389 : INFO : < 200 OK [3360]
2018-01-01 21:39:12,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 216, '_0n1': 270}
2018-01-01 21:39:12,393 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,397 : INFO : < 200 OK [3406]
2018-01-01 21:39:12,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 252, '_0n1': 404}
2018-01-01 21:39:12,405 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,409 : INFO : < 200 OK [3395]
2018-01-01 21:39:12,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 252, '_0n1': 459}
2018-01-01 21:39:12,417 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,421 : INFO : < 200 OK [3440]
2018-01-01 21:39:12,429 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 217, '_0n1': 275}
2018-01-01 21:39:12,429 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:12,433 : INFO : < 200 OK [3386]
2018-01-01 21:39:12,440 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 217, '_0n1': 255}
2018-01-01 21:39:12,442 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,446 : INFO : < 200 OK [3386]
2018-01-01 21:39:12,452 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 1247}
2018-01-01 21:39:12,452 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:12,456 : INFO : < 200 OK [3393]
2018-01-01 21:39:12,460 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 253, '_0n1': 201}
2018-01-01 21:39:12,460 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,464 : INFO : < 200 OK [3352]
2018-01-01 21:39:12,468 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 218, '_0n1': 217}
2018-01-01 21:39:12,472 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,476 : INFO : < 200 OK [3394]
2018-01-01 21:39:12,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 218, '_0n1': 215}
2018-01-01 21:39:12,480 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,484 : INFO : < 200 OK [3350]
2018-01-01 21:39:12,492 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 254, '_0n1': 252}
2018-01-01 21:39:12,492 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,496 : INFO : < 200 OK [3437]
2018-01-01 21:39:12,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 254, '_0n1': 404}
2018-01-01 21:39:12,504 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,508 : INFO : < 200 OK [3387]
2018-01-01 21:39:12,516 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 219, '_0n1': 523}
2018-01-01 21:39:12,516 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,528 : INFO : < 200 OK [3376]
2018-01-01 21:39:12,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 219, '_0n1': 252}
2018-01-01 21:39:12,539 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,543 : INFO : < 200 OK [3387]
2018-01-01 21:39:12,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 255, '_0n1': 217}
2018-01-01 21:39:12,551 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,557 : INFO : < 200 OK [3386]
2018-01-01 21:39:12,561 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 255, '_0n1': 565}
2018-01-01 21:39:12,561 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,569 : INFO : < 200 OK [3412]
2018-01-01 21:39:12,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 220, '_0n1': 282}
2018-01-01 21:39:12,573 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,581 : INFO : < 200 OK [3297]
2018-01-01 21:39:12,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 220, '_0n1': 287}
2018-01-01 21:39:12,589 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,593 : INFO : < 200 OK [3320]
2018-01-01 21:39:12,597 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 256, '_0n1': 282}
2018-01-01 21:39:12,597 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,605 : INFO : < 200 OK [3312]
2018-01-01 21:39:12,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 256, '_0n1': 220}
2018-01-01 21:39:12,613 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,621 : INFO : < 200 OK [3332]
2018-01-01 21:39:12,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 260, '_0n1': 96}
2018-01-01 21:39:12,629 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:12,633 : INFO : < 200 OK [3360]
2018-01-01 21:39:12,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 260, '_0n1': 291}
2018-01-01 21:39:12,643 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,647 : INFO : < 200 OK [3390]
2018-01-01 21:39:12,652 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 257, '_0n1': 259}
2018-01-01 21:39:12,652 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,656 : INFO : < 200 OK [3406]
2018-01-01 21:39:12,660 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 257, '_0n1': 438}
2018-01-01 21:39:12,660 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,664 : INFO : < 200 OK [3436]
2018-01-01 21:39:12,668 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 261, '_0n1': 345}
2018-01-01 21:39:12,672 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,676 : INFO : < 200 OK [3362]
2018-01-01 21:39:12,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 261, '_0n1': 352}
2018-01-01 21:39:12,680 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,684 : INFO : < 200 OK [3386]
2018-01-01 21:39:12,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 258, '_0n1': 319}
2018-01-01 21:39:12,692 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,700 : INFO : < 200 OK [3380]
2018-01-01 21:39:12,704 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 258, '_0n1': 336}
2018-01-01 21:39:12,708 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,712 : INFO : < 200 OK [3403]
2018-01-01 21:39:12,720 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 262, '_0n1': 589}
2018-01-01 21:39:12,720 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,728 : INFO : < 200 OK [3440]

2018-01-01 21:39:12,732 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 262, '_0n1': 71}
2018-01-01 21:39:12,732 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:12,742 : INFO : < 200 OK [3421]
2018-01-01 21:39:12,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 259, '_0n1': 257}
2018-01-01 21:39:12,749 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,753 : INFO : < 200 OK [3406]
2018-01-01 21:39:12,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 259, '_0n1': 443}
2018-01-01 21:39:12,761 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,765 : INFO : < 200 OK [3411]
2018-01-01 21:39:12,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 263, '_0n1': 90}
2018-01-01 21:39:12,773 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:12,777 : INFO : < 200 OK [3375]
2018-01-01 21:39:12,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 263, '_0n1': 76}
2018-01-01 21:39:12,785 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:12,793 : INFO : < 200 OK [3356]
2018-01-01 21:39:12,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 280, '_0n1': 346}
2018-01-01 21:39:12,801 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,805 : INFO : < 200 OK [3381]
2018-01-01 21:39:12,813 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 280, '_0n1': 286}
2018-01-01 21:39:12,813 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,817 : INFO : < 200 OK [3461]
2018-01-01 21:39:12,829 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 264, '_0n1': 280}
2018-01-01 21:39:12,829 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,833 : INFO : < 200 OK [3417]
2018-01-01 21:39:12,841 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 264, '_0n1': 131}
2018-01-01 21:39:12,842 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,848 : INFO : < 200 OK [3386]
2018-01-01 21:39:12,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 281, '_0n1': 381}
2018-01-01 21:39:12,857 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,865 : INFO : < 200 OK [3378]
2018-01-01 21:39:12,869 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 281, '_0n1': 401}
2018-01-01 21:39:12,873 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,877 : INFO : < 200 OK [3352]
2018-01-01 21:39:12,881 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 265, '_0n1': 271}
2018-01-01 21:39:12,885 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,889 : INFO : < 200 OK [3420]
2018-01-01 21:39:12,893 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 265, '_0n1': 83}
2018-01-01 21:39:12,893 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:12,897 : INFO : < 200 OK [3389]
2018-01-01 21:39:12,901 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 282, '_0n1': 220}
2018-01-01 21:39:12,905 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,909 : INFO : < 200 OK [3297]
2018-01-01 21:39:12,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 282, '_0n1': 287}
2018-01-01 21:39:12,913 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,917 : INFO : < 200 OK [3300]
2018-01-01 21:39:12,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 54}
2018-01-01 21:39:12,925 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:12,929 : INFO : < 200 OK [3374]
2018-01-01 21:39:12,933 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 560}
2018-01-01 21:39:12,933 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,940 : INFO : < 200 OK [3399]
2018-01-01 21:39:12,944 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 283, '_0n1': 287}
2018-01-01 21:39:12,946 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,952 : INFO : < 200 OK [3326]
2018-01-01 21:39:12,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 283, '_0n1': 220}
2018-01-01 21:39:12,957 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,961 : INFO : < 200 OK [3323]
2018-01-01 21:39:12,969 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 267, '_0n1': 201}
2018-01-01 21:39:12,969 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,977 : INFO : < 200 OK [3372]
2018-01-01 21:39:12,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 267, '_0n1': 436}
2018-01-01 21:39:12,985 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:12,993 : INFO : < 200 OK [3394]
2018-01-01 21:39:12,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 284, '_0n1': 272}
2018-01-01 21:39:13,001 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,005 : INFO : < 200 OK [3428]
2018-01-01 21:39:13,009 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 284, '_0n1': 484}
2018-01-01 21:39:13,009 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,017 : INFO : < 200 OK [3413]
2018-01-01 21:39:13,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 268, '_0n1': 287}
2018-01-01 21:39:13,025 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,029 : INFO : < 200 OK [3322]
2018-01-01 21:39:13,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 268, '_0n1': 220}

2018-01-01 21:39:13,037 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,041 : INFO : < 200 OK [3319]
2018-01-01 21:39:13,050 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 285, '_0n1': 414}
2018-01-01 21:39:13,053 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,057 : INFO : < 200 OK [3332]
2018-01-01 21:39:13,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 285, '_0n1': 551}
2018-01-01 21:39:13,065 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,069 : INFO : < 200 OK [3370]
2018-01-01 21:39:13,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 286, '_0n1': 280}
2018-01-01 21:39:13,089 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,093 : INFO : < 200 OK [3461]
2018-01-01 21:39:13,097 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 286, '_0n1': 261}
2018-01-01 21:39:13,101 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,105 : INFO : < 200 OK [3414]
2018-01-01 21:39:13,109 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 270, '_0n1': 333}
2018-01-01 21:39:13,113 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,117 : INFO : < 200 OK [3397]
2018-01-01 21:39:13,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 270, '_0n1': 136}
2018-01-01 21:39:13,125 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,129 : INFO : < 200 OK [3432]
2018-01-01 21:39:13,133 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 287, '_0n1': 220}
2018-01-01 21:39:13,133 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,139 : INFO : < 200 OK [3320]
2018-01-01 21:39:13,143 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 287, '_0n1': 268}
2018-01-01 21:39:13,144 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,149 : INFO : < 200 OK [3322]
2018-01-01 21:39:13,152 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 271, '_0n1': 265}
2018-01-01 21:39:13,152 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,157 : INFO : < 200 OK [3420]
2018-01-01 21:39:13,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 271, '_0n1': 81}
2018-01-01 21:39:13,161 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:13,165 : INFO : < 200 OK [3391]
2018-01-01 21:39:13,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 272, '_0n1': 284}
2018-01-01 21:39:13,173 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,177 : INFO : < 200 OK [3428]
2018-01-01 21:39:13,181 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 272, '_0n1': 484}
2018-01-01 21:39:13,181 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,189 : INFO : < 200 OK [3416]
2018-01-01 21:39:13,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 289, '_0n1': 519}
2018-01-01 21:39:13,197 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,205 : INFO : < 200 OK [3385]
2018-01-01 21:39:13,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 289, '_0n1': 345}
2018-01-01 21:39:13,213 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,217 : INFO : < 200 OK [3380]
2018-01-01 21:39:13,221 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 273, '_0n1': 164}
2018-01-01 21:39:13,221 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,225 : INFO : < 200 OK [3352]
2018-01-01 21:39:13,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 273, '_0n1': 214}
2018-01-01 21:39:13,233 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,239 : INFO : < 200 OK [3367]
2018-01-01 21:39:13,245 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 290, '_0n1': 353}
2018-01-01 21:39:13,247 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,251 : INFO : < 200 OK [3339]
2018-01-01 21:39:13,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 290, '_0n1': 162}
2018-01-01 21:39:13,257 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,261 : INFO : < 200 OK [3395]
2018-01-01 21:39:13,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 274, '_0n1': 31}
2018-01-01 21:39:13,265 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:13,269 : INFO : < 200 OK [3425]
2018-01-01 21:39:13,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 274, '_0n1': 614}
2018-01-01 21:39:13,277 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,281 : INFO : < 200 OK [3409]
2018-01-01 21:39:13,289 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 291, '_0n1': 503}
2018-01-01 21:39:13,289 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,293 : INFO : < 200 OK [3356]
2018-01-01 21:39:13,297 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 291, '_0n1': 578}
2018-01-01 21:39:13,301 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,305 : INFO : < 200 OK [3400]
2018-01-01 21:39:13,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 275, '_0n1': 217}
2018-01-01 21:39:13,313 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,317 : INFO : < 200 OK [3386]
2018-01-01 21:39:13,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 275, '_0n1': 215}
2018-01-01 21:39:13,325 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:13,329 : INFO : < 200 OK [3342]
2018-01-01 21:39:13,340 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 276, '_0n1': 298}
2018-01-01 21:39:13,341 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,345 : INFO : < 200 OK [3360]
2018-01-01 21:39:13,353 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 307}
2018-01-01 21:39:13,353 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,361 : INFO : < 200 OK [3403]
2018-01-01 21:39:13,365 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 604}
2018-01-01 21:39:13,369 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,373 : INFO : < 200 OK [3413]
2018-01-01 21:39:13,381 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 298}
2018-01-01 21:39:13,381 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,385 : INFO : < 200 OK [3421]
2018-01-01 21:39:13,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 303}
2018-01-01 21:39:13,393 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,397 : INFO : < 200 OK [3424]
2018-01-01 21:39:13,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 527}
2018-01-01 21:39:13,401 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,405 : INFO : < 200 OK [3399]
2018-01-01 21:39:13,409 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 503}
2018-01-01 21:39:13,409 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,413 : INFO : < 200 OK [3373]
2018-01-01 21:39:13,425 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 326}
2018-01-01 21:39:13,425 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,429 : INFO : < 200 OK [3403]
2018-01-01 21:39:13,433 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 325}
2018-01-01 21:39:13,437 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,443 : INFO : < 200 OK [3370]
2018-01-01 21:39:13,451 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 122}
2018-01-01 21:39:13,453 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,457 : INFO : < 200 OK [3356]
2018-01-01 21:39:13,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 96}
2018-01-01 21:39:13,461 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:13,469 : INFO : < 200 OK [3340]
2018-01-01 21:39:13,489 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 301, '_0n1': 150}
2018-01-01 21:39:13,493 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,497 : INFO : < 200 OK [3369]
2018-01-01 21:39:13,505 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 301, '_0n1': 303}
2018-01-01 21:39:13,505 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,513 : INFO : < 200 OK [3371]
2018-01-01 21:39:13,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 298, '_0n1': 303}
2018-01-01 21:39:13,517 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,521 : INFO : < 200 OK [3402]
2018-01-01 21:39:13,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 298, '_0n1': 276}
2018-01-01 21:39:13,525 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,533 : INFO : < 200 OK [3360]
2018-01-01 21:39:13,537 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 302, '_0n1': 522}
2018-01-01 21:39:13,539 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,543 : INFO : < 200 OK [3372]
2018-01-01 21:39:13,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 302, '_0n1': 310}
2018-01-01 21:39:13,549 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,553 : INFO : < 200 OK [3416]
2018-01-01 21:39:13,565 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 299, '_0n1': 500}
2018-01-01 21:39:13,565 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,569 : INFO : < 200 OK [3359]
2018-01-01 21:39:13,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 299, '_0n1': 103}
2018-01-01 21:39:13,577 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,581 : INFO : < 200 OK [3381]
2018-01-01 21:39:13,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 298}
2018-01-01 21:39:13,589 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,593 : INFO : < 200 OK [3402]
2018-01-01 21:39:13,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 304, '_0n1': 291}
2018-01-01 21:39:13,605 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,609 : INFO : < 200 OK [3349]
2018-01-01 21:39:13,613 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 304, '_0n1': 146}
2018-01-01 21:39:13,617 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,621 : INFO : < 200 OK [3347]
2018-01-01 21:39:13,633 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 321, '_0n1': 578}
2018-01-01 21:39:13,633 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,640 : INFO : < 200 OK [3430]
2018-01-01 21:39:13,646 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 312}
2018-01-01 21:39:13,648 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:13,653 : INFO : < 200 OK [3437]
2018-01-01 21:39:13,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 322, '_0n1': 614}
2018-01-01 21:39:13,665 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,669 : INFO : < 200 OK [3391]
2018-01-01 21:39:13,673 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 316}
2018-01-01 21:39:13,673 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,677 : INFO : < 200 OK [3364]
2018-01-01 21:39:13,681 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 333}
2018-01-01 21:39:13,681 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,685 : INFO : < 200 OK [3367]
2018-01-01 21:39:13,697 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 307, '_0n1': 293}
2018-01-01 21:39:13,697 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,701 : INFO : < 200 OK [3403]
2018-01-01 21:39:13,705 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 307, '_0n1': 589}
2018-01-01 21:39:13,705 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,717 : INFO : < 200 OK [3444]
2018-01-01 21:39:13,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 324, '_0n1': 335}
2018-01-01 21:39:13,739 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,743 : INFO : < 200 OK [3359]
2018-01-01 21:39:13,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 308, '_0n1': 278}
2018-01-01 21:39:13,750 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,753 : INFO : < 200 OK [3401]
2018-01-01 21:39:13,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 308, '_0n1': 167}
2018-01-01 21:39:13,757 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,761 : INFO : < 200 OK [3336]
2018-01-01 21:39:13,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 295}
2018-01-01 21:39:13,769 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,773 : INFO : < 200 OK [3370]
2018-01-01 21:39:13,777 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 326}
2018-01-01 21:39:13,777 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,785 : INFO : < 200 OK [3370]
2018-01-01 21:39:13,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 295}
2018-01-01 21:39:13,801 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,805 : INFO : < 200 OK [3403]
2018-01-01 21:39:13,809 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 325}
2018-01-01 21:39:13,809 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,817 : INFO : < 200 OK [3370]
2018-01-01 21:39:13,829 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 311, '_0n1': 158}
2018-01-01 21:39:13,833 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,839 : INFO : < 200 OK [3360]
2018-01-01 21:39:13,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 311, '_0n1': 139}
2018-01-01 21:39:13,847 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,851 : INFO : < 200 OK [3376]
2018-01-01 21:39:13,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 328, '_0n1': 125}
2018-01-01 21:39:13,865 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,869 : INFO : < 200 OK [3390]
2018-01-01 21:39:13,877 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 312, '_0n1': 305}
2018-01-01 21:39:13,877 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,881 : INFO : < 200 OK [3437]
2018-01-01 21:39:13,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 329, '_0n1': 61}
2018-01-01 21:39:13,889 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:13,893 : INFO : < 200 OK [3375]
2018-01-01 21:39:13,897 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 329, '_0n1': 1251}
2018-01-01 21:39:13,897 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:13,905 : INFO : < 200 OK [3440]
2018-01-01 21:39:13,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 330, '_0n1': 125}
2018-01-01 21:39:13,917 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,921 : INFO : < 200 OK [3390]
2018-01-01 21:39:13,942 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 331, '_0n1': 403}
2018-01-01 21:39:13,944 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,948 : INFO : < 200 OK [3420]
2018-01-01 21:39:13,953 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 315, '_0n1': 589}
2018-01-01 21:39:13,953 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,957 : INFO : < 200 OK [3400]
2018-01-01 21:39:13,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 315, '_0n1': 71}
2018-01-01 21:39:13,965 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:13,969 : INFO : < 200 OK [3381]
2018-01-01 21:39:13,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 316, '_0n1': 306}
2018-01-01 21:39:13,985 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:13,989 : INFO : < 200 OK [3364]
2018-01-01 21:39:13,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 316, '_0n1': 333}
2018-01-01 21:39:13,997 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,005 : INFO : < 200 OK [3366]

2018-01-01 21:39:14,009 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 333, '_0n1': 316}
2018-01-01 21:39:14,009 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,013 : INFO : < 200 OK [3366]
2018-01-01 21:39:14,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 333, '_0n1': 306}
2018-01-01 21:39:14,017 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,021 : INFO : < 200 OK [3367]
2018-01-01 21:39:14,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 317, '_0n1': 1251}
2018-01-01 21:39:14,029 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:14,033 : INFO : < 200 OK [3449]
2018-01-01 21:39:14,041 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 317, '_0n1': 1229}
2018-01-01 21:39:14,042 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:14,046 : INFO : < 200 OK [3459]
2018-01-01 21:39:14,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 334, '_0n1': 555}
2018-01-01 21:39:14,053 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,057 : INFO : < 200 OK [3351]
2018-01-01 21:39:14,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 318, '_0n1': 356}
2018-01-01 21:39:14,073 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,077 : INFO : < 200 OK [3346]
2018-01-01 21:39:14,081 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 324}
2018-01-01 21:39:14,085 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,089 : INFO : < 200 OK [3359]
2018-01-01 21:39:14,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 337}
2018-01-01 21:39:14,097 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,101 : INFO : < 200 OK [3365]
2018-01-01 21:39:14,109 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 319, '_0n1': 258}
2018-01-01 21:39:14,109 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,113 : INFO : < 200 OK [3380]
2018-01-01 21:39:14,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 336, '_0n1': 258}
2018-01-01 21:39:14,121 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,125 : INFO : < 200 OK [3403]
2018-01-01 21:39:14,133 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 212}
2018-01-01 21:39:14,133 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,137 : INFO : < 200 OK [3401]
2018-01-01 21:39:14,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 532}
2018-01-01 21:39:14,149 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,153 : INFO : < 200 OK [3364]
2018-01-01 21:39:14,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 337, '_0n1': 328}
2018-01-01 21:39:14,161 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,165 : INFO : < 200 OK [3373]
2018-01-01 21:39:14,173 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 337, '_0n1': 315}
2018-01-01 21:39:14,173 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,177 : INFO : < 200 OK [3344]
2018-01-01 21:39:14,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 341, '_0n1': 555}
2018-01-01 21:39:14,189 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,193 : INFO : < 200 OK [3347]
2018-01-01 21:39:14,201 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 341, '_0n1': 603}
2018-01-01 21:39:14,201 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,209 : INFO : < 200 OK [3384]
2018-01-01 21:39:14,221 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 338, '_0n1': 444}
2018-01-01 21:39:14,221 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,225 : INFO : < 200 OK [3378]
2018-01-01 21:39:14,238 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 338, '_0n1': 0}
2018-01-01 21:39:14,239 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:14,244 : INFO : < 200 OK [3323]
2018-01-01 21:39:14,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 342, '_0n1': 172}
2018-01-01 21:39:14,258 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,262 : INFO : < 200 OK [3376]
2018-01-01 21:39:14,270 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 339, '_0n1': 415}
2018-01-01 21:39:14,274 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,278 : INFO : < 200 OK [3323]
2018-01-01 21:39:14,282 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 339, '_0n1': 305}
2018-01-01 21:39:14,286 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,290 : INFO : < 200 OK [3363]
2018-01-01 21:39:14,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 166}
2018-01-01 21:39:14,298 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,302 : INFO : < 200 OK [3410]
2018-01-01 21:39:14,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 293}
2018-01-01 21:39:14,310 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,314 : INFO : < 200 OK [3404]
2018-01-01 21:39:14,344 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 345, '_0n1': 261}
2018-01-01 21:39:14,349 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,354 : INFO : < 200 OK [3362]
2018-01-01 21:39:14,362 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 345, '_0n1': 364}

2018-01-01 21:39:14,364 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,370 : INFO : < 200 OK [3375]
2018-01-01 21:39:14,399 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 347, '_0n1': 358}
2018-01-01 21:39:14,401 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,405 : INFO : < 200 OK [3323]
2018-01-01 21:39:14,412 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 347, '_0n1': 473}
2018-01-01 21:39:14,413 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,418 : INFO : < 200 OK [3357]
2018-01-01 21:39:14,433 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 348, '_0n1': 429}
2018-01-01 21:39:14,436 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,444 : INFO : < 200 OK [3368]
2018-01-01 21:39:14,451 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 348, '_0n1': 514}
2018-01-01 21:39:14,454 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,458 : INFO : < 200 OK [3337]
2018-01-01 21:39:14,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 182}
2018-01-01 21:39:14,482 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,487 : INFO : < 200 OK [3324]
2018-01-01 21:39:14,495 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 531}
2018-01-01 21:39:14,497 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,502 : INFO : < 200 OK [3368]
2018-01-01 21:39:14,508 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 350, '_0n1': 365}
2018-01-01 21:39:14,510 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,516 : INFO : < 200 OK [3401]
2018-01-01 21:39:14,520 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 350, '_0n1': 108}
2018-01-01 21:39:14,522 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,526 : INFO : < 200 OK [3420]
2018-01-01 21:39:14,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 367, '_0n1': 522}
2018-01-01 21:39:14,534 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,539 : INFO : < 200 OK [3358]
2018-01-01 21:39:14,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 367, '_0n1': 353}
2018-01-01 21:39:14,545 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,549 : INFO : < 200 OK [3355]
2018-01-01 21:39:14,560 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 516}
2018-01-01 21:39:14,565 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,575 : INFO : < 200 OK [3355]
2018-01-01 21:39:14,581 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 368, '_0n1': 370}
2018-01-01 21:39:14,583 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,588 : INFO : < 200 OK [3422]
2018-01-01 21:39:14,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 368, '_0n1': 578}
2018-01-01 21:39:14,595 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,599 : INFO : < 200 OK [3436]
2018-01-01 21:39:14,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 352, '_0n1': 261}
2018-01-01 21:39:14,608 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,612 : INFO : < 200 OK [3386]
2018-01-01 21:39:14,618 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 352, '_0n1': 345}
2018-01-01 21:39:14,620 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,624 : INFO : < 200 OK [3393]
2018-01-01 21:39:14,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 369, '_0n1': 372}
2018-01-01 21:39:14,630 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,635 : INFO : < 200 OK [3437]
2018-01-01 21:39:14,640 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 369, '_0n1': 290}
2018-01-01 21:39:14,642 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,646 : INFO : < 200 OK [3428]
2018-01-01 21:39:14,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 353, '_0n1': 290}
2018-01-01 21:39:14,655 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,662 : INFO : < 200 OK [3339]
2018-01-01 21:39:14,670 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 353, '_0n1': 162}
2018-01-01 21:39:14,672 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,676 : INFO : < 200 OK [3379]
2018-01-01 21:39:14,684 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 370, '_0n1': 368}
2018-01-01 21:39:14,686 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,690 : INFO : < 200 OK [3422]
2018-01-01 21:39:14,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 370, '_0n1': 503}
2018-01-01 21:39:14,698 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,703 : INFO : < 200 OK [3371]
2018-01-01 21:39:14,710 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 354, '_0n1': 161}
2018-01-01 21:39:14,711 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,716 : INFO : < 200 OK [3406]
2018-01-01 21:39:14,719 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 354, '_0n1': 251}
2018-01-01 21:39:14,721 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,726 : INFO : < 200 OK [3397]
2018-01-01 21:39:14,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 355, '_0n1': 437}
2018-01-01 21:39:14,749 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:14,753 : INFO : < 200 OK [3336]
2018-01-01 21:39:14,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 372, '_0n1': 503}
2018-01-01 21:39:14,760 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,765 : INFO : < 200 OK [3357]
2018-01-01 21:39:14,770 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 372, '_0n1': 578}
2018-01-01 21:39:14,772 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,777 : INFO : < 200 OK [3401]
2018-01-01 21:39:14,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 356, '_0n1': 602}
2018-01-01 21:39:14,786 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,790 : INFO : < 200 OK [3326]
2018-01-01 21:39:14,795 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 356, '_0n1': 318}
2018-01-01 21:39:14,797 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,801 : INFO : < 200 OK [3346]
2018-01-01 21:39:14,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 373, '_0n1': 425}
2018-01-01 21:39:14,818 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,827 : INFO : < 200 OK [3406]
2018-01-01 21:39:14,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 373, '_0n1': 519}
2018-01-01 21:39:14,835 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,840 : INFO : < 200 OK [3415]
2018-01-01 21:39:14,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 357, '_0n1': 44}
2018-01-01 21:39:14,847 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:14,851 : INFO : < 200 OK [3427]
2018-01-01 21:39:14,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 357, '_0n1': 39}
2018-01-01 21:39:14,858 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:14,862 : INFO : < 200 OK [3461]
2018-01-01 21:39:14,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 427}
2018-01-01 21:39:14,876 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,881 : INFO : < 200 OK [3337]
2018-01-01 21:39:14,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 358, '_0n1': 473}
2018-01-01 21:39:14,888 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,892 : INFO : < 200 OK [3345]
2018-01-01 21:39:14,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 358, '_0n1': 347}
2018-01-01 21:39:14,897 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,902 : INFO : < 200 OK [3323]
2018-01-01 21:39:14,910 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 375, '_0n1': 408}
2018-01-01 21:39:14,912 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,916 : INFO : < 200 OK [3389]
2018-01-01 21:39:14,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 375, '_0n1': 440}
2018-01-01 21:39:14,926 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,932 : INFO : < 200 OK [3387]
2018-01-01 21:39:14,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 359, '_0n1': 464}
2018-01-01 21:39:14,940 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,944 : INFO : < 200 OK [3386]
2018-01-01 21:39:14,948 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 359, '_0n1': 291}
2018-01-01 21:39:14,950 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,954 : INFO : < 200 OK [3361]
2018-01-01 21:39:14,963 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 67}
2018-01-01 21:39:14,965 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:14,969 : INFO : < 200 OK [3437]
2018-01-01 21:39:14,976 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 66}
2018-01-01 21:39:14,977 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:14,982 : INFO : < 200 OK [3388]
2018-01-01 21:39:14,992 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 380, '_0n1': 417}
2018-01-01 21:39:14,994 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:14,998 : INFO : < 200 OK [3397]
2018-01-01 21:39:15,007 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 523}
2018-01-01 21:39:15,009 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,013 : INFO : < 200 OK [3442]
2018-01-01 21:39:15,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 10}
2018-01-01 21:39:15,023 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:15,027 : INFO : < 200 OK [3425]
2018-01-01 21:39:15,036 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 381, '_0n1': 401}
2018-01-01 21:39:15,039 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,043 : INFO : < 200 OK [3385]
2018-01-01 21:39:15,048 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 381, '_0n1': 365}
2018-01-01 21:39:15,050 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,055 : INFO : < 200 OK [3397]
2018-01-01 21:39:15,062 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 378, '_0n1': 379}
2018-01-01 21:39:15,064 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,068 : INFO : < 200 OK [3337]
2018-01-01 21:39:15,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 378, '_0n1': 437}
2018-01-01 21:39:15,076 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:15,081 : INFO : < 200 OK [3327]
2018-01-01 21:39:15,088 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 382, '_0n1': 66}
2018-01-01 21:39:15,091 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:15,095 : INFO : < 200 OK [3385]
2018-01-01 21:39:15,099 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 382, '_0n1': 219}
2018-01-01 21:39:15,101 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,105 : INFO : < 200 OK [3359]
2018-01-01 21:39:15,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 379, '_0n1': 405}
2018-01-01 21:39:15,115 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,119 : INFO : < 200 OK [3388]
2018-01-01 21:39:15,126 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 379, '_0n1': 417}
2018-01-01 21:39:15,127 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,132 : INFO : < 200 OK [3378]
2018-01-01 21:39:15,138 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1247}
2018-01-01 21:39:15,140 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:15,144 : INFO : < 200 OK [3402]
2018-01-01 21:39:15,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 201}
2018-01-01 21:39:15,155 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,160 : INFO : < 200 OK [3361]
2018-01-01 21:39:15,165 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 570}
2018-01-01 21:39:15,168 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,172 : INFO : < 200 OK [3398]
2018-01-01 21:39:15,176 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 502}
2018-01-01 21:39:15,178 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,183 : INFO : < 200 OK [3386]
2018-01-01 21:39:15,190 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 384, '_0n1': 66}
2018-01-01 21:39:15,191 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:15,196 : INFO : < 200 OK [3385]
2018-01-01 21:39:15,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 384, '_0n1': 417}
2018-01-01 21:39:15,203 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,207 : INFO : < 200 OK [3401]
2018-01-01 21:39:15,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 401, '_0n1': 486}
2018-01-01 21:39:15,217 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,222 : INFO : < 200 OK [3350]
2018-01-01 21:39:15,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 401, '_0n1': 381}
2018-01-01 21:39:15,230 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,235 : INFO : < 200 OK [3385]
2018-01-01 21:39:15,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 385, '_0n1': 1251}
2018-01-01 21:39:15,248 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:15,253 : INFO : < 200 OK [3469]
2018-01-01 21:39:15,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 402, '_0n1': 405}
2018-01-01 21:39:15,266 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,274 : INFO : < 200 OK [3386]
2018-01-01 21:39:15,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 386, '_0n1': 424}
2018-01-01 21:39:15,285 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,290 : INFO : < 200 OK [3366]
2018-01-01 21:39:15,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 386, '_0n1': 464}
2018-01-01 21:39:15,300 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,304 : INFO : < 200 OK [3375]
2018-01-01 21:39:15,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 403, '_0n1': 126}
2018-01-01 21:39:15,317 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,321 : INFO : < 200 OK [3464]
2018-01-01 21:39:15,329 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 387, '_0n1': 405}
2018-01-01 21:39:15,331 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,336 : INFO : < 200 OK [3461]
2018-01-01 21:39:15,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 387, '_0n1': 380}
2018-01-01 21:39:15,345 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,349 : INFO : < 200 OK [3435]
2018-01-01 21:39:15,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 404, '_0n1': 252}
2018-01-01 21:39:15,360 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,370 : INFO : < 200 OK [3395]
2018-01-01 21:39:15,379 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 404, '_0n1': 459}
2018-01-01 21:39:15,381 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,387 : INFO : < 200 OK [3390]
2018-01-01 21:39:15,399 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 379}
2018-01-01 21:39:15,401 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,406 : INFO : < 200 OK [3388]
2018-01-01 21:39:15,412 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 402}
2018-01-01 21:39:15,414 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,418 : INFO : < 200 OK [3386]
2018-01-01 21:39:15,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 398}
2018-01-01 21:39:15,428 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,433 : INFO : < 200 OK [3410]

2018-01-01 21:39:15,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 436}
2018-01-01 21:39:15,440 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,444 : INFO : < 200 OK [3396]
2018-01-01 21:39:15,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 390, '_0n1': 358}
2018-01-01 21:39:15,459 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,466 : INFO : < 200 OK [3339]
2018-01-01 21:39:15,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 391, '_0n1': 314}
2018-01-01 21:39:15,487 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,492 : INFO : < 200 OK [3358]
2018-01-01 21:39:15,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 391, '_0n1': 187}
2018-01-01 21:39:15,502 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,507 : INFO : < 200 OK [3345]
2018-01-01 21:39:15,514 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 408, '_0n1': 187}
2018-01-01 21:39:15,515 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,517 : INFO : < 200 OK [3349]
2018-01-01 21:39:15,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 408, '_0n1': 440}
2018-01-01 21:39:15,525 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,529 : INFO : < 200 OK [3365]
2018-01-01 21:39:15,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 64}
2018-01-01 21:39:15,533 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:15,537 : INFO : < 200 OK [3307]
2018-01-01 21:39:15,545 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 548}
2018-01-01 21:39:15,545 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,549 : INFO : < 200 OK [3319]
2018-01-01 21:39:15,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 414, '_0n1': 340}
2018-01-01 21:39:15,612 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,617 : INFO : < 200 OK [3327]
2018-01-01 21:39:15,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 414, '_0n1': 285}
2018-01-01 21:39:15,629 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,633 : INFO : < 200 OK [3332]
2018-01-01 21:39:15,637 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 398, '_0n1': 530}
2018-01-01 21:39:15,641 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,645 : INFO : < 200 OK [3369]
2018-01-01 21:39:15,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 398, '_0n1': 436}
2018-01-01 21:39:15,649 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,653 : INFO : < 200 OK [3407]
2018-01-01 21:39:15,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 399, '_0n1': 529}
2018-01-01 21:39:15,669 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,673 : INFO : < 200 OK [3402]
2018-01-01 21:39:15,685 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 416, '_0n1': 549}
2018-01-01 21:39:15,685 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,689 : INFO : < 200 OK [3395]
2018-01-01 21:39:15,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 416, '_0n1': 426}
2018-01-01 21:39:15,697 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,701 : INFO : < 200 OK [3328]
2018-01-01 21:39:15,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 417, '_0n1': 379}
2018-01-01 21:39:15,713 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,717 : INFO : < 200 OK [3378]
2018-01-01 21:39:15,725 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 417, '_0n1': 66}
2018-01-01 21:39:15,725 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:15,733 : INFO : < 200 OK [3397]
2018-01-01 21:39:15,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 422, '_0n1': 425}
2018-01-01 21:39:15,749 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,753 : INFO : < 200 OK [3376]
2018-01-01 21:39:15,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 422, '_0n1': 454}
2018-01-01 21:39:15,761 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,765 : INFO : < 200 OK [3410]
2018-01-01 21:39:15,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 361}
2018-01-01 21:39:15,773 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,777 : INFO : < 200 OK [3366]
2018-01-01 21:39:15,785 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 360}
2018-01-01 21:39:15,785 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,789 : INFO : < 200 OK [3387]
2018-01-01 21:39:15,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 423, '_0n1': 429}
2018-01-01 21:39:15,797 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,803 : INFO : < 200 OK [3399]
2018-01-01 21:39:15,808 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 423, '_0n1': 469}
2018-01-01 21:39:15,809 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,813 : INFO : < 200 OK [3406]
2018-01-01 21:39:15,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 440, '_0n1': 408}
2018-01-01 21:39:15,821 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,825 : INFO : < 200 OK [3365]
2018-01-01 21:39:15,829 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 440, '_0n1': 184}

2018-01-01 21:39:15,829 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,833 : INFO : < 200 OK [3364]
2018-01-01 21:39:15,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 424, '_0n1': 386}
2018-01-01 21:39:15,845 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,853 : INFO : < 200 OK [3366]
2018-01-01 21:39:15,857 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 424, '_0n1': 142}
2018-01-01 21:39:15,861 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,865 : INFO : < 200 OK [3417]
2018-01-01 21:39:15,873 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 558}
2018-01-01 21:39:15,873 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,877 : INFO : < 200 OK [3392]
2018-01-01 21:39:15,881 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 398}
2018-01-01 21:39:15,881 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,885 : INFO : < 200 OK [3408]
2018-01-01 21:39:15,893 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 425, '_0n1': 373}
2018-01-01 21:39:15,893 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,897 : INFO : < 200 OK [3406]
2018-01-01 21:39:15,904 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 425, '_0n1': 519}
2018-01-01 21:39:15,906 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,910 : INFO : < 200 OK [3370]
2018-01-01 21:39:15,917 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 442, '_0n1': 475}
2018-01-01 21:39:15,917 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,921 : INFO : < 200 OK [3357]
2018-01-01 21:39:15,933 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 426, '_0n1': 538}
2018-01-01 21:39:15,937 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,941 : INFO : < 200 OK [3337]
2018-01-01 21:39:15,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 431}
2018-01-01 21:39:15,945 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,953 : INFO : < 200 OK [3378]
2018-01-01 21:39:15,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 2}
2018-01-01 21:39:15,957 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:15,965 : INFO : < 200 OK [3407]
2018-01-01 21:39:15,969 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 427, '_0n1': 373}
2018-01-01 21:39:15,969 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,973 : INFO : < 200 OK [3397]
2018-01-01 21:39:15,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 427, '_0n1': 425}
2018-01-01 21:39:15,981 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:15,989 : INFO : < 200 OK [3352]
2018-01-01 21:39:16,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 428, '_0n1': 201}
2018-01-01 21:39:16,007 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,012 : INFO : < 200 OK [3342]
2018-01-01 21:39:16,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 428, '_0n1': 1247}
2018-01-01 21:39:16,017 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:16,021 : INFO : < 200 OK [3383]
2018-01-01 21:39:16,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 445, '_0n1': 425}
2018-01-01 21:39:16,029 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,033 : INFO : < 200 OK [3387]
2018-01-01 21:39:16,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 429, '_0n1': 348}
2018-01-01 21:39:16,049 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,053 : INFO : < 200 OK [3368]
2018-01-01 21:39:16,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 446, '_0n1': 604}
2018-01-01 21:39:16,061 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,065 : INFO : < 200 OK [3436]
2018-01-01 21:39:16,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 430, '_0n1': 191}
2018-01-01 21:39:16,077 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,081 : INFO : < 200 OK [3342]
2018-01-01 21:39:16,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 430, '_0n1': 354}
2018-01-01 21:39:16,085 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,089 : INFO : < 200 OK [3391]
2018-01-01 21:39:16,097 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 447, '_0n1': 38}
2018-01-01 21:39:16,097 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:16,103 : INFO : < 200 OK [3415]
2018-01-01 21:39:16,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 447, '_0n1': 438}
2018-01-01 21:39:16,109 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,115 : INFO : < 200 OK [3432]
2018-01-01 21:39:16,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 443}
2018-01-01 21:39:16,121 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,125 : INFO : < 200 OK [3378]
2018-01-01 21:39:16,129 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 533}
2018-01-01 21:39:16,133 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,137 : INFO : < 200 OK [3339]
2018-01-01 21:39:16,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 432, '_0n1': 177}
2018-01-01 21:39:16,149 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:16,153 : INFO : < 200 OK [3368]
2018-01-01 21:39:16,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 432, '_0n1': 58}
2018-01-01 21:39:16,161 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:16,165 : INFO : < 200 OK [3388]
2018-01-01 21:39:16,173 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 449, '_0n1': 260}
2018-01-01 21:39:16,177 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,181 : INFO : < 200 OK [3383]
2018-01-01 21:39:16,209 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 451, '_0n1': 519}
2018-01-01 21:39:16,211 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,216 : INFO : < 200 OK [3324]
2018-01-01 21:39:16,221 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 451, '_0n1': 506}
2018-01-01 21:39:16,221 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,225 : INFO : < 200 OK [3312]
2018-01-01 21:39:16,237 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 452, '_0n1': 2}
2018-01-01 21:39:16,241 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2018-01-01 21:39:16,245 : INFO : < 200 OK [3388]
2018-01-01 21:39:16,249 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 436, '_0n1': 398}
2018-01-01 21:39:16,253 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,257 : INFO : < 200 OK [3407]
2018-01-01 21:39:16,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 436, '_0n1': 441}
2018-01-01 21:39:16,261 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,269 : INFO : < 200 OK [3394]
2018-01-01 21:39:16,277 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 213}
2018-01-01 21:39:16,281 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,285 : INFO : < 200 OK [3419]
2018-01-01 21:39:16,293 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 437, '_0n1': 355}
2018-01-01 21:39:16,293 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,297 : INFO : < 200 OK [3336]
2018-01-01 21:39:16,305 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 437, '_0n1': 378}
2018-01-01 21:39:16,307 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,311 : INFO : < 200 OK [3327]
2018-01-01 21:39:16,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 438, '_0n1': 77}
2018-01-01 21:39:16,321 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:16,329 : INFO : < 200 OK [3442]
2018-01-01 21:39:16,333 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 438, '_0n1': 58}
2018-01-01 21:39:16,337 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:16,341 : INFO : < 200 OK [3425]
2018-01-01 21:39:16,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 455, '_0n1': 468}
2018-01-01 21:39:16,345 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,349 : INFO : < 200 OK [3328]
2018-01-01 21:39:16,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 455, '_0n1': 440}
2018-01-01 21:39:16,357 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,361 : INFO : < 200 OK [3341]
2018-01-01 21:39:16,365 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 439, '_0n1': 356}
2018-01-01 21:39:16,369 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,373 : INFO : < 200 OK [3368]
2018-01-01 21:39:16,377 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 439, '_0n1': 512}
2018-01-01 21:39:16,377 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,381 : INFO : < 200 OK [3381]
2018-01-01 21:39:16,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 456, '_0n1': 513}
2018-01-01 21:39:16,389 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,397 : INFO : < 200 OK [3399]
2018-01-01 21:39:16,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 456, '_0n1': 516}
2018-01-01 21:39:16,405 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,410 : INFO : < 200 OK [3385]
2018-01-01 21:39:16,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 460, '_0n1': 451}
2018-01-01 21:39:16,417 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,418 : INFO : < 200 OK [3301]
2018-01-01 21:39:16,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 561}
2018-01-01 21:39:16,430 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,434 : INFO : < 200 OK [3399]
2018-01-01 21:39:16,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 415}
2018-01-01 21:39:16,438 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,446 : INFO : < 200 OK [3350]
2018-01-01 21:39:16,450 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 461, '_0n1': 549}
2018-01-01 21:39:16,454 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,458 : INFO : < 200 OK [3367]
2018-01-01 21:39:16,466 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 461, '_0n1': 80}
2018-01-01 21:39:16,466 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:16,470 : INFO : < 200 OK [3349]
2018-01-01 21:39:16,478 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 458, '_0n1': 213}
2018-01-01 21:39:16,478 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,486 : INFO : < 200 OK [3371]

2018-01-01 21:39:16,490 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 458, '_0n1': 128}
2018-01-01 21:39:16,490 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,498 : INFO : < 200 OK [3402]
2018-01-01 21:39:16,506 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 462, '_0n1': 348}
2018-01-01 21:39:16,508 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,512 : INFO : < 200 OK [3365]
2018-01-01 21:39:16,518 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 459, '_0n1': 252}
2018-01-01 21:39:16,518 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,522 : INFO : < 200 OK [3440]
2018-01-01 21:39:16,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 459, '_0n1': 404}
2018-01-01 21:39:16,530 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,534 : INFO : < 200 OK [3390]
2018-01-01 21:39:16,542 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 213}
2018-01-01 21:39:16,542 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,546 : INFO : < 200 OK [3378]
2018-01-01 21:39:16,550 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 431}
2018-01-01 21:39:16,554 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,558 : INFO : < 200 OK [3345]
2018-01-01 21:39:16,566 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 480, '_0n1': 360}
2018-01-01 21:39:16,570 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,578 : INFO : < 200 OK [3380]
2018-01-01 21:39:16,586 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 464, '_0n1': 500}
2018-01-01 21:39:16,586 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,590 : INFO : < 200 OK [3382]
2018-01-01 21:39:16,598 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 464, '_0n1': 386}
2018-01-01 21:39:16,598 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,605 : INFO : < 200 OK [3375]
2018-01-01 21:39:16,610 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 481, '_0n1': 523}
2018-01-01 21:39:16,612 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,616 : INFO : < 200 OK [3379]
2018-01-01 21:39:16,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 482, '_0n1': 354}
2018-01-01 21:39:16,629 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,637 : INFO : < 200 OK [3368]
2018-01-01 21:39:16,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 466, '_0n1': 618}
2018-01-01 21:39:16,641 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,649 : INFO : < 200 OK [3367]
2018-01-01 21:39:16,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 466, '_0n1': 93}
2018-01-01 21:39:16,657 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:16,661 : INFO : < 200 OK [3337]
2018-01-01 21:39:16,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 561}
2018-01-01 21:39:16,669 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,673 : INFO : < 200 OK [3406]
2018-01-01 21:39:16,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 560}
2018-01-01 21:39:16,681 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,685 : INFO : < 200 OK [3398]
2018-01-01 21:39:16,697 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 484, '_0n1': 122}
2018-01-01 21:39:16,697 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,701 : INFO : < 200 OK [3372]
2018-01-01 21:39:16,707 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 484, '_0n1': 53}
2018-01-01 21:39:16,710 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:16,715 : INFO : < 200 OK [3372]
2018-01-01 21:39:16,722 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 468, '_0n1': 96}
2018-01-01 21:39:16,726 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:16,730 : INFO : < 200 OK [3324]
2018-01-01 21:39:16,738 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 485, '_0n1': 252}
2018-01-01 21:39:16,738 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,742 : INFO : < 200 OK [3450]
2018-01-01 21:39:16,750 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 469, '_0n1': 133}
2018-01-01 21:39:16,754 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,758 : INFO : < 200 OK [3401]
2018-01-01 21:39:16,762 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 486, '_0n1': 401}
2018-01-01 21:39:16,766 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,770 : INFO : < 200 OK [3350]
2018-01-01 21:39:16,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 500, '_0n1': 299}
2018-01-01 21:39:16,786 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,790 : INFO : < 200 OK [3359]
2018-01-01 21:39:16,794 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 500, '_0n1': 464}
2018-01-01 21:39:16,798 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,804 : INFO : < 200 OK [3382]
2018-01-01 21:39:16,808 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 471, '_0n1': 213}
2018-01-01 21:39:16,810 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,813 : INFO : < 200 OK [3382]
2018-01-01 21:39:16,818 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 471, '_0n1': 515}

2018-01-01 21:39:16,818 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,822 : INFO : < 200 OK [3365]
2018-01-01 21:39:16,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 501, '_0n1': 353}
2018-01-01 21:39:16,830 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,834 : INFO : < 200 OK [3363]
2018-01-01 21:39:16,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 501, '_0n1': 345}
2018-01-01 21:39:16,842 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,846 : INFO : < 200 OK [3386]
2018-01-01 21:39:16,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 472, '_0n1': 537}
2018-01-01 21:39:16,854 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,862 : INFO : < 200 OK [3319]
2018-01-01 21:39:16,866 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 472, '_0n1': 437}
2018-01-01 21:39:16,866 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,874 : INFO : < 200 OK [3321]
2018-01-01 21:39:16,878 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 502, '_0n1': 400}
2018-01-01 21:39:16,878 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,882 : INFO : < 200 OK [3386]
2018-01-01 21:39:16,890 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 502, '_0n1': 529}
2018-01-01 21:39:16,890 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,894 : INFO : < 200 OK [3399]
2018-01-01 21:39:16,898 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 473, '_0n1': 358}
2018-01-01 21:39:16,898 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,906 : INFO : < 200 OK [3345]
2018-01-01 21:39:16,911 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 473, '_0n1': 347}
2018-01-01 21:39:16,912 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,916 : INFO : < 200 OK [3357]
2018-01-01 21:39:16,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 503, '_0n1': 578}
2018-01-01 21:39:16,922 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,926 : INFO : < 200 OK [3385]
2018-01-01 21:39:16,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 503, '_0n1': 1260}
2018-01-01 21:39:16,938 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:16,942 : INFO : < 200 OK [3358]
2018-01-01 21:39:16,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 474, '_0n1': 537}
2018-01-01 21:39:16,950 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,954 : INFO : < 200 OK [3369]
2018-01-01 21:39:16,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 474, '_0n1': 313}
2018-01-01 21:39:16,958 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,966 : INFO : < 200 OK [3386]
2018-01-01 21:39:16,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 504, '_0n1': 66}
2018-01-01 21:39:16,974 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:16,978 : INFO : < 200 OK [3364]
2018-01-01 21:39:16,986 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 475, '_0n1': 371}
2018-01-01 21:39:16,986 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:16,994 : INFO : < 200 OK [3351]
2018-01-01 21:39:16,998 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 505, '_0n1': 386}
2018-01-01 21:39:17,002 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,008 : INFO : < 200 OK [3371]
2018-01-01 21:39:17,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 505, '_0n1': 424}
2018-01-01 21:39:17,016 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,018 : INFO : < 200 OK [3408]
2018-01-01 21:39:17,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 476, '_0n1': 426}
2018-01-01 21:39:17,030 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,034 : INFO : < 200 OK [3315]
2018-01-01 21:39:17,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 506, '_0n1': 451}
2018-01-01 21:39:17,042 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,046 : INFO : < 200 OK [3312]
2018-01-01 21:39:17,050 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 506, '_0n1': 460}
2018-01-01 21:39:17,054 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,058 : INFO : < 200 OK [3344]
2018-01-01 21:39:17,070 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 507, '_0n1': 604}
2018-01-01 21:39:17,070 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,074 : INFO : < 200 OK [3445]
2018-01-01 21:39:17,078 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 507, '_0n1': 166}
2018-01-01 21:39:17,082 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,086 : INFO : < 200 OK [3425]
2018-01-01 21:39:17,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 513}
2018-01-01 21:39:17,098 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,106 : INFO : < 200 OK [3411]
2018-01-01 21:39:17,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 309}
2018-01-01 21:39:17,113 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,117 : INFO : < 200 OK [3366]
2018-01-01 21:39:17,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 479, '_0n1': 252}
2018-01-01 21:39:17,122 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:17,126 : INFO : < 200 OK [3425]
2018-01-01 21:39:17,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 479, '_0n1': 459}
2018-01-01 21:39:17,130 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,138 : INFO : < 200 OK [3420]
2018-01-01 21:39:17,142 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 509, '_0n1': 439}
2018-01-01 21:39:17,142 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,146 : INFO : < 200 OK [3420]
2018-01-01 21:39:17,154 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 509, '_0n1': 422}
2018-01-01 21:39:17,154 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,158 : INFO : < 200 OK [3410]
2018-01-01 21:39:17,170 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 508}
2018-01-01 21:39:17,170 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,174 : INFO : < 200 OK [3411]
2018-01-01 21:39:17,178 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 456}
2018-01-01 21:39:17,182 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,186 : INFO : < 200 OK [3399]
2018-01-01 21:39:17,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 514, '_0n1': 348}
2018-01-01 21:39:17,198 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,203 : INFO : < 200 OK [3337]
2018-01-01 21:39:17,210 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 514, '_0n1': 429}
2018-01-01 21:39:17,211 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,215 : INFO : < 200 OK [3390]
2018-01-01 21:39:17,222 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 511, '_0n1': 521}
2018-01-01 21:39:17,222 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,226 : INFO : < 200 OK [3381]
2018-01-01 21:39:17,230 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 511, '_0n1': 549}
2018-01-01 21:39:17,234 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,238 : INFO : < 200 OK [3401]
2018-01-01 21:39:17,246 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 515, '_0n1': 471}
2018-01-01 21:39:17,246 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,254 : INFO : < 200 OK [3365]
2018-01-01 21:39:17,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 512, '_0n1': 601}
2018-01-01 21:39:17,262 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,266 : INFO : < 200 OK [3356]
2018-01-01 21:39:17,270 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 512, '_0n1': 618}
2018-01-01 21:39:17,270 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,278 : INFO : < 200 OK [3362]
2018-01-01 21:39:17,286 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 516, '_0n1': 456}
2018-01-01 21:39:17,286 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,290 : INFO : < 200 OK [3385]
2018-01-01 21:39:17,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 533, '_0n1': 459}
2018-01-01 21:39:17,294 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,302 : INFO : < 200 OK [3401]
2018-01-01 21:39:17,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 533, '_0n1': 252}
2018-01-01 21:39:17,309 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,314 : INFO : < 200 OK [3406]
2018-01-01 21:39:17,318 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 517, '_0n1': 590}
2018-01-01 21:39:17,322 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,326 : INFO : < 200 OK [3402]
2018-01-01 21:39:17,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 517, '_0n1': 411}
2018-01-01 21:39:17,330 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,338 : INFO : < 200 OK [3384]
2018-01-01 21:39:17,346 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 518, '_0n1': 578}
2018-01-01 21:39:17,350 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,354 : INFO : < 200 OK [3386]
2018-01-01 21:39:17,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 518, '_0n1': 567}
2018-01-01 21:39:17,358 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,362 : INFO : < 200 OK [3380]
2018-01-01 21:39:17,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 535, '_0n1': 95}
2018-01-01 21:39:17,374 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:17,378 : INFO : < 200 OK [3369]
2018-01-01 21:39:17,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 519, '_0n1': 373}
2018-01-01 21:39:17,386 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,390 : INFO : < 200 OK [3415]
2018-01-01 21:39:17,394 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 519, '_0n1': 425}
2018-01-01 21:39:17,394 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,398 : INFO : < 200 OK [3370]
2018-01-01 21:39:17,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 536, '_0n1': 128}
2018-01-01 21:39:17,414 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,418 : INFO : < 200 OK [3396]
2018-01-01 21:39:17,422 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 520, '_0n1': 531}
2018-01-01 21:39:17,422 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:17,430 : INFO : < 200 OK [3411]
2018-01-01 21:39:17,434 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 520, '_0n1': 545}
2018-01-01 21:39:17,438 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,442 : INFO : < 200 OK [3407]
2018-01-01 21:39:17,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 537, '_0n1': 472}
2018-01-01 21:39:17,450 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,454 : INFO : < 200 OK [3319]
2018-01-01 21:39:17,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 537, '_0n1': 474}
2018-01-01 21:39:17,462 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,466 : INFO : < 200 OK [3369]
2018-01-01 21:39:17,470 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 521, '_0n1': 511}
2018-01-01 21:39:17,474 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,478 : INFO : < 200 OK [3381]
2018-01-01 21:39:17,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 521, '_0n1': 549}
2018-01-01 21:39:17,486 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,494 : INFO : < 200 OK [3379]
2018-01-01 21:39:17,503 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 538, '_0n1': 549}
2018-01-01 21:39:17,505 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,510 : INFO : < 200 OK [3404]
2018-01-01 21:39:17,518 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 538, '_0n1': 426}
2018-01-01 21:39:17,522 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,526 : INFO : < 200 OK [3337]
2018-01-01 21:39:17,534 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 522, '_0n1': 302}
2018-01-01 21:39:17,538 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,542 : INFO : < 200 OK [3372]
2018-01-01 21:39:17,546 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 522, '_0n1': 367}
2018-01-01 21:39:17,550 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,558 : INFO : < 200 OK [3358]
2018-01-01 21:39:17,566 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 539, '_0n1': 17}
2018-01-01 21:39:17,566 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:17,570 : INFO : < 200 OK [3386]
2018-01-01 21:39:17,574 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 539, '_0n1': 462}
2018-01-01 21:39:17,578 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,582 : INFO : < 200 OK [3381]
2018-01-01 21:39:17,586 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 523, '_0n1': 219}
2018-01-01 21:39:17,586 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,590 : INFO : < 200 OK [3376]
2018-01-01 21:39:17,594 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 523, '_0n1': 481}
2018-01-01 21:39:17,594 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,602 : INFO : < 200 OK [3379]
2018-01-01 21:39:17,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 540, '_0n1': 549}
2018-01-01 21:39:17,609 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,613 : INFO : < 200 OK [3363]
2018-01-01 21:39:17,622 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 540, '_0n1': 426}
2018-01-01 21:39:17,622 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,630 : INFO : < 200 OK [3296]
2018-01-01 21:39:17,634 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 524, '_0n1': 163}
2018-01-01 21:39:17,638 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,642 : INFO : < 200 OK [3359]
2018-01-01 21:39:17,646 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 524, '_0n1': 200}
2018-01-01 21:39:17,646 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,654 : INFO : < 200 OK [3389]
2018-01-01 21:39:17,662 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 542, '_0n1': 122}
2018-01-01 21:39:17,666 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,670 : INFO : < 200 OK [3347]
2018-01-01 21:39:17,674 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 542, '_0n1': 96}
2018-01-01 21:39:17,674 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:17,678 : INFO : < 200 OK [3331]
2018-01-01 21:39:17,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 526, '_0n1': 349}
2018-01-01 21:39:17,686 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,690 : INFO : < 200 OK [3442]
2018-01-01 21:39:17,690 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 526, '_0n1': 344}
2018-01-01 21:39:17,694 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,698 : INFO : < 200 OK [3447]
2018-01-01 21:39:17,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 543, '_0n1': 554}
2018-01-01 21:39:17,711 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,716 : INFO : < 200 OK [3384]
2018-01-01 21:39:17,722 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 527, '_0n1': 503}
2018-01-01 21:39:17,722 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,730 : INFO : < 200 OK [3367]
2018-01-01 21:39:17,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 527, '_0n1': 578}
2018-01-01 21:39:17,734 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:17,738 : INFO : < 200 OK [3411]
2018-01-01 21:39:17,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 544, '_0n1': 74}
2018-01-01 21:39:17,746 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:17,750 : INFO : < 200 OK [3342]
2018-01-01 21:39:17,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 528, '_0n1': 1247}
2018-01-01 21:39:17,758 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:17,762 : INFO : < 200 OK [3465]
2018-01-01 21:39:17,766 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 528, '_0n1': 201}
2018-01-01 21:39:17,766 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,770 : INFO : < 200 OK [3424]
2018-01-01 21:39:17,778 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 545, '_0n1': 520}
2018-01-01 21:39:17,778 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,782 : INFO : < 200 OK [3407]
2018-01-01 21:39:17,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 545, '_0n1': 529}
2018-01-01 21:39:17,790 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,790 : INFO : < 200 OK [3436]
2018-01-01 21:39:17,798 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 529, '_0n1': 399}
2018-01-01 21:39:17,798 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,805 : INFO : < 200 OK [3402]
2018-01-01 21:39:17,809 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 529, '_0n1': 531}
2018-01-01 21:39:17,811 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,817 : INFO : < 200 OK [3440]
2018-01-01 21:39:17,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 546, '_0n1': 212}
2018-01-01 21:39:17,826 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,830 : INFO : < 200 OK [3428]
2018-01-01 21:39:17,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 530, '_0n1': 398}
2018-01-01 21:39:17,838 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,842 : INFO : < 200 OK [3369]
2018-01-01 21:39:17,846 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 530, '_0n1': 89}
2018-01-01 21:39:17,846 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:17,850 : INFO : < 200 OK [3341]
2018-01-01 21:39:17,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 547, '_0n1': 449}
2018-01-01 21:39:17,858 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,862 : INFO : < 200 OK [3386]
2018-01-01 21:39:17,866 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 547, '_0n1': 468}
2018-01-01 21:39:17,870 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,874 : INFO : < 200 OK [3376]
2018-01-01 21:39:17,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 531, '_0n1': 529}
2018-01-01 21:39:17,886 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,890 : INFO : < 200 OK [3440]
2018-01-01 21:39:17,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 531, '_0n1': 520}
2018-01-01 21:39:17,894 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,903 : INFO : < 200 OK [3411]
2018-01-01 21:39:17,910 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 548, '_0n1': 64}
2018-01-01 21:39:17,911 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:17,915 : INFO : < 200 OK [3305]
2018-01-01 21:39:17,918 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 548, '_0n1': 392}
2018-01-01 21:39:17,918 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,922 : INFO : < 200 OK [3319]
2018-01-01 21:39:17,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 532, '_0n1': 212}
2018-01-01 21:39:17,930 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,934 : INFO : < 200 OK [3396]
2018-01-01 21:39:17,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 532, '_0n1': 340}
2018-01-01 21:39:17,938 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,946 : INFO : < 200 OK [3364]
2018-01-01 21:39:17,970 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 550, '_0n1': 331}
2018-01-01 21:39:17,970 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,974 : INFO : < 200 OK [3417]
2018-01-01 21:39:17,982 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 554, '_0n1': 543}
2018-01-01 21:39:17,982 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,986 : INFO : < 200 OK [3384]
2018-01-01 21:39:17,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 554, '_0n1': 478}
2018-01-01 21:39:17,994 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:17,998 : INFO : < 200 OK [3432]
2018-01-01 21:39:18,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 551, '_0n1': 556}
2018-01-01 21:39:18,002 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,009 : INFO : < 200 OK [3361]
2018-01-01 21:39:18,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 551, '_0n1': 414}
2018-01-01 21:39:18,018 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,022 : INFO : < 200 OK [3323]
2018-01-01 21:39:18,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 555, '_0n1': 341}
2018-01-01 21:39:18,030 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,034 : INFO : < 200 OK [3347]

2018-01-01 21:39:18,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 555, '_0n1': 334}
2018-01-01 21:39:18,042 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,046 : INFO : < 200 OK [3351]
2018-01-01 21:39:18,054 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 552, '_0n1': 392}
2018-01-01 21:39:18,054 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,062 : INFO : < 200 OK [3329]
2018-01-01 21:39:18,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 552, '_0n1': 64}
2018-01-01 21:39:18,066 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:18,070 : INFO : < 200 OK [3315]
2018-01-01 21:39:18,078 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 556, '_0n1': 551}
2018-01-01 21:39:18,078 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,082 : INFO : < 200 OK [3361]
2018-01-01 21:39:18,090 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 556, '_0n1': 212}
2018-01-01 21:39:18,090 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,098 : INFO : < 200 OK [3397]
2018-01-01 21:39:18,106 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 573, '_0n1': 212}
2018-01-01 21:39:18,107 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,111 : INFO : < 200 OK [3383]
2018-01-01 21:39:18,118 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 573, '_0n1': 340}
2018-01-01 21:39:18,118 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,122 : INFO : < 200 OK [3351]
2018-01-01 21:39:18,126 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 557, '_0n1': 392}
2018-01-01 21:39:18,130 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,134 : INFO : < 200 OK [3377]
2018-01-01 21:39:18,142 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 574, '_0n1': 426}
2018-01-01 21:39:18,146 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,150 : INFO : < 200 OK [3308]
2018-01-01 21:39:18,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 575, '_0n1': 251}
2018-01-01 21:39:18,162 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,166 : INFO : < 200 OK [3406]
2018-01-01 21:39:18,170 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 575, '_0n1': 121}
2018-01-01 21:39:18,174 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,178 : INFO : < 200 OK [3438]
2018-01-01 21:39:18,182 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 559, '_0n1': 124}
2018-01-01 21:39:18,186 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,190 : INFO : < 200 OK [3405]
2018-01-01 21:39:18,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 559, '_0n1': 252}
2018-01-01 21:39:18,194 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,203 : INFO : < 200 OK [3430]
2018-01-01 21:39:18,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 560, '_0n1': 561}
2018-01-01 21:39:18,214 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,218 : INFO : < 200 OK [3413]
2018-01-01 21:39:18,219 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 560, '_0n1': 54}
2018-01-01 21:39:18,223 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:18,227 : INFO : < 200 OK [3380]
2018-01-01 21:39:18,235 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 577, '_0n1': 110}
2018-01-01 21:39:18,235 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,239 : INFO : < 200 OK [3412]
2018-01-01 21:39:18,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 561, '_0n1': 483}
2018-01-01 21:39:18,247 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,255 : INFO : < 200 OK [3406]
2018-01-01 21:39:18,259 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 561, '_0n1': 560}
2018-01-01 21:39:18,263 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,267 : INFO : < 200 OK [3413]
2018-01-01 21:39:18,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 578, '_0n1': 503}
2018-01-01 21:39:18,279 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,283 : INFO : < 200 OK [3385]
2018-01-01 21:39:18,291 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 562, '_0n1': 593}
2018-01-01 21:39:18,291 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,295 : INFO : < 200 OK [3337]
2018-01-01 21:39:18,299 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 562, '_0n1': 76}
2018-01-01 21:39:18,299 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:18,307 : INFO : < 200 OK [3346]
2018-01-01 21:39:18,312 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 604}
2018-01-01 21:39:18,314 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,318 : INFO : < 200 OK [3436]
2018-01-01 21:39:18,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 563, '_0n1': 78}
2018-01-01 21:39:18,327 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:18,331 : INFO : < 200 OK [3426]
2018-01-01 21:39:18,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 563, '_0n1': 118}
2018-01-01 21:39:18,335 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,339 : INFO : < 200 OK [3451]

2018-01-01 21:39:18,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 580, '_0n1': 164}
2018-01-01 21:39:18,351 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,355 : INFO : < 200 OK [3349]
2018-01-01 21:39:18,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 580, '_0n1': 273}
2018-01-01 21:39:18,359 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,363 : INFO : < 200 OK [3372]
2018-01-01 21:39:18,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 564, '_0n1': 153}
2018-01-01 21:39:18,371 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,375 : INFO : < 200 OK [3398]
2018-01-01 21:39:18,379 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 564, '_0n1': 158}
2018-01-01 21:39:18,383 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,387 : INFO : < 200 OK [3377]
2018-01-01 21:39:18,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 581, '_0n1': 302}
2018-01-01 21:39:18,391 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,395 : INFO : < 200 OK [3381]
2018-01-01 21:39:18,399 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 581, '_0n1': 522}
2018-01-01 21:39:18,403 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,407 : INFO : < 200 OK [3338]
2018-01-01 21:39:18,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 565, '_0n1': 275}
2018-01-01 21:39:18,413 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,417 : INFO : < 200 OK [3412]
2018-01-01 21:39:18,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 565, '_0n1': 217}
2018-01-01 21:39:18,419 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,423 : INFO : < 200 OK [3417]
2018-01-01 21:39:18,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 582, '_0n1': 599}
2018-01-01 21:39:18,435 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,439 : INFO : < 200 OK [3375]
2018-01-01 21:39:18,463 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 571}
2018-01-01 21:39:18,467 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,471 : INFO : < 200 OK [3436]
2018-01-01 21:39:18,475 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 33}
2018-01-01 21:39:18,475 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:18,479 : INFO : < 200 OK [3375]
2018-01-01 21:39:18,483 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 568, '_0n1': 148}
2018-01-01 21:39:18,487 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,491 : INFO : < 200 OK [3410]
2018-01-01 21:39:18,495 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 568, '_0n1': 578}
2018-01-01 21:39:18,499 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,504 : INFO : < 200 OK [3426]
2018-01-01 21:39:18,510 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 585, '_0n1': 68}
2018-01-01 21:39:18,511 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:18,515 : INFO : < 200 OK [3355]
2018-01-01 21:39:18,519 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 585, '_0n1': 54}
2018-01-01 21:39:18,523 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:18,527 : INFO : < 200 OK [3356]
2018-01-01 21:39:18,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 569, '_0n1': 503}
2018-01-01 21:39:18,535 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,539 : INFO : < 200 OK [3377]
2018-01-01 21:39:18,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 586, '_0n1': 124}
2018-01-01 21:39:18,547 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,551 : INFO : < 200 OK [3416]
2018-01-01 21:39:18,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 586, '_0n1': 596}
2018-01-01 21:39:18,559 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,563 : INFO : < 200 OK [3410]
2018-01-01 21:39:18,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 400}
2018-01-01 21:39:18,575 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,579 : INFO : < 200 OK [3398]
2018-01-01 21:39:18,583 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 297}
2018-01-01 21:39:18,583 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,591 : INFO : < 200 OK [3407]
2018-01-01 21:39:18,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 583}
2018-01-01 21:39:18,595 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,603 : INFO : < 200 OK [3393]
2018-01-01 21:39:18,612 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 584}
2018-01-01 21:39:18,614 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,618 : INFO : < 200 OK [3436]
2018-01-01 21:39:18,635 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 589, '_0n1': 71}
2018-01-01 21:39:18,635 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:18,639 : INFO : < 200 OK [3450]
2018-01-01 21:39:18,643 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 589, '_0n1': 262}
2018-01-01 21:39:18,647 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,651 : INFO : < 200 OK [3440]
2018-01-01 21:39:18,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 593, '_0n1': 562}

2018-01-01 21:39:18,659 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,663 : INFO : < 200 OK [3337]
2018-01-01 21:39:18,667 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 593, '_0n1': 295}
2018-01-01 21:39:18,671 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,675 : INFO : < 200 OK [3370]
2018-01-01 21:39:18,687 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 590, '_0n1': 357}
2018-01-01 21:39:18,687 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,691 : INFO : < 200 OK [3449]
2018-01-01 21:39:18,699 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 594, '_0n1': 591}
2018-01-01 21:39:18,699 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,705 : INFO : < 200 OK [3414]
2018-01-01 21:39:18,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 594, '_0n1': 140}
2018-01-01 21:39:18,712 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,716 : INFO : < 200 OK [3376]
2018-01-01 21:39:18,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 591, '_0n1': 139}
2018-01-01 21:39:18,723 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,727 : INFO : < 200 OK [3394]
2018-01-01 21:39:18,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 591, '_0n1': 613}
2018-01-01 21:39:18,735 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,739 : INFO : < 200 OK [3404]
2018-01-01 21:39:18,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 595, '_0n1': 119}
2018-01-01 21:39:18,747 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,755 : INFO : < 200 OK [3412]
2018-01-01 21:39:18,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 595, '_0n1': 301}
2018-01-01 21:39:18,759 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,767 : INFO : < 200 OK [3390]
2018-01-01 21:39:18,775 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 567}
2018-01-01 21:39:18,779 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,783 : INFO : < 200 OK [3400]
2018-01-01 21:39:18,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 331}
2018-01-01 21:39:18,787 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,795 : INFO : < 200 OK [3371]
2018-01-01 21:39:18,799 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 613, '_0n1': 591}
2018-01-01 21:39:18,799 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,804 : INFO : < 200 OK [3404]
2018-01-01 21:39:18,809 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 613, '_0n1': 594}
2018-01-01 21:39:18,811 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,817 : INFO : < 200 OK [3385]
2018-01-01 21:39:18,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 597, '_0n1': 139}
2018-01-01 21:39:18,827 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,831 : INFO : < 200 OK [3371]
2018-01-01 21:39:18,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 597, '_0n1': 181}
2018-01-01 21:39:18,839 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,843 : INFO : < 200 OK [3351]
2018-01-01 21:39:18,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 614, '_0n1': 322}
2018-01-01 21:39:18,847 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,851 : INFO : < 200 OK [3391]
2018-01-01 21:39:18,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 614, '_0n1': 582}
2018-01-01 21:39:18,859 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,863 : INFO : < 200 OK [3392]
2018-01-01 21:39:18,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 615, '_0n1': 352}
2018-01-01 21:39:18,875 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,883 : INFO : < 200 OK [3408]
2018-01-01 21:39:18,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 615, '_0n1': 389}
2018-01-01 21:39:18,887 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,895 : INFO : < 200 OK [3399]
2018-01-01 21:39:18,910 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 616, '_0n1': 122}
2018-01-01 21:39:18,911 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,915 : INFO : < 200 OK [3374]
2018-01-01 21:39:18,923 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 600, '_0n1': 47}
2018-01-01 21:39:18,923 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:18,927 : INFO : < 200 OK [3386]
2018-01-01 21:39:18,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 600, '_0n1': 1256}
2018-01-01 21:39:18,935 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2018-01-01 21:39:18,943 : INFO : < 200 OK [3420]
2018-01-01 21:39:18,971 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 602, '_0n1': 356}
2018-01-01 21:39:18,971 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,979 : INFO : < 200 OK [3326]
2018-01-01 21:39:18,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 603, '_0n1': 414}
2018-01-01 21:39:18,991 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:18,995 : INFO : < 200 OK [3357]
2018-01-01 21:39:18,999 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 603, '_0n1': 341}
2018-01-01 21:39:18,999 : INFO : > POST http://localhost:7474/db/data/cypher [183]

2018-01-01 21:39:19,005 : INFO : < 200 OK [3384]
2018-01-01 21:39:19,010 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 604, '_0n1': 59}
2018-01-01 21:39:19,012 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2018-01-01 21:39:19,016 : INFO : < 200 OK [3386]
2018-01-01 21:39:19,019 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 604, '_0n1': 446}
2018-01-01 21:39:19,019 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:19,023 : INFO : < 200 OK [3436]
2018-01-01 21:39:19,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 621, '_0n1': 273}
2018-01-01 21:39:19,035 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2018-01-01 21:39:19,043 : INFO : < 200 OK [3363]

In [65]:
check_list = ['C++', 'python', 'Java', 'HTML', 'Javascript', 'PHP', ' R ', ' C ', 
              'perl', 'spark', 'hadoop', 'Swift', 'Android', 'Ruby', 'programming language']
program_dict = {}
for language in check_list:
    program_dict[language] = Node("Programming language", name=language)
    graph.create(program_dict[language])

2018-01-01 21:39:19,203 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'C++'}}
2018-01-01 21:39:19,218 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:39:19,221 : INFO : < 200 OK [1391]
2018-01-01 21:39:19,225 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'python'}}
2018-01-01 21:39:19,229 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:39:19,229 : INFO : < 200 OK [1394]
2018-01-01 21:39:19,233 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'Java'}}
2018-01-01 21:39:19,233 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:39:19,241 : INFO : < 200 OK [1392]
2018-01-01 21:39:19,241 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'HTML'}}
2018-01-01 21:39:19,245 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:39:19,249 : INFO : < 200 OK [1392]
2018-01-01 21:39:19,249 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'Javascript'}}
2018-01-01 21:39:19,253 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2018-01-01 21:39:19,257 : INFO : < 200 OK [1398]
2018-01-01 21:39:19,257 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'PHP'}}
2018-01-01 21:39:19,261 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:39:19,265 : INFO : < 200 OK [1391]
2018-01-01 21:39:19,265 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': ' R '}}
2018-01-01 21:39:19,269 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:39:19,273 : INFO : < 200 OK [1391]
2018-01-01 21:39:19,273 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': ' C '}}
2018-01-01 21:39:19,277 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2018-01-01 21:39:19,281 : INFO : < 200 OK [1391]
2018-01-01 21:39:19,281 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'perl'}}
2018-01-01 21:39:19,285 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:39:19,289 : INFO : < 200 OK [1392]
2018-01-01 21:39:19,289 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'spark'}}
2018-01-01 21:39:19,293 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:39:19,301 : INFO : < 200 OK [1393]
2018-01-01 21:39:19,301 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'hadoop'}}
2018-01-01 21:39:19,305 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2018-01-01 21:39:19,311 : INFO : < 200 OK [1394]
2018-01-01 21:39:19,313 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'Swift'}}
2018-01-01 21:39:19,315 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2018-01-01 21:39:19,319 : INFO : < 200 OK [1393]
2018-01-01 21:39:19,319 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'Android'}}
2018-01-01 21:39:19,323 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2018-01-01 21:39:19,327 : INFO : < 200 OK [1395]
2018-01-01 21:39:19,327 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'Ruby'}}
2018-01-01 21:39:19,331 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2018-01-01 21:39:19,335 : INFO : < 200 OK [1392]
2018-01-01 21:39:19,335 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'programming language'}}
2018-01-01 21:39:19,335 : INFO : > POST http://localhost:7474/db/data/cypher [110]
2018-01-01 21:39:19,339 : INFO : < 200 OK [1408]

In [66]:
for i, row in data_language_df.iterrows():
    x = course_dict[row.uid]
    for language in check_list:
        if row[language]:
            y = program_dict[language]
            graph.create(Relationship(x, "use", y))

2018-01-01 21:39:19,516 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1233, '_0n1': 1192}
2018-01-01 21:39:19,517 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,519 : INFO : < 200 OK [3285]
2018-01-01 21:39:19,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1233, '_0n1': 1193}
2018-01-01 21:39:19,523 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,527 : INFO : < 200 OK [3286]
2018-01-01 21:39:19,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1234, '_0n1': 1199}
2018-01-01 21:39:19,531 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,535 : INFO : < 200 OK [3313]
2018-01-01 21:39:19,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1254, '_0n1': 1192}
2018-01-01 21:39:19,543 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,547 : INFO : < 200 OK [3337]
2018-01-01 21:39:19,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1254, '_0n1': 1193}
2018-01-01 21:39:19,547 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,551 : INFO : < 200 OK [3338]
2018-01-01 21:39:19,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1255, '_0n1': 1216}
2018-01-01 21:39:19,559 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,563 : INFO : < 200 OK [3373]
2018-01-01 21:39:19,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1255, '_0n1': 1216}
2018-01-01 21:39:19,567 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,571 : INFO : < 200 OK [3373]
2018-01-01 21:39:19,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1239, '_0n1': 1211}
2018-01-01 21:39:19,575 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,579 : INFO : < 200 OK [3368]
2018-01-01 21:39:19,583 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1239, '_0n1': 1193}
2018-01-01 21:39:19,583 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,591 : INFO : < 200 OK [3366]
2018-01-01 21:39:19,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1240, '_0n1': 1198}
2018-01-01 21:39:19,595 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,599 : INFO : < 200 OK [3323]
2018-01-01 21:39:19,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1260, '_0n1': 1211}
2018-01-01 21:39:19,606 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,610 : INFO : < 200 OK [3304]
2018-01-01 21:39:19,613 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 0, '_0n1': 1193}
2018-01-01 21:39:19,614 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,619 : INFO : < 200 OK [3265]
2018-01-01 21:39:19,619 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 0, '_0n1': 1194}
2018-01-01 21:39:19,619 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,627 : INFO : < 200 OK [3271]
2018-01-01 21:39:19,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1302, '_0n1': 1212}
2018-01-01 21:39:19,631 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:19,635 : INFO : < 200 OK [3338]
2018-01-01 21:39:19,635 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 1211}
2018-01-01 21:39:19,639 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,643 : INFO : < 200 OK [3301]
2018-01-01 21:39:19,643 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 1193}
2018-01-01 21:39:19,647 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,651 : INFO : < 200 OK [3299]
2018-01-01 21:39:19,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 1215}
2018-01-01 21:39:19,655 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,659 : INFO : < 200 OK [3300]
2018-01-01 21:39:19,663 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 1197}
2018-01-01 21:39:19,667 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,671 : INFO : < 200 OK [3301]
2018-01-01 21:39:19,675 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 1199}
2018-01-01 21:39:19,675 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,679 : INFO : < 200 OK [3315]
2018-01-01 21:39:19,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 1211}
2018-01-01 21:39:19,683 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,687 : INFO : < 200 OK [3301]
2018-01-01 21:39:19,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 1193}
2018-01-01 21:39:19,691 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,695 : INFO : < 200 OK [3299]
2018-01-01 21:39:19,699 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 1215}
2018-01-01 21:39:19,699 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,705 : INFO : < 200 OK [3300]
2018-01-01 21:39:19,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 1197}
2018-01-01 21:39:19,709 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,714 : INFO : < 200 OK [3301]
2018-01-01 21:39:19,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 2, '_0n1': 1199}
2018-01-01 21:39:19,719 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,723 : INFO : < 200 OK [3315]
2018-01-01 21:39:19,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 3, '_0n1': 1197}
2018-01-01 21:39:19,727 : INFO : > POST http://localhost:7474/db/data/cypher [173]

2018-01-01 21:39:19,731 : INFO : < 200 OK [3279]
2018-01-01 21:39:19,735 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 8, '_0n1': 1199}
2018-01-01 21:39:19,739 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,743 : INFO : < 200 OK [3303]
2018-01-01 21:39:19,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 8, '_0n1': 1199}
2018-01-01 21:39:19,747 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:19,751 : INFO : < 200 OK [3303]
2018-01-01 21:39:19,755 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 27, '_0n1': 1213}
2018-01-01 21:39:19,755 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,763 : INFO : < 200 OK [3296]
2018-01-01 21:39:19,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 13, '_0n1': 1198}
2018-01-01 21:39:19,771 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,775 : INFO : < 200 OK [3287]
2018-01-01 21:39:19,779 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 13, '_0n1': 1198}
2018-01-01 21:39:19,783 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,787 : INFO : < 200 OK [3287]
2018-01-01 21:39:19,799 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 48, '_0n1': 1193}
2018-01-01 21:39:19,805 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,809 : INFO : < 200 OK [3287]
2018-01-01 21:39:19,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 48, '_0n1': 1194}
2018-01-01 21:39:19,813 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,817 : INFO : < 200 OK [3293]
2018-01-01 21:39:19,819 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 48, '_0n1': 1193}
2018-01-01 21:39:19,819 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,823 : INFO : < 200 OK [3287]
2018-01-01 21:39:19,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 48, '_0n1': 1194}
2018-01-01 21:39:19,827 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,831 : INFO : < 200 OK [3293]
2018-01-01 21:39:19,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 1211}
2018-01-01 21:39:19,835 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,839 : INFO : < 200 OK [3307]
2018-01-01 21:39:19,843 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 1211}
2018-01-01 21:39:19,843 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,847 : INFO : < 200 OK [3307]
2018-01-01 21:39:19,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 1211}
2018-01-01 21:39:19,851 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,855 : INFO : < 200 OK [3307]
2018-01-01 21:39:19,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 1196}
2018-01-01 21:39:19,859 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,863 : INFO : < 200 OK [3301]
2018-01-01 21:39:19,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 1196}
2018-01-01 21:39:19,867 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,871 : INFO : < 200 OK [3301]
2018-01-01 21:39:19,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 1196}
2018-01-01 21:39:19,875 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,879 : INFO : < 200 OK [3301]
2018-01-01 21:39:19,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 50, '_0n1': 1193}
2018-01-01 21:39:19,887 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,891 : INFO : < 200 OK [3290]
2018-01-01 21:39:19,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 50, '_0n1': 1193}
2018-01-01 21:39:19,899 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,905 : INFO : < 200 OK [3290]
2018-01-01 21:39:19,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1199}
2018-01-01 21:39:19,911 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,915 : INFO : < 200 OK [3307]
2018-01-01 21:39:19,919 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1199}
2018-01-01 21:39:19,919 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,923 : INFO : < 200 OK [3307]
2018-01-01 21:39:19,927 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1199}
2018-01-01 21:39:19,927 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,931 : INFO : < 200 OK [3307]
2018-01-01 21:39:19,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1199}
2018-01-01 21:39:19,935 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,943 : INFO : < 200 OK [3307]
2018-01-01 21:39:19,943 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1199}
2018-01-01 21:39:19,947 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,951 : INFO : < 200 OK [3307]
2018-01-01 21:39:19,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 1211}
2018-01-01 21:39:19,955 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,959 : INFO : < 200 OK [3302]
2018-01-01 21:39:19,963 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 1211}
2018-01-01 21:39:19,963 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,967 : INFO : < 200 OK [3302]
2018-01-01 21:39:19,971 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 1211}

2018-01-01 21:39:19,971 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,975 : INFO : < 200 OK [3302]
2018-01-01 21:39:19,979 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 1211}
2018-01-01 21:39:19,979 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,983 : INFO : < 200 OK [3302]
2018-01-01 21:39:19,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 1193}
2018-01-01 21:39:19,987 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,991 : INFO : < 200 OK [3291]
2018-01-01 21:39:19,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 1195}
2018-01-01 21:39:19,995 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:19,999 : INFO : < 200 OK [3290]
2018-01-01 21:39:20,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 1193}
2018-01-01 21:39:20,006 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,010 : INFO : < 200 OK [3291]
2018-01-01 21:39:20,013 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 1195}
2018-01-01 21:39:20,014 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,018 : INFO : < 200 OK [3290]
2018-01-01 21:39:20,019 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1192}
2018-01-01 21:39:20,019 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,027 : INFO : < 200 OK [3285]
2018-01-01 21:39:20,027 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1211}
2018-01-01 21:39:20,031 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,035 : INFO : < 200 OK [3288]
2018-01-01 21:39:20,039 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1193}
2018-01-01 21:39:20,043 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,055 : INFO : < 200 OK [3286]
2018-01-01 21:39:20,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1199}
2018-01-01 21:39:20,059 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,063 : INFO : < 200 OK [3302]
2018-01-01 21:39:20,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1192}
2018-01-01 21:39:20,067 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,071 : INFO : < 200 OK [3285]
2018-01-01 21:39:20,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1211}
2018-01-01 21:39:20,075 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,083 : INFO : < 200 OK [3288]
2018-01-01 21:39:20,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1193}
2018-01-01 21:39:20,087 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,091 : INFO : < 200 OK [3286]
2018-01-01 21:39:20,091 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1199}
2018-01-01 21:39:20,095 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,099 : INFO : < 200 OK [3302]
2018-01-01 21:39:20,099 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1192}
2018-01-01 21:39:20,104 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,108 : INFO : < 200 OK [3285]
2018-01-01 21:39:20,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1211}
2018-01-01 21:39:20,112 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,116 : INFO : < 200 OK [3288]
2018-01-01 21:39:20,119 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1193}
2018-01-01 21:39:20,119 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,123 : INFO : < 200 OK [3286]
2018-01-01 21:39:20,127 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1199}
2018-01-01 21:39:20,127 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,131 : INFO : < 200 OK [3302]
2018-01-01 21:39:20,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1192}
2018-01-01 21:39:20,135 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,139 : INFO : < 200 OK [3285]
2018-01-01 21:39:20,143 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1211}
2018-01-01 21:39:20,143 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,147 : INFO : < 200 OK [3288]
2018-01-01 21:39:20,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1193}
2018-01-01 21:39:20,151 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,155 : INFO : < 200 OK [3286]
2018-01-01 21:39:20,159 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 53, '_0n1': 1199}
2018-01-01 21:39:20,159 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,163 : INFO : < 200 OK [3302]
2018-01-01 21:39:20,167 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 71, '_0n1': 1193}
2018-01-01 21:39:20,167 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,171 : INFO : < 200 OK [3330]
2018-01-01 21:39:20,175 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 71, '_0n1': 1193}
2018-01-01 21:39:20,175 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,179 : INFO : < 200 OK [3330]
2018-01-01 21:39:20,187 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 72, '_0n1': 1192}
2018-01-01 21:39:20,187 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,191 : INFO : < 200 OK [3298]
2018-01-01 21:39:20,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 72, '_0n1': 1193}

2018-01-01 21:39:20,199 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,205 : INFO : < 200 OK [3299]
2018-01-01 21:39:20,210 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 72, '_0n1': 1199}
2018-01-01 21:39:20,212 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,216 : INFO : < 200 OK [3315]
2018-01-01 21:39:20,219 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 1211}
2018-01-01 21:39:20,219 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,223 : INFO : < 200 OK [3286]
2018-01-01 21:39:20,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 1211}
2018-01-01 21:39:20,227 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,231 : INFO : < 200 OK [3286]
2018-01-01 21:39:20,235 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 1211}
2018-01-01 21:39:20,239 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,243 : INFO : < 200 OK [3286]
2018-01-01 21:39:20,243 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 74, '_0n1': 1211}
2018-01-01 21:39:20,247 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,251 : INFO : < 200 OK [3271]
2018-01-01 21:39:20,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 57, '_0n1': 1192}
2018-01-01 21:39:20,255 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,259 : INFO : < 200 OK [3276]
2018-01-01 21:39:20,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 57, '_0n1': 1211}
2018-01-01 21:39:20,263 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,267 : INFO : < 200 OK [3279]
2018-01-01 21:39:20,271 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 57, '_0n1': 1193}
2018-01-01 21:39:20,271 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,275 : INFO : < 200 OK [3277]
2018-01-01 21:39:20,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 57, '_0n1': 1194}
2018-01-01 21:39:20,279 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,287 : INFO : < 200 OK [3283]
2018-01-01 21:39:20,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 57, '_0n1': 1215}
2018-01-01 21:39:20,291 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,295 : INFO : < 200 OK [3278]
2018-01-01 21:39:20,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 57, '_0n1': 1197}
2018-01-01 21:39:20,299 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,304 : INFO : < 200 OK [3279]
2018-01-01 21:39:20,308 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 57, '_0n1': 1217}
2018-01-01 21:39:20,309 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,313 : INFO : < 200 OK [3277]
2018-01-01 21:39:20,318 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 1214}
2018-01-01 21:39:20,319 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,323 : INFO : < 200 OK [3280]
2018-01-01 21:39:20,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 1214}
2018-01-01 21:39:20,327 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,331 : INFO : < 200 OK [3280]
2018-01-01 21:39:20,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 1214}
2018-01-01 21:39:20,339 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,343 : INFO : < 200 OK [3280]
2018-01-01 21:39:20,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 80, '_0n1': 1211}
2018-01-01 21:39:20,351 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,355 : INFO : < 200 OK [3298]
2018-01-01 21:39:20,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 83, '_0n1': 1211}
2018-01-01 21:39:20,359 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,367 : INFO : < 200 OK [3299]
2018-01-01 21:39:20,367 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 83, '_0n1': 1211}
2018-01-01 21:39:20,371 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,375 : INFO : < 200 OK [3299]
2018-01-01 21:39:20,379 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1211}
2018-01-01 21:39:20,379 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,383 : INFO : < 200 OK [3318]
2018-01-01 21:39:20,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1199}
2018-01-01 21:39:20,387 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,395 : INFO : < 200 OK [3332]
2018-01-01 21:39:20,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1211}
2018-01-01 21:39:20,399 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,404 : INFO : < 200 OK [3318]
2018-01-01 21:39:20,406 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1199}
2018-01-01 21:39:20,408 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,411 : INFO : < 200 OK [3332]
2018-01-01 21:39:20,415 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1211}
2018-01-01 21:39:20,416 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,420 : INFO : < 200 OK [3318]
2018-01-01 21:39:20,420 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1199}
2018-01-01 21:39:20,424 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,428 : INFO : < 200 OK [3332]
2018-01-01 21:39:20,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 84, '_0n1': 1196}

2018-01-01 21:39:20,432 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,440 : INFO : < 200 OK [3289]
2018-01-01 21:39:20,444 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 1199}
2018-01-01 21:39:20,444 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,452 : INFO : < 200 OK [3333]
2018-01-01 21:39:20,452 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 1199}
2018-01-01 21:39:20,456 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,460 : INFO : < 200 OK [3333]
2018-01-01 21:39:20,464 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 1199}
2018-01-01 21:39:20,468 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,472 : INFO : < 200 OK [3333]
2018-01-01 21:39:20,472 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 1199}
2018-01-01 21:39:20,476 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,480 : INFO : < 200 OK [3333]
2018-01-01 21:39:20,484 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 85, '_0n1': 1193}
2018-01-01 21:39:20,484 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,492 : INFO : < 200 OK [3303]
2018-01-01 21:39:20,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 85, '_0n1': 1193}
2018-01-01 21:39:20,496 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,500 : INFO : < 200 OK [3303]
2018-01-01 21:39:20,504 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 85, '_0n1': 1193}
2018-01-01 21:39:20,506 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,510 : INFO : < 200 OK [3303]
2018-01-01 21:39:20,514 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 103, '_0n1': 1199}
2018-01-01 21:39:20,515 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,520 : INFO : < 200 OK [3324]
2018-01-01 21:39:20,520 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 103, '_0n1': 1199}
2018-01-01 21:39:20,524 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,528 : INFO : < 200 OK [3324]
2018-01-01 21:39:20,528 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 103, '_0n1': 1199}
2018-01-01 21:39:20,528 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,536 : INFO : < 200 OK [3324]
2018-01-01 21:39:20,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 103, '_0n1': 1199}
2018-01-01 21:39:20,540 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,544 : INFO : < 200 OK [3324]
2018-01-01 21:39:20,548 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 87, '_0n1': 1193}
2018-01-01 21:39:20,548 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,552 : INFO : < 200 OK [3301]
2018-01-01 21:39:20,556 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 1211}
2018-01-01 21:39:20,556 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,564 : INFO : < 200 OK [3346]
2018-01-01 21:39:20,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 1211}
2018-01-01 21:39:20,572 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,576 : INFO : < 200 OK [3346]
2018-01-01 21:39:20,580 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 1211}
2018-01-01 21:39:20,580 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,584 : INFO : < 200 OK [3346]
2018-01-01 21:39:20,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 1211}
2018-01-01 21:39:20,588 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,592 : INFO : < 200 OK [3346]
2018-01-01 21:39:20,596 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 1211}
2018-01-01 21:39:20,600 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,604 : INFO : < 200 OK [3315]
2018-01-01 21:39:20,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 1211}
2018-01-01 21:39:20,610 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,614 : INFO : < 200 OK [3315]
2018-01-01 21:39:20,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 1211}
2018-01-01 21:39:20,618 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,620 : INFO : < 200 OK [3315]
2018-01-01 21:39:20,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 89, '_0n1': 1195}
2018-01-01 21:39:20,624 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,628 : INFO : < 200 OK [3296]
2018-01-01 21:39:20,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 89, '_0n1': 1215}
2018-01-01 21:39:20,632 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,636 : INFO : < 200 OK [3298]
2018-01-01 21:39:20,640 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 1211}
2018-01-01 21:39:20,640 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,644 : INFO : < 200 OK [3306]
2018-01-01 21:39:20,648 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 1211}
2018-01-01 21:39:20,652 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,656 : INFO : < 200 OK [3306]
2018-01-01 21:39:20,660 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 1211}
2018-01-01 21:39:20,660 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,668 : INFO : < 200 OK [3306]
2018-01-01 21:39:20,672 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 92, '_0n1': 1192}

2018-01-01 21:39:20,672 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,676 : INFO : < 200 OK [3293]
2018-01-01 21:39:20,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 92, '_0n1': 1211}
2018-01-01 21:39:20,684 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,688 : INFO : < 200 OK [3296]
2018-01-01 21:39:20,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 92, '_0n1': 1193}
2018-01-01 21:39:20,692 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,696 : INFO : < 200 OK [3294]
2018-01-01 21:39:20,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 1193}
2018-01-01 21:39:20,700 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,708 : INFO : < 200 OK [3319]
2018-01-01 21:39:20,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 1193}
2018-01-01 21:39:20,714 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,719 : INFO : < 200 OK [3319]
2018-01-01 21:39:20,720 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 1193}
2018-01-01 21:39:20,720 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,724 : INFO : < 200 OK [3319]
2018-01-01 21:39:20,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 93, '_0n1': 1192}
2018-01-01 21:39:20,728 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,732 : INFO : < 200 OK [3270]
2018-01-01 21:39:20,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 93, '_0n1': 1193}
2018-01-01 21:39:20,736 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,740 : INFO : < 200 OK [3271]
2018-01-01 21:39:20,744 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 93, '_0n1': 1215}
2018-01-01 21:39:20,744 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,748 : INFO : < 200 OK [3272]
2018-01-01 21:39:20,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 93, '_0n1': 1197}
2018-01-01 21:39:20,752 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,756 : INFO : < 200 OK [3273]
2018-01-01 21:39:20,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 93, '_0n1': 1199}
2018-01-01 21:39:20,764 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,768 : INFO : < 200 OK [3287]
2018-01-01 21:39:20,772 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 94, '_0n1': 1211}
2018-01-01 21:39:20,772 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,780 : INFO : < 200 OK [3286]
2018-01-01 21:39:20,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 112, '_0n1': 1211}
2018-01-01 21:39:20,784 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,788 : INFO : < 200 OK [3285]
2018-01-01 21:39:20,792 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 112, '_0n1': 1211}
2018-01-01 21:39:20,796 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,800 : INFO : < 200 OK [3285]
2018-01-01 21:39:20,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1211}
2018-01-01 21:39:20,807 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,812 : INFO : < 200 OK [3303]
2018-01-01 21:39:20,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1199}
2018-01-01 21:39:20,818 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,820 : INFO : < 200 OK [3317]
2018-01-01 21:39:20,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1211}
2018-01-01 21:39:20,824 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,828 : INFO : < 200 OK [3303]
2018-01-01 21:39:20,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1199}
2018-01-01 21:39:20,832 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,836 : INFO : < 200 OK [3317]
2018-01-01 21:39:20,840 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1211}
2018-01-01 21:39:20,840 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,844 : INFO : < 200 OK [3303]
2018-01-01 21:39:20,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1199}
2018-01-01 21:39:20,852 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,856 : INFO : < 200 OK [3317]
2018-01-01 21:39:20,860 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1211}
2018-01-01 21:39:20,860 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,864 : INFO : < 200 OK [3288]
2018-01-01 21:39:20,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1199}
2018-01-01 21:39:20,868 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,872 : INFO : < 200 OK [3302]
2018-01-01 21:39:20,872 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1211}
2018-01-01 21:39:20,876 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,880 : INFO : < 200 OK [3288]
2018-01-01 21:39:20,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1199}
2018-01-01 21:39:20,884 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,888 : INFO : < 200 OK [3302]
2018-01-01 21:39:20,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1211}
2018-01-01 21:39:20,892 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,900 : INFO : < 200 OK [3288]
2018-01-01 21:39:20,904 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1199}

2018-01-01 21:39:20,904 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,912 : INFO : < 200 OK [3302]
2018-01-01 21:39:20,917 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 99, '_0n1': 1192}
2018-01-01 21:39:20,919 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,920 : INFO : < 200 OK [3295]
2018-01-01 21:39:20,924 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 99, '_0n1': 1211}
2018-01-01 21:39:20,924 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,928 : INFO : < 200 OK [3298]
2018-01-01 21:39:20,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 99, '_0n1': 1193}
2018-01-01 21:39:20,932 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:20,936 : INFO : < 200 OK [3296]
2018-01-01 21:39:20,944 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 119, '_0n1': 1211}
2018-01-01 21:39:20,948 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,952 : INFO : < 200 OK [3307]
2018-01-01 21:39:20,960 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1211}
2018-01-01 21:39:20,960 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,964 : INFO : < 200 OK [3314]
2018-01-01 21:39:20,968 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1199}
2018-01-01 21:39:20,968 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,976 : INFO : < 200 OK [3328]
2018-01-01 21:39:20,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1211}
2018-01-01 21:39:20,980 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,984 : INFO : < 200 OK [3314]
2018-01-01 21:39:20,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1199}
2018-01-01 21:39:20,988 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:20,996 : INFO : < 200 OK [3328]
2018-01-01 21:39:20,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 142, '_0n1': 1211}
2018-01-01 21:39:21,000 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,006 : INFO : < 200 OK [3332]
2018-01-01 21:39:21,013 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 1211}
2018-01-01 21:39:21,017 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,020 : INFO : < 200 OK [3312]
2018-01-01 21:39:21,024 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 1211}
2018-01-01 21:39:21,024 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,032 : INFO : < 200 OK [3312]
2018-01-01 21:39:21,036 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 1211}
2018-01-01 21:39:21,036 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,040 : INFO : < 200 OK [3312]
2018-01-01 21:39:21,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 145, '_0n1': 1211}
2018-01-01 21:39:21,044 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,052 : INFO : < 200 OK [3347]
2018-01-01 21:39:21,056 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 145, '_0n1': 1215}
2018-01-01 21:39:21,056 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,060 : INFO : < 200 OK [3346]
2018-01-01 21:39:21,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 128, '_0n1': 1213}
2018-01-01 21:39:21,064 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,068 : INFO : < 200 OK [3333]
2018-01-01 21:39:21,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1193}
2018-01-01 21:39:21,072 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,080 : INFO : < 200 OK [3298]
2018-01-01 21:39:21,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1212}
2018-01-01 21:39:21,084 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,088 : INFO : < 200 OK [3298]
2018-01-01 21:39:21,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1194}
2018-01-01 21:39:21,096 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,100 : INFO : < 200 OK [3304]
2018-01-01 21:39:21,106 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1196}
2018-01-01 21:39:21,107 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,112 : INFO : < 200 OK [3298]
2018-01-01 21:39:21,116 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1217}
2018-01-01 21:39:21,118 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,120 : INFO : < 200 OK [3298]
2018-01-01 21:39:21,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 130, '_0n1': 1212}
2018-01-01 21:39:21,128 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,132 : INFO : < 200 OK [3319]
2018-01-01 21:39:21,132 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 130, '_0n1': 1213}
2018-01-01 21:39:21,136 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,140 : INFO : < 200 OK [3318]
2018-01-01 21:39:21,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 148, '_0n1': 1192}
2018-01-01 21:39:21,144 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,148 : INFO : < 200 OK [3312]
2018-01-01 21:39:21,152 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 148, '_0n1': 1211}
2018-01-01 21:39:21,156 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,160 : INFO : < 200 OK [3315]
2018-01-01 21:39:21,160 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 148, '_0n1': 1214}

2018-01-01 21:39:21,160 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,168 : INFO : < 200 OK [3312]
2018-01-01 21:39:21,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 132, '_0n1': 1214}
2018-01-01 21:39:21,172 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,176 : INFO : < 200 OK [3334]
2018-01-01 21:39:21,176 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 150, '_0n1': 1193}
2018-01-01 21:39:21,180 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,184 : INFO : < 200 OK [3315]
2018-01-01 21:39:21,184 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 150, '_0n1': 1194}
2018-01-01 21:39:21,188 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,192 : INFO : < 200 OK [3321]
2018-01-01 21:39:21,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 150, '_0n1': 1213}
2018-01-01 21:39:21,192 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,196 : INFO : < 200 OK [3314]
2018-01-01 21:39:21,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1234, '_0n1': 1199}
2018-01-01 21:39:21,208 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:21,214 : INFO : < 200 OK [3313]
2018-01-01 21:39:21,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,220 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,224 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,228 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,228 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,232 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,236 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,236 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,240 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,248 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,252 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,256 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,256 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,260 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,264 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,268 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,272 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,272 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,276 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,280 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 154, '_0n1': 1212}
2018-01-01 21:39:21,280 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,288 : INFO : < 200 OK [3324]
2018-01-01 21:39:21,288 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 154, '_0n1': 1213}
2018-01-01 21:39:21,292 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,296 : INFO : < 200 OK [3323]
2018-01-01 21:39:21,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 137, '_0n1': 1215}
2018-01-01 21:39:21,300 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,307 : INFO : < 200 OK [3311]
2018-01-01 21:39:21,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 138, '_0n1': 1214}
2018-01-01 21:39:21,316 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,320 : INFO : < 200 OK [3318]
2018-01-01 21:39:21,324 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 1195}
2018-01-01 21:39:21,328 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,332 : INFO : < 200 OK [3331]
2018-01-01 21:39:21,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 1199}
2018-01-01 21:39:21,336 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,340 : INFO : < 200 OK [3348]
2018-01-01 21:39:21,344 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 1195}
2018-01-01 21:39:21,344 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,348 : INFO : < 200 OK [3331]
2018-01-01 21:39:21,352 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 1199}
2018-01-01 21:39:21,352 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,356 : INFO : < 200 OK [3348]
2018-01-01 21:39:21,360 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 160, '_0n1': 1214}
2018-01-01 21:39:21,360 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,364 : INFO : < 200 OK [3316]
2018-01-01 21:39:21,372 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 186, '_0n1': 1198}
2018-01-01 21:39:21,372 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,380 : INFO : < 200 OK [3293]
2018-01-01 21:39:21,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 173, '_0n1': 1215}
2018-01-01 21:39:21,388 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,392 : INFO : < 200 OK [3283]
2018-01-01 21:39:21,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 190, '_0n1': 1198}
2018-01-01 21:39:21,396 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,400 : INFO : < 200 OK [3341]
2018-01-01 21:39:21,409 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 132, '_0n1': 1214}

2018-01-01 21:39:21,410 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,414 : INFO : < 200 OK [3334]
2018-01-01 21:39:21,418 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 195, '_0n1': 1214}
2018-01-01 21:39:21,419 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,421 : INFO : < 200 OK [3356]
2018-01-01 21:39:21,429 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 179, '_0n1': 1214}
2018-01-01 21:39:21,429 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,433 : INFO : < 200 OK [3291]
2018-01-01 21:39:21,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 179, '_0n1': 1199}
2018-01-01 21:39:21,437 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,445 : INFO : < 200 OK [3308]
2018-01-01 21:39:21,449 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,453 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,457 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,461 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,465 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,473 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,477 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,477 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,481 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,485 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,489 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,489 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,493 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,497 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,501 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,505 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,508 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,510 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,514 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,518 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,520 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,521 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,525 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,529 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,533 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,541 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,545 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,549 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,553 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,553 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,557 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,565 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,565 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,569 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,577 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,581 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 196, '_0n1': 1195}
2018-01-01 21:39:21,585 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,593 : INFO : < 200 OK [3264]
2018-01-01 21:39:21,597 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,597 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,601 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,607 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,611 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,617 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,620 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,624 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,628 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,632 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,636 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,640 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}
2018-01-01 21:39:21,640 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,648 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,648 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 136, '_0n1': 1199}

2018-01-01 21:39:21,652 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,656 : INFO : < 200 OK [3350]
2018-01-01 21:39:21,656 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1260, '_0n1': 1211}
2018-01-01 21:39:21,660 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:21,664 : INFO : < 200 OK [3304]
2018-01-01 21:39:21,668 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 199, '_0n1': 1214}
2018-01-01 21:39:21,668 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,672 : INFO : < 200 OK [3293]
2018-01-01 21:39:21,676 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 199, '_0n1': 1214}
2018-01-01 21:39:21,676 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,680 : INFO : < 200 OK [3293]
2018-01-01 21:39:21,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 206, '_0n1': 1197}
2018-01-01 21:39:21,688 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,696 : INFO : < 200 OK [3288]
2018-01-01 21:39:21,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 206, '_0n1': 1198}
2018-01-01 21:39:21,700 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,706 : INFO : < 200 OK [3289]
2018-01-01 21:39:21,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 206, '_0n1': 1199}
2018-01-01 21:39:21,711 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,715 : INFO : < 200 OK [3302]
2018-01-01 21:39:21,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 243, '_0n1': 1211}
2018-01-01 21:39:21,719 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,721 : INFO : < 200 OK [3310]
2018-01-01 21:39:21,725 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 243, '_0n1': 1193}
2018-01-01 21:39:21,725 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,729 : INFO : < 200 OK [3308]
2018-01-01 21:39:21,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 243, '_0n1': 1198}
2018-01-01 21:39:21,733 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,737 : INFO : < 200 OK [3311]
2018-01-01 21:39:21,741 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 243, '_0n1': 1211}
2018-01-01 21:39:21,741 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,749 : INFO : < 200 OK [3310]
2018-01-01 21:39:21,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 243, '_0n1': 1193}
2018-01-01 21:39:21,753 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,757 : INFO : < 200 OK [3308]
2018-01-01 21:39:21,761 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 243, '_0n1': 1198}
2018-01-01 21:39:21,761 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,769 : INFO : < 200 OK [3311]
2018-01-01 21:39:21,773 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1192}
2018-01-01 21:39:21,773 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,777 : INFO : < 200 OK [3296]
2018-01-01 21:39:21,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1211}
2018-01-01 21:39:21,781 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,789 : INFO : < 200 OK [3299]
2018-01-01 21:39:21,789 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1214}
2018-01-01 21:39:21,793 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,797 : INFO : < 200 OK [3296]
2018-01-01 21:39:21,801 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1198}
2018-01-01 21:39:21,801 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,807 : INFO : < 200 OK [3300]
2018-01-01 21:39:21,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1192}
2018-01-01 21:39:21,813 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,817 : INFO : < 200 OK [3296]
2018-01-01 21:39:21,820 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1211}
2018-01-01 21:39:21,820 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,825 : INFO : < 200 OK [3299]
2018-01-01 21:39:21,825 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1214}
2018-01-01 21:39:21,829 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,833 : INFO : < 200 OK [3296]
2018-01-01 21:39:21,837 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1198}
2018-01-01 21:39:21,837 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,841 : INFO : < 200 OK [3300]
2018-01-01 21:39:21,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 210, '_0n1': 1214}
2018-01-01 21:39:21,845 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,849 : INFO : < 200 OK [3317]
2018-01-01 21:39:21,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 210, '_0n1': 1214}
2018-01-01 21:39:21,853 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,861 : INFO : < 200 OK [3317]
2018-01-01 21:39:21,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 246, '_0n1': 1195}
2018-01-01 21:39:21,865 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,869 : INFO : < 200 OK [3325]
2018-01-01 21:39:21,873 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 246, '_0n1': 1214}
2018-01-01 21:39:21,873 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,877 : INFO : < 200 OK [3325]
2018-01-01 21:39:21,881 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 211, '_0n1': 1211}

2018-01-01 21:39:21,881 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,885 : INFO : < 200 OK [3357]
2018-01-01 21:39:21,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1211}
2018-01-01 21:39:21,893 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,897 : INFO : < 200 OK [3314]
2018-01-01 21:39:21,901 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1199}
2018-01-01 21:39:21,901 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,906 : INFO : < 200 OK [3328]
2018-01-01 21:39:21,909 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1211}
2018-01-01 21:39:21,911 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,916 : INFO : < 200 OK [3314]
2018-01-01 21:39:21,920 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 124, '_0n1': 1199}
2018-01-01 21:39:21,921 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,925 : INFO : < 200 OK [3328]
2018-01-01 21:39:21,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 213, '_0n1': 1211}
2018-01-01 21:39:21,929 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,933 : INFO : < 200 OK [3305]
2018-01-01 21:39:21,937 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 213, '_0n1': 1199}
2018-01-01 21:39:21,937 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,941 : INFO : < 200 OK [3319]
2018-01-01 21:39:21,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 214, '_0n1': 1212}
2018-01-01 21:39:21,945 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,953 : INFO : < 200 OK [3294]
2018-01-01 21:39:21,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 214, '_0n1': 1212}
2018-01-01 21:39:21,957 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,961 : INFO : < 200 OK [3294]
2018-01-01 21:39:21,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 214, '_0n1': 1212}
2018-01-01 21:39:21,965 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,977 : INFO : < 200 OK [3294]
2018-01-01 21:39:21,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 215, '_0n1': 1214}
2018-01-01 21:39:21,985 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,989 : INFO : < 200 OK [3265]
2018-01-01 21:39:21,993 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 252, '_0n1': 1195}
2018-01-01 21:39:21,993 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:21,997 : INFO : < 200 OK [3336]
2018-01-01 21:39:22,007 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 1211}
2018-01-01 21:39:22,010 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:22,014 : INFO : < 200 OK [3286]
2018-01-01 21:39:22,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 1211}
2018-01-01 21:39:22,019 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:22,021 : INFO : < 200 OK [3286]
2018-01-01 21:39:22,025 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 56, '_0n1': 1211}
2018-01-01 21:39:22,025 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:22,033 : INFO : < 200 OK [3286]
2018-01-01 21:39:22,037 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 254, '_0n1': 1195}
2018-01-01 21:39:22,037 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,041 : INFO : < 200 OK [3328]
2018-01-01 21:39:22,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 80, '_0n1': 1211}
2018-01-01 21:39:22,049 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:22,053 : INFO : < 200 OK [3298]
2018-01-01 21:39:22,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 256, '_0n1': 1214}
2018-01-01 21:39:22,057 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,061 : INFO : < 200 OK [3287]
2018-01-01 21:39:22,065 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 83, '_0n1': 1211}
2018-01-01 21:39:22,065 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:22,069 : INFO : < 200 OK [3299]
2018-01-01 21:39:22,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 83, '_0n1': 1211}
2018-01-01 21:39:22,073 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:22,077 : INFO : < 200 OK [3299]
2018-01-01 21:39:22,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 262, '_0n1': 1212}
2018-01-01 21:39:22,089 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,093 : INFO : < 200 OK [3320]
2018-01-01 21:39:22,097 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 262, '_0n1': 1212}
2018-01-01 21:39:22,101 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,105 : INFO : < 200 OK [3320]
2018-01-01 21:39:22,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 262, '_0n1': 1212}
2018-01-01 21:39:22,109 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,114 : INFO : < 200 OK [3320]
2018-01-01 21:39:22,117 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 1211}
2018-01-01 21:39:22,118 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,121 : INFO : < 200 OK [3315]
2018-01-01 21:39:22,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 1211}
2018-01-01 21:39:22,125 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,129 : INFO : < 200 OK [3315]
2018-01-01 21:39:22,133 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 106, '_0n1': 1211}

2018-01-01 21:39:22,133 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,137 : INFO : < 200 OK [3315]
2018-01-01 21:39:22,141 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 280, '_0n1': 1195}
2018-01-01 21:39:22,141 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,153 : INFO : < 200 OK [3338]
2018-01-01 21:39:22,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 280, '_0n1': 1199}
2018-01-01 21:39:22,157 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,161 : INFO : < 200 OK [3355]
2018-01-01 21:39:22,165 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1195}
2018-01-01 21:39:22,169 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,173 : INFO : < 200 OK [3310]
2018-01-01 21:39:22,173 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1199}
2018-01-01 21:39:22,177 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,181 : INFO : < 200 OK [3327]
2018-01-01 21:39:22,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1195}
2018-01-01 21:39:22,185 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,189 : INFO : < 200 OK [3310]
2018-01-01 21:39:22,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1199}
2018-01-01 21:39:22,193 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,197 : INFO : < 200 OK [3327]
2018-01-01 21:39:22,201 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 94, '_0n1': 1211}
2018-01-01 21:39:22,201 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:22,208 : INFO : < 200 OK [3286]
2018-01-01 21:39:22,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 286, '_0n1': 1195}
2018-01-01 21:39:22,217 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,220 : INFO : < 200 OK [3350]
2018-01-01 21:39:22,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 286, '_0n1': 1199}
2018-01-01 21:39:22,225 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,229 : INFO : < 200 OK [3367]
2018-01-01 21:39:22,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 292, '_0n1': 1211}
2018-01-01 21:39:22,237 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,241 : INFO : < 200 OK [3274]
2018-01-01 21:39:22,245 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 292, '_0n1': 1211}
2018-01-01 21:39:22,245 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,249 : INFO : < 200 OK [3274]
2018-01-01 21:39:22,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 276, '_0n1': 1193}
2018-01-01 21:39:22,253 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,257 : INFO : < 200 OK [3275]
2018-01-01 21:39:22,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 276, '_0n1': 1212}
2018-01-01 21:39:22,261 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,273 : INFO : < 200 OK [3275]
2018-01-01 21:39:22,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 276, '_0n1': 1194}
2018-01-01 21:39:22,277 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,285 : INFO : < 200 OK [3281]
2018-01-01 21:39:22,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 276, '_0n1': 1196}
2018-01-01 21:39:22,289 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,293 : INFO : < 200 OK [3275]
2018-01-01 21:39:22,293 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1193}
2018-01-01 21:39:22,297 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,301 : INFO : < 200 OK [3308]
2018-01-01 21:39:22,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1212}
2018-01-01 21:39:22,307 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,311 : INFO : < 200 OK [3308]
2018-01-01 21:39:22,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1198}
2018-01-01 21:39:22,317 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,320 : INFO : < 200 OK [3311]
2018-01-01 21:39:22,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1193}
2018-01-01 21:39:22,324 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,328 : INFO : < 200 OK [3308]
2018-01-01 21:39:22,328 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1212}
2018-01-01 21:39:22,332 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,336 : INFO : < 200 OK [3308]
2018-01-01 21:39:22,340 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1198}
2018-01-01 21:39:22,340 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,344 : INFO : < 200 OK [3311]
2018-01-01 21:39:22,348 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1193}
2018-01-01 21:39:22,348 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,352 : INFO : < 200 OK [3336]
2018-01-01 21:39:22,352 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1212}
2018-01-01 21:39:22,356 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,360 : INFO : < 200 OK [3336]
2018-01-01 21:39:22,364 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1194}
2018-01-01 21:39:22,364 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,368 : INFO : < 200 OK [3342]

2018-01-01 21:39:22,372 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1193}
2018-01-01 21:39:22,376 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,380 : INFO : < 200 OK [3336]
2018-01-01 21:39:22,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1212}
2018-01-01 21:39:22,384 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,388 : INFO : < 200 OK [3336]
2018-01-01 21:39:22,392 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1194}
2018-01-01 21:39:22,392 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,400 : INFO : < 200 OK [3342]
2018-01-01 21:39:22,400 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1193}
2018-01-01 21:39:22,404 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,409 : INFO : < 200 OK [3336]
2018-01-01 21:39:22,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1212}
2018-01-01 21:39:22,413 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,418 : INFO : < 200 OK [3336]
2018-01-01 21:39:22,421 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1194}
2018-01-01 21:39:22,421 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,425 : INFO : < 200 OK [3342]
2018-01-01 21:39:22,429 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1193}
2018-01-01 21:39:22,429 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,433 : INFO : < 200 OK [3336]
2018-01-01 21:39:22,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1212}
2018-01-01 21:39:22,437 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,441 : INFO : < 200 OK [3336]
2018-01-01 21:39:22,445 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 277, '_0n1': 1194}
2018-01-01 21:39:22,445 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,449 : INFO : < 200 OK [3342]
2018-01-01 21:39:22,453 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 128, '_0n1': 1213}
2018-01-01 21:39:22,453 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,457 : INFO : < 200 OK [3333]
2018-01-01 21:39:22,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 1193}
2018-01-01 21:39:22,461 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,465 : INFO : < 200 OK [3317]
2018-01-01 21:39:22,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 1212}
2018-01-01 21:39:22,469 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,473 : INFO : < 200 OK [3317]
2018-01-01 21:39:22,477 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 1194}
2018-01-01 21:39:22,477 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,481 : INFO : < 200 OK [3323]
2018-01-01 21:39:22,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 1196}
2018-01-01 21:39:22,485 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,489 : INFO : < 200 OK [3317]
2018-01-01 21:39:22,493 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 1193}
2018-01-01 21:39:22,497 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,501 : INFO : < 200 OK [3317]
2018-01-01 21:39:22,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 1212}
2018-01-01 21:39:22,509 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,513 : INFO : < 200 OK [3317]
2018-01-01 21:39:22,516 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 1194}
2018-01-01 21:39:22,518 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,521 : INFO : < 200 OK [3323]
2018-01-01 21:39:22,521 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 294, '_0n1': 1196}
2018-01-01 21:39:22,525 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,529 : INFO : < 200 OK [3317]
2018-01-01 21:39:22,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1193}
2018-01-01 21:39:22,533 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,537 : INFO : < 200 OK [3298]
2018-01-01 21:39:22,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1212}
2018-01-01 21:39:22,541 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,549 : INFO : < 200 OK [3298]
2018-01-01 21:39:22,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1194}
2018-01-01 21:39:22,553 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,557 : INFO : < 200 OK [3304]
2018-01-01 21:39:22,561 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1196}
2018-01-01 21:39:22,561 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,565 : INFO : < 200 OK [3298]
2018-01-01 21:39:22,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 146, '_0n1': 1217}
2018-01-01 21:39:22,569 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,573 : INFO : < 200 OK [3298]
2018-01-01 21:39:22,577 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 278, '_0n1': 1193}
2018-01-01 21:39:22,577 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,581 : INFO : < 200 OK [3337]
2018-01-01 21:39:22,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 278, '_0n1': 1212}

2018-01-01 21:39:22,585 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,589 : INFO : < 200 OK [3337]
2018-01-01 21:39:22,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 278, '_0n1': 1194}
2018-01-01 21:39:22,597 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,601 : INFO : < 200 OK [3343]
2018-01-01 21:39:22,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 1193}
2018-01-01 21:39:22,609 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,613 : INFO : < 200 OK [3316]
2018-01-01 21:39:22,617 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 1214}
2018-01-01 21:39:22,619 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,621 : INFO : < 200 OK [3315]
2018-01-01 21:39:22,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 1217}
2018-01-01 21:39:22,625 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,633 : INFO : < 200 OK [3316]
2018-01-01 21:39:22,633 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 1199}
2018-01-01 21:39:22,637 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,641 : INFO : < 200 OK [3332]
2018-01-01 21:39:22,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1193}
2018-01-01 21:39:22,645 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,649 : INFO : < 200 OK [3299]
2018-01-01 21:39:22,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1198}
2018-01-01 21:39:22,653 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,657 : INFO : < 200 OK [3302]
2018-01-01 21:39:22,657 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1199}
2018-01-01 21:39:22,661 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,665 : INFO : < 200 OK [3315]
2018-01-01 21:39:22,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1193}
2018-01-01 21:39:22,669 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,673 : INFO : < 200 OK [3299]
2018-01-01 21:39:22,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1198}
2018-01-01 21:39:22,677 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,681 : INFO : < 200 OK [3302]
2018-01-01 21:39:22,685 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1199}
2018-01-01 21:39:22,685 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,689 : INFO : < 200 OK [3315]
2018-01-01 21:39:22,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1193}
2018-01-01 21:39:22,693 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,697 : INFO : < 200 OK [3299]
2018-01-01 21:39:22,701 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1198}
2018-01-01 21:39:22,701 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,708 : INFO : < 200 OK [3302]
2018-01-01 21:39:22,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1199}
2018-01-01 21:39:22,715 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,719 : INFO : < 200 OK [3315]
2018-01-01 21:39:22,721 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1193}
2018-01-01 21:39:22,725 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,729 : INFO : < 200 OK [3299]
2018-01-01 21:39:22,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1198}
2018-01-01 21:39:22,737 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,741 : INFO : < 200 OK [3302]
2018-01-01 21:39:22,741 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 279, '_0n1': 1199}
2018-01-01 21:39:22,745 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,749 : INFO : < 200 OK [3315]
2018-01-01 21:39:22,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 296, '_0n1': 1193}
2018-01-01 21:39:22,753 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,757 : INFO : < 200 OK [3327]
2018-01-01 21:39:22,761 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 296, '_0n1': 1212}
2018-01-01 21:39:22,761 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,769 : INFO : < 200 OK [3327]
2018-01-01 21:39:22,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 296, '_0n1': 1194}
2018-01-01 21:39:22,773 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,777 : INFO : < 200 OK [3333]
2018-01-01 21:39:22,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 130, '_0n1': 1212}
2018-01-01 21:39:22,781 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,785 : INFO : < 200 OK [3319]
2018-01-01 21:39:22,789 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 130, '_0n1': 1213}
2018-01-01 21:39:22,789 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,793 : INFO : < 200 OK [3318]
2018-01-01 21:39:22,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 300, '_0n1': 1193}
2018-01-01 21:39:22,797 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,801 : INFO : < 200 OK [3274]
2018-01-01 21:39:22,805 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 300, '_0n1': 1212}
2018-01-01 21:39:22,807 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,812 : INFO : < 200 OK [3274]
2018-01-01 21:39:22,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 300, '_0n1': 1194}

2018-01-01 21:39:22,816 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,821 : INFO : < 200 OK [3280]
2018-01-01 21:39:22,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 297, '_0n1': 1193}
2018-01-01 21:39:22,825 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,829 : INFO : < 200 OK [3343]
2018-01-01 21:39:22,833 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 297, '_0n1': 1212}
2018-01-01 21:39:22,833 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,837 : INFO : < 200 OK [3343]
2018-01-01 21:39:22,841 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 297, '_0n1': 1194}
2018-01-01 21:39:22,841 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,845 : INFO : < 200 OK [3349]
2018-01-01 21:39:22,849 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 301, '_0n1': 1193}
2018-01-01 21:39:22,849 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,853 : INFO : < 200 OK [3283]
2018-01-01 21:39:22,857 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 301, '_0n1': 1212}
2018-01-01 21:39:22,857 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,861 : INFO : < 200 OK [3283]
2018-01-01 21:39:22,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 301, '_0n1': 1194}
2018-01-01 21:39:22,865 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,869 : INFO : < 200 OK [3289]
2018-01-01 21:39:22,873 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 301, '_0n1': 1199}
2018-01-01 21:39:22,873 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,881 : INFO : < 200 OK [3299]
2018-01-01 21:39:22,885 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 298, '_0n1': 1193}
2018-01-01 21:39:22,885 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,889 : INFO : < 200 OK [3314]
2018-01-01 21:39:22,897 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 298, '_0n1': 1212}
2018-01-01 21:39:22,897 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,901 : INFO : < 200 OK [3314]
2018-01-01 21:39:22,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 298, '_0n1': 1194}
2018-01-01 21:39:22,908 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,912 : INFO : < 200 OK [3320]
2018-01-01 21:39:22,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 298, '_0n1': 1196}
2018-01-01 21:39:22,916 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,920 : INFO : < 200 OK [3314]
2018-01-01 21:39:22,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 298, '_0n1': 1199}
2018-01-01 21:39:22,925 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,929 : INFO : < 200 OK [3330]
2018-01-01 21:39:22,933 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 150, '_0n1': 1193}
2018-01-01 21:39:22,933 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,937 : INFO : < 200 OK [3315]
2018-01-01 21:39:22,941 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 150, '_0n1': 1194}
2018-01-01 21:39:22,941 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,945 : INFO : < 200 OK [3321]
2018-01-01 21:39:22,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 150, '_0n1': 1213}
2018-01-01 21:39:22,949 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,953 : INFO : < 200 OK [3314]
2018-01-01 21:39:22,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 302, '_0n1': 1193}
2018-01-01 21:39:22,957 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,961 : INFO : < 200 OK [3322]
2018-01-01 21:39:22,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 302, '_0n1': 1198}
2018-01-01 21:39:22,965 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,969 : INFO : < 200 OK [3325]
2018-01-01 21:39:22,973 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 299, '_0n1': 1193}
2018-01-01 21:39:22,973 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,981 : INFO : < 200 OK [3302]
2018-01-01 21:39:22,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 299, '_0n1': 1198}
2018-01-01 21:39:22,985 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:22,993 : INFO : < 200 OK [3305]
2018-01-01 21:39:22,993 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1193}
2018-01-01 21:39:22,997 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,001 : INFO : < 200 OK [3317]
2018-01-01 21:39:23,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1212}
2018-01-01 21:39:23,007 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,011 : INFO : < 200 OK [3317]
2018-01-01 21:39:23,013 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1194}
2018-01-01 21:39:23,015 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,019 : INFO : < 200 OK [3323]
2018-01-01 21:39:23,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1196}
2018-01-01 21:39:23,021 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,025 : INFO : < 200 OK [3317]
2018-01-01 21:39:23,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1193}
2018-01-01 21:39:23,029 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,033 : INFO : < 200 OK [3317]
2018-01-01 21:39:23,037 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1212}

2018-01-01 21:39:23,037 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,041 : INFO : < 200 OK [3317]
2018-01-01 21:39:23,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1194}
2018-01-01 21:39:23,045 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,049 : INFO : < 200 OK [3323]
2018-01-01 21:39:23,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1196}
2018-01-01 21:39:23,053 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,057 : INFO : < 200 OK [3317]
2018-01-01 21:39:23,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1193}
2018-01-01 21:39:23,061 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,065 : INFO : < 200 OK [3317]
2018-01-01 21:39:23,069 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1212}
2018-01-01 21:39:23,069 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,073 : INFO : < 200 OK [3317]
2018-01-01 21:39:23,077 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1194}
2018-01-01 21:39:23,077 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,081 : INFO : < 200 OK [3323]
2018-01-01 21:39:23,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 303, '_0n1': 1196}
2018-01-01 21:39:23,085 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,089 : INFO : < 200 OK [3317]
2018-01-01 21:39:23,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 320, '_0n1': 1193}
2018-01-01 21:39:23,093 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,097 : INFO : < 200 OK [3284]
2018-01-01 21:39:23,101 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 320, '_0n1': 1217}
2018-01-01 21:39:23,106 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,111 : INFO : < 200 OK [3284]
2018-01-01 21:39:23,114 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 320, '_0n1': 1199}
2018-01-01 21:39:23,116 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,121 : INFO : < 200 OK [3300]
2018-01-01 21:39:23,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 321, '_0n1': 1193}
2018-01-01 21:39:23,125 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,129 : INFO : < 200 OK [3330]
2018-01-01 21:39:23,133 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 321, '_0n1': 1212}
2018-01-01 21:39:23,133 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,137 : INFO : < 200 OK [3330]
2018-01-01 21:39:23,141 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 321, '_0n1': 1194}
2018-01-01 21:39:23,141 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,145 : INFO : < 200 OK [3336]
2018-01-01 21:39:23,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 321, '_0n1': 1217}
2018-01-01 21:39:23,153 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,157 : INFO : < 200 OK [3330]
2018-01-01 21:39:23,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 321, '_0n1': 1199}
2018-01-01 21:39:23,161 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,165 : INFO : < 200 OK [3346]
2018-01-01 21:39:23,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 1193}
2018-01-01 21:39:23,169 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,173 : INFO : < 200 OK [3316]
2018-01-01 21:39:23,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 1212}
2018-01-01 21:39:23,177 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,181 : INFO : < 200 OK [3316]
2018-01-01 21:39:23,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 1194}
2018-01-01 21:39:23,185 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,193 : INFO : < 200 OK [3322]
2018-01-01 21:39:23,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 1198}
2018-01-01 21:39:23,197 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,205 : INFO : < 200 OK [3319]
2018-01-01 21:39:23,208 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 154, '_0n1': 1212}
2018-01-01 21:39:23,210 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,216 : INFO : < 200 OK [3324]
2018-01-01 21:39:23,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 154, '_0n1': 1213}
2018-01-01 21:39:23,221 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,225 : INFO : < 200 OK [3323]
2018-01-01 21:39:23,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 322, '_0n1': 1193}
2018-01-01 21:39:23,233 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,237 : INFO : < 200 OK [3308]
2018-01-01 21:39:23,241 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 322, '_0n1': 1198}
2018-01-01 21:39:23,241 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,245 : INFO : < 200 OK [3311]
2018-01-01 21:39:23,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1193}
2018-01-01 21:39:23,253 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,261 : INFO : < 200 OK [3297]
2018-01-01 21:39:23,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1212}
2018-01-01 21:39:23,265 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,273 : INFO : < 200 OK [3297]
2018-01-01 21:39:23,277 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1194}

2018-01-01 21:39:23,277 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,281 : INFO : < 200 OK [3303]
2018-01-01 21:39:23,289 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1217}
2018-01-01 21:39:23,289 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,293 : INFO : < 200 OK [3297]
2018-01-01 21:39:23,297 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1199}
2018-01-01 21:39:23,297 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,301 : INFO : < 200 OK [3313]
2018-01-01 21:39:23,309 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1193}
2018-01-01 21:39:23,310 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,315 : INFO : < 200 OK [3297]
2018-01-01 21:39:23,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1212}
2018-01-01 21:39:23,321 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,325 : INFO : < 200 OK [3297]
2018-01-01 21:39:23,325 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1194}
2018-01-01 21:39:23,329 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,333 : INFO : < 200 OK [3303]
2018-01-01 21:39:23,337 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1217}
2018-01-01 21:39:23,337 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,341 : INFO : < 200 OK [3297]
2018-01-01 21:39:23,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 306, '_0n1': 1199}
2018-01-01 21:39:23,349 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,353 : INFO : < 200 OK [3313]
2018-01-01 21:39:23,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 1193}
2018-01-01 21:39:23,361 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,365 : INFO : < 200 OK [3331]
2018-01-01 21:39:23,369 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 1212}
2018-01-01 21:39:23,369 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,373 : INFO : < 200 OK [3331]
2018-01-01 21:39:23,377 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 1194}
2018-01-01 21:39:23,377 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,381 : INFO : < 200 OK [3337]
2018-01-01 21:39:23,385 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 1198}
2018-01-01 21:39:23,385 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,393 : INFO : < 200 OK [3334]
2018-01-01 21:39:23,397 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 307, '_0n1': 1198}
2018-01-01 21:39:23,397 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,401 : INFO : < 200 OK [3327]
2018-01-01 21:39:23,408 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 324, '_0n1': 1214}
2018-01-01 21:39:23,410 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,415 : INFO : < 200 OK [3286]
2018-01-01 21:39:23,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 324, '_0n1': 1216}
2018-01-01 21:39:23,421 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,425 : INFO : < 200 OK [3288]
2018-01-01 21:39:23,425 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 324, '_0n1': 1199}
2018-01-01 21:39:23,429 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,437 : INFO : < 200 OK [3303]
2018-01-01 21:39:23,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 308, '_0n1': 1193}
2018-01-01 21:39:23,441 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,445 : INFO : < 200 OK [3293]
2018-01-01 21:39:23,449 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 308, '_0n1': 1212}
2018-01-01 21:39:23,453 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,457 : INFO : < 200 OK [3293]
2018-01-01 21:39:23,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 308, '_0n1': 1194}
2018-01-01 21:39:23,461 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,469 : INFO : < 200 OK [3299]
2018-01-01 21:39:23,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 308, '_0n1': 1199}
2018-01-01 21:39:23,473 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,477 : INFO : < 200 OK [3309]
2018-01-01 21:39:23,477 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 1193}
2018-01-01 21:39:23,481 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,485 : INFO : < 200 OK [3283]
2018-01-01 21:39:23,489 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 1214}
2018-01-01 21:39:23,489 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,493 : INFO : < 200 OK [3282]
2018-01-01 21:39:23,497 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 1217}
2018-01-01 21:39:23,497 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,501 : INFO : < 200 OK [3283]
2018-01-01 21:39:23,506 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 1199}
2018-01-01 21:39:23,508 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,512 : INFO : < 200 OK [3299]
2018-01-01 21:39:23,514 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1193}
2018-01-01 21:39:23,516 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,520 : INFO : < 200 OK [3275]
2018-01-01 21:39:23,521 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1212}

2018-01-01 21:39:23,525 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,529 : INFO : < 200 OK [3275]
2018-01-01 21:39:23,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1194}
2018-01-01 21:39:23,533 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,537 : INFO : < 200 OK [3281]
2018-01-01 21:39:23,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1193}
2018-01-01 21:39:23,541 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,545 : INFO : < 200 OK [3275]
2018-01-01 21:39:23,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1212}
2018-01-01 21:39:23,549 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,553 : INFO : < 200 OK [3275]
2018-01-01 21:39:23,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1194}
2018-01-01 21:39:23,557 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,561 : INFO : < 200 OK [3281]
2018-01-01 21:39:23,565 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1193}
2018-01-01 21:39:23,565 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,569 : INFO : < 200 OK [3275]
2018-01-01 21:39:23,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1212}
2018-01-01 21:39:23,573 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,577 : INFO : < 200 OK [3275]
2018-01-01 21:39:23,581 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1194}
2018-01-01 21:39:23,581 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,585 : INFO : < 200 OK [3281]
2018-01-01 21:39:23,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1193}
2018-01-01 21:39:23,589 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,593 : INFO : < 200 OK [3275]
2018-01-01 21:39:23,597 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1212}
2018-01-01 21:39:23,597 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,601 : INFO : < 200 OK [3275]
2018-01-01 21:39:23,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 309, '_0n1': 1194}
2018-01-01 21:39:23,605 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,612 : INFO : < 200 OK [3281]
2018-01-01 21:39:23,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 1193}
2018-01-01 21:39:23,619 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,621 : INFO : < 200 OK [3316]
2018-01-01 21:39:23,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 1214}
2018-01-01 21:39:23,625 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,629 : INFO : < 200 OK [3315]
2018-01-01 21:39:23,633 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 1217}
2018-01-01 21:39:23,633 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,641 : INFO : < 200 OK [3316]
2018-01-01 21:39:23,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 1199}
2018-01-01 21:39:23,649 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,653 : INFO : < 200 OK [3332]
2018-01-01 21:39:23,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 310, '_0n1': 1193}
2018-01-01 21:39:23,657 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,661 : INFO : < 200 OK [3323]
2018-01-01 21:39:23,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 310, '_0n1': 1198}
2018-01-01 21:39:23,665 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,673 : INFO : < 200 OK [3326]
2018-01-01 21:39:23,673 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 310, '_0n1': 1193}
2018-01-01 21:39:23,677 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,681 : INFO : < 200 OK [3323]
2018-01-01 21:39:23,685 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 310, '_0n1': 1198}
2018-01-01 21:39:23,685 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,693 : INFO : < 200 OK [3326]
2018-01-01 21:39:23,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 310, '_0n1': 1193}
2018-01-01 21:39:23,697 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,701 : INFO : < 200 OK [3323]
2018-01-01 21:39:23,701 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 310, '_0n1': 1198}
2018-01-01 21:39:23,706 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,711 : INFO : < 200 OK [3326]
2018-01-01 21:39:23,713 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 327, '_0n1': 1193}
2018-01-01 21:39:23,715 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,720 : INFO : < 200 OK [3341]
2018-01-01 21:39:23,722 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 327, '_0n1': 1212}
2018-01-01 21:39:23,722 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,726 : INFO : < 200 OK [3341]
2018-01-01 21:39:23,730 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 327, '_0n1': 1194}
2018-01-01 21:39:23,730 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,734 : INFO : < 200 OK [3347]
2018-01-01 21:39:23,738 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 327, '_0n1': 1198}
2018-01-01 21:39:23,738 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,742 : INFO : < 200 OK [3344]
2018-01-01 21:39:23,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 328, '_0n1': 1193}

2018-01-01 21:39:23,746 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,754 : INFO : < 200 OK [3309]
2018-01-01 21:39:23,754 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 328, '_0n1': 1212}
2018-01-01 21:39:23,758 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,762 : INFO : < 200 OK [3309]
2018-01-01 21:39:23,766 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 328, '_0n1': 1194}
2018-01-01 21:39:23,766 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,770 : INFO : < 200 OK [3315]
2018-01-01 21:39:23,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 312, '_0n1': 1193}
2018-01-01 21:39:23,774 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,778 : INFO : < 200 OK [3350]
2018-01-01 21:39:23,782 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 312, '_0n1': 1198}
2018-01-01 21:39:23,782 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,786 : INFO : < 200 OK [3353]
2018-01-01 21:39:23,790 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 206, '_0n1': 1197}
2018-01-01 21:39:23,790 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,794 : INFO : < 200 OK [3288]
2018-01-01 21:39:23,798 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 206, '_0n1': 1198}
2018-01-01 21:39:23,798 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,802 : INFO : < 200 OK [3289]
2018-01-01 21:39:23,807 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 206, '_0n1': 1199}
2018-01-01 21:39:23,809 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,814 : INFO : < 200 OK [3302]
2018-01-01 21:39:23,819 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 329, '_0n1': 1198}
2018-01-01 21:39:23,822 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,826 : INFO : < 200 OK [3325]
2018-01-01 21:39:23,830 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1193}
2018-01-01 21:39:23,830 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,834 : INFO : < 200 OK [3291]
2018-01-01 21:39:23,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1198}
2018-01-01 21:39:23,838 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,842 : INFO : < 200 OK [3294]
2018-01-01 21:39:23,846 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1193}
2018-01-01 21:39:23,846 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,854 : INFO : < 200 OK [3291]
2018-01-01 21:39:23,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1198}
2018-01-01 21:39:23,858 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,862 : INFO : < 200 OK [3294]
2018-01-01 21:39:23,866 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1193}
2018-01-01 21:39:23,866 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,870 : INFO : < 200 OK [3291]
2018-01-01 21:39:23,874 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1198}
2018-01-01 21:39:23,874 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,878 : INFO : < 200 OK [3294]
2018-01-01 21:39:23,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 330, '_0n1': 1217}
2018-01-01 21:39:23,886 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,890 : INFO : < 200 OK [3309]
2018-01-01 21:39:23,890 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 314, '_0n1': 1193}
2018-01-01 21:39:23,894 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,898 : INFO : < 200 OK [3293]
2018-01-01 21:39:23,902 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 314, '_0n1': 1212}
2018-01-01 21:39:23,902 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,908 : INFO : < 200 OK [3293]
2018-01-01 21:39:23,911 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 314, '_0n1': 1194}
2018-01-01 21:39:23,913 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,917 : INFO : < 200 OK [3299]
2018-01-01 21:39:23,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 315, '_0n1': 1216}
2018-01-01 21:39:23,922 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,926 : INFO : < 200 OK [3281]
2018-01-01 21:39:23,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 332, '_0n1': 1217}
2018-01-01 21:39:23,930 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,934 : INFO : < 200 OK [3294]
2018-01-01 21:39:23,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 316, '_0n1': 1214}
2018-01-01 21:39:23,938 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,942 : INFO : < 200 OK [3295]
2018-01-01 21:39:23,946 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 316, '_0n1': 1199}
2018-01-01 21:39:23,950 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,954 : INFO : < 200 OK [3312]
2018-01-01 21:39:23,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 316, '_0n1': 1214}
2018-01-01 21:39:23,958 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,966 : INFO : < 200 OK [3295]
2018-01-01 21:39:23,966 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 316, '_0n1': 1199}
2018-01-01 21:39:23,970 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,974 : INFO : < 200 OK [3312]
2018-01-01 21:39:23,978 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 333, '_0n1': 1198}

2018-01-01 21:39:23,982 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,986 : INFO : < 200 OK [3302]
2018-01-01 21:39:23,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 333, '_0n1': 1199}
2018-01-01 21:39:23,990 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:23,994 : INFO : < 200 OK [3315]
2018-01-01 21:39:24,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 334, '_0n1': 1216}
2018-01-01 21:39:24,006 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,010 : INFO : < 200 OK [3289]
2018-01-01 21:39:24,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 1216}
2018-01-01 21:39:24,019 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,022 : INFO : < 200 OK [3302]
2018-01-01 21:39:24,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 1199}
2018-01-01 21:39:24,026 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,030 : INFO : < 200 OK [3317]
2018-01-01 21:39:24,034 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 1216}
2018-01-01 21:39:24,038 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,042 : INFO : < 200 OK [3302]
2018-01-01 21:39:24,046 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 1199}
2018-01-01 21:39:24,050 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,054 : INFO : < 200 OK [3317]
2018-01-01 21:39:24,058 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 1216}
2018-01-01 21:39:24,058 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,062 : INFO : < 200 OK [3302]
2018-01-01 21:39:24,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 335, '_0n1': 1199}
2018-01-01 21:39:24,066 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,070 : INFO : < 200 OK [3317]
2018-01-01 21:39:24,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 319, '_0n1': 1216}
2018-01-01 21:39:24,074 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,082 : INFO : < 200 OK [3281]
2018-01-01 21:39:24,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1193}
2018-01-01 21:39:24,086 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,090 : INFO : < 200 OK [3299]
2018-01-01 21:39:24,090 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1198}
2018-01-01 21:39:24,094 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,098 : INFO : < 200 OK [3302]
2018-01-01 21:39:24,102 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1193}
2018-01-01 21:39:24,102 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,107 : INFO : < 200 OK [3299]
2018-01-01 21:39:24,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1198}
2018-01-01 21:39:24,111 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,115 : INFO : < 200 OK [3302]
2018-01-01 21:39:24,118 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1193}
2018-01-01 21:39:24,120 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,122 : INFO : < 200 OK [3299]
2018-01-01 21:39:24,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1198}
2018-01-01 21:39:24,126 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,130 : INFO : < 200 OK [3302]
2018-01-01 21:39:24,134 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 337, '_0n1': 1193}
2018-01-01 21:39:24,134 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,138 : INFO : < 200 OK [3293]
2018-01-01 21:39:24,142 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 337, '_0n1': 1194}
2018-01-01 21:39:24,142 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,146 : INFO : < 200 OK [3299]
2018-01-01 21:39:24,150 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 337, '_0n1': 1217}
2018-01-01 21:39:24,150 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,158 : INFO : < 200 OK [3293]
2018-01-01 21:39:24,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 338, '_0n1': 1193}
2018-01-01 21:39:24,162 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,170 : INFO : < 200 OK [3287]
2018-01-01 21:39:24,174 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 338, '_0n1': 1212}
2018-01-01 21:39:24,178 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,182 : INFO : < 200 OK [3287]
2018-01-01 21:39:24,186 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 338, '_0n1': 1194}
2018-01-01 21:39:24,190 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,194 : INFO : < 200 OK [3293]
2018-01-01 21:39:24,198 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 339, '_0n1': 1216}
2018-01-01 21:39:24,202 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,206 : INFO : < 200 OK [3277]
2018-01-01 21:39:24,210 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 1212}
2018-01-01 21:39:24,212 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,216 : INFO : < 200 OK [3325]
2018-01-01 21:39:24,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 1198}
2018-01-01 21:39:24,220 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,222 : INFO : < 200 OK [3328]
2018-01-01 21:39:24,226 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 1212}

2018-01-01 21:39:24,226 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,230 : INFO : < 200 OK [3325]
2018-01-01 21:39:24,234 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 1198}
2018-01-01 21:39:24,234 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,238 : INFO : < 200 OK [3328]
2018-01-01 21:39:24,242 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 1212}
2018-01-01 21:39:24,246 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,250 : INFO : < 200 OK [3325]
2018-01-01 21:39:24,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 343, '_0n1': 1198}
2018-01-01 21:39:24,254 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,262 : INFO : < 200 OK [3328]
2018-01-01 21:39:24,262 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1240, '_0n1': 1198}
2018-01-01 21:39:24,266 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:24,270 : INFO : < 200 OK [3323]
2018-01-01 21:39:24,274 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1302, '_0n1': 1212}
2018-01-01 21:39:24,274 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:24,278 : INFO : < 200 OK [3338]
2018-01-01 21:39:24,282 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1195}
2018-01-01 21:39:24,282 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,286 : INFO : < 200 OK [3299]
2018-01-01 21:39:24,290 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1199}
2018-01-01 21:39:24,290 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,294 : INFO : < 200 OK [3316]
2018-01-01 21:39:24,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1195}
2018-01-01 21:39:24,298 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,302 : INFO : < 200 OK [3299]
2018-01-01 21:39:24,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1199}
2018-01-01 21:39:24,308 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,311 : INFO : < 200 OK [3316]
2018-01-01 21:39:24,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1195}
2018-01-01 21:39:24,316 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,320 : INFO : < 200 OK [3299]
2018-01-01 21:39:24,322 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1199}
2018-01-01 21:39:24,322 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,326 : INFO : < 200 OK [3316]
2018-01-01 21:39:24,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 344, '_0n1': 1195}
2018-01-01 21:39:24,334 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,338 : INFO : < 200 OK [3318]
2018-01-01 21:39:24,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 252, '_0n1': 1195}
2018-01-01 21:39:24,342 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,346 : INFO : < 200 OK [3336]
2018-01-01 21:39:24,354 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 1195}
2018-01-01 21:39:24,354 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,358 : INFO : < 200 OK [3278]
2018-01-01 21:39:24,366 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 1195}
2018-01-01 21:39:24,366 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,370 : INFO : < 200 OK [3278]
2018-01-01 21:39:24,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 1195}
2018-01-01 21:39:24,374 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,378 : INFO : < 200 OK [3278]
2018-01-01 21:39:24,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 345, '_0n1': 1195}
2018-01-01 21:39:24,382 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,390 : INFO : < 200 OK [3298]
2018-01-01 21:39:24,390 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 345, '_0n1': 1195}
2018-01-01 21:39:24,394 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,398 : INFO : < 200 OK [3298]
2018-01-01 21:39:24,402 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 1195}
2018-01-01 21:39:24,402 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,408 : INFO : < 200 OK [3278]
2018-01-01 21:39:24,410 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 1195}
2018-01-01 21:39:24,412 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,416 : INFO : < 200 OK [3278]
2018-01-01 21:39:24,420 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 1195}
2018-01-01 21:39:24,422 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,422 : INFO : < 200 OK [3278]
2018-01-01 21:39:24,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 1195}
2018-01-01 21:39:24,430 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,434 : INFO : < 200 OK [3270]
2018-01-01 21:39:24,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 1195}
2018-01-01 21:39:24,438 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,442 : INFO : < 200 OK [3270]
2018-01-01 21:39:24,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 1195}
2018-01-01 21:39:24,450 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,454 : INFO : < 200 OK [3270]
2018-01-01 21:39:24,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 1195}

2018-01-01 21:39:24,458 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,462 : INFO : < 200 OK [3274]
2018-01-01 21:39:24,466 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 1195}
2018-01-01 21:39:24,466 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,470 : INFO : < 200 OK [3274]
2018-01-01 21:39:24,474 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 1195}
2018-01-01 21:39:24,474 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,478 : INFO : < 200 OK [3274]
2018-01-01 21:39:24,482 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 347, '_0n1': 1211}
2018-01-01 21:39:24,482 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,486 : INFO : < 200 OK [3284]
2018-01-01 21:39:24,490 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 347, '_0n1': 1211}
2018-01-01 21:39:24,490 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,498 : INFO : < 200 OK [3284]
2018-01-01 21:39:24,502 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 364, '_0n1': 1195}
2018-01-01 21:39:24,507 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,511 : INFO : < 200 OK [3304]
2018-01-01 21:39:24,513 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 254, '_0n1': 1195}
2018-01-01 21:39:24,515 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,520 : INFO : < 200 OK [3328]
2018-01-01 21:39:24,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 1195}
2018-01-01 21:39:24,522 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,526 : INFO : < 200 OK [3305]
2018-01-01 21:39:24,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 1195}
2018-01-01 21:39:24,530 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,538 : INFO : < 200 OK [3305]
2018-01-01 21:39:24,542 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 1195}
2018-01-01 21:39:24,542 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,546 : INFO : < 200 OK [3305]
2018-01-01 21:39:24,550 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 1195}
2018-01-01 21:39:24,550 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,554 : INFO : < 200 OK [3305]
2018-01-01 21:39:24,558 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 349, '_0n1': 1195}
2018-01-01 21:39:24,562 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,566 : INFO : < 200 OK [3313]
2018-01-01 21:39:24,570 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 1195}
2018-01-01 21:39:24,570 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,574 : INFO : < 200 OK [3274]
2018-01-01 21:39:24,578 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 1195}
2018-01-01 21:39:24,578 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,582 : INFO : < 200 OK [3274]
2018-01-01 21:39:24,586 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 1195}
2018-01-01 21:39:24,586 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,590 : INFO : < 200 OK [3274]
2018-01-01 21:39:24,594 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 350, '_0n1': 1195}
2018-01-01 21:39:24,594 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,598 : INFO : < 200 OK [3323]
2018-01-01 21:39:24,602 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 367, '_0n1': 1196}
2018-01-01 21:39:24,602 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,608 : INFO : < 200 OK [3308]
2018-01-01 21:39:24,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1212}
2018-01-01 21:39:24,613 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,619 : INFO : < 200 OK [3278]
2018-01-01 21:39:24,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1195}
2018-01-01 21:39:24,622 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,626 : INFO : < 200 OK [3277]
2018-01-01 21:39:24,630 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1212}
2018-01-01 21:39:24,634 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,638 : INFO : < 200 OK [3278]
2018-01-01 21:39:24,642 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1195}
2018-01-01 21:39:24,642 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,646 : INFO : < 200 OK [3277]
2018-01-01 21:39:24,650 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1212}
2018-01-01 21:39:24,650 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,654 : INFO : < 200 OK [3278]
2018-01-01 21:39:24,658 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1195}
2018-01-01 21:39:24,662 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,666 : INFO : < 200 OK [3277]
2018-01-01 21:39:24,670 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 369, '_0n1': 1195}
2018-01-01 21:39:24,674 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,678 : INFO : < 200 OK [3364]
2018-01-01 21:39:24,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 353, '_0n1': 1195}
2018-01-01 21:39:24,682 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,686 : INFO : < 200 OK [3275]
2018-01-01 21:39:24,690 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 353, '_0n1': 1195}

2018-01-01 21:39:24,690 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,694 : INFO : < 200 OK [3275]
2018-01-01 21:39:24,702 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 280, '_0n1': 1195}
2018-01-01 21:39:24,702 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,708 : INFO : < 200 OK [3338]
2018-01-01 21:39:24,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 280, '_0n1': 1199}
2018-01-01 21:39:24,713 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,717 : INFO : < 200 OK [3355]
2018-01-01 21:39:24,720 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 354, '_0n1': 1214}
2018-01-01 21:39:24,722 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,722 : INFO : < 200 OK [3317]
2018-01-01 21:39:24,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 371, '_0n1': 1211}
2018-01-01 21:39:24,730 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,734 : INFO : < 200 OK [3287]
2018-01-01 21:39:24,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 371, '_0n1': 1211}
2018-01-01 21:39:24,738 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,742 : INFO : < 200 OK [3287]
2018-01-01 21:39:24,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 286, '_0n1': 1195}
2018-01-01 21:39:24,746 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,750 : INFO : < 200 OK [3350]
2018-01-01 21:39:24,754 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 286, '_0n1': 1199}
2018-01-01 21:39:24,754 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,758 : INFO : < 200 OK [3367]
2018-01-01 21:39:24,762 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 355, '_0n1': 1195}
2018-01-01 21:39:24,762 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,770 : INFO : < 200 OK [3288]
2018-01-01 21:39:24,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 1195}
2018-01-01 21:39:24,778 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,782 : INFO : < 200 OK [3279]
2018-01-01 21:39:24,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 1195}
2018-01-01 21:39:24,786 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,794 : INFO : < 200 OK [3279]
2018-01-01 21:39:24,794 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 1195}
2018-01-01 21:39:24,798 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,802 : INFO : < 200 OK [3279]
2018-01-01 21:39:24,807 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 1195}
2018-01-01 21:39:24,809 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,813 : INFO : < 200 OK [3279]
2018-01-01 21:39:24,819 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 1211}
2018-01-01 21:39:24,820 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:24,822 : INFO : < 200 OK [3307]
2018-01-01 21:39:24,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 1211}
2018-01-01 21:39:24,826 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:24,830 : INFO : < 200 OK [3307]
2018-01-01 21:39:24,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 66, '_0n1': 1211}
2018-01-01 21:39:24,834 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:24,838 : INFO : < 200 OK [3307]
2018-01-01 21:39:24,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 1196}
2018-01-01 21:39:24,846 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:24,850 : INFO : < 200 OK [3301]
2018-01-01 21:39:24,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 1196}
2018-01-01 21:39:24,854 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:24,858 : INFO : < 200 OK [3301]
2018-01-01 21:39:24,862 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 49, '_0n1': 1196}
2018-01-01 21:39:24,862 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:24,866 : INFO : < 200 OK [3301]
2018-01-01 21:39:24,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 359, '_0n1': 1211}
2018-01-01 21:39:24,870 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,874 : INFO : < 200 OK [3292]
2018-01-01 21:39:24,878 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 1211}
2018-01-01 21:39:24,882 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,890 : INFO : < 200 OK [3314]
2018-01-01 21:39:24,890 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 1211}
2018-01-01 21:39:24,894 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,898 : INFO : < 200 OK [3314]
2018-01-01 21:39:24,902 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 1211}
2018-01-01 21:39:24,902 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,910 : INFO : < 200 OK [3314]
2018-01-01 21:39:24,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 1211}
2018-01-01 21:39:24,917 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,922 : INFO : < 200 OK [3314]
2018-01-01 21:39:24,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 376, '_0n1': 1211}
2018-01-01 21:39:24,926 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,930 : INFO : < 200 OK [3314]
2018-01-01 21:39:24,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 380, '_0n1': 1211}

2018-01-01 21:39:24,934 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,938 : INFO : < 200 OK [3307]
2018-01-01 21:39:24,942 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 380, '_0n1': 1211}
2018-01-01 21:39:24,946 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,950 : INFO : < 200 OK [3307]
2018-01-01 21:39:24,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1211}
2018-01-01 21:39:24,954 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,958 : INFO : < 200 OK [3347]
2018-01-01 21:39:24,962 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1211}
2018-01-01 21:39:24,962 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,966 : INFO : < 200 OK [3347]
2018-01-01 21:39:24,970 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1211}
2018-01-01 21:39:24,970 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,974 : INFO : < 200 OK [3347]
2018-01-01 21:39:24,978 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1211}
2018-01-01 21:39:24,978 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,982 : INFO : < 200 OK [3347]
2018-01-01 21:39:24,986 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1211}
2018-01-01 21:39:24,986 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,990 : INFO : < 200 OK [3347]
2018-01-01 21:39:24,994 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 382, '_0n1': 1211}
2018-01-01 21:39:24,994 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:24,998 : INFO : < 200 OK [3311]
2018-01-01 21:39:25,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 382, '_0n1': 1211}
2018-01-01 21:39:25,007 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,011 : INFO : < 200 OK [3311]
2018-01-01 21:39:25,015 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 347, '_0n1': 1211}
2018-01-01 21:39:25,017 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,022 : INFO : < 200 OK [3284]
2018-01-01 21:39:25,022 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 347, '_0n1': 1211}
2018-01-01 21:39:25,026 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,034 : INFO : < 200 OK [3284]
2018-01-01 21:39:25,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 379, '_0n1': 1211}
2018-01-01 21:39:25,038 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,042 : INFO : < 200 OK [3288]
2018-01-01 21:39:25,046 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 379, '_0n1': 1211}
2018-01-01 21:39:25,046 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,054 : INFO : < 200 OK [3288]
2018-01-01 21:39:25,058 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1199}
2018-01-01 21:39:25,058 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,062 : INFO : < 200 OK [3317]
2018-01-01 21:39:25,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1199}
2018-01-01 21:39:25,066 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,070 : INFO : < 200 OK [3317]
2018-01-01 21:39:25,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1199}
2018-01-01 21:39:25,074 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,078 : INFO : < 200 OK [3317]
2018-01-01 21:39:25,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1199}
2018-01-01 21:39:25,082 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,086 : INFO : < 200 OK [3317]
2018-01-01 21:39:25,090 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1211}
2018-01-01 21:39:25,090 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,094 : INFO : < 200 OK [3336]
2018-01-01 21:39:25,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1193}
2018-01-01 21:39:25,098 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,102 : INFO : < 200 OK [3334]
2018-01-01 21:39:25,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1194}
2018-01-01 21:39:25,112 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,117 : INFO : < 200 OK [3340]
2018-01-01 21:39:25,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1199}
2018-01-01 21:39:25,122 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,126 : INFO : < 200 OK [3350]
2018-01-01 21:39:25,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1211}
2018-01-01 21:39:25,130 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,138 : INFO : < 200 OK [3336]
2018-01-01 21:39:25,138 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1193}
2018-01-01 21:39:25,142 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,146 : INFO : < 200 OK [3334]
2018-01-01 21:39:25,146 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1194}
2018-01-01 21:39:25,150 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,154 : INFO : < 200 OK [3340]
2018-01-01 21:39:25,158 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1199}
2018-01-01 21:39:25,158 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,162 : INFO : < 200 OK [3350]
2018-01-01 21:39:25,166 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 401, '_0n1': 1211}

2018-01-01 21:39:25,166 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,170 : INFO : < 200 OK [3296]
2018-01-01 21:39:25,178 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 401, '_0n1': 1211}
2018-01-01 21:39:25,178 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,182 : INFO : < 200 OK [3296]
2018-01-01 21:39:25,186 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 385, '_0n1': 1211}
2018-01-01 21:39:25,186 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,190 : INFO : < 200 OK [3353]
2018-01-01 21:39:25,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 385, '_0n1': 1215}
2018-01-01 21:39:25,198 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,202 : INFO : < 200 OK [3352]
2018-01-01 21:39:25,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 385, '_0n1': 1197}
2018-01-01 21:39:25,202 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,210 : INFO : < 200 OK [3353]
2018-01-01 21:39:25,212 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 402, '_0n1': 1215}
2018-01-01 21:39:25,214 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,218 : INFO : < 200 OK [3285]
2018-01-01 21:39:25,221 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 402, '_0n1': 1215}
2018-01-01 21:39:25,222 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,226 : INFO : < 200 OK [3285]
2018-01-01 21:39:25,226 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 403, '_0n1': 1211}
2018-01-01 21:39:25,230 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,234 : INFO : < 200 OK [3357]
2018-01-01 21:39:25,234 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 403, '_0n1': 1199}
2018-01-01 21:39:25,238 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,242 : INFO : < 200 OK [3371]
2018-01-01 21:39:25,246 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 388, '_0n1': 1211}
2018-01-01 21:39:25,246 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,254 : INFO : < 200 OK [3362]
2018-01-01 21:39:25,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 388, '_0n1': 1215}
2018-01-01 21:39:25,258 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,266 : INFO : < 200 OK [3361]
2018-01-01 21:39:25,270 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 388, '_0n1': 1197}
2018-01-01 21:39:25,270 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,278 : INFO : < 200 OK [3362]
2018-01-01 21:39:25,278 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:25,282 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,286 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,290 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}
2018-01-01 21:39:25,290 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,298 : INFO : < 200 OK [3332]
2018-01-01 21:39:25,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:25,302 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,306 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:25,310 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,314 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,317 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}
2018-01-01 21:39:25,318 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,322 : INFO : < 200 OK [3332]
2018-01-01 21:39:25,322 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:25,326 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,330 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,334 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:25,334 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,338 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}
2018-01-01 21:39:25,342 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,346 : INFO : < 200 OK [3332]
2018-01-01 21:39:25,350 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:25,350 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,358 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:25,362 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,366 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}
2018-01-01 21:39:25,374 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,378 : INFO : < 200 OK [3332]
2018-01-01 21:39:25,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:25,382 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,386 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,390 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:25,390 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,398 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,398 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}

2018-01-01 21:39:25,402 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,406 : INFO : < 200 OK [3332]
2018-01-01 21:39:25,406 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:25,412 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,416 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:25,421 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,423 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}
2018-01-01 21:39:25,427 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,431 : INFO : < 200 OK [3332]
2018-01-01 21:39:25,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:25,435 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,439 : INFO : < 200 OK [3333]
2018-01-01 21:39:25,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1211}
2018-01-01 21:39:25,443 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,447 : INFO : < 200 OK [3316]
2018-01-01 21:39:25,451 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1193}
2018-01-01 21:39:25,451 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,455 : INFO : < 200 OK [3314]
2018-01-01 21:39:25,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1194}
2018-01-01 21:39:25,463 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,467 : INFO : < 200 OK [3320]
2018-01-01 21:39:25,471 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1213}
2018-01-01 21:39:25,471 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,475 : INFO : < 200 OK [3313]
2018-01-01 21:39:25,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1195}
2018-01-01 21:39:25,479 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,483 : INFO : < 200 OK [3313]
2018-01-01 21:39:25,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1196}
2018-01-01 21:39:25,491 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,495 : INFO : < 200 OK [3314]
2018-01-01 21:39:25,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1199}
2018-01-01 21:39:25,503 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,508 : INFO : < 200 OK [3330]
2018-01-01 21:39:25,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 406, '_0n1': 1211}
2018-01-01 21:39:25,514 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,519 : INFO : < 200 OK [3290]
2018-01-01 21:39:25,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 406, '_0n1': 1211}
2018-01-01 21:39:25,523 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,527 : INFO : < 200 OK [3290]
2018-01-01 21:39:25,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 1216}
2018-01-01 21:39:25,535 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,539 : INFO : < 200 OK [3276]
2018-01-01 21:39:25,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 1216}
2018-01-01 21:39:25,543 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,547 : INFO : < 200 OK [3276]
2018-01-01 21:39:25,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 1216}
2018-01-01 21:39:25,659 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,667 : INFO : < 200 OK [3276]
2018-01-01 21:39:25,671 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 398, '_0n1': 1211}
2018-01-01 21:39:25,675 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,679 : INFO : < 200 OK [3327]
2018-01-01 21:39:25,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 213, '_0n1': 1211}
2018-01-01 21:39:25,687 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,691 : INFO : < 200 OK [3305]
2018-01-01 21:39:25,695 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 213, '_0n1': 1199}
2018-01-01 21:39:25,695 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,699 : INFO : < 200 OK [3319]
2018-01-01 21:39:25,703 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 359, '_0n1': 1211}
2018-01-01 21:39:25,703 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,709 : INFO : < 200 OK [3292]
2018-01-01 21:39:25,713 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1195}
2018-01-01 21:39:25,715 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,720 : INFO : < 200 OK [3299]
2018-01-01 21:39:25,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1199}
2018-01-01 21:39:25,727 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,731 : INFO : < 200 OK [3316]
2018-01-01 21:39:25,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1195}
2018-01-01 21:39:25,735 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,739 : INFO : < 200 OK [3299]
2018-01-01 21:39:25,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1199}
2018-01-01 21:39:25,743 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,747 : INFO : < 200 OK [3316]
2018-01-01 21:39:25,751 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1195}

2018-01-01 21:39:25,751 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,755 : INFO : < 200 OK [3299]
2018-01-01 21:39:25,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 360, '_0n1': 1199}
2018-01-01 21:39:25,759 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,763 : INFO : < 200 OK [3316]
2018-01-01 21:39:25,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1211}
2018-01-01 21:39:25,767 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,771 : INFO : < 200 OK [3278]
2018-01-01 21:39:25,775 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1193}
2018-01-01 21:39:25,775 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,779 : INFO : < 200 OK [3276]
2018-01-01 21:39:25,783 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1194}
2018-01-01 21:39:25,783 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,787 : INFO : < 200 OK [3282]
2018-01-01 21:39:25,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1213}
2018-01-01 21:39:25,791 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,795 : INFO : < 200 OK [3275]
2018-01-01 21:39:25,795 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1199}
2018-01-01 21:39:25,799 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,803 : INFO : < 200 OK [3292]
2018-01-01 21:39:25,803 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 416, '_0n1': 1211}
2018-01-01 21:39:25,808 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,812 : INFO : < 200 OK [3312]
2018-01-01 21:39:25,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 416, '_0n1': 1195}
2018-01-01 21:39:25,821 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,827 : INFO : < 200 OK [3309]
2018-01-01 21:39:25,831 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 344, '_0n1': 1195}
2018-01-01 21:39:25,831 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,839 : INFO : < 200 OK [3318]
2018-01-01 21:39:25,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 420, '_0n1': 1197}
2018-01-01 21:39:25,847 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,851 : INFO : < 200 OK [3280]
2018-01-01 21:39:25,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 420, '_0n1': 1197}
2018-01-01 21:39:25,859 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,863 : INFO : < 200 OK [3280]
2018-01-01 21:39:25,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 417, '_0n1': 1211}
2018-01-01 21:39:25,871 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,879 : INFO : < 200 OK [3323]
2018-01-01 21:39:25,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1211}
2018-01-01 21:39:25,887 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,895 : INFO : < 200 OK [3347]
2018-01-01 21:39:25,899 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1211}
2018-01-01 21:39:25,903 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,913 : INFO : < 200 OK [3347]
2018-01-01 21:39:25,918 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1211}
2018-01-01 21:39:25,920 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,926 : INFO : < 200 OK [3347]
2018-01-01 21:39:25,929 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1211}
2018-01-01 21:39:25,932 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,938 : INFO : < 200 OK [3347]
2018-01-01 21:39:25,942 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 377, '_0n1': 1211}
2018-01-01 21:39:25,944 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,948 : INFO : < 200 OK [3347]
2018-01-01 21:39:25,953 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 418, '_0n1': 1211}
2018-01-01 21:39:25,955 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,960 : INFO : < 200 OK [3283]
2018-01-01 21:39:25,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 145, '_0n1': 1211}
2018-01-01 21:39:25,967 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,973 : INFO : < 200 OK [3347]
2018-01-01 21:39:25,976 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 145, '_0n1': 1215}
2018-01-01 21:39:25,979 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,984 : INFO : < 200 OK [3346]
2018-01-01 21:39:25,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1212}
2018-01-01 21:39:25,991 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:25,996 : INFO : < 200 OK [3316]
2018-01-01 21:39:26,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1195}
2018-01-01 21:39:26,003 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,008 : INFO : < 200 OK [3315]
2018-01-01 21:39:26,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1199}
2018-01-01 21:39:26,015 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,019 : INFO : < 200 OK [3332]
2018-01-01 21:39:26,022 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1212}
2018-01-01 21:39:26,024 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,029 : INFO : < 200 OK [3316]
2018-01-01 21:39:26,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1195}

2018-01-01 21:39:26,035 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,039 : INFO : < 200 OK [3315]
2018-01-01 21:39:26,042 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1199}
2018-01-01 21:39:26,043 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,047 : INFO : < 200 OK [3332]
2018-01-01 21:39:26,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 1195}
2018-01-01 21:39:26,051 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,055 : INFO : < 200 OK [3278]
2018-01-01 21:39:26,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 1195}
2018-01-01 21:39:26,059 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,063 : INFO : < 200 OK [3278]
2018-01-01 21:39:26,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 361, '_0n1': 1195}
2018-01-01 21:39:26,067 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,075 : INFO : < 200 OK [3278]
2018-01-01 21:39:26,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 424, '_0n1': 1211}
2018-01-01 21:39:26,079 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,083 : INFO : < 200 OK [3318]
2018-01-01 21:39:26,087 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 1211}
2018-01-01 21:39:26,087 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,091 : INFO : < 200 OK [3314]
2018-01-01 21:39:26,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 1199}
2018-01-01 21:39:26,095 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,099 : INFO : < 200 OK [3328]
2018-01-01 21:39:26,103 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 1211}
2018-01-01 21:39:26,107 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,111 : INFO : < 200 OK [3314]
2018-01-01 21:39:26,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 1199}
2018-01-01 21:39:26,115 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,119 : INFO : < 200 OK [3328]
2018-01-01 21:39:26,123 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 442, '_0n1': 1195}
2018-01-01 21:39:26,123 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,129 : INFO : < 200 OK [3290]
2018-01-01 21:39:26,133 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1211}
2018-01-01 21:39:26,134 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,138 : INFO : < 200 OK [3339]
2018-01-01 21:39:26,141 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1215}
2018-01-01 21:39:26,143 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,147 : INFO : < 200 OK [3338]
2018-01-01 21:39:26,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1197}
2018-01-01 21:39:26,151 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,155 : INFO : < 200 OK [3339]
2018-01-01 21:39:26,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1211}
2018-01-01 21:39:26,159 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,163 : INFO : < 200 OK [3339]
2018-01-01 21:39:26,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1215}
2018-01-01 21:39:26,167 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,171 : INFO : < 200 OK [3338]
2018-01-01 21:39:26,171 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1197}
2018-01-01 21:39:26,175 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,179 : INFO : < 200 OK [3339]
2018-01-01 21:39:26,183 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1211}
2018-01-01 21:39:26,183 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,191 : INFO : < 200 OK [3339]
2018-01-01 21:39:26,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1215}
2018-01-01 21:39:26,199 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,203 : INFO : < 200 OK [3338]
2018-01-01 21:39:26,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1197}
2018-01-01 21:39:26,207 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,211 : INFO : < 200 OK [3339]
2018-01-01 21:39:26,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1211}
2018-01-01 21:39:26,215 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,219 : INFO : < 200 OK [3339]
2018-01-01 21:39:26,223 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1215}
2018-01-01 21:39:26,223 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,230 : INFO : < 200 OK [3338]
2018-01-01 21:39:26,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1197}
2018-01-01 21:39:26,235 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,240 : INFO : < 200 OK [3339]
2018-01-01 21:39:26,243 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 444, '_0n1': 1211}
2018-01-01 21:39:26,243 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,247 : INFO : < 200 OK [3322]
2018-01-01 21:39:26,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 1195}
2018-01-01 21:39:26,255 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,259 : INFO : < 200 OK [3278]
2018-01-01 21:39:26,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 1195}

2018-01-01 21:39:26,263 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,267 : INFO : < 200 OK [3278]
2018-01-01 21:39:26,271 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 362, '_0n1': 1195}
2018-01-01 21:39:26,271 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,279 : INFO : < 200 OK [3278]
2018-01-01 21:39:26,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 1195}
2018-01-01 21:39:26,283 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,287 : INFO : < 200 OK [3270]
2018-01-01 21:39:26,291 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 1195}
2018-01-01 21:39:26,291 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,295 : INFO : < 200 OK [3270]
2018-01-01 21:39:26,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 346, '_0n1': 1195}
2018-01-01 21:39:26,299 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,303 : INFO : < 200 OK [3270]
2018-01-01 21:39:26,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 429, '_0n1': 1211}
2018-01-01 21:39:26,307 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,311 : INFO : < 200 OK [3327]
2018-01-01 21:39:26,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 429, '_0n1': 1195}
2018-01-01 21:39:26,315 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,319 : INFO : < 200 OK [3324]
2018-01-01 21:39:26,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 429, '_0n1': 1211}
2018-01-01 21:39:26,323 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,330 : INFO : < 200 OK [3327]
2018-01-01 21:39:26,334 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 429, '_0n1': 1195}
2018-01-01 21:39:26,335 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,339 : INFO : < 200 OK [3324]
2018-01-01 21:39:26,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 1195}
2018-01-01 21:39:26,343 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,347 : INFO : < 200 OK [3274]
2018-01-01 21:39:26,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 1195}
2018-01-01 21:39:26,351 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,355 : INFO : < 200 OK [3274]
2018-01-01 21:39:26,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 363, '_0n1': 1195}
2018-01-01 21:39:26,363 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,367 : INFO : < 200 OK [3274]
2018-01-01 21:39:26,375 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 364, '_0n1': 1195}
2018-01-01 21:39:26,375 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,379 : INFO : < 200 OK [3304]
2018-01-01 21:39:26,383 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 447, '_0n1': 1211}
2018-01-01 21:39:26,383 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,391 : INFO : < 200 OK [3330]
2018-01-01 21:39:26,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1211}
2018-01-01 21:39:26,395 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,399 : INFO : < 200 OK [3272]
2018-01-01 21:39:26,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1193}
2018-01-01 21:39:26,403 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,407 : INFO : < 200 OK [3270]
2018-01-01 21:39:26,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1215}
2018-01-01 21:39:26,411 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,415 : INFO : < 200 OK [3271]
2018-01-01 21:39:26,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1197}
2018-01-01 21:39:26,419 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,423 : INFO : < 200 OK [3272]
2018-01-01 21:39:26,428 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1211}
2018-01-01 21:39:26,429 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,433 : INFO : < 200 OK [3272]
2018-01-01 21:39:26,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1193}
2018-01-01 21:39:26,438 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,443 : INFO : < 200 OK [3270]
2018-01-01 21:39:26,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1215}
2018-01-01 21:39:26,447 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,451 : INFO : < 200 OK [3271]
2018-01-01 21:39:26,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1197}
2018-01-01 21:39:26,459 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,463 : INFO : < 200 OK [3272]
2018-01-01 21:39:26,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1211}
2018-01-01 21:39:26,467 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,471 : INFO : < 200 OK [3272]
2018-01-01 21:39:26,475 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1193}
2018-01-01 21:39:26,475 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,479 : INFO : < 200 OK [3270]
2018-01-01 21:39:26,483 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1215}
2018-01-01 21:39:26,483 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,491 : INFO : < 200 OK [3271]

2018-01-01 21:39:26,491 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 431, '_0n1': 1197}
2018-01-01 21:39:26,495 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,499 : INFO : < 200 OK [3272]
2018-01-01 21:39:26,503 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 1195}
2018-01-01 21:39:26,503 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,511 : INFO : < 200 OK [3305]
2018-01-01 21:39:26,511 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 1195}
2018-01-01 21:39:26,515 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,519 : INFO : < 200 OK [3305]
2018-01-01 21:39:26,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 1195}
2018-01-01 21:39:26,523 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,530 : INFO : < 200 OK [3305]
2018-01-01 21:39:26,532 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 365, '_0n1': 1195}
2018-01-01 21:39:26,534 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,538 : INFO : < 200 OK [3305]
2018-01-01 21:39:26,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 349, '_0n1': 1195}
2018-01-01 21:39:26,543 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,543 : INFO : < 200 OK [3313]
2018-01-01 21:39:26,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 433, '_0n1': 1215}
2018-01-01 21:39:26,551 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,555 : INFO : < 200 OK [3295]
2018-01-01 21:39:26,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 433, '_0n1': 1197}
2018-01-01 21:39:26,559 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,563 : INFO : < 200 OK [3296]
2018-01-01 21:39:26,567 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 433, '_0n1': 1215}
2018-01-01 21:39:26,567 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,571 : INFO : < 200 OK [3295]
2018-01-01 21:39:26,575 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 433, '_0n1': 1197}
2018-01-01 21:39:26,575 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,579 : INFO : < 200 OK [3296]
2018-01-01 21:39:26,583 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 401, '_0n1': 1211}
2018-01-01 21:39:26,583 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,587 : INFO : < 200 OK [3296]
2018-01-01 21:39:26,591 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 401, '_0n1': 1211}
2018-01-01 21:39:26,591 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,595 : INFO : < 200 OK [3296]
2018-01-01 21:39:26,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 450, '_0n1': 1215}
2018-01-01 21:39:26,603 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,607 : INFO : < 200 OK [3329]
2018-01-01 21:39:26,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 385, '_0n1': 1211}
2018-01-01 21:39:26,611 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,619 : INFO : < 200 OK [3353]
2018-01-01 21:39:26,619 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 385, '_0n1': 1215}
2018-01-01 21:39:26,623 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,629 : INFO : < 200 OK [3352]
2018-01-01 21:39:26,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 385, '_0n1': 1197}
2018-01-01 21:39:26,635 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,638 : INFO : < 200 OK [3353]
2018-01-01 21:39:26,643 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 1195}
2018-01-01 21:39:26,643 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,647 : INFO : < 200 OK [3274]
2018-01-01 21:39:26,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 1195}
2018-01-01 21:39:26,651 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,655 : INFO : < 200 OK [3274]
2018-01-01 21:39:26,659 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 366, '_0n1': 1195}
2018-01-01 21:39:26,659 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,663 : INFO : < 200 OK [3274]
2018-01-01 21:39:26,667 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1212}
2018-01-01 21:39:26,667 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,675 : INFO : < 200 OK [3278]
2018-01-01 21:39:26,675 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1195}
2018-01-01 21:39:26,679 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,683 : INFO : < 200 OK [3277]
2018-01-01 21:39:26,687 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1212}
2018-01-01 21:39:26,687 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,691 : INFO : < 200 OK [3278]
2018-01-01 21:39:26,695 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1195}
2018-01-01 21:39:26,695 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,699 : INFO : < 200 OK [3277]
2018-01-01 21:39:26,703 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1212}
2018-01-01 21:39:26,703 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,715 : INFO : < 200 OK [3278]
2018-01-01 21:39:26,719 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 351, '_0n1': 1195}

2018-01-01 21:39:26,719 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,728 : INFO : < 200 OK [3277]
2018-01-01 21:39:26,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 452, '_0n1': 1215}
2018-01-01 21:39:26,734 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,738 : INFO : < 200 OK [3319]
2018-01-01 21:39:26,740 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 452, '_0n1': 1197}
2018-01-01 21:39:26,742 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,743 : INFO : < 200 OK [3320]
2018-01-01 21:39:26,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 452, '_0n1': 1215}
2018-01-01 21:39:26,747 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,755 : INFO : < 200 OK [3319]
2018-01-01 21:39:26,755 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 452, '_0n1': 1197}
2018-01-01 21:39:26,759 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,763 : INFO : < 200 OK [3320]
2018-01-01 21:39:26,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 436, '_0n1': 1211}
2018-01-01 21:39:26,767 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,771 : INFO : < 200 OK [3313]
2018-01-01 21:39:26,771 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 436, '_0n1': 1199}
2018-01-01 21:39:26,775 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,779 : INFO : < 200 OK [3327]
2018-01-01 21:39:26,779 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1211}
2018-01-01 21:39:26,783 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,787 : INFO : < 200 OK [3347]
2018-01-01 21:39:26,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1215}
2018-01-01 21:39:26,791 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,795 : INFO : < 200 OK [3346]
2018-01-01 21:39:26,799 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1197}
2018-01-01 21:39:26,799 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,803 : INFO : < 200 OK [3347]
2018-01-01 21:39:26,807 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1211}
2018-01-01 21:39:26,807 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,811 : INFO : < 200 OK [3347]
2018-01-01 21:39:26,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1215}
2018-01-01 21:39:26,815 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,823 : INFO : < 200 OK [3346]
2018-01-01 21:39:26,829 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1197}
2018-01-01 21:39:26,831 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,837 : INFO : < 200 OK [3347]
2018-01-01 21:39:26,840 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1211}
2018-01-01 21:39:26,842 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,843 : INFO : < 200 OK [3347]
2018-01-01 21:39:26,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1215}
2018-01-01 21:39:26,851 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,855 : INFO : < 200 OK [3346]
2018-01-01 21:39:26,855 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1197}
2018-01-01 21:39:26,859 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,863 : INFO : < 200 OK [3347]
2018-01-01 21:39:26,863 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1211}
2018-01-01 21:39:26,867 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,871 : INFO : < 200 OK [3347]
2018-01-01 21:39:26,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1215}
2018-01-01 21:39:26,875 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,879 : INFO : < 200 OK [3346]
2018-01-01 21:39:26,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1197}
2018-01-01 21:39:26,883 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,887 : INFO : < 200 OK [3347]
2018-01-01 21:39:26,891 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 438, '_0n1': 1195}
2018-01-01 21:39:26,891 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,895 : INFO : < 200 OK [3332]
2018-01-01 21:39:26,899 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 456, '_0n1': 1211}
2018-01-01 21:39:26,899 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,903 : INFO : < 200 OK [3310]
2018-01-01 21:39:26,907 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 456, '_0n1': 1211}
2018-01-01 21:39:26,911 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,915 : INFO : < 200 OK [3310]
2018-01-01 21:39:26,923 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 1211}
2018-01-01 21:39:26,923 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,932 : INFO : < 200 OK [3305]
2018-01-01 21:39:26,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 1199}
2018-01-01 21:39:26,936 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,940 : INFO : < 200 OK [3319]
2018-01-01 21:39:26,943 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 1211}
2018-01-01 21:39:26,943 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,947 : INFO : < 200 OK [3305]
2018-01-01 21:39:26,951 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 1199}

2018-01-01 21:39:26,951 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,955 : INFO : < 200 OK [3319]
2018-01-01 21:39:26,959 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 1211}
2018-01-01 21:39:26,959 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,967 : INFO : < 200 OK [3306]
2018-01-01 21:39:26,967 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 1215}
2018-01-01 21:39:26,971 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,975 : INFO : < 200 OK [3305]
2018-01-01 21:39:26,979 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 1197}
2018-01-01 21:39:26,979 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,983 : INFO : < 200 OK [3306]
2018-01-01 21:39:26,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 1199}
2018-01-01 21:39:26,987 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,991 : INFO : < 200 OK [3320]
2018-01-01 21:39:26,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 480, '_0n1': 1195}
2018-01-01 21:39:26,995 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:26,999 : INFO : < 200 OK [3308]
2018-01-01 21:39:27,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 480, '_0n1': 1195}
2018-01-01 21:39:27,003 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,007 : INFO : < 200 OK [3308]
2018-01-01 21:39:27,011 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 465, '_0n1': 1211}
2018-01-01 21:39:27,011 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,015 : INFO : < 200 OK [3289]
2018-01-01 21:39:27,019 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 388, '_0n1': 1211}
2018-01-01 21:39:27,019 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,028 : INFO : < 200 OK [3362]
2018-01-01 21:39:27,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 388, '_0n1': 1215}
2018-01-01 21:39:27,032 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,036 : INFO : < 200 OK [3361]
2018-01-01 21:39:27,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 388, '_0n1': 1197}
2018-01-01 21:39:27,040 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,043 : INFO : < 200 OK [3362]
2018-01-01 21:39:27,047 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 369, '_0n1': 1195}
2018-01-01 21:39:27,051 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,055 : INFO : < 200 OK [3364]
2018-01-01 21:39:27,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 1211}
2018-01-01 21:39:27,063 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,067 : INFO : < 200 OK [3312]
2018-01-01 21:39:27,071 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 1199}
2018-01-01 21:39:27,071 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,075 : INFO : < 200 OK [3326]
2018-01-01 21:39:27,079 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 1211}
2018-01-01 21:39:27,079 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,087 : INFO : < 200 OK [3312]
2018-01-01 21:39:27,091 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 1199}
2018-01-01 21:39:27,091 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,095 : INFO : < 200 OK [3326]
2018-01-01 21:39:27,099 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 484, '_0n1': 1214}
2018-01-01 21:39:27,099 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,107 : INFO : < 200 OK [3314]
2018-01-01 21:39:27,107 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 470, '_0n1': 1193}
2018-01-01 21:39:27,111 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,115 : INFO : < 200 OK [3348]
2018-01-01 21:39:27,119 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 406, '_0n1': 1211}
2018-01-01 21:39:27,119 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,123 : INFO : < 200 OK [3290]
2018-01-01 21:39:27,128 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 406, '_0n1': 1211}
2018-01-01 21:39:27,129 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,134 : INFO : < 200 OK [3290]
2018-01-01 21:39:27,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1211}
2018-01-01 21:39:27,139 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,143 : INFO : < 200 OK [3316]
2018-01-01 21:39:27,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1193}
2018-01-01 21:39:27,147 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,155 : INFO : < 200 OK [3314]
2018-01-01 21:39:27,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1194}
2018-01-01 21:39:27,159 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,163 : INFO : < 200 OK [3320]
2018-01-01 21:39:27,167 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1213}
2018-01-01 21:39:27,167 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,171 : INFO : < 200 OK [3313]
2018-01-01 21:39:27,175 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1195}
2018-01-01 21:39:27,179 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,183 : INFO : < 200 OK [3313]
2018-01-01 21:39:27,187 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1196}

2018-01-01 21:39:27,187 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,191 : INFO : < 200 OK [3314]
2018-01-01 21:39:27,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 389, '_0n1': 1199}
2018-01-01 21:39:27,195 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,203 : INFO : < 200 OK [3330]
2018-01-01 21:39:27,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 353, '_0n1': 1195}
2018-01-01 21:39:27,207 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,211 : INFO : < 200 OK [3275]
2018-01-01 21:39:27,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 353, '_0n1': 1195}
2018-01-01 21:39:27,215 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,219 : INFO : < 200 OK [3275]
2018-01-01 21:39:27,223 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 471, '_0n1': 1211}
2018-01-01 21:39:27,223 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,230 : INFO : < 200 OK [3310]
2018-01-01 21:39:27,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 471, '_0n1': 1199}
2018-01-01 21:39:27,234 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,238 : INFO : < 200 OK [3324]
2018-01-01 21:39:27,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 471, '_0n1': 1211}
2018-01-01 21:39:27,242 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,244 : INFO : < 200 OK [3310]
2018-01-01 21:39:27,248 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 471, '_0n1': 1199}
2018-01-01 21:39:27,248 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,252 : INFO : < 200 OK [3324]
2018-01-01 21:39:27,256 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 473, '_0n1': 1195}
2018-01-01 21:39:27,256 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,260 : INFO : < 200 OK [3303]
2018-01-01 21:39:27,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1195}
2018-01-01 21:39:27,264 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,268 : INFO : < 200 OK [3310]
2018-01-01 21:39:27,272 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1199}
2018-01-01 21:39:27,276 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,280 : INFO : < 200 OK [3327]
2018-01-01 21:39:27,280 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1195}
2018-01-01 21:39:27,284 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,288 : INFO : < 200 OK [3310]
2018-01-01 21:39:27,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 266, '_0n1': 1199}
2018-01-01 21:39:27,292 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,296 : INFO : < 200 OK [3327]
2018-01-01 21:39:27,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 1195}
2018-01-01 21:39:27,304 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,308 : INFO : < 200 OK [3331]
2018-01-01 21:39:27,312 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 1199}
2018-01-01 21:39:27,316 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,320 : INFO : < 200 OK [3348]
2018-01-01 21:39:27,324 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 1195}
2018-01-01 21:39:27,324 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,330 : INFO : < 200 OK [3331]
2018-01-01 21:39:27,333 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 162, '_0n1': 1199}
2018-01-01 21:39:27,335 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,339 : INFO : < 200 OK [3348]
2018-01-01 21:39:27,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 503, '_0n1': 1211}
2018-01-01 21:39:27,344 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,348 : INFO : < 200 OK [3287]
2018-01-01 21:39:27,352 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 503, '_0n1': 1199}
2018-01-01 21:39:27,352 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,356 : INFO : < 200 OK [3301]
2018-01-01 21:39:27,360 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 503, '_0n1': 1211}
2018-01-01 21:39:27,360 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,364 : INFO : < 200 OK [3287]
2018-01-01 21:39:27,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 503, '_0n1': 1199}
2018-01-01 21:39:27,368 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,372 : INFO : < 200 OK [3301]
2018-01-01 21:39:27,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 475, '_0n1': 1195}
2018-01-01 21:39:27,376 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,384 : INFO : < 200 OK [3294]
2018-01-01 21:39:27,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 505, '_0n1': 1193}
2018-01-01 21:39:27,388 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,392 : INFO : < 200 OK [3321]
2018-01-01 21:39:27,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 476, '_0n1': 1195}
2018-01-01 21:39:27,396 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,400 : INFO : < 200 OK [3296]
2018-01-01 21:39:27,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 476, '_0n1': 1199}
2018-01-01 21:39:27,408 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,412 : INFO : < 200 OK [3313]
2018-01-01 21:39:27,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 507, '_0n1': 1211}

2018-01-01 21:39:27,416 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,424 : INFO : < 200 OK [3342]
2018-01-01 21:39:27,424 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 507, '_0n1': 1215}
2018-01-01 21:39:27,429 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,434 : INFO : < 200 OK [3341]
2018-01-01 21:39:27,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 507, '_0n1': 1199}
2018-01-01 21:39:27,439 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,443 : INFO : < 200 OK [3356]
2018-01-01 21:39:27,444 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 1195}
2018-01-01 21:39:27,448 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,452 : INFO : < 200 OK [3319]
2018-01-01 21:39:27,452 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 1199}
2018-01-01 21:39:27,456 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,460 : INFO : < 200 OK [3336]
2018-01-01 21:39:27,464 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 1195}
2018-01-01 21:39:27,464 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,468 : INFO : < 200 OK [3319]
2018-01-01 21:39:27,472 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 1199}
2018-01-01 21:39:27,472 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,476 : INFO : < 200 OK [3336]
2018-01-01 21:39:27,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 1195}
2018-01-01 21:39:27,480 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,484 : INFO : < 200 OK [3319]
2018-01-01 21:39:27,488 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 508, '_0n1': 1199}
2018-01-01 21:39:27,488 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,492 : INFO : < 200 OK [3336]
2018-01-01 21:39:27,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 1212}
2018-01-01 21:39:27,496 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,500 : INFO : < 200 OK [3320]
2018-01-01 21:39:27,504 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 1195}
2018-01-01 21:39:27,504 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,508 : INFO : < 200 OK [3319]
2018-01-01 21:39:27,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 1212}
2018-01-01 21:39:27,512 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,516 : INFO : < 200 OK [3320]
2018-01-01 21:39:27,520 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 1195}
2018-01-01 21:39:27,520 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,524 : INFO : < 200 OK [3319]
2018-01-01 21:39:27,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 510, '_0n1': 1211}
2018-01-01 21:39:27,531 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,535 : INFO : < 200 OK [3275]
2018-01-01 21:39:27,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 510, '_0n1': 1211}
2018-01-01 21:39:27,541 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,544 : INFO : < 200 OK [3275]
2018-01-01 21:39:27,548 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 371, '_0n1': 1211}
2018-01-01 21:39:27,552 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,556 : INFO : < 200 OK [3287]
2018-01-01 21:39:27,556 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 371, '_0n1': 1211}
2018-01-01 21:39:27,560 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,564 : INFO : < 200 OK [3287]
2018-01-01 21:39:27,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 112, '_0n1': 1211}
2018-01-01 21:39:27,572 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,576 : INFO : < 200 OK [3285]
2018-01-01 21:39:27,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 112, '_0n1': 1211}
2018-01-01 21:39:27,580 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,584 : INFO : < 200 OK [3285]
2018-01-01 21:39:27,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 516, '_0n1': 1195}
2018-01-01 21:39:27,592 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,596 : INFO : < 200 OK [3305]
2018-01-01 21:39:27,600 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 516, '_0n1': 1195}
2018-01-01 21:39:27,600 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,604 : INFO : < 200 OK [3305]
2018-01-01 21:39:27,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 533, '_0n1': 1211}
2018-01-01 21:39:27,608 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,612 : INFO : < 200 OK [3300]
2018-01-01 21:39:27,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 533, '_0n1': 1215}
2018-01-01 21:39:27,620 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,624 : INFO : < 200 OK [3299]
2018-01-01 21:39:27,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 533, '_0n1': 1211}
2018-01-01 21:39:27,629 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,633 : INFO : < 200 OK [3300]
2018-01-01 21:39:27,635 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 533, '_0n1': 1215}
2018-01-01 21:39:27,637 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,641 : INFO : < 200 OK [3299]
2018-01-01 21:39:27,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 1216}

2018-01-01 21:39:27,644 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,648 : INFO : < 200 OK [3276]
2018-01-01 21:39:27,652 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 1216}
2018-01-01 21:39:27,652 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,660 : INFO : < 200 OK [3276]
2018-01-01 21:39:27,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 392, '_0n1': 1216}
2018-01-01 21:39:27,664 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,672 : INFO : < 200 OK [3276]
2018-01-01 21:39:27,676 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 536, '_0n1': 1195}
2018-01-01 21:39:27,680 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,684 : INFO : < 200 OK [3290]
2018-01-01 21:39:27,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 538, '_0n1': 1195}
2018-01-01 21:39:27,692 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,696 : INFO : < 200 OK [3318]
2018-01-01 21:39:27,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 538, '_0n1': 1196}
2018-01-01 21:39:27,700 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,704 : INFO : < 200 OK [3319]
2018-01-01 21:39:27,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 522, '_0n1': 1195}
2018-01-01 21:39:27,708 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,712 : INFO : < 200 OK [3278]
2018-01-01 21:39:27,716 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 523, '_0n1': 1211}
2018-01-01 21:39:27,716 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,724 : INFO : < 200 OK [3328]
2018-01-01 21:39:27,729 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1211}
2018-01-01 21:39:27,731 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,735 : INFO : < 200 OK [3302]
2018-01-01 21:39:27,737 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1215}
2018-01-01 21:39:27,738 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,742 : INFO : < 200 OK [3301]
2018-01-01 21:39:27,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1197}
2018-01-01 21:39:27,743 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,747 : INFO : < 200 OK [3302]
2018-01-01 21:39:27,751 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1211}
2018-01-01 21:39:27,751 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,759 : INFO : < 200 OK [3302]
2018-01-01 21:39:27,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1215}
2018-01-01 21:39:27,759 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,763 : INFO : < 200 OK [3301]
2018-01-01 21:39:27,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1197}
2018-01-01 21:39:27,771 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,775 : INFO : < 200 OK [3302]
2018-01-01 21:39:27,779 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1211}
2018-01-01 21:39:27,779 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,787 : INFO : < 200 OK [3302]
2018-01-01 21:39:27,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1215}
2018-01-01 21:39:27,791 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,795 : INFO : < 200 OK [3301]
2018-01-01 21:39:27,799 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1197}
2018-01-01 21:39:27,799 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,803 : INFO : < 200 OK [3302]
2018-01-01 21:39:27,807 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1211}
2018-01-01 21:39:27,811 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,815 : INFO : < 200 OK [3302]
2018-01-01 21:39:27,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1215}
2018-01-01 21:39:27,819 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,823 : INFO : < 200 OK [3301]
2018-01-01 21:39:27,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1197}
2018-01-01 21:39:27,827 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,832 : INFO : < 200 OK [3302]
2018-01-01 21:39:27,836 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 542, '_0n1': 1195}
2018-01-01 21:39:27,838 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,842 : INFO : < 200 OK [3289]
2018-01-01 21:39:27,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 527, '_0n1': 1214}
2018-01-01 21:39:27,848 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,852 : INFO : < 200 OK [3310]
2018-01-01 21:39:27,860 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 530, '_0n1': 1211}
2018-01-01 21:39:27,860 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,864 : INFO : < 200 OK [3275]
2018-01-01 21:39:27,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 530, '_0n1': 1199}
2018-01-01 21:39:27,868 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,872 : INFO : < 200 OK [3289]
2018-01-01 21:39:27,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 1195}
2018-01-01 21:39:27,876 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,880 : INFO : < 200 OK [3279]
2018-01-01 21:39:27,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 1195}

2018-01-01 21:39:27,884 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,888 : INFO : < 200 OK [3279]
2018-01-01 21:39:27,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 1195}
2018-01-01 21:39:27,892 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,896 : INFO : < 200 OK [3279]
2018-01-01 21:39:27,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 374, '_0n1': 1195}
2018-01-01 21:39:27,900 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,904 : INFO : < 200 OK [3279]
2018-01-01 21:39:27,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 547, '_0n1': 1195}
2018-01-01 21:39:27,908 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,912 : INFO : < 200 OK [3321]
2018-01-01 21:39:27,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 547, '_0n1': 1195}
2018-01-01 21:39:27,916 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,924 : INFO : < 200 OK [3321]
2018-01-01 21:39:27,931 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 553, '_0n1': 1215}
2018-01-01 21:39:27,934 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,938 : INFO : < 200 OK [3282]
2018-01-01 21:39:27,941 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 553, '_0n1': 1215}
2018-01-01 21:39:27,943 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,943 : INFO : < 200 OK [3282]
2018-01-01 21:39:27,952 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 551, '_0n1': 1193}
2018-01-01 21:39:27,952 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,960 : INFO : < 200 OK [3295]
2018-01-01 21:39:27,960 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 551, '_0n1': 1193}
2018-01-01 21:39:27,964 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,968 : INFO : < 200 OK [3295]
2018-01-01 21:39:27,968 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 551, '_0n1': 1193}
2018-01-01 21:39:27,972 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,976 : INFO : < 200 OK [3295]
2018-01-01 21:39:27,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 555, '_0n1': 1196}
2018-01-01 21:39:27,980 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,984 : INFO : < 200 OK [3292]
2018-01-01 21:39:27,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 552, '_0n1': 1195}
2018-01-01 21:39:27,988 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:27,992 : INFO : < 200 OK [3282]
2018-01-01 21:39:27,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 552, '_0n1': 1195}
2018-01-01 21:39:27,996 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,000 : INFO : < 200 OK [3282]
2018-01-01 21:39:28,004 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 556, '_0n1': 1211}
2018-01-01 21:39:28,004 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,008 : INFO : < 200 OK [3297]
2018-01-01 21:39:28,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 556, '_0n1': 1211}
2018-01-01 21:39:28,016 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,020 : INFO : < 200 OK [3297]
2018-01-01 21:39:28,024 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 573, '_0n1': 1211}
2018-01-01 21:39:28,024 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,032 : INFO : < 200 OK [3283]
2018-01-01 21:39:28,036 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 557, '_0n1': 1195}
2018-01-01 21:39:28,040 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,044 : INFO : < 200 OK [3330]
2018-01-01 21:39:28,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 557, '_0n1': 1195}
2018-01-01 21:39:28,048 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,052 : INFO : < 200 OK [3330]
2018-01-01 21:39:28,056 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 142, '_0n1': 1211}
2018-01-01 21:39:28,056 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,064 : INFO : < 200 OK [3332]
2018-01-01 21:39:28,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 558, '_0n1': 1211}
2018-01-01 21:39:28,068 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,072 : INFO : < 200 OK [3311]
2018-01-01 21:39:28,076 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 575, '_0n1': 1193}
2018-01-01 21:39:28,076 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,080 : INFO : < 200 OK [3327]
2018-01-01 21:39:28,084 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 575, '_0n1': 1194}
2018-01-01 21:39:28,084 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,088 : INFO : < 200 OK [3333]
2018-01-01 21:39:28,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 575, '_0n1': 1196}
2018-01-01 21:39:28,092 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,096 : INFO : < 200 OK [3327]
2018-01-01 21:39:28,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 575, '_0n1': 1193}
2018-01-01 21:39:28,100 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,104 : INFO : < 200 OK [3327]
2018-01-01 21:39:28,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 575, '_0n1': 1194}
2018-01-01 21:39:28,108 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,112 : INFO : < 200 OK [3333]
2018-01-01 21:39:28,116 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 575, '_0n1': 1196}

2018-01-01 21:39:28,116 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,120 : INFO : < 200 OK [3327]
2018-01-01 21:39:28,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 50, '_0n1': 1193}
2018-01-01 21:39:28,129 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,133 : INFO : < 200 OK [3290]
2018-01-01 21:39:28,138 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 50, '_0n1': 1193}
2018-01-01 21:39:28,139 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,144 : INFO : < 200 OK [3290]
2018-01-01 21:39:28,148 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 398, '_0n1': 1211}
2018-01-01 21:39:28,148 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,152 : INFO : < 200 OK [3327]
2018-01-01 21:39:28,156 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1199}
2018-01-01 21:39:28,160 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,164 : INFO : < 200 OK [3307]
2018-01-01 21:39:28,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1199}
2018-01-01 21:39:28,168 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,172 : INFO : < 200 OK [3307]
2018-01-01 21:39:28,176 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1199}
2018-01-01 21:39:28,176 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,180 : INFO : < 200 OK [3307]
2018-01-01 21:39:28,184 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1199}
2018-01-01 21:39:28,184 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,192 : INFO : < 200 OK [3307]
2018-01-01 21:39:28,196 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 68, '_0n1': 1199}
2018-01-01 21:39:28,196 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,200 : INFO : < 200 OK [3307]
2018-01-01 21:39:28,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1211}
2018-01-01 21:39:28,204 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,208 : INFO : < 200 OK [3278]
2018-01-01 21:39:28,208 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1193}
2018-01-01 21:39:28,212 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,216 : INFO : < 200 OK [3276]
2018-01-01 21:39:28,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1194}
2018-01-01 21:39:28,220 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,224 : INFO : < 200 OK [3282]
2018-01-01 21:39:28,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1213}
2018-01-01 21:39:28,231 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,235 : INFO : < 200 OK [3275]
2018-01-01 21:39:28,237 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 415, '_0n1': 1199}
2018-01-01 21:39:28,239 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,243 : INFO : < 200 OK [3292]
2018-01-01 21:39:28,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 559, '_0n1': 1192}
2018-01-01 21:39:28,244 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,252 : INFO : < 200 OK [3321]
2018-01-01 21:39:28,256 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 559, '_0n1': 1193}
2018-01-01 21:39:28,256 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,260 : INFO : < 200 OK [3322]
2018-01-01 21:39:28,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 559, '_0n1': 1192}
2018-01-01 21:39:28,268 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,272 : INFO : < 200 OK [3321]
2018-01-01 21:39:28,276 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 559, '_0n1': 1193}
2018-01-01 21:39:28,276 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,280 : INFO : < 200 OK [3322]
2018-01-01 21:39:28,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 576, '_0n1': 1192}
2018-01-01 21:39:28,288 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,292 : INFO : < 200 OK [3284]
2018-01-01 21:39:28,296 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 576, '_0n1': 1211}
2018-01-01 21:39:28,296 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,304 : INFO : < 200 OK [3287]
2018-01-01 21:39:28,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 576, '_0n1': 1193}
2018-01-01 21:39:28,308 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,312 : INFO : < 200 OK [3285]
2018-01-01 21:39:28,316 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 576, '_0n1': 1212}
2018-01-01 21:39:28,316 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,320 : INFO : < 200 OK [3285]
2018-01-01 21:39:28,324 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 576, '_0n1': 1194}
2018-01-01 21:39:28,324 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,331 : INFO : < 200 OK [3291]
2018-01-01 21:39:28,334 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 560, '_0n1': 1211}
2018-01-01 21:39:28,336 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,340 : INFO : < 200 OK [3319]
2018-01-01 21:39:28,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 560, '_0n1': 1196}
2018-01-01 21:39:28,344 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,348 : INFO : < 200 OK [3317]
2018-01-01 21:39:28,352 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 560, '_0n1': 1211}

2018-01-01 21:39:28,352 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,356 : INFO : < 200 OK [3319]
2018-01-01 21:39:28,360 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 560, '_0n1': 1196}
2018-01-01 21:39:28,360 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,364 : INFO : < 200 OK [3317]
2018-01-01 21:39:28,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1193}
2018-01-01 21:39:28,368 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,372 : INFO : < 200 OK [3308]
2018-01-01 21:39:28,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1212}
2018-01-01 21:39:28,376 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,380 : INFO : < 200 OK [3308]
2018-01-01 21:39:28,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1198}
2018-01-01 21:39:28,384 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,388 : INFO : < 200 OK [3311]
2018-01-01 21:39:28,392 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1193}
2018-01-01 21:39:28,392 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,396 : INFO : < 200 OK [3308]
2018-01-01 21:39:28,400 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1212}
2018-01-01 21:39:28,400 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,404 : INFO : < 200 OK [3308]
2018-01-01 21:39:28,408 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 293, '_0n1': 1198}
2018-01-01 21:39:28,408 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,416 : INFO : < 200 OK [3311]
2018-01-01 21:39:28,420 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 577, '_0n1': 1193}
2018-01-01 21:39:28,424 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,428 : INFO : < 200 OK [3322]
2018-01-01 21:39:28,428 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 577, '_0n1': 1193}
2018-01-01 21:39:28,433 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,438 : INFO : < 200 OK [3322]
2018-01-01 21:39:28,442 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 577, '_0n1': 1193}
2018-01-01 21:39:28,443 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,448 : INFO : < 200 OK [3322]
2018-01-01 21:39:28,448 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 418, '_0n1': 1211}
2018-01-01 21:39:28,452 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,456 : INFO : < 200 OK [3283]
2018-01-01 21:39:28,460 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 561, '_0n1': 1211}
2018-01-01 21:39:28,460 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,464 : INFO : < 200 OK [3327]
2018-01-01 21:39:28,468 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 1211}
2018-01-01 21:39:28,468 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,472 : INFO : < 200 OK [3302]
2018-01-01 21:39:28,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 1211}
2018-01-01 21:39:28,476 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,480 : INFO : < 200 OK [3302]
2018-01-01 21:39:28,484 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 1211}
2018-01-01 21:39:28,484 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,488 : INFO : < 200 OK [3302]
2018-01-01 21:39:28,492 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 52, '_0n1': 1211}
2018-01-01 21:39:28,492 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,496 : INFO : < 200 OK [3302]
2018-01-01 21:39:28,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 578, '_0n1': 1192}
2018-01-01 21:39:28,500 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,504 : INFO : < 200 OK [3328]
2018-01-01 21:39:28,508 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 578, '_0n1': 1211}
2018-01-01 21:39:28,508 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,512 : INFO : < 200 OK [3331]
2018-01-01 21:39:28,516 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 578, '_0n1': 1193}
2018-01-01 21:39:28,516 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,520 : INFO : < 200 OK [3329]
2018-01-01 21:39:28,524 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 578, '_0n1': 1194}
2018-01-01 21:39:28,524 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,532 : INFO : < 200 OK [3335]
2018-01-01 21:39:28,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 578, '_0n1': 1215}
2018-01-01 21:39:28,538 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,543 : INFO : < 200 OK [3330]
2018-01-01 21:39:28,545 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 578, '_0n1': 1217}
2018-01-01 21:39:28,545 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,553 : INFO : < 200 OK [3329]
2018-01-01 21:39:28,553 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 578, '_0n1': 1199}
2018-01-01 21:39:28,557 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,561 : INFO : < 200 OK [3345]
2018-01-01 21:39:28,565 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1212}
2018-01-01 21:39:28,565 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,573 : INFO : < 200 OK [3316]
2018-01-01 21:39:28,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1195}

2018-01-01 21:39:28,577 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,581 : INFO : < 200 OK [3315]
2018-01-01 21:39:28,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1199}
2018-01-01 21:39:28,585 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,593 : INFO : < 200 OK [3332]
2018-01-01 21:39:28,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1212}
2018-01-01 21:39:28,597 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,601 : INFO : < 200 OK [3316]
2018-01-01 21:39:28,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1195}
2018-01-01 21:39:28,605 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,609 : INFO : < 200 OK [3315]
2018-01-01 21:39:28,613 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 419, '_0n1': 1199}
2018-01-01 21:39:28,613 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,617 : INFO : < 200 OK [3332]
2018-01-01 21:39:28,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 1193}
2018-01-01 21:39:28,621 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,625 : INFO : < 200 OK [3291]
2018-01-01 21:39:28,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 1195}
2018-01-01 21:39:28,631 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,635 : INFO : < 200 OK [3290]
2018-01-01 21:39:28,638 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 1193}
2018-01-01 21:39:28,640 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,644 : INFO : < 200 OK [3291]
2018-01-01 21:39:28,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 70, '_0n1': 1195}
2018-01-01 21:39:28,645 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:28,649 : INFO : < 200 OK [3290]
2018-01-01 21:39:28,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 562, '_0n1': 1192}
2018-01-01 21:39:28,653 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,657 : INFO : < 200 OK [3282]
2018-01-01 21:39:28,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 562, '_0n1': 1214}
2018-01-01 21:39:28,661 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,665 : INFO : < 200 OK [3282]
2018-01-01 21:39:28,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1193}
2018-01-01 21:39:28,669 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,677 : INFO : < 200 OK [3331]
2018-01-01 21:39:28,681 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1212}
2018-01-01 21:39:28,681 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,689 : INFO : < 200 OK [3331]
2018-01-01 21:39:28,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1194}
2018-01-01 21:39:28,693 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,697 : INFO : < 200 OK [3337]
2018-01-01 21:39:28,701 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1199}
2018-01-01 21:39:28,705 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,709 : INFO : < 200 OK [3347]
2018-01-01 21:39:28,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1193}
2018-01-01 21:39:28,713 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,717 : INFO : < 200 OK [3331]
2018-01-01 21:39:28,721 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1212}
2018-01-01 21:39:28,721 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,725 : INFO : < 200 OK [3331]
2018-01-01 21:39:28,730 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1194}
2018-01-01 21:39:28,732 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,736 : INFO : < 200 OK [3337]
2018-01-01 21:39:28,738 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1199}
2018-01-01 21:39:28,740 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,743 : INFO : < 200 OK [3347]
2018-01-01 21:39:28,744 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1193}
2018-01-01 21:39:28,748 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,752 : INFO : < 200 OK [3331]
2018-01-01 21:39:28,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1212}
2018-01-01 21:39:28,756 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,760 : INFO : < 200 OK [3331]
2018-01-01 21:39:28,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1194}
2018-01-01 21:39:28,764 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,768 : INFO : < 200 OK [3337]
2018-01-01 21:39:28,768 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1199}
2018-01-01 21:39:28,772 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,776 : INFO : < 200 OK [3347]
2018-01-01 21:39:28,776 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1193}
2018-01-01 21:39:28,780 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,788 : INFO : < 200 OK [3331]
2018-01-01 21:39:28,792 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1212}
2018-01-01 21:39:28,796 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,800 : INFO : < 200 OK [3331]
2018-01-01 21:39:28,804 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1194}

2018-01-01 21:39:28,808 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,812 : INFO : < 200 OK [3337]
2018-01-01 21:39:28,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 579, '_0n1': 1199}
2018-01-01 21:39:28,816 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,820 : INFO : < 200 OK [3347]
2018-01-01 21:39:28,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 424, '_0n1': 1211}
2018-01-01 21:39:28,824 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,828 : INFO : < 200 OK [3318]
2018-01-01 21:39:28,833 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 1211}
2018-01-01 21:39:28,835 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,840 : INFO : < 200 OK [3314]
2018-01-01 21:39:28,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 1199}
2018-01-01 21:39:28,844 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,849 : INFO : < 200 OK [3328]
2018-01-01 21:39:28,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 1211}
2018-01-01 21:39:28,853 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,857 : INFO : < 200 OK [3314]
2018-01-01 21:39:28,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 441, '_0n1': 1199}
2018-01-01 21:39:28,861 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,865 : INFO : < 200 OK [3328]
2018-01-01 21:39:28,869 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 563, '_0n1': 1211}
2018-01-01 21:39:28,869 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,873 : INFO : < 200 OK [3340]
2018-01-01 21:39:28,877 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 563, '_0n1': 1211}
2018-01-01 21:39:28,877 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,881 : INFO : < 200 OK [3340]
2018-01-01 21:39:28,885 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1211}
2018-01-01 21:39:28,885 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,889 : INFO : < 200 OK [3339]
2018-01-01 21:39:28,893 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1215}
2018-01-01 21:39:28,893 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,897 : INFO : < 200 OK [3338]
2018-01-01 21:39:28,901 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1197}
2018-01-01 21:39:28,901 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,909 : INFO : < 200 OK [3339]
2018-01-01 21:39:28,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1211}
2018-01-01 21:39:28,917 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,921 : INFO : < 200 OK [3339]
2018-01-01 21:39:28,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1215}
2018-01-01 21:39:28,925 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,930 : INFO : < 200 OK [3338]
2018-01-01 21:39:28,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1197}
2018-01-01 21:39:28,936 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,940 : INFO : < 200 OK [3339]
2018-01-01 21:39:28,944 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1211}
2018-01-01 21:39:28,945 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,949 : INFO : < 200 OK [3339]
2018-01-01 21:39:28,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1215}
2018-01-01 21:39:28,953 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,957 : INFO : < 200 OK [3338]
2018-01-01 21:39:28,961 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1197}
2018-01-01 21:39:28,961 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,965 : INFO : < 200 OK [3339]
2018-01-01 21:39:28,969 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1211}
2018-01-01 21:39:28,969 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,973 : INFO : < 200 OK [3339]
2018-01-01 21:39:28,977 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1215}
2018-01-01 21:39:28,977 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,981 : INFO : < 200 OK [3338]
2018-01-01 21:39:28,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 443, '_0n1': 1197}
2018-01-01 21:39:28,985 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,989 : INFO : < 200 OK [3339]
2018-01-01 21:39:28,993 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 444, '_0n1': 1211}
2018-01-01 21:39:28,993 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:28,997 : INFO : < 200 OK [3322]
2018-01-01 21:39:29,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 1193}
2018-01-01 21:39:29,001 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,005 : INFO : < 200 OK [3316]
2018-01-01 21:39:29,009 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 1214}
2018-01-01 21:39:29,009 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,013 : INFO : < 200 OK [3315]
2018-01-01 21:39:29,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 1217}
2018-01-01 21:39:29,017 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,021 : INFO : < 200 OK [3316]
2018-01-01 21:39:29,025 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 295, '_0n1': 1199}

2018-01-01 21:39:29,025 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,032 : INFO : < 200 OK [3332]
2018-01-01 21:39:29,037 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 296, '_0n1': 1193}
2018-01-01 21:39:29,039 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,044 : INFO : < 200 OK [3327]
2018-01-01 21:39:29,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 296, '_0n1': 1212}
2018-01-01 21:39:29,049 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,053 : INFO : < 200 OK [3327]
2018-01-01 21:39:29,057 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 296, '_0n1': 1194}
2018-01-01 21:39:29,057 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,061 : INFO : < 200 OK [3333]
2018-01-01 21:39:29,065 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 580, '_0n1': 1211}
2018-01-01 21:39:29,069 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,073 : INFO : < 200 OK [3301]
2018-01-01 21:39:29,077 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 580, '_0n1': 1199}
2018-01-01 21:39:29,077 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,081 : INFO : < 200 OK [3315]
2018-01-01 21:39:29,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 580, '_0n1': 1211}
2018-01-01 21:39:29,089 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,093 : INFO : < 200 OK [3301]
2018-01-01 21:39:29,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 580, '_0n1': 1199}
2018-01-01 21:39:29,097 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,101 : INFO : < 200 OK [3315]
2018-01-01 21:39:29,101 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 148, '_0n1': 1192}
2018-01-01 21:39:29,105 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,109 : INFO : < 200 OK [3312]
2018-01-01 21:39:29,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 148, '_0n1': 1211}
2018-01-01 21:39:29,113 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,117 : INFO : < 200 OK [3315]
2018-01-01 21:39:29,117 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 148, '_0n1': 1214}
2018-01-01 21:39:29,121 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,125 : INFO : < 200 OK [3312]
2018-01-01 21:39:29,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 297, '_0n1': 1193}
2018-01-01 21:39:29,131 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,135 : INFO : < 200 OK [3343]
2018-01-01 21:39:29,138 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 297, '_0n1': 1212}
2018-01-01 21:39:29,140 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,144 : INFO : < 200 OK [3343]
2018-01-01 21:39:29,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 297, '_0n1': 1194}
2018-01-01 21:39:29,145 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,149 : INFO : < 200 OK [3349]
2018-01-01 21:39:29,153 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 447, '_0n1': 1211}
2018-01-01 21:39:29,153 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,157 : INFO : < 200 OK [3330]
2018-01-01 21:39:29,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 581, '_0n1': 1192}
2018-01-01 21:39:29,165 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,169 : INFO : < 200 OK [3287]
2018-01-01 21:39:29,173 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 581, '_0n1': 1193}
2018-01-01 21:39:29,173 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,177 : INFO : < 200 OK [3288]
2018-01-01 21:39:29,181 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 581, '_0n1': 1214}
2018-01-01 21:39:29,185 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,189 : INFO : < 200 OK [3287]
2018-01-01 21:39:29,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 581, '_0n1': 1198}
2018-01-01 21:39:29,193 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,197 : INFO : < 200 OK [3291]
2018-01-01 21:39:29,201 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 581, '_0n1': 1199}
2018-01-01 21:39:29,201 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,209 : INFO : < 200 OK [3304]
2018-01-01 21:39:29,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 565, '_0n1': 1192}
2018-01-01 21:39:29,213 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,217 : INFO : < 200 OK [3335]
2018-01-01 21:39:29,221 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 565, '_0n1': 1211}
2018-01-01 21:39:29,221 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,229 : INFO : < 200 OK [3338]
2018-01-01 21:39:29,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 565, '_0n1': 1214}
2018-01-01 21:39:29,233 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,237 : INFO : < 200 OK [3335]
2018-01-01 21:39:29,241 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1199}
2018-01-01 21:39:29,243 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,244 : INFO : < 200 OK [3317]
2018-01-01 21:39:29,249 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1199}
2018-01-01 21:39:29,249 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,253 : INFO : < 200 OK [3317]

2018-01-01 21:39:29,257 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1199}
2018-01-01 21:39:29,261 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,265 : INFO : < 200 OK [3317]
2018-01-01 21:39:29,269 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 383, '_0n1': 1199}
2018-01-01 21:39:29,269 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,273 : INFO : < 200 OK [3317]
2018-01-01 21:39:29,277 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 582, '_0n1': 1193}
2018-01-01 21:39:29,277 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,285 : INFO : < 200 OK [3309]
2018-01-01 21:39:29,289 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 582, '_0n1': 1198}
2018-01-01 21:39:29,289 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,293 : INFO : < 200 OK [3312]
2018-01-01 21:39:29,297 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 582, '_0n1': 1199}
2018-01-01 21:39:29,297 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,305 : INFO : < 200 OK [3325]
2018-01-01 21:39:29,305 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 1211}
2018-01-01 21:39:29,309 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,313 : INFO : < 200 OK [3312]
2018-01-01 21:39:29,317 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 1211}
2018-01-01 21:39:29,317 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,321 : INFO : < 200 OK [3312]
2018-01-01 21:39:29,325 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 125, '_0n1': 1211}
2018-01-01 21:39:29,325 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,332 : INFO : < 200 OK [3312]
2018-01-01 21:39:29,337 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 195, '_0n1': 1214}
2018-01-01 21:39:29,339 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,344 : INFO : < 200 OK [3356]
2018-01-01 21:39:29,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1211}
2018-01-01 21:39:29,345 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,353 : INFO : < 200 OK [3336]
2018-01-01 21:39:29,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1193}
2018-01-01 21:39:29,357 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,361 : INFO : < 200 OK [3334]
2018-01-01 21:39:29,365 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1194}
2018-01-01 21:39:29,365 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,373 : INFO : < 200 OK [3340]
2018-01-01 21:39:29,377 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1199}
2018-01-01 21:39:29,377 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,385 : INFO : < 200 OK [3350]
2018-01-01 21:39:29,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1211}
2018-01-01 21:39:29,389 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,397 : INFO : < 200 OK [3336]
2018-01-01 21:39:29,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1193}
2018-01-01 21:39:29,405 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,409 : INFO : < 200 OK [3334]
2018-01-01 21:39:29,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1194}
2018-01-01 21:39:29,417 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,421 : INFO : < 200 OK [3340]
2018-01-01 21:39:29,425 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 400, '_0n1': 1199}
2018-01-01 21:39:29,425 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,434 : INFO : < 200 OK [3350]
2018-01-01 21:39:29,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 302, '_0n1': 1193}
2018-01-01 21:39:29,440 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,445 : INFO : < 200 OK [3322]
2018-01-01 21:39:29,449 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 302, '_0n1': 1198}
2018-01-01 21:39:29,449 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,453 : INFO : < 200 OK [3325]
2018-01-01 21:39:29,457 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 299, '_0n1': 1193}
2018-01-01 21:39:29,461 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,465 : INFO : < 200 OK [3302]
2018-01-01 21:39:29,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 299, '_0n1': 1198}
2018-01-01 21:39:29,473 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,477 : INFO : < 200 OK [3305]
2018-01-01 21:39:29,481 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 1214}
2018-01-01 21:39:29,485 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:29,489 : INFO : < 200 OK [3280]
2018-01-01 21:39:29,493 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 1214}
2018-01-01 21:39:29,493 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:29,501 : INFO : < 200 OK [3280]
2018-01-01 21:39:29,505 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 59, '_0n1': 1214}
2018-01-01 21:39:29,505 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:29,509 : INFO : < 200 OK [3280]
2018-01-01 21:39:29,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 179, '_0n1': 1214}

2018-01-01 21:39:29,517 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,525 : INFO : < 200 OK [3291]
2018-01-01 21:39:29,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 179, '_0n1': 1199}
2018-01-01 21:39:29,532 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,536 : INFO : < 200 OK [3308]
2018-01-01 21:39:29,540 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 583, '_0n1': 1192}
2018-01-01 21:39:29,542 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,545 : INFO : < 200 OK [3314]
2018-01-01 21:39:29,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 583, '_0n1': 1193}
2018-01-01 21:39:29,549 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,553 : INFO : < 200 OK [3315]
2018-01-01 21:39:29,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 583, '_0n1': 1199}
2018-01-01 21:39:29,557 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,561 : INFO : < 200 OK [3331]
2018-01-01 21:39:29,565 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 567, '_0n1': 1211}
2018-01-01 21:39:29,569 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,573 : INFO : < 200 OK [3325]
2018-01-01 21:39:29,577 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 567, '_0n1': 1199}
2018-01-01 21:39:29,577 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,581 : INFO : < 200 OK [3339]
2018-01-01 21:39:29,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 436, '_0n1': 1211}
2018-01-01 21:39:29,589 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,593 : INFO : < 200 OK [3313]
2018-01-01 21:39:29,597 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 436, '_0n1': 1199}
2018-01-01 21:39:29,597 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,601 : INFO : < 200 OK [3327]
2018-01-01 21:39:29,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1211}
2018-01-01 21:39:29,605 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,613 : INFO : < 200 OK [3347]
2018-01-01 21:39:29,617 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1215}
2018-01-01 21:39:29,617 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,621 : INFO : < 200 OK [3346]
2018-01-01 21:39:29,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1197}
2018-01-01 21:39:29,625 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,632 : INFO : < 200 OK [3347]
2018-01-01 21:39:29,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1211}
2018-01-01 21:39:29,638 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,643 : INFO : < 200 OK [3347]
2018-01-01 21:39:29,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1215}
2018-01-01 21:39:29,645 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,653 : INFO : < 200 OK [3346]
2018-01-01 21:39:29,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1197}
2018-01-01 21:39:29,657 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,661 : INFO : < 200 OK [3347]
2018-01-01 21:39:29,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1211}
2018-01-01 21:39:29,669 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,673 : INFO : < 200 OK [3347]
2018-01-01 21:39:29,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1215}
2018-01-01 21:39:29,681 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,685 : INFO : < 200 OK [3346]
2018-01-01 21:39:29,689 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1197}
2018-01-01 21:39:29,693 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,697 : INFO : < 200 OK [3347]
2018-01-01 21:39:29,701 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1211}
2018-01-01 21:39:29,701 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,705 : INFO : < 200 OK [3347]
2018-01-01 21:39:29,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1215}
2018-01-01 21:39:29,713 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,717 : INFO : < 200 OK [3346]
2018-01-01 21:39:29,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 453, '_0n1': 1197}
2018-01-01 21:39:29,721 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,729 : INFO : < 200 OK [3347]
2018-01-01 21:39:29,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1193}
2018-01-01 21:39:29,735 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,739 : INFO : < 200 OK [3335]
2018-01-01 21:39:29,742 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1212}
2018-01-01 21:39:29,744 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,745 : INFO : < 200 OK [3335]
2018-01-01 21:39:29,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1194}
2018-01-01 21:39:29,753 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,757 : INFO : < 200 OK [3341]
2018-01-01 21:39:29,761 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1199}
2018-01-01 21:39:29,761 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,765 : INFO : < 200 OK [3351]
2018-01-01 21:39:29,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1193}

2018-01-01 21:39:29,769 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,777 : INFO : < 200 OK [3335]
2018-01-01 21:39:29,777 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1212}
2018-01-01 21:39:29,781 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,785 : INFO : < 200 OK [3335]
2018-01-01 21:39:29,789 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1194}
2018-01-01 21:39:29,789 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,793 : INFO : < 200 OK [3341]
2018-01-01 21:39:29,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1199}
2018-01-01 21:39:29,797 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,801 : INFO : < 200 OK [3351]
2018-01-01 21:39:29,805 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1193}
2018-01-01 21:39:29,809 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,817 : INFO : < 200 OK [3335]
2018-01-01 21:39:29,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1212}
2018-01-01 21:39:29,821 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,829 : INFO : < 200 OK [3335]
2018-01-01 21:39:29,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1194}
2018-01-01 21:39:29,835 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,839 : INFO : < 200 OK [3341]
2018-01-01 21:39:29,843 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1199}
2018-01-01 21:39:29,845 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,849 : INFO : < 200 OK [3351]
2018-01-01 21:39:29,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1193}
2018-01-01 21:39:29,853 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,857 : INFO : < 200 OK [3335]
2018-01-01 21:39:29,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1212}
2018-01-01 21:39:29,861 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,869 : INFO : < 200 OK [3335]
2018-01-01 21:39:29,869 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1194}
2018-01-01 21:39:29,873 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,877 : INFO : < 200 OK [3341]
2018-01-01 21:39:29,881 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 584, '_0n1': 1199}
2018-01-01 21:39:29,885 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,889 : INFO : < 200 OK [3351]
2018-01-01 21:39:29,893 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 568, '_0n1': 1214}
2018-01-01 21:39:29,893 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,897 : INFO : < 200 OK [3325]
2018-01-01 21:39:29,901 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1211}
2018-01-01 21:39:29,905 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,909 : INFO : < 200 OK [3318]
2018-01-01 21:39:29,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1199}
2018-01-01 21:39:29,917 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,921 : INFO : < 200 OK [3332]
2018-01-01 21:39:29,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1211}
2018-01-01 21:39:29,925 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,932 : INFO : < 200 OK [3318]
2018-01-01 21:39:29,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1199}
2018-01-01 21:39:29,938 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,942 : INFO : < 200 OK [3332]
2018-01-01 21:39:29,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1211}
2018-01-01 21:39:29,945 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,949 : INFO : < 200 OK [3318]
2018-01-01 21:39:29,953 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 101, '_0n1': 1199}
2018-01-01 21:39:29,953 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,961 : INFO : < 200 OK [3332]
2018-01-01 21:39:29,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 1199}
2018-01-01 21:39:29,965 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,969 : INFO : < 200 OK [3333]
2018-01-01 21:39:29,973 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 1199}
2018-01-01 21:39:29,977 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,981 : INFO : < 200 OK [3333]
2018-01-01 21:39:29,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 1199}
2018-01-01 21:39:29,985 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:29,989 : INFO : < 200 OK [3333]
2018-01-01 21:39:29,993 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 102, '_0n1': 1199}
2018-01-01 21:39:29,993 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,001 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 585, '_0n1': 1211}
2018-01-01 21:39:30,005 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,009 : INFO : < 200 OK [3295]
2018-01-01 21:39:30,013 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 585, '_0n1': 1211}
2018-01-01 21:39:30,017 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,021 : INFO : < 200 OK [3295]
2018-01-01 21:39:30,025 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 569, '_0n1': 1192}

2018-01-01 21:39:30,025 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,032 : INFO : < 200 OK [3320]
2018-01-01 21:39:30,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 569, '_0n1': 1211}
2018-01-01 21:39:30,036 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,041 : INFO : < 200 OK [3323]
2018-01-01 21:39:30,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 569, '_0n1': 1193}
2018-01-01 21:39:30,045 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,049 : INFO : < 200 OK [3321]
2018-01-01 21:39:30,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 569, '_0n1': 1194}
2018-01-01 21:39:30,053 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,061 : INFO : < 200 OK [3327]
2018-01-01 21:39:30,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 569, '_0n1': 1217}
2018-01-01 21:39:30,065 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,069 : INFO : < 200 OK [3321]
2018-01-01 21:39:30,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 586, '_0n1': 1192}
2018-01-01 21:39:30,073 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,081 : INFO : < 200 OK [3332]
2018-01-01 21:39:30,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 586, '_0n1': 1211}
2018-01-01 21:39:30,085 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,089 : INFO : < 200 OK [3335]
2018-01-01 21:39:30,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 586, '_0n1': 1192}
2018-01-01 21:39:30,093 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,101 : INFO : < 200 OK [3332]
2018-01-01 21:39:30,101 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 586, '_0n1': 1211}
2018-01-01 21:39:30,105 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,109 : INFO : < 200 OK [3335]
2018-01-01 21:39:30,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 1193}
2018-01-01 21:39:30,117 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,121 : INFO : < 200 OK [3316]
2018-01-01 21:39:30,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 1212}
2018-01-01 21:39:30,125 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,135 : INFO : < 200 OK [3316]
2018-01-01 21:39:30,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 1194}
2018-01-01 21:39:30,141 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,145 : INFO : < 200 OK [3322]
2018-01-01 21:39:30,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 305, '_0n1': 1198}
2018-01-01 21:39:30,149 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,157 : INFO : < 200 OK [3319]
2018-01-01 21:39:30,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 456, '_0n1': 1211}
2018-01-01 21:39:30,165 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,169 : INFO : < 200 OK [3310]
2018-01-01 21:39:30,173 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 456, '_0n1': 1211}
2018-01-01 21:39:30,173 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,177 : INFO : < 200 OK [3310]
2018-01-01 21:39:30,181 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 1211}
2018-01-01 21:39:30,185 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,189 : INFO : < 200 OK [3305]
2018-01-01 21:39:30,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 1199}
2018-01-01 21:39:30,193 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,197 : INFO : < 200 OK [3319]
2018-01-01 21:39:30,201 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 1211}
2018-01-01 21:39:30,201 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,209 : INFO : < 200 OK [3305]
2018-01-01 21:39:30,209 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 457, '_0n1': 1199}
2018-01-01 21:39:30,213 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,217 : INFO : < 200 OK [3319]
2018-01-01 21:39:30,217 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 1193}
2018-01-01 21:39:30,221 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,225 : INFO : < 200 OK [3293]
2018-01-01 21:39:30,230 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 1194}
2018-01-01 21:39:30,232 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,236 : INFO : < 200 OK [3299]
2018-01-01 21:39:30,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 1193}
2018-01-01 21:39:30,242 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,245 : INFO : < 200 OK [3293]
2018-01-01 21:39:30,245 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 1194}
2018-01-01 21:39:30,249 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,253 : INFO : < 200 OK [3299]
2018-01-01 21:39:30,257 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 1193}
2018-01-01 21:39:30,257 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,261 : INFO : < 200 OK [3293]
2018-01-01 21:39:30,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 1194}
2018-01-01 21:39:30,269 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,273 : INFO : < 200 OK [3299]
2018-01-01 21:39:30,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 1193}

2018-01-01 21:39:30,277 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,281 : INFO : < 200 OK [3293]
2018-01-01 21:39:30,281 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 570, '_0n1': 1194}
2018-01-01 21:39:30,285 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,289 : INFO : < 200 OK [3299]
2018-01-01 21:39:30,293 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1192}
2018-01-01 21:39:30,293 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,297 : INFO : < 200 OK [3306]
2018-01-01 21:39:30,301 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1211}
2018-01-01 21:39:30,301 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,305 : INFO : < 200 OK [3309]
2018-01-01 21:39:30,309 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1193}
2018-01-01 21:39:30,309 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,313 : INFO : < 200 OK [3307]
2018-01-01 21:39:30,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1194}
2018-01-01 21:39:30,317 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,321 : INFO : < 200 OK [3313]
2018-01-01 21:39:30,325 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1217}
2018-01-01 21:39:30,325 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,329 : INFO : < 200 OK [3307]
2018-01-01 21:39:30,334 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1192}
2018-01-01 21:39:30,336 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,340 : INFO : < 200 OK [3306]
2018-01-01 21:39:30,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1211}
2018-01-01 21:39:30,344 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,346 : INFO : < 200 OK [3309]
2018-01-01 21:39:30,350 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1193}
2018-01-01 21:39:30,350 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,358 : INFO : < 200 OK [3307]
2018-01-01 21:39:30,362 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1194}
2018-01-01 21:39:30,362 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,366 : INFO : < 200 OK [3313]
2018-01-01 21:39:30,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 587, '_0n1': 1217}
2018-01-01 21:39:30,374 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,378 : INFO : < 200 OK [3307]
2018-01-01 21:39:30,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 403, '_0n1': 1211}
2018-01-01 21:39:30,386 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,390 : INFO : < 200 OK [3357]
2018-01-01 21:39:30,390 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 403, '_0n1': 1199}
2018-01-01 21:39:30,394 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,398 : INFO : < 200 OK [3371]
2018-01-01 21:39:30,402 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 322, '_0n1': 1193}
2018-01-01 21:39:30,402 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,406 : INFO : < 200 OK [3308]
2018-01-01 21:39:30,410 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 322, '_0n1': 1198}
2018-01-01 21:39:30,410 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,414 : INFO : < 200 OK [3311]
2018-01-01 21:39:30,418 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1193}
2018-01-01 21:39:30,418 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,426 : INFO : < 200 OK [3330]
2018-01-01 21:39:30,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1212}
2018-01-01 21:39:30,431 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,435 : INFO : < 200 OK [3330]
2018-01-01 21:39:30,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1194}
2018-01-01 21:39:30,440 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,444 : INFO : < 200 OK [3336]
2018-01-01 21:39:30,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1199}
2018-01-01 21:39:30,446 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,450 : INFO : < 200 OK [3346]
2018-01-01 21:39:30,454 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1193}
2018-01-01 21:39:30,454 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,458 : INFO : < 200 OK [3330]
2018-01-01 21:39:30,462 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1212}
2018-01-01 21:39:30,462 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,466 : INFO : < 200 OK [3330]
2018-01-01 21:39:30,470 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1194}
2018-01-01 21:39:30,470 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,474 : INFO : < 200 OK [3336]
2018-01-01 21:39:30,478 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1199}
2018-01-01 21:39:30,478 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,482 : INFO : < 200 OK [3346]
2018-01-01 21:39:30,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1193}
2018-01-01 21:39:30,486 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,490 : INFO : < 200 OK [3330]
2018-01-01 21:39:30,494 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1212}

2018-01-01 21:39:30,494 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,498 : INFO : < 200 OK [3330]
2018-01-01 21:39:30,502 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1194}
2018-01-01 21:39:30,502 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,506 : INFO : < 200 OK [3336]
2018-01-01 21:39:30,510 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1199}
2018-01-01 21:39:30,510 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,518 : INFO : < 200 OK [3346]
2018-01-01 21:39:30,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1193}
2018-01-01 21:39:30,522 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,530 : INFO : < 200 OK [3330]
2018-01-01 21:39:30,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1212}
2018-01-01 21:39:30,534 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,538 : INFO : < 200 OK [3330]
2018-01-01 21:39:30,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1194}
2018-01-01 21:39:30,543 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,546 : INFO : < 200 OK [3336]
2018-01-01 21:39:30,550 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 571, '_0n1': 1199}
2018-01-01 21:39:30,550 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,554 : INFO : < 200 OK [3346]
2018-01-01 21:39:30,558 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 87, '_0n1': 1193}
2018-01-01 21:39:30,558 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:30,562 : INFO : < 200 OK [3301]
2018-01-01 21:39:30,566 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1255, '_0n1': 1216}
2018-01-01 21:39:30,566 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:30,574 : INFO : < 200 OK [3373]
2018-01-01 21:39:30,574 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1255, '_0n1': 1216}
2018-01-01 21:39:30,578 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:30,582 : INFO : < 200 OK [3373]
2018-01-01 21:39:30,586 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 1211}
2018-01-01 21:39:30,586 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,590 : INFO : < 200 OK [3306]
2018-01-01 21:39:30,590 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 1215}
2018-01-01 21:39:30,594 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,598 : INFO : < 200 OK [3305]
2018-01-01 21:39:30,602 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 1197}
2018-01-01 21:39:30,602 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,606 : INFO : < 200 OK [3306]
2018-01-01 21:39:30,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 463, '_0n1': 1199}
2018-01-01 21:39:30,610 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,614 : INFO : < 200 OK [3320]
2018-01-01 21:39:30,618 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 480, '_0n1': 1195}
2018-01-01 21:39:30,618 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,622 : INFO : < 200 OK [3308]
2018-01-01 21:39:30,626 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 480, '_0n1': 1195}
2018-01-01 21:39:30,626 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,632 : INFO : < 200 OK [3308]
2018-01-01 21:39:30,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 1211}
2018-01-01 21:39:30,637 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,641 : INFO : < 200 OK [3346]
2018-01-01 21:39:30,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 1211}
2018-01-01 21:39:30,646 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,650 : INFO : < 200 OK [3346]
2018-01-01 21:39:30,654 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 1211}
2018-01-01 21:39:30,654 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,662 : INFO : < 200 OK [3346]
2018-01-01 21:39:30,670 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 105, '_0n1': 1211}
2018-01-01 21:39:30,670 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,674 : INFO : < 200 OK [3346]
2018-01-01 21:39:30,678 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 588, '_0n1': 1192}
2018-01-01 21:39:30,682 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,686 : INFO : < 200 OK [3317]
2018-01-01 21:39:30,690 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 588, '_0n1': 1193}
2018-01-01 21:39:30,690 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,698 : INFO : < 200 OK [3318]
2018-01-01 21:39:30,702 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 588, '_0n1': 1215}
2018-01-01 21:39:30,702 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,706 : INFO : < 200 OK [3319]
2018-01-01 21:39:30,710 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 588, '_0n1': 1197}
2018-01-01 21:39:30,710 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,714 : INFO : < 200 OK [3320]
2018-01-01 21:39:30,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 1193}
2018-01-01 21:39:30,722 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,726 : INFO : < 200 OK [3331]
2018-01-01 21:39:30,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 1212}

2018-01-01 21:39:30,730 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,734 : INFO : < 200 OK [3331]
2018-01-01 21:39:30,738 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 1194}
2018-01-01 21:39:30,739 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,744 : INFO : < 200 OK [3337]
2018-01-01 21:39:30,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 323, '_0n1': 1198}
2018-01-01 21:39:30,746 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,754 : INFO : < 200 OK [3334]
2018-01-01 21:39:30,754 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 138, '_0n1': 1214}
2018-01-01 21:39:30,758 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,762 : INFO : < 200 OK [3318]
2018-01-01 21:39:30,762 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 307, '_0n1': 1198}
2018-01-01 21:39:30,766 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,770 : INFO : < 200 OK [3327]
2018-01-01 21:39:30,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:30,774 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,778 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,782 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}
2018-01-01 21:39:30,782 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,786 : INFO : < 200 OK [3332]
2018-01-01 21:39:30,790 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:30,790 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,794 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,798 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:30,798 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,802 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}
2018-01-01 21:39:30,806 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,810 : INFO : < 200 OK [3332]
2018-01-01 21:39:30,814 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:30,814 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,818 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,822 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:30,826 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,832 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}
2018-01-01 21:39:30,837 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,842 : INFO : < 200 OK [3332]
2018-01-01 21:39:30,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:30,845 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,850 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:30,854 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,858 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,862 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}
2018-01-01 21:39:30,862 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,866 : INFO : < 200 OK [3332]
2018-01-01 21:39:30,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:30,870 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,874 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,878 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:30,878 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,882 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,886 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}
2018-01-01 21:39:30,886 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,890 : INFO : < 200 OK [3332]
2018-01-01 21:39:30,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:30,894 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,898 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,902 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1211}
2018-01-01 21:39:30,906 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,910 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,910 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1215}
2018-01-01 21:39:30,914 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,918 : INFO : < 200 OK [3332]
2018-01-01 21:39:30,918 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 405, '_0n1': 1197}
2018-01-01 21:39:30,922 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,926 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,926 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 1211}
2018-01-01 21:39:30,931 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,936 : INFO : < 200 OK [3312]
2018-01-01 21:39:30,940 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 1199}
2018-01-01 21:39:30,942 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,950 : INFO : < 200 OK [3326]
2018-01-01 21:39:30,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 1211}

2018-01-01 21:39:30,954 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,958 : INFO : < 200 OK [3312]
2018-01-01 21:39:30,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 483, '_0n1': 1199}
2018-01-01 21:39:30,962 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,966 : INFO : < 200 OK [3326]
2018-01-01 21:39:30,966 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 572, '_0n1': 1193}
2018-01-01 21:39:30,970 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,974 : INFO : < 200 OK [3317]
2018-01-01 21:39:30,978 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 572, '_0n1': 1199}
2018-01-01 21:39:30,978 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:30,982 : INFO : < 200 OK [3333]
2018-01-01 21:39:30,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1239, '_0n1': 1211}
2018-01-01 21:39:30,990 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:30,994 : INFO : < 200 OK [3368]
2018-01-01 21:39:30,998 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 1239, '_0n1': 1193}
2018-01-01 21:39:30,998 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2018-01-01 21:39:31,002 : INFO : < 200 OK [3366]
2018-01-01 21:39:31,006 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 589, '_0n1': 1193}
2018-01-01 21:39:31,006 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,010 : INFO : < 200 OK [3349]
2018-01-01 21:39:31,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 589, '_0n1': 1199}
2018-01-01 21:39:31,014 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,018 : INFO : < 200 OK [3365]
2018-01-01 21:39:31,022 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 593, '_0n1': 1192}
2018-01-01 21:39:31,022 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,026 : INFO : < 200 OK [3282]
2018-01-01 21:39:31,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 593, '_0n1': 1214}
2018-01-01 21:39:31,032 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,037 : INFO : < 200 OK [3282]
2018-01-01 21:39:31,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 590, '_0n1': 1193}
2018-01-01 21:39:31,042 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,045 : INFO : < 200 OK [3331]
2018-01-01 21:39:31,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 590, '_0n1': 1193}
2018-01-01 21:39:31,050 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,054 : INFO : < 200 OK [3331]
2018-01-01 21:39:31,054 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 590, '_0n1': 1193}
2018-01-01 21:39:31,058 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,062 : INFO : < 200 OK [3331]
2018-01-01 21:39:31,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 470, '_0n1': 1193}
2018-01-01 21:39:31,066 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,070 : INFO : < 200 OK [3348]
2018-01-01 21:39:31,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 1193}
2018-01-01 21:39:31,078 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,082 : INFO : < 200 OK [3283]
2018-01-01 21:39:31,090 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 1214}
2018-01-01 21:39:31,090 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,098 : INFO : < 200 OK [3282]
2018-01-01 21:39:31,102 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 1217}
2018-01-01 21:39:31,102 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,106 : INFO : < 200 OK [3283]
2018-01-01 21:39:31,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 325, '_0n1': 1199}
2018-01-01 21:39:31,110 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,118 : INFO : < 200 OK [3299]
2018-01-01 21:39:31,118 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 1211}
2018-01-01 21:39:31,122 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:31,126 : INFO : < 200 OK [3306]
2018-01-01 21:39:31,126 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 1211}
2018-01-01 21:39:31,131 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:31,135 : INFO : < 200 OK [3306]
2018-01-01 21:39:31,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 91, '_0n1': 1211}
2018-01-01 21:39:31,139 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:31,143 : INFO : < 200 OK [3306]
2018-01-01 21:39:31,146 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 1193}
2018-01-01 21:39:31,146 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,150 : INFO : < 200 OK [3319]
2018-01-01 21:39:31,154 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 1193}
2018-01-01 21:39:31,154 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,158 : INFO : < 200 OK [3319]
2018-01-01 21:39:31,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 110, '_0n1': 1193}
2018-01-01 21:39:31,162 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,166 : INFO : < 200 OK [3319]
2018-01-01 21:39:31,170 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 1193}
2018-01-01 21:39:31,170 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,174 : INFO : < 200 OK [3316]
2018-01-01 21:39:31,178 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 1214}

2018-01-01 21:39:31,178 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,182 : INFO : < 200 OK [3315]
2018-01-01 21:39:31,186 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 1217}
2018-01-01 21:39:31,186 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,190 : INFO : < 200 OK [3316]
2018-01-01 21:39:31,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 326, '_0n1': 1199}
2018-01-01 21:39:31,198 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,202 : INFO : < 200 OK [3332]
2018-01-01 21:39:31,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 160, '_0n1': 1214}
2018-01-01 21:39:31,210 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,214 : INFO : < 200 OK [3316]
2018-01-01 21:39:31,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 505, '_0n1': 1193}
2018-01-01 21:39:31,218 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,222 : INFO : < 200 OK [3321]
2018-01-01 21:39:31,226 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 327, '_0n1': 1193}
2018-01-01 21:39:31,226 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,234 : INFO : < 200 OK [3341]
2018-01-01 21:39:31,237 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 327, '_0n1': 1212}
2018-01-01 21:39:31,239 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,243 : INFO : < 200 OK [3341]
2018-01-01 21:39:31,246 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 327, '_0n1': 1194}
2018-01-01 21:39:31,246 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,250 : INFO : < 200 OK [3347]
2018-01-01 21:39:31,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 327, '_0n1': 1198}
2018-01-01 21:39:31,254 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,258 : INFO : < 200 OK [3344]
2018-01-01 21:39:31,262 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 1212}
2018-01-01 21:39:31,266 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,270 : INFO : < 200 OK [3320]
2018-01-01 21:39:31,274 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 1195}
2018-01-01 21:39:31,274 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,278 : INFO : < 200 OK [3319]
2018-01-01 21:39:31,282 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 1212}
2018-01-01 21:39:31,286 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,290 : INFO : < 200 OK [3320]
2018-01-01 21:39:31,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 513, '_0n1': 1195}
2018-01-01 21:39:31,294 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,298 : INFO : < 200 OK [3319]
2018-01-01 21:39:31,302 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1211}
2018-01-01 21:39:31,302 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:31,310 : INFO : < 200 OK [3303]
2018-01-01 21:39:31,314 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1199}
2018-01-01 21:39:31,314 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:31,322 : INFO : < 200 OK [3317]
2018-01-01 21:39:31,326 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1211}
2018-01-01 21:39:31,326 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:31,333 : INFO : < 200 OK [3303]
2018-01-01 21:39:31,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1199}
2018-01-01 21:39:31,338 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:31,342 : INFO : < 200 OK [3317]
2018-01-01 21:39:31,344 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1211}
2018-01-01 21:39:31,345 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:31,350 : INFO : < 200 OK [3303]
2018-01-01 21:39:31,350 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 95, '_0n1': 1199}
2018-01-01 21:39:31,354 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:31,358 : INFO : < 200 OK [3317]
2018-01-01 21:39:31,362 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 595, '_0n1': 1192}
2018-01-01 21:39:31,362 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,366 : INFO : < 200 OK [3335]
2018-01-01 21:39:31,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 328, '_0n1': 1193}
2018-01-01 21:39:31,370 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,374 : INFO : < 200 OK [3309]
2018-01-01 21:39:31,378 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 328, '_0n1': 1212}
2018-01-01 21:39:31,382 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,386 : INFO : < 200 OK [3309]
2018-01-01 21:39:31,390 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 328, '_0n1': 1194}
2018-01-01 21:39:31,390 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,394 : INFO : < 200 OK [3315]
2018-01-01 21:39:31,398 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1211}
2018-01-01 21:39:31,398 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,406 : INFO : < 200 OK [3288]
2018-01-01 21:39:31,406 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1199}
2018-01-01 21:39:31,410 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,414 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,418 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1211}

2018-01-01 21:39:31,418 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,422 : INFO : < 200 OK [3288]
2018-01-01 21:39:31,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1199}
2018-01-01 21:39:31,426 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,434 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1211}
2018-01-01 21:39:31,442 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,445 : INFO : < 200 OK [3288]
2018-01-01 21:39:31,445 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 114, '_0n1': 1199}
2018-01-01 21:39:31,449 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,453 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,457 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 8, '_0n1': 1199}
2018-01-01 21:39:31,457 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:31,461 : INFO : < 200 OK [3303]
2018-01-01 21:39:31,465 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 8, '_0n1': 1199}
2018-01-01 21:39:31,469 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2018-01-01 21:39:31,473 : INFO : < 200 OK [3303]
2018-01-01 21:39:31,473 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 516, '_0n1': 1195}
2018-01-01 21:39:31,477 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,481 : INFO : < 200 OK [3305]
2018-01-01 21:39:31,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 516, '_0n1': 1195}
2018-01-01 21:39:31,485 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,489 : INFO : < 200 OK [3305]
2018-01-01 21:39:31,493 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 592, '_0n1': 1198}
2018-01-01 21:39:31,493 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,497 : INFO : < 200 OK [3294]
2018-01-01 21:39:31,501 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 312, '_0n1': 1193}
2018-01-01 21:39:31,501 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,505 : INFO : < 200 OK [3350]
2018-01-01 21:39:31,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 312, '_0n1': 1198}
2018-01-01 21:39:31,509 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,513 : INFO : < 200 OK [3353]
2018-01-01 21:39:31,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 27, '_0n1': 1213}
2018-01-01 21:39:31,517 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2018-01-01 21:39:31,521 : INFO : < 200 OK [3296]
2018-01-01 21:39:31,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1193}
2018-01-01 21:39:31,525 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,529 : INFO : < 200 OK [3291]
2018-01-01 21:39:31,534 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1198}
2018-01-01 21:39:31,536 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,540 : INFO : < 200 OK [3294]
2018-01-01 21:39:31,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1193}
2018-01-01 21:39:31,545 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,545 : INFO : < 200 OK [3291]
2018-01-01 21:39:31,550 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1198}
2018-01-01 21:39:31,550 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,558 : INFO : < 200 OK [3294]
2018-01-01 21:39:31,558 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1193}
2018-01-01 21:39:31,562 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,570 : INFO : < 200 OK [3291]
2018-01-01 21:39:31,574 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 313, '_0n1': 1198}
2018-01-01 21:39:31,578 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,582 : INFO : < 200 OK [3294]
2018-01-01 21:39:31,586 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 186, '_0n1': 1198}
2018-01-01 21:39:31,586 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,590 : INFO : < 200 OK [3293]
2018-01-01 21:39:31,594 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1192}
2018-01-01 21:39:31,594 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,602 : INFO : < 200 OK [3305]
2018-01-01 21:39:31,602 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1193}
2018-01-01 21:39:31,606 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,610 : INFO : < 200 OK [3306]
2018-01-01 21:39:31,610 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1194}
2018-01-01 21:39:31,614 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,618 : INFO : < 200 OK [3312]
2018-01-01 21:39:31,618 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1198}
2018-01-01 21:39:31,622 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,626 : INFO : < 200 OK [3309]
2018-01-01 21:39:31,630 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1192}
2018-01-01 21:39:31,632 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,636 : INFO : < 200 OK [3305]
2018-01-01 21:39:31,638 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1193}
2018-01-01 21:39:31,640 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,644 : INFO : < 200 OK [3306]
2018-01-01 21:39:31,646 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1194}

2018-01-01 21:39:31,646 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,650 : INFO : < 200 OK [3312]
2018-01-01 21:39:31,654 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1198}
2018-01-01 21:39:31,654 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,662 : INFO : < 200 OK [3309]
2018-01-01 21:39:31,662 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1192}
2018-01-01 21:39:31,662 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,666 : INFO : < 200 OK [3305]
2018-01-01 21:39:31,670 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1193}
2018-01-01 21:39:31,670 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,674 : INFO : < 200 OK [3306]
2018-01-01 21:39:31,678 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1194}
2018-01-01 21:39:31,678 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,682 : INFO : < 200 OK [3312]
2018-01-01 21:39:31,686 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 596, '_0n1': 1198}
2018-01-01 21:39:31,686 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,690 : INFO : < 200 OK [3309]
2018-01-01 21:39:31,694 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 330, '_0n1': 1217}
2018-01-01 21:39:31,694 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,698 : INFO : < 200 OK [3309]
2018-01-01 21:39:31,702 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 613, '_0n1': 1198}
2018-01-01 21:39:31,706 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,710 : INFO : < 200 OK [3305]
2018-01-01 21:39:31,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 332, '_0n1': 1217}
2018-01-01 21:39:31,714 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,718 : INFO : < 200 OK [3294]
2018-01-01 21:39:31,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 614, '_0n1': 1195}
2018-01-01 21:39:31,726 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,732 : INFO : < 200 OK [3311]
2018-01-01 21:39:31,739 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1192}
2018-01-01 21:39:31,743 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,746 : INFO : < 200 OK [3296]
2018-01-01 21:39:31,750 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1211}
2018-01-01 21:39:31,750 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,758 : INFO : < 200 OK [3299]
2018-01-01 21:39:31,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1214}
2018-01-01 21:39:31,762 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,766 : INFO : < 200 OK [3296]
2018-01-01 21:39:31,766 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1198}
2018-01-01 21:39:31,770 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,774 : INFO : < 200 OK [3300]
2018-01-01 21:39:31,778 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1192}
2018-01-01 21:39:31,778 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,786 : INFO : < 200 OK [3296]
2018-01-01 21:39:31,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1211}
2018-01-01 21:39:31,790 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,794 : INFO : < 200 OK [3299]
2018-01-01 21:39:31,794 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1214}
2018-01-01 21:39:31,798 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,802 : INFO : < 200 OK [3296]
2018-01-01 21:39:31,802 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 209, '_0n1': 1198}
2018-01-01 21:39:31,806 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,810 : INFO : < 200 OK [3300]
2018-01-01 21:39:31,814 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 599, '_0n1': 1193}
2018-01-01 21:39:31,814 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,818 : INFO : < 200 OK [3295]
2018-01-01 21:39:31,822 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1211}
2018-01-01 21:39:31,826 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,831 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1215}
2018-01-01 21:39:31,837 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,842 : INFO : < 200 OK [3301]
2018-01-01 21:39:31,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1197}
2018-01-01 21:39:31,846 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,850 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1211}
2018-01-01 21:39:31,854 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,862 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,866 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1215}
2018-01-01 21:39:31,866 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,870 : INFO : < 200 OK [3301]
2018-01-01 21:39:31,874 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1197}
2018-01-01 21:39:31,874 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,878 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1211}

2018-01-01 21:39:31,882 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,886 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,890 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1215}
2018-01-01 21:39:31,890 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,898 : INFO : < 200 OK [3301]
2018-01-01 21:39:31,898 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1197}
2018-01-01 21:39:31,902 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,906 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,910 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1211}
2018-01-01 21:39:31,910 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,918 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,918 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1215}
2018-01-01 21:39:31,922 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,926 : INFO : < 200 OK [3301]
2018-01-01 21:39:31,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 525, '_0n1': 1197}
2018-01-01 21:39:31,931 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,936 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,939 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 210, '_0n1': 1214}
2018-01-01 21:39:31,941 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,945 : INFO : < 200 OK [3317]
2018-01-01 21:39:31,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 210, '_0n1': 1214}
2018-01-01 21:39:31,945 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,954 : INFO : < 200 OK [3317]
2018-01-01 21:39:31,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 319, '_0n1': 1216}
2018-01-01 21:39:31,958 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,962 : INFO : < 200 OK [3281]
2018-01-01 21:39:31,966 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1193}
2018-01-01 21:39:31,970 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,974 : INFO : < 200 OK [3299]
2018-01-01 21:39:31,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1198}
2018-01-01 21:39:31,974 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,982 : INFO : < 200 OK [3302]
2018-01-01 21:39:31,986 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1193}
2018-01-01 21:39:31,986 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:31,994 : INFO : < 200 OK [3299]
2018-01-01 21:39:31,994 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1198}
2018-01-01 21:39:31,998 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:32,006 : INFO : < 200 OK [3302]
2018-01-01 21:39:32,006 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1193}
2018-01-01 21:39:32,010 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:32,014 : INFO : < 200 OK [3299]
2018-01-01 21:39:32,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 340, '_0n1': 1198}
2018-01-01 21:39:32,018 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:32,022 : INFO : < 200 OK [3302]
2018-01-01 21:39:32,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 604, '_0n1': 1193}
2018-01-01 21:39:32,026 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:32,033 : INFO : < 200 OK [3334]
2018-01-01 21:39:32,036 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 604, '_0n1': 1193}
2018-01-01 21:39:32,038 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:32,042 : INFO : < 200 OK [3334]
2018-01-01 21:39:32,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 604, '_0n1': 1193}
2018-01-01 21:39:32,046 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:32,046 : INFO : < 200 OK [3334]
2018-01-01 21:39:32,050 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 604, '_0n1': 1193}
2018-01-01 21:39:32,054 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:32,058 : INFO : < 200 OK [3334]
2018-01-01 21:39:32,062 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 557, '_0n1': 1195}
2018-01-01 21:39:32,062 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:32,070 : INFO : < 200 OK [3330]
2018-01-01 21:39:32,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n0': 557, '_0n1': 1195}
2018-01-01 21:39:32,074 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2018-01-01 21:39:32,078 : INFO : < 200 OK [3330]

In [50]:
from vis import draw

options = {"Teacher": "name", 'Institue': 'name'}
draw(graph,"match p= (n:Course{name:'Usable Security'})-[]-() return p", options)

AttributeError: 'Graph' object has no attribute 'run'

In [ ]:
title_relation_df.head()

In [ ]:
from sklearn.cluster import KMeans
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import Normalizer

svd = TruncatedSVD(100)
normalizer = Normalizer(copy=False)
lsa = make_pipeline(svd, normalizer)
X = lsa.fit_transform(document_matrix)
inertia_list = []  
for i in range(2,15):
    kmeans = KMeans(n_clusters=i).fit(X)
    inertia_list.append(kmeans.inertia_)

import matplotlib.pyplot as plt
plt.plot(range(2,15), inertia_list, linestyle='-', marker='o')
plt.show()

In [ ]:
![image.png](attachment:image.png)

In [ ]:
#IsDuplicated = data_to_mysql.duplicated()

In [ ]:
# duplicate_course=0
# for i in range(len(data_to_mysql)):
#     if IsDuplicated[i] == True:
#         duplicate_course=duplicate_course+1
#         #print(i)
# print(duplicate_course)

In [ ]:
#data = data_to_mysql.drop_duplicates()

In [ ]:
#data_to_mysql.head()

### --------------------------------------------------------------------------------

In [ ]:
### Testing

In [ ]:
# v=[]
# for n in range(len(all_data)):
#     for j in range(len(all_data[n]['week_data'])):     
#         v.append(list((all_data[n]['week_data'][j]).values())[0])
#         #a.append(pd.Series(v).str.cat(sep=''))

In [ ]:
# v= pd.Series(v).str.cat(sep='')