In [5]:
%load_ext autoreload
%autoreload 2
# Supress default INFO logging  (Hide Info)

import logging
logger = logging.getLogger()
logger.setLevel(logging.CRITICAL)
#logging.root.hanlder = []
#logging.basicConfig(format="%(asctime)s : %(leveltime)s : %(message)s", message=logging.INFO)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
import logging
import collections
logging.root.handlers = []  # Jupyter messes up logging so needs a reset
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
from smart_open import smart_open 
import pandas as pd
import numpy as np
from numpy import random
from collections import Counter
import heapq #check n largest
import json
import warnings
from sqlalchemy import create_engine 
import nltk
import spacy
import json
import seaborn as sns

In [7]:
def isEnglish(s):
    try:
        s.encode(encoding='utf-8').decode('ascii')
    except UnicodeDecodeError:
        return False
    else:
        return True

In [8]:
bath_path = r'C:/Users/asus/Downloads/ADB_final/'

computer_security_and_networks = json.load(open(bath_path + r'computer-security-and-networks.json', encoding='utf8'))
algorithms = json.load(open(bath_path + r'algorithms.json', encoding='utf8'))
cloud_computing = json.load(open(bath_path + r'cloud-computing.json', encoding='utf8'))
data_management = json.load(open(bath_path + r'data-management.json', encoding='utf8'))
design_and_product = json.load(open(bath_path + r'design-and-product.json', encoding='utf8'))
electrical_engineering = json.load(open(bath_path + r'electrical-engineering.json', encoding='utf8'))
math_and_logic = json.load(open(bath_path + r'math-and-logic.json', encoding='utf8'))
mobile_and_web_development = json.load(open(bath_path + r'mobile-and-web-development.json', encoding='utf8'))
networking = json.load(open(bath_path + r'networking.json', encoding='utf8'))
probability_and_statistics = json.load(open(bath_path + r'probability-and-statistics.json', encoding='utf8'))
security = json.load(open(bath_path + r'security.json', encoding='utf8'))
machine_learning = json.load(open(bath_path + r'machine-learning.json', encoding='utf8'))
data_analysis = json.load(open(bath_path + r'data-analysis.json', encoding='utf8'))
software_development = json.load(open(bath_path + r'software-development.json', encoding='utf8'))

all_data = computer_security_and_networks + \
algorithms + \
cloud_computing + \
data_management + \
design_and_product + \
electrical_engineering + \
math_and_logic + \
mobile_and_web_development + \
networking + \
probability_and_statistics + \
security + \
machine_learning + \
data_analysis + \
software_development

In [9]:
len(all_data)

881

In [54]:
def get_course(course):
    cat=[]; title=[]; week_data=[]; target_audience=[]; created_by=[]; teach_by=[]
    week_data_title=[]; course_info=[]; department=[]; week_data_desc=[]
    package_num=[];package_name=[]; level=[]; rating=[]; index=[]; uid=[]
    x = 0
    for (category) in course:
        for n in range(len(eval(category))):
            for i in range(len(eval(category)[n]['teach_by'])):
                    uid.append(x)
                    cat.append(category)
                    title.append(eval(category)[n]['title'])
                    target_audience.append(eval(category)[n]['target_audience'])
                    created_by.append(eval(category)[n]['created_by'])
                    course_info.append(eval(category)[n]['course_info'])
                    package_num.append(eval(category)[n]['package_num'])
                    package_name.append(eval(category)[n]['package_name'])
                    level.append(eval(category)[n]['level'])
                    rating.append(eval(category)[n]['rating']) 
                    index.append(n)
                    teach_by.append(list((eval(category)[n]['teach_by'][i].values()))[1])  
                    department.append(list((eval(category)[n]['teach_by'][i].values()))[0])
            x += 1
    data = pd.DataFrame({
                   'category': cat,
                   'uid': uid,
                    'title': title,
                    'target_audience': target_audience,
                    'created_by' : created_by,  
                    'course_info': course_info,
                    'teach_by': teach_by,
                     'department': department,
                     'level': level,
                     'rating': rating,
                     'package_num': package_num,
                     'package_name': package_name          
                    },
                    columns = ['uid','category', 'title',
                               'course_info', 'target_audience', 'created_by','teach_by',
                               'department','package_num','package_name', 'level','rating']) 
    return data

In [55]:
course_list_cat = ['computer_security_and_networks','algorithms','cloud_computing' ,'data_management' ,
               'design_and_product','electrical_engineering' ,'math_and_logic' ,'mobile_and_web_development' ,'networking',
              'probability_and_statistics','security','machine_learning' ,'data_analysis','software_development']

In [56]:
data = get_course(course_list_cat)

In [57]:
tmp = data.drop_duplicates(subset=['uid'])
tmp.reset_index(inplace=True)

In [58]:
for i, row in tmp.iterrows():
    data.loc[(data.course_info==row.course_info) & (data.title==row.title), 'uid'] = i

In [59]:
for i, row in data.iterrows():
    if not isEnglish(row.title):
        data.drop(i, inplace=True)

In [60]:
data.head()

,uid,category,title,course_info,target_audience,created_by,teach_by,department,package_num,package_name,level,rating
0,0,computer_security_and_networks,Bitcoin and Cryptocurrency Technologies,About this course: To really understand what i...,None,Princeton University,Arvind Narayanan,Computer Science,None,None,None,4.7
1,284,computer_security_and_networks,Cryptography I,About this course: Cryptography is an indispen...,None,Stanford University,Dan Boneh,Computer Science,None,None,None,4.8
2,157,computer_security_and_networks,Google Cloud Platform Fundamentals: Core Infra...,About this course: <<< ATTENTION >>> Learners ...,Who is this class for: This specialization is ...,Google Cloud,Google Cloud Training,None,1,Architecting with Google Cloud Platform Specia...,Intermediate,4.6
3,3,computer_security_and_networks,G Suite Administrator Fundamentals,About this course: G Suite Administrator Funda...,Who is this class for: This class is intended ...,Google Cloud,Google Cloud Training,None,None,None,Beginner,4.5
4,4,computer_security_and_networks,Usable Security,About this course: This course focuses on how ...,None,"University of Maryland, College Park",Jennifer Golbeck,Human-Computer Interaction Lab,1,Cybersecurity Specialization,None,4.5

In [17]:
len(data.uid.unique())

609

In [18]:
len(data.course_info.unique())

606

In [19]:
title=[]; created_by=[]; course_info=[]
data_title=[]; data_desc=[]; data_video=[]; course_info=[];
uid = []
# teach_by, week_data: 多值
for n in range(len(all_data)):
    week_data_title=[];  week_data_desc=[];week_data_video=[]
    title.append(all_data[n]['title'])
    created_by.append(all_data[n]['created_by'])
    course_info.append(all_data[n]['course_info'])
    uid.append(n)
    
    for i in range(len(all_data[n]['week_data'])):
        week_data_desc.append(all_data[n]['week_data'][i]['description'])
        week_data_title.append(all_data[n]['week_data'][i]['title'])
        week_data_video += all_data[n]['week_data'][i]['video']
    data_title.append(week_data_title)
    data_desc.append(week_data_desc)
    data_video.append(week_data_video)

In [20]:
data_created_by = pd.DataFrame({'title': title,
                    'created_by':created_by,
                    'uid':uid,
                    'course_info':course_info},
                    columns = ['title', 'created_by', 'uid', 'course_info'])

data_detail = pd.DataFrame({     
                    'week_data_desc': data_desc,
                    'week_data_title': data_title,
                    'week_data_video': data_video
                    },
                    columns = ['week_data_desc', 'week_data_title','week_data_video'])

In [21]:
for i, row in data_created_by.iterrows():
    if not isEnglish(row.title):
        data_created_by.drop(i, inplace=True)

In [22]:
for i, row in data_created_by.iterrows():
    data_created_by.loc[(data_created_by.course_info==row.course_info) & (data_created_by.title==row.title), 'uid'] = i

In [23]:
data_created_by.head()

,title,created_by,uid,course_info
0,Bitcoin and Cryptocurrency Technologies,Princeton University,0,About this course: To really understand what i...
1,Cryptography I,Stanford University,284,About this course: Cryptography is an indispen...
2,Google Cloud Platform Fundamentals: Core Infra...,Google Cloud,157,About this course: <<< ATTENTION >>> Learners ...
3,G Suite Administrator Fundamentals,Google Cloud,3,About this course: G Suite Administrator Funda...
4,Usable Security,"University of Maryland, College Park",4,About this course: This course focuses on how ...

In [24]:
data_created_by.drop_duplicates(subset=['title', 'created_by'], inplace=True)

In [25]:
data_detail = pd.merge(data_created_by, data_detail, left_index=True, right_index=True, how="left")

In [26]:
data_detail.head()

,title,created_by,uid,course_info,week_data_desc,week_data_title,week_data_video
0,Bitcoin and Cryptocurrency Technologies,Princeton University,0,About this course: To really understand what i...,"[Learn about cryptographic building blocks (""p...","[Introduction to Crypto and Cryptocurrencies, ...","[Welcome, Cryptographic Hash Functions, Hash P..."
1,Cryptography I,Stanford University,284,About this course: Cryptography is an indispen...,[Week 1. This week's topic is an overview of ...,"[Course overview and stream ciphers, Block Cip...","[Lecture slides for all six weeks, Course over..."
2,Google Cloud Platform Fundamentals: Core Infra...,Google Cloud,157,About this course: <<< ATTENTION >>> Learners ...,"[, , , , , , , , , , , , , , , ]",[Welcome to GCP Fundamentals: Core Infrastruct...,"[Welcome, Please read me, What is Google Cloud..."
3,G Suite Administrator Fundamentals,Google Cloud,3,About this course: G Suite Administrator Funda...,[You will be setting up your G Suite account a...,"[GETTING STARTED, USERS, SERVICES, SECURITY, D...","[Welcome and Getting Started Guide!, G Suite O..."
4,Usable Security,"University of Maryland, College Park",4,About this course: This course focuses on how ...,[Fundamentals of Human-Computer Interaction: u...,"[Week 1, Week 2, Week 3, Week 4, Week 5, Week ...","[Privacy Policy, Syllabus, Grading and Logisti..."

In [61]:
for i, row in data_detail.iterrows():
    if len(row.week_data_video) == 0:
        data_detail.drop(i, inplace=True)

In [62]:
data_detail = data_detail.reset_index(drop=True)

In [29]:
len(data_detail)

596

In [30]:
nlp = spacy.load(r'C:\Users\asus\AppData\Local\Programs\Python\Python35\Lib\site-packages\en_core_web_lg\en_core_web_lg-2.0.0')

In [63]:
week_video_list = []
for video_data in data_detail.week_data_video:
    video_str = ''
    x = ' '.join(video_data)
    doc = nlp(x.lower())
    for token in doc:
        if not token.is_stop and token.is_alpha:
            video_str += token.lemma_
            video_str += ' '
    week_video_list.append(video_str)

In [64]:
data_detail['week_data_video_str'] = pd.Series(week_video_list)
data_detail.dropna(inplace=True)
data_detail = data_detail.reset_index(drop=True)

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorize = TfidfVectorizer(max_df=150)
bows = vectorize.fit(data_detail.week_data_video_str)
document_matrix = bows.transform(data_detail.week_data_video_str).toarray()

In [66]:
document_matrix.shape

(596, 8805)

In [67]:
f = bows.get_feature_names()

In [68]:
from sklearn.metrics.pairwise import cosine_similarity
result = cosine_similarity(document_matrix)

In [69]:
data_detail.loc[np.argsort(result[20])[::-1], :]

,title,created_by,uid,course_info,week_data_desc,week_data_title,week_data_video,week_data_video_str
20,Introduction to Cybersecurity for Business,University of Colorado System,463,About this course: The world runs computers. ...,[Understand the basics of computer security fo...,"[What is Practical Computer Security, The CIA ...","[Welcome!, About the Instructor, Glossary of C...",welcome about the instructor glossary of compu...
13,Information Security: Context and Introduction,University of London,13,About this course: In this course you will exp...,"[, This module introduces cryptography, which ...","[Introduction to Information Security, Introdu...","[An overview, What are you hoping to achieve i...",an overview what be -PRON- hop to achieve in t...
6,Cybersecurity and Its Ten Domains,University System of Georgia,6,About this course: This course is designed to ...,[Checkout our marquee speaker. She's the Chief...,"[Welcome and Course Overview, Introduction to ...","[Welcome to ""Cybersecurity and Its Ten Domains...",welcome to cybersecurity and -PRON- ten domain...
408,Cyber Security in Manufacturing,"University at Buffalo, The State University of...",515,About this course: The nature of digital manuf...,[The purpose of this module is to introduce yo...,[Introduction to Digital Manufacturing Securit...,"[Course Introduction, Digital Manufacturing Se...",course introduction digital manufacture securi...
49,Enterprise and Infrastructure Security,New York University Tandon School of Engineering,50,About this course: This course introduces a se...,[This module includes an introduction to many ...,"[Security Awareness, Compliance, Assessments, ...",[Introduction: What You Will Learn from This C...,introduction what -PRON- will learn from this ...
588,Software Requirements Prioritization: Risk Ana...,University of Colorado System,845,"About this course: Risk Analysis, Assessment, ...",[Once requirements have been somewhat/mostly d...,"[Risk Analysis, Assessment and Prioritization,...","[Intro to Risk Analysis, Assessment, and Prior...",intro to risk analysis assessment and prioriti...
79,The Business of Cybersecurity Capstone,University System of Georgia,874,About this course: This course intends to make...,[This module provides a welcome to the course ...,[Welcome to the Management of Information Secu...,"[An overview of this course, Welcome to securi...",an overview of this course welcome to security...
1,Cryptography I,Stanford University,284,About this course: Cryptography is an indispen...,[Week 1. This week's topic is an overview of ...,"[Course overview and stream ciphers, Block Cip...","[Lecture slides for all six weeks, Course over...",lecture slide for all six week course overview...
33,Enterprise System Management and Security,University of Colorado System,464,About this course: The world runs on computers...,[Welcome and Introduction to Enterprise System...,[It's not that different from my home computer...,"[Welcome!, About this course, Resources for bu...",welcome about this course resource for build -...
38,Cyber Threats and Attack Vectors,University of Colorado System,465,About this course: Data breaches occur nearly ...,[Welcome! This week we'll explore users and us...,[THREATS AND ATTACK VECTORS IN COMPUTER SECURI...,"[Introduction, About this course, About the In...",introduction about this course about the instr...
27,Cryptography,"University of Maryland, College Park",28,About this course: This course will introduce ...,"[Introduction to Classical Cryptography, Comp...","[Week 1, Week 2, Week 3, Week 4, Week 5, Week ...","[Course Overview, Syllabus, Programming Assign...",course overview syllabus programming assignmen...
30,Cryptography and Information Theory,University of Colorado System,322,About this course: Welcome to Cryptography and...,[This module defines the technical terms in cr...,"[Cryptography Overview, Information Entropy, B...","[Instructor Introduction, Module Objectives, A...",instructor introduction module objective alice...
42,Cyber Attack Countermeasures,New York University Tandon School of Engineering,43,About this course: This course introduces the ...,[This module provides an introduction to secur...,"[ Cyber Security Safeguards, Understanding Aut...",[Introduction: What You Will Learn from This C...,introduction what -PRON- will learn from this ...
127,Algorithms for DNA Sequencing,Johns Hopkins University,640,About this course: We will learn computational...,[This module we begin our exploration of algor...,"[DNA sequencing, strings and matching, Preproc...","[Welcome to Algorithms for DNA Sequencing, Pre...",welcome to algorithm for dna sequencing pre co...
74,Cybersecurity and the X-Factor,University System of Georgia,75,About this course: What is the X-Factor? In Cy...,[The X-factor within information security is h...,"[Introduction to the X-Factor, Security Educat...","[Course Overview video, Learning Objectives, S...",course overview video learn objective security...
60,Asymmetric Cryptography and Key Management,University of Colorado System,344,About this course: Welcome to Asymmetric Crypt...,[This module reviews the principles and requir...,"[Asymmetric Cryptography Overview, RSA Algorit...","[Instructor Introduction, Module Objectives, W...",instructor introduction module objective what ...
61,Web Connectivity and Security in Embedded Systems,EIT Digital,62,About this course: Welcome to Web Connectivity...,[In this module you will learn about the layer...,"[Introduction to Web Connectivity & Security, ...","[Introduction, Introduction to CPS: Web Connec...",introduction introduction to cps web connectiv...
7,Introduction to Cyber Attacks,New York University Tandon School of Engineering,7,About this course: This course provides learne...,[This module provides exposure to basic cyber ...,"[Introduction to Cyber Security, Understanding...",[Introduction: What You Will Learn from This C...,introduction what -PRON- will learn from this ...
64,Cryptographic Hash and Integrity Protection,University of Colorado System,346,About this course: Welcome to Cryptographic Ha...,[Cryptographic hash function is a fundamental ...,"[Cryptographic Hash Function, Cryptographic Ha...","[Instructor Introduction, Module Objectives, H...",instructor introduction module objective hash ...
130,Approximation Algorithms Part I,École normale supérieure,137,"About this course: Approximation algorithms, P...",[We introduce the course topic by a typical ex...,"[Vertex cover and Linear Programming, Knapsack...","[Lecture: Introduction, Slides, Quiz 1: P vs. ...",lecture introduction slide quiz p np review al...
62,Proactive Computer Security,University of Colorado System,468,About this course: I’ve heard this before – “I...,[This module covers information sharing. Info...,"[Information Sharing and Threat Intelligence, ...","[Introduction, About this course, About the In...",introduction about this course about the instr...
23,Home Networking Basics,Cisco,424,About this course: Welcome to the fourth of fi...,"[In this module, you will compare different ty...","[Building a Home Network, Module 2: Connecting...","[About this Course, Cisco Packet Tracer, Conne...",about this course cisco packet tracer connect ...
48,Real-Time Cyber Threat Detection and Mitigation,New York University Tandon School of Engineering,49,About this course: This course introduces real...,[This module introduces the basics of TCP/IP f...,"[Basic Network Security, More Advanced Network...",[Introduction: What You Will Learn from This C...,introduction what -PRON- will learn from this ...
36,Classical Cryptosystems and Core Concepts,University of Colorado System,329,About this course: Welcome to Introduction to ...,[This module covers an introduction of the spe...,"[Specialization Introduction, Cryptographic Ti...","[About the Instructors, Course Introduction, A...",about the instructor course introduction about...
46,Windows Server Management and Security,University of Colorado System,466,About this course: Microsoft Windows has been ...,[In this module we'll discuss how Windows is u...,[Introduction to practical Windows system mana...,"[Welcome!, About This Course, Resources for bu...",welcome about this course resource for build -...
157,Introduction to the Internet of Things and Emb...,"University of California, Irvine",726,About this course: The explosive growth of the...,[The Internet of Things (IoT) is a popular buz...,"[What Is the Internet of Things (IoT)?, Embedd...","[Pre-Course Survey, Prof. Harris' Introduction...",pre course survey prof harris introduction cou...
22,Design and Analyze Secure Networked Systems,University of Colorado System,195,"About this course: In this MOOC, we will learn...","[In this module, we will introduce the basic c...",[Cybersecurity Concepts and Security Principle...,"[Course Overview, Lesson 1. Vulnerabilities a...",course overview lesson vulnerability and threa...
257,Introduction to Complex Analysis,Wesleyan University,305,About this course: This course provides an int...,[We’ll begin this module by briefly learning a...,"[Introduction to Complex Numbers, Complex Func...","[History of Complex Numbers, Lecture Slides, A...",history of complex number lecture slide algebr...
285,Dynamical Modeling Methods for Systems Biology,Icahn School of Medicine at Mount Sinai,347,About this course: An introduction to dynamica...,"[The description goes here, The description go...","[Introduction | Computing with MATLAB, Introdu...","[Syllabus, Supplemental Files, Lecture 1 - Int...",syllabus supplemental file lecture introductio...
67,"Planning, Auditing and Maintaining Enterprise ...",University of Colorado System,469,About this course: Good system management not ...,[This module covers the essentials of what you...,"[Critical first steps in System Management, Pl...","[Introduction, About this course, Resources fo...",introduction about this course resource for bu...
...,...,...,...,...,...,...,...,...
239,Capstone Design Project in Power Electronics,University of Colorado Boulder,277,About this course: Learners will design a DC-D...,[Select a converter circuit approach for the b...,"[Introduction and Power Stage Design, Power St...","[Introduction and Specifications, Introduction...",introduction and specification introduction sp...
331,App Design and Development for iOS,University of Toronto,409,About this course: In App Design and Developme...,"[Get oriented to the course., In this module y...",[Welcome to App Design and Development for iOS...,"[Welcome to the Course, Demo Project File, Scr...",welcome to the course demo project file scroll...
338,iOS Project: Transreality Game,"University of California, Irvine",417,About this course: Students will produce a net...,[In this module we go through the project that...,"[The Project and the Plan, Basic Scaffold Impl...","[Project Description, Capstone Grading, Welcom...",project description capstone grading welcome p...
143,The Fundamentals of Computing Capstone Exam,Rice University,871,About this course: While most specializations ...,[Complete a 25 question exam to demonstrate yo...,[Fundamentals of Computing Capstone Exam],"[Class Overview, Exam Preparation, Frequently ...",class overview exam preparation frequently ask...
569,Parallel programming,École Polytechnique Fédérale de Lausanne,764,About this course: With every smartphone and c...,[We motivate parallel programming and introduc...,"[Parallel Programming, Basic Task Parallel Alg...","[Course Overview, Introduction to Parallel Com...",course overview introduction to parallel compu...
259,Mathematical Biostatistics Boot Camp 1,Johns Hopkins University,309,About this course: This class presents the fun...,[You are about to undergo an intense and deman...,"[Introduction, Probability, Expectations, and ...","[Welcome to the Course, Syllabus, Faculty, Bio...",welcome to the course syllabus faculty biostat...
410,Recommender Systems Capstone,University of Minnesota,518,About this course: This capstone project cours...,[],[Capstone Project],"[Capstone Course: Introduction, Capstone Assig...",capstone course introduction capstone assignme...
552,"C++ For C Programmers, Part A","University of California, Santa Cruz",715,About this course: This course is for experien...,[How to convert an existing C program to C++. ...,"[Module 1, Module 2, Module 3, Module 4, Final...","[1.0 Module 1 Overview, 1.1 Overview and Cours...",module overview overview and course organizati...
373,Structuring Machine Learning Projects,deeplearning.ai,520,About this course: You will learn how to build...,"[, ]","[ML Strategy (1), ML Strategy (2)]","[Why ML Strategy, Orthogonalization, Single nu...",why ml strategy orthogonalization single numbe...
287,Robotics: Capstone,University of Pennsylvania,358,About this course: In our 6 week Robotics Caps...,[Welcome to Robotics Capstone! This week you w...,"[Week 1, Week 2, Week 3, Week 4, Week 5, Week 6]",[Capstone Introduction and Choosing the Capsto...,capstone introduction and choose the capstone ...
384,Deep Learning for Business,Yonsei University,488,"About this course: Your smartphone, smartwatch...","[For the course “Deep Learning for Business,” ...","[Deep Learning Products & Services , Business ...",[0.0 Introduction to Deep Learning for Busines...,introduction to deep learning for business fut...
78,Cloud Computing Project,University of Illinois at Urbana-Champaign,79,About this course: Note: You should complete a...,"[In this module, you will become familiar with...","[Orientation, Week 1 - Task Overview, Week 2, ...","[Welcome to the Cloud Computing Project!, Orie...",welcome to the cloud computing project orienta...
334,Interfaz de usuario en iOS,Tecnológico de Monterrey,864,About this course: En este curso podrás crear ...,"[La interfaz gráfica, una pieza fundamental en...","[Introducción y bienvenida, La interfaz gráfic...","[Bienvenidos al curso, La experiencia gráfica,...",bienvenidos al curso la experiencia gráfica pl...
205,System Validation (2): Model process behaviour,EIT Digital,857,About this course: System Validation is the fi...,"[, , ]","[Sequential behaviour, Data types, Parallel be...","[Introduction MOOC model process behaviour, Ac...",introduction mooc model process behaviour acti...
206,System Validation (3): Requirements by modal f...,EIT Digital,860,About this course: System Validation is the fi...,[In this module you learn how to specify requi...,"[Basic modal formulas, Advanced modal formulas]",[Introduction MOOC requirements by modal formu...,introduction mooc requirement by modal formula...
207,UI Design Capstone,University of Minnesota,868,About this course: This Capstone Course for th...,"[, , , , , , , ]","[Preface, User research and ideation I, User r...","[Welcome to UI Design Capstone Project, Projec...",welcome to ui design capstone project project ...
274,Valuing Companies,University of Michigan,330,About this course: This course is a theoretica...,[This module contains detailed videos and syll...,"[Overview of Specialization & Course, Module 1...","[Specialization: An Overview , Specialization:...",specialization an overview specialization a co...
483,Understanding Your Data: Analytical Tools,University of Virginia,624,About this course: Are you trying to understan...,[Welcome to the first week of our research met...,"[Mediation and Moderation, Conditional Indirec...","[Course Overview, Course Overview and Requirem...",course overview course overview and requiremen...
496,Data Analysis Tools,Wesleyan University,637,"About this course: In this course, you will de...",[This session starts where the Data Management...,"[Hypothesis Testing and ANOVA, Chi Square Test...",[Lesson 1 - The role of probability in inferen...,lesson the role of probability in inference le...
232,Magnetics for Power Electronic Converters,University of Colorado Boulder,269,About this course: This course covers the anal...,[This module introduces the physical principle...,"[Introduction to Magnetics and Inductors, Tran...","[Introduction to Magnetics, Inductance, Reluct...",introduction to magnetic inductance reluctance...
366,Statistics for Genomic Data Science,Johns Hopkins University,455,About this course: An introduction to the stat...,[This course is structured to hit the key conc...,"[Module 1, Module 2, Module 3, Module 4]",[Welcome to Statistics for Genomic Data Scienc...,welcome to statistic for genomic datum science...
508,Bioconductor for Genomic Data Science,Johns Hopkins University,655,About this course: Learn to use tools from the...,[The class will cover how to install and use B...,"[Week One, Week Two, Week Three, Week Four]","[Welcome, Syllabus, Pre Course Survey, Install...",welcome syllabus pre course survey instal r on...
98,Big Data Analysis with Scala and Spark,École Polytechnique Fédérale de Lausanne,100,About this course: Manipulating big data distr...,[Get up and running with Scala on your compute...,"[Getting Started + Spark Basics, Reduction Ope...","[Tools setup, Eclipse tutorial, Intellij IDEA ...",tool setup eclipse tutorial intellij idea tuto...
267,Fibonacci Numbers and the Golden Ratio,The Hong Kong University of Science and Techno...,319,About this course: This is a course about the ...,"[By the end of this week, you will be able to:...","[Dip your toes in the water, Dive deeper, Swim...","[Course Overview, Assignments and Grading, Pre...",course overview assignment and grade pre cours...
223,Wireless Communications for Everybody,Yonsei University,258,About this course: This course will provide an...,"[In this part of the course, we will learn the...",[Introduction and History of Cellular Communic...,"[1.1 Cellular Communication, Services in Cellu...",cellular communication service in cellular sys...
531,Data Mining Project,University of Illinois at Urbana-Champaign,872,About this course: Note: You should complete a...,"[In this module, you will become familiar with...","[Orientation, Task 1 - Exploration of a Data S...","[Welcome to the Data Mining Project!, Orientat...",welcome to the data mining project orientation...
540,Data Analysis and Interpretation Capstone,Wesleyan University,692,About this course: The Capstone project will a...,"[In this Module, your goal is to review the le...",[Module 1. Identify Your Data and Research Que...,"[Read Me First, Introduction to the Capstone C...",read -PRON- first introduction to the capstone...
32,Getting Started with Google Kubernetes Engine,Google Cloud,162,About this course: >>> By enrolling in this co...,"[Welcome to the course., Acquaint yourself wit...",[Welcome to Getting Started with Google Kubern...,"[Welcome to the Course, Course Overview, What ...",welcome to the course course overview what be ...
542,Mastering Software Development in R Capstone,Johns Hopkins University,876,About this course: R Programming Capstone,[The overall goal of the capstone project is t...,"[Obtain and Clean the Data, Building Geoms, Bu...","[Welcome to the Capstone Project, Introduction...",welcome to the capstone project introduction m...
336,"Capstone MOOC for ""Android App Development""",Vanderbilt University,870,About this course: The Capstone project integr...,[This module provides an introduction to the c...,"[Capstone Overview, Week 2 Milestone, Week 3 M...","[Overview of the Capstone Project, Summary of ...",overview of the capstone project summary of th...

In [70]:
## build title & Top-5 relation   (use this to build similatyty)

def get_nth_relation(index, n_th):
    return data_detail.loc[np.argsort(result[index])[::-1][n_th], :]['uid']

title_relation_df = pd.DataFrame(data_detail[['title', 'uid']])
title_relation_df['index'] = list(range(len(data_detail)))

top_n = 5
for i in range(1, top_n+1):
    str_i = str(i)
    title_relation_df['relate_'+str_i] = title_relation_df['index'].apply(lambda x: get_nth_relation(x, i))

title_relation_df.drop('index', axis=1, inplace=True)
title_relation_df.head()

,title,uid,relate_1,relate_2,relate_3,relate_4,relate_5
0,Bitcoin and Cryptocurrency Technologies,0,852,346,596,294,707
1,Cryptography I,284,28,340,822,344,463
2,Google Cloud Platform Fundamentals: Core Infra...,157,840,867,161,159,829
3,G Suite Administrator Fundamentals,3,250,733,436,365,706
4,Usable Security,4,654,858,743,60,70

In [71]:
## data_more for more word  (need data, data_detail)
data_more = pd.merge(data, data_detail, left_on='uid', right_on='uid', how="left")

## lower check, in 'data_more'
print ('lower check:')
check_list = ['C++', 'python', 'Java', 'HTML', 'Javascript', 'PHP', ' R ', ' C ', 'perl', 'spark', 'hadoop',
              'Swift', 'Android', 'Ruby', 'programming language']

for check_ele in check_list:
    check_times = 0
    check_ele = check_ele.lower()
    for all_info in data_more.values:
        info = ' '
        for all_info_ele in all_info:
            info = info + ' ' + str(all_info_ele)
        if check_ele in info.lower():
            check_times += 1
    print ('check_ele: "{}", check_times: {}'.format(check_ele, check_times))
##  data_language_df:  use it to build language relation

def check_function(uid, check_ele):
    data_target = data_more[data_more['uid']==uid]
    for all_info in data_target.values:
        info = ' '
        for all_info_ele in all_info:
            info = info + ' ' + str(all_info_ele)
        if check_ele in info.lower():
            return True
        else:
            return False

check_list = ['C++', 'python', 'Java', 'HTML', 'Javascript', 'PHP', ' R ', ' C ', 
              'perl', 'spark', 'hadoop', 'Swift', 'Android', 'Ruby', 'programming language']

data_language_df = pd.DataFrame(data_more['uid'])
for check_ele in check_list:
    check_ele = check_ele.lower()
    data_language_df[check_ele] = data_language_df['uid'].apply(lambda x: check_function(x, check_ele))
check_list.insert(0, 'uid')
data_language_df.columns = check_list
data_language_df.head()

lower check:
check_ele: "c++", check_times: 36
check_ele: "python", check_times: 272
check_ele: "java", check_times: 183
check_ele: "html", check_times: 84
check_ele: "javascript", check_times: 79
check_ele: "php", check_times: 14
check_ele: " r ", check_times: 153
check_ele: " c ", check_times: 48
check_ele: "perl", check_times: 25
check_ele: "spark", check_times: 68
check_ele: "hadoop", check_times: 59
check_ele: "swift", check_times: 19
check_ele: "android", check_times: 66
check_ele: "ruby", check_times: 22
check_ele: "programming language", check_times: 189

,uid,C++,python,Java,HTML,Javascript,PHP,R,C,perl,spark,hadoop,Swift,Android,Ruby,programming language
0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,284,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,157,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [72]:
data_clear = data.drop_duplicates(subset = ['uid'])

In [73]:
from py2neo import Graph
from py2neo import Relationship
from py2neo import Node

graph = Graph()
graph.delete_all()

2017-12-31 21:30:54,898 : INFO : > Sending batch request with 2 jobs
2017-12-31 21:30:54,901 : INFO : > {0} POST cypher {"query":"MATCH ()-[r]->()\nDELETE r"}
2017-12-31 21:30:54,906 : INFO : > {1} POST cypher {"query":"MATCH (n)\nDELETE n"}
2017-12-31 21:30:54,910 : INFO : > POST http://localhost:7474/db/data/batch [164]
2017-12-31 21:30:54,916 : INFO : ~ Reconnecting (peer closed connection)
2017-12-31 21:30:55,922 : INFO : > POST http://localhost:7474/db/data/batch [164]
2017-12-31 21:30:56,049 : INFO : < 200 OK [141]
2017-12-31 21:30:56,054 : INFO : < Received batch response for 2 jobs
2017-12-31 21:30:56,058 : INFO : < Discarding batch response

In [74]:
cat_dict = {}
for category in course_list_cat:
    cat_dict[category] = Node("Category", name=category)
    graph.create(cat_dict[category])

2017-12-31 21:30:56,275 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'computer_security_and_networks'}}
2017-12-31 21:30:56,278 : INFO : > POST http://localhost:7474/db/data/cypher [106]
2017-12-31 21:30:56,285 : INFO : < 200 OK [1392]
2017-12-31 21:30:56,290 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'algorithms'}}
2017-12-31 21:30:56,293 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:30:56,300 : INFO : < 200 OK [1372]
2017-12-31 21:30:56,304 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'cloud_computing'}}
2017-12-31 21:30:56,308 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:30:56,315 : INFO : < 200 OK [1377]
2017-12-31 21:30:56,319 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'data_management'}}
2017-12-31 21:30:56,322 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:30:56,327 : INFO : < 200 OK [1377]
2017-12-31 21:30:56,331 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'design_and_product'}}
2017-12-31 21:30:56,334 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:30:56,340 : INFO : < 200 OK [1380]
2017-12-31 21:30:56,343 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'electrical_engineering'}}
2017-12-31 21:30:56,345 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:30:56,351 : INFO : < 200 OK [1384]
2017-12-31 21:30:56,355 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'math_and_logic'}}
2017-12-31 21:30:56,358 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:30:56,364 : INFO : < 200 OK [1376]
2017-12-31 21:30:56,368 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'mobile_and_web_development'}}
2017-12-31 21:30:56,371 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2017-12-31 21:30:56,377 : INFO : < 200 OK [1388]
2017-12-31 21:30:56,381 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'networking'}}
2017-12-31 21:30:56,385 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:30:56,392 : INFO : < 200 OK [1372]
2017-12-31 21:30:56,396 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'probability_and_statistics'}}
2017-12-31 21:30:56,400 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2017-12-31 21:30:56,408 : INFO : < 200 OK [1388]
2017-12-31 21:30:56,413 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'security'}}
2017-12-31 21:30:56,417 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:30:56,422 : INFO : < 200 OK [1370]
2017-12-31 21:30:56,426 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'machine_learning'}}
2017-12-31 21:30:56,429 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:30:56,435 : INFO : < 200 OK [1378]
2017-12-31 21:30:56,438 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'data_analysis'}}
2017-12-31 21:30:56,442 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:30:56,448 : INFO : < 200 OK [1389]
2017-12-31 21:30:56,452 : INFO : execute 'CREATE (_0:Category {_0})\nRETURN _0' {'_0': {'name': 'software_development'}}
2017-12-31 21:30:56,456 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:30:56,462 : INFO : < 200 OK [1382]

In [75]:
course_dict = {}
for i, row in data_clear.iterrows():
    course_dict[row.uid] = Node("Course", name=row.title, rating=row.rating, level=row.level, id=row.uid)
    graph.create(course_dict[row.uid])

2017-12-31 21:30:56,672 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 0, 'name': 'Bitcoin and Cryptocurrency Technologies'}}
2017-12-31 21:30:56,676 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2017-12-31 21:30:56,686 : INFO : < 200 OK [1455]
2017-12-31 21:30:56,690 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 284, 'name': 'Cryptography I'}}
2017-12-31 21:30:56,694 : INFO : > POST http://localhost:7474/db/data/cypher [112]
2017-12-31 21:30:56,702 : INFO : < 200 OK [1418]
2017-12-31 21:30:56,706 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 157, 'level': 'Intermediate', 'name': 'Google Cloud Platform Fundamentals: Core Infrastructure'}}
2017-12-31 21:30:56,710 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:30:56,717 : INFO : < 200 OK [1506]
2017-12-31 21:30:56,722 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 3, 'level': 'Beginner', 'name': 'G Suite Administrator Fundamentals'}}
2017-12-31 21:30:56,727 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:30:56,735 : INFO : < 200 OK [1465]
2017-12-31 21:30:56,741 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 4, 'name': 'Usable Security'}}
2017-12-31 21:30:56,746 : INFO : > POST http://localhost:7474/db/data/cypher [111]
2017-12-31 21:30:56,752 : INFO : < 200 OK [1431]
2017-12-31 21:30:56,756 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 422, 'level': 'Beginner', 'name': 'Internet Connection: How to Get Online?'}}
2017-12-31 21:30:56,761 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2017-12-31 21:30:56,767 : INFO : < 200 OK [1472]
2017-12-31 21:30:56,771 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 6, 'level': 'Beginner', 'name': 'Cybersecurity and Its Ten Domains'}}
2017-12-31 21:30:56,775 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:30:56,783 : INFO : < 200 OK [1436]
2017-12-31 21:30:56,787 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 7, 'level': 'Beginner', 'name': 'Introduction to Cyber Attacks'}}
2017-12-31 21:30:56,790 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:30:56,798 : INFO : < 200 OK [1460]
2017-12-31 21:30:56,802 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 246, 'level': 'Beginner', 'name': 'Introduction to TCP/IP'}}
2017-12-31 21:30:56,806 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:30:56,814 : INFO : < 200 OK [1427]
2017-12-31 21:30:56,818 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 158, 'level': 'Intermediate', 'name': 'Essential Cloud Infrastructure: Foundation'}}
2017-12-31 21:30:56,821 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2017-12-31 21:30:56,827 : INFO : < 200 OK [1479]
2017-12-31 21:30:56,834 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 10, 'name': 'Software Security '}}
2017-12-31 21:30:56,839 : INFO : > POST http://localhost:7474/db/data/cypher [115]
2017-12-31 21:30:56,845 : INFO : < 200 OK [1393]
2017-12-31 21:30:56,851 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 159, 'level': 'Intermediate', 'name': 'Essential Cloud Infrastructure: Core Services'}}
2017-12-31 21:30:56,854 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2017-12-31 21:30:56,860 : INFO : < 200 OK [1482]
2017-12-31 21:30:56,867 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 186, 'level': 'Intermediate', 'name': 'Hacking and Patching'}}
2017-12-31 21:30:56,871 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2017-12-31 21:30:56,879 : INFO : < 200 OK [1404]
2017-12-31 21:30:56,884 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 13, 'level': 'Beginner', 'name': 'Information Security: Context and Introduction'}}
2017-12-31 21:30:56,888 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2017-12-31 21:30:56,894 : INFO : < 200 OK [1478]
2017-12-31 21:30:56,901 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 160, 'level': 'Intermediate', 'name': 'Elastic Cloud Infrastructure: Scaling and Automation'}}
2017-12-31 21:30:56,905 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:30:56,912 : INFO : < 200 OK [1461]
2017-12-31 21:30:56,918 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 423, 'level': 'Beginner', 'name': 'Network Protocols and Architecture'}}
2017-12-31 21:30:56,921 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2017-12-31 21:30:56,927 : INFO : < 200 OK [1467]
2017-12-31 21:30:56,932 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 161, 'level': 'Intermediate', 'name': 'Elastic Cloud Infrastructure: Containers and Services'}}
2017-12-31 21:30:56,936 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:30:56,941 : INFO : < 200 OK [1462]
2017-12-31 21:30:56,946 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 17, 'level': 'Intermediate', 'name': 'Fundamentals of Network Communication'}}
2017-12-31 21:30:56,949 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2017-12-31 21:30:56,955 : INFO : < 200 OK [1473]
2017-12-31 21:30:56,959 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 462, 'level': 'Intermediate', 'name': 'Linux Server Management and Security'}}
2017-12-31 21:30:56,962 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2017-12-31 21:30:56,968 : INFO : < 200 OK [1445]
2017-12-31 21:30:56,973 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.9', 'id': 769, 'level': 'Intermediate', 'name': 'Cloud Computing Applications, Part 1: Cloud Systems and Infrastructure'}}
2017-12-31 21:30:56,976 : INFO : > POST http://localhost:7474/db/data/cypher [191]
2017-12-31 21:30:56,982 : INFO : < 200 OK [1493]
2017-12-31 21:30:56,986 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 773, 'name': 'Software Defined Networking'}}
2017-12-31 21:30:56,989 : INFO : > POST http://localhost:7474/db/data/cypher [110]
2017-12-31 21:30:56,995 : INFO : < 200 OK [1378]
2017-12-31 21:30:56,998 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 463, 'level': 'Beginner', 'name': 'Introduction to Cybersecurity for Business'}}
2017-12-31 21:30:57,002 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2017-12-31 21:30:57,008 : INFO : < 200 OK [1461]
2017-12-31 21:30:57,012 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 782, 'level': 'Intermediate', 'name': 'Serverless Data Analysis with Google BigQuery and Cloud Dataflow'}}
2017-12-31 21:30:57,015 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2017-12-31 21:30:57,021 : INFO : < 200 OK [1473]
2017-12-31 21:30:57,027 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.8', 'id': 195, 'level': 'Intermediate', 'name': 'Design and Analyze Secure Networked Systems'}}
2017-12-31 21:30:57,030 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2017-12-31 21:30:57,036 : INFO : < 200 OK [1466]
2017-12-31 21:30:57,040 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 424, 'level': 'Beginner', 'name': 'Home Networking Basics'}}
2017-12-31 21:30:57,043 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:30:57,049 : INFO : < 200 OK [1427]
2017-12-31 21:30:57,054 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 254, 'name': 'Interfacing with the Raspberry Pi'}}
2017-12-31 21:30:57,057 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2017-12-31 21:30:57,063 : INFO : < 200 OK [1423]

2017-12-31 21:30:57,067 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 26, 'name': 'Internet History, Technology, and Security'}}
2017-12-31 21:30:57,071 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:30:57,077 : INFO : < 200 OK [1431]
2017-12-31 21:30:57,082 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 425, 'level': 'Beginner', 'name': 'Introduction to Cisco Networking'}}
2017-12-31 21:30:57,086 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:30:57,092 : INFO : < 200 OK [1451]
2017-12-31 21:30:57,097 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 28, 'name': 'Cryptography'}}
2017-12-31 21:30:57,100 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2017-12-31 21:30:57,106 : INFO : < 200 OK [1401]
2017-12-31 21:30:57,110 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 426, 'level': 'Beginner', 'name': 'Data Communications and Network Services'}}
2017-12-31 21:30:57,113 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2017-12-31 21:30:57,119 : INFO : < 200 OK [1459]
2017-12-31 21:30:57,124 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 30, 'name': 'Cloud Computing Applications, Part 2: Big Data and Applications in the Cloud'}}
2017-12-31 21:30:57,127 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:30:57,132 : INFO : < 200 OK [1465]
2017-12-31 21:30:57,136 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 322, 'level': 'Intermediate', 'name': 'Cryptography and Information Theory'}}
2017-12-31 21:30:57,139 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2017-12-31 21:30:57,145 : INFO : < 200 OK [1458]
2017-12-31 21:30:57,149 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 32, 'name': 'Big Data, Cloud Computing, & CDN Emerging Technologies'}}
2017-12-31 21:30:57,152 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2017-12-31 21:30:57,158 : INFO : < 200 OK [1443]
2017-12-31 21:30:57,162 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 162, 'level': 'Intermediate', 'name': 'Getting Started with Google Kubernetes Engine'}}
2017-12-31 21:30:57,165 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2017-12-31 21:30:57,171 : INFO : < 200 OK [1468]
2017-12-31 21:30:57,175 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 464, 'level': 'Beginner', 'name': 'Enterprise System Management and Security '}}
2017-12-31 21:30:57,178 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2017-12-31 21:30:57,183 : INFO : < 200 OK [1461]
2017-12-31 21:30:57,188 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 35, 'name': 'Cloud Networking'}}
2017-12-31 21:30:57,191 : INFO : > POST http://localhost:7474/db/data/cypher [113]
2017-12-31 21:30:57,196 : INFO : < 200 OK [1405]
2017-12-31 21:30:57,200 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 163, 'level': 'Intermediate', 'name': 'Reliable Cloud Infrastructure: Design and Process'}}
2017-12-31 21:30:57,203 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2017-12-31 21:30:57,209 : INFO : < 200 OK [1472]
2017-12-31 21:30:57,213 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 329, 'level': 'Beginner', 'name': 'Classical Cryptosystems and Core Concepts'}}
2017-12-31 21:30:57,216 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:30:57,222 : INFO : < 200 OK [1460]
2017-12-31 21:30:57,227 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 38, 'name': 'Hardware Security'}}
2017-12-31 21:30:57,231 : INFO : > POST http://localhost:7474/db/data/cypher [114]
2017-12-31 21:30:57,236 : INFO : < 200 OK [1406]
2017-12-31 21:30:57,241 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 465, 'level': 'Beginner', 'name': 'Cyber Threats and Attack Vectors'}}
2017-12-31 21:30:57,244 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:30:57,250 : INFO : < 200 OK [1451]
2017-12-31 21:30:57,255 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 262, 'name': 'Wireless Communication Emerging Technologies'}}
2017-12-31 21:30:57,259 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:30:57,267 : INFO : < 200 OK [1434]
2017-12-31 21:30:57,271 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 41, 'name': 'TCP/IP and Advanced Topics'}}
2017-12-31 21:30:57,275 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2017-12-31 21:30:57,283 : INFO : < 200 OK [1415]
2017-12-31 21:30:57,288 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 817, 'level': 'Intermediate', 'name': 'Architecting Smart IoT Devices'}}
2017-12-31 21:30:57,292 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2017-12-31 21:30:57,299 : INFO : < 200 OK [1453]
2017-12-31 21:30:57,303 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 43, 'level': 'Intermediate', 'name': 'Cyber Attack Countermeasures'}}
2017-12-31 21:30:57,307 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:30:57,313 : INFO : < 200 OK [1450]
2017-12-31 21:30:57,317 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 44, 'name': 'International Cyber Conflicts'}}
2017-12-31 21:30:57,321 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2017-12-31 21:30:57,327 : INFO : < 200 OK [1418]
2017-12-31 21:30:57,332 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 822, 'level': 'Intermediate', 'name': 'Basic Cryptography and Programming with Crypto API'}}
2017-12-31 21:30:57,335 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2017-12-31 21:30:57,341 : INFO : < 200 OK [1448]
2017-12-31 21:30:57,345 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 140, 'level': 'Beginner', 'name': 'Mathematical Foundations for Cryptography'}}
2017-12-31 21:30:57,348 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:30:57,354 : INFO : < 200 OK [1460]
2017-12-31 21:30:57,358 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 466, 'level': 'Beginner', 'name': 'Windows Server Management and Security'}}
2017-12-31 21:30:57,361 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2017-12-31 21:30:57,368 : INFO : < 200 OK [1432]
2017-12-31 21:30:57,372 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 48, 'level': 'Intermediate', 'name': 'Cybersecurity and the Internet of Things'}}
2017-12-31 21:30:57,376 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2017-12-31 21:30:57,382 : INFO : < 200 OK [1462]
2017-12-31 21:30:57,387 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 49, 'level': 'Intermediate', 'name': 'Real-Time Cyber Threat Detection and Mitigation'}}
2017-12-31 21:30:57,391 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2017-12-31 21:30:57,398 : INFO : < 200 OK [1444]
2017-12-31 21:30:57,404 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 50, 'level': 'Intermediate', 'name': 'Enterprise and Infrastructure Security'}}
2017-12-31 21:30:57,407 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:30:57,414 : INFO : < 200 OK [1460]
2017-12-31 21:30:57,418 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 467, 'level': 'Beginner', 'name': 'Detecting and Mitigating Cyber Threats and Attacks'}}
2017-12-31 21:30:57,421 : INFO : > POST http://localhost:7474/db/data/cypher [167]
2017-12-31 21:30:57,428 : INFO : < 200 OK [1469]

2017-12-31 21:30:57,432 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 52, 'name': 'Internet of Things: Communication Technologies'}}
2017-12-31 21:30:57,435 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2017-12-31 21:30:57,441 : INFO : < 200 OK [1435]
2017-12-31 21:30:57,445 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 829, 'level': 'Intermediate', 'name': 'Google Cloud Platform Fundamentals for AWS Professionals'}}
2017-12-31 21:30:57,448 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:30:57,454 : INFO : < 200 OK [1479]
2017-12-31 21:30:57,458 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.7', 'id': 833, 'level': 'Beginner', 'name': 'Introduction to Architecting Smart IoT Devices'}}
2017-12-31 21:30:57,462 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2017-12-31 21:30:57,467 : INFO : < 200 OK [1465]
2017-12-31 21:30:57,471 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 55, 'name': 'Peer-to-Peer Protocols and Local Area Networks'}}
2017-12-31 21:30:57,475 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:30:57,481 : INFO : < 200 OK [1410]
2017-12-31 21:30:57,485 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 56, 'name': 'Networks: Friends, Money, and Bytes'}}
2017-12-31 21:30:57,488 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:30:57,494 : INFO : < 200 OK [1424]
2017-12-31 21:30:57,498 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 340, 'level': 'Intermediate', 'name': 'Symmetric Cryptography'}}
2017-12-31 21:30:57,502 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:30:57,507 : INFO : < 200 OK [1420]
2017-12-31 21:30:57,511 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 222, 'level': 'Intermediate', 'name': 'Secure Networked System with Firewall and IDS'}}
2017-12-31 21:30:57,514 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2017-12-31 21:30:57,520 : INFO : < 200 OK [1468]
2017-12-31 21:30:57,524 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 59, 'level': 'Intermediate', 'name': 'Packet Switching Networks and Algorithms'}}
2017-12-31 21:30:57,528 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:30:57,534 : INFO : < 200 OK [1437]
2017-12-31 21:30:57,538 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 60, 'level': 'Beginner', 'name': 'Privacy, Reputation, and Identity in a Digital Age Teach-Out'}}
2017-12-31 21:30:57,541 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:30:57,547 : INFO : < 200 OK [1478]
2017-12-31 21:30:57,551 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 344, 'level': 'Intermediate', 'name': 'Asymmetric Cryptography and Key Management'}}
2017-12-31 21:30:57,555 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:30:57,561 : INFO : < 200 OK [1440]
2017-12-31 21:30:57,565 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 62, 'level': 'Intermediate', 'name': 'Web Connectivity and Security in Embedded Systems'}}
2017-12-31 21:30:57,568 : INFO : > POST http://localhost:7474/db/data/cypher [169]
2017-12-31 21:30:57,574 : INFO : < 200 OK [1471]
2017-12-31 21:30:57,577 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 468, 'level': 'Beginner', 'name': 'Proactive Computer Security'}}
2017-12-31 21:30:57,581 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:30:57,586 : INFO : < 200 OK [1446]
2017-12-31 21:30:57,590 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 64, 'name': 'Internet Emerging Technologies'}}
2017-12-31 21:30:57,594 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:30:57,599 : INFO : < 200 OK [1419]
2017-12-31 21:30:57,603 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 346, 'level': 'Intermediate', 'name': 'Cryptographic Hash and Integrity Protection'}}
2017-12-31 21:30:57,607 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:30:57,612 : INFO : < 200 OK [1441]
2017-12-31 21:30:57,616 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 66, 'level': 'Beginner', 'name': 'Cybersecurity and Mobility'}}
2017-12-31 21:30:57,619 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:30:57,626 : INFO : < 200 OK [1444]
2017-12-31 21:30:57,629 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 67, 'level': 'Beginner', 'name': 'Networks Illustrated: Principles without Calculus'}}
2017-12-31 21:30:57,632 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:30:57,638 : INFO : < 200 OK [1467]
2017-12-31 21:30:57,644 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 469, 'level': 'Intermediate', 'name': 'Planning, Auditing and Maintaining Enterprise Systems'}}
2017-12-31 21:30:57,647 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2017-12-31 21:30:57,653 : INFO : < 200 OK [1451]
2017-12-31 21:30:57,656 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 69, 'level': 'Beginner', 'name': "Homeland Security & Cybersecurity Connection - It's Not About the Terrorists"}}
2017-12-31 21:30:57,659 : INFO : > POST http://localhost:7474/db/data/cypher [192]
2017-12-31 21:30:57,665 : INFO : < 200 OK [1494]
2017-12-31 21:30:57,669 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 70, 'name': 'Securing Digital Democracy'}}
2017-12-31 21:30:57,672 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2017-12-31 21:30:57,677 : INFO : < 200 OK [1415]
2017-12-31 21:30:57,681 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 855, 'level': 'Advanced', 'name': 'System Validation (4): Modelling Software, Protocols, and other behaviour'}}
2017-12-31 21:30:57,685 : INFO : > POST http://localhost:7474/db/data/cypher [190]
2017-12-31 21:30:57,693 : INFO : < 200 OK [1492]
2017-12-31 21:30:57,698 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 72, 'level': 'Beginner', 'name': 'Cybersecurity Policy for Water and Electricity Infrastructures'}}
2017-12-31 21:30:57,702 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:30:57,709 : INFO : < 200 OK [1480]
2017-12-31 21:30:57,715 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 412, 'name': 'Networking and Security in iOS Applications'}}
2017-12-31 21:30:57,719 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:30:57,725 : INFO : < 200 OK [1433]
2017-12-31 21:30:57,730 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 74, 'level': 'Beginner', 'name': 'Homeland Security and Cybersecurity Future'}}
2017-12-31 21:30:57,734 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:30:57,739 : INFO : < 200 OK [1460]
2017-12-31 21:30:57,744 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 75, 'level': 'Beginner', 'name': 'Cybersecurity and the X-Factor'}}
2017-12-31 21:30:57,747 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2017-12-31 21:30:57,753 : INFO : < 200 OK [1448]
2017-12-31 21:30:57,757 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 274, 'name': 'Emerging Technologies Capstone '}}
2017-12-31 21:30:57,761 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2017-12-31 21:30:57,767 : INFO : < 200 OK [1421]
2017-12-31 21:30:57,771 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 77, 'level': 'Beginner', 'name': 'Cybersecurity Policy for Aviation and Internet Infrastructures'}}
2017-12-31 21:30:57,775 : INFO : > POST http://localhost:7474/db/data/cypher [178]

2017-12-31 21:30:57,781 : INFO : < 200 OK [1480]
2017-12-31 21:30:57,785 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 867, 'level': 'Beginner', 'name': 'Develop and Deploy Windows Applications on Google Cloud Platform'}}
2017-12-31 21:30:57,788 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:30:57,794 : INFO : < 200 OK [1483]
2017-12-31 21:30:57,799 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 79, 'name': 'Cloud Computing Project'}}
2017-12-31 21:30:57,802 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2017-12-31 21:30:57,808 : INFO : < 200 OK [1412]
2017-12-31 21:30:57,812 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 874, 'level': 'Beginner', 'name': 'The Business of Cybersecurity Capstone'}}
2017-12-31 21:30:57,815 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2017-12-31 21:30:57,821 : INFO : < 200 OK [1457]
2017-12-31 21:30:57,825 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 81, 'level': 'Intermediate', 'name': 'Cybersecurity Capstone Project'}}
2017-12-31 21:30:57,829 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:30:57,835 : INFO : < 200 OK [1452]
2017-12-31 21:30:57,839 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 82, 'level': 'Beginner', 'name': 'The Internet and You'}}
2017-12-31 21:30:57,843 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:30:57,848 : INFO : < 200 OK [1438]
2017-12-31 21:30:57,853 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 471, 'level': 'Intermediate', 'name': 'Neural Networks and Deep Learning'}}
2017-12-31 21:30:57,856 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:30:57,862 : INFO : < 200 OK [1456]
2017-12-31 21:30:57,865 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 472, 'level': 'Intermediate', 'name': 'Convolutional Neural Networks'}}
2017-12-31 21:30:57,869 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:30:57,875 : INFO : < 200 OK [1452]
2017-12-31 21:30:57,879 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 473, 'level': 'Beginner', 'name': 'Improving Deep Neural Networks: Hyperparameter tuning, Regularization and Optimization'}}
2017-12-31 21:30:57,882 : INFO : > POST http://localhost:7474/db/data/cypher [203]
2017-12-31 21:30:57,888 : INFO : < 200 OK [1505]
2017-12-31 21:30:57,892 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 699, 'level': 'Intermediate', 'name': 'Algorithms, Part I'}}
2017-12-31 21:30:57,896 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:30:57,902 : INFO : < 200 OK [1441]
2017-12-31 21:30:57,907 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 701, 'level': 'Intermediate', 'name': 'Algorithmic Toolbox'}}
2017-12-31 21:30:57,911 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2017-12-31 21:30:57,917 : INFO : < 200 OK [1442]
2017-12-31 21:30:57,921 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 476, 'level': 'Intermediate', 'name': 'Sequence Models'}}
2017-12-31 21:30:57,924 : INFO : > POST http://localhost:7474/db/data/cypher [121]
2017-12-31 21:30:57,930 : INFO : < 200 OK [1413]
2017-12-31 21:30:57,934 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 288, 'level': 'Intermediate', 'name': 'Divide and Conquer, Sorting and Searching, and Randomized Algorithms'}}
2017-12-31 21:30:57,937 : INFO : > POST http://localhost:7474/db/data/cypher [189]
2017-12-31 21:30:57,943 : INFO : < 200 OK [1491]
2017-12-31 21:30:57,947 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 711, 'name': 'An Introduction to Interactive Programming in Python (Part 1)'}}
2017-12-31 21:30:57,950 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2017-12-31 21:30:57,955 : INFO : < 200 OK [1451]
2017-12-31 21:30:57,960 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 714, 'level': 'Intermediate', 'name': 'Algorithms, Part II'}}
2017-12-31 21:30:57,964 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2017-12-31 21:30:57,969 : INFO : < 200 OK [1442]
2017-12-31 21:30:57,973 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 92, 'level': 'Intermediate', 'name': 'Data Structures'}}
2017-12-31 21:30:57,976 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2017-12-31 21:30:57,982 : INFO : < 200 OK [1437]
2017-12-31 21:30:57,986 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 93, 'name': 'Build a Modern Computer from First Principles: From Nand to Tetris (Project-Centered Course)'}}
2017-12-31 21:30:57,989 : INFO : > POST http://localhost:7474/db/data/cypher [189]
2017-12-31 21:30:57,995 : INFO : < 200 OK [1481]
2017-12-31 21:30:57,999 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 723, 'level': 'Beginner', 'name': 'Programming Fundamentals'}}
2017-12-31 21:30:58,002 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:30:58,007 : INFO : < 200 OK [1443]
2017-12-31 21:30:58,011 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 95, 'level': 'Beginner', 'name': 'Cloud Computing Concepts, Part 1'}}
2017-12-31 21:30:58,014 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:30:58,020 : INFO : < 200 OK [1450]
2017-12-31 21:30:58,024 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 239, 'name': 'Fundamentals of Digital Image and Video Processing'}}
2017-12-31 21:30:58,027 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:30:58,034 : INFO : < 200 OK [1440]
2017-12-31 21:30:58,038 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 484, 'level': 'Advanced', 'name': 'Probabilistic Graphical Models 1: Representation'}}
2017-12-31 21:30:58,041 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:30:58,046 : INFO : < 200 OK [1467]
2017-12-31 21:30:58,051 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 294, 'level': 'Beginner', 'name': 'What is a Proof?'}}
2017-12-31 21:30:58,054 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2017-12-31 21:30:58,059 : INFO : < 200 OK [1435]
2017-12-31 21:30:58,063 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 99, 'name': 'Computational Investing, Part I'}}
2017-12-31 21:30:58,067 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:30:58,072 : INFO : < 200 OK [1420]
2017-12-31 21:30:58,076 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 100, 'name': 'Big Data Analysis with Scala and Spark'}}
2017-12-31 21:30:58,080 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:30:58,090 : INFO : < 200 OK [1428]
2017-12-31 21:30:58,095 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 243, 'level': 'Beginner', 'name': 'Building Arduino robots and devices'}}
2017-12-31 21:30:58,099 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2017-12-31 21:30:58,107 : INFO : < 200 OK [1454]
2017-12-31 21:30:58,113 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 297, 'level': 'Intermediate', 'name': 'Graph Search, Shortest Paths, and Data Structures'}}
2017-12-31 21:30:58,116 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2017-12-31 21:30:58,122 : INFO : < 200 OK [1472]
2017-12-31 21:30:58,127 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 740, 'level': 'Intermediate', 'name': 'Algorithms on Graphs'}}
2017-12-31 21:30:58,131 : INFO : > POST http://localhost:7474/db/data/cypher [141]

2017-12-31 21:30:58,137 : INFO : < 200 OK [1443]
2017-12-31 21:30:58,141 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 742, 'level': 'Beginner', 'name': 'Writing, Running, and Fixing Code in C'}}
2017-12-31 21:30:58,144 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2017-12-31 21:30:58,150 : INFO : < 200 OK [1432]
2017-12-31 21:30:58,154 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 299, 'level': 'Intermediate', 'name': 'Greedy Algorithms, Minimum Spanning Trees, and Dynamic Programming'}}
2017-12-31 21:30:58,158 : INFO : > POST http://localhost:7474/db/data/cypher [187]
2017-12-31 21:30:58,163 : INFO : < 200 OK [1489]
2017-12-31 21:30:58,168 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.7', 'id': 301, 'level': 'Intermediate', 'name': 'Discrete Mathematics'}}
2017-12-31 21:30:58,171 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:30:58,177 : INFO : < 200 OK [1443]
2017-12-31 21:30:58,183 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 107, 'level': 'Beginner', 'name': 'Finding Hidden Messages in DNA (Bioinformatics I)'}}
2017-12-31 21:30:58,186 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2017-12-31 21:30:58,193 : INFO : < 200 OK [1468]
2017-12-31 21:30:58,198 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 302, 'level': 'Intermediate', 'name': 'Discrete Optimization'}}
2017-12-31 21:30:58,201 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:30:58,208 : INFO : < 200 OK [1444]
2017-12-31 21:30:58,212 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 303, 'level': 'Beginner', 'name': 'Introduction to Graph Theory'}}
2017-12-31 21:30:58,216 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:30:58,222 : INFO : < 200 OK [1447]
2017-12-31 21:30:58,226 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 307, 'level': 'Beginner', 'name': 'Combinatorics and Probability'}}
2017-12-31 21:30:58,230 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2017-12-31 21:30:58,237 : INFO : < 200 OK [1462]
2017-12-31 21:30:58,241 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 753, 'level': 'Intermediate', 'name': 'Algorithmic Thinking (Part 1)'}}
2017-12-31 21:30:58,245 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:30:58,251 : INFO : < 200 OK [1452]
2017-12-31 21:30:58,256 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 112, 'level': 'Beginner', 'name': 'Excel/VBA for Creative Problem Solving, Part 1'}}
2017-12-31 21:30:58,259 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:30:58,266 : INFO : < 200 OK [1454]
2017-12-31 21:30:58,269 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 755, 'level': 'Advanced', 'name': 'Advanced Algorithms and Complexity'}}
2017-12-31 21:30:58,273 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2017-12-31 21:30:58,278 : INFO : < 200 OK [1467]
2017-12-31 21:30:58,283 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 114, 'level': 'Intermediate', 'name': 'Data Structures and Performance'}}
2017-12-31 21:30:58,286 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2017-12-31 21:30:58,292 : INFO : < 200 OK [1468]
2017-12-31 21:30:58,296 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 115, 'level': 'Intermediate', 'name': 'Algorithms on Strings'}}
2017-12-31 21:30:58,299 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:30:58,305 : INFO : < 200 OK [1458]
2017-12-31 21:30:58,308 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 308, 'level': 'Intermediate', 'name': 'Shortest Paths Revisited, NP-Complete Problems and What To Do About Them'}}
2017-12-31 21:30:58,312 : INFO : > POST http://localhost:7474/db/data/cypher [193]
2017-12-31 21:30:58,317 : INFO : < 200 OK [1509]
2017-12-31 21:30:58,321 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 586, 'name': 'Introduction to Genomic Technologies'}}
2017-12-31 21:30:58,324 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:30:58,329 : INFO : < 200 OK [1440]
2017-12-31 21:30:58,334 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 768, 'level': 'Intermediate', 'name': 'Interactive Computer Graphics'}}
2017-12-31 21:30:58,337 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:30:58,343 : INFO : < 200 OK [1466]
2017-12-31 21:30:58,346 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 772, 'level': 'Beginner', 'name': 'An Introduction to Interactive Programming in Python (Part 2)'}}
2017-12-31 21:30:58,349 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:30:58,355 : INFO : < 200 OK [1494]
2017-12-31 21:30:58,359 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 496, 'level': 'Intermediate', 'name': 'Practical Reinforcement Learning'}}
2017-12-31 21:30:58,362 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:30:58,368 : INFO : < 200 OK [1444]
2017-12-31 21:30:58,372 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 312, 'level': 'Beginner', 'name': 'Number Theory and Cryptography'}}
2017-12-31 21:30:58,375 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2017-12-31 21:30:58,382 : INFO : < 200 OK [1463]
2017-12-31 21:30:58,387 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 122, 'level': 'Advanced', 'name': 'Big Data, Genes, and Medicine'}}
2017-12-31 21:30:58,391 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2017-12-31 21:30:58,397 : INFO : < 200 OK [1462]
2017-12-31 21:30:58,403 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 123, 'level': 'Advanced', 'name': 'Natural Language Processing'}}
2017-12-31 21:30:58,407 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2017-12-31 21:30:58,414 : INFO : < 200 OK [1435]
2017-12-31 21:30:58,418 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 499, 'level': 'Advanced', 'name': 'Probabilistic Graphical Models 2: Inference'}}
2017-12-31 21:30:58,421 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2017-12-31 21:30:58,427 : INFO : < 200 OK [1476]
2017-12-31 21:30:58,431 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 502, 'level': 'Advanced', 'name': 'Probabilistic Graphical Models 3: Learning'}}
2017-12-31 21:30:58,435 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2017-12-31 21:30:58,441 : INFO : < 200 OK [1475]
2017-12-31 21:30:58,444 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 789, 'level': 'Intermediate', 'name': 'Principles of Computing (Part 1)'}}
2017-12-31 21:30:58,448 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:30:58,453 : INFO : < 200 OK [1469]
2017-12-31 21:30:58,457 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 128, 'level': 'Advanced', 'name': 'Analysis of Algorithms'}}
2017-12-31 21:30:58,461 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2017-12-31 21:30:58,466 : INFO : < 200 OK [1430]
2017-12-31 21:30:58,470 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 129, 'level': 'Intermediate', 'name': 'VLSI CAD Part I: Logic'}}
2017-12-31 21:30:58,473 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2017-12-31 21:30:58,479 : INFO : < 200 OK [1459]
2017-12-31 21:30:58,483 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 791, 'level': 'Intermediate', 'name': 'Advanced Data Structures in Java'}}
2017-12-31 21:30:58,487 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:30:58,493 : INFO : < 200 OK [1469]

2017-12-31 21:30:58,497 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 131, 'name': 'Cloud Computing Concepts: Part 2'}}
2017-12-31 21:30:58,501 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:30:58,506 : INFO : < 200 OK [1436]
2017-12-31 21:30:58,510 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 132, 'level': 'Advanced', 'name': 'Deep Learning in Computer Vision'}}
2017-12-31 21:30:58,513 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:30:58,519 : INFO : < 200 OK [1440]
2017-12-31 21:30:58,523 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 324, 'level': 'Beginner', 'name': 'Delivery Problem'}}
2017-12-31 21:30:58,527 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2017-12-31 21:30:58,533 : INFO : < 200 OK [1449]
2017-12-31 21:30:58,538 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 640, 'name': 'Algorithms for DNA Sequencing'}}
2017-12-31 21:30:58,541 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:30:58,547 : INFO : < 200 OK [1433]
2017-12-31 21:30:58,552 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 811, 'level': 'Intermediate', 'name': 'Algorithmic Thinking (Part 2)'}}
2017-12-31 21:30:58,556 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:30:58,562 : INFO : < 200 OK [1466]
2017-12-31 21:30:58,566 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 136, 'level': 'Advanced', 'name': 'Kinematics: Describing the Motions of Spacecraft'}}
2017-12-31 21:30:58,569 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:30:58,575 : INFO : < 200 OK [1481]
2017-12-31 21:30:58,578 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 137, 'name': 'Approximation Algorithms Part I'}}
2017-12-31 21:30:58,581 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2017-12-31 21:30:58,587 : INFO : < 200 OK [1435]
2017-12-31 21:30:58,591 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 815, 'name': 'Principles of Computing (Part 2)'}}
2017-12-31 21:30:58,594 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:30:58,599 : INFO : < 200 OK [1436]
2017-12-31 21:30:58,604 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 139, 'level': 'Advanced', 'name': 'Kinetics: Studying Spacecraft Motion'}}
2017-12-31 21:30:58,607 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:30:58,615 : INFO : < 200 OK [1469]
2017-12-31 21:30:58,619 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 141, 'level': 'Beginner', 'name': 'Genome Sequencing (Bioinformatics II)'}}
2017-12-31 21:30:58,622 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:30:58,627 : INFO : < 200 OK [1470]
2017-12-31 21:30:58,632 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 142, 'level': 'Advanced', 'name': 'Control of Nonlinear Spacecraft Attitude Motion'}}
2017-12-31 21:30:58,636 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2017-12-31 21:30:58,642 : INFO : < 200 OK [1480]
2017-12-31 21:30:58,646 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 143, 'level': 'Beginner', 'name': 'Genomic Data Science and Clustering (Bioinformatics V)'}}
2017-12-31 21:30:58,650 : INFO : > POST http://localhost:7474/db/data/cypher [171]
2017-12-31 21:30:58,657 : INFO : < 200 OK [1487]
2017-12-31 21:30:58,661 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 144, 'level': 'Intermediate', 'name': 'VLSI CAD Part II: Layout'}}
2017-12-31 21:30:58,666 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:30:58,672 : INFO : < 200 OK [1461]
2017-12-31 21:30:58,676 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 145, 'level': 'Advanced', 'name': 'Addressing Large Hadron Collider Challenges by Machine Learning'}}
2017-12-31 21:30:58,680 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:30:58,686 : INFO : < 200 OK [1471]
2017-12-31 21:30:58,690 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 146, 'level': 'Beginner', 'name': 'Molecular Evolution (Bioinformatics IV)'}}
2017-12-31 21:30:58,693 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2017-12-31 21:30:58,699 : INFO : < 200 OK [1472]
2017-12-31 21:30:58,703 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 147, 'level': 'Beginner', 'name': 'Comparing Genes, Proteins, and Genomes (Bioinformatics III)'}}
2017-12-31 21:30:58,707 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:30:58,713 : INFO : < 200 OK [1492]
2017-12-31 21:30:58,718 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 148, 'level': 'Beginner', 'name': 'Finding Mutations in DNA and Proteins (Bioinformatics VI)'}}
2017-12-31 21:30:58,721 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:30:58,727 : INFO : < 200 OK [1490]
2017-12-31 21:30:58,731 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 150, 'name': 'Global Warming II: Create Your Own Models in Python'}}
2017-12-31 21:30:58,735 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:30:58,741 : INFO : < 200 OK [1455]
2017-12-31 21:30:58,744 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 151, 'name': 'Approximation Algorithms Part II'}}
2017-12-31 21:30:58,748 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:30:58,754 : INFO : < 200 OK [1436]
2017-12-31 21:30:58,758 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 152, 'level': 'Advanced', 'name': 'Genome Assembly Programming Challenge'}}
2017-12-31 21:30:58,762 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:30:58,768 : INFO : < 200 OK [1470]
2017-12-31 21:30:58,772 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 871, 'level': 'Intermediate', 'name': 'The Fundamentals of Computing Capstone Exam'}}
2017-12-31 21:30:58,775 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2017-12-31 21:30:58,781 : INFO : < 200 OK [1480]
2017-12-31 21:30:58,786 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 154, 'level': 'Beginner', 'name': 'Bioinformatics Capstone: Big Data in Biology'}}
2017-12-31 21:30:58,789 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2017-12-31 21:30:58,795 : INFO : < 200 OK [1477]
2017-12-31 21:30:58,798 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 279, 'level': 'Intermediate', 'name': 'Digital Signal Processing'}}
2017-12-31 21:30:58,801 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2017-12-31 21:30:58,807 : INFO : < 200 OK [1462]
2017-12-31 21:30:58,811 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 696, 'level': 'Intermediate', 'name': 'Introduction to Natural Language Processing'}}
2017-12-31 21:30:58,814 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2017-12-31 21:30:58,820 : INFO : < 200 OK [1480]
2017-12-31 21:30:58,824 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 736, 'level': 'Intermediate', 'name': 'Introduction to MongoDB'}}
2017-12-31 21:30:58,827 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:30:58,833 : INFO : < 200 OK [1460]
2017-12-31 21:30:58,837 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 641, 'level': 'Intermediate', 'name': 'Applying Machine Learning to your Data with GCP'}}
2017-12-31 21:30:58,840 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:30:58,846 : INFO : < 200 OK [1459]

2017-12-31 21:30:58,850 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 667, 'level': 'Beginner', 'name': 'Creating New BigQuery Datasets and Visualizing Insights'}}
2017-12-31 21:30:58,854 : INFO : > POST http://localhost:7474/db/data/cypher [172]
2017-12-31 21:30:58,859 : INFO : < 200 OK [1488]
2017-12-31 21:30:58,864 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 671, 'level': 'Beginner', 'name': 'Achieving Advanced Insights with BigQuery'}}
2017-12-31 21:30:58,867 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:30:58,873 : INFO : < 200 OK [1474]
2017-12-31 21:30:58,878 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 169, 'name': 'Fundamentals of Graphic Design'}}
2017-12-31 21:30:58,881 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:30:58,888 : INFO : < 200 OK [1434]
2017-12-31 21:30:58,892 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 535, 'level': 'Intermediate', 'name': 'Applied Plotting, Charting & Data Representation in Python'}}
2017-12-31 21:30:58,895 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2017-12-31 21:30:58,901 : INFO : < 200 OK [1495]
2017-12-31 21:30:58,906 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 362, 'level': 'Intermediate', 'name': 'Introduction to Structured Query Language (SQL)'}}
2017-12-31 21:30:58,909 : INFO : > POST http://localhost:7474/db/data/cypher [168]
2017-12-31 21:30:58,915 : INFO : < 200 OK [1484]
2017-12-31 21:30:58,919 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 364, 'name': 'HTML, CSS, and Javascript for Web Developers'}}
2017-12-31 21:30:58,922 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:30:58,928 : INFO : < 200 OK [1448]
2017-12-31 21:30:58,933 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 238, 'level': 'Advanced', 'name': 'Computer Architecture'}}
2017-12-31 21:30:58,937 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:30:58,943 : INFO : < 200 OK [1454]
2017-12-31 21:30:58,947 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 174, 'level': 'Beginner', 'name': 'Introduction to User Experience Design '}}
2017-12-31 21:30:58,951 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2017-12-31 21:30:58,956 : INFO : < 200 OK [1472]
2017-12-31 21:30:58,961 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 369, 'level': 'Intermediate', 'name': 'Building Web Applications in PHP'}}
2017-12-31 21:30:58,964 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:30:58,971 : INFO : < 200 OK [1469]
2017-12-31 21:30:58,975 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 726, 'name': 'Introduction to the Internet of Things and Embedded Systems'}}
2017-12-31 21:30:58,978 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2017-12-31 21:30:58,984 : INFO : < 200 OK [1463]
2017-12-31 21:30:58,988 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 177, 'level': 'Beginner', 'name': 'VR & 360 Video Production'}}
2017-12-31 21:30:58,991 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:30:58,997 : INFO : < 200 OK [1458]
2017-12-31 21:30:59,001 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 178, 'name': 'Gamification'}}
2017-12-31 21:30:59,004 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:30:59,009 : INFO : < 200 OK [1391]
2017-12-31 21:30:59,013 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 241, 'level': 'Intermediate', 'name': 'Introduction to FPGA Design for Embedded Systems'}}
2017-12-31 21:30:59,016 : INFO : > POST http://localhost:7474/db/data/cypher [169]
2017-12-31 21:30:59,021 : INFO : < 200 OK [1485]
2017-12-31 21:30:59,026 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 374, 'level': 'Intermediate', 'name': 'JavaScript, jQuery, and JSON'}}
2017-12-31 21:30:59,029 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:30:59,035 : INFO : < 200 OK [1465]
2017-12-31 21:30:59,041 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 734, 'name': 'Getting Started: Agile Meets Design Thinking'}}
2017-12-31 21:30:59,046 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:30:59,053 : INFO : < 200 OK [1448]
2017-12-31 21:30:59,056 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 182, 'name': 'Human-Centered Design: an Introduction'}}
2017-12-31 21:30:59,059 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:30:59,066 : INFO : < 200 OK [1442]
2017-12-31 21:30:59,071 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 743, 'level': 'Beginner', 'name': 'Introduction to UI Design'}}
2017-12-31 21:30:59,074 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:30:59,082 : INFO : < 200 OK [1458]
2017-12-31 21:30:59,088 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 184, 'name': 'Introduction to Typography'}}
2017-12-31 21:30:59,093 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2017-12-31 21:30:59,100 : INFO : < 200 OK [1430]
2017-12-31 21:30:59,105 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 185, 'level': 'Intermediate', 'name': 'Autodesk Fusion 360 Integrated CAD/CAM/CAE'}}
2017-12-31 21:30:59,109 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:30:59,116 : INFO : < 200 OK [1454]
2017-12-31 21:30:59,121 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 756, 'name': 'Introduction to Software Product Management'}}
2017-12-31 21:30:59,125 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:30:59,131 : INFO : < 200 OK [1447]
2017-12-31 21:30:59,136 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 251, 'level': 'Intermediate', 'name': 'Digital Systems: From Logic Gates to Processors'}}
2017-12-31 21:30:59,140 : INFO : > POST http://localhost:7474/db/data/cypher [168]
2017-12-31 21:30:59,146 : INFO : < 200 OK [1484]
2017-12-31 21:30:59,151 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 382, 'level': 'Intermediate', 'name': 'Building Database Applications in PHP'}}
2017-12-31 21:30:59,155 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:30:59,162 : INFO : < 200 OK [1474]
2017-12-31 21:30:59,167 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 190, 'level': 'Beginner', 'name': 'Introduction to Imagemaking'}}
2017-12-31 21:30:59,171 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:30:59,178 : INFO : < 200 OK [1460]
2017-12-31 21:30:59,183 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 384, 'level': 'Beginner', 'name': 'Introduction to Virtual Reality'}}
2017-12-31 21:30:59,186 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:30:59,192 : INFO : < 200 OK [1464]
2017-12-31 21:30:59,197 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 776, 'level': 'Intermediate', 'name': 'Development of Real-Time Systems'}}
2017-12-31 21:30:59,200 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:30:59,206 : INFO : < 200 OK [1469]
2017-12-31 21:30:59,210 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 193, 'level': 'Beginner', 'name': 'Introduction to Game Design'}}
2017-12-31 21:30:59,214 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:30:59,219 : INFO : < 200 OK [1460]

2017-12-31 21:30:59,224 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 781, 'name': 'Software Processes and Agile Practices'}}
2017-12-31 21:30:59,227 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:30:59,233 : INFO : < 200 OK [1442]
2017-12-31 21:30:59,237 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 609, 'name': 'Data Warehouse Concepts, Design, and Data Integration'}}
2017-12-31 21:30:59,241 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2017-12-31 21:30:59,247 : INFO : < 200 OK [1457]
2017-12-31 21:30:59,251 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 790, 'name': 'Client Needs and Software Requirements '}}
2017-12-31 21:30:59,254 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:30:59,259 : INFO : < 200 OK [1443]
2017-12-31 21:30:59,263 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 198, 'name': 'Managing an Agile Team'}}
2017-12-31 21:30:59,266 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2017-12-31 21:30:59,273 : INFO : < 200 OK [1426]
2017-12-31 21:30:59,277 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 199, 'level': 'Beginner', 'name': 'Design Principles: an Introduction'}}
2017-12-31 21:30:59,280 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2017-12-31 21:30:59,286 : INFO : < 200 OK [1467]
2017-12-31 21:30:59,290 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 794, 'name': 'Agile Planning for Software Products'}}
2017-12-31 21:30:59,294 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:30:59,299 : INFO : < 200 OK [1440]
2017-12-31 21:30:59,304 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.6', 'id': 622, 'level': 'Intermediate', 'name': 'Designing, Running, and Analyzing Experiments'}}
2017-12-31 21:30:59,307 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2017-12-31 21:30:59,312 : INFO : < 200 OK [1482]
2017-12-31 21:30:59,317 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 795, 'level': 'Intermediate', 'name': 'Running Product Design Sprints'}}
2017-12-31 21:30:59,320 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2017-12-31 21:30:59,326 : INFO : < 200 OK [1467]
2017-12-31 21:30:59,330 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 203, 'name': 'User Experience: Research & Prototyping'}}
2017-12-31 21:30:59,333 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:30:59,340 : INFO : < 200 OK [1443]
2017-12-31 21:30:59,345 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 798, 'name': 'Principles of Game Design'}}
2017-12-31 21:30:59,348 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2017-12-31 21:30:59,354 : INFO : < 200 OK [1429]
2017-12-31 21:30:59,359 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 802, 'name': 'Testing with Agile'}}
2017-12-31 21:30:59,363 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2017-12-31 21:30:59,370 : INFO : < 200 OK [1422]
2017-12-31 21:30:59,374 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 803, 'level': 'Intermediate', 'name': '3D Models for Virtual Reality'}}
2017-12-31 21:30:59,377 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:30:59,383 : INFO : < 200 OK [1466]
2017-12-31 21:30:59,388 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 804, 'name': 'User Research and Design'}}
2017-12-31 21:30:59,391 : INFO : > POST http://localhost:7474/db/data/cypher [122]
2017-12-31 21:30:59,397 : INFO : < 200 OK [1428]
2017-12-31 21:30:59,402 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.9', 'id': 208, 'name': 'Internet of Things & Augmented Reality Emerging Technologies'}}
2017-12-31 21:30:59,406 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:30:59,413 : INFO : < 200 OK [1464]
2017-12-31 21:30:59,418 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 814, 'name': 'Prototyping and Design'}}
2017-12-31 21:30:59,422 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2017-12-31 21:30:59,428 : INFO : < 200 OK [1426]
2017-12-31 21:30:59,433 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 210, 'name': 'Information Design'}}
2017-12-31 21:30:59,436 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2017-12-31 21:30:59,443 : INFO : < 200 OK [1422]
2017-12-31 21:30:59,447 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 816, 'name': 'Reviews & Metrics for Software Improvements'}}
2017-12-31 21:30:59,451 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:30:59,457 : INFO : < 200 OK [1447]
2017-12-31 21:30:59,460 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 818, 'level': 'Intermediate', 'name': 'Agile Development in Practice (Project-centered Course)'}}
2017-12-31 21:30:59,464 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:30:59,470 : INFO : < 200 OK [1492]
2017-12-31 21:30:59,474 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 213, 'name': 'Story and Narrative Development for Video Games'}}
2017-12-31 21:30:59,478 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:30:59,484 : INFO : < 200 OK [1451]
2017-12-31 21:30:59,488 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 214, 'name': 'Character Design for Video Games'}}
2017-12-31 21:30:59,491 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:30:59,497 : INFO : < 200 OK [1436]
2017-12-31 21:30:59,501 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 825, 'name': 'Software Product Management Capstone'}}
2017-12-31 21:30:59,505 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:30:59,511 : INFO : < 200 OK [1440]
2017-12-31 21:30:59,515 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 827, 'level': 'Intermediate', 'name': 'Building Interactive 3D Characters and Social VR'}}
2017-12-31 21:30:59,519 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:30:59,525 : INFO : < 200 OK [1460]
2017-12-31 21:30:59,530 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 830, 'name': 'Evaluating User Interfaces'}}
2017-12-31 21:30:59,533 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2017-12-31 21:30:59,539 : INFO : < 200 OK [1430]
2017-12-31 21:30:59,544 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 218, 'level': 'Beginner', 'name': 'Intro to Digital Manufacturing with Autodesk Fusion 360'}}
2017-12-31 21:30:59,548 : INFO : > POST http://localhost:7474/db/data/cypher [172]
2017-12-31 21:30:59,554 : INFO : < 200 OK [1488]
2017-12-31 21:30:59,558 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 832, 'level': 'Intermediate', 'name': '3D Interaction Design in Virtual Reality'}}
2017-12-31 21:30:59,562 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2017-12-31 21:30:59,568 : INFO : < 200 OK [1477]
2017-12-31 21:30:59,572 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 835, 'level': 'Intermediate', 'name': 'Making Your First Virtual Reality Game'}}
2017-12-31 21:30:59,576 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:30:59,582 : INFO : < 200 OK [1450]
2017-12-31 21:30:59,586 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 221, 'name': 'Input and Interaction'}}
2017-12-31 21:30:59,590 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2017-12-31 21:30:59,596 : INFO : < 200 OK [1425]

2017-12-31 21:30:59,601 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 223, 'name': 'World Design for Video Games'}}
2017-12-31 21:30:59,604 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2017-12-31 21:30:59,610 : INFO : < 200 OK [1432]
2017-12-31 21:30:59,615 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 224, 'level': 'Intermediate', 'name': 'Mobile Interaction Design: How to Design Usable Mobile Products and Services'}}
2017-12-31 21:30:59,618 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:30:59,624 : INFO : < 200 OK [1488]
2017-12-31 21:30:59,629 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 849, 'level': 'Intermediate', 'name': 'System Validation: Automata and behavioural equivalences'}}
2017-12-31 21:30:59,632 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:30:59,639 : INFO : < 200 OK [1493]
2017-12-31 21:30:59,644 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 230, 'name': 'Brand New Brand'}}
2017-12-31 21:30:59,647 : INFO : > POST http://localhost:7474/db/data/cypher [113]
2017-12-31 21:30:59,654 : INFO : < 200 OK [1419]
2017-12-31 21:30:59,659 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 857, 'level': 'Intermediate', 'name': 'System Validation (2): Model process behaviour'}}
2017-12-31 21:30:59,663 : INFO : > POST http://localhost:7474/db/data/cypher [167]
2017-12-31 21:30:59,669 : INFO : < 200 OK [1483]
2017-12-31 21:30:59,673 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.8', 'id': 860, 'level': 'Advanced', 'name': 'System Validation (3): Requirements by modal formulas'}}
2017-12-31 21:30:59,677 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2017-12-31 21:30:59,682 : INFO : < 200 OK [1486]
2017-12-31 21:30:59,686 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 868, 'name': 'UI Design Capstone'}}
2017-12-31 21:30:59,689 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2017-12-31 21:30:59,695 : INFO : < 200 OK [1422]
2017-12-31 21:30:59,699 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 235, 'name': 'Interaction Design Capstone Project'}}
2017-12-31 21:30:59,702 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2017-12-31 21:30:59,707 : INFO : < 200 OK [1439]
2017-12-31 21:30:59,711 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 236, 'name': 'Game Design Document: Define the Art & Concepts'}}
2017-12-31 21:30:59,715 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:30:59,720 : INFO : < 200 OK [1451]
2017-12-31 21:30:59,724 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 237, 'name': 'Introduction to Electronics'}}
2017-12-31 21:30:59,727 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2017-12-31 21:30:59,733 : INFO : < 200 OK [1431]
2017-12-31 21:30:59,737 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 240, 'level': 'Beginner', 'name': 'Introduction to solar cells'}}
2017-12-31 21:30:59,740 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:30:59,746 : INFO : < 200 OK [1460]
2017-12-31 21:30:59,750 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 737, 'level': 'Intermediate', 'name': 'Introduction to Embedded Systems Software and Development Environments'}}
2017-12-31 21:30:59,753 : INFO : > POST http://localhost:7474/db/data/cypher [191]
2017-12-31 21:30:59,759 : INFO : < 200 OK [1507]
2017-12-31 21:30:59,763 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 744, 'name': 'The Arduino Platform and C Programming'}}
2017-12-31 21:30:59,765 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:30:59,771 : INFO : < 200 OK [1442]
2017-12-31 21:30:59,778 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 245, 'name': 'Wind Energy'}}
2017-12-31 21:30:59,781 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2017-12-31 21:30:59,786 : INFO : < 200 OK [1415]
2017-12-31 21:30:59,791 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 248, 'name': 'Introduction to Power Electronics'}}
2017-12-31 21:30:59,794 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2017-12-31 21:30:59,801 : INFO : < 200 OK [1437]
2017-12-31 21:30:59,806 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 249, 'name': 'Linear Circuits 1: DC Analysis'}}
2017-12-31 21:30:59,809 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:30:59,817 : INFO : < 200 OK [1434]
2017-12-31 21:30:59,822 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 250, 'name': 'Introduction to Systems Engineering'}}
2017-12-31 21:30:59,825 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2017-12-31 21:30:59,832 : INFO : < 200 OK [1439]
2017-12-31 21:30:59,836 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 252, 'name': 'Fundamentals of Audio and Music Engineering: Part 1 Musical Sound & Electronics'}}
2017-12-31 21:30:59,839 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:30:59,846 : INFO : < 200 OK [1483]
2017-12-31 21:30:59,851 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 253, 'name': 'Interfacing with the Arduino'}}
2017-12-31 21:30:59,855 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2017-12-31 21:30:59,861 : INFO : < 200 OK [1432]
2017-12-31 21:30:59,864 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 255, 'name': 'Internet of Things: How did we get here?'}}
2017-12-31 21:30:59,868 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:30:59,873 : INFO : < 200 OK [1444]
2017-12-31 21:30:59,877 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 256, 'level': 'Intermediate', 'name': 'Linear Circuits 2: AC Analysis '}}
2017-12-31 21:30:59,881 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2017-12-31 21:30:59,886 : INFO : < 200 OK [1468]
2017-12-31 21:30:59,890 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 257, 'level': 'Beginner', 'name': 'Introduction to Satellite Communications'}}
2017-12-31 21:30:59,893 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2017-12-31 21:30:59,899 : INFO : < 200 OK [1473]
2017-12-31 21:30:59,902 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 258, 'level': 'Beginner', 'name': 'Wireless Communications for Everybody'}}
2017-12-31 21:30:59,906 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:30:59,912 : INFO : < 200 OK [1470]
2017-12-31 21:30:59,916 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 259, 'name': 'MOS Transistors'}}
2017-12-31 21:30:59,919 : INFO : > POST http://localhost:7474/db/data/cypher [113]
2017-12-31 21:30:59,925 : INFO : < 200 OK [1419]
2017-12-31 21:30:59,928 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 260, 'name': 'Converter Circuits'}}
2017-12-31 21:30:59,932 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2017-12-31 21:30:59,937 : INFO : < 200 OK [1422]
2017-12-31 21:30:59,941 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 261, 'level': 'Intermediate', 'name': 'Intro to Acoustics (Part 1)'}}
2017-12-31 21:30:59,944 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2017-12-31 21:30:59,950 : INFO : < 200 OK [1439]
2017-12-31 21:30:59,954 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 398, 'name': 'Smartphone Emerging Technologies'}}
2017-12-31 21:30:59,957 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:30:59,963 : INFO : < 200 OK [1436]

2017-12-31 21:30:59,968 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 264, 'name': 'Requirements Writing'}}
2017-12-31 21:30:59,971 : INFO : > POST http://localhost:7474/db/data/cypher [103]
2017-12-31 21:30:59,977 : INFO : < 200 OK [1399]
2017-12-31 21:30:59,981 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 265, 'name': 'Converter Control'}}
2017-12-31 21:30:59,984 : INFO : > POST http://localhost:7474/db/data/cypher [115]
2017-12-31 21:30:59,990 : INFO : < 200 OK [1421]
2017-12-31 21:30:59,994 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 266, 'name': 'Internet of Things: Sensing and Actuation From Devices'}}
2017-12-31 21:30:59,998 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2017-12-31 21:31:00,004 : INFO : < 200 OK [1458]
2017-12-31 21:31:00,009 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 268, 'level': 'Intermediate', 'name': 'Advanced Converter Control Techniques'}}
2017-12-31 21:31:00,013 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:31:00,019 : INFO : < 200 OK [1474]
2017-12-31 21:31:00,023 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 269, 'level': 'Intermediate', 'name': 'Magnetics for Power Electronic Converters'}}
2017-12-31 21:31:00,025 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2017-12-31 21:31:00,031 : INFO : < 200 OK [1478]
2017-12-31 21:31:00,035 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 841, 'name': 'Internet of Things: Multimedia Technologies'}}
2017-12-31 21:31:00,038 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:31:00,043 : INFO : < 200 OK [1447]
2017-12-31 21:31:00,047 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 271, 'level': 'Beginner', 'name': 'Personal Leadership Development Planning and Leading High Performing Teams'}}
2017-12-31 21:31:00,050 : INFO : > POST http://localhost:7474/db/data/cypher [191]
2017-12-31 21:31:00,056 : INFO : < 200 OK [1507]
2017-12-31 21:31:00,060 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 854, 'name': 'Quantitative Formal Modeling and Worst-Case Performance Analysis'}}
2017-12-31 21:31:00,063 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2017-12-31 21:31:00,068 : INFO : < 200 OK [1468]
2017-12-31 21:31:00,072 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 273, 'level': 'Intermediate', 'name': 'Bioelectricity: A Quantitative Approach'}}
2017-12-31 21:31:00,075 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2017-12-31 21:31:00,080 : INFO : < 200 OK [1476]
2017-12-31 21:31:00,084 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 275, 'level': 'Intermediate', 'name': 'Bioelectricity:  The Mechanism of Origin of Extracellular Potentials'}}
2017-12-31 21:31:00,087 : INFO : > POST http://localhost:7474/db/data/cypher [189]
2017-12-31 21:31:00,092 : INFO : < 200 OK [1505]
2017-12-31 21:31:00,097 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 869, 'name': 'Programming for the Internet of Things Project'}}
2017-12-31 21:31:00,100 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:31:00,105 : INFO : < 200 OK [1450]
2017-12-31 21:31:00,110 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 277, 'level': 'Intermediate', 'name': 'Capstone Design Project in Power Electronics'}}
2017-12-31 21:31:00,114 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:31:00,122 : INFO : < 200 OK [1481]
2017-12-31 21:31:00,126 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.9', 'id': 278, 'name': 'Internet of Things Capstone: Build a Mobile Surveillance System'}}
2017-12-31 21:31:00,131 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2017-12-31 21:31:00,138 : INFO : < 200 OK [1467]
2017-12-31 21:31:00,143 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 521, 'level': 'Beginner', 'name': 'SQL for Data Science'}}
2017-12-31 21:31:00,147 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:31:00,153 : INFO : < 200 OK [1453]
2017-12-31 21:31:00,157 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 281, 'level': 'Intermediate', 'name': 'Introduction to Mathematical Thinking'}}
2017-12-31 21:31:00,160 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:31:00,166 : INFO : < 200 OK [1474]
2017-12-31 21:31:00,170 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 283, 'level': 'Beginner', 'name': 'Game Theory'}}
2017-12-31 21:31:00,173 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:31:00,179 : INFO : < 200 OK [1444]
2017-12-31 21:31:00,183 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 530, 'level': 'Beginner', 'name': 'Data Science Math Skills'}}
2017-12-31 21:31:00,186 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:31:00,192 : INFO : < 200 OK [1457]
2017-12-31 21:31:00,196 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 286, 'name': 'Calculus One'}}
2017-12-31 21:31:00,199 : INFO : > POST http://localhost:7474/db/data/cypher [110]
2017-12-31 21:31:00,205 : INFO : < 200 OK [1416]
2017-12-31 21:31:00,209 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 706, 'level': 'Intermediate', 'name': 'Introduction to Logic'}}
2017-12-31 21:31:00,212 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:31:00,218 : INFO : < 200 OK [1458]
2017-12-31 21:31:00,222 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 289, 'level': 'Intermediate', 'name': 'Machine Design Part I'}}
2017-12-31 21:31:00,225 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:31:00,230 : INFO : < 200 OK [1458]
2017-12-31 21:31:00,234 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 429, 'level': 'Intermediate', 'name': 'Bayesian Statistics: From Concept to Data Analysis'}}
2017-12-31 21:31:00,237 : INFO : > POST http://localhost:7474/db/data/cypher [171]
2017-12-31 21:31:00,243 : INFO : < 200 OK [1487]
2017-12-31 21:31:00,247 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 291, 'level': 'Intermediate', 'name': 'Pre-Calculus: Functions'}}
2017-12-31 21:31:00,250 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:31:00,255 : INFO : < 200 OK [1460]
2017-12-31 21:31:00,260 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 436, 'name': 'Econometrics: Methods and Applications'}}
2017-12-31 21:31:00,263 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:31:00,268 : INFO : < 200 OK [1442]
2017-12-31 21:31:00,272 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 293, 'level': 'Intermediate', 'name': 'Pre-Calculus: Trigonometry'}}
2017-12-31 21:31:00,276 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2017-12-31 21:31:00,281 : INFO : < 200 OK [1463]
2017-12-31 21:31:00,286 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 438, 'level': 'Intermediate', 'name': 'Bayesian Statistics: Techniques and Models'}}
2017-12-31 21:31:00,289 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2017-12-31 21:31:00,298 : INFO : < 200 OK [1479]
2017-12-31 21:31:00,303 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 296, 'name': 'Robotics: Aerial Robotics'}}
2017-12-31 21:31:00,306 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2017-12-31 21:31:00,314 : INFO : < 200 OK [1429]

2017-12-31 21:31:00,319 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 298, 'level': 'Beginner', 'name': 'Introduction to Ordinary Differential Equations'}}
2017-12-31 21:31:00,323 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:31:00,332 : INFO : < 200 OK [1455]
2017-12-31 21:31:00,336 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 300, 'name': 'Calculus: Single Variable Part 1 - Functions'}}
2017-12-31 21:31:00,340 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:31:00,347 : INFO : < 200 OK [1423]
2017-12-31 21:31:00,351 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 304, 'name': 'Calculus Two: Sequences and Series'}}
2017-12-31 21:31:00,355 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:31:00,361 : INFO : < 200 OK [1438]
2017-12-31 21:31:00,366 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 305, 'level': 'Intermediate', 'name': 'Introduction to Complex Analysis'}}
2017-12-31 21:31:00,369 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:31:00,376 : INFO : < 200 OK [1469]
2017-12-31 21:31:00,380 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 750, 'name': 'Image and Video Processing: From Mars to Hollywood with a Stop at the Hospital'}}
2017-12-31 21:31:00,384 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:00,390 : INFO : < 200 OK [1482]
2017-12-31 21:31:00,394 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 309, 'name': 'Mathematical Biostatistics Boot Camp 1'}}
2017-12-31 21:31:00,398 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:31:00,405 : INFO : < 200 OK [1442]
2017-12-31 21:31:00,410 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 310, 'level': 'Advanced', 'name': 'Introduction into General Theory of Relativity'}}
2017-12-31 21:31:00,413 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2017-12-31 21:31:00,419 : INFO : < 200 OK [1479]
2017-12-31 21:31:00,424 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 311, 'level': 'Advanced', 'name': 'Game Theory II: Advanced Applications'}}
2017-12-31 21:31:00,428 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:31:00,434 : INFO : < 200 OK [1470]
2017-12-31 21:31:00,439 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 314, 'level': 'Advanced', 'name': 'Interest Rate Models'}}
2017-12-31 21:31:00,442 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:31:00,448 : INFO : < 200 OK [1453]
2017-12-31 21:31:00,453 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 315, 'name': 'Robotics: Computational Motion Planning'}}
2017-12-31 21:31:00,456 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:31:00,462 : INFO : < 200 OK [1443]
2017-12-31 21:31:00,467 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 451, 'level': 'Advanced', 'name': 'Advanced Linear Models for Data Science 1: Least Squares'}}
2017-12-31 21:31:00,470 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:31:00,476 : INFO : < 200 OK [1489]
2017-12-31 21:31:00,480 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 317, 'level': 'Intermediate', 'name': 'Robotics: Perception'}}
2017-12-31 21:31:00,483 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:31:00,488 : INFO : < 200 OK [1457]
2017-12-31 21:31:00,492 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 318, 'name': 'Robotics: Estimation and Learning'}}
2017-12-31 21:31:00,495 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2017-12-31 21:31:00,500 : INFO : < 200 OK [1437]
2017-12-31 21:31:00,504 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 319, 'level': 'Beginner', 'name': 'Fibonacci Numbers and the Golden Ratio'}}
2017-12-31 21:31:00,507 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2017-12-31 21:31:00,512 : INFO : < 200 OK [1471]
2017-12-31 21:31:00,516 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 320, 'name': 'Single Variable Calculus'}}
2017-12-31 21:31:00,520 : INFO : > POST http://localhost:7474/db/data/cypher [107]
2017-12-31 21:31:00,526 : INFO : < 200 OK [1403]
2017-12-31 21:31:00,529 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 621, 'level': 'Beginner', 'name': 'Julia Scientific Programming'}}
2017-12-31 21:31:00,533 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:31:00,539 : INFO : < 200 OK [1461]
2017-12-31 21:31:00,544 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 323, 'name': 'Calculus: Single Variable Part 2 - Differentiation'}}
2017-12-31 21:31:00,549 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2017-12-31 21:31:00,556 : INFO : < 200 OK [1429]
2017-12-31 21:31:00,560 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 325, 'level': 'Advanced', 'name': 'Introduction to Galois Theory'}}
2017-12-31 21:31:00,564 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2017-12-31 21:31:00,570 : INFO : < 200 OK [1462]
2017-12-31 21:31:00,575 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 806, 'level': 'Intermediate', 'name': 'Basic Modeling for Discrete Optimization'}}
2017-12-31 21:31:00,578 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2017-12-31 21:31:00,584 : INFO : < 200 OK [1477]
2017-12-31 21:31:00,588 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 328, 'name': 'Calculus: Single Variable Part 3 - Integration'}}
2017-12-31 21:31:00,591 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2017-12-31 21:31:00,598 : INFO : < 200 OK [1425]
2017-12-31 21:31:00,602 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 330, 'level': 'Intermediate', 'name': 'Valuing Companies'}}
2017-12-31 21:31:00,605 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:31:00,611 : INFO : < 200 OK [1454]
2017-12-31 21:31:00,615 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.8', 'id': 331, 'name': 'Robotics: Mobility'}}
2017-12-31 21:31:00,618 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2017-12-31 21:31:00,623 : INFO : < 200 OK [1422]
2017-12-31 21:31:00,628 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 454, 'level': 'Advanced', 'name': 'Advanced Linear Models for Data Science 2: Statistical Linear Models'}}
2017-12-31 21:31:00,631 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2017-12-31 21:31:00,637 : INFO : < 200 OK [1501]
2017-12-31 21:31:00,641 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 333, 'level': 'Intermediate', 'name': 'Mechanics of Materials III: Beam Bending'}}
2017-12-31 21:31:00,644 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2017-12-31 21:31:00,650 : INFO : < 200 OK [1477]
2017-12-31 21:31:00,655 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 334, 'name': 'Calculus: Single Variable Part 4 - Applications'}}
2017-12-31 21:31:00,658 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:31:00,664 : INFO : < 200 OK [1426]
2017-12-31 21:31:00,668 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 336, 'level': 'Intermediate', 'name': 'Introduction to Enumerative Combinatorics'}}
2017-12-31 21:31:00,672 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2017-12-31 21:31:00,677 : INFO : < 200 OK [1478]
2017-12-31 21:31:00,681 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 338, 'level': 'Intermediate', 'name': 'Analytic Combinatorics'}}

2017-12-31 21:31:00,684 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:31:00,689 : INFO : < 200 OK [1434]
2017-12-31 21:31:00,693 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 834, 'level': 'Intermediate', 'name': 'Advanced Modeling for Discrete Optimization'}}
2017-12-31 21:31:00,697 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2017-12-31 21:31:00,702 : INFO : < 200 OK [1480]
2017-12-31 21:31:00,706 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 341, 'level': 'Beginner', 'name': 'Six Sigma Tools for Analyze'}}
2017-12-31 21:31:00,709 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:31:00,715 : INFO : < 200 OK [1460]
2017-12-31 21:31:00,719 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 342, 'name': 'Games without Chance: Combinatorial Game Theory '}}
2017-12-31 21:31:00,722 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2017-12-31 21:31:00,728 : INFO : < 200 OK [1452]
2017-12-31 21:31:00,733 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 458, 'name': 'Mathematical Biostatistics Boot Camp 2'}}
2017-12-31 21:31:00,736 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:31:00,743 : INFO : < 200 OK [1442]
2017-12-31 21:31:00,748 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 661, 'level': 'Intermediate', 'name': 'Introduction to Formal Concept Analysis'}}
2017-12-31 21:31:00,752 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2017-12-31 21:31:00,758 : INFO : < 200 OK [1476]
2017-12-31 21:31:00,763 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 347, 'name': 'Dynamical Modeling Methods for Systems Biology'}}
2017-12-31 21:31:00,767 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:31:00,772 : INFO : < 200 OK [1450]
2017-12-31 21:31:00,776 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.7', 'id': 349, 'name': 'Quantitative Foundations for International Business'}}
2017-12-31 21:31:00,779 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:31:00,785 : INFO : < 200 OK [1455]
2017-12-31 21:31:00,789 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 358, 'name': 'Robotics: Capstone'}}
2017-12-31 21:31:00,792 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2017-12-31 21:31:00,798 : INFO : < 200 OK [1422]
2017-12-31 21:31:00,803 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 359, 'name': 'Introduction to HTML5'}}
2017-12-31 21:31:00,806 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2017-12-31 21:31:00,812 : INFO : < 200 OK [1425]
2017-12-31 21:31:00,816 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 707, 'name': 'Build Your First Android App (Project-Centered Course)'}}
2017-12-31 21:31:00,819 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2017-12-31 21:31:00,825 : INFO : < 200 OK [1458]
2017-12-31 21:31:00,829 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 361, 'level': 'Beginner', 'name': 'Programming Foundations with JavaScript, HTML and CSS'}}
2017-12-31 21:31:00,832 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2017-12-31 21:31:00,838 : INFO : < 200 OK [1486]
2017-12-31 21:31:00,842 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.3', 'id': 363, 'name': 'How To Create a Website in a Weekend! (Project-Centered Course)'}}
2017-12-31 21:31:00,845 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2017-12-31 21:31:00,851 : INFO : < 200 OK [1467]
2017-12-31 21:31:00,855 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 365, 'level': 'Intermediate', 'name': 'Front-End Web UI Frameworks and Tools: Bootstrap 4'}}
2017-12-31 21:31:00,858 : INFO : > POST http://localhost:7474/db/data/cypher [171]
2017-12-31 21:31:00,864 : INFO : < 200 OK [1487]
2017-12-31 21:31:00,869 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 722, 'level': 'Intermediate', 'name': 'Programming Languages, Part A'}}
2017-12-31 21:31:00,872 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:31:00,877 : INFO : < 200 OK [1466]
2017-12-31 21:31:00,882 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 367, 'level': 'Beginner', 'name': 'Java for Android'}}
2017-12-31 21:31:00,885 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2017-12-31 21:31:00,892 : INFO : < 200 OK [1449]
2017-12-31 21:31:00,896 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 724, 'level': 'Intermediate', 'name': 'Front-End JavaScript Frameworks: Angular'}}
2017-12-31 21:31:00,900 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2017-12-31 21:31:00,908 : INFO : < 200 OK [1477]
2017-12-31 21:31:00,913 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 370, 'name': 'Introduction to CSS3'}}
2017-12-31 21:31:00,917 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2017-12-31 21:31:00,923 : INFO : < 200 OK [1424]
2017-12-31 21:31:00,929 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 728, 'level': 'Intermediate', 'name': 'Server-side Development with NodeJS, Express and MongoDB'}}
2017-12-31 21:31:00,932 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:00,939 : INFO : < 200 OK [1493]
2017-12-31 21:31:00,943 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 372, 'name': 'Interactivity with JavaScript'}}
2017-12-31 21:31:00,947 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:31:00,953 : INFO : < 200 OK [1433]
2017-12-31 21:31:00,958 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 373, 'level': 'Beginner', 'name': 'Introduction to Web Development'}}
2017-12-31 21:31:00,962 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:31:00,968 : INFO : < 200 OK [1464]
2017-12-31 21:31:00,973 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 739, 'name': 'Programming Mobile Applications for Android Handheld Systems: Part 1'}}
2017-12-31 21:31:00,976 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2017-12-31 21:31:00,982 : INFO : < 200 OK [1472]
2017-12-31 21:31:00,987 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 741, 'level': 'Intermediate', 'name': 'Design Patterns'}}
2017-12-31 21:31:00,990 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:31:00,996 : INFO : < 200 OK [1452]
2017-12-31 21:31:01,001 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 377, 'name': 'Responsive Website Basics: Code with HTML, CSS, and JavaScript '}}
2017-12-31 21:31:01,005 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2017-12-31 21:31:01,011 : INFO : < 200 OK [1467]
2017-12-31 21:31:01,015 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 378, 'name': 'Ruby on Rails: An Introduction'}}
2017-12-31 21:31:01,018 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:31:01,024 : INFO : < 200 OK [1434]
2017-12-31 21:31:01,028 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 754, 'name': 'Control of Mobile Robots'}}
2017-12-31 21:31:01,031 : INFO : > POST http://localhost:7474/db/data/cypher [122]
2017-12-31 21:31:01,037 : INFO : < 200 OK [1428]
2017-12-31 21:31:01,041 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 380, 'level': 'Intermediate', 'name': 'Single Page Web Applications with AngularJS'}}
2017-12-31 21:31:01,044 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2017-12-31 21:31:01,050 : INFO : < 200 OK [1480]

2017-12-31 21:31:01,055 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 760, 'level': 'Intermediate', 'name': 'Service-Oriented Architecture'}}
2017-12-31 21:31:01,058 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:31:01,064 : INFO : < 200 OK [1466]
2017-12-31 21:31:01,068 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 766, 'level': 'Intermediate', 'name': 'Software Architecture'}}
2017-12-31 21:31:01,072 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:31:01,078 : INFO : < 200 OK [1458]
2017-12-31 21:31:01,083 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 385, 'name': 'Web Application Development: Basic Concepts'}}
2017-12-31 21:31:01,088 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:31:01,093 : INFO : < 200 OK [1447]
2017-12-31 21:31:01,099 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 775, 'name': 'Multiplatform Mobile App Development with Web Technologies: Ionic and Cordova'}}
2017-12-31 21:31:01,102 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:01,108 : INFO : < 200 OK [1481]
2017-12-31 21:31:01,113 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 777, 'level': 'Beginner', 'name': 'Developing Android Apps with App Inventor'}}
2017-12-31 21:31:01,116 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:31:01,123 : INFO : < 200 OK [1474]
2017-12-31 21:31:01,127 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.9', 'id': 388, 'name': 'Introduction To Swift Programming'}}
2017-12-31 21:31:01,131 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2017-12-31 21:31:01,137 : INFO : < 200 OK [1437]
2017-12-31 21:31:01,141 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 389, 'name': 'Advanced Styling with Responsive Design'}}
2017-12-31 21:31:01,145 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:31:01,151 : INFO : < 200 OK [1443]
2017-12-31 21:31:01,156 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 788, 'name': 'Programming Languages, Part C'}}
2017-12-31 21:31:01,160 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:31:01,166 : INFO : < 200 OK [1433]
2017-12-31 21:31:01,170 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 391, 'name': 'Responsive Web Design'}}
2017-12-31 21:31:01,174 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2017-12-31 21:31:01,181 : INFO : < 200 OK [1425]
2017-12-31 21:31:01,185 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 793, 'level': 'Intermediate', 'name': 'Programming Languages, Part B'}}
2017-12-31 21:31:01,189 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:31:01,195 : INFO : < 200 OK [1466]
2017-12-31 21:31:01,199 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 393, 'name': 'Android App Components - Intents, Activities, and Broadcast Receivers'}}
2017-12-31 21:31:01,202 : INFO : > POST http://localhost:7474/db/data/cypher [167]
2017-12-31 21:31:01,208 : INFO : < 200 OK [1473]
2017-12-31 21:31:01,213 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 799, 'level': 'Intermediate', 'name': 'Multiplatform Mobile App Development with NativeScript'}}
2017-12-31 21:31:01,216 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:01,222 : INFO : < 200 OK [1491]
2017-12-31 21:31:01,226 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 801, 'level': 'Intermediate', 'name': 'Agile Software Development'}}
2017-12-31 21:31:01,229 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2017-12-31 21:31:01,235 : INFO : < 200 OK [1463]
2017-12-31 21:31:01,240 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 813, 'name': 'Web Application Development with JavaScript and MongoDB'}}
2017-12-31 21:31:01,243 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:31:01,249 : INFO : < 200 OK [1459]
2017-12-31 21:31:01,254 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 821, 'level': 'Beginner', 'name': 'Android App Components - Services, Local IPC, and Content Providers'}}
2017-12-31 21:31:01,257 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2017-12-31 21:31:01,263 : INFO : < 200 OK [1500]
2017-12-31 21:31:01,268 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 399, 'name': 'Programming Mobile Applications for Android Handheld Systems: Part 2'}}
2017-12-31 21:31:01,272 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2017-12-31 21:31:01,278 : INFO : < 200 OK [1472]
2017-12-31 21:31:01,284 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 824, 'name': 'Engineering Maintainable Android Apps'}}
2017-12-31 21:31:01,288 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2017-12-31 21:31:01,294 : INFO : < 200 OK [1441]
2017-12-31 21:31:01,299 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 828, 'name': 'Ruby on Rails Web Services and Integration with MongoDB'}}
2017-12-31 21:31:01,303 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:31:01,309 : INFO : < 200 OK [1459]
2017-12-31 21:31:01,314 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 402, 'name': 'Introduction to Meteor.js Development  '}}
2017-12-31 21:31:01,318 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:31:01,324 : INFO : < 200 OK [1443]
2017-12-31 21:31:01,329 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 403, 'name': 'Responsive Website Tutorial and Examples'}}
2017-12-31 21:31:01,332 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:31:01,338 : INFO : < 200 OK [1444]
2017-12-31 21:31:01,343 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 404, 'name': 'iOS App Development Basics'}}
2017-12-31 21:31:01,346 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2017-12-31 21:31:01,352 : INFO : < 200 OK [1430]
2017-12-31 21:31:01,357 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 837, 'name': 'Rails with Active Record and Action Pack'}}
2017-12-31 21:31:01,360 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:31:01,366 : INFO : < 200 OK [1444]
2017-12-31 21:31:01,370 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 406, 'name': 'Foundations of Objective-C App Development'}}
2017-12-31 21:31:01,374 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2017-12-31 21:31:01,379 : INFO : < 200 OK [1446]
2017-12-31 21:31:01,384 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 407, 'name': 'CODAPPS: Coding mobile apps for entrepreneurs'}}
2017-12-31 21:31:01,387 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2017-12-31 21:31:01,393 : INFO : < 200 OK [1449]
2017-12-31 21:31:01,398 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 840, 'level': 'Intermediate', 'name': 'Getting Started With Application Development'}}
2017-12-31 21:31:01,402 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:31:01,409 : INFO : < 200 OK [1481]
2017-12-31 21:31:01,415 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 409, 'name': 'App Design and Development for iOS'}}
2017-12-31 21:31:01,418 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:31:01,424 : INFO : < 200 OK [1438]

2017-12-31 21:31:01,429 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 410, 'name': 'Best Practices for iOS User Interface Design'}}
2017-12-31 21:31:01,433 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:31:01,439 : INFO : < 200 OK [1448]
2017-12-31 21:31:01,444 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.8', 'id': 411, 'name': 'Toward the Future of iOS Development with Swift'}}
2017-12-31 21:31:01,447 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:31:01,453 : INFO : < 200 OK [1451]
2017-12-31 21:31:01,458 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 864, 'name': 'Interfaz de usuario en iOS'}}
2017-12-31 21:31:01,462 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2017-12-31 21:31:01,468 : INFO : < 200 OK [1430]
2017-12-31 21:31:01,472 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 865, 'name': 'Interactuando con el hardware del dispositivo iOS'}}
2017-12-31 21:31:01,476 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2017-12-31 21:31:01,481 : INFO : < 200 OK [1453]
2017-12-31 21:31:01,486 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 870, 'name': 'Capstone MOOC for "Android App Development"'}}
2017-12-31 21:31:01,489 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2017-12-31 21:31:01,497 : INFO : < 200 OK [1449]
2017-12-31 21:31:01,502 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 416, 'name': 'Capstone: Photo Tourist Web Application'}}
2017-12-31 21:31:01,505 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:31:01,511 : INFO : < 200 OK [1443]
2017-12-31 21:31:01,515 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 417, 'name': 'iOS Project: Transreality Game'}}
2017-12-31 21:31:01,519 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:31:01,524 : INFO : < 200 OK [1434]
2017-12-31 21:31:01,529 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 418, 'name': 'Web Design for Everybody Capstone'}}
2017-12-31 21:31:01,532 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2017-12-31 21:31:01,539 : INFO : < 200 OK [1437]
2017-12-31 21:31:01,543 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 419, 'name': 'Responsive Website Development and Design Capstone '}}
2017-12-31 21:31:01,547 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:31:01,555 : INFO : < 200 OK [1455]
2017-12-31 21:31:01,559 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '2.8', 'id': 420, 'name': 'Build Your Own iOS App'}}
2017-12-31 21:31:01,564 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2017-12-31 21:31:01,570 : INFO : < 200 OK [1426]
2017-12-31 21:31:01,574 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 421, 'level': 'Intermediate', 'name': 'Getting started with Augmented Reality'}}
2017-12-31 21:31:01,578 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2017-12-31 21:31:01,584 : INFO : < 200 OK [1475]
2017-12-31 21:31:01,589 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 524, 'level': 'Intermediate', 'name': 'R Programming'}}
2017-12-31 21:31:01,592 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:31:01,598 : INFO : < 200 OK [1450]
2017-12-31 21:31:01,603 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 528, 'level': 'Beginner', 'name': 'Introduction to Probability and Data'}}
2017-12-31 21:31:01,606 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:31:01,612 : INFO : < 200 OK [1469]
2017-12-31 21:31:01,617 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 539, 'name': 'Getting and Cleaning Data'}}
2017-12-31 21:31:01,620 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2017-12-31 21:31:01,626 : INFO : < 200 OK [1429]
2017-12-31 21:31:01,631 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 431, 'level': 'Beginner', 'name': 'Basic Statistics'}}
2017-12-31 21:31:01,634 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2017-12-31 21:31:01,640 : INFO : < 200 OK [1449]
2017-12-31 21:31:01,644 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 551, 'name': 'Exploratory Data Analysis'}}
2017-12-31 21:31:01,647 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2017-12-31 21:31:01,653 : INFO : < 200 OK [1429]
2017-12-31 21:31:01,658 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 553, 'name': 'Regression Models'}}
2017-12-31 21:31:01,661 : INFO : > POST http://localhost:7474/db/data/cypher [115]
2017-12-31 21:31:01,667 : INFO : < 200 OK [1421]
2017-12-31 21:31:01,672 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 555, 'name': 'Statistical Inference'}}
2017-12-31 21:31:01,675 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2017-12-31 21:31:01,682 : INFO : < 200 OK [1425]
2017-12-31 21:31:01,687 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 483, 'name': 'Machine Learning: Regression'}}
2017-12-31 21:31:01,691 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2017-12-31 21:31:01,698 : INFO : < 200 OK [1432]
2017-12-31 21:31:01,703 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 558, 'level': 'Beginner', 'name': 'Inferential Statistics'}}
2017-12-31 21:31:01,706 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:31:01,713 : INFO : < 200 OK [1455]
2017-12-31 21:31:01,718 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 562, 'name': 'Data Visualization'}}
2017-12-31 21:31:01,721 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2017-12-31 21:31:01,728 : INFO : < 200 OK [1422]
2017-12-31 21:31:01,732 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.8', 'id': 564, 'level': 'Intermediate', 'name': 'Bayesian Statistics'}}
2017-12-31 21:31:01,735 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2017-12-31 21:31:01,742 : INFO : < 200 OK [1456]
2017-12-31 21:31:01,746 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 566, 'level': 'Beginner', 'name': 'Linear Regression and Modeling '}}
2017-12-31 21:31:01,749 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:31:01,755 : INFO : < 200 OK [1464]
2017-12-31 21:31:01,760 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 572, 'name': 'Reproducible Research'}}
2017-12-31 21:31:01,764 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2017-12-31 21:31:01,770 : INFO : < 200 OK [1425]
2017-12-31 21:31:01,774 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 443, 'level': 'Intermediate', 'name': 'Improving your statistical inferences'}}
2017-12-31 21:31:01,778 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:31:01,783 : INFO : < 200 OK [1474]
2017-12-31 21:31:01,788 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 444, 'name': 'Understanding Clinical Research: Behind the Statistics'}}
2017-12-31 21:31:01,793 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2017-12-31 21:31:01,799 : INFO : < 200 OK [1458]
2017-12-31 21:31:01,804 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 575, 'name': 'Developing Data Products'}}
2017-12-31 21:31:01,809 : INFO : > POST http://localhost:7474/db/data/cypher [122]
2017-12-31 21:31:01,816 : INFO : < 200 OK [1428]

2017-12-31 21:31:01,821 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 446, 'name': 'Statistical Reasoning for Public Health 1: Estimation, Inference, & Interpretation'}}
2017-12-31 21:31:01,825 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:01,831 : INFO : < 200 OK [1486]
2017-12-31 21:31:01,836 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 447, 'level': 'Beginner', 'name': 'An Intuitive Introduction to Probability'}}
2017-12-31 21:31:01,840 : INFO : > POST http://localhost:7474/db/data/cypher [157]
2017-12-31 21:31:01,846 : INFO : < 200 OK [1473]
2017-12-31 21:31:01,851 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 602, 'level': 'Intermediate', 'name': 'A Crash Course in Causality:  Inferring Causal Effects from Observational Data'}}
2017-12-31 21:31:01,854 : INFO : > POST http://localhost:7474/db/data/cypher [199]
2017-12-31 21:31:01,861 : INFO : < 200 OK [1515]
2017-12-31 21:31:01,866 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 614, 'name': 'Inferential Statistics'}}
2017-12-31 21:31:01,869 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2017-12-31 21:31:01,876 : INFO : < 200 OK [1426]
2017-12-31 21:31:01,880 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 450, 'name': 'Statistical Reasoning for Public Health 2: Regression Methods'}}
2017-12-31 21:31:01,884 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2017-12-31 21:31:01,890 : INFO : < 200 OK [1465]
2017-12-31 21:31:01,894 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 452, 'level': 'Intermediate', 'name': 'Experimentation for Improvement'}}
2017-12-31 21:31:01,898 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2017-12-31 21:31:01,904 : INFO : < 200 OK [1468]
2017-12-31 21:31:01,909 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 638, 'name': 'Regression Modeling in Practice'}}
2017-12-31 21:31:01,913 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2017-12-31 21:31:01,920 : INFO : < 200 OK [1435]
2017-12-31 21:31:01,924 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 455, 'name': 'Statistics for Genomic Data Science'}}
2017-12-31 21:31:01,927 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2017-12-31 21:31:01,933 : INFO : < 200 OK [1439]
2017-12-31 21:31:01,937 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 456, 'name': 'Measuring Causal Effects in the Social Sciences'}}
2017-12-31 21:31:01,941 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:31:01,947 : INFO : < 200 OK [1451]
2017-12-31 21:31:01,951 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 654, 'level': 'Beginner', 'name': 'Data Science Ethics'}}
2017-12-31 21:31:01,954 : INFO : > POST http://localhost:7474/db/data/cypher [121]
2017-12-31 21:31:01,960 : INFO : < 200 OK [1427]
2017-12-31 21:31:01,964 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 459, 'level': 'Beginner', 'name': 'Exploring and Producing Data for Business Decision Making'}}
2017-12-31 21:31:01,968 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:01,974 : INFO : < 200 OK [1490]
2017-12-31 21:31:01,979 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 460, 'level': 'Beginner', 'name': 'Science Literacy - How Solid Science Can Help You Save the World'}}
2017-12-31 21:31:01,982 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:01,990 : INFO : < 200 OK [1497]
2017-12-31 21:31:01,995 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 680, 'name': 'Statistics with R Capstone'}}
2017-12-31 21:31:01,999 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2017-12-31 21:31:02,005 : INFO : < 200 OK [1430]
2017-12-31 21:31:02,009 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 470, 'name': 'Machine Learning'}}
2017-12-31 21:31:02,013 : INFO : > POST http://localhost:7474/db/data/cypher [114]
2017-12-31 21:31:02,019 : INFO : < 200 OK [1420]
2017-12-31 21:31:02,024 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 520, 'level': 'Beginner', 'name': 'Structuring Machine Learning Projects'}}
2017-12-31 21:31:02,028 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:31:02,034 : INFO : < 200 OK [1470]
2017-12-31 21:31:02,038 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 523, 'name': 'Neural Networks for Machine Learning'}}
2017-12-31 21:31:02,042 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:31:02,048 : INFO : < 200 OK [1440]
2017-12-31 21:31:02,053 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 477, 'level': 'Advanced', 'name': 'Introduction to Deep Learning'}}
2017-12-31 21:31:02,056 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2017-12-31 21:31:02,063 : INFO : < 200 OK [1462]
2017-12-31 21:31:02,067 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 478, 'name': 'Machine Learning Foundations: A Case Study Approach'}}
2017-12-31 21:31:02,071 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:31:02,077 : INFO : < 200 OK [1455]
2017-12-31 21:31:02,081 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 532, 'level': 'Advanced', 'name': 'How to Win a Data Science Competition: Learn from Top Kagglers'}}
2017-12-31 21:31:02,085 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2017-12-31 21:31:02,090 : INFO : < 200 OK [1495]
2017-12-31 21:31:02,095 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 480, 'level': 'Advanced', 'name': 'Bayesian Methods for Machine Learning'}}
2017-12-31 21:31:02,098 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:31:02,104 : INFO : < 200 OK [1470]
2017-12-31 21:31:02,108 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 549, 'name': 'Practical Machine Learning'}}
2017-12-31 21:31:02,112 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2017-12-31 21:31:02,118 : INFO : < 200 OK [1430]
2017-12-31 21:31:02,122 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 482, 'level': 'Beginner', 'name': 'Computational Neuroscience'}}
2017-12-31 21:31:02,125 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2017-12-31 21:31:02,131 : INFO : < 200 OK [1459]
2017-12-31 21:31:02,135 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 485, 'name': 'Machine Learning: Classification'}}
2017-12-31 21:31:02,139 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:31:02,145 : INFO : < 200 OK [1436]
2017-12-31 21:31:02,149 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 733, 'level': 'Beginner', 'name': 'The Unix Workbench'}}
2017-12-31 21:31:02,153 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2017-12-31 21:31:02,160 : INFO : < 200 OK [1451]
2017-12-31 21:31:02,166 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 738, 'level': 'Beginner', 'name': "A developer's guide to the Internet of Things (IoT)"}}
2017-12-31 21:31:02,170 : INFO : > POST http://localhost:7474/db/data/cypher [168]
2017-12-31 21:31:02,176 : INFO : < 200 OK [1484]
2017-12-31 21:31:02,182 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 488, 'level': 'Beginner', 'name': 'Deep Learning for Business'}}
2017-12-31 21:31:02,185 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2017-12-31 21:31:02,191 : INFO : < 200 OK [1459]

2017-12-31 21:31:02,196 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 568, 'name': 'Machine Learning: Clustering & Retrieval'}}
2017-12-31 21:31:02,199 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:31:02,206 : INFO : < 200 OK [1444]
2017-12-31 21:31:02,210 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 570, 'level': 'Intermediate', 'name': 'Google Cloud Platform Big Data and Machine Learning Fundamentals'}}
2017-12-31 21:31:02,213 : INFO : > POST http://localhost:7474/db/data/cypher [185]
2017-12-31 21:31:02,219 : INFO : < 200 OK [1501]
2017-12-31 21:31:02,223 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 491, 'name': 'Machine Learning With Big Data'}}
2017-12-31 21:31:02,227 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:31:02,232 : INFO : < 200 OK [1434]
2017-12-31 21:31:02,237 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 577, 'name': 'Text Mining and Analytics'}}
2017-12-31 21:31:02,240 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2017-12-31 21:31:02,246 : INFO : < 200 OK [1429]
2017-12-31 21:31:02,250 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 765, 'level': 'Intermediate', 'name': 'Serverless Machine Learning with Tensorflow on Google Cloud Platform'}}
2017-12-31 21:31:02,254 : INFO : > POST http://localhost:7474/db/data/cypher [189]
2017-12-31 21:31:02,259 : INFO : < 200 OK [1505]
2017-12-31 21:31:02,264 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 494, 'level': 'Intermediate', 'name': 'Introduction to Recommender Systems:  Non-Personalized and Content-Based'}}
2017-12-31 21:31:02,268 : INFO : > POST http://localhost:7474/db/data/cypher [193]
2017-12-31 21:31:02,274 : INFO : < 200 OK [1509]
2017-12-31 21:31:02,278 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 589, 'name': 'Text Retrieval and Search Engines'}}
2017-12-31 21:31:02,283 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2017-12-31 21:31:02,290 : INFO : < 200 OK [1437]
2017-12-31 21:31:02,295 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 600, 'level': 'Intermediate', 'name': 'Leveraging Unstructured Data with Cloud Dataproc on Google Cloud Platform'}}
2017-12-31 21:31:02,299 : INFO : > POST http://localhost:7474/db/data/cypher [194]
2017-12-31 21:31:02,305 : INFO : < 200 OK [1510]
2017-12-31 21:31:02,309 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.7', 'id': 778, 'level': 'Advanced', 'name': 'Big Data Applications: Machine Learning at Scale'}}
2017-12-31 21:31:02,313 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:31:02,319 : INFO : < 200 OK [1481]
2017-12-31 21:31:02,324 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 613, 'level': 'Intermediate', 'name': 'Social Media Data Analytics'}}
2017-12-31 21:31:02,328 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:31:02,334 : INFO : < 200 OK [1464]
2017-12-31 21:31:02,338 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 612, 'name': 'Machine Learning for Data Analysis'}}
2017-12-31 21:31:02,342 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:31:02,348 : INFO : < 200 OK [1438]
2017-12-31 21:31:02,352 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 503, 'name': 'Matrix Factorization and Advanced Techniques'}}
2017-12-31 21:31:02,356 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:31:02,362 : INFO : < 200 OK [1448]
2017-12-31 21:31:02,367 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 504, 'level': 'Beginner', 'name': 'Digital Manufacturing & Design'}}
2017-12-31 21:31:02,370 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2017-12-31 21:31:02,376 : INFO : < 200 OK [1463]
2017-12-31 21:31:02,381 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 505, 'name': 'Nearest Neighbor Collaborative Filtering'}}
2017-12-31 21:31:02,384 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:31:02,390 : INFO : < 200 OK [1444]
2017-12-31 21:31:02,395 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 506, 'name': 'Recommender Systems:  Evaluation and Metrics'}}
2017-12-31 21:31:02,398 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:31:02,404 : INFO : < 200 OK [1448]
2017-12-31 21:31:02,408 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 649, 'name': 'Data Science Capstone'}}
2017-12-31 21:31:02,412 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2017-12-31 21:31:02,417 : INFO : < 200 OK [1425]
2017-12-31 21:31:02,422 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 508, 'level': 'Beginner', 'name': 'Intelligent Machining'}}
2017-12-31 21:31:02,425 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:31:02,431 : INFO : < 200 OK [1454]
2017-12-31 21:31:02,435 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 509, 'level': 'Beginner', 'name': 'MBSE: Model-Based Systems Engineering '}}
2017-12-31 21:31:02,439 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2017-12-31 21:31:02,445 : INFO : < 200 OK [1471]
2017-12-31 21:31:02,450 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 510, 'level': 'Beginner', 'name': 'Advanced Manufacturing Process Analysis'}}
2017-12-31 21:31:02,454 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2017-12-31 21:31:02,462 : INFO : < 200 OK [1472]
2017-12-31 21:31:02,466 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 511, 'level': 'Beginner', 'name': 'Digital Thread: Components'}}
2017-12-31 21:31:02,470 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2017-12-31 21:31:02,477 : INFO : < 200 OK [1459]
2017-12-31 21:31:02,482 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 512, 'level': 'Beginner', 'name': 'Digital Thread: Implementation'}}
2017-12-31 21:31:02,486 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2017-12-31 21:31:02,492 : INFO : < 200 OK [1463]
2017-12-31 21:31:02,497 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 513, 'level': 'Beginner', 'name': 'Advanced Manufacturing Enterprise'}}
2017-12-31 21:31:02,500 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:31:02,506 : INFO : < 200 OK [1466]
2017-12-31 21:31:02,510 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 514, 'level': 'Beginner', 'name': 'Roadmap to Success in Digital Manufacturing & Design '}}
2017-12-31 21:31:02,514 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2017-12-31 21:31:02,519 : INFO : < 200 OK [1461]
2017-12-31 21:31:02,524 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 515, 'level': 'Beginner', 'name': 'Cyber Security in Manufacturing  '}}
2017-12-31 21:31:02,527 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:31:02,533 : INFO : < 200 OK [1466]
2017-12-31 21:31:02,537 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.9', 'id': 516, 'level': 'Beginner', 'name': 'Digital Manufacturing Commons (opendmc.org)'}}
2017-12-31 21:31:02,540 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2017-12-31 21:31:02,546 : INFO : < 200 OK [1476]
2017-12-31 21:31:02,550 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 862, 'level': 'Advanced', 'name': 'Big Data Services: Capstone Project'}}
2017-12-31 21:31:02,554 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:31:02,559 : INFO : < 200 OK [1443]

2017-12-31 21:31:02,564 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 518, 'name': 'Recommender Systems Capstone'}}
2017-12-31 21:31:02,567 : INFO : > POST http://localhost:7474/db/data/cypher [111]
2017-12-31 21:31:02,573 : INFO : < 200 OK [1407]
2017-12-31 21:31:02,578 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 700, 'level': 'Intermediate', 'name': 'Introduction to Data Science in Python'}}
2017-12-31 21:31:02,581 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2017-12-31 21:31:02,588 : INFO : < 200 OK [1475]
2017-12-31 21:31:02,594 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 702, 'name': 'Python Data Structures'}}
2017-12-31 21:31:02,598 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2017-12-31 21:31:02,604 : INFO : < 200 OK [1426]
2017-12-31 21:31:02,609 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 526, 'name': 'A Crash Course in Data Science'}}
2017-12-31 21:31:02,613 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:31:02,619 : INFO : < 200 OK [1434]
2017-12-31 21:31:02,624 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 527, 'level': 'Beginner', 'name': 'Data-driven Decision Making'}}
2017-12-31 21:31:02,628 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:31:02,634 : INFO : < 200 OK [1460]
2017-12-31 21:31:02,639 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 529, 'name': 'Introduction to Big Data'}}
2017-12-31 21:31:02,642 : INFO : > POST http://localhost:7474/db/data/cypher [122]
2017-12-31 21:31:02,648 : INFO : < 200 OK [1428]
2017-12-31 21:31:02,653 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 531, 'level': 'Intermediate', 'name': 'Applied Machine Learning in Python'}}
2017-12-31 21:31:02,657 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2017-12-31 21:31:02,663 : INFO : < 200 OK [1471]
2017-12-31 21:31:02,668 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 533, 'level': 'Beginner', 'name': 'Excel Skills for Business: Essentials'}}
2017-12-31 21:31:02,672 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:31:02,677 : INFO : < 200 OK [1470]
2017-12-31 21:31:02,682 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 709, 'name': 'Using Databases with Python'}}
2017-12-31 21:31:02,686 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2017-12-31 21:31:02,692 : INFO : < 200 OK [1431]
2017-12-31 21:31:02,696 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 536, 'level': 'Beginner', 'name': 'Problem Solving with Excel '}}
2017-12-31 21:31:02,700 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:31:02,706 : INFO : < 200 OK [1460]
2017-12-31 21:31:02,710 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 713, 'level': 'Intermediate', 'name': 'The R Programming Environment'}}
2017-12-31 21:31:02,714 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:31:02,720 : INFO : < 200 OK [1466]
2017-12-31 21:31:02,725 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 538, 'name': 'Data Visualization and Communication with Tableau'}}
2017-12-31 21:31:02,729 : INFO : > POST http://localhost:7474/db/data/cypher [147]
2017-12-31 21:31:02,736 : INFO : < 200 OK [1453]
2017-12-31 21:31:02,741 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 540, 'name': 'Business Metrics for Data-Driven Companies'}}
2017-12-31 21:31:02,745 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2017-12-31 21:31:02,751 : INFO : < 200 OK [1446]
2017-12-31 21:31:02,756 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 717, 'level': 'Intermediate', 'name': 'Applied Text Mining in Python'}}
2017-12-31 21:31:02,760 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:31:02,766 : INFO : < 200 OK [1466]
2017-12-31 21:31:02,770 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 718, 'level': 'Beginner', 'name': 'Python Programming Essentials'}}
2017-12-31 21:31:02,774 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2017-12-31 21:31:02,781 : INFO : < 200 OK [1462]
2017-12-31 21:31:02,786 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 543, 'name': 'Introduction to Data Analysis Using Excel'}}
2017-12-31 21:31:02,789 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:31:02,795 : INFO : < 200 OK [1445]
2017-12-31 21:31:02,800 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 544, 'name': 'Fundamentals of Quantitative Modeling'}}
2017-12-31 21:31:02,804 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2017-12-31 21:31:02,810 : INFO : < 200 OK [1441]
2017-12-31 21:31:02,815 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 545, 'name': 'Customer Analytics'}}
2017-12-31 21:31:02,818 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2017-12-31 21:31:02,824 : INFO : < 200 OK [1397]
2017-12-31 21:31:02,828 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 720, 'level': 'Intermediate', 'name': 'Big Data Essentials: HDFS, MapReduce and Spark RDD'}}
2017-12-31 21:31:02,832 : INFO : > POST http://localhost:7474/db/data/cypher [171]
2017-12-31 21:31:02,838 : INFO : < 200 OK [1487]
2017-12-31 21:31:02,842 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 547, 'name': 'Mastering Data Analysis in Excel'}}
2017-12-31 21:31:02,846 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:31:02,852 : INFO : < 200 OK [1436]
2017-12-31 21:31:02,857 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 721, 'name': 'Capstone: Retrieving, Processing, and Visualizing Data with Python'}}
2017-12-31 21:31:02,860 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2017-12-31 21:31:02,867 : INFO : < 200 OK [1470]
2017-12-31 21:31:02,872 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 550, 'name': 'Managing Big Data with MySQL'}}
2017-12-31 21:31:02,876 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2017-12-31 21:31:02,882 : INFO : < 200 OK [1432]
2017-12-31 21:31:02,886 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 552, 'level': 'Beginner', 'name': 'Data Visualization with Advanced Excel'}}
2017-12-31 21:31:02,890 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2017-12-31 21:31:02,895 : INFO : < 200 OK [1471]
2017-12-31 21:31:02,900 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 554, 'level': 'Beginner', 'name': 'Fundamentals of Visualization with Tableau'}}
2017-12-31 21:31:02,904 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2017-12-31 21:31:02,910 : INFO : < 200 OK [1475]
2017-12-31 21:31:02,915 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 556, 'level': 'Beginner', 'name': 'Effective Business Presentations with Powerpoint'}}
2017-12-31 21:31:02,918 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:31:02,924 : INFO : < 200 OK [1481]
2017-12-31 21:31:02,929 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 557, 'level': 'Beginner', 'name': 'Marketing Analytics'}}
2017-12-31 21:31:02,933 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:31:02,939 : INFO : < 200 OK [1452]
2017-12-31 21:31:02,944 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 729, 'level': 'Intermediate', 'name': 'Applied Social Network Analysis in Python'}}
2017-12-31 21:31:02,948 : INFO : > POST http://localhost:7474/db/data/cypher [162]

2017-12-31 21:31:02,954 : INFO : < 200 OK [1478]
2017-12-31 21:31:02,958 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 560, 'name': 'Hadoop Platform and Application Framework'}}
2017-12-31 21:31:02,962 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2017-12-31 21:31:02,968 : INFO : < 200 OK [1420]
2017-12-31 21:31:02,973 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 732, 'name': 'Database Management Essentials'}}
2017-12-31 21:31:02,977 : INFO : > POST http://localhost:7474/db/data/cypher [128]
2017-12-31 21:31:02,984 : INFO : < 200 OK [1434]
2017-12-31 21:31:02,988 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 563, 'name': 'Introduction to Search Engine Optimization'}}
2017-12-31 21:31:02,992 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2017-12-31 21:31:02,998 : INFO : < 200 OK [1446]
2017-12-31 21:31:03,003 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 565, 'name': 'Introduction to Spreadsheets and Models'}}
2017-12-31 21:31:03,006 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:31:03,013 : INFO : < 200 OK [1443]
2017-12-31 21:31:03,018 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 567, 'name': 'Big Data Modeling and Management Systems'}}
2017-12-31 21:31:03,021 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:31:03,028 : INFO : < 200 OK [1444]
2017-12-31 21:31:03,033 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 569, 'level': 'Intermediate', 'name': 'Excel Skills for Business: Intermediate I'}}
2017-12-31 21:31:03,037 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2017-12-31 21:31:03,043 : INFO : < 200 OK [1478]
2017-12-31 21:31:03,049 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 571, 'name': 'People Analytics'}}
2017-12-31 21:31:03,052 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2017-12-31 21:31:03,058 : INFO : < 200 OK [1395]
2017-12-31 21:31:03,063 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 573, 'name': 'Operations Analytics'}}
2017-12-31 21:31:03,067 : INFO : > POST http://localhost:7474/db/data/cypher [103]
2017-12-31 21:31:03,073 : INFO : < 200 OK [1399]
2017-12-31 21:31:03,077 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 574, 'level': 'Intermediate', 'name': 'Excel Skills for Business: Advanced'}}
2017-12-31 21:31:03,081 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:31:03,087 : INFO : < 200 OK [1447]
2017-12-31 21:31:03,091 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 576, 'level': 'Beginner', 'name': 'Big Data Integration and Processing'}}
2017-12-31 21:31:03,095 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2017-12-31 21:31:03,101 : INFO : < 200 OK [1468]
2017-12-31 21:31:03,106 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 748, 'level': 'Beginner', 'name': 'Data Processing Using Python'}}
2017-12-31 21:31:03,110 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:31:03,116 : INFO : < 200 OK [1461]
2017-12-31 21:31:03,121 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.9', 'id': 749, 'level': 'Advanced', 'name': 'Big Data Analysis: Hive, Spark SQL, DataFrames and GraphFrames'}}
2017-12-31 21:31:03,124 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2017-12-31 21:31:03,130 : INFO : < 200 OK [1495]
2017-12-31 21:31:03,135 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 580, 'name': 'Managing Data Analysis'}}
2017-12-31 21:31:03,138 : INFO : > POST http://localhost:7474/db/data/cypher [120]
2017-12-31 21:31:03,144 : INFO : < 200 OK [1426]
2017-12-31 21:31:03,149 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 581, 'level': 'Intermediate', 'name': 'Excel Skills for Business: Intermediate II'}}
2017-12-31 21:31:03,153 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2017-12-31 21:31:03,159 : INFO : < 200 OK [1479]
2017-12-31 21:31:03,163 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 582, 'level': 'Advanced', 'name': 'Social and Economic Networks:  Models and Analysis'}}
2017-12-31 21:31:03,167 : INFO : > POST http://localhost:7474/db/data/cypher [167]
2017-12-31 21:31:03,173 : INFO : < 200 OK [1483]
2017-12-31 21:31:03,178 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 583, 'name': 'Accounting Analytics'}}
2017-12-31 21:31:03,181 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2017-12-31 21:31:03,187 : INFO : < 200 OK [1424]
2017-12-31 21:31:03,191 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 584, 'level': 'Beginner', 'name': 'Data Management for Clinical Research'}}
2017-12-31 21:31:03,195 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:31:03,201 : INFO : < 200 OK [1470]
2017-12-31 21:31:03,205 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 761, 'level': 'Beginner', 'name': 'Python Data Visualization'}}
2017-12-31 21:31:03,208 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:31:03,214 : INFO : < 200 OK [1458]
2017-12-31 21:31:03,218 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 587, 'name': 'Modeling Risk and Realities'}}
2017-12-31 21:31:03,222 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2017-12-31 21:31:03,228 : INFO : < 200 OK [1431]
2017-12-31 21:31:03,232 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 762, 'level': 'Beginner', 'name': 'Python Data Analysis'}}
2017-12-31 21:31:03,236 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:31:03,241 : INFO : < 200 OK [1453]
2017-12-31 21:31:03,246 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 590, 'name': 'Graph Analytics for Big Data'}}
2017-12-31 21:31:03,249 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2017-12-31 21:31:03,256 : INFO : < 200 OK [1432]
2017-12-31 21:31:03,260 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 591, 'name': 'Introduction to Data Analytics for Business'}}
2017-12-31 21:31:03,264 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:31:03,271 : INFO : < 200 OK [1447]
2017-12-31 21:31:03,275 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 592, 'level': 'Beginner', 'name': 'Essential Design Principles for Tableau'}}
2017-12-31 21:31:03,280 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2017-12-31 21:31:03,286 : INFO : < 200 OK [1472]
2017-12-31 21:31:03,290 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 593, 'name': 'Digital Analytics for Marketing Professionals: Marketing Analytics in Practice'}}
2017-12-31 21:31:03,294 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:03,300 : INFO : < 200 OK [1482]
2017-12-31 21:31:03,305 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 770, 'name': 'Data Manipulation at Scale: Systems and Algorithms'}}
2017-12-31 21:31:03,308 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:31:03,314 : INFO : < 200 OK [1454]
2017-12-31 21:31:03,319 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 771, 'level': 'Intermediate', 'name': 'Advanced R Programming'}}
2017-12-31 21:31:03,323 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2017-12-31 21:31:03,329 : INFO : < 200 OK [1459]
2017-12-31 21:31:03,333 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 596, 'level': 'Intermediate', 'name': 'Process Mining: Data science in Action'}}
2017-12-31 21:31:03,337 : INFO : > POST http://localhost:7474/db/data/cypher [159]

2017-12-31 21:31:03,343 : INFO : < 200 OK [1475]
2017-12-31 21:31:03,348 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 597, 'name': 'Building a Data Science Team'}}
2017-12-31 21:31:03,351 : INFO : > POST http://localhost:7474/db/data/cypher [126]
2017-12-31 21:31:03,357 : INFO : < 200 OK [1432]
2017-12-31 21:31:03,362 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 598, 'name': 'Data Management and Visualization'}}
2017-12-31 21:31:03,365 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2017-12-31 21:31:03,371 : INFO : < 200 OK [1437]
2017-12-31 21:31:03,376 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 599, 'name': 'Data Science in Real Life'}}
2017-12-31 21:31:03,379 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2017-12-31 21:31:03,385 : INFO : < 200 OK [1429]
2017-12-31 21:31:03,390 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 601, 'name': 'Forensic Accounting and Fraud Examination'}}
2017-12-31 21:31:03,393 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:31:03,399 : INFO : < 200 OK [1445]
2017-12-31 21:31:03,404 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 779, 'level': 'Beginner', 'name': 'Python Data Representations'}}
2017-12-31 21:31:03,407 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:31:03,413 : INFO : < 200 OK [1460]
2017-12-31 21:31:03,418 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 604, 'level': 'Beginner', 'name': 'Visual Analytics with Tableau'}}
2017-12-31 21:31:03,421 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2017-12-31 21:31:03,427 : INFO : < 200 OK [1462]
2017-12-31 21:31:03,432 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 605, 'level': 'Intermediate', 'name': 'Qualitative Research Methods'}}
2017-12-31 21:31:03,435 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:31:03,441 : INFO : < 200 OK [1465]
2017-12-31 21:31:03,445 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 606, 'name': 'Decision-Making and Scenarios'}}
2017-12-31 21:31:03,449 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:31:03,455 : INFO : < 200 OK [1433]
2017-12-31 21:31:03,459 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 607, 'name': 'Basic Data Descriptors, Statistical Distributions, and Application to Business Decisions'}}
2017-12-31 21:31:03,463 : INFO : > POST http://localhost:7474/db/data/cypher [186]
2017-12-31 21:31:03,469 : INFO : < 200 OK [1492]
2017-12-31 21:31:03,473 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 608, 'level': 'Beginner', 'name': 'Creating Dashboards and Storytelling with Tableau'}}
2017-12-31 21:31:03,477 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2017-12-31 21:31:03,483 : INFO : < 200 OK [1482]
2017-12-31 21:31:03,488 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 786, 'name': 'Cluster Analysis in Data Mining'}}
2017-12-31 21:31:03,491 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2017-12-31 21:31:03,497 : INFO : < 200 OK [1435]
2017-12-31 21:31:03,502 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 787, 'level': 'Intermediate', 'name': 'Building Resilient Streaming Systems on Google Cloud Platform'}}
2017-12-31 21:31:03,506 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:03,512 : INFO : < 200 OK [1498]
2017-12-31 21:31:03,517 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 792, 'name': 'Pattern Discovery in Data Mining'}}
2017-12-31 21:31:03,521 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:31:03,527 : INFO : < 200 OK [1436]
2017-12-31 21:31:03,532 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 616, 'level': 'Intermediate', 'name': 'Data-driven Astronomy'}}
2017-12-31 21:31:03,535 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:31:03,541 : INFO : < 200 OK [1458]
2017-12-31 21:31:03,545 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 617, 'level': 'Beginner', 'name': 'Data Analytics for Lean Six Sigma'}}
2017-12-31 21:31:03,549 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:31:03,555 : INFO : < 200 OK [1466]
2017-12-31 21:31:03,559 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 618, 'name': 'Principles of fMRI 1'}}
2017-12-31 21:31:03,563 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2017-12-31 21:31:03,569 : INFO : < 200 OK [1424]
2017-12-31 21:31:03,574 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 619, 'name': 'The Importance of Listening'}}
2017-12-31 21:31:03,577 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2017-12-31 21:31:03,583 : INFO : < 200 OK [1431]
2017-12-31 21:31:03,588 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 620, 'name': 'Practical Predictive Analytics: Models and Methods'}}
2017-12-31 21:31:03,591 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:31:03,598 : INFO : < 200 OK [1454]
2017-12-31 21:31:03,602 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 623, 'name': 'Python for Genomic Data Science'}}
2017-12-31 21:31:03,606 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2017-12-31 21:31:03,612 : INFO : < 200 OK [1435]
2017-12-31 21:31:03,616 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 624, 'level': 'Beginner', 'name': 'Understanding Your Data: Analytical Tools'}}
2017-12-31 21:31:03,620 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:31:03,626 : INFO : < 200 OK [1474]
2017-12-31 21:31:03,631 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.7', 'id': 625, 'name': 'Predictive Modeling and Analytics '}}
2017-12-31 21:31:03,634 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:31:03,642 : INFO : < 200 OK [1438]
2017-12-31 21:31:03,648 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 626, 'name': 'Linear Regression for Business Statistics'}}
2017-12-31 21:31:03,652 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:31:03,658 : INFO : < 200 OK [1445]
2017-12-31 21:31:03,663 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 797, 'level': 'Intermediate', 'name': 'Hands-on Text Mining and Analytics'}}
2017-12-31 21:31:03,667 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2017-12-31 21:31:03,673 : INFO : < 200 OK [1471]
2017-12-31 21:31:03,678 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 628, 'name': 'Foundations of strategic business analytics'}}
2017-12-31 21:31:03,682 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:31:03,688 : INFO : < 200 OK [1447]
2017-12-31 21:31:03,692 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 629, 'name': 'Business Analytics for Decision Making'}}
2017-12-31 21:31:03,696 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:31:03,703 : INFO : < 200 OK [1442]
2017-12-31 21:31:03,708 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 800, 'name': 'Business Intelligence Concepts, Tools, and Applications'}}
2017-12-31 21:31:03,711 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:31:03,717 : INFO : < 200 OK [1459]
2017-12-31 21:31:03,722 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 631, 'level': 'Beginner', 'name': "A developer's guide to Exploring and Visualizing IoT Data"}}

2017-12-31 21:31:03,726 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:03,731 : INFO : < 200 OK [1490]
2017-12-31 21:31:03,736 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 632, 'name': 'Business Applications of Hypothesis Testing and Confidence Interval Estimation '}}
2017-12-31 21:31:03,739 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:03,745 : INFO : < 200 OK [1483]
2017-12-31 21:31:03,750 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 633, 'level': 'Intermediate', 'name': 'Introduction to Neurohacking In R'}}
2017-12-31 21:31:03,753 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:31:03,759 : INFO : < 200 OK [1470]
2017-12-31 21:31:03,763 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 634, 'level': 'Beginner', 'name': 'Maps and the Geospatial Revolution'}}
2017-12-31 21:31:03,766 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2017-12-31 21:31:03,772 : INFO : < 200 OK [1467]
2017-12-31 21:31:03,777 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 635, 'level': 'Intermediate', 'name': 'Framework for Data Collection and Analysis'}}
2017-12-31 21:31:03,781 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2017-12-31 21:31:03,788 : INFO : < 200 OK [1479]
2017-12-31 21:31:03,793 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 808, 'level': 'Intermediate', 'name': 'Building Data Visualization Tools'}}
2017-12-31 21:31:03,798 : INFO : > POST http://localhost:7474/db/data/cypher [154]
2017-12-31 21:31:03,804 : INFO : < 200 OK [1470]
2017-12-31 21:31:03,808 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 637, 'name': 'Data Analysis Tools'}}
2017-12-31 21:31:03,813 : INFO : > POST http://localhost:7474/db/data/cypher [117]
2017-12-31 21:31:03,819 : INFO : < 200 OK [1423]
2017-12-31 21:31:03,823 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 809, 'name': 'Functional Programming in Scala Capstone'}}
2017-12-31 21:31:03,827 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:31:03,833 : INFO : < 200 OK [1444]
2017-12-31 21:31:03,838 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 642, 'level': 'Intermediate', 'name': 'Meaningful Marketing Insights'}}
2017-12-31 21:31:03,841 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:31:03,847 : INFO : < 200 OK [1466]
2017-12-31 21:31:03,852 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.6', 'id': 643, 'name': 'Genomic Data Science with Galaxy'}}
2017-12-31 21:31:03,855 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:31:03,861 : INFO : < 200 OK [1436]
2017-12-31 21:31:03,866 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 645, 'name': 'Research Data Management and Sharing'}}
2017-12-31 21:31:03,869 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:31:03,875 : INFO : < 200 OK [1440]
2017-12-31 21:31:03,880 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 819, 'level': 'Intermediate', 'name': 'Building R Packages'}}
2017-12-31 21:31:03,884 : INFO : > POST http://localhost:7474/db/data/cypher [140]
2017-12-31 21:31:03,890 : INFO : < 200 OK [1456]
2017-12-31 21:31:03,894 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 647, 'level': 'Intermediate', 'name': 'Introduction to Apache Spark and AWS'}}
2017-12-31 21:31:03,898 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:31:03,903 : INFO : < 200 OK [1448]
2017-12-31 21:31:03,908 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 648, 'level': 'Beginner', 'name': 'Digital Footprint'}}
2017-12-31 21:31:03,911 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:31:03,917 : INFO : < 200 OK [1450]
2017-12-31 21:31:03,921 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 823, 'name': 'Relational Database Support for Data Warehouses'}}
2017-12-31 21:31:03,924 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:31:03,930 : INFO : < 200 OK [1451]
2017-12-31 21:31:03,935 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 651, 'name': 'Introduction to People Analytics'}}
2017-12-31 21:31:03,938 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:31:03,944 : INFO : < 200 OK [1436]
2017-12-31 21:31:03,948 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 652, 'name': 'Command Line Tools for Genomic Data Science'}}
2017-12-31 21:31:03,952 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:31:03,957 : INFO : < 200 OK [1447]
2017-12-31 21:31:03,963 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 653, 'level': 'Beginner', 'name': 'Math behind Moneyball'}}
2017-12-31 21:31:03,966 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:31:03,972 : INFO : < 200 OK [1454]
2017-12-31 21:31:03,978 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.9', 'id': 655, 'name': 'Bioconductor for Genomic Data Science'}}
2017-12-31 21:31:03,982 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2017-12-31 21:31:03,988 : INFO : < 200 OK [1441]
2017-12-31 21:31:03,993 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 656, 'name': 'Understanding China, 1700-2000: A Data Analytic Approach, Part 1'}}
2017-12-31 21:31:03,997 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2017-12-31 21:31:04,003 : INFO : < 200 OK [1468]
2017-12-31 21:31:04,008 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 657, 'name': 'Principles of fMRI 2'}}
2017-12-31 21:31:04,012 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2017-12-31 21:31:04,018 : INFO : < 200 OK [1424]
2017-12-31 21:31:04,023 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 658, 'name': 'Communicating Business Analytics Results'}}
2017-12-31 21:31:04,027 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:31:04,033 : INFO : < 200 OK [1444]
2017-12-31 21:31:04,038 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.0', 'id': 659, 'level': 'Beginner', 'name': 'Business Analytics and Digital Media'}}
2017-12-31 21:31:04,041 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:31:04,048 : INFO : < 200 OK [1469]
2017-12-31 21:31:04,052 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.8', 'id': 660, 'name': 'Dealing With Missing Data'}}
2017-12-31 21:31:04,056 : INFO : > POST http://localhost:7474/db/data/cypher [123]
2017-12-31 21:31:04,062 : INFO : < 200 OK [1429]
2017-12-31 21:31:04,067 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.5', 'id': 662, 'name': 'Communicating Data Science Results'}}
2017-12-31 21:31:04,070 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:31:04,076 : INFO : < 200 OK [1438]
2017-12-31 21:31:04,080 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 663, 'level': 'Intermediate', 'name': 'Materials Data Sciences and Informatics'}}
2017-12-31 21:31:04,084 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2017-12-31 21:31:04,090 : INFO : < 200 OK [1476]
2017-12-31 21:31:04,094 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 664, 'name': 'Case studies in business analytics with ACCENTURE'}}
2017-12-31 21:31:04,098 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:31:04,105 : INFO : < 200 OK [1428]

2017-12-31 21:31:04,109 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 665, 'name': 'Interprofessional Healthcare Informatics '}}
2017-12-31 21:31:04,113 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:31:04,119 : INFO : < 200 OK [1445]
2017-12-31 21:31:04,123 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 666, 'name': 'Business Statistics and Analysis Capstone'}}
2017-12-31 21:31:04,127 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:31:04,133 : INFO : < 200 OK [1445]
2017-12-31 21:31:04,138 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 846, 'level': 'Advanced', 'name': 'Big Data Applications: Real-Time Streaming'}}
2017-12-31 21:31:04,142 : INFO : > POST http://localhost:7474/db/data/cypher [144]
2017-12-31 21:31:04,148 : INFO : < 200 OK [1450]
2017-12-31 21:31:04,153 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 669, 'name': 'Combining and Analyzing Complex Data'}}
2017-12-31 21:31:04,156 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:31:04,162 : INFO : < 200 OK [1440]
2017-12-31 21:31:04,167 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 670, 'level': 'Intermediate', 'name': 'Biological Diversity (Theories, Measures and Data sampling techniques)'}}
2017-12-31 21:31:04,171 : INFO : > POST http://localhost:7474/db/data/cypher [191]
2017-12-31 21:31:04,177 : INFO : < 200 OK [1507]
2017-12-31 21:31:04,182 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 672, 'name': 'Executive Data Science Capstone'}}
2017-12-31 21:31:04,186 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2017-12-31 21:31:04,193 : INFO : < 200 OK [1435]
2017-12-31 21:31:04,197 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 673, 'level': 'Beginner', 'name': 'Geodesign: Change Your World'}}
2017-12-31 21:31:04,201 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:31:04,208 : INFO : < 200 OK [1461]
2017-12-31 21:31:04,214 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 674, 'name': 'Wharton Business and Financial Modeling Capstone'}}
2017-12-31 21:31:04,217 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2017-12-31 21:31:04,224 : INFO : < 200 OK [1452]
2017-12-31 21:31:04,229 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 675, 'level': 'Intermediate', 'name': 'Big Data Science with the BD2K-LINCS Data Coordination and Integration Center'}}
2017-12-31 21:31:04,232 : INFO : > POST http://localhost:7474/db/data/cypher [198]
2017-12-31 21:31:04,238 : INFO : < 200 OK [1514]
2017-12-31 21:31:04,242 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 676, 'name': 'Understanding China, 1700-2000: A Data Analytic Approach, Part 2'}}
2017-12-31 21:31:04,246 : INFO : > POST http://localhost:7474/db/data/cypher [162]
2017-12-31 21:31:04,252 : INFO : < 200 OK [1468]
2017-12-31 21:31:04,256 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 677, 'level': 'Beginner', 'name': 'Social Science Approaches to the Study of Chinese Society Part 1'}}
2017-12-31 21:31:04,259 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:04,265 : INFO : < 200 OK [1497]
2017-12-31 21:31:04,270 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 678, 'level': 'Intermediate', 'name': 'Data Visualization with Tableau Project'}}
2017-12-31 21:31:04,273 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2017-12-31 21:31:04,280 : INFO : < 200 OK [1476]
2017-12-31 21:31:04,285 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 679, 'name': 'Data Analytics Foundations for Accountancy I'}}
2017-12-31 21:31:04,289 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:31:04,296 : INFO : < 200 OK [1423]
2017-12-31 21:31:04,301 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 681, 'name': 'Increasing Real Estate Management Profits: Harnessing Data Analytics'}}
2017-12-31 21:31:04,304 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2017-12-31 21:31:04,311 : INFO : < 200 OK [1472]
2017-12-31 21:31:04,315 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 682, 'level': 'Beginner', 'name': 'Social Science Approaches to the Study of Chinese Society Part 2'}}
2017-12-31 21:31:04,318 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2017-12-31 21:31:04,324 : INFO : < 200 OK [1472]
2017-12-31 21:31:04,329 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 872, 'name': 'Data Mining Project'}}
2017-12-31 21:31:04,332 : INFO : > POST http://localhost:7474/db/data/cypher [117]
2017-12-31 21:31:04,338 : INFO : < 200 OK [1423]
2017-12-31 21:31:04,343 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 684, 'name': 'Data Science at Scale - Capstone Project'}}
2017-12-31 21:31:04,346 : INFO : > POST http://localhost:7474/db/data/cypher [138]
2017-12-31 21:31:04,352 : INFO : < 200 OK [1444]
2017-12-31 21:31:04,357 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 685, 'level': 'Intermediate', 'name': 'Business Analytics Capstone'}}
2017-12-31 21:31:04,361 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:31:04,367 : INFO : < 200 OK [1464]
2017-12-31 21:31:04,371 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 686, 'name': 'Big Data - Capstone Project'}}
2017-12-31 21:31:04,375 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2017-12-31 21:31:04,381 : INFO : < 200 OK [1431]
2017-12-31 21:31:04,385 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 687, 'level': 'Beginner', 'name': 'Data Analysis and Presentation Skills: the PwC Approach Final Project'}}
2017-12-31 21:31:04,389 : INFO : > POST http://localhost:7474/db/data/cypher [186]
2017-12-31 21:31:04,395 : INFO : < 200 OK [1502]
2017-12-31 21:31:04,400 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 688, 'name': 'Design and Build a Data Warehouse for Business Intelligence Implementation'}}
2017-12-31 21:31:04,403 : INFO : > POST http://localhost:7474/db/data/cypher [172]
2017-12-31 21:31:04,410 : INFO : < 200 OK [1478]
2017-12-31 21:31:04,415 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 689, 'name': 'Capstone: Analyzing (Social) Network Data'}}
2017-12-31 21:31:04,418 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:31:04,425 : INFO : < 200 OK [1445]
2017-12-31 21:31:04,429 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.6', 'id': 690, 'name': 'Capstone:  Create Value from Open Data'}}
2017-12-31 21:31:04,433 : INFO : > POST http://localhost:7474/db/data/cypher [136]
2017-12-31 21:31:04,439 : INFO : < 200 OK [1442]
2017-12-31 21:31:04,444 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 691, 'name': 'Genomic Data Science Capstone'}}
2017-12-31 21:31:04,447 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:31:04,452 : INFO : < 200 OK [1433]
2017-12-31 21:31:04,457 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 692, 'name': 'Data Analysis and Interpretation Capstone'}}
2017-12-31 21:31:04,460 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:31:04,468 : INFO : < 200 OK [1445]
2017-12-31 21:31:04,473 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 693, 'name': 'Geospatial Analysis Project'}}
2017-12-31 21:31:04,476 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2017-12-31 21:31:04,482 : INFO : < 200 OK [1431]

2017-12-31 21:31:04,486 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.1', 'id': 876, 'level': 'Intermediate', 'name': 'Mastering Software Development in R Capstone'}}
2017-12-31 21:31:04,489 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:31:04,495 : INFO : < 200 OK [1481]
2017-12-31 21:31:04,500 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 695, 'name': 'Advanced Business Analytics Capstone'}}
2017-12-31 21:31:04,503 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:31:04,509 : INFO : < 200 OK [1440]
2017-12-31 21:31:04,514 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 697, 'name': 'Programming for Everybody (Getting Started with Python)'}}
2017-12-31 21:31:04,518 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:31:04,525 : INFO : < 200 OK [1459]
2017-12-31 21:31:04,531 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 698, 'level': 'Intermediate', 'name': 'IBM Blockchain Foundation for Developers'}}
2017-12-31 21:31:04,534 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2017-12-31 21:31:04,541 : INFO : < 200 OK [1477]
2017-12-31 21:31:04,547 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 703, 'level': 'Beginner', 'name': 'Introduction to Programming with MATLAB'}}
2017-12-31 21:31:04,550 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2017-12-31 21:31:04,556 : INFO : < 200 OK [1472]
2017-12-31 21:31:04,561 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 704, 'name': 'Using Python to Access Web Data'}}
2017-12-31 21:31:04,564 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2017-12-31 21:31:04,570 : INFO : < 200 OK [1435]
2017-12-31 21:31:04,574 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 705, 'level': 'Beginner', 'name': 'Learn to Program: The Fundamentals'}}
2017-12-31 21:31:04,578 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2017-12-31 21:31:04,583 : INFO : < 200 OK [1467]
2017-12-31 21:31:04,587 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 708, 'level': 'Intermediate', 'name': 'Object Oriented Programming in Java'}}
2017-12-31 21:31:04,591 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2017-12-31 21:31:04,596 : INFO : < 200 OK [1472]
2017-12-31 21:31:04,601 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 710, 'level': 'Beginner', 'name': 'Python Programming: A Concise Introduction'}}
2017-12-31 21:31:04,604 : INFO : > POST http://localhost:7474/db/data/cypher [159]
2017-12-31 21:31:04,611 : INFO : < 200 OK [1475]
2017-12-31 21:31:04,615 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 712, 'level': 'Intermediate', 'name': 'Functional Programming Principles in Scala'}}
2017-12-31 21:31:04,621 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2017-12-31 21:31:04,627 : INFO : < 200 OK [1479]
2017-12-31 21:31:04,632 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.3', 'id': 715, 'name': 'C++ For C Programmers, Part A'}}
2017-12-31 21:31:04,636 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:31:04,642 : INFO : < 200 OK [1433]
2017-12-31 21:31:04,647 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 716, 'level': 'Beginner', 'name': 'Java Programming: Solving Problems with Software'}}
2017-12-31 21:31:04,650 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:31:04,657 : INFO : < 200 OK [1481]
2017-12-31 21:31:04,661 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 719, 'level': 'Beginner', 'name': 'Biology Meets Programming: Bioinformatics for Beginners'}}
2017-12-31 21:31:04,665 : INFO : > POST http://localhost:7474/db/data/cypher [172]
2017-12-31 21:31:04,671 : INFO : < 200 OK [1488]
2017-12-31 21:31:04,675 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 725, 'name': 'Code Yourself! An Introduction to Programming'}}
2017-12-31 21:31:04,679 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2017-12-31 21:31:04,684 : INFO : < 200 OK [1449]
2017-12-31 21:31:04,689 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 727, 'level': 'Beginner', 'name': 'Digital Product Management: Modern Fundamentals'}}
2017-12-31 21:31:04,692 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2017-12-31 21:31:04,698 : INFO : < 200 OK [1480]
2017-12-31 21:31:04,702 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 730, 'name': 'Beginning Game Programming with C#'}}
2017-12-31 21:31:04,706 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:31:04,711 : INFO : < 200 OK [1438]
2017-12-31 21:31:04,716 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 731, 'level': 'Intermediate', 'name': 'The Finite Element Method for Problems in Physics'}}
2017-12-31 21:31:04,719 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2017-12-31 21:31:04,725 : INFO : < 200 OK [1486]
2017-12-31 21:31:04,730 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 735, 'level': 'Intermediate', 'name': 'Object-Oriented Design'}}
2017-12-31 21:31:04,734 : INFO : > POST http://localhost:7474/db/data/cypher [143]
2017-12-31 21:31:04,740 : INFO : < 200 OK [1459]
2017-12-31 21:31:04,745 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 745, 'name': 'Introduction to Game Development'}}
2017-12-31 21:31:04,750 : INFO : > POST http://localhost:7474/db/data/cypher [130]
2017-12-31 21:31:04,756 : INFO : < 200 OK [1436]
2017-12-31 21:31:04,761 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 746, 'level': 'Intermediate', 'name': 'Parallel Programming in Java'}}
2017-12-31 21:31:04,765 : INFO : > POST http://localhost:7474/db/data/cypher [149]
2017-12-31 21:31:04,771 : INFO : < 200 OK [1465]
2017-12-31 21:31:04,775 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 747, 'name': 'The Raspberry Pi Platform and Python Programming for the Raspberry Pi'}}
2017-12-31 21:31:04,780 : INFO : > POST http://localhost:7474/db/data/cypher [167]
2017-12-31 21:31:04,786 : INFO : < 200 OK [1473]
2017-12-31 21:31:04,790 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 751, 'level': 'Beginner', 'name': 'Java Programming: Arrays, Lists, and Structured Data'}}
2017-12-31 21:31:04,794 : INFO : > POST http://localhost:7474/db/data/cypher [169]
2017-12-31 21:31:04,800 : INFO : < 200 OK [1485]
2017-12-31 21:31:04,805 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '3.7', 'id': 752, 'level': 'Intermediate', 'name': 'Embedded Hardware and Operating Systems'}}
2017-12-31 21:31:04,808 : INFO : > POST http://localhost:7474/db/data/cypher [160]
2017-12-31 21:31:04,814 : INFO : < 200 OK [1476]
2017-12-31 21:31:04,819 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 757, 'name': 'Learn to Program: Crafting Quality Code'}}
2017-12-31 21:31:04,822 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:31:04,828 : INFO : < 200 OK [1443]
2017-12-31 21:31:04,833 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 758, 'level': 'Intermediate', 'name': 'Functional Program Design in Scala'}}
2017-12-31 21:31:04,837 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2017-12-31 21:31:04,843 : INFO : < 200 OK [1471]
2017-12-31 21:31:04,847 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 759, 'level': 'Intermediate', 'name': 'Audio Signal Processing for Music Applications'}}
2017-12-31 21:31:04,851 : INFO : > POST http://localhost:7474/db/data/cypher [167]

2017-12-31 21:31:04,857 : INFO : < 200 OK [1483]
2017-12-31 21:31:04,861 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 763, 'level': 'Intermediate', 'name': "A Developer's guide to Node-RED"}}
2017-12-31 21:31:04,865 : INFO : > POST http://localhost:7474/db/data/cypher [137]
2017-12-31 21:31:04,871 : INFO : < 200 OK [1443]
2017-12-31 21:31:04,875 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 764, 'level': 'Intermediate', 'name': 'Parallel programming'}}
2017-12-31 21:31:04,879 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:31:04,885 : INFO : < 200 OK [1457]
2017-12-31 21:31:04,889 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 767, 'level': 'Beginner', 'name': 'Java Programming: Principles of Software Design'}}
2017-12-31 21:31:04,893 : INFO : > POST http://localhost:7474/db/data/cypher [164]
2017-12-31 21:31:04,898 : INFO : < 200 OK [1480]
2017-12-31 21:31:04,902 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.4', 'id': 774, 'level': 'Intermediate', 'name': 'Distributed Programming in Java'}}
2017-12-31 21:31:04,906 : INFO : > POST http://localhost:7474/db/data/cypher [152]
2017-12-31 21:31:04,912 : INFO : < 200 OK [1468]
2017-12-31 21:31:04,916 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 780, 'level': 'Intermediate', 'name': 'Concurrent Programming in Java'}}
2017-12-31 21:31:04,920 : INFO : > POST http://localhost:7474/db/data/cypher [151]
2017-12-31 21:31:04,926 : INFO : < 200 OK [1467]
2017-12-31 21:31:04,930 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.9', 'id': 783, 'name': 'Build a Modern Computer from First Principles: Nand to Tetris Part II (project-centered course)'}}
2017-12-31 21:31:04,933 : INFO : > POST http://localhost:7474/db/data/cypher [193]
2017-12-31 21:31:04,939 : INFO : < 200 OK [1499]
2017-12-31 21:31:04,943 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 784, 'name': 'C++ For C Programmers, Part B'}}
2017-12-31 21:31:04,947 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:31:04,953 : INFO : < 200 OK [1433]
2017-12-31 21:31:04,958 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 785, 'level': 'Intermediate', 'name': 'Mastering the Software Engineering Interview'}}
2017-12-31 21:31:04,962 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:31:04,970 : INFO : < 200 OK [1481]
2017-12-31 21:31:04,975 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 805, 'level': 'Beginner', 'name': 'Requirements Gathering for Secure Software Development'}}
2017-12-31 21:31:04,980 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2017-12-31 21:31:04,989 : INFO : < 200 OK [1462]
2017-12-31 21:31:04,995 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 810, 'level': 'Beginner', 'name': 'Software Development Processes and Methodologies'}}
2017-12-31 21:31:04,998 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:31:05,004 : INFO : < 200 OK [1481]
2017-12-31 21:31:05,009 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '2.0', 'id': 812, 'level': 'Intermediate', 'name': 'Fundamentals of Parallelism on Intel Architecture'}}
2017-12-31 21:31:05,012 : INFO : > POST http://localhost:7474/db/data/cypher [170]
2017-12-31 21:31:05,018 : INFO : < 200 OK [1486]
2017-12-31 21:31:05,022 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.8', 'id': 820, 'name': 'Game Development for Modern Platforms'}}
2017-12-31 21:31:05,026 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2017-12-31 21:31:05,032 : INFO : < 200 OK [1441]
2017-12-31 21:31:05,036 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 826, 'name': 'Creative Programming for Digital Media & Mobile Apps'}}
2017-12-31 21:31:05,040 : INFO : > POST http://localhost:7474/db/data/cypher [150]
2017-12-31 21:31:05,046 : INFO : < 200 OK [1456]
2017-12-31 21:31:05,050 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.2', 'id': 831, 'name': 'Software Architecture for the Internet of Things'}}
2017-12-31 21:31:05,053 : INFO : > POST http://localhost:7474/db/data/cypher [146]
2017-12-31 21:31:05,059 : INFO : < 200 OK [1452]
2017-12-31 21:31:05,064 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '1.0', 'id': 836, 'level': 'Beginner', 'name': 'Lean Software Development'}}
2017-12-31 21:31:05,067 : INFO : > POST http://localhost:7474/db/data/cypher [142]
2017-12-31 21:31:05,073 : INFO : < 200 OK [1458]
2017-12-31 21:31:05,078 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 838, 'level': 'Beginner', 'name': 'SRS Documents: Requirements and Diagrammatic Notations'}}
2017-12-31 21:31:05,083 : INFO : > POST http://localhost:7474/db/data/cypher [156]
2017-12-31 21:31:05,090 : INFO : < 200 OK [1462]
2017-12-31 21:31:05,096 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 839, 'name': 'Software Design as an Element of the Software Development Lifecycle'}}
2017-12-31 21:31:05,101 : INFO : > POST http://localhost:7474/db/data/cypher [165]
2017-12-31 21:31:05,108 : INFO : < 200 OK [1471]
2017-12-31 21:31:05,114 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.5', 'id': 842, 'level': 'Intermediate', 'name': 'Quantitative Model Checking'}}
2017-12-31 21:31:05,118 : INFO : > POST http://localhost:7474/db/data/cypher [148]
2017-12-31 21:31:05,124 : INFO : < 200 OK [1464]
2017-12-31 21:31:05,130 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 843, 'level': 'Intermediate', 'name': 'Software Design Methods and Tools'}}
2017-12-31 21:31:05,135 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:31:05,142 : INFO : < 200 OK [1445]
2017-12-31 21:31:05,149 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 844, 'level': 'Beginner', 'name': 'Requirements Elicitation: Artifact and Stakeholder Analysis'}}
2017-12-31 21:31:05,152 : INFO : > POST http://localhost:7474/db/data/cypher [161]
2017-12-31 21:31:05,159 : INFO : < 200 OK [1467]
2017-12-31 21:31:05,167 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 845, 'level': 'Beginner', 'name': 'Software Requirements Prioritization: Risk Analysis'}}
2017-12-31 21:31:05,171 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:31:05,180 : INFO : < 200 OK [1459]
2017-12-31 21:31:05,186 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 847, 'level': 'Beginner', 'name': 'Requirements Specifications: Goals and Conflict Analysis'}}
2017-12-31 21:31:05,190 : INFO : > POST http://localhost:7474/db/data/cypher [158]
2017-12-31 21:31:05,199 : INFO : < 200 OK [1464]
2017-12-31 21:31:05,204 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 850, 'level': 'Intermediate', 'name': 'Software Design as an Abstraction'}}
2017-12-31 21:31:05,208 : INFO : > POST http://localhost:7474/db/data/cypher [139]
2017-12-31 21:31:05,216 : INFO : < 200 OK [1445]
2017-12-31 21:31:05,221 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 852, 'level': 'Intermediate', 'name': 'Software Design Threats and Mitigations'}}
2017-12-31 21:31:05,225 : INFO : > POST http://localhost:7474/db/data/cypher [145]
2017-12-31 21:31:05,231 : INFO : < 200 OK [1451]
2017-12-31 21:31:05,236 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.6', 'id': 858, 'name': 'Games, Sensors and Media'}}
2017-12-31 21:31:05,241 : INFO : > POST http://localhost:7474/db/data/cypher [122]
2017-12-31 21:31:05,248 : INFO : < 200 OK [1428]
2017-12-31 21:31:05,254 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 859, 'name': 'Malicious Software and its Underground Economy: Two Sides to Every Story'}}
2017-12-31 21:31:05,259 : INFO : > POST http://localhost:7474/db/data/cypher [155]
2017-12-31 21:31:05,266 : INFO : < 200 OK [1451]

2017-12-31 21:31:05,271 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '5.0', 'id': 861, 'level': 'Advanced', 'name': 'Capstone:  Autonomous Runway Detection for IoT'}}
2017-12-31 21:31:05,276 : INFO : > POST http://localhost:7474/db/data/cypher [163]
2017-12-31 21:31:05,283 : INFO : < 200 OK [1479]
2017-12-31 21:31:05,288 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'id': 866, 'name': 'Engineering Practices for Building Quality Software'}}
2017-12-31 21:31:05,292 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:31:05,300 : INFO : < 200 OK [1430]
2017-12-31 21:31:05,306 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 873, 'level': 'Intermediate', 'name': 'Java Programming: Build a Recommendation System'}}
2017-12-31 21:31:05,309 : INFO : > POST http://localhost:7474/db/data/cypher [168]
2017-12-31 21:31:05,316 : INFO : < 200 OK [1484]
2017-12-31 21:31:05,321 : INFO : execute 'CREATE (_0:Course {_0})\nRETURN _0' {'_0': {'rating': '4.7', 'id': 875, 'name': 'Game Design and Development Capstone'}}
2017-12-31 21:31:05,324 : INFO : > POST http://localhost:7474/db/data/cypher [134]
2017-12-31 21:31:05,331 : INFO : < 200 OK [1440]

In [76]:
for i, row in data.drop_duplicates(subset=['category', 'uid']).iterrows():
    graph.create(Relationship(course_dict[row.uid], 'belong to', cat_dict[row.category]))

2017-12-31 21:31:05,626 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 1012}
2017-12-31 21:31:05,632 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:05,640 : INFO : < 200 OK [3305]
2017-12-31 21:31:05,648 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 987}
2017-12-31 21:31:05,652 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:05,659 : INFO : < 200 OK [3279]
2017-12-31 21:31:05,666 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 1013}
2017-12-31 21:31:05,671 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:05,678 : INFO : < 200 OK [3356]
2017-12-31 21:31:05,684 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 988}
2017-12-31 21:31:05,688 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:05,694 : INFO : < 200 OK [3326]
2017-12-31 21:31:05,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 1014}
2017-12-31 21:31:05,704 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:05,711 : INFO : < 200 OK [3281]
2017-12-31 21:31:05,716 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 989}
2017-12-31 21:31:05,720 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:05,727 : INFO : < 200 OK [3333]
2017-12-31 21:31:05,732 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 0}
2017-12-31 21:31:05,736 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:05,742 : INFO : < 200 OK [3283]
2017-12-31 21:31:05,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 990}
2017-12-31 21:31:05,750 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:05,756 : INFO : < 200 OK [3321]
2017-12-31 21:31:05,761 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 1}
2017-12-31 21:31:05,764 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:05,770 : INFO : < 200 OK [3274]
2017-12-31 21:31:05,775 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 991}
2017-12-31 21:31:05,778 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:05,784 : INFO : < 200 OK [3340]
2017-12-31 21:31:05,789 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 2}
2017-12-31 21:31:05,794 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:05,800 : INFO : < 200 OK [3240]
2017-12-31 21:31:05,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 992}
2017-12-31 21:31:05,810 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:05,818 : INFO : < 200 OK [3343]
2017-12-31 21:31:05,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 3}
2017-12-31 21:31:05,828 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:05,834 : INFO : < 200 OK [3251]
2017-12-31 21:31:05,841 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 993}
2017-12-31 21:31:05,846 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:05,853 : INFO : < 200 OK [3339]
2017-12-31 21:31:05,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 4}
2017-12-31 21:31:05,863 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:05,869 : INFO : < 200 OK [3308]
2017-12-31 21:31:05,874 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 994}
2017-12-31 21:31:05,878 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:05,884 : INFO : < 200 OK [3328]
2017-12-31 21:31:05,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 5}
2017-12-31 21:31:05,893 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:05,899 : INFO : < 200 OK [3309]
2017-12-31 21:31:05,904 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 995}
2017-12-31 21:31:05,908 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:05,914 : INFO : < 200 OK [3334]
2017-12-31 21:31:05,919 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 6}
2017-12-31 21:31:05,923 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:05,929 : INFO : < 200 OK [3292]
2017-12-31 21:31:05,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 12}
2017-12-31 21:31:05,938 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:05,944 : INFO : < 200 OK [3353]
2017-12-31 21:31:05,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 7}
2017-12-31 21:31:05,953 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:05,958 : INFO : < 200 OK [3229]
2017-12-31 21:31:05,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 13}
2017-12-31 21:31:05,967 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:05,973 : INFO : < 200 OK [3321]
2017-12-31 21:31:05,978 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 8}
2017-12-31 21:31:05,982 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:05,987 : INFO : < 200 OK [3324]
2017-12-31 21:31:05,992 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 14}
2017-12-31 21:31:05,996 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,001 : INFO : < 200 OK [3326]

2017-12-31 21:31:06,006 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 9}
2017-12-31 21:31:06,009 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:06,015 : INFO : < 200 OK [3278]
2017-12-31 21:31:06,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 15}
2017-12-31 21:31:06,023 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,029 : INFO : < 200 OK [3283]
2017-12-31 21:31:06,034 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 10}
2017-12-31 21:31:06,037 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,043 : INFO : < 200 OK [3283]
2017-12-31 21:31:06,048 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 16}
2017-12-31 21:31:06,052 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,058 : INFO : < 200 OK [3311]
2017-12-31 21:31:06,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 11}
2017-12-31 21:31:06,072 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,080 : INFO : < 200 OK [3253]
2017-12-31 21:31:06,086 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 17}
2017-12-31 21:31:06,089 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,096 : INFO : < 200 OK [3319]
2017-12-31 21:31:06,103 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 32}
2017-12-31 21:31:06,106 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,114 : INFO : < 200 OK [3317]
2017-12-31 21:31:06,119 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 18}
2017-12-31 21:31:06,123 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,129 : INFO : < 200 OK [3318]
2017-12-31 21:31:06,134 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 33}
2017-12-31 21:31:06,138 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,143 : INFO : < 200 OK [3295]
2017-12-31 21:31:06,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 19}
2017-12-31 21:31:06,152 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,158 : INFO : < 200 OK [3328]
2017-12-31 21:31:06,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 34}
2017-12-31 21:31:06,166 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,172 : INFO : < 200 OK [3313]
2017-12-31 21:31:06,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 20}
2017-12-31 21:31:06,180 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,186 : INFO : < 200 OK [3265]
2017-12-31 21:31:06,191 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 35}
2017-12-31 21:31:06,195 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,202 : INFO : < 200 OK [3324]
2017-12-31 21:31:06,208 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 21}
2017-12-31 21:31:06,213 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,218 : INFO : < 200 OK [3320]
2017-12-31 21:31:06,224 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 36}
2017-12-31 21:31:06,227 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,233 : INFO : < 200 OK [3258]
2017-12-31 21:31:06,239 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 22}
2017-12-31 21:31:06,243 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,249 : INFO : < 200 OK [3303]
2017-12-31 21:31:06,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 37}
2017-12-31 21:31:06,258 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,264 : INFO : < 200 OK [3286]
2017-12-31 21:31:06,269 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 23}
2017-12-31 21:31:06,273 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,279 : INFO : < 200 OK [3267]
2017-12-31 21:31:06,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 38}
2017-12-31 21:31:06,287 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,293 : INFO : < 200 OK [3305]
2017-12-31 21:31:06,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 24}
2017-12-31 21:31:06,301 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,307 : INFO : < 200 OK [3302]
2017-12-31 21:31:06,312 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 39}
2017-12-31 21:31:06,315 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,321 : INFO : < 200 OK [3270]
2017-12-31 21:31:06,326 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 25}
2017-12-31 21:31:06,329 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,335 : INFO : < 200 OK [3300]
2017-12-31 21:31:06,340 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 40}
2017-12-31 21:31:06,344 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,351 : INFO : < 200 OK [3312]
2017-12-31 21:31:06,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 26}
2017-12-31 21:31:06,362 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,368 : INFO : < 200 OK [3284]

2017-12-31 21:31:06,373 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 41}
2017-12-31 21:31:06,377 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,383 : INFO : < 200 OK [3314]
2017-12-31 21:31:06,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 27}
2017-12-31 21:31:06,392 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,398 : INFO : < 200 OK [3296]
2017-12-31 21:31:06,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 42}
2017-12-31 21:31:06,407 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,413 : INFO : < 200 OK [3312]
2017-12-31 21:31:06,418 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 28}
2017-12-31 21:31:06,422 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,428 : INFO : < 200 OK [3321]
2017-12-31 21:31:06,433 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 43}
2017-12-31 21:31:06,437 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,443 : INFO : < 200 OK [3287]
2017-12-31 21:31:06,448 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 29}
2017-12-31 21:31:06,452 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,459 : INFO : < 200 OK [3331]
2017-12-31 21:31:06,465 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 44}
2017-12-31 21:31:06,468 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,474 : INFO : < 200 OK [3317]
2017-12-31 21:31:06,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 30}
2017-12-31 21:31:06,483 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,488 : INFO : < 200 OK [3262]
2017-12-31 21:31:06,493 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 45}
2017-12-31 21:31:06,497 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,502 : INFO : < 200 OK [3276]
2017-12-31 21:31:06,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 31}
2017-12-31 21:31:06,511 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,516 : INFO : < 200 OK [3272]
2017-12-31 21:31:06,521 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 46}
2017-12-31 21:31:06,524 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,530 : INFO : < 200 OK [3320]
2017-12-31 21:31:06,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 52}
2017-12-31 21:31:06,540 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,546 : INFO : < 200 OK [3289]
2017-12-31 21:31:06,553 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 47}
2017-12-31 21:31:06,556 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,563 : INFO : < 200 OK [3330]
2017-12-31 21:31:06,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 53}
2017-12-31 21:31:06,573 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,579 : INFO : < 200 OK [3292]
2017-12-31 21:31:06,584 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 48}
2017-12-31 21:31:06,587 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,602 : INFO : < 200 OK [3323]
2017-12-31 21:31:06,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 54}
2017-12-31 21:31:06,612 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,617 : INFO : < 200 OK [3298]
2017-12-31 21:31:06,622 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 49}
2017-12-31 21:31:06,627 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,633 : INFO : < 200 OK [3271]
2017-12-31 21:31:06,638 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 55}
2017-12-31 21:31:06,642 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,650 : INFO : < 200 OK [3293]
2017-12-31 21:31:06,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 50}
2017-12-31 21:31:06,659 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,667 : INFO : < 200 OK [3296]
2017-12-31 21:31:06,673 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 56}
2017-12-31 21:31:06,679 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,685 : INFO : < 200 OK [3319]
2017-12-31 21:31:06,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 51}
2017-12-31 21:31:06,696 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,702 : INFO : < 200 OK [3303]
2017-12-31 21:31:06,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 57}
2017-12-31 21:31:06,714 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,722 : INFO : < 200 OK [3346]
2017-12-31 21:31:06,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 72}
2017-12-31 21:31:06,733 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,739 : INFO : < 200 OK [3267]
2017-12-31 21:31:06,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 58}
2017-12-31 21:31:06,750 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,756 : INFO : < 200 OK [3344]

2017-12-31 21:31:06,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 73}
2017-12-31 21:31:06,768 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,774 : INFO : < 200 OK [3332]
2017-12-31 21:31:06,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 59}
2017-12-31 21:31:06,785 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,790 : INFO : < 200 OK [3285]
2017-12-31 21:31:06,795 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 74}
2017-12-31 21:31:06,799 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,805 : INFO : < 200 OK [3312]
2017-12-31 21:31:06,810 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 60}
2017-12-31 21:31:06,814 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,819 : INFO : < 200 OK [3300]
2017-12-31 21:31:06,825 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 75}
2017-12-31 21:31:06,830 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,836 : INFO : < 200 OK [3273]
2017-12-31 21:31:06,841 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 61}
2017-12-31 21:31:06,847 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,853 : INFO : < 200 OK [3332]
2017-12-31 21:31:06,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 76}
2017-12-31 21:31:06,863 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,871 : INFO : < 200 OK [3335]
2017-12-31 21:31:06,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 62}
2017-12-31 21:31:06,880 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,887 : INFO : < 200 OK [3264]
2017-12-31 21:31:06,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 77}
2017-12-31 21:31:06,896 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:06,904 : INFO : < 200 OK [3309]
2017-12-31 21:31:06,909 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 63}
2017-12-31 21:31:06,914 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,048 : INFO : < 200 OK [3304]
2017-12-31 21:31:07,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 974, '_0n0': 78}
2017-12-31 21:31:07,057 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,064 : INFO : < 200 OK [3290]
2017-12-31 21:31:07,069 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 64}
2017-12-31 21:31:07,073 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,079 : INFO : < 200 OK [3288]
2017-12-31 21:31:07,084 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 80}
2017-12-31 21:31:07,088 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,093 : INFO : < 200 OK [3284]
2017-12-31 21:31:07,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 65}
2017-12-31 21:31:07,102 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,108 : INFO : < 200 OK [3337]
2017-12-31 21:31:07,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 81}
2017-12-31 21:31:07,117 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,123 : INFO : < 200 OK [3273]
2017-12-31 21:31:07,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 66}
2017-12-31 21:31:07,135 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,141 : INFO : < 200 OK [3274]
2017-12-31 21:31:07,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 82}
2017-12-31 21:31:07,150 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,164 : INFO : < 200 OK [3245]
2017-12-31 21:31:07,170 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 67}
2017-12-31 21:31:07,174 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,180 : INFO : < 200 OK [3323]
2017-12-31 21:31:07,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 83}
2017-12-31 21:31:07,189 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,195 : INFO : < 200 OK [3283]
2017-12-31 21:31:07,200 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 68}
2017-12-31 21:31:07,204 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,209 : INFO : < 200 OK [3274]
2017-12-31 21:31:07,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 84}
2017-12-31 21:31:07,218 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,224 : INFO : < 200 OK [3269]
2017-12-31 21:31:07,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 69}
2017-12-31 21:31:07,233 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,238 : INFO : < 200 OK [3313]
2017-12-31 21:31:07,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 85}
2017-12-31 21:31:07,247 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,253 : INFO : < 200 OK [3275]
2017-12-31 21:31:07,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 70}
2017-12-31 21:31:07,262 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,268 : INFO : < 200 OK [3282]

2017-12-31 21:31:07,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 86}
2017-12-31 21:31:07,276 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,282 : INFO : < 200 OK [3272]
2017-12-31 21:31:07,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 71}
2017-12-31 21:31:07,290 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,296 : INFO : < 200 OK [3299]
2017-12-31 21:31:07,301 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 87}
2017-12-31 21:31:07,304 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,310 : INFO : < 200 OK [3267]
2017-12-31 21:31:07,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 93}
2017-12-31 21:31:07,318 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,324 : INFO : < 200 OK [3252]
2017-12-31 21:31:07,329 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 88}
2017-12-31 21:31:07,332 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,338 : INFO : < 200 OK [3260]
2017-12-31 21:31:07,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 94}
2017-12-31 21:31:07,346 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,352 : INFO : < 200 OK [3286]
2017-12-31 21:31:07,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 89}
2017-12-31 21:31:07,360 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,366 : INFO : < 200 OK [3304]
2017-12-31 21:31:07,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 95}
2017-12-31 21:31:07,375 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,381 : INFO : < 200 OK [3275]
2017-12-31 21:31:07,386 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 90}
2017-12-31 21:31:07,390 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,397 : INFO : < 200 OK [3264]
2017-12-31 21:31:07,402 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 96}
2017-12-31 21:31:07,406 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,412 : INFO : < 200 OK [3321]
2017-12-31 21:31:07,417 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 91}
2017-12-31 21:31:07,420 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,428 : INFO : < 200 OK [3275]
2017-12-31 21:31:07,434 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 97}
2017-12-31 21:31:07,438 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,446 : INFO : < 200 OK [3300]
2017-12-31 21:31:07,451 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 92}
2017-12-31 21:31:07,455 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,461 : INFO : < 200 OK [3276]
2017-12-31 21:31:07,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 98}
2017-12-31 21:31:07,470 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,477 : INFO : < 200 OK [3279]
2017-12-31 21:31:07,482 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 113}
2017-12-31 21:31:07,486 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,493 : INFO : < 200 OK [3295]
2017-12-31 21:31:07,498 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 99}
2017-12-31 21:31:07,501 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,507 : INFO : < 200 OK [3284]
2017-12-31 21:31:07,513 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 114}
2017-12-31 21:31:07,517 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,523 : INFO : < 200 OK [3287]
2017-12-31 21:31:07,528 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 100}
2017-12-31 21:31:07,531 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,537 : INFO : < 200 OK [3300]
2017-12-31 21:31:07,542 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 115}
2017-12-31 21:31:07,546 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,553 : INFO : < 200 OK [3301]
2017-12-31 21:31:07,558 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 101}
2017-12-31 21:31:07,561 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,567 : INFO : < 200 OK [3291]
2017-12-31 21:31:07,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 116}
2017-12-31 21:31:07,576 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,582 : INFO : < 200 OK [3342]
2017-12-31 21:31:07,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 102}
2017-12-31 21:31:07,591 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,597 : INFO : < 200 OK [3273]
2017-12-31 21:31:07,602 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 117}
2017-12-31 21:31:07,606 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,611 : INFO : < 200 OK [3299]
2017-12-31 21:31:07,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 103}
2017-12-31 21:31:07,619 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,625 : INFO : < 200 OK [3331]

2017-12-31 21:31:07,630 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 118}
2017-12-31 21:31:07,633 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,639 : INFO : < 200 OK [3281]
2017-12-31 21:31:07,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 104}
2017-12-31 21:31:07,648 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,653 : INFO : < 200 OK [3300]
2017-12-31 21:31:07,659 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 119}
2017-12-31 21:31:07,662 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,668 : INFO : < 200 OK [3299]
2017-12-31 21:31:07,673 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 105}
2017-12-31 21:31:07,676 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,682 : INFO : < 200 OK [3272]
2017-12-31 21:31:07,687 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 120}
2017-12-31 21:31:07,691 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,696 : INFO : < 200 OK [3313]
2017-12-31 21:31:07,701 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 106}
2017-12-31 21:31:07,705 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,711 : INFO : < 200 OK [3312]
2017-12-31 21:31:07,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 121}
2017-12-31 21:31:07,721 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,728 : INFO : < 200 OK [3306]
2017-12-31 21:31:07,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 107}
2017-12-31 21:31:07,737 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,744 : INFO : < 200 OK [3267]
2017-12-31 21:31:07,750 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 122}
2017-12-31 21:31:07,753 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,759 : INFO : < 200 OK [3296]
2017-12-31 21:31:07,765 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 108}
2017-12-31 21:31:07,768 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,775 : INFO : < 200 OK [3306]
2017-12-31 21:31:07,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 123}
2017-12-31 21:31:07,784 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,790 : INFO : < 200 OK [3273]
2017-12-31 21:31:07,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 109}
2017-12-31 21:31:07,799 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,805 : INFO : < 200 OK [3277]
2017-12-31 21:31:07,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 124}
2017-12-31 21:31:07,815 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,821 : INFO : < 200 OK [3286]
2017-12-31 21:31:07,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 110}
2017-12-31 21:31:07,830 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,836 : INFO : < 200 OK [3270]
2017-12-31 21:31:07,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 125}
2017-12-31 21:31:07,845 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,851 : INFO : < 200 OK [3303]
2017-12-31 21:31:07,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 111}
2017-12-31 21:31:07,860 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,866 : INFO : < 200 OK [3318]
2017-12-31 21:31:07,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 126}
2017-12-31 21:31:07,874 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,880 : INFO : < 200 OK [3272]
2017-12-31 21:31:07,885 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 112}
2017-12-31 21:31:07,889 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,895 : INFO : < 200 OK [3273]
2017-12-31 21:31:07,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 127}
2017-12-31 21:31:07,903 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,909 : INFO : < 200 OK [3306]
2017-12-31 21:31:07,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 40}
2017-12-31 21:31:07,918 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:07,924 : INFO : < 200 OK [3296]
2017-12-31 21:31:07,929 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 133}
2017-12-31 21:31:07,932 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,938 : INFO : < 200 OK [3307]
2017-12-31 21:31:07,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 128}
2017-12-31 21:31:07,949 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,955 : INFO : < 200 OK [3317]
2017-12-31 21:31:07,963 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 134}
2017-12-31 21:31:07,967 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,974 : INFO : < 200 OK [3324]
2017-12-31 21:31:07,982 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 129}
2017-12-31 21:31:07,985 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:07,992 : INFO : < 200 OK [3298]

2017-12-31 21:31:07,998 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 135}
2017-12-31 21:31:08,001 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,007 : INFO : < 200 OK [3308]
2017-12-31 21:31:08,013 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 130}
2017-12-31 21:31:08,017 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,023 : INFO : < 200 OK [3309]
2017-12-31 21:31:08,028 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 136}
2017-12-31 21:31:08,032 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,038 : INFO : < 200 OK [3329]
2017-12-31 21:31:08,043 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 131}
2017-12-31 21:31:08,046 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,053 : INFO : < 200 OK [3327]
2017-12-31 21:31:08,058 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 137}
2017-12-31 21:31:08,062 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,068 : INFO : < 200 OK [3292]
2017-12-31 21:31:08,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 132}
2017-12-31 21:31:08,077 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,083 : INFO : < 200 OK [3273]
2017-12-31 21:31:08,089 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 138}
2017-12-31 21:31:08,093 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,099 : INFO : < 200 OK [3307]
2017-12-31 21:31:08,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 153}
2017-12-31 21:31:08,108 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,114 : INFO : < 200 OK [3317]
2017-12-31 21:31:08,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 139}
2017-12-31 21:31:08,124 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,130 : INFO : < 200 OK [3314]
2017-12-31 21:31:08,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 154}
2017-12-31 21:31:08,138 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,144 : INFO : < 200 OK [3299]
2017-12-31 21:31:08,150 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 980, '_0n0': 140}
2017-12-31 21:31:08,153 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,159 : INFO : < 200 OK [3317]
2017-12-31 21:31:08,164 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 975, '_0n0': 1013}
2017-12-31 21:31:08,168 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:08,173 : INFO : < 200 OK [3349]
2017-12-31 21:31:08,178 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 975, '_0n0': 991}
2017-12-31 21:31:08,182 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,188 : INFO : < 200 OK [3321]
2017-12-31 21:31:08,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 975, '_0n0': 992}
2017-12-31 21:31:08,196 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,235 : INFO : < 200 OK [3324]
2017-12-31 21:31:08,241 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 975, '_0n0': 4}
2017-12-31 21:31:08,245 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:08,308 : INFO : < 200 OK [3301]
2017-12-31 21:31:08,314 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 975, '_0n0': 5}
2017-12-31 21:31:08,317 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:08,347 : INFO : < 200 OK [3302]
2017-12-31 21:31:08,352 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 975, '_0n0': 19}
2017-12-31 21:31:08,355 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:08,383 : INFO : < 200 OK [3309]
2017-12-31 21:31:08,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 975, '_0n0': 35}
2017-12-31 21:31:08,393 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:08,448 : INFO : < 200 OK [3313]
2017-12-31 21:31:08,454 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 981, '_0n0': 155}
2017-12-31 21:31:08,457 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,471 : INFO : < 200 OK [3302]
2017-12-31 21:31:08,477 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 981, '_0n0': 141}
2017-12-31 21:31:08,481 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,496 : INFO : < 200 OK [3301]
2017-12-31 21:31:08,501 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 981, '_0n0': 156}
2017-12-31 21:31:08,505 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,519 : INFO : < 200 OK [3330]
2017-12-31 21:31:08,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 981, '_0n0': 142}
2017-12-31 21:31:08,528 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,543 : INFO : < 200 OK [3316]
2017-12-31 21:31:08,548 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 157}
2017-12-31 21:31:08,552 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,567 : INFO : < 200 OK [3279]
2017-12-31 21:31:08,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 143}
2017-12-31 21:31:08,577 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,591 : INFO : < 200 OK [3340]

2017-12-31 21:31:08,598 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 158}
2017-12-31 21:31:08,605 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,621 : INFO : < 200 OK [3329]
2017-12-31 21:31:08,626 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 144}
2017-12-31 21:31:08,631 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,647 : INFO : < 200 OK [3293]
2017-12-31 21:31:08,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 159}
2017-12-31 21:31:08,657 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,683 : INFO : < 200 OK [3299]
2017-12-31 21:31:08,689 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 145}
2017-12-31 21:31:08,695 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,707 : INFO : < 200 OK [3317]
2017-12-31 21:31:08,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 160}
2017-12-31 21:31:08,715 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,722 : INFO : < 200 OK [3314]
2017-12-31 21:31:08,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 146}
2017-12-31 21:31:08,731 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,737 : INFO : < 200 OK [3308]
2017-12-31 21:31:08,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 161}
2017-12-31 21:31:08,746 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,752 : INFO : < 200 OK [3303]
2017-12-31 21:31:08,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 147}
2017-12-31 21:31:08,762 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,769 : INFO : < 200 OK [3236]
2017-12-31 21:31:08,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 162}
2017-12-31 21:31:08,778 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,784 : INFO : < 200 OK [3330]
2017-12-31 21:31:08,788 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 148}
2017-12-31 21:31:08,792 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,798 : INFO : < 200 OK [3310]
2017-12-31 21:31:08,803 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 163}
2017-12-31 21:31:08,807 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,813 : INFO : < 200 OK [3293]
2017-12-31 21:31:08,818 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 149}
2017-12-31 21:31:08,822 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,828 : INFO : < 200 OK [3287]
2017-12-31 21:31:08,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 164}
2017-12-31 21:31:08,837 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,843 : INFO : < 200 OK [3303]
2017-12-31 21:31:08,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 150}
2017-12-31 21:31:08,852 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,865 : INFO : < 200 OK [3275]
2017-12-31 21:31:08,872 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 165}
2017-12-31 21:31:08,876 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,883 : INFO : < 200 OK [3299]
2017-12-31 21:31:08,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 3}
2017-12-31 21:31:08,893 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:08,899 : INFO : < 200 OK [3247]
2017-12-31 21:31:08,904 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 151}
2017-12-31 21:31:08,908 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,914 : INFO : < 200 OK [3292]
2017-12-31 21:31:08,919 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 166}
2017-12-31 21:31:08,923 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,929 : INFO : < 200 OK [3329]
2017-12-31 21:31:08,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 152}
2017-12-31 21:31:08,938 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,944 : INFO : < 200 OK [3319]
2017-12-31 21:31:08,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 167}
2017-12-31 21:31:08,952 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,958 : INFO : < 200 OK [3305]
2017-12-31 21:31:08,963 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 173}
2017-12-31 21:31:08,967 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,972 : INFO : < 200 OK [3309]
2017-12-31 21:31:08,977 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 168}
2017-12-31 21:31:08,980 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:08,986 : INFO : < 200 OK [3314]
2017-12-31 21:31:08,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 174}
2017-12-31 21:31:08,995 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,000 : INFO : < 200 OK [3305]
2017-12-31 21:31:09,006 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 169}
2017-12-31 21:31:09,010 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,016 : INFO : < 200 OK [3287]

2017-12-31 21:31:09,022 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 14}
2017-12-31 21:31:09,026 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:09,032 : INFO : < 200 OK [3310]
2017-12-31 21:31:09,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 175}
2017-12-31 21:31:09,041 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,047 : INFO : < 200 OK [3302]
2017-12-31 21:31:09,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 170}
2017-12-31 21:31:09,057 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,063 : INFO : < 200 OK [3288]
2017-12-31 21:31:09,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 176}
2017-12-31 21:31:09,071 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,077 : INFO : < 200 OK [3271]
2017-12-31 21:31:09,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 171}
2017-12-31 21:31:09,086 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,093 : INFO : < 200 OK [3312]
2017-12-31 21:31:09,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 177}
2017-12-31 21:31:09,102 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,108 : INFO : < 200 OK [3285]
2017-12-31 21:31:09,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 172}
2017-12-31 21:31:09,116 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,122 : INFO : < 200 OK [3327]
2017-12-31 21:31:09,127 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 178}
2017-12-31 21:31:09,130 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,136 : INFO : < 200 OK [3312]
2017-12-31 21:31:09,141 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 193}
2017-12-31 21:31:09,145 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,150 : INFO : < 200 OK [3288]
2017-12-31 21:31:09,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 179}
2017-12-31 21:31:09,159 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,164 : INFO : < 200 OK [3274]
2017-12-31 21:31:09,170 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 194}
2017-12-31 21:31:09,173 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,180 : INFO : < 200 OK [3267]
2017-12-31 21:31:09,187 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 180}
2017-12-31 21:31:09,191 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,199 : INFO : < 200 OK [3311]
2017-12-31 21:31:09,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 195}
2017-12-31 21:31:09,208 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,217 : INFO : < 200 OK [3273]
2017-12-31 21:31:09,222 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 181}
2017-12-31 21:31:09,226 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,234 : INFO : < 200 OK [3309]
2017-12-31 21:31:09,239 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 196}
2017-12-31 21:31:09,244 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,252 : INFO : < 200 OK [3271]
2017-12-31 21:31:09,257 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 182}
2017-12-31 21:31:09,261 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,269 : INFO : < 200 OK [3267]
2017-12-31 21:31:09,274 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 197}
2017-12-31 21:31:09,278 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,285 : INFO : < 200 OK [3292]
2017-12-31 21:31:09,291 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 183}
2017-12-31 21:31:09,295 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,301 : INFO : < 200 OK [3337]
2017-12-31 21:31:09,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 198}
2017-12-31 21:31:09,310 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,316 : INFO : < 200 OK [3296]
2017-12-31 21:31:09,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 184}
2017-12-31 21:31:09,326 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,332 : INFO : < 200 OK [3281]
2017-12-31 21:31:09,338 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 199}
2017-12-31 21:31:09,342 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,349 : INFO : < 200 OK [3285]
2017-12-31 21:31:09,354 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 185}
2017-12-31 21:31:09,357 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,364 : INFO : < 200 OK [3305]
2017-12-31 21:31:09,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 200}
2017-12-31 21:31:09,373 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,380 : INFO : < 200 OK [3275]
2017-12-31 21:31:09,385 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 186}
2017-12-31 21:31:09,388 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,394 : INFO : < 200 OK [3333]

2017-12-31 21:31:09,400 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 201}
2017-12-31 21:31:09,403 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,409 : INFO : < 200 OK [3322]
2017-12-31 21:31:09,414 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 187}
2017-12-31 21:31:09,418 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,424 : INFO : < 200 OK [3295]
2017-12-31 21:31:09,429 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 202}
2017-12-31 21:31:09,433 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,438 : INFO : < 200 OK [3270]
2017-12-31 21:31:09,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 46}
2017-12-31 21:31:09,447 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:09,452 : INFO : < 200 OK [3312]
2017-12-31 21:31:09,457 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 188}
2017-12-31 21:31:09,461 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,466 : INFO : < 200 OK [3277]
2017-12-31 21:31:09,471 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 203}
2017-12-31 21:31:09,475 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,480 : INFO : < 200 OK [3333]
2017-12-31 21:31:09,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 189}
2017-12-31 21:31:09,489 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,495 : INFO : < 200 OK [3338]
2017-12-31 21:31:09,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 204}
2017-12-31 21:31:09,504 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,510 : INFO : < 200 OK [3264]
2017-12-31 21:31:09,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 190}
2017-12-31 21:31:09,519 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,526 : INFO : < 200 OK [3328]
2017-12-31 21:31:09,532 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 205}
2017-12-31 21:31:09,535 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,542 : INFO : < 200 OK [3331]
2017-12-31 21:31:09,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 191}
2017-12-31 21:31:09,551 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,557 : INFO : < 200 OK [3267]
2017-12-31 21:31:09,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 206}
2017-12-31 21:31:09,566 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,572 : INFO : < 200 OK [3284]
2017-12-31 21:31:09,578 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 996, '_0n0': 192}
2017-12-31 21:31:09,581 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,587 : INFO : < 200 OK [3296]
2017-12-31 21:31:09,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 207}
2017-12-31 21:31:09,597 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,603 : INFO : < 200 OK [3280]
2017-12-31 21:31:09,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 159}
2017-12-31 21:31:09,612 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,618 : INFO : < 200 OK [3303]
2017-12-31 21:31:09,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 86}
2017-12-31 21:31:09,628 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:09,634 : INFO : < 200 OK [3288]
2017-12-31 21:31:09,639 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 213}
2017-12-31 21:31:09,642 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,648 : INFO : < 200 OK [3309]
2017-12-31 21:31:09,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 162}
2017-12-31 21:31:09,656 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,662 : INFO : < 200 OK [3334]
2017-12-31 21:31:09,667 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 208}
2017-12-31 21:31:09,671 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,677 : INFO : < 200 OK [3356]
2017-12-31 21:31:09,681 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 94}
2017-12-31 21:31:09,685 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:09,691 : INFO : < 200 OK [3302]
2017-12-31 21:31:09,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 214}
2017-12-31 21:31:09,700 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,706 : INFO : < 200 OK [3291]
2017-12-31 21:31:09,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 209}
2017-12-31 21:31:09,715 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,721 : INFO : < 200 OK [3264]
2017-12-31 21:31:09,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 1}
2017-12-31 21:31:09,731 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:09,737 : INFO : < 200 OK [3274]
2017-12-31 21:31:09,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 215}
2017-12-31 21:31:09,747 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,754 : INFO : < 200 OK [3286]

2017-12-31 21:31:09,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 210}
2017-12-31 21:31:09,763 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,769 : INFO : < 200 OK [3283]
2017-12-31 21:31:09,775 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 216}
2017-12-31 21:31:09,779 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,785 : INFO : < 200 OK [3288]
2017-12-31 21:31:09,790 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 166}
2017-12-31 21:31:09,793 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,799 : INFO : < 200 OK [3333]
2017-12-31 21:31:09,804 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 211}
2017-12-31 21:31:09,808 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,814 : INFO : < 200 OK [3332]
2017-12-31 21:31:09,819 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 217}
2017-12-31 21:31:09,822 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,828 : INFO : < 200 OK [3281]
2017-12-31 21:31:09,833 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 15}
2017-12-31 21:31:09,837 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:09,842 : INFO : < 200 OK [3271]
2017-12-31 21:31:09,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 212}
2017-12-31 21:31:09,851 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,858 : INFO : < 200 OK [3293]
2017-12-31 21:31:09,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 218}
2017-12-31 21:31:09,869 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,876 : INFO : < 200 OK [3317]
2017-12-31 21:31:09,881 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 252}
2017-12-31 21:31:09,885 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,891 : INFO : < 200 OK [3322]
2017-12-31 21:31:09,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 219}
2017-12-31 21:31:09,900 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,908 : INFO : < 200 OK [3319]
2017-12-31 21:31:09,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 253}
2017-12-31 21:31:09,917 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,923 : INFO : < 200 OK [3268]
2017-12-31 21:31:09,928 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 220}
2017-12-31 21:31:09,932 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,937 : INFO : < 200 OK [3271]
2017-12-31 21:31:09,943 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 254}
2017-12-31 21:31:09,946 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,952 : INFO : < 200 OK [3288]
2017-12-31 21:31:09,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 37}
2017-12-31 21:31:09,961 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:09,967 : INFO : < 200 OK [3282]
2017-12-31 21:31:09,973 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 221}
2017-12-31 21:31:09,976 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,982 : INFO : < 200 OK [3285]
2017-12-31 21:31:09,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 255}
2017-12-31 21:31:09,992 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:09,999 : INFO : < 200 OK [3248]
2017-12-31 21:31:10,004 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 222}
2017-12-31 21:31:10,008 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,016 : INFO : < 200 OK [3270]
2017-12-31 21:31:10,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 256}
2017-12-31 21:31:10,026 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,034 : INFO : < 200 OK [3307]
2017-12-31 21:31:10,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 223}
2017-12-31 21:31:10,045 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,052 : INFO : < 200 OK [3323]
2017-12-31 21:31:10,058 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 257}
2017-12-31 21:31:10,064 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,071 : INFO : < 200 OK [3327]
2017-12-31 21:31:10,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 243}
2017-12-31 21:31:10,081 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,087 : INFO : < 200 OK [3296]
2017-12-31 21:31:10,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 258}
2017-12-31 21:31:10,097 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,103 : INFO : < 200 OK [3356]
2017-12-31 21:31:10,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 244}
2017-12-31 21:31:10,112 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,118 : INFO : < 200 OK [3317]
2017-12-31 21:31:10,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 259}
2017-12-31 21:31:10,127 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,133 : INFO : < 200 OK [3325]

2017-12-31 21:31:10,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 75}
2017-12-31 21:31:10,142 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:10,148 : INFO : < 200 OK [3269]
2017-12-31 21:31:10,154 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 245}
2017-12-31 21:31:10,157 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,164 : INFO : < 200 OK [3354]
2017-12-31 21:31:10,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 260}
2017-12-31 21:31:10,173 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,179 : INFO : < 200 OK [3299]
2017-12-31 21:31:10,186 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 246}
2017-12-31 21:31:10,190 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,197 : INFO : < 200 OK [3330]
2017-12-31 21:31:10,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 261}
2017-12-31 21:31:10,206 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,213 : INFO : < 200 OK [3316]
2017-12-31 21:31:10,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 982, '_0n0': 154}
2017-12-31 21:31:10,222 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,229 : INFO : < 200 OK [3311]
2017-12-31 21:31:10,234 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 247}
2017-12-31 21:31:10,238 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,244 : INFO : < 200 OK [3294]
2017-12-31 21:31:10,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 262}
2017-12-31 21:31:10,253 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,259 : INFO : < 200 OK [3315]
2017-12-31 21:31:10,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 248}
2017-12-31 21:31:10,267 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,273 : INFO : < 200 OK [3285]
2017-12-31 21:31:10,278 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 987}
2017-12-31 21:31:10,281 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,286 : INFO : < 200 OK [3259]
2017-12-31 21:31:10,291 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 263}
2017-12-31 21:31:10,294 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,299 : INFO : < 200 OK [3298]
2017-12-31 21:31:10,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 249}
2017-12-31 21:31:10,308 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,314 : INFO : < 200 OK [3257]
2017-12-31 21:31:10,318 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 264}
2017-12-31 21:31:10,322 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,327 : INFO : < 200 OK [3299]
2017-12-31 21:31:10,332 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 67}
2017-12-31 21:31:10,336 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:10,341 : INFO : < 200 OK [3331]
2017-12-31 21:31:10,346 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 250}
2017-12-31 21:31:10,350 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,355 : INFO : < 200 OK [3299]
2017-12-31 21:31:10,361 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 265}
2017-12-31 21:31:10,364 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,369 : INFO : < 200 OK [3328]
2017-12-31 21:31:10,375 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 251}
2017-12-31 21:31:10,378 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,383 : INFO : < 200 OK [3301]
2017-12-31 21:31:10,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 266}
2017-12-31 21:31:10,390 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,396 : INFO : < 200 OK [3283]
2017-12-31 21:31:10,400 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 272}
2017-12-31 21:31:10,403 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,410 : INFO : < 200 OK [3304]
2017-12-31 21:31:10,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 87}
2017-12-31 21:31:10,420 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:10,426 : INFO : < 200 OK [3275]
2017-12-31 21:31:10,433 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 267}
2017-12-31 21:31:10,436 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,441 : INFO : < 200 OK [3320]
2017-12-31 21:31:10,448 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 273}
2017-12-31 21:31:10,451 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,456 : INFO : < 200 OK [3270]
2017-12-31 21:31:10,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 89}
2017-12-31 21:31:10,464 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:10,471 : INFO : < 200 OK [3312]
2017-12-31 21:31:10,475 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 268}
2017-12-31 21:31:10,478 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,484 : INFO : < 200 OK [3296]

2017-12-31 21:31:10,489 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 96}
2017-12-31 21:31:10,492 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:10,498 : INFO : < 200 OK [3329]
2017-12-31 21:31:10,504 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 274}
2017-12-31 21:31:10,506 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,511 : INFO : < 200 OK [3264]
2017-12-31 21:31:10,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 91}
2017-12-31 21:31:10,518 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:10,523 : INFO : < 200 OK [3283]
2017-12-31 21:31:10,528 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 92}
2017-12-31 21:31:10,531 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:10,536 : INFO : < 200 OK [3284]
2017-12-31 21:31:10,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 98}
2017-12-31 21:31:10,545 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:10,551 : INFO : < 200 OK [3287]
2017-12-31 21:31:10,556 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 269}
2017-12-31 21:31:10,559 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,566 : INFO : < 200 OK [3279]
2017-12-31 21:31:10,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 275}
2017-12-31 21:31:10,575 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,583 : INFO : < 200 OK [3310]
2017-12-31 21:31:10,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 270}
2017-12-31 21:31:10,592 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,599 : INFO : < 200 OK [3323]
2017-12-31 21:31:10,604 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 113}
2017-12-31 21:31:10,608 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,614 : INFO : < 200 OK [3303]
2017-12-31 21:31:10,620 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 116}
2017-12-31 21:31:10,624 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,631 : INFO : < 200 OK [3350]
2017-12-31 21:31:10,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 276}
2017-12-31 21:31:10,639 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,645 : INFO : < 200 OK [3283]
2017-12-31 21:31:10,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 271}
2017-12-31 21:31:10,655 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,661 : INFO : < 200 OK [3320]
2017-12-31 21:31:10,667 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 277}
2017-12-31 21:31:10,670 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,676 : INFO : < 200 OK [3311]
2017-12-31 21:31:10,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 104}
2017-12-31 21:31:10,686 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,693 : INFO : < 200 OK [3304]
2017-12-31 21:31:10,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 292}
2017-12-31 21:31:10,702 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,708 : INFO : < 200 OK [3294]
2017-12-31 21:31:10,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 278}
2017-12-31 21:31:10,717 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,724 : INFO : < 200 OK [3284]
2017-12-31 21:31:10,729 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 293}
2017-12-31 21:31:10,733 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,739 : INFO : < 200 OK [3330]
2017-12-31 21:31:10,744 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 279}
2017-12-31 21:31:10,748 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,755 : INFO : < 200 OK [3298]
2017-12-31 21:31:10,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 294}
2017-12-31 21:31:10,764 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,770 : INFO : < 200 OK [3278]
2017-12-31 21:31:10,775 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 280}
2017-12-31 21:31:10,779 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,785 : INFO : < 200 OK [3312]
2017-12-31 21:31:10,790 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 295}
2017-12-31 21:31:10,793 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,799 : INFO : < 200 OK [3244]
2017-12-31 21:31:10,805 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 281}
2017-12-31 21:31:10,809 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,816 : INFO : < 200 OK [3302]
2017-12-31 21:31:10,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 18}
2017-12-31 21:31:10,825 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:10,831 : INFO : < 200 OK [3298]
2017-12-31 21:31:10,836 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 296}
2017-12-31 21:31:10,840 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,846 : INFO : < 200 OK [3270]

2017-12-31 21:31:10,852 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 124}
2017-12-31 21:31:10,855 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,862 : INFO : < 200 OK [3290]
2017-12-31 21:31:10,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 282}
2017-12-31 21:31:10,870 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,876 : INFO : < 200 OK [3303]
2017-12-31 21:31:10,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 297}
2017-12-31 21:31:10,885 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,891 : INFO : < 200 OK [3318]
2017-12-31 21:31:10,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 283}
2017-12-31 21:31:10,899 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,905 : INFO : < 200 OK [3266]
2017-12-31 21:31:10,911 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 21}
2017-12-31 21:31:10,914 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:10,920 : INFO : < 200 OK [3300]
2017-12-31 21:31:10,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 298}
2017-12-31 21:31:10,927 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,933 : INFO : < 200 OK [3295]
2017-12-31 21:31:10,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 284}
2017-12-31 21:31:10,941 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,947 : INFO : < 200 OK [3263]
2017-12-31 21:31:10,952 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 299}
2017-12-31 21:31:10,956 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,961 : INFO : < 200 OK [3342]
2017-12-31 21:31:10,967 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 285}
2017-12-31 21:31:10,971 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,977 : INFO : < 200 OK [3318]
2017-12-31 21:31:10,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 300}
2017-12-31 21:31:10,987 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:10,992 : INFO : < 200 OK [3267]
2017-12-31 21:31:10,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 286}
2017-12-31 21:31:11,000 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,006 : INFO : < 200 OK [3319]
2017-12-31 21:31:11,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 301}
2017-12-31 21:31:11,016 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,022 : INFO : < 200 OK [3275]
2017-12-31 21:31:11,028 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 287}
2017-12-31 21:31:11,032 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,038 : INFO : < 200 OK [3321]
2017-12-31 21:31:11,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 31}
2017-12-31 21:31:11,048 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:11,054 : INFO : < 200 OK [3260]
2017-12-31 21:31:11,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 302}
2017-12-31 21:31:11,063 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,070 : INFO : < 200 OK [3301]
2017-12-31 21:31:11,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 288}
2017-12-31 21:31:11,079 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,085 : INFO : < 200 OK [3293]
2017-12-31 21:31:11,090 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 303}
2017-12-31 21:31:11,094 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,100 : INFO : < 200 OK [3283]
2017-12-31 21:31:11,106 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 53}
2017-12-31 21:31:11,109 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:11,115 : INFO : < 200 OK [3280]
2017-12-31 21:31:11,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 289}
2017-12-31 21:31:11,125 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,131 : INFO : < 200 OK [3317]
2017-12-31 21:31:11,136 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 55}
2017-12-31 21:31:11,140 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:11,146 : INFO : < 200 OK [3281]
2017-12-31 21:31:11,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 304}
2017-12-31 21:31:11,155 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,161 : INFO : < 200 OK [3291]
2017-12-31 21:31:11,166 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 290}
2017-12-31 21:31:11,170 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,176 : INFO : < 200 OK [3296]
2017-12-31 21:31:11,181 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 997, '_0n0': 305}
2017-12-31 21:31:11,185 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,190 : INFO : < 200 OK [3263]
2017-12-31 21:31:11,196 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 291}
2017-12-31 21:31:11,199 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,205 : INFO : < 200 OK [3278]

2017-12-31 21:31:11,210 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 306}
2017-12-31 21:31:11,213 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,219 : INFO : < 200 OK [3311]
2017-12-31 21:31:11,224 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 312}
2017-12-31 21:31:11,228 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,234 : INFO : < 200 OK [3339]
2017-12-31 21:31:11,239 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 158}
2017-12-31 21:31:11,243 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,249 : INFO : < 200 OK [3337]
2017-12-31 21:31:11,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 307}
2017-12-31 21:31:11,258 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,264 : INFO : < 200 OK [3320]
2017-12-31 21:31:11,269 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 144}
2017-12-31 21:31:11,273 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,279 : INFO : < 200 OK [3301]
2017-12-31 21:31:11,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 313}
2017-12-31 21:31:11,287 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,293 : INFO : < 200 OK [3340]
2017-12-31 21:31:11,299 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 308}
2017-12-31 21:31:11,302 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,308 : INFO : < 200 OK [3319]
2017-12-31 21:31:11,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 314}
2017-12-31 21:31:11,316 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,322 : INFO : < 200 OK [3302]
2017-12-31 21:31:11,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 309}
2017-12-31 21:31:11,331 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,340 : INFO : < 200 OK [3330]
2017-12-31 21:31:11,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 160}
2017-12-31 21:31:11,349 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,355 : INFO : < 200 OK [3322]
2017-12-31 21:31:11,360 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 315}
2017-12-31 21:31:11,364 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,370 : INFO : < 200 OK [3277]
2017-12-31 21:31:11,375 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 310}
2017-12-31 21:31:11,379 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,385 : INFO : < 200 OK [3346]
2017-12-31 21:31:11,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 316}
2017-12-31 21:31:11,395 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,401 : INFO : < 200 OK [3286]
2017-12-31 21:31:11,406 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 311}
2017-12-31 21:31:11,409 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,415 : INFO : < 200 OK [3317]
2017-12-31 21:31:11,420 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 148}
2017-12-31 21:31:11,423 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,429 : INFO : < 200 OK [3318]
2017-12-31 21:31:11,434 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 317}
2017-12-31 21:31:11,437 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,443 : INFO : < 200 OK [3325]
2017-12-31 21:31:11,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 332}
2017-12-31 21:31:11,450 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,456 : INFO : < 200 OK [3305]
2017-12-31 21:31:11,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 318}
2017-12-31 21:31:11,462 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,468 : INFO : < 200 OK [3320]
2017-12-31 21:31:11,473 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 333}
2017-12-31 21:31:11,476 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,483 : INFO : < 200 OK [3287]
2017-12-31 21:31:11,488 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 319}
2017-12-31 21:31:11,494 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,501 : INFO : < 200 OK [3281]
2017-12-31 21:31:11,505 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 334}
2017-12-31 21:31:11,509 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,515 : INFO : < 200 OK [3333]
2017-12-31 21:31:11,520 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 320}
2017-12-31 21:31:11,523 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,529 : INFO : < 200 OK [3319]
2017-12-31 21:31:11,534 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 152}
2017-12-31 21:31:11,537 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,544 : INFO : < 200 OK [3327]
2017-12-31 21:31:11,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 335}
2017-12-31 21:31:11,552 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,558 : INFO : < 200 OK [3311]

2017-12-31 21:31:11,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 173}
2017-12-31 21:31:11,567 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,572 : INFO : < 200 OK [3317]
2017-12-31 21:31:11,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 321}
2017-12-31 21:31:11,579 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,584 : INFO : < 200 OK [3300]
2017-12-31 21:31:11,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 336}
2017-12-31 21:31:11,592 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,597 : INFO : < 200 OK [3334]
2017-12-31 21:31:11,602 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 322}
2017-12-31 21:31:11,605 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,611 : INFO : < 200 OK [3327]
2017-12-31 21:31:11,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 337}
2017-12-31 21:31:11,620 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,626 : INFO : < 200 OK [3290]
2017-12-31 21:31:11,633 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 323}
2017-12-31 21:31:11,636 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,642 : INFO : < 200 OK [3296]
2017-12-31 21:31:11,647 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 338}
2017-12-31 21:31:11,651 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,656 : INFO : < 200 OK [3286]
2017-12-31 21:31:11,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 324}
2017-12-31 21:31:11,665 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,671 : INFO : < 200 OK [3278]
2017-12-31 21:31:11,675 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 339}
2017-12-31 21:31:11,678 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,684 : INFO : < 200 OK [3319]
2017-12-31 21:31:11,689 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 325}
2017-12-31 21:31:11,693 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,699 : INFO : < 200 OK [3326]
2017-12-31 21:31:11,704 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 340}
2017-12-31 21:31:11,707 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,713 : INFO : < 200 OK [3344]
2017-12-31 21:31:11,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 326}
2017-12-31 21:31:11,721 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,727 : INFO : < 200 OK [3316]
2017-12-31 21:31:11,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 341}
2017-12-31 21:31:11,735 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,740 : INFO : < 200 OK [3312]
2017-12-31 21:31:11,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 327}
2017-12-31 21:31:11,748 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,753 : INFO : < 200 OK [3353]
2017-12-31 21:31:11,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 221}
2017-12-31 21:31:11,760 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,765 : INFO : < 200 OK [3289]
2017-12-31 21:31:11,770 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 342}
2017-12-31 21:31:11,774 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,780 : INFO : < 200 OK [3325]
2017-12-31 21:31:11,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 328}
2017-12-31 21:31:11,791 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,797 : INFO : < 200 OK [3294]
2017-12-31 21:31:11,802 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 343}
2017-12-31 21:31:11,806 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,812 : INFO : < 200 OK [3312]
2017-12-31 21:31:11,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 329}
2017-12-31 21:31:11,819 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,825 : INFO : < 200 OK [3296]
2017-12-31 21:31:11,830 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 344}
2017-12-31 21:31:11,834 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,839 : INFO : < 200 OK [3297]
2017-12-31 21:31:11,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 330}
2017-12-31 21:31:11,847 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,853 : INFO : < 200 OK [3283]
2017-12-31 21:31:11,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 345}
2017-12-31 21:31:11,861 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,866 : INFO : < 200 OK [3297]
2017-12-31 21:31:11,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 331}
2017-12-31 21:31:11,874 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,879 : INFO : < 200 OK [3299]
2017-12-31 21:31:11,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 346}
2017-12-31 21:31:11,886 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,891 : INFO : < 200 OK [3302]

2017-12-31 21:31:11,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 352}
2017-12-31 21:31:11,899 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,905 : INFO : < 200 OK [3334]
2017-12-31 21:31:11,911 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 347}
2017-12-31 21:31:11,915 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,922 : INFO : < 200 OK [3291]
2017-12-31 21:31:11,928 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 353}
2017-12-31 21:31:11,931 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,937 : INFO : < 200 OK [3301]
2017-12-31 21:31:11,942 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 348}
2017-12-31 21:31:11,945 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,951 : INFO : < 200 OK [3304]
2017-12-31 21:31:11,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 59}
2017-12-31 21:31:11,958 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:11,964 : INFO : < 200 OK [3285]
2017-12-31 21:31:11,968 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 354}
2017-12-31 21:31:11,972 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,977 : INFO : < 200 OK [3283]
2017-12-31 21:31:11,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 349}
2017-12-31 21:31:11,985 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:11,990 : INFO : < 200 OK [3306]
2017-12-31 21:31:11,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 355}
2017-12-31 21:31:11,998 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,004 : INFO : < 200 OK [3302]
2017-12-31 21:31:12,009 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 350}
2017-12-31 21:31:12,013 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,019 : INFO : < 200 OK [3296]
2017-12-31 21:31:12,023 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 356}
2017-12-31 21:31:12,026 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,031 : INFO : < 200 OK [3287]
2017-12-31 21:31:12,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 351}
2017-12-31 21:31:12,039 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,044 : INFO : < 200 OK [3290]
2017-12-31 21:31:12,050 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 357}
2017-12-31 21:31:12,053 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,057 : INFO : < 200 OK [3308]
2017-12-31 21:31:12,062 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 372}
2017-12-31 21:31:12,065 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,071 : INFO : < 200 OK [3279]
2017-12-31 21:31:12,076 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 983, '_0n0': 358}
2017-12-31 21:31:12,079 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,084 : INFO : < 200 OK [3328]
2017-12-31 21:31:12,089 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 998, '_0n0': 989}
2017-12-31 21:31:12,093 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,099 : INFO : < 200 OK [3309]
2017-12-31 21:31:12,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 998, '_0n0': 994}
2017-12-31 21:31:12,108 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,115 : INFO : < 200 OK [3304]
2017-12-31 21:31:12,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 998, '_0n0': 9}
2017-12-31 21:31:12,125 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:12,131 : INFO : < 200 OK [3262]
2017-12-31 21:31:12,136 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 998, '_0n0': 16}
2017-12-31 21:31:12,140 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,146 : INFO : < 200 OK [3287]
2017-12-31 21:31:12,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 998, '_0n0': 17}
2017-12-31 21:31:12,155 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,160 : INFO : < 200 OK [3295]
2017-12-31 21:31:12,165 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 373}
2017-12-31 21:31:12,168 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,173 : INFO : < 200 OK [3303]
2017-12-31 21:31:12,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 359}
2017-12-31 21:31:12,182 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,188 : INFO : < 200 OK [3322]
2017-12-31 21:31:12,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 265}
2017-12-31 21:31:12,196 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,202 : INFO : < 200 OK [3340]
2017-12-31 21:31:12,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 374}
2017-12-31 21:31:12,209 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,215 : INFO : < 200 OK [3282]
2017-12-31 21:31:12,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 360}
2017-12-31 21:31:12,223 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,229 : INFO : < 200 OK [3302]

2017-12-31 21:31:12,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 375}
2017-12-31 21:31:12,237 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,243 : INFO : < 200 OK [3282]
2017-12-31 21:31:12,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 361}
2017-12-31 21:31:12,250 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,257 : INFO : < 200 OK [3274]
2017-12-31 21:31:12,262 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 376}
2017-12-31 21:31:12,265 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,271 : INFO : < 200 OK [3278]
2017-12-31 21:31:12,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 362}
2017-12-31 21:31:12,278 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,283 : INFO : < 200 OK [3285]
2017-12-31 21:31:12,288 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 266}
2017-12-31 21:31:12,291 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,297 : INFO : < 200 OK [3295]
2017-12-31 21:31:12,302 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 377}
2017-12-31 21:31:12,306 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,311 : INFO : < 200 OK [3308]
2017-12-31 21:31:12,316 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 267}
2017-12-31 21:31:12,319 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,325 : INFO : < 200 OK [3332]
2017-12-31 21:31:12,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 363}
2017-12-31 21:31:12,333 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,339 : INFO : < 200 OK [3275]
2017-12-31 21:31:12,344 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 378}
2017-12-31 21:31:12,347 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,353 : INFO : < 200 OK [3309]
2017-12-31 21:31:12,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 364}
2017-12-31 21:31:12,360 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,365 : INFO : < 200 OK [3317]
2017-12-31 21:31:12,369 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 379}
2017-12-31 21:31:12,372 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,379 : INFO : < 200 OK [3278]
2017-12-31 21:31:12,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 365}
2017-12-31 21:31:12,387 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,393 : INFO : < 200 OK [3327]
2017-12-31 21:31:12,398 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 380}
2017-12-31 21:31:12,400 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,406 : INFO : < 200 OK [3311]
2017-12-31 21:31:12,410 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 366}
2017-12-31 21:31:12,413 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,432 : INFO : < 200 OK [3281]
2017-12-31 21:31:12,439 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 381}
2017-12-31 21:31:12,444 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,450 : INFO : < 200 OK [3339]
2017-12-31 21:31:12,456 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 367}
2017-12-31 21:31:12,459 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,465 : INFO : < 200 OK [3326]
2017-12-31 21:31:12,471 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 382}
2017-12-31 21:31:12,474 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,480 : INFO : < 200 OK [3368]
2017-12-31 21:31:12,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 368}
2017-12-31 21:31:12,489 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,495 : INFO : < 200 OK [3279]
2017-12-31 21:31:12,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 383}
2017-12-31 21:31:12,504 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,510 : INFO : < 200 OK [3318]
2017-12-31 21:31:12,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 293}
2017-12-31 21:31:12,519 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,525 : INFO : < 200 OK [3342]
2017-12-31 21:31:12,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 369}
2017-12-31 21:31:12,536 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,542 : INFO : < 200 OK [3321]
2017-12-31 21:31:12,548 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 384}
2017-12-31 21:31:12,552 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,558 : INFO : < 200 OK [3288]
2017-12-31 21:31:12,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 299}
2017-12-31 21:31:12,568 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,574 : INFO : < 200 OK [3354]
2017-12-31 21:31:12,579 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 370}
2017-12-31 21:31:12,582 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,588 : INFO : < 200 OK [3292]

2017-12-31 21:31:12,594 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 385}
2017-12-31 21:31:12,597 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,607 : INFO : < 200 OK [3304]
2017-12-31 21:31:12,612 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 371}
2017-12-31 21:31:12,616 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,622 : INFO : < 200 OK [3280]
2017-12-31 21:31:12,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 303}
2017-12-31 21:31:12,631 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,637 : INFO : < 200 OK [3295]
2017-12-31 21:31:12,642 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 386}
2017-12-31 21:31:12,646 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,652 : INFO : < 200 OK [3343]
2017-12-31 21:31:12,657 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 392}
2017-12-31 21:31:12,661 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,667 : INFO : < 200 OK [3350]
2017-12-31 21:31:12,672 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 984, '_0n0': 387}
2017-12-31 21:31:12,676 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,683 : INFO : < 200 OK [3283]
2017-12-31 21:31:12,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 999, '_0n0': 6}
2017-12-31 21:31:12,691 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:12,697 : INFO : < 200 OK [3278]
2017-12-31 21:31:12,702 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 999, '_0n0': 13}
2017-12-31 21:31:12,705 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,711 : INFO : < 200 OK [3295]
2017-12-31 21:31:12,716 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 999, '_0n0': 34}
2017-12-31 21:31:12,719 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,725 : INFO : < 200 OK [3295]
2017-12-31 21:31:12,730 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 999, '_0n0': 22}
2017-12-31 21:31:12,734 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,740 : INFO : < 200 OK [3285]
2017-12-31 21:31:12,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 999, '_0n0': 26}
2017-12-31 21:31:12,749 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,756 : INFO : < 200 OK [3266]
2017-12-31 21:31:12,761 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 999, '_0n0': 28}
2017-12-31 21:31:12,764 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,771 : INFO : < 200 OK [3303]
2017-12-31 21:31:12,777 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 999, '_0n0': 54}
2017-12-31 21:31:12,780 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,788 : INFO : < 200 OK [3280]
2017-12-31 21:31:12,793 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 999, '_0n0': 51}
2017-12-31 21:31:12,797 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,818 : INFO : < 200 OK [3285]
2017-12-31 21:31:12,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 393}
2017-12-31 21:31:12,827 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,833 : INFO : < 200 OK [3263]
2017-12-31 21:31:12,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 64}
2017-12-31 21:31:12,842 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,848 : INFO : < 200 OK [3298]
2017-12-31 21:31:12,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 80}
2017-12-31 21:31:12,856 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,862 : INFO : < 200 OK [3294]
2017-12-31 21:31:12,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 65}
2017-12-31 21:31:12,871 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,878 : INFO : < 200 OK [3347]
2017-12-31 21:31:12,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 388}
2017-12-31 21:31:12,887 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,894 : INFO : < 200 OK [3313]
2017-12-31 21:31:12,899 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 394}
2017-12-31 21:31:12,903 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,909 : INFO : < 200 OK [3283]
2017-12-31 21:31:12,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 82}
2017-12-31 21:31:12,917 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:12,922 : INFO : < 200 OK [3255]
2017-12-31 21:31:12,927 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 389}
2017-12-31 21:31:12,931 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,937 : INFO : < 200 OK [3305]
2017-12-31 21:31:12,942 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 395}
2017-12-31 21:31:12,945 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,951 : INFO : < 200 OK [3298]
2017-12-31 21:31:12,956 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 390}
2017-12-31 21:31:12,959 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,965 : INFO : < 200 OK [3338]

2017-12-31 21:31:12,970 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 396}
2017-12-31 21:31:12,973 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,979 : INFO : < 200 OK [3313]
2017-12-31 21:31:12,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 391}
2017-12-31 21:31:12,987 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:12,993 : INFO : < 200 OK [3273]
2017-12-31 21:31:12,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 397}
2017-12-31 21:31:13,001 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,010 : INFO : < 200 OK [3302]
2017-12-31 21:31:13,015 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 362}
2017-12-31 21:31:13,019 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,025 : INFO : < 200 OK [3275]
2017-12-31 21:31:13,032 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 71}
2017-12-31 21:31:13,035 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:13,040 : INFO : < 200 OK [3309]
2017-12-31 21:31:13,046 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 412}
2017-12-31 21:31:13,048 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,054 : INFO : < 200 OK [3279]
2017-12-31 21:31:13,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 398}
2017-12-31 21:31:13,062 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,067 : INFO : < 200 OK [3294]
2017-12-31 21:31:13,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 413}
2017-12-31 21:31:13,076 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,081 : INFO : < 200 OK [3327]
2017-12-31 21:31:13,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 399}
2017-12-31 21:31:13,088 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,094 : INFO : < 200 OK [3302]
2017-12-31 21:31:13,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 414}
2017-12-31 21:31:13,101 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,107 : INFO : < 200 OK [3287]
2017-12-31 21:31:13,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 400}
2017-12-31 21:31:13,117 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,123 : INFO : < 200 OK [3344]
2017-12-31 21:31:13,129 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 415}
2017-12-31 21:31:13,133 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,139 : INFO : < 200 OK [3277]
2017-12-31 21:31:13,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 401}
2017-12-31 21:31:13,147 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,152 : INFO : < 200 OK [3272]
2017-12-31 21:31:13,158 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 416}
2017-12-31 21:31:13,161 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,167 : INFO : < 200 OK [3348]
2017-12-31 21:31:13,172 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 402}
2017-12-31 21:31:13,175 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,180 : INFO : < 200 OK [3352]
2017-12-31 21:31:13,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 417}
2017-12-31 21:31:13,188 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,194 : INFO : < 200 OK [3280]
2017-12-31 21:31:13,198 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 118}
2017-12-31 21:31:13,202 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,207 : INFO : < 200 OK [3287]
2017-12-31 21:31:13,212 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 403}
2017-12-31 21:31:13,215 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,220 : INFO : < 200 OK [3353]
2017-12-31 21:31:13,224 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 418}
2017-12-31 21:31:13,228 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,235 : INFO : < 200 OK [3324]
2017-12-31 21:31:13,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 120}
2017-12-31 21:31:13,244 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,250 : INFO : < 200 OK [3319]
2017-12-31 21:31:13,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 404}
2017-12-31 21:31:13,258 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,265 : INFO : < 200 OK [3307]
2017-12-31 21:31:13,269 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 419}
2017-12-31 21:31:13,273 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,278 : INFO : < 200 OK [3281]
2017-12-31 21:31:13,283 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 106}
2017-12-31 21:31:13,287 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,292 : INFO : < 200 OK [3318]
2017-12-31 21:31:13,297 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 405}
2017-12-31 21:31:13,301 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,306 : INFO : < 200 OK [3291]

2017-12-31 21:31:13,311 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 420}
2017-12-31 21:31:13,314 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,319 : INFO : < 200 OK [3306]
2017-12-31 21:31:13,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 406}
2017-12-31 21:31:13,327 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,332 : INFO : < 200 OK [3287]
2017-12-31 21:31:13,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 421}
2017-12-31 21:31:13,340 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,345 : INFO : < 200 OK [3291]
2017-12-31 21:31:13,349 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 407}
2017-12-31 21:31:13,352 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,357 : INFO : < 200 OK [3268]
2017-12-31 21:31:13,361 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 422}
2017-12-31 21:31:13,365 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,371 : INFO : < 200 OK [3297]
2017-12-31 21:31:13,377 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 408}
2017-12-31 21:31:13,382 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,388 : INFO : < 200 OK [3314]
2017-12-31 21:31:13,393 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 423}
2017-12-31 21:31:13,396 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,403 : INFO : < 200 OK [3315]
2017-12-31 21:31:13,407 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 409}
2017-12-31 21:31:13,411 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,417 : INFO : < 200 OK [3302]
2017-12-31 21:31:13,422 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 424}
2017-12-31 21:31:13,425 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,431 : INFO : < 200 OK [3306]
2017-12-31 21:31:13,436 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 410}
2017-12-31 21:31:13,439 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,445 : INFO : < 200 OK [3309]
2017-12-31 21:31:13,450 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 425}
2017-12-31 21:31:13,453 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,459 : INFO : < 200 OK [3304]
2017-12-31 21:31:13,463 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 411}
2017-12-31 21:31:13,466 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,471 : INFO : < 200 OK [3309]
2017-12-31 21:31:13,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 426}
2017-12-31 21:31:13,479 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,484 : INFO : < 200 OK [3319]
2017-12-31 21:31:13,489 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 432}
2017-12-31 21:31:13,493 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,499 : INFO : < 200 OK [3286]
2017-12-31 21:31:13,505 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 985, '_0n0': 427}
2017-12-31 21:31:13,508 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:13,515 : INFO : < 200 OK [3250]
2017-12-31 21:31:13,520 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 433}
2017-12-31 21:31:13,524 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,530 : INFO : < 200 OK [3330]
2017-12-31 21:31:13,534 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 388}
2017-12-31 21:31:13,538 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,544 : INFO : < 200 OK [3325]
2017-12-31 21:31:13,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 247}
2017-12-31 21:31:13,553 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,558 : INFO : < 200 OK [3308]
2017-12-31 21:31:13,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 394}
2017-12-31 21:31:13,567 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,572 : INFO : < 200 OK [3295]
2017-12-31 21:31:13,577 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 373}
2017-12-31 21:31:13,580 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,585 : INFO : < 200 OK [3305]
2017-12-31 21:31:13,590 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 428}
2017-12-31 21:31:13,593 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,598 : INFO : < 200 OK [3281]
2017-12-31 21:31:13,603 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 434}
2017-12-31 21:31:13,606 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,611 : INFO : < 200 OK [3289]
2017-12-31 21:31:13,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 429}
2017-12-31 21:31:13,619 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,624 : INFO : < 200 OK [3315]
2017-12-31 21:31:13,628 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 359}
2017-12-31 21:31:13,632 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,638 : INFO : < 200 OK [3324]

2017-12-31 21:31:13,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 435}
2017-12-31 21:31:13,647 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,653 : INFO : < 200 OK [3283]
2017-12-31 21:31:13,658 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 263}
2017-12-31 21:31:13,663 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,668 : INFO : < 200 OK [3312]
2017-12-31 21:31:13,673 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 430}
2017-12-31 21:31:13,676 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,682 : INFO : < 200 OK [3326]
2017-12-31 21:31:13,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 390}
2017-12-31 21:31:13,691 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,697 : INFO : < 200 OK [3350]
2017-12-31 21:31:13,701 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 436}
2017-12-31 21:31:13,704 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,710 : INFO : < 200 OK [3325]
2017-12-31 21:31:13,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 431}
2017-12-31 21:31:13,716 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,721 : INFO : < 200 OK [3286]
2017-12-31 21:31:13,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 143}
2017-12-31 21:31:13,729 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,735 : INFO : < 200 OK [3350]
2017-12-31 21:31:13,739 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 437}
2017-12-31 21:31:13,742 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,748 : INFO : < 200 OK [3315]
2017-12-31 21:31:13,753 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 452}
2017-12-31 21:31:13,758 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,764 : INFO : < 200 OK [3321]
2017-12-31 21:31:13,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 438}
2017-12-31 21:31:13,772 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,779 : INFO : < 200 OK [3308]
2017-12-31 21:31:13,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 374}
2017-12-31 21:31:13,787 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,793 : INFO : < 200 OK [3284]
2017-12-31 21:31:13,798 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 453}
2017-12-31 21:31:13,801 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,807 : INFO : < 200 OK [3301]
2017-12-31 21:31:13,813 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 439}
2017-12-31 21:31:13,816 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,821 : INFO : < 200 OK [3321]
2017-12-31 21:31:13,825 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 454}
2017-12-31 21:31:13,829 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,834 : INFO : < 200 OK [3317]
2017-12-31 21:31:13,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 440}
2017-12-31 21:31:13,841 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,846 : INFO : < 200 OK [3300]
2017-12-31 21:31:13,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 455}
2017-12-31 21:31:13,854 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,859 : INFO : < 200 OK [3296]
2017-12-31 21:31:13,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 441}
2017-12-31 21:31:13,867 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,871 : INFO : < 200 OK [3252]
2017-12-31 21:31:13,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 456}
2017-12-31 21:31:13,879 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,885 : INFO : < 200 OK [3342]
2017-12-31 21:31:13,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 442}
2017-12-31 21:31:13,892 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,897 : INFO : < 200 OK [3291]
2017-12-31 21:31:13,902 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 457}
2017-12-31 21:31:13,905 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,912 : INFO : < 200 OK [3325]
2017-12-31 21:31:13,917 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 391}
2017-12-31 21:31:13,921 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,927 : INFO : < 200 OK [3285]
2017-12-31 21:31:13,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 443}
2017-12-31 21:31:13,935 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,941 : INFO : < 200 OK [3287]
2017-12-31 21:31:13,946 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 375}
2017-12-31 21:31:13,949 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,955 : INFO : < 200 OK [3284]
2017-12-31 21:31:13,959 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 458}
2017-12-31 21:31:13,963 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,968 : INFO : < 200 OK [3326]

2017-12-31 21:31:13,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 361}
2017-12-31 21:31:13,976 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,981 : INFO : < 200 OK [3276]
2017-12-31 21:31:13,986 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 444}
2017-12-31 21:31:13,989 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:13,994 : INFO : < 200 OK [3330]
2017-12-31 21:31:13,998 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 376}
2017-12-31 21:31:14,000 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,006 : INFO : < 200 OK [3280]
2017-12-31 21:31:14,011 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 459}
2017-12-31 21:31:14,014 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,019 : INFO : < 200 OK [3336]
2017-12-31 21:31:14,023 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 445}
2017-12-31 21:31:14,027 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,032 : INFO : < 200 OK [3307]
2017-12-31 21:31:14,037 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 377}
2017-12-31 21:31:14,041 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,049 : INFO : < 200 OK [3310]
2017-12-31 21:31:14,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 460}
2017-12-31 21:31:14,057 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,063 : INFO : < 200 OK [3333]
2017-12-31 21:31:14,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 446}
2017-12-31 21:31:14,072 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,077 : INFO : < 200 OK [3275]
2017-12-31 21:31:14,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 461}
2017-12-31 21:31:14,086 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,091 : INFO : < 200 OK [3289]
2017-12-31 21:31:14,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 363}
2017-12-31 21:31:14,099 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,105 : INFO : < 200 OK [3277]
2017-12-31 21:31:14,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 447}
2017-12-31 21:31:14,113 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,118 : INFO : < 200 OK [3301]
2017-12-31 21:31:14,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 378}
2017-12-31 21:31:14,125 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,130 : INFO : < 200 OK [3311]
2017-12-31 21:31:14,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 462}
2017-12-31 21:31:14,138 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,144 : INFO : < 200 OK [3298]
2017-12-31 21:31:14,148 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 364}
2017-12-31 21:31:14,152 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,157 : INFO : < 200 OK [3319]
2017-12-31 21:31:14,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 448}
2017-12-31 21:31:14,165 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,171 : INFO : < 200 OK [3299]
2017-12-31 21:31:14,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 414}
2017-12-31 21:31:14,182 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,187 : INFO : < 200 OK [3299]
2017-12-31 21:31:14,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 463}
2017-12-31 21:31:14,196 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,201 : INFO : < 200 OK [3333]
2017-12-31 21:31:14,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 400}
2017-12-31 21:31:14,210 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,216 : INFO : < 200 OK [3356]
2017-12-31 21:31:14,221 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 449}
2017-12-31 21:31:14,224 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,229 : INFO : < 200 OK [3250]
2017-12-31 21:31:14,235 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 379}
2017-12-31 21:31:14,238 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,243 : INFO : < 200 OK [3280]
2017-12-31 21:31:14,248 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 464}
2017-12-31 21:31:14,251 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,257 : INFO : < 200 OK [3254]
2017-12-31 21:31:14,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 450}
2017-12-31 21:31:14,265 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,270 : INFO : < 200 OK [3302]
2017-12-31 21:31:14,274 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 366}
2017-12-31 21:31:14,278 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,283 : INFO : < 200 OK [3283]
2017-12-31 21:31:14,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 465}
2017-12-31 21:31:14,290 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,295 : INFO : < 200 OK [3323]

2017-12-31 21:31:14,299 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 401}
2017-12-31 21:31:14,302 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,309 : INFO : < 200 OK [3284]
2017-12-31 21:31:14,314 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 451}
2017-12-31 21:31:14,318 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,325 : INFO : < 200 OK [3316]
2017-12-31 21:31:14,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 466}
2017-12-31 21:31:14,335 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,341 : INFO : < 200 OK [3350]
2017-12-31 21:31:14,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 472}
2017-12-31 21:31:14,351 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,357 : INFO : < 200 OK [3281]
2017-12-31 21:31:14,364 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 467}
2017-12-31 21:31:14,368 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,374 : INFO : < 200 OK [3334]
2017-12-31 21:31:14,380 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 473}
2017-12-31 21:31:14,383 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,389 : INFO : < 200 OK [3338]
2017-12-31 21:31:14,394 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 468}
2017-12-31 21:31:14,398 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,404 : INFO : < 200 OK [3279]
2017-12-31 21:31:14,409 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 474}
2017-12-31 21:31:14,413 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,419 : INFO : < 200 OK [3325]
2017-12-31 21:31:14,424 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 469}
2017-12-31 21:31:14,428 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,434 : INFO : < 200 OK [3313]
2017-12-31 21:31:14,439 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 102}
2017-12-31 21:31:14,442 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,448 : INFO : < 200 OK [3295]
2017-12-31 21:31:14,453 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 475}
2017-12-31 21:31:14,456 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,462 : INFO : < 200 OK [3286]
2017-12-31 21:31:14,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 470}
2017-12-31 21:31:14,470 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,475 : INFO : < 200 OK [3308]
2017-12-31 21:31:14,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 417}
2017-12-31 21:31:14,484 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,490 : INFO : < 200 OK [3292]
2017-12-31 21:31:14,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 476}
2017-12-31 21:31:14,500 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,506 : INFO : < 200 OK [3287]
2017-12-31 21:31:14,513 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 471}
2017-12-31 21:31:14,516 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,523 : INFO : < 200 OK [3302]
2017-12-31 21:31:14,528 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 477}
2017-12-31 21:31:14,531 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,537 : INFO : < 200 OK [3327]
2017-12-31 21:31:14,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 505}
2017-12-31 21:31:14,546 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,552 : INFO : < 200 OK [3337]
2017-12-31 21:31:14,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 478}
2017-12-31 21:31:14,561 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,567 : INFO : < 200 OK [3309]
2017-12-31 21:31:14,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 506}
2017-12-31 21:31:14,575 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,581 : INFO : < 200 OK [3314]
2017-12-31 21:31:14,586 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 479}
2017-12-31 21:31:14,590 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,596 : INFO : < 200 OK [3330]
2017-12-31 21:31:14,601 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 507}
2017-12-31 21:31:14,604 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,610 : INFO : < 200 OK [3287]
2017-12-31 21:31:14,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 480}
2017-12-31 21:31:14,619 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,625 : INFO : < 200 OK [3292]
2017-12-31 21:31:14,630 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 508}
2017-12-31 21:31:14,633 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,639 : INFO : < 200 OK [3284]
2017-12-31 21:31:14,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 403}
2017-12-31 21:31:14,649 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,655 : INFO : < 200 OK [3365]

2017-12-31 21:31:14,660 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 481}
2017-12-31 21:31:14,664 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,670 : INFO : < 200 OK [3300]
2017-12-31 21:31:14,675 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 382}
2017-12-31 21:31:14,678 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,684 : INFO : < 200 OK [3370]
2017-12-31 21:31:14,689 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 509}
2017-12-31 21:31:14,693 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,699 : INFO : < 200 OK [3315]
2017-12-31 21:31:14,703 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 482}
2017-12-31 21:31:14,707 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,713 : INFO : < 200 OK [3317]
2017-12-31 21:31:14,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 510}
2017-12-31 21:31:14,721 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,727 : INFO : < 200 OK [3320]
2017-12-31 21:31:14,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 483}
2017-12-31 21:31:14,734 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,740 : INFO : < 200 OK [3288]
2017-12-31 21:31:14,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 511}
2017-12-31 21:31:14,748 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,754 : INFO : < 200 OK [3347]
2017-12-31 21:31:14,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 484}
2017-12-31 21:31:14,763 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,771 : INFO : < 200 OK [3337]
2017-12-31 21:31:14,776 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 175}
2017-12-31 21:31:14,781 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,787 : INFO : < 200 OK [3312]
2017-12-31 21:31:14,792 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 512}
2017-12-31 21:31:14,796 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,801 : INFO : < 200 OK [3290]
2017-12-31 21:31:14,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 485}
2017-12-31 21:31:14,809 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,815 : INFO : < 200 OK [3353]
2017-12-31 21:31:14,819 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 419}
2017-12-31 21:31:14,823 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,828 : INFO : < 200 OK [3293]
2017-12-31 21:31:14,833 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 404}
2017-12-31 21:31:14,837 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,842 : INFO : < 200 OK [3319]
2017-12-31 21:31:14,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 368}
2017-12-31 21:31:14,850 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,856 : INFO : < 200 OK [3281]
2017-12-31 21:31:14,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 513}
2017-12-31 21:31:14,864 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,871 : INFO : < 200 OK [3291]
2017-12-31 21:31:14,878 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 486}
2017-12-31 21:31:14,881 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,887 : INFO : < 200 OK [3313]
2017-12-31 21:31:14,893 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 514}
2017-12-31 21:31:14,897 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,903 : INFO : < 200 OK [3321]
2017-12-31 21:31:14,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 500}
2017-12-31 21:31:14,911 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,917 : INFO : < 200 OK [3279]
2017-12-31 21:31:14,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 515}
2017-12-31 21:31:14,926 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,932 : INFO : < 200 OK [3286]
2017-12-31 21:31:14,937 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 501}
2017-12-31 21:31:14,940 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,946 : INFO : < 200 OK [3309]
2017-12-31 21:31:14,951 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 281}
2017-12-31 21:31:14,954 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,960 : INFO : < 200 OK [3316]
2017-12-31 21:31:14,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 172}
2017-12-31 21:31:14,968 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,974 : INFO : < 200 OK [3337]
2017-12-31 21:31:14,979 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 516}
2017-12-31 21:31:14,982 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:14,990 : INFO : < 200 OK [3290]
2017-12-31 21:31:14,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 502}
2017-12-31 21:31:14,999 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,006 : INFO : < 200 OK [3329]

2017-12-31 21:31:15,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 517}
2017-12-31 21:31:15,016 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,023 : INFO : < 200 OK [3293]
2017-12-31 21:31:15,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 503}
2017-12-31 21:31:15,034 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,041 : INFO : < 200 OK [3300]
2017-12-31 21:31:15,047 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 518}
2017-12-31 21:31:15,051 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,057 : INFO : < 200 OK [3326]
2017-12-31 21:31:15,063 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 504}
2017-12-31 21:31:15,068 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,076 : INFO : < 200 OK [3302]
2017-12-31 21:31:15,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 519}
2017-12-31 21:31:15,088 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,097 : INFO : < 200 OK [3297]
2017-12-31 21:31:15,104 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 525}
2017-12-31 21:31:15,108 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,116 : INFO : < 200 OK [3314]
2017-12-31 21:31:15,123 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 520}
2017-12-31 21:31:15,129 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,135 : INFO : < 200 OK [3345]
2017-12-31 21:31:15,141 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 526}
2017-12-31 21:31:15,146 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,153 : INFO : < 200 OK [3338]
2017-12-31 21:31:15,158 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 521}
2017-12-31 21:31:15,162 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,169 : INFO : < 200 OK [3325]
2017-12-31 21:31:15,174 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 527}
2017-12-31 21:31:15,177 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,183 : INFO : < 200 OK [3322]
2017-12-31 21:31:15,188 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 522}
2017-12-31 21:31:15,192 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,198 : INFO : < 200 OK [3334]
2017-12-31 21:31:15,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 528}
2017-12-31 21:31:15,207 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,214 : INFO : < 200 OK [3325]
2017-12-31 21:31:15,219 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 523}
2017-12-31 21:31:15,222 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,228 : INFO : < 200 OK [3278]
2017-12-31 21:31:15,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 384}
2017-12-31 21:31:15,236 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,242 : INFO : < 200 OK [3290]
2017-12-31 21:31:15,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 529}
2017-12-31 21:31:15,250 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,256 : INFO : < 200 OK [3299]
2017-12-31 21:31:15,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 110}
2017-12-31 21:31:15,264 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,270 : INFO : < 200 OK [3288]
2017-12-31 21:31:15,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 141}
2017-12-31 21:31:15,279 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,285 : INFO : < 200 OK [3314]
2017-12-31 21:31:15,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 524}
2017-12-31 21:31:15,296 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,302 : INFO : < 200 OK [3321]
2017-12-31 21:31:15,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 530}
2017-12-31 21:31:15,310 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,316 : INFO : < 200 OK [3291]
2017-12-31 21:31:15,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 545}
2017-12-31 21:31:15,325 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,330 : INFO : < 200 OK [3295]
2017-12-31 21:31:15,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 531}
2017-12-31 21:31:15,338 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,342 : INFO : < 200 OK [3311]
2017-12-31 21:31:15,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 546}
2017-12-31 21:31:15,350 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,355 : INFO : < 200 OK [3303]
2017-12-31 21:31:15,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 532}
2017-12-31 21:31:15,362 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,368 : INFO : < 200 OK [3305]
2017-12-31 21:31:15,372 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 407}
2017-12-31 21:31:15,376 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,381 : INFO : < 200 OK [3280]

2017-12-31 21:31:15,385 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 547}
2017-12-31 21:31:15,388 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,394 : INFO : < 200 OK [3306]
2017-12-31 21:31:15,399 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 533}
2017-12-31 21:31:15,403 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,411 : INFO : < 200 OK [3291]
2017-12-31 21:31:15,415 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 548}
2017-12-31 21:31:15,419 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,424 : INFO : < 200 OK [3302]
2017-12-31 21:31:15,429 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 534}
2017-12-31 21:31:15,433 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,439 : INFO : < 200 OK [3309]
2017-12-31 21:31:15,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 371}
2017-12-31 21:31:15,446 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,452 : INFO : < 200 OK [3282]
2017-12-31 21:31:15,456 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 549}
2017-12-31 21:31:15,459 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,465 : INFO : < 200 OK [3296]
2017-12-31 21:31:15,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 535}
2017-12-31 21:31:15,473 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,479 : INFO : < 200 OK [3323]
2017-12-31 21:31:15,484 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 550}
2017-12-31 21:31:15,487 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,492 : INFO : < 200 OK [3279]
2017-12-31 21:31:15,497 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 536}
2017-12-31 21:31:15,500 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,505 : INFO : < 200 OK [3299]
2017-12-31 21:31:15,511 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 551}
2017-12-31 21:31:15,515 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,521 : INFO : < 200 OK [3324]
2017-12-31 21:31:15,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 537}
2017-12-31 21:31:15,531 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,537 : INFO : < 200 OK [3284]
2017-12-31 21:31:15,542 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 289}
2017-12-31 21:31:15,546 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,552 : INFO : < 200 OK [3331]
2017-12-31 21:31:15,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 552}
2017-12-31 21:31:15,561 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,566 : INFO : < 200 OK [3293]
2017-12-31 21:31:15,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 538}
2017-12-31 21:31:15,575 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,580 : INFO : < 200 OK [3331]
2017-12-31 21:31:15,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 553}
2017-12-31 21:31:15,588 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,594 : INFO : < 200 OK [3283]
2017-12-31 21:31:15,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 539}
2017-12-31 21:31:15,604 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,610 : INFO : < 200 OK [3300]
2017-12-31 21:31:15,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 554}
2017-12-31 21:31:15,618 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,624 : INFO : < 200 OK [3300]
2017-12-31 21:31:15,628 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 156}
2017-12-31 21:31:15,631 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,637 : INFO : < 200 OK [3343]
2017-12-31 21:31:15,642 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 540}
2017-12-31 21:31:15,645 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,650 : INFO : < 200 OK [3305]
2017-12-31 21:31:15,654 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 555}
2017-12-31 21:31:15,656 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,662 : INFO : < 200 OK [3295]
2017-12-31 21:31:15,666 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 541}
2017-12-31 21:31:15,669 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,675 : INFO : < 200 OK [3362]
2017-12-31 21:31:15,681 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 142}
2017-12-31 21:31:15,685 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,692 : INFO : < 200 OK [3329]
2017-12-31 21:31:15,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 556}
2017-12-31 21:31:15,702 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,707 : INFO : < 200 OK [3290]
2017-12-31 21:31:15,713 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 542}
2017-12-31 21:31:15,716 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,722 : INFO : < 200 OK [3316]

2017-12-31 21:31:15,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 557}
2017-12-31 21:31:15,730 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,735 : INFO : < 200 OK [3307]
2017-12-31 21:31:15,739 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 543}
2017-12-31 21:31:15,742 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,747 : INFO : < 200 OK [3369]
2017-12-31 21:31:15,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 558}
2017-12-31 21:31:15,755 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,760 : INFO : < 200 OK [3323]
2017-12-31 21:31:15,765 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 544}
2017-12-31 21:31:15,769 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,775 : INFO : < 200 OK [3352]
2017-12-31 21:31:15,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 559}
2017-12-31 21:31:15,786 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,792 : INFO : < 200 OK [3331]
2017-12-31 21:31:15,798 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 565}
2017-12-31 21:31:15,800 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,806 : INFO : < 200 OK [3278]
2017-12-31 21:31:15,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 387}
2017-12-31 21:31:15,814 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,819 : INFO : < 200 OK [3285]
2017-12-31 21:31:15,825 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 560}
2017-12-31 21:31:15,828 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,834 : INFO : < 200 OK [3327]
2017-12-31 21:31:15,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 566}
2017-12-31 21:31:15,841 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,847 : INFO : < 200 OK [3327]
2017-12-31 21:31:15,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 561}
2017-12-31 21:31:15,854 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,860 : INFO : < 200 OK [3278]
2017-12-31 21:31:15,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 567}
2017-12-31 21:31:15,867 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,873 : INFO : < 200 OK [3299]
2017-12-31 21:31:15,878 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 562}
2017-12-31 21:31:15,881 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,887 : INFO : < 200 OK [3319]
2017-12-31 21:31:15,890 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 568}
2017-12-31 21:31:15,894 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,899 : INFO : < 200 OK [3286]
2017-12-31 21:31:15,903 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 563}
2017-12-31 21:31:15,906 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,911 : INFO : < 200 OK [3357]
2017-12-31 21:31:15,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 569}
2017-12-31 21:31:15,919 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,924 : INFO : < 200 OK [3333]
2017-12-31 21:31:15,929 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 564}
2017-12-31 21:31:15,931 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,937 : INFO : < 200 OK [3300]
2017-12-31 21:31:15,941 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 570}
2017-12-31 21:31:15,944 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,951 : INFO : < 200 OK [3297]
2017-12-31 21:31:15,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 585}
2017-12-31 21:31:15,961 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,967 : INFO : < 200 OK [3288]
2017-12-31 21:31:15,973 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 571}
2017-12-31 21:31:15,977 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,983 : INFO : < 200 OK [3300]
2017-12-31 21:31:15,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 586}
2017-12-31 21:31:15,992 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:15,998 : INFO : < 200 OK [3286]
2017-12-31 21:31:16,004 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 572}
2017-12-31 21:31:16,008 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:16,015 : INFO : < 200 OK [3336]
2017-12-31 21:31:16,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 587}
2017-12-31 21:31:16,025 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:16,032 : INFO : < 200 OK [3295]
2017-12-31 21:31:16,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1000, '_0n0': 140}
2017-12-31 21:31:16,042 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:16,048 : INFO : < 200 OK [3335]
2017-12-31 21:31:16,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 573}
2017-12-31 21:31:16,057 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,063 : INFO : < 200 OK [3306]

2017-12-31 21:31:16,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 588}
2017-12-31 21:31:16,072 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,078 : INFO : < 200 OK [3324]
2017-12-31 21:31:16,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 81}
2017-12-31 21:31:16,087 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:16,093 : INFO : < 200 OK [3287]
2017-12-31 21:31:16,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 433}
2017-12-31 21:31:16,102 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,108 : INFO : < 200 OK [3322]
2017-12-31 21:31:16,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 66}
2017-12-31 21:31:16,117 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:16,123 : INFO : < 200 OK [3288]
2017-12-31 21:31:16,128 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 428}
2017-12-31 21:31:16,132 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,140 : INFO : < 200 OK [3273]
2017-12-31 21:31:16,146 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 574}
2017-12-31 21:31:16,151 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,157 : INFO : < 200 OK [3319]
2017-12-31 21:31:16,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 589}
2017-12-31 21:31:16,167 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,174 : INFO : < 200 OK [3282]
2017-12-31 21:31:16,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 575}
2017-12-31 21:31:16,182 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,189 : INFO : < 200 OK [3314]
2017-12-31 21:31:16,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 264}
2017-12-31 21:31:16,197 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,204 : INFO : < 200 OK [3305]
2017-12-31 21:31:16,209 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 306}
2017-12-31 21:31:16,213 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,220 : INFO : < 200 OK [3305]
2017-12-31 21:31:16,225 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 590}
2017-12-31 21:31:16,229 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,235 : INFO : < 200 OK [3319]
2017-12-31 21:31:16,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 431}
2017-12-31 21:31:16,244 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,250 : INFO : < 200 OK [3278]
2017-12-31 21:31:16,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 576}
2017-12-31 21:31:16,258 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,264 : INFO : < 200 OK [3322]
2017-12-31 21:31:16,269 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 83}
2017-12-31 21:31:16,274 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:16,280 : INFO : < 200 OK [3297]
2017-12-31 21:31:16,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 591}
2017-12-31 21:31:16,289 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,296 : INFO : < 200 OK [3326]
2017-12-31 21:31:16,303 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 452}
2017-12-31 21:31:16,306 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,314 : INFO : < 200 OK [3313]
2017-12-31 21:31:16,319 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 68}
2017-12-31 21:31:16,323 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:16,329 : INFO : < 200 OK [3288]
2017-12-31 21:31:16,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 577}
2017-12-31 21:31:16,339 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,345 : INFO : < 200 OK [3280]
2017-12-31 21:31:16,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 592}
2017-12-31 21:31:16,354 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,361 : INFO : < 200 OK [3328]
2017-12-31 21:31:16,366 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 439}
2017-12-31 21:31:16,370 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,376 : INFO : < 200 OK [3313]
2017-12-31 21:31:16,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 454}
2017-12-31 21:31:16,386 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,393 : INFO : < 200 OK [3309]
2017-12-31 21:31:16,398 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 578}
2017-12-31 21:31:16,402 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,408 : INFO : < 200 OK [3335]
2017-12-31 21:31:16,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 456}
2017-12-31 21:31:16,417 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,423 : INFO : < 200 OK [3334]
2017-12-31 21:31:16,428 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 457}
2017-12-31 21:31:16,432 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,438 : INFO : < 200 OK [3317]

2017-12-31 21:31:16,444 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 308}
2017-12-31 21:31:16,447 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,452 : INFO : < 200 OK [3313]
2017-12-31 21:31:16,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 85}
2017-12-31 21:31:16,462 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:16,468 : INFO : < 200 OK [3289]
2017-12-31 21:31:16,474 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 309}
2017-12-31 21:31:16,478 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,484 : INFO : < 200 OK [3324]
2017-12-31 21:31:16,490 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 593}
2017-12-31 21:31:16,494 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,503 : INFO : < 200 OK [3296]
2017-12-31 21:31:16,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 146}
2017-12-31 21:31:16,514 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,520 : INFO : < 200 OK [3310]
2017-12-31 21:31:16,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 579}
2017-12-31 21:31:16,531 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,537 : INFO : < 200 OK [3327]
2017-12-31 21:31:16,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 310}
2017-12-31 21:31:16,547 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,554 : INFO : < 200 OK [3340]
2017-12-31 21:31:16,560 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 460}
2017-12-31 21:31:16,564 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,570 : INFO : < 200 OK [3325]
2017-12-31 21:31:16,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 594}
2017-12-31 21:31:16,580 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,586 : INFO : < 200 OK [3285]
2017-12-31 21:31:16,591 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 580}
2017-12-31 21:31:16,595 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,601 : INFO : < 200 OK [3333]
2017-12-31 21:31:16,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 461}
2017-12-31 21:31:16,610 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,615 : INFO : < 200 OK [3281]
2017-12-31 21:31:16,620 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 398}
2017-12-31 21:31:16,623 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,628 : INFO : < 200 OK [3298]
2017-12-31 21:31:16,633 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 163}
2017-12-31 21:31:16,638 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,644 : INFO : < 200 OK [3295]
2017-12-31 21:31:16,650 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 595}
2017-12-31 21:31:16,653 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,660 : INFO : < 200 OK [3306]
2017-12-31 21:31:16,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 155}
2017-12-31 21:31:16,668 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,673 : INFO : < 200 OK [3307]
2017-12-31 21:31:16,678 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 208}
2017-12-31 21:31:16,681 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,687 : INFO : < 200 OK [3354]
2017-12-31 21:31:16,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 413}
2017-12-31 21:31:16,696 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,701 : INFO : < 200 OK [3331]
2017-12-31 21:31:16,706 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 317}
2017-12-31 21:31:16,710 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,715 : INFO : < 200 OK [3319]
2017-12-31 21:31:16,720 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 95}
2017-12-31 21:31:16,724 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:16,729 : INFO : < 200 OK [3289]
2017-12-31 21:31:16,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 332}
2017-12-31 21:31:16,737 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,742 : INFO : < 200 OK [3299]
2017-12-31 21:31:16,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 90}
2017-12-31 21:31:16,750 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:16,756 : INFO : < 200 OK [3278]
2017-12-31 21:31:16,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 164}
2017-12-31 21:31:16,764 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,769 : INFO : < 200 OK [3305]
2017-12-31 21:31:16,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 214}
2017-12-31 21:31:16,777 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,782 : INFO : < 200 OK [3289]
2017-12-31 21:31:16,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 581}
2017-12-31 21:31:16,790 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,796 : INFO : < 200 OK [3283]

2017-12-31 21:31:16,802 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 596}
2017-12-31 21:31:16,806 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,813 : INFO : < 200 OK [3312]
2017-12-31 21:31:16,818 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 582}
2017-12-31 21:31:16,821 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,827 : INFO : < 200 OK [3320]
2017-12-31 21:31:16,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 451}
2017-12-31 21:31:16,835 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,840 : INFO : < 200 OK [3308]
2017-12-31 21:31:16,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 466}
2017-12-31 21:31:16,848 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,853 : INFO : < 200 OK [3342]
2017-12-31 21:31:16,857 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 270}
2017-12-31 21:31:16,860 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,865 : INFO : < 200 OK [3329]
2017-12-31 21:31:16,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 597}
2017-12-31 21:31:16,872 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,878 : INFO : < 200 OK [3332]
2017-12-31 21:31:16,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 583}
2017-12-31 21:31:16,885 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,889 : INFO : < 200 OK [3323]
2017-12-31 21:31:16,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 99}
2017-12-31 21:31:16,897 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:16,903 : INFO : < 200 OK [3298]
2017-12-31 21:31:16,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 319}
2017-12-31 21:31:16,912 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,918 : INFO : < 200 OK [3275]
2017-12-31 21:31:16,924 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 100}
2017-12-31 21:31:16,929 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,934 : INFO : < 200 OK [3314]
2017-12-31 21:31:16,939 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 151}
2017-12-31 21:31:16,942 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,948 : INFO : < 200 OK [3294]
2017-12-31 21:31:16,954 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 598}
2017-12-31 21:31:16,958 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,964 : INFO : < 200 OK [3290]
2017-12-31 21:31:16,969 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 584}
2017-12-31 21:31:16,973 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,979 : INFO : < 200 OK [3318]
2017-12-31 21:31:16,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 599}
2017-12-31 21:31:16,988 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:16,994 : INFO : < 200 OK [3330]
2017-12-31 21:31:17,000 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 320}
2017-12-31 21:31:17,003 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,009 : INFO : < 200 OK [3313]
2017-12-31 21:31:17,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 469}
2017-12-31 21:31:17,017 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,023 : INFO : < 200 OK [3305]
2017-12-31 21:31:17,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 470}
2017-12-31 21:31:17,032 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,038 : INFO : < 200 OK [3300]
2017-12-31 21:31:17,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 605}
2017-12-31 21:31:17,048 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,054 : INFO : < 200 OK [3290]
2017-12-31 21:31:17,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 600}
2017-12-31 21:31:17,062 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,068 : INFO : < 200 OK [3304]
2017-12-31 21:31:17,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 416}
2017-12-31 21:31:17,077 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,082 : INFO : < 200 OK [3352]
2017-12-31 21:31:17,087 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 335}
2017-12-31 21:31:17,090 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,096 : INFO : < 200 OK [3305]
2017-12-31 21:31:17,101 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 606}
2017-12-31 21:31:17,105 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,111 : INFO : < 200 OK [3327]
2017-12-31 21:31:17,117 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 117}
2017-12-31 21:31:17,122 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,129 : INFO : < 200 OK [3313]
2017-12-31 21:31:17,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 12}
2017-12-31 21:31:17,138 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:17,146 : INFO : < 200 OK [3339]

2017-12-31 21:31:17,150 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 478}
2017-12-31 21:31:17,154 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,160 : INFO : < 200 OK [3301]
2017-12-31 21:31:17,165 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 506}
2017-12-31 21:31:17,168 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,174 : INFO : < 200 OK [3306]
2017-12-31 21:31:17,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 103}
2017-12-31 21:31:17,183 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,189 : INFO : < 200 OK [3341]
2017-12-31 21:31:17,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 7}
2017-12-31 21:31:17,197 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:17,203 : INFO : < 200 OK [3223]
2017-12-31 21:31:17,209 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 601}
2017-12-31 21:31:17,213 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,219 : INFO : < 200 OK [3315]
2017-12-31 21:31:17,224 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 336}
2017-12-31 21:31:17,228 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,234 : INFO : < 200 OK [3328]
2017-12-31 21:31:17,239 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 168}
2017-12-31 21:31:17,242 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,248 : INFO : < 200 OK [3316]
2017-12-31 21:31:17,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 322}
2017-12-31 21:31:17,256 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,262 : INFO : < 200 OK [3321]
2017-12-31 21:31:17,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 418}
2017-12-31 21:31:17,271 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,277 : INFO : < 200 OK [3328]
2017-12-31 21:31:17,281 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 509}
2017-12-31 21:31:17,284 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,290 : INFO : < 200 OK [3307]
2017-12-31 21:31:17,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 607}
2017-12-31 21:31:17,297 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,303 : INFO : < 200 OK [3314]
2017-12-31 21:31:17,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 169}
2017-12-31 21:31:17,310 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,315 : INFO : < 200 OK [3289]
2017-12-31 21:31:17,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 8}
2017-12-31 21:31:17,323 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:17,329 : INFO : < 200 OK [3318]
2017-12-31 21:31:17,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 602}
2017-12-31 21:31:17,338 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,344 : INFO : < 200 OK [3346]
2017-12-31 21:31:17,349 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 608}
2017-12-31 21:31:17,352 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,360 : INFO : < 200 OK [3280]
2017-12-31 21:31:17,365 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 603}
2017-12-31 21:31:17,369 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,374 : INFO : < 200 OK [3328]
2017-12-31 21:31:17,380 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 512}
2017-12-31 21:31:17,384 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,390 : INFO : < 200 OK [3282]
2017-12-31 21:31:17,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 485}
2017-12-31 21:31:17,400 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,406 : INFO : < 200 OK [3345]
2017-12-31 21:31:17,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 338}
2017-12-31 21:31:17,414 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,420 : INFO : < 200 OK [3280]
2017-12-31 21:31:17,425 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 121}
2017-12-31 21:31:17,428 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,434 : INFO : < 200 OK [3316]
2017-12-31 21:31:17,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 170}
2017-12-31 21:31:17,441 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,446 : INFO : < 200 OK [3290]
2017-12-31 21:31:17,451 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 108}
2017-12-31 21:31:17,455 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,460 : INFO : < 200 OK [3316]
2017-12-31 21:31:17,464 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 513}
2017-12-31 21:31:17,467 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,473 : INFO : < 200 OK [3283]
2017-12-31 21:31:17,477 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 339}
2017-12-31 21:31:17,480 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,485 : INFO : < 200 OK [3313]

2017-12-31 21:31:17,490 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 177}
2017-12-31 21:31:17,493 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,498 : INFO : < 200 OK [3287]
2017-12-31 21:31:17,502 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 178}
2017-12-31 21:31:17,505 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,511 : INFO : < 200 OK [3314]
2017-12-31 21:31:17,518 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 518}
2017-12-31 21:31:17,521 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,529 : INFO : < 200 OK [3318]
2017-12-31 21:31:17,533 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 179}
2017-12-31 21:31:17,536 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,541 : INFO : < 200 OK [3276]
2017-12-31 21:31:17,546 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 340}
2017-12-31 21:31:17,550 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,555 : INFO : < 200 OK [3338]
2017-12-31 21:31:17,560 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 525}
2017-12-31 21:31:17,563 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,568 : INFO : < 200 OK [3306]
2017-12-31 21:31:17,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 326}
2017-12-31 21:31:17,577 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,582 : INFO : < 200 OK [3310]
2017-12-31 21:31:17,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 194}
2017-12-31 21:31:17,590 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,595 : INFO : < 200 OK [3269]
2017-12-31 21:31:17,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 180}
2017-12-31 21:31:17,602 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,607 : INFO : < 200 OK [3313]
2017-12-31 21:31:17,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 195}
2017-12-31 21:31:17,614 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,619 : INFO : < 200 OK [3275]
2017-12-31 21:31:17,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 609}
2017-12-31 21:31:17,627 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,632 : INFO : < 200 OK [3309]
2017-12-31 21:31:17,637 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 297}
2017-12-31 21:31:17,640 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,646 : INFO : < 200 OK [3324]
2017-12-31 21:31:17,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 528}
2017-12-31 21:31:17,657 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,663 : INFO : < 200 OK [3317]
2017-12-31 21:31:17,667 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 529}
2017-12-31 21:31:17,671 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,677 : INFO : < 200 OK [3291]
2017-12-31 21:31:17,681 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 604}
2017-12-31 21:31:17,685 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,691 : INFO : < 200 OK [3328]
2017-12-31 21:31:17,695 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 125}
2017-12-31 21:31:17,698 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,703 : INFO : < 200 OK [3313]
2017-12-31 21:31:17,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 610}
2017-12-31 21:31:17,712 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,716 : INFO : < 200 OK [3333]
2017-12-31 21:31:17,721 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 341}
2017-12-31 21:31:17,724 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,729 : INFO : < 200 OK [3306]
2017-12-31 21:31:17,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 196}
2017-12-31 21:31:17,737 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,742 : INFO : < 200 OK [3273]
2017-12-31 21:31:17,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 112}
2017-12-31 21:31:17,749 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,753 : INFO : < 200 OK [3283]
2017-12-31 21:31:17,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 197}
2017-12-31 21:31:17,761 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,766 : INFO : < 200 OK [3294]
2017-12-31 21:31:17,772 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 38}
2017-12-31 21:31:17,775 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:17,783 : INFO : < 200 OK [3299]
2017-12-31 21:31:17,788 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 183}
2017-12-31 21:31:17,792 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,798 : INFO : < 200 OK [3339]
2017-12-31 21:31:17,803 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 531}
2017-12-31 21:31:17,807 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,812 : INFO : < 200 OK [3303]

2017-12-31 21:31:17,817 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 625}
2017-12-31 21:31:17,821 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,826 : INFO : < 200 OK [3288]
2017-12-31 21:31:17,831 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 327}
2017-12-31 21:31:17,835 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,840 : INFO : < 200 OK [3347]
2017-12-31 21:31:17,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 25}
2017-12-31 21:31:17,848 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:17,853 : INFO : < 200 OK [3294]
2017-12-31 21:31:17,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 547}
2017-12-31 21:31:17,861 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,867 : INFO : < 200 OK [3298]
2017-12-31 21:31:17,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 328}
2017-12-31 21:31:17,874 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,880 : INFO : < 200 OK [3288]
2017-12-31 21:31:17,885 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 199}
2017-12-31 21:31:17,888 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,893 : INFO : < 200 OK [3287]
2017-12-31 21:31:17,898 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 611}
2017-12-31 21:31:17,901 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,907 : INFO : < 200 OK [3303]
2017-12-31 21:31:17,912 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 185}
2017-12-31 21:31:17,915 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,920 : INFO : < 200 OK [3307]
2017-12-31 21:31:17,924 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 343}
2017-12-31 21:31:17,927 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,933 : INFO : < 200 OK [3306]
2017-12-31 21:31:17,937 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 29}
2017-12-31 21:31:17,940 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:17,945 : INFO : < 200 OK [3325]
2017-12-31 21:31:17,951 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 200}
2017-12-31 21:31:17,955 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,963 : INFO : < 200 OK [3277]
2017-12-31 21:31:17,968 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 626}
2017-12-31 21:31:17,971 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,978 : INFO : < 200 OK [3299]
2017-12-31 21:31:17,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 201}
2017-12-31 21:31:17,986 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:17,992 : INFO : < 200 OK [3324]
2017-12-31 21:31:17,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 44}
2017-12-31 21:31:18,000 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:18,006 : INFO : < 200 OK [3311]
2017-12-31 21:31:18,010 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 287}
2017-12-31 21:31:18,013 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,018 : INFO : < 200 OK [3327]
2017-12-31 21:31:18,022 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 187}
2017-12-31 21:31:18,025 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,030 : INFO : < 200 OK [3297]
2017-12-31 21:31:18,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 612}
2017-12-31 21:31:18,039 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,045 : INFO : < 200 OK [3305]
2017-12-31 21:31:18,050 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 345}
2017-12-31 21:31:18,054 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,060 : INFO : < 200 OK [3291]
2017-12-31 21:31:18,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 627}
2017-12-31 21:31:18,069 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,076 : INFO : < 200 OK [3309]
2017-12-31 21:31:18,081 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 613}
2017-12-31 21:31:18,085 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,091 : INFO : < 200 OK [3318]
2017-12-31 21:31:18,096 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 352}
2017-12-31 21:31:18,100 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,106 : INFO : < 200 OK [3328]
2017-12-31 21:31:18,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 243}
2017-12-31 21:31:18,113 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,119 : INFO : < 200 OK [3294]
2017-12-31 21:31:18,123 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 628}
2017-12-31 21:31:18,126 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,132 : INFO : < 200 OK [3311]
2017-12-31 21:31:18,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 614}
2017-12-31 21:31:18,140 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,145 : INFO : < 200 OK [3292]

2017-12-31 21:31:18,150 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 629}
2017-12-31 21:31:18,153 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,158 : INFO : < 200 OK [3314]
2017-12-31 21:31:18,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 615}
2017-12-31 21:31:18,167 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,173 : INFO : < 200 OK [3306]
2017-12-31 21:31:18,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 540}
2017-12-31 21:31:18,183 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,189 : INFO : < 200 OK [3297]
2017-12-31 21:31:18,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 630}
2017-12-31 21:31:18,197 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,202 : INFO : < 200 OK [3311]
2017-12-31 21:31:18,207 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 189}
2017-12-31 21:31:18,210 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,216 : INFO : < 200 OK [3340]
2017-12-31 21:31:18,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 616}
2017-12-31 21:31:18,224 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,229 : INFO : < 200 OK [3292]
2017-12-31 21:31:18,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 631}
2017-12-31 21:31:18,237 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,243 : INFO : < 200 OK [3298]
2017-12-31 21:31:18,248 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 244}
2017-12-31 21:31:18,252 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,257 : INFO : < 200 OK [3315]
2017-12-31 21:31:18,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 58}
2017-12-31 21:31:18,265 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:18,270 : INFO : < 200 OK [3338]
2017-12-31 21:31:18,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 190}
2017-12-31 21:31:18,277 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,282 : INFO : < 200 OK [3330]
2017-12-31 21:31:18,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 617}
2017-12-31 21:31:18,290 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,295 : INFO : < 200 OK [3275]
2017-12-31 21:31:18,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 632}
2017-12-31 21:31:18,303 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,308 : INFO : < 200 OK [3298]
2017-12-31 21:31:18,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 205}
2017-12-31 21:31:18,317 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,323 : INFO : < 200 OK [3333]
2017-12-31 21:31:18,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 618}
2017-12-31 21:31:18,333 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,339 : INFO : < 200 OK [3326]
2017-12-31 21:31:18,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 432}
2017-12-31 21:31:18,348 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,353 : INFO : < 200 OK [3290]
2017-12-31 21:31:18,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 354}
2017-12-31 21:31:18,361 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,367 : INFO : < 200 OK [3277]
2017-12-31 21:31:18,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 349}
2017-12-31 21:31:18,375 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,380 : INFO : < 200 OK [3300]
2017-12-31 21:31:18,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 633}
2017-12-31 21:31:18,388 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,393 : INFO : < 200 OK [3277]
2017-12-31 21:31:18,397 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 76}
2017-12-31 21:31:18,400 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:18,406 : INFO : < 200 OK [3329]
2017-12-31 21:31:18,412 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 191}
2017-12-31 21:31:18,415 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,422 : INFO : < 200 OK [3269]
2017-12-31 21:31:18,427 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 260}
2017-12-31 21:31:18,431 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,436 : INFO : < 200 OK [3297]
2017-12-31 21:31:18,441 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 355}
2017-12-31 21:31:18,444 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,450 : INFO : < 200 OK [3296]
2017-12-31 21:31:18,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 153}
2017-12-31 21:31:18,459 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,464 : INFO : < 200 OK [3327]
2017-12-31 21:31:18,468 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 561}
2017-12-31 21:31:18,471 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,477 : INFO : < 200 OK [3270]

2017-12-31 21:31:18,482 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 619}
2017-12-31 21:31:18,485 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,490 : INFO : < 200 OK [3331]
2017-12-31 21:31:18,495 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 77}
2017-12-31 21:31:18,498 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:18,502 : INFO : < 200 OK [3303]
2017-12-31 21:31:18,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 634}
2017-12-31 21:31:18,510 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,515 : INFO : < 200 OK [3287]
2017-12-31 21:31:18,519 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`belong to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 986, '_0n0': 572}
2017-12-31 21:31:18,522 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:18,527 : INFO : < 200 OK [3328]

In [77]:
institute_dict = {}
for created_by in set(data.created_by):
    institute_dict[created_by] = Node("Institute", name=created_by)
    graph.create(institute_dict[created_by])

2017-12-31 21:31:18,766 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'emlyon business school'}}
2017-12-31 21:31:18,769 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2017-12-31 21:31:18,775 : INFO : < 200 OK [1385]
2017-12-31 21:31:18,778 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Shanghai Jiao Tong University'}}
2017-12-31 21:31:18,781 : INFO : > POST http://localhost:7474/db/data/cypher [106]
2017-12-31 21:31:18,786 : INFO : < 200 OK [1392]
2017-12-31 21:31:18,790 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University System of Georgia'}}
2017-12-31 21:31:18,793 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2017-12-31 21:31:18,798 : INFO : < 200 OK [1391]
2017-12-31 21:31:18,802 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Technical University of Denmark (DTU)'}}
2017-12-31 21:31:18,806 : INFO : > POST http://localhost:7474/db/data/cypher [114]
2017-12-31 21:31:18,812 : INFO : < 200 OK [1400]
2017-12-31 21:31:18,815 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Columbia University'}}
2017-12-31 21:31:18,819 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:18,823 : INFO : < 200 OK [1382]
2017-12-31 21:31:18,828 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Zurich'}}
2017-12-31 21:31:18,831 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:18,837 : INFO : < 200 OK [1383]
2017-12-31 21:31:18,842 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Rutgers the State University of New Jersey'}}
2017-12-31 21:31:18,845 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2017-12-31 21:31:18,851 : INFO : < 200 OK [1405]
2017-12-31 21:31:18,854 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Sydney'}}
2017-12-31 21:31:18,857 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2017-12-31 21:31:18,862 : INFO : < 200 OK [1387]
2017-12-31 21:31:18,865 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Pennsylvania'}}
2017-12-31 21:31:18,868 : INFO : > POST http://localhost:7474/db/data/cypher [103]
2017-12-31 21:31:18,873 : INFO : < 200 OK [1389]
2017-12-31 21:31:18,877 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'UNSW Australia (The University of New South Wales)'}}
2017-12-31 21:31:18,880 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:31:18,886 : INFO : < 200 OK [1413]
2017-12-31 21:31:18,889 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Toronto'}}
2017-12-31 21:31:18,893 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:18,898 : INFO : < 200 OK [1384]
2017-12-31 21:31:18,903 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Stanford University, The University of British Columbia'}}
2017-12-31 21:31:18,906 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:31:18,912 : INFO : < 200 OK [1418]
2017-12-31 21:31:18,915 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Maryland, College Park'}}
2017-12-31 21:31:18,918 : INFO : > POST http://localhost:7474/db/data/cypher [113]
2017-12-31 21:31:18,924 : INFO : < 200 OK [1399]
2017-12-31 21:31:18,928 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Tecnológico de Monterrey'}}
2017-12-31 21:31:18,931 : INFO : > POST http://localhost:7474/db/data/cypher [106]
2017-12-31 21:31:18,937 : INFO : < 200 OK [1388]
2017-12-31 21:31:18,941 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'West Virginia University'}}
2017-12-31 21:31:18,944 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2017-12-31 21:31:18,950 : INFO : < 200 OK [1387]
2017-12-31 21:31:18,954 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'École normale supérieure'}}
2017-12-31 21:31:18,957 : INFO : > POST http://localhost:7474/db/data/cypher [111]
2017-12-31 21:31:18,962 : INFO : < 200 OK [1389]
2017-12-31 21:31:18,966 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Michigan State University'}}
2017-12-31 21:31:18,969 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2017-12-31 21:31:18,975 : INFO : < 200 OK [1388]
2017-12-31 21:31:18,979 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Yandex'}}
2017-12-31 21:31:18,982 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2017-12-31 21:31:18,988 : INFO : < 200 OK [1369]
2017-12-31 21:31:18,991 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The Hong Kong University of Science and Technology'}}
2017-12-31 21:31:18,994 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:31:18,999 : INFO : < 200 OK [1413]
2017-12-31 21:31:19,003 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The State University of New York'}}
2017-12-31 21:31:19,006 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2017-12-31 21:31:19,011 : INFO : < 200 OK [1395]
2017-12-31 21:31:19,014 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Michigan'}}
2017-12-31 21:31:19,017 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2017-12-31 21:31:19,022 : INFO : < 200 OK [1385]
2017-12-31 21:31:19,026 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'IBM'}}
2017-12-31 21:31:19,029 : INFO : > POST http://localhost:7474/db/data/cypher [80]
2017-12-31 21:31:19,034 : INFO : < 200 OK [1366]
2017-12-31 21:31:19,038 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Vanderbilt University'}}
2017-12-31 21:31:19,041 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:19,047 : INFO : < 200 OK [1384]
2017-12-31 21:31:19,051 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The Ohio State University'}}
2017-12-31 21:31:19,054 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2017-12-31 21:31:19,061 : INFO : < 200 OK [1388]
2017-12-31 21:31:19,065 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Intel'}}
2017-12-31 21:31:19,070 : INFO : > POST http://localhost:7474/db/data/cypher [82]
2017-12-31 21:31:19,077 : INFO : < 200 OK [1368]
2017-12-31 21:31:19,081 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'ESSEC Business School'}}
2017-12-31 21:31:19,084 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:19,089 : INFO : < 200 OK [1384]
2017-12-31 21:31:19,093 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'National Research University Higher School of Economics'}}
2017-12-31 21:31:19,096 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:31:19,102 : INFO : < 200 OK [1418]
2017-12-31 21:31:19,106 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Korea Advanced Institute of Science and Technology'}}
2017-12-31 21:31:19,109 : INFO : > POST http://localhost:7474/db/data/cypher [127]
2017-12-31 21:31:19,114 : INFO : < 200 OK [1413]
2017-12-31 21:31:19,119 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Johns Hopkins University, University of Colorado Boulder'}}
2017-12-31 21:31:19,122 : INFO : > POST http://localhost:7474/db/data/cypher [133]
2017-12-31 21:31:19,127 : INFO : < 200 OK [1419]
2017-12-31 21:31:19,131 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Emory University'}}
2017-12-31 21:31:19,134 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:19,140 : INFO : < 200 OK [1379]
2017-12-31 21:31:19,144 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Minnesota'}}
2017-12-31 21:31:19,148 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:19,153 : INFO : < 200 OK [1386]

2017-12-31 21:31:19,157 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Google Daydream Impact'}}
2017-12-31 21:31:19,160 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2017-12-31 21:31:19,166 : INFO : < 200 OK [1385]
2017-12-31 21:31:19,170 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of London, Goldsmiths, University of London'}}
2017-12-31 21:31:19,173 : INFO : > POST http://localhost:7474/db/data/cypher [131]
2017-12-31 21:31:19,178 : INFO : < 200 OK [1417]
2017-12-31 21:31:19,183 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The Pennsylvania State University'}}
2017-12-31 21:31:19,186 : INFO : > POST http://localhost:7474/db/data/cypher [110]
2017-12-31 21:31:19,192 : INFO : < 200 OK [1396]
2017-12-31 21:31:19,196 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Nanjing University'}}
2017-12-31 21:31:19,199 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:19,204 : INFO : < 200 OK [1381]
2017-12-31 21:31:19,207 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'deeplearning.ai'}}
2017-12-31 21:31:19,210 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:19,216 : INFO : < 200 OK [1378]
2017-12-31 21:31:19,221 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Melbourne'}}
2017-12-31 21:31:19,224 : INFO : > POST http://localhost:7474/db/data/cypher [104]
2017-12-31 21:31:19,230 : INFO : < 200 OK [1390]
2017-12-31 21:31:19,234 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Northwestern University'}}
2017-12-31 21:31:19,238 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:19,244 : INFO : < 200 OK [1386]
2017-12-31 21:31:19,248 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Rochester'}}
2017-12-31 21:31:19,251 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:19,256 : INFO : < 200 OK [1386]
2017-12-31 21:31:19,260 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Amsterdam'}}
2017-12-31 21:31:19,263 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:19,269 : INFO : < 200 OK [1386]
2017-12-31 21:31:19,272 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Chicago'}}
2017-12-31 21:31:19,275 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2017-12-31 21:31:19,284 : INFO : < 200 OK [1388]
2017-12-31 21:31:19,288 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Colorado System'}}
2017-12-31 21:31:19,291 : INFO : > POST http://localhost:7474/db/data/cypher [106]
2017-12-31 21:31:19,297 : INFO : < 200 OK [1392]
2017-12-31 21:31:19,301 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Icahn School of Medicine at Mount Sinai'}}
2017-12-31 21:31:19,304 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2017-12-31 21:31:19,309 : INFO : < 200 OK [1402]
2017-12-31 21:31:19,313 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Georgia Institute of Technology'}}
2017-12-31 21:31:19,316 : INFO : > POST http://localhost:7474/db/data/cypher [108]
2017-12-31 21:31:19,321 : INFO : < 200 OK [1394]
2017-12-31 21:31:19,324 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Yonsei University'}}
2017-12-31 21:31:19,327 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:19,333 : INFO : < 200 OK [1380]
2017-12-31 21:31:19,337 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Edinburgh'}}
2017-12-31 21:31:19,340 : INFO : > POST http://localhost:7474/db/data/cypher [104]
2017-12-31 21:31:19,346 : INFO : < 200 OK [1390]
2017-12-31 21:31:19,350 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of New Mexico'}}
2017-12-31 21:31:19,353 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2017-12-31 21:31:19,358 : INFO : < 200 OK [1387]
2017-12-31 21:31:19,361 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Wesleyan University'}}
2017-12-31 21:31:19,364 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:19,369 : INFO : < 200 OK [1382]
2017-12-31 21:31:19,373 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Autodesk'}}
2017-12-31 21:31:19,376 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:19,381 : INFO : < 200 OK [1371]
2017-12-31 21:31:19,384 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Edinburgh, Universidad ORT Uruguay'}}
2017-12-31 21:31:19,387 : INFO : > POST http://localhost:7474/db/data/cypher [129]
2017-12-31 21:31:19,393 : INFO : < 200 OK [1415]
2017-12-31 21:31:19,396 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Universitat Autònoma de Barcelona'}}
2017-12-31 21:31:19,400 : INFO : > POST http://localhost:7474/db/data/cypher [115]
2017-12-31 21:31:19,405 : INFO : < 200 OK [1397]
2017-12-31 21:31:19,409 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Virginia'}}
2017-12-31 21:31:19,413 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2017-12-31 21:31:19,419 : INFO : < 200 OK [1385]
2017-12-31 21:31:19,424 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Washington'}}
2017-12-31 21:31:19,428 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2017-12-31 21:31:19,434 : INFO : < 200 OK [1387]
2017-12-31 21:31:19,438 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'McMaster University'}}
2017-12-31 21:31:19,443 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:19,448 : INFO : < 200 OK [1382]
2017-12-31 21:31:19,451 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Illinois at Urbana-Champaign'}}
2017-12-31 21:31:19,455 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2017-12-31 21:31:19,460 : INFO : < 200 OK [1405]
2017-12-31 21:31:19,464 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'New York University Tandon School of Engineering'}}
2017-12-31 21:31:19,467 : INFO : > POST http://localhost:7474/db/data/cypher [125]
2017-12-31 21:31:19,473 : INFO : < 200 OK [1411]
2017-12-31 21:31:19,477 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Rice University'}}
2017-12-31 21:31:19,480 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:19,485 : INFO : < 200 OK [1378]
2017-12-31 21:31:19,488 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'EIT Digital '}}
2017-12-31 21:31:19,491 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:19,496 : INFO : < 200 OK [1375]
2017-12-31 21:31:19,500 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of California, San Diego, National Research University Higher School of Economics'}}
2017-12-31 21:31:19,504 : INFO : > POST http://localhost:7474/db/data/cypher [169]
2017-12-31 21:31:19,509 : INFO : < 200 OK [1455]
2017-12-31 21:31:19,513 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of North Carolina at Chapel Hill, The University of Edinburgh'}}
2017-12-31 21:31:19,516 : INFO : > POST http://localhost:7474/db/data/cypher [153]
2017-12-31 21:31:19,521 : INFO : < 200 OK [1439]
2017-12-31 21:31:19,525 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Tokyo'}}
2017-12-31 21:31:19,527 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:19,532 : INFO : < 200 OK [1386]
2017-12-31 21:31:19,536 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'National Research Tomsk State University'}}
2017-12-31 21:31:19,539 : INFO : > POST http://localhost:7474/db/data/cypher [117]

2017-12-31 21:31:19,544 : INFO : < 200 OK [1403]
2017-12-31 21:31:19,548 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Johns Hopkins University'}}
2017-12-31 21:31:19,550 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2017-12-31 21:31:19,555 : INFO : < 200 OK [1387]
2017-12-31 21:31:19,559 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'California Institute of the Arts'}}
2017-12-31 21:31:19,562 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2017-12-31 21:31:19,567 : INFO : < 200 OK [1395]
2017-12-31 21:31:19,570 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Alberta'}}
2017-12-31 21:31:19,573 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:19,578 : INFO : < 200 OK [1384]
2017-12-31 21:31:19,582 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Princeton University'}}
2017-12-31 21:31:19,587 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:19,593 : INFO : < 200 OK [1383]
2017-12-31 21:31:19,597 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Universitat Pompeu Fabra of Barcelona, Stanford University'}}
2017-12-31 21:31:19,602 : INFO : > POST http://localhost:7474/db/data/cypher [135]
2017-12-31 21:31:19,608 : INFO : < 200 OK [1421]
2017-12-31 21:31:19,613 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Hebrew University of Jerusalem'}}
2017-12-31 21:31:19,616 : INFO : > POST http://localhost:7474/db/data/cypher [107]
2017-12-31 21:31:19,622 : INFO : < 200 OK [1393]
2017-12-31 21:31:19,626 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Institut Mines-Télécom'}}
2017-12-31 21:31:19,629 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2017-12-31 21:31:19,634 : INFO : < 200 OK [1387]
2017-12-31 21:31:19,638 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'PwC'}}
2017-12-31 21:31:19,641 : INFO : > POST http://localhost:7474/db/data/cypher [80]
2017-12-31 21:31:19,648 : INFO : < 200 OK [1366]
2017-12-31 21:31:19,651 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'MongoDB Inc.'}}
2017-12-31 21:31:19,654 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:19,659 : INFO : < 200 OK [1375]
2017-12-31 21:31:19,663 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Colorado Boulder'}}
2017-12-31 21:31:19,666 : INFO : > POST http://localhost:7474/db/data/cypher [107]
2017-12-31 21:31:19,670 : INFO : < 200 OK [1393]
2017-12-31 21:31:19,674 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of California, Irvine'}}
2017-12-31 21:31:19,678 : INFO : > POST http://localhost:7474/db/data/cypher [109]
2017-12-31 21:31:19,683 : INFO : < 200 OK [1395]
2017-12-31 21:31:19,688 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of London'}}
2017-12-31 21:31:19,691 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:19,699 : INFO : < 200 OK [1383]
2017-12-31 21:31:19,703 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Stanford University'}}
2017-12-31 21:31:19,705 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:19,711 : INFO : < 200 OK [1382]
2017-12-31 21:31:19,715 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Cape Town'}}
2017-12-31 21:31:19,719 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:19,725 : INFO : < 200 OK [1386]
2017-12-31 21:31:19,728 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'CentraleSupélec'}}
2017-12-31 21:31:19,731 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:19,737 : INFO : < 200 OK [1379]
2017-12-31 21:31:19,741 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University at Buffalo, The State University of New York'}}
2017-12-31 21:31:19,744 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:31:19,750 : INFO : < 200 OK [1418]
2017-12-31 21:31:19,753 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of California, San Diego'}}
2017-12-31 21:31:19,756 : INFO : > POST http://localhost:7474/db/data/cypher [112]
2017-12-31 21:31:19,761 : INFO : < 200 OK [1398]
2017-12-31 21:31:19,765 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Duke University'}}
2017-12-31 21:31:19,767 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:19,773 : INFO : < 200 OK [1378]
2017-12-31 21:31:19,776 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Houston System'}}
2017-12-31 21:31:19,779 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2017-12-31 21:31:19,784 : INFO : < 200 OK [1391]
2017-12-31 21:31:19,788 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of Copenhagen'}}
2017-12-31 21:31:19,791 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2017-12-31 21:31:19,796 : INFO : < 200 OK [1387]
2017-12-31 21:31:19,801 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Google Cloud'}}
2017-12-31 21:31:19,804 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:19,812 : INFO : < 200 OK [1375]
2017-12-31 21:31:19,815 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of California, Davis'}}
2017-12-31 21:31:19,819 : INFO : > POST http://localhost:7474/db/data/cypher [108]
2017-12-31 21:31:19,824 : INFO : < 200 OK [1394]
2017-12-31 21:31:19,829 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Erasmus University Rotterdam'}}
2017-12-31 21:31:19,832 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2017-12-31 21:31:19,837 : INFO : < 200 OK [1391]
2017-12-31 21:31:19,841 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Indian School of Business'}}
2017-12-31 21:31:19,845 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2017-12-31 21:31:19,851 : INFO : < 200 OK [1388]
2017-12-31 21:31:19,854 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'The University of Melbourne, The Chinese University of Hong Kong'}}
2017-12-31 21:31:19,858 : INFO : > POST http://localhost:7474/db/data/cypher [141]
2017-12-31 21:31:19,863 : INFO : < 200 OK [1427]
2017-12-31 21:31:19,868 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Moscow Institute of Physics and Technology'}}
2017-12-31 21:31:19,871 : INFO : > POST http://localhost:7474/db/data/cypher [119]
2017-12-31 21:31:19,877 : INFO : < 200 OK [1405]
2017-12-31 21:31:19,881 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'École Polytechnique Fédérale de Lausanne'}}
2017-12-31 21:31:19,885 : INFO : > POST http://localhost:7474/db/data/cypher [132]
2017-12-31 21:31:19,890 : INFO : < 200 OK [1406]
2017-12-31 21:31:19,894 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Macquarie University'}}
2017-12-31 21:31:19,897 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:19,901 : INFO : < 200 OK [1383]
2017-12-31 21:31:19,905 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Eindhoven University of Technology'}}
2017-12-31 21:31:19,907 : INFO : > POST http://localhost:7474/db/data/cypher [111]
2017-12-31 21:31:19,912 : INFO : < 200 OK [1397]
2017-12-31 21:31:19,916 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'Cisco'}}
2017-12-31 21:31:19,919 : INFO : > POST http://localhost:7474/db/data/cypher [82]
2017-12-31 21:31:19,923 : INFO : < 200 OK [1368]
2017-12-31 21:31:19,927 : INFO : execute 'CREATE (_0:Institute {_0})\nRETURN _0' {'_0': {'name': 'University of California, Santa Cruz'}}
2017-12-31 21:31:19,930 : INFO : > POST http://localhost:7474/db/data/cypher [113]
2017-12-31 21:31:19,935 : INFO : < 200 OK [1399]

In [78]:
teach_dict = {}
for teach_by in set(data.teach_by):
    teach_dict[teach_by] = Node("Teacher", name=teach_by)
    graph.create(teach_dict[teach_by])

2017-12-31 21:31:20,168 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'ChengXiang Zhai'}}
2017-12-31 21:31:20,171 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:20,177 : INFO : < 200 OK [1376]
2017-12-31 21:31:20,181 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Williams'}}
2017-12-31 21:31:20,184 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:20,189 : INFO : < 200 OK [1375]
2017-12-31 21:31:20,193 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dmitry Altukhov'}}
2017-12-31 21:31:20,196 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:20,201 : INFO : < 200 OK [1376]
2017-12-31 21:31:20,205 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Emil Akhmedov'}}
2017-12-31 21:31:20,208 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:20,213 : INFO : < 200 OK [1374]
2017-12-31 21:31:20,217 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Takeo Igarashi'}}
2017-12-31 21:31:20,221 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:20,227 : INFO : < 200 OK [1375]
2017-12-31 21:31:20,232 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mia Minnes'}}
2017-12-31 21:31:20,237 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:20,243 : INFO : < 200 OK [1371]
2017-12-31 21:31:20,247 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nguyen Gia Tuan'}}
2017-12-31 21:31:20,251 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:20,256 : INFO : < 200 OK [1376]
2017-12-31 21:31:20,260 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anton Konushin'}}
2017-12-31 21:31:20,263 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:20,268 : INFO : < 200 OK [1375]
2017-12-31 21:31:20,272 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vivek Sarkar'}}
2017-12-31 21:31:20,275 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:20,281 : INFO : < 200 OK [1373]
2017-12-31 21:31:20,285 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Virginie Galtier'}}
2017-12-31 21:31:20,288 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:20,293 : INFO : < 200 OK [1381]
2017-12-31 21:31:20,296 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Herbert J. Mattord, Ph.D., CISM, CISSP, CDP'}}
2017-12-31 21:31:20,299 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2017-12-31 21:31:20,304 : INFO : < 200 OK [1404]
2017-12-31 21:31:20,307 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Hartman'}}
2017-12-31 21:31:20,310 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:20,315 : INFO : < 200 OK [1374]
2017-12-31 21:31:20,319 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kenny Wong'}}
2017-12-31 21:31:20,323 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:20,329 : INFO : < 200 OK [1371]
2017-12-31 21:31:20,333 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel Romero'}}
2017-12-31 21:31:20,337 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:20,343 : INFO : < 200 OK [1374]
2017-12-31 21:31:20,347 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Aleksandar Prokopec'}}
2017-12-31 21:31:20,350 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:20,365 : INFO : < 200 OK [1384]
2017-12-31 21:31:20,370 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John Muschelli III '}}
2017-12-31 21:31:20,373 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:20,380 : INFO : < 200 OK [1380]
2017-12-31 21:31:20,385 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anne Bracy'}}
2017-12-31 21:31:20,389 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:20,396 : INFO : < 200 OK [1371]
2017-12-31 21:31:20,400 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tim McKay'}}
2017-12-31 21:31:20,404 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:20,410 : INFO : < 200 OK [1370]
2017-12-31 21:31:20,414 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nikita Kazeev'}}
2017-12-31 21:31:20,418 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:20,424 : INFO : < 200 OK [1374]
2017-12-31 21:31:20,430 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert Ghrist'}}
2017-12-31 21:31:20,433 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:20,439 : INFO : < 200 OK [1374]
2017-12-31 21:31:20,443 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Dunn'}}
2017-12-31 21:31:20,447 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:20,454 : INFO : < 200 OK [1371]
2017-12-31 21:31:20,458 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Bañeres'}}
2017-12-31 21:31:20,462 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:20,468 : INFO : < 200 OK [1375]
2017-12-31 21:31:20,472 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Charles Severance'}}
2017-12-31 21:31:20,476 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:20,481 : INFO : < 200 OK [1378]
2017-12-31 21:31:20,485 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Matthew Yee-King'}}
2017-12-31 21:31:20,489 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:20,495 : INFO : < 200 OK [1380]
2017-12-31 21:31:20,500 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Martin Vetterli'}}
2017-12-31 21:31:20,503 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:20,510 : INFO : < 200 OK [1376]
2017-12-31 21:31:20,514 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Aggelos K. Katsaggelos'}}
2017-12-31 21:31:20,517 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:20,523 : INFO : < 200 OK [1383]
2017-12-31 21:31:20,529 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Amarnath Gupta'}}
2017-12-31 21:31:20,532 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:20,538 : INFO : < 200 OK [1375]
2017-12-31 21:31:20,543 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Wentzlaff '}}
2017-12-31 21:31:20,546 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:20,552 : INFO : < 200 OK [1377]
2017-12-31 21:31:20,557 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jong-Moon Chung'}}
2017-12-31 21:31:20,560 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:20,566 : INFO : < 200 OK [1376]
2017-12-31 21:31:20,572 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Seong-Lyun Kim'}}
2017-12-31 21:31:20,577 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:20,582 : INFO : < 200 OK [1375]
2017-12-31 21:31:20,586 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr.  Margaret Anne Schedel'}}
2017-12-31 21:31:20,590 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2017-12-31 21:31:20,596 : INFO : < 200 OK [1387]
2017-12-31 21:31:20,600 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Martin Timmerman'}}
2017-12-31 21:31:20,604 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:20,610 : INFO : < 200 OK [1377]
2017-12-31 21:31:20,614 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ilkay Altintas'}}
2017-12-31 21:31:20,617 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:20,623 : INFO : < 200 OK [1375]

2017-12-31 21:31:20,627 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Laurent Franck'}}
2017-12-31 21:31:20,631 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:20,636 : INFO : < 200 OK [1375]
2017-12-31 21:31:20,640 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Damir Filipović'}}
2017-12-31 21:31:20,643 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:20,649 : INFO : < 200 OK [1377]
2017-12-31 21:31:20,653 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Poul Ejnar Sørensen'}}
2017-12-31 21:31:20,657 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2017-12-31 21:31:20,663 : INFO : < 200 OK [1381]
2017-12-31 21:31:20,667 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sudhir Voleti'}}
2017-12-31 21:31:20,671 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:20,683 : INFO : < 200 OK [1374]
2017-12-31 21:31:20,687 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Edward Chow'}}
2017-12-31 21:31:20,691 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:20,697 : INFO : < 200 OK [1372]
2017-12-31 21:31:20,701 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sergey Yudin'}}
2017-12-31 21:31:20,705 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:20,712 : INFO : < 200 OK [1373]
2017-12-31 21:31:20,717 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Greg Heileman'}}
2017-12-31 21:31:20,720 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:20,727 : INFO : < 200 OK [1374]
2017-12-31 21:31:20,731 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tim Roughgarden'}}
2017-12-31 21:31:20,734 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:20,740 : INFO : < 200 OK [1376]
2017-12-31 21:31:20,744 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Prof. Jimmy Ho Man Lee'}}
2017-12-31 21:31:20,748 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:20,753 : INFO : < 200 OK [1383]
2017-12-31 21:31:20,758 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Brooke Anderson'}}
2017-12-31 21:31:20,761 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:20,767 : INFO : < 200 OK [1376]
2017-12-31 21:31:20,771 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ian Harris'}}
2017-12-31 21:31:20,774 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:20,780 : INFO : < 200 OK [1371]
2017-12-31 21:31:20,784 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Cade Massey'}}
2017-12-31 21:31:20,788 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:20,793 : INFO : < 200 OK [1372]
2017-12-31 21:31:20,797 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Yvonne Breyer'}}
2017-12-31 21:31:20,801 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:20,807 : INFO : < 200 OK [1377]
2017-12-31 21:31:20,811 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniil Polykovskiy'}}
2017-12-31 21:31:20,814 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:20,820 : INFO : < 200 OK [1379]
2017-12-31 21:31:20,824 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nikolay Vyahhi'}}
2017-12-31 21:31:20,827 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:20,833 : INFO : < 200 OK [1375]
2017-12-31 21:31:20,837 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ekaterina Amerik'}}
2017-12-31 21:31:20,840 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:20,846 : INFO : < 200 OK [1377]
2017-12-31 21:31:20,850 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Whitman, Ph.D., CISM, CISSP'}}
2017-12-31 21:31:20,853 : INFO : > POST http://localhost:7474/db/data/cypher [110]
2017-12-31 21:31:20,859 : INFO : < 200 OK [1396]
2017-12-31 21:31:20,863 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Loren Terveen'}}
2017-12-31 21:31:20,867 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:20,872 : INFO : < 200 OK [1374]
2017-12-31 21:31:20,876 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Merlise A Clyde'}}
2017-12-31 21:31:20,880 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:20,885 : INFO : < 200 OK [1376]
2017-12-31 21:31:20,889 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Don Patterson'}}
2017-12-31 21:31:20,895 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:20,901 : INFO : < 200 OK [1374]
2017-12-31 21:31:20,906 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Keith Devlin'}}
2017-12-31 21:31:20,909 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:20,915 : INFO : < 200 OK [1377]
2017-12-31 21:31:20,919 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Torgerson'}}
2017-12-31 21:31:20,922 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:20,928 : INFO : < 200 OK [1376]
2017-12-31 21:31:20,933 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Henri Laurie'}}
2017-12-31 21:31:20,937 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:20,943 : INFO : < 200 OK [1373]
2017-12-31 21:31:20,947 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Harinath Garudadri'}}
2017-12-31 21:31:20,950 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:20,956 : INFO : < 200 OK [1379]
2017-12-31 21:31:20,962 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Manuel Laguna'}}
2017-12-31 21:31:20,965 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:20,971 : INFO : < 200 OK [1374]
2017-12-31 21:31:20,977 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Susan H. Rodger'}}
2017-12-31 21:31:20,981 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:20,987 : INFO : < 200 OK [1376]
2017-12-31 21:31:20,991 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jason A. Roy, Ph.D. '}}
2017-12-31 21:31:20,995 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:21,001 : INFO : < 200 OK [1381]
2017-12-31 21:31:21,006 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Isabelle Bichindaritz'}}
2017-12-31 21:31:21,009 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:21,015 : INFO : < 200 OK [1382]
2017-12-31 21:31:21,019 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alma Salnaja'}}
2017-12-31 21:31:21,023 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:21,028 : INFO : < 200 OK [1373]
2017-12-31 21:31:21,032 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'CJ Taylor'}}
2017-12-31 21:31:21,035 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:21,041 : INFO : < 200 OK [1370]
2017-12-31 21:31:21,044 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alex Cowan'}}
2017-12-31 21:31:21,048 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:21,053 : INFO : < 200 OK [1371]
2017-12-31 21:31:21,057 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sara Behdad'}}
2017-12-31 21:31:21,060 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:21,066 : INFO : < 200 OK [1372]
2017-12-31 21:31:21,070 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christophe Rhodes'}}
2017-12-31 21:31:21,073 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:21,078 : INFO : < 200 OK [1378]

2017-12-31 21:31:21,082 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nick Santos'}}
2017-12-31 21:31:21,086 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:21,092 : INFO : < 200 OK [1372]
2017-12-31 21:31:21,095 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Praveen Mittal'}}
2017-12-31 21:31:21,099 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:21,104 : INFO : < 200 OK [1375]
2017-12-31 21:31:21,109 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Natasha Balac'}}
2017-12-31 21:31:21,112 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:21,118 : INFO : < 200 OK [1374]
2017-12-31 21:31:21,122 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Amy Moore'}}
2017-12-31 21:31:21,126 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:21,132 : INFO : < 200 OK [1370]
2017-12-31 21:31:21,136 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Elena Valderrama'}}
2017-12-31 21:31:21,139 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:21,146 : INFO : < 200 OK [1377]
2017-12-31 21:31:21,150 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Worthington'}}
2017-12-31 21:31:21,155 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:21,164 : INFO : < 200 OK [1380]
2017-12-31 21:31:21,169 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jonathan  Katz'}}
2017-12-31 21:31:21,172 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:21,178 : INFO : < 200 OK [1375]
2017-12-31 21:31:21,183 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Wayne Whiteman, PE'}}
2017-12-31 21:31:21,186 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:21,192 : INFO : < 200 OK [1383]
2017-12-31 21:31:21,199 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Rajesh P. N. Rao'}}
2017-12-31 21:31:21,202 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:21,209 : INFO : < 200 OK [1377]
2017-12-31 21:31:21,213 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Yaakov Chaikin'}}
2017-12-31 21:31:21,217 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:21,223 : INFO : < 200 OK [1375]
2017-12-31 21:31:21,227 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Bonnie Ram'}}
2017-12-31 21:31:21,231 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:21,237 : INFO : < 200 OK [1371]
2017-12-31 21:31:21,241 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ben Langmead, PhD'}}
2017-12-31 21:31:21,245 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:21,250 : INFO : < 200 OK [1378]
2017-12-31 21:31:21,254 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Yang-Hann Kim'}}
2017-12-31 21:31:21,258 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:21,263 : INFO : < 200 OK [1374]
2017-12-31 21:31:21,267 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexander Novikov'}}
2017-12-31 21:31:21,271 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:21,278 : INFO : < 200 OK [1378]
2017-12-31 21:31:21,281 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Humayun Zafar'}}
2017-12-31 21:31:21,284 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:21,290 : INFO : < 200 OK [1378]
2017-12-31 21:31:21,294 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Albert Glock'}}
2017-12-31 21:31:21,297 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:21,302 : INFO : < 200 OK [1373]
2017-12-31 21:31:21,306 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Morten Hartvig Hansen'}}
2017-12-31 21:31:21,310 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:21,315 : INFO : < 200 OK [1382]
2017-12-31 21:31:21,319 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Shannon Bradshaw'}}
2017-12-31 21:31:21,323 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:21,328 : INFO : < 200 OK [1377]
2017-12-31 21:31:21,332 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Tom  Morley'}}
2017-12-31 21:31:21,336 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:21,341 : INFO : < 200 OK [1376]
2017-12-31 21:31:21,345 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Fataneh Taghaboni-Dutta'}}
2017-12-31 21:31:21,348 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:21,353 : INFO : < 200 OK [1384]
2017-12-31 21:31:21,357 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Eric Bradlow'}}
2017-12-31 21:31:21,361 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:21,366 : INFO : < 200 OK [1373]
2017-12-31 21:31:21,370 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Douglas C. Schmidt'}}
2017-12-31 21:31:21,373 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:21,379 : INFO : < 200 OK [1383]
2017-12-31 21:31:21,382 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Richard White'}}
2017-12-31 21:31:21,385 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:21,391 : INFO : < 200 OK [1374]
2017-12-31 21:31:21,395 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Xiaobo Zhou'}}
2017-12-31 21:31:21,398 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:21,404 : INFO : < 200 OK [1372]
2017-12-31 21:31:21,408 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John McGready, PhD, MS'}}
2017-12-31 21:31:21,411 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:21,417 : INFO : < 200 OK [1383]
2017-12-31 21:31:21,420 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Adrienne Fairhall'}}
2017-12-31 21:31:21,424 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:21,430 : INFO : < 200 OK [1378]
2017-12-31 21:31:21,435 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': "Maeve O'Reilly"}}
2017-12-31 21:31:21,439 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:21,446 : INFO : < 200 OK [1375]
2017-12-31 21:31:21,451 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Дмитрий Савицкий'}}
2017-12-31 21:31:21,455 : INFO : > POST http://localhost:7474/db/data/cypher [166]
2017-12-31 21:31:21,461 : INFO : < 200 OK [1392]
2017-12-31 21:31:21,464 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Roger D. Peng, PhD'}}
2017-12-31 21:31:21,468 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:21,473 : INFO : < 200 OK [1379]
2017-12-31 21:31:21,477 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Morten Vesterager Madsen'}}
2017-12-31 21:31:21,480 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2017-12-31 21:31:21,486 : INFO : < 200 OK [1385]
2017-12-31 21:31:21,489 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Juan H Klopper'}}
2017-12-31 21:31:21,492 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:21,497 : INFO : < 200 OK [1375]
2017-12-31 21:31:21,500 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Paul Bendich'}}
2017-12-31 21:31:21,503 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:21,508 : INFO : < 200 OK [1373]
2017-12-31 21:31:21,512 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christiaan Heij'}}
2017-12-31 21:31:21,516 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:21,521 : INFO : < 200 OK [1376]

2017-12-31 21:31:21,525 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ankit Singla'}}
2017-12-31 21:31:21,528 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:21,534 : INFO : < 200 OK [1373]
2017-12-31 21:31:21,538 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Julien Richard-Foy'}}
2017-12-31 21:31:21,541 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:21,547 : INFO : < 200 OK [1383]
2017-12-31 21:31:21,551 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Richard Valliant, Ph.D.'}}
2017-12-31 21:31:21,554 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:21,560 : INFO : < 200 OK [1384]
2017-12-31 21:31:21,564 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Telethia Willis'}}
2017-12-31 21:31:21,567 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:21,573 : INFO : < 200 OK [1376]
2017-12-31 21:31:21,577 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Neil Rhodes'}}
2017-12-31 21:31:21,581 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:21,586 : INFO : < 200 OK [1372]
2017-12-31 21:31:21,590 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dominik Scheder'}}
2017-12-31 21:31:21,593 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:21,599 : INFO : < 200 OK [1376]
2017-12-31 21:31:21,602 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John Walicki'}}
2017-12-31 21:31:21,605 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:21,611 : INFO : < 200 OK [1373]
2017-12-31 21:31:21,614 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Song-Kuk Kim'}}
2017-12-31 21:31:21,617 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:21,622 : INFO : < 200 OK [1373]
2017-12-31 21:31:21,626 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'James Z. Lee'}}
2017-12-31 21:31:21,629 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:21,634 : INFO : < 200 OK [1373]
2017-12-31 21:31:21,638 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Rahul Rai'}}
2017-12-31 21:31:21,641 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:21,648 : INFO : < 200 OK [1370]
2017-12-31 21:31:21,653 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sergei Obiedkov '}}
2017-12-31 21:31:21,657 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:21,664 : INFO : < 200 OK [1377]
2017-12-31 21:31:21,668 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'J. Alex Halderman'}}
2017-12-31 21:31:21,672 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:21,678 : INFO : < 200 OK [1378]
2017-12-31 21:31:21,682 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Chirag Shah'}}
2017-12-31 21:31:21,685 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:21,691 : INFO : < 200 OK [1372]
2017-12-31 21:31:21,695 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Chan-Byoung Chae'}}
2017-12-31 21:31:21,699 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:21,705 : INFO : < 200 OK [1377]
2017-12-31 21:31:21,709 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jogesh K. Muppala'}}
2017-12-31 21:31:21,712 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:21,718 : INFO : < 200 OK [1378]
2017-12-31 21:31:21,722 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Richard Riley, Ph.D'}}
2017-12-31 21:31:21,726 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:21,732 : INFO : < 200 OK [1384]
2017-12-31 21:31:21,735 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'George Kapetanios'}}
2017-12-31 21:31:21,739 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:21,744 : INFO : < 200 OK [1378]
2017-12-31 21:31:21,748 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. C. Jules White'}}
2017-12-31 21:31:21,751 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:21,756 : INFO : < 200 OK [1379]
2017-12-31 21:31:21,760 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Owen Astrachan'}}
2017-12-31 21:31:21,762 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:21,768 : INFO : < 200 OK [1375]
2017-12-31 21:31:21,771 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ken English'}}
2017-12-31 21:31:21,774 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:21,780 : INFO : < 200 OK [1372]
2017-12-31 21:31:21,784 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Evgeny Smirnov'}}
2017-12-31 21:31:21,788 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:21,794 : INFO : < 200 OK [1375]
2017-12-31 21:31:21,798 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kwon, Kil Hyun'}}
2017-12-31 21:31:21,801 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:21,807 : INFO : < 200 OK [1375]
2017-12-31 21:31:21,812 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Mary Ann Weitnauer'}}
2017-12-31 21:31:21,816 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:21,823 : INFO : < 200 OK [1382]
2017-12-31 21:31:21,828 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Pavel  Pevzner'}}
2017-12-31 21:31:21,832 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:21,837 : INFO : < 200 OK [1375]
2017-12-31 21:31:21,841 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dan  Grossman'}}
2017-12-31 21:31:21,844 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:21,849 : INFO : < 200 OK [1374]
2017-12-31 21:31:21,854 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kiran Chittargi'}}
2017-12-31 21:31:21,857 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:21,862 : INFO : < 200 OK [1376]
2017-12-31 21:31:21,866 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Robert Erickson'}}
2017-12-31 21:31:21,869 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:21,875 : INFO : < 200 OK [1380]
2017-12-31 21:31:21,879 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Torben Krogh Mikkelsen'}}
2017-12-31 21:31:21,883 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:21,888 : INFO : < 200 OK [1383]
2017-12-31 21:31:21,892 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Noah Gans'}}
2017-12-31 21:31:21,895 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:21,901 : INFO : < 200 OK [1370]
2017-12-31 21:31:21,904 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Jorge Blasco Alis'}}
2017-12-31 21:31:21,908 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:21,913 : INFO : < 200 OK [1381]
2017-12-31 21:31:21,917 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Chi Zhou'}}
2017-12-31 21:31:21,921 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2017-12-31 21:31:21,927 : INFO : < 200 OK [1369]
2017-12-31 21:31:21,931 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John C. Hart'}}
2017-12-31 21:31:21,935 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:21,940 : INFO : < 200 OK [1373]
2017-12-31 21:31:21,943 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexey Dolinskiy'}}
2017-12-31 21:31:21,946 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:21,951 : INFO : < 200 OK [1377]

2017-12-31 21:31:21,955 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Govind Acharya'}}
2017-12-31 21:31:21,958 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:21,963 : INFO : < 200 OK [1375]
2017-12-31 21:31:21,967 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Magnus Egerstedt'}}
2017-12-31 21:31:21,970 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:21,975 : INFO : < 200 OK [1381]
2017-12-31 21:31:21,979 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrew D. Hilton'}}
2017-12-31 21:31:21,982 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:21,988 : INFO : < 200 OK [1377]
2017-12-31 21:31:21,992 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dick van Dijk '}}
2017-12-31 21:31:21,994 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:21,999 : INFO : < 200 OK [1375]
2017-12-31 21:31:22,003 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Leo Porter'}}
2017-12-31 21:31:22,006 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:22,012 : INFO : < 200 OK [1371]
2017-12-31 21:31:22,015 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sven-Erik Gryning'}}
2017-12-31 21:31:22,019 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:22,024 : INFO : < 200 OK [1378]
2017-12-31 21:31:22,029 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Peter Fader'}}
2017-12-31 21:31:22,034 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:22,041 : INFO : < 200 OK [1372]
2017-12-31 21:31:22,046 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ron Berman'}}
2017-12-31 21:31:22,051 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:22,056 : INFO : < 200 OK [1371]
2017-12-31 21:31:22,061 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anders Holm'}}
2017-12-31 21:31:22,064 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:22,070 : INFO : < 200 OK [1372]
2017-12-31 21:31:22,073 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jacob O. Wobbrock'}}
2017-12-31 21:31:22,077 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:22,083 : INFO : < 200 OK [1378]
2017-12-31 21:31:22,087 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'P. Brighten Godfrey'}}
2017-12-31 21:31:22,090 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:22,095 : INFO : < 200 OK [1380]
2017-12-31 21:31:22,099 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Martin Odersky'}}
2017-12-31 21:31:22,101 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:22,106 : INFO : < 200 OK [1375]
2017-12-31 21:31:22,110 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Gail Swanlund'}}
2017-12-31 21:31:22,113 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:22,118 : INFO : < 200 OK [1374]
2017-12-31 21:31:22,122 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Yannis Tsividis'}}
2017-12-31 21:31:22,127 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:22,131 : INFO : < 200 OK [1376]
2017-12-31 21:31:22,135 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michel van der Wel'}}
2017-12-31 21:31:22,137 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:22,143 : INFO : < 200 OK [1379]
2017-12-31 21:31:22,147 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ciprian M. Crainiceanu'}}
2017-12-31 21:31:22,150 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:22,155 : INFO : < 200 OK [1383]
2017-12-31 21:31:22,159 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Colleen van Lent, Ph.D.'}}
2017-12-31 21:31:22,162 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:22,168 : INFO : < 200 OK [1384]
2017-12-31 21:31:22,172 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mikhail Trofimov'}}
2017-12-31 21:31:22,176 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:22,182 : INFO : < 200 OK [1377]
2017-12-31 21:31:22,186 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Wharton Teaching Staff'}}
2017-12-31 21:31:22,192 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:22,198 : INFO : < 200 OK [1383]
2017-12-31 21:31:22,202 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sol Bermann'}}
2017-12-31 21:31:22,205 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:22,211 : INFO : < 200 OK [1372]
2017-12-31 21:31:22,215 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dan Boneh'}}
2017-12-31 21:31:22,219 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:22,224 : INFO : < 200 OK [1370]
2017-12-31 21:31:22,228 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Justin-Nicholas Toyama '}}
2017-12-31 21:31:22,231 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:22,236 : INFO : < 200 OK [1384]
2017-12-31 21:31:22,240 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kostas Daniilidis'}}
2017-12-31 21:31:22,243 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:22,249 : INFO : < 200 OK [1378]
2017-12-31 21:31:22,252 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Google Cloud Training'}}
2017-12-31 21:31:22,255 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:22,260 : INFO : < 200 OK [1382]
2017-12-31 21:31:22,264 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. José Martín Molina Espinosa'}}
2017-12-31 21:31:22,267 : INFO : > POST http://localhost:7474/db/data/cypher [116]
2017-12-31 21:31:22,273 : INFO : < 200 OK [1394]
2017-12-31 21:31:22,276 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Cristiano Guarana'}}
2017-12-31 21:31:22,280 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:22,285 : INFO : < 200 OK [1378]
2017-12-31 21:31:22,289 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert Sedgewick'}}
2017-12-31 21:31:22,292 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:22,297 : INFO : < 200 OK [1377]
2017-12-31 21:31:22,301 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kellie Liket'}}
2017-12-31 21:31:22,304 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:22,310 : INFO : < 200 OK [1373]
2017-12-31 21:31:22,314 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Senthil Veeraraghavan'}}
2017-12-31 21:31:22,317 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:22,322 : INFO : < 200 OK [1382]
2017-12-31 21:31:22,325 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jiawei Han'}}
2017-12-31 21:31:22,329 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:22,334 : INFO : < 200 OK [1371]
2017-12-31 21:31:22,337 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Levin'}}
2017-12-31 21:31:22,340 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:22,345 : INFO : < 200 OK [1374]
2017-12-31 21:31:22,348 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mark  Bocko'}}
2017-12-31 21:31:22,351 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:22,356 : INFO : < 200 OK [1372]
2017-12-31 21:31:22,360 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Frank Gielen'}}
2017-12-31 21:31:22,362 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:22,367 : INFO : < 200 OK [1373]

2017-12-31 21:31:22,371 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Richard Waterman'}}
2017-12-31 21:31:22,374 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:22,379 : INFO : < 200 OK [1377]
2017-12-31 21:31:22,383 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr  Lorenzo Cavallaro'}}
2017-12-31 21:31:22,386 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:22,392 : INFO : < 200 OK [1382]
2017-12-31 21:31:22,395 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Rob A. Rutenbar'}}
2017-12-31 21:31:22,399 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:22,405 : INFO : < 200 OK [1376]
2017-12-31 21:31:22,410 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alex Mannella'}}
2017-12-31 21:31:22,413 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:22,421 : INFO : < 200 OK [1374]
2017-12-31 21:31:22,424 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Areti Manataki'}}
2017-12-31 21:31:22,428 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:22,433 : INFO : < 200 OK [1375]
2017-12-31 21:31:22,437 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Tucker Balch'}}
2017-12-31 21:31:22,441 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:22,446 : INFO : < 200 OK [1377]
2017-12-31 21:31:22,450 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christopher Brooks'}}
2017-12-31 21:31:22,453 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:22,458 : INFO : < 200 OK [1379]
2017-12-31 21:31:22,462 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Professor Keith M. Martin'}}
2017-12-31 21:31:22,465 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:22,471 : INFO : < 200 OK [1386]
2017-12-31 21:31:22,474 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kalman Hazins'}}
2017-12-31 21:31:22,477 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:22,482 : INFO : < 200 OK [1374]
2017-12-31 21:31:22,486 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Jerry Roth'}}
2017-12-31 21:31:22,489 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:22,494 : INFO : < 200 OK [1375]
2017-12-31 21:31:22,497 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': ' Dr Sorrel Harriet'}}
2017-12-31 21:31:22,500 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:22,505 : INFO : < 200 OK [1379]
2017-12-31 21:31:22,509 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Van Kleeck'}}
2017-12-31 21:31:22,512 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:22,517 : INFO : < 200 OK [1377]
2017-12-31 21:31:22,521 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dan Zhang'}}
2017-12-31 21:31:22,524 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:22,529 : INFO : < 200 OK [1370]
2017-12-31 21:31:22,532 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexander Panin'}}
2017-12-31 21:31:22,535 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:22,540 : INFO : < 200 OK [1376]
2017-12-31 21:31:22,544 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dennis Fok'}}
2017-12-31 21:31:22,546 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:22,552 : INFO : < 200 OK [1371]
2017-12-31 21:31:22,555 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Shimon Schocken'}}
2017-12-31 21:31:22,558 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:22,564 : INFO : < 200 OK [1376]
2017-12-31 21:31:22,567 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sam Kaufman'}}
2017-12-31 21:31:22,570 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:22,577 : INFO : < 200 OK [1372]
2017-12-31 21:31:22,582 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Professor Pascal Van Hentenryck'}}
2017-12-31 21:31:22,586 : INFO : > POST http://localhost:7474/db/data/cypher [106]
2017-12-31 21:31:22,592 : INFO : < 200 OK [1392]
2017-12-31 21:31:22,598 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Henrik Bredmose'}}
2017-12-31 21:31:22,602 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:22,608 : INFO : < 200 OK [1376]
2017-12-31 21:31:22,613 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Joe Warren'}}
2017-12-31 21:31:22,616 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:22,621 : INFO : < 200 OK [1371]
2017-12-31 21:31:22,625 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tom Cronin'}}
2017-12-31 21:31:22,628 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:22,633 : INFO : < 200 OK [1371]
2017-12-31 21:31:22,637 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Annemarie Zand Scholten'}}
2017-12-31 21:31:22,641 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:22,646 : INFO : < 200 OK [1384]
2017-12-31 21:31:22,650 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Scott Rixner'}}
2017-12-31 21:31:22,654 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:22,659 : INFO : < 200 OK [1373]
2017-12-31 21:31:22,663 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Hilmar Kjartansson Danielsen'}}
2017-12-31 21:31:22,666 : INFO : > POST http://localhost:7474/db/data/cypher [103]
2017-12-31 21:31:22,671 : INFO : < 200 OK [1389]
2017-12-31 21:31:22,675 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vijay Kumar'}}
2017-12-31 21:31:22,678 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:22,684 : INFO : < 200 OK [1372]
2017-12-31 21:31:22,688 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kasper Daniel Hansen, PhD'}}
2017-12-31 21:31:22,691 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:22,697 : INFO : < 200 OK [1386]
2017-12-31 21:31:22,701 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Mike Ryan'}}
2017-12-31 21:31:22,704 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:22,709 : INFO : < 200 OK [1373]
2017-12-31 21:31:22,712 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vladimir Podolskii'}}
2017-12-31 21:31:22,715 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:22,721 : INFO : < 200 OK [1379]
2017-12-31 21:31:22,725 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Bill Boyd'}}
2017-12-31 21:31:22,728 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:22,734 : INFO : < 200 OK [1370]
2017-12-31 21:31:22,738 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Inez Zwetsloot'}}
2017-12-31 21:31:22,741 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:22,747 : INFO : < 200 OK [1375]
2017-12-31 21:31:22,750 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Emiel van Loon'}}
2017-12-31 21:31:22,754 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:22,759 : INFO : < 200 OK [1375]
2017-12-31 21:31:22,763 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Walker'}}
2017-12-31 21:31:22,765 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:22,771 : INFO : < 200 OK [1375]
2017-12-31 21:31:22,776 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Gautam Kaul'}}
2017-12-31 21:31:22,779 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:22,786 : INFO : < 200 OK [1372]

2017-12-31 21:31:22,790 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Karl Schmedders'}}
2017-12-31 21:31:22,793 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:22,799 : INFO : < 200 OK [1376]
2017-12-31 21:31:22,802 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Tim "Dr. T" Chamillard'}}
2017-12-31 21:31:22,806 : INFO : > POST http://localhost:7474/db/data/cypher [103]
2017-12-31 21:31:22,810 : INFO : < 200 OK [1389]
2017-12-31 21:31:22,814 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jean-Pierre Deschamps'}}
2017-12-31 21:31:22,817 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:22,822 : INFO : < 200 OK [1382]
2017-12-31 21:31:22,826 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Xavier Serra'}}
2017-12-31 21:31:22,828 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:22,833 : INFO : < 200 OK [1373]
2017-12-31 21:31:22,837 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Simon Holmbacka'}}
2017-12-31 21:31:22,840 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:22,845 : INFO : < 200 OK [1376]
2017-12-31 21:31:22,848 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Matthew Bidwell'}}
2017-12-31 21:31:22,851 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:22,856 : INFO : < 200 OK [1376]
2017-12-31 21:31:22,861 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Brent Hecht'}}
2017-12-31 21:31:22,865 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:22,871 : INFO : < 200 OK [1376]
2017-12-31 21:31:22,876 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michel Ianotto '}}
2017-12-31 21:31:22,881 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:22,886 : INFO : < 200 OK [1376]
2017-12-31 21:31:22,890 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Elizabeth Sweeney '}}
2017-12-31 21:31:22,894 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:22,899 : INFO : < 200 OK [1383]
2017-12-31 21:31:22,903 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kim Branner'}}
2017-12-31 21:31:22,907 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:22,912 : INFO : < 200 OK [1372]
2017-12-31 21:31:22,916 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Maarten Weyn'}}
2017-12-31 21:31:22,919 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:22,924 : INFO : < 200 OK [1373]
2017-12-31 21:31:22,927 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Min Song'}}
2017-12-31 21:31:22,930 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2017-12-31 21:31:22,936 : INFO : < 200 OK [1369]
2017-12-31 21:31:22,940 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Lluis Terés'}}
2017-12-31 21:31:22,945 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:22,952 : INFO : < 200 OK [1373]
2017-12-31 21:31:22,955 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'William Bahn'}}
2017-12-31 21:31:22,959 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:22,964 : INFO : < 200 OK [1373]
2017-12-31 21:31:22,968 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Louise Connelly'}}
2017-12-31 21:31:22,971 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:22,977 : INFO : < 200 OK [1376]
2017-12-31 21:31:22,980 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Lars Pilgaard Mikkelsen'}}
2017-12-31 21:31:22,984 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:22,989 : INFO : < 200 OK [1384]
2017-12-31 21:31:22,993 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Hanspeter Schaub'}}
2017-12-31 21:31:22,996 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:23,001 : INFO : < 200 OK [1377]
2017-12-31 21:31:23,005 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel Lee'}}
2017-12-31 21:31:23,008 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:23,015 : INFO : < 200 OK [1371]
2017-12-31 21:31:23,019 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ralf Brockhaus '}}
2017-12-31 21:31:23,023 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:23,030 : INFO : < 200 OK [1376]
2017-12-31 21:31:23,034 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Rajkumar Venkatesan'}}
2017-12-31 21:31:23,038 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:23,044 : INFO : < 200 OK [1380]
2017-12-31 21:31:23,049 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anna Kozlova'}}
2017-12-31 21:31:23,052 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:23,058 : INFO : < 200 OK [1373]
2017-12-31 21:31:23,061 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Niels-Erik Clausen'}}
2017-12-31 21:31:23,065 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:23,070 : INFO : < 200 OK [1379]
2017-12-31 21:31:23,074 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Luay Nakhleh'}}
2017-12-31 21:31:23,077 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:23,083 : INFO : < 200 OK [1373]
2017-12-31 21:31:23,086 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dae-Sik Hong'}}
2017-12-31 21:31:23,090 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:23,095 : INFO : < 200 OK [1373]
2017-12-31 21:31:23,099 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John Greiner'}}
2017-12-31 21:31:23,102 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:23,107 : INFO : < 200 OK [1373]
2017-12-31 21:31:23,110 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel Lakens'}}
2017-12-31 21:31:23,114 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:23,119 : INFO : < 200 OK [1374]
2017-12-31 21:31:23,123 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Adam Porter'}}
2017-12-31 21:31:23,126 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:23,132 : INFO : < 200 OK [1376]
2017-12-31 21:31:23,137 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mine Çetinkaya-Rundel'}}
2017-12-31 21:31:23,140 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2017-12-31 21:31:23,148 : INFO : < 200 OK [1383]
2017-12-31 21:31:23,151 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Rachel Cohen Lehman'}}
2017-12-31 21:31:23,154 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:23,162 : INFO : < 200 OK [1384]
2017-12-31 21:31:23,165 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Farhoud Hosseinpour'}}
2017-12-31 21:31:23,169 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:23,174 : INFO : < 200 OK [1380]
2017-12-31 21:31:23,179 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Juan Antonio Martínez'}}
2017-12-31 21:31:23,182 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2017-12-31 21:31:23,188 : INFO : < 200 OK [1383]
2017-12-31 21:31:23,192 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Merce Rullan'}}
2017-12-31 21:31:23,196 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:23,201 : INFO : < 200 OK [1373]
2017-12-31 21:31:23,206 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Professor Peter Komisarczuk'}}
2017-12-31 21:31:23,210 : INFO : > POST http://localhost:7474/db/data/cypher [102]
2017-12-31 21:31:23,215 : INFO : < 200 OK [1388]

2017-12-31 21:31:23,218 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kwang-Soon Kim'}}
2017-12-31 21:31:23,221 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:23,227 : INFO : < 200 OK [1375]
2017-12-31 21:31:23,231 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kristen Walcott-Justice'}}
2017-12-31 21:31:23,234 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:23,238 : INFO : < 200 OK [1384]
2017-12-31 21:31:23,242 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Bill Howe'}}
2017-12-31 21:31:23,245 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:23,250 : INFO : < 200 OK [1370]
2017-12-31 21:31:23,254 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Pavel Manakhov'}}
2017-12-31 21:31:23,256 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:23,261 : INFO : < 200 OK [1375]
2017-12-31 21:31:23,265 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Brian Caffo, PhD'}}
2017-12-31 21:31:23,269 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:23,274 : INFO : < 200 OK [1377]
2017-12-31 21:31:23,278 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Joseph A Konstan'}}
2017-12-31 21:31:23,281 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:23,286 : INFO : < 200 OK [1377]
2017-12-31 21:31:23,290 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': "Casey O'Donnell"}}
2017-12-31 21:31:23,293 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:23,298 : INFO : < 200 OK [1376]
2017-12-31 21:31:23,302 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Genesereth'}}
2017-12-31 21:31:23,305 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:23,310 : INFO : < 200 OK [1393]
2017-12-31 21:31:23,313 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Steven Salzberg, PhD'}}
2017-12-31 21:31:23,316 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:23,321 : INFO : < 200 OK [1395]
2017-12-31 21:31:23,324 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Frank Ayars '}}
2017-12-31 21:31:23,327 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:23,332 : INFO : < 200 OK [1387]
2017-12-31 21:31:23,335 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Herbert Lee'}}
2017-12-31 21:31:23,338 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:23,344 : INFO : < 200 OK [1386]
2017-12-31 21:31:23,349 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Erik Kole'}}
2017-12-31 21:31:23,352 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:23,359 : INFO : < 200 OK [1384]
2017-12-31 21:31:23,363 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Matthijs Rooduijn'}}
2017-12-31 21:31:23,367 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:23,372 : INFO : < 200 OK [1392]
2017-12-31 21:31:23,377 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Richard Lambert'}}
2017-12-31 21:31:23,380 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:23,385 : INFO : < 200 OK [1390]
2017-12-31 21:31:23,390 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Traci Carte'}}
2017-12-31 21:31:23,393 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:23,398 : INFO : < 200 OK [1390]
2017-12-31 21:31:23,402 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Anthony C. Robinson'}}
2017-12-31 21:31:23,404 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:23,410 : INFO : < 200 OK [1398]
2017-12-31 21:31:23,413 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jianbo Shi'}}
2017-12-31 21:31:23,416 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:23,421 : INFO : < 200 OK [1385]
2017-12-31 21:31:23,424 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Marius Preda'}}
2017-12-31 21:31:23,427 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:23,432 : INFO : < 200 OK [1387]
2017-12-31 21:31:23,435 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sarah Jones'}}
2017-12-31 21:31:23,438 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:23,444 : INFO : < 200 OK [1386]
2017-12-31 21:31:23,448 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Noam  Nisan'}}
2017-12-31 21:31:23,452 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:23,459 : INFO : < 200 OK [1386]
2017-12-31 21:31:23,463 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Ian  Faulconbridge '}}
2017-12-31 21:31:23,466 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:23,472 : INFO : < 200 OK [1397]
2017-12-31 21:31:23,476 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Wil van der Aalst'}}
2017-12-31 21:31:23,479 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:23,484 : INFO : < 200 OK [1392]
2017-12-31 21:31:23,488 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Indranil Gupta'}}
2017-12-31 21:31:23,490 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:23,496 : INFO : < 200 OK [1389]
2017-12-31 21:31:23,499 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Inés Friss de Kereki'}}
2017-12-31 21:31:23,502 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:23,508 : INFO : < 200 OK [1396]
2017-12-31 21:31:23,512 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Evgeniy Ryabenko'}}
2017-12-31 21:31:23,515 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:23,519 : INFO : < 200 OK [1391]
2017-12-31 21:31:23,523 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Douglas Van Houweling'}}
2017-12-31 21:31:23,525 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:23,530 : INFO : < 200 OK [1396]
2017-12-31 21:31:23,535 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Shambhu Upadhyaya'}}
2017-12-31 21:31:23,538 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:23,544 : INFO : < 200 OK [1392]
2017-12-31 21:31:23,548 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ilya Breyman'}}
2017-12-31 21:31:23,558 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:23,564 : INFO : < 200 OK [1387]
2017-12-31 21:31:23,569 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Leyton-Brown'}}
2017-12-31 21:31:23,572 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:23,578 : INFO : < 200 OK [1393]
2017-12-31 21:31:23,582 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr.ir. Pieter Cuijpers'}}
2017-12-31 21:31:23,586 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:23,591 : INFO : < 200 OK [1397]
2017-12-31 21:31:23,595 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sanjay Goel'}}
2017-12-31 21:31:23,599 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:23,604 : INFO : < 200 OK [1386]
2017-12-31 21:31:23,608 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Krishna Garikipati, Ph.D.'}}
2017-12-31 21:31:23,611 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:23,616 : INFO : < 200 OK [1400]
2017-12-31 21:31:23,620 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dave Gorman'}}
2017-12-31 21:31:23,623 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:23,628 : INFO : < 200 OK [1386]

2017-12-31 21:31:23,632 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Julie L. Johnson'}}
2017-12-31 21:31:23,635 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:23,640 : INFO : < 200 OK [1395]
2017-12-31 21:31:23,644 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Heather Miller'}}
2017-12-31 21:31:23,647 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:23,653 : INFO : < 200 OK [1393]
2017-12-31 21:31:23,656 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ganz Chockalingam'}}
2017-12-31 21:31:23,659 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:23,664 : INFO : < 200 OK [1392]
2017-12-31 21:31:23,669 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'V. G. Vinod Vydiswaran'}}
2017-12-31 21:31:23,672 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:23,678 : INFO : < 200 OK [1397]
2017-12-31 21:31:23,682 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Avi Ma’ayan, PhD'}}
2017-12-31 21:31:23,685 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:23,690 : INFO : < 200 OK [1393]
2017-12-31 21:31:23,694 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Merete Badger'}}
2017-12-31 21:31:23,696 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:23,702 : INFO : < 200 OK [1388]
2017-12-31 21:31:23,706 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexey Artemov'}}
2017-12-31 21:31:23,709 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:23,714 : INFO : < 200 OK [1389]
2017-12-31 21:31:23,717 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mike Fitzpatrick'}}
2017-12-31 21:31:23,721 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:23,727 : INFO : < 200 OK [1391]
2017-12-31 21:31:23,731 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Reza Farivar'}}
2017-12-31 21:31:23,736 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:23,741 : INFO : < 200 OK [1387]
2017-12-31 21:31:23,746 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Brian J Bushee'}}
2017-12-31 21:31:23,748 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:23,754 : INFO : < 200 OK [1389]
2017-12-31 21:31:23,758 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael D. Ekstrand'}}
2017-12-31 21:31:23,761 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:23,766 : INFO : < 200 OK [1394]
2017-12-31 21:31:23,770 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Don Huesman'}}
2017-12-31 21:31:23,773 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:23,780 : INFO : < 200 OK [1386]
2017-12-31 21:31:23,783 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Roy H. Campbell'}}
2017-12-31 21:31:23,785 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:23,791 : INFO : < 200 OK [1390]
2017-12-31 21:31:23,795 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Nick Feamster'}}
2017-12-31 21:31:23,798 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:23,803 : INFO : < 200 OK [1392]
2017-12-31 21:31:23,807 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Manel Martínez-Ramón'}}
2017-12-31 21:31:23,811 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2017-12-31 21:31:23,816 : INFO : < 200 OK [1397]
2017-12-31 21:31:23,819 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Marie-Laure Boucheret'}}
2017-12-31 21:31:23,823 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:23,828 : INFO : < 200 OK [1396]
2017-12-31 21:31:23,832 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Francine Gresnigt'}}
2017-12-31 21:31:23,835 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:23,840 : INFO : < 200 OK [1392]
2017-12-31 21:31:23,844 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Akos Ledeczi'}}
2017-12-31 21:31:23,846 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:23,852 : INFO : < 200 OK [1387]
2017-12-31 21:31:23,855 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dariush Derakhshani'}}
2017-12-31 21:31:23,858 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:23,863 : INFO : < 200 OK [1394]
2017-12-31 21:31:23,867 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Matthew O. Jackson'}}
2017-12-31 21:31:23,870 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:23,879 : INFO : < 200 OK [1393]
2017-12-31 21:31:23,885 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mikhail Hushchyn'}}
2017-12-31 21:31:23,888 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:23,895 : INFO : < 200 OK [1391]
2017-12-31 21:31:23,900 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Gerben Moerman'}}
2017-12-31 21:31:23,903 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:23,910 : INFO : < 200 OK [1389]
2017-12-31 21:31:23,914 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Head Teaching Assistant - Kian Katanforoosh'}}
2017-12-31 21:31:23,918 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2017-12-31 21:31:23,924 : INFO : < 200 OK [1418]
2017-12-31 21:31:23,928 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Norberto Leite'}}
2017-12-31 21:31:23,931 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:23,937 : INFO : < 200 OK [1389]
2017-12-31 21:31:23,942 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Алексей Перепелкин'}}
2017-12-31 21:31:23,946 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:23,952 : INFO : < 200 OK [1410]
2017-12-31 21:31:23,956 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Robert Allen Robinson, Jr.'}}
2017-12-31 21:31:23,960 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2017-12-31 21:31:23,966 : INFO : < 200 OK [1405]
2017-12-31 21:31:23,970 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Roger Barr'}}
2017-12-31 21:31:23,974 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:23,980 : INFO : < 200 OK [1389]
2017-12-31 21:31:23,984 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Colin Rundel '}}
2017-12-31 21:31:23,988 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:23,993 : INFO : < 200 OK [1388]
2017-12-31 21:31:23,997 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexander S. Kulikov'}}
2017-12-31 21:31:24,001 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:24,006 : INFO : < 200 OK [1395]
2017-12-31 21:31:24,010 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jeffrey R. Chasnov'}}
2017-12-31 21:31:24,014 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:24,019 : INFO : < 200 OK [1393]
2017-12-31 21:31:24,023 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Carlos Guestrin'}}
2017-12-31 21:31:24,027 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:24,033 : INFO : < 200 OK [1390]
2017-12-31 21:31:24,037 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nathalie Thomas'}}
2017-12-31 21:31:24,041 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:24,046 : INFO : < 200 OK [1390]
2017-12-31 21:31:24,050 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Gregory Wiles, PhD'}}
2017-12-31 21:31:24,054 : INFO : > POST http://localhost:7474/db/data/cypher [93]

2017-12-31 21:31:24,059 : INFO : < 200 OK [1393]
2017-12-31 21:31:24,063 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Kathryn Wingate'}}
2017-12-31 21:31:24,067 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:24,073 : INFO : < 200 OK [1394]
2017-12-31 21:31:24,078 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mihaela Pertea, PhD'}}
2017-12-31 21:31:24,081 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:24,088 : INFO : < 200 OK [1394]
2017-12-31 21:31:24,094 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Evgeny Frolov'}}
2017-12-31 21:31:24,098 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:24,104 : INFO : < 200 OK [1388]
2017-12-31 21:31:24,109 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Pavel Klemenkov'}}
2017-12-31 21:31:24,113 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:24,118 : INFO : < 200 OK [1390]
2017-12-31 21:31:24,123 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daydream Impact Training'}}
2017-12-31 21:31:24,126 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2017-12-31 21:31:24,132 : INFO : < 200 OK [1399]
2017-12-31 21:31:24,136 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Edward G. Amoroso'}}
2017-12-31 21:31:24,140 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:24,146 : INFO : < 200 OK [1396]
2017-12-31 21:31:24,150 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mung Chiang'}}
2017-12-31 21:31:24,153 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:24,159 : INFO : < 200 OK [1386]
2017-12-31 21:31:24,163 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Marios Michailidis'}}
2017-12-31 21:31:24,166 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:24,171 : INFO : < 200 OK [1393]
2017-12-31 21:31:24,175 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Guillermo Sapiro'}}
2017-12-31 21:31:24,179 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:24,184 : INFO : < 200 OK [1391]
2017-12-31 21:31:24,188 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Mannino'}}
2017-12-31 21:31:24,191 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:24,196 : INFO : < 200 OK [1390]
2017-12-31 21:31:24,200 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrei Ustyuzhanin'}}
2017-12-31 21:31:24,203 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:24,208 : INFO : < 200 OK [1393]
2017-12-31 21:31:24,212 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Gang Qu'}}
2017-12-31 21:31:24,215 : INFO : > POST http://localhost:7474/db/data/cypher [82]
2017-12-31 21:31:24,220 : INFO : < 200 OK [1382]
2017-12-31 21:31:24,223 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Genevieve M. Lipp'}}
2017-12-31 21:31:24,227 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:24,232 : INFO : < 200 OK [1392]
2017-12-31 21:31:24,235 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tor Wager'}}
2017-12-31 21:31:24,238 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:24,244 : INFO : < 200 OK [1384]
2017-12-31 21:31:24,248 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Dragan Maksimovic'}}
2017-12-31 21:31:24,251 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:24,257 : INFO : < 200 OK [1396]
2017-12-31 21:31:24,261 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kirby Kohlmorgen'}}
2017-12-31 21:31:24,264 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:24,269 : INFO : < 200 OK [1391]
2017-12-31 21:31:24,273 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Lisa Dierker'}}
2017-12-31 21:31:24,276 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:24,281 : INFO : < 200 OK [1387]
2017-12-31 21:31:24,284 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Brian Innes'}}
2017-12-31 21:31:24,288 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:24,293 : INFO : < 200 OK [1386]
2017-12-31 21:31:24,296 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anna Potapenko'}}
2017-12-31 21:31:24,299 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:24,305 : INFO : < 200 OK [1389]
2017-12-31 21:31:24,309 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ira Pohl'}}
2017-12-31 21:31:24,311 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2017-12-31 21:31:24,317 : INFO : < 200 OK [1383]
2017-12-31 21:31:24,320 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Yianna Papadakis Kantos'}}
2017-12-31 21:31:24,323 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:24,328 : INFO : < 200 OK [1398]
2017-12-31 21:31:24,332 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Prof Julius O Smith, III'}}
2017-12-31 21:31:24,335 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2017-12-31 21:31:24,341 : INFO : < 200 OK [1399]
2017-12-31 21:31:24,345 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert W. Holthausen'}}
2017-12-31 21:31:24,349 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:24,355 : INFO : < 200 OK [1395]
2017-12-31 21:31:24,359 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Haiyi Zhu'}}
2017-12-31 21:31:24,362 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:24,367 : INFO : < 200 OK [1384]
2017-12-31 21:31:24,371 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Stephen Wong'}}
2017-12-31 21:31:24,374 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:24,379 : INFO : < 200 OK [1387]
2017-12-31 21:31:24,382 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Traian Lavric'}}
2017-12-31 21:31:24,385 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:24,390 : INFO : < 200 OK [1388]
2017-12-31 21:31:24,394 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Richard Dull, Ph.D'}}
2017-12-31 21:31:24,397 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:24,402 : INFO : < 200 OK [1397]
2017-12-31 21:31:24,405 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert Brunner'}}
2017-12-31 21:31:24,407 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:24,412 : INFO : < 200 OK [1389]
2017-12-31 21:31:24,416 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr James Ohene-Djan'}}
2017-12-31 21:31:24,419 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:24,424 : INFO : < 200 OK [1394]
2017-12-31 21:31:24,427 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vladimir Fedorov'}}
2017-12-31 21:31:24,430 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:24,436 : INFO : < 200 OK [1391]
2017-12-31 21:31:24,440 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jana Schaich Borg'}}
2017-12-31 21:31:24,443 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:24,449 : INFO : < 200 OK [1392]
2017-12-31 21:31:24,454 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel Randall'}}
2017-12-31 21:31:24,458 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:24,467 : INFO : < 200 OK [1389]
2017-12-31 21:31:24,471 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Lana Yarosh'}}
2017-12-31 21:31:24,475 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:24,481 : INFO : < 200 OK [1386]

2017-12-31 21:31:24,485 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ivan Puzyrevskiy'}}
2017-12-31 21:31:24,488 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:24,494 : INFO : < 200 OK [1391]
2017-12-31 21:31:24,498 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jennifer Campbell'}}
2017-12-31 21:31:24,502 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:24,507 : INFO : < 200 OK [1392]
2017-12-31 21:31:24,511 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Melissa Clarke'}}
2017-12-31 21:31:24,515 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:24,520 : INFO : < 200 OK [1389]
2017-12-31 21:31:24,524 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Werbach'}}
2017-12-31 21:31:24,528 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:24,533 : INFO : < 200 OK [1388]
2017-12-31 21:31:24,537 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sharad Borle'}}
2017-12-31 21:31:24,540 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:24,545 : INFO : < 200 OK [1387]
2017-12-31 21:31:24,549 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Schweidel'}}
2017-12-31 21:31:24,553 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:24,558 : INFO : < 200 OK [1390]
2017-12-31 21:31:24,561 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel M Kane'}}
2017-12-31 21:31:24,564 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:24,569 : INFO : < 200 OK [1388]
2017-12-31 21:31:24,572 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Khurram Afridi'}}
2017-12-31 21:31:24,574 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:24,579 : INFO : < 200 OK [1393]
2017-12-31 21:31:24,583 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Geoffrey Hinton'}}
2017-12-31 21:31:24,586 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:24,591 : INFO : < 200 OK [1390]
2017-12-31 21:31:24,595 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alex Fosdick'}}
2017-12-31 21:31:24,599 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:24,604 : INFO : < 200 OK [1387]
2017-12-31 21:31:24,607 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sean Kross'}}
2017-12-31 21:31:24,610 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:24,616 : INFO : < 200 OK [1385]
2017-12-31 21:31:24,621 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sadie St. Lawrence'}}
2017-12-31 21:31:24,624 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:24,632 : INFO : < 200 OK [1393]
2017-12-31 21:31:24,636 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Archer'}}
2017-12-31 21:31:24,640 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:24,646 : INFO : < 200 OK [1387]
2017-12-31 21:31:24,650 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Greg Williams'}}
2017-12-31 21:31:24,654 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:24,661 : INFO : < 200 OK [1388]
2017-12-31 21:31:24,665 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrey Vladimirov'}}
2017-12-31 21:31:24,669 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:24,675 : INFO : < 200 OK [1392]
2017-12-31 21:31:24,679 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Claire Mathieu'}}
2017-12-31 21:31:24,682 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:24,688 : INFO : < 200 OK [1389]
2017-12-31 21:31:24,691 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Veronica Scurtu'}}
2017-12-31 21:31:24,694 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:24,699 : INFO : < 200 OK [1390]
2017-12-31 21:31:24,702 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Pavel Shvechikov'}}
2017-12-31 21:31:24,705 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:24,710 : INFO : < 200 OK [1391]
2017-12-31 21:31:24,713 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sid Deliwala'}}
2017-12-31 21:31:24,717 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:24,723 : INFO : < 200 OK [1387]
2017-12-31 21:31:24,727 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Stephany Duda, PhD'}}
2017-12-31 21:31:24,729 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:24,733 : INFO : < 200 OK [1393]
2017-12-31 21:31:24,736 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexey Zobnin'}}
2017-12-31 21:31:24,739 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:24,744 : INFO : < 200 OK [1388]
2017-12-31 21:31:24,747 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Mick Grierson'}}
2017-12-31 21:31:24,750 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:24,754 : INFO : < 200 OK [1391]
2017-12-31 21:31:24,758 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Marco Gillies'}}
2017-12-31 21:31:24,760 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:24,766 : INFO : < 200 OK [1391]
2017-12-31 21:31:24,769 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jeff Leek, PhD'}}
2017-12-31 21:31:24,771 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:24,776 : INFO : < 200 OK [1389]
2017-12-31 21:31:24,779 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jahangir Karimi'}}
2017-12-31 21:31:24,781 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:24,786 : INFO : < 200 OK [1390]
2017-12-31 21:31:24,789 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Romeo Kienzler'}}
2017-12-31 21:31:24,791 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:24,795 : INFO : < 200 OK [1389]
2017-12-31 21:31:24,798 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Prof. Kelleann Foster'}}
2017-12-31 21:31:24,800 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:24,805 : INFO : < 200 OK [1396]
2017-12-31 21:31:24,808 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': "Nick O'Leary"}}
2017-12-31 21:31:24,812 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:24,817 : INFO : < 200 OK [1387]
2017-12-31 21:31:24,820 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Rosa I. Arriaga'}}
2017-12-31 21:31:24,823 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:24,828 : INFO : < 200 OK [1394]
2017-12-31 21:31:24,832 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Simon Murphy'}}
2017-12-31 21:31:24,835 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:24,841 : INFO : < 200 OK [1387]
2017-12-31 21:31:24,844 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Scott  Klemmer'}}
2017-12-31 21:31:24,847 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:24,853 : INFO : < 200 OK [1389]
2017-12-31 21:31:24,856 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Carleton Coffrin'}}
2017-12-31 21:31:24,859 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:24,865 : INFO : < 200 OK [1395]
2017-12-31 21:31:24,869 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Paul Gries'}}
2017-12-31 21:31:24,873 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:24,880 : INFO : < 200 OK [1385]

2017-12-31 21:31:24,884 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Richard Paap'}}
2017-12-31 21:31:24,887 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:24,894 : INFO : < 200 OK [1387]
2017-12-31 21:31:24,897 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anne Remke'}}
2017-12-31 21:31:24,900 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:24,905 : INFO : < 200 OK [1385]
2017-12-31 21:31:24,909 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kenneth W T Leung'}}
2017-12-31 21:31:24,912 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:24,918 : INFO : < 200 OK [1392]
2017-12-31 21:31:24,921 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr.  Sarah Eichhorn'}}
2017-12-31 21:31:24,924 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:24,930 : INFO : < 200 OK [1394]
2017-12-31 21:31:24,933 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Martine Haas'}}
2017-12-31 21:31:24,936 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:24,942 : INFO : < 200 OK [1387]
2017-12-31 21:31:24,945 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Professor Wayne Winston'}}
2017-12-31 21:31:24,948 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:24,953 : INFO : < 200 OK [1398]
2017-12-31 21:31:24,957 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Evgeny Sokolov'}}
2017-12-31 21:31:24,960 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:24,966 : INFO : < 200 OK [1389]
2017-12-31 21:31:24,970 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Autodesk Education'}}
2017-12-31 21:31:24,973 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:24,979 : INFO : < 200 OK [1393]
2017-12-31 21:31:24,983 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mai Nguyen'}}
2017-12-31 21:31:24,986 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:24,991 : INFO : < 200 OK [1385]
2017-12-31 21:31:24,995 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mariel Leonard'}}
2017-12-31 21:31:24,998 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:25,003 : INFO : < 200 OK [1389]
2017-12-31 21:31:25,007 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Roberto Cazzolla Gatti'}}
2017-12-31 21:31:25,010 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:25,015 : INFO : < 200 OK [1397]
2017-12-31 21:31:25,018 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Cameron Campbell'}}
2017-12-31 21:31:25,021 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:25,026 : INFO : < 200 OK [1391]
2017-12-31 21:31:25,029 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christopher D. Ittner'}}
2017-12-31 21:31:25,032 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:25,038 : INFO : < 200 OK [1396]
2017-12-31 21:31:25,042 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nicola Osborne'}}
2017-12-31 21:31:25,046 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:25,052 : INFO : < 200 OK [1389]
2017-12-31 21:31:25,056 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Joyelle Harris'}}
2017-12-31 21:31:25,061 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:25,066 : INFO : < 200 OK [1393]
2017-12-31 21:31:25,070 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Julien Fasson'}}
2017-12-31 21:31:25,074 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:25,080 : INFO : < 200 OK [1388]
2017-12-31 21:31:25,084 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Prof. Viktor Kuncak'}}
2017-12-31 21:31:25,087 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:25,093 : INFO : < 200 OK [1394]
2017-12-31 21:31:25,097 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Joaquín Saiz Alcaine'}}
2017-12-31 21:31:25,100 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:25,105 : INFO : < 200 OK [1396]
2017-12-31 21:31:25,109 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Emily Fox'}}
2017-12-31 21:31:25,112 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:25,116 : INFO : < 200 OK [1384]
2017-12-31 21:31:25,120 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jacob Pritt'}}
2017-12-31 21:31:25,122 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:25,127 : INFO : < 200 OK [1386]
2017-12-31 21:31:25,131 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Paolo Prandoni'}}
2017-12-31 21:31:25,134 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:25,139 : INFO : < 200 OK [1389]
2017-12-31 21:31:25,143 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert Duvall'}}
2017-12-31 21:31:25,147 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:25,154 : INFO : < 200 OK [1388]
2017-12-31 21:31:25,160 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vera Schölmerich'}}
2017-12-31 21:31:25,163 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:25,168 : INFO : < 200 OK [1392]
2017-12-31 21:31:25,172 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Wayne'}}
2017-12-31 21:31:25,175 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:25,181 : INFO : < 200 OK [1386]
2017-12-31 21:31:25,185 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Robert  Clark'}}
2017-12-31 21:31:25,188 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:25,193 : INFO : < 200 OK [1388]
2017-12-31 21:31:25,196 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Juha Plosila'}}
2017-12-31 21:31:25,199 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:25,204 : INFO : < 200 OK [1387]
2017-12-31 21:31:25,208 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel Egger'}}
2017-12-31 21:31:25,211 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:25,216 : INFO : < 200 OK [1387]
2017-12-31 21:31:25,219 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jim Fowler, PhD'}}
2017-12-31 21:31:25,223 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:25,228 : INFO : < 200 OK [1390]
2017-12-31 21:31:25,231 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Paul Rodriguez'}}
2017-12-31 21:31:25,234 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:25,239 : INFO : < 200 OK [1389]
2017-12-31 21:31:25,243 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Mr. Andy Green'}}
2017-12-31 21:31:25,246 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:25,251 : INFO : < 200 OK [1389]
2017-12-31 21:31:25,255 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jim Stafford'}}
2017-12-31 21:31:25,259 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:25,265 : INFO : < 200 OK [1387]
2017-12-31 21:31:25,271 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Karen  Monsen, Ph.D., RN, FAAN'}}
2017-12-31 21:31:25,274 : INFO : > POST http://localhost:7474/db/data/cypher [105]
2017-12-31 21:31:25,281 : INFO : < 200 OK [1405]
2017-12-31 21:31:25,285 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Brian Winn'}}
2017-12-31 21:31:25,288 : INFO : > POST http://localhost:7474/db/data/cypher [85]
2017-12-31 21:31:25,294 : INFO : < 200 OK [1385]

2017-12-31 21:31:25,298 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Théotime Vaillant'}}
2017-12-31 21:31:25,302 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:25,308 : INFO : < 200 OK [1393]
2017-12-31 21:31:25,311 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Surya Kalidindi'}}
2017-12-31 21:31:25,314 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:25,320 : INFO : < 200 OK [1394]
2017-12-31 21:31:25,323 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexander Guschin'}}
2017-12-31 21:31:25,327 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:25,332 : INFO : < 200 OK [1392]
2017-12-31 21:31:25,335 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Paul Harris, PhD'}}
2017-12-31 21:31:25,338 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:25,344 : INFO : < 200 OK [1391]
2017-12-31 21:31:25,348 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Petra Bonfert-Taylor'}}
2017-12-31 21:31:25,351 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2017-12-31 21:31:25,355 : INFO : < 200 OK [1399]
2017-12-31 21:31:25,360 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'James Taylor, PhD'}}
2017-12-31 21:31:25,363 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:25,369 : INFO : < 200 OK [1392]
2017-12-31 21:31:25,372 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Charlie Nuttelman'}}
2017-12-31 21:31:25,376 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:25,381 : INFO : < 200 OK [1392]
2017-12-31 21:31:25,385 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Nicolas Glady '}}
2017-12-31 21:31:25,389 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:25,394 : INFO : < 200 OK [1389]
2017-12-31 21:31:25,398 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daniel E. Koditschek'}}
2017-12-31 21:31:25,402 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:25,407 : INFO : < 200 OK [1395]
2017-12-31 21:31:25,411 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ameya Sathe'}}
2017-12-31 21:31:25,415 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:25,421 : INFO : < 200 OK [1386]
2017-12-31 21:31:25,425 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr Kate Devlin'}}
2017-12-31 21:31:25,429 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:25,434 : INFO : < 200 OK [1389]
2017-12-31 21:31:25,438 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Daphne Koller'}}
2017-12-31 21:31:25,442 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:25,448 : INFO : < 200 OK [1388]
2017-12-31 21:31:25,452 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrea Zonca'}}
2017-12-31 21:31:25,455 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:25,460 : INFO : < 200 OK [1387]
2017-12-31 21:31:25,464 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Raghu Iyengar'}}
2017-12-31 21:31:25,467 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:25,473 : INFO : < 200 OK [1388]
2017-12-31 21:31:25,477 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'ZHANG Li'}}
2017-12-31 21:31:25,480 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2017-12-31 21:31:25,485 : INFO : < 200 OK [1383]
2017-12-31 21:31:25,490 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'John Gill, J.D., CFE'}}
2017-12-31 21:31:25,493 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:25,505 : INFO : < 200 OK [1395]
2017-12-31 21:31:25,511 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christopher Brinton'}}
2017-12-31 21:31:25,514 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:25,520 : INFO : < 200 OK [1394]
2017-12-31 21:31:25,524 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Bill Bailey, PhD'}}
2017-12-31 21:31:25,528 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:25,534 : INFO : < 200 OK [1391]
2017-12-31 21:31:25,538 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Cook, PhD'}}
2017-12-31 21:31:25,541 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:25,547 : INFO : < 200 OK [1390]
2017-12-31 21:31:25,551 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tarik Benaddi'}}
2017-12-31 21:31:25,554 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:25,560 : INFO : < 200 OK [1388]
2017-12-31 21:31:25,564 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Natalia Pritykovskaya'}}
2017-12-31 21:31:25,567 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:25,573 : INFO : < 200 OK [1396]
2017-12-31 21:31:25,577 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christine Alvarado'}}
2017-12-31 21:31:25,581 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:25,587 : INFO : < 200 OK [1393]
2017-12-31 21:31:25,592 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Philip Hans Franses'}}
2017-12-31 21:31:25,596 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:25,602 : INFO : < 200 OK [1394]
2017-12-31 21:31:25,606 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrei Zimovnov'}}
2017-12-31 21:31:25,610 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:25,616 : INFO : < 200 OK [1390]
2017-12-31 21:31:25,620 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Phillip Compeau'}}
2017-12-31 21:31:25,623 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:25,629 : INFO : < 200 OK [1390]
2017-12-31 21:31:25,633 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Andrew Ng'}}
2017-12-31 21:31:25,636 : INFO : > POST http://localhost:7474/db/data/cypher [84]
2017-12-31 21:31:25,642 : INFO : < 200 OK [1384]
2017-12-31 21:31:25,646 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Prof. Peter James Stuckey'}}
2017-12-31 21:31:25,650 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:25,656 : INFO : < 200 OK [1400]
2017-12-31 21:31:25,660 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Emeli Dral '}}
2017-12-31 21:31:25,664 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:25,670 : INFO : < 200 OK [1386]
2017-12-31 21:31:25,674 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Clement Levallois'}}
2017-12-31 21:31:25,678 : INFO : > POST http://localhost:7474/db/data/cypher [92]
2017-12-31 21:31:25,684 : INFO : < 200 OK [1392]
2017-12-31 21:31:25,688 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jennifer Golbeck'}}
2017-12-31 21:31:25,692 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:25,698 : INFO : < 200 OK [1391]
2017-12-31 21:31:25,704 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Teaching Assistant - Younes Bensouda Mourri'}}
2017-12-31 21:31:25,709 : INFO : > POST http://localhost:7474/db/data/cypher [118]
2017-12-31 21:31:25,716 : INFO : < 200 OK [1418]
2017-12-31 21:31:25,720 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'H.V. Jagadish'}}
2017-12-31 21:31:25,724 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:25,730 : INFO : < 200 OK [1388]
2017-12-31 21:31:25,734 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Liliana Florea, PhD'}}
2017-12-31 21:31:25,737 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:25,743 : INFO : < 200 OK [1394]

2017-12-31 21:31:25,747 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Vladimir Lesnichenko'}}
2017-12-31 21:31:25,751 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:25,756 : INFO : < 200 OK [1395]
2017-12-31 21:31:25,760 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dmitry Ulyanov'}}
2017-12-31 21:31:25,764 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:25,769 : INFO : < 200 OK [1389]
2017-12-31 21:31:25,773 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevin Wendt'}}
2017-12-31 21:31:25,778 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:25,784 : INFO : < 200 OK [1386]
2017-12-31 21:31:25,788 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Elizabeth Gerber'}}
2017-12-31 21:31:25,792 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:25,798 : INFO : < 200 OK [1391]
2017-12-31 21:31:25,802 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Hunter Whitney'}}
2017-12-31 21:31:25,805 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:25,811 : INFO : < 200 OK [1389]
2017-12-31 21:31:25,815 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Helen Tibbo'}}
2017-12-31 21:31:25,818 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:25,824 : INFO : < 200 OK [1386]
2017-12-31 21:31:25,828 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jan Friso Groote'}}
2017-12-31 21:31:25,831 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:25,836 : INFO : < 200 OK [1391]
2017-12-31 21:31:25,840 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': ' Dr Sylvia Xueni Pan'}}
2017-12-31 21:31:25,843 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:25,849 : INFO : < 200 OK [1395]
2017-12-31 21:31:25,853 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Kevyn Collins-Thompson'}}
2017-12-31 21:31:25,857 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:25,862 : INFO : < 200 OK [1397]
2017-12-31 21:31:25,867 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Alexey A. Dral'}}
2017-12-31 21:31:25,871 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:25,878 : INFO : < 200 OK [1389]
2017-12-31 21:31:25,882 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Timothy Scherr'}}
2017-12-31 21:31:25,885 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:25,891 : INFO : < 200 OK [1389]
2017-12-31 21:31:25,895 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'David Banks'}}
2017-12-31 21:31:25,899 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:25,904 : INFO : < 200 OK [1386]
2017-12-31 21:31:25,908 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Suk S. Brar, M.B.A.'}}
2017-12-31 21:31:25,912 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:25,917 : INFO : < 200 OK [1394]
2017-12-31 21:31:25,921 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sergei Savin'}}
2017-12-31 21:31:25,925 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:25,930 : INFO : < 200 OK [1387]
2017-12-31 21:31:25,934 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Martin Lindquist, PhD, MSc'}}
2017-12-31 21:31:25,938 : INFO : > POST http://localhost:7474/db/data/cypher [101]
2017-12-31 21:31:25,944 : INFO : < 200 OK [1401]
2017-12-31 21:31:25,948 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Rebekah May'}}
2017-12-31 21:31:25,951 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:25,956 : INFO : < 200 OK [1386]
2017-12-31 21:31:25,960 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Parham Aarabi'}}
2017-12-31 21:31:25,964 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:25,969 : INFO : < 200 OK [1388]
2017-12-31 21:31:25,973 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Arvind Narayanan'}}
2017-12-31 21:31:25,977 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:25,983 : INFO : < 200 OK [1391]
2017-12-31 21:31:25,987 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Anther Kiley'}}
2017-12-31 21:31:25,991 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:25,997 : INFO : < 200 OK [1387]
2017-12-31 21:31:26,001 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Jen Rose'}}
2017-12-31 21:31:26,004 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2017-12-31 21:31:26,010 : INFO : < 200 OK [1383]
2017-12-31 21:31:26,014 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Víctor Manuel de la Cueva Hernández'}}
2017-12-31 21:31:26,018 : INFO : > POST http://localhost:7474/db/data/cypher [124]
2017-12-31 21:31:26,023 : INFO : < 200 OK [1416]
2017-12-31 21:31:26,027 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ilya Trofimov'}}
2017-12-31 21:31:26,031 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:26,036 : INFO : < 200 OK [1388]
2017-12-31 21:31:26,040 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Yoav Shoham'}}
2017-12-31 21:31:26,043 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:26,049 : INFO : < 200 OK [1386]
2017-12-31 21:31:26,053 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Michael Hicks'}}
2017-12-31 21:31:26,057 : INFO : > POST http://localhost:7474/db/data/cypher [88]
2017-12-31 21:31:26,063 : INFO : < 200 OK [1388]
2017-12-31 21:31:26,067 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ant Cole'}}
2017-12-31 21:31:26,072 : INFO : > POST http://localhost:7474/db/data/cypher [83]
2017-12-31 21:31:26,079 : INFO : < 200 OK [1383]
2017-12-31 21:31:26,083 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dr. Bonnie H. Ferri'}}
2017-12-31 21:31:26,087 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:26,092 : INFO : < 200 OK [1394]
2017-12-31 21:31:26,096 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Frauke Kreuter, Ph.D.'}}
2017-12-31 21:31:26,099 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:26,105 : INFO : < 200 OK [1396]
2017-12-31 21:31:26,109 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Sang-Yoon Chang'}}
2017-12-31 21:31:26,112 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:26,117 : INFO : < 200 OK [1390]
2017-12-31 21:31:26,121 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Tara Murphy'}}
2017-12-31 21:31:26,125 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:26,130 : INFO : < 200 OK [1386]
2017-12-31 21:31:26,134 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Eric Sobie, PhD'}}
2017-12-31 21:31:26,138 : INFO : > POST http://localhost:7474/db/data/cypher [90]
2017-12-31 21:31:26,145 : INFO : < 200 OK [1390]
2017-12-31 21:31:26,150 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Pavel Mezentsev '}}
2017-12-31 21:31:26,154 : INFO : > POST http://localhost:7474/db/data/cypher [91]
2017-12-31 21:31:26,160 : INFO : < 200 OK [1391]
2017-12-31 21:31:26,164 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Ekaterina Lobacheva'}}
2017-12-31 21:31:26,169 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:26,175 : INFO : < 200 OK [1394]
2017-12-31 21:31:26,180 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Fran Krause'}}
2017-12-31 21:31:26,183 : INFO : > POST http://localhost:7474/db/data/cypher [86]
2017-12-31 21:31:26,191 : INFO : < 200 OK [1386]

2017-12-31 21:31:26,196 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Randy Hlavac'}}
2017-12-31 21:31:26,200 : INFO : > POST http://localhost:7474/db/data/cypher [87]
2017-12-31 21:31:26,206 : INFO : < 200 OK [1387]
2017-12-31 21:31:26,211 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Christina Scherrer, PhD'}}
2017-12-31 21:31:26,215 : INFO : > POST http://localhost:7474/db/data/cypher [98]
2017-12-31 21:31:26,221 : INFO : < 200 OK [1398]
2017-12-31 21:31:26,225 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Myrthe van Dieijen'}}
2017-12-31 21:31:26,228 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:26,233 : INFO : < 200 OK [1393]
2017-12-31 21:31:26,237 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Dragomir R. Radev, Ph.D.'}}
2017-12-31 21:31:26,240 : INFO : > POST http://localhost:7474/db/data/cypher [99]
2017-12-31 21:31:26,246 : INFO : < 200 OK [1399]
2017-12-31 21:31:26,252 : INFO : execute 'CREATE (_0:Teacher {_0})\nRETURN _0' {'_0': {'name': 'Matthew Heiner'}}
2017-12-31 21:31:26,255 : INFO : > POST http://localhost:7474/db/data/cypher [89]
2017-12-31 21:31:26,261 : INFO : < 200 OK [1389]

In [85]:
## add teach relation
for i, row in data.drop_duplicates(subset=['teach_by', 'uid']).iterrows():
    x = teach_dict[row.teach_by]
    y = course_dict[row.uid]
    graph.create(Relationship(x, "teach", y))

2017-12-31 21:35:35,666 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1012, '_0n0': 1223}
2017-12-31 21:35:35,670 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:35:35,673 : INFO : ~ Reconnecting (connection aborted)
2017-12-31 21:35:36,680 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:35:36,724 : INFO : < 200 OK [3309]
2017-12-31 21:35:36,729 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 987, '_0n0': 878}
2017-12-31 21:35:36,732 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:36,738 : INFO : < 200 OK [3249]
2017-12-31 21:35:36,742 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1013, '_0n0': 895}
2017-12-31 21:35:36,745 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:36,750 : INFO : < 200 OK [3350]
2017-12-31 21:35:36,755 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 988, '_0n0': 895}
2017-12-31 21:35:36,758 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:36,763 : INFO : < 200 OK [3308]
2017-12-31 21:35:36,771 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1014, '_0n0': 1208}
2017-12-31 21:35:36,775 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:35:36,781 : INFO : < 200 OK [3285]
2017-12-31 21:35:36,788 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 989, '_0n0': 833}
2017-12-31 21:35:36,793 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:36,799 : INFO : < 200 OK [3309]
2017-12-31 21:35:36,804 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 0, '_0n0': 822}
2017-12-31 21:35:36,808 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:35:36,815 : INFO : < 200 OK [3273]
2017-12-31 21:35:36,820 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 990, '_0n0': 1071}
2017-12-31 21:35:36,824 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:36,829 : INFO : < 200 OK [3318]
2017-12-31 21:35:36,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1, '_0n0': 746}
2017-12-31 21:35:36,837 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:35:36,842 : INFO : < 200 OK [3262]
2017-12-31 21:35:36,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 991, '_0n0': 895}
2017-12-31 21:35:36,849 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:36,854 : INFO : < 200 OK [3322]
2017-12-31 21:35:36,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 2, '_0n0': 1226}
2017-12-31 21:35:36,862 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:36,867 : INFO : < 200 OK [3241]
2017-12-31 21:35:36,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 992, '_0n0': 895}
2017-12-31 21:35:36,874 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:36,879 : INFO : < 200 OK [3325]
2017-12-31 21:35:36,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 3, '_0n0': 776}
2017-12-31 21:35:36,886 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:35:36,891 : INFO : < 200 OK [3235]
2017-12-31 21:35:36,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 993, '_0n0': 958}
2017-12-31 21:35:36,899 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:36,904 : INFO : < 200 OK [3327]
2017-12-31 21:35:36,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 993, '_0n0': 908}
2017-12-31 21:35:36,911 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:36,919 : INFO : < 200 OK [3325]
2017-12-31 21:35:36,926 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 993, '_0n0': 866}
2017-12-31 21:35:36,932 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:36,941 : INFO : < 200 OK [3320]
2017-12-31 21:35:36,946 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 4, '_0n0': 895}
2017-12-31 21:35:36,950 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:35:36,956 : INFO : < 200 OK [3302]
2017-12-31 21:35:36,962 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 994, '_0n0': 833}
2017-12-31 21:35:36,965 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:36,971 : INFO : < 200 OK [3304]
2017-12-31 21:35:36,976 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 5, '_0n0': 895}
2017-12-31 21:35:36,980 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:35:36,986 : INFO : < 200 OK [3303]
2017-12-31 21:35:36,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 995, '_0n0': 842}
2017-12-31 21:35:36,995 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,001 : INFO : < 200 OK [3306]
2017-12-31 21:35:37,006 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 6, '_0n0': 1127}
2017-12-31 21:35:37,009 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,015 : INFO : < 200 OK [3293]
2017-12-31 21:35:37,018 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 12, '_0n0': 1038}
2017-12-31 21:35:37,022 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,027 : INFO : < 200 OK [3344]
2017-12-31 21:35:37,032 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 12, '_0n0': 1036}
2017-12-31 21:35:37,035 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,040 : INFO : < 200 OK [3341]
2017-12-31 21:35:37,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 7, '_0n0': 1054}
2017-12-31 21:35:37,048 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,054 : INFO : < 200 OK [3230]

2017-12-31 21:35:37,058 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 13, '_0n0': 1127}
2017-12-31 21:35:37,061 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,066 : INFO : < 200 OK [3310]
2017-12-31 21:35:37,071 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 8, '_0n0': 895}
2017-12-31 21:35:37,074 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:35:37,079 : INFO : < 200 OK [3314]
2017-12-31 21:35:37,084 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 14, '_0n0': 776}
2017-12-31 21:35:37,087 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,092 : INFO : < 200 OK [3298]
2017-12-31 21:35:37,097 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 9, '_0n0': 833}
2017-12-31 21:35:37,100 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:35:37,106 : INFO : < 200 OK [3262]
2017-12-31 21:35:37,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 15, '_0n0': 779}
2017-12-31 21:35:37,114 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,119 : INFO : < 200 OK [3254]
2017-12-31 21:35:37,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 10, '_0n0': 743}
2017-12-31 21:35:37,128 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,134 : INFO : < 200 OK [3269]
2017-12-31 21:35:37,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 16, '_0n0': 833}
2017-12-31 21:35:37,143 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,148 : INFO : < 200 OK [3287]
2017-12-31 21:35:37,154 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 11, '_0n0': 798}
2017-12-31 21:35:37,157 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,162 : INFO : < 200 OK [3236]
2017-12-31 21:35:37,166 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 17, '_0n0': 833}
2017-12-31 21:35:37,169 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,174 : INFO : < 200 OK [3295]
2017-12-31 21:35:37,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 32, '_0n0': 1036}
2017-12-31 21:35:37,182 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,187 : INFO : < 200 OK [3313]
2017-12-31 21:35:37,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 32, '_0n0': 1038}
2017-12-31 21:35:37,195 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,200 : INFO : < 200 OK [3316]
2017-12-31 21:35:37,205 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 18, '_0n0': 1228}
2017-12-31 21:35:37,207 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,213 : INFO : < 200 OK [3309]
2017-12-31 21:35:37,217 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 33, '_0n0': 746}
2017-12-31 21:35:37,220 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,225 : INFO : < 200 OK [3279]
2017-12-31 21:35:37,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 19, '_0n0': 895}
2017-12-31 21:35:37,232 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,237 : INFO : < 200 OK [3310]
2017-12-31 21:35:37,241 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 34, '_0n0': 1127}
2017-12-31 21:35:37,244 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,249 : INFO : < 200 OK [3310]
2017-12-31 21:35:37,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 20, '_0n0': 873}
2017-12-31 21:35:37,257 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,263 : INFO : < 200 OK [3245]
2017-12-31 21:35:37,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 20, '_0n0': 847}
2017-12-31 21:35:37,270 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,276 : INFO : < 200 OK [3238]
2017-12-31 21:35:37,281 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 35, '_0n0': 895}
2017-12-31 21:35:37,285 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,294 : INFO : < 200 OK [3314]
2017-12-31 21:35:37,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 21, '_0n0': 964}
2017-12-31 21:35:37,303 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,310 : INFO : < 200 OK [3293]
2017-12-31 21:35:37,317 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 21, '_0n0': 826}
2017-12-31 21:35:37,321 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,328 : INFO : < 200 OK [3294]
2017-12-31 21:35:37,333 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 21, '_0n0': 1228}
2017-12-31 21:35:37,338 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,343 : INFO : < 200 OK [3311]
2017-12-31 21:35:37,348 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 36, '_0n0': 1074}
2017-12-31 21:35:37,351 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,357 : INFO : < 200 OK [3249]
2017-12-31 21:35:37,362 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 22, '_0n0': 1127}
2017-12-31 21:35:37,365 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,371 : INFO : < 200 OK [3300]
2017-12-31 21:35:37,375 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 37, '_0n0': 746}
2017-12-31 21:35:37,379 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,385 : INFO : < 200 OK [3270]

2017-12-31 21:35:37,390 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 23, '_0n0': 842}
2017-12-31 21:35:37,392 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,398 : INFO : < 200 OK [3247]
2017-12-31 21:35:37,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 38, '_0n0': 773}
2017-12-31 21:35:37,407 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,413 : INFO : < 200 OK [3290]
2017-12-31 21:35:37,417 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 38, '_0n0': 946}
2017-12-31 21:35:37,420 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,426 : INFO : < 200 OK [3286]
2017-12-31 21:35:37,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 24, '_0n0': 1071}
2017-12-31 21:35:37,433 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,439 : INFO : < 200 OK [3307]
2017-12-31 21:35:37,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 39, '_0n0': 1046}
2017-12-31 21:35:37,447 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,452 : INFO : < 200 OK [3265]
2017-12-31 21:35:37,457 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 39, '_0n0': 733}
2017-12-31 21:35:37,460 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,466 : INFO : < 200 OK [3253]
2017-12-31 21:35:37,470 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 25, '_0n0': 776}
2017-12-31 21:35:37,474 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,480 : INFO : < 200 OK [3280]
2017-12-31 21:35:37,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 40, '_0n0': 964}
2017-12-31 21:35:37,489 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,496 : INFO : < 200 OK [3293]
2017-12-31 21:35:37,501 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 40, '_0n0': 826}
2017-12-31 21:35:37,504 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,510 : INFO : < 200 OK [3294]
2017-12-31 21:35:37,514 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 40, '_0n0': 1228}
2017-12-31 21:35:37,517 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,523 : INFO : < 200 OK [3311]
2017-12-31 21:35:37,528 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 26, '_0n0': 1127}
2017-12-31 21:35:37,531 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,536 : INFO : < 200 OK [3281]
2017-12-31 21:35:37,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 41, '_0n0': 822}
2017-12-31 21:35:37,544 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,549 : INFO : < 200 OK [3300]
2017-12-31 21:35:37,554 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 41, '_0n0': 1018}
2017-12-31 21:35:37,557 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,562 : INFO : < 200 OK [3313]
2017-12-31 21:35:37,567 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 41, '_0n0': 1156}
2017-12-31 21:35:37,569 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,575 : INFO : < 200 OK [3312]
2017-12-31 21:35:37,579 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 41, '_0n0': 752}
2017-12-31 21:35:37,582 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,587 : INFO : < 200 OK [3326]
2017-12-31 21:35:37,592 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 41, '_0n0': 802}
2017-12-31 21:35:37,596 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,601 : INFO : < 200 OK [3318]
2017-12-31 21:35:37,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 27, '_0n0': 1071}
2017-12-31 21:35:37,607 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,613 : INFO : < 200 OK [3301]
2017-12-31 21:35:37,618 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 42, '_0n0': 1071}
2017-12-31 21:35:37,620 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,626 : INFO : < 200 OK [3317]
2017-12-31 21:35:37,630 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 28, '_0n0': 1127}
2017-12-31 21:35:37,634 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,639 : INFO : < 200 OK [3318]
2017-12-31 21:35:37,643 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 43, '_0n0': 1033}
2017-12-31 21:35:37,646 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,651 : INFO : < 200 OK [3288]
2017-12-31 21:35:37,656 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 43, '_0n0': 790}
2017-12-31 21:35:37,659 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,664 : INFO : < 200 OK [3274]
2017-12-31 21:35:37,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 29, '_0n0': 895}
2017-12-31 21:35:37,672 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,678 : INFO : < 200 OK [3321]
2017-12-31 21:35:37,684 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 44, '_0n0': 773}
2017-12-31 21:35:37,689 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,696 : INFO : < 200 OK [3302]
2017-12-31 21:35:37,702 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 30, '_0n0': 842}
2017-12-31 21:35:37,707 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,714 : INFO : < 200 OK [3242]

2017-12-31 21:35:37,719 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 45, '_0n0': 1087}
2017-12-31 21:35:37,722 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,728 : INFO : < 200 OK [3271]
2017-12-31 21:35:37,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 45, '_0n0': 1186}
2017-12-31 21:35:37,736 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,742 : INFO : < 200 OK [3279]
2017-12-31 21:35:37,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 31, '_0n0': 1228}
2017-12-31 21:35:37,749 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,755 : INFO : < 200 OK [3271]
2017-12-31 21:35:37,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 46, '_0n0': 776}
2017-12-31 21:35:37,763 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,769 : INFO : < 200 OK [3300]
2017-12-31 21:35:37,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 52, '_0n0': 842}
2017-12-31 21:35:37,777 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,782 : INFO : < 200 OK [3269]
2017-12-31 21:35:37,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 47, '_0n0': 756}
2017-12-31 21:35:37,790 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,795 : INFO : < 200 OK [3308]
2017-12-31 21:35:37,801 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 47, '_0n0': 893}
2017-12-31 21:35:37,805 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,811 : INFO : < 200 OK [3310]
2017-12-31 21:35:37,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 53, '_0n0': 1228}
2017-12-31 21:35:37,818 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,823 : INFO : < 200 OK [3291]
2017-12-31 21:35:37,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 48, '_0n0': 1154}
2017-12-31 21:35:37,831 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,837 : INFO : < 200 OK [3319]
2017-12-31 21:35:37,841 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 48, '_0n0': 972}
2017-12-31 21:35:37,845 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,850 : INFO : < 200 OK [3311]
2017-12-31 21:35:37,856 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 54, '_0n0': 1127}
2017-12-31 21:35:37,860 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,865 : INFO : < 200 OK [3295]
2017-12-31 21:35:37,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 49, '_0n0': 746}
2017-12-31 21:35:37,874 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,880 : INFO : < 200 OK [3255]
2017-12-31 21:35:37,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 55, '_0n0': 1228}
2017-12-31 21:35:37,887 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,893 : INFO : < 200 OK [3292]
2017-12-31 21:35:37,898 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 50, '_0n0': 822}
2017-12-31 21:35:37,902 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,909 : INFO : < 200 OK [3282]
2017-12-31 21:35:37,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 56, '_0n0': 1186}
2017-12-31 21:35:37,917 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,923 : INFO : < 200 OK [3322]
2017-12-31 21:35:37,928 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 56, '_0n0': 1087}
2017-12-31 21:35:37,932 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,937 : INFO : < 200 OK [3314]
2017-12-31 21:35:37,943 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 51, '_0n0': 1127}
2017-12-31 21:35:37,946 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,952 : INFO : < 200 OK [3300]
2017-12-31 21:35:37,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 57, '_0n0': 826}
2017-12-31 21:35:37,961 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,967 : INFO : < 200 OK [3328]
2017-12-31 21:35:37,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 72, '_0n0': 837}
2017-12-31 21:35:37,975 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:37,981 : INFO : < 200 OK [3253]
2017-12-31 21:35:37,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 58, '_0n0': 1213}
2017-12-31 21:35:37,989 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:37,995 : INFO : < 200 OK [3344]
2017-12-31 21:35:38,000 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 73, '_0n0': 826}
2017-12-31 21:35:38,003 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,009 : INFO : < 200 OK [3314]
2017-12-31 21:35:38,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 59, '_0n0': 788}
2017-12-31 21:35:38,017 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,025 : INFO : < 200 OK [3267]
2017-12-31 21:35:38,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 59, '_0n0': 928}
2017-12-31 21:35:38,032 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,037 : INFO : < 200 OK [3265]
2017-12-31 21:35:38,042 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 74, '_0n0': 826}
2017-12-31 21:35:38,045 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,050 : INFO : < 200 OK [3294]

2017-12-31 21:35:38,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 60, '_0n0': 822}
2017-12-31 21:35:38,058 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,063 : INFO : < 200 OK [3286]
2017-12-31 21:35:38,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 60, '_0n0': 1018}
2017-12-31 21:35:38,071 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,077 : INFO : < 200 OK [3299]
2017-12-31 21:35:38,081 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 60, '_0n0': 752}
2017-12-31 21:35:38,084 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,090 : INFO : < 200 OK [3312]
2017-12-31 21:35:38,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 60, '_0n0': 1156}
2017-12-31 21:35:38,099 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,107 : INFO : < 200 OK [3298]
2017-12-31 21:35:38,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 60, '_0n0': 802}
2017-12-31 21:35:38,119 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,125 : INFO : < 200 OK [3304]
2017-12-31 21:35:38,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 75, '_0n0': 746}
2017-12-31 21:35:38,134 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,139 : INFO : < 200 OK [3257]
2017-12-31 21:35:38,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 61, '_0n0': 826}
2017-12-31 21:35:38,147 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,153 : INFO : < 200 OK [3314]
2017-12-31 21:35:38,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 76, '_0n0': 895}
2017-12-31 21:35:38,160 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,166 : INFO : < 200 OK [3325]
2017-12-31 21:35:38,172 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 62, '_0n0': 1042}
2017-12-31 21:35:38,175 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,181 : INFO : < 200 OK [3262]
2017-12-31 21:35:38,188 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 62, '_0n0': 1038}
2017-12-31 21:35:38,191 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,196 : INFO : < 200 OK [3263]
2017-12-31 21:35:38,201 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 62, '_0n0': 873}
2017-12-31 21:35:38,204 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,210 : INFO : < 200 OK [3252]
2017-12-31 21:35:38,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 62, '_0n0': 847}
2017-12-31 21:35:38,218 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,223 : INFO : < 200 OK [3245]
2017-12-31 21:35:38,228 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 77, '_0n0': 822}
2017-12-31 21:35:38,231 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,236 : INFO : < 200 OK [3295]
2017-12-31 21:35:38,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 77, '_0n0': 1018}
2017-12-31 21:35:38,243 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,248 : INFO : < 200 OK [3308]
2017-12-31 21:35:38,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 77, '_0n0': 752}
2017-12-31 21:35:38,256 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,261 : INFO : < 200 OK [3321]
2017-12-31 21:35:38,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 77, '_0n0': 1156}
2017-12-31 21:35:38,268 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,274 : INFO : < 200 OK [3307]
2017-12-31 21:35:38,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 77, '_0n0': 802}
2017-12-31 21:35:38,283 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,289 : INFO : < 200 OK [3313]
2017-12-31 21:35:38,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 63, '_0n0': 1208}
2017-12-31 21:35:38,298 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,304 : INFO : < 200 OK [3304]
2017-12-31 21:35:38,311 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 78, '_0n0': 743}
2017-12-31 21:35:38,315 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,321 : INFO : < 200 OK [3276]
2017-12-31 21:35:38,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 78, '_0n0': 1028}
2017-12-31 21:35:38,330 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,335 : INFO : < 200 OK [3295]
2017-12-31 21:35:38,340 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 64, '_0n0': 1206}
2017-12-31 21:35:38,343 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,349 : INFO : < 200 OK [3301]
2017-12-31 21:35:38,354 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 64, '_0n0': 1063}
2017-12-31 21:35:38,358 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,364 : INFO : < 200 OK [3335]
2017-12-31 21:35:38,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 64, '_0n0': 1193}
2017-12-31 21:35:38,371 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,376 : INFO : < 200 OK [3335]
2017-12-31 21:35:38,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 80, '_0n0': 1206}
2017-12-31 21:35:38,385 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,391 : INFO : < 200 OK [3297]

2017-12-31 21:35:38,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 80, '_0n0': 1063}
2017-12-31 21:35:38,398 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,404 : INFO : < 200 OK [3331]
2017-12-31 21:35:38,409 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 80, '_0n0': 1193}
2017-12-31 21:35:38,412 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,418 : INFO : < 200 OK [3331]
2017-12-31 21:35:38,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 65, '_0n0': 1206}
2017-12-31 21:35:38,427 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,434 : INFO : < 200 OK [3350]
2017-12-31 21:35:38,440 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 65, '_0n0': 1063}
2017-12-31 21:35:38,444 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,450 : INFO : < 200 OK [3384]
2017-12-31 21:35:38,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 65, '_0n0': 1193}
2017-12-31 21:35:38,459 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,465 : INFO : < 200 OK [3384]
2017-12-31 21:35:38,471 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 81, '_0n0': 1153}
2017-12-31 21:35:38,474 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,480 : INFO : < 200 OK [3288]
2017-12-31 21:35:38,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 81, '_0n0': 901}
2017-12-31 21:35:38,489 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,495 : INFO : < 200 OK [3278]
2017-12-31 21:35:38,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 66, '_0n0': 1066}
2017-12-31 21:35:38,503 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,509 : INFO : < 200 OK [3298]
2017-12-31 21:35:38,513 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 66, '_0n0': 903}
2017-12-31 21:35:38,517 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,523 : INFO : < 200 OK [3276]
2017-12-31 21:35:38,528 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 66, '_0n0': 849}
2017-12-31 21:35:38,531 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,536 : INFO : < 200 OK [3274]
2017-12-31 21:35:38,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 66, '_0n0': 863}
2017-12-31 21:35:38,544 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,549 : INFO : < 200 OK [3277]
2017-12-31 21:35:38,554 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 66, '_0n0': 1108}
2017-12-31 21:35:38,557 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,565 : INFO : < 200 OK [3291]
2017-12-31 21:35:38,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 82, '_0n0': 1206}
2017-12-31 21:35:38,574 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,582 : INFO : < 200 OK [3258]
2017-12-31 21:35:38,586 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 82, '_0n0': 1063}
2017-12-31 21:35:38,589 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,595 : INFO : < 200 OK [3292]
2017-12-31 21:35:38,600 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 82, '_0n0': 1193}
2017-12-31 21:35:38,603 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,608 : INFO : < 200 OK [3292]
2017-12-31 21:35:38,614 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 67, '_0n0': 782}
2017-12-31 21:35:38,617 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,622 : INFO : < 200 OK [3327]
2017-12-31 21:35:38,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 83, '_0n0': 953}
2017-12-31 21:35:38,631 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,637 : INFO : < 200 OK [3284]
2017-12-31 21:35:38,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 83, '_0n0': 1096}
2017-12-31 21:35:38,644 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,650 : INFO : < 200 OK [3299]
2017-12-31 21:35:38,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 83, '_0n0': 931}
2017-12-31 21:35:38,659 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,664 : INFO : < 200 OK [3284]
2017-12-31 21:35:38,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 83, '_0n0': 914}
2017-12-31 21:35:38,672 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,677 : INFO : < 200 OK [3282]
2017-12-31 21:35:38,681 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 68, '_0n0': 901}
2017-12-31 21:35:38,684 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,690 : INFO : < 200 OK [3279]
2017-12-31 21:35:38,694 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 68, '_0n0': 1153}
2017-12-31 21:35:38,697 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,703 : INFO : < 200 OK [3289]
2017-12-31 21:35:38,707 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 84, '_0n0': 1066}
2017-12-31 21:35:38,710 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,715 : INFO : < 200 OK [3293]
2017-12-31 21:35:38,721 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 84, '_0n0': 903}
2017-12-31 21:35:38,725 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,730 : INFO : < 200 OK [3271]

2017-12-31 21:35:38,735 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 84, '_0n0': 1108}
2017-12-31 21:35:38,738 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,747 : INFO : < 200 OK [3286]
2017-12-31 21:35:38,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 84, '_0n0': 849}
2017-12-31 21:35:38,757 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,764 : INFO : < 200 OK [3269]
2017-12-31 21:35:38,768 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 69, '_0n0': 912}
2017-12-31 21:35:38,772 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,778 : INFO : < 200 OK [3317]
2017-12-31 21:35:38,782 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 69, '_0n0': 1025}
2017-12-31 21:35:38,786 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,792 : INFO : < 200 OK [3328]
2017-12-31 21:35:38,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 85, '_0n0': 869}
2017-12-31 21:35:38,800 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,806 : INFO : < 200 OK [3280]
2017-12-31 21:35:38,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 85, '_0n0': 1090}
2017-12-31 21:35:38,814 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,820 : INFO : < 200 OK [3296]
2017-12-31 21:35:38,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 85, '_0n0': 740}
2017-12-31 21:35:38,827 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,833 : INFO : < 200 OK [3274]
2017-12-31 21:35:38,837 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 70, '_0n0': 1042}
2017-12-31 21:35:38,840 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,846 : INFO : < 200 OK [3300]
2017-12-31 21:35:38,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 86, '_0n0': 760}
2017-12-31 21:35:38,854 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,859 : INFO : < 200 OK [3283]
2017-12-31 21:35:38,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 71, '_0n0': 1199}
2017-12-31 21:35:38,867 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,872 : INFO : < 200 OK [3316]
2017-12-31 21:35:38,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 87, '_0n0': 1066}
2017-12-31 21:35:38,879 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,885 : INFO : < 200 OK [3291]
2017-12-31 21:35:38,891 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 87, '_0n0': 903}
2017-12-31 21:35:38,895 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,901 : INFO : < 200 OK [3269]
2017-12-31 21:35:38,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 87, '_0n0': 918}
2017-12-31 21:35:38,911 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,917 : INFO : < 200 OK [3274]
2017-12-31 21:35:38,923 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 93, '_0n0': 907}
2017-12-31 21:35:38,927 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,932 : INFO : < 200 OK [3257]
2017-12-31 21:35:38,936 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 88, '_0n0': 1048}
2017-12-31 21:35:38,939 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,945 : INFO : < 200 OK [3282]
2017-12-31 21:35:38,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 94, '_0n0': 1064}
2017-12-31 21:35:38,953 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,959 : INFO : < 200 OK [3325]
2017-12-31 21:35:38,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 94, '_0n0': 844}
2017-12-31 21:35:38,967 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,972 : INFO : < 200 OK [3306]
2017-12-31 21:35:38,977 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 89, '_0n0': 782}
2017-12-31 21:35:38,980 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:38,985 : INFO : < 200 OK [3308]
2017-12-31 21:35:38,989 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 95, '_0n0': 1066}
2017-12-31 21:35:38,993 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:38,998 : INFO : < 200 OK [3299]
2017-12-31 21:35:39,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 95, '_0n0': 903}
2017-12-31 21:35:39,005 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:39,010 : INFO : < 200 OK [3277]
2017-12-31 21:35:39,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 95, '_0n0': 1108}
2017-12-31 21:35:39,019 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,025 : INFO : < 200 OK [3292]
2017-12-31 21:35:39,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 95, '_0n0': 849}
2017-12-31 21:35:39,033 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:39,038 : INFO : < 200 OK [3275]
2017-12-31 21:35:39,043 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 90, '_0n0': 869}
2017-12-31 21:35:39,046 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:39,055 : INFO : < 200 OK [3269]
2017-12-31 21:35:39,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 90, '_0n0': 1090}
2017-12-31 21:35:39,065 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,070 : INFO : < 200 OK [3285]

2017-12-31 21:35:39,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 90, '_0n0': 740}
2017-12-31 21:35:39,079 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:39,084 : INFO : < 200 OK [3263]
2017-12-31 21:35:39,088 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 96, '_0n0': 782}
2017-12-31 21:35:39,092 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:39,097 : INFO : < 200 OK [3325]
2017-12-31 21:35:39,103 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 91, '_0n0': 834}
2017-12-31 21:35:39,106 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:39,111 : INFO : < 200 OK [3279]
2017-12-31 21:35:39,116 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 97, '_0n0': 863}
2017-12-31 21:35:39,120 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:39,126 : INFO : < 200 OK [3303]
2017-12-31 21:35:39,132 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 97, '_0n0': 1190}
2017-12-31 21:35:39,135 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,140 : INFO : < 200 OK [3319]
2017-12-31 21:35:39,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 92, '_0n0': 913}
2017-12-31 21:35:39,148 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:39,154 : INFO : < 200 OK [3296]
2017-12-31 21:35:39,159 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 92, '_0n0': 1136}
2017-12-31 21:35:39,162 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,168 : INFO : < 200 OK [3300]
2017-12-31 21:35:39,173 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 98, '_0n0': 1066}
2017-12-31 21:35:39,176 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,182 : INFO : < 200 OK [3303]
2017-12-31 21:35:39,186 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 113, '_0n0': 1066}
2017-12-31 21:35:39,189 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,195 : INFO : < 200 OK [3319]
2017-12-31 21:35:39,200 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 113, '_0n0': 918}
2017-12-31 21:35:39,203 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,208 : INFO : < 200 OK [3302]
2017-12-31 21:35:39,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 99, '_0n0': 952}
2017-12-31 21:35:39,217 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:39,222 : INFO : < 200 OK [3285]
2017-12-31 21:35:39,228 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 99, '_0n0': 931}
2017-12-31 21:35:39,231 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:39,237 : INFO : < 200 OK [3285]
2017-12-31 21:35:39,242 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 99, '_0n0': 914}
2017-12-31 21:35:39,245 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:35:39,250 : INFO : < 200 OK [3283]
2017-12-31 21:35:39,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 114, '_0n0': 1181}
2017-12-31 21:35:39,257 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,262 : INFO : < 200 OK [3308]
2017-12-31 21:35:39,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 100, '_0n0': 1066}
2017-12-31 21:35:39,269 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,275 : INFO : < 200 OK [3324]
2017-12-31 21:35:39,280 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 100, '_0n0': 903}
2017-12-31 21:35:39,283 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,291 : INFO : < 200 OK [3302]
2017-12-31 21:35:39,296 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 100, '_0n0': 1108}
2017-12-31 21:35:39,300 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,307 : INFO : < 200 OK [3317]
2017-12-31 21:35:39,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 100, '_0n0': 849}
2017-12-31 21:35:39,316 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,322 : INFO : < 200 OK [3300]
2017-12-31 21:35:39,328 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 115, '_0n0': 1204}
2017-12-31 21:35:39,332 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,337 : INFO : < 200 OK [3323]
2017-12-31 21:35:39,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 115, '_0n0': 735}
2017-12-31 21:35:39,345 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,351 : INFO : < 200 OK [3300]
2017-12-31 21:35:39,355 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 115, '_0n0': 870}
2017-12-31 21:35:39,359 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,364 : INFO : < 200 OK [3300]
2017-12-31 21:35:39,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 101, '_0n0': 1066}
2017-12-31 21:35:39,373 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,380 : INFO : < 200 OK [3315]
2017-12-31 21:35:39,386 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 101, '_0n0': 903}
2017-12-31 21:35:39,390 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,396 : INFO : < 200 OK [3293]
2017-12-31 21:35:39,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 101, '_0n0': 863}
2017-12-31 21:35:39,406 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,412 : INFO : < 200 OK [3294]

2017-12-31 21:35:39,417 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 101, '_0n0': 849}
2017-12-31 21:35:39,421 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,427 : INFO : < 200 OK [3291]
2017-12-31 21:35:39,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 116, '_0n0': 782}
2017-12-31 21:35:39,436 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,442 : INFO : < 200 OK [3346]
2017-12-31 21:35:39,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 102, '_0n0': 1015}
2017-12-31 21:35:39,450 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,456 : INFO : < 200 OK [3297]
2017-12-31 21:35:39,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 102, '_0n0': 1132}
2017-12-31 21:35:39,465 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,471 : INFO : < 200 OK [3291]
2017-12-31 21:35:39,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 117, '_0n0': 729}
2017-12-31 21:35:39,480 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,486 : INFO : < 200 OK [3302]
2017-12-31 21:35:39,491 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 103, '_0n0': 914}
2017-12-31 21:35:39,494 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,500 : INFO : < 200 OK [3326]
2017-12-31 21:35:39,505 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 103, '_0n0': 931}
2017-12-31 21:35:39,509 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,515 : INFO : < 200 OK [3328]
2017-12-31 21:35:39,520 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 103, '_0n0': 953}
2017-12-31 21:35:39,524 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,529 : INFO : < 200 OK [3328]
2017-12-31 21:35:39,534 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 103, '_0n0': 1096}
2017-12-31 21:35:39,538 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,544 : INFO : < 200 OK [3343]
2017-12-31 21:35:39,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 118, '_0n0': 1129}
2017-12-31 21:35:39,552 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,558 : INFO : < 200 OK [3297]
2017-12-31 21:35:39,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 118, '_0n0': 911}
2017-12-31 21:35:39,566 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,572 : INFO : < 200 OK [3281]
2017-12-31 21:35:39,577 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 104, '_0n0': 1066}
2017-12-31 21:35:39,581 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,586 : INFO : < 200 OK [3320]
2017-12-31 21:35:39,592 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 104, '_0n0': 903}
2017-12-31 21:35:39,596 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,602 : INFO : < 200 OK [3298]
2017-12-31 21:35:39,607 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 104, '_0n0': 918}
2017-12-31 21:35:39,610 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,616 : INFO : < 200 OK [3303]
2017-12-31 21:35:39,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 119, '_0n0': 792}
2017-12-31 21:35:39,625 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,631 : INFO : < 200 OK [3305]
2017-12-31 21:35:39,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 105, '_0n0': 1093}
2017-12-31 21:35:39,639 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,645 : INFO : < 200 OK [3286]
2017-12-31 21:35:39,650 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 105, '_0n0': 1115}
2017-12-31 21:35:39,654 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,660 : INFO : < 200 OK [3285]
2017-12-31 21:35:39,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 105, '_0n0': 951}
2017-12-31 21:35:39,668 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,674 : INFO : < 200 OK [3269]
2017-12-31 21:35:39,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 105, '_0n0': 781}
2017-12-31 21:35:39,683 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,690 : INFO : < 200 OK [3269]
2017-12-31 21:35:39,694 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 105, '_0n0': 1205}
2017-12-31 21:35:39,698 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,704 : INFO : < 200 OK [3287]
2017-12-31 21:35:39,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 120, '_0n0': 1199}
2017-12-31 21:35:39,712 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,718 : INFO : < 200 OK [3326]
2017-12-31 21:35:39,725 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 106, '_0n0': 1199}
2017-12-31 21:35:39,729 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,735 : INFO : < 200 OK [3325]
2017-12-31 21:35:39,740 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 121, '_0n0': 931}
2017-12-31 21:35:39,743 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,749 : INFO : < 200 OK [3303]
2017-12-31 21:35:39,754 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 121, '_0n0': 914}
2017-12-31 21:35:39,758 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,764 : INFO : < 200 OK [3301]

2017-12-31 21:35:39,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 121, '_0n0': 952}
2017-12-31 21:35:39,772 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,778 : INFO : < 200 OK [3303]
2017-12-31 21:35:39,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 107, '_0n0': 901}
2017-12-31 21:35:39,787 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,793 : INFO : < 200 OK [3268]
2017-12-31 21:35:39,798 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 122, '_0n0': 921}
2017-12-31 21:35:39,801 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,806 : INFO : < 200 OK [3296]
2017-12-31 21:35:39,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 108, '_0n0': 870}
2017-12-31 21:35:39,815 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,821 : INFO : < 200 OK [3301]
2017-12-31 21:35:39,825 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 108, '_0n0': 735}
2017-12-31 21:35:39,828 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,834 : INFO : < 200 OK [3301]
2017-12-31 21:35:39,839 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 108, '_0n0': 1204}
2017-12-31 21:35:39,843 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,849 : INFO : < 200 OK [3324]
2017-12-31 21:35:39,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 123, '_0n0': 1042}
2017-12-31 21:35:39,858 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,864 : INFO : < 200 OK [3287]
2017-12-31 21:35:39,869 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 109, '_0n0': 736}
2017-12-31 21:35:39,872 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,878 : INFO : < 200 OK [3276]
2017-12-31 21:35:39,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 109, '_0n0': 1035}
2017-12-31 21:35:39,887 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,892 : INFO : < 200 OK [3291]
2017-12-31 21:35:39,897 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 124, '_0n0': 1066}
2017-12-31 21:35:39,901 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,906 : INFO : < 200 OK [3306]
2017-12-31 21:35:39,912 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 110, '_0n0': 816}
2017-12-31 21:35:39,915 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,921 : INFO : < 200 OK [3272]
2017-12-31 21:35:39,926 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 110, '_0n0': 1151}
2017-12-31 21:35:39,930 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:39,935 : INFO : < 200 OK [3281]
2017-12-31 21:35:39,940 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 125, '_0n0': 952}
2017-12-31 21:35:39,944 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,950 : INFO : < 200 OK [3300]
2017-12-31 21:35:39,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 125, '_0n0': 931}
2017-12-31 21:35:39,959 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,964 : INFO : < 200 OK [3300]
2017-12-31 21:35:39,970 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 125, '_0n0': 914}
2017-12-31 21:35:39,974 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,979 : INFO : < 200 OK [3298]
2017-12-31 21:35:39,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 111, '_0n0': 949}
2017-12-31 21:35:39,988 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:39,993 : INFO : < 200 OK [3319]
2017-12-31 21:35:39,998 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 1128}
2017-12-31 21:35:40,002 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,007 : INFO : < 200 OK [3286]
2017-12-31 21:35:40,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 112, '_0n0': 931}
2017-12-31 21:35:40,016 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,021 : INFO : < 200 OK [3270]
2017-12-31 21:35:40,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 112, '_0n0': 914}
2017-12-31 21:35:40,030 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,035 : INFO : < 200 OK [3268]
2017-12-31 21:35:40,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 112, '_0n0': 952}
2017-12-31 21:35:40,044 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,049 : INFO : < 200 OK [3270]
2017-12-31 21:35:40,054 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 127, '_0n0': 949}
2017-12-31 21:35:40,058 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,063 : INFO : < 200 OK [3307]
2017-12-31 21:35:40,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 133, '_0n0': 863}
2017-12-31 21:35:40,071 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,077 : INFO : < 200 OK [3306]
2017-12-31 21:35:40,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 133, '_0n0': 1190}
2017-12-31 21:35:40,085 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,091 : INFO : < 200 OK [3322]
2017-12-31 21:35:40,096 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 128, '_0n0': 949}
2017-12-31 21:35:40,100 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,107 : INFO : < 200 OK [3318]

2017-12-31 21:35:40,114 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 134, '_0n0': 863}
2017-12-31 21:35:40,117 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,123 : INFO : < 200 OK [3323]
2017-12-31 21:35:40,128 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 134, '_0n0': 1190}
2017-12-31 21:35:40,132 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,138 : INFO : < 200 OK [3339]
2017-12-31 21:35:40,143 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 129, '_0n0': 921}
2017-12-31 21:35:40,147 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,153 : INFO : < 200 OK [3298]
2017-12-31 21:35:40,159 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 135, '_0n0': 1089}
2017-12-31 21:35:40,162 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,168 : INFO : < 200 OK [3326]
2017-12-31 21:35:40,173 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 135, '_0n0': 1062}
2017-12-31 21:35:40,177 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,183 : INFO : < 200 OK [3324]
2017-12-31 21:35:40,188 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 130, '_0n0': 863}
2017-12-31 21:35:40,192 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,197 : INFO : < 200 OK [3308]
2017-12-31 21:35:40,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 130, '_0n0': 1190}
2017-12-31 21:35:40,206 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,212 : INFO : < 200 OK [3324]
2017-12-31 21:35:40,217 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 136, '_0n0': 863}
2017-12-31 21:35:40,220 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,225 : INFO : < 200 OK [3328]
2017-12-31 21:35:40,230 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 136, '_0n0': 1190}
2017-12-31 21:35:40,234 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,248 : INFO : < 200 OK [3344]
2017-12-31 21:35:40,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 136, '_0n0': 801}
2017-12-31 21:35:40,257 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,263 : INFO : < 200 OK [3328]
2017-12-31 21:35:40,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 131, '_0n0': 863}
2017-12-31 21:35:40,271 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,277 : INFO : < 200 OK [3326]
2017-12-31 21:35:40,282 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 131, '_0n0': 1190}
2017-12-31 21:35:40,285 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,292 : INFO : < 200 OK [3342]
2017-12-31 21:35:40,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 137, '_0n0': 1111}
2017-12-31 21:35:40,302 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,308 : INFO : < 200 OK [3304]
2017-12-31 21:35:40,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 132, '_0n0': 1128}
2017-12-31 21:35:40,319 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,324 : INFO : < 200 OK [3287]
2017-12-31 21:35:40,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 138, '_0n0': 1066}
2017-12-31 21:35:40,334 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,340 : INFO : < 200 OK [3327]
2017-12-31 21:35:40,346 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 138, '_0n0': 903}
2017-12-31 21:35:40,349 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,355 : INFO : < 200 OK [3305]
2017-12-31 21:35:40,360 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 138, '_0n0': 863}
2017-12-31 21:35:40,364 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,369 : INFO : < 200 OK [3306]
2017-12-31 21:35:40,375 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 138, '_0n0': 849}
2017-12-31 21:35:40,378 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,384 : INFO : < 200 OK [3303]
2017-12-31 21:35:40,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 153, '_0n0': 914}
2017-12-31 21:35:40,393 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,399 : INFO : < 200 OK [3312]
2017-12-31 21:35:40,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 153, '_0n0': 931}
2017-12-31 21:35:40,407 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,413 : INFO : < 200 OK [3314]
2017-12-31 21:35:40,418 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 153, '_0n0': 952}
2017-12-31 21:35:40,421 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,426 : INFO : < 200 OK [3314]
2017-12-31 21:35:40,431 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 139, '_0n0': 1190}
2017-12-31 21:35:40,435 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,440 : INFO : < 200 OK [3329]
2017-12-31 21:35:40,445 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 139, '_0n0': 863}
2017-12-31 21:35:40,448 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,454 : INFO : < 200 OK [3313]
2017-12-31 21:35:40,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 154, '_0n0': 1167}
2017-12-31 21:35:40,462 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,468 : INFO : < 200 OK [3313]

2017-12-31 21:35:40,473 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 154, '_0n0': 744}
2017-12-31 21:35:40,476 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,482 : INFO : < 200 OK [3299]
2017-12-31 21:35:40,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 140, '_0n0': 1248}
2017-12-31 21:35:40,494 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,503 : INFO : < 200 OK [3341]
2017-12-31 21:35:40,508 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 155, '_0n0': 1079}
2017-12-31 21:35:40,512 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,518 : INFO : < 200 OK [3311]
2017-12-31 21:35:40,524 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 155, '_0n0': 1076}
2017-12-31 21:35:40,527 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,534 : INFO : < 200 OK [3313]
2017-12-31 21:35:40,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 155, '_0n0': 819}
2017-12-31 21:35:40,543 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,549 : INFO : < 200 OK [3298]
2017-12-31 21:35:40,553 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 141, '_0n0': 895}
2017-12-31 21:35:40,557 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,562 : INFO : < 200 OK [3302]
2017-12-31 21:35:40,567 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 156, '_0n0': 895}
2017-12-31 21:35:40,571 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,576 : INFO : < 200 OK [3331]
2017-12-31 21:35:40,581 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 142, '_0n0': 895}
2017-12-31 21:35:40,584 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,590 : INFO : < 200 OK [3317]
2017-12-31 21:35:40,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 157, '_0n0': 813}
2017-12-31 21:35:40,598 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,604 : INFO : < 200 OK [3275]
2017-12-31 21:35:40,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 143, '_0n0': 923}
2017-12-31 21:35:40,613 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,619 : INFO : < 200 OK [3335]
2017-12-31 21:35:40,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 158, '_0n0': 743}
2017-12-31 21:35:40,628 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,634 : INFO : < 200 OK [3323]
2017-12-31 21:35:40,642 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 144, '_0n0': 815}
2017-12-31 21:35:40,646 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,651 : INFO : < 200 OK [3284]
2017-12-31 21:35:40,657 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 159, '_0n0': 761}
2017-12-31 21:35:40,660 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,666 : INFO : < 200 OK [3292]
2017-12-31 21:35:40,671 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 145, '_0n0': 1139}
2017-12-31 21:35:40,675 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,680 : INFO : < 200 OK [3328]
2017-12-31 21:35:40,685 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 160, '_0n0': 743}
2017-12-31 21:35:40,688 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,694 : INFO : < 200 OK [3308]
2017-12-31 21:35:40,699 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 146, '_0n0': 779}
2017-12-31 21:35:40,702 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,708 : INFO : < 200 OK [3295]
2017-12-31 21:35:40,713 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 161, '_0n0': 1086}
2017-12-31 21:35:40,716 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,722 : INFO : < 200 OK [3319]
2017-12-31 21:35:40,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 147, '_0n0': 1122}
2017-12-31 21:35:40,731 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,737 : INFO : < 200 OK [3241]
2017-12-31 21:35:40,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 162, '_0n0': 1215}
2017-12-31 21:35:40,747 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,752 : INFO : < 200 OK [3336]
2017-12-31 21:35:40,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 148, '_0n0': 743}
2017-12-31 21:35:40,762 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,768 : INFO : < 200 OK [3304]
2017-12-31 21:35:40,773 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 163, '_0n0': 809}
2017-12-31 21:35:40,776 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,782 : INFO : < 200 OK [3280]
2017-12-31 21:35:40,788 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 149, '_0n0': 1140}
2017-12-31 21:35:40,792 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,798 : INFO : < 200 OK [3293]
2017-12-31 21:35:40,803 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 164, '_0n0': 787}
2017-12-31 21:35:40,806 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,812 : INFO : < 200 OK [3293]
2017-12-31 21:35:40,817 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 164, '_0n0': 1100}
2017-12-31 21:35:40,821 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,827 : INFO : < 200 OK [3304]

2017-12-31 21:35:40,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 164, '_0n0': 1120}
2017-12-31 21:35:40,835 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,841 : INFO : < 200 OK [3306]
2017-12-31 21:35:40,846 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 164, '_0n0': 944}
2017-12-31 21:35:40,849 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,855 : INFO : < 200 OK [3295]
2017-12-31 21:35:40,860 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 164, '_0n0': 961}
2017-12-31 21:35:40,863 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,869 : INFO : < 200 OK [3296]
2017-12-31 21:35:40,874 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 150, '_0n0': 1239}
2017-12-31 21:35:40,877 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,883 : INFO : < 200 OK [3279]
2017-12-31 21:35:40,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 165, '_0n0': 1145}
2017-12-31 21:35:40,891 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,896 : INFO : < 200 OK [3309]
2017-12-31 21:35:40,901 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 151, '_0n0': 753}
2017-12-31 21:35:40,904 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,910 : INFO : < 200 OK [3279]
2017-12-31 21:35:40,915 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 166, '_0n0': 797}
2017-12-31 21:35:40,919 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,924 : INFO : < 200 OK [3322]
2017-12-31 21:35:40,929 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 166, '_0n0': 942}
2017-12-31 21:35:40,932 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,938 : INFO : < 200 OK [3327]
2017-12-31 21:35:40,943 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 166, '_0n0': 947}
2017-12-31 21:35:40,946 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,952 : INFO : < 200 OK [3318]
2017-12-31 21:35:40,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 166, '_0n0': 973}
2017-12-31 21:35:40,961 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,966 : INFO : < 200 OK [3318]
2017-12-31 21:35:40,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 166, '_0n0': 1150}
2017-12-31 21:35:40,975 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:40,981 : INFO : < 200 OK [3342]
2017-12-31 21:35:40,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 166, '_0n0': 758}
2017-12-31 21:35:40,992 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:40,998 : INFO : < 200 OK [3320]
2017-12-31 21:35:41,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 166, '_0n0': 957}
2017-12-31 21:35:41,007 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,013 : INFO : < 200 OK [3328]
2017-12-31 21:35:41,018 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 152, '_0n0': 743}
2017-12-31 21:35:41,022 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,027 : INFO : < 200 OK [3313]
2017-12-31 21:35:41,032 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 167, '_0n0': 874}
2017-12-31 21:35:41,037 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,042 : INFO : < 200 OK [3295]
2017-12-31 21:35:41,047 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 173, '_0n0': 1198}
2017-12-31 21:35:41,051 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,056 : INFO : < 200 OK [3321]
2017-12-31 21:35:41,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 173, '_0n0': 1116}
2017-12-31 21:35:41,065 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,070 : INFO : < 200 OK [3317]
2017-12-31 21:35:41,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 168, '_0n0': 943}
2017-12-31 21:35:41,078 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,084 : INFO : < 200 OK [3306]
2017-12-31 21:35:41,089 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 174, '_0n0': 1246}
2017-12-31 21:35:41,092 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,101 : INFO : < 200 OK [3308]
2017-12-31 21:35:41,107 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 169, '_0n0': 753}
2017-12-31 21:35:41,110 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,116 : INFO : < 200 OK [3274]
2017-12-31 21:35:41,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 175, '_0n0': 1073}
2017-12-31 21:35:41,125 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,132 : INFO : < 200 OK [3309]
2017-12-31 21:35:41,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 170, '_0n0': 753}
2017-12-31 21:35:41,141 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,147 : INFO : < 200 OK [3275]
2017-12-31 21:35:41,152 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 176, '_0n0': 809}
2017-12-31 21:35:41,156 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,162 : INFO : < 200 OK [3258]
2017-12-31 21:35:41,166 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 171, '_0n0': 1140}
2017-12-31 21:35:41,170 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,192 : INFO : < 200 OK [3318]

2017-12-31 21:35:41,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 177, '_0n0': 753}
2017-12-31 21:35:41,201 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,207 : INFO : < 200 OK [3272]
2017-12-31 21:35:41,212 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 172, '_0n0': 1140}
2017-12-31 21:35:41,216 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,221 : INFO : < 200 OK [3333]
2017-12-31 21:35:41,226 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 172, '_0n0': 888}
2017-12-31 21:35:41,229 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,235 : INFO : < 200 OK [3321]
2017-12-31 21:35:41,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 178, '_0n0': 809}
2017-12-31 21:35:41,243 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,249 : INFO : < 200 OK [3299]
2017-12-31 21:35:41,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 193, '_0n0': 1196}
2017-12-31 21:35:41,259 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,265 : INFO : < 200 OK [3296]
2017-12-31 21:35:41,271 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 193, '_0n0': 1140}
2017-12-31 21:35:41,275 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,281 : INFO : < 200 OK [3294]
2017-12-31 21:35:41,286 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 179, '_0n0': 979}
2017-12-31 21:35:41,290 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,296 : INFO : < 200 OK [3266]
2017-12-31 21:35:41,301 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 194, '_0n0': 809}
2017-12-31 21:35:41,304 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,310 : INFO : < 200 OK [3254]
2017-12-31 21:35:41,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 180, '_0n0': 1198}
2017-12-31 21:35:41,321 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,327 : INFO : < 200 OK [3323]
2017-12-31 21:35:41,332 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 180, '_0n0': 1116}
2017-12-31 21:35:41,335 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,341 : INFO : < 200 OK [3319]
2017-12-31 21:35:41,346 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 195, '_0n0': 787}
2017-12-31 21:35:41,350 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,355 : INFO : < 200 OK [3263]
2017-12-31 21:35:41,360 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 195, '_0n0': 1100}
2017-12-31 21:35:41,364 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,370 : INFO : < 200 OK [3274]
2017-12-31 21:35:41,375 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 195, '_0n0': 1120}
2017-12-31 21:35:41,378 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,384 : INFO : < 200 OK [3276]
2017-12-31 21:35:41,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 195, '_0n0': 944}
2017-12-31 21:35:41,392 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,398 : INFO : < 200 OK [3265]
2017-12-31 21:35:41,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 195, '_0n0': 961}
2017-12-31 21:35:41,407 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,412 : INFO : < 200 OK [3266]
2017-12-31 21:35:41,418 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 181, '_0n0': 746}
2017-12-31 21:35:41,421 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,427 : INFO : < 200 OK [3301]
2017-12-31 21:35:41,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 196, '_0n0': 787}
2017-12-31 21:35:41,435 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,442 : INFO : < 200 OK [3261]
2017-12-31 21:35:41,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 196, '_0n0': 1100}
2017-12-31 21:35:41,450 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,456 : INFO : < 200 OK [3272]
2017-12-31 21:35:41,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 196, '_0n0': 1120}
2017-12-31 21:35:41,465 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,470 : INFO : < 200 OK [3274]
2017-12-31 21:35:41,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 196, '_0n0': 944}
2017-12-31 21:35:41,480 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,485 : INFO : < 200 OK [3263]
2017-12-31 21:35:41,490 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 196, '_0n0': 961}
2017-12-31 21:35:41,494 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,499 : INFO : < 200 OK [3264]
2017-12-31 21:35:41,504 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 182, '_0n0': 1140}
2017-12-31 21:35:41,507 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,512 : INFO : < 200 OK [3273]
2017-12-31 21:35:41,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 197, '_0n0': 753}
2017-12-31 21:35:41,520 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,526 : INFO : < 200 OK [3279]
2017-12-31 21:35:41,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 183, '_0n0': 809}
2017-12-31 21:35:41,535 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,541 : INFO : < 200 OK [3324]

2017-12-31 21:35:41,546 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 198, '_0n0': 1061}
2017-12-31 21:35:41,550 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,556 : INFO : < 200 OK [3307]
2017-12-31 21:35:41,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 184, '_0n0': 1246}
2017-12-31 21:35:41,567 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,573 : INFO : < 200 OK [3284]
2017-12-31 21:35:41,580 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 199, '_0n0': 753}
2017-12-31 21:35:41,584 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,590 : INFO : < 200 OK [3272]
2017-12-31 21:35:41,596 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 185, '_0n0': 1198}
2017-12-31 21:35:41,600 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,607 : INFO : < 200 OK [3317]
2017-12-31 21:35:41,612 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 185, '_0n0': 1116}
2017-12-31 21:35:41,616 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,622 : INFO : < 200 OK [3313]
2017-12-31 21:35:41,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 787}
2017-12-31 21:35:41,631 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,637 : INFO : < 200 OK [3265]
2017-12-31 21:35:41,643 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 1100}
2017-12-31 21:35:41,646 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,652 : INFO : < 200 OK [3276]
2017-12-31 21:35:41,658 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 1120}
2017-12-31 21:35:41,661 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,667 : INFO : < 200 OK [3278]
2017-12-31 21:35:41,672 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 944}
2017-12-31 21:35:41,676 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,681 : INFO : < 200 OK [3267]
2017-12-31 21:35:41,686 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 961}
2017-12-31 21:35:41,689 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,695 : INFO : < 200 OK [3268]
2017-12-31 21:35:41,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 186, '_0n0': 1145}
2017-12-31 21:35:41,704 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,712 : INFO : < 200 OK [3343]
2017-12-31 21:35:41,719 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 201, '_0n0': 1198}
2017-12-31 21:35:41,723 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,730 : INFO : < 200 OK [3334]
2017-12-31 21:35:41,735 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 201, '_0n0': 1116}
2017-12-31 21:35:41,739 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,745 : INFO : < 200 OK [3330]
2017-12-31 21:35:41,751 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 187, '_0n0': 1198}
2017-12-31 21:35:41,754 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,760 : INFO : < 200 OK [3307]
2017-12-31 21:35:41,765 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 187, '_0n0': 1116}
2017-12-31 21:35:41,768 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,774 : INFO : < 200 OK [3303]
2017-12-31 21:35:41,779 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 202, '_0n0': 1140}
2017-12-31 21:35:41,783 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,788 : INFO : < 200 OK [3276]
2017-12-31 21:35:41,793 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 188, '_0n0': 1158}
2017-12-31 21:35:41,796 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,802 : INFO : < 200 OK [3287]
2017-12-31 21:35:41,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 203, '_0n0': 960}
2017-12-31 21:35:41,810 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,815 : INFO : < 200 OK [3324]
2017-12-31 21:35:41,820 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 189, '_0n0': 1213}
2017-12-31 21:35:41,823 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,829 : INFO : < 200 OK [3346]
2017-12-31 21:35:41,835 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 204, '_0n0': 813}
2017-12-31 21:35:41,839 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,846 : INFO : < 200 OK [3260]
2017-12-31 21:35:41,852 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 190, '_0n0': 1213}
2017-12-31 21:35:41,856 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,862 : INFO : < 200 OK [3336]
2017-12-31 21:35:41,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 205, '_0n0': 1213}
2017-12-31 21:35:41,871 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,877 : INFO : < 200 OK [3339]
2017-12-31 21:35:41,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 191, '_0n0': 961}
2017-12-31 21:35:41,886 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,891 : INFO : < 200 OK [3260]
2017-12-31 21:35:41,897 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 191, '_0n0': 787}
2017-12-31 21:35:41,900 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,906 : INFO : < 200 OK [3257]

2017-12-31 21:35:41,912 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 191, '_0n0': 1100}
2017-12-31 21:35:41,915 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,920 : INFO : < 200 OK [3268]
2017-12-31 21:35:41,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 191, '_0n0': 1120}
2017-12-31 21:35:41,929 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,935 : INFO : < 200 OK [3270]
2017-12-31 21:35:41,940 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 191, '_0n0': 944}
2017-12-31 21:35:41,943 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:41,949 : INFO : < 200 OK [3259]
2017-12-31 21:35:41,954 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 206, '_0n0': 1140}
2017-12-31 21:35:41,957 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,963 : INFO : < 200 OK [3290]
2017-12-31 21:35:41,968 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 192, '_0n0': 1061}
2017-12-31 21:35:41,971 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,977 : INFO : < 200 OK [3307]
2017-12-31 21:35:41,982 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 192, '_0n0': 1158}
2017-12-31 21:35:41,986 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:41,992 : INFO : < 200 OK [3306]
2017-12-31 21:35:41,999 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 207, '_0n0': 1227}
2017-12-31 21:35:42,003 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,009 : INFO : < 200 OK [3287]
2017-12-31 21:35:42,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 207, '_0n0': 1080}
2017-12-31 21:35:42,018 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,024 : INFO : < 200 OK [3298]
2017-12-31 21:35:42,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 213, '_0n0': 845}
2017-12-31 21:35:42,032 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,038 : INFO : < 200 OK [3306]
2017-12-31 21:35:42,043 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 208, '_0n0': 1125}
2017-12-31 21:35:42,047 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,053 : INFO : < 200 OK [3356]
2017-12-31 21:35:42,058 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 214, '_0n0': 779}
2017-12-31 21:35:42,061 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,067 : INFO : < 200 OK [3274]
2017-12-31 21:35:42,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 1050}
2017-12-31 21:35:42,075 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,080 : INFO : < 200 OK [3265]
2017-12-31 21:35:42,084 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 808}
2017-12-31 21:35:42,087 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,093 : INFO : < 200 OK [3249]
2017-12-31 21:35:42,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 965}
2017-12-31 21:35:42,101 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,107 : INFO : < 200 OK [3260]
2017-12-31 21:35:42,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 1178}
2017-12-31 21:35:42,114 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,120 : INFO : < 200 OK [3263]
2017-12-31 21:35:42,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 1103}
2017-12-31 21:35:42,127 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,132 : INFO : < 200 OK [3268]
2017-12-31 21:35:42,136 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 930}
2017-12-31 21:35:42,139 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,145 : INFO : < 200 OK [3247]
2017-12-31 21:35:42,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 865}
2017-12-31 21:35:42,153 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,159 : INFO : < 200 OK [3259]
2017-12-31 21:35:42,164 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 823}
2017-12-31 21:35:42,168 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,173 : INFO : < 200 OK [3258]
2017-12-31 21:35:42,178 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 968}
2017-12-31 21:35:42,181 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,186 : INFO : < 200 OK [3255]
2017-12-31 21:35:42,191 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 800}
2017-12-31 21:35:42,194 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,199 : INFO : < 200 OK [3247]
2017-12-31 21:35:42,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 886}
2017-12-31 21:35:42,207 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,213 : INFO : < 200 OK [3254]
2017-12-31 21:35:42,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 962}
2017-12-31 21:35:42,221 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,227 : INFO : < 200 OK [3248]
2017-12-31 21:35:42,232 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 775}
2017-12-31 21:35:42,234 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,239 : INFO : < 200 OK [3257]

2017-12-31 21:35:42,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 916}
2017-12-31 21:35:42,248 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,257 : INFO : < 200 OK [3265]
2017-12-31 21:35:42,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 929}
2017-12-31 21:35:42,267 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,275 : INFO : < 200 OK [3252]
2017-12-31 21:35:42,280 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 215, '_0n0': 860}
2017-12-31 21:35:42,283 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,288 : INFO : < 200 OK [3278]
2017-12-31 21:35:42,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 210, '_0n0': 1227}
2017-12-31 21:35:42,298 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,304 : INFO : < 200 OK [3290]
2017-12-31 21:35:42,309 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 210, '_0n0': 1164}
2017-12-31 21:35:42,312 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,317 : INFO : < 200 OK [3289]
2017-12-31 21:35:42,322 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 210, '_0n0': 858}
2017-12-31 21:35:42,326 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,331 : INFO : < 200 OK [3277]
2017-12-31 21:35:42,337 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 216, '_0n0': 933}
2017-12-31 21:35:42,340 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,346 : INFO : < 200 OK [3273]
2017-12-31 21:35:42,352 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 216, '_0n0': 1041}
2017-12-31 21:35:42,355 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,361 : INFO : < 200 OK [3298]
2017-12-31 21:35:42,367 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 211, '_0n0': 1169}
2017-12-31 21:35:42,370 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,376 : INFO : < 200 OK [3333]
2017-12-31 21:35:42,381 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 211, '_0n0': 899}
2017-12-31 21:35:42,384 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,390 : INFO : < 200 OK [3316]
2017-12-31 21:35:42,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 217, '_0n0': 779}
2017-12-31 21:35:42,398 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,404 : INFO : < 200 OK [3264]
2017-12-31 21:35:42,409 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 212, '_0n0': 790}
2017-12-31 21:35:42,412 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,418 : INFO : < 200 OK [3284]
2017-12-31 21:35:42,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 212, '_0n0': 1033}
2017-12-31 21:35:42,426 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,431 : INFO : < 200 OK [3298]
2017-12-31 21:35:42,436 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 218, '_0n0': 1227}
2017-12-31 21:35:42,439 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,445 : INFO : < 200 OK [3324]
2017-12-31 21:35:42,449 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 218, '_0n0': 1164}
2017-12-31 21:35:42,452 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,457 : INFO : < 200 OK [3323]
2017-12-31 21:35:42,462 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 252, '_0n0': 774}
2017-12-31 21:35:42,466 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,472 : INFO : < 200 OK [3309]
2017-12-31 21:35:42,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 252, '_0n0': 1203}
2017-12-31 21:35:42,479 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,485 : INFO : < 200 OK [3323]
2017-12-31 21:35:42,489 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 252, '_0n0': 1149}
2017-12-31 21:35:42,492 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,497 : INFO : < 200 OK [3323]
2017-12-31 21:35:42,503 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 252, '_0n0': 1083}
2017-12-31 21:35:42,506 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,511 : INFO : < 200 OK [3325]
2017-12-31 21:35:42,516 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 252, '_0n0': 1055}
2017-12-31 21:35:42,519 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,524 : INFO : < 200 OK [3331]
2017-12-31 21:35:42,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 219, '_0n0': 976}
2017-12-31 21:35:42,532 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,538 : INFO : < 200 OK [3306]
2017-12-31 21:35:42,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 219, '_0n0': 772}
2017-12-31 21:35:42,546 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,551 : INFO : < 200 OK [3306]
2017-12-31 21:35:42,556 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 219, '_0n0': 838}
2017-12-31 21:35:42,559 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,565 : INFO : < 200 OK [3308]
2017-12-31 21:35:42,570 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 219, '_0n0': 969}
2017-12-31 21:35:42,573 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,578 : INFO : < 200 OK [3304]

2017-12-31 21:35:42,583 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 219, '_0n0': 835}
2017-12-31 21:35:42,586 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,592 : INFO : < 200 OK [3304]
2017-12-31 21:35:42,597 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 253, '_0n0': 890}
2017-12-31 21:35:42,601 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,607 : INFO : < 200 OK [3256]
2017-12-31 21:35:42,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 220, '_0n0': 860}
2017-12-31 21:35:42,614 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,620 : INFO : < 200 OK [3263]
2017-12-31 21:35:42,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 254, '_0n0': 821}
2017-12-31 21:35:42,627 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,632 : INFO : < 200 OK [3274]
2017-12-31 21:35:42,637 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 221, '_0n0': 746}
2017-12-31 21:35:42,640 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,645 : INFO : < 200 OK [3273]
2017-12-31 21:35:42,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 255, '_0n0': 933}
2017-12-31 21:35:42,653 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,658 : INFO : < 200 OK [3233]
2017-12-31 21:35:42,663 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 222, '_0n0': 860}
2017-12-31 21:35:42,667 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,672 : INFO : < 200 OK [3262]
2017-12-31 21:35:42,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 256, '_0n0': 1033}
2017-12-31 21:35:42,681 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,686 : INFO : < 200 OK [3312]
2017-12-31 21:35:42,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 256, '_0n0': 790}
2017-12-31 21:35:42,695 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,700 : INFO : < 200 OK [3298]
2017-12-31 21:35:42,705 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 223, '_0n0': 1091}
2017-12-31 21:35:42,709 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,714 : INFO : < 200 OK [3332]
2017-12-31 21:35:42,719 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 257, '_0n0': 1124}
2017-12-31 21:35:42,722 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,728 : INFO : < 200 OK [3333]
2017-12-31 21:35:42,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 243, '_0n0': 790}
2017-12-31 21:35:42,737 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,742 : INFO : < 200 OK [3287]
2017-12-31 21:35:42,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 243, '_0n0': 1033}
2017-12-31 21:35:42,753 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,759 : INFO : < 200 OK [3301]
2017-12-31 21:35:42,765 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 258, '_0n0': 910}
2017-12-31 21:35:42,768 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,774 : INFO : < 200 OK [3345]
2017-12-31 21:35:42,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 244, '_0n0': 1030}
2017-12-31 21:35:42,783 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,790 : INFO : < 200 OK [3327]
2017-12-31 21:35:42,795 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 244, '_0n0': 1142}
2017-12-31 21:35:42,798 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,804 : INFO : < 200 OK [3315]
2017-12-31 21:35:42,809 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 259, '_0n0': 1065}
2017-12-31 21:35:42,813 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,818 : INFO : < 200 OK [3327]
2017-12-31 21:35:42,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 245, '_0n0': 1065}
2017-12-31 21:35:42,827 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,833 : INFO : < 200 OK [3356]
2017-12-31 21:35:42,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 260, '_0n0': 779}
2017-12-31 21:35:42,841 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,847 : INFO : < 200 OK [3282]
2017-12-31 21:35:42,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 246, '_0n0': 860}
2017-12-31 21:35:42,858 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,863 : INFO : < 200 OK [3322]
2017-12-31 21:35:42,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 246, '_0n0': 1091}
2017-12-31 21:35:42,872 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,878 : INFO : < 200 OK [3339]
2017-12-31 21:35:42,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 246, '_0n0': 1124}
2017-12-31 21:35:42,886 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,892 : INFO : < 200 OK [3336]
2017-12-31 21:35:42,897 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 261, '_0n0': 1033}
2017-12-31 21:35:42,901 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,907 : INFO : < 200 OK [3321]
2017-12-31 21:35:42,912 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 261, '_0n0': 790}
2017-12-31 21:35:42,915 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,922 : INFO : < 200 OK [3307]

2017-12-31 21:35:42,927 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 247, '_0n0': 1126}
2017-12-31 21:35:42,931 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,936 : INFO : < 200 OK [3308]
2017-12-31 21:35:42,941 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 262, '_0n0': 804}
2017-12-31 21:35:42,944 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:42,951 : INFO : < 200 OK [3312]
2017-12-31 21:35:42,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 248, '_0n0': 1057}
2017-12-31 21:35:42,960 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,967 : INFO : < 200 OK [3299]
2017-12-31 21:35:42,973 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 248, '_0n0': 1045}
2017-12-31 21:35:42,977 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:42,983 : INFO : < 200 OK [3299]
2017-12-31 21:35:42,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 248, '_0n0': 1241}
2017-12-31 21:35:42,994 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,000 : INFO : < 200 OK [3292]
2017-12-31 21:35:43,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 263, '_0n0': 1170}
2017-12-31 21:35:43,009 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,015 : INFO : < 200 OK [3306]
2017-12-31 21:35:43,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 263, '_0n0': 846}
2017-12-31 21:35:43,025 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,031 : INFO : < 200 OK [3291]
2017-12-31 21:35:43,036 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 249, '_0n0': 1155}
2017-12-31 21:35:43,040 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,046 : INFO : < 200 OK [3268]
2017-12-31 21:35:43,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 264, '_0n0': 1019}
2017-12-31 21:35:43,055 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,062 : INFO : < 200 OK [3313]
2017-12-31 21:35:43,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 250, '_0n0': 1084}
2017-12-31 21:35:43,074 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,082 : INFO : < 200 OK [3314]
2017-12-31 21:35:43,087 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 265, '_0n0': 1016}
2017-12-31 21:35:43,092 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,098 : INFO : < 200 OK [3335]
2017-12-31 21:35:43,104 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 251, '_0n0': 1143}
2017-12-31 21:35:43,108 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,114 : INFO : < 200 OK [3316]
2017-12-31 21:35:43,119 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 251, '_0n0': 956}
2017-12-31 21:35:43,123 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,129 : INFO : < 200 OK [3305]
2017-12-31 21:35:43,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 266, '_0n0': 1189}
2017-12-31 21:35:43,139 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,146 : INFO : < 200 OK [3298]
2017-12-31 21:35:43,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 266, '_0n0': 831}
2017-12-31 21:35:43,154 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,160 : INFO : < 200 OK [3279]
2017-12-31 21:35:43,167 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 266, '_0n0': 875}
2017-12-31 21:35:43,171 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,177 : INFO : < 200 OK [3282]
2017-12-31 21:35:43,182 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 266, '_0n0': 927}
2017-12-31 21:35:43,186 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,192 : INFO : < 200 OK [3274]
2017-12-31 21:35:43,198 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 266, '_0n0': 1137}
2017-12-31 21:35:43,202 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,207 : INFO : < 200 OK [3291]
2017-12-31 21:35:43,212 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 266, '_0n0': 885}
2017-12-31 21:35:43,216 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,225 : INFO : < 200 OK [3278]
2017-12-31 21:35:43,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 266, '_0n0': 1021}
2017-12-31 21:35:43,237 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,245 : INFO : < 200 OK [3288]
2017-12-31 21:35:43,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 266, '_0n0': 1060}
2017-12-31 21:35:43,254 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,260 : INFO : < 200 OK [3296]
2017-12-31 21:35:43,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 266, '_0n0': 1232}
2017-12-31 21:35:43,269 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,276 : INFO : < 200 OK [3297]
2017-12-31 21:35:43,281 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 272, '_0n0': 1143}
2017-12-31 21:35:43,285 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,291 : INFO : < 200 OK [3319]
2017-12-31 21:35:43,297 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 272, '_0n0': 956}
2017-12-31 21:35:43,300 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,306 : INFO : < 200 OK [3308]

2017-12-31 21:35:43,311 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 267, '_0n0': 1233}
2017-12-31 21:35:43,315 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,321 : INFO : < 200 OK [3330]
2017-12-31 21:35:43,326 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 273, '_0n0': 932}
2017-12-31 21:35:43,329 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,335 : INFO : < 200 OK [3262]
2017-12-31 21:35:43,340 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 268, '_0n0': 862}
2017-12-31 21:35:43,344 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,350 : INFO : < 200 OK [3291]
2017-12-31 21:35:43,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 274, '_0n0': 757}
2017-12-31 21:35:43,360 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,366 : INFO : < 200 OK [3258]
2017-12-31 21:35:43,372 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 269, '_0n0': 1155}
2017-12-31 21:35:43,376 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,382 : INFO : < 200 OK [3290]
2017-12-31 21:35:43,388 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 275, '_0n0': 1180}
2017-12-31 21:35:43,393 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,399 : INFO : < 200 OK [3330]
2017-12-31 21:35:43,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 270, '_0n0': 1088}
2017-12-31 21:35:43,407 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,414 : INFO : < 200 OK [3335]
2017-12-31 21:35:43,421 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 276, '_0n0': 978}
2017-12-31 21:35:43,425 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,432 : INFO : < 200 OK [3280]
2017-12-31 21:35:43,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 271, '_0n0': 734}
2017-12-31 21:35:43,444 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,449 : INFO : < 200 OK [3314]
2017-12-31 21:35:43,455 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 277, '_0n0': 1057}
2017-12-31 21:35:43,460 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,466 : INFO : < 200 OK [3325]
2017-12-31 21:35:43,472 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 277, '_0n0': 1045}
2017-12-31 21:35:43,476 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,483 : INFO : < 200 OK [3325]
2017-12-31 21:35:43,490 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 277, '_0n0': 1241}
2017-12-31 21:35:43,494 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,500 : INFO : < 200 OK [3318]
2017-12-31 21:35:43,506 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 292, '_0n0': 749}
2017-12-31 21:35:43,510 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,516 : INFO : < 200 OK [3291]
2017-12-31 21:35:43,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 278, '_0n0': 793}
2017-12-31 21:35:43,526 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,532 : INFO : < 200 OK [3274]
2017-12-31 21:35:43,538 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 293, '_0n0': 978}
2017-12-31 21:35:43,543 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,549 : INFO : < 200 OK [3327]
2017-12-31 21:35:43,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 279, '_0n0': 879}
2017-12-31 21:35:43,560 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,566 : INFO : < 200 OK [3296]
2017-12-31 21:35:43,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 279, '_0n0': 1039}
2017-12-31 21:35:43,576 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,582 : INFO : < 200 OK [3304]
2017-12-31 21:35:43,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 294, '_0n0': 966}
2017-12-31 21:35:43,592 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,599 : INFO : < 200 OK [3269]
2017-12-31 21:35:43,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 280, '_0n0': 1082}
2017-12-31 21:35:43,609 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,616 : INFO : < 200 OK [3326]
2017-12-31 21:35:43,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 295, '_0n0': 757}
2017-12-31 21:35:43,625 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,631 : INFO : < 200 OK [3238]
2017-12-31 21:35:43,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 281, '_0n0': 830}
2017-12-31 21:35:43,639 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,648 : INFO : < 200 OK [3297]
2017-12-31 21:35:43,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 281, '_0n0': 805}
2017-12-31 21:35:43,658 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,664 : INFO : < 200 OK [3295]
2017-12-31 21:35:43,670 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 296, '_0n0': 757}
2017-12-31 21:35:43,674 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,681 : INFO : < 200 OK [3264]
2017-12-31 21:35:43,686 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 282, '_0n0': 786}
2017-12-31 21:35:43,689 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,695 : INFO : < 200 OK [3300]

2017-12-31 21:35:43,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 297, '_0n0': 1191}
2017-12-31 21:35:43,704 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,710 : INFO : < 200 OK [3339]
2017-12-31 21:35:43,716 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 297, '_0n0': 778}
2017-12-31 21:35:43,719 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,725 : INFO : < 200 OK [3321]
2017-12-31 21:35:43,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 283, '_0n0': 757}
2017-12-31 21:35:43,734 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,740 : INFO : < 200 OK [3260]
2017-12-31 21:35:43,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 298, '_0n0': 936}
2017-12-31 21:35:43,749 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,754 : INFO : < 200 OK [3287]
2017-12-31 21:35:43,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 284, '_0n0': 1182}
2017-12-31 21:35:43,763 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,768 : INFO : < 200 OK [3279]
2017-12-31 21:35:43,773 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 299, '_0n0': 978}
2017-12-31 21:35:43,777 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,782 : INFO : < 200 OK [3339]
2017-12-31 21:35:43,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 285, '_0n0': 814}
2017-12-31 21:35:43,790 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,796 : INFO : < 200 OK [3321]
2017-12-31 21:35:43,800 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 300, '_0n0': 757}
2017-12-31 21:35:43,804 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,809 : INFO : < 200 OK [3261]
2017-12-31 21:35:43,814 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 286, '_0n0': 857}
2017-12-31 21:35:43,817 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,823 : INFO : < 200 OK [3314]
2017-12-31 21:35:43,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 301, '_0n0': 901}
2017-12-31 21:35:43,832 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,837 : INFO : < 200 OK [3272]
2017-12-31 21:35:43,843 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 287, '_0n0': 778}
2017-12-31 21:35:43,847 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,853 : INFO : < 200 OK [3324]
2017-12-31 21:35:43,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 287, '_0n0': 1191}
2017-12-31 21:35:43,863 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,868 : INFO : < 200 OK [3342]
2017-12-31 21:35:43,874 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 302, '_0n0': 1247}
2017-12-31 21:35:43,878 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,883 : INFO : < 200 OK [3320]
2017-12-31 21:35:43,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 302, '_0n0': 1187}
2017-12-31 21:35:43,892 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,898 : INFO : < 200 OK [3312]
2017-12-31 21:35:43,903 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 302, '_0n0': 1068}
2017-12-31 21:35:43,907 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,912 : INFO : < 200 OK [3315]
2017-12-31 21:35:43,918 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 302, '_0n0': 1202}
2017-12-31 21:35:43,921 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,927 : INFO : < 200 OK [3313]
2017-12-31 21:35:43,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 288, '_0n0': 824}
2017-12-31 21:35:43,936 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,941 : INFO : < 200 OK [3289]
2017-12-31 21:35:43,946 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 303, '_0n0': 978}
2017-12-31 21:35:43,949 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,955 : INFO : < 200 OK [3280]
2017-12-31 21:35:43,960 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 289, '_0n0': 852}
2017-12-31 21:35:43,964 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,969 : INFO : < 200 OK [3314]
2017-12-31 21:35:43,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 304, '_0n0': 1229}
2017-12-31 21:35:43,978 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:43,983 : INFO : < 200 OK [3302]
2017-12-31 21:35:43,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 290, '_0n0': 855}
2017-12-31 21:35:43,991 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:43,997 : INFO : < 200 OK [3294]
2017-12-31 21:35:44,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 305, '_0n0': 879}
2017-12-31 21:35:44,005 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,012 : INFO : < 200 OK [3261]
2017-12-31 21:35:44,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 305, '_0n0': 1114}
2017-12-31 21:35:44,020 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,025 : INFO : < 200 OK [3271]
2017-12-31 21:35:44,032 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 291, '_0n0': 876}
2017-12-31 21:35:44,036 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,042 : INFO : < 200 OK [3270]

2017-12-31 21:35:44,047 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 306, '_0n0': 737}
2017-12-31 21:35:44,051 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,058 : INFO : < 200 OK [3300]
2017-12-31 21:35:44,063 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 306, '_0n0': 940}
2017-12-31 21:35:44,067 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,072 : INFO : < 200 OK [3295]
2017-12-31 21:35:44,078 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 312, '_0n0': 791}
2017-12-31 21:35:44,081 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,086 : INFO : < 200 OK [3323]
2017-12-31 21:35:44,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 312, '_0n0': 1152}
2017-12-31 21:35:44,095 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,101 : INFO : < 200 OK [3336]
2017-12-31 21:35:44,107 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 312, '_0n0': 856}
2017-12-31 21:35:44,110 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,116 : INFO : < 200 OK [3322]
2017-12-31 21:35:44,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 312, '_0n0': 869}
2017-12-31 21:35:44,125 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,130 : INFO : < 200 OK [3324]
2017-12-31 21:35:44,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 307, '_0n0': 747}
2017-12-31 21:35:44,139 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,144 : INFO : < 200 OK [3315]
2017-12-31 21:35:44,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 307, '_0n0': 1106}
2017-12-31 21:35:44,153 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,158 : INFO : < 200 OK [3318]
2017-12-31 21:35:44,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 313, '_0n0': 854}
2017-12-31 21:35:44,166 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,171 : INFO : < 200 OK [3326]
2017-12-31 21:35:44,176 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 308, '_0n0': 859}
2017-12-31 21:35:44,179 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,184 : INFO : < 200 OK [3301]
2017-12-31 21:35:44,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 314, '_0n0': 909}
2017-12-31 21:35:44,192 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,197 : INFO : < 200 OK [3285]
2017-12-31 21:35:44,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 314, '_0n0': 1032}
2017-12-31 21:35:44,205 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,211 : INFO : < 200 OK [3306]
2017-12-31 21:35:44,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 314, '_0n0': 920}
2017-12-31 21:35:44,219 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,224 : INFO : < 200 OK [3285]
2017-12-31 21:35:44,228 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 314, '_0n0': 841}
2017-12-31 21:35:44,232 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,236 : INFO : < 200 OK [3293]
2017-12-31 21:35:44,241 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 309, '_0n0': 854}
2017-12-31 21:35:44,244 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,249 : INFO : < 200 OK [3316]
2017-12-31 21:35:44,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 315, '_0n0': 876}
2017-12-31 21:35:44,256 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,261 : INFO : < 200 OK [3269]
2017-12-31 21:35:44,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 310, '_0n0': 854}
2017-12-31 21:35:44,268 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,274 : INFO : < 200 OK [3332]
2017-12-31 21:35:44,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 316, '_0n0': 876}
2017-12-31 21:35:44,283 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,289 : INFO : < 200 OK [3278]
2017-12-31 21:35:44,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 311, '_0n0': 1104}
2017-12-31 21:35:44,298 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,303 : INFO : < 200 OK [3315]
2017-12-31 21:35:44,309 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 317, '_0n0': 954}
2017-12-31 21:35:44,312 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,317 : INFO : < 200 OK [3309]
2017-12-31 21:35:44,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 332, '_0n0': 753}
2017-12-31 21:35:44,325 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,330 : INFO : < 200 OK [3284]
2017-12-31 21:35:44,334 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 318, '_0n0': 759}
2017-12-31 21:35:44,338 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,343 : INFO : < 200 OK [3308]
2017-12-31 21:35:44,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 318, '_0n0': 1116}
2017-12-31 21:35:44,350 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,356 : INFO : < 200 OK [3320]
2017-12-31 21:35:44,361 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 318, '_0n0': 1183}
2017-12-31 21:35:44,365 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,370 : INFO : < 200 OK [3318]

2017-12-31 21:35:44,375 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 333, '_0n0': 924}
2017-12-31 21:35:44,379 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,384 : INFO : < 200 OK [3269]
2017-12-31 21:35:44,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 319, '_0n0': 884}
2017-12-31 21:35:44,393 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,399 : INFO : < 200 OK [3270]
2017-12-31 21:35:44,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 334, '_0n0': 815}
2017-12-31 21:35:44,407 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,413 : INFO : < 200 OK [3316]
2017-12-31 21:35:44,417 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 320, '_0n0': 753}
2017-12-31 21:35:44,421 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,426 : INFO : < 200 OK [3298]
2017-12-31 21:35:44,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 335, '_0n0': 753}
2017-12-31 21:35:44,433 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,438 : INFO : < 200 OK [3290]
2017-12-31 21:35:44,444 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 321, '_0n0': 777}
2017-12-31 21:35:44,446 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,454 : INFO : < 200 OK [3282]
2017-12-31 21:35:44,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 321, '_0n0': 1059}
2017-12-31 21:35:44,462 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,468 : INFO : < 200 OK [3306]
2017-12-31 21:35:44,473 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 336, '_0n0': 854}
2017-12-31 21:35:44,476 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,481 : INFO : < 200 OK [3320]
2017-12-31 21:35:44,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 322, '_0n0': 1138}
2017-12-31 21:35:44,490 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,495 : INFO : < 200 OK [3328]
2017-12-31 21:35:44,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 337, '_0n0': 1218}
2017-12-31 21:35:44,503 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,508 : INFO : < 200 OK [3287]
2017-12-31 21:35:44,513 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 323, '_0n0': 876}
2017-12-31 21:35:44,517 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,522 : INFO : < 200 OK [3288]
2017-12-31 21:35:44,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 338, '_0n0': 859}
2017-12-31 21:35:44,530 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,535 : INFO : < 200 OK [3268]
2017-12-31 21:35:44,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 324, '_0n0': 759}
2017-12-31 21:35:44,543 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,552 : INFO : < 200 OK [3266]
2017-12-31 21:35:44,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 324, '_0n0': 1183}
2017-12-31 21:35:44,560 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,565 : INFO : < 200 OK [3276]
2017-12-31 21:35:44,570 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 324, '_0n0': 1116}
2017-12-31 21:35:44,574 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,580 : INFO : < 200 OK [3278]
2017-12-31 21:35:44,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 324, '_0n0': 1131}
2017-12-31 21:35:44,588 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,593 : INFO : < 200 OK [3278]
2017-12-31 21:35:44,598 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 339, '_0n0': 859}
2017-12-31 21:35:44,601 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,607 : INFO : < 200 OK [3301]
2017-12-31 21:35:44,612 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 325, '_0n0': 841}
2017-12-31 21:35:44,615 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,620 : INFO : < 200 OK [3317]
2017-12-31 21:35:44,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 325, '_0n0': 920}
2017-12-31 21:35:44,627 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,632 : INFO : < 200 OK [3309]
2017-12-31 21:35:44,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 325, '_0n0': 840}
2017-12-31 21:35:44,639 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,644 : INFO : < 200 OK [3313]
2017-12-31 21:35:44,648 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 340, '_0n0': 854}
2017-12-31 21:35:44,651 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,657 : INFO : < 200 OK [3330]
2017-12-31 21:35:44,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 326, '_0n0': 811}
2017-12-31 21:35:44,664 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,670 : INFO : < 200 OK [3299]
2017-12-31 21:35:44,674 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 341, '_0n0': 759}
2017-12-31 21:35:44,677 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,683 : INFO : < 200 OK [3300]
2017-12-31 21:35:44,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 327, '_0n0': 841}
2017-12-31 21:35:44,691 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,697 : INFO : < 200 OK [3344]

2017-12-31 21:35:44,703 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 342, '_0n0': 954}
2017-12-31 21:35:44,707 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,713 : INFO : < 200 OK [3309]
2017-12-31 21:35:44,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 328, '_0n0': 841}
2017-12-31 21:35:44,722 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,729 : INFO : < 200 OK [3285]
2017-12-31 21:35:44,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 328, '_0n0': 920}
2017-12-31 21:35:44,737 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,742 : INFO : < 200 OK [3277]
2017-12-31 21:35:44,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 328, '_0n0': 840}
2017-12-31 21:35:44,750 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,756 : INFO : < 200 OK [3281]
2017-12-31 21:35:44,761 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 343, '_0n0': 864}
2017-12-31 21:35:44,764 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,770 : INFO : < 200 OK [3296]
2017-12-31 21:35:44,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 329, '_0n0': 759}
2017-12-31 21:35:44,777 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,782 : INFO : < 200 OK [3284]
2017-12-31 21:35:44,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 344, '_0n0': 759}
2017-12-31 21:35:44,791 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,796 : INFO : < 200 OK [3285]
2017-12-31 21:35:44,800 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 344, '_0n0': 1131}
2017-12-31 21:35:44,803 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,809 : INFO : < 200 OK [3297]
2017-12-31 21:35:44,814 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 330, '_0n0': 1218}
2017-12-31 21:35:44,817 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,822 : INFO : < 200 OK [3280]
2017-12-31 21:35:44,827 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 345, '_0n0': 924}
2017-12-31 21:35:44,830 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,836 : INFO : < 200 OK [3279]
2017-12-31 21:35:44,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 331, '_0n0': 788}
2017-12-31 21:35:44,846 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,852 : INFO : < 200 OK [3281]
2017-12-31 21:35:44,860 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 331, '_0n0': 928}
2017-12-31 21:35:44,863 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,868 : INFO : < 200 OK [3279]
2017-12-31 21:35:44,873 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 346, '_0n0': 1192}
2017-12-31 21:35:44,877 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,882 : INFO : < 200 OK [3303]
2017-12-31 21:35:44,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 352, '_0n0': 895}
2017-12-31 21:35:44,890 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,896 : INFO : < 200 OK [3324]
2017-12-31 21:35:44,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 347, '_0n0': 1218}
2017-12-31 21:35:44,904 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,910 : INFO : < 200 OK [3288]
2017-12-31 21:35:44,915 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 353, '_0n0': 788}
2017-12-31 21:35:44,918 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,924 : INFO : < 200 OK [3283]
2017-12-31 21:35:44,929 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 353, '_0n0': 928}
2017-12-31 21:35:44,932 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,937 : INFO : < 200 OK [3281]
2017-12-31 21:35:44,942 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 348, '_0n0': 894}
2017-12-31 21:35:44,946 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,951 : INFO : < 200 OK [3296]
2017-12-31 21:35:44,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 348, '_0n0': 1020}
2017-12-31 21:35:44,958 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:44,963 : INFO : < 200 OK [3300]
2017-12-31 21:35:44,968 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 348, '_0n0': 950}
2017-12-31 21:35:44,971 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,976 : INFO : < 200 OK [3288]
2017-12-31 21:35:44,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 354, '_0n0': 880}
2017-12-31 21:35:44,984 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:44,989 : INFO : < 200 OK [3285]
2017-12-31 21:35:44,993 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 349, '_0n0': 1240}
2017-12-31 21:35:44,996 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,001 : INFO : < 200 OK [3331]
2017-12-31 21:35:45,006 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 355, '_0n0': 841}
2017-12-31 21:35:45,009 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,015 : INFO : < 200 OK [3293]
2017-12-31 21:35:45,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 355, '_0n0': 920}
2017-12-31 21:35:45,025 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,031 : INFO : < 200 OK [3285]

2017-12-31 21:35:45,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 355, '_0n0': 840}
2017-12-31 21:35:45,043 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,049 : INFO : < 200 OK [3289]
2017-12-31 21:35:45,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 350, '_0n0': 1172}
2017-12-31 21:35:45,059 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,064 : INFO : < 200 OK [3292]
2017-12-31 21:35:45,069 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 356, '_0n0': 788}
2017-12-31 21:35:45,072 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,078 : INFO : < 200 OK [3269]
2017-12-31 21:35:45,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 356, '_0n0': 928}
2017-12-31 21:35:45,085 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,091 : INFO : < 200 OK [3267]
2017-12-31 21:35:45,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 351, '_0n0': 876}
2017-12-31 21:35:45,097 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,102 : INFO : < 200 OK [3282]
2017-12-31 21:35:45,107 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 357, '_0n0': 759}
2017-12-31 21:35:45,110 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,115 : INFO : < 200 OK [3296]
2017-12-31 21:35:45,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 357, '_0n0': 1098}
2017-12-31 21:35:45,124 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,129 : INFO : < 200 OK [3311]
2017-12-31 21:35:45,133 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 372, '_0n0': 1218}
2017-12-31 21:35:45,136 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,142 : INFO : < 200 OK [3276]
2017-12-31 21:35:45,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 358, '_0n0': 1024}
2017-12-31 21:35:45,151 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,159 : INFO : < 200 OK [3324]
2017-12-31 21:35:45,164 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 358, '_0n0': 1113}
2017-12-31 21:35:45,167 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,172 : INFO : < 200 OK [3327]
2017-12-31 21:35:45,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 358, '_0n0': 1101}
2017-12-31 21:35:45,182 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,188 : INFO : < 200 OK [3325]
2017-12-31 21:35:45,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 373, '_0n0': 829}
2017-12-31 21:35:45,196 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,201 : INFO : < 200 OK [3290]
2017-12-31 21:35:45,207 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 373, '_0n0': 1132}
2017-12-31 21:35:45,211 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,217 : INFO : < 200 OK [3301]
2017-12-31 21:35:45,222 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 373, '_0n0': 978}
2017-12-31 21:35:45,226 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,231 : INFO : < 200 OK [3288]
2017-12-31 21:35:45,236 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 359, '_0n0': 971}
2017-12-31 21:35:45,240 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,245 : INFO : < 200 OK [3313]
2017-12-31 21:35:45,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 374, '_0n0': 1132}
2017-12-31 21:35:45,254 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,259 : INFO : < 200 OK [3280]
2017-12-31 21:35:45,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 374, '_0n0': 829}
2017-12-31 21:35:45,267 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,272 : INFO : < 200 OK [3269]
2017-12-31 21:35:45,277 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 374, '_0n0': 978}
2017-12-31 21:35:45,281 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,286 : INFO : < 200 OK [3267]
2017-12-31 21:35:45,291 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 360, '_0n0': 1017}
2017-12-31 21:35:45,294 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,299 : INFO : < 200 OK [3303]
2017-12-31 21:35:45,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 360, '_0n0': 935}
2017-12-31 21:35:45,306 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,311 : INFO : < 200 OK [3285]
2017-12-31 21:35:45,317 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 375, '_0n0': 829}
2017-12-31 21:35:45,320 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,325 : INFO : < 200 OK [3269]
2017-12-31 21:35:45,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 375, '_0n0': 1132}
2017-12-31 21:35:45,333 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,338 : INFO : < 200 OK [3280]
2017-12-31 21:35:45,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 375, '_0n0': 978}
2017-12-31 21:35:45,346 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,351 : INFO : < 200 OK [3267]
2017-12-31 21:35:45,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 361, '_0n0': 978}
2017-12-31 21:35:45,360 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,366 : INFO : < 200 OK [3259]

2017-12-31 21:35:45,372 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 361, '_0n0': 829}
2017-12-31 21:35:45,376 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,382 : INFO : < 200 OK [3261]
2017-12-31 21:35:45,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 361, '_0n0': 1132}
2017-12-31 21:35:45,390 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,397 : INFO : < 200 OK [3272]
2017-12-31 21:35:45,402 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 376, '_0n0': 978}
2017-12-31 21:35:45,405 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,410 : INFO : < 200 OK [3263]
2017-12-31 21:35:45,414 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 376, '_0n0': 829}
2017-12-31 21:35:45,418 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,424 : INFO : < 200 OK [3265]
2017-12-31 21:35:45,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 376, '_0n0': 1132}
2017-12-31 21:35:45,433 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,438 : INFO : < 200 OK [3276]
2017-12-31 21:35:45,442 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 362, '_0n0': 1166}
2017-12-31 21:35:45,445 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,450 : INFO : < 200 OK [3278]
2017-12-31 21:35:45,454 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 362, '_0n0': 1067}
2017-12-31 21:35:45,457 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,463 : INFO : < 200 OK [3284]
2017-12-31 21:35:45,468 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 377, '_0n0': 971}
2017-12-31 21:35:45,471 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,476 : INFO : < 200 OK [3299]
2017-12-31 21:35:45,481 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 363, '_0n0': 867}
2017-12-31 21:35:45,484 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,490 : INFO : < 200 OK [3256]
2017-12-31 21:35:45,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 378, '_0n0': 971}
2017-12-31 21:35:45,500 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,505 : INFO : < 200 OK [3300]
2017-12-31 21:35:45,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 378, '_0n0': 1220}
2017-12-31 21:35:45,515 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,521 : INFO : < 200 OK [3304]
2017-12-31 21:35:45,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 378, '_0n0': 1081}
2017-12-31 21:35:45,530 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,536 : INFO : < 200 OK [3306]
2017-12-31 21:35:45,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 378, '_0n0': 803}
2017-12-31 21:35:45,545 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,550 : INFO : < 200 OK [3293]
2017-12-31 21:35:45,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 364, '_0n0': 971}
2017-12-31 21:35:45,559 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,564 : INFO : < 200 OK [3308]
2017-12-31 21:35:45,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 379, '_0n0': 829}
2017-12-31 21:35:45,573 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,579 : INFO : < 200 OK [3265]
2017-12-31 21:35:45,584 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 379, '_0n0': 1132}
2017-12-31 21:35:45,587 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,593 : INFO : < 200 OK [3276]
2017-12-31 21:35:45,597 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 379, '_0n0': 978}
2017-12-31 21:35:45,600 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,605 : INFO : < 200 OK [3263]
2017-12-31 21:35:45,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 365, '_0n0': 970}
2017-12-31 21:35:45,614 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,619 : INFO : < 200 OK [3309]
2017-12-31 21:35:45,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 380, '_0n0': 830}
2017-12-31 21:35:45,627 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,632 : INFO : < 200 OK [3294]
2017-12-31 21:35:45,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 366, '_0n0': 978}
2017-12-31 21:35:45,639 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,644 : INFO : < 200 OK [3266]
2017-12-31 21:35:45,648 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 366, '_0n0': 1132}
2017-12-31 21:35:45,652 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,657 : INFO : < 200 OK [3279]
2017-12-31 21:35:45,663 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 366, '_0n0': 829}
2017-12-31 21:35:45,667 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,674 : INFO : < 200 OK [3268]
2017-12-31 21:35:45,679 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 381, '_0n0': 827}
2017-12-31 21:35:45,682 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,688 : INFO : < 200 OK [3330]
2017-12-31 21:35:45,695 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 367, '_0n0': 941}
2017-12-31 21:35:45,698 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,704 : INFO : < 200 OK [3310]

2017-12-31 21:35:45,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 382, '_0n0': 807}
2017-12-31 21:35:45,713 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,718 : INFO : < 200 OK [3357]
2017-12-31 21:35:45,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 368, '_0n0': 915}
2017-12-31 21:35:45,727 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,732 : INFO : < 200 OK [3271]
2017-12-31 21:35:45,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 368, '_0n0': 935}
2017-12-31 21:35:45,739 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,744 : INFO : < 200 OK [3262]
2017-12-31 21:35:45,748 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 383, '_0n0': 827}
2017-12-31 21:35:45,751 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,756 : INFO : < 200 OK [3309]
2017-12-31 21:35:45,762 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 369, '_0n0': 742}
2017-12-31 21:35:45,765 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,770 : INFO : < 200 OK [3300]
2017-12-31 21:35:45,775 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 384, '_0n0': 1224}
2017-12-31 21:35:45,778 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,782 : INFO : < 200 OK [3280]
2017-12-31 21:35:45,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 384, '_0n0': 1092}
2017-12-31 21:35:45,790 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,796 : INFO : < 200 OK [3284]
2017-12-31 21:35:45,801 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 370, '_0n0': 1132}
2017-12-31 21:35:45,805 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,813 : INFO : < 200 OK [3290]
2017-12-31 21:35:45,819 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 385, '_0n0': 872}
2017-12-31 21:35:45,823 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,830 : INFO : < 200 OK [3284]
2017-12-31 21:35:45,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 371, '_0n0': 1209}
2017-12-31 21:35:45,837 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,844 : INFO : < 200 OK [3277]
2017-12-31 21:35:45,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 386, '_0n0': 820}
2017-12-31 21:35:45,852 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,857 : INFO : < 200 OK [3335]
2017-12-31 21:35:45,862 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 392, '_0n0': 1168}
2017-12-31 21:35:45,865 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,871 : INFO : < 200 OK [3351]
2017-12-31 21:35:45,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 392, '_0n0': 897}
2017-12-31 21:35:45,879 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,885 : INFO : < 200 OK [3331]
2017-12-31 21:35:45,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 387, '_0n0': 803}
2017-12-31 21:35:45,893 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,898 : INFO : < 200 OK [3267]
2017-12-31 21:35:45,903 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 387, '_0n0': 1081}
2017-12-31 21:35:45,906 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,912 : INFO : < 200 OK [3280]
2017-12-31 21:35:45,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 387, '_0n0': 1220}
2017-12-31 21:35:45,919 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,924 : INFO : < 200 OK [3278]
2017-12-31 21:35:45,928 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 387, '_0n0': 971}
2017-12-31 21:35:45,932 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:45,937 : INFO : < 200 OK [3274]
2017-12-31 21:35:45,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 393, '_0n0': 1206}
2017-12-31 21:35:45,949 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,955 : INFO : < 200 OK [3266]
2017-12-31 21:35:45,962 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 388, '_0n0': 1206}
2017-12-31 21:35:45,965 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,971 : INFO : < 200 OK [3316]
2017-12-31 21:35:45,976 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 388, '_0n0': 1063}
2017-12-31 21:35:45,979 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,985 : INFO : < 200 OK [3350]
2017-12-31 21:35:45,989 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 388, '_0n0': 1193}
2017-12-31 21:35:45,993 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:45,998 : INFO : < 200 OK [3350]
2017-12-31 21:35:46,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 394, '_0n0': 1109}
2017-12-31 21:35:46,006 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,012 : INFO : < 200 OK [3292]
2017-12-31 21:35:46,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 389, '_0n0': 1160}
2017-12-31 21:35:46,021 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,027 : INFO : < 200 OK [3313]
2017-12-31 21:35:46,032 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 389, '_0n0': 1205}
2017-12-31 21:35:46,035 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,040 : INFO : < 200 OK [3314]

2017-12-31 21:35:46,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 389, '_0n0': 911}
2017-12-31 21:35:46,048 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,053 : INFO : < 200 OK [3299]
2017-12-31 21:35:46,057 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 389, '_0n0': 1230}
2017-12-31 21:35:46,059 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,065 : INFO : < 200 OK [3318]
2017-12-31 21:35:46,070 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 389, '_0n0': 741}
2017-12-31 21:35:46,073 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,078 : INFO : < 200 OK [3297]
2017-12-31 21:35:46,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 395, '_0n0': 1067}
2017-12-31 21:35:46,085 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,091 : INFO : < 200 OK [3307]
2017-12-31 21:35:46,096 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 395, '_0n0': 1166}
2017-12-31 21:35:46,100 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,106 : INFO : < 200 OK [3301]
2017-12-31 21:35:46,112 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 390, '_0n0': 1195}
2017-12-31 21:35:46,117 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,123 : INFO : < 200 OK [3346]
2017-12-31 21:35:46,129 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 390, '_0n0': 1179}
2017-12-31 21:35:46,132 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,138 : INFO : < 200 OK [3349]
2017-12-31 21:35:46,143 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 390, '_0n0': 892}
2017-12-31 21:35:46,147 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,152 : INFO : < 200 OK [3333]
2017-12-31 21:35:46,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 390, '_0n0': 728}
2017-12-31 21:35:46,160 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,165 : INFO : < 200 OK [3332]
2017-12-31 21:35:46,170 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 390, '_0n0': 1072}
2017-12-31 21:35:46,174 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,179 : INFO : < 200 OK [3350]
2017-12-31 21:35:46,184 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 396, '_0n0': 785}
2017-12-31 21:35:46,187 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,192 : INFO : < 200 OK [3310]
2017-12-31 21:35:46,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 396, '_0n0': 817}
2017-12-31 21:35:46,201 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,207 : INFO : < 200 OK [3309]
2017-12-31 21:35:46,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 391, '_0n0': 1132}
2017-12-31 21:35:46,216 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,223 : INFO : < 200 OK [3281]
2017-12-31 21:35:46,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 391, '_0n0': 829}
2017-12-31 21:35:46,232 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,238 : INFO : < 200 OK [3270]
2017-12-31 21:35:46,243 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 391, '_0n0': 978}
2017-12-31 21:35:46,247 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,253 : INFO : < 200 OK [3268]
2017-12-31 21:35:46,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 397, '_0n0': 799}
2017-12-31 21:35:46,261 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,267 : INFO : < 200 OK [3297]
2017-12-31 21:35:46,271 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 397, '_0n0': 843}
2017-12-31 21:35:46,275 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,280 : INFO : < 200 OK [3298]
2017-12-31 21:35:46,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 412, '_0n0': 1067}
2017-12-31 21:35:46,288 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,294 : INFO : < 200 OK [3288]
2017-12-31 21:35:46,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 412, '_0n0': 1166}
2017-12-31 21:35:46,301 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,306 : INFO : < 200 OK [3282]
2017-12-31 21:35:46,311 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 398, '_0n0': 1110}
2017-12-31 21:35:46,314 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,319 : INFO : < 200 OK [3298]
2017-12-31 21:35:46,324 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 398, '_0n0': 1132}
2017-12-31 21:35:46,328 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,333 : INFO : < 200 OK [3302]
2017-12-31 21:35:46,338 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 398, '_0n0': 978}
2017-12-31 21:35:46,341 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,347 : INFO : < 200 OK [3289]
2017-12-31 21:35:46,352 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 398, '_0n0': 829}
2017-12-31 21:35:46,356 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,363 : INFO : < 200 OK [3291]
2017-12-31 21:35:46,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 413, '_0n0': 1077}
2017-12-31 21:35:46,373 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,381 : INFO : < 200 OK [3332]

2017-12-31 21:35:46,386 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 413, '_0n0': 1094}
2017-12-31 21:35:46,389 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,396 : INFO : < 200 OK [3344]
2017-12-31 21:35:46,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 399, '_0n0': 746}
2017-12-31 21:35:46,405 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,411 : INFO : < 200 OK [3296]
2017-12-31 21:35:46,417 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 414, '_0n0': 1166}
2017-12-31 21:35:46,421 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,427 : INFO : < 200 OK [3290]
2017-12-31 21:35:46,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 414, '_0n0': 1067}
2017-12-31 21:35:46,435 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,440 : INFO : < 200 OK [3296]
2017-12-31 21:35:46,444 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 400, '_0n0': 895}
2017-12-31 21:35:46,448 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,453 : INFO : < 200 OK [3344]
2017-12-31 21:35:46,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 415, '_0n0': 1161}
2017-12-31 21:35:46,462 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,467 : INFO : < 200 OK [3281]
2017-12-31 21:35:46,471 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 415, '_0n0': 748}
2017-12-31 21:35:46,475 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,480 : INFO : < 200 OK [3270]
2017-12-31 21:35:46,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 401, '_0n0': 727}
2017-12-31 21:35:46,488 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,493 : INFO : < 200 OK [3266]
2017-12-31 21:35:46,498 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 416, '_0n0': 895}
2017-12-31 21:35:46,501 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,507 : INFO : < 200 OK [3348]
2017-12-31 21:35:46,513 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 402, '_0n0': 961}
2017-12-31 21:35:46,517 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,525 : INFO : < 200 OK [3347]
2017-12-31 21:35:46,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 402, '_0n0': 1037}
2017-12-31 21:35:46,535 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,541 : INFO : < 200 OK [3365]
2017-12-31 21:35:46,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 417, '_0n0': 727}
2017-12-31 21:35:46,550 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,557 : INFO : < 200 OK [3274]
2017-12-31 21:35:46,562 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 403, '_0n0': 895}
2017-12-31 21:35:46,566 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,571 : INFO : < 200 OK [3353]
2017-12-31 21:35:46,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 418, '_0n0': 1210}
2017-12-31 21:35:46,580 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,586 : INFO : < 200 OK [3338]
2017-12-31 21:35:46,592 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 418, '_0n0': 1245}
2017-12-31 21:35:46,595 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,601 : INFO : < 200 OK [3334]
2017-12-31 21:35:46,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 418, '_0n0': 1207}
2017-12-31 21:35:46,609 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,615 : INFO : < 200 OK [3329]
2017-12-31 21:35:46,619 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 418, '_0n0': 1219}
2017-12-31 21:35:46,623 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,629 : INFO : < 200 OK [3332]
2017-12-31 21:35:46,634 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 418, '_0n0': 1225}
2017-12-31 21:35:46,637 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,643 : INFO : < 200 OK [3331]
2017-12-31 21:35:46,647 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 418, '_0n0': 1085}
2017-12-31 21:35:46,651 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,656 : INFO : < 200 OK [3331]
2017-12-31 21:35:46,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 404, '_0n0': 853}
2017-12-31 21:35:46,664 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,670 : INFO : < 200 OK [3297]
2017-12-31 21:35:46,676 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 419, '_0n0': 1224}
2017-12-31 21:35:46,680 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,686 : INFO : < 200 OK [3283]
2017-12-31 21:35:46,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 419, '_0n0': 1092}
2017-12-31 21:35:46,697 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,703 : INFO : < 200 OK [3287]
2017-12-31 21:35:46,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 405, '_0n0': 1037}
2017-12-31 21:35:46,712 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,718 : INFO : < 200 OK [3304]
2017-12-31 21:35:46,724 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 405, '_0n0': 961}
2017-12-31 21:35:46,728 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,734 : INFO : < 200 OK [3286]

2017-12-31 21:35:46,740 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 420, '_0n0': 861}
2017-12-31 21:35:46,744 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,750 : INFO : < 200 OK [3296]
2017-12-31 21:35:46,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 406, '_0n0': 961}
2017-12-31 21:35:46,760 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,766 : INFO : < 200 OK [3282]
2017-12-31 21:35:46,770 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 406, '_0n0': 1037}
2017-12-31 21:35:46,773 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,779 : INFO : < 200 OK [3300]
2017-12-31 21:35:46,783 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 421, '_0n0': 1037}
2017-12-31 21:35:46,786 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,792 : INFO : < 200 OK [3304]
2017-12-31 21:35:46,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 421, '_0n0': 961}
2017-12-31 21:35:46,799 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,804 : INFO : < 200 OK [3286]
2017-12-31 21:35:46,810 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 407, '_0n0': 1132}
2017-12-31 21:35:46,813 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,818 : INFO : < 200 OK [3276]
2017-12-31 21:35:46,822 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 407, '_0n0': 829}
2017-12-31 21:35:46,826 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,831 : INFO : < 200 OK [3265]
2017-12-31 21:35:46,836 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 407, '_0n0': 978}
2017-12-31 21:35:46,840 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,848 : INFO : < 200 OK [3263]
2017-12-31 21:35:46,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 422, '_0n0': 836}
2017-12-31 21:35:46,858 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,865 : INFO : < 200 OK [3285]
2017-12-31 21:35:46,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 408, '_0n0': 861}
2017-12-31 21:35:46,873 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,880 : INFO : < 200 OK [3304]
2017-12-31 21:35:46,886 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 423, '_0n0': 836}
2017-12-31 21:35:46,889 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,896 : INFO : < 200 OK [3303]
2017-12-31 21:35:46,901 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 409, '_0n0': 861}
2017-12-31 21:35:46,904 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,911 : INFO : < 200 OK [3292]
2017-12-31 21:35:46,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 424, '_0n0': 861}
2017-12-31 21:35:46,919 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,925 : INFO : < 200 OK [3296]
2017-12-31 21:35:46,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 410, '_0n0': 794}
2017-12-31 21:35:46,934 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,939 : INFO : < 200 OK [3299]
2017-12-31 21:35:46,944 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 425, '_0n0': 812}
2017-12-31 21:35:46,947 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,952 : INFO : < 200 OK [3292]
2017-12-31 21:35:46,956 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 411, '_0n0': 1044}
2017-12-31 21:35:46,960 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:46,965 : INFO : < 200 OK [3320]
2017-12-31 21:35:46,970 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 426, '_0n0': 882}
2017-12-31 21:35:46,974 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:46,980 : INFO : < 200 OK [3306]
2017-12-31 21:35:46,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 432, '_0n0': 1219}
2017-12-31 21:35:46,994 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,000 : INFO : < 200 OK [3294]
2017-12-31 21:35:47,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 432, '_0n0': 1105}
2017-12-31 21:35:47,009 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,017 : INFO : < 200 OK [3296]
2017-12-31 21:35:47,022 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 427, '_0n0': 1037}
2017-12-31 21:35:47,026 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,032 : INFO : < 200 OK [3263]
2017-12-31 21:35:47,037 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 427, '_0n0': 961}
2017-12-31 21:35:47,040 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,046 : INFO : < 200 OK [3245]
2017-12-31 21:35:47,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 433, '_0n0': 923}
2017-12-31 21:35:47,054 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,060 : INFO : < 200 OK [3315]
2017-12-31 21:35:47,065 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 428, '_0n0': 743}
2017-12-31 21:35:47,067 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,073 : INFO : < 200 OK [3265]
2017-12-31 21:35:47,078 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 434, '_0n0': 1132}
2017-12-31 21:35:47,082 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,087 : INFO : < 200 OK [3285]

2017-12-31 21:35:47,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 434, '_0n0': 978}
2017-12-31 21:35:47,095 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,101 : INFO : < 200 OK [3272]
2017-12-31 21:35:47,106 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 434, '_0n0': 829}
2017-12-31 21:35:47,111 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,117 : INFO : < 200 OK [3274]
2017-12-31 21:35:47,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 429, '_0n0': 906}
2017-12-31 21:35:47,130 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,136 : INFO : < 200 OK [3295]
2017-12-31 21:35:47,143 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 435, '_0n0': 748}
2017-12-31 21:35:47,147 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,154 : INFO : < 200 OK [3264]
2017-12-31 21:35:47,159 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 435, '_0n0': 745}
2017-12-31 21:35:47,163 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,169 : INFO : < 200 OK [3264]
2017-12-31 21:35:47,175 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 430, '_0n0': 1214}
2017-12-31 21:35:47,179 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,185 : INFO : < 200 OK [3330]
2017-12-31 21:35:47,191 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 436, '_0n0': 780}
2017-12-31 21:35:47,196 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,202 : INFO : < 200 OK [3308]
2017-12-31 21:35:47,208 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 431, '_0n0': 743}
2017-12-31 21:35:47,212 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,222 : INFO : < 200 OK [3270]
2017-12-31 21:35:47,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 437, '_0n0': 906}
2017-12-31 21:35:47,235 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,245 : INFO : < 200 OK [3295]
2017-12-31 21:35:47,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 452, '_0n0': 829}
2017-12-31 21:35:47,255 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,265 : INFO : < 200 OK [3306]
2017-12-31 21:35:47,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 452, '_0n0': 783}
2017-12-31 21:35:47,281 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,286 : INFO : < 200 OK [3303]
2017-12-31 21:35:47,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 438, '_0n0': 1170}
2017-12-31 21:35:47,297 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,302 : INFO : < 200 OK [3302]
2017-12-31 21:35:47,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 438, '_0n0': 1119}
2017-12-31 21:35:47,312 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,317 : INFO : < 200 OK [3307]
2017-12-31 21:35:47,322 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 453, '_0n0': 1170}
2017-12-31 21:35:47,328 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,333 : INFO : < 200 OK [3295]
2017-12-31 21:35:47,338 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 453, '_0n0': 1119}
2017-12-31 21:35:47,343 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,350 : INFO : < 200 OK [3300]
2017-12-31 21:35:47,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 439, '_0n0': 1049}
2017-12-31 21:35:47,360 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,367 : INFO : < 200 OK [3325]
2017-12-31 21:35:47,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 454, '_0n0': 931}
2017-12-31 21:35:47,378 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,384 : INFO : < 200 OK [3296]
2017-12-31 21:35:47,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 454, '_0n0': 914}
2017-12-31 21:35:47,393 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,399 : INFO : < 200 OK [3294]
2017-12-31 21:35:47,405 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 440, '_0n0': 1107}
2017-12-31 21:35:47,408 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,414 : INFO : < 200 OK [3294]
2017-12-31 21:35:47,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 455, '_0n0': 900}
2017-12-31 21:35:47,422 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,427 : INFO : < 200 OK [3279]
2017-12-31 21:35:47,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 441, '_0n0': 825}
2017-12-31 21:35:47,436 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,442 : INFO : < 200 OK [3231]
2017-12-31 21:35:47,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 441, '_0n0': 871}
2017-12-31 21:35:47,451 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,457 : INFO : < 200 OK [3230]
2017-12-31 21:35:47,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 441, '_0n0': 1200}
2017-12-31 21:35:47,464 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,469 : INFO : < 200 OK [3247]
2017-12-31 21:35:47,474 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 441, '_0n0': 887}
2017-12-31 21:35:47,477 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,482 : INFO : < 200 OK [3229]

2017-12-31 21:35:47,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 456, '_0n0': 1105}
2017-12-31 21:35:47,491 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,497 : INFO : < 200 OK [3340]
2017-12-31 21:35:47,502 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 456, '_0n0': 1219}
2017-12-31 21:35:47,505 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,510 : INFO : < 200 OK [3338]
2017-12-31 21:35:47,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 456, '_0n0': 1207}
2017-12-31 21:35:47,518 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,524 : INFO : < 200 OK [3335]
2017-12-31 21:35:47,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 456, '_0n0': 1043}
2017-12-31 21:35:47,535 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,541 : INFO : < 200 OK [3340]
2017-12-31 21:35:47,548 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 442, '_0n0': 1119}
2017-12-31 21:35:47,551 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,556 : INFO : < 200 OK [3290]
2017-12-31 21:35:47,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 442, '_0n0': 1170}
2017-12-31 21:35:47,567 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,572 : INFO : < 200 OK [3285]
2017-12-31 21:35:47,577 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 457, '_0n0': 743}
2017-12-31 21:35:47,580 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,586 : INFO : < 200 OK [3309]
2017-12-31 21:35:47,592 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 443, '_0n0': 1170}
2017-12-31 21:35:47,595 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,601 : INFO : < 200 OK [3281]
2017-12-31 21:35:47,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 443, '_0n0': 1119}
2017-12-31 21:35:47,610 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,616 : INFO : < 200 OK [3286]
2017-12-31 21:35:47,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 458, '_0n0': 906}
2017-12-31 21:35:47,625 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,630 : INFO : < 200 OK [3306]
2017-12-31 21:35:47,634 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 444, '_0n0': 1216}
2017-12-31 21:35:47,638 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,643 : INFO : < 200 OK [3331]
2017-12-31 21:35:47,648 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 444, '_0n0': 868}
2017-12-31 21:35:47,651 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,656 : INFO : < 200 OK [3311]
2017-12-31 21:35:47,660 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 459, '_0n0': 906}
2017-12-31 21:35:47,664 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,669 : INFO : < 200 OK [3316]
2017-12-31 21:35:47,675 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 445, '_0n0': 967}
2017-12-31 21:35:47,679 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,685 : INFO : < 200 OK [3293]
2017-12-31 21:35:47,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 460, '_0n0': 739}
2017-12-31 21:35:47,697 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,703 : INFO : < 200 OK [3313]
2017-12-31 21:35:47,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 446, '_0n0': 796}
2017-12-31 21:35:47,711 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,717 : INFO : < 200 OK [3255]
2017-12-31 21:35:47,722 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 446, '_0n0': 1171}
2017-12-31 21:35:47,725 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,731 : INFO : < 200 OK [3271]
2017-12-31 21:35:47,735 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 446, '_0n0': 1184}
2017-12-31 21:35:47,738 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,743 : INFO : < 200 OK [3269]
2017-12-31 21:35:47,748 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 461, '_0n0': 1073}
2017-12-31 21:35:47,751 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,757 : INFO : < 200 OK [3286]
2017-12-31 21:35:47,761 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 447, '_0n0': 1222}
2017-12-31 21:35:47,765 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,770 : INFO : < 200 OK [3294]
2017-12-31 21:35:47,775 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 462, '_0n0': 1053}
2017-12-31 21:35:47,778 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,783 : INFO : < 200 OK [3291]
2017-12-31 21:35:47,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 448, '_0n0': 748}
2017-12-31 21:35:47,790 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,796 : INFO : < 200 OK [3280]
2017-12-31 21:35:47,802 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 448, '_0n0': 745}
2017-12-31 21:35:47,806 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,813 : INFO : < 200 OK [3280]
2017-12-31 21:35:47,818 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 463, '_0n0': 780}
2017-12-31 21:35:47,821 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,827 : INFO : < 200 OK [3316]

2017-12-31 21:35:47,831 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 449, '_0n0': 784}
2017-12-31 21:35:47,834 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,840 : INFO : < 200 OK [3228]
2017-12-31 21:35:47,846 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 449, '_0n0': 1159}
2017-12-31 21:35:47,850 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,856 : INFO : < 200 OK [3244]
2017-12-31 21:35:47,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 449, '_0n0': 939}
2017-12-31 21:35:47,865 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,871 : INFO : < 200 OK [3232]
2017-12-31 21:35:47,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 464, '_0n0': 902}
2017-12-31 21:35:47,879 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,884 : INFO : < 200 OK [3242]
2017-12-31 21:35:47,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 464, '_0n0': 1221}
2017-12-31 21:35:47,891 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,897 : INFO : < 200 OK [3248]
2017-12-31 21:35:47,902 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 464, '_0n0': 881}
2017-12-31 21:35:47,906 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,912 : INFO : < 200 OK [3230]
2017-12-31 21:35:47,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 450, '_0n0': 780}
2017-12-31 21:35:47,919 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,925 : INFO : < 200 OK [3285]
2017-12-31 21:35:47,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 465, '_0n0': 748}
2017-12-31 21:35:47,933 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,938 : INFO : < 200 OK [3304]
2017-12-31 21:35:47,944 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 465, '_0n0': 745}
2017-12-31 21:35:47,947 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:47,952 : INFO : < 200 OK [3304]
2017-12-31 21:35:47,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 451, '_0n0': 1185}
2017-12-31 21:35:47,961 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,967 : INFO : < 200 OK [3306]
2017-12-31 21:35:47,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 466, '_0n0': 1188}
2017-12-31 21:35:47,975 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,982 : INFO : < 200 OK [3353]
2017-12-31 21:35:47,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 466, '_0n0': 1070}
2017-12-31 21:35:47,993 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:47,999 : INFO : < 200 OK [3347]
2017-12-31 21:35:48,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 466, '_0n0': 1245}
2017-12-31 21:35:48,010 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,017 : INFO : < 200 OK [3348]
2017-12-31 21:35:48,022 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 466, '_0n0': 1219}
2017-12-31 21:35:48,027 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,032 : INFO : < 200 OK [3346]
2017-12-31 21:35:48,037 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 472, '_0n0': 1132}
2017-12-31 21:35:48,041 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,047 : INFO : < 200 OK [3277]
2017-12-31 21:35:48,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 472, '_0n0': 978}
2017-12-31 21:35:48,057 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,062 : INFO : < 200 OK [3264]
2017-12-31 21:35:48,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 472, '_0n0': 829}
2017-12-31 21:35:48,071 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,077 : INFO : < 200 OK [3266]
2017-12-31 21:35:48,081 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 467, '_0n0': 780}
2017-12-31 21:35:48,085 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,090 : INFO : < 200 OK [3317]
2017-12-31 21:35:48,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 473, '_0n0': 1057}
2017-12-31 21:35:48,098 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,103 : INFO : < 200 OK [3338]
2017-12-31 21:35:48,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 468, '_0n0': 1052}
2017-12-31 21:35:48,111 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,117 : INFO : < 200 OK [3275]
2017-12-31 21:35:48,123 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 468, '_0n0': 1163}
2017-12-31 21:35:48,126 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,132 : INFO : < 200 OK [3282]
2017-12-31 21:35:48,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 474, '_0n0': 1130}
2017-12-31 21:35:48,142 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,149 : INFO : < 200 OK [3325]
2017-12-31 21:35:48,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 474, '_0n0': 1175}
2017-12-31 21:35:48,159 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,172 : INFO : < 200 OK [3323]
2017-12-31 21:35:48,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 469, '_0n0': 931}
2017-12-31 21:35:48,181 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,187 : INFO : < 200 OK [3292]

2017-12-31 21:35:48,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 469, '_0n0': 914}
2017-12-31 21:35:48,195 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,200 : INFO : < 200 OK [3290]
2017-12-31 21:35:48,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 475, '_0n0': 1221}
2017-12-31 21:35:48,208 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,214 : INFO : < 200 OK [3280]
2017-12-31 21:35:48,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 475, '_0n0': 902}
2017-12-31 21:35:48,223 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,228 : INFO : < 200 OK [3274]
2017-12-31 21:35:48,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 470, '_0n0': 931}
2017-12-31 21:35:48,236 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,242 : INFO : < 200 OK [3287]
2017-12-31 21:35:48,246 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 470, '_0n0': 914}
2017-12-31 21:35:48,249 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,255 : INFO : < 200 OK [3285]
2017-12-31 21:35:48,260 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 476, '_0n0': 745}
2017-12-31 21:35:48,263 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,268 : INFO : < 200 OK [3268]
2017-12-31 21:35:48,272 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 471, '_0n0': 789}
2017-12-31 21:35:48,276 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,281 : INFO : < 200 OK [3284]
2017-12-31 21:35:48,286 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 477, '_0n0': 868}
2017-12-31 21:35:48,290 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,296 : INFO : < 200 OK [3308]
2017-12-31 21:35:48,301 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 477, '_0n0': 1212}
2017-12-31 21:35:48,305 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,314 : INFO : < 200 OK [3323]
2017-12-31 21:35:48,319 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 505, '_0n0': 738}
2017-12-31 21:35:48,323 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,328 : INFO : < 200 OK [3317]
2017-12-31 21:35:48,333 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 478, '_0n0': 977}
2017-12-31 21:35:48,336 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,342 : INFO : < 200 OK [3285]
2017-12-31 21:35:48,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 506, '_0n0': 829}
2017-12-31 21:35:48,351 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,357 : INFO : < 200 OK [3299]
2017-12-31 21:35:48,362 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 506, '_0n0': 783}
2017-12-31 21:35:48,366 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,371 : INFO : < 200 OK [3296]
2017-12-31 21:35:48,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 479, '_0n0': 1026}
2017-12-31 21:35:48,380 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,385 : INFO : < 200 OK [3329]
2017-12-31 21:35:48,390 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 507, '_0n0': 1132}
2017-12-31 21:35:48,393 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,399 : INFO : < 200 OK [3283]
2017-12-31 21:35:48,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 507, '_0n0': 978}
2017-12-31 21:35:48,407 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,412 : INFO : < 200 OK [3270]
2017-12-31 21:35:48,417 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 507, '_0n0': 829}
2017-12-31 21:35:48,420 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,426 : INFO : < 200 OK [3272]
2017-12-31 21:35:48,431 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 480, '_0n0': 1092}
2017-12-31 21:35:48,434 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,440 : INFO : < 200 OK [3286]
2017-12-31 21:35:48,445 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 508, '_0n0': 978}
2017-12-31 21:35:48,449 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,456 : INFO : < 200 OK [3267]
2017-12-31 21:35:48,462 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 508, '_0n0': 1132}
2017-12-31 21:35:48,467 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,472 : INFO : < 200 OK [3280]
2017-12-31 21:35:48,477 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 508, '_0n0': 829}
2017-12-31 21:35:48,480 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,486 : INFO : < 200 OK [3269]
2017-12-31 21:35:48,491 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 481, '_0n0': 839}
2017-12-31 21:35:48,495 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,500 : INFO : < 200 OK [3290]
2017-12-31 21:35:48,506 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 481, '_0n0': 1097}
2017-12-31 21:35:48,510 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,516 : INFO : < 200 OK [3304]
2017-12-31 21:35:48,521 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 481, '_0n0': 1201}
2017-12-31 21:35:48,526 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,531 : INFO : < 200 OK [3302]

2017-12-31 21:35:48,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 509, '_0n0': 931}
2017-12-31 21:35:48,539 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,545 : INFO : < 200 OK [3294]
2017-12-31 21:35:48,550 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 509, '_0n0': 914}
2017-12-31 21:35:48,554 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,559 : INFO : < 200 OK [3292]
2017-12-31 21:35:48,564 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 482, '_0n0': 1216}
2017-12-31 21:35:48,567 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,573 : INFO : < 200 OK [3318]
2017-12-31 21:35:48,577 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 510, '_0n0': 1058}
2017-12-31 21:35:48,580 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,586 : INFO : < 200 OK [3316]
2017-12-31 21:35:48,592 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 483, '_0n0': 1022}
2017-12-31 21:35:48,596 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,602 : INFO : < 200 OK [3285]
2017-12-31 21:35:48,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 483, '_0n0': 1095}
2017-12-31 21:35:48,614 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,621 : INFO : < 200 OK [3290]
2017-12-31 21:35:48,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 511, '_0n0': 1107}
2017-12-31 21:35:48,630 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,636 : INFO : < 200 OK [3341]
2017-12-31 21:35:48,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 484, '_0n0': 868}
2017-12-31 21:35:48,645 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,650 : INFO : < 200 OK [3318]
2017-12-31 21:35:48,654 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 484, '_0n0': 1212}
2017-12-31 21:35:48,658 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,664 : INFO : < 200 OK [3333]
2017-12-31 21:35:48,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 512, '_0n0': 898}
2017-12-31 21:35:48,672 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,679 : INFO : < 200 OK [3267]
2017-12-31 21:35:48,684 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 485, '_0n0': 895}
2017-12-31 21:35:48,687 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,693 : INFO : < 200 OK [3341]
2017-12-31 21:35:48,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 513, '_0n0': 898}
2017-12-31 21:35:48,701 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,707 : INFO : < 200 OK [3268]
2017-12-31 21:35:48,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 486, '_0n0': 1244}
2017-12-31 21:35:48,715 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,721 : INFO : < 200 OK [3306]
2017-12-31 21:35:48,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 486, '_0n0': 1135}
2017-12-31 21:35:48,731 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,736 : INFO : < 200 OK [3307]
2017-12-31 21:35:48,741 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 514, '_0n0': 919}
2017-12-31 21:35:48,745 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,752 : INFO : < 200 OK [3302]
2017-12-31 21:35:48,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 500, '_0n0': 1217}
2017-12-31 21:35:48,762 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,769 : INFO : < 200 OK [3287]
2017-12-31 21:35:48,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 500, '_0n0': 1075}
2017-12-31 21:35:48,779 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,786 : INFO : < 200 OK [3270]
2017-12-31 21:35:48,794 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 515, '_0n0': 1231}
2017-12-31 21:35:48,799 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,807 : INFO : < 200 OK [3280]
2017-12-31 21:35:48,814 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 501, '_0n0': 977}
2017-12-31 21:35:48,819 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,825 : INFO : < 200 OK [3285]
2017-12-31 21:35:48,830 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 516, '_0n0': 1069}
2017-12-31 21:35:48,834 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,839 : INFO : < 200 OK [3291]
2017-12-31 21:35:48,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 516, '_0n0': 1015}
2017-12-31 21:35:48,847 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,852 : INFO : < 200 OK [3292]
2017-12-31 21:35:48,857 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 502, '_0n0': 896}
2017-12-31 21:35:48,860 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,866 : INFO : < 200 OK [3313]
2017-12-31 21:35:48,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 517, '_0n0': 926}
2017-12-31 21:35:48,874 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,883 : INFO : < 200 OK [3269]
2017-12-31 21:35:48,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 503, '_0n0': 1107}
2017-12-31 21:35:48,893 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,903 : INFO : < 200 OK [3294]

2017-12-31 21:35:48,909 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 518, '_0n0': 963}
2017-12-31 21:35:48,914 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,921 : INFO : < 200 OK [3301]
2017-12-31 21:35:48,928 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 504, '_0n0': 1177}
2017-12-31 21:35:48,932 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,938 : INFO : < 200 OK [3298]
2017-12-31 21:35:48,947 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 519, '_0n0': 806}
2017-12-31 21:35:48,951 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:48,957 : INFO : < 200 OK [3277]
2017-12-31 21:35:48,963 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 525, '_0n0': 1117}
2017-12-31 21:35:48,967 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,973 : INFO : < 200 OK [3311]
2017-12-31 21:35:48,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 520, '_0n0': 1133}
2017-12-31 21:35:48,984 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:48,990 : INFO : < 200 OK [3341]
2017-12-31 21:35:48,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 526, '_0n0': 1107}
2017-12-31 21:35:49,000 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,006 : INFO : < 200 OK [3332]
2017-12-31 21:35:49,013 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 521, '_0n0': 945}
2017-12-31 21:35:49,016 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,022 : INFO : < 200 OK [3314]
2017-12-31 21:35:49,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 521, '_0n0': 891}
2017-12-31 21:35:49,032 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,037 : INFO : < 200 OK [3314]
2017-12-31 21:35:49,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 521, '_0n0': 755}
2017-12-31 21:35:49,048 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,053 : INFO : < 200 OK [3311]
2017-12-31 21:35:49,062 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 527, '_0n0': 1023}
2017-12-31 21:35:49,066 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,072 : INFO : < 200 OK [3327]
2017-12-31 21:35:49,079 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 522, '_0n0': 1243}
2017-12-31 21:35:49,082 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,088 : INFO : < 200 OK [3337]
2017-12-31 21:35:49,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 522, '_0n0': 1146}
2017-12-31 21:35:49,098 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,104 : INFO : < 200 OK [3330]
2017-12-31 21:35:49,112 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 528, '_0n0': 829}
2017-12-31 21:35:49,115 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,120 : INFO : < 200 OK [3310]
2017-12-31 21:35:49,128 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 528, '_0n0': 783}
2017-12-31 21:35:49,132 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,138 : INFO : < 200 OK [3307]
2017-12-31 21:35:49,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 523, '_0n0': 1224}
2017-12-31 21:35:49,147 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,153 : INFO : < 200 OK [3268]
2017-12-31 21:35:49,158 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 523, '_0n0': 1092}
2017-12-31 21:35:49,162 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,168 : INFO : < 200 OK [3272]
2017-12-31 21:35:49,176 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 529, '_0n0': 832}
2017-12-31 21:35:49,180 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,185 : INFO : < 200 OK [3288]
2017-12-31 21:35:49,190 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 524, '_0n0': 1123}
2017-12-31 21:35:49,194 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,199 : INFO : < 200 OK [3318]
2017-12-31 21:35:49,204 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 530, '_0n0': 1176}
2017-12-31 21:35:49,207 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,213 : INFO : < 200 OK [3290]
2017-12-31 21:35:49,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 545, '_0n0': 1197}
2017-12-31 21:35:49,222 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,228 : INFO : < 200 OK [3288]
2017-12-31 21:35:49,232 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 545, '_0n0': 1040}
2017-12-31 21:35:49,235 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,241 : INFO : < 200 OK [3288]
2017-12-31 21:35:49,246 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 531, '_0n0': 829}
2017-12-31 21:35:49,249 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,255 : INFO : < 200 OK [3296]
2017-12-31 21:35:49,260 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 531, '_0n0': 783}
2017-12-31 21:35:49,263 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,269 : INFO : < 200 OK [3293]
2017-12-31 21:35:49,274 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 546, '_0n0': 925}
2017-12-31 21:35:49,278 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,285 : INFO : < 200 OK [3288]

2017-12-31 21:35:49,290 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 546, '_0n0': 810}
2017-12-31 21:35:49,295 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,302 : INFO : < 200 OK [3287]
2017-12-31 21:35:49,308 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 532, '_0n0': 948}
2017-12-31 21:35:49,311 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,317 : INFO : < 200 OK [3287]
2017-12-31 21:35:49,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 532, '_0n0': 1148}
2017-12-31 21:35:49,327 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,334 : INFO : < 200 OK [3301]
2017-12-31 21:35:49,340 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 547, '_0n0': 1073}
2017-12-31 21:35:49,344 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,351 : INFO : < 200 OK [3303]
2017-12-31 21:35:49,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 533, '_0n0': 1029}
2017-12-31 21:35:49,361 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,370 : INFO : < 200 OK [3285]
2017-12-31 21:35:49,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 533, '_0n0': 883}
2017-12-31 21:35:49,381 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,387 : INFO : < 200 OK [3274]
2017-12-31 21:35:49,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 548, '_0n0': 1194}
2017-12-31 21:35:49,398 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,404 : INFO : < 200 OK [3303]
2017-12-31 21:35:49,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 534, '_0n0': 1144}
2017-12-31 21:35:49,415 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,420 : INFO : < 200 OK [3314]
2017-12-31 21:35:49,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 549, '_0n0': 917}
2017-12-31 21:35:49,430 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,436 : INFO : < 200 OK [3288]
2017-12-31 21:35:49,442 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 535, '_0n0': 851}
2017-12-31 21:35:49,446 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,452 : INFO : < 200 OK [3302]
2017-12-31 21:35:49,457 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 550, '_0n0': 1217}
2017-12-31 21:35:49,461 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,467 : INFO : < 200 OK [3287]
2017-12-31 21:35:49,472 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 550, '_0n0': 1075}
2017-12-31 21:35:49,475 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,481 : INFO : < 200 OK [3270]
2017-12-31 21:35:49,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 536, '_0n0': 806}
2017-12-31 21:35:49,490 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,496 : INFO : < 200 OK [3279]
2017-12-31 21:35:49,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 536, '_0n0': 926}
2017-12-31 21:35:49,504 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,510 : INFO : < 200 OK [3275]
2017-12-31 21:35:49,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 536, '_0n0': 789}
2017-12-31 21:35:49,518 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,524 : INFO : < 200 OK [3281]
2017-12-31 21:35:49,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 551, '_0n0': 750}
2017-12-31 21:35:49,533 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,539 : INFO : < 200 OK [3304]
2017-12-31 21:35:49,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 537, '_0n0': 848}
2017-12-31 21:35:49,547 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,553 : INFO : < 200 OK [3274]
2017-12-31 21:35:49,558 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 552, '_0n0': 977}
2017-12-31 21:35:49,562 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,567 : INFO : < 200 OK [3269]
2017-12-31 21:35:49,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 538, '_0n0': 1174}
2017-12-31 21:35:49,577 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,582 : INFO : < 200 OK [3332]
2017-12-31 21:35:49,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 553, '_0n0': 1177}
2017-12-31 21:35:49,589 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,596 : INFO : < 200 OK [3279]
2017-12-31 21:35:49,601 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 539, '_0n0': 1157}
2017-12-31 21:35:49,605 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,611 : INFO : < 200 OK [3312]
2017-12-31 21:35:49,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 554, '_0n0': 1107}
2017-12-31 21:35:49,622 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,638 : INFO : < 200 OK [3294]
2017-12-31 21:35:49,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 540, '_0n0': 1105}
2017-12-31 21:35:49,647 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,654 : INFO : < 200 OK [3303]
2017-12-31 21:35:49,659 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 540, '_0n0': 1245}
2017-12-31 21:35:49,663 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,669 : INFO : < 200 OK [3303]

2017-12-31 21:35:49,676 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 540, '_0n0': 1207}
2017-12-31 21:35:49,681 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,687 : INFO : < 200 OK [3298]
2017-12-31 21:35:49,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 540, '_0n0': 1219}
2017-12-31 21:35:49,697 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,704 : INFO : < 200 OK [3301]
2017-12-31 21:35:49,710 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 555, '_0n0': 848}
2017-12-31 21:35:49,715 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,721 : INFO : < 200 OK [3285]
2017-12-31 21:35:49,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 541, '_0n0': 1162}
2017-12-31 21:35:49,731 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,737 : INFO : < 200 OK [3366]
2017-12-31 21:35:49,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 556, '_0n0': 1132}
2017-12-31 21:35:49,749 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,756 : INFO : < 200 OK [3286]
2017-12-31 21:35:49,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 556, '_0n0': 978}
2017-12-31 21:35:49,767 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,774 : INFO : < 200 OK [3273]
2017-12-31 21:35:49,779 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 556, '_0n0': 829}
2017-12-31 21:35:49,784 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,790 : INFO : < 200 OK [3275]
2017-12-31 21:35:49,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 542, '_0n0': 1118}
2017-12-31 21:35:49,800 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,809 : INFO : < 200 OK [3319]
2017-12-31 21:35:49,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 557, '_0n0': 1022}
2017-12-31 21:35:49,820 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,826 : INFO : < 200 OK [3304]
2017-12-31 21:35:49,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 557, '_0n0': 1095}
2017-12-31 21:35:49,836 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,842 : INFO : < 200 OK [3309]
2017-12-31 21:35:49,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 557, '_0n0': 1053}
2017-12-31 21:35:49,852 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,858 : INFO : < 200 OK [3300]
2017-12-31 21:35:49,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 557, '_0n0': 900}
2017-12-31 21:35:49,868 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,875 : INFO : < 200 OK [3290]
2017-12-31 21:35:49,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 543, '_0n0': 1034}
2017-12-31 21:35:49,884 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,890 : INFO : < 200 OK [3369]
2017-12-31 21:35:49,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 558, '_0n0': 851}
2017-12-31 21:35:49,902 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:49,910 : INFO : < 200 OK [3302]
2017-12-31 21:35:49,915 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 544, '_0n0': 1147}
2017-12-31 21:35:49,919 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,926 : INFO : < 200 OK [3350]
2017-12-31 21:35:49,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 559, '_0n0': 1216}
2017-12-31 21:35:49,936 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,942 : INFO : < 200 OK [3332]
2017-12-31 21:35:49,948 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 559, '_0n0': 1212}
2017-12-31 21:35:49,953 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,960 : INFO : < 200 OK [3327]
2017-12-31 21:35:49,966 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 565, '_0n0': 1102}
2017-12-31 21:35:49,970 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,978 : INFO : < 200 OK [3274]
2017-12-31 21:35:49,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 560, '_0n0': 1170}
2017-12-31 21:35:49,988 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:49,995 : INFO : < 200 OK [3321]
2017-12-31 21:35:50,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 560, '_0n0': 1119}
2017-12-31 21:35:50,005 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,013 : INFO : < 200 OK [3326]
2017-12-31 21:35:50,019 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 566, '_0n0': 1147}
2017-12-31 21:35:50,023 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,029 : INFO : < 200 OK [3325]
2017-12-31 21:35:50,036 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 561, '_0n0': 898}
2017-12-31 21:35:50,040 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,047 : INFO : < 200 OK [3255]
2017-12-31 21:35:50,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 561, '_0n0': 727}
2017-12-31 21:35:50,057 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,065 : INFO : < 200 OK [3260]
2017-12-31 21:35:50,070 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 561, '_0n0': 867}
2017-12-31 21:35:50,075 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,081 : INFO : < 200 OK [3257]

2017-12-31 21:35:50,086 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 567, '_0n0': 977}
2017-12-31 21:35:50,091 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,097 : INFO : < 200 OK [3275]
2017-12-31 21:35:50,102 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 562, '_0n0': 877}
2017-12-31 21:35:50,107 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,113 : INFO : < 200 OK [3308]
2017-12-31 21:35:50,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 568, '_0n0': 748}
2017-12-31 21:35:50,124 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,132 : INFO : < 200 OK [3267]
2017-12-31 21:35:50,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 568, '_0n0': 745}
2017-12-31 21:35:50,142 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,149 : INFO : < 200 OK [3267]
2017-12-31 21:35:50,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 563, '_0n0': 906}
2017-12-31 21:35:50,161 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,166 : INFO : < 200 OK [3337]
2017-12-31 21:35:50,171 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 569, '_0n0': 1073}
2017-12-31 21:35:50,177 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,182 : INFO : < 200 OK [3330]
2017-12-31 21:35:50,188 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 569, '_0n0': 1117}
2017-12-31 21:35:50,193 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,199 : INFO : < 200 OK [3330]
2017-12-31 21:35:50,205 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 564, '_0n0': 1204}
2017-12-31 21:35:50,210 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,216 : INFO : < 200 OK [3300]
2017-12-31 21:35:50,222 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 564, '_0n0': 735}
2017-12-31 21:35:50,227 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,233 : INFO : < 200 OK [3277]
2017-12-31 21:35:50,238 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 564, '_0n0': 870}
2017-12-31 21:35:50,244 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,250 : INFO : < 200 OK [3277]
2017-12-31 21:35:50,256 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 570, '_0n0': 1177}
2017-12-31 21:35:50,262 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,269 : INFO : < 200 OK [3293]
2017-12-31 21:35:50,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 585, '_0n0': 1132}
2017-12-31 21:35:50,279 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,285 : INFO : < 200 OK [3284]
2017-12-31 21:35:50,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 585, '_0n0': 917}
2017-12-31 21:35:50,297 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,303 : INFO : < 200 OK [3280]
2017-12-31 21:35:50,310 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 571, '_0n0': 1224}
2017-12-31 21:35:50,315 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,321 : INFO : < 200 OK [3290]
2017-12-31 21:35:50,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 571, '_0n0': 1092}
2017-12-31 21:35:50,331 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,337 : INFO : < 200 OK [3294]
2017-12-31 21:35:50,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 586, '_0n0': 795}
2017-12-31 21:35:50,347 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,354 : INFO : < 200 OK [3264]
2017-12-31 21:35:50,361 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 572, '_0n0': 829}
2017-12-31 21:35:50,366 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,372 : INFO : < 200 OK [3321]
2017-12-31 21:35:50,378 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 572, '_0n0': 783}
2017-12-31 21:35:50,383 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,389 : INFO : < 200 OK [3318]
2017-12-31 21:35:50,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 587, '_0n0': 806}
2017-12-31 21:35:50,400 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,406 : INFO : < 200 OK [3275]
2017-12-31 21:35:50,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 587, '_0n0': 926}
2017-12-31 21:35:50,416 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,423 : INFO : < 200 OK [3271]
2017-12-31 21:35:50,429 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 587, '_0n0': 789}
2017-12-31 21:35:50,434 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,440 : INFO : < 200 OK [3277]
2017-12-31 21:35:50,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 573, '_0n0': 743}
2017-12-31 21:35:50,450 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,457 : INFO : < 200 OK [3298]
2017-12-31 21:35:50,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 588, '_0n0': 1242}
2017-12-31 21:35:50,477 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,483 : INFO : < 200 OK [3322]
2017-12-31 21:35:50,490 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 588, '_0n0': 1047}
2017-12-31 21:35:50,494 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,500 : INFO : < 200 OK [3325]

2017-12-31 21:35:50,506 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 574, '_0n0': 1056}
2017-12-31 21:35:50,510 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,516 : INFO : < 200 OK [3321]
2017-12-31 21:35:50,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 574, '_0n0': 1051}
2017-12-31 21:35:50,527 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,533 : INFO : < 200 OK [3325]
2017-12-31 21:35:50,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 589, '_0n0': 743}
2017-12-31 21:35:50,545 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,552 : INFO : < 200 OK [3274]
2017-12-31 21:35:50,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 575, '_0n0': 1121}
2017-12-31 21:35:50,561 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,567 : INFO : < 200 OK [3321]
2017-12-31 21:35:50,575 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 575, '_0n0': 1141}
2017-12-31 21:35:50,580 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,587 : INFO : < 200 OK [3314]
2017-12-31 21:35:50,594 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 590, '_0n0': 735}
2017-12-31 21:35:50,598 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,604 : INFO : < 200 OK [3304]
2017-12-31 21:35:50,610 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 590, '_0n0': 870}
2017-12-31 21:35:50,614 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,620 : INFO : < 200 OK [3304]
2017-12-31 21:35:50,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 590, '_0n0': 1204}
2017-12-31 21:35:50,630 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,638 : INFO : < 200 OK [3327]
2017-12-31 21:35:50,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 576, '_0n0': 934}
2017-12-31 21:35:50,648 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,655 : INFO : < 200 OK [3306]
2017-12-31 21:35:50,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 889}
2017-12-31 21:35:50,665 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,671 : INFO : < 200 OK [3315]
2017-12-31 21:35:50,678 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 577, '_0n0': 1078}
2017-12-31 21:35:50,683 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,689 : INFO : < 200 OK [3278]
2017-12-31 21:35:50,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 592, '_0n0': 856}
2017-12-31 21:35:50,700 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,706 : INFO : < 200 OK [3317]
2017-12-31 21:35:50,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 592, '_0n0': 1152}
2017-12-31 21:35:50,716 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,722 : INFO : < 200 OK [3331]
2017-12-31 21:35:50,729 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 592, '_0n0': 869}
2017-12-31 21:35:50,733 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,741 : INFO : < 200 OK [3319]
2017-12-31 21:35:50,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 592, '_0n0': 791}
2017-12-31 21:35:50,751 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,757 : INFO : < 200 OK [3318]
2017-12-31 21:35:50,764 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 578, '_0n0': 863}
2017-12-31 21:35:50,768 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,776 : INFO : < 200 OK [3324]
2017-12-31 21:35:50,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 578, '_0n0': 1190}
2017-12-31 21:35:50,785 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,791 : INFO : < 200 OK [3340]
2017-12-31 21:35:50,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 593, '_0n0': 922}
2017-12-31 21:35:50,801 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,807 : INFO : < 200 OK [3285]
2017-12-31 21:35:50,813 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 593, '_0n0': 1027}
2017-12-31 21:35:50,818 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,825 : INFO : < 200 OK [3307]
2017-12-31 21:35:50,831 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 579, '_0n0': 809}
2017-12-31 21:35:50,835 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,841 : INFO : < 200 OK [3312]
2017-12-31 21:35:50,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 594, '_0n0': 937}
2017-12-31 21:35:50,852 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,859 : INFO : < 200 OK [3288]
2017-12-31 21:35:50,865 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 580, '_0n0': 1031}
2017-12-31 21:35:50,869 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,878 : INFO : < 200 OK [3348]
2017-12-31 21:35:50,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 595, '_0n0': 753}
2017-12-31 21:35:50,887 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,894 : INFO : < 200 OK [3291]
2017-12-31 21:35:50,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 581, '_0n0': 1173}
2017-12-31 21:35:50,904 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,911 : INFO : < 200 OK [3283]

2017-12-31 21:35:50,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 596, '_0n0': 751}
2017-12-31 21:35:50,921 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,927 : INFO : < 200 OK [3299]
2017-12-31 21:35:50,933 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 582, '_0n0': 779}
2017-12-31 21:35:50,937 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,944 : INFO : < 200 OK [3305]
2017-12-31 21:35:50,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 597, '_0n0': 869}
2017-12-31 21:35:50,953 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,960 : INFO : < 200 OK [3323]
2017-12-31 21:35:50,966 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 597, '_0n0': 1152}
2017-12-31 21:35:50,969 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:50,976 : INFO : < 200 OK [3335]
2017-12-31 21:35:50,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 597, '_0n0': 856}
2017-12-31 21:35:50,987 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:50,993 : INFO : < 200 OK [3321]
2017-12-31 21:35:50,999 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 597, '_0n0': 791}
2017-12-31 21:35:51,003 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,010 : INFO : < 200 OK [3322]
2017-12-31 21:35:51,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 583, '_0n0': 730}
2017-12-31 21:35:51,020 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,027 : INFO : < 200 OK [3313]
2017-12-31 21:35:51,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 598, '_0n0': 1121}
2017-12-31 21:35:51,037 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,043 : INFO : < 200 OK [3297]
2017-12-31 21:35:51,050 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 598, '_0n0': 1141}
2017-12-31 21:35:51,055 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,063 : INFO : < 200 OK [3290]
2017-12-31 21:35:51,069 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 584, '_0n0': 889}
2017-12-31 21:35:51,073 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,079 : INFO : < 200 OK [3307]
2017-12-31 21:35:51,086 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 599, '_0n0': 938}
2017-12-31 21:35:51,090 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,097 : INFO : < 200 OK [3317]
2017-12-31 21:35:51,102 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 599, '_0n0': 1099}
2017-12-31 21:35:51,106 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,113 : INFO : < 200 OK [3344]
2017-12-31 21:35:51,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 605, '_0n0': 1077}
2017-12-31 21:35:51,124 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,131 : INFO : < 200 OK [3291]
2017-12-31 21:35:51,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 605, '_0n0': 1134}
2017-12-31 21:35:51,141 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,147 : INFO : < 200 OK [3292]
2017-12-31 21:35:51,154 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 605, '_0n0': 828}
2017-12-31 21:35:51,159 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,165 : INFO : < 200 OK [3279]
2017-12-31 21:35:51,171 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 605, '_0n0': 850}
2017-12-31 21:35:51,176 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,184 : INFO : < 200 OK [3277]
2017-12-31 21:35:51,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 600, '_0n0': 1165}
2017-12-31 21:35:51,194 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,200 : INFO : < 200 OK [3313]
2017-12-31 21:35:51,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 600, '_0n0': 754}
2017-12-31 21:35:51,209 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,215 : INFO : < 200 OK [3302]
2017-12-31 21:35:51,221 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 606, '_0n0': 1152}
2017-12-31 21:35:51,225 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,231 : INFO : < 200 OK [3330]
2017-12-31 21:35:51,238 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 606, '_0n0': 856}
2017-12-31 21:35:51,243 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,249 : INFO : < 200 OK [3316]
2017-12-31 21:35:51,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 606, '_0n0': 869}
2017-12-31 21:35:51,260 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,266 : INFO : < 200 OK [3318]
2017-12-31 21:35:51,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 606, '_0n0': 791}
2017-12-31 21:35:51,278 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,284 : INFO : < 200 OK [3317]
2017-12-31 21:35:51,290 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 601, '_0n0': 751}
2017-12-31 21:35:51,294 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,302 : INFO : < 200 OK [3302]
2017-12-31 21:35:51,308 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 607, '_0n0': 751}
2017-12-31 21:35:51,312 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,319 : INFO : < 200 OK [3301]

2017-12-31 21:35:51,324 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 602, '_0n0': 912}
2017-12-31 21:35:51,328 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,336 : INFO : < 200 OK [3336]
2017-12-31 21:35:51,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 608, '_0n0': 1078}
2017-12-31 21:35:51,345 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,351 : INFO : < 200 OK [3278]
2017-12-31 21:35:51,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 603, '_0n0': 735}
2017-12-31 21:35:51,360 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,367 : INFO : < 200 OK [3313]
2017-12-31 21:35:51,373 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 603, '_0n0': 870}
2017-12-31 21:35:51,377 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,384 : INFO : < 200 OK [3313]
2017-12-31 21:35:51,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 603, '_0n0': 1204}
2017-12-31 21:35:51,395 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,401 : INFO : < 200 OK [3336]
2017-12-31 21:35:51,406 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 609, '_0n0': 959}
2017-12-31 21:35:51,410 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,416 : INFO : < 200 OK [3307]
2017-12-31 21:35:51,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 604, '_0n0': 811}
2017-12-31 21:35:51,427 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,433 : INFO : < 200 OK [3317]
2017-12-31 21:35:51,439 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 604, '_0n0': 1211}
2017-12-31 21:35:51,443 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,449 : INFO : < 200 OK [3329]
2017-12-31 21:35:51,454 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 610, '_0n0': 1112}
2017-12-31 21:35:51,458 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,464 : INFO : < 200 OK [3340]
2017-12-31 21:35:51,470 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 625, '_0n0': 1173}
2017-12-31 21:35:51,475 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,480 : INFO : < 200 OK [3288]
2017-12-31 21:35:51,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 611, '_0n0': 1116}
2017-12-31 21:35:51,489 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,494 : INFO : < 200 OK [3309]
2017-12-31 21:35:51,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 611, '_0n0': 759}
2017-12-31 21:35:51,503 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,510 : INFO : < 200 OK [3297]
2017-12-31 21:35:51,516 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 611, '_0n0': 1131}
2017-12-31 21:35:51,520 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,527 : INFO : < 200 OK [3309]
2017-12-31 21:35:51,532 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 626, '_0n0': 904}
2017-12-31 21:35:51,535 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,542 : INFO : < 200 OK [3286]
2017-12-31 21:35:51,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 612, '_0n0': 811}
2017-12-31 21:35:51,552 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,559 : INFO : < 200 OK [3294]
2017-12-31 21:35:51,564 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 627, '_0n0': 959}
2017-12-31 21:35:51,567 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,572 : INFO : < 200 OK [3307]
2017-12-31 21:35:51,578 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 613, '_0n0': 818}
2017-12-31 21:35:51,582 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,588 : INFO : < 200 OK [3305]
2017-12-31 21:35:51,594 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 628, '_0n0': 1142}
2017-12-31 21:35:51,598 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,604 : INFO : < 200 OK [3311]
2017-12-31 21:35:51,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 614, '_0n0': 818}
2017-12-31 21:35:51,613 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,619 : INFO : < 200 OK [3279]
2017-12-31 21:35:51,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 629, '_0n0': 959}
2017-12-31 21:35:51,628 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,634 : INFO : < 200 OK [3312]
2017-12-31 21:35:51,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 615, '_0n0': 959}
2017-12-31 21:35:51,645 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,651 : INFO : < 200 OK [3304]
2017-12-31 21:35:51,657 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 630, '_0n0': 959}
2017-12-31 21:35:51,661 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,668 : INFO : < 200 OK [3309]
2017-12-31 21:35:51,673 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 616, '_0n0': 818}
2017-12-31 21:35:51,678 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,684 : INFO : < 200 OK [3279]
2017-12-31 21:35:51,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 631, '_0n0': 818}
2017-12-31 21:35:51,695 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,701 : INFO : < 200 OK [3285]

2017-12-31 21:35:51,707 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 617, '_0n0': 788}
2017-12-31 21:35:51,711 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,717 : INFO : < 200 OK [3263]
2017-12-31 21:35:51,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 617, '_0n0': 928}
2017-12-31 21:35:51,728 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,735 : INFO : < 200 OK [3261]
2017-12-31 21:35:51,742 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 632, '_0n0': 905}
2017-12-31 21:35:51,746 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,752 : INFO : < 200 OK [3294]
2017-12-31 21:35:51,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 618, '_0n0': 1154}
2017-12-31 21:35:51,762 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,768 : INFO : < 200 OK [3328]
2017-12-31 21:35:51,773 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 633, '_0n0': 811}
2017-12-31 21:35:51,777 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,783 : INFO : < 200 OK [3266]
2017-12-31 21:35:51,790 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 633, '_0n0': 1211}
2017-12-31 21:35:51,794 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,800 : INFO : < 200 OK [3278]
2017-12-31 21:35:51,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 619, '_0n0': 1152}
2017-12-31 21:35:51,809 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,816 : INFO : < 200 OK [3334]
2017-12-31 21:35:51,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 619, '_0n0': 856}
2017-12-31 21:35:51,825 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,833 : INFO : < 200 OK [3320]
2017-12-31 21:35:51,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 619, '_0n0': 869}
2017-12-31 21:35:51,842 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,848 : INFO : < 200 OK [3322]
2017-12-31 21:35:51,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 619, '_0n0': 791}
2017-12-31 21:35:51,858 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,867 : INFO : < 200 OK [3321]
2017-12-31 21:35:51,872 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 634, '_0n0': 1173}
2017-12-31 21:35:51,877 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:35:51,891 : INFO : < 200 OK [3287]
2017-12-31 21:35:51,897 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:teach]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 634, '_0n0': 979}
2017-12-31 21:35:51,900 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:35:51,907 : INFO : < 200 OK [3277]

In [79]:
for i, row in data.drop_duplicates(subset=['created_by', 'teach_by']).iterrows():
    x = teach_dict[row.teach_by]
    y = institute_dict[row.created_by]
    graph.create(Relationship(x, "from", y))

2017-12-31 21:31:26,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 713, '_0n0': 1223}
2017-12-31 21:31:26,519 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,526 : INFO : < 200 OK [3230]
2017-12-31 21:31:26,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 703, '_0n0': 878}
2017-12-31 21:31:26,534 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,539 : INFO : < 200 OK [3207]
2017-12-31 21:31:26,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 707, '_0n0': 895}
2017-12-31 21:31:26,547 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,552 : INFO : < 200 OK [3212]
2017-12-31 21:31:26,556 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 646, '_0n0': 1208}
2017-12-31 21:31:26,559 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,564 : INFO : < 200 OK [3246]
2017-12-31 21:31:26,567 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 726, '_0n0': 833}
2017-12-31 21:31:26,570 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,575 : INFO : < 200 OK [3199]
2017-12-31 21:31:26,580 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 621, '_0n0': 822}
2017-12-31 21:31:26,583 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,588 : INFO : < 200 OK [3224]
2017-12-31 21:31:26,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 688, '_0n0': 1071}
2017-12-31 21:31:26,596 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,601 : INFO : < 200 OK [3263]
2017-12-31 21:31:26,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 662, '_0n0': 746}
2017-12-31 21:31:26,609 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,615 : INFO : < 200 OK [3211]
2017-12-31 21:31:26,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 646, '_0n0': 1226}
2017-12-31 21:31:26,624 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,630 : INFO : < 200 OK [3243]
2017-12-31 21:31:26,634 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 681, '_0n0': 776}
2017-12-31 21:31:26,638 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,643 : INFO : < 200 OK [3219]
2017-12-31 21:31:26,648 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 717, '_0n0': 958}
2017-12-31 21:31:26,652 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,659 : INFO : < 200 OK [3226]
2017-12-31 21:31:26,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 717, '_0n0': 908}
2017-12-31 21:31:26,667 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,672 : INFO : < 200 OK [3224]
2017-12-31 21:31:26,676 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 717, '_0n0': 866}
2017-12-31 21:31:26,679 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,685 : INFO : < 200 OK [3219]
2017-12-31 21:31:26,689 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 681, '_0n0': 842}
2017-12-31 21:31:26,692 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,697 : INFO : < 200 OK [3219]
2017-12-31 21:31:26,701 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 681, '_0n0': 1127}
2017-12-31 21:31:26,704 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,709 : INFO : < 200 OK [3236]
2017-12-31 21:31:26,713 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 1038}
2017-12-31 21:31:26,716 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,722 : INFO : < 200 OK [3251]
2017-12-31 21:31:26,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 1036}
2017-12-31 21:31:26,729 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,737 : INFO : < 200 OK [3248]
2017-12-31 21:31:26,742 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 713, '_0n0': 1054}
2017-12-31 21:31:26,746 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,752 : INFO : < 200 OK [3231]
2017-12-31 21:31:26,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 702, '_0n0': 779}
2017-12-31 21:31:26,761 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,766 : INFO : < 200 OK [3221]
2017-12-31 21:31:26,771 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 743}
2017-12-31 21:31:26,774 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,780 : INFO : < 200 OK [3218]
2017-12-31 21:31:26,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 646, '_0n0': 798}
2017-12-31 21:31:26,788 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,793 : INFO : < 200 OK [3229]
2017-12-31 21:31:26,798 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 681, '_0n0': 1228}
2017-12-31 21:31:26,800 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,806 : INFO : < 200 OK [3238]
2017-12-31 21:31:26,810 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 873}
2017-12-31 21:31:26,814 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,819 : INFO : < 200 OK [3240]
2017-12-31 21:31:26,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 847}
2017-12-31 21:31:26,828 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,833 : INFO : < 200 OK [3233]

2017-12-31 21:31:26,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 681, '_0n0': 964}
2017-12-31 21:31:26,841 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,846 : INFO : < 200 OK [3220]
2017-12-31 21:31:26,850 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 681, '_0n0': 826}
2017-12-31 21:31:26,853 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,858 : INFO : < 200 OK [3221]
2017-12-31 21:31:26,862 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 646, '_0n0': 1074}
2017-12-31 21:31:26,865 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,870 : INFO : < 200 OK [3237]
2017-12-31 21:31:26,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 689, '_0n0': 773}
2017-12-31 21:31:26,878 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,884 : INFO : < 200 OK [3207]
2017-12-31 21:31:26,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 689, '_0n0': 946}
2017-12-31 21:31:26,894 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,899 : INFO : < 200 OK [3203]
2017-12-31 21:31:26,904 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 644, '_0n0': 1046}
2017-12-31 21:31:26,907 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,913 : INFO : < 200 OK [3237]
2017-12-31 21:31:26,918 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 644, '_0n0': 733}
2017-12-31 21:31:26,920 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,926 : INFO : < 200 OK [3225]
2017-12-31 21:31:26,931 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 621, '_0n0': 1018}
2017-12-31 21:31:26,934 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,939 : INFO : < 200 OK [3237]
2017-12-31 21:31:26,944 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 621, '_0n0': 1156}
2017-12-31 21:31:26,947 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,953 : INFO : < 200 OK [3236]
2017-12-31 21:31:26,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 621, '_0n0': 752}
2017-12-31 21:31:26,962 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,967 : INFO : < 200 OK [3250]
2017-12-31 21:31:26,971 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 621, '_0n0': 802}
2017-12-31 21:31:26,974 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:26,980 : INFO : < 200 OK [3242]
2017-12-31 21:31:26,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 1033}
2017-12-31 21:31:26,988 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:26,993 : INFO : < 200 OK [3246]
2017-12-31 21:31:26,998 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 790}
2017-12-31 21:31:27,001 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,006 : INFO : < 200 OK [3232]
2017-12-31 21:31:27,010 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 713, '_0n0': 1087}
2017-12-31 21:31:27,013 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,019 : INFO : < 200 OK [3225]
2017-12-31 21:31:27,023 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 713, '_0n0': 1186}
2017-12-31 21:31:27,026 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,032 : INFO : < 200 OK [3233]
2017-12-31 21:31:27,037 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 756}
2017-12-31 21:31:27,041 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,048 : INFO : < 200 OK [3210]
2017-12-31 21:31:27,052 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 893}
2017-12-31 21:31:27,054 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,061 : INFO : < 200 OK [3212]
2017-12-31 21:31:27,065 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 689, '_0n0': 1154}
2017-12-31 21:31:27,068 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,074 : INFO : < 200 OK [3218]
2017-12-31 21:31:27,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 689, '_0n0': 972}
2017-12-31 21:31:27,083 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,089 : INFO : < 200 OK [3210]
2017-12-31 21:31:27,095 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 837}
2017-12-31 21:31:27,098 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,105 : INFO : < 200 OK [3218]
2017-12-31 21:31:27,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 689, '_0n0': 1213}
2017-12-31 21:31:27,114 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,119 : INFO : < 200 OK [3222]
2017-12-31 21:31:27,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 702, '_0n0': 788}
2017-12-31 21:31:27,128 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,134 : INFO : < 200 OK [3224]
2017-12-31 21:31:27,138 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 702, '_0n0': 928}
2017-12-31 21:31:27,141 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,147 : INFO : < 200 OK [3222]
2017-12-31 21:31:27,152 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 1042}
2017-12-31 21:31:27,155 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,161 : INFO : < 200 OK [3250]

2017-12-31 21:31:27,166 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 1028}
2017-12-31 21:31:27,169 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,176 : INFO : < 200 OK [3237]
2017-12-31 21:31:27,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 678, '_0n0': 1206}
2017-12-31 21:31:27,184 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,190 : INFO : < 200 OK [3218]
2017-12-31 21:31:27,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 678, '_0n0': 1063}
2017-12-31 21:31:27,198 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,203 : INFO : < 200 OK [3252]
2017-12-31 21:31:27,209 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 678, '_0n0': 1193}
2017-12-31 21:31:27,218 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,224 : INFO : < 200 OK [3252]
2017-12-31 21:31:27,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 713, '_0n0': 1153}
2017-12-31 21:31:27,233 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,238 : INFO : < 200 OK [3225]
2017-12-31 21:31:27,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 713, '_0n0': 901}
2017-12-31 21:31:27,247 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,252 : INFO : < 200 OK [3215]
2017-12-31 21:31:27,257 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 695, '_0n0': 1066}
2017-12-31 21:31:27,261 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,267 : INFO : < 200 OK [3306]
2017-12-31 21:31:27,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 695, '_0n0': 903}
2017-12-31 21:31:27,276 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,282 : INFO : < 200 OK [3284]
2017-12-31 21:31:27,291 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 695, '_0n0': 849}
2017-12-31 21:31:27,297 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,304 : INFO : < 200 OK [3282]
2017-12-31 21:31:27,311 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 695, '_0n0': 863}
2017-12-31 21:31:27,315 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,322 : INFO : < 200 OK [3285]
2017-12-31 21:31:27,328 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 695, '_0n0': 1108}
2017-12-31 21:31:27,332 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,338 : INFO : < 200 OK [3299]
2017-12-31 21:31:27,344 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 703, '_0n0': 782}
2017-12-31 21:31:27,348 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,355 : INFO : < 200 OK [3213]
2017-12-31 21:31:27,361 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 694, '_0n0': 953}
2017-12-31 21:31:27,365 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,372 : INFO : < 200 OK [3206]
2017-12-31 21:31:27,378 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 694, '_0n0': 1096}
2017-12-31 21:31:27,383 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,389 : INFO : < 200 OK [3221]
2017-12-31 21:31:27,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 694, '_0n0': 931}
2017-12-31 21:31:27,400 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,408 : INFO : < 200 OK [3206]
2017-12-31 21:31:27,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 694, '_0n0': 914}
2017-12-31 21:31:27,417 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,423 : INFO : < 200 OK [3204]
2017-12-31 21:31:27,429 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 714, '_0n0': 912}
2017-12-31 21:31:27,434 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,440 : INFO : < 200 OK [3224]
2017-12-31 21:31:27,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 714, '_0n0': 1025}
2017-12-31 21:31:27,450 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,457 : INFO : < 200 OK [3235]
2017-12-31 21:31:27,462 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 869}
2017-12-31 21:31:27,466 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,472 : INFO : < 200 OK [3210]
2017-12-31 21:31:27,478 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 1090}
2017-12-31 21:31:27,482 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,488 : INFO : < 200 OK [3226]
2017-12-31 21:31:27,494 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 740}
2017-12-31 21:31:27,498 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,504 : INFO : < 200 OK [3204]
2017-12-31 21:31:27,511 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 679, '_0n0': 760}
2017-12-31 21:31:27,514 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,521 : INFO : < 200 OK [3224]
2017-12-31 21:31:27,526 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 703, '_0n0': 1199}
2017-12-31 21:31:27,537 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,545 : INFO : < 200 OK [3226]
2017-12-31 21:31:27,551 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 695, '_0n0': 918}
2017-12-31 21:31:27,555 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,562 : INFO : < 200 OK [3289]

2017-12-31 21:31:27,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 682, '_0n0': 907}
2017-12-31 21:31:27,572 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,579 : INFO : < 200 OK [3226]
2017-12-31 21:31:27,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 710, '_0n0': 1048}
2017-12-31 21:31:27,589 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,595 : INFO : < 200 OK [3255]
2017-12-31 21:31:27,601 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 724, '_0n0': 1064}
2017-12-31 21:31:27,605 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,611 : INFO : < 200 OK [3271]
2017-12-31 21:31:27,617 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 724, '_0n0': 844}
2017-12-31 21:31:27,621 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,628 : INFO : < 200 OK [3252]
2017-12-31 21:31:27,633 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 635, '_0n0': 834}
2017-12-31 21:31:27,637 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,643 : INFO : < 200 OK [3223]
2017-12-31 21:31:27,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 863}
2017-12-31 21:31:27,653 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,659 : INFO : < 200 OK [3228]
2017-12-31 21:31:27,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 1190}
2017-12-31 21:31:27,669 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,675 : INFO : < 200 OK [3244]
2017-12-31 21:31:27,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 658, '_0n0': 913}
2017-12-31 21:31:27,683 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,689 : INFO : < 200 OK [3237]
2017-12-31 21:31:27,694 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 658, '_0n0': 1136}
2017-12-31 21:31:27,698 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,704 : INFO : < 200 OK [3241]
2017-12-31 21:31:27,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 694, '_0n0': 952}
2017-12-31 21:31:27,714 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,720 : INFO : < 200 OK [3206]
2017-12-31 21:31:27,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 716, '_0n0': 1181}
2017-12-31 21:31:27,729 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,735 : INFO : < 200 OK [3241]
2017-12-31 21:31:27,742 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 1204}
2017-12-31 21:31:27,746 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,753 : INFO : < 200 OK [3247]
2017-12-31 21:31:27,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 735}
2017-12-31 21:31:27,763 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,769 : INFO : < 200 OK [3224]
2017-12-31 21:31:27,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 870}
2017-12-31 21:31:27,778 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,784 : INFO : < 200 OK [3224]
2017-12-31 21:31:27,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 1015}
2017-12-31 21:31:27,794 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,800 : INFO : < 200 OK [3238]
2017-12-31 21:31:27,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 1132}
2017-12-31 21:31:27,811 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,817 : INFO : < 200 OK [3232]
2017-12-31 21:31:27,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 696, '_0n0': 729}
2017-12-31 21:31:27,826 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,832 : INFO : < 200 OK [3216]
2017-12-31 21:31:27,837 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1129}
2017-12-31 21:31:27,841 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,846 : INFO : < 200 OK [3265]
2017-12-31 21:31:27,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 911}
2017-12-31 21:31:27,855 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,861 : INFO : < 200 OK [3249]
2017-12-31 21:31:27,866 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 644, '_0n0': 792}
2017-12-31 21:31:27,869 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,875 : INFO : < 200 OK [3232]
2017-12-31 21:31:27,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1093}
2017-12-31 21:31:27,884 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,890 : INFO : < 200 OK [3263]
2017-12-31 21:31:27,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1115}
2017-12-31 21:31:27,899 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,906 : INFO : < 200 OK [3262]
2017-12-31 21:31:27,912 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 951}
2017-12-31 21:31:27,916 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,922 : INFO : < 200 OK [3246]
2017-12-31 21:31:27,926 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 781}
2017-12-31 21:31:27,929 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,934 : INFO : < 200 OK [3246]

2017-12-31 21:31:27,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1205}
2017-12-31 21:31:27,940 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,946 : INFO : < 200 OK [3264]
2017-12-31 21:31:27,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 921}
2017-12-31 21:31:27,953 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,959 : INFO : < 200 OK [3236]
2017-12-31 21:31:27,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 736}
2017-12-31 21:31:27,967 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:27,974 : INFO : < 200 OK [3248]
2017-12-31 21:31:27,979 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1035}
2017-12-31 21:31:27,983 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:27,988 : INFO : < 200 OK [3263]
2017-12-31 21:31:27,994 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 816}
2017-12-31 21:31:27,997 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,002 : INFO : < 200 OK [3220]
2017-12-31 21:31:28,007 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 1151}
2017-12-31 21:31:28,010 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,015 : INFO : < 200 OK [3229]
2017-12-31 21:31:28,019 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 716, '_0n0': 949}
2017-12-31 21:31:28,022 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,027 : INFO : < 200 OK [3225]
2017-12-31 21:31:28,032 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 642, '_0n0': 1128}
2017-12-31 21:31:28,035 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,040 : INFO : < 200 OK [3234]
2017-12-31 21:31:28,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1089}
2017-12-31 21:31:28,047 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,052 : INFO : < 200 OK [3267]
2017-12-31 21:31:28,056 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1062}
2017-12-31 21:31:28,059 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,065 : INFO : < 200 OK [3265]
2017-12-31 21:31:28,071 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 801}
2017-12-31 21:31:28,076 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,081 : INFO : < 200 OK [3228]
2017-12-31 21:31:28,086 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 660, '_0n0': 1111}
2017-12-31 21:31:28,089 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,095 : INFO : < 200 OK [3231]
2017-12-31 21:31:28,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 710, '_0n0': 1167}
2017-12-31 21:31:28,103 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,109 : INFO : < 200 OK [3251]
2017-12-31 21:31:28,114 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 710, '_0n0': 744}
2017-12-31 21:31:28,117 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,122 : INFO : < 200 OK [3237]
2017-12-31 21:31:28,127 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 1248}
2017-12-31 21:31:28,130 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,135 : INFO : < 200 OK [3240]
2017-12-31 21:31:28,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 701, '_0n0': 1079}
2017-12-31 21:31:28,142 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,147 : INFO : < 200 OK [3220]
2017-12-31 21:31:28,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 701, '_0n0': 1076}
2017-12-31 21:31:28,154 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,159 : INFO : < 200 OK [3222]
2017-12-31 21:31:28,164 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 701, '_0n0': 819}
2017-12-31 21:31:28,167 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,172 : INFO : < 200 OK [3207]
2017-12-31 21:31:28,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 712, '_0n0': 813}
2017-12-31 21:31:28,180 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,186 : INFO : < 200 OK [3230]
2017-12-31 21:31:28,191 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 923}
2017-12-31 21:31:28,194 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,199 : INFO : < 200 OK [3219]
2017-12-31 21:31:28,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 815}
2017-12-31 21:31:28,206 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,212 : INFO : < 200 OK [3217]
2017-12-31 21:31:28,217 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 713, '_0n0': 761}
2017-12-31 21:31:28,220 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,225 : INFO : < 200 OK [3215]
2017-12-31 21:31:28,230 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 682, '_0n0': 1139}
2017-12-31 21:31:28,234 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,239 : INFO : < 200 OK [3244]
2017-12-31 21:31:28,243 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 676, '_0n0': 1086}
2017-12-31 21:31:28,245 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,250 : INFO : < 200 OK [3240]

2017-12-31 21:31:28,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1122}
2017-12-31 21:31:28,257 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,262 : INFO : < 200 OK [3233]
2017-12-31 21:31:28,266 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 716, '_0n0': 1215}
2017-12-31 21:31:28,268 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,274 : INFO : < 200 OK [3238]
2017-12-31 21:31:28,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 686, '_0n0': 809}
2017-12-31 21:31:28,283 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,290 : INFO : < 200 OK [3211]
2017-12-31 21:31:28,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 1140}
2017-12-31 21:31:28,299 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,305 : INFO : < 200 OK [3243]
2017-12-31 21:31:28,309 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 655, '_0n0': 787}
2017-12-31 21:31:28,313 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,318 : INFO : < 200 OK [3215]
2017-12-31 21:31:28,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 655, '_0n0': 1100}
2017-12-31 21:31:28,327 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,332 : INFO : < 200 OK [3226]
2017-12-31 21:31:28,337 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 655, '_0n0': 1120}
2017-12-31 21:31:28,339 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,345 : INFO : < 200 OK [3228]
2017-12-31 21:31:28,349 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 655, '_0n0': 944}
2017-12-31 21:31:28,352 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,357 : INFO : < 200 OK [3217]
2017-12-31 21:31:28,362 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 655, '_0n0': 961}
2017-12-31 21:31:28,365 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,370 : INFO : < 200 OK [3218]
2017-12-31 21:31:28,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 712, '_0n0': 1239}
2017-12-31 21:31:28,377 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,383 : INFO : < 200 OK [3238]
2017-12-31 21:31:28,388 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 664, '_0n0': 1145}
2017-12-31 21:31:28,391 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,397 : INFO : < 200 OK [3220]
2017-12-31 21:31:28,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 698, '_0n0': 753}
2017-12-31 21:31:28,407 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,413 : INFO : < 200 OK [3210]
2017-12-31 21:31:28,418 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 691, '_0n0': 797}
2017-12-31 21:31:28,422 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,428 : INFO : < 200 OK [3229]
2017-12-31 21:31:28,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 691, '_0n0': 942}
2017-12-31 21:31:28,435 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,441 : INFO : < 200 OK [3234]
2017-12-31 21:31:28,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 691, '_0n0': 947}
2017-12-31 21:31:28,449 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,455 : INFO : < 200 OK [3225]
2017-12-31 21:31:28,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 691, '_0n0': 973}
2017-12-31 21:31:28,463 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,468 : INFO : < 200 OK [3225]
2017-12-31 21:31:28,472 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 691, '_0n0': 1150}
2017-12-31 21:31:28,475 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,480 : INFO : < 200 OK [3249]
2017-12-31 21:31:28,485 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 691, '_0n0': 758}
2017-12-31 21:31:28,488 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,493 : INFO : < 200 OK [3227]
2017-12-31 21:31:28,497 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 691, '_0n0': 957}
2017-12-31 21:31:28,500 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,506 : INFO : < 200 OK [3235]
2017-12-31 21:31:28,510 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 712, '_0n0': 874}
2017-12-31 21:31:28,513 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,518 : INFO : < 200 OK [3224]
2017-12-31 21:31:28,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 656, '_0n0': 1198}
2017-12-31 21:31:28,526 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,531 : INFO : < 200 OK [3268]
2017-12-31 21:31:28,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 656, '_0n0': 1116}
2017-12-31 21:31:28,539 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,545 : INFO : < 200 OK [3264]
2017-12-31 21:31:28,550 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 689, '_0n0': 943}
2017-12-31 21:31:28,555 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,561 : INFO : < 200 OK [3206]
2017-12-31 21:31:28,565 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 712, '_0n0': 1246}
2017-12-31 21:31:28,568 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,573 : INFO : < 200 OK [3237]

2017-12-31 21:31:28,578 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 681, '_0n0': 1073}
2017-12-31 21:31:28,582 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,587 : INFO : < 200 OK [3238]
2017-12-31 21:31:28,592 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 888}
2017-12-31 21:31:28,595 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,600 : INFO : < 200 OK [3231]
2017-12-31 21:31:28,604 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 1196}
2017-12-31 21:31:28,608 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,614 : INFO : < 200 OK [3245]
2017-12-31 21:31:28,618 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 648, '_0n0': 979}
2017-12-31 21:31:28,621 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,627 : INFO : < 200 OK [3219]
2017-12-31 21:31:28,631 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 712, '_0n0': 1061}
2017-12-31 21:31:28,635 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,640 : INFO : < 200 OK [3245]
2017-12-31 21:31:28,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 712, '_0n0': 1158}
2017-12-31 21:31:28,649 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,654 : INFO : < 200 OK [3244]
2017-12-31 21:31:28,658 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 960}
2017-12-31 21:31:28,661 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,666 : INFO : < 200 OK [3248]
2017-12-31 21:31:28,671 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 682, '_0n0': 1227}
2017-12-31 21:31:28,674 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,679 : INFO : < 200 OK [3244]
2017-12-31 21:31:28,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 682, '_0n0': 1080}
2017-12-31 21:31:28,686 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,693 : INFO : < 200 OK [3255]
2017-12-31 21:31:28,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 845}
2017-12-31 21:31:28,701 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,707 : INFO : < 200 OK [3240]
2017-12-31 21:31:28,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 716, '_0n0': 1125}
2017-12-31 21:31:28,714 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,719 : INFO : < 200 OK [3236]
2017-12-31 21:31:28,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 1050}
2017-12-31 21:31:28,727 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,731 : INFO : < 200 OK [3244]
2017-12-31 21:31:28,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 808}
2017-12-31 21:31:28,739 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,744 : INFO : < 200 OK [3228]
2017-12-31 21:31:28,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 965}
2017-12-31 21:31:28,752 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,757 : INFO : < 200 OK [3239]
2017-12-31 21:31:28,762 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 1178}
2017-12-31 21:31:28,766 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,772 : INFO : < 200 OK [3246]
2017-12-31 21:31:28,778 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 1103}
2017-12-31 21:31:28,781 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,787 : INFO : < 200 OK [3247]
2017-12-31 21:31:28,793 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 930}
2017-12-31 21:31:28,795 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,801 : INFO : < 200 OK [3230]
2017-12-31 21:31:28,805 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 865}
2017-12-31 21:31:28,809 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,816 : INFO : < 200 OK [3238]
2017-12-31 21:31:28,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 823}
2017-12-31 21:31:28,824 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,829 : INFO : < 200 OK [3241]
2017-12-31 21:31:28,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 968}
2017-12-31 21:31:28,837 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,842 : INFO : < 200 OK [3234]
2017-12-31 21:31:28,846 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 800}
2017-12-31 21:31:28,849 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,854 : INFO : < 200 OK [3230]
2017-12-31 21:31:28,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 886}
2017-12-31 21:31:28,862 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,867 : INFO : < 200 OK [3233]
2017-12-31 21:31:28,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 962}
2017-12-31 21:31:28,875 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,880 : INFO : < 200 OK [3231]
2017-12-31 21:31:28,885 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 775}
2017-12-31 21:31:28,888 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,893 : INFO : < 200 OK [3236]

2017-12-31 21:31:28,897 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 916}
2017-12-31 21:31:28,900 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,905 : INFO : < 200 OK [3248]
2017-12-31 21:31:28,909 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 636, '_0n0': 929}
2017-12-31 21:31:28,912 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,917 : INFO : < 200 OK [3231]
2017-12-31 21:31:28,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 716, '_0n0': 860}
2017-12-31 21:31:28,924 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,929 : INFO : < 200 OK [3232]
2017-12-31 21:31:28,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 682, '_0n0': 1164}
2017-12-31 21:31:28,937 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,941 : INFO : < 200 OK [3243]
2017-12-31 21:31:28,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 682, '_0n0': 858}
2017-12-31 21:31:28,948 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,953 : INFO : < 200 OK [3235]
2017-12-31 21:31:28,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 639, '_0n0': 933}
2017-12-31 21:31:28,961 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:28,967 : INFO : < 200 OK [3241]
2017-12-31 21:31:28,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 639, '_0n0': 1041}
2017-12-31 21:31:28,977 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,982 : INFO : < 200 OK [3270]
2017-12-31 21:31:28,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 659, '_0n0': 1169}
2017-12-31 21:31:28,991 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:28,996 : INFO : < 200 OK [3230]
2017-12-31 21:31:29,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 659, '_0n0': 899}
2017-12-31 21:31:29,004 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,009 : INFO : < 200 OK [3217]
2017-12-31 21:31:29,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 700, '_0n0': 774}
2017-12-31 21:31:29,017 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,022 : INFO : < 200 OK [3217]
2017-12-31 21:31:29,027 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 700, '_0n0': 1203}
2017-12-31 21:31:29,030 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,036 : INFO : < 200 OK [3235]
2017-12-31 21:31:29,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 700, '_0n0': 1149}
2017-12-31 21:31:29,043 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,049 : INFO : < 200 OK [3231]
2017-12-31 21:31:29,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 700, '_0n0': 1083}
2017-12-31 21:31:29,057 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,062 : INFO : < 200 OK [3237]
2017-12-31 21:31:29,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 700, '_0n0': 1055}
2017-12-31 21:31:29,068 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,073 : INFO : < 200 OK [3239]
2017-12-31 21:31:29,078 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 662, '_0n0': 976}
2017-12-31 21:31:29,081 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,087 : INFO : < 200 OK [3214]
2017-12-31 21:31:29,091 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 662, '_0n0': 772}
2017-12-31 21:31:29,094 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,099 : INFO : < 200 OK [3210]
2017-12-31 21:31:29,103 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 662, '_0n0': 838}
2017-12-31 21:31:29,106 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,111 : INFO : < 200 OK [3216]
2017-12-31 21:31:29,116 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 662, '_0n0': 969}
2017-12-31 21:31:29,120 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,125 : INFO : < 200 OK [3208]
2017-12-31 21:31:29,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 662, '_0n0': 835}
2017-12-31 21:31:29,133 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,138 : INFO : < 200 OK [3212]
2017-12-31 21:31:29,142 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 622, '_0n0': 890}
2017-12-31 21:31:29,145 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,151 : INFO : < 200 OK [3213]
2017-12-31 21:31:29,156 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 674, '_0n0': 821}
2017-12-31 21:31:29,159 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,164 : INFO : < 200 OK [3246]
2017-12-31 21:31:29,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 716, '_0n0': 1091}
2017-12-31 21:31:29,171 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,176 : INFO : < 200 OK [3245]
2017-12-31 21:31:29,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 716, '_0n0': 1124}
2017-12-31 21:31:29,184 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,190 : INFO : < 200 OK [3246]
2017-12-31 21:31:29,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 694, '_0n0': 910}
2017-12-31 21:31:29,198 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,204 : INFO : < 200 OK [3210]

2017-12-31 21:31:29,209 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 689, '_0n0': 1030}
2017-12-31 21:31:29,212 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,217 : INFO : < 200 OK [3232]
2017-12-31 21:31:29,222 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 689, '_0n0': 1142}
2017-12-31 21:31:29,225 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,231 : INFO : < 200 OK [3220]
2017-12-31 21:31:29,236 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 1065}
2017-12-31 21:31:29,239 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,244 : INFO : < 200 OK [3227]
2017-12-31 21:31:29,249 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 722, '_0n0': 1126}
2017-12-31 21:31:29,252 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,257 : INFO : < 200 OK [3247]
2017-12-31 21:31:29,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 703, '_0n0': 804}
2017-12-31 21:31:29,265 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,269 : INFO : < 200 OK [3218]
2017-12-31 21:31:29,274 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 640, '_0n0': 1057}
2017-12-31 21:31:29,277 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,283 : INFO : < 200 OK [3271]
2017-12-31 21:31:29,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 640, '_0n0': 1045}
2017-12-31 21:31:29,290 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,296 : INFO : < 200 OK [3271]
2017-12-31 21:31:29,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 640, '_0n0': 1241}
2017-12-31 21:31:29,303 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,308 : INFO : < 200 OK [3264]
2017-12-31 21:31:29,312 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 1170}
2017-12-31 21:31:29,314 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,319 : INFO : < 200 OK [3225]
2017-12-31 21:31:29,324 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 846}
2017-12-31 21:31:29,327 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,332 : INFO : < 200 OK [3210]
2017-12-31 21:31:29,337 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 672, '_0n0': 1155}
2017-12-31 21:31:29,341 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,350 : INFO : < 200 OK [3238]
2017-12-31 21:31:29,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 703, '_0n0': 1019}
2017-12-31 21:31:29,359 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,367 : INFO : < 200 OK [3235]
2017-12-31 21:31:29,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 682, '_0n0': 1084}
2017-12-31 21:31:29,378 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,385 : INFO : < 200 OK [3248]
2017-12-31 21:31:29,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 732, '_0n0': 1016}
2017-12-31 21:31:29,395 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,401 : INFO : < 200 OK [3245]
2017-12-31 21:31:29,407 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 702, '_0n0': 1143}
2017-12-31 21:31:29,412 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,417 : INFO : < 200 OK [3249]
2017-12-31 21:31:29,422 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 702, '_0n0': 956}
2017-12-31 21:31:29,426 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,432 : INFO : < 200 OK [3238]
2017-12-31 21:31:29,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 708, '_0n0': 1189}
2017-12-31 21:31:29,440 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,446 : INFO : < 200 OK [3245]
2017-12-31 21:31:29,450 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 708, '_0n0': 831}
2017-12-31 21:31:29,454 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,460 : INFO : < 200 OK [3226]
2017-12-31 21:31:29,465 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 708, '_0n0': 875}
2017-12-31 21:31:29,468 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,474 : INFO : < 200 OK [3229]
2017-12-31 21:31:29,478 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 708, '_0n0': 927}
2017-12-31 21:31:29,482 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,488 : INFO : < 200 OK [3221]
2017-12-31 21:31:29,493 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 708, '_0n0': 1137}
2017-12-31 21:31:29,497 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,502 : INFO : < 200 OK [3238]
2017-12-31 21:31:29,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 708, '_0n0': 885}
2017-12-31 21:31:29,511 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,517 : INFO : < 200 OK [3225]
2017-12-31 21:31:29,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 708, '_0n0': 1021}
2017-12-31 21:31:29,525 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,530 : INFO : < 200 OK [3235]
2017-12-31 21:31:29,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 708, '_0n0': 1060}
2017-12-31 21:31:29,538 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,544 : INFO : < 200 OK [3243]

2017-12-31 21:31:29,548 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 708, '_0n0': 1232}
2017-12-31 21:31:29,552 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,558 : INFO : < 200 OK [3244]
2017-12-31 21:31:29,562 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 732, '_0n0': 1233}
2017-12-31 21:31:29,565 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,571 : INFO : < 200 OK [3248]
2017-12-31 21:31:29,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 932}
2017-12-31 21:31:29,579 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,584 : INFO : < 200 OK [3220]
2017-12-31 21:31:29,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 674, '_0n0': 862}
2017-12-31 21:31:29,593 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,598 : INFO : < 200 OK [3247]
2017-12-31 21:31:29,603 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 757}
2017-12-31 21:31:29,606 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,612 : INFO : < 200 OK [3222]
2017-12-31 21:31:29,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 684, '_0n0': 1180}
2017-12-31 21:31:29,621 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,626 : INFO : < 200 OK [3241]
2017-12-31 21:31:29,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 1088}
2017-12-31 21:31:29,636 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,644 : INFO : < 200 OK [3229]
2017-12-31 21:31:29,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 978}
2017-12-31 21:31:29,652 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,658 : INFO : < 200 OK [3223]
2017-12-31 21:31:29,663 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 734}
2017-12-31 21:31:29,666 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,672 : INFO : < 200 OK [3251]
2017-12-31 21:31:29,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 710, '_0n0': 749}
2017-12-31 21:31:29,681 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,686 : INFO : < 200 OK [3242]
2017-12-31 21:31:29,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 793}
2017-12-31 21:31:29,695 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,701 : INFO : < 200 OK [3218]
2017-12-31 21:31:29,706 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 879}
2017-12-31 21:31:29,710 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,715 : INFO : < 200 OK [3226]
2017-12-31 21:31:29,720 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1039}
2017-12-31 21:31:29,723 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,728 : INFO : < 200 OK [3234]
2017-12-31 21:31:29,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 966}
2017-12-31 21:31:29,736 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,741 : INFO : < 200 OK [3219]
2017-12-31 21:31:29,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 649, '_0n0': 1082}
2017-12-31 21:31:29,748 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,753 : INFO : < 200 OK [3266]
2017-12-31 21:31:29,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 718, '_0n0': 830}
2017-12-31 21:31:29,761 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,766 : INFO : < 200 OK [3220]
2017-12-31 21:31:29,770 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 718, '_0n0': 805}
2017-12-31 21:31:29,774 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,779 : INFO : < 200 OK [3218]
2017-12-31 21:31:29,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 786}
2017-12-31 21:31:29,789 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,797 : INFO : < 200 OK [3254]
2017-12-31 21:31:29,802 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 709, '_0n0': 1191}
2017-12-31 21:31:29,806 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,812 : INFO : < 200 OK [3287]
2017-12-31 21:31:29,817 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 709, '_0n0': 778}
2017-12-31 21:31:29,820 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,826 : INFO : < 200 OK [3269]
2017-12-31 21:31:29,830 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 936}
2017-12-31 21:31:29,834 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,839 : INFO : < 200 OK [3216]
2017-12-31 21:31:29,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1182}
2017-12-31 21:31:29,847 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,853 : INFO : < 200 OK [3244]
2017-12-31 21:31:29,857 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 682, '_0n0': 814}
2017-12-31 21:31:29,859 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,865 : INFO : < 200 OK [3236]
2017-12-31 21:31:29,869 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 857}
2017-12-31 21:31:29,872 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,878 : INFO : < 200 OK [3252]

2017-12-31 21:31:29,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 621, '_0n0': 1247}
2017-12-31 21:31:29,885 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,890 : INFO : < 200 OK [3249]
2017-12-31 21:31:29,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 621, '_0n0': 1187}
2017-12-31 21:31:29,898 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,903 : INFO : < 200 OK [3241]
2017-12-31 21:31:29,907 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 621, '_0n0': 1068}
2017-12-31 21:31:29,911 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,916 : INFO : < 200 OK [3244]
2017-12-31 21:31:29,920 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 621, '_0n0': 1202}
2017-12-31 21:31:29,923 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,929 : INFO : < 200 OK [3242]
2017-12-31 21:31:29,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 682, '_0n0': 824}
2017-12-31 21:31:29,937 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,942 : INFO : < 200 OK [3229]
2017-12-31 21:31:29,946 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 852}
2017-12-31 21:31:29,949 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,954 : INFO : < 200 OK [3254]
2017-12-31 21:31:29,959 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 661, '_0n0': 1229}
2017-12-31 21:31:29,961 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,966 : INFO : < 200 OK [3252]
2017-12-31 21:31:29,970 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 717, '_0n0': 855}
2017-12-31 21:31:29,972 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:29,977 : INFO : < 200 OK [3220]
2017-12-31 21:31:29,983 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1114}
2017-12-31 21:31:29,988 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:29,994 : INFO : < 200 OK [3236]
2017-12-31 21:31:30,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 876}
2017-12-31 21:31:30,004 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,011 : INFO : < 200 OK [3228]
2017-12-31 21:31:30,015 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 704, '_0n0': 737}
2017-12-31 21:31:30,018 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,024 : INFO : < 200 OK [3219]
2017-12-31 21:31:30,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 704, '_0n0': 940}
2017-12-31 21:31:30,032 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,037 : INFO : < 200 OK [3214]
2017-12-31 21:31:30,042 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 791}
2017-12-31 21:31:30,045 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,050 : INFO : < 200 OK [3213]
2017-12-31 21:31:30,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 1152}
2017-12-31 21:31:30,058 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,063 : INFO : < 200 OK [3226]
2017-12-31 21:31:30,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 856}
2017-12-31 21:31:30,069 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,075 : INFO : < 200 OK [3212]
2017-12-31 21:31:30,079 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 644, '_0n0': 747}
2017-12-31 21:31:30,082 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,087 : INFO : < 200 OK [3241]
2017-12-31 21:31:30,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 644, '_0n0': 1106}
2017-12-31 21:31:30,095 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,100 : INFO : < 200 OK [3244]
2017-12-31 21:31:30,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 649, '_0n0': 854}
2017-12-31 21:31:30,108 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,113 : INFO : < 200 OK [3250]
2017-12-31 21:31:30,117 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 692, '_0n0': 859}
2017-12-31 21:31:30,120 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,125 : INFO : < 200 OK [3220]
2017-12-31 21:31:30,129 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 651, '_0n0': 909}
2017-12-31 21:31:30,132 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,137 : INFO : < 200 OK [3218]
2017-12-31 21:31:30,141 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 651, '_0n0': 1032}
2017-12-31 21:31:30,144 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,148 : INFO : < 200 OK [3239]
2017-12-31 21:31:30,153 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 651, '_0n0': 920}
2017-12-31 21:31:30,157 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,163 : INFO : < 200 OK [3218]
2017-12-31 21:31:30,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 651, '_0n0': 841}
2017-12-31 21:31:30,171 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,177 : INFO : < 200 OK [3226]
2017-12-31 21:31:30,182 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 722, '_0n0': 1104}
2017-12-31 21:31:30,184 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,189 : INFO : < 200 OK [3243]

2017-12-31 21:31:30,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 646, '_0n0': 954}
2017-12-31 21:31:30,197 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,202 : INFO : < 200 OK [3234]
2017-12-31 21:31:30,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 656, '_0n0': 759}
2017-12-31 21:31:30,209 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,215 : INFO : < 200 OK [3256]
2017-12-31 21:31:30,220 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 656, '_0n0': 1183}
2017-12-31 21:31:30,224 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,229 : INFO : < 200 OK [3266]
2017-12-31 21:31:30,234 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 924}
2017-12-31 21:31:30,237 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,242 : INFO : < 200 OK [3220]
2017-12-31 21:31:30,246 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 682, '_0n0': 884}
2017-12-31 21:31:30,249 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,254 : INFO : < 200 OK [3234]
2017-12-31 21:31:30,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 663, '_0n0': 777}
2017-12-31 21:31:30,261 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,266 : INFO : < 200 OK [3220]
2017-12-31 21:31:30,270 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 663, '_0n0': 1059}
2017-12-31 21:31:30,273 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,278 : INFO : < 200 OK [3244]
2017-12-31 21:31:30,282 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 649, '_0n0': 1138}
2017-12-31 21:31:30,285 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,291 : INFO : < 200 OK [3265]
2017-12-31 21:31:30,297 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 645, '_0n0': 1218}
2017-12-31 21:31:30,300 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,307 : INFO : < 200 OK [3232]
2017-12-31 21:31:30,312 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 656, '_0n0': 1131}
2017-12-31 21:31:30,315 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,322 : INFO : < 200 OK [3268]
2017-12-31 21:31:30,329 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 651, '_0n0': 840}
2017-12-31 21:31:30,332 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,338 : INFO : < 200 OK [3222]
2017-12-31 21:31:30,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 655, '_0n0': 811}
2017-12-31 21:31:30,346 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,352 : INFO : < 200 OK [3220]
2017-12-31 21:31:30,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 864}
2017-12-31 21:31:30,359 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,364 : INFO : < 200 OK [3222]
2017-12-31 21:31:30,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 620, '_0n0': 1192}
2017-12-31 21:31:30,371 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,376 : INFO : < 200 OK [3237]
2017-12-31 21:31:30,380 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 702, '_0n0': 894}
2017-12-31 21:31:30,384 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,388 : INFO : < 200 OK [3238]
2017-12-31 21:31:30,393 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 702, '_0n0': 1020}
2017-12-31 21:31:30,396 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,401 : INFO : < 200 OK [3242]
2017-12-31 21:31:30,406 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 702, '_0n0': 950}
2017-12-31 21:31:30,410 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,416 : INFO : < 200 OK [3230]
2017-12-31 21:31:30,422 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 641, '_0n0': 880}
2017-12-31 21:31:30,427 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,431 : INFO : < 200 OK [3241]
2017-12-31 21:31:30,436 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 641, '_0n0': 1240}
2017-12-31 21:31:30,439 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,445 : INFO : < 200 OK [3264]
2017-12-31 21:31:30,449 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 1172}
2017-12-31 21:31:30,452 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,458 : INFO : < 200 OK [3234]
2017-12-31 21:31:30,462 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 656, '_0n0': 1098}
2017-12-31 21:31:30,465 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,471 : INFO : < 200 OK [3271]
2017-12-31 21:31:30,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 700, '_0n0': 1024}
2017-12-31 21:31:30,480 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,485 : INFO : < 200 OK [3234]
2017-12-31 21:31:30,490 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 700, '_0n0': 1113}
2017-12-31 21:31:30,493 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,499 : INFO : < 200 OK [3237]
2017-12-31 21:31:30,503 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 700, '_0n0': 1101}
2017-12-31 21:31:30,506 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,512 : INFO : < 200 OK [3235]

2017-12-31 21:31:30,516 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 829}
2017-12-31 21:31:30,519 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,525 : INFO : < 200 OK [3225]
2017-12-31 21:31:30,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 971}
2017-12-31 21:31:30,532 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,537 : INFO : < 200 OK [3220]
2017-12-31 21:31:30,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 680, '_0n0': 1017}
2017-12-31 21:31:30,546 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,553 : INFO : < 200 OK [3238]
2017-12-31 21:31:30,559 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 680, '_0n0': 935}
2017-12-31 21:31:30,562 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,568 : INFO : < 200 OK [3220]
2017-12-31 21:31:30,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 692, '_0n0': 1166}
2017-12-31 21:31:30,576 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,581 : INFO : < 200 OK [3231]
2017-12-31 21:31:30,586 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 692, '_0n0': 1067}
2017-12-31 21:31:30,589 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,594 : INFO : < 200 OK [3237]
2017-12-31 21:31:30,598 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 867}
2017-12-31 21:31:30,600 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,606 : INFO : < 200 OK [3237]
2017-12-31 21:31:30,610 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 1220}
2017-12-31 21:31:30,613 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,618 : INFO : < 200 OK [3224]
2017-12-31 21:31:30,623 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 1081}
2017-12-31 21:31:30,626 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,631 : INFO : < 200 OK [3226]
2017-12-31 21:31:30,637 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 803}
2017-12-31 21:31:30,640 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,647 : INFO : < 200 OK [3213]
2017-12-31 21:31:30,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 731, '_0n0': 970}
2017-12-31 21:31:30,654 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,660 : INFO : < 200 OK [3230]
2017-12-31 21:31:30,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 827}
2017-12-31 21:31:30,667 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,673 : INFO : < 200 OK [3229]
2017-12-31 21:31:30,678 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 637, '_0n0': 941}
2017-12-31 21:31:30,682 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,687 : INFO : < 200 OK [3218]
2017-12-31 21:31:30,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 807}
2017-12-31 21:31:30,695 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,701 : INFO : < 200 OK [3229]
2017-12-31 21:31:30,705 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 680, '_0n0': 915}
2017-12-31 21:31:30,708 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,714 : INFO : < 200 OK [3229]
2017-12-31 21:31:30,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 687, '_0n0': 742}
2017-12-31 21:31:30,721 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,727 : INFO : < 200 OK [3212]
2017-12-31 21:31:30,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 684, '_0n0': 1224}
2017-12-31 21:31:30,734 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,739 : INFO : < 200 OK [3225]
2017-12-31 21:31:30,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 684, '_0n0': 1092}
2017-12-31 21:31:30,746 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,750 : INFO : < 200 OK [3229]
2017-12-31 21:31:30,754 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 721, '_0n0': 872}
2017-12-31 21:31:30,757 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,762 : INFO : < 200 OK [3218]
2017-12-31 21:31:30,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 1209}
2017-12-31 21:31:30,770 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,775 : INFO : < 200 OK [3233]
2017-12-31 21:31:30,778 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 820}
2017-12-31 21:31:30,781 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,786 : INFO : < 200 OK [3248]
2017-12-31 21:31:30,792 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 708, '_0n0': 1168}
2017-12-31 21:31:30,795 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,802 : INFO : < 200 OK [3243]
2017-12-31 21:31:30,808 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 708, '_0n0': 897}
2017-12-31 21:31:30,811 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,816 : INFO : < 200 OK [3223]
2017-12-31 21:31:30,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 703, '_0n0': 1206}
2017-12-31 21:31:30,827 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,832 : INFO : < 200 OK [3226]

2017-12-31 21:31:30,836 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 645, '_0n0': 1109}
2017-12-31 21:31:30,839 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,845 : INFO : < 200 OK [3234]
2017-12-31 21:31:30,849 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1160}
2017-12-31 21:31:30,852 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,857 : INFO : < 200 OK [3267]
2017-12-31 21:31:30,862 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1230}
2017-12-31 21:31:30,865 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,870 : INFO : < 200 OK [3272]
2017-12-31 21:31:30,874 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 741}
2017-12-31 21:31:30,877 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,882 : INFO : < 200 OK [3251]
2017-12-31 21:31:30,886 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1195}
2017-12-31 21:31:30,888 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,893 : INFO : < 200 OK [3267]
2017-12-31 21:31:30,898 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1179}
2017-12-31 21:31:30,900 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:30,906 : INFO : < 200 OK [3270]
2017-12-31 21:31:30,910 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 892}
2017-12-31 21:31:30,913 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:30,918 : INFO : < 200 OK [3254]
2017-12-31 21:31:30,923 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 728}
2017-12-31 21:31:30,926 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,063 : INFO : < 200 OK [3253]
2017-12-31 21:31:31,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 1072}
2017-12-31 21:31:31,069 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,075 : INFO : < 200 OK [3271]
2017-12-31 21:31:31,079 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 785}
2017-12-31 21:31:31,082 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,087 : INFO : < 200 OK [3256]
2017-12-31 21:31:31,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 653, '_0n0': 817}
2017-12-31 21:31:31,096 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,103 : INFO : < 200 OK [3255]
2017-12-31 21:31:31,108 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 692, '_0n0': 799}
2017-12-31 21:31:31,111 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,117 : INFO : < 200 OK [3223]
2017-12-31 21:31:31,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 692, '_0n0': 843}
2017-12-31 21:31:31,126 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,131 : INFO : < 200 OK [3224]
2017-12-31 21:31:31,136 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 1110}
2017-12-31 21:31:31,139 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,145 : INFO : < 200 OK [3232]
2017-12-31 21:31:31,150 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 665, '_0n0': 1077}
2017-12-31 21:31:31,153 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,158 : INFO : < 200 OK [3212]
2017-12-31 21:31:31,163 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 665, '_0n0': 1094}
2017-12-31 21:31:31,167 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,172 : INFO : < 200 OK [3224]
2017-12-31 21:31:31,176 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 1161}
2017-12-31 21:31:31,179 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,184 : INFO : < 200 OK [3243]
2017-12-31 21:31:31,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 748}
2017-12-31 21:31:31,192 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,198 : INFO : < 200 OK [3232]
2017-12-31 21:31:31,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 727}
2017-12-31 21:31:31,205 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,210 : INFO : < 200 OK [3240]
2017-12-31 21:31:31,214 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 655, '_0n0': 1037}
2017-12-31 21:31:31,217 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,222 : INFO : < 200 OK [3240]
2017-12-31 21:31:31,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 643, '_0n0': 1210}
2017-12-31 21:31:31,230 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,236 : INFO : < 200 OK [3224]
2017-12-31 21:31:31,241 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 643, '_0n0': 1245}
2017-12-31 21:31:31,245 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,251 : INFO : < 200 OK [3220]
2017-12-31 21:31:31,256 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 643, '_0n0': 1207}
2017-12-31 21:31:31,261 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,266 : INFO : < 200 OK [3215]
2017-12-31 21:31:31,272 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 643, '_0n0': 1219}
2017-12-31 21:31:31,276 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,281 : INFO : < 200 OK [3218]

2017-12-31 21:31:31,286 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 643, '_0n0': 1225}
2017-12-31 21:31:31,289 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,295 : INFO : < 200 OK [3217]
2017-12-31 21:31:31,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 643, '_0n0': 1085}
2017-12-31 21:31:31,303 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,309 : INFO : < 200 OK [3217]
2017-12-31 21:31:31,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 623, '_0n0': 853}
2017-12-31 21:31:31,316 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,321 : INFO : < 200 OK [3236]
2017-12-31 21:31:31,326 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 719, '_0n0': 861}
2017-12-31 21:31:31,330 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,335 : INFO : < 200 OK [3249]
2017-12-31 21:31:31,338 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 719, '_0n0': 836}
2017-12-31 21:31:31,341 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,346 : INFO : < 200 OK [3247]
2017-12-31 21:31:31,350 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 719, '_0n0': 794}
2017-12-31 21:31:31,353 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,358 : INFO : < 200 OK [3249]
2017-12-31 21:31:31,362 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 719, '_0n0': 812}
2017-12-31 21:31:31,364 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,369 : INFO : < 200 OK [3247]
2017-12-31 21:31:31,373 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 719, '_0n0': 1044}
2017-12-31 21:31:31,376 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,382 : INFO : < 200 OK [3270]
2017-12-31 21:31:31,386 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 719, '_0n0': 882}
2017-12-31 21:31:31,389 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,395 : INFO : < 200 OK [3246]
2017-12-31 21:31:31,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 643, '_0n0': 1105}
2017-12-31 21:31:31,404 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,410 : INFO : < 200 OK [3220]
2017-12-31 21:31:31,414 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 715, '_0n0': 906}
2017-12-31 21:31:31,417 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,423 : INFO : < 200 OK [3199]
2017-12-31 21:31:31,429 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 745}
2017-12-31 21:31:31,432 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,437 : INFO : < 200 OK [3232]
2017-12-31 21:31:31,441 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 1214}
2017-12-31 21:31:31,445 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,450 : INFO : < 200 OK [3242]
2017-12-31 21:31:31,454 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 725, '_0n0': 780}
2017-12-31 21:31:31,458 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,463 : INFO : < 200 OK [3219]
2017-12-31 21:31:31,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 783}
2017-12-31 21:31:31,470 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,476 : INFO : < 200 OK [3222]
2017-12-31 21:31:31,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 720, '_0n0': 1119}
2017-12-31 21:31:31,483 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,488 : INFO : < 200 OK [3230]
2017-12-31 21:31:31,492 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 1049}
2017-12-31 21:31:31,495 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,500 : INFO : < 200 OK [3242]
2017-12-31 21:31:31,504 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 694, '_0n0': 1107}
2017-12-31 21:31:31,507 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,512 : INFO : < 200 OK [3225]
2017-12-31 21:31:31,516 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 900}
2017-12-31 21:31:31,519 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,525 : INFO : < 200 OK [3225]
2017-12-31 21:31:31,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 825}
2017-12-31 21:31:31,534 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,540 : INFO : < 200 OK [3221]
2017-12-31 21:31:31,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 871}
2017-12-31 21:31:31,550 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,556 : INFO : < 200 OK [3220]
2017-12-31 21:31:31,561 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1200}
2017-12-31 21:31:31,564 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,569 : INFO : < 200 OK [3237]
2017-12-31 21:31:31,574 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 887}
2017-12-31 21:31:31,577 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,582 : INFO : < 200 OK [3219]
2017-12-31 21:31:31,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 643, '_0n0': 1043}
2017-12-31 21:31:31,591 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,596 : INFO : < 200 OK [3220]

2017-12-31 21:31:31,600 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 722, '_0n0': 1216}
2017-12-31 21:31:31,603 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,608 : INFO : < 200 OK [3248]
2017-12-31 21:31:31,613 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 722, '_0n0': 868}
2017-12-31 21:31:31,616 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,621 : INFO : < 200 OK [3228]
2017-12-31 21:31:31,626 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 686, '_0n0': 967}
2017-12-31 21:31:31,629 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,634 : INFO : < 200 OK [3224]
2017-12-31 21:31:31,639 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 739}
2017-12-31 21:31:31,642 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,648 : INFO : < 200 OK [3218]
2017-12-31 21:31:31,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 796}
2017-12-31 21:31:31,659 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,664 : INFO : < 200 OK [3231]
2017-12-31 21:31:31,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 1171}
2017-12-31 21:31:31,673 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,679 : INFO : < 200 OK [3247]
2017-12-31 21:31:31,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 705, '_0n0': 1184}
2017-12-31 21:31:31,687 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,692 : INFO : < 200 OK [3245]
2017-12-31 21:31:31,697 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 722, '_0n0': 1222}
2017-12-31 21:31:31,700 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,705 : INFO : < 200 OK [3240]
2017-12-31 21:31:31,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1053}
2017-12-31 21:31:31,712 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,717 : INFO : < 200 OK [3235]
2017-12-31 21:31:31,722 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 784}
2017-12-31 21:31:31,725 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,730 : INFO : < 200 OK [3220]
2017-12-31 21:31:31,735 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1159}
2017-12-31 21:31:31,739 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,744 : INFO : < 200 OK [3236]
2017-12-31 21:31:31,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 939}
2017-12-31 21:31:31,752 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,757 : INFO : < 200 OK [3224]
2017-12-31 21:31:31,761 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 902}
2017-12-31 21:31:31,765 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,769 : INFO : < 200 OK [3230]
2017-12-31 21:31:31,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1221}
2017-12-31 21:31:31,777 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,782 : INFO : < 200 OK [3236]
2017-12-31 21:31:31,785 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 881}
2017-12-31 21:31:31,788 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,793 : INFO : < 200 OK [3218]
2017-12-31 21:31:31,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 657, '_0n0': 1185}
2017-12-31 21:31:31,800 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,806 : INFO : < 200 OK [3224]
2017-12-31 21:31:31,810 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 643, '_0n0': 1188}
2017-12-31 21:31:31,812 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,818 : INFO : < 200 OK [3225]
2017-12-31 21:31:31,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 643, '_0n0': 1070}
2017-12-31 21:31:31,827 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,833 : INFO : < 200 OK [3219]
2017-12-31 21:31:31,839 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 703, '_0n0': 1057}
2017-12-31 21:31:31,844 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,849 : INFO : < 200 OK [3235]
2017-12-31 21:31:31,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1052}
2017-12-31 21:31:31,858 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,863 : INFO : < 200 OK [3238]
2017-12-31 21:31:31,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1163}
2017-12-31 21:31:31,870 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,876 : INFO : < 200 OK [3245]
2017-12-31 21:31:31,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 651, '_0n0': 1130}
2017-12-31 21:31:31,885 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,891 : INFO : < 200 OK [3237]
2017-12-31 21:31:31,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 651, '_0n0': 1175}
2017-12-31 21:31:31,897 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,902 : INFO : < 200 OK [3235]
2017-12-31 21:31:31,907 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 716, '_0n0': 789}
2017-12-31 21:31:31,910 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,916 : INFO : < 200 OK [3228]

2017-12-31 21:31:31,920 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 722, '_0n0': 1212}
2017-12-31 21:31:31,924 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,929 : INFO : < 200 OK [3243]
2017-12-31 21:31:31,933 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 738}
2017-12-31 21:31:31,936 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,941 : INFO : < 200 OK [3238]
2017-12-31 21:31:31,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 692, '_0n0': 977}
2017-12-31 21:31:31,948 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,955 : INFO : < 200 OK [3216]
2017-12-31 21:31:31,961 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 731, '_0n0': 1026}
2017-12-31 21:31:31,965 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,970 : INFO : < 200 OK [3249]
2017-12-31 21:31:31,976 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 647, '_0n0': 839}
2017-12-31 21:31:31,979 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:31,984 : INFO : < 200 OK [3230]
2017-12-31 21:31:31,989 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 647, '_0n0': 1097}
2017-12-31 21:31:31,992 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:31,998 : INFO : < 200 OK [3244]
2017-12-31 21:31:32,003 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 647, '_0n0': 1201}
2017-12-31 21:31:32,006 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,012 : INFO : < 200 OK [3242]
2017-12-31 21:31:32,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 680, '_0n0': 1058}
2017-12-31 21:31:32,020 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,025 : INFO : < 200 OK [3235]
2017-12-31 21:31:32,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1022}
2017-12-31 21:31:32,032 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,037 : INFO : < 200 OK [3239]
2017-12-31 21:31:32,042 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 1095}
2017-12-31 21:31:32,045 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,050 : INFO : < 200 OK [3244]
2017-12-31 21:31:32,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 898}
2017-12-31 21:31:32,058 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,063 : INFO : < 200 OK [3235]
2017-12-31 21:31:32,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 638, '_0n0': 1244}
2017-12-31 21:31:32,070 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,075 : INFO : < 200 OK [3233]
2017-12-31 21:31:32,079 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 638, '_0n0': 1135}
2017-12-31 21:31:32,082 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,088 : INFO : < 200 OK [3234]
2017-12-31 21:31:32,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 680, '_0n0': 919}
2017-12-31 21:31:32,097 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,104 : INFO : < 200 OK [3220]
2017-12-31 21:31:32,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 654, '_0n0': 1217}
2017-12-31 21:31:32,113 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,119 : INFO : < 200 OK [3280]
2017-12-31 21:31:32,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 654, '_0n0': 1075}
2017-12-31 21:31:32,127 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,132 : INFO : < 200 OK [3263]
2017-12-31 21:31:32,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 679, '_0n0': 1231}
2017-12-31 21:31:32,140 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,145 : INFO : < 200 OK [3233]
2017-12-31 21:31:32,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 1069}
2017-12-31 21:31:32,152 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,157 : INFO : < 200 OK [3241]
2017-12-31 21:31:32,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 686, '_0n0': 896}
2017-12-31 21:31:32,165 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,170 : INFO : < 200 OK [3222]
2017-12-31 21:31:32,174 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 716, '_0n0': 926}
2017-12-31 21:31:32,177 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,182 : INFO : < 200 OK [3222]
2017-12-31 21:31:32,187 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 662, '_0n0': 963}
2017-12-31 21:31:32,190 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,196 : INFO : < 200 OK [3208]
2017-12-31 21:31:32,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 673, '_0n0': 1177}
2017-12-31 21:31:32,206 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,212 : INFO : < 200 OK [3233]
2017-12-31 21:31:32,217 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 716, '_0n0': 806}
2017-12-31 21:31:32,221 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,227 : INFO : < 200 OK [3226]
2017-12-31 21:31:32,232 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 681, '_0n0': 1117}
2017-12-31 21:31:32,235 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,240 : INFO : < 200 OK [3242]

2017-12-31 21:31:32,246 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 665, '_0n0': 1133}
2017-12-31 21:31:32,249 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,254 : INFO : < 200 OK [3215]
2017-12-31 21:31:32,259 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 945}
2017-12-31 21:31:32,262 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,267 : INFO : < 200 OK [3229]
2017-12-31 21:31:32,271 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 891}
2017-12-31 21:31:32,274 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,279 : INFO : < 200 OK [3229]
2017-12-31 21:31:32,283 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 755}
2017-12-31 21:31:32,285 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,290 : INFO : < 200 OK [3226]
2017-12-31 21:31:32,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 677, '_0n0': 1023}
2017-12-31 21:31:32,299 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,305 : INFO : < 200 OK [3254]
2017-12-31 21:31:32,310 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 646, '_0n0': 1243}
2017-12-31 21:31:32,315 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,319 : INFO : < 200 OK [3255]
2017-12-31 21:31:32,325 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 646, '_0n0': 1146}
2017-12-31 21:31:32,328 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,333 : INFO : < 200 OK [3248]
2017-12-31 21:31:32,338 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 710, '_0n0': 832}
2017-12-31 21:31:32,341 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,347 : INFO : < 200 OK [3248]
2017-12-31 21:31:32,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 675, '_0n0': 1123}
2017-12-31 21:31:32,355 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,360 : INFO : < 200 OK [3229]
2017-12-31 21:31:32,367 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 1176}
2017-12-31 21:31:32,370 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,375 : INFO : < 200 OK [3239]
2017-12-31 21:31:32,379 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 690, '_0n0': 1197}
2017-12-31 21:31:32,383 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,388 : INFO : < 200 OK [3285]
2017-12-31 21:31:32,392 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 690, '_0n0': 1040}
2017-12-31 21:31:32,394 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,400 : INFO : < 200 OK [3285]
2017-12-31 21:31:32,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 717, '_0n0': 925}
2017-12-31 21:31:32,407 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,412 : INFO : < 200 OK [3221]
2017-12-31 21:31:32,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 717, '_0n0': 810}
2017-12-31 21:31:32,419 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,424 : INFO : < 200 OK [3220]
2017-12-31 21:31:32,428 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 683, '_0n0': 948}
2017-12-31 21:31:32,431 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,437 : INFO : < 200 OK [3225]
2017-12-31 21:31:32,442 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 683, '_0n0': 1148}
2017-12-31 21:31:32,446 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,452 : INFO : < 200 OK [3239]
2017-12-31 21:31:32,457 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 724, '_0n0': 1029}
2017-12-31 21:31:32,462 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,467 : INFO : < 200 OK [3252]
2017-12-31 21:31:32,472 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 724, '_0n0': 883}
2017-12-31 21:31:32,476 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,481 : INFO : < 200 OK [3241]
2017-12-31 21:31:32,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 1194}
2017-12-31 21:31:32,490 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,495 : INFO : < 200 OK [3241]
2017-12-31 21:31:32,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 706, '_0n0': 1144}
2017-12-31 21:31:32,502 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,507 : INFO : < 200 OK [3249]
2017-12-31 21:31:32,511 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 697, '_0n0': 917}
2017-12-31 21:31:32,515 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,520 : INFO : < 200 OK [3232]
2017-12-31 21:31:32,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 649, '_0n0': 851}
2017-12-31 21:31:32,529 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,536 : INFO : < 200 OK [3245]
2017-12-31 21:31:32,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 723, '_0n0': 750}
2017-12-31 21:31:32,545 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,550 : INFO : < 200 OK [3221]
2017-12-31 21:31:32,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 646, '_0n0': 848}
2017-12-31 21:31:32,559 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,565 : INFO : < 200 OK [3242]

2017-12-31 21:31:32,570 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 682, '_0n0': 1174}
2017-12-31 21:31:32,573 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,578 : INFO : < 200 OK [3248]
2017-12-31 21:31:32,582 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 655, '_0n0': 1157}
2017-12-31 21:31:32,585 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,590 : INFO : < 200 OK [3251]
2017-12-31 21:31:32,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 711, '_0n0': 1162}
2017-12-31 21:31:32,597 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,602 : INFO : < 200 OK [3260]
2017-12-31 21:31:32,607 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 677, '_0n0': 1118}
2017-12-31 21:31:32,610 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,615 : INFO : < 200 OK [3252]
2017-12-31 21:31:32,620 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 661, '_0n0': 1034}
2017-12-31 21:31:32,623 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,629 : INFO : < 200 OK [3255]
2017-12-31 21:31:32,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 649, '_0n0': 1147}
2017-12-31 21:31:32,639 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,646 : INFO : < 200 OK [3264]
2017-12-31 21:31:32,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 693, '_0n0': 1102}
2017-12-31 21:31:32,654 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,660 : INFO : < 200 OK [3254]
2017-12-31 21:31:32,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 624, '_0n0': 877}
2017-12-31 21:31:32,669 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,674 : INFO : < 200 OK [3231]
2017-12-31 21:31:32,679 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 722, '_0n0': 795}
2017-12-31 21:31:32,682 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,687 : INFO : < 200 OK [3225]
2017-12-31 21:31:32,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 665, '_0n0': 1242}
2017-12-31 21:31:32,694 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,699 : INFO : < 200 OK [3209]
2017-12-31 21:31:32,704 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 665, '_0n0': 1047}
2017-12-31 21:31:32,708 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,713 : INFO : < 200 OK [3212]
2017-12-31 21:31:32,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 651, '_0n0': 1056}
2017-12-31 21:31:32,721 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,726 : INFO : < 200 OK [3231]
2017-12-31 21:31:32,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 651, '_0n0': 1051}
2017-12-31 21:31:32,733 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,738 : INFO : < 200 OK [3235]
2017-12-31 21:31:32,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 645, '_0n0': 1121}
2017-12-31 21:31:32,747 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,752 : INFO : < 200 OK [3236]
2017-12-31 21:31:32,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 645, '_0n0': 1141}
2017-12-31 21:31:32,759 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,764 : INFO : < 200 OK [3229]
2017-12-31 21:31:32,768 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 684, '_0n0': 934}
2017-12-31 21:31:32,771 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,777 : INFO : < 200 OK [3211]
2017-12-31 21:31:32,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 710, '_0n0': 889}
2017-12-31 21:31:32,785 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,791 : INFO : < 200 OK [3240]
2017-12-31 21:31:32,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 732, '_0n0': 1078}
2017-12-31 21:31:32,800 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,806 : INFO : < 200 OK [3242]
2017-12-31 21:31:32,812 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 685, '_0n0': 922}
2017-12-31 21:31:32,815 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,821 : INFO : < 200 OK [3249]
2017-12-31 21:31:32,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 685, '_0n0': 1027}
2017-12-31 21:31:32,829 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,834 : INFO : < 200 OK [3271]
2017-12-31 21:31:32,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 681, '_0n0': 937}
2017-12-31 21:31:32,841 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,846 : INFO : < 200 OK [3240]
2017-12-31 21:31:32,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 650, '_0n0': 1031}
2017-12-31 21:31:32,854 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,859 : INFO : < 200 OK [3245]
2017-12-31 21:31:32,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 648, '_0n0': 1173}
2017-12-31 21:31:32,867 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,872 : INFO : < 200 OK [3233]
2017-12-31 21:31:32,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 694, '_0n0': 751}
2017-12-31 21:31:32,880 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,886 : INFO : < 200 OK [3210]

2017-12-31 21:31:32,891 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 689, '_0n0': 730}
2017-12-31 21:31:32,896 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,901 : INFO : < 200 OK [3210]
2017-12-31 21:31:32,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 699, '_0n0': 938}
2017-12-31 21:31:32,910 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,915 : INFO : < 200 OK [3253]
2017-12-31 21:31:32,919 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 699, '_0n0': 1099}
2017-12-31 21:31:32,921 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,927 : INFO : < 200 OK [3280]
2017-12-31 21:31:32,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 665, '_0n0': 1134}
2017-12-31 21:31:32,936 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,941 : INFO : < 200 OK [3213]
2017-12-31 21:31:32,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 665, '_0n0': 828}
2017-12-31 21:31:32,949 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,954 : INFO : < 200 OK [3200]
2017-12-31 21:31:32,959 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 665, '_0n0': 850}
2017-12-31 21:31:32,962 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,967 : INFO : < 200 OK [3198]
2017-12-31 21:31:32,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 710, '_0n0': 1165}
2017-12-31 21:31:32,975 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:32,980 : INFO : < 200 OK [3260]
2017-12-31 21:31:32,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 710, '_0n0': 754}
2017-12-31 21:31:32,988 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:32,993 : INFO : < 200 OK [3249]
2017-12-31 21:31:32,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 681, '_0n0': 959}
2017-12-31 21:31:33,000 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:33,006 : INFO : < 200 OK [3235]
2017-12-31 21:31:33,009 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 655, '_0n0': 1211}
2017-12-31 21:31:33,012 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:33,017 : INFO : < 200 OK [3232]
2017-12-31 21:31:33,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 652, '_0n0': 1112}
2017-12-31 21:31:33,024 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:33,029 : INFO : < 200 OK [3220]
2017-12-31 21:31:33,034 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 689, '_0n0': 904}
2017-12-31 21:31:33,037 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:33,042 : INFO : < 200 OK [3207]
2017-12-31 21:31:33,047 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 681, '_0n0': 818}
2017-12-31 21:31:33,050 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:33,056 : INFO : < 200 OK [3224]
2017-12-31 21:31:33,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:from]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 717, '_0n0': 905}
2017-12-31 21:31:33,065 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:33,070 : INFO : < 200 OK [3224]

In [80]:
df = pd.merge(title_relation_df, data_clear[['uid', 'package_name', 'package_num']], on='uid', how='left')
df.head()

,title,uid,relate_1,relate_2,relate_3,relate_4,relate_5,package_name,package_num
0,Bitcoin and Cryptocurrency Technologies,0,852,346,596,294,707,None,None
1,Cryptography I,284,28,340,822,344,463,None,None
2,Google Cloud Platform Fundamentals: Core Infra...,157,840,867,161,159,829,Architecting with Google Cloud Platform Specia...,1
3,G Suite Administrator Fundamentals,3,250,733,436,365,706,None,None
4,Usable Security,4,654,858,743,60,70,Cybersecurity Specialization,1

In [81]:
for name, group in df.groupby('package_name')['uid']:
    tmp = list(group)
    for i, row in enumerate(tmp):
        if i != 0:
            x = course_dict[tmp[i-1]]
            y = course_dict[row]
            graph.create(Relationship(x, "require", y))

2017-12-31 21:31:33,560 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 517, '_0n0': 471}
2017-12-31 21:31:33,563 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,568 : INFO : < 200 OK [3350]
2017-12-31 21:31:33,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 519, '_0n0': 517}
2017-12-31 21:31:33,576 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,582 : INFO : < 200 OK [3345]
2017-12-31 21:31:33,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 536, '_0n0': 519}
2017-12-31 21:31:33,591 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,597 : INFO : < 200 OK [3351]
2017-12-31 21:31:33,601 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 587, '_0n0': 536}
2017-12-31 21:31:33,604 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,610 : INFO : < 200 OK [3349]
2017-12-31 21:31:33,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 390, '_0n0': 389}
2017-12-31 21:31:33,618 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,623 : INFO : < 200 OK [3422]
2017-12-31 21:31:33,626 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 396, '_0n0': 390}
2017-12-31 21:31:33,630 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,635 : INFO : < 200 OK [3430]
2017-12-31 21:31:33,639 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 176, '_0n0': 163}
2017-12-31 21:31:33,642 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,648 : INFO : < 200 OK [3339]
2017-12-31 21:31:33,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 178, '_0n0': 176}
2017-12-31 21:31:33,656 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,661 : INFO : < 200 OK [3358]
2017-12-31 21:31:33,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 194, '_0n0': 178}
2017-12-31 21:31:33,667 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,672 : INFO : < 200 OK [3354]
2017-12-31 21:31:33,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 183, '_0n0': 194}
2017-12-31 21:31:33,680 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,685 : INFO : < 200 OK [3379]
2017-12-31 21:31:33,689 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 89, '_0n0': 67}
2017-12-31 21:31:33,693 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:33,698 : INFO : < 200 OK [3426]
2017-12-31 21:31:33,702 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 96, '_0n0': 89}
2017-12-31 21:31:33,705 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:33,710 : INFO : < 200 OK [3424]
2017-12-31 21:31:33,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 116, '_0n0': 96}
2017-12-31 21:31:33,717 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:33,722 : INFO : < 200 OK [3462]
2017-12-31 21:31:33,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 146, '_0n0': 15}
2017-12-31 21:31:33,731 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:33,737 : INFO : < 200 OK [3350]
2017-12-31 21:31:33,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 214, '_0n0': 146}
2017-12-31 21:31:33,746 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,752 : INFO : < 200 OK [3370]
2017-12-31 21:31:33,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 217, '_0n0': 214}
2017-12-31 21:31:33,761 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,767 : INFO : < 200 OK [3339]
2017-12-31 21:31:33,771 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 260, '_0n0': 217}
2017-12-31 21:31:33,775 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,780 : INFO : < 200 OK [3347]
2017-12-31 21:31:33,785 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 582, '_0n0': 260}
2017-12-31 21:31:33,788 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,794 : INFO : < 200 OK [3388]
2017-12-31 21:31:33,799 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 325, '_0n0': 314}
2017-12-31 21:31:33,802 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,807 : INFO : < 200 OK [3387]
2017-12-31 21:31:33,812 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 327, '_0n0': 325}
2017-12-31 21:31:33,815 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,820 : INFO : < 200 OK [3438]
2017-12-31 21:31:33,825 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 328, '_0n0': 327}
2017-12-31 21:31:33,828 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,833 : INFO : < 200 OK [3406]
2017-12-31 21:31:33,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 355, '_0n0': 328}
2017-12-31 21:31:33,841 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,846 : INFO : < 200 OK [3355]
2017-12-31 21:31:33,850 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 31, '_0n0': 18}
2017-12-31 21:31:33,854 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:33,860 : INFO : < 200 OK [3341]
2017-12-31 21:31:33,865 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 53, '_0n0': 31}
2017-12-31 21:31:33,868 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:33,875 : INFO : < 200 OK [3323]

2017-12-31 21:31:33,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 55, '_0n0': 53}
2017-12-31 21:31:33,885 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:33,891 : INFO : < 200 OK [3344]
2017-12-31 21:31:33,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 433, '_0n0': 143}
2017-12-31 21:31:33,899 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,905 : INFO : < 200 OK [3435]
2017-12-31 21:31:33,909 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 430, '_0n0': 433}
2017-12-31 21:31:33,913 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,918 : INFO : < 200 OK [3411]
2017-12-31 21:31:33,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 439, '_0n0': 430}
2017-12-31 21:31:33,925 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,931 : INFO : < 200 OK [3402]
2017-12-31 21:31:33,936 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 460, '_0n0': 439}
2017-12-31 21:31:33,939 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,945 : INFO : < 200 OK [3409]
2017-12-31 21:31:33,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 991, '_0n0': 1013}
2017-12-31 21:31:33,954 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2017-12-31 21:31:33,960 : INFO : < 200 OK [3451]
2017-12-31 21:31:33,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 992, '_0n0': 991}
2017-12-31 21:31:33,967 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:33,972 : INFO : < 200 OK [3426]
2017-12-31 21:31:33,977 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 4, '_0n0': 992}
2017-12-31 21:31:33,980 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:33,986 : INFO : < 200 OK [3406]
2017-12-31 21:31:33,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 5, '_0n0': 4}
2017-12-31 21:31:33,995 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:34,000 : INFO : < 200 OK [3384]
2017-12-31 21:31:34,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 35, '_0n0': 5}
2017-12-31 21:31:34,008 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:34,013 : INFO : < 200 OK [3396]
2017-12-31 21:31:34,018 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 435, '_0n0': 415}
2017-12-31 21:31:34,020 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,026 : INFO : < 200 OK [3327]
2017-12-31 21:31:34,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 448, '_0n0': 435}
2017-12-31 21:31:34,033 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,038 : INFO : < 200 OK [3337]
2017-12-31 21:31:34,043 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 465, '_0n0': 448}
2017-12-31 21:31:34,047 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,055 : INFO : < 200 OK [3377]
2017-12-31 21:31:34,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 476, '_0n0': 465}
2017-12-31 21:31:34,064 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,069 : INFO : < 200 OK [3365]
2017-12-31 21:31:34,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 568, '_0n0': 476}
2017-12-31 21:31:34,077 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,082 : INFO : < 200 OK [3328]
2017-12-31 21:31:34,088 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 456, '_0n0': 418}
2017-12-31 21:31:34,091 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,096 : INFO : < 200 OK [3433]
2017-12-31 21:31:34,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 466, '_0n0': 456}
2017-12-31 21:31:34,103 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,108 : INFO : < 200 OK [3447]
2017-12-31 21:31:34,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 133, '_0n0': 97}
2017-12-31 21:31:34,116 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:34,121 : INFO : < 200 OK [3402]
2017-12-31 21:31:34,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 134, '_0n0': 133}
2017-12-31 21:31:34,128 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,132 : INFO : < 200 OK [3422]
2017-12-31 21:31:34,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 130, '_0n0': 134}
2017-12-31 21:31:34,141 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,146 : INFO : < 200 OK [3424]
2017-12-31 21:31:34,152 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 136, '_0n0': 130}
2017-12-31 21:31:34,156 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,162 : INFO : < 200 OK [3429]
2017-12-31 21:31:34,167 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 131, '_0n0': 136}
2017-12-31 21:31:34,171 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,176 : INFO : < 200 OK [3447]
2017-12-31 21:31:34,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 139, '_0n0': 131}
2017-12-31 21:31:34,183 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,189 : INFO : < 200 OK [3432]
2017-12-31 21:31:34,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 449, '_0n0': 441}
2017-12-31 21:31:34,196 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,201 : INFO : < 200 OK [3257]

2017-12-31 21:31:34,205 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 464, '_0n0': 449}
2017-12-31 21:31:34,208 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,212 : INFO : < 200 OK [3259]
2017-12-31 21:31:34,216 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 468, '_0n0': 464}
2017-12-31 21:31:34,219 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,223 : INFO : < 200 OK [3288]
2017-12-31 21:31:34,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 562, '_0n0': 468}
2017-12-31 21:31:34,231 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,236 : INFO : < 200 OK [3353]
2017-12-31 21:31:34,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 511, '_0n0': 440}
2017-12-31 21:31:34,243 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,248 : INFO : < 200 OK [3402]
2017-12-31 21:31:34,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 503, '_0n0': 511}
2017-12-31 21:31:34,256 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,261 : INFO : < 200 OK [3402]
2017-12-31 21:31:34,266 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 526, '_0n0': 503}
2017-12-31 21:31:34,270 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,277 : INFO : < 200 OK [3393]
2017-12-31 21:31:34,281 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 554, '_0n0': 526}
2017-12-31 21:31:34,284 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,289 : INFO : < 200 OK [3393]
2017-12-31 21:31:34,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 462, '_0n0': 455}
2017-12-31 21:31:34,297 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,301 : INFO : < 200 OK [3349]
2017-12-31 21:31:34,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 475, '_0n0': 462}
2017-12-31 21:31:34,309 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,315 : INFO : < 200 OK [3339]
2017-12-31 21:31:34,319 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 483, '_0n0': 475}
2017-12-31 21:31:34,323 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,328 : INFO : < 200 OK [3329]
2017-12-31 21:31:34,332 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 557, '_0n0': 483}
2017-12-31 21:31:34,335 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,340 : INFO : < 200 OK [3350]
2017-12-31 21:31:34,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 994, '_0n0': 989}
2017-12-31 21:31:34,348 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,353 : INFO : < 200 OK [3404]
2017-12-31 21:31:34,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 9, '_0n0': 994}
2017-12-31 21:31:34,360 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,366 : INFO : < 200 OK [3357]
2017-12-31 21:31:34,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 16, '_0n0': 9}
2017-12-31 21:31:34,373 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:34,378 : INFO : < 200 OK [3340]
2017-12-31 21:31:34,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 17, '_0n0': 16}
2017-12-31 21:31:34,386 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,392 : INFO : < 200 OK [3373]
2017-12-31 21:31:34,397 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 32, '_0n0': 12}
2017-12-31 21:31:34,402 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,409 : INFO : < 200 OK [3421]
2017-12-31 21:31:34,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 20, '_0n0': 32}
2017-12-31 21:31:34,416 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,421 : INFO : < 200 OK [3333]
2017-12-31 21:31:34,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 62, '_0n0': 20}
2017-12-31 21:31:34,429 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,435 : INFO : < 200 OK [3280]
2017-12-31 21:31:34,440 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 70, '_0n0': 62}
2017-12-31 21:31:34,443 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,448 : INFO : < 200 OK [3325]
2017-12-31 21:31:34,452 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 123, '_0n0': 70}
2017-12-31 21:31:34,455 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:34,460 : INFO : < 200 OK [3350]
2017-12-31 21:31:34,464 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 23, '_0n0': 995}
2017-12-31 21:31:34,467 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:34,472 : INFO : < 200 OK [3352]
2017-12-31 21:31:34,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 30, '_0n0': 23}
2017-12-31 21:31:34,479 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,484 : INFO : < 200 OK [3288]
2017-12-31 21:31:34,488 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 52, '_0n0': 30}
2017-12-31 21:31:34,493 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,499 : INFO : < 200 OK [3310]
2017-12-31 21:31:34,505 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 34, '_0n0': 6}
2017-12-31 21:31:34,509 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:34,514 : INFO : < 200 OK [3368]

2017-12-31 21:31:34,518 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 26, '_0n0': 34}
2017-12-31 21:31:34,522 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,527 : INFO : < 200 OK [3356]
2017-12-31 21:31:34,532 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 51, '_0n0': 26}
2017-12-31 21:31:34,534 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,540 : INFO : < 200 OK [3346]
2017-12-31 21:31:34,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 2, '_0n0': 1014}
2017-12-31 21:31:34,547 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:34,552 : INFO : < 200 OK [3288]
2017-12-31 21:31:34,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 11, '_0n0': 2}
2017-12-31 21:31:34,560 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:34,565 : INFO : < 200 OK [3256]
2017-12-31 21:31:34,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 36, '_0n0': 11}
2017-12-31 21:31:34,572 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,576 : INFO : < 200 OK [3270]
2017-12-31 21:31:34,581 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 63, '_0n0': 36}
2017-12-31 21:31:34,584 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,589 : INFO : < 200 OK [3321]
2017-12-31 21:31:34,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 22, '_0n0': 13}
2017-12-31 21:31:34,596 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,601 : INFO : < 200 OK [3375]
2017-12-31 21:31:34,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 28, '_0n0': 22}
2017-12-31 21:31:34,608 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,613 : INFO : < 200 OK [3383]
2017-12-31 21:31:34,617 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 54, '_0n0': 28}
2017-12-31 21:31:34,620 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,625 : INFO : < 200 OK [3378]
2017-12-31 21:31:34,630 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 50, '_0n0': 41}
2017-12-31 21:31:34,634 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,639 : INFO : < 200 OK [3369]
2017-12-31 21:31:34,643 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 60, '_0n0': 50}
2017-12-31 21:31:34,647 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,652 : INFO : < 200 OK [3355]
2017-12-31 21:31:34,657 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 77, '_0n0': 60}
2017-12-31 21:31:34,660 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,666 : INFO : < 200 OK [3368]
2017-12-31 21:31:34,674 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 419, '_0n0': 384}
2017-12-31 21:31:34,677 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,683 : INFO : < 200 OK [3338]
2017-12-31 21:31:34,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 480, '_0n0': 419}
2017-12-31 21:31:34,692 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,698 : INFO : < 200 OK [3340]
2017-12-31 21:31:34,703 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 523, '_0n0': 480}
2017-12-31 21:31:34,706 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,711 : INFO : < 200 OK [3325]
2017-12-31 21:31:34,716 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 571, '_0n0': 523}
2017-12-31 21:31:34,719 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,724 : INFO : < 200 OK [3333]
2017-12-31 21:31:34,729 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 437, '_0n0': 429}
2017-12-31 21:31:34,732 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,737 : INFO : < 200 OK [3385]
2017-12-31 21:31:34,742 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 458, '_0n0': 437}
2017-12-31 21:31:34,745 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,751 : INFO : < 200 OK [3396]
2017-12-31 21:31:34,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 459, '_0n0': 458}
2017-12-31 21:31:34,761 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,767 : INFO : < 200 OK [3417]
2017-12-31 21:31:34,772 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 563, '_0n0': 459}
2017-12-31 21:31:34,776 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,782 : INFO : < 200 OK [3448]
2017-12-31 21:31:34,787 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 400, '_0n0': 8}
2017-12-31 21:31:34,790 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:34,796 : INFO : < 200 OK [3437]
2017-12-31 21:31:34,801 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 416, '_0n0': 400}
2017-12-31 21:31:34,804 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,810 : INFO : < 200 OK [3471]
2017-12-31 21:31:34,814 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 403, '_0n0': 416}
2017-12-31 21:31:34,818 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,823 : INFO : < 200 OK [3480]
2017-12-31 21:31:34,827 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 485, '_0n0': 403}
2017-12-31 21:31:34,830 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,836 : INFO : < 200 OK [3473]

2017-12-31 21:31:34,841 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 401, '_0n0': 363}
2017-12-31 21:31:34,844 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,850 : INFO : < 200 OK [3316]
2017-12-31 21:31:34,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 417, '_0n0': 401}
2017-12-31 21:31:34,858 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,863 : INFO : < 200 OK [3331]
2017-12-31 21:31:34,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 512, '_0n0': 417}
2017-12-31 21:31:34,872 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,878 : INFO : < 200 OK [3337]
2017-12-31 21:31:34,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 513, '_0n0': 512}
2017-12-31 21:31:34,888 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,895 : INFO : < 200 OK [3336]
2017-12-31 21:31:34,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 561, '_0n0': 513}
2017-12-31 21:31:34,903 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,909 : INFO : < 200 OK [3324]
2017-12-31 21:31:34,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 374, '_0n0': 373}
2017-12-31 21:31:34,916 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,921 : INFO : < 200 OK [3344]
2017-12-31 21:31:34,926 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 375, '_0n0': 374}
2017-12-31 21:31:34,930 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,935 : INFO : < 200 OK [3323]
2017-12-31 21:31:34,939 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 361, '_0n0': 375}
2017-12-31 21:31:34,943 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,948 : INFO : < 200 OK [3315]
2017-12-31 21:31:34,952 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 376, '_0n0': 361}
2017-12-31 21:31:34,956 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,961 : INFO : < 200 OK [3311]
2017-12-31 21:31:34,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 379, '_0n0': 376}
2017-12-31 21:31:34,968 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,974 : INFO : < 200 OK [3315]
2017-12-31 21:31:34,978 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 366, '_0n0': 379}
2017-12-31 21:31:34,981 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,986 : INFO : < 200 OK [3318]
2017-12-31 21:31:34,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 391, '_0n0': 366}
2017-12-31 21:31:34,994 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:34,999 : INFO : < 200 OK [3323]
2017-12-31 21:31:35,004 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 407, '_0n0': 391}
2017-12-31 21:31:35,007 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,013 : INFO : < 200 OK [3320]
2017-12-31 21:31:35,019 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 501, '_0n0': 478}
2017-12-31 21:31:35,023 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,030 : INFO : < 200 OK [3373]
2017-12-31 21:31:35,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 552, '_0n0': 501}
2017-12-31 21:31:35,038 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,045 : INFO : < 200 OK [3357]
2017-12-31 21:31:35,049 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 567, '_0n0': 552}
2017-12-31 21:31:35,052 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,058 : INFO : < 200 OK [3347]
2017-12-31 21:31:35,062 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 84, '_0n0': 66}
2017-12-31 21:31:35,065 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:35,071 : INFO : < 200 OK [3342]
2017-12-31 21:31:35,075 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 95, '_0n0': 84}
2017-12-31 21:31:35,079 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:35,084 : INFO : < 200 OK [3343]
2017-12-31 21:31:35,089 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 100, '_0n0': 95}
2017-12-31 21:31:35,092 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:35,098 : INFO : < 200 OK [3374]
2017-12-31 21:31:35,102 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 101, '_0n0': 100}
2017-12-31 21:31:35,104 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,109 : INFO : < 200 OK [3390]
2017-12-31 21:31:35,114 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 138, '_0n0': 101}
2017-12-31 21:31:35,118 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,126 : INFO : < 200 OK [3393]
2017-12-31 21:31:35,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 477, '_0n0': 444}
2017-12-31 21:31:35,133 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,139 : INFO : < 200 OK [3412]
2017-12-31 21:31:35,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 482, '_0n0': 477}
2017-12-31 21:31:35,148 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,153 : INFO : < 200 OK [3399]
2017-12-31 21:31:35,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 484, '_0n0': 482}
2017-12-31 21:31:35,160 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,165 : INFO : < 200 OK [3409]

2017-12-31 21:31:35,170 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 559, '_0n0': 484}
2017-12-31 21:31:35,173 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,178 : INFO : < 200 OK [3423]
2017-12-31 21:31:35,183 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 461, '_0n0': 175}
2017-12-31 21:31:35,186 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,192 : INFO : < 200 OK [3356]
2017-12-31 21:31:35,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 525, '_0n0': 461}
2017-12-31 21:31:35,200 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,205 : INFO : < 200 OK [3358]
2017-12-31 21:31:35,210 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 547, '_0n0': 525}
2017-12-31 21:31:35,213 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,219 : INFO : < 200 OK [3375]
2017-12-31 21:31:35,224 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 569, '_0n0': 547}
2017-12-31 21:31:35,228 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,233 : INFO : < 200 OK [3394]
2017-12-31 21:31:35,237 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 80, '_0n0': 64}
2017-12-31 21:31:35,241 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:35,246 : INFO : < 200 OK [3371]
2017-12-31 21:31:35,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 65, '_0n0': 80}
2017-12-31 21:31:35,253 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:35,259 : INFO : < 200 OK [3420]
2017-12-31 21:31:35,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 388, '_0n0': 65}
2017-12-31 21:31:35,267 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:35,272 : INFO : < 200 OK [3439]
2017-12-31 21:31:35,277 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 349, '_0n0': 354}
2017-12-31 21:31:35,280 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,285 : INFO : < 200 OK [3348]
2017-12-31 21:31:35,290 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 422, '_0n0': 420}
2017-12-31 21:31:35,293 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,298 : INFO : < 200 OK [3382]
2017-12-31 21:31:35,303 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 408, '_0n0': 422}
2017-12-31 21:31:35,306 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,310 : INFO : < 200 OK [3390]
2017-12-31 21:31:35,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 423, '_0n0': 408}
2017-12-31 21:31:35,318 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,323 : INFO : < 200 OK [3408]
2017-12-31 21:31:35,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 409, '_0n0': 423}
2017-12-31 21:31:35,330 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,335 : INFO : < 200 OK [3396]
2017-12-31 21:31:35,339 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 424, '_0n0': 409}
2017-12-31 21:31:35,343 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,349 : INFO : < 200 OK [3387]
2017-12-31 21:31:35,354 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 410, '_0n0': 424}
2017-12-31 21:31:35,358 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,364 : INFO : < 200 OK [3394]
2017-12-31 21:31:35,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 425, '_0n0': 410}
2017-12-31 21:31:35,370 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,377 : INFO : < 200 OK [3392]
2017-12-31 21:31:35,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 411, '_0n0': 425}
2017-12-31 21:31:35,386 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,391 : INFO : < 200 OK [3392]
2017-12-31 21:31:35,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 426, '_0n0': 411}
2017-12-31 21:31:35,398 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,403 : INFO : < 200 OK [3407]
2017-12-31 21:31:35,406 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 37, '_0n0': 33}
2017-12-31 21:31:35,409 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:35,414 : INFO : < 200 OK [3340]
2017-12-31 21:31:35,418 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 49, '_0n0': 37}
2017-12-31 21:31:35,422 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:35,427 : INFO : < 200 OK [3316]
2017-12-31 21:31:35,431 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 75, '_0n0': 49}
2017-12-31 21:31:35,434 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:35,439 : INFO : < 200 OK [3303]
2017-12-31 21:31:35,444 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 181, '_0n0': 75}
2017-12-31 21:31:35,448 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:35,455 : INFO : < 200 OK [3349]
2017-12-31 21:31:35,460 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 221, '_0n0': 181}
2017-12-31 21:31:35,463 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,468 : INFO : < 200 OK [3365]
2017-12-31 21:31:35,474 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 463, '_0n0': 436}
2017-12-31 21:31:35,477 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,483 : INFO : < 200 OK [3413]

2017-12-31 21:31:35,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 450, '_0n0': 463}
2017-12-31 21:31:35,490 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,496 : INFO : < 200 OK [3390]
2017-12-31 21:31:35,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 467, '_0n0': 450}
2017-12-31 21:31:35,502 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,508 : INFO : < 200 OK [3391]
2017-12-31 21:31:35,513 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 453, '_0n0': 438}
2017-12-31 21:31:35,516 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,522 : INFO : < 200 OK [3364]
2017-12-31 21:31:35,526 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 442, '_0n0': 453}
2017-12-31 21:31:35,529 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,535 : INFO : < 200 OK [3347]
2017-12-31 21:31:35,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 443, '_0n0': 442}
2017-12-31 21:31:35,542 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,548 : INFO : < 200 OK [3333]
2017-12-31 21:31:35,553 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 560, '_0n0': 443}
2017-12-31 21:31:35,556 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,561 : INFO : < 200 OK [3369]
2017-12-31 21:31:35,566 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 472, '_0n0': 434}
2017-12-31 21:31:35,569 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,575 : INFO : < 200 OK [3325]
2017-12-31 21:31:35,579 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 507, '_0n0': 472}
2017-12-31 21:31:35,583 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,589 : INFO : < 200 OK [3323]
2017-12-31 21:31:35,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 508, '_0n0': 507}
2017-12-31 21:31:35,601 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,608 : INFO : < 200 OK [3326]
2017-12-31 21:31:35,613 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 556, '_0n0': 508}
2017-12-31 21:31:35,616 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,622 : INFO : < 200 OK [3329]
2017-12-31 21:31:35,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 142, '_0n0': 156}
2017-12-31 21:31:35,631 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,637 : INFO : < 200 OK [3427]
2017-12-31 21:31:35,642 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 309, '_0n0': 313}
2017-12-31 21:31:35,645 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,651 : INFO : < 200 OK [3429]
2017-12-31 21:31:35,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 310, '_0n0': 309}
2017-12-31 21:31:35,659 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,664 : INFO : < 200 OK [3435]
2017-12-31 21:31:35,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 336, '_0n0': 310}
2017-12-31 21:31:35,673 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,678 : INFO : < 200 OK [3439]
2017-12-31 21:31:35,684 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 340, '_0n0': 336}
2017-12-31 21:31:35,688 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,694 : INFO : < 200 OK [3437]
2017-12-31 21:31:35,699 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 529, '_0n0': 88}
2017-12-31 21:31:35,703 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:35,708 : INFO : < 200 OK [3336]
2017-12-31 21:31:35,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 529}
2017-12-31 21:31:35,716 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,721 : INFO : < 200 OK [3388]
2017-12-31 21:31:35,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 584, '_0n0': 591}
2017-12-31 21:31:35,729 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,734 : INFO : < 200 OK [3415]
2017-12-31 21:31:35,739 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 600, '_0n0': 584}
2017-12-31 21:31:35,742 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,747 : INFO : < 200 OK [3393]
2017-12-31 21:31:35,753 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 14, '_0n0': 3}
2017-12-31 21:31:35,757 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:35,764 : INFO : < 200 OK [3332]
2017-12-31 21:31:35,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 25, '_0n0': 14}
2017-12-31 21:31:35,772 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:35,778 : INFO : < 200 OK [3377]
2017-12-31 21:31:35,783 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 46, '_0n0': 25}
2017-12-31 21:31:35,786 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:35,791 : INFO : < 200 OK [3379]
2017-12-31 21:31:35,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 99, '_0n0': 83}
2017-12-31 21:31:35,799 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:35,804 : INFO : < 200 OK [3366]
2017-12-31 21:31:35,809 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 103, '_0n0': 99}
2017-12-31 21:31:35,812 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:35,817 : INFO : < 200 OK [3410]

2017-12-31 21:31:35,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 121, '_0n0': 103}
2017-12-31 21:31:35,825 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,830 : INFO : < 200 OK [3428]
2017-12-31 21:31:35,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 125, '_0n0': 121}
2017-12-31 21:31:35,837 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,843 : INFO : < 200 OK [3400]
2017-12-31 21:31:35,847 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 112, '_0n0': 125}
2017-12-31 21:31:35,850 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,854 : INFO : < 200 OK [3367]
2017-12-31 21:31:35,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 153, '_0n0': 112}
2017-12-31 21:31:35,861 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,866 : INFO : < 200 OK [3381]
2017-12-31 21:31:35,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 581, '_0n0': 179}
2017-12-31 21:31:35,873 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,878 : INFO : < 200 OK [3330]
2017-12-31 21:31:35,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 625, '_0n0': 581}
2017-12-31 21:31:35,885 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,890 : INFO : < 200 OK [3342]
2017-12-31 21:31:35,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 634, '_0n0': 625}
2017-12-31 21:31:35,898 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,903 : INFO : < 200 OK [3346]
2017-12-31 21:31:35,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 198, '_0n0': 174}
2017-12-31 21:31:35,911 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,916 : INFO : < 200 OK [3376]
2017-12-31 21:31:35,920 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 184, '_0n0': 198}
2017-12-31 21:31:35,923 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,928 : INFO : < 200 OK [3352]
2017-12-31 21:31:35,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 188, '_0n0': 184}
2017-12-31 21:31:35,935 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,940 : INFO : < 200 OK [3333]
2017-12-31 21:31:35,944 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 192, '_0n0': 188}
2017-12-31 21:31:35,947 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,953 : INFO : < 200 OK [3348]
2017-12-31 21:31:35,959 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 110, '_0n0': 102}
2017-12-31 21:31:35,962 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,970 : INFO : < 200 OK [3338]
2017-12-31 21:31:35,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 370, '_0n0': 110}
2017-12-31 21:31:35,978 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,983 : INFO : < 200 OK [3337]
2017-12-31 21:31:35,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 516, '_0n0': 370}
2017-12-31 21:31:35,991 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:35,996 : INFO : < 200 OK [3339]
2017-12-31 21:31:36,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 530, '_0n0': 516}
2017-12-31 21:31:36,005 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,011 : INFO : < 200 OK [3336]
2017-12-31 21:31:36,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 548, '_0n0': 530}
2017-12-31 21:31:36,019 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,024 : INFO : < 200 OK [3348]
2017-12-31 21:31:36,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 549, '_0n0': 548}
2017-12-31 21:31:36,033 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,038 : INFO : < 200 OK [3353]
2017-12-31 21:31:36,042 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 585, '_0n0': 549}
2017-12-31 21:31:36,045 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,051 : INFO : < 200 OK [3339]
2017-12-31 21:31:36,056 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 150, '_0n0': 157}
2017-12-31 21:31:36,058 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,063 : INFO : < 200 OK [3329]
2017-12-31 21:31:36,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 167, '_0n0': 150}
2017-12-31 21:31:36,070 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,075 : INFO : < 200 OK [3355]
2017-12-31 21:31:36,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 204, '_0n0': 167}
2017-12-31 21:31:36,083 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,088 : INFO : < 200 OK [3344]
2017-12-31 21:31:36,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 73, '_0n0': 57}
2017-12-31 21:31:36,097 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:36,103 : INFO : < 200 OK [3437]
2017-12-31 21:31:36,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 74, '_0n0': 73}
2017-12-31 21:31:36,114 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:36,120 : INFO : < 200 OK [3403]
2017-12-31 21:31:36,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 61, '_0n0': 74}
2017-12-31 21:31:36,127 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:36,134 : INFO : < 200 OK [3403]

2017-12-31 21:31:36,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 171, '_0n0': 149}
2017-12-31 21:31:36,142 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,148 : INFO : < 200 OK [3374]
2017-12-31 21:31:36,152 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 172, '_0n0': 171}
2017-12-31 21:31:36,155 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,160 : INFO : < 200 OK [3414]
2017-12-31 21:31:36,166 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 193, '_0n0': 172}
2017-12-31 21:31:36,169 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,175 : INFO : < 200 OK [3390]
2017-12-31 21:31:36,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 182, '_0n0': 193}
2017-12-31 21:31:36,183 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,188 : INFO : < 200 OK [3330]
2017-12-31 21:31:36,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 202, '_0n0': 182}
2017-12-31 21:31:36,195 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,201 : INFO : < 200 OK [3312]
2017-12-31 21:31:36,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 206, '_0n0': 202}
2017-12-31 21:31:36,209 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,214 : INFO : < 200 OK [3329]
2017-12-31 21:31:36,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 212, '_0n0': 43}
2017-12-31 21:31:36,221 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:36,227 : INFO : < 200 OK [3343]
2017-12-31 21:31:36,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 256, '_0n0': 212}
2017-12-31 21:31:36,233 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,238 : INFO : < 200 OK [3367]
2017-12-31 21:31:36,243 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 243, '_0n0': 256}
2017-12-31 21:31:36,247 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,253 : INFO : < 200 OK [3370]
2017-12-31 21:31:36,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 261, '_0n0': 243}
2017-12-31 21:31:36,262 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,269 : INFO : < 200 OK [3379]
2017-12-31 21:31:36,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 40, '_0n0': 21}
2017-12-31 21:31:36,279 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:36,285 : INFO : < 200 OK [3383]
2017-12-31 21:31:36,291 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 24, '_0n0': 990}
2017-12-31 21:31:36,295 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:36,302 : INFO : < 200 OK [3374]
2017-12-31 21:31:36,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 27, '_0n0': 24}
2017-12-31 21:31:36,311 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:36,316 : INFO : < 200 OK [3357]
2017-12-31 21:31:36,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 42, '_0n0': 27}
2017-12-31 21:31:36,325 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:36,330 : INFO : < 200 OK [3367]
2017-12-31 21:31:36,334 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 98, '_0n0': 87}
2017-12-31 21:31:36,336 : INFO : > POST http://localhost:7474/db/data/cypher [176]
2017-12-31 21:31:36,342 : INFO : < 200 OK [3345]
2017-12-31 21:31:36,346 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 113, '_0n0': 98}
2017-12-31 21:31:36,349 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:36,354 : INFO : < 200 OK [3373]
2017-12-31 21:31:36,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 104, '_0n0': 113}
2017-12-31 21:31:36,361 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,366 : INFO : < 200 OK [3390]
2017-12-31 21:31:36,371 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 124, '_0n0': 104}
2017-12-31 21:31:36,375 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,382 : INFO : < 200 OK [3377]
2017-12-31 21:31:36,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 469, '_0n0': 454}
2017-12-31 21:31:36,390 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,396 : INFO : < 200 OK [3385]
2017-12-31 21:31:36,400 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 470, '_0n0': 469}
2017-12-31 21:31:36,403 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,409 : INFO : < 200 OK [3376]
2017-12-31 21:31:36,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 509, '_0n0': 470}
2017-12-31 21:31:36,416 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,421 : INFO : < 200 OK [3378]
2017-12-31 21:31:36,425 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 606, '_0n0': 312}
2017-12-31 21:31:36,428 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,433 : INFO : < 200 OK [3431]
2017-12-31 21:31:36,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 619, '_0n0': 606}
2017-12-31 21:31:36,439 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,444 : INFO : < 200 OK [3429]
2017-12-31 21:31:36,449 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 395, '_0n0': 362}
2017-12-31 21:31:36,452 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,457 : INFO : < 200 OK [3352]

2017-12-31 21:31:36,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 412, '_0n0': 395}
2017-12-31 21:31:36,464 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,469 : INFO : < 200 OK [3356]
2017-12-31 21:31:36,473 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 414, '_0n0': 412}
2017-12-31 21:31:36,476 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,482 : INFO : < 200 OK [3345]
2017-12-31 21:31:36,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 506, '_0n0': 452}
2017-12-31 21:31:36,493 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,498 : INFO : < 200 OK [3390]
2017-12-31 21:31:36,502 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 528, '_0n0': 506}
2017-12-31 21:31:36,506 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,512 : INFO : < 200 OK [3394]
2017-12-31 21:31:36,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 531, '_0n0': 528}
2017-12-31 21:31:36,520 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,525 : INFO : < 200 OK [3391]
2017-12-31 21:31:36,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 572, '_0n0': 531}
2017-12-31 21:31:36,534 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,540 : INFO : < 200 OK [3402]
2017-12-31 21:31:36,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 368, '_0n0': 360}
2017-12-31 21:31:36,547 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,552 : INFO : < 200 OK [3340]
2017-12-31 21:31:36,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 510, '_0n0': 368}
2017-12-31 21:31:36,560 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,564 : INFO : < 200 OK [3356]
2017-12-31 21:31:36,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 564, '_0n0': 108}
2017-12-31 21:31:36,571 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,576 : INFO : < 200 OK [3379]
2017-12-31 21:31:36,581 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 603, '_0n0': 564}
2017-12-31 21:31:36,584 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,589 : INFO : < 200 OK [3391]
2017-12-31 21:31:36,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 590, '_0n0': 115}
2017-12-31 21:31:36,595 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,600 : INFO : < 200 OK [3405]
2017-12-31 21:31:36,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 592, '_0n0': 590}
2017-12-31 21:31:36,609 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,616 : INFO : < 200 OK [3418]
2017-12-31 21:31:36,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 597, '_0n0': 592}
2017-12-31 21:31:36,625 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,631 : INFO : < 200 OK [3431]
2017-12-31 21:31:36,635 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 601, '_0n0': 596}
2017-12-31 21:31:36,637 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,644 : INFO : < 200 OK [3398]
2017-12-31 21:31:36,647 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 607, '_0n0': 601}
2017-12-31 21:31:36,650 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,655 : INFO : < 200 OK [3400]
2017-12-31 21:31:36,660 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 220, '_0n0': 215}
2017-12-31 21:31:36,663 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,668 : INFO : < 200 OK [3324]
2017-12-31 21:31:36,672 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 222, '_0n0': 220}
2017-12-31 21:31:36,674 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,679 : INFO : < 200 OK [3308]
2017-12-31 21:31:36,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 223, '_0n0': 222}
2017-12-31 21:31:36,686 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,690 : INFO : < 200 OK [3360]
2017-12-31 21:31:36,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 257, '_0n0': 223}
2017-12-31 21:31:36,699 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,705 : INFO : < 200 OK [3417]
2017-12-31 21:31:36,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 246, '_0n0': 257}
2017-12-31 21:31:36,714 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,720 : INFO : < 200 OK [3424]
2017-12-31 21:31:36,725 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 120, '_0n0': 71}
2017-12-31 21:31:36,729 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:36,733 : INFO : < 200 OK [3407]
2017-12-31 21:31:36,737 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 106, '_0n0': 120}
2017-12-31 21:31:36,740 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,745 : INFO : < 200 OK [3416]
2017-12-31 21:31:36,750 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 431, '_0n0': 428}
2017-12-31 21:31:36,753 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,759 : INFO : < 200 OK [3322]
2017-12-31 21:31:36,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 457, '_0n0': 431}
2017-12-31 21:31:36,767 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,772 : INFO : < 200 OK [3366]

2017-12-31 21:31:36,776 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 573, '_0n0': 457}
2017-12-31 21:31:36,779 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,784 : INFO : < 200 OK [3394]
2017-12-31 21:31:36,789 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 589, '_0n0': 573}
2017-12-31 21:31:36,793 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,798 : INFO : < 200 OK [3359]
2017-12-31 21:31:36,803 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 405, '_0n0': 402}
2017-12-31 21:31:36,806 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,812 : INFO : < 200 OK [3422]
2017-12-31 21:31:36,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 406, '_0n0': 405}
2017-12-31 21:31:36,820 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,825 : INFO : < 200 OK [3357]
2017-12-31 21:31:36,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 421, '_0n0': 406}
2017-12-31 21:31:36,831 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,836 : INFO : < 200 OK [3357]
2017-12-31 21:31:36,840 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 427, '_0n0': 421}
2017-12-31 21:31:36,843 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,848 : INFO : < 200 OK [3320]
2017-12-31 21:31:36,852 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 627, '_0n0': 609}
2017-12-31 21:31:36,855 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,860 : INFO : < 200 OK [3389]
2017-12-31 21:31:36,865 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 629, '_0n0': 627}
2017-12-31 21:31:36,867 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,873 : INFO : < 200 OK [3394]
2017-12-31 21:31:36,877 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 615, '_0n0': 629}
2017-12-31 21:31:36,881 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,887 : INFO : < 200 OK [3391]
2017-12-31 21:31:36,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 630, '_0n0': 615}
2017-12-31 21:31:36,897 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,903 : INFO : < 200 OK [3388]
2017-12-31 21:31:36,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 324, '_0n0': 318}
2017-12-31 21:31:36,912 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,917 : INFO : < 200 OK [3357]
2017-12-31 21:31:36,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 341, '_0n0': 324}
2017-12-31 21:31:36,925 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,930 : INFO : < 200 OK [3349]
2017-12-31 21:31:36,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 329, '_0n0': 341}
2017-12-31 21:31:36,938 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,943 : INFO : < 200 OK [3367]
2017-12-31 21:31:36,947 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 344, '_0n0': 329}
2017-12-31 21:31:36,950 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,956 : INFO : < 200 OK [3352]
2017-12-31 21:31:36,960 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 357, '_0n0': 344}
2017-12-31 21:31:36,963 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,967 : INFO : < 200 OK [3364]
2017-12-31 21:31:36,973 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 278, '_0n0': 273}
2017-12-31 21:31:36,976 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,982 : INFO : < 200 OK [3337]
2017-12-31 21:31:36,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 279, '_0n0': 278}
2017-12-31 21:31:36,991 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:36,996 : INFO : < 200 OK [3365]
2017-12-31 21:31:37,000 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 294, '_0n0': 279}
2017-12-31 21:31:37,004 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,009 : INFO : < 200 OK [3359]
2017-12-31 21:31:37,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 284, '_0n0': 294}
2017-12-31 21:31:37,017 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,023 : INFO : < 200 OK [3324]
2017-12-31 21:31:37,028 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 305, '_0n0': 284}
2017-12-31 21:31:37,031 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,037 : INFO : < 200 OK [3309]
2017-12-31 21:31:37,041 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 333, '_0n0': 144}
2017-12-31 21:31:37,044 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,049 : INFO : < 200 OK [3347]
2017-12-31 21:31:37,053 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 334, '_0n0': 333}
2017-12-31 21:31:37,056 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,061 : INFO : < 200 OK [3379]
2017-12-31 21:31:37,065 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 343, '_0n0': 334}
2017-12-31 21:31:37,068 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,073 : INFO : < 200 OK [3404]
2017-12-31 21:31:37,077 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 345, '_0n0': 343}
2017-12-31 21:31:37,079 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,084 : INFO : < 200 OK [3368]

2017-12-31 21:31:37,089 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 350, '_0n0': 345}
2017-12-31 21:31:37,092 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,098 : INFO : < 200 OK [3352]
2017-12-31 21:31:37,106 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 614, '_0n0': 613}
2017-12-31 21:31:37,110 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,115 : INFO : < 200 OK [3381]
2017-12-31 21:31:37,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 616, '_0n0': 614}
2017-12-31 21:31:37,124 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,129 : INFO : < 200 OK [3355]
2017-12-31 21:31:37,134 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 631, '_0n0': 616}
2017-12-31 21:31:37,137 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,142 : INFO : < 200 OK [3361]
2017-12-31 21:31:37,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 320, '_0n0': 332}
2017-12-31 21:31:37,150 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,156 : INFO : < 200 OK [3383]
2017-12-31 21:31:37,160 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 335, '_0n0': 320}
2017-12-31 21:31:37,163 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,168 : INFO : < 200 OK [3389]
2017-12-31 21:31:37,172 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 595, '_0n0': 335}
2017-12-31 21:31:37,176 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,181 : INFO : < 200 OK [3382]
2017-12-31 21:31:37,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 604, '_0n0': 326}
2017-12-31 21:31:37,188 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,193 : INFO : < 200 OK [3409]
2017-12-31 21:31:37,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 612, '_0n0': 604}
2017-12-31 21:31:37,200 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,205 : INFO : < 200 OK [3404]
2017-12-31 21:31:37,210 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 169, '_0n0': 151}
2017-12-31 21:31:37,213 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,219 : INFO : < 200 OK [3354]
2017-12-31 21:31:37,225 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 170, '_0n0': 169}
2017-12-31 21:31:37,230 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,236 : INFO : < 200 OK [3350]
2017-12-31 21:31:37,241 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 177, '_0n0': 170}
2017-12-31 21:31:37,244 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,249 : INFO : < 200 OK [3348]
2017-12-31 21:31:37,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 197, '_0n0': 177}
2017-12-31 21:31:37,257 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,263 : INFO : < 200 OK [3352]
2017-12-31 21:31:37,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 199, '_0n0': 197}
2017-12-31 21:31:37,270 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,275 : INFO : < 200 OK [3352]
2017-12-31 21:31:37,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 377, '_0n0': 359}
2017-12-31 21:31:37,282 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,287 : INFO : < 200 OK [3389]
2017-12-31 21:31:37,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 378, '_0n0': 377}
2017-12-31 21:31:37,295 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,299 : INFO : < 200 OK [3376]
2017-12-31 21:31:37,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 364, '_0n0': 378}
2017-12-31 21:31:37,307 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,312 : INFO : < 200 OK [3385]
2017-12-31 21:31:37,317 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 387, '_0n0': 364}
2017-12-31 21:31:37,320 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,327 : INFO : < 200 OK [3359]
2017-12-31 21:31:37,332 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 553, '_0n0': 504}
2017-12-31 21:31:37,336 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,343 : INFO : < 200 OK [3340]
2017-12-31 21:31:37,349 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 570, '_0n0': 553}
2017-12-31 21:31:37,352 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,358 : INFO : < 200 OK [3335]
2017-12-31 21:31:37,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 537, '_0n0': 522}
2017-12-31 21:31:37,366 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,371 : INFO : < 200 OK [3373]
2017-12-31 21:31:37,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 555, '_0n0': 537}
2017-12-31 21:31:37,380 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,385 : INFO : < 200 OK [3334]
2017-12-31 21:31:37,390 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 195, '_0n0': 164}
2017-12-31 21:31:37,394 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,399 : INFO : < 200 OK [3351]
2017-12-31 21:31:37,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 196, '_0n0': 195}
2017-12-31 21:31:37,408 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,413 : INFO : < 200 OK [3319]

2017-12-31 21:31:37,418 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 196}
2017-12-31 21:31:37,421 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,427 : INFO : < 200 OK [3321]
2017-12-31 21:31:37,431 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 191, '_0n0': 200}
2017-12-31 21:31:37,434 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,439 : INFO : < 200 OK [3317]
2017-12-31 21:31:37,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 180, '_0n0': 173}
2017-12-31 21:31:37,446 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,450 : INFO : < 200 OK [3395]
2017-12-31 21:31:37,454 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 185, '_0n0': 180}
2017-12-31 21:31:37,457 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,462 : INFO : < 200 OK [3391]
2017-12-31 21:31:37,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 201, '_0n0': 185}
2017-12-31 21:31:37,470 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,476 : INFO : < 200 OK [3402]
2017-12-31 21:31:37,481 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 187, '_0n0': 201}
2017-12-31 21:31:37,484 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,492 : INFO : < 200 OK [3392]
2017-12-31 21:31:37,495 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 160, '_0n0': 158}
2017-12-31 21:31:37,499 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,504 : INFO : < 200 OK [3418]
2017-12-31 21:31:37,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 148, '_0n0': 160}
2017-12-31 21:31:37,512 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,517 : INFO : < 200 OK [3399]
2017-12-31 21:31:37,523 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 152, '_0n0': 148}
2017-12-31 21:31:37,526 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,530 : INFO : < 200 OK [3404]
2017-12-31 21:31:37,534 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 315, '_0n0': 291}
2017-12-31 21:31:37,537 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,542 : INFO : < 200 OK [3314]
2017-12-31 21:31:37,545 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 316, '_0n0': 315}
2017-12-31 21:31:37,548 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,554 : INFO : < 200 OK [3322]
2017-12-31 21:31:37,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 323, '_0n0': 316}
2017-12-31 21:31:37,560 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,565 : INFO : < 200 OK [3341]
2017-12-31 21:31:37,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 351, '_0n0': 323}
2017-12-31 21:31:37,571 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,576 : INFO : < 200 OK [3345]
2017-12-31 21:31:37,580 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 330, '_0n0': 337}
2017-12-31 21:31:37,584 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,589 : INFO : < 200 OK [3332]
2017-12-31 21:31:37,594 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 347, '_0n0': 330}
2017-12-31 21:31:37,598 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,604 : INFO : < 200 OK [3333]
2017-12-31 21:31:37,610 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 372, '_0n0': 347}
2017-12-31 21:31:37,613 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,618 : INFO : < 200 OK [3329]
2017-12-31 21:31:37,623 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 331, '_0n0': 59}
2017-12-31 21:31:37,627 : INFO : > POST http://localhost:7474/db/data/cypher [177]
2017-12-31 21:31:37,633 : INFO : < 200 OK [3343]
2017-12-31 21:31:37,638 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 353, '_0n0': 331}
2017-12-31 21:31:37,641 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,646 : INFO : < 200 OK [3359]
2017-12-31 21:31:37,650 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 348, '_0n0': 353}
2017-12-31 21:31:37,653 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,658 : INFO : < 200 OK [3364]
2017-12-31 21:31:37,662 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 356, '_0n0': 348}
2017-12-31 21:31:37,666 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,672 : INFO : < 200 OK [3350]
2017-12-31 21:31:37,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:require]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 617, '_0n0': 356}
2017-12-31 21:31:37,680 : INFO : > POST http://localhost:7474/db/data/cypher [178]
2017-12-31 21:31:37,685 : INFO : < 200 OK [3327]

In [82]:
tmp = data.drop_duplicates(subset=['uid', 'category'])
for i, row in title_relation_df.iterrows():
    uid = row['uid']
    x = course_dict[row.uid]
    cat_x = list(tmp[tmp.uid==row.uid])
    for i in range(1, 3):
        y = course_dict[row['relate_%s' % i]]
        cat_y = list(tmp[tmp.uid==row['relate_%s' % i]])
        flag = False
        for cat in cat_x:
            if cat in cat_y:
                flag = True
        if flag:
            if df[df.uid == uid].package_name.values[0] != None:
                if df[df.uid == row['relate_%s' % i]].package_name.values[0] != df[df.uid == uid].package_name.values[0]:
                    graph.create(Relationship(x, "related to", y))
                   # graph.create(Relationship(y, "related to", x))
            else:
                graph.create(Relationship(x, "related to", y))

2017-12-31 21:31:38,031 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 631, '_0n0': 1012}
2017-12-31 21:31:38,035 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2017-12-31 21:31:38,042 : INFO : < 200 OK [3378]
2017-12-31 21:31:38,050 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 55, '_0n0': 1012}
2017-12-31 21:31:38,054 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:38,060 : INFO : < 200 OK [3367]
2017-12-31 21:31:38,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 11, '_0n0': 987}
2017-12-31 21:31:38,071 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,076 : INFO : < 200 OK [3289]
2017-12-31 21:31:38,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 31, '_0n0': 987}
2017-12-31 21:31:38,086 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,092 : INFO : < 200 OK [3308]
2017-12-31 21:31:38,101 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 352, '_0n0': 1013}
2017-12-31 21:31:38,104 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2017-12-31 21:31:38,110 : INFO : < 200 OK [3459]
2017-12-31 21:31:38,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 76, '_0n0': 1013}
2017-12-31 21:31:38,123 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:38,129 : INFO : < 200 OK [3460]
2017-12-31 21:31:38,140 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 216, '_0n0': 988}
2017-12-31 21:31:38,144 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:38,150 : INFO : < 200 OK [3375]
2017-12-31 21:31:38,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 398, '_0n0': 988}
2017-12-31 21:31:38,162 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:38,168 : INFO : < 200 OK [3387]
2017-12-31 21:31:38,178 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 371, '_0n0': 1014}
2017-12-31 21:31:38,182 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2017-12-31 21:31:38,188 : INFO : < 200 OK [3330]
2017-12-31 21:31:38,196 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 617, '_0n0': 1014}
2017-12-31 21:31:38,201 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2017-12-31 21:31:38,207 : INFO : < 200 OK [3331]
2017-12-31 21:31:38,224 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 993, '_0n0': 0}
2017-12-31 21:31:38,227 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,234 : INFO : < 200 OK [3383]
2017-12-31 21:31:38,241 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 411, '_0n0': 0}
2017-12-31 21:31:38,244 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,250 : INFO : < 200 OK [3371]
2017-12-31 21:31:38,268 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 49, '_0n0': 1}
2017-12-31 21:31:38,271 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:38,277 : INFO : < 200 OK [3314]
2017-12-31 21:31:38,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 23, '_0n0': 1}
2017-12-31 21:31:38,288 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:38,294 : INFO : < 200 OK [3310]
2017-12-31 21:31:38,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 400, '_0n0': 991}
2017-12-31 21:31:38,311 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:38,318 : INFO : < 200 OK [3451]
2017-12-31 21:31:38,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 3, '_0n0': 2}
2017-12-31 21:31:38,335 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2017-12-31 21:31:38,342 : INFO : < 200 OK [3264]
2017-12-31 21:31:38,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 0, '_0n0': 2}
2017-12-31 21:31:38,355 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2017-12-31 21:31:38,362 : INFO : < 200 OK [3296]
2017-12-31 21:31:38,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 352, '_0n0': 992}
2017-12-31 21:31:38,379 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:38,385 : INFO : < 200 OK [3434]
2017-12-31 21:31:38,395 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 2, '_0n0': 3}
2017-12-31 21:31:38,399 : INFO : > POST http://localhost:7474/db/data/cypher [179]
2017-12-31 21:31:38,404 : INFO : < 200 OK [3264]
2017-12-31 21:31:38,412 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 22, '_0n0': 3}
2017-12-31 21:31:38,415 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:38,420 : INFO : < 200 OK [3323]
2017-12-31 21:31:38,429 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 0, '_0n0': 993}
2017-12-31 21:31:38,433 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,441 : INFO : < 200 OK [3383]
2017-12-31 21:31:38,448 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 13, '_0n0': 993}
2017-12-31 21:31:38,451 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,457 : INFO : < 200 OK [3409]
2017-12-31 21:31:38,498 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 582, '_0n0': 6}
2017-12-31 21:31:38,502 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,508 : INFO : < 200 OK [3387]
2017-12-31 21:31:38,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 6}
2017-12-31 21:31:38,521 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,527 : INFO : < 200 OK [3349]

2017-12-31 21:31:38,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 352, '_0n0': 12}
2017-12-31 21:31:38,539 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,545 : INFO : < 200 OK [3444]
2017-12-31 21:31:38,554 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1013, '_0n0': 12}
2017-12-31 21:31:38,557 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:38,563 : INFO : < 200 OK [3470]
2017-12-31 21:31:38,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 993, '_0n0': 13}
2017-12-31 21:31:38,576 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,581 : INFO : < 200 OK [3409]
2017-12-31 21:31:38,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 0, '_0n0': 13}
2017-12-31 21:31:38,592 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:38,597 : INFO : < 200 OK [3365]
2017-12-31 21:31:38,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 142, '_0n0': 8}
2017-12-31 21:31:38,609 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,615 : INFO : < 200 OK [3416]
2017-12-31 21:31:38,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 156, '_0n0': 8}
2017-12-31 21:31:38,629 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,635 : INFO : < 200 OK [3430]
2017-12-31 21:31:38,646 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 0, '_0n0': 14}
2017-12-31 21:31:38,649 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:38,654 : INFO : < 200 OK [3370]
2017-12-31 21:31:38,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 589, '_0n0': 10}
2017-12-31 21:31:38,680 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,685 : INFO : < 200 OK [3336]
2017-12-31 21:31:38,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 431, '_0n0': 10}
2017-12-31 21:31:38,695 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,700 : INFO : < 200 OK [3332]
2017-12-31 21:31:38,716 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 987, '_0n0': 11}
2017-12-31 21:31:38,720 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,726 : INFO : < 200 OK [3289]
2017-12-31 21:31:38,735 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 53, '_0n0': 11}
2017-12-31 21:31:38,739 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,745 : INFO : < 200 OK [3310]
2017-12-31 21:31:38,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 465, '_0n0': 32}
2017-12-31 21:31:38,766 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,772 : INFO : < 200 OK [3403]
2017-12-31 21:31:38,778 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 446, '_0n0': 32}
2017-12-31 21:31:38,781 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,786 : INFO : < 200 OK [3355]
2017-12-31 21:31:38,794 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 22, '_0n0': 18}
2017-12-31 21:31:38,798 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,803 : INFO : < 200 OK [3378]
2017-12-31 21:31:38,810 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 13, '_0n0': 18}
2017-12-31 21:31:38,813 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,818 : INFO : < 200 OK [3388]
2017-12-31 21:31:38,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 352, '_0n0': 33}
2017-12-31 21:31:38,832 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,840 : INFO : < 200 OK [3394]
2017-12-31 21:31:38,848 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 435, '_0n0': 33}
2017-12-31 21:31:38,852 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,858 : INFO : < 200 OK [3341]
2017-12-31 21:31:38,866 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 5, '_0n0': 19}
2017-12-31 21:31:38,869 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:38,875 : INFO : < 200 OK [3398]
2017-12-31 21:31:38,882 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 35, '_0n0': 19}
2017-12-31 21:31:38,886 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,891 : INFO : < 200 OK [3409]
2017-12-31 21:31:38,898 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 13, '_0n0': 34}
2017-12-31 21:31:38,901 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,907 : INFO : < 200 OK [3391]
2017-12-31 21:31:38,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 993, '_0n0': 34}
2017-12-31 21:31:38,918 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,923 : INFO : < 200 OK [3409]
2017-12-31 21:31:38,931 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 34, '_0n0': 20}
2017-12-31 21:31:38,934 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,939 : INFO : < 200 OK [3335]
2017-12-31 21:31:38,947 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 371, '_0n0': 20}
2017-12-31 21:31:38,952 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:38,958 : INFO : < 200 OK [3302]
2017-12-31 21:31:38,969 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 0, '_0n0': 35}
2017-12-31 21:31:38,973 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:38,979 : INFO : < 200 OK [3376]

2017-12-31 21:31:38,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 19, '_0n0': 35}
2017-12-31 21:31:38,991 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:38,997 : INFO : < 200 OK [3409]
2017-12-31 21:31:39,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 55, '_0n0': 21}
2017-12-31 21:31:39,008 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,013 : INFO : < 200 OK [3370]
2017-12-31 21:31:39,025 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 22, '_0n0': 36}
2017-12-31 21:31:39,027 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,032 : INFO : < 200 OK [3326]
2017-12-31 21:31:39,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 28, '_0n0': 36}
2017-12-31 21:31:39,044 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,050 : INFO : < 200 OK [3344]
2017-12-31 21:31:39,071 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 219, '_0n0': 37}
2017-12-31 21:31:39,076 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,083 : INFO : < 200 OK [3374]
2017-12-31 21:31:39,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 9, '_0n0': 37}
2017-12-31 21:31:39,097 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:39,103 : INFO : < 200 OK [3329]
2017-12-31 21:31:39,114 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 49, '_0n0': 23}
2017-12-31 21:31:39,118 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,124 : INFO : < 200 OK [3303]
2017-12-31 21:31:39,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 411, '_0n0': 38}
2017-12-31 21:31:39,144 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,152 : INFO : < 200 OK [3389]
2017-12-31 21:31:39,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 41, '_0n0': 38}
2017-12-31 21:31:39,166 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,173 : INFO : < 200 OK [3384]
2017-12-31 21:31:39,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1, '_0n0': 39}
2017-12-31 21:31:39,198 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:39,205 : INFO : < 200 OK [3313]
2017-12-31 21:31:39,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 41, '_0n0': 39}
2017-12-31 21:31:39,218 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,225 : INFO : < 200 OK [3349]
2017-12-31 21:31:39,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 53, '_0n0': 25}
2017-12-31 21:31:39,245 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,254 : INFO : < 200 OK [3357]
2017-12-31 21:31:39,266 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 987, '_0n0': 25}
2017-12-31 21:31:39,271 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,280 : INFO : < 200 OK [3336]
2017-12-31 21:31:39,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 40}
2017-12-31 21:31:39,303 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,311 : INFO : < 200 OK [3365]
2017-12-31 21:31:39,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 13, '_0n0': 26}
2017-12-31 21:31:39,334 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,342 : INFO : < 200 OK [3362]
2017-12-31 21:31:39,355 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 181, '_0n0': 41}
2017-12-31 21:31:39,361 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,368 : INFO : < 200 OK [3396]
2017-12-31 21:31:39,381 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1, '_0n0': 41}
2017-12-31 21:31:39,385 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:39,392 : INFO : < 200 OK [3357]
2017-12-31 21:31:39,422 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 0, '_0n0': 42}
2017-12-31 21:31:39,426 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:39,433 : INFO : < 200 OK [3364]
2017-12-31 21:31:39,445 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 27, '_0n0': 28}
2017-12-31 21:31:39,449 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,457 : INFO : < 200 OK [3382]
2017-12-31 21:31:39,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1013, '_0n0': 29}
2017-12-31 21:31:39,484 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:39,492 : INFO : < 200 OK [3456]
2017-12-31 21:31:39,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 128, '_0n0': 29}
2017-12-31 21:31:39,503 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,510 : INFO : < 200 OK [3429]
2017-12-31 21:31:39,519 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 408, '_0n0': 44}
2017-12-31 21:31:39,524 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,531 : INFO : < 200 OK [3406]
2017-12-31 21:31:39,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 410, '_0n0': 44}
2017-12-31 21:31:39,546 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,555 : INFO : < 200 OK [3401]
2017-12-31 21:31:39,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 30}
2017-12-31 21:31:39,572 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,578 : INFO : < 200 OK [3315]

2017-12-31 21:31:39,591 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 123, '_0n0': 45}
2017-12-31 21:31:39,594 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,600 : INFO : < 200 OK [3330]
2017-12-31 21:31:39,607 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 300, '_0n0': 45}
2017-12-31 21:31:39,610 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,616 : INFO : < 200 OK [3320]
2017-12-31 21:31:39,626 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 987, '_0n0': 31}
2017-12-31 21:31:39,630 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,636 : INFO : < 200 OK [3308]
2017-12-31 21:31:39,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 21, '_0n0': 31}
2017-12-31 21:31:39,648 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,654 : INFO : < 200 OK [3349]
2017-12-31 21:31:39,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 28, '_0n0': 46}
2017-12-31 21:31:39,668 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,674 : INFO : < 200 OK [3406]
2017-12-31 21:31:39,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 27, '_0n0': 46}
2017-12-31 21:31:39,686 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,692 : INFO : < 200 OK [3381]
2017-12-31 21:31:39,703 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 52}
2017-12-31 21:31:39,707 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,715 : INFO : < 200 OK [3342]
2017-12-31 21:31:39,724 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 275, '_0n0': 52}
2017-12-31 21:31:39,728 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,733 : INFO : < 200 OK [3376]
2017-12-31 21:31:39,741 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 552, '_0n0': 47}
2017-12-31 21:31:39,745 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,751 : INFO : < 200 OK [3386]
2017-12-31 21:31:39,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1014, '_0n0': 47}
2017-12-31 21:31:39,763 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:39,769 : INFO : < 200 OK [3380]
2017-12-31 21:31:39,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 25, '_0n0': 53}
2017-12-31 21:31:39,784 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,790 : INFO : < 200 OK [3357]
2017-12-31 21:31:39,799 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 11, '_0n0': 53}
2017-12-31 21:31:39,802 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,808 : INFO : < 200 OK [3310]
2017-12-31 21:31:39,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 49, '_0n0': 48}
2017-12-31 21:31:39,820 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,825 : INFO : < 200 OK [3359]
2017-12-31 21:31:39,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 993, '_0n0': 48}
2017-12-31 21:31:39,836 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,843 : INFO : < 200 OK [3419]
2017-12-31 21:31:39,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 54}
2017-12-31 21:31:39,857 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,864 : INFO : < 200 OK [3351]
2017-12-31 21:31:39,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 993, '_0n0': 54}
2017-12-31 21:31:39,879 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:39,885 : INFO : < 200 OK [3394]
2017-12-31 21:31:39,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1, '_0n0': 49}
2017-12-31 21:31:39,900 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:39,906 : INFO : < 200 OK [3314]
2017-12-31 21:31:39,915 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 23, '_0n0': 49}
2017-12-31 21:31:39,919 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,925 : INFO : < 200 OK [3303]
2017-12-31 21:31:39,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 21, '_0n0': 55}
2017-12-31 21:31:39,939 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,945 : INFO : < 200 OK [3370]
2017-12-31 21:31:39,953 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 84, '_0n0': 55}
2017-12-31 21:31:39,957 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,963 : INFO : < 200 OK [3347]
2017-12-31 21:31:39,979 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 45, '_0n0': 56}
2017-12-31 21:31:39,982 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:39,988 : INFO : < 200 OK [3360]
2017-12-31 21:31:39,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 460, '_0n0': 56}
2017-12-31 21:31:39,999 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,004 : INFO : < 200 OK [3415]
2017-12-31 21:31:40,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 51}
2017-12-31 21:31:40,018 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,024 : INFO : < 200 OK [3356]
2017-12-31 21:31:40,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 275, '_0n0': 51}
2017-12-31 21:31:40,036 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,042 : INFO : < 200 OK [3390]

2017-12-31 21:31:40,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1014, '_0n0': 72}
2017-12-31 21:31:40,065 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:40,071 : INFO : < 200 OK [3317]
2017-12-31 21:31:40,079 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 993, '_0n0': 72}
2017-12-31 21:31:40,083 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,089 : INFO : < 200 OK [3363]
2017-12-31 21:31:40,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 49, '_0n0': 58}
2017-12-31 21:31:40,101 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:40,108 : INFO : < 200 OK [3380]
2017-12-31 21:31:40,115 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 190, '_0n0': 58}
2017-12-31 21:31:40,119 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,125 : INFO : < 200 OK [3445]
2017-12-31 21:31:40,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 346, '_0n0': 59}
2017-12-31 21:31:40,148 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,154 : INFO : < 200 OK [3352]
2017-12-31 21:31:40,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 404, '_0n0': 59}
2017-12-31 21:31:40,166 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,171 : INFO : < 200 OK [3367]
2017-12-31 21:31:40,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 993, '_0n0': 60}
2017-12-31 21:31:40,193 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,199 : INFO : < 200 OK [3396]
2017-12-31 21:31:40,208 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 0, '_0n0': 60}
2017-12-31 21:31:40,212 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:40,218 : INFO : < 200 OK [3352]
2017-12-31 21:31:40,228 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 352, '_0n0': 75}
2017-12-31 21:31:40,231 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,237 : INFO : < 200 OK [3372]
2017-12-31 21:31:40,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 34, '_0n0': 75}
2017-12-31 21:31:40,250 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:40,257 : INFO : < 200 OK [3351]
2017-12-31 21:31:40,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1013, '_0n0': 76}
2017-12-31 21:31:40,278 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:40,284 : INFO : < 200 OK [3460]
2017-12-31 21:31:40,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 5, '_0n0': 76}
2017-12-31 21:31:40,295 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:40,301 : INFO : < 200 OK [3413]
2017-12-31 21:31:40,312 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 561, '_0n0': 62}
2017-12-31 21:31:40,316 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,323 : INFO : < 200 OK [3305]
2017-12-31 21:31:40,332 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 407, '_0n0': 62}
2017-12-31 21:31:40,336 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,341 : INFO : < 200 OK [3307]
2017-12-31 21:31:40,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 0, '_0n0': 77}
2017-12-31 21:31:40,355 : INFO : > POST http://localhost:7474/db/data/cypher [180]
2017-12-31 21:31:40,361 : INFO : < 200 OK [3361]
2017-12-31 21:31:40,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 615, '_0n0': 77}
2017-12-31 21:31:40,374 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,379 : INFO : < 200 OK [3386]
2017-12-31 21:31:40,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 421, '_0n0': 63}
2017-12-31 21:31:40,394 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,400 : INFO : < 200 OK [3370]
2017-12-31 21:31:40,410 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 564, '_0n0': 63}
2017-12-31 21:31:40,414 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,422 : INFO : < 200 OK [3367]
2017-12-31 21:31:40,431 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 10, '_0n0': 78}
2017-12-31 21:31:40,435 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:40,441 : INFO : < 200 OK [3338]
2017-12-31 21:31:40,448 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 259, '_0n0': 78}
2017-12-31 21:31:40,453 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,460 : INFO : < 200 OK [3384]
2017-12-31 21:31:40,468 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 399, '_0n0': 64}
2017-12-31 21:31:40,472 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,477 : INFO : < 200 OK [3385]
2017-12-31 21:31:40,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 517, '_0n0': 64}
2017-12-31 21:31:40,489 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,495 : INFO : < 200 OK [3364]
2017-12-31 21:31:40,506 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 399, '_0n0': 80}
2017-12-31 21:31:40,510 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,515 : INFO : < 200 OK [3381]
2017-12-31 21:31:40,526 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 393, '_0n0': 65}
2017-12-31 21:31:40,530 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,536 : INFO : < 200 OK [3395]

2017-12-31 21:31:40,550 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 68, '_0n0': 81}
2017-12-31 21:31:40,553 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:40,559 : INFO : < 200 OK [3352]
2017-12-31 21:31:40,566 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 81}
2017-12-31 21:31:40,569 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,575 : INFO : < 200 OK [3346]
2017-12-31 21:31:40,584 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 116, '_0n0': 66}
2017-12-31 21:31:40,587 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,593 : INFO : < 200 OK [3421]
2017-12-31 21:31:40,601 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 67, '_0n0': 66}
2017-12-31 21:31:40,605 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:40,610 : INFO : < 200 OK [3402]
2017-12-31 21:31:40,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 81, '_0n0': 68}
2017-12-31 21:31:40,632 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:40,638 : INFO : < 200 OK [3352]
2017-12-31 21:31:40,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 68}
2017-12-31 21:31:40,647 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,652 : INFO : < 200 OK [3347]
2017-12-31 21:31:40,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 89, '_0n0': 84}
2017-12-31 21:31:40,667 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:40,672 : INFO : < 200 OK [3378]
2017-12-31 21:31:40,678 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 602, '_0n0': 69}
2017-12-31 21:31:40,681 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,686 : INFO : < 200 OK [3450]
2017-12-31 21:31:40,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 277, '_0n0': 69}
2017-12-31 21:31:40,697 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,703 : INFO : < 200 OK [3421]
2017-12-31 21:31:40,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 575, '_0n0': 85}
2017-12-31 21:31:40,715 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,720 : INFO : < 200 OK [3380]
2017-12-31 21:31:40,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 592, '_0n0': 85}
2017-12-31 21:31:40,731 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,737 : INFO : < 200 OK [3394]
2017-12-31 21:31:40,753 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 274, '_0n0': 70}
2017-12-31 21:31:40,758 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,766 : INFO : < 200 OK [3343]
2017-12-31 21:31:40,775 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 300, '_0n0': 86}
2017-12-31 21:31:40,778 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,784 : INFO : < 200 OK [3336]
2017-12-31 21:31:40,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 274, '_0n0': 86}
2017-12-31 21:31:40,795 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,801 : INFO : < 200 OK [3333]
2017-12-31 21:31:40,810 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 393, '_0n0': 71}
2017-12-31 21:31:40,814 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,820 : INFO : < 200 OK [3357]
2017-12-31 21:31:40,841 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 557, '_0n0': 93}
2017-12-31 21:31:40,844 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,850 : INFO : < 200 OK [3342]
2017-12-31 21:31:40,857 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 351, '_0n0': 93}
2017-12-31 21:31:40,860 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,866 : INFO : < 200 OK [3327]
2017-12-31 21:31:40,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 465, '_0n0': 88}
2017-12-31 21:31:40,884 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,889 : INFO : < 200 OK [3366]
2017-12-31 21:31:40,898 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 95, '_0n0': 94}
2017-12-31 21:31:40,902 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:40,908 : INFO : < 200 OK [3366]
2017-12-31 21:31:40,915 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 214, '_0n0': 94}
2017-12-31 21:31:40,919 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,925 : INFO : < 200 OK [3366]
2017-12-31 21:31:40,952 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 96, '_0n0': 95}
2017-12-31 21:31:40,956 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:40,962 : INFO : < 200 OK [3401]
2017-12-31 21:31:40,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 619, '_0n0': 90}
2017-12-31 21:31:40,976 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:40,981 : INFO : < 200 OK [3386]
2017-12-31 21:31:40,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 85, '_0n0': 90}
2017-12-31 21:31:40,992 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:40,998 : INFO : < 200 OK [3344]
2017-12-31 21:31:41,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 98, '_0n0': 91}
2017-12-31 21:31:41,017 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:41,024 : INFO : < 200 OK [3359]

2017-12-31 21:31:41,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 476, '_0n0': 91}
2017-12-31 21:31:41,033 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:41,038 : INFO : < 200 OK [3345]
2017-12-31 21:31:41,047 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 578, '_0n0': 97}
2017-12-31 21:31:41,050 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:41,055 : INFO : < 200 OK [3426]
2017-12-31 21:31:41,064 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 116, '_0n0': 92}
2017-12-31 21:31:41,067 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:41,072 : INFO : < 200 OK [3423]
2017-12-31 21:31:41,077 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 66, '_0n0': 92}
2017-12-31 21:31:41,080 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:41,086 : INFO : < 200 OK [3355]
2017-12-31 21:31:41,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 91, '_0n0': 98}
2017-12-31 21:31:41,101 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:41,107 : INFO : < 200 OK [3359]
2017-12-31 21:31:41,116 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 132, '_0n0': 113}
2017-12-31 21:31:41,119 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,123 : INFO : < 200 OK [3369]
2017-12-31 21:31:41,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 113}
2017-12-31 21:31:41,134 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,140 : INFO : < 200 OK [3368]
2017-12-31 21:31:41,156 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 108, '_0n0': 99}
2017-12-31 21:31:41,160 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:41,165 : INFO : < 200 OK [3391]
2017-12-31 21:31:41,173 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 464, '_0n0': 114}
2017-12-31 21:31:41,176 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,182 : INFO : < 200 OK [3324]
2017-12-31 21:31:41,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 534, '_0n0': 114}
2017-12-31 21:31:41,193 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,198 : INFO : < 200 OK [3379]
2017-12-31 21:31:41,208 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 116, '_0n0': 100}
2017-12-31 21:31:41,211 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,217 : INFO : < 200 OK [3447]
2017-12-31 21:31:41,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 108, '_0n0': 115}
2017-12-31 21:31:41,235 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,239 : INFO : < 200 OK [3408]
2017-12-31 21:31:41,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 332, '_0n0': 101}
2017-12-31 21:31:41,254 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,259 : INFO : < 200 OK [3381]
2017-12-31 21:31:41,266 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 100, '_0n0': 116}
2017-12-31 21:31:41,269 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,274 : INFO : < 200 OK [3447]
2017-12-31 21:31:41,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 434, '_0n0': 102}
2017-12-31 21:31:41,295 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,301 : INFO : < 200 OK [3345]
2017-12-31 21:31:41,308 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 529, '_0n0': 117}
2017-12-31 21:31:41,312 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,319 : INFO : < 200 OK [3381]
2017-12-31 21:31:41,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 201, '_0n0': 117}
2017-12-31 21:31:41,331 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,337 : INFO : < 200 OK [3414]
2017-12-31 21:31:41,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 40, '_0n0': 104}
2017-12-31 21:31:41,360 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:41,366 : INFO : < 200 OK [3393]
2017-12-31 21:31:41,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 132, '_0n0': 104}
2017-12-31 21:31:41,377 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,382 : INFO : < 200 OK [3370]
2017-12-31 21:31:41,389 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 565, '_0n0': 119}
2017-12-31 21:31:41,392 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,398 : INFO : < 200 OK [3356]
2017-12-31 21:31:41,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 433, '_0n0': 119}
2017-12-31 21:31:41,406 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,412 : INFO : < 200 OK [3408]
2017-12-31 21:31:41,421 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 98, '_0n0': 120}
2017-12-31 21:31:41,425 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:41,430 : INFO : < 200 OK [3393]
2017-12-31 21:31:41,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 396, '_0n0': 120}
2017-12-31 21:31:41,440 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,445 : INFO : < 200 OK [3417]
2017-12-31 21:31:41,454 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 378, '_0n0': 106}
2017-12-31 21:31:41,457 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,463 : INFO : < 200 OK [3402]

2017-12-31 21:31:41,471 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 396, '_0n0': 106}
2017-12-31 21:31:41,475 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,480 : INFO : < 200 OK [3416]
2017-12-31 21:31:41,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 205, '_0n0': 122}
2017-12-31 21:31:41,503 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,510 : INFO : < 200 OK [3416]
2017-12-31 21:31:41,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 454, '_0n0': 122}
2017-12-31 21:31:41,520 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,525 : INFO : < 200 OK [3392]
2017-12-31 21:31:41,534 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 115, '_0n0': 108}
2017-12-31 21:31:41,537 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,542 : INFO : < 200 OK [3408]
2017-12-31 21:31:41,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 590, '_0n0': 108}
2017-12-31 21:31:41,553 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,558 : INFO : < 200 OK [3412]
2017-12-31 21:31:41,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 300, '_0n0': 123}
2017-12-31 21:31:41,571 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,576 : INFO : < 200 OK [3333]
2017-12-31 21:31:41,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 100, '_0n0': 124}
2017-12-31 21:31:41,591 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,598 : INFO : < 200 OK [3387]
2017-12-31 21:31:41,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 116, '_0n0': 124}
2017-12-31 21:31:41,611 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,617 : INFO : < 200 OK [3429]
2017-12-31 21:31:41,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 110}
2017-12-31 21:31:41,636 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,642 : INFO : < 200 OK [3383]
2017-12-31 21:31:41,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 66, '_0n0': 125}
2017-12-31 21:31:41,659 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:41,664 : INFO : < 200 OK [3378]
2017-12-31 21:31:41,670 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 128, '_0n0': 111}
2017-12-31 21:31:41,673 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,678 : INFO : < 200 OK [3432]
2017-12-31 21:31:41,684 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 127, '_0n0': 111}
2017-12-31 21:31:41,686 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,691 : INFO : < 200 OK [3421]
2017-12-31 21:31:41,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 275, '_0n0': 126}
2017-12-31 21:31:41,702 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,708 : INFO : < 200 OK [3375]
2017-12-31 21:31:41,716 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 304, '_0n0': 126}
2017-12-31 21:31:41,719 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,725 : INFO : < 200 OK [3356]
2017-12-31 21:31:41,740 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 128, '_0n0': 127}
2017-12-31 21:31:41,744 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,749 : INFO : < 200 OK [3420]
2017-12-31 21:31:41,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 111, '_0n0': 127}
2017-12-31 21:31:41,759 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,765 : INFO : < 200 OK [3421]
2017-12-31 21:31:41,782 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 127, '_0n0': 128}
2017-12-31 21:31:41,785 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,790 : INFO : < 200 OK [3420]
2017-12-31 21:31:41,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 111, '_0n0': 128}
2017-12-31 21:31:41,800 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,805 : INFO : < 200 OK [3432]
2017-12-31 21:31:41,820 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 122, '_0n0': 129}
2017-12-31 21:31:41,824 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,830 : INFO : < 200 OK [3391]
2017-12-31 21:31:41,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 52, '_0n0': 129}
2017-12-31 21:31:41,842 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:41,848 : INFO : < 200 OK [3368]
2017-12-31 21:31:41,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 316, '_0n0': 137}
2017-12-31 21:31:41,883 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,888 : INFO : < 200 OK [3359]
2017-12-31 21:31:41,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 318, '_0n0': 137}
2017-12-31 21:31:41,897 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,903 : INFO : < 200 OK [3393]
2017-12-31 21:31:41,911 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 132}
2017-12-31 21:31:41,916 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,923 : INFO : < 200 OK [3342]
2017-12-31 21:31:41,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 275, '_0n0': 132}
2017-12-31 21:31:41,933 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,939 : INFO : < 200 OK [3376]

2017-12-31 21:31:41,947 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 110, '_0n0': 138}
2017-12-31 21:31:41,951 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,957 : INFO : < 200 OK [3374]
2017-12-31 21:31:41,966 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 133, '_0n0': 138}
2017-12-31 21:31:41,969 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,975 : INFO : < 200 OK [3411]
2017-12-31 21:31:41,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 427, '_0n0': 153}
2017-12-31 21:31:41,987 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:41,992 : INFO : < 200 OK [3358]
2017-12-31 21:31:41,999 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 537, '_0n0': 153}
2017-12-31 21:31:42,002 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,007 : INFO : < 200 OK [3380]
2017-12-31 21:31:42,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 158, '_0n0': 139}
2017-12-31 21:31:42,019 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,024 : INFO : < 200 OK [3432]
2017-12-31 21:31:42,032 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 431, '_0n0': 139}
2017-12-31 21:31:42,035 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,041 : INFO : < 200 OK [3379]
2017-12-31 21:31:42,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 417, '_0n0': 154}
2017-12-31 21:31:42,054 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,061 : INFO : < 200 OK [3370]
2017-12-31 21:31:42,068 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 265, '_0n0': 154}
2017-12-31 21:31:42,071 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,076 : INFO : < 200 OK [3420]
2017-12-31 21:31:42,084 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 439, '_0n0': 140}
2017-12-31 21:31:42,086 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,092 : INFO : < 200 OK [3417]
2017-12-31 21:31:42,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 401, '_0n0': 140}
2017-12-31 21:31:42,102 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,108 : INFO : < 200 OK [3380]
2017-12-31 21:31:42,114 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 343, '_0n0': 155}
2017-12-31 21:31:42,116 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,122 : INFO : < 200 OK [3390]
2017-12-31 21:31:42,128 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 465, '_0n0': 155}
2017-12-31 21:31:42,131 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,137 : INFO : < 200 OK [3399]
2017-12-31 21:31:42,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 400, '_0n0': 156}
2017-12-31 21:31:42,152 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,157 : INFO : < 200 OK [3460]
2017-12-31 21:31:42,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 8, '_0n0': 142}
2017-12-31 21:31:42,172 : INFO : > POST http://localhost:7474/db/data/cypher [181]
2017-12-31 21:31:42,178 : INFO : < 200 OK [3416]
2017-12-31 21:31:42,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 482, '_0n0': 143}
2017-12-31 21:31:42,200 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,206 : INFO : < 200 OK [3428]
2017-12-31 21:31:42,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 477, '_0n0': 143}
2017-12-31 21:31:42,217 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,222 : INFO : < 200 OK [3438]
2017-12-31 21:31:42,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 431, '_0n0': 158}
2017-12-31 21:31:42,234 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,240 : INFO : < 200 OK [3386]
2017-12-31 21:31:42,252 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 144}
2017-12-31 21:31:42,255 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,261 : INFO : < 200 OK [3398]
2017-12-31 21:31:42,269 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 207, '_0n0': 159}
2017-12-31 21:31:42,272 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,278 : INFO : < 200 OK [3356]
2017-12-31 21:31:42,286 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 208, '_0n0': 159}
2017-12-31 21:31:42,291 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,297 : INFO : < 200 OK [3432]
2017-12-31 21:31:42,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 145}
2017-12-31 21:31:42,308 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,313 : INFO : < 200 OK [3373]
2017-12-31 21:31:42,319 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 170, '_0n0': 145}
2017-12-31 21:31:42,323 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,328 : INFO : < 200 OK [3386]
2017-12-31 21:31:42,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 311, '_0n0': 160}
2017-12-31 21:31:42,345 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,350 : INFO : < 200 OK [3404]
2017-12-31 21:31:42,365 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 173, '_0n0': 161}
2017-12-31 21:31:42,369 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,374 : INFO : < 200 OK [3393]

2017-12-31 21:31:42,381 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 180, '_0n0': 161}
2017-12-31 21:31:42,385 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,390 : INFO : < 200 OK [3395]
2017-12-31 21:31:42,397 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 179, '_0n0': 147}
2017-12-31 21:31:42,400 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,405 : INFO : < 200 OK [3291]
2017-12-31 21:31:42,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 174, '_0n0': 147}
2017-12-31 21:31:42,415 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,420 : INFO : < 200 OK [3322]
2017-12-31 21:31:42,427 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 36, '_0n0': 162}
2017-12-31 21:31:42,430 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:42,435 : INFO : < 200 OK [3361]
2017-12-31 21:31:42,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 583, '_0n0': 162}
2017-12-31 21:31:42,447 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,454 : INFO : < 200 OK [3432]
2017-12-31 21:31:42,465 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 316, '_0n0': 148}
2017-12-31 21:31:42,468 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,474 : INFO : < 200 OK [3369]
2017-12-31 21:31:42,498 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 149}
2017-12-31 21:31:42,501 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,506 : INFO : < 200 OK [3343]
2017-12-31 21:31:42,516 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 62, '_0n0': 164}
2017-12-31 21:31:42,519 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:42,525 : INFO : < 200 OK [3340]
2017-12-31 21:31:42,534 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 407, '_0n0': 164}
2017-12-31 21:31:42,538 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,545 : INFO : < 200 OK [3354]
2017-12-31 21:31:42,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 85, '_0n0': 150}
2017-12-31 21:31:42,561 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:42,566 : INFO : < 200 OK [3343]
2017-12-31 21:31:42,574 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 186, '_0n0': 165}
2017-12-31 21:31:42,578 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,583 : INFO : < 200 OK [3413]
2017-12-31 21:31:42,590 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 988, '_0n0': 165}
2017-12-31 21:31:42,594 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,600 : INFO : < 200 OK [3390]
2017-12-31 21:31:42,613 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 346, '_0n0': 166}
2017-12-31 21:31:42,616 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,622 : INFO : < 200 OK [3404]
2017-12-31 21:31:42,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 417, '_0n0': 166}
2017-12-31 21:31:42,630 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,635 : INFO : < 200 OK [3392]
2017-12-31 21:31:42,658 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 284, '_0n0': 167}
2017-12-31 21:31:42,662 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,667 : INFO : < 200 OK [3353]
2017-12-31 21:31:42,685 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 115, '_0n0': 168}
2017-12-31 21:31:42,689 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,695 : INFO : < 200 OK [3408]
2017-12-31 21:31:42,703 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 29, '_0n0': 168}
2017-12-31 21:31:42,707 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:42,713 : INFO : < 200 OK [3418]
2017-12-31 21:31:42,724 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 179, '_0n0': 174}
2017-12-31 21:31:42,727 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,733 : INFO : < 200 OK [3360]
2017-12-31 21:31:42,742 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 288, '_0n0': 174}
2017-12-31 21:31:42,746 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,751 : INFO : < 200 OK [3383]
2017-12-31 21:31:42,764 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 604, '_0n0': 169}
2017-12-31 21:31:42,767 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,773 : INFO : < 200 OK [3394]
2017-12-31 21:31:42,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 609, '_0n0': 170}
2017-12-31 21:31:42,794 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,799 : INFO : < 200 OK [3376]
2017-12-31 21:31:42,813 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 326, '_0n0': 176}
2017-12-31 21:31:42,816 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,822 : INFO : < 200 OK [3360]
2017-12-31 21:31:42,836 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 369, '_0n0': 171}
2017-12-31 21:31:42,839 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,845 : INFO : < 200 OK [3406]
2017-12-31 21:31:42,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 368, '_0n0': 172}
2017-12-31 21:31:42,874 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,880 : INFO : < 200 OK [3379]

2017-12-31 21:31:42,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 303, '_0n0': 172}
2017-12-31 21:31:42,892 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,898 : INFO : < 200 OK [3395]
2017-12-31 21:31:42,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 326, '_0n0': 178}
2017-12-31 21:31:42,916 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,922 : INFO : < 200 OK [3401]
2017-12-31 21:31:42,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 132, '_0n0': 193}
2017-12-31 21:31:42,936 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,942 : INFO : < 200 OK [3350]
2017-12-31 21:31:42,952 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 193}
2017-12-31 21:31:42,955 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,963 : INFO : < 200 OK [3349]
2017-12-31 21:31:42,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 288, '_0n0': 179}
2017-12-31 21:31:42,978 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:42,984 : INFO : < 200 OK [3352]
2017-12-31 21:31:42,995 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 174, '_0n0': 179}
2017-12-31 21:31:42,998 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,005 : INFO : < 200 OK [3360]
2017-12-31 21:31:43,018 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 612, '_0n0': 194}
2017-12-31 21:31:43,022 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,030 : INFO : < 200 OK [3351]
2017-12-31 21:31:43,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 379, '_0n0': 195}
2017-12-31 21:31:43,064 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,071 : INFO : < 200 OK [3324]
2017-12-31 21:31:43,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 41, '_0n0': 181}
2017-12-31 21:31:43,085 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:43,092 : INFO : < 200 OK [3396]
2017-12-31 21:31:43,101 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 358, '_0n0': 181}
2017-12-31 21:31:43,105 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,112 : INFO : < 200 OK [3410]
2017-12-31 21:31:43,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 145, '_0n0': 196}
2017-12-31 21:31:43,128 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,134 : INFO : < 200 OK [3369]
2017-12-31 21:31:43,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 332, '_0n0': 196}
2017-12-31 21:31:43,148 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,153 : INFO : < 200 OK [3349]
2017-12-31 21:31:43,165 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 323, '_0n0': 182}
2017-12-31 21:31:43,168 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,173 : INFO : < 200 OK [3336]
2017-12-31 21:31:43,181 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 41, '_0n0': 182}
2017-12-31 21:31:43,185 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:43,191 : INFO : < 200 OK [3354]
2017-12-31 21:31:43,214 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 246, '_0n0': 183}
2017-12-31 21:31:43,218 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,224 : INFO : < 200 OK [3444]
2017-12-31 21:31:43,237 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 484, '_0n0': 198}
2017-12-31 21:31:43,243 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,249 : INFO : < 200 OK [3404]
2017-12-31 21:31:43,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 300, '_0n0': 184}
2017-12-31 21:31:43,264 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,270 : INFO : < 200 OK [3333]
2017-12-31 21:31:43,280 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 274, '_0n0': 184}
2017-12-31 21:31:43,284 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,291 : INFO : < 200 OK [3330]
2017-12-31 21:31:43,319 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 421, '_0n0': 200}
2017-12-31 21:31:43,323 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,329 : INFO : < 200 OK [3349]
2017-12-31 21:31:43,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 203, '_0n0': 200}
2017-12-31 21:31:43,340 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,346 : INFO : < 200 OK [3389]
2017-12-31 21:31:43,353 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 165, '_0n0': 186}
2017-12-31 21:31:43,358 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,364 : INFO : < 200 OK [3413]
2017-12-31 21:31:43,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 420, '_0n0': 186}
2017-12-31 21:31:43,373 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,380 : INFO : < 200 OK [3422]
2017-12-31 21:31:43,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 201, '_0n0': 202}
2017-12-31 21:31:43,420 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,428 : INFO : < 200 OK [3373]
2017-12-31 21:31:43,436 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 202}
2017-12-31 21:31:43,441 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,447 : INFO : < 200 OK [3331]

2017-12-31 21:31:43,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 179, '_0n0': 188}
2017-12-31 21:31:43,461 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,467 : INFO : < 200 OK [3332]
2017-12-31 21:31:43,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 203}
2017-12-31 21:31:43,483 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,488 : INFO : < 200 OK [3389]
2017-12-31 21:31:43,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 178, '_0n0': 203}
2017-12-31 21:31:43,499 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,505 : INFO : < 200 OK [3426]
2017-12-31 21:31:43,513 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 58, '_0n0': 189}
2017-12-31 21:31:43,516 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:43,521 : INFO : < 200 OK [3455]
2017-12-31 21:31:43,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 580, '_0n0': 189}
2017-12-31 21:31:43,533 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,539 : INFO : < 200 OK [3450]
2017-12-31 21:31:43,550 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 445, '_0n0': 204}
2017-12-31 21:31:43,553 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,559 : INFO : < 200 OK [3342]
2017-12-31 21:31:43,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 58, '_0n0': 190}
2017-12-31 21:31:43,576 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:43,584 : INFO : < 200 OK [3445]
2017-12-31 21:31:43,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 600, '_0n0': 190}
2017-12-31 21:31:43,597 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,603 : INFO : < 200 OK [3411]
2017-12-31 21:31:43,614 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 122, '_0n0': 205}
2017-12-31 21:31:43,618 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,627 : INFO : < 200 OK [3416]
2017-12-31 21:31:43,633 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 251, '_0n0': 205}
2017-12-31 21:31:43,637 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,645 : INFO : < 200 OK [3417]
2017-12-31 21:31:43,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 355, '_0n0': 191}
2017-12-31 21:31:43,659 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,665 : INFO : < 200 OK [3342]
2017-12-31 21:31:43,675 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 246, '_0n0': 191}
2017-12-31 21:31:43,678 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,684 : INFO : < 200 OK [3374]
2017-12-31 21:31:43,695 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 206}
2017-12-31 21:31:43,698 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,704 : INFO : < 200 OK [3340]
2017-12-31 21:31:43,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 179, '_0n0': 192}
2017-12-31 21:31:43,718 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,724 : INFO : < 200 OK [3351]
2017-12-31 21:31:43,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 288, '_0n0': 192}
2017-12-31 21:31:43,738 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,745 : INFO : < 200 OK [3374]
2017-12-31 21:31:43,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 218, '_0n0': 207}
2017-12-31 21:31:43,756 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,762 : INFO : < 200 OK [3370]
2017-12-31 21:31:43,769 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 210, '_0n0': 207}
2017-12-31 21:31:43,772 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,778 : INFO : < 200 OK [3336]
2017-12-31 21:31:43,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 102, '_0n0': 213}
2017-12-31 21:31:43,789 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,794 : INFO : < 200 OK [3371]
2017-12-31 21:31:43,801 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 304, '_0n0': 213}
2017-12-31 21:31:43,804 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,809 : INFO : < 200 OK [3381]
2017-12-31 21:31:43,819 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 452, '_0n0': 208}
2017-12-31 21:31:43,824 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,830 : INFO : < 200 OK [3444]
2017-12-31 21:31:43,839 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 159, '_0n0': 208}
2017-12-31 21:31:43,843 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,851 : INFO : < 200 OK [3432]
2017-12-31 21:31:43,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 257, '_0n0': 209}
2017-12-31 21:31:43,876 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,882 : INFO : < 200 OK [3364]
2017-12-31 21:31:43,891 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 387, '_0n0': 209}
2017-12-31 21:31:43,895 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,901 : INFO : < 200 OK [3316]
2017-12-31 21:31:43,919 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 207, '_0n0': 210}
2017-12-31 21:31:43,924 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,929 : INFO : < 200 OK [3336]

2017-12-31 21:31:43,936 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 218, '_0n0': 210}
2017-12-31 21:31:43,940 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,946 : INFO : < 200 OK [3373]
2017-12-31 21:31:43,954 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 988, '_0n0': 216}
2017-12-31 21:31:43,957 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,963 : INFO : < 200 OK [3375]
2017-12-31 21:31:43,970 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 398, '_0n0': 216}
2017-12-31 21:31:43,974 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:43,980 : INFO : < 200 OK [3361]
2017-12-31 21:31:43,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 223, '_0n0': 211}
2017-12-31 21:31:43,993 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,002 : INFO : < 200 OK [3428]
2017-12-31 21:31:44,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 218, '_0n0': 211}
2017-12-31 21:31:44,016 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,024 : INFO : < 200 OK [3422]
2017-12-31 21:31:44,045 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 417, '_0n0': 212}
2017-12-31 21:31:44,048 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,055 : INFO : < 200 OK [3352]
2017-12-31 21:31:44,064 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 265, '_0n0': 212}
2017-12-31 21:31:44,068 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,074 : INFO : < 200 OK [3402]
2017-12-31 21:31:44,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 207, '_0n0': 218}
2017-12-31 21:31:44,086 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,092 : INFO : < 200 OK [3370]
2017-12-31 21:31:44,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 210, '_0n0': 218}
2017-12-31 21:31:44,102 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,108 : INFO : < 200 OK [3373]
2017-12-31 21:31:44,116 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 539, '_0n0': 252}
2017-12-31 21:31:44,120 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,130 : INFO : < 200 OK [3389]
2017-12-31 21:31:44,140 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 193, '_0n0': 252}
2017-12-31 21:31:44,144 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,150 : INFO : < 200 OK [3387]
2017-12-31 21:31:44,160 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 37, '_0n0': 219}
2017-12-31 21:31:44,164 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:44,170 : INFO : < 200 OK [3374]
2017-12-31 21:31:44,178 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 52, '_0n0': 219}
2017-12-31 21:31:44,182 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:44,188 : INFO : < 200 OK [3377]
2017-12-31 21:31:44,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 223, '_0n0': 253}
2017-12-31 21:31:44,202 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,209 : INFO : < 200 OK [3364]
2017-12-31 21:31:44,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 154, '_0n0': 253}
2017-12-31 21:31:44,222 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,229 : INFO : < 200 OK [3352]
2017-12-31 21:31:44,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 516, '_0n0': 254}
2017-12-31 21:31:44,255 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,263 : INFO : < 200 OK [3345]
2017-12-31 21:31:44,270 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 254}
2017-12-31 21:31:44,276 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,282 : INFO : < 200 OK [3389]
2017-12-31 21:31:44,293 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 325, '_0n0': 221}
2017-12-31 21:31:44,298 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,307 : INFO : < 200 OK [3380]
2017-12-31 21:31:44,317 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 327, '_0n0': 221}
2017-12-31 21:31:44,322 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,329 : INFO : < 200 OK [3407]
2017-12-31 21:31:44,338 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 321, '_0n0': 255}
2017-12-31 21:31:44,343 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,350 : INFO : < 200 OK [3317]
2017-12-31 21:31:44,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 331, '_0n0': 255}
2017-12-31 21:31:44,363 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,370 : INFO : < 200 OK [3316]
2017-12-31 21:31:44,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 209, '_0n0': 257}
2017-12-31 21:31:44,419 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,428 : INFO : < 200 OK [3364]
2017-12-31 21:31:44,453 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 507, '_0n0': 258}
2017-12-31 21:31:44,458 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,464 : INFO : < 200 OK [3410]
2017-12-31 21:31:44,474 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 630, '_0n0': 258}
2017-12-31 21:31:44,478 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,483 : INFO : < 200 OK [3442]

2017-12-31 21:31:44,492 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 96, '_0n0': 244}
2017-12-31 21:31:44,496 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:44,503 : INFO : < 200 OK [3427]
2017-12-31 21:31:44,510 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 95, '_0n0': 244}
2017-12-31 21:31:44,513 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:44,519 : INFO : < 200 OK [3381]
2017-12-31 21:31:44,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 245, '_0n0': 259}
2017-12-31 21:31:44,532 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,538 : INFO : < 200 OK [3452]
2017-12-31 21:31:44,546 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 207, '_0n0': 259}
2017-12-31 21:31:44,549 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,555 : INFO : < 200 OK [3378]
2017-12-31 21:31:44,564 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 259, '_0n0': 245}
2017-12-31 21:31:44,567 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,575 : INFO : < 200 OK [3452]
2017-12-31 21:31:44,580 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 132, '_0n0': 245}
2017-12-31 21:31:44,584 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,590 : INFO : < 200 OK [3412]
2017-12-31 21:31:44,598 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 357, '_0n0': 260}
2017-12-31 21:31:44,602 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,609 : INFO : < 200 OK [3376]
2017-12-31 21:31:44,617 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 321, '_0n0': 260}
2017-12-31 21:31:44,620 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,628 : INFO : < 200 OK [3368]
2017-12-31 21:31:44,637 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 355, '_0n0': 246}
2017-12-31 21:31:44,642 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,647 : INFO : < 200 OK [3401]
2017-12-31 21:31:44,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 567, '_0n0': 246}
2017-12-31 21:31:44,659 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,665 : INFO : < 200 OK [3396]
2017-12-31 21:31:44,676 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 355, '_0n0': 261}
2017-12-31 21:31:44,679 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,685 : INFO : < 200 OK [3387]
2017-12-31 21:31:44,695 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 471, '_0n0': 247}
2017-12-31 21:31:44,699 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,705 : INFO : < 200 OK [3371]
2017-12-31 21:31:44,713 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 158, '_0n0': 247}
2017-12-31 21:31:44,717 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,723 : INFO : < 200 OK [3408]
2017-12-31 21:31:44,732 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 262}
2017-12-31 21:31:44,736 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,743 : INFO : < 200 OK [3424]
2017-12-31 21:31:44,750 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 584, '_0n0': 262}
2017-12-31 21:31:44,753 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,759 : INFO : < 200 OK [3416]
2017-12-31 21:31:44,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 288, '_0n0': 248}
2017-12-31 21:31:44,771 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,777 : INFO : < 200 OK [3367]
2017-12-31 21:31:44,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 179, '_0n0': 248}
2017-12-31 21:31:44,787 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,794 : INFO : < 200 OK [3344]
2017-12-31 21:31:44,801 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 547, '_0n0': 263}
2017-12-31 21:31:44,805 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,811 : INFO : < 200 OK [3379]
2017-12-31 21:31:44,818 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 461, '_0n0': 263}
2017-12-31 21:31:44,822 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,829 : INFO : < 200 OK [3362]
2017-12-31 21:31:44,837 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 290, '_0n0': 249}
2017-12-31 21:31:44,841 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,847 : INFO : < 200 OK [3342]
2017-12-31 21:31:44,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 269, '_0n0': 249}
2017-12-31 21:31:44,859 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,864 : INFO : < 200 OK [3325]
2017-12-31 21:31:44,873 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 339, '_0n0': 264}
2017-12-31 21:31:44,876 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,881 : INFO : < 200 OK [3395]
2017-12-31 21:31:44,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 988, '_0n0': 264}
2017-12-31 21:31:44,891 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,897 : INFO : < 200 OK [3394]
2017-12-31 21:31:44,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 207, '_0n0': 250}
2017-12-31 21:31:44,909 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,914 : INFO : < 200 OK [3360]

2017-12-31 21:31:44,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 285, '_0n0': 250}
2017-12-31 21:31:44,925 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,931 : INFO : < 200 OK [3406]
2017-12-31 21:31:44,940 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 417, '_0n0': 265}
2017-12-31 21:31:44,943 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,948 : INFO : < 200 OK [3395]
2017-12-31 21:31:44,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 505, '_0n0': 265}
2017-12-31 21:31:44,959 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,965 : INFO : < 200 OK [3440]
2017-12-31 21:31:44,973 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 290, '_0n0': 251}
2017-12-31 21:31:44,976 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,981 : INFO : < 200 OK [3386]
2017-12-31 21:31:44,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 268, '_0n0': 251}
2017-12-31 21:31:44,992 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:44,998 : INFO : < 200 OK [3386]
2017-12-31 21:31:45,007 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 988, '_0n0': 266}
2017-12-31 21:31:45,011 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,017 : INFO : < 200 OK [3378]
2017-12-31 21:31:45,023 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 216, '_0n0': 266}
2017-12-31 21:31:45,027 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,033 : INFO : < 200 OK [3352]
2017-12-31 21:31:45,042 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 251, '_0n0': 272}
2017-12-31 21:31:45,045 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,051 : INFO : < 200 OK [3394]
2017-12-31 21:31:45,058 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 249, '_0n0': 272}
2017-12-31 21:31:45,061 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,067 : INFO : < 200 OK [3350]
2017-12-31 21:31:45,077 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 265, '_0n0': 267}
2017-12-31 21:31:45,080 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,086 : INFO : < 200 OK [3437]
2017-12-31 21:31:45,094 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 417, '_0n0': 267}
2017-12-31 21:31:45,098 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,104 : INFO : < 200 OK [3387]
2017-12-31 21:31:45,115 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 538, '_0n0': 273}
2017-12-31 21:31:45,118 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,124 : INFO : < 200 OK [3376]
2017-12-31 21:31:45,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 265, '_0n0': 273}
2017-12-31 21:31:45,135 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,141 : INFO : < 200 OK [3387]
2017-12-31 21:31:45,149 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 251, '_0n0': 268}
2017-12-31 21:31:45,153 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,160 : INFO : < 200 OK [3386]
2017-12-31 21:31:45,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 580, '_0n0': 268}
2017-12-31 21:31:45,172 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,178 : INFO : < 200 OK [3412]
2017-12-31 21:31:45,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 295, '_0n0': 274}
2017-12-31 21:31:45,188 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,195 : INFO : < 200 OK [3297]
2017-12-31 21:31:45,201 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 300, '_0n0': 274}
2017-12-31 21:31:45,205 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,211 : INFO : < 200 OK [3320]
2017-12-31 21:31:45,219 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 295, '_0n0': 269}
2017-12-31 21:31:45,223 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,229 : INFO : < 200 OK [3312]
2017-12-31 21:31:45,236 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 274, '_0n0': 269}
2017-12-31 21:31:45,241 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,247 : INFO : < 200 OK [3332]
2017-12-31 21:31:45,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 275}
2017-12-31 21:31:45,258 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,264 : INFO : < 200 OK [3375]
2017-12-31 21:31:45,272 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 304, '_0n0': 275}
2017-12-31 21:31:45,275 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,280 : INFO : < 200 OK [3390]
2017-12-31 21:31:45,288 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 292, '_0n0': 270}
2017-12-31 21:31:45,292 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,298 : INFO : < 200 OK [3406]
2017-12-31 21:31:45,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 473, '_0n0': 270}
2017-12-31 21:31:45,308 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,312 : INFO : < 200 OK [3436]
2017-12-31 21:31:45,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 360, '_0n0': 276}
2017-12-31 21:31:45,324 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,330 : INFO : < 200 OK [3362]

2017-12-31 21:31:45,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 367, '_0n0': 276}
2017-12-31 21:31:45,341 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,347 : INFO : < 200 OK [3386]
2017-12-31 21:31:45,355 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 354, '_0n0': 271}
2017-12-31 21:31:45,359 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,364 : INFO : < 200 OK [3380]
2017-12-31 21:31:45,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 349, '_0n0': 271}
2017-12-31 21:31:45,374 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,379 : INFO : < 200 OK [3403]
2017-12-31 21:31:45,386 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 602, '_0n0': 277}
2017-12-31 21:31:45,390 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,396 : INFO : < 200 OK [3440]
2017-12-31 21:31:45,402 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 69, '_0n0': 277}
2017-12-31 21:31:45,406 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:45,411 : INFO : < 200 OK [3421]
2017-12-31 21:31:45,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 270, '_0n0': 292}
2017-12-31 21:31:45,423 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,429 : INFO : < 200 OK [3406]
2017-12-31 21:31:45,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 456, '_0n0': 292}
2017-12-31 21:31:45,440 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,445 : INFO : < 200 OK [3411]
2017-12-31 21:31:45,454 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 120, '_0n0': 278}
2017-12-31 21:31:45,459 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,464 : INFO : < 200 OK [3390]
2017-12-31 21:31:45,473 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 95, '_0n0': 278}
2017-12-31 21:31:45,477 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:45,482 : INFO : < 200 OK [3356]
2017-12-31 21:31:45,490 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 361, '_0n0': 293}
2017-12-31 21:31:45,494 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,499 : INFO : < 200 OK [3381]
2017-12-31 21:31:45,505 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 299, '_0n0': 293}
2017-12-31 21:31:45,509 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,515 : INFO : < 200 OK [3461]
2017-12-31 21:31:45,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 293, '_0n0': 279}
2017-12-31 21:31:45,528 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,535 : INFO : < 200 OK [3417]
2017-12-31 21:31:45,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 161, '_0n0': 279}
2017-12-31 21:31:45,548 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,553 : INFO : < 200 OK [3386]
2017-12-31 21:31:45,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 396, '_0n0': 294}
2017-12-31 21:31:45,566 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,571 : INFO : < 200 OK [3378]
2017-12-31 21:31:45,578 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 414, '_0n0': 294}
2017-12-31 21:31:45,582 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,587 : INFO : < 200 OK [3352]
2017-12-31 21:31:45,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 286, '_0n0': 280}
2017-12-31 21:31:45,598 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,604 : INFO : < 200 OK [3420]
2017-12-31 21:31:45,610 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 113, '_0n0': 280}
2017-12-31 21:31:45,614 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,619 : INFO : < 200 OK [3404]
2017-12-31 21:31:45,628 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 274, '_0n0': 295}
2017-12-31 21:31:45,631 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,636 : INFO : < 200 OK [3297]
2017-12-31 21:31:45,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 300, '_0n0': 295}
2017-12-31 21:31:45,647 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,652 : INFO : < 200 OK [3300]
2017-12-31 21:31:45,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 85, '_0n0': 281}
2017-12-31 21:31:45,664 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:45,669 : INFO : < 200 OK [3374]
2017-12-31 21:31:45,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 575, '_0n0': 281}
2017-12-31 21:31:45,680 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,685 : INFO : < 200 OK [3399]
2017-12-31 21:31:45,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 300, '_0n0': 296}
2017-12-31 21:31:45,696 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,702 : INFO : < 200 OK [3326]
2017-12-31 21:31:45,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 274, '_0n0': 296}
2017-12-31 21:31:45,712 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,718 : INFO : < 200 OK [3323]
2017-12-31 21:31:45,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 216, '_0n0': 282}
2017-12-31 21:31:45,729 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,734 : INFO : < 200 OK [3372]

2017-12-31 21:31:45,741 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 451, '_0n0': 282}
2017-12-31 21:31:45,744 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,750 : INFO : < 200 OK [3394]
2017-12-31 21:31:45,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 287, '_0n0': 297}
2017-12-31 21:31:45,761 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,767 : INFO : < 200 OK [3428]
2017-12-31 21:31:45,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 510, '_0n0': 297}
2017-12-31 21:31:45,777 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,782 : INFO : < 200 OK [3413]
2017-12-31 21:31:45,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 300, '_0n0': 283}
2017-12-31 21:31:45,794 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,800 : INFO : < 200 OK [3322]
2017-12-31 21:31:45,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 274, '_0n0': 283}
2017-12-31 21:31:45,809 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,815 : INFO : < 200 OK [3319]
2017-12-31 21:31:45,825 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 427, '_0n0': 298}
2017-12-31 21:31:45,829 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,834 : INFO : < 200 OK [3332]
2017-12-31 21:31:45,843 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 564, '_0n0': 298}
2017-12-31 21:31:45,847 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,852 : INFO : < 200 OK [3370]
2017-12-31 21:31:45,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 293, '_0n0': 299}
2017-12-31 21:31:45,871 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,877 : INFO : < 200 OK [3461]
2017-12-31 21:31:45,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 276, '_0n0': 299}
2017-12-31 21:31:45,887 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,893 : INFO : < 200 OK [3414]
2017-12-31 21:31:45,901 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 346, '_0n0': 285}
2017-12-31 21:31:45,906 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,911 : INFO : < 200 OK [3397]
2017-12-31 21:31:45,919 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 166, '_0n0': 285}
2017-12-31 21:31:45,922 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,928 : INFO : < 200 OK [3432]
2017-12-31 21:31:45,936 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 274, '_0n0': 300}
2017-12-31 21:31:45,940 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,946 : INFO : < 200 OK [3320]
2017-12-31 21:31:45,952 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 283, '_0n0': 300}
2017-12-31 21:31:45,956 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,962 : INFO : < 200 OK [3322]
2017-12-31 21:31:45,969 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 280, '_0n0': 286}
2017-12-31 21:31:45,973 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:45,978 : INFO : < 200 OK [3420]
2017-12-31 21:31:45,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 91, '_0n0': 286}
2017-12-31 21:31:45,988 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:45,994 : INFO : < 200 OK [3391]
2017-12-31 21:31:46,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 297, '_0n0': 287}
2017-12-31 21:31:46,006 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,011 : INFO : < 200 OK [3428]
2017-12-31 21:31:46,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 510, '_0n0': 287}
2017-12-31 21:31:46,021 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,027 : INFO : < 200 OK [3416]
2017-12-31 21:31:46,037 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 534, '_0n0': 302}
2017-12-31 21:31:46,041 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,047 : INFO : < 200 OK [3385]
2017-12-31 21:31:46,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 360, '_0n0': 302}
2017-12-31 21:31:46,059 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,064 : INFO : < 200 OK [3380]
2017-12-31 21:31:46,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 179, '_0n0': 288}
2017-12-31 21:31:46,075 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,081 : INFO : < 200 OK [3352]
2017-12-31 21:31:46,087 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 248, '_0n0': 288}
2017-12-31 21:31:46,092 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,097 : INFO : < 200 OK [3367]
2017-12-31 21:31:46,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 368, '_0n0': 303}
2017-12-31 21:31:46,109 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,115 : INFO : < 200 OK [3339]
2017-12-31 21:31:46,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 172, '_0n0': 303}
2017-12-31 21:31:46,125 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,131 : INFO : < 200 OK [3395]
2017-12-31 21:31:46,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 29, '_0n0': 289}
2017-12-31 21:31:46,143 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:46,148 : INFO : < 200 OK [3425]

2017-12-31 21:31:46,154 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 627, '_0n0': 289}
2017-12-31 21:31:46,159 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,165 : INFO : < 200 OK [3409]
2017-12-31 21:31:46,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 516, '_0n0': 304}
2017-12-31 21:31:46,182 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,188 : INFO : < 200 OK [3356]
2017-12-31 21:31:46,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 304}
2017-12-31 21:31:46,200 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,206 : INFO : < 200 OK [3400]
2017-12-31 21:31:46,217 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 251, '_0n0': 290}
2017-12-31 21:31:46,220 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,227 : INFO : < 200 OK [3386]
2017-12-31 21:31:46,237 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 249, '_0n0': 290}
2017-12-31 21:31:46,241 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,248 : INFO : < 200 OK [3342]
2017-12-31 21:31:46,266 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 311, '_0n0': 291}
2017-12-31 21:31:46,269 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,275 : INFO : < 200 OK [3360]
2017-12-31 21:31:46,289 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 322, '_0n0': 306}
2017-12-31 21:31:46,294 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,301 : INFO : < 200 OK [3403]
2017-12-31 21:31:46,308 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 619, '_0n0': 306}
2017-12-31 21:31:46,312 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,317 : INFO : < 200 OK [3413]
2017-12-31 21:31:46,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 311, '_0n0': 312}
2017-12-31 21:31:46,331 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,336 : INFO : < 200 OK [3421]
2017-12-31 21:31:46,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 318, '_0n0': 312}
2017-12-31 21:31:46,351 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,358 : INFO : < 200 OK [3424]
2017-12-31 21:31:46,367 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 542, '_0n0': 307}
2017-12-31 21:31:46,372 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,378 : INFO : < 200 OK [3399]
2017-12-31 21:31:46,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 516, '_0n0': 307}
2017-12-31 21:31:46,392 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,399 : INFO : < 200 OK [3373]
2017-12-31 21:31:46,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 339, '_0n0': 308}
2017-12-31 21:31:46,420 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,427 : INFO : < 200 OK [3403]
2017-12-31 21:31:46,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 338, '_0n0': 308}
2017-12-31 21:31:46,439 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,446 : INFO : < 200 OK [3370]
2017-12-31 21:31:46,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 132, '_0n0': 314}
2017-12-31 21:31:46,462 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,470 : INFO : < 200 OK [3356]
2017-12-31 21:31:46,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 314}
2017-12-31 21:31:46,484 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,490 : INFO : < 200 OK [3355]
2017-12-31 21:31:46,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 148, '_0n0': 316}
2017-12-31 21:31:46,533 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,539 : INFO : < 200 OK [3369]
2017-12-31 21:31:46,548 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 318, '_0n0': 316}
2017-12-31 21:31:46,551 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,558 : INFO : < 200 OK [3371]
2017-12-31 21:31:46,566 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 318, '_0n0': 311}
2017-12-31 21:31:46,569 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,576 : INFO : < 200 OK [3402]
2017-12-31 21:31:46,583 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 291, '_0n0': 311}
2017-12-31 21:31:46,586 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,592 : INFO : < 200 OK [3360]
2017-12-31 21:31:46,600 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 537, '_0n0': 317}
2017-12-31 21:31:46,604 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,610 : INFO : < 200 OK [3372]
2017-12-31 21:31:46,617 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 325, '_0n0': 317}
2017-12-31 21:31:46,621 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,628 : INFO : < 200 OK [3416]
2017-12-31 21:31:46,639 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 513, '_0n0': 332}
2017-12-31 21:31:46,643 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,650 : INFO : < 200 OK [3359]
2017-12-31 21:31:46,660 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 101, '_0n0': 332}
2017-12-31 21:31:46,664 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,670 : INFO : < 200 OK [3381]

2017-12-31 21:31:46,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 311, '_0n0': 318}
2017-12-31 21:31:46,684 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,690 : INFO : < 200 OK [3402]
2017-12-31 21:31:46,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 304, '_0n0': 319}
2017-12-31 21:31:46,715 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,721 : INFO : < 200 OK [3349]
2017-12-31 21:31:46,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 144, '_0n0': 319}
2017-12-31 21:31:46,732 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,738 : INFO : < 200 OK [3347]
2017-12-31 21:31:46,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 334}
2017-12-31 21:31:46,756 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,762 : INFO : < 200 OK [3430]
2017-12-31 21:31:46,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 327, '_0n0': 320}
2017-12-31 21:31:46,777 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,783 : INFO : < 200 OK [3437]
2017-12-31 21:31:46,802 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 627, '_0n0': 335}
2017-12-31 21:31:46,807 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,813 : INFO : < 200 OK [3391]
2017-12-31 21:31:46,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 331, '_0n0': 321}
2017-12-31 21:31:46,825 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,831 : INFO : < 200 OK [3364]
2017-12-31 21:31:46,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 346, '_0n0': 321}
2017-12-31 21:31:46,842 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,848 : INFO : < 200 OK [3367]
2017-12-31 21:31:46,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 306, '_0n0': 322}
2017-12-31 21:31:46,870 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,876 : INFO : < 200 OK [3403]
2017-12-31 21:31:46,883 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 602, '_0n0': 322}
2017-12-31 21:31:46,886 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,893 : INFO : < 200 OK [3444]
2017-12-31 21:31:46,907 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 348, '_0n0': 337}
2017-12-31 21:31:46,910 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,916 : INFO : < 200 OK [3359]
2017-12-31 21:31:46,927 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 313, '_0n0': 323}
2017-12-31 21:31:46,930 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,936 : INFO : < 200 OK [3401]
2017-12-31 21:31:46,946 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 182, '_0n0': 323}
2017-12-31 21:31:46,950 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,956 : INFO : < 200 OK [3336]
2017-12-31 21:31:46,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 308, '_0n0': 338}
2017-12-31 21:31:46,968 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,975 : INFO : < 200 OK [3370]
2017-12-31 21:31:46,982 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 339, '_0n0': 338}
2017-12-31 21:31:46,985 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:46,992 : INFO : < 200 OK [3370]
2017-12-31 21:31:47,009 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 308, '_0n0': 339}
2017-12-31 21:31:47,013 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,019 : INFO : < 200 OK [3403]
2017-12-31 21:31:47,027 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 338, '_0n0': 339}
2017-12-31 21:31:47,031 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,037 : INFO : < 200 OK [3370]
2017-12-31 21:31:47,065 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 176, '_0n0': 326}
2017-12-31 21:31:47,068 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,075 : INFO : < 200 OK [3360]
2017-12-31 21:31:47,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 169, '_0n0': 326}
2017-12-31 21:31:47,086 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,092 : INFO : < 200 OK [3376]
2017-12-31 21:31:47,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 155, '_0n0': 341}
2017-12-31 21:31:47,108 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,114 : INFO : < 200 OK [3390]
2017-12-31 21:31:47,126 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 320, '_0n0': 327}
2017-12-31 21:31:47,129 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,135 : INFO : < 200 OK [3437]
2017-12-31 21:31:47,142 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 59, '_0n0': 342}
2017-12-31 21:31:47,145 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:47,151 : INFO : < 200 OK [3375]
2017-12-31 21:31:47,158 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 992, '_0n0': 342}
2017-12-31 21:31:47,161 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,167 : INFO : < 200 OK [3425]
2017-12-31 21:31:47,186 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 155, '_0n0': 343}
2017-12-31 21:31:47,190 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,196 : INFO : < 200 OK [3390]

2017-12-31 21:31:47,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 416, '_0n0': 344}
2017-12-31 21:31:47,221 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,228 : INFO : < 200 OK [3420]
2017-12-31 21:31:47,236 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 602, '_0n0': 330}
2017-12-31 21:31:47,240 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,245 : INFO : < 200 OK [3400]
2017-12-31 21:31:47,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 69, '_0n0': 330}
2017-12-31 21:31:47,256 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:47,262 : INFO : < 200 OK [3381]
2017-12-31 21:31:47,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 321, '_0n0': 331}
2017-12-31 21:31:47,278 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,283 : INFO : < 200 OK [3364]
2017-12-31 21:31:47,290 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 346, '_0n0': 331}
2017-12-31 21:31:47,293 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,298 : INFO : < 200 OK [3366]
2017-12-31 21:31:47,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 331, '_0n0': 346}
2017-12-31 21:31:47,309 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,314 : INFO : < 200 OK [3366]
2017-12-31 21:31:47,319 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 321, '_0n0': 346}
2017-12-31 21:31:47,322 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,328 : INFO : < 200 OK [3367]
2017-12-31 21:31:47,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 992, '_0n0': 352}
2017-12-31 21:31:47,340 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,345 : INFO : < 200 OK [3434]
2017-12-31 21:31:47,353 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1013, '_0n0': 352}
2017-12-31 21:31:47,357 : INFO : > POST http://localhost:7474/db/data/cypher [184]
2017-12-31 21:31:47,363 : INFO : < 200 OK [3459]
2017-12-31 21:31:47,373 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 570, '_0n0': 347}
2017-12-31 21:31:47,376 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,381 : INFO : < 200 OK [3351]
2017-12-31 21:31:47,393 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 371, '_0n0': 353}
2017-12-31 21:31:47,396 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,401 : INFO : < 200 OK [3346]
2017-12-31 21:31:47,410 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 337, '_0n0': 348}
2017-12-31 21:31:47,412 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,418 : INFO : < 200 OK [3359]
2017-12-31 21:31:47,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 350, '_0n0': 348}
2017-12-31 21:31:47,428 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,434 : INFO : < 200 OK [3365]
2017-12-31 21:31:47,445 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 271, '_0n0': 354}
2017-12-31 21:31:47,448 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,456 : INFO : < 200 OK [3380]
2017-12-31 21:31:47,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 271, '_0n0': 349}
2017-12-31 21:31:47,470 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,476 : INFO : < 200 OK [3403]
2017-12-31 21:31:47,484 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 246, '_0n0': 355}
2017-12-31 21:31:47,486 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,493 : INFO : < 200 OK [3401]
2017-12-31 21:31:47,501 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 567, '_0n0': 355}
2017-12-31 21:31:47,505 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,511 : INFO : < 200 OK [3364]
2017-12-31 21:31:47,519 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 341, '_0n0': 350}
2017-12-31 21:31:47,523 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,529 : INFO : < 200 OK [3373]
2017-12-31 21:31:47,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 330, '_0n0': 350}
2017-12-31 21:31:47,540 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,545 : INFO : < 200 OK [3344]
2017-12-31 21:31:47,554 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 570, '_0n0': 356}
2017-12-31 21:31:47,558 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,564 : INFO : < 200 OK [3347]
2017-12-31 21:31:47,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 618, '_0n0': 356}
2017-12-31 21:31:47,575 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,580 : INFO : < 200 OK [3384]
2017-12-31 21:31:47,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 457, '_0n0': 351}
2017-12-31 21:31:47,593 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,598 : INFO : < 200 OK [3378]
2017-12-31 21:31:47,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 10, '_0n0': 351}
2017-12-31 21:31:47,609 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:47,615 : INFO : < 200 OK [3338]
2017-12-31 21:31:47,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 187, '_0n0': 357}
2017-12-31 21:31:47,630 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,635 : INFO : < 200 OK [3376]

2017-12-31 21:31:47,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 428, '_0n0': 372}
2017-12-31 21:31:47,648 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,654 : INFO : < 200 OK [3323]
2017-12-31 21:31:47,663 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 320, '_0n0': 372}
2017-12-31 21:31:47,665 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,671 : INFO : < 200 OK [3363]
2017-12-31 21:31:47,679 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 181, '_0n0': 358}
2017-12-31 21:31:47,682 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,688 : INFO : < 200 OK [3410]
2017-12-31 21:31:47,695 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 306, '_0n0': 358}
2017-12-31 21:31:47,698 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,704 : INFO : < 200 OK [3404]
2017-12-31 21:31:47,731 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 276, '_0n0': 360}
2017-12-31 21:31:47,733 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,739 : INFO : < 200 OK [3362]
2017-12-31 21:31:47,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 377, '_0n0': 360}
2017-12-31 21:31:47,749 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,756 : INFO : < 200 OK [3375]
2017-12-31 21:31:47,779 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 393, '_0n0': 362}
2017-12-31 21:31:47,782 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,788 : INFO : < 200 OK [3323]
2017-12-31 21:31:47,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 501, '_0n0': 362}
2017-12-31 21:31:47,798 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,804 : INFO : < 200 OK [3357]
2017-12-31 21:31:47,817 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 444, '_0n0': 363}
2017-12-31 21:31:47,820 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,827 : INFO : < 200 OK [3368]
2017-12-31 21:31:47,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 529, '_0n0': 363}
2017-12-31 21:31:47,836 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,842 : INFO : < 200 OK [3337]
2017-12-31 21:31:47,862 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 195, '_0n0': 379}
2017-12-31 21:31:47,864 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,870 : INFO : < 200 OK [3324]
2017-12-31 21:31:47,877 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 566, '_0n0': 379}
2017-12-31 21:31:47,880 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,885 : INFO : < 200 OK [3368]
2017-12-31 21:31:47,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 378, '_0n0': 365}
2017-12-31 21:31:47,896 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,902 : INFO : < 200 OK [3401]
2017-12-31 21:31:47,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 106, '_0n0': 365}
2017-12-31 21:31:47,911 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,916 : INFO : < 200 OK [3420]
2017-12-31 21:31:47,923 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 537, '_0n0': 380}
2017-12-31 21:31:47,926 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,931 : INFO : < 200 OK [3358]
2017-12-31 21:31:47,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 368, '_0n0': 380}
2017-12-31 21:31:47,941 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,946 : INFO : < 200 OK [3355]
2017-12-31 21:31:47,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 531, '_0n0': 366}
2017-12-31 21:31:47,961 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,966 : INFO : < 200 OK [3355]
2017-12-31 21:31:47,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 383, '_0n0': 381}
2017-12-31 21:31:47,976 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,981 : INFO : < 200 OK [3422]
2017-12-31 21:31:47,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 381}
2017-12-31 21:31:47,991 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:47,997 : INFO : < 200 OK [3436]
2017-12-31 21:31:48,004 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 276, '_0n0': 367}
2017-12-31 21:31:48,007 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,012 : INFO : < 200 OK [3386]
2017-12-31 21:31:48,018 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 360, '_0n0': 367}
2017-12-31 21:31:48,021 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,027 : INFO : < 200 OK [3393]
2017-12-31 21:31:48,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 385, '_0n0': 382}
2017-12-31 21:31:48,036 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,042 : INFO : < 200 OK [3437]
2017-12-31 21:31:48,049 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 303, '_0n0': 382}
2017-12-31 21:31:48,052 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,058 : INFO : < 200 OK [3428]
2017-12-31 21:31:48,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 303, '_0n0': 368}
2017-12-31 21:31:48,070 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,076 : INFO : < 200 OK [3339]

2017-12-31 21:31:48,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 172, '_0n0': 368}
2017-12-31 21:31:48,086 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,092 : INFO : < 200 OK [3379]
2017-12-31 21:31:48,099 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 381, '_0n0': 383}
2017-12-31 21:31:48,101 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,107 : INFO : < 200 OK [3422]
2017-12-31 21:31:48,113 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 516, '_0n0': 383}
2017-12-31 21:31:48,116 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,121 : INFO : < 200 OK [3371]
2017-12-31 21:31:48,129 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 171, '_0n0': 369}
2017-12-31 21:31:48,132 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,137 : INFO : < 200 OK [3406]
2017-12-31 21:31:48,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 264, '_0n0': 369}
2017-12-31 21:31:48,146 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,152 : INFO : < 200 OK [3397]
2017-12-31 21:31:48,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 472, '_0n0': 370}
2017-12-31 21:31:48,173 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,179 : INFO : < 200 OK [3336]
2017-12-31 21:31:48,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 516, '_0n0': 385}
2017-12-31 21:31:48,187 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,194 : INFO : < 200 OK [3357]
2017-12-31 21:31:48,200 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 385}
2017-12-31 21:31:48,203 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,209 : INFO : < 200 OK [3401]
2017-12-31 21:31:48,216 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 617, '_0n0': 371}
2017-12-31 21:31:48,218 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,224 : INFO : < 200 OK [3326]
2017-12-31 21:31:48,230 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 353, '_0n0': 371}
2017-12-31 21:31:48,233 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,239 : INFO : < 200 OK [3346]
2017-12-31 21:31:48,246 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 440, '_0n0': 386}
2017-12-31 21:31:48,249 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,255 : INFO : < 200 OK [3406]
2017-12-31 21:31:48,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 534, '_0n0': 386}
2017-12-31 21:31:48,267 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,272 : INFO : < 200 OK [3415]
2017-12-31 21:31:48,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 74, '_0n0': 392}
2017-12-31 21:31:48,282 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:48,288 : INFO : < 200 OK [3427]
2017-12-31 21:31:48,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 57, '_0n0': 392}
2017-12-31 21:31:48,298 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:48,304 : INFO : < 200 OK [3461]
2017-12-31 21:31:48,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 442, '_0n0': 387}
2017-12-31 21:31:48,318 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,324 : INFO : < 200 OK [3337]
2017-12-31 21:31:48,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 501, '_0n0': 393}
2017-12-31 21:31:48,333 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,340 : INFO : < 200 OK [3345]
2017-12-31 21:31:48,346 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 362, '_0n0': 393}
2017-12-31 21:31:48,349 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,355 : INFO : < 200 OK [3323]
2017-12-31 21:31:48,364 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 421, '_0n0': 388}
2017-12-31 21:31:48,367 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,373 : INFO : < 200 OK [3389]
2017-12-31 21:31:48,380 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 453, '_0n0': 388}
2017-12-31 21:31:48,383 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,389 : INFO : < 200 OK [3387]
2017-12-31 21:31:48,397 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 479, '_0n0': 394}
2017-12-31 21:31:48,399 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,405 : INFO : < 200 OK [3386]
2017-12-31 21:31:48,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 304, '_0n0': 394}
2017-12-31 21:31:48,414 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,421 : INFO : < 200 OK [3361]
2017-12-31 21:31:48,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 65, '_0n0': 389}
2017-12-31 21:31:48,433 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:48,439 : INFO : < 200 OK [3437]
2017-12-31 21:31:48,448 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 64, '_0n0': 389}
2017-12-31 21:31:48,452 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:48,461 : INFO : < 200 OK [3388]
2017-12-31 21:31:48,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 430, '_0n0': 395}
2017-12-31 21:31:48,481 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,487 : INFO : < 200 OK [3397]

2017-12-31 21:31:48,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 538, '_0n0': 390}
2017-12-31 21:31:48,503 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,510 : INFO : < 200 OK [3442]
2017-12-31 21:31:48,521 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 40, '_0n0': 390}
2017-12-31 21:31:48,526 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:48,533 : INFO : < 200 OK [3425]
2017-12-31 21:31:48,545 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 414, '_0n0': 396}
2017-12-31 21:31:48,549 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,555 : INFO : < 200 OK [3385]
2017-12-31 21:31:48,566 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 378, '_0n0': 396}
2017-12-31 21:31:48,569 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,577 : INFO : < 200 OK [3397]
2017-12-31 21:31:48,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 412, '_0n0': 391}
2017-12-31 21:31:48,592 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,599 : INFO : < 200 OK [3337]
2017-12-31 21:31:48,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 472, '_0n0': 391}
2017-12-31 21:31:48,615 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,622 : INFO : < 200 OK [3327]
2017-12-31 21:31:48,631 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 64, '_0n0': 397}
2017-12-31 21:31:48,635 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:48,644 : INFO : < 200 OK [3385]
2017-12-31 21:31:48,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 273, '_0n0': 397}
2017-12-31 21:31:48,655 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,662 : INFO : < 200 OK [3359]
2017-12-31 21:31:48,675 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 418, '_0n0': 412}
2017-12-31 21:31:48,680 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,686 : INFO : < 200 OK [3388]
2017-12-31 21:31:48,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 430, '_0n0': 412}
2017-12-31 21:31:48,700 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,709 : INFO : < 200 OK [3378]
2017-12-31 21:31:48,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 988, '_0n0': 398}
2017-12-31 21:31:48,721 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,728 : INFO : < 200 OK [3387]
2017-12-31 21:31:48,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 216, '_0n0': 398}
2017-12-31 21:31:48,740 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,747 : INFO : < 200 OK [3361]
2017-12-31 21:31:48,755 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 605, '_0n0': 413}
2017-12-31 21:31:48,760 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,767 : INFO : < 200 OK [3398]
2017-12-31 21:31:48,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 515, '_0n0': 413}
2017-12-31 21:31:48,778 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,784 : INFO : < 200 OK [3386]
2017-12-31 21:31:48,793 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 64, '_0n0': 399}
2017-12-31 21:31:48,797 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:48,803 : INFO : < 200 OK [3385]
2017-12-31 21:31:48,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 430, '_0n0': 399}
2017-12-31 21:31:48,815 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,822 : INFO : < 200 OK [3401]
2017-12-31 21:31:48,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 512, '_0n0': 414}
2017-12-31 21:31:48,836 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,844 : INFO : < 200 OK [3350]
2017-12-31 21:31:48,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 396, '_0n0': 414}
2017-12-31 21:31:48,859 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,865 : INFO : < 200 OK [3385]
2017-12-31 21:31:48,879 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 992, '_0n0': 400}
2017-12-31 21:31:48,883 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,889 : INFO : < 200 OK [3454]
2017-12-31 21:31:48,902 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 418, '_0n0': 415}
2017-12-31 21:31:48,906 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,914 : INFO : < 200 OK [3386]
2017-12-31 21:31:48,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 439, '_0n0': 401}
2017-12-31 21:31:48,928 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,934 : INFO : < 200 OK [3366]
2017-12-31 21:31:48,944 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 479, '_0n0': 401}
2017-12-31 21:31:48,947 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,953 : INFO : < 200 OK [3375]
2017-12-31 21:31:48,967 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 156, '_0n0': 416}
2017-12-31 21:31:48,970 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,977 : INFO : < 200 OK [3464]
2017-12-31 21:31:48,987 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 418, '_0n0': 402}
2017-12-31 21:31:48,992 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:48,999 : INFO : < 200 OK [3461]

2017-12-31 21:31:49,009 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 395, '_0n0': 402}
2017-12-31 21:31:49,012 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,018 : INFO : < 200 OK [3435]
2017-12-31 21:31:49,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 265, '_0n0': 417}
2017-12-31 21:31:49,032 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,039 : INFO : < 200 OK [3395]
2017-12-31 21:31:49,048 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 505, '_0n0': 417}
2017-12-31 21:31:49,052 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,060 : INFO : < 200 OK [3390]
2017-12-31 21:31:49,076 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 412, '_0n0': 418}
2017-12-31 21:31:49,080 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,086 : INFO : < 200 OK [3388]
2017-12-31 21:31:49,097 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 415, '_0n0': 418}
2017-12-31 21:31:49,102 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,109 : INFO : < 200 OK [3386]
2017-12-31 21:31:49,118 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 433, '_0n0': 404}
2017-12-31 21:31:49,123 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,131 : INFO : < 200 OK [3410]
2017-12-31 21:31:49,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 451, '_0n0': 404}
2017-12-31 21:31:49,142 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,149 : INFO : < 200 OK [3396]
2017-12-31 21:31:49,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 393, '_0n0': 405}
2017-12-31 21:31:49,172 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,178 : INFO : < 200 OK [3339]
2017-12-31 21:31:49,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 329, '_0n0': 406}
2017-12-31 21:31:49,200 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,208 : INFO : < 200 OK [3358]
2017-12-31 21:31:49,216 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 406}
2017-12-31 21:31:49,219 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,225 : INFO : < 200 OK [3345]
2017-12-31 21:31:49,234 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 200, '_0n0': 421}
2017-12-31 21:31:49,237 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,243 : INFO : < 200 OK [3349]
2017-12-31 21:31:49,249 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 453, '_0n0': 421}
2017-12-31 21:31:49,252 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,258 : INFO : < 200 OK [3365]
2017-12-31 21:31:49,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 62, '_0n0': 407}
2017-12-31 21:31:49,269 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:49,275 : INFO : < 200 OK [3307]
2017-12-31 21:31:49,282 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 561, '_0n0': 407}
2017-12-31 21:31:49,285 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,292 : INFO : < 200 OK [3319]
2017-12-31 21:31:49,341 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 355, '_0n0': 427}
2017-12-31 21:31:49,344 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,350 : INFO : < 200 OK [3327]
2017-12-31 21:31:49,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 298, '_0n0': 427}
2017-12-31 21:31:49,362 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,367 : INFO : < 200 OK [3332]
2017-12-31 21:31:49,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 565, '_0n0': 433}
2017-12-31 21:31:49,379 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,385 : INFO : < 200 OK [3369]
2017-12-31 21:31:49,393 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 451, '_0n0': 433}
2017-12-31 21:31:49,395 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,401 : INFO : < 200 OK [3407]
2017-12-31 21:31:49,414 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 544, '_0n0': 434}
2017-12-31 21:31:49,417 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,422 : INFO : < 200 OK [3402]
2017-12-31 21:31:49,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 562, '_0n0': 429}
2017-12-31 21:31:49,435 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,440 : INFO : < 200 OK [3395]
2017-12-31 21:31:49,448 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 441, '_0n0': 429}
2017-12-31 21:31:49,451 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,456 : INFO : < 200 OK [3328]
2017-12-31 21:31:49,470 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 412, '_0n0': 430}
2017-12-31 21:31:49,473 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,478 : INFO : < 200 OK [3378]
2017-12-31 21:31:49,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 64, '_0n0': 430}
2017-12-31 21:31:49,489 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:49,496 : INFO : < 200 OK [3397]
2017-12-31 21:31:49,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 440, '_0n0': 437}
2017-12-31 21:31:49,515 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,520 : INFO : < 200 OK [3376]

2017-12-31 21:31:49,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 467, '_0n0': 437}
2017-12-31 21:31:49,531 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,537 : INFO : < 200 OK [3410]
2017-12-31 21:31:49,545 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 374, '_0n0': 452}
2017-12-31 21:31:49,548 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,554 : INFO : < 200 OK [3366]
2017-12-31 21:31:49,564 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 373, '_0n0': 452}
2017-12-31 21:31:49,566 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,572 : INFO : < 200 OK [3387]
2017-12-31 21:31:49,579 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 444, '_0n0': 438}
2017-12-31 21:31:49,581 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,587 : INFO : < 200 OK [3399]
2017-12-31 21:31:49,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 484, '_0n0': 438}
2017-12-31 21:31:49,597 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,603 : INFO : < 200 OK [3406]
2017-12-31 21:31:49,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 421, '_0n0': 453}
2017-12-31 21:31:49,613 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,619 : INFO : < 200 OK [3365]
2017-12-31 21:31:49,626 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 197, '_0n0': 453}
2017-12-31 21:31:49,629 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,635 : INFO : < 200 OK [3364]
2017-12-31 21:31:49,643 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 401, '_0n0': 439}
2017-12-31 21:31:49,646 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,651 : INFO : < 200 OK [3366]
2017-12-31 21:31:49,660 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 140, '_0n0': 439}
2017-12-31 21:31:49,664 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,669 : INFO : < 200 OK [3417]
2017-12-31 21:31:49,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 573, '_0n0': 454}
2017-12-31 21:31:49,680 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,685 : INFO : < 200 OK [3392]
2017-12-31 21:31:49,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 433, '_0n0': 454}
2017-12-31 21:31:49,696 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,702 : INFO : < 200 OK [3408]
2017-12-31 21:31:49,710 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 386, '_0n0': 440}
2017-12-31 21:31:49,712 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,718 : INFO : < 200 OK [3406]
2017-12-31 21:31:49,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 534, '_0n0': 440}
2017-12-31 21:31:49,729 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,735 : INFO : < 200 OK [3370]
2017-12-31 21:31:49,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 503, '_0n0': 455}
2017-12-31 21:31:49,748 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,753 : INFO : < 200 OK [3357]
2017-12-31 21:31:49,766 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 551, '_0n0': 441}
2017-12-31 21:31:49,768 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,774 : INFO : < 200 OK [3337]
2017-12-31 21:31:49,782 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 446, '_0n0': 456}
2017-12-31 21:31:49,785 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,792 : INFO : < 200 OK [3378]
2017-12-31 21:31:49,800 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 32, '_0n0': 456}
2017-12-31 21:31:49,802 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:49,809 : INFO : < 200 OK [3422]
2017-12-31 21:31:49,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 386, '_0n0': 442}
2017-12-31 21:31:49,819 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,825 : INFO : < 200 OK [3397]
2017-12-31 21:31:49,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 440, '_0n0': 442}
2017-12-31 21:31:49,835 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,841 : INFO : < 200 OK [3352]
2017-12-31 21:31:49,855 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 216, '_0n0': 443}
2017-12-31 21:31:49,858 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,864 : INFO : < 200 OK [3342]
2017-12-31 21:31:49,871 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 988, '_0n0': 443}
2017-12-31 21:31:49,874 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,880 : INFO : < 200 OK [3368]
2017-12-31 21:31:49,890 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 440, '_0n0': 458}
2017-12-31 21:31:49,893 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,898 : INFO : < 200 OK [3387]
2017-12-31 21:31:49,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 363, '_0n0': 444}
2017-12-31 21:31:49,911 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,917 : INFO : < 200 OK [3368]
2017-12-31 21:31:49,926 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 619, '_0n0': 459}
2017-12-31 21:31:49,928 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,934 : INFO : < 200 OK [3436]

2017-12-31 21:31:49,943 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 204, '_0n0': 445}
2017-12-31 21:31:49,946 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,951 : INFO : < 200 OK [3342]
2017-12-31 21:31:49,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 369, '_0n0': 445}
2017-12-31 21:31:49,961 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,967 : INFO : < 200 OK [3391]
2017-12-31 21:31:49,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 56, '_0n0': 460}
2017-12-31 21:31:49,978 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:49,983 : INFO : < 200 OK [3415]
2017-12-31 21:31:49,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 473, '_0n0': 460}
2017-12-31 21:31:49,993 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:49,998 : INFO : < 200 OK [3432]
2017-12-31 21:31:50,006 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 456, '_0n0': 446}
2017-12-31 21:31:50,009 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,014 : INFO : < 200 OK [3378]
2017-12-31 21:31:50,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 546, '_0n0': 446}
2017-12-31 21:31:50,023 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,029 : INFO : < 200 OK [3339]
2017-12-31 21:31:50,043 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 192, '_0n0': 447}
2017-12-31 21:31:50,045 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,051 : INFO : < 200 OK [3368]
2017-12-31 21:31:50,058 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 89, '_0n0': 447}
2017-12-31 21:31:50,062 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:50,068 : INFO : < 200 OK [3388]
2017-12-31 21:31:50,078 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 275, '_0n0': 462}
2017-12-31 21:31:50,081 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,086 : INFO : < 200 OK [3383]
2017-12-31 21:31:50,109 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 534, '_0n0': 464}
2017-12-31 21:31:50,112 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,117 : INFO : < 200 OK [3324]
2017-12-31 21:31:50,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 519, '_0n0': 464}
2017-12-31 21:31:50,127 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,133 : INFO : < 200 OK [3312]
2017-12-31 21:31:50,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 32, '_0n0': 465}
2017-12-31 21:31:50,148 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:50,154 : INFO : < 200 OK [3403]
2017-12-31 21:31:50,164 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 433, '_0n0': 451}
2017-12-31 21:31:50,168 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,174 : INFO : < 200 OK [3407]
2017-12-31 21:31:50,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 454, '_0n0': 451}
2017-12-31 21:31:50,183 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,188 : INFO : < 200 OK [3394]
2017-12-31 21:31:50,199 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 247, '_0n0': 466}
2017-12-31 21:31:50,202 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,208 : INFO : < 200 OK [3419]
2017-12-31 21:31:50,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 370, '_0n0': 472}
2017-12-31 21:31:50,218 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,224 : INFO : < 200 OK [3336]
2017-12-31 21:31:50,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 391, '_0n0': 472}
2017-12-31 21:31:50,234 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,239 : INFO : < 200 OK [3327]
2017-12-31 21:31:50,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 96, '_0n0': 473}
2017-12-31 21:31:50,254 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:50,261 : INFO : < 200 OK [3442]
2017-12-31 21:31:50,268 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 89, '_0n0': 473}
2017-12-31 21:31:50,272 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:50,277 : INFO : < 200 OK [3425]
2017-12-31 21:31:50,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 483, '_0n0': 468}
2017-12-31 21:31:50,288 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,295 : INFO : < 200 OK [3328]
2017-12-31 21:31:50,303 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 453, '_0n0': 468}
2017-12-31 21:31:50,306 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,312 : INFO : < 200 OK [3341]
2017-12-31 21:31:50,319 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 371, '_0n0': 474}
2017-12-31 21:31:50,322 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,329 : INFO : < 200 OK [3368]
2017-12-31 21:31:50,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 545, '_0n0': 474}
2017-12-31 21:31:50,338 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,344 : INFO : < 200 OK [3381]
2017-12-31 21:31:50,352 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 528, '_0n0': 469}
2017-12-31 21:31:50,356 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,362 : INFO : < 200 OK [3399]

2017-12-31 21:31:50,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 531, '_0n0': 469}
2017-12-31 21:31:50,373 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,378 : INFO : < 200 OK [3385]
2017-12-31 21:31:50,386 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 464, '_0n0': 475}
2017-12-31 21:31:50,389 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,395 : INFO : < 200 OK [3301]
2017-12-31 21:31:50,406 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 576, '_0n0': 470}
2017-12-31 21:31:50,408 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,413 : INFO : < 200 OK [3399]
2017-12-31 21:31:50,420 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 428, '_0n0': 470}
2017-12-31 21:31:50,423 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,429 : INFO : < 200 OK [3350]
2017-12-31 21:31:50,437 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 562, '_0n0': 476}
2017-12-31 21:31:50,440 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,445 : INFO : < 200 OK [3367]
2017-12-31 21:31:50,452 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 98, '_0n0': 476}
2017-12-31 21:31:50,455 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:50,461 : INFO : < 200 OK [3349]
2017-12-31 21:31:50,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 247, '_0n0': 471}
2017-12-31 21:31:50,473 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,478 : INFO : < 200 OK [3371]
2017-12-31 21:31:50,484 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 158, '_0n0': 471}
2017-12-31 21:31:50,487 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,494 : INFO : < 200 OK [3402]
2017-12-31 21:31:50,504 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 363, '_0n0': 477}
2017-12-31 21:31:50,507 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,513 : INFO : < 200 OK [3365]
2017-12-31 21:31:50,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 265, '_0n0': 505}
2017-12-31 21:31:50,525 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,531 : INFO : < 200 OK [3440]
2017-12-31 21:31:50,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 417, '_0n0': 505}
2017-12-31 21:31:50,542 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,548 : INFO : < 200 OK [3390]
2017-12-31 21:31:50,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 247, '_0n0': 478}
2017-12-31 21:31:50,560 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,566 : INFO : < 200 OK [3378]
2017-12-31 21:31:50,575 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 446, '_0n0': 478}
2017-12-31 21:31:50,578 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,583 : INFO : < 200 OK [3345]
2017-12-31 21:31:50,592 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 373, '_0n0': 506}
2017-12-31 21:31:50,594 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,600 : INFO : < 200 OK [3380]
2017-12-31 21:31:50,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 513, '_0n0': 479}
2017-12-31 21:31:50,612 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,617 : INFO : < 200 OK [3382]
2017-12-31 21:31:50,624 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 401, '_0n0': 479}
2017-12-31 21:31:50,627 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,632 : INFO : < 200 OK [3375]
2017-12-31 21:31:50,640 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 538, '_0n0': 507}
2017-12-31 21:31:50,643 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,648 : INFO : < 200 OK [3379]
2017-12-31 21:31:50,666 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 369, '_0n0': 508}
2017-12-31 21:31:50,670 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,676 : INFO : < 200 OK [3368]
2017-12-31 21:31:50,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 631, '_0n0': 481}
2017-12-31 21:31:50,686 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,691 : INFO : < 200 OK [3367]
2017-12-31 21:31:50,699 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 123, '_0n0': 481}
2017-12-31 21:31:50,702 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,709 : INFO : < 200 OK [3352]
2017-12-31 21:31:50,719 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 576, '_0n0': 509}
2017-12-31 21:31:50,724 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,731 : INFO : < 200 OK [3406]
2017-12-31 21:31:50,740 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 575, '_0n0': 509}
2017-12-31 21:31:50,743 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,749 : INFO : < 200 OK [3398]
2017-12-31 21:31:50,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 132, '_0n0': 510}
2017-12-31 21:31:50,770 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,777 : INFO : < 200 OK [3372]
2017-12-31 21:31:50,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 84, '_0n0': 510}
2017-12-31 21:31:50,791 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:50,798 : INFO : < 200 OK [3372]

2017-12-31 21:31:50,809 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 483}
2017-12-31 21:31:50,812 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,817 : INFO : < 200 OK [3339]
2017-12-31 21:31:50,831 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 265, '_0n0': 511}
2017-12-31 21:31:50,833 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,840 : INFO : < 200 OK [3450]
2017-12-31 21:31:50,850 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 163, '_0n0': 484}
2017-12-31 21:31:50,853 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,861 : INFO : < 200 OK [3401]
2017-12-31 21:31:50,869 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 414, '_0n0': 512}
2017-12-31 21:31:50,874 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,879 : INFO : < 200 OK [3350]
2017-12-31 21:31:50,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 332, '_0n0': 513}
2017-12-31 21:31:50,899 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,906 : INFO : < 200 OK [3359]
2017-12-31 21:31:50,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 479, '_0n0': 513}
2017-12-31 21:31:50,918 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,925 : INFO : < 200 OK [3382]
2017-12-31 21:31:50,933 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 247, '_0n0': 486}
2017-12-31 21:31:50,936 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,943 : INFO : < 200 OK [3382]
2017-12-31 21:31:50,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 530, '_0n0': 486}
2017-12-31 21:31:50,952 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,959 : INFO : < 200 OK [3365]
2017-12-31 21:31:50,967 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 368, '_0n0': 514}
2017-12-31 21:31:50,970 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,977 : INFO : < 200 OK [3363]
2017-12-31 21:31:50,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 360, '_0n0': 514}
2017-12-31 21:31:50,987 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:50,994 : INFO : < 200 OK [3386]
2017-12-31 21:31:51,002 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 550, '_0n0': 500}
2017-12-31 21:31:51,006 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,013 : INFO : < 200 OK [3319]
2017-12-31 21:31:51,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 472, '_0n0': 500}
2017-12-31 21:31:51,025 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,032 : INFO : < 200 OK [3321]
2017-12-31 21:31:51,041 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 413, '_0n0': 515}
2017-12-31 21:31:51,045 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,051 : INFO : < 200 OK [3386]
2017-12-31 21:31:51,060 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 544, '_0n0': 515}
2017-12-31 21:31:51,063 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,069 : INFO : < 200 OK [3399]
2017-12-31 21:31:51,081 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 393, '_0n0': 501}
2017-12-31 21:31:51,085 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,091 : INFO : < 200 OK [3345]
2017-12-31 21:31:51,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 362, '_0n0': 501}
2017-12-31 21:31:51,103 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,111 : INFO : < 200 OK [3357]
2017-12-31 21:31:51,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 516}
2017-12-31 21:31:51,124 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,130 : INFO : < 200 OK [3385]
2017-12-31 21:31:51,141 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 15, '_0n0': 516}
2017-12-31 21:31:51,144 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:51,150 : INFO : < 200 OK [3328]
2017-12-31 21:31:51,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 550, '_0n0': 502}
2017-12-31 21:31:51,164 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,170 : INFO : < 200 OK [3369]
2017-12-31 21:31:51,179 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 328, '_0n0': 502}
2017-12-31 21:31:51,183 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,191 : INFO : < 200 OK [3386]
2017-12-31 21:31:51,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 64, '_0n0': 517}
2017-12-31 21:31:51,207 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:51,213 : INFO : < 200 OK [3364]
2017-12-31 21:31:51,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 384, '_0n0': 503}
2017-12-31 21:31:51,230 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,235 : INFO : < 200 OK [3351]
2017-12-31 21:31:51,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 401, '_0n0': 518}
2017-12-31 21:31:51,247 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,254 : INFO : < 200 OK [3371]
2017-12-31 21:31:51,262 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 439, '_0n0': 518}
2017-12-31 21:31:51,265 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,272 : INFO : < 200 OK [3408]

2017-12-31 21:31:51,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 441, '_0n0': 504}
2017-12-31 21:31:51,289 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,297 : INFO : < 200 OK [3315]
2017-12-31 21:31:51,307 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 464, '_0n0': 519}
2017-12-31 21:31:51,310 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,316 : INFO : < 200 OK [3312]
2017-12-31 21:31:51,325 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 475, '_0n0': 519}
2017-12-31 21:31:51,329 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,335 : INFO : < 200 OK [3344]
2017-12-31 21:31:51,348 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 619, '_0n0': 520}
2017-12-31 21:31:51,352 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,359 : INFO : < 200 OK [3445]
2017-12-31 21:31:51,367 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 181, '_0n0': 520}
2017-12-31 21:31:51,369 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,376 : INFO : < 200 OK [3425]
2017-12-31 21:31:51,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 528, '_0n0': 521}
2017-12-31 21:31:51,399 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,405 : INFO : < 200 OK [3411]
2017-12-31 21:31:51,412 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 324, '_0n0': 521}
2017-12-31 21:31:51,416 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,424 : INFO : < 200 OK [3366]
2017-12-31 21:31:51,432 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 265, '_0n0': 527}
2017-12-31 21:31:51,434 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,441 : INFO : < 200 OK [3425]
2017-12-31 21:31:51,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 505, '_0n0': 527}
2017-12-31 21:31:51,451 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,458 : INFO : < 200 OK [3420]
2017-12-31 21:31:51,468 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 474, '_0n0': 522}
2017-12-31 21:31:51,470 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,477 : INFO : < 200 OK [3420]
2017-12-31 21:31:51,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 437, '_0n0': 522}
2017-12-31 21:31:51,491 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,515 : INFO : < 200 OK [3410]
2017-12-31 21:31:51,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 521, '_0n0': 528}
2017-12-31 21:31:51,530 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,536 : INFO : < 200 OK [3411]
2017-12-31 21:31:51,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 469, '_0n0': 528}
2017-12-31 21:31:51,547 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,554 : INFO : < 200 OK [3399]
2017-12-31 21:31:51,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 363, '_0n0': 529}
2017-12-31 21:31:51,573 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,580 : INFO : < 200 OK [3337]
2017-12-31 21:31:51,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 444, '_0n0': 529}
2017-12-31 21:31:51,594 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,599 : INFO : < 200 OK [3390]
2017-12-31 21:31:51,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 536, '_0n0': 524}
2017-12-31 21:31:51,611 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,617 : INFO : < 200 OK [3381]
2017-12-31 21:31:51,627 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 562, '_0n0': 524}
2017-12-31 21:31:51,630 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,635 : INFO : < 200 OK [3401]
2017-12-31 21:31:51,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 486, '_0n0': 530}
2017-12-31 21:31:51,648 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,655 : INFO : < 200 OK [3365]
2017-12-31 21:31:51,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 616, '_0n0': 545}
2017-12-31 21:31:51,669 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,676 : INFO : < 200 OK [3356]
2017-12-31 21:31:51,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 631, '_0n0': 545}
2017-12-31 21:31:51,685 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,692 : INFO : < 200 OK [3362]
2017-12-31 21:31:51,703 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 469, '_0n0': 531}
2017-12-31 21:31:51,707 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,712 : INFO : < 200 OK [3385]
2017-12-31 21:31:51,720 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 505, '_0n0': 546}
2017-12-31 21:31:51,725 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,731 : INFO : < 200 OK [3401]
2017-12-31 21:31:51,737 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 265, '_0n0': 546}
2017-12-31 21:31:51,741 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,747 : INFO : < 200 OK [3406]
2017-12-31 21:31:51,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 603, '_0n0': 532}
2017-12-31 21:31:51,760 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,765 : INFO : < 200 OK [3402]

2017-12-31 21:31:51,773 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 424, '_0n0': 532}
2017-12-31 21:31:51,777 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,784 : INFO : < 200 OK [3384]
2017-12-31 21:31:51,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 533}
2017-12-31 21:31:51,800 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,805 : INFO : < 200 OK [3386]
2017-12-31 21:31:51,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 582, '_0n0': 533}
2017-12-31 21:31:51,819 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,826 : INFO : < 200 OK [3380]
2017-12-31 21:31:51,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 125, '_0n0': 548}
2017-12-31 21:31:51,848 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,858 : INFO : < 200 OK [3384]
2017-12-31 21:31:51,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 386, '_0n0': 534}
2017-12-31 21:31:51,873 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,880 : INFO : < 200 OK [3415]
2017-12-31 21:31:51,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 440, '_0n0': 534}
2017-12-31 21:31:51,893 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,900 : INFO : < 200 OK [3370]
2017-12-31 21:31:51,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 158, '_0n0': 549}
2017-12-31 21:31:51,920 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,927 : INFO : < 200 OK [3396]
2017-12-31 21:31:51,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 566, '_0n0': 535}
2017-12-31 21:31:51,937 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,944 : INFO : < 200 OK [3411]
2017-12-31 21:31:51,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 558, '_0n0': 535}
2017-12-31 21:31:51,952 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,959 : INFO : < 200 OK [3407]
2017-12-31 21:31:51,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 500, '_0n0': 550}
2017-12-31 21:31:51,968 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,974 : INFO : < 200 OK [3319]
2017-12-31 21:31:51,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 502, '_0n0': 550}
2017-12-31 21:31:51,984 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:51,989 : INFO : < 200 OK [3369]
2017-12-31 21:31:51,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 524, '_0n0': 536}
2017-12-31 21:31:52,000 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,006 : INFO : < 200 OK [3381]
2017-12-31 21:31:52,013 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 562, '_0n0': 536}
2017-12-31 21:31:52,015 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,020 : INFO : < 200 OK [3379]
2017-12-31 21:31:52,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 562, '_0n0': 551}
2017-12-31 21:31:52,032 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,037 : INFO : < 200 OK [3404]
2017-12-31 21:31:52,046 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 441, '_0n0': 551}
2017-12-31 21:31:52,049 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,055 : INFO : < 200 OK [3337]
2017-12-31 21:31:52,065 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 317, '_0n0': 537}
2017-12-31 21:31:52,068 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,074 : INFO : < 200 OK [3372]
2017-12-31 21:31:52,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 380, '_0n0': 537}
2017-12-31 21:31:52,087 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,095 : INFO : < 200 OK [3358]
2017-12-31 21:31:52,103 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 47, '_0n0': 552}
2017-12-31 21:31:52,107 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:52,113 : INFO : < 200 OK [3386]
2017-12-31 21:31:52,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 477, '_0n0': 552}
2017-12-31 21:31:52,125 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,131 : INFO : < 200 OK [3381]
2017-12-31 21:31:52,137 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 273, '_0n0': 538}
2017-12-31 21:31:52,141 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,147 : INFO : < 200 OK [3376]
2017-12-31 21:31:52,154 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 507, '_0n0': 538}
2017-12-31 21:31:52,158 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,164 : INFO : < 200 OK [3379]
2017-12-31 21:31:52,174 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 562, '_0n0': 553}
2017-12-31 21:31:52,177 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,183 : INFO : < 200 OK [3363]
2017-12-31 21:31:52,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 441, '_0n0': 553}
2017-12-31 21:31:52,195 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,201 : INFO : < 200 OK [3296]
2017-12-31 21:31:52,209 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 193, '_0n0': 539}
2017-12-31 21:31:52,212 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,218 : INFO : < 200 OK [3359]

2017-12-31 21:31:52,225 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 252, '_0n0': 539}
2017-12-31 21:31:52,228 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,233 : INFO : < 200 OK [3389]
2017-12-31 21:31:52,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 132, '_0n0': 555}
2017-12-31 21:31:52,249 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,255 : INFO : < 200 OK [3347]
2017-12-31 21:31:52,262 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 126, '_0n0': 555}
2017-12-31 21:31:52,265 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,271 : INFO : < 200 OK [3346]
2017-12-31 21:31:52,280 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 364, '_0n0': 541}
2017-12-31 21:31:52,283 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,288 : INFO : < 200 OK [3442]
2017-12-31 21:31:52,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 359, '_0n0': 541}
2017-12-31 21:31:52,298 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,303 : INFO : < 200 OK [3447]
2017-12-31 21:31:52,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 569, '_0n0': 556}
2017-12-31 21:31:52,318 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,324 : INFO : < 200 OK [3384]
2017-12-31 21:31:52,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 516, '_0n0': 542}
2017-12-31 21:31:52,334 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,340 : INFO : < 200 OK [3367]
2017-12-31 21:31:52,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 542}
2017-12-31 21:31:52,350 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,356 : INFO : < 200 OK [3411]
2017-12-31 21:31:52,364 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 93, '_0n0': 557}
2017-12-31 21:31:52,367 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:52,372 : INFO : < 200 OK [3342]
2017-12-31 21:31:52,383 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 988, '_0n0': 543}
2017-12-31 21:31:52,386 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,393 : INFO : < 200 OK [3450]
2017-12-31 21:31:52,399 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 216, '_0n0': 543}
2017-12-31 21:31:52,402 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,409 : INFO : < 200 OK [3424]
2017-12-31 21:31:52,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 535, '_0n0': 558}
2017-12-31 21:31:52,418 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,425 : INFO : < 200 OK [3407]
2017-12-31 21:31:52,433 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 544, '_0n0': 558}
2017-12-31 21:31:52,436 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,444 : INFO : < 200 OK [3436]
2017-12-31 21:31:52,452 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 434, '_0n0': 544}
2017-12-31 21:31:52,457 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,463 : INFO : < 200 OK [3402]
2017-12-31 21:31:52,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 566, '_0n0': 544}
2017-12-31 21:31:52,474 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,480 : INFO : < 200 OK [3440]
2017-12-31 21:31:52,492 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 246, '_0n0': 559}
2017-12-31 21:31:52,495 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,501 : INFO : < 200 OK [3428]
2017-12-31 21:31:52,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 433, '_0n0': 565}
2017-12-31 21:31:52,511 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,518 : INFO : < 200 OK [3369]
2017-12-31 21:31:52,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 119, '_0n0': 565}
2017-12-31 21:31:52,528 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,534 : INFO : < 200 OK [3356]
2017-12-31 21:31:52,542 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 462, '_0n0': 560}
2017-12-31 21:31:52,545 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,551 : INFO : < 200 OK [3386]
2017-12-31 21:31:52,560 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 483, '_0n0': 560}
2017-12-31 21:31:52,564 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,570 : INFO : < 200 OK [3376]
2017-12-31 21:31:52,578 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 544, '_0n0': 566}
2017-12-31 21:31:52,580 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,586 : INFO : < 200 OK [3440]
2017-12-31 21:31:52,594 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 535, '_0n0': 566}
2017-12-31 21:31:52,597 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,602 : INFO : < 200 OK [3411]
2017-12-31 21:31:52,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 62, '_0n0': 561}
2017-12-31 21:31:52,614 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:52,620 : INFO : < 200 OK [3305]
2017-12-31 21:31:52,628 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 407, '_0n0': 561}
2017-12-31 21:31:52,630 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,636 : INFO : < 200 OK [3319]

2017-12-31 21:31:52,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 246, '_0n0': 567}
2017-12-31 21:31:52,648 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,653 : INFO : < 200 OK [3396]
2017-12-31 21:31:52,662 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 355, '_0n0': 567}
2017-12-31 21:31:52,664 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,670 : INFO : < 200 OK [3364]
2017-12-31 21:31:52,703 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 344, '_0n0': 563}
2017-12-31 21:31:52,707 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,713 : INFO : < 200 OK [3417]
2017-12-31 21:31:52,722 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 556, '_0n0': 569}
2017-12-31 21:31:52,725 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,730 : INFO : < 200 OK [3384]
2017-12-31 21:31:52,738 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 526, '_0n0': 569}
2017-12-31 21:31:52,741 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,747 : INFO : < 200 OK [3432]
2017-12-31 21:31:52,754 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 571, '_0n0': 564}
2017-12-31 21:31:52,758 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,763 : INFO : < 200 OK [3361]
2017-12-31 21:31:52,771 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 427, '_0n0': 564}
2017-12-31 21:31:52,775 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,782 : INFO : < 200 OK [3323]
2017-12-31 21:31:52,792 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 356, '_0n0': 570}
2017-12-31 21:31:52,795 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,801 : INFO : < 200 OK [3347]
2017-12-31 21:31:52,809 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 347, '_0n0': 570}
2017-12-31 21:31:52,814 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,820 : INFO : < 200 OK [3351]
2017-12-31 21:31:52,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 407, '_0n0': 585}
2017-12-31 21:31:52,831 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,837 : INFO : < 200 OK [3329]
2017-12-31 21:31:52,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 62, '_0n0': 585}
2017-12-31 21:31:52,848 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:52,853 : INFO : < 200 OK [3315]
2017-12-31 21:31:52,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 564, '_0n0': 571}
2017-12-31 21:31:52,864 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,870 : INFO : < 200 OK [3361]
2017-12-31 21:31:52,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 246, '_0n0': 571}
2017-12-31 21:31:52,879 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,884 : INFO : < 200 OK [3397]
2017-12-31 21:31:52,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 246, '_0n0': 586}
2017-12-31 21:31:52,896 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,902 : INFO : < 200 OK [3383]
2017-12-31 21:31:52,909 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 355, '_0n0': 586}
2017-12-31 21:31:52,912 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,917 : INFO : < 200 OK [3351]
2017-12-31 21:31:52,925 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 407, '_0n0': 572}
2017-12-31 21:31:52,927 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,933 : INFO : < 200 OK [3377]
2017-12-31 21:31:52,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 441, '_0n0': 587}
2017-12-31 21:31:52,948 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,953 : INFO : < 200 OK [3308]
2017-12-31 21:31:52,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 264, '_0n0': 588}
2017-12-31 21:31:52,967 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,973 : INFO : < 200 OK [3406]
2017-12-31 21:31:52,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 131, '_0n0': 588}
2017-12-31 21:31:52,983 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:52,990 : INFO : < 200 OK [3438]
2017-12-31 21:31:52,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 154, '_0n0': 574}
2017-12-31 21:31:53,000 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,005 : INFO : < 200 OK [3405]
2017-12-31 21:31:53,011 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 265, '_0n0': 574}
2017-12-31 21:31:53,014 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,020 : INFO : < 200 OK [3430]
2017-12-31 21:31:53,031 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 576, '_0n0': 575}
2017-12-31 21:31:53,034 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,040 : INFO : < 200 OK [3413]
2017-12-31 21:31:53,046 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 85, '_0n0': 575}
2017-12-31 21:31:53,049 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:53,054 : INFO : < 200 OK [3380]
2017-12-31 21:31:53,067 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 108, '_0n0': 590}
2017-12-31 21:31:53,069 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,075 : INFO : < 200 OK [3412]

2017-12-31 21:31:53,083 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 509, '_0n0': 576}
2017-12-31 21:31:53,086 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,092 : INFO : < 200 OK [3406]
2017-12-31 21:31:53,098 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 575, '_0n0': 576}
2017-12-31 21:31:53,101 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,107 : INFO : < 200 OK [3413]
2017-12-31 21:31:53,115 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 516, '_0n0': 591}
2017-12-31 21:31:53,118 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,123 : INFO : < 200 OK [3385]
2017-12-31 21:31:53,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 608, '_0n0': 577}
2017-12-31 21:31:53,138 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,144 : INFO : < 200 OK [3337]
2017-12-31 21:31:53,150 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 95, '_0n0': 577}
2017-12-31 21:31:53,154 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:53,159 : INFO : < 200 OK [3346]
2017-12-31 21:31:53,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 619, '_0n0': 592}
2017-12-31 21:31:53,171 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,177 : INFO : < 200 OK [3436]
2017-12-31 21:31:53,188 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 97, '_0n0': 578}
2017-12-31 21:31:53,193 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:53,198 : INFO : < 200 OK [3426]
2017-12-31 21:31:53,205 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 136, '_0n0': 578}
2017-12-31 21:31:53,208 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,214 : INFO : < 200 OK [3451]
2017-12-31 21:31:53,222 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 179, '_0n0': 593}
2017-12-31 21:31:53,225 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,230 : INFO : < 200 OK [3349]
2017-12-31 21:31:53,236 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 288, '_0n0': 593}
2017-12-31 21:31:53,239 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,245 : INFO : < 200 OK [3372]
2017-12-31 21:31:53,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 151, '_0n0': 579}
2017-12-31 21:31:53,254 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,260 : INFO : < 200 OK [3398]
2017-12-31 21:31:53,266 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 176, '_0n0': 579}
2017-12-31 21:31:53,269 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,276 : INFO : < 200 OK [3377]
2017-12-31 21:31:53,282 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 317, '_0n0': 594}
2017-12-31 21:31:53,284 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,291 : INFO : < 200 OK [3381]
2017-12-31 21:31:53,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 537, '_0n0': 594}
2017-12-31 21:31:53,301 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,307 : INFO : < 200 OK [3338]
2017-12-31 21:31:53,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 290, '_0n0': 580}
2017-12-31 21:31:53,319 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,324 : INFO : < 200 OK [3412]
2017-12-31 21:31:53,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 251, '_0n0': 580}
2017-12-31 21:31:53,333 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,338 : INFO : < 200 OK [3417]
2017-12-31 21:31:53,348 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 614, '_0n0': 595}
2017-12-31 21:31:53,350 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,356 : INFO : < 200 OK [3375]
2017-12-31 21:31:53,378 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 606, '_0n0': 597}
2017-12-31 21:31:53,380 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,386 : INFO : < 200 OK [3436]
2017-12-31 21:31:53,393 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 31, '_0n0': 597}
2017-12-31 21:31:53,396 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:53,401 : INFO : < 200 OK [3375]
2017-12-31 21:31:53,407 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 146, '_0n0': 583}
2017-12-31 21:31:53,410 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,415 : INFO : < 200 OK [3410]
2017-12-31 21:31:53,421 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 591, '_0n0': 583}
2017-12-31 21:31:53,424 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,429 : INFO : < 200 OK [3426]
2017-12-31 21:31:53,436 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 66, '_0n0': 598}
2017-12-31 21:31:53,439 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:53,444 : INFO : < 200 OK [3355]
2017-12-31 21:31:53,450 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 85, '_0n0': 598}
2017-12-31 21:31:53,453 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:53,459 : INFO : < 200 OK [3356]
2017-12-31 21:31:53,469 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 516, '_0n0': 584}
2017-12-31 21:31:53,471 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,476 : INFO : < 200 OK [3377]

2017-12-31 21:31:53,483 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 154, '_0n0': 599}
2017-12-31 21:31:53,486 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,492 : INFO : < 200 OK [3416]
2017-12-31 21:31:53,498 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 611, '_0n0': 599}
2017-12-31 21:31:53,501 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,506 : INFO : < 200 OK [3410]
2017-12-31 21:31:53,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 413, '_0n0': 605}
2017-12-31 21:31:53,515 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,520 : INFO : < 200 OK [3398]
2017-12-31 21:31:53,526 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 310, '_0n0': 605}
2017-12-31 21:31:53,529 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,535 : INFO : < 200 OK [3407]
2017-12-31 21:31:53,542 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 596, '_0n0': 600}
2017-12-31 21:31:53,545 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,550 : INFO : < 200 OK [3393]
2017-12-31 21:31:53,562 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 597, '_0n0': 606}
2017-12-31 21:31:53,565 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,571 : INFO : < 200 OK [3436]
2017-12-31 21:31:53,590 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 69, '_0n0': 602}
2017-12-31 21:31:53,593 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:53,598 : INFO : < 200 OK [3450]
2017-12-31 21:31:53,604 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 277, '_0n0': 602}
2017-12-31 21:31:53,607 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,612 : INFO : < 200 OK [3440]
2017-12-31 21:31:53,619 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 577, '_0n0': 608}
2017-12-31 21:31:53,622 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,627 : INFO : < 200 OK [3337]
2017-12-31 21:31:53,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 308, '_0n0': 608}
2017-12-31 21:31:53,635 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,640 : INFO : < 200 OK [3370]
2017-12-31 21:31:53,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 392, '_0n0': 603}
2017-12-31 21:31:53,652 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,657 : INFO : < 200 OK [3449]
2017-12-31 21:31:53,666 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 604, '_0n0': 609}
2017-12-31 21:31:53,669 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,675 : INFO : < 200 OK [3414]
2017-12-31 21:31:53,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 170, '_0n0': 609}
2017-12-31 21:31:53,685 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,691 : INFO : < 200 OK [3376]
2017-12-31 21:31:53,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 169, '_0n0': 604}
2017-12-31 21:31:53,703 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,709 : INFO : < 200 OK [3394]
2017-12-31 21:31:53,716 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 626, '_0n0': 604}
2017-12-31 21:31:53,719 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,725 : INFO : < 200 OK [3404]
2017-12-31 21:31:53,732 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 137, '_0n0': 610}
2017-12-31 21:31:53,735 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,741 : INFO : < 200 OK [3412]
2017-12-31 21:31:53,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 316, '_0n0': 610}
2017-12-31 21:31:53,750 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,756 : INFO : < 200 OK [3390]
2017-12-31 21:31:53,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 582, '_0n0': 611}
2017-12-31 21:31:53,770 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,775 : INFO : < 200 OK [3400]
2017-12-31 21:31:53,782 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 344, '_0n0': 611}
2017-12-31 21:31:53,785 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,791 : INFO : < 200 OK [3371]
2017-12-31 21:31:53,798 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 604, '_0n0': 626}
2017-12-31 21:31:53,800 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,806 : INFO : < 200 OK [3404]
2017-12-31 21:31:53,813 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 609, '_0n0': 626}
2017-12-31 21:31:53,816 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,822 : INFO : < 200 OK [3385]
2017-12-31 21:31:53,830 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 169, '_0n0': 612}
2017-12-31 21:31:53,833 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,838 : INFO : < 200 OK [3371]
2017-12-31 21:31:53,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 194, '_0n0': 612}
2017-12-31 21:31:53,848 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,853 : INFO : < 200 OK [3351]
2017-12-31 21:31:53,861 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 335, '_0n0': 627}
2017-12-31 21:31:53,864 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,869 : INFO : < 200 OK [3391]

2017-12-31 21:31:53,877 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 595, '_0n0': 627}
2017-12-31 21:31:53,880 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,886 : INFO : < 200 OK [3392]
2017-12-31 21:31:53,898 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 367, '_0n0': 628}
2017-12-31 21:31:53,901 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,907 : INFO : < 200 OK [3408]
2017-12-31 21:31:53,913 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 404, '_0n0': 628}
2017-12-31 21:31:53,915 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,921 : INFO : < 200 OK [3399]
2017-12-31 21:31:53,933 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 132, '_0n0': 629}
2017-12-31 21:31:53,936 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:53,941 : INFO : < 200 OK [3374]
2017-12-31 21:31:53,951 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 77, '_0n0': 615}
2017-12-31 21:31:53,953 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:53,958 : INFO : < 200 OK [3386]
2017-12-31 21:31:53,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 13, '_0n0': 615}
2017-12-31 21:31:53,968 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:53,973 : INFO : < 200 OK [3390]
2017-12-31 21:31:53,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 371, '_0n0': 617}
2017-12-31 21:31:53,998 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:54,004 : INFO : < 200 OK [3326]
2017-12-31 21:31:54,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 427, '_0n0': 618}
2017-12-31 21:31:54,015 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:54,021 : INFO : < 200 OK [3357]
2017-12-31 21:31:54,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 356, '_0n0': 618}
2017-12-31 21:31:54,029 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:54,035 : INFO : < 200 OK [3384]
2017-12-31 21:31:54,043 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 90, '_0n0': 619}
2017-12-31 21:31:54,046 : INFO : > POST http://localhost:7474/db/data/cypher [182]
2017-12-31 21:31:54,051 : INFO : < 200 OK [3386]
2017-12-31 21:31:54,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 459, '_0n0': 619}
2017-12-31 21:31:54,062 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:54,069 : INFO : < 200 OK [3436]
2017-12-31 21:31:54,079 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:`related to`]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 288, '_0n0': 634}
2017-12-31 21:31:54,082 : INFO : > POST http://localhost:7474/db/data/cypher [183]
2017-12-31 21:31:54,087 : INFO : < 200 OK [3363]

In [83]:
check_list = ['C++', 'python', 'Java', 'HTML', 'Javascript', 'PHP', ' R ', ' C ', 
              'perl', 'spark', 'hadoop', 'Swift', 'Android', 'Ruby', 'programming language']
program_dict = {}
for language in check_list:
    program_dict[language] = Node("Programming language", name=language)
    graph.create(program_dict[language])

2017-12-31 21:31:54,255 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'C++'}}
2017-12-31 21:31:54,258 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:54,264 : INFO : < 200 OK [1391]
2017-12-31 21:31:54,267 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'python'}}
2017-12-31 21:31:54,271 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:54,276 : INFO : < 200 OK [1394]
2017-12-31 21:31:54,279 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'Java'}}
2017-12-31 21:31:54,283 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:54,288 : INFO : < 200 OK [1392]
2017-12-31 21:31:54,292 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'HTML'}}
2017-12-31 21:31:54,296 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:54,302 : INFO : < 200 OK [1392]
2017-12-31 21:31:54,311 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'Javascript'}}
2017-12-31 21:31:54,318 : INFO : > POST http://localhost:7474/db/data/cypher [100]
2017-12-31 21:31:54,325 : INFO : < 200 OK [1398]
2017-12-31 21:31:54,329 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'PHP'}}
2017-12-31 21:31:54,334 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:54,341 : INFO : < 200 OK [1391]
2017-12-31 21:31:54,345 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': ' R '}}
2017-12-31 21:31:54,348 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:54,354 : INFO : < 200 OK [1391]
2017-12-31 21:31:54,358 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': ' C '}}
2017-12-31 21:31:54,362 : INFO : > POST http://localhost:7474/db/data/cypher [93]
2017-12-31 21:31:54,368 : INFO : < 200 OK [1391]
2017-12-31 21:31:54,372 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'perl'}}
2017-12-31 21:31:54,376 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:54,382 : INFO : < 200 OK [1392]
2017-12-31 21:31:54,386 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'spark'}}
2017-12-31 21:31:54,389 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:54,395 : INFO : < 200 OK [1393]
2017-12-31 21:31:54,400 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'hadoop'}}
2017-12-31 21:31:54,403 : INFO : > POST http://localhost:7474/db/data/cypher [96]
2017-12-31 21:31:54,409 : INFO : < 200 OK [1394]
2017-12-31 21:31:54,413 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'Swift'}}
2017-12-31 21:31:54,417 : INFO : > POST http://localhost:7474/db/data/cypher [95]
2017-12-31 21:31:54,422 : INFO : < 200 OK [1393]
2017-12-31 21:31:54,426 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'Android'}}
2017-12-31 21:31:54,430 : INFO : > POST http://localhost:7474/db/data/cypher [97]
2017-12-31 21:31:54,435 : INFO : < 200 OK [1395]
2017-12-31 21:31:54,439 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'Ruby'}}
2017-12-31 21:31:54,443 : INFO : > POST http://localhost:7474/db/data/cypher [94]
2017-12-31 21:31:54,448 : INFO : < 200 OK [1392]
2017-12-31 21:31:54,452 : INFO : execute 'CREATE (_0:`Programming language` {_0})\nRETURN _0' {'_0': {'name': 'programming language'}}
2017-12-31 21:31:54,455 : INFO : > POST http://localhost:7474/db/data/cypher [110]
2017-12-31 21:31:54,461 : INFO : < 200 OK [1408]

In [84]:
for i, row in data_language_df.iterrows():
    x = course_dict[row.uid]
    for language in check_list:
        if row[language]:
            y = program_dict[language]
            graph.create(Relationship(x, "use", y))

2017-12-31 21:31:54,662 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 2}
2017-12-31 21:31:54,666 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:31:54,671 : INFO : < 200 OK [3240]
2017-12-31 21:31:54,675 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 2}
2017-12-31 21:31:54,679 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:31:54,684 : INFO : < 200 OK [3241]
2017-12-31 21:31:54,689 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 3}
2017-12-31 21:31:54,692 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:31:54,698 : INFO : < 200 OK [3268]
2017-12-31 21:31:54,704 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 995}
2017-12-31 21:31:54,706 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:54,711 : INFO : < 200 OK [3322]
2017-12-31 21:31:54,715 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 995}
2017-12-31 21:31:54,718 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:54,722 : INFO : < 200 OK [3323]
2017-12-31 21:31:54,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 12}
2017-12-31 21:31:54,730 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,735 : INFO : < 200 OK [3343]
2017-12-31 21:31:54,740 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 12}
2017-12-31 21:31:54,743 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,747 : INFO : < 200 OK [3343]
2017-12-31 21:31:54,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 8}
2017-12-31 21:31:54,754 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:31:54,759 : INFO : < 200 OK [3323]
2017-12-31 21:31:54,763 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 8}
2017-12-31 21:31:54,766 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:31:54,773 : INFO : < 200 OK [3321]
2017-12-31 21:31:54,777 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 9}
2017-12-31 21:31:54,780 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:31:54,785 : INFO : < 200 OK [3278]
2017-12-31 21:31:54,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 15}
2017-12-31 21:31:54,794 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,799 : INFO : < 200 OK [3274]
2017-12-31 21:31:54,803 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 10}
2017-12-31 21:31:54,806 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,811 : INFO : < 200 OK [3280]
2017-12-31 21:31:54,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 10}
2017-12-31 21:31:54,819 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,825 : INFO : < 200 OK [3286]
2017-12-31 21:31:54,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 17}
2017-12-31 21:31:54,835 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,840 : INFO : < 200 OK [3308]
2017-12-31 21:31:54,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 32}
2017-12-31 21:31:54,849 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,854 : INFO : < 200 OK [3316]
2017-12-31 21:31:54,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 32}
2017-12-31 21:31:54,862 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,868 : INFO : < 200 OK [3314]
2017-12-31 21:31:54,873 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 32}
2017-12-31 21:31:54,877 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,883 : INFO : < 200 OK [3315]
2017-12-31 21:31:54,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 32}
2017-12-31 21:31:54,892 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,898 : INFO : < 200 OK [3316]
2017-12-31 21:31:54,904 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 32}
2017-12-31 21:31:54,908 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,914 : INFO : < 200 OK [3330]
2017-12-31 21:31:54,920 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 32}
2017-12-31 21:31:54,923 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,929 : INFO : < 200 OK [3316]
2017-12-31 21:31:54,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 32}
2017-12-31 21:31:54,938 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,944 : INFO : < 200 OK [3314]
2017-12-31 21:31:54,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 32}
2017-12-31 21:31:54,953 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,959 : INFO : < 200 OK [3315]
2017-12-31 21:31:54,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 32}
2017-12-31 21:31:54,968 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,974 : INFO : < 200 OK [3316]
2017-12-31 21:31:54,979 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 32}
2017-12-31 21:31:54,983 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:54,990 : INFO : < 200 OK [3330]
2017-12-31 21:31:54,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 33}

2017-12-31 21:31:55,001 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,007 : INFO : < 200 OK [3294]
2017-12-31 21:31:55,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 38}
2017-12-31 21:31:55,021 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,027 : INFO : < 200 OK [3318]
2017-12-31 21:31:55,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 38}
2017-12-31 21:31:55,036 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,043 : INFO : < 200 OK [3318]
2017-12-31 21:31:55,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 25}
2017-12-31 21:31:55,056 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,063 : INFO : < 200 OK [3296]
2017-12-31 21:31:55,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 43}
2017-12-31 21:31:55,078 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,084 : INFO : < 200 OK [3287]
2017-12-31 21:31:55,090 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 43}
2017-12-31 21:31:55,093 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,099 : INFO : < 200 OK [3287]
2017-12-31 21:31:55,127 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 78}
2017-12-31 21:31:55,130 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,136 : INFO : < 200 OK [3287]
2017-12-31 21:31:55,142 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 78}
2017-12-31 21:31:55,146 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,152 : INFO : < 200 OK [3293]
2017-12-31 21:31:55,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 78}
2017-12-31 21:31:55,161 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,167 : INFO : < 200 OK [3287]
2017-12-31 21:31:55,174 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 78}
2017-12-31 21:31:55,178 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,186 : INFO : < 200 OK [3293]
2017-12-31 21:31:55,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 64}
2017-12-31 21:31:55,197 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,203 : INFO : < 200 OK [3307]
2017-12-31 21:31:55,211 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 64}
2017-12-31 21:31:55,215 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,222 : INFO : < 200 OK [3307]
2017-12-31 21:31:55,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 64}
2017-12-31 21:31:55,231 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,237 : INFO : < 200 OK [3307]
2017-12-31 21:31:55,243 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 80}
2017-12-31 21:31:55,248 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,254 : INFO : < 200 OK [3301]
2017-12-31 21:31:55,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 80}
2017-12-31 21:31:55,267 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,274 : INFO : < 200 OK [3301]
2017-12-31 21:31:55,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 80}
2017-12-31 21:31:55,283 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,289 : INFO : < 200 OK [3301]
2017-12-31 21:31:55,295 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 81}
2017-12-31 21:31:55,300 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,308 : INFO : < 200 OK [3290]
2017-12-31 21:31:55,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 81}
2017-12-31 21:31:55,317 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,324 : INFO : < 200 OK [3290]
2017-12-31 21:31:55,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 66}
2017-12-31 21:31:55,334 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,339 : INFO : < 200 OK [3307]
2017-12-31 21:31:55,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 66}
2017-12-31 21:31:55,348 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,354 : INFO : < 200 OK [3307]
2017-12-31 21:31:55,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 66}
2017-12-31 21:31:55,364 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,371 : INFO : < 200 OK [3307]
2017-12-31 21:31:55,377 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 66}
2017-12-31 21:31:55,380 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,386 : INFO : < 200 OK [3307]
2017-12-31 21:31:55,393 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 66}
2017-12-31 21:31:55,398 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,403 : INFO : < 200 OK [3307]
2017-12-31 21:31:55,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 83}
2017-12-31 21:31:55,417 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,425 : INFO : < 200 OK [3302]
2017-12-31 21:31:55,431 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 83}
2017-12-31 21:31:55,435 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,441 : INFO : < 200 OK [3302]

2017-12-31 21:31:55,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 83}
2017-12-31 21:31:55,450 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,458 : INFO : < 200 OK [3302]
2017-12-31 21:31:55,463 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 83}
2017-12-31 21:31:55,467 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,473 : INFO : < 200 OK [3302]
2017-12-31 21:31:55,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 68}
2017-12-31 21:31:55,483 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,489 : INFO : < 200 OK [3291]
2017-12-31 21:31:55,494 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 68}
2017-12-31 21:31:55,497 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,503 : INFO : < 200 OK [3290]
2017-12-31 21:31:55,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 68}
2017-12-31 21:31:55,513 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,519 : INFO : < 200 OK [3291]
2017-12-31 21:31:55,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 68}
2017-12-31 21:31:55,529 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,535 : INFO : < 200 OK [3290]
2017-12-31 21:31:55,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 84}
2017-12-31 21:31:55,545 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,550 : INFO : < 200 OK [3285]
2017-12-31 21:31:55,555 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 84}
2017-12-31 21:31:55,559 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,564 : INFO : < 200 OK [3288]
2017-12-31 21:31:55,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 84}
2017-12-31 21:31:55,573 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,579 : INFO : < 200 OK [3286]
2017-12-31 21:31:55,584 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 84}
2017-12-31 21:31:55,588 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,594 : INFO : < 200 OK [3302]
2017-12-31 21:31:55,599 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 84}
2017-12-31 21:31:55,602 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,609 : INFO : < 200 OK [3285]
2017-12-31 21:31:55,613 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 84}
2017-12-31 21:31:55,617 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,624 : INFO : < 200 OK [3288]
2017-12-31 21:31:55,628 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 84}
2017-12-31 21:31:55,632 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,637 : INFO : < 200 OK [3286]
2017-12-31 21:31:55,642 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 84}
2017-12-31 21:31:55,645 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,650 : INFO : < 200 OK [3302]
2017-12-31 21:31:55,655 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 84}
2017-12-31 21:31:55,659 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,664 : INFO : < 200 OK [3285]
2017-12-31 21:31:55,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 84}
2017-12-31 21:31:55,673 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,678 : INFO : < 200 OK [3288]
2017-12-31 21:31:55,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 84}
2017-12-31 21:31:55,685 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,691 : INFO : < 200 OK [3286]
2017-12-31 21:31:55,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 84}
2017-12-31 21:31:55,699 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,705 : INFO : < 200 OK [3302]
2017-12-31 21:31:55,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 84}
2017-12-31 21:31:55,714 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,720 : INFO : < 200 OK [3285]
2017-12-31 21:31:55,724 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 84}
2017-12-31 21:31:55,727 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,732 : INFO : < 200 OK [3288]
2017-12-31 21:31:55,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 84}
2017-12-31 21:31:55,740 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,746 : INFO : < 200 OK [3286]
2017-12-31 21:31:55,751 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 84}
2017-12-31 21:31:55,755 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,762 : INFO : < 200 OK [3302]
2017-12-31 21:31:55,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 69}
2017-12-31 21:31:55,770 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,776 : INFO : < 200 OK [3330]
2017-12-31 21:31:55,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 69}
2017-12-31 21:31:55,785 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,791 : INFO : < 200 OK [3330]
2017-12-31 21:31:55,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 70}

2017-12-31 21:31:55,800 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,806 : INFO : < 200 OK [3298]
2017-12-31 21:31:55,812 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 70}
2017-12-31 21:31:55,815 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,820 : INFO : < 200 OK [3299]
2017-12-31 21:31:55,825 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 70}
2017-12-31 21:31:55,829 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,835 : INFO : < 200 OK [3315]
2017-12-31 21:31:55,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 87}
2017-12-31 21:31:55,846 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,852 : INFO : < 200 OK [3286]
2017-12-31 21:31:55,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 87}
2017-12-31 21:31:55,863 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,870 : INFO : < 200 OK [3286]
2017-12-31 21:31:55,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 87}
2017-12-31 21:31:55,881 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,889 : INFO : < 200 OK [3286]
2017-12-31 21:31:55,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 93}
2017-12-31 21:31:55,899 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,906 : INFO : < 200 OK [3271]
2017-12-31 21:31:55,911 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 88}
2017-12-31 21:31:55,915 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,921 : INFO : < 200 OK [3276]
2017-12-31 21:31:55,926 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 88}
2017-12-31 21:31:55,930 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,936 : INFO : < 200 OK [3279]
2017-12-31 21:31:55,942 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 88}
2017-12-31 21:31:55,946 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,952 : INFO : < 200 OK [3277]
2017-12-31 21:31:55,957 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 88}
2017-12-31 21:31:55,961 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,967 : INFO : < 200 OK [3283]
2017-12-31 21:31:55,973 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 88}
2017-12-31 21:31:55,977 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:55,983 : INFO : < 200 OK [3278]
2017-12-31 21:31:55,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 88}
2017-12-31 21:31:55,991 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,000 : INFO : < 200 OK [3279]
2017-12-31 21:31:56,006 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 88}
2017-12-31 21:31:56,010 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,016 : INFO : < 200 OK [3277]
2017-12-31 21:31:56,024 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 90}
2017-12-31 21:31:56,028 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,034 : INFO : < 200 OK [3280]
2017-12-31 21:31:56,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 90}
2017-12-31 21:31:56,044 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,050 : INFO : < 200 OK [3280]
2017-12-31 21:31:56,056 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 90}
2017-12-31 21:31:56,060 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,066 : INFO : < 200 OK [3280]
2017-12-31 21:31:56,074 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 98}
2017-12-31 21:31:56,078 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,085 : INFO : < 200 OK [3298]
2017-12-31 21:31:56,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 113}
2017-12-31 21:31:56,095 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,101 : INFO : < 200 OK [3314]
2017-12-31 21:31:56,107 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 113}
2017-12-31 21:31:56,111 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,117 : INFO : < 200 OK [3314]
2017-12-31 21:31:56,123 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 99}
2017-12-31 21:31:56,127 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,133 : INFO : < 200 OK [3303]
2017-12-31 21:31:56,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 99}
2017-12-31 21:31:56,143 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,149 : INFO : < 200 OK [3317]
2017-12-31 21:31:56,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 99}
2017-12-31 21:31:56,159 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,165 : INFO : < 200 OK [3303]
2017-12-31 21:31:56,170 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 99}
2017-12-31 21:31:56,174 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,181 : INFO : < 200 OK [3317]
2017-12-31 21:31:56,186 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 99}
2017-12-31 21:31:56,190 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,196 : INFO : < 200 OK [3303]

2017-12-31 21:31:56,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 99}
2017-12-31 21:31:56,206 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:56,212 : INFO : < 200 OK [3317]
2017-12-31 21:31:56,217 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 114}
2017-12-31 21:31:56,222 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,228 : INFO : < 200 OK [3304]
2017-12-31 21:31:56,234 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 100}
2017-12-31 21:31:56,238 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,245 : INFO : < 200 OK [3333]
2017-12-31 21:31:56,251 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 100}
2017-12-31 21:31:56,255 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,263 : INFO : < 200 OK [3333]
2017-12-31 21:31:56,269 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 100}
2017-12-31 21:31:56,275 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,283 : INFO : < 200 OK [3333]
2017-12-31 21:31:56,290 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 100}
2017-12-31 21:31:56,294 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,303 : INFO : < 200 OK [3333]
2017-12-31 21:31:56,309 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 115}
2017-12-31 21:31:56,312 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,319 : INFO : < 200 OK [3318]
2017-12-31 21:31:56,325 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 115}
2017-12-31 21:31:56,328 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,335 : INFO : < 200 OK [3318]
2017-12-31 21:31:56,341 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 115}
2017-12-31 21:31:56,345 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,351 : INFO : < 200 OK [3318]
2017-12-31 21:31:56,357 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 101}
2017-12-31 21:31:56,360 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,366 : INFO : < 200 OK [3324]
2017-12-31 21:31:56,372 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 101}
2017-12-31 21:31:56,376 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,382 : INFO : < 200 OK [3324]
2017-12-31 21:31:56,388 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 101}
2017-12-31 21:31:56,392 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,398 : INFO : < 200 OK [3324]
2017-12-31 21:31:56,404 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 101}
2017-12-31 21:31:56,407 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,413 : INFO : < 200 OK [3324]
2017-12-31 21:31:56,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 117}
2017-12-31 21:31:56,423 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,429 : INFO : < 200 OK [3316]
2017-12-31 21:31:56,434 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 103}
2017-12-31 21:31:56,438 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,444 : INFO : < 200 OK [3346]
2017-12-31 21:31:56,451 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 103}
2017-12-31 21:31:56,456 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,461 : INFO : < 200 OK [3346]
2017-12-31 21:31:56,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 103}
2017-12-31 21:31:56,470 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,476 : INFO : < 200 OK [3346]
2017-12-31 21:31:56,482 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 103}
2017-12-31 21:31:56,485 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,491 : INFO : < 200 OK [3346]
2017-12-31 21:31:56,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 104}
2017-12-31 21:31:56,499 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,505 : INFO : < 200 OK [3315]
2017-12-31 21:31:56,510 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 104}
2017-12-31 21:31:56,514 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,520 : INFO : < 200 OK [3315]
2017-12-31 21:31:56,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 104}
2017-12-31 21:31:56,531 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,537 : INFO : < 200 OK [3315]
2017-12-31 21:31:56,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 119}
2017-12-31 21:31:56,546 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,553 : INFO : < 200 OK [3311]
2017-12-31 21:31:56,558 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 119}
2017-12-31 21:31:56,563 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,573 : INFO : < 200 OK [3313]
2017-12-31 21:31:56,582 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 121}
2017-12-31 21:31:56,586 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,593 : INFO : < 200 OK [3321]
2017-12-31 21:31:56,598 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 121}

2017-12-31 21:31:56,602 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,608 : INFO : < 200 OK [3321]
2017-12-31 21:31:56,613 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 121}
2017-12-31 21:31:56,616 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,623 : INFO : < 200 OK [3321]
2017-12-31 21:31:56,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 122}
2017-12-31 21:31:56,632 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,638 : INFO : < 200 OK [3308]
2017-12-31 21:31:56,643 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 122}
2017-12-31 21:31:56,647 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,652 : INFO : < 200 OK [3311]
2017-12-31 21:31:56,657 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 122}
2017-12-31 21:31:56,661 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,667 : INFO : < 200 OK [3309]
2017-12-31 21:31:56,672 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 108}
2017-12-31 21:31:56,679 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,686 : INFO : < 200 OK [3319]
2017-12-31 21:31:56,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 108}
2017-12-31 21:31:56,695 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,703 : INFO : < 200 OK [3319]
2017-12-31 21:31:56,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 108}
2017-12-31 21:31:56,715 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,722 : INFO : < 200 OK [3319]
2017-12-31 21:31:56,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 123}
2017-12-31 21:31:56,733 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,739 : INFO : < 200 OK [3285]
2017-12-31 21:31:56,745 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 123}
2017-12-31 21:31:56,749 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,757 : INFO : < 200 OK [3286]
2017-12-31 21:31:56,762 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 123}
2017-12-31 21:31:56,766 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,772 : INFO : < 200 OK [3287]
2017-12-31 21:31:56,777 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 123}
2017-12-31 21:31:56,780 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,786 : INFO : < 200 OK [3288]
2017-12-31 21:31:56,791 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 123}
2017-12-31 21:31:56,795 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,800 : INFO : < 200 OK [3302]
2017-12-31 21:31:56,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 124}
2017-12-31 21:31:56,809 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,816 : INFO : < 200 OK [3301]
2017-12-31 21:31:56,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 110}
2017-12-31 21:31:56,825 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,831 : INFO : < 200 OK [3285]
2017-12-31 21:31:56,837 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 110}
2017-12-31 21:31:56,841 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,847 : INFO : < 200 OK [3285]
2017-12-31 21:31:56,853 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 125}
2017-12-31 21:31:56,856 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,863 : INFO : < 200 OK [3318]
2017-12-31 21:31:56,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 125}
2017-12-31 21:31:56,871 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,877 : INFO : < 200 OK [3332]
2017-12-31 21:31:56,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 125}
2017-12-31 21:31:56,889 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,896 : INFO : < 200 OK [3318]
2017-12-31 21:31:56,901 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 125}
2017-12-31 21:31:56,905 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,912 : INFO : < 200 OK [3332]
2017-12-31 21:31:56,917 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 125}
2017-12-31 21:31:56,921 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,928 : INFO : < 200 OK [3318]
2017-12-31 21:31:56,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 125}
2017-12-31 21:31:56,938 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,944 : INFO : < 200 OK [3332]
2017-12-31 21:31:56,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 112}
2017-12-31 21:31:56,952 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,958 : INFO : < 200 OK [3288]
2017-12-31 21:31:56,962 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 112}
2017-12-31 21:31:56,965 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,970 : INFO : < 200 OK [3302]
2017-12-31 21:31:56,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 112}
2017-12-31 21:31:56,976 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,981 : INFO : < 200 OK [3288]

2017-12-31 21:31:56,986 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 112}
2017-12-31 21:31:56,990 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:56,996 : INFO : < 200 OK [3302]
2017-12-31 21:31:57,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 112}
2017-12-31 21:31:57,004 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,009 : INFO : < 200 OK [3288]
2017-12-31 21:31:57,014 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 112}
2017-12-31 21:31:57,017 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,023 : INFO : < 200 OK [3302]
2017-12-31 21:31:57,030 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 129}
2017-12-31 21:31:57,034 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,039 : INFO : < 200 OK [3310]
2017-12-31 21:31:57,044 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 129}
2017-12-31 21:31:57,047 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,053 : INFO : < 200 OK [3313]
2017-12-31 21:31:57,058 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 129}
2017-12-31 21:31:57,061 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,067 : INFO : < 200 OK [3311]
2017-12-31 21:31:57,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 137}
2017-12-31 21:31:57,076 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,082 : INFO : < 200 OK [3307]
2017-12-31 21:31:57,090 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 154}
2017-12-31 21:31:57,094 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,100 : INFO : < 200 OK [3314]
2017-12-31 21:31:57,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 154}
2017-12-31 21:31:57,108 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,113 : INFO : < 200 OK [3328]
2017-12-31 21:31:57,117 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 154}
2017-12-31 21:31:57,120 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,126 : INFO : < 200 OK [3314]
2017-12-31 21:31:57,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 154}
2017-12-31 21:31:57,135 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,141 : INFO : < 200 OK [3328]
2017-12-31 21:31:57,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 140}
2017-12-31 21:31:57,148 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,154 : INFO : < 200 OK [3332]
2017-12-31 21:31:57,160 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 155}
2017-12-31 21:31:57,163 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,169 : INFO : < 200 OK [3312]
2017-12-31 21:31:57,174 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 155}
2017-12-31 21:31:57,177 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,182 : INFO : < 200 OK [3312]
2017-12-31 21:31:57,187 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 155}
2017-12-31 21:31:57,190 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,196 : INFO : < 200 OK [3312]
2017-12-31 21:31:57,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 143}
2017-12-31 21:31:57,205 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,211 : INFO : < 200 OK [3347]
2017-12-31 21:31:57,216 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 143}
2017-12-31 21:31:57,219 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,225 : INFO : < 200 OK [3346]
2017-12-31 21:31:57,230 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 158}
2017-12-31 21:31:57,234 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,240 : INFO : < 200 OK [3333]
2017-12-31 21:31:57,246 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 144}
2017-12-31 21:31:57,248 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,255 : INFO : < 200 OK [3298]
2017-12-31 21:31:57,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 144}
2017-12-31 21:31:57,264 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,270 : INFO : < 200 OK [3298]
2017-12-31 21:31:57,275 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 144}
2017-12-31 21:31:57,278 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,284 : INFO : < 200 OK [3304]
2017-12-31 21:31:57,289 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 144}
2017-12-31 21:31:57,292 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,298 : INFO : < 200 OK [3298]
2017-12-31 21:31:57,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 144}
2017-12-31 21:31:57,307 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,314 : INFO : < 200 OK [3298]
2017-12-31 21:31:57,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 160}
2017-12-31 21:31:57,324 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,331 : INFO : < 200 OK [3319]
2017-12-31 21:31:57,338 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 160}

2017-12-31 21:31:57,343 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,350 : INFO : < 200 OK [3318]
2017-12-31 21:31:57,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 146}
2017-12-31 21:31:57,359 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,367 : INFO : < 200 OK [3312]
2017-12-31 21:31:57,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 146}
2017-12-31 21:31:57,377 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,382 : INFO : < 200 OK [3315]
2017-12-31 21:31:57,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 146}
2017-12-31 21:31:57,391 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,396 : INFO : < 200 OK [3312]
2017-12-31 21:31:57,402 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 162}
2017-12-31 21:31:57,405 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,410 : INFO : < 200 OK [3334]
2017-12-31 21:31:57,415 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 148}
2017-12-31 21:31:57,418 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,423 : INFO : < 200 OK [3315]
2017-12-31 21:31:57,428 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 148}
2017-12-31 21:31:57,431 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,437 : INFO : < 200 OK [3321]
2017-12-31 21:31:57,442 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 148}
2017-12-31 21:31:57,445 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,451 : INFO : < 200 OK [3314]
2017-12-31 21:31:57,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 3}
2017-12-31 21:31:57,462 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:31:57,467 : INFO : < 200 OK [3268]
2017-12-31 21:31:57,472 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:57,475 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,481 : INFO : < 200 OK [3350]
2017-12-31 21:31:57,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:57,489 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,495 : INFO : < 200 OK [3350]
2017-12-31 21:31:57,501 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:57,504 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,510 : INFO : < 200 OK [3350]
2017-12-31 21:31:57,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:57,518 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,523 : INFO : < 200 OK [3350]
2017-12-31 21:31:57,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:57,530 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,536 : INFO : < 200 OK [3350]
2017-12-31 21:31:57,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:57,544 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,549 : INFO : < 200 OK [3350]
2017-12-31 21:31:57,554 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:57,558 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,563 : INFO : < 200 OK [3350]
2017-12-31 21:31:57,568 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 152}
2017-12-31 21:31:57,571 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,577 : INFO : < 200 OK [3324]
2017-12-31 21:31:57,582 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 152}
2017-12-31 21:31:57,585 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,590 : INFO : < 200 OK [3323]
2017-12-31 21:31:57,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 167}
2017-12-31 21:31:57,598 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,605 : INFO : < 200 OK [3311]
2017-12-31 21:31:57,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 168}
2017-12-31 21:31:57,615 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,621 : INFO : < 200 OK [3318]
2017-12-31 21:31:57,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 172}
2017-12-31 21:31:57,632 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,638 : INFO : < 200 OK [3331]
2017-12-31 21:31:57,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 172}
2017-12-31 21:31:57,648 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,655 : INFO : < 200 OK [3348]
2017-12-31 21:31:57,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 172}
2017-12-31 21:31:57,666 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,672 : INFO : < 200 OK [3331]
2017-12-31 21:31:57,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 172}
2017-12-31 21:31:57,681 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,688 : INFO : < 200 OK [3348]
2017-12-31 21:31:57,694 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 178}
2017-12-31 21:31:57,698 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,704 : INFO : < 200 OK [3316]

2017-12-31 21:31:57,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 199}
2017-12-31 21:31:57,726 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,732 : INFO : < 200 OK [3293]
2017-12-31 21:31:57,744 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 188}
2017-12-31 21:31:57,747 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,753 : INFO : < 200 OK [3283]
2017-12-31 21:31:57,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 203}
2017-12-31 21:31:57,763 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,768 : INFO : < 200 OK [3341]
2017-12-31 21:31:57,779 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 162}
2017-12-31 21:31:57,783 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,789 : INFO : < 200 OK [3334]
2017-12-31 21:31:57,794 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 208}
2017-12-31 21:31:57,797 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,803 : INFO : < 200 OK [3356]
2017-12-31 21:31:57,809 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 214}
2017-12-31 21:31:57,812 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,818 : INFO : < 200 OK [3291]
2017-12-31 21:31:57,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 214}
2017-12-31 21:31:57,827 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,833 : INFO : < 200 OK [3308]
2017-12-31 21:31:57,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,842 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,848 : INFO : < 200 OK [3264]
2017-12-31 21:31:57,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,858 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,863 : INFO : < 200 OK [3264]
2017-12-31 21:31:57,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,871 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,876 : INFO : < 200 OK [3264]
2017-12-31 21:31:57,881 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,884 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,890 : INFO : < 200 OK [3264]
2017-12-31 21:31:57,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,898 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,903 : INFO : < 200 OK [3264]
2017-12-31 21:31:57,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,912 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,918 : INFO : < 200 OK [3264]
2017-12-31 21:31:57,922 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,925 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,930 : INFO : < 200 OK [3264]
2017-12-31 21:31:57,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,938 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,944 : INFO : < 200 OK [3264]
2017-12-31 21:31:57,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,953 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,958 : INFO : < 200 OK [3264]
2017-12-31 21:31:57,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,967 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,973 : INFO : < 200 OK [3264]
2017-12-31 21:31:57,977 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,980 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:57,986 : INFO : < 200 OK [3264]
2017-12-31 21:31:57,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:57,995 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,000 : INFO : < 200 OK [3264]
2017-12-31 21:31:58,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:58,009 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,014 : INFO : < 200 OK [3264]
2017-12-31 21:31:58,019 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:58,022 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,028 : INFO : < 200 OK [3264]
2017-12-31 21:31:58,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 209}
2017-12-31 21:31:58,036 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,041 : INFO : < 200 OK [3264]
2017-12-31 21:31:58,050 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:58,053 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,060 : INFO : < 200 OK [3350]
2017-12-31 21:31:58,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:58,070 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,076 : INFO : < 200 OK [3350]
2017-12-31 21:31:58,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}

2017-12-31 21:31:58,086 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,094 : INFO : < 200 OK [3350]
2017-12-31 21:31:58,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:58,106 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,112 : INFO : < 200 OK [3350]
2017-12-31 21:31:58,118 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:58,124 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,130 : INFO : < 200 OK [3350]
2017-12-31 21:31:58,135 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:58,141 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,147 : INFO : < 200 OK [3350]
2017-12-31 21:31:58,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 166}
2017-12-31 21:31:58,159 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,165 : INFO : < 200 OK [3350]
2017-12-31 21:31:58,174 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 15}
2017-12-31 21:31:58,178 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:58,183 : INFO : < 200 OK [3274]
2017-12-31 21:31:58,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 212}
2017-12-31 21:31:58,196 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,202 : INFO : < 200 OK [3293]
2017-12-31 21:31:58,210 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 212}
2017-12-31 21:31:58,213 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,219 : INFO : < 200 OK [3293]
2017-12-31 21:31:58,232 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 221}
2017-12-31 21:31:58,235 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,244 : INFO : < 200 OK [3288]
2017-12-31 21:31:58,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 221}
2017-12-31 21:31:58,256 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,265 : INFO : < 200 OK [3289]
2017-12-31 21:31:58,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 221}
2017-12-31 21:31:58,283 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,293 : INFO : < 200 OK [3302]
2017-12-31 21:31:58,299 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 256}
2017-12-31 21:31:58,302 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,310 : INFO : < 200 OK [3310]
2017-12-31 21:31:58,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 256}
2017-12-31 21:31:58,319 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,326 : INFO : < 200 OK [3308]
2017-12-31 21:31:58,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 256}
2017-12-31 21:31:58,335 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,341 : INFO : < 200 OK [3311]
2017-12-31 21:31:58,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 256}
2017-12-31 21:31:58,351 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,358 : INFO : < 200 OK [3310]
2017-12-31 21:31:58,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 256}
2017-12-31 21:31:58,367 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,373 : INFO : < 200 OK [3308]
2017-12-31 21:31:58,378 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 256}
2017-12-31 21:31:58,382 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,388 : INFO : < 200 OK [3311]
2017-12-31 21:31:58,394 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 243}
2017-12-31 21:31:58,397 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,403 : INFO : < 200 OK [3296]
2017-12-31 21:31:58,408 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 243}
2017-12-31 21:31:58,412 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,418 : INFO : < 200 OK [3299]
2017-12-31 21:31:58,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 243}
2017-12-31 21:31:58,426 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,432 : INFO : < 200 OK [3296]
2017-12-31 21:31:58,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 243}
2017-12-31 21:31:58,442 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,448 : INFO : < 200 OK [3300]
2017-12-31 21:31:58,453 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 243}
2017-12-31 21:31:58,457 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,462 : INFO : < 200 OK [3296]
2017-12-31 21:31:58,467 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 243}
2017-12-31 21:31:58,471 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,477 : INFO : < 200 OK [3299]
2017-12-31 21:31:58,482 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 243}
2017-12-31 21:31:58,486 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,492 : INFO : < 200 OK [3296]
2017-12-31 21:31:58,497 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 243}
2017-12-31 21:31:58,500 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,506 : INFO : < 200 OK [3300]

2017-12-31 21:31:58,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 244}
2017-12-31 21:31:58,515 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,521 : INFO : < 200 OK [3317]
2017-12-31 21:31:58,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 244}
2017-12-31 21:31:58,530 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,536 : INFO : < 200 OK [3317]
2017-12-31 21:31:58,541 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 259}
2017-12-31 21:31:58,545 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,551 : INFO : < 200 OK [3325]
2017-12-31 21:31:58,556 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 259}
2017-12-31 21:31:58,560 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,565 : INFO : < 200 OK [3325]
2017-12-31 21:31:58,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 245}
2017-12-31 21:31:58,575 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,581 : INFO : < 200 OK [3357]
2017-12-31 21:31:58,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 154}
2017-12-31 21:31:58,592 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,598 : INFO : < 200 OK [3314]
2017-12-31 21:31:58,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 154}
2017-12-31 21:31:58,609 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,615 : INFO : < 200 OK [3328]
2017-12-31 21:31:58,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 154}
2017-12-31 21:31:58,625 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,631 : INFO : < 200 OK [3314]
2017-12-31 21:31:58,636 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 154}
2017-12-31 21:31:58,640 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,646 : INFO : < 200 OK [3328]
2017-12-31 21:31:58,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 247}
2017-12-31 21:31:58,655 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,661 : INFO : < 200 OK [3305]
2017-12-31 21:31:58,666 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 247}
2017-12-31 21:31:58,671 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,677 : INFO : < 200 OK [3319]
2017-12-31 21:31:58,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 248}
2017-12-31 21:31:58,687 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,694 : INFO : < 200 OK [3294]
2017-12-31 21:31:58,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 248}
2017-12-31 21:31:58,704 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,711 : INFO : < 200 OK [3294]
2017-12-31 21:31:58,718 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 248}
2017-12-31 21:31:58,723 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,729 : INFO : < 200 OK [3294]
2017-12-31 21:31:58,737 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 249}
2017-12-31 21:31:58,742 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,751 : INFO : < 200 OK [3265]
2017-12-31 21:31:58,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 265}
2017-12-31 21:31:58,764 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,771 : INFO : < 200 OK [3336]
2017-12-31 21:31:58,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 87}
2017-12-31 21:31:58,790 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:58,797 : INFO : < 200 OK [3286]
2017-12-31 21:31:58,803 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 87}
2017-12-31 21:31:58,809 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:58,816 : INFO : < 200 OK [3286]
2017-12-31 21:31:58,824 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 87}
2017-12-31 21:31:58,828 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:58,836 : INFO : < 200 OK [3286]
2017-12-31 21:31:58,842 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 267}
2017-12-31 21:31:58,848 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,857 : INFO : < 200 OK [3328]
2017-12-31 21:31:58,869 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 98}
2017-12-31 21:31:58,876 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:31:58,883 : INFO : < 200 OK [3298]
2017-12-31 21:31:58,891 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 269}
2017-12-31 21:31:58,896 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,902 : INFO : < 200 OK [3287]
2017-12-31 21:31:58,910 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 113}
2017-12-31 21:31:58,914 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,928 : INFO : < 200 OK [3314]
2017-12-31 21:31:58,935 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 113}
2017-12-31 21:31:58,940 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,948 : INFO : < 200 OK [3314]
2017-12-31 21:31:58,958 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 277}

2017-12-31 21:31:58,962 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,971 : INFO : < 200 OK [3320]
2017-12-31 21:31:58,977 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 277}
2017-12-31 21:31:58,982 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:58,991 : INFO : < 200 OK [3320]
2017-12-31 21:31:58,997 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 277}
2017-12-31 21:31:59,002 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,009 : INFO : < 200 OK [3320]
2017-12-31 21:31:59,015 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 104}
2017-12-31 21:31:59,019 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,027 : INFO : < 200 OK [3315]
2017-12-31 21:31:59,034 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 104}
2017-12-31 21:31:59,040 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,051 : INFO : < 200 OK [3315]
2017-12-31 21:31:59,059 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 104}
2017-12-31 21:31:59,066 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,077 : INFO : < 200 OK [3315]
2017-12-31 21:31:59,084 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 293}
2017-12-31 21:31:59,088 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,096 : INFO : < 200 OK [3338]
2017-12-31 21:31:59,104 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 293}
2017-12-31 21:31:59,108 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,115 : INFO : < 200 OK [3355]
2017-12-31 21:31:59,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 281}
2017-12-31 21:31:59,128 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,141 : INFO : < 200 OK [3310]
2017-12-31 21:31:59,147 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 281}
2017-12-31 21:31:59,152 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,164 : INFO : < 200 OK [3327]
2017-12-31 21:31:59,173 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 281}
2017-12-31 21:31:59,184 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,197 : INFO : < 200 OK [3310]
2017-12-31 21:31:59,203 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 281}
2017-12-31 21:31:59,208 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,216 : INFO : < 200 OK [3327]
2017-12-31 21:31:59,225 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 124}
2017-12-31 21:31:59,229 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,239 : INFO : < 200 OK [3301]
2017-12-31 21:31:59,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 299}
2017-12-31 21:31:59,255 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,263 : INFO : < 200 OK [3350]
2017-12-31 21:31:59,268 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 299}
2017-12-31 21:31:59,274 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,283 : INFO : < 200 OK [3367]
2017-12-31 21:31:59,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 305}
2017-12-31 21:31:59,304 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,313 : INFO : < 200 OK [3274]
2017-12-31 21:31:59,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 305}
2017-12-31 21:31:59,326 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,333 : INFO : < 200 OK [3274]
2017-12-31 21:31:59,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 291}
2017-12-31 21:31:59,347 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,357 : INFO : < 200 OK [3275]
2017-12-31 21:31:59,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 291}
2017-12-31 21:31:59,367 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,375 : INFO : < 200 OK [3275]
2017-12-31 21:31:59,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 291}
2017-12-31 21:31:59,388 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,396 : INFO : < 200 OK [3281]
2017-12-31 21:31:59,402 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 291}
2017-12-31 21:31:59,407 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,415 : INFO : < 200 OK [3275]
2017-12-31 21:31:59,424 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 306}
2017-12-31 21:31:59,427 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,435 : INFO : < 200 OK [3308]
2017-12-31 21:31:59,441 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 306}
2017-12-31 21:31:59,448 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,456 : INFO : < 200 OK [3308]
2017-12-31 21:31:59,462 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 306}
2017-12-31 21:31:59,467 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,475 : INFO : < 200 OK [3311]
2017-12-31 21:31:59,481 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 306}
2017-12-31 21:31:59,486 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,499 : INFO : < 200 OK [3308]

2017-12-31 21:31:59,507 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 306}
2017-12-31 21:31:59,513 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,519 : INFO : < 200 OK [3308]
2017-12-31 21:31:59,525 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 306}
2017-12-31 21:31:59,529 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,537 : INFO : < 200 OK [3311]
2017-12-31 21:31:59,545 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 312}
2017-12-31 21:31:59,549 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,559 : INFO : < 200 OK [3336]
2017-12-31 21:31:59,565 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 312}
2017-12-31 21:31:59,569 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,579 : INFO : < 200 OK [3336]
2017-12-31 21:31:59,585 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 312}
2017-12-31 21:31:59,591 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,597 : INFO : < 200 OK [3342]
2017-12-31 21:31:59,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 312}
2017-12-31 21:31:59,610 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,616 : INFO : < 200 OK [3336]
2017-12-31 21:31:59,622 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 312}
2017-12-31 21:31:59,627 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,637 : INFO : < 200 OK [3336]
2017-12-31 21:31:59,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 312}
2017-12-31 21:31:59,648 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,657 : INFO : < 200 OK [3342]
2017-12-31 21:31:59,664 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 312}
2017-12-31 21:31:59,668 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,676 : INFO : < 200 OK [3336]
2017-12-31 21:31:59,681 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 312}
2017-12-31 21:31:59,685 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,691 : INFO : < 200 OK [3336]
2017-12-31 21:31:59,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 312}
2017-12-31 21:31:59,700 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,706 : INFO : < 200 OK [3342]
2017-12-31 21:31:59,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 312}
2017-12-31 21:31:59,715 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,721 : INFO : < 200 OK [3336]
2017-12-31 21:31:59,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 312}
2017-12-31 21:31:59,730 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,736 : INFO : < 200 OK [3336]
2017-12-31 21:31:59,742 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 312}
2017-12-31 21:31:59,747 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,755 : INFO : < 200 OK [3342]
2017-12-31 21:31:59,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 158}
2017-12-31 21:31:59,764 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,774 : INFO : < 200 OK [3333]
2017-12-31 21:31:59,780 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 307}
2017-12-31 21:31:59,785 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,793 : INFO : < 200 OK [3317]
2017-12-31 21:31:59,798 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 307}
2017-12-31 21:31:59,802 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,809 : INFO : < 200 OK [3317]
2017-12-31 21:31:59,814 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 307}
2017-12-31 21:31:59,818 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,824 : INFO : < 200 OK [3323]
2017-12-31 21:31:59,829 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 307}
2017-12-31 21:31:59,833 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,839 : INFO : < 200 OK [3317]
2017-12-31 21:31:59,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 307}
2017-12-31 21:31:59,848 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,854 : INFO : < 200 OK [3317]
2017-12-31 21:31:59,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 307}
2017-12-31 21:31:59,863 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,869 : INFO : < 200 OK [3317]
2017-12-31 21:31:59,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 307}
2017-12-31 21:31:59,879 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,886 : INFO : < 200 OK [3323]
2017-12-31 21:31:59,892 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 307}
2017-12-31 21:31:59,896 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,903 : INFO : < 200 OK [3317]
2017-12-31 21:31:59,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 144}
2017-12-31 21:31:59,912 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,918 : INFO : < 200 OK [3298]
2017-12-31 21:31:59,923 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 144}

2017-12-31 21:31:59,927 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,933 : INFO : < 200 OK [3298]
2017-12-31 21:31:59,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 144}
2017-12-31 21:31:59,942 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,953 : INFO : < 200 OK [3304]
2017-12-31 21:31:59,960 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 144}
2017-12-31 21:31:59,964 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,971 : INFO : < 200 OK [3298]
2017-12-31 21:31:59,978 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 144}
2017-12-31 21:31:59,982 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:31:59,988 : INFO : < 200 OK [3298]
2017-12-31 21:31:59,994 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 313}
2017-12-31 21:31:59,998 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,006 : INFO : < 200 OK [3337]
2017-12-31 21:32:00,012 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 313}
2017-12-31 21:32:00,016 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,024 : INFO : < 200 OK [3337]
2017-12-31 21:32:00,029 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 313}
2017-12-31 21:32:00,034 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,041 : INFO : < 200 OK [3343]
2017-12-31 21:32:00,046 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 308}
2017-12-31 21:32:00,053 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,063 : INFO : < 200 OK [3316]
2017-12-31 21:32:00,069 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 308}
2017-12-31 21:32:00,074 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,080 : INFO : < 200 OK [3315]
2017-12-31 21:32:00,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 308}
2017-12-31 21:32:00,090 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,097 : INFO : < 200 OK [3316]
2017-12-31 21:32:00,104 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 308}
2017-12-31 21:32:00,108 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,117 : INFO : < 200 OK [3332]
2017-12-31 21:32:00,124 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 314}
2017-12-31 21:32:00,129 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,135 : INFO : < 200 OK [3299]
2017-12-31 21:32:00,140 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 314}
2017-12-31 21:32:00,144 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,154 : INFO : < 200 OK [3302]
2017-12-31 21:32:00,160 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 314}
2017-12-31 21:32:00,167 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,178 : INFO : < 200 OK [3315]
2017-12-31 21:32:00,185 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 314}
2017-12-31 21:32:00,191 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,199 : INFO : < 200 OK [3299]
2017-12-31 21:32:00,207 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 314}
2017-12-31 21:32:00,210 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,218 : INFO : < 200 OK [3302]
2017-12-31 21:32:00,226 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 314}
2017-12-31 21:32:00,230 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,237 : INFO : < 200 OK [3315]
2017-12-31 21:32:00,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 314}
2017-12-31 21:32:00,248 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,256 : INFO : < 200 OK [3299]
2017-12-31 21:32:00,263 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 314}
2017-12-31 21:32:00,268 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,276 : INFO : < 200 OK [3302]
2017-12-31 21:32:00,281 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 314}
2017-12-31 21:32:00,288 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,297 : INFO : < 200 OK [3315]
2017-12-31 21:32:00,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 314}
2017-12-31 21:32:00,309 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,317 : INFO : < 200 OK [3299]
2017-12-31 21:32:00,324 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 314}
2017-12-31 21:32:00,328 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,339 : INFO : < 200 OK [3302]
2017-12-31 21:32:00,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 314}
2017-12-31 21:32:00,350 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,359 : INFO : < 200 OK [3315]
2017-12-31 21:32:00,366 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 309}
2017-12-31 21:32:00,371 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,377 : INFO : < 200 OK [3327]
2017-12-31 21:32:00,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 309}
2017-12-31 21:32:00,388 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,397 : INFO : < 200 OK [3327]

2017-12-31 21:32:00,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 309}
2017-12-31 21:32:00,409 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,418 : INFO : < 200 OK [3333]
2017-12-31 21:32:00,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 160}
2017-12-31 21:32:00,430 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,439 : INFO : < 200 OK [3319]
2017-12-31 21:32:00,445 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 160}
2017-12-31 21:32:00,450 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,458 : INFO : < 200 OK [3318]
2017-12-31 21:32:00,463 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 315}
2017-12-31 21:32:00,467 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,474 : INFO : < 200 OK [3274]
2017-12-31 21:32:00,481 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 315}
2017-12-31 21:32:00,485 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,494 : INFO : < 200 OK [3274]
2017-12-31 21:32:00,499 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 315}
2017-12-31 21:32:00,504 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,512 : INFO : < 200 OK [3280]
2017-12-31 21:32:00,519 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 310}
2017-12-31 21:32:00,524 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,532 : INFO : < 200 OK [3343]
2017-12-31 21:32:00,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 310}
2017-12-31 21:32:00,543 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,551 : INFO : < 200 OK [3343]
2017-12-31 21:32:00,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 310}
2017-12-31 21:32:00,560 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,566 : INFO : < 200 OK [3349]
2017-12-31 21:32:00,573 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 316}
2017-12-31 21:32:00,578 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,584 : INFO : < 200 OK [3283]
2017-12-31 21:32:00,591 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 316}
2017-12-31 21:32:00,596 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,602 : INFO : < 200 OK [3283]
2017-12-31 21:32:00,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 316}
2017-12-31 21:32:00,613 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,619 : INFO : < 200 OK [3289]
2017-12-31 21:32:00,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 316}
2017-12-31 21:32:00,629 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,638 : INFO : < 200 OK [3299]
2017-12-31 21:32:00,644 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 311}
2017-12-31 21:32:00,649 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,657 : INFO : < 200 OK [3314]
2017-12-31 21:32:00,662 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 311}
2017-12-31 21:32:00,666 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,676 : INFO : < 200 OK [3314]
2017-12-31 21:32:00,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 311}
2017-12-31 21:32:00,687 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,695 : INFO : < 200 OK [3320]
2017-12-31 21:32:00,704 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 311}
2017-12-31 21:32:00,708 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,715 : INFO : < 200 OK [3314]
2017-12-31 21:32:00,721 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 311}
2017-12-31 21:32:00,724 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,730 : INFO : < 200 OK [3330]
2017-12-31 21:32:00,736 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 148}
2017-12-31 21:32:00,741 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,747 : INFO : < 200 OK [3315]
2017-12-31 21:32:00,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 148}
2017-12-31 21:32:00,757 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,762 : INFO : < 200 OK [3321]
2017-12-31 21:32:00,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 148}
2017-12-31 21:32:00,771 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,777 : INFO : < 200 OK [3314]
2017-12-31 21:32:00,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 317}
2017-12-31 21:32:00,788 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,796 : INFO : < 200 OK [3322]
2017-12-31 21:32:00,801 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 317}
2017-12-31 21:32:00,806 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,815 : INFO : < 200 OK [3325]
2017-12-31 21:32:00,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 332}
2017-12-31 21:32:00,826 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,837 : INFO : < 200 OK [3302]
2017-12-31 21:32:00,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 332}

2017-12-31 21:32:00,849 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,857 : INFO : < 200 OK [3305]
2017-12-31 21:32:00,863 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 318}
2017-12-31 21:32:00,867 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,881 : INFO : < 200 OK [3317]
2017-12-31 21:32:00,888 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 318}
2017-12-31 21:32:00,893 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,900 : INFO : < 200 OK [3317]
2017-12-31 21:32:00,907 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 318}
2017-12-31 21:32:00,912 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,923 : INFO : < 200 OK [3323]
2017-12-31 21:32:00,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 318}
2017-12-31 21:32:00,934 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,944 : INFO : < 200 OK [3317]
2017-12-31 21:32:00,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 318}
2017-12-31 21:32:00,956 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,966 : INFO : < 200 OK [3317]
2017-12-31 21:32:00,972 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 318}
2017-12-31 21:32:00,978 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:00,984 : INFO : < 200 OK [3317]
2017-12-31 21:32:00,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 318}
2017-12-31 21:32:00,995 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,002 : INFO : < 200 OK [3323]
2017-12-31 21:32:01,008 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 318}
2017-12-31 21:32:01,012 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,020 : INFO : < 200 OK [3317]
2017-12-31 21:32:01,027 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 318}
2017-12-31 21:32:01,030 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,037 : INFO : < 200 OK [3317]
2017-12-31 21:32:01,043 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 318}
2017-12-31 21:32:01,046 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,052 : INFO : < 200 OK [3317]
2017-12-31 21:32:01,057 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 318}
2017-12-31 21:32:01,061 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,067 : INFO : < 200 OK [3323]
2017-12-31 21:32:01,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 318}
2017-12-31 21:32:01,076 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,086 : INFO : < 200 OK [3317]
2017-12-31 21:32:01,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 333}
2017-12-31 21:32:01,097 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,105 : INFO : < 200 OK [3284]
2017-12-31 21:32:01,110 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 333}
2017-12-31 21:32:01,115 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,123 : INFO : < 200 OK [3284]
2017-12-31 21:32:01,128 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 333}
2017-12-31 21:32:01,134 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,144 : INFO : < 200 OK [3300]
2017-12-31 21:32:01,150 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 334}
2017-12-31 21:32:01,156 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,163 : INFO : < 200 OK [3330]
2017-12-31 21:32:01,169 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 334}
2017-12-31 21:32:01,175 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,182 : INFO : < 200 OK [3330]
2017-12-31 21:32:01,192 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 334}
2017-12-31 21:32:01,196 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,202 : INFO : < 200 OK [3336]
2017-12-31 21:32:01,210 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 334}
2017-12-31 21:32:01,214 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,224 : INFO : < 200 OK [3330]
2017-12-31 21:32:01,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 334}
2017-12-31 21:32:01,235 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,243 : INFO : < 200 OK [3346]
2017-12-31 21:32:01,249 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 320}
2017-12-31 21:32:01,255 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,261 : INFO : < 200 OK [3316]
2017-12-31 21:32:01,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 320}
2017-12-31 21:32:01,272 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,279 : INFO : < 200 OK [3316]
2017-12-31 21:32:01,286 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 320}
2017-12-31 21:32:01,291 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,298 : INFO : < 200 OK [3322]
2017-12-31 21:32:01,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 320}
2017-12-31 21:32:01,310 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,317 : INFO : < 200 OK [3319]

2017-12-31 21:32:01,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 152}
2017-12-31 21:32:01,328 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,338 : INFO : < 200 OK [3324]
2017-12-31 21:32:01,343 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 152}
2017-12-31 21:32:01,347 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,354 : INFO : < 200 OK [3323]
2017-12-31 21:32:01,360 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 335}
2017-12-31 21:32:01,365 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,373 : INFO : < 200 OK [3308]
2017-12-31 21:32:01,380 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 335}
2017-12-31 21:32:01,384 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,392 : INFO : < 200 OK [3311]
2017-12-31 21:32:01,399 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 321}
2017-12-31 21:32:01,406 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,417 : INFO : < 200 OK [3297]
2017-12-31 21:32:01,425 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 321}
2017-12-31 21:32:01,430 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,440 : INFO : < 200 OK [3297]
2017-12-31 21:32:01,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 321}
2017-12-31 21:32:01,450 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,457 : INFO : < 200 OK [3303]
2017-12-31 21:32:01,464 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 321}
2017-12-31 21:32:01,468 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,476 : INFO : < 200 OK [3297]
2017-12-31 21:32:01,483 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 321}
2017-12-31 21:32:01,488 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,495 : INFO : < 200 OK [3313]
2017-12-31 21:32:01,502 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 321}
2017-12-31 21:32:01,507 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,514 : INFO : < 200 OK [3297]
2017-12-31 21:32:01,521 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 321}
2017-12-31 21:32:01,526 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,533 : INFO : < 200 OK [3297]
2017-12-31 21:32:01,540 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 321}
2017-12-31 21:32:01,544 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,551 : INFO : < 200 OK [3303]
2017-12-31 21:32:01,558 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 321}
2017-12-31 21:32:01,562 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,568 : INFO : < 200 OK [3297]
2017-12-31 21:32:01,574 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 321}
2017-12-31 21:32:01,577 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,583 : INFO : < 200 OK [3313]
2017-12-31 21:32:01,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 336}
2017-12-31 21:32:01,592 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,598 : INFO : < 200 OK [3331]
2017-12-31 21:32:01,603 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 336}
2017-12-31 21:32:01,607 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,614 : INFO : < 200 OK [3331]
2017-12-31 21:32:01,620 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 336}
2017-12-31 21:32:01,624 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,632 : INFO : < 200 OK [3337]
2017-12-31 21:32:01,639 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 336}
2017-12-31 21:32:01,643 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,651 : INFO : < 200 OK [3334]
2017-12-31 21:32:01,660 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 322}
2017-12-31 21:32:01,663 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,677 : INFO : < 200 OK [3327]
2017-12-31 21:32:01,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 337}
2017-12-31 21:32:01,688 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,694 : INFO : < 200 OK [3286]
2017-12-31 21:32:01,699 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 337}
2017-12-31 21:32:01,703 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,712 : INFO : < 200 OK [3288]
2017-12-31 21:32:01,719 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 337}
2017-12-31 21:32:01,723 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,729 : INFO : < 200 OK [3303]
2017-12-31 21:32:01,734 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 323}
2017-12-31 21:32:01,738 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,747 : INFO : < 200 OK [3293]
2017-12-31 21:32:01,755 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 323}
2017-12-31 21:32:01,759 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,765 : INFO : < 200 OK [3293]
2017-12-31 21:32:01,771 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 323}

2017-12-31 21:32:01,776 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,785 : INFO : < 200 OK [3299]
2017-12-31 21:32:01,792 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 323}
2017-12-31 21:32:01,796 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,807 : INFO : < 200 OK [3309]
2017-12-31 21:32:01,813 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 338}
2017-12-31 21:32:01,817 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,824 : INFO : < 200 OK [3283]
2017-12-31 21:32:01,829 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 338}
2017-12-31 21:32:01,833 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,839 : INFO : < 200 OK [3282]
2017-12-31 21:32:01,843 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 338}
2017-12-31 21:32:01,847 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,854 : INFO : < 200 OK [3283]
2017-12-31 21:32:01,862 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 338}
2017-12-31 21:32:01,866 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,873 : INFO : < 200 OK [3299]
2017-12-31 21:32:01,879 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 324}
2017-12-31 21:32:01,884 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,891 : INFO : < 200 OK [3275]
2017-12-31 21:32:01,896 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 324}
2017-12-31 21:32:01,900 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,906 : INFO : < 200 OK [3275]
2017-12-31 21:32:01,911 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 324}
2017-12-31 21:32:01,915 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,923 : INFO : < 200 OK [3281]
2017-12-31 21:32:01,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 324}
2017-12-31 21:32:01,934 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,940 : INFO : < 200 OK [3275]
2017-12-31 21:32:01,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 324}
2017-12-31 21:32:01,949 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,955 : INFO : < 200 OK [3275]
2017-12-31 21:32:01,960 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 324}
2017-12-31 21:32:01,964 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,970 : INFO : < 200 OK [3281]
2017-12-31 21:32:01,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 324}
2017-12-31 21:32:01,979 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,985 : INFO : < 200 OK [3275]
2017-12-31 21:32:01,989 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 324}
2017-12-31 21:32:01,993 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:01,999 : INFO : < 200 OK [3275]
2017-12-31 21:32:02,004 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 324}
2017-12-31 21:32:02,008 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,014 : INFO : < 200 OK [3281]
2017-12-31 21:32:02,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 324}
2017-12-31 21:32:02,023 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,029 : INFO : < 200 OK [3275]
2017-12-31 21:32:02,034 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 324}
2017-12-31 21:32:02,038 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,044 : INFO : < 200 OK [3275]
2017-12-31 21:32:02,049 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 324}
2017-12-31 21:32:02,053 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,058 : INFO : < 200 OK [3281]
2017-12-31 21:32:02,064 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 339}
2017-12-31 21:32:02,068 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,073 : INFO : < 200 OK [3316]
2017-12-31 21:32:02,078 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 339}
2017-12-31 21:32:02,082 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,088 : INFO : < 200 OK [3315]
2017-12-31 21:32:02,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 339}
2017-12-31 21:32:02,096 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,102 : INFO : < 200 OK [3316]
2017-12-31 21:32:02,107 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 339}
2017-12-31 21:32:02,111 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,116 : INFO : < 200 OK [3332]
2017-12-31 21:32:02,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 325}
2017-12-31 21:32:02,125 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,131 : INFO : < 200 OK [3323]
2017-12-31 21:32:02,136 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 325}
2017-12-31 21:32:02,139 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,152 : INFO : < 200 OK [3326]
2017-12-31 21:32:02,157 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 325}
2017-12-31 21:32:02,160 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,166 : INFO : < 200 OK [3323]

2017-12-31 21:32:02,171 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 325}
2017-12-31 21:32:02,175 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,181 : INFO : < 200 OK [3326]
2017-12-31 21:32:02,186 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 325}
2017-12-31 21:32:02,190 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,196 : INFO : < 200 OK [3323]
2017-12-31 21:32:02,201 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 325}
2017-12-31 21:32:02,204 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,210 : INFO : < 200 OK [3326]
2017-12-31 21:32:02,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 340}
2017-12-31 21:32:02,219 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,224 : INFO : < 200 OK [3341]
2017-12-31 21:32:02,229 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 340}
2017-12-31 21:32:02,232 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,239 : INFO : < 200 OK [3341]
2017-12-31 21:32:02,245 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 340}
2017-12-31 21:32:02,249 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,256 : INFO : < 200 OK [3347]
2017-12-31 21:32:02,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 340}
2017-12-31 21:32:02,265 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,272 : INFO : < 200 OK [3344]
2017-12-31 21:32:02,278 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 341}
2017-12-31 21:32:02,282 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,291 : INFO : < 200 OK [3309]
2017-12-31 21:32:02,297 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 341}
2017-12-31 21:32:02,300 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,307 : INFO : < 200 OK [3309]
2017-12-31 21:32:02,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 341}
2017-12-31 21:32:02,316 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,325 : INFO : < 200 OK [3315]
2017-12-31 21:32:02,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 327}
2017-12-31 21:32:02,335 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,342 : INFO : < 200 OK [3350]
2017-12-31 21:32:02,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 327}
2017-12-31 21:32:02,350 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,357 : INFO : < 200 OK [3353]
2017-12-31 21:32:02,363 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 221}
2017-12-31 21:32:02,368 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,375 : INFO : < 200 OK [3288]
2017-12-31 21:32:02,382 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 221}
2017-12-31 21:32:02,386 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,393 : INFO : < 200 OK [3289]
2017-12-31 21:32:02,398 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 221}
2017-12-31 21:32:02,402 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,409 : INFO : < 200 OK [3302]
2017-12-31 21:32:02,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 342}
2017-12-31 21:32:02,421 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,427 : INFO : < 200 OK [3325]
2017-12-31 21:32:02,433 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 328}
2017-12-31 21:32:02,437 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,443 : INFO : < 200 OK [3291]
2017-12-31 21:32:02,449 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 328}
2017-12-31 21:32:02,455 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,461 : INFO : < 200 OK [3294]
2017-12-31 21:32:02,466 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 328}
2017-12-31 21:32:02,470 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,476 : INFO : < 200 OK [3291]
2017-12-31 21:32:02,482 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 328}
2017-12-31 21:32:02,487 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,494 : INFO : < 200 OK [3294]
2017-12-31 21:32:02,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 328}
2017-12-31 21:32:02,504 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,511 : INFO : < 200 OK [3291]
2017-12-31 21:32:02,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 328}
2017-12-31 21:32:02,521 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,528 : INFO : < 200 OK [3294]
2017-12-31 21:32:02,534 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 343}
2017-12-31 21:32:02,539 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,545 : INFO : < 200 OK [3309]
2017-12-31 21:32:02,551 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 329}
2017-12-31 21:32:02,556 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,564 : INFO : < 200 OK [3293]
2017-12-31 21:32:02,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 329}

2017-12-31 21:32:02,579 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,586 : INFO : < 200 OK [3293]
2017-12-31 21:32:02,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 329}
2017-12-31 21:32:02,597 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,603 : INFO : < 200 OK [3299]
2017-12-31 21:32:02,611 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 330}
2017-12-31 21:32:02,615 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,622 : INFO : < 200 OK [3281]
2017-12-31 21:32:02,628 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 345}
2017-12-31 21:32:02,632 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,639 : INFO : < 200 OK [3294]
2017-12-31 21:32:02,645 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 331}
2017-12-31 21:32:02,649 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,656 : INFO : < 200 OK [3295]
2017-12-31 21:32:02,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 331}
2017-12-31 21:32:02,665 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,672 : INFO : < 200 OK [3312]
2017-12-31 21:32:02,679 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 331}
2017-12-31 21:32:02,682 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,690 : INFO : < 200 OK [3295]
2017-12-31 21:32:02,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 331}
2017-12-31 21:32:02,700 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,707 : INFO : < 200 OK [3312]
2017-12-31 21:32:02,712 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 346}
2017-12-31 21:32:02,717 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,725 : INFO : < 200 OK [3302]
2017-12-31 21:32:02,730 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 346}
2017-12-31 21:32:02,735 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,742 : INFO : < 200 OK [3315]
2017-12-31 21:32:02,749 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 347}
2017-12-31 21:32:02,754 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,760 : INFO : < 200 OK [3289]
2017-12-31 21:32:02,767 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 348}
2017-12-31 21:32:02,771 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,779 : INFO : < 200 OK [3302]
2017-12-31 21:32:02,785 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 348}
2017-12-31 21:32:02,790 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,798 : INFO : < 200 OK [3317]
2017-12-31 21:32:02,804 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 348}
2017-12-31 21:32:02,808 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,813 : INFO : < 200 OK [3302]
2017-12-31 21:32:02,818 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 348}
2017-12-31 21:32:02,822 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,828 : INFO : < 200 OK [3317]
2017-12-31 21:32:02,834 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 348}
2017-12-31 21:32:02,838 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,844 : INFO : < 200 OK [3302]
2017-12-31 21:32:02,850 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 348}
2017-12-31 21:32:02,855 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,860 : INFO : < 200 OK [3317]
2017-12-31 21:32:02,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 354}
2017-12-31 21:32:02,871 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,881 : INFO : < 200 OK [3281]
2017-12-31 21:32:02,889 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 355}
2017-12-31 21:32:02,893 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,900 : INFO : < 200 OK [3299]
2017-12-31 21:32:02,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 355}
2017-12-31 21:32:02,910 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,916 : INFO : < 200 OK [3302]
2017-12-31 21:32:02,921 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 355}
2017-12-31 21:32:02,925 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,931 : INFO : < 200 OK [3299]
2017-12-31 21:32:02,937 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 355}
2017-12-31 21:32:02,940 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,947 : INFO : < 200 OK [3302]
2017-12-31 21:32:02,952 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 355}
2017-12-31 21:32:02,956 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,963 : INFO : < 200 OK [3299]
2017-12-31 21:32:02,970 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 355}
2017-12-31 21:32:02,974 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,980 : INFO : < 200 OK [3302]
2017-12-31 21:32:02,985 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 350}
2017-12-31 21:32:02,990 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:02,998 : INFO : < 200 OK [3293]

2017-12-31 21:32:03,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 350}
2017-12-31 21:32:03,008 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,015 : INFO : < 200 OK [3299]
2017-12-31 21:32:03,022 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 350}
2017-12-31 21:32:03,026 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,032 : INFO : < 200 OK [3293]
2017-12-31 21:32:03,041 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 351}
2017-12-31 21:32:03,046 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,054 : INFO : < 200 OK [3287]
2017-12-31 21:32:03,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 351}
2017-12-31 21:32:03,066 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,075 : INFO : < 200 OK [3287]
2017-12-31 21:32:03,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 351}
2017-12-31 21:32:03,085 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,096 : INFO : < 200 OK [3293]
2017-12-31 21:32:03,103 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 372}
2017-12-31 21:32:03,107 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,114 : INFO : < 200 OK [3277]
2017-12-31 21:32:03,120 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 358}
2017-12-31 21:32:03,125 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,131 : INFO : < 200 OK [3325]
2017-12-31 21:32:03,139 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 358}
2017-12-31 21:32:03,143 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,150 : INFO : < 200 OK [3328]
2017-12-31 21:32:03,156 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 358}
2017-12-31 21:32:03,161 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,168 : INFO : < 200 OK [3325]
2017-12-31 21:32:03,176 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 358}
2017-12-31 21:32:03,180 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,187 : INFO : < 200 OK [3328]
2017-12-31 21:32:03,194 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 358}
2017-12-31 21:32:03,197 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,205 : INFO : < 200 OK [3325]
2017-12-31 21:32:03,211 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 358}
2017-12-31 21:32:03,215 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,224 : INFO : < 200 OK [3328]
2017-12-31 21:32:03,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 9}
2017-12-31 21:32:03,236 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:32:03,243 : INFO : < 200 OK [3278]
2017-12-31 21:32:03,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 17}
2017-12-31 21:32:03,254 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:03,261 : INFO : < 200 OK [3308]
2017-12-31 21:32:03,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 373}
2017-12-31 21:32:03,272 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,279 : INFO : < 200 OK [3299]
2017-12-31 21:32:03,285 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 373}
2017-12-31 21:32:03,290 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,296 : INFO : < 200 OK [3316]
2017-12-31 21:32:03,303 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 373}
2017-12-31 21:32:03,307 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,314 : INFO : < 200 OK [3299]
2017-12-31 21:32:03,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 373}
2017-12-31 21:32:03,326 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,332 : INFO : < 200 OK [3316]
2017-12-31 21:32:03,338 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 373}
2017-12-31 21:32:03,343 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,350 : INFO : < 200 OK [3299]
2017-12-31 21:32:03,356 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 373}
2017-12-31 21:32:03,361 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,367 : INFO : < 200 OK [3316]
2017-12-31 21:32:03,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 359}
2017-12-31 21:32:03,378 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,386 : INFO : < 200 OK [3318]
2017-12-31 21:32:03,392 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 265}
2017-12-31 21:32:03,398 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,404 : INFO : < 200 OK [3336]
2017-12-31 21:32:03,410 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 374}
2017-12-31 21:32:03,413 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,419 : INFO : < 200 OK [3278]
2017-12-31 21:32:03,425 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 374}
2017-12-31 21:32:03,430 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,437 : INFO : < 200 OK [3278]
2017-12-31 21:32:03,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 374}

2017-12-31 21:32:03,448 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,455 : INFO : < 200 OK [3278]
2017-12-31 21:32:03,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 360}
2017-12-31 21:32:03,465 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,472 : INFO : < 200 OK [3298]
2017-12-31 21:32:03,478 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 360}
2017-12-31 21:32:03,482 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,488 : INFO : < 200 OK [3298]
2017-12-31 21:32:03,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 375}
2017-12-31 21:32:03,500 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,507 : INFO : < 200 OK [3278]
2017-12-31 21:32:03,515 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 375}
2017-12-31 21:32:03,519 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,527 : INFO : < 200 OK [3278]
2017-12-31 21:32:03,535 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 375}
2017-12-31 21:32:03,540 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,546 : INFO : < 200 OK [3278]
2017-12-31 21:32:03,554 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 361}
2017-12-31 21:32:03,558 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,566 : INFO : < 200 OK [3270]
2017-12-31 21:32:03,572 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 361}
2017-12-31 21:32:03,576 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,582 : INFO : < 200 OK [3270]
2017-12-31 21:32:03,588 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 361}
2017-12-31 21:32:03,594 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,600 : INFO : < 200 OK [3270]
2017-12-31 21:32:03,606 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 376}
2017-12-31 21:32:03,610 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,617 : INFO : < 200 OK [3274]
2017-12-31 21:32:03,623 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 376}
2017-12-31 21:32:03,627 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,633 : INFO : < 200 OK [3274]
2017-12-31 21:32:03,638 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 376}
2017-12-31 21:32:03,642 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,648 : INFO : < 200 OK [3274]
2017-12-31 21:32:03,654 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 362}
2017-12-31 21:32:03,658 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,664 : INFO : < 200 OK [3284]
2017-12-31 21:32:03,671 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 362}
2017-12-31 21:32:03,675 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,681 : INFO : < 200 OK [3284]
2017-12-31 21:32:03,692 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 377}
2017-12-31 21:32:03,697 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,704 : INFO : < 200 OK [3304]
2017-12-31 21:32:03,710 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 267}
2017-12-31 21:32:03,714 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,720 : INFO : < 200 OK [3328]
2017-12-31 21:32:03,728 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 378}
2017-12-31 21:32:03,732 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,739 : INFO : < 200 OK [3305]
2017-12-31 21:32:03,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 378}
2017-12-31 21:32:03,749 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,756 : INFO : < 200 OK [3305]
2017-12-31 21:32:03,762 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 378}
2017-12-31 21:32:03,768 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,775 : INFO : < 200 OK [3305]
2017-12-31 21:32:03,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 378}
2017-12-31 21:32:03,785 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,792 : INFO : < 200 OK [3305]
2017-12-31 21:32:03,798 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 364}
2017-12-31 21:32:03,802 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,810 : INFO : < 200 OK [3313]
2017-12-31 21:32:03,816 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 379}
2017-12-31 21:32:03,821 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,833 : INFO : < 200 OK [3274]
2017-12-31 21:32:03,839 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 379}
2017-12-31 21:32:03,843 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,850 : INFO : < 200 OK [3274]
2017-12-31 21:32:03,858 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 379}
2017-12-31 21:32:03,862 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,868 : INFO : < 200 OK [3274]
2017-12-31 21:32:03,876 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 365}
2017-12-31 21:32:03,880 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,888 : INFO : < 200 OK [3323]

2017-12-31 21:32:03,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 380}
2017-12-31 21:32:03,899 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,906 : INFO : < 200 OK [3308]
2017-12-31 21:32:03,912 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 366}
2017-12-31 21:32:03,917 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,924 : INFO : < 200 OK [3278]
2017-12-31 21:32:03,929 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 366}
2017-12-31 21:32:03,935 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,942 : INFO : < 200 OK [3277]
2017-12-31 21:32:03,948 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 366}
2017-12-31 21:32:03,952 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,959 : INFO : < 200 OK [3278]
2017-12-31 21:32:03,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 366}
2017-12-31 21:32:03,970 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,977 : INFO : < 200 OK [3277]
2017-12-31 21:32:03,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 366}
2017-12-31 21:32:03,989 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:03,994 : INFO : < 200 OK [3278]
2017-12-31 21:32:04,000 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 366}
2017-12-31 21:32:04,005 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,012 : INFO : < 200 OK [3277]
2017-12-31 21:32:04,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 382}
2017-12-31 21:32:04,025 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,031 : INFO : < 200 OK [3364]
2017-12-31 21:32:04,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 368}
2017-12-31 21:32:04,042 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,050 : INFO : < 200 OK [3275]
2017-12-31 21:32:04,057 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 368}
2017-12-31 21:32:04,061 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,068 : INFO : < 200 OK [3275]
2017-12-31 21:32:04,076 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 293}
2017-12-31 21:32:04,079 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,086 : INFO : < 200 OK [3338]
2017-12-31 21:32:04,091 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 293}
2017-12-31 21:32:04,095 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,102 : INFO : < 200 OK [3355]
2017-12-31 21:32:04,109 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 369}
2017-12-31 21:32:04,113 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,120 : INFO : < 200 OK [3317]
2017-12-31 21:32:04,126 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 384}
2017-12-31 21:32:04,131 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,138 : INFO : < 200 OK [3287]
2017-12-31 21:32:04,144 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 384}
2017-12-31 21:32:04,149 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,156 : INFO : < 200 OK [3287]
2017-12-31 21:32:04,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 299}
2017-12-31 21:32:04,166 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,173 : INFO : < 200 OK [3350]
2017-12-31 21:32:04,180 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 299}
2017-12-31 21:32:04,184 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,191 : INFO : < 200 OK [3367]
2017-12-31 21:32:04,198 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 370}
2017-12-31 21:32:04,202 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,209 : INFO : < 200 OK [3288]
2017-12-31 21:32:04,218 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 387}
2017-12-31 21:32:04,224 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,230 : INFO : < 200 OK [3279]
2017-12-31 21:32:04,236 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 387}
2017-12-31 21:32:04,241 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,248 : INFO : < 200 OK [3279]
2017-12-31 21:32:04,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 387}
2017-12-31 21:32:04,259 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,266 : INFO : < 200 OK [3279]
2017-12-31 21:32:04,274 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 387}
2017-12-31 21:32:04,278 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,286 : INFO : < 200 OK [3279]
2017-12-31 21:32:04,296 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 64}
2017-12-31 21:32:04,300 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:04,307 : INFO : < 200 OK [3307]
2017-12-31 21:32:04,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 64}
2017-12-31 21:32:04,317 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:04,325 : INFO : < 200 OK [3307]
2017-12-31 21:32:04,331 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 64}

2017-12-31 21:32:04,335 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:04,343 : INFO : < 200 OK [3307]
2017-12-31 21:32:04,350 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 80}
2017-12-31 21:32:04,355 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:04,362 : INFO : < 200 OK [3301]
2017-12-31 21:32:04,369 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 80}
2017-12-31 21:32:04,373 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:04,380 : INFO : < 200 OK [3301]
2017-12-31 21:32:04,387 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 80}
2017-12-31 21:32:04,391 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:04,398 : INFO : < 200 OK [3301]
2017-12-31 21:32:04,408 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 394}
2017-12-31 21:32:04,413 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,420 : INFO : < 200 OK [3292]
2017-12-31 21:32:04,428 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 389}
2017-12-31 21:32:04,433 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,440 : INFO : < 200 OK [3314]
2017-12-31 21:32:04,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 389}
2017-12-31 21:32:04,451 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,459 : INFO : < 200 OK [3314]
2017-12-31 21:32:04,465 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 389}
2017-12-31 21:32:04,469 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,476 : INFO : < 200 OK [3314]
2017-12-31 21:32:04,483 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 389}
2017-12-31 21:32:04,488 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,494 : INFO : < 200 OK [3314]
2017-12-31 21:32:04,501 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 389}
2017-12-31 21:32:04,506 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,512 : INFO : < 200 OK [3314]
2017-12-31 21:32:04,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 395}
2017-12-31 21:32:04,526 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,532 : INFO : < 200 OK [3307]
2017-12-31 21:32:04,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 395}
2017-12-31 21:32:04,544 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,550 : INFO : < 200 OK [3307]
2017-12-31 21:32:04,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 390}
2017-12-31 21:32:04,561 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,568 : INFO : < 200 OK [3347]
2017-12-31 21:32:04,575 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 390}
2017-12-31 21:32:04,580 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,587 : INFO : < 200 OK [3347]
2017-12-31 21:32:04,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 390}
2017-12-31 21:32:04,598 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,606 : INFO : < 200 OK [3347]
2017-12-31 21:32:04,612 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 390}
2017-12-31 21:32:04,616 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,622 : INFO : < 200 OK [3347]
2017-12-31 21:32:04,629 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 390}
2017-12-31 21:32:04,633 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,641 : INFO : < 200 OK [3347]
2017-12-31 21:32:04,651 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 397}
2017-12-31 21:32:04,655 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,663 : INFO : < 200 OK [3311]
2017-12-31 21:32:04,669 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 397}
2017-12-31 21:32:04,674 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,681 : INFO : < 200 OK [3311]
2017-12-31 21:32:04,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 362}
2017-12-31 21:32:04,693 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,699 : INFO : < 200 OK [3284]
2017-12-31 21:32:04,706 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 362}
2017-12-31 21:32:04,710 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,716 : INFO : < 200 OK [3284]
2017-12-31 21:32:04,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 412}
2017-12-31 21:32:04,729 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,735 : INFO : < 200 OK [3288]
2017-12-31 21:32:04,742 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 412}
2017-12-31 21:32:04,747 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,754 : INFO : < 200 OK [3288]
2017-12-31 21:32:04,760 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 398}
2017-12-31 21:32:04,765 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,772 : INFO : < 200 OK [3317]
2017-12-31 21:32:04,778 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 398}
2017-12-31 21:32:04,782 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,789 : INFO : < 200 OK [3317]

2017-12-31 21:32:04,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 398}
2017-12-31 21:32:04,800 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,808 : INFO : < 200 OK [3317]
2017-12-31 21:32:04,814 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 398}
2017-12-31 21:32:04,818 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,825 : INFO : < 200 OK [3317]
2017-12-31 21:32:04,832 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 413}
2017-12-31 21:32:04,837 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,844 : INFO : < 200 OK [3336]
2017-12-31 21:32:04,850 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 413}
2017-12-31 21:32:04,856 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,862 : INFO : < 200 OK [3334]
2017-12-31 21:32:04,868 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 413}
2017-12-31 21:32:04,873 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,879 : INFO : < 200 OK [3340]
2017-12-31 21:32:04,885 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 413}
2017-12-31 21:32:04,889 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,897 : INFO : < 200 OK [3350]
2017-12-31 21:32:04,902 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 413}
2017-12-31 21:32:04,907 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,913 : INFO : < 200 OK [3336]
2017-12-31 21:32:04,919 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 413}
2017-12-31 21:32:04,922 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,930 : INFO : < 200 OK [3334]
2017-12-31 21:32:04,936 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 413}
2017-12-31 21:32:04,940 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,947 : INFO : < 200 OK [3340]
2017-12-31 21:32:04,954 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 413}
2017-12-31 21:32:04,958 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,964 : INFO : < 200 OK [3350]
2017-12-31 21:32:04,973 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 414}
2017-12-31 21:32:04,977 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:04,983 : INFO : < 200 OK [3296]
2017-12-31 21:32:04,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 414}
2017-12-31 21:32:04,995 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,001 : INFO : < 200 OK [3296]
2017-12-31 21:32:05,010 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 400}
2017-12-31 21:32:05,014 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,021 : INFO : < 200 OK [3353]
2017-12-31 21:32:05,028 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 400}
2017-12-31 21:32:05,032 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,039 : INFO : < 200 OK [3352]
2017-12-31 21:32:05,046 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 400}
2017-12-31 21:32:05,050 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,057 : INFO : < 200 OK [3353]
2017-12-31 21:32:05,064 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 415}
2017-12-31 21:32:05,068 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,075 : INFO : < 200 OK [3285]
2017-12-31 21:32:05,082 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 415}
2017-12-31 21:32:05,087 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,099 : INFO : < 200 OK [3285]
2017-12-31 21:32:05,107 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 416}
2017-12-31 21:32:05,111 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,121 : INFO : < 200 OK [3357]
2017-12-31 21:32:05,127 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 416}
2017-12-31 21:32:05,131 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,140 : INFO : < 200 OK [3371]
2017-12-31 21:32:05,148 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 403}
2017-12-31 21:32:05,152 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,160 : INFO : < 200 OK [3362]
2017-12-31 21:32:05,166 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 403}
2017-12-31 21:32:05,171 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,177 : INFO : < 200 OK [3361]
2017-12-31 21:32:05,182 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 403}
2017-12-31 21:32:05,186 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,192 : INFO : < 200 OK [3362]
2017-12-31 21:32:05,197 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:05,201 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,208 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,214 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:05,217 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,223 : INFO : < 200 OK [3332]
2017-12-31 21:32:05,228 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}

2017-12-31 21:32:05,232 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,238 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:05,248 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,255 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,260 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:05,263 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,270 : INFO : < 200 OK [3332]
2017-12-31 21:32:05,276 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}
2017-12-31 21:32:05,279 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,285 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,291 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:05,295 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,301 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:05,310 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,316 : INFO : < 200 OK [3332]
2017-12-31 21:32:05,321 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}
2017-12-31 21:32:05,325 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,331 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,337 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:05,341 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,349 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,355 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:05,359 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,365 : INFO : < 200 OK [3332]
2017-12-31 21:32:05,370 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}
2017-12-31 21:32:05,374 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,379 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,386 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:05,391 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,397 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,401 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:05,406 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,411 : INFO : < 200 OK [3332]
2017-12-31 21:32:05,416 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}
2017-12-31 21:32:05,420 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,426 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,431 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:05,435 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,441 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:05,450 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,456 : INFO : < 200 OK [3332]
2017-12-31 21:32:05,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}
2017-12-31 21:32:05,465 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,471 : INFO : < 200 OK [3333]
2017-12-31 21:32:05,476 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 404}
2017-12-31 21:32:05,480 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,486 : INFO : < 200 OK [3316]
2017-12-31 21:32:05,491 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 404}
2017-12-31 21:32:05,495 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,503 : INFO : < 200 OK [3314]
2017-12-31 21:32:05,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 404}
2017-12-31 21:32:05,513 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,523 : INFO : < 200 OK [3320]
2017-12-31 21:32:05,529 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 404}
2017-12-31 21:32:05,533 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,541 : INFO : < 200 OK [3313]
2017-12-31 21:32:05,546 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 404}
2017-12-31 21:32:05,549 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,556 : INFO : < 200 OK [3313]
2017-12-31 21:32:05,561 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 404}
2017-12-31 21:32:05,565 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,571 : INFO : < 200 OK [3314]
2017-12-31 21:32:05,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 404}
2017-12-31 21:32:05,580 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,586 : INFO : < 200 OK [3330]
2017-12-31 21:32:05,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 419}
2017-12-31 21:32:05,597 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,603 : INFO : < 200 OK [3290]
2017-12-31 21:32:05,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 419}
2017-12-31 21:32:05,613 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,619 : INFO : < 200 OK [3290]

2017-12-31 21:32:05,630 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 407}
2017-12-31 21:32:05,634 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,643 : INFO : < 200 OK [3276]
2017-12-31 21:32:05,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 407}
2017-12-31 21:32:05,654 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,661 : INFO : < 200 OK [3276]
2017-12-31 21:32:05,667 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 407}
2017-12-31 21:32:05,672 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,679 : INFO : < 200 OK [3276]
2017-12-31 21:32:05,691 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 433}
2017-12-31 21:32:05,695 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,701 : INFO : < 200 OK [3327]
2017-12-31 21:32:05,709 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 247}
2017-12-31 21:32:05,713 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,719 : INFO : < 200 OK [3305]
2017-12-31 21:32:05,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 247}
2017-12-31 21:32:05,731 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,738 : INFO : < 200 OK [3319]
2017-12-31 21:32:05,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 394}
2017-12-31 21:32:05,747 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,752 : INFO : < 200 OK [3292]
2017-12-31 21:32:05,758 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 373}
2017-12-31 21:32:05,762 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,769 : INFO : < 200 OK [3299]
2017-12-31 21:32:05,776 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 373}
2017-12-31 21:32:05,780 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,785 : INFO : < 200 OK [3316]
2017-12-31 21:32:05,793 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 373}
2017-12-31 21:32:05,797 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,803 : INFO : < 200 OK [3299]
2017-12-31 21:32:05,808 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 373}
2017-12-31 21:32:05,812 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,818 : INFO : < 200 OK [3316]
2017-12-31 21:32:05,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 373}
2017-12-31 21:32:05,827 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,832 : INFO : < 200 OK [3299]
2017-12-31 21:32:05,837 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 373}
2017-12-31 21:32:05,841 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,847 : INFO : < 200 OK [3316]
2017-12-31 21:32:05,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 428}
2017-12-31 21:32:05,859 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,864 : INFO : < 200 OK [3278]
2017-12-31 21:32:05,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 428}
2017-12-31 21:32:05,874 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,881 : INFO : < 200 OK [3276]
2017-12-31 21:32:05,886 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 428}
2017-12-31 21:32:05,890 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,895 : INFO : < 200 OK [3282]
2017-12-31 21:32:05,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 428}
2017-12-31 21:32:05,903 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,909 : INFO : < 200 OK [3275]
2017-12-31 21:32:05,914 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 428}
2017-12-31 21:32:05,917 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,925 : INFO : < 200 OK [3292]
2017-12-31 21:32:05,931 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 429}
2017-12-31 21:32:05,935 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,944 : INFO : < 200 OK [3312]
2017-12-31 21:32:05,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 429}
2017-12-31 21:32:05,953 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,959 : INFO : < 200 OK [3309]
2017-12-31 21:32:05,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 359}
2017-12-31 21:32:05,969 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,976 : INFO : < 200 OK [3318]
2017-12-31 21:32:05,982 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 435}
2017-12-31 21:32:05,986 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:05,992 : INFO : < 200 OK [3280]
2017-12-31 21:32:05,998 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 435}
2017-12-31 21:32:06,005 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,011 : INFO : < 200 OK [3280]
2017-12-31 21:32:06,017 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 430}
2017-12-31 21:32:06,022 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,028 : INFO : < 200 OK [3323]
2017-12-31 21:32:06,034 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 390}

2017-12-31 21:32:06,037 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,045 : INFO : < 200 OK [3347]
2017-12-31 21:32:06,051 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 390}
2017-12-31 21:32:06,057 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,063 : INFO : < 200 OK [3347]
2017-12-31 21:32:06,070 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 390}
2017-12-31 21:32:06,074 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,081 : INFO : < 200 OK [3347]
2017-12-31 21:32:06,088 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 390}
2017-12-31 21:32:06,092 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,098 : INFO : < 200 OK [3347]
2017-12-31 21:32:06,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 390}
2017-12-31 21:32:06,109 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,115 : INFO : < 200 OK [3347]
2017-12-31 21:32:06,123 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 431}
2017-12-31 21:32:06,127 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,134 : INFO : < 200 OK [3283]
2017-12-31 21:32:06,142 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 143}
2017-12-31 21:32:06,146 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,153 : INFO : < 200 OK [3347]
2017-12-31 21:32:06,160 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 143}
2017-12-31 21:32:06,164 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,171 : INFO : < 200 OK [3346]
2017-12-31 21:32:06,178 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 452}
2017-12-31 21:32:06,181 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,190 : INFO : < 200 OK [3316]
2017-12-31 21:32:06,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 452}
2017-12-31 21:32:06,199 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,207 : INFO : < 200 OK [3315]
2017-12-31 21:32:06,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 452}
2017-12-31 21:32:06,217 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,226 : INFO : < 200 OK [3332]
2017-12-31 21:32:06,232 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 452}
2017-12-31 21:32:06,237 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,244 : INFO : < 200 OK [3316]
2017-12-31 21:32:06,250 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 452}
2017-12-31 21:32:06,254 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,261 : INFO : < 200 OK [3315]
2017-12-31 21:32:06,268 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 452}
2017-12-31 21:32:06,272 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,280 : INFO : < 200 OK [3332]
2017-12-31 21:32:06,287 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 374}
2017-12-31 21:32:06,291 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,298 : INFO : < 200 OK [3278]
2017-12-31 21:32:06,304 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 374}
2017-12-31 21:32:06,309 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,315 : INFO : < 200 OK [3278]
2017-12-31 21:32:06,323 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 374}
2017-12-31 21:32:06,326 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,333 : INFO : < 200 OK [3278]
2017-12-31 21:32:06,342 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 439}
2017-12-31 21:32:06,345 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,351 : INFO : < 200 OK [3318]
2017-12-31 21:32:06,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 454}
2017-12-31 21:32:06,362 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,368 : INFO : < 200 OK [3314]
2017-12-31 21:32:06,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 454}
2017-12-31 21:32:06,380 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,386 : INFO : < 200 OK [3328]
2017-12-31 21:32:06,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 454}
2017-12-31 21:32:06,395 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,401 : INFO : < 200 OK [3314]
2017-12-31 21:32:06,408 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 454}
2017-12-31 21:32:06,411 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,417 : INFO : < 200 OK [3328]
2017-12-31 21:32:06,425 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 455}
2017-12-31 21:32:06,428 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,434 : INFO : < 200 OK [3290]
2017-12-31 21:32:06,442 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 456}
2017-12-31 21:32:06,446 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,451 : INFO : < 200 OK [3339]
2017-12-31 21:32:06,458 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 456}
2017-12-31 21:32:06,461 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,467 : INFO : < 200 OK [3338]

2017-12-31 21:32:06,472 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 456}
2017-12-31 21:32:06,476 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,482 : INFO : < 200 OK [3339]
2017-12-31 21:32:06,488 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 456}
2017-12-31 21:32:06,491 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,497 : INFO : < 200 OK [3339]
2017-12-31 21:32:06,503 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 456}
2017-12-31 21:32:06,507 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,513 : INFO : < 200 OK [3338]
2017-12-31 21:32:06,520 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 456}
2017-12-31 21:32:06,526 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,531 : INFO : < 200 OK [3339]
2017-12-31 21:32:06,540 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 456}
2017-12-31 21:32:06,543 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,549 : INFO : < 200 OK [3339]
2017-12-31 21:32:06,556 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 456}
2017-12-31 21:32:06,559 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,565 : INFO : < 200 OK [3338]
2017-12-31 21:32:06,570 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 456}
2017-12-31 21:32:06,574 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,579 : INFO : < 200 OK [3339]
2017-12-31 21:32:06,584 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 456}
2017-12-31 21:32:06,589 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,595 : INFO : < 200 OK [3339]
2017-12-31 21:32:06,600 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 456}
2017-12-31 21:32:06,604 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,610 : INFO : < 200 OK [3338]
2017-12-31 21:32:06,616 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 456}
2017-12-31 21:32:06,620 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,626 : INFO : < 200 OK [3339]
2017-12-31 21:32:06,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 457}
2017-12-31 21:32:06,638 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,648 : INFO : < 200 OK [3322]
2017-12-31 21:32:06,659 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 375}
2017-12-31 21:32:06,664 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,675 : INFO : < 200 OK [3278]
2017-12-31 21:32:06,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 375}
2017-12-31 21:32:06,684 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,692 : INFO : < 200 OK [3278]
2017-12-31 21:32:06,697 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 375}
2017-12-31 21:32:06,700 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,708 : INFO : < 200 OK [3278]
2017-12-31 21:32:06,714 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 361}
2017-12-31 21:32:06,718 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,724 : INFO : < 200 OK [3270]
2017-12-31 21:32:06,730 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 361}
2017-12-31 21:32:06,734 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,740 : INFO : < 200 OK [3270]
2017-12-31 21:32:06,746 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 361}
2017-12-31 21:32:06,749 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,756 : INFO : < 200 OK [3270]
2017-12-31 21:32:06,761 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 444}
2017-12-31 21:32:06,765 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,771 : INFO : < 200 OK [3327]
2017-12-31 21:32:06,777 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 444}
2017-12-31 21:32:06,780 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,786 : INFO : < 200 OK [3324]
2017-12-31 21:32:06,792 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 444}
2017-12-31 21:32:06,795 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,801 : INFO : < 200 OK [3327]
2017-12-31 21:32:06,806 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 444}
2017-12-31 21:32:06,810 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,816 : INFO : < 200 OK [3324]
2017-12-31 21:32:06,823 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 376}
2017-12-31 21:32:06,826 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,832 : INFO : < 200 OK [3274]
2017-12-31 21:32:06,838 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 376}
2017-12-31 21:32:06,842 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,848 : INFO : < 200 OK [3274]
2017-12-31 21:32:06,854 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 376}
2017-12-31 21:32:06,857 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,863 : INFO : < 200 OK [3274]
2017-12-31 21:32:06,870 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 377}

2017-12-31 21:32:06,873 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,879 : INFO : < 200 OK [3304]
2017-12-31 21:32:06,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 460}
2017-12-31 21:32:06,888 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,894 : INFO : < 200 OK [3330]
2017-12-31 21:32:06,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 446}
2017-12-31 21:32:06,904 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,910 : INFO : < 200 OK [3272]
2017-12-31 21:32:06,915 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 446}
2017-12-31 21:32:06,918 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,925 : INFO : < 200 OK [3270]
2017-12-31 21:32:06,930 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 446}
2017-12-31 21:32:06,934 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,940 : INFO : < 200 OK [3271]
2017-12-31 21:32:06,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 446}
2017-12-31 21:32:06,949 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,956 : INFO : < 200 OK [3272]
2017-12-31 21:32:06,961 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 446}
2017-12-31 21:32:06,965 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,970 : INFO : < 200 OK [3272]
2017-12-31 21:32:06,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 446}
2017-12-31 21:32:06,979 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:06,985 : INFO : < 200 OK [3270]
2017-12-31 21:32:06,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 446}
2017-12-31 21:32:06,994 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,000 : INFO : < 200 OK [3271]
2017-12-31 21:32:07,006 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 446}
2017-12-31 21:32:07,009 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,015 : INFO : < 200 OK [3272]
2017-12-31 21:32:07,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 446}
2017-12-31 21:32:07,024 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,030 : INFO : < 200 OK [3272]
2017-12-31 21:32:07,035 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 446}
2017-12-31 21:32:07,038 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,044 : INFO : < 200 OK [3270]
2017-12-31 21:32:07,049 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 446}
2017-12-31 21:32:07,053 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,059 : INFO : < 200 OK [3271]
2017-12-31 21:32:07,064 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 446}
2017-12-31 21:32:07,067 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,073 : INFO : < 200 OK [3272]
2017-12-31 21:32:07,081 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 378}
2017-12-31 21:32:07,085 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,091 : INFO : < 200 OK [3305]
2017-12-31 21:32:07,097 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 378}
2017-12-31 21:32:07,100 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,106 : INFO : < 200 OK [3305]
2017-12-31 21:32:07,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 378}
2017-12-31 21:32:07,115 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,121 : INFO : < 200 OK [3305]
2017-12-31 21:32:07,126 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 378}
2017-12-31 21:32:07,130 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,136 : INFO : < 200 OK [3305]
2017-12-31 21:32:07,142 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 364}
2017-12-31 21:32:07,146 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,152 : INFO : < 200 OK [3313]
2017-12-31 21:32:07,159 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 448}
2017-12-31 21:32:07,163 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,170 : INFO : < 200 OK [3295]
2017-12-31 21:32:07,175 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 448}
2017-12-31 21:32:07,179 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,184 : INFO : < 200 OK [3296]
2017-12-31 21:32:07,190 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 448}
2017-12-31 21:32:07,193 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,200 : INFO : < 200 OK [3295]
2017-12-31 21:32:07,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 448}
2017-12-31 21:32:07,210 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,216 : INFO : < 200 OK [3296]
2017-12-31 21:32:07,222 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 414}
2017-12-31 21:32:07,227 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,234 : INFO : < 200 OK [3296]
2017-12-31 21:32:07,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 414}
2017-12-31 21:32:07,244 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,249 : INFO : < 200 OK [3296]

2017-12-31 21:32:07,255 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 463}
2017-12-31 21:32:07,259 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,264 : INFO : < 200 OK [3329]
2017-12-31 21:32:07,270 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 400}
2017-12-31 21:32:07,274 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,279 : INFO : < 200 OK [3353]
2017-12-31 21:32:07,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 400}
2017-12-31 21:32:07,288 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,294 : INFO : < 200 OK [3352]
2017-12-31 21:32:07,299 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 400}
2017-12-31 21:32:07,303 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,309 : INFO : < 200 OK [3353]
2017-12-31 21:32:07,315 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 379}
2017-12-31 21:32:07,319 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,324 : INFO : < 200 OK [3274]
2017-12-31 21:32:07,330 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 379}
2017-12-31 21:32:07,334 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,340 : INFO : < 200 OK [3274]
2017-12-31 21:32:07,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 379}
2017-12-31 21:32:07,349 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,357 : INFO : < 200 OK [3274]
2017-12-31 21:32:07,365 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 366}
2017-12-31 21:32:07,368 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,375 : INFO : < 200 OK [3278]
2017-12-31 21:32:07,380 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 366}
2017-12-31 21:32:07,383 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,388 : INFO : < 200 OK [3277]
2017-12-31 21:32:07,394 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 366}
2017-12-31 21:32:07,397 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,403 : INFO : < 200 OK [3278]
2017-12-31 21:32:07,408 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 366}
2017-12-31 21:32:07,412 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,417 : INFO : < 200 OK [3277]
2017-12-31 21:32:07,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 366}
2017-12-31 21:32:07,426 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,432 : INFO : < 200 OK [3278]
2017-12-31 21:32:07,438 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 366}
2017-12-31 21:32:07,441 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,452 : INFO : < 200 OK [3277]
2017-12-31 21:32:07,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 465}
2017-12-31 21:32:07,462 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,472 : INFO : < 200 OK [3319]
2017-12-31 21:32:07,477 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 465}
2017-12-31 21:32:07,480 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,486 : INFO : < 200 OK [3320]
2017-12-31 21:32:07,491 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 465}
2017-12-31 21:32:07,494 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,500 : INFO : < 200 OK [3319]
2017-12-31 21:32:07,505 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 465}
2017-12-31 21:32:07,509 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,514 : INFO : < 200 OK [3320]
2017-12-31 21:32:07,520 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 451}
2017-12-31 21:32:07,524 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,529 : INFO : < 200 OK [3313]
2017-12-31 21:32:07,534 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 451}
2017-12-31 21:32:07,538 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,544 : INFO : < 200 OK [3327]
2017-12-31 21:32:07,549 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 466}
2017-12-31 21:32:07,552 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,558 : INFO : < 200 OK [3347]
2017-12-31 21:32:07,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 466}
2017-12-31 21:32:07,567 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,573 : INFO : < 200 OK [3346]
2017-12-31 21:32:07,578 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 466}
2017-12-31 21:32:07,581 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,587 : INFO : < 200 OK [3347]
2017-12-31 21:32:07,593 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 466}
2017-12-31 21:32:07,597 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,603 : INFO : < 200 OK [3347]
2017-12-31 21:32:07,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 466}
2017-12-31 21:32:07,612 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,617 : INFO : < 200 OK [3346]
2017-12-31 21:32:07,622 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 466}

2017-12-31 21:32:07,626 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,632 : INFO : < 200 OK [3347]
2017-12-31 21:32:07,638 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 466}
2017-12-31 21:32:07,641 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,648 : INFO : < 200 OK [3347]
2017-12-31 21:32:07,653 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 466}
2017-12-31 21:32:07,656 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,662 : INFO : < 200 OK [3346]
2017-12-31 21:32:07,667 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 466}
2017-12-31 21:32:07,671 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,677 : INFO : < 200 OK [3347]
2017-12-31 21:32:07,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 466}
2017-12-31 21:32:07,685 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,691 : INFO : < 200 OK [3347]
2017-12-31 21:32:07,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 466}
2017-12-31 21:32:07,700 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,706 : INFO : < 200 OK [3346]
2017-12-31 21:32:07,710 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 466}
2017-12-31 21:32:07,714 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,720 : INFO : < 200 OK [3347]
2017-12-31 21:32:07,727 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 473}
2017-12-31 21:32:07,731 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,738 : INFO : < 200 OK [3332]
2017-12-31 21:32:07,747 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 469}
2017-12-31 21:32:07,750 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,757 : INFO : < 200 OK [3310]
2017-12-31 21:32:07,762 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 469}
2017-12-31 21:32:07,766 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,772 : INFO : < 200 OK [3310]
2017-12-31 21:32:07,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 470}
2017-12-31 21:32:07,785 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,791 : INFO : < 200 OK [3305]
2017-12-31 21:32:07,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 470}
2017-12-31 21:32:07,799 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,805 : INFO : < 200 OK [3319]
2017-12-31 21:32:07,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 470}
2017-12-31 21:32:07,816 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,823 : INFO : < 200 OK [3305]
2017-12-31 21:32:07,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 470}
2017-12-31 21:32:07,832 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,838 : INFO : < 200 OK [3319]
2017-12-31 21:32:07,846 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 478}
2017-12-31 21:32:07,851 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,858 : INFO : < 200 OK [3306]
2017-12-31 21:32:07,863 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 478}
2017-12-31 21:32:07,866 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,872 : INFO : < 200 OK [3305]
2017-12-31 21:32:07,877 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 478}
2017-12-31 21:32:07,882 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,890 : INFO : < 200 OK [3306]
2017-12-31 21:32:07,895 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 478}
2017-12-31 21:32:07,906 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,912 : INFO : < 200 OK [3320]
2017-12-31 21:32:07,917 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 506}
2017-12-31 21:32:07,925 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,932 : INFO : < 200 OK [3308]
2017-12-31 21:32:07,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 506}
2017-12-31 21:32:07,942 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,948 : INFO : < 200 OK [3308]
2017-12-31 21:32:07,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 480}
2017-12-31 21:32:07,959 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,967 : INFO : < 200 OK [3289]
2017-12-31 21:32:07,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 403}
2017-12-31 21:32:07,978 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:07,984 : INFO : < 200 OK [3362]
2017-12-31 21:32:07,989 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 403}
2017-12-31 21:32:07,993 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,001 : INFO : < 200 OK [3361]
2017-12-31 21:32:08,008 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 403}
2017-12-31 21:32:08,012 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,017 : INFO : < 200 OK [3362]
2017-12-31 21:32:08,024 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 382}
2017-12-31 21:32:08,028 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,034 : INFO : < 200 OK [3364]

2017-12-31 21:32:08,038 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 509}
2017-12-31 21:32:08,041 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,047 : INFO : < 200 OK [3312]
2017-12-31 21:32:08,052 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 509}
2017-12-31 21:32:08,055 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,061 : INFO : < 200 OK [3326]
2017-12-31 21:32:08,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 509}
2017-12-31 21:32:08,068 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,073 : INFO : < 200 OK [3312]
2017-12-31 21:32:08,080 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 509}
2017-12-31 21:32:08,083 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,088 : INFO : < 200 OK [3326]
2017-12-31 21:32:08,094 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 510}
2017-12-31 21:32:08,097 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,103 : INFO : < 200 OK [3314]
2017-12-31 21:32:08,111 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 485}
2017-12-31 21:32:08,114 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,120 : INFO : < 200 OK [3348]
2017-12-31 21:32:08,125 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 419}
2017-12-31 21:32:08,129 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,134 : INFO : < 200 OK [3290]
2017-12-31 21:32:08,140 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 419}
2017-12-31 21:32:08,143 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,149 : INFO : < 200 OK [3290]
2017-12-31 21:32:08,154 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 404}
2017-12-31 21:32:08,158 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,164 : INFO : < 200 OK [3316]
2017-12-31 21:32:08,168 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 404}
2017-12-31 21:32:08,172 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,177 : INFO : < 200 OK [3314]
2017-12-31 21:32:08,182 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 404}
2017-12-31 21:32:08,186 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,191 : INFO : < 200 OK [3320]
2017-12-31 21:32:08,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 404}
2017-12-31 21:32:08,324 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,330 : INFO : < 200 OK [3313]
2017-12-31 21:32:08,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 404}
2017-12-31 21:32:08,338 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,344 : INFO : < 200 OK [3313]
2017-12-31 21:32:08,348 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 404}
2017-12-31 21:32:08,352 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,357 : INFO : < 200 OK [3314]
2017-12-31 21:32:08,362 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 404}
2017-12-31 21:32:08,366 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,371 : INFO : < 200 OK [3330]
2017-12-31 21:32:08,376 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 368}
2017-12-31 21:32:08,380 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,385 : INFO : < 200 OK [3275]
2017-12-31 21:32:08,391 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 368}
2017-12-31 21:32:08,394 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,399 : INFO : < 200 OK [3275]
2017-12-31 21:32:08,405 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 486}
2017-12-31 21:32:08,408 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,414 : INFO : < 200 OK [3310]
2017-12-31 21:32:08,419 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 486}
2017-12-31 21:32:08,423 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,428 : INFO : < 200 OK [3324]
2017-12-31 21:32:08,433 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 486}
2017-12-31 21:32:08,437 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,442 : INFO : < 200 OK [3310]
2017-12-31 21:32:08,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 486}
2017-12-31 21:32:08,450 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,456 : INFO : < 200 OK [3324]
2017-12-31 21:32:08,461 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 501}
2017-12-31 21:32:08,464 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,469 : INFO : < 200 OK [3303]
2017-12-31 21:32:08,473 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 281}
2017-12-31 21:32:08,477 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,482 : INFO : < 200 OK [3310]
2017-12-31 21:32:08,486 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 281}
2017-12-31 21:32:08,489 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,493 : INFO : < 200 OK [3327]
2017-12-31 21:32:08,498 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 281}

2017-12-31 21:32:08,502 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,507 : INFO : < 200 OK [3310]
2017-12-31 21:32:08,512 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 281}
2017-12-31 21:32:08,515 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,520 : INFO : < 200 OK [3327]
2017-12-31 21:32:08,526 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 172}
2017-12-31 21:32:08,529 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,534 : INFO : < 200 OK [3331]
2017-12-31 21:32:08,539 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 172}
2017-12-31 21:32:08,542 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,547 : INFO : < 200 OK [3348]
2017-12-31 21:32:08,552 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 172}
2017-12-31 21:32:08,556 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,561 : INFO : < 200 OK [3331]
2017-12-31 21:32:08,567 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 172}
2017-12-31 21:32:08,570 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,575 : INFO : < 200 OK [3348]
2017-12-31 21:32:08,581 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 516}
2017-12-31 21:32:08,584 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,591 : INFO : < 200 OK [3287]
2017-12-31 21:32:08,595 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 516}
2017-12-31 21:32:08,599 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,604 : INFO : < 200 OK [3301]
2017-12-31 21:32:08,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 516}
2017-12-31 21:32:08,612 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,617 : INFO : < 200 OK [3287]
2017-12-31 21:32:08,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 516}
2017-12-31 21:32:08,624 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,630 : INFO : < 200 OK [3301]
2017-12-31 21:32:08,635 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 503}
2017-12-31 21:32:08,638 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,643 : INFO : < 200 OK [3294]
2017-12-31 21:32:08,648 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 518}
2017-12-31 21:32:08,651 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,656 : INFO : < 200 OK [3321]
2017-12-31 21:32:08,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 504}
2017-12-31 21:32:08,665 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,669 : INFO : < 200 OK [3296]
2017-12-31 21:32:08,673 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 504}
2017-12-31 21:32:08,676 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,682 : INFO : < 200 OK [3313]
2017-12-31 21:32:08,688 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 520}
2017-12-31 21:32:08,691 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,696 : INFO : < 200 OK [3342]
2017-12-31 21:32:08,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 520}
2017-12-31 21:32:08,703 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,708 : INFO : < 200 OK [3341]
2017-12-31 21:32:08,713 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 520}
2017-12-31 21:32:08,716 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,721 : INFO : < 200 OK [3356]
2017-12-31 21:32:08,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 521}
2017-12-31 21:32:08,729 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,735 : INFO : < 200 OK [3319]
2017-12-31 21:32:08,740 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 521}
2017-12-31 21:32:08,743 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,749 : INFO : < 200 OK [3336]
2017-12-31 21:32:08,755 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 521}
2017-12-31 21:32:08,758 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,764 : INFO : < 200 OK [3319]
2017-12-31 21:32:08,768 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 521}
2017-12-31 21:32:08,772 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,778 : INFO : < 200 OK [3336]
2017-12-31 21:32:08,783 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 521}
2017-12-31 21:32:08,786 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,792 : INFO : < 200 OK [3319]
2017-12-31 21:32:08,797 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 521}
2017-12-31 21:32:08,801 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,806 : INFO : < 200 OK [3336]
2017-12-31 21:32:08,812 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 528}
2017-12-31 21:32:08,816 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,821 : INFO : < 200 OK [3320]
2017-12-31 21:32:08,825 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 528}
2017-12-31 21:32:08,829 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,834 : INFO : < 200 OK [3319]

2017-12-31 21:32:08,839 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 528}
2017-12-31 21:32:08,842 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,847 : INFO : < 200 OK [3320]
2017-12-31 21:32:08,852 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 528}
2017-12-31 21:32:08,856 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,861 : INFO : < 200 OK [3319]
2017-12-31 21:32:08,866 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 523}
2017-12-31 21:32:08,869 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,875 : INFO : < 200 OK [3275]
2017-12-31 21:32:08,880 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 523}
2017-12-31 21:32:08,883 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,889 : INFO : < 200 OK [3275]
2017-12-31 21:32:08,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 384}
2017-12-31 21:32:08,897 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,902 : INFO : < 200 OK [3287]
2017-12-31 21:32:08,906 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 384}
2017-12-31 21:32:08,909 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,914 : INFO : < 200 OK [3287]
2017-12-31 21:32:08,920 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 110}
2017-12-31 21:32:08,923 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,929 : INFO : < 200 OK [3285]
2017-12-31 21:32:08,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 110}
2017-12-31 21:32:08,938 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,943 : INFO : < 200 OK [3285]
2017-12-31 21:32:08,950 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 531}
2017-12-31 21:32:08,954 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,959 : INFO : < 200 OK [3305]
2017-12-31 21:32:08,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 531}
2017-12-31 21:32:08,969 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,974 : INFO : < 200 OK [3305]
2017-12-31 21:32:08,980 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 546}
2017-12-31 21:32:08,983 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:08,988 : INFO : < 200 OK [3300]
2017-12-31 21:32:08,993 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 546}
2017-12-31 21:32:08,997 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,002 : INFO : < 200 OK [3299]
2017-12-31 21:32:09,007 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 546}
2017-12-31 21:32:09,011 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,016 : INFO : < 200 OK [3300]
2017-12-31 21:32:09,021 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 546}
2017-12-31 21:32:09,024 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,030 : INFO : < 200 OK [3299]
2017-12-31 21:32:09,036 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 407}
2017-12-31 21:32:09,039 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,045 : INFO : < 200 OK [3276]
2017-12-31 21:32:09,049 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 407}
2017-12-31 21:32:09,052 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,057 : INFO : < 200 OK [3276]
2017-12-31 21:32:09,061 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 407}
2017-12-31 21:32:09,065 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,071 : INFO : < 200 OK [3276]
2017-12-31 21:32:09,076 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 549}
2017-12-31 21:32:09,079 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,084 : INFO : < 200 OK [3290]
2017-12-31 21:32:09,090 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 551}
2017-12-31 21:32:09,093 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,098 : INFO : < 200 OK [3318]
2017-12-31 21:32:09,103 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 551}
2017-12-31 21:32:09,107 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,113 : INFO : < 200 OK [3319]
2017-12-31 21:32:09,117 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 537}
2017-12-31 21:32:09,121 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,126 : INFO : < 200 OK [3278]
2017-12-31 21:32:09,132 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 538}
2017-12-31 21:32:09,135 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,140 : INFO : < 200 OK [3328]
2017-12-31 21:32:09,146 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 540}
2017-12-31 21:32:09,150 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,156 : INFO : < 200 OK [3302]
2017-12-31 21:32:09,160 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 540}
2017-12-31 21:32:09,164 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,169 : INFO : < 200 OK [3301]
2017-12-31 21:32:09,174 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 540}

2017-12-31 21:32:09,178 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,183 : INFO : < 200 OK [3302]
2017-12-31 21:32:09,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 540}
2017-12-31 21:32:09,192 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,198 : INFO : < 200 OK [3302]
2017-12-31 21:32:09,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 540}
2017-12-31 21:32:09,205 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,211 : INFO : < 200 OK [3301]
2017-12-31 21:32:09,215 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 540}
2017-12-31 21:32:09,219 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,225 : INFO : < 200 OK [3302]
2017-12-31 21:32:09,231 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 540}
2017-12-31 21:32:09,234 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,240 : INFO : < 200 OK [3302]
2017-12-31 21:32:09,244 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 540}
2017-12-31 21:32:09,248 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,253 : INFO : < 200 OK [3301]
2017-12-31 21:32:09,258 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 540}
2017-12-31 21:32:09,262 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,267 : INFO : < 200 OK [3302]
2017-12-31 21:32:09,273 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 540}
2017-12-31 21:32:09,276 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,282 : INFO : < 200 OK [3302]
2017-12-31 21:32:09,286 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 540}
2017-12-31 21:32:09,290 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,296 : INFO : < 200 OK [3301]
2017-12-31 21:32:09,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 540}
2017-12-31 21:32:09,304 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,312 : INFO : < 200 OK [3302]
2017-12-31 21:32:09,317 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 555}
2017-12-31 21:32:09,322 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,329 : INFO : < 200 OK [3289]
2017-12-31 21:32:09,337 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 542}
2017-12-31 21:32:09,341 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,347 : INFO : < 200 OK [3310]
2017-12-31 21:32:09,355 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 565}
2017-12-31 21:32:09,358 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,363 : INFO : < 200 OK [3275]
2017-12-31 21:32:09,369 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 565}
2017-12-31 21:32:09,372 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,378 : INFO : < 200 OK [3289]
2017-12-31 21:32:09,383 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 387}
2017-12-31 21:32:09,387 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,392 : INFO : < 200 OK [3279]
2017-12-31 21:32:09,397 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 387}
2017-12-31 21:32:09,401 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,406 : INFO : < 200 OK [3279]
2017-12-31 21:32:09,411 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 387}
2017-12-31 21:32:09,414 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,419 : INFO : < 200 OK [3279]
2017-12-31 21:32:09,423 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 387}
2017-12-31 21:32:09,426 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,431 : INFO : < 200 OK [3279]
2017-12-31 21:32:09,436 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 560}
2017-12-31 21:32:09,439 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,444 : INFO : < 200 OK [3321]
2017-12-31 21:32:09,449 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 560}
2017-12-31 21:32:09,453 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,458 : INFO : < 200 OK [3321]
2017-12-31 21:32:09,466 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 568}
2017-12-31 21:32:09,470 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,475 : INFO : < 200 OK [3282]
2017-12-31 21:32:09,481 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 568}
2017-12-31 21:32:09,484 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,489 : INFO : < 200 OK [3282]
2017-12-31 21:32:09,494 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 564}
2017-12-31 21:32:09,497 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,502 : INFO : < 200 OK [3295]
2017-12-31 21:32:09,508 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 564}
2017-12-31 21:32:09,511 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,517 : INFO : < 200 OK [3295]
2017-12-31 21:32:09,522 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 564}
2017-12-31 21:32:09,526 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,532 : INFO : < 200 OK [3295]

2017-12-31 21:32:09,538 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 570}
2017-12-31 21:32:09,541 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,547 : INFO : < 200 OK [3292]
2017-12-31 21:32:09,553 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 585}
2017-12-31 21:32:09,557 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,564 : INFO : < 200 OK [3282]
2017-12-31 21:32:09,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 585}
2017-12-31 21:32:09,575 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,581 : INFO : < 200 OK [3282]
2017-12-31 21:32:09,587 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 571}
2017-12-31 21:32:09,591 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,597 : INFO : < 200 OK [3297]
2017-12-31 21:32:09,602 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 571}
2017-12-31 21:32:09,606 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,612 : INFO : < 200 OK [3297]
2017-12-31 21:32:09,617 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 586}
2017-12-31 21:32:09,621 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,626 : INFO : < 200 OK [3283]
2017-12-31 21:32:09,632 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 572}
2017-12-31 21:32:09,636 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,643 : INFO : < 200 OK [3330]
2017-12-31 21:32:09,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 572}
2017-12-31 21:32:09,654 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,660 : INFO : < 200 OK [3330]
2017-12-31 21:32:09,666 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 140}
2017-12-31 21:32:09,669 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,675 : INFO : < 200 OK [3332]
2017-12-31 21:32:09,680 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 573}
2017-12-31 21:32:09,683 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,689 : INFO : < 200 OK [3311]
2017-12-31 21:32:09,694 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 588}
2017-12-31 21:32:09,697 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,703 : INFO : < 200 OK [3327]
2017-12-31 21:32:09,707 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 588}
2017-12-31 21:32:09,711 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,716 : INFO : < 200 OK [3333]
2017-12-31 21:32:09,721 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 588}
2017-12-31 21:32:09,726 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,732 : INFO : < 200 OK [3327]
2017-12-31 21:32:09,737 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 588}
2017-12-31 21:32:09,741 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,747 : INFO : < 200 OK [3327]
2017-12-31 21:32:09,752 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 588}
2017-12-31 21:32:09,755 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,761 : INFO : < 200 OK [3333]
2017-12-31 21:32:09,766 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 588}
2017-12-31 21:32:09,770 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,776 : INFO : < 200 OK [3327]
2017-12-31 21:32:09,781 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 81}
2017-12-31 21:32:09,785 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:09,791 : INFO : < 200 OK [3290]
2017-12-31 21:32:09,796 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 81}
2017-12-31 21:32:09,799 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:09,805 : INFO : < 200 OK [3290]
2017-12-31 21:32:09,811 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 433}
2017-12-31 21:32:09,815 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,821 : INFO : < 200 OK [3327]
2017-12-31 21:32:09,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 66}
2017-12-31 21:32:09,833 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:09,839 : INFO : < 200 OK [3307]
2017-12-31 21:32:09,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 66}
2017-12-31 21:32:09,848 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:09,854 : INFO : < 200 OK [3307]
2017-12-31 21:32:09,860 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 66}
2017-12-31 21:32:09,864 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:09,870 : INFO : < 200 OK [3307]
2017-12-31 21:32:09,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 66}
2017-12-31 21:32:09,879 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:09,885 : INFO : < 200 OK [3307]
2017-12-31 21:32:09,891 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 66}
2017-12-31 21:32:09,895 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:09,903 : INFO : < 200 OK [3307]
2017-12-31 21:32:09,908 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 428}

2017-12-31 21:32:09,912 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,918 : INFO : < 200 OK [3278]
2017-12-31 21:32:09,924 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 428}
2017-12-31 21:32:09,927 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,933 : INFO : < 200 OK [3276]
2017-12-31 21:32:09,938 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 428}
2017-12-31 21:32:09,942 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,949 : INFO : < 200 OK [3282]
2017-12-31 21:32:09,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 428}
2017-12-31 21:32:09,959 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,965 : INFO : < 200 OK [3275]
2017-12-31 21:32:09,971 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 428}
2017-12-31 21:32:09,975 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:09,981 : INFO : < 200 OK [3292]
2017-12-31 21:32:09,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 574}
2017-12-31 21:32:09,993 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,001 : INFO : < 200 OK [3321]
2017-12-31 21:32:10,007 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 574}
2017-12-31 21:32:10,010 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,017 : INFO : < 200 OK [3322]
2017-12-31 21:32:10,023 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 574}
2017-12-31 21:32:10,027 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,033 : INFO : < 200 OK [3321]
2017-12-31 21:32:10,039 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 574}
2017-12-31 21:32:10,043 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,049 : INFO : < 200 OK [3322]
2017-12-31 21:32:10,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 589}
2017-12-31 21:32:10,059 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,065 : INFO : < 200 OK [3284]
2017-12-31 21:32:10,070 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 589}
2017-12-31 21:32:10,073 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,080 : INFO : < 200 OK [3287]
2017-12-31 21:32:10,085 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 589}
2017-12-31 21:32:10,089 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,096 : INFO : < 200 OK [3285]
2017-12-31 21:32:10,101 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 589}
2017-12-31 21:32:10,105 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,111 : INFO : < 200 OK [3285]
2017-12-31 21:32:10,115 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 589}
2017-12-31 21:32:10,119 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,125 : INFO : < 200 OK [3291]
2017-12-31 21:32:10,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 575}
2017-12-31 21:32:10,134 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,141 : INFO : < 200 OK [3319]
2017-12-31 21:32:10,146 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 575}
2017-12-31 21:32:10,150 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,156 : INFO : < 200 OK [3317]
2017-12-31 21:32:10,162 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 575}
2017-12-31 21:32:10,165 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,171 : INFO : < 200 OK [3319]
2017-12-31 21:32:10,177 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1253, '_0n0': 575}
2017-12-31 21:32:10,181 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,187 : INFO : < 200 OK [3317]
2017-12-31 21:32:10,193 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 306}
2017-12-31 21:32:10,197 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,203 : INFO : < 200 OK [3308]
2017-12-31 21:32:10,208 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 306}
2017-12-31 21:32:10,211 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,218 : INFO : < 200 OK [3308]
2017-12-31 21:32:10,223 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 306}
2017-12-31 21:32:10,227 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,232 : INFO : < 200 OK [3311]
2017-12-31 21:32:10,238 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 306}
2017-12-31 21:32:10,242 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,248 : INFO : < 200 OK [3308]
2017-12-31 21:32:10,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 306}
2017-12-31 21:32:10,257 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,263 : INFO : < 200 OK [3308]
2017-12-31 21:32:10,267 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 306}
2017-12-31 21:32:10,271 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,278 : INFO : < 200 OK [3311]
2017-12-31 21:32:10,284 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 590}
2017-12-31 21:32:10,288 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,295 : INFO : < 200 OK [3322]

2017-12-31 21:32:10,300 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 590}
2017-12-31 21:32:10,304 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,311 : INFO : < 200 OK [3322]
2017-12-31 21:32:10,317 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 590}
2017-12-31 21:32:10,322 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,332 : INFO : < 200 OK [3322]
2017-12-31 21:32:10,339 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 431}
2017-12-31 21:32:10,345 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,351 : INFO : < 200 OK [3283]
2017-12-31 21:32:10,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 576}
2017-12-31 21:32:10,363 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,370 : INFO : < 200 OK [3327]
2017-12-31 21:32:10,378 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 83}
2017-12-31 21:32:10,383 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:10,390 : INFO : < 200 OK [3302]
2017-12-31 21:32:10,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 83}
2017-12-31 21:32:10,401 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:10,408 : INFO : < 200 OK [3302]
2017-12-31 21:32:10,414 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 83}
2017-12-31 21:32:10,419 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:10,427 : INFO : < 200 OK [3302]
2017-12-31 21:32:10,433 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 83}
2017-12-31 21:32:10,439 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:10,448 : INFO : < 200 OK [3302]
2017-12-31 21:32:10,457 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 591}
2017-12-31 21:32:10,461 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,470 : INFO : < 200 OK [3328]
2017-12-31 21:32:10,479 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 591}
2017-12-31 21:32:10,486 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,495 : INFO : < 200 OK [3331]
2017-12-31 21:32:10,504 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 591}
2017-12-31 21:32:10,508 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,515 : INFO : < 200 OK [3329]
2017-12-31 21:32:10,521 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 591}
2017-12-31 21:32:10,527 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,536 : INFO : < 200 OK [3335]
2017-12-31 21:32:10,542 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 591}
2017-12-31 21:32:10,546 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,554 : INFO : < 200 OK [3330]
2017-12-31 21:32:10,561 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 591}
2017-12-31 21:32:10,565 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,572 : INFO : < 200 OK [3329]
2017-12-31 21:32:10,579 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 591}
2017-12-31 21:32:10,586 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,596 : INFO : < 200 OK [3345]
2017-12-31 21:32:10,603 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 452}
2017-12-31 21:32:10,608 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,615 : INFO : < 200 OK [3316]
2017-12-31 21:32:10,621 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 452}
2017-12-31 21:32:10,625 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,633 : INFO : < 200 OK [3315]
2017-12-31 21:32:10,640 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 452}
2017-12-31 21:32:10,645 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,653 : INFO : < 200 OK [3332]
2017-12-31 21:32:10,659 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 452}
2017-12-31 21:32:10,663 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,670 : INFO : < 200 OK [3316]
2017-12-31 21:32:10,677 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 452}
2017-12-31 21:32:10,682 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,690 : INFO : < 200 OK [3315]
2017-12-31 21:32:10,696 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 452}
2017-12-31 21:32:10,700 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,707 : INFO : < 200 OK [3332]
2017-12-31 21:32:10,713 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 68}
2017-12-31 21:32:10,718 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:10,724 : INFO : < 200 OK [3291]
2017-12-31 21:32:10,730 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 68}
2017-12-31 21:32:10,734 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:10,741 : INFO : < 200 OK [3290]
2017-12-31 21:32:10,748 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 68}
2017-12-31 21:32:10,752 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:10,759 : INFO : < 200 OK [3291]
2017-12-31 21:32:10,766 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 68}

2017-12-31 21:32:10,771 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:10,777 : INFO : < 200 OK [3290]
2017-12-31 21:32:10,784 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 577}
2017-12-31 21:32:10,788 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,794 : INFO : < 200 OK [3282]
2017-12-31 21:32:10,800 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 577}
2017-12-31 21:32:10,805 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,812 : INFO : < 200 OK [3282]
2017-12-31 21:32:10,822 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 592}
2017-12-31 21:32:10,826 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,833 : INFO : < 200 OK [3331]
2017-12-31 21:32:10,840 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 592}
2017-12-31 21:32:10,845 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,852 : INFO : < 200 OK [3331]
2017-12-31 21:32:10,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 592}
2017-12-31 21:32:10,862 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,868 : INFO : < 200 OK [3337]
2017-12-31 21:32:10,875 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 592}
2017-12-31 21:32:10,880 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,887 : INFO : < 200 OK [3347]
2017-12-31 21:32:10,894 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 592}
2017-12-31 21:32:10,901 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,910 : INFO : < 200 OK [3331]
2017-12-31 21:32:10,917 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 592}
2017-12-31 21:32:10,923 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,930 : INFO : < 200 OK [3331]
2017-12-31 21:32:10,936 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 592}
2017-12-31 21:32:10,940 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,946 : INFO : < 200 OK [3337]
2017-12-31 21:32:10,952 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 592}
2017-12-31 21:32:10,957 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,964 : INFO : < 200 OK [3347]
2017-12-31 21:32:10,970 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 592}
2017-12-31 21:32:10,976 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,982 : INFO : < 200 OK [3331]
2017-12-31 21:32:10,988 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 592}
2017-12-31 21:32:10,992 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:10,999 : INFO : < 200 OK [3331]
2017-12-31 21:32:11,004 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 592}
2017-12-31 21:32:11,008 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,014 : INFO : < 200 OK [3337]
2017-12-31 21:32:11,022 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 592}
2017-12-31 21:32:11,025 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,032 : INFO : < 200 OK [3347]
2017-12-31 21:32:11,037 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 592}
2017-12-31 21:32:11,042 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,049 : INFO : < 200 OK [3331]
2017-12-31 21:32:11,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 592}
2017-12-31 21:32:11,060 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,066 : INFO : < 200 OK [3331]
2017-12-31 21:32:11,072 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 592}
2017-12-31 21:32:11,076 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,081 : INFO : < 200 OK [3337]
2017-12-31 21:32:11,087 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 592}
2017-12-31 21:32:11,092 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,099 : INFO : < 200 OK [3347]
2017-12-31 21:32:11,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 439}
2017-12-31 21:32:11,110 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,116 : INFO : < 200 OK [3318]
2017-12-31 21:32:11,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 454}
2017-12-31 21:32:11,126 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,134 : INFO : < 200 OK [3314]
2017-12-31 21:32:11,140 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 454}
2017-12-31 21:32:11,144 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,149 : INFO : < 200 OK [3328]
2017-12-31 21:32:11,155 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 454}
2017-12-31 21:32:11,160 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,166 : INFO : < 200 OK [3314]
2017-12-31 21:32:11,172 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 454}
2017-12-31 21:32:11,176 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,184 : INFO : < 200 OK [3328]
2017-12-31 21:32:11,190 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 578}
2017-12-31 21:32:11,194 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,202 : INFO : < 200 OK [3340]

2017-12-31 21:32:11,208 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 578}
2017-12-31 21:32:11,212 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,219 : INFO : < 200 OK [3340]
2017-12-31 21:32:11,225 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 456}
2017-12-31 21:32:11,230 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,236 : INFO : < 200 OK [3339]
2017-12-31 21:32:11,243 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 456}
2017-12-31 21:32:11,247 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,255 : INFO : < 200 OK [3338]
2017-12-31 21:32:11,261 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 456}
2017-12-31 21:32:11,265 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,272 : INFO : < 200 OK [3339]
2017-12-31 21:32:11,277 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 456}
2017-12-31 21:32:11,281 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,287 : INFO : < 200 OK [3339]
2017-12-31 21:32:11,294 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 456}
2017-12-31 21:32:11,299 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,306 : INFO : < 200 OK [3338]
2017-12-31 21:32:11,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 456}
2017-12-31 21:32:11,319 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,328 : INFO : < 200 OK [3339]
2017-12-31 21:32:11,333 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 456}
2017-12-31 21:32:11,337 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,344 : INFO : < 200 OK [3339]
2017-12-31 21:32:11,350 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 456}
2017-12-31 21:32:11,355 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,363 : INFO : < 200 OK [3338]
2017-12-31 21:32:11,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 456}
2017-12-31 21:32:11,372 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,379 : INFO : < 200 OK [3339]
2017-12-31 21:32:11,385 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 456}
2017-12-31 21:32:11,389 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,395 : INFO : < 200 OK [3339]
2017-12-31 21:32:11,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 456}
2017-12-31 21:32:11,407 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,415 : INFO : < 200 OK [3338]
2017-12-31 21:32:11,421 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 456}
2017-12-31 21:32:11,425 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,433 : INFO : < 200 OK [3339]
2017-12-31 21:32:11,440 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 457}
2017-12-31 21:32:11,445 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,452 : INFO : < 200 OK [3322]
2017-12-31 21:32:11,459 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 308}
2017-12-31 21:32:11,465 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,472 : INFO : < 200 OK [3316]
2017-12-31 21:32:11,478 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 308}
2017-12-31 21:32:11,483 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,490 : INFO : < 200 OK [3315]
2017-12-31 21:32:11,496 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 308}
2017-12-31 21:32:11,501 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,508 : INFO : < 200 OK [3316]
2017-12-31 21:32:11,513 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 308}
2017-12-31 21:32:11,517 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,523 : INFO : < 200 OK [3332]
2017-12-31 21:32:11,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 309}
2017-12-31 21:32:11,534 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,540 : INFO : < 200 OK [3327]
2017-12-31 21:32:11,545 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 309}
2017-12-31 21:32:11,549 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,557 : INFO : < 200 OK [3327]
2017-12-31 21:32:11,563 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 309}
2017-12-31 21:32:11,567 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,576 : INFO : < 200 OK [3333]
2017-12-31 21:32:11,582 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 593}
2017-12-31 21:32:11,588 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,595 : INFO : < 200 OK [3301]
2017-12-31 21:32:11,601 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 593}
2017-12-31 21:32:11,606 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,612 : INFO : < 200 OK [3315]
2017-12-31 21:32:11,619 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 593}
2017-12-31 21:32:11,623 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,629 : INFO : < 200 OK [3301]
2017-12-31 21:32:11,634 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 593}

2017-12-31 21:32:11,638 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,644 : INFO : < 200 OK [3315]
2017-12-31 21:32:11,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 146}
2017-12-31 21:32:11,653 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,658 : INFO : < 200 OK [3312]
2017-12-31 21:32:11,663 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 146}
2017-12-31 21:32:11,667 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,673 : INFO : < 200 OK [3315]
2017-12-31 21:32:11,678 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 146}
2017-12-31 21:32:11,682 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,688 : INFO : < 200 OK [3312]
2017-12-31 21:32:11,694 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 310}
2017-12-31 21:32:11,698 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,704 : INFO : < 200 OK [3343]
2017-12-31 21:32:11,711 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 310}
2017-12-31 21:32:11,714 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,721 : INFO : < 200 OK [3343]
2017-12-31 21:32:11,726 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 310}
2017-12-31 21:32:11,729 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,736 : INFO : < 200 OK [3349]
2017-12-31 21:32:11,741 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 460}
2017-12-31 21:32:11,745 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,753 : INFO : < 200 OK [3330]
2017-12-31 21:32:11,759 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 594}
2017-12-31 21:32:11,763 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,769 : INFO : < 200 OK [3287]
2017-12-31 21:32:11,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 594}
2017-12-31 21:32:11,779 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,786 : INFO : < 200 OK [3288]
2017-12-31 21:32:11,792 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 594}
2017-12-31 21:32:11,796 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,804 : INFO : < 200 OK [3287]
2017-12-31 21:32:11,810 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 594}
2017-12-31 21:32:11,814 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,822 : INFO : < 200 OK [3291]
2017-12-31 21:32:11,828 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 594}
2017-12-31 21:32:11,832 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,840 : INFO : < 200 OK [3304]
2017-12-31 21:32:11,846 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 580}
2017-12-31 21:32:11,850 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,858 : INFO : < 200 OK [3335]
2017-12-31 21:32:11,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 580}
2017-12-31 21:32:11,868 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,876 : INFO : < 200 OK [3338]
2017-12-31 21:32:11,881 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 580}
2017-12-31 21:32:11,886 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,892 : INFO : < 200 OK [3335]
2017-12-31 21:32:11,899 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 398}
2017-12-31 21:32:11,903 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,911 : INFO : < 200 OK [3317]
2017-12-31 21:32:11,917 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 398}
2017-12-31 21:32:11,922 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,929 : INFO : < 200 OK [3317]
2017-12-31 21:32:11,936 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 398}
2017-12-31 21:32:11,940 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,948 : INFO : < 200 OK [3317]
2017-12-31 21:32:11,955 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 398}
2017-12-31 21:32:11,959 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,965 : INFO : < 200 OK [3317]
2017-12-31 21:32:11,974 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 595}
2017-12-31 21:32:11,978 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:11,984 : INFO : < 200 OK [3309]
2017-12-31 21:32:11,991 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 595}
2017-12-31 21:32:11,995 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,001 : INFO : < 200 OK [3312]
2017-12-31 21:32:12,007 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 595}
2017-12-31 21:32:12,011 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,018 : INFO : < 200 OK [3325]
2017-12-31 21:32:12,025 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 155}
2017-12-31 21:32:12,029 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,036 : INFO : < 200 OK [3312]
2017-12-31 21:32:12,042 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 155}
2017-12-31 21:32:12,045 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,051 : INFO : < 200 OK [3312]

2017-12-31 21:32:12,057 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 155}
2017-12-31 21:32:12,061 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,067 : INFO : < 200 OK [3312]
2017-12-31 21:32:12,073 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 208}
2017-12-31 21:32:12,077 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,087 : INFO : < 200 OK [3356]
2017-12-31 21:32:12,093 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 413}
2017-12-31 21:32:12,098 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,106 : INFO : < 200 OK [3336]
2017-12-31 21:32:12,112 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 413}
2017-12-31 21:32:12,116 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,124 : INFO : < 200 OK [3334]
2017-12-31 21:32:12,129 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 413}
2017-12-31 21:32:12,133 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,140 : INFO : < 200 OK [3340]
2017-12-31 21:32:12,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 413}
2017-12-31 21:32:12,149 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,155 : INFO : < 200 OK [3350]
2017-12-31 21:32:12,160 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 413}
2017-12-31 21:32:12,164 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,170 : INFO : < 200 OK [3336]
2017-12-31 21:32:12,175 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 413}
2017-12-31 21:32:12,180 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,188 : INFO : < 200 OK [3334]
2017-12-31 21:32:12,195 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 413}
2017-12-31 21:32:12,199 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,206 : INFO : < 200 OK [3340]
2017-12-31 21:32:12,213 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 413}
2017-12-31 21:32:12,216 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,223 : INFO : < 200 OK [3350]
2017-12-31 21:32:12,233 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 317}
2017-12-31 21:32:12,237 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,243 : INFO : < 200 OK [3322]
2017-12-31 21:32:12,248 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 317}
2017-12-31 21:32:12,254 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,260 : INFO : < 200 OK [3325]
2017-12-31 21:32:12,268 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 332}
2017-12-31 21:32:12,273 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,280 : INFO : < 200 OK [3302]
2017-12-31 21:32:12,286 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 332}
2017-12-31 21:32:12,290 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,298 : INFO : < 200 OK [3305]
2017-12-31 21:32:12,305 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 90}
2017-12-31 21:32:12,308 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:12,315 : INFO : < 200 OK [3280]
2017-12-31 21:32:12,320 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 90}
2017-12-31 21:32:12,324 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:12,330 : INFO : < 200 OK [3280]
2017-12-31 21:32:12,336 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 90}
2017-12-31 21:32:12,341 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:12,348 : INFO : < 200 OK [3280]
2017-12-31 21:32:12,358 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 214}
2017-12-31 21:32:12,362 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,368 : INFO : < 200 OK [3291]
2017-12-31 21:32:12,374 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 214}
2017-12-31 21:32:12,379 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,384 : INFO : < 200 OK [3308]
2017-12-31 21:32:12,392 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 596}
2017-12-31 21:32:12,396 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,402 : INFO : < 200 OK [3314]
2017-12-31 21:32:12,409 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 596}
2017-12-31 21:32:12,413 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,420 : INFO : < 200 OK [3315]
2017-12-31 21:32:12,425 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 596}
2017-12-31 21:32:12,430 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,437 : INFO : < 200 OK [3331]
2017-12-31 21:32:12,443 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 582}
2017-12-31 21:32:12,448 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,455 : INFO : < 200 OK [3325]
2017-12-31 21:32:12,460 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 582}
2017-12-31 21:32:12,464 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,469 : INFO : < 200 OK [3339]
2017-12-31 21:32:12,475 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 451}

2017-12-31 21:32:12,480 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,487 : INFO : < 200 OK [3313]
2017-12-31 21:32:12,493 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 451}
2017-12-31 21:32:12,497 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,505 : INFO : < 200 OK [3327]
2017-12-31 21:32:12,511 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 466}
2017-12-31 21:32:12,515 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,523 : INFO : < 200 OK [3347]
2017-12-31 21:32:12,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 466}
2017-12-31 21:32:12,534 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,541 : INFO : < 200 OK [3346]
2017-12-31 21:32:12,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 466}
2017-12-31 21:32:12,551 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,557 : INFO : < 200 OK [3347]
2017-12-31 21:32:12,565 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 466}
2017-12-31 21:32:12,570 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,577 : INFO : < 200 OK [3347]
2017-12-31 21:32:12,582 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 466}
2017-12-31 21:32:12,588 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,593 : INFO : < 200 OK [3346]
2017-12-31 21:32:12,598 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 466}
2017-12-31 21:32:12,603 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,609 : INFO : < 200 OK [3347]
2017-12-31 21:32:12,615 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 466}
2017-12-31 21:32:12,618 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,624 : INFO : < 200 OK [3347]
2017-12-31 21:32:12,630 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 466}
2017-12-31 21:32:12,636 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,642 : INFO : < 200 OK [3346]
2017-12-31 21:32:12,649 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 466}
2017-12-31 21:32:12,653 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,659 : INFO : < 200 OK [3347]
2017-12-31 21:32:12,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 466}
2017-12-31 21:32:12,670 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,676 : INFO : < 200 OK [3347]
2017-12-31 21:32:12,682 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 466}
2017-12-31 21:32:12,686 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,692 : INFO : < 200 OK [3346]
2017-12-31 21:32:12,698 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 466}
2017-12-31 21:32:12,703 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,709 : INFO : < 200 OK [3347]
2017-12-31 21:32:12,716 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 597}
2017-12-31 21:32:12,721 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,727 : INFO : < 200 OK [3335]
2017-12-31 21:32:12,738 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 597}
2017-12-31 21:32:12,743 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,750 : INFO : < 200 OK [3335]
2017-12-31 21:32:12,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 597}
2017-12-31 21:32:12,759 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,765 : INFO : < 200 OK [3341]
2017-12-31 21:32:12,770 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 597}
2017-12-31 21:32:12,773 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,779 : INFO : < 200 OK [3351]
2017-12-31 21:32:12,786 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 597}
2017-12-31 21:32:12,790 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,796 : INFO : < 200 OK [3335]
2017-12-31 21:32:12,802 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 597}
2017-12-31 21:32:12,806 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,814 : INFO : < 200 OK [3335]
2017-12-31 21:32:12,821 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 597}
2017-12-31 21:32:12,824 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,830 : INFO : < 200 OK [3341]
2017-12-31 21:32:12,836 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 597}
2017-12-31 21:32:12,840 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,846 : INFO : < 200 OK [3351]
2017-12-31 21:32:12,851 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 597}
2017-12-31 21:32:12,854 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,861 : INFO : < 200 OK [3335]
2017-12-31 21:32:12,867 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 597}
2017-12-31 21:32:12,872 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,878 : INFO : < 200 OK [3335]
2017-12-31 21:32:12,884 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 597}
2017-12-31 21:32:12,889 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,896 : INFO : < 200 OK [3341]

2017-12-31 21:32:12,903 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 597}
2017-12-31 21:32:12,906 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,913 : INFO : < 200 OK [3351]
2017-12-31 21:32:12,918 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 597}
2017-12-31 21:32:12,923 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,929 : INFO : < 200 OK [3335]
2017-12-31 21:32:12,934 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 597}
2017-12-31 21:32:12,938 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,945 : INFO : < 200 OK [3335]
2017-12-31 21:32:12,951 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 597}
2017-12-31 21:32:12,954 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,962 : INFO : < 200 OK [3341]
2017-12-31 21:32:12,967 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 597}
2017-12-31 21:32:12,973 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,978 : INFO : < 200 OK [3351]
2017-12-31 21:32:12,984 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 583}
2017-12-31 21:32:12,989 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:12,994 : INFO : < 200 OK [3325]
2017-12-31 21:32:13,001 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 99}
2017-12-31 21:32:13,006 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:13,011 : INFO : < 200 OK [3303]
2017-12-31 21:32:13,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 99}
2017-12-31 21:32:13,019 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:13,025 : INFO : < 200 OK [3317]
2017-12-31 21:32:13,031 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 99}
2017-12-31 21:32:13,035 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:13,041 : INFO : < 200 OK [3303]
2017-12-31 21:32:13,047 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 99}
2017-12-31 21:32:13,051 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:13,057 : INFO : < 200 OK [3317]
2017-12-31 21:32:13,063 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 99}
2017-12-31 21:32:13,066 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:13,072 : INFO : < 200 OK [3303]
2017-12-31 21:32:13,077 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 99}
2017-12-31 21:32:13,081 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:13,086 : INFO : < 200 OK [3317]
2017-12-31 21:32:13,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 100}
2017-12-31 21:32:13,095 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,101 : INFO : < 200 OK [3333]
2017-12-31 21:32:13,107 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 100}
2017-12-31 21:32:13,110 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,117 : INFO : < 200 OK [3333]
2017-12-31 21:32:13,122 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 100}
2017-12-31 21:32:13,125 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,131 : INFO : < 200 OK [3333]
2017-12-31 21:32:13,136 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 100}
2017-12-31 21:32:13,140 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,145 : INFO : < 200 OK [3333]
2017-12-31 21:32:13,151 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 598}
2017-12-31 21:32:13,155 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,160 : INFO : < 200 OK [3295]
2017-12-31 21:32:13,166 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 598}
2017-12-31 21:32:13,169 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,175 : INFO : < 200 OK [3295]
2017-12-31 21:32:13,181 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 584}
2017-12-31 21:32:13,184 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,190 : INFO : < 200 OK [3320]
2017-12-31 21:32:13,196 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 584}
2017-12-31 21:32:13,200 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,206 : INFO : < 200 OK [3323]
2017-12-31 21:32:13,214 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 584}
2017-12-31 21:32:13,217 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,225 : INFO : < 200 OK [3321]
2017-12-31 21:32:13,230 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 584}
2017-12-31 21:32:13,234 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,241 : INFO : < 200 OK [3327]
2017-12-31 21:32:13,247 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 584}
2017-12-31 21:32:13,253 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,258 : INFO : < 200 OK [3321]
2017-12-31 21:32:13,264 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 599}
2017-12-31 21:32:13,267 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,273 : INFO : < 200 OK [3332]
2017-12-31 21:32:13,279 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 599}

2017-12-31 21:32:13,284 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,290 : INFO : < 200 OK [3335]
2017-12-31 21:32:13,296 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 599}
2017-12-31 21:32:13,299 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,306 : INFO : < 200 OK [3332]
2017-12-31 21:32:13,312 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 599}
2017-12-31 21:32:13,315 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,323 : INFO : < 200 OK [3335]
2017-12-31 21:32:13,329 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 320}
2017-12-31 21:32:13,333 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,342 : INFO : < 200 OK [3316]
2017-12-31 21:32:13,347 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 320}
2017-12-31 21:32:13,351 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,358 : INFO : < 200 OK [3316]
2017-12-31 21:32:13,364 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 320}
2017-12-31 21:32:13,367 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,375 : INFO : < 200 OK [3322]
2017-12-31 21:32:13,381 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 320}
2017-12-31 21:32:13,384 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,392 : INFO : < 200 OK [3319]
2017-12-31 21:32:13,397 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 469}
2017-12-31 21:32:13,400 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,407 : INFO : < 200 OK [3310]
2017-12-31 21:32:13,414 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 469}
2017-12-31 21:32:13,418 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,424 : INFO : < 200 OK [3310]
2017-12-31 21:32:13,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 470}
2017-12-31 21:32:13,434 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,440 : INFO : < 200 OK [3305]
2017-12-31 21:32:13,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 470}
2017-12-31 21:32:13,450 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,456 : INFO : < 200 OK [3319]
2017-12-31 21:32:13,463 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 470}
2017-12-31 21:32:13,468 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,475 : INFO : < 200 OK [3305]
2017-12-31 21:32:13,480 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 470}
2017-12-31 21:32:13,484 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,489 : INFO : < 200 OK [3319]
2017-12-31 21:32:13,495 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 605}
2017-12-31 21:32:13,498 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,504 : INFO : < 200 OK [3293]
2017-12-31 21:32:13,509 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 605}
2017-12-31 21:32:13,513 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,520 : INFO : < 200 OK [3299]
2017-12-31 21:32:13,527 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 605}
2017-12-31 21:32:13,531 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,538 : INFO : < 200 OK [3293]
2017-12-31 21:32:13,543 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 605}
2017-12-31 21:32:13,547 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,553 : INFO : < 200 OK [3299]
2017-12-31 21:32:13,559 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 605}
2017-12-31 21:32:13,563 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,569 : INFO : < 200 OK [3293]
2017-12-31 21:32:13,574 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 605}
2017-12-31 21:32:13,577 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,583 : INFO : < 200 OK [3299]
2017-12-31 21:32:13,589 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 605}
2017-12-31 21:32:13,592 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,599 : INFO : < 200 OK [3293]
2017-12-31 21:32:13,608 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 605}
2017-12-31 21:32:13,613 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,619 : INFO : < 200 OK [3299]
2017-12-31 21:32:13,625 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 600}
2017-12-31 21:32:13,629 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,636 : INFO : < 200 OK [3306]
2017-12-31 21:32:13,641 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 600}
2017-12-31 21:32:13,645 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,651 : INFO : < 200 OK [3309]
2017-12-31 21:32:13,656 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 600}
2017-12-31 21:32:13,660 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,672 : INFO : < 200 OK [3307]
2017-12-31 21:32:13,679 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 600}
2017-12-31 21:32:13,683 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,694 : INFO : < 200 OK [3313]

2017-12-31 21:32:13,700 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 600}
2017-12-31 21:32:13,705 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,711 : INFO : < 200 OK [3307]
2017-12-31 21:32:13,717 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 600}
2017-12-31 21:32:13,722 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,728 : INFO : < 200 OK [3306]
2017-12-31 21:32:13,733 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 600}
2017-12-31 21:32:13,738 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,747 : INFO : < 200 OK [3309]
2017-12-31 21:32:13,753 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 600}
2017-12-31 21:32:13,758 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,765 : INFO : < 200 OK [3307]
2017-12-31 21:32:13,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 600}
2017-12-31 21:32:13,778 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,785 : INFO : < 200 OK [3313]
2017-12-31 21:32:13,792 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 600}
2017-12-31 21:32:13,797 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,804 : INFO : < 200 OK [3307]
2017-12-31 21:32:13,810 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 416}
2017-12-31 21:32:13,814 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,820 : INFO : < 200 OK [3357]
2017-12-31 21:32:13,827 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 416}
2017-12-31 21:32:13,831 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,839 : INFO : < 200 OK [3371]
2017-12-31 21:32:13,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 335}
2017-12-31 21:32:13,849 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,858 : INFO : < 200 OK [3308]
2017-12-31 21:32:13,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 335}
2017-12-31 21:32:13,868 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,874 : INFO : < 200 OK [3311]
2017-12-31 21:32:13,881 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 606}
2017-12-31 21:32:13,887 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,894 : INFO : < 200 OK [3330]
2017-12-31 21:32:13,900 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 606}
2017-12-31 21:32:13,905 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,911 : INFO : < 200 OK [3330]
2017-12-31 21:32:13,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 606}
2017-12-31 21:32:13,920 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,927 : INFO : < 200 OK [3336]
2017-12-31 21:32:13,932 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 606}
2017-12-31 21:32:13,937 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,944 : INFO : < 200 OK [3346]
2017-12-31 21:32:13,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 606}
2017-12-31 21:32:13,954 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,960 : INFO : < 200 OK [3330]
2017-12-31 21:32:13,965 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 606}
2017-12-31 21:32:13,969 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,977 : INFO : < 200 OK [3330]
2017-12-31 21:32:13,982 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 606}
2017-12-31 21:32:13,988 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:13,994 : INFO : < 200 OK [3336]
2017-12-31 21:32:13,999 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 606}
2017-12-31 21:32:14,005 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,011 : INFO : < 200 OK [3346]
2017-12-31 21:32:14,016 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 606}
2017-12-31 21:32:14,021 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,027 : INFO : < 200 OK [3330]
2017-12-31 21:32:14,033 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 606}
2017-12-31 21:32:14,039 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,048 : INFO : < 200 OK [3330]
2017-12-31 21:32:14,054 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 606}
2017-12-31 21:32:14,058 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,065 : INFO : < 200 OK [3336]
2017-12-31 21:32:14,071 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 606}
2017-12-31 21:32:14,075 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,082 : INFO : < 200 OK [3346]
2017-12-31 21:32:14,088 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 606}
2017-12-31 21:32:14,093 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,099 : INFO : < 200 OK [3330]
2017-12-31 21:32:14,106 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 606}
2017-12-31 21:32:14,109 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,116 : INFO : < 200 OK [3330]
2017-12-31 21:32:14,121 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 606}

2017-12-31 21:32:14,125 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,131 : INFO : < 200 OK [3336]
2017-12-31 21:32:14,138 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 606}
2017-12-31 21:32:14,142 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,148 : INFO : < 200 OK [3346]
2017-12-31 21:32:14,154 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 117}
2017-12-31 21:32:14,158 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,165 : INFO : < 200 OK [3316]
2017-12-31 21:32:14,173 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 12}
2017-12-31 21:32:14,177 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:14,183 : INFO : < 200 OK [3343]
2017-12-31 21:32:14,191 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 12}
2017-12-31 21:32:14,195 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:14,200 : INFO : < 200 OK [3343]
2017-12-31 21:32:14,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 478}
2017-12-31 21:32:14,210 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,216 : INFO : < 200 OK [3306]
2017-12-31 21:32:14,222 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 478}
2017-12-31 21:32:14,226 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,233 : INFO : < 200 OK [3305]
2017-12-31 21:32:14,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 478}
2017-12-31 21:32:14,244 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,250 : INFO : < 200 OK [3306]
2017-12-31 21:32:14,257 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 478}
2017-12-31 21:32:14,261 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,267 : INFO : < 200 OK [3320]
2017-12-31 21:32:14,274 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 506}
2017-12-31 21:32:14,278 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,284 : INFO : < 200 OK [3308]
2017-12-31 21:32:14,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 506}
2017-12-31 21:32:14,296 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,304 : INFO : < 200 OK [3308]
2017-12-31 21:32:14,310 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 103}
2017-12-31 21:32:14,314 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,322 : INFO : < 200 OK [3346]
2017-12-31 21:32:14,327 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 103}
2017-12-31 21:32:14,331 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,339 : INFO : < 200 OK [3346]
2017-12-31 21:32:14,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 103}
2017-12-31 21:32:14,349 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,356 : INFO : < 200 OK [3346]
2017-12-31 21:32:14,362 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 103}
2017-12-31 21:32:14,365 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,373 : INFO : < 200 OK [3346]
2017-12-31 21:32:14,379 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 601}
2017-12-31 21:32:14,383 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,391 : INFO : < 200 OK [3317]
2017-12-31 21:32:14,396 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 601}
2017-12-31 21:32:14,400 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,408 : INFO : < 200 OK [3318]
2017-12-31 21:32:14,413 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 601}
2017-12-31 21:32:14,417 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,424 : INFO : < 200 OK [3319]
2017-12-31 21:32:14,430 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 601}
2017-12-31 21:32:14,433 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,441 : INFO : < 200 OK [3320]
2017-12-31 21:32:14,447 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 336}
2017-12-31 21:32:14,452 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,459 : INFO : < 200 OK [3331]
2017-12-31 21:32:14,465 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 336}
2017-12-31 21:32:14,470 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,477 : INFO : < 200 OK [3331]
2017-12-31 21:32:14,482 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 336}
2017-12-31 21:32:14,487 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,493 : INFO : < 200 OK [3337]
2017-12-31 21:32:14,500 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 336}
2017-12-31 21:32:14,505 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,511 : INFO : < 200 OK [3334]
2017-12-31 21:32:14,518 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 168}
2017-12-31 21:32:14,523 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,529 : INFO : < 200 OK [3318]
2017-12-31 21:32:14,536 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 322}
2017-12-31 21:32:14,540 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,547 : INFO : < 200 OK [3327]

2017-12-31 21:32:14,553 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:14,557 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,564 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,571 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:14,576 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,583 : INFO : < 200 OK [3332]
2017-12-31 21:32:14,591 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}
2017-12-31 21:32:14,595 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,602 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,609 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:14,613 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,620 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,626 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:14,630 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,637 : INFO : < 200 OK [3332]
2017-12-31 21:32:14,643 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}
2017-12-31 21:32:14,646 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,654 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,661 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:14,667 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,678 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,683 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:14,689 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,696 : INFO : < 200 OK [3332]
2017-12-31 21:32:14,702 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}
2017-12-31 21:32:14,707 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,713 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,721 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:14,725 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,731 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,738 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:14,743 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,748 : INFO : < 200 OK [3332]
2017-12-31 21:32:14,756 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}
2017-12-31 21:32:14,761 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,768 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,776 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:14,779 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,786 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,792 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:14,796 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,802 : INFO : < 200 OK [3332]
2017-12-31 21:32:14,809 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}
2017-12-31 21:32:14,813 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,820 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,826 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 418}
2017-12-31 21:32:14,830 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,838 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,844 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 418}
2017-12-31 21:32:14,848 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,858 : INFO : < 200 OK [3332]
2017-12-31 21:32:14,864 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 418}
2017-12-31 21:32:14,868 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,876 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,881 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 509}
2017-12-31 21:32:14,888 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,894 : INFO : < 200 OK [3312]
2017-12-31 21:32:14,899 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 509}
2017-12-31 21:32:14,905 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,911 : INFO : < 200 OK [3326]
2017-12-31 21:32:14,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 509}
2017-12-31 21:32:14,922 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,927 : INFO : < 200 OK [3312]
2017-12-31 21:32:14,933 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 509}
2017-12-31 21:32:14,938 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,944 : INFO : < 200 OK [3326]
2017-12-31 21:32:14,949 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 607}
2017-12-31 21:32:14,954 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,959 : INFO : < 200 OK [3317]
2017-12-31 21:32:14,964 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 607}
2017-12-31 21:32:14,969 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:14,975 : INFO : < 200 OK [3333]
2017-12-31 21:32:14,981 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 8}

2017-12-31 21:32:14,985 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:32:14,991 : INFO : < 200 OK [3323]
2017-12-31 21:32:14,996 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 8}
2017-12-31 21:32:15,000 : INFO : > POST http://localhost:7474/db/data/cypher [173]
2017-12-31 21:32:15,006 : INFO : < 200 OK [3321]
2017-12-31 21:32:15,011 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 602}
2017-12-31 21:32:15,014 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,020 : INFO : < 200 OK [3349]
2017-12-31 21:32:15,026 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 602}
2017-12-31 21:32:15,029 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,035 : INFO : < 200 OK [3365]
2017-12-31 21:32:15,040 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 608}
2017-12-31 21:32:15,044 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,049 : INFO : < 200 OK [3282]
2017-12-31 21:32:15,055 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 608}
2017-12-31 21:32:15,058 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,064 : INFO : < 200 OK [3282]
2017-12-31 21:32:15,069 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 603}
2017-12-31 21:32:15,073 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,078 : INFO : < 200 OK [3331]
2017-12-31 21:32:15,084 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 603}
2017-12-31 21:32:15,088 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,094 : INFO : < 200 OK [3331]
2017-12-31 21:32:15,100 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 603}
2017-12-31 21:32:15,104 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,109 : INFO : < 200 OK [3331]
2017-12-31 21:32:15,115 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 485}
2017-12-31 21:32:15,119 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,125 : INFO : < 200 OK [3348]
2017-12-31 21:32:15,130 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 338}
2017-12-31 21:32:15,134 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,140 : INFO : < 200 OK [3283]
2017-12-31 21:32:15,145 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 338}
2017-12-31 21:32:15,148 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,154 : INFO : < 200 OK [3282]
2017-12-31 21:32:15,159 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 338}
2017-12-31 21:32:15,163 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,169 : INFO : < 200 OK [3283]
2017-12-31 21:32:15,175 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 338}
2017-12-31 21:32:15,178 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,184 : INFO : < 200 OK [3299]
2017-12-31 21:32:15,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 121}
2017-12-31 21:32:15,193 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,200 : INFO : < 200 OK [3321]
2017-12-31 21:32:15,206 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 121}
2017-12-31 21:32:15,210 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,216 : INFO : < 200 OK [3321]
2017-12-31 21:32:15,223 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 121}
2017-12-31 21:32:15,227 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,233 : INFO : < 200 OK [3321]
2017-12-31 21:32:15,239 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 108}
2017-12-31 21:32:15,242 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,248 : INFO : < 200 OK [3319]
2017-12-31 21:32:15,254 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 108}
2017-12-31 21:32:15,257 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,263 : INFO : < 200 OK [3319]
2017-12-31 21:32:15,268 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 108}
2017-12-31 21:32:15,272 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,278 : INFO : < 200 OK [3319]
2017-12-31 21:32:15,283 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 339}
2017-12-31 21:32:15,287 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,293 : INFO : < 200 OK [3316]
2017-12-31 21:32:15,298 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 339}
2017-12-31 21:32:15,302 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,307 : INFO : < 200 OK [3315]
2017-12-31 21:32:15,313 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 339}
2017-12-31 21:32:15,316 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,329 : INFO : < 200 OK [3316]
2017-12-31 21:32:15,335 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 339}
2017-12-31 21:32:15,338 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,344 : INFO : < 200 OK [3332]
2017-12-31 21:32:15,351 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 178}
2017-12-31 21:32:15,356 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,363 : INFO : < 200 OK [3316]

2017-12-31 21:32:15,368 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 518}
2017-12-31 21:32:15,372 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,378 : INFO : < 200 OK [3321]
2017-12-31 21:32:15,384 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 340}
2017-12-31 21:32:15,387 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,393 : INFO : < 200 OK [3341]
2017-12-31 21:32:15,398 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 340}
2017-12-31 21:32:15,402 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,407 : INFO : < 200 OK [3341]
2017-12-31 21:32:15,412 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 340}
2017-12-31 21:32:15,415 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,421 : INFO : < 200 OK [3347]
2017-12-31 21:32:15,426 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 340}
2017-12-31 21:32:15,430 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,436 : INFO : < 200 OK [3344]
2017-12-31 21:32:15,446 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 528}
2017-12-31 21:32:15,450 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,455 : INFO : < 200 OK [3320]
2017-12-31 21:32:15,460 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 528}
2017-12-31 21:32:15,463 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,468 : INFO : < 200 OK [3319]
2017-12-31 21:32:15,473 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 528}
2017-12-31 21:32:15,477 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,483 : INFO : < 200 OK [3320]
2017-12-31 21:32:15,487 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 528}
2017-12-31 21:32:15,491 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,496 : INFO : < 200 OK [3319]
2017-12-31 21:32:15,503 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 125}
2017-12-31 21:32:15,506 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,512 : INFO : < 200 OK [3318]
2017-12-31 21:32:15,517 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 125}
2017-12-31 21:32:15,520 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,526 : INFO : < 200 OK [3332]
2017-12-31 21:32:15,530 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 125}
2017-12-31 21:32:15,534 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,541 : INFO : < 200 OK [3318]
2017-12-31 21:32:15,547 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 125}
2017-12-31 21:32:15,550 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,557 : INFO : < 200 OK [3332]
2017-12-31 21:32:15,561 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 125}
2017-12-31 21:32:15,565 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,571 : INFO : < 200 OK [3318]
2017-12-31 21:32:15,576 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 125}
2017-12-31 21:32:15,580 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,586 : INFO : < 200 OK [3332]
2017-12-31 21:32:15,590 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 610}
2017-12-31 21:32:15,594 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,599 : INFO : < 200 OK [3335]
2017-12-31 21:32:15,605 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 341}
2017-12-31 21:32:15,608 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,615 : INFO : < 200 OK [3309]
2017-12-31 21:32:15,620 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1235, '_0n0': 341}
2017-12-31 21:32:15,624 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,630 : INFO : < 200 OK [3309]
2017-12-31 21:32:15,637 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 341}
2017-12-31 21:32:15,640 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,645 : INFO : < 200 OK [3315]
2017-12-31 21:32:15,652 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 112}
2017-12-31 21:32:15,655 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,661 : INFO : < 200 OK [3288]
2017-12-31 21:32:15,665 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 112}
2017-12-31 21:32:15,669 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,674 : INFO : < 200 OK [3302]
2017-12-31 21:32:15,679 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 112}
2017-12-31 21:32:15,683 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,688 : INFO : < 200 OK [3288]
2017-12-31 21:32:15,693 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 112}
2017-12-31 21:32:15,697 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,703 : INFO : < 200 OK [3302]
2017-12-31 21:32:15,708 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 112}
2017-12-31 21:32:15,711 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,717 : INFO : < 200 OK [3288]
2017-12-31 21:32:15,723 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 112}

2017-12-31 21:32:15,727 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,737 : INFO : < 200 OK [3302]
2017-12-31 21:32:15,743 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 38}
2017-12-31 21:32:15,746 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:15,752 : INFO : < 200 OK [3318]
2017-12-31 21:32:15,757 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1256, '_0n0': 38}
2017-12-31 21:32:15,761 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:15,766 : INFO : < 200 OK [3318]
2017-12-31 21:32:15,774 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 531}
2017-12-31 21:32:15,777 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,782 : INFO : < 200 OK [3305]
2017-12-31 21:32:15,788 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 531}
2017-12-31 21:32:15,791 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,796 : INFO : < 200 OK [3305]
2017-12-31 21:32:15,801 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 625}
2017-12-31 21:32:15,804 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,810 : INFO : < 200 OK [3294]
2017-12-31 21:32:15,815 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 327}
2017-12-31 21:32:15,819 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,825 : INFO : < 200 OK [3350]
2017-12-31 21:32:15,830 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 327}
2017-12-31 21:32:15,835 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,840 : INFO : < 200 OK [3353]
2017-12-31 21:32:15,845 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1236, '_0n0': 25}
2017-12-31 21:32:15,848 : INFO : > POST http://localhost:7474/db/data/cypher [174]
2017-12-31 21:32:15,854 : INFO : < 200 OK [3296]
2017-12-31 21:32:15,859 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 328}
2017-12-31 21:32:15,862 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,867 : INFO : < 200 OK [3291]
2017-12-31 21:32:15,873 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 328}
2017-12-31 21:32:15,876 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,882 : INFO : < 200 OK [3294]
2017-12-31 21:32:15,887 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 328}
2017-12-31 21:32:15,890 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,896 : INFO : < 200 OK [3291]
2017-12-31 21:32:15,901 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 328}
2017-12-31 21:32:15,905 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,911 : INFO : < 200 OK [3294]
2017-12-31 21:32:15,916 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 328}
2017-12-31 21:32:15,920 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,926 : INFO : < 200 OK [3291]
2017-12-31 21:32:15,931 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 328}
2017-12-31 21:32:15,934 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,940 : INFO : < 200 OK [3294]
2017-12-31 21:32:15,945 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 199}
2017-12-31 21:32:15,949 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,954 : INFO : < 200 OK [3293]
2017-12-31 21:32:15,960 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 611}
2017-12-31 21:32:15,963 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,969 : INFO : < 200 OK [3305]
2017-12-31 21:32:15,975 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 611}
2017-12-31 21:32:15,979 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,985 : INFO : < 200 OK [3306]
2017-12-31 21:32:15,990 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 611}
2017-12-31 21:32:15,994 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:15,999 : INFO : < 200 OK [3312]
2017-12-31 21:32:16,005 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 611}
2017-12-31 21:32:16,009 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,014 : INFO : < 200 OK [3309]
2017-12-31 21:32:16,020 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 611}
2017-12-31 21:32:16,023 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,029 : INFO : < 200 OK [3305]
2017-12-31 21:32:16,034 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 611}
2017-12-31 21:32:16,038 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,044 : INFO : < 200 OK [3306]
2017-12-31 21:32:16,049 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 611}
2017-12-31 21:32:16,053 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,060 : INFO : < 200 OK [3312]
2017-12-31 21:32:16,066 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 611}
2017-12-31 21:32:16,070 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,076 : INFO : < 200 OK [3309]
2017-12-31 21:32:16,079 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 611}
2017-12-31 21:32:16,082 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,087 : INFO : < 200 OK [3305]

2017-12-31 21:32:16,092 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 611}
2017-12-31 21:32:16,095 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,101 : INFO : < 200 OK [3306]
2017-12-31 21:32:16,105 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1251, '_0n0': 611}
2017-12-31 21:32:16,108 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,113 : INFO : < 200 OK [3312]
2017-12-31 21:32:16,117 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 611}
2017-12-31 21:32:16,120 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,126 : INFO : < 200 OK [3309]
2017-12-31 21:32:16,131 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 343}
2017-12-31 21:32:16,134 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,139 : INFO : < 200 OK [3309]
2017-12-31 21:32:16,146 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 626}
2017-12-31 21:32:16,149 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,154 : INFO : < 200 OK [3305]
2017-12-31 21:32:16,161 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1260, '_0n0': 345}
2017-12-31 21:32:16,165 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,170 : INFO : < 200 OK [3294]
2017-12-31 21:32:16,175 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 627}
2017-12-31 21:32:16,177 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,182 : INFO : < 200 OK [3311]
2017-12-31 21:32:16,189 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 243}
2017-12-31 21:32:16,192 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,197 : INFO : < 200 OK [3296]
2017-12-31 21:32:16,202 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 243}
2017-12-31 21:32:16,205 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,210 : INFO : < 200 OK [3299]
2017-12-31 21:32:16,214 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 243}
2017-12-31 21:32:16,217 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,222 : INFO : < 200 OK [3296]
2017-12-31 21:32:16,227 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 243}
2017-12-31 21:32:16,229 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,235 : INFO : < 200 OK [3300]
2017-12-31 21:32:16,240 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1249, '_0n0': 243}
2017-12-31 21:32:16,243 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,248 : INFO : < 200 OK [3296]
2017-12-31 21:32:16,253 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 243}
2017-12-31 21:32:16,256 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,261 : INFO : < 200 OK [3299]
2017-12-31 21:32:16,265 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 243}
2017-12-31 21:32:16,269 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,274 : INFO : < 200 OK [3296]
2017-12-31 21:32:16,278 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 243}
2017-12-31 21:32:16,282 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,287 : INFO : < 200 OK [3300]
2017-12-31 21:32:16,292 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 614}
2017-12-31 21:32:16,296 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,302 : INFO : < 200 OK [3295]
2017-12-31 21:32:16,306 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 540}
2017-12-31 21:32:16,309 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,315 : INFO : < 200 OK [3302]
2017-12-31 21:32:16,319 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 540}
2017-12-31 21:32:16,323 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,328 : INFO : < 200 OK [3301]
2017-12-31 21:32:16,332 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 540}
2017-12-31 21:32:16,336 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,341 : INFO : < 200 OK [3302]
2017-12-31 21:32:16,345 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 540}
2017-12-31 21:32:16,348 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,354 : INFO : < 200 OK [3302]
2017-12-31 21:32:16,359 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 540}
2017-12-31 21:32:16,362 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,368 : INFO : < 200 OK [3301]
2017-12-31 21:32:16,373 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 540}
2017-12-31 21:32:16,377 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,383 : INFO : < 200 OK [3302]
2017-12-31 21:32:16,388 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 540}
2017-12-31 21:32:16,391 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,397 : INFO : < 200 OK [3302]
2017-12-31 21:32:16,403 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 540}
2017-12-31 21:32:16,407 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,413 : INFO : < 200 OK [3301]
2017-12-31 21:32:16,420 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 540}

2017-12-31 21:32:16,424 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,430 : INFO : < 200 OK [3302]
2017-12-31 21:32:16,435 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1234, '_0n0': 540}
2017-12-31 21:32:16,439 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,445 : INFO : < 200 OK [3302]
2017-12-31 21:32:16,450 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1238, '_0n0': 540}
2017-12-31 21:32:16,454 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,459 : INFO : < 200 OK [3301]
2017-12-31 21:32:16,464 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1254, '_0n0': 540}
2017-12-31 21:32:16,468 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,474 : INFO : < 200 OK [3302]
2017-12-31 21:32:16,482 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 244}
2017-12-31 21:32:16,487 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,493 : INFO : < 200 OK [3317]
2017-12-31 21:32:16,498 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1237, '_0n0': 244}
2017-12-31 21:32:16,501 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,507 : INFO : < 200 OK [3317]
2017-12-31 21:32:16,514 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1259, '_0n0': 354}
2017-12-31 21:32:16,516 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,522 : INFO : < 200 OK [3281]
2017-12-31 21:32:16,531 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 355}
2017-12-31 21:32:16,534 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,540 : INFO : < 200 OK [3299]
2017-12-31 21:32:16,544 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 355}
2017-12-31 21:32:16,548 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,553 : INFO : < 200 OK [3302]
2017-12-31 21:32:16,557 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 355}
2017-12-31 21:32:16,560 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,564 : INFO : < 200 OK [3299]
2017-12-31 21:32:16,569 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 355}
2017-12-31 21:32:16,572 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,578 : INFO : < 200 OK [3302]
2017-12-31 21:32:16,583 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 355}
2017-12-31 21:32:16,587 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,592 : INFO : < 200 OK [3299]
2017-12-31 21:32:16,597 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1255, '_0n0': 355}
2017-12-31 21:32:16,601 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,606 : INFO : < 200 OK [3302]
2017-12-31 21:32:16,613 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 619}
2017-12-31 21:32:16,617 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,623 : INFO : < 200 OK [3334]
2017-12-31 21:32:16,628 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 619}
2017-12-31 21:32:16,632 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,637 : INFO : < 200 OK [3334]
2017-12-31 21:32:16,642 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 619}
2017-12-31 21:32:16,645 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,650 : INFO : < 200 OK [3334]
2017-12-31 21:32:16,656 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1250, '_0n0': 619}
2017-12-31 21:32:16,659 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,665 : INFO : < 200 OK [3334]
2017-12-31 21:32:16,673 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 572}
2017-12-31 21:32:16,676 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,682 : INFO : < 200 OK [3330]
2017-12-31 21:32:16,687 : INFO : execute 'MATCH (_0n0) WHERE id(_0n0)={_0n0}\nMATCH (_0n1) WHERE id(_0n1)={_0n1}\n\nCREATE (_0n0)-[_0r0:use]->(_0n1)\nRETURN _0n0,_0n1,_0r0' {'_0n1': 1252, '_0n0': 572}
2017-12-31 21:32:16,690 : INFO : > POST http://localhost:7474/db/data/cypher [175]
2017-12-31 21:32:16,695 : INFO : < 200 OK [3330]

In [53]:
from vis import draw

options = {"Teacher": "name", 'Institue': 'name'}
draw(graph,"match p= (n:Course{name:'Usable Security'})-[]-() return p", options)

ImportError: No module named 'vis'

In [ ]:
title_relation_df.head()

In [ ]:
from sklearn.cluster import KMeans
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import Normalizer

svd = TruncatedSVD(100)
normalizer = Normalizer(copy=False)
lsa = make_pipeline(svd, normalizer)
X = lsa.fit_transform(document_matrix)
inertia_list = []  
for i in range(2,15):
    kmeans = KMeans(n_clusters=i).fit(X)
    inertia_list.append(kmeans.inertia_)

import matplotlib.pyplot as plt
plt.plot(range(2,15), inertia_list, linestyle='-', marker='o')
plt.show()

In [ ]:
![image.png](attachment:image.png)

In [ ]:
#IsDuplicated = data_to_mysql.duplicated()

In [ ]:
# duplicate_course=0
# for i in range(len(data_to_mysql)):
#     if IsDuplicated[i] == True:
#         duplicate_course=duplicate_course+1
#         #print(i)
# print(duplicate_course)

In [ ]:
#data = data_to_mysql.drop_duplicates()

In [ ]:
#data_to_mysql.head()

### --------------------------------------------------------------------------------

In [ ]:
### Testing

In [ ]:
# v=[]
# for n in range(len(all_data)):
#     for j in range(len(all_data[n]['week_data'])):     
#         v.append(list((all_data[n]['week_data'][j]).values())[0])
#         #a.append(pd.Series(v).str.cat(sep=''))

In [ ]:
# v= pd.Series(v).str.cat(sep='')